### ISSUE TITLE
Support scripts that can be LTR and RTL

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1000]
Like Old Italic.  For these, we shouldn't enforce a native direction.

**Comment by behdad** [comment]
Ebrahim, want to work on this?

**Comment by behdad** [comment]
@marekjez86 can you follow up with Monotype to get a test font please? Thanks.

**Comment by marekjez86** [comment]
The attached sample font has added mirror-imaged glyphs only for A & B (u+10300, u+10301), as well as substitution code to use the reflected glyphs when the “rtlm” feature is triggered. Please use it for testing (again only u+10300 and u+10301).

[NotoSansOldItalic-20180423.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/1940199/NotoSansOldItalic-20180423.ttf.zip)

**Comment by ebraminio** [comment]
> Ebrahim, want to work on this?

Busy with other things but looking carefully to get more context.

**Comment by ebraminio** [comment]
Okay Behdad what should happen here? Defining a new value for `hb_direction_t`, like HB_DIRECTION_NEUTRAL, then returning that from hb_script_get_horizontal_direction for that scripts, then? :)

**Comment by behdad** [comment]
> Okay Behdad what should happen here? Defining a new value for hb_direction_t, like HB_DIRECTION_NEUTRAL, then returning that from hb_script_get_horizontal_direction for that scripts, then? :)

Nope. HB_DIRECTION_NONE is enough.
