### ISSUE TITLE
hb-{view,shape} should support reading font file from stdin

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1001]
It should both support, `hb-{shape,view} {/dev/stdin,-} <font.ttf` and `cat font.ttf | hb-{shape,view} {/dev/stdin,-}`. More nice if it uses `hb_blob_create_from_file` underneath. It should be tested on both Linux and macOS (their implementation differs), and even better, Windows also (\r thing). AIX doesn't have `/dev/stdin` (not the most used platform, but well) so we should have some workaround for that in mind also (specially not redirecting `-` to `/dev/stdin`)

**Comment by behdad** [comment]
Something really weird is happening right now.
