### ISSUE TITLE
hb_ensure_native_direction can change the meaning of the text

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#1006]
Bidi-reversing Devanagari, or any script that uses a virama, or emoji, can change the text, even for a reader who knows to read in the opposite direction.
```console
$ hb-shape --direction ltr --ned --no-clusters --no-positions -u 0937,0940,0915,094d NotoSansDevanagari-Regular.ttf
[ssadeva|iivowelsigndeva|kadeva|viramadeva]
$ hb-shape --direction rtl --ned --no-clusters --no-positions -u 0937,0940,0915,094d NotoSansDevanagari-Regular.ttf
[kassadeva|iivowelsigndeva]
$ hb-shape --direction rtl --ned --no-clusters --no-positions -u 1F1EA,1F1F8 TwemojiMozilla.ttf 
[u1f1f8_1f1ea]
$ hb-shape --direction ltr --ned --no-clusters --no-positions -u 1F1EA,1F1F8 TwemojiMozilla.ttf
[u1f1ea_1f1f8]
```

Ideally, ⟨षीक्⟩ would be split into ⟨षी⟩ and ⟨क्⟩, which be reversed and recomposed with a ZWNJ into ⟨क्‌षी⟩, and ⟨🇪🇸⟩ would be considered a single cluster, so it would not be split. I’ve come up with a rough draft of an algorithm to visually bidi-reverse strings, a more general version of the fix for #169 and of whatever is planned for #1000. Would this be of interest?

**Comment by behdad** [comment]
For emoji, we are going to implement `xpicto-sequence` in https://github.com/harfbuzz/harfbuzz/issues/1159

Do share your algorithm if you have it written down already.  Thanks.
