### ISSUE TITLE
[Question] Myanmar: purpose of `CS` in syllable-identification regexp?

### ISSUE THREAD

**Issue by n8willis** [harfbuzz/harfbuzz#1007]
Trying to understand the Myanmar syllable-id Ragel machine. The consonant-syllable expression starts with (k|CS)? ... and the `CS` category AFAICT is "Consonant_Subjoined", which isn't used in Myanmar. Is that right? 

If so, how does CS factor into Myanmar text runs? It's not discussed in the Unicode chapter, as far as I can see.

**Comment by behdad** [comment]
git blame points to: https://github.com/harfbuzz/harfbuzz/commit/f559c633073f63b9d87cb2440048b4413cfa1c05

**Comment by n8willis** [comment]
Well, I kind of have the same question about Consonant_with_Stacker, though. That exists in Brahmi and som other scripts, but not in Myanmar. 

I do see, in the MS Typography docs, a reference to "zero or more stacked consonants or full vowel forms" following a kinzi. But it seems like that's a reference to subjoined "halant,C" consonants after the base (using different terminology than MS usually does). 

And their regexps don't seem to employ _CS_: they're [K] <C | IV | D | GB>[VS] (H <C | IV> [VS])

**Comment by behdad** [comment]
The bug and commit suggest that this is something not anticipated by the spec.
