### ISSUE TITLE
Lao: Difference in Word and HB

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1008]
Text: ຖີູ ຖູີ ຍູ
[saysettha_ot.zip](https://github.com/harfbuzz/harfbuzz/files/1954890/saysettha_ot.zip)
The first two ligatures have a different position of the same Unicode but still, Harfbuzz shapes them the same. Is it because Harfbuzz doesn't show standalone diacritic in this scenario or it is a shaping issue.

If HB is not showing standalone matra then it is Harfbuzz inconsistency in different locales.

**Comment by ohbendy** [comment]
The Saysettha font attached doesn't contain ligatures, but what I think you're illustrating is that the two vowel marks could be typed in either order, as -ii + -uu or as -uu + -ii. There's nothing in the OT spec for Lao to suggest either combination is invalid, but I don't think Lao language permits the combination -ii with -uu. Where did these test sequences come from?

I've checked several other Lao fonts and it and the dotted circles are not appearing. This makes me think it could be a font-level setting, for example that there's no languagesystem declaration or script tags present in Saysettha.

**Comment by behdad** [comment]
Currently our Thai and Lao shapers do NOT have a grammar so this is expected currently.  We probably should fix it at some point, but I don't consider this a bug since it's only relevant to wrongly-encoded sequences.

**Comment by behdad** [comment]
It looks like OT spec doesn't enforce an order for Thai/Lao marks.  It just says only one vowel of each category is allowed.  We currently don't enforce those kinds of rules in any shaper.  As such, nothing to be done here.
