### ISSUE TITLE
Lao: Difference in Word and Harfbuzz

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1009]
Text1: ◌ະິຶຸເ-ະແ-ະ
Text2:ໂ-ະເ-າະເິເັຍເຶອົວະ
Text3:-າີືູເ-ແ-
Text4: ໂ-ໍເີເ-ຍເືອົວ
Text5:(ເຄື່ອງຫມາຍກາລັນ)
Text6: ະເຈົ້າສົນໄຊຮັບສັ່ງຂະບວນໃຫ້ໄປຮັບເອົາພະເວດສັນດອນແລະນາງມັດທີຢູ່ເຂົາວົງກົດຂະນະນັ້ນພະເຈົ້າກະລິງຄະຣັດກໍໃຫ້ພາມນຳຊ້າງປັດໃຈນາຄມາຄືນພະເຈົ້າສົນໄຊຈິ່ງນຳຂະບວນດ້ວຍຊ້າງປັດໃຈນາຄ.ເມື່ອກະສັດທັງ6ພະອົງໄດ້ແກ້ພະເຈົ້າສົນໄຊພະນາງບຸດສະດີ
[dokchamp.zip](https://github.com/harfbuzz/harfbuzz/files/1954916/dokchamp.zip)

**Comment by behdad** [comment]
Same comment as https://github.com/harfbuzz/harfbuzz/issues/1008

**Comment by behdad** [comment]
Closing in preference for https://github.com/harfbuzz/harfbuzz/issues/1008
