### ISSUE TITLE
USE data overrides

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1012]
From an opentype-layout thread, from Andrew Glass:
```
Here is the override:

  # ================================================
  # Indic_Matra_Category=Bottom
  0F72        ; Bottom # Mn      TIBETAN VOWEL SIGN I
  0F7A..0F7D  ; Bottom # Mn  [4] TIBETAN VOWEL SIGN E..TIBETAN VOWEL SIGN OO
  0F80        ; Bottom # Mn      TIBETAN VOWEL SIGN REVERSED I
  11127..11129; Bottom # Mn  [3] CHAKMA VOWEL SIGN A..CHAKMA VOWEL SIGN II
  1112D       ; Bottom # Mn      CHAKMA VOWEL SIGN AI
  11130       ; Bottom # Mn      CHAKMA VOWEL SIGN OI
```

**Comment by behdad** [comment]
From another email from Andrew Glass, also:
```
  # Indic_Syllabic_Category=Gemination_Mark
  11134      ; Gemination_Mark # Mc      CHAKMA MAAYYAA
```

**Comment by behdad** [comment]
Actually, those are now listed in USE spec itself:
https://docs.microsoft.com/en-gb/typography/script-development/use#overrides

```
Overrides to Indic_Syllabic_Category

  # Indic_Syllabic_Category=Bindu
  AA29       ; Bindu          # Mn       CHAM VOWEL SIGN AA
  # ================================================
  # Indic_Syllabic_Category=Nukta
  0F71       ; Nukta          # Mn       TIBETAN VOWEL SIGN AA
  # ================================================
  # Indic_Syllabic_Category=Tone_Mark
  A982       ; Tone_Mark      # Mn       JAVANESE SIGN LAYAR
  # ================================================
  # Indic_Syllabic_Category=Consonant_Dead
  0F7F       ; Consonant_Dead # Mc       TIBETAN SIGN RNAM BCAD
  # ================================================
  # Indic_Syllabic_Category=Gemination_Mark 
  11134      ; Gemination_Mark # Mc      CHAKMA MAAYYAA

Overrides to Indic_Positional_Category

  # Indic_Matra_Category=Top
  0F74        ; Top     # Mn      TIBETAN VOWEL SIGN U
  AA35        ; Top     # Mn      CHAM CONSONANT SIGN
  1A18        ; Top     # Mn      BUGINESE VOWEL SIGN U

  # ================================================
  # Indic_Matra_Category=Bottom
  0F72        ; Bottom  # Mn      TIBETAN VOWEL SIGN I
  0F7A..0F7D  ; Bottom  # Mn  [4] TIBETAN VOWEL SIGN E..TIBETAN VOWEL SIGN OO
  0F80        ; Bottom  # Mn      TIBETAN VOWEL SIGN REVERSED I
  11127..11129; Bottom  # Mn  [3] CHAKMA VOWEL SIGN A..CHAKMA VOWEL SIGN II
  1112D       ; Bottom  # Mn      CHAKMA VOWEL SIGN AI
  11130       ; Bottom  # Mn      CHAKMA VOWEL SIGN OI
```

**Comment by behdad** [comment]
@jfkthame Any comments here?  For Tibetan we decided to apply the override based on category (all top matras) instead of hardcoding.  Maybe I should just implement override files and ship these verbatim?

**Comment by behdad** [comment]
From Ned email from Jan 3, 2018:
```
# Indic_Syllabic_Category=Bindu
AA29       ; Bindu          # Mn       CHAM VOWEL SIGN AA
# ================================================
# Indic_Syllabic_Category=Nukta
0F71       ; Nukta          # Mn       TIBETAN VOWEL SIGN AA
1BF2..1BF3 ; Nukta          # Mc [2]   BATAK PANGOLAT..BATAK PANONGONAN
# ================================================
# Indic_Syllabic_Category=Tone_Mark
1CED       ; Tone_Mark      # Mn       VEDIC SIGN TIRYAK
A982       ; Tone_Mark      # Mn       JAVANESE SIGN LAYAR
# ================================================
# Indic_Syllabic_Category=Consonant_Dead
002D       ; Consonant_Dead # Pd       HYPHEN MINUS
0F7F       ; Consonant_Dead # Mc       TIBETAN SIGN RNAM BCAD
# ================================================
# Indic_Syllabic_Category=Gemination_Mark
11134      ; Gemination_Mark # Mc      CHAKMA MAAYYAA
# ================================================
# Indic_Syllabic_Category=Symbol_Combining
1B6B..1B73 ; Symbol_Combining # Mn [9] BALINESE MUSICAL SYMBOL COMBINING TEGEH..BALINESE MUSICAL SYMBOL COMBINING GONG
# ================================================
# Indic_Syllabic_Category=Cantillation_Mark
1CE2..1CE8 ; Cantillation_Mark # Mn [7] VEDIC SIGN VISARGA SVARITA..VEDIC SIGN VISARGA ANUDATTA WITH TAIL
# ================================================
# Indic_Syllabic_Category=Consonant
A8F2..A8F7 ; Consonant      # Lo [6]   DEVANAGARI SIGN SPACING CANDRABINDU..DEVANAGARI SIGN CANDRABINDU AVAGRAHA
A8FB       ; Consonant      # Lo       DEVANAGARI HEADSTROKE
A8FD       ; Consonant      # Lo       DEVANAGARI JAIN OM
# ================================================
# Indic_Syllabic_Category=Consonant_Medial
0A51       ; Consonant_Medial # Mn     GURMUKHI SIGN UDAAT
A8B4       ; Consonant_Medial # Mc     SAURASHTRA CONSONANT SIGN HAARU
# ================================================
# Indic_Syllabic_Category=Consonant_Placeholder
0C80       ; Consonant_Placeholder # Lo     KANNADA SIGN SPACING CANDRABINDU
2015       ; Consonant_Placeholder # Pd     HORIZONTAL BAR
2022       ; Consonant_Placeholder # Po     BULLET
25FB..25FE ; Consonant_Placeholder # Sm [4] WHITE MEDIUM SQUARE..BLACK MEDIUM SMALL SQUARE
```
# Indic_Positional_Category=Left
1C29          ; Left # Mc       LEPCHA VOWEL SIGN OO
# ================================================
# Indic_Positional_Category=Top
0F74       ; Top     # Mn      TIBETAN VOWEL SIGN U
1A18       ; Top     # Mn      BUGINESE VOWEL SIGN U
1B6B       ; Top     # Mn      BALINESE MUSICAL SYMBOL COMBINING TEGEH
1B6D..1B73 ; Top     # Mn  [7] BALINESE MUSICAL SYMBOL COMBINING KEMPUL..BALINESE MUSICAL SYMBOL COMBINING GONG
AA35        ; Top     # Mn      CHAM CONSONANT SIGN
# ================================================
# Indic_Positional_Category=Bottom
0A51       ; Bottom  # Mn      GURMUKHI SIGN UDAAT
0F72       ; Bottom  # Mn      TIBETAN VOWEL SIGN I
0F7A..0F7D ; Bottom  # Mn  [4] TIBETAN VOWEL SIGN E..TIBETAN VOWEL SIGN OO
0F80       ; Bottom  # Mn      TIBETAN VOWEL SIGN REVERSED I
1B6C       ; Bottom  # Mn      BALINESE MUSICAL SYMBOL COMBINING ENDEP
1BF2..1BF3 ; Bottom  # Mc  [2] BATAK PANGOLAT..BATAK PANONGONAN
11127..11129; Bottom # Mn  [3] CHAKMA VOWEL SIGN A..CHAKMA VOWEL SIGN II
1112D       ; Bottom # Mn      CHAKMA VOWEL SIGN AI
11130       ; Bottom # Mn      CHAKMA VOWEL SIGN OI
```

**Comment by brawer** [comment]
Is there somewhere a complete list of overrides? (For getting the data fixed upstream, at Unicode).

**Comment by behdad** [comment]
I've been maintaining what I've received from other implementations here, to be cross-checked with what we do in HarfBuzz at some point.

**Comment by KrasnayaPloshchad** [comment]
CC @domschl

**Comment by KrasnayaPloshchad** [comment]
CC @eroux

**Comment by Richard57** [comment]
> Is there somewhere a complete list of overrides? (For getting the data fixed upstream, at Unicode).

Last UTC meeting I was at (by phone) that discussed the issue declared that the needs of the USE did not determine the Unicode categories.  For example, one couldn't change Tai Tham Consonant_Medial to Consonant_Subjoined just because that gave better results from the USE.

**Comment by behdad** [comment]
MS finally released those (silently!):

https://github.com/microsoft/font-tools/tree/master/USE

Let's change our processors to read that, and we can move our own exceptions on top of that.

**Comment by dscorbett** [comment]
I’d already started working on this, but I had to stop because the data files contain new property values not mentioned in the USE spec. In particular, there are new values for Egyptian quadrats. I therefore plan to wait for the spec to be updated. Alternatively, I could skip the new properties for now and push what I have.

**Comment by behdad** [comment]
Please open an issue with MS on their repo so we get Andrew's feedback on when to expect spec changes.

**Comment by dscorbett** [comment]
I opened MicrosoftDocs/typography-issues#315. I get the feeling we’re not supposed to have noticed these files yet.

**Comment by dscorbett** [comment]
The USE spec refers to those external override files now, and HarfBuzz consumes them.
