### ISSUE TITLE
GSUB/GPOS subsetting

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1017]
- [x] Clean up `UnsizedArray` type and use it everywhere.
- [x] Implement population caching in `hb_set_t`.
- [x] Implement `hb_auto_t<>` that calls init/fini on the object inside, for auto lifecycle management.
- [ ] Write down Supplier protocol. A Supplier will have `iter_forward()` and `iter_backward()`. Check for C++ idioms.
- [x] Write `sized_array_t<>` that takes unsized array-like object and a len and enforces bound checking.
- [ ] Write `SubsetView<>` that takes a set and an array-like object (ensure it has .len) and provides iterators for a subsetted view of the array.
- [x] Change/implement `serialize()` methods that take a `typename Supplier` and work with it.
- [ ] Implement `subset()` methods that build `SubsetView<>`s and calls `serialize()`.

**Comment by behdad** [comment]
This is done now. We have a lot of refactoring / cleanup to do. But that's separate.

**Comment by behdad** [comment]
Waiting for @garretrieger to enable layout subsetting by default.

**Comment by yisibl** [comment]
Apart from COLRv1, which is still working, are there any other tables that cannot be subsetted?

**Comment by behdad** [comment]
> Apart from COLRv1, which is still working, are there any other tables that cannot be subsetted?

All the relevant tables in OpenType are there:
https://github.com/harfbuzz/harfbuzz/blob/4cc4cd3b24ded40cfff651ebf63d20d19253c505/src/hb-subset.cc#L243

**Comment by yisibl** [comment]
> Subsetter now fully supports GSUB/GPOS/GDEF tables (including variations); as such, layout tables are retained by subsetter by default.

https://github.com/harfbuzz/harfbuzz/pull/2958#issuecomment-831396202
