### ISSUE TITLE
Khmer shaping issue

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1026]
[khmer-bokor.zip](https://github.com/harfbuzz/harfbuzz/files/1991456/khmer-bokor.zip)

Text: 

ស្រ្តា ស្រ្តិ ស្រ្តី ស្រ្តឹ ស្រ្តឺ ស្រ្តុ ស្រ្តូ ស្រ្តួ ស្រ្តើ ស្រ្តឿ ត្រ្សៀ
ត្រ្សេ ត្រ្សែ ត្រ្សៃ ត្រ្សោ ត្រ្សៅ ឃ្ល្សុំ ឃ្ល្សំ ឃ្ល្សាំ ឃ្ល្សះ ឃ្ល្សិះ
ឃ្ល្សុះ ឃ្ល្សេះ ឃ្ល្សោះ ស្រ្ត៊ឿ ស្រ្ត៊ៀ ស្រ្ត៊េ ស្រ្ត៊ែ ស្រ្ត៊ៃ ស្រ្ត៊ំ ម្ត្ល៉ា
ម្ត្ល៉ុ ម្ត្ល៉ឿ ម្ត្ល៉ៀ ហ្គ្ស៊ើ ហ្គ្ស៊ឿ ហ្គ្ស៊ៀ ក្សាន្ត ក្សិន្ត ក្សីន្ត ក្សឹន្ត
ក្សឺន្ត ក្សុន្ត ក្សូន្ត ក្សួន្ត ក្សឿន្ត ធ្លោក់ ធ្លៅក់ ធ្លុំក់
ធ្លំក់ កន្ត្រាក់ កន្រ្សិក់ កន្រ្សីក់ សាស្ត្រឃ្ឈងា សាស្ត្រឃ្ឈងិ
សាស្ត្រឃ្ឈងី ស្ត្រីវ័ខ្ញ្សា យ្យើហ្វ្លៃ

**Comment by Amritasingh0512** [comment]
![output_hb](https://user-images.githubusercontent.com/38288804/39869169-2d6e07c2-547a-11e8-9cf5-b3f59bc32a7a.png)
![output_uniscribe](https://user-images.githubusercontent.com/38288804/39869170-2d9d1fe4-547a-11e8-80ba-9b4c7045e1ad.png)

**Comment by Richard57** [comment]
What is the problem?  I see strings such as ស្រ្តី <U+179F SA,  U+17D2 COENG, U+179A RO, U+17D2, U+178F TA, U+17B8 SIGN II>.  The rendering sensibly distinguishes this word (whose encoding looks like gibberish) from something like Sanskrit ស្ត្រី <U+179F SA,  U+17D2 COENG, U+178F TA, U+17D2, U+179A RO, U+17B8 SIGN II>; I would expect it to look like the archaic spelling ស្រី្ត <U+179F SA,  U+17D2 COENG, U+179A RO, U+17B8 SIGN II, U+17D2, U+178F TA>.

It is to the good if it can distinguish a Sanskrit cluster grv- គ្រ្វ <U+1782  KO, U+17D2, U+179A, U+17D2, U+179C  VO> from gvr- គ្វ្រ <1782, 17D2, 179C, 17D2, 179A>.

**Comment by olivierberten** [comment]
The sting displayed here is ស្រ្តើ <U+179F,U+17D2,U+179A,U+17D2,U+178F,U+17BE>, first line is harfbuzz while second line is uniscribe. You can see harfbuzz doesn't prepend the first part of vowel OE.
If you give the normalized orthography ស្ត្រើ <U+179F,U+17D2,U+178F,U+17D2,U+179A,U+17BE> (switching COENG RO and COENG TA), it gives the expected result.

As you can test at: https://fonts.google.com/?subset=khmer it is the case for most fonts there.

**Comment by Richard57** [comment]
It was well hidden from me, as the font Firefox 60.0.1 uses doesn't suffer the problem on Firefox.
