### ISSUE TITLE
hb-buffer-deserialize-text.hh] Error 1

### ISSUE THREAD

**Issue by tlgbjk** [harfbuzz/harfbuzz#1030]
tmp/harfbuzz-build-arm1176/harfbuzz-1.7.6/missing: line 81: ragel: command not found
WARNING: 'ragel' is missing on your system.
         You might have modified some files without having the proper
         tools for further handling them.  Check the 'README' file, it
         often tells you about the needed prerequisites for installing
         this package.  You may also peek at any GNU archive site, in
         case some other package contains this missing 'ragel' program.
make[3]: *** [hb-buffer-deserialize-text.hh] Error 1
make[3]: Leaving directory `/tmp/harfbuzz-build-arm1176/harfbuzz-1.7.6/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/harfbuzz-build-arm1176/harfbuzz-1.7.6'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/harfbuzz-build-arm1176/harfbuzz-1.7.6'
make: *** [build] Error 2

I am getting  this error How can i ignore regal process during build time? do we really need ragel

**Comment by ebraminio** [comment]
Make checks timestamps to see if a file needs to be updated or not. There is a maintainer mode on automake that disabling it is supposed to stop things like that but I personally couldn't use it. Please let us know if you had any success on them.

**Comment by behdad** [comment]
Yeah this shouldn't happen unless you somehow messed up file timestamps.  Try a 'touch src/*.hh' see if that helps.

**Comment by behdad** [comment]
Anyway, not really our issue.
