### ISSUE TITLE
armcc: warning:  #1293-D: assignment in condition

### ISSUE THREAD

**Issue by imgtec** [harfbuzz/harfbuzz#1031]
Hi there.
This warning is reported 11 times by armcc.
it is refer to some code like
```
src\hb-buffer.cc(723): warning:  #1293-D: assignment in condition
```
```
  if (!(buffer = hb_object_create<hb_buffer_t> ()))
```
I change it to, the warning gone.
```
  if ((buffer = hb_object_create<hb_buffer_t> ()) == 0)
```
I seems the coding style cause the warning.

which one is better? should I change it?

**Comment by imgtec** [comment]
all warnings are here:

https://paste.ubuntu.com/p/qRNrZfmXT7/

**Comment by behdad** [comment]
Not a huge fan of changing this.

**Comment by ebraminio** [comment]
What confuse me is this vector_size error https://paste.ubuntu.com/p/5GpF3wfGmN/ Does armcc, like clang, define `__GNUC__` or we have some error?

**Comment by behdad** [comment]
Yeah looks like bad impersonation.

**Comment by behdad** [comment]
We can add some if()'s based on sizeof(vector type).

**Comment by ebraminio** [comment]
So apparently you've defined it already? What happens if you don't? (Still not related to the main topic of this issue)

**Comment by behdad** [comment]
Leaning on closing this.

**Comment by ebraminio** [comment]
Ok. We will sort it with @imgtec if needed :)
