### ISSUE TITLE
Khmer: below base mark misplacement

### ISSUE THREAD

**Issue by ChetanPawar93** [harfbuzz/harfbuzz#1032]
Font: Khmer UI
Text: ញូ ដូ ឋូ ឌូ ឍូ ណូ
![image](https://user-images.githubusercontent.com/11992107/40221149-341fe5ac-5a99-11e8-8751-41f529c17814.png)

**Comment by olivierberten** [comment]
This must be a bug in hb-view because hb-shape gets it right...

**Comment by behdad** [comment]
Which syllable is the one showed in the image?

**Comment by olivierberten** [comment]
ឋូ
The other 4 are fine
(and it's the same with Leelawadee UI)

**Comment by behdad** [comment]
Uniscribe (Windows 7 at least) renders the same.  Not our bug.
