### ISSUE TITLE
Burmese: Medial WA+ Vowel UI overlap 

### ISSUE THREAD

**Issue by ChetanPawar93** [harfbuzz/harfbuzz#1033]
Font: Padauk
[Padauk.zip](https://github.com/harfbuzz/harfbuzz/files/2015904/Padauk.zip)
Text: ခုႏွစ္၊ 

![burmese_wa vowel ui](https://user-images.githubusercontent.com/11992107/40222028-caeee5bc-5a9b-11e8-9724-c401498d543e.png)

**Comment by behdad** [comment]
Padauk shaping depends on whether Graphite is enabled or not.  Not sure we care about its OpenType performance.

**Comment by ohbendy** [comment]
The correct sequence has dotted circles? That normally implies an invalid sequence?

**Comment by mhosken** [comment]
If erroneous sequences are handled prettily that is a bonus, but there are so many cases that it's hard to test for them all. In this particular situation, when I enter the text into libreoffice against Padauk, everything renders just as the submitter requests. Sorry, can't reproduce at least on the Graphite side.

**Comment by behdad** [comment]
Yeah not sure there's anything to be done here.
