### ISSUE TITLE
Move Sinhala to USE

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1044]
See https://github.com/harfbuzz/harfbuzz/issues/967 for some context.  Sinhala shaping apparently changed between Win7 and Win10. We used to match Win7 behavior. Then hacked our shaper to be closer to Win10. Moving to USE should be a better long-term fix.

**Comment by behdad** [comment]
Jonathan and I looked into this.  Pushed a few commits into branch, but hit a wall.  Reported to Andrew Glass:

Sinhala uses explicit reph formation.  Ie, Ra,H,ZWJ forms a reordering reph form.  However, MS iskpota fonts seem to ligate both Ra,H and Ra,H,ZWJ in the rphf feature, only one of which should be reordered.  Detecting this basically would introduce a special-casing hack in the USE, which is not documented in the spec.

Stalled for now.

**Comment by behdad** [comment]
https://github.com/harfbuzz/harfbuzz/commits/use-sinhala

**Comment by Richard57** [comment]
I believe U+0DCA SINHALA SIGN AL-LAKUNA needs to be added to the same new USE category as U+11046 BRAHMI VIRAMA, for it is the final component of U+0DDA SINHALA VOWEL SIGN DIGA KOMBUVA and U+0DDD SINHALA VOWEL SIGN KOMBUVA HAA DIGA AELA-PILLA.

**Comment by behdad** [comment]
> Jonathan and I looked into this. Pushed a few commits into branch, but hit a wall. Reported to Andrew Glass:
> 
> Sinhala uses explicit reph formation. Ie, Ra,H,ZWJ forms a reordering reph form. However, MS iskpota fonts seem to ligate both Ra,H and Ra,H,ZWJ in the rphf feature, only one of which should be reordered. Detecting this basically would introduce a special-casing hack in the USE, which is not documented in the spec.

@xadxura can you advise?  What does DWrite implementation do?

**Comment by khaledhosny** [comment]
What do we need to unblock this issue?

**Comment by Richard57** [comment]
Abandon Windows 8 and earlier, or accept a hack to special case fonts known to use rphf the way Iskoola Pota does.  The Microsoft renderers can simply branch on operating system, and I suspect modern MS Edge isn't required to support Pali in Sinhala script - that seemingly went out with Windows 8.  (End of life might be Windows 7.)  Iskoola Pota was replaced for Sinhala by Nirmala UI, which doesn't support touching letters, which is how most conjuncts are formed in traditional Pali.

The connection between touching letters and this issue is just a matter of the idiosyncrasies of fonts that support touching letters.

**Comment by khaledhosny** [comment]
Since you are the expert here, I guess you have to decide which of these two solutions makes more sense and go ahead with it. After 5 years, I don’t think we are going to get any other input.

**Comment by Richard57** [comment]
I suggest you go ahead with the hack.  To be detected, all of the following conditions have to be satisfied:

a) Script is Sinhala.
b) Input length is 2 glyphs (this is not valid for rphf for Sinhala with the standard encoding)
c) Input glyphs are from  <U+0DBB, U+0DCA>
d) Glyph IDs are what the font in its various forms has used.  On my Windows 7 machine, they are <737, 746> for both regular and bold.  This is Version 5.90 of the font.

**Comment by behdad** [comment]
@dscorbett Are you interested in working on this?
