### ISSUE TITLE
multi-line text files not processed correctly in Windows build of hb-shape

### ISSUE THREAD

**Issue by cjchapman** [harfbuzz/harfbuzz#1045]
There was a problem with the pre-built 1.7.6 Windows binary for hb-shape, but when Behdad sent me a build of the latest code, we saw a problem with garbage output for everything after the first line of a multi-line text file. It seems similar to the OS X multi-line hb-shape problem I reported earlier (https://github.com/harfbuzz/harfbuzz/issues/888).

**Comment by ebraminio** [comment]
On an updated master,
```bash
➜  harfbuzz git:(master) ✗ wine winbuild/util/hb-shape.exe iskpota.ttf -u U+0DBB,U+0DCA,U+200D,U+0DBA,U+0DCA,U+200D,U+0DBA,U+0A,U+0DBB,U+0DCA,U+200D,U+0DBA,U+0DCA,U+200D,U+0DBA
[gid736=0+1343|gid600=0+1130]
[gid736=0+1343|gid600=0+1130]
```

So no idea how to repro.

**Comment by ebraminio** [comment]
Also tried input from file and was working correctly.

**Comment by HinTak** [comment]
Again, is this win32 harfbuzz or win64 harfbuzz?

**Comment by khaledhosny** [comment]
I can’t reproduce this (pre-built binaries, Windows 10), please re-open if it is still an issue.
