### ISSUE TITLE
hb-shape with default shaper (not uniscribe) not shaping Sinhala at all on Windows

### ISSUE THREAD

**Issue by cjchapman** [harfbuzz/harfbuzz#1046]
Follow up to my previous bug: Behdad and I also noticed that hb-shape with its default OpenType shaper (i.e. not using Uniscribe) seemed to not shape a line of Sinhala at all (using the text & font from https://github.com/harfbuzz/harfbuzz/issues/967) -- i.e. the glyphs were all the nominal glyphs for the characters, not the shaped glyphs.

**Comment by ebraminio** [comment]
On an updated master,
```bash
➜  harfbuzz git:(master) ✗ wine winbuild/util/hb-shape.exe iskpota.ttf -u U+0DBB,U+0DCA,U+200D,U+0DBA,U+0DCA,U+200D,U+0DBA,U+0A,U+0DBB,U+0DCA,U+200D,U+0DBA,U+0DCA,U+200D,U+0DBA
[gid736=0+1343|gid600=0+1130]
[gid736=0+1343|gid600=0+1130]
```

So no idea how to repro.

**Comment by behdad** [comment]
I can't repro using wine either. Issue only exhibited when we tried the binaries on a Windows 10 VM.

**Comment by ebraminio** [comment]
So Sinhala test is working on our CI on both mingw and MSVC. Weird :/

**Comment by HinTak** [comment]
Are you talking about win32 harfbuzz or win64 harfbuzz? I assume the VM is likey 64-bit, but the wine instruction is 32-bit.

**Comment by khaledhosny** [comment]
I can’t reproduce this (pre-built binaries, Windows 10), please re-open if it is still an issue.
