### ISSUE TITLE
 failed: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

### ISSUE THREAD

**Issue by timelessz** [harfbuzz/harfbuzz#1051]
how to fix this bug?

**Comment by timelessz** [comment]
how to  install the official freetype2 ?

**Comment by ebraminio** [comment]
Hi there!

> how to fix this bug?

You need an updated version of freetype. 

> how to install the official freetype2 ?

Similar way with harfbuzz.

Consider using a forum or Google search for the next time. Good luck :)
