### ISSUE TITLE
Kh-bokor

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1056]
[Bug_Kh-Bokor.zip](https://github.com/harfbuzz/harfbuzz/files/2096966/Bug_Kh-Bokor.zip)
[Harfbuzz-314 updated.docx](https://github.com/harfbuzz/harfbuzz/files/2096968/Harfbuzz-314.updated.docx)
Shaping issue can be seen with the attached document.

**Comment by behdad** [comment]
Fixed by recent changes.
