### ISSUE TITLE
Khmer: Above base feature garble (Leelawadi UI)

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1057]
![abv_base_matra_garble](https://user-images.githubusercontent.com/38288804/41336477-fcc2d59e-6f09-11e8-80d8-518b503a40a6.PNG)
[leelawadee-ui.zip](https://github.com/harfbuzz/harfbuzz/files/2097009/leelawadee-ui.zip)

**Comment by olivierberten** [comment]
Text for this sample is in issue #1026

**Comment by behdad** [comment]
> But it is a font limitation since Harfbuzz and Uniscribe agree on these ones...

Thanks. Closing.
