### ISSUE TITLE
With 1.8.1 all tests fail

### ISSUE THREAD

**Issue by zarniwhoop73** [harfbuzz/harfbuzz#1067]
[test-suite.log](https://github.com/harfbuzz/harfbuzz/files/2130235/test-suite.log)

All fail with -
Traceback (most recent call last):
  File "./../run-tests.py", line 117, in <module>
    _, returncode = cmd(["which", "ttx"])
  File "./../run-tests.py", line 21, in cmd
    command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

This is on last week's Beyond Linux From Scratch, Python-2.7.15, gcc-8.1.0, binutils-2.30, glibc-2.27.

**Comment by ebraminio** [comment]
It seems you don't have the popular `which` command on your system. Please try to make that happen (or maybe alias it to `where` or `whereis`) and keep us tuned about the result. Thanks

**Comment by zarniwhoop73** [comment]
Never heard of 'where' or 'whereis' in a regular linux context. And yes, I do have 'which' 
ken@origin /tmp/harfbuzz-1.8.1 $which which
/usr/bin/which

ken@origin /tmp/harfbuzz-1.8.1 $cat /usr/bin/which
type -pa "$@" | head -n 1 ; exit ${PIPESTATUS[0]}

For some reason I only got a 'closed' message, not your comment, so I'll probably describe this version as "does not have a working testsuite"

**Comment by zarniwhoop73** [comment]
Your comment that I seem to lack 'which' has now arrived, some time after the notification of closure.  Email is fun, isn't it.

**Comment by ebraminio** [comment]
> I'll probably describe this version as "does not have a working testsuite"

We have a number of CI bots with great diversity, from Windows, macOS, ArchLinux and Alpine Linux to PSVita and emscripten (the latter ones don't run the test suit, but still), that's why we are confident that we do have a working test suit :P

**Comment by ebraminio** [comment]
So. It isn't fixed yet? Can we access your environment somehow? Maybe with Docker image or so?

**Comment by ebraminio** [comment]
Anyway we like to solve your issue and will accept the fix patch if it isn't disturbing.

**Comment by zarniwhoop73** [comment]
I don't do docker, and anyway my system is not distributable (e.g. I build ffmpeg with options which prevent that). And I don't have a patch - will maybe look later, but python is most definitely not my strong point.

**Comment by zarniwhoop73** [comment]
First, I apologize for not realising that the main part of the tests had completed ok - I only watched the screen intermittently and just saw the many compiles. It's only these last three tests which fail.

And I come from a traditional computing background - look at the first error message, then try to understand what it is saying. In this case, google suggested the file was not executable (e.g. lacking a shebang line) so I did not  look at the "which" line (and like most python it is still obscure to me). But after searching for "ttx" (what I really like about _perl_ is that the module distributions generally tell you what is missing) I found it comes from fonttools. So, I installed that for python2. No obvious difference (threw away the previous test build, used fresh source).

Traceback (most recent call last):
  File "./../run-tests.py", line 117, in <module>
    _, returncode = cmd(["which", "ttx"])
  File "./../run-tests.py", line 21, in cmd
    command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
FAIL tests/basics.tests (exit status: 1)

And since the tracebacks explicityl reference 2.7 I assume it intends to run python2 not python3, so no point installing a module for 3.

**Comment by ebraminio** [comment]
Oh that tests will be skipped when ttx doesn't exist, and it is just about testing some obsecur part of harfbuzz so ignore the whole thing I would say, but if the error doesn't let you to have a successful make check it is a bug.

**Comment by zarniwhoop73** [comment]
In that case, I suggest it **is** a bug.  It tells me

See test/subset/data/test-suite.log
Please report to https://github.com/harfbuzz/harfbuzz/issues/new
(which is why I reported this) then make test-suite.log ends with Error 1, make check-TESTS ends with Error 2, makecheck ends with Error 1 and status is 2.

**Comment by ebraminio** [comment]
But we don't still have any idea why it happens there but not on our bots :/ Please see if you can fix it also.

**Comment by ebraminio** [comment]
Okay. I think I have a clue what can improved from our side.

**Comment by ebraminio** [comment]
Please try https://github.com/harfbuzz/harfbuzz/pull/1075 (or `curl -L https://github.com/harfbuzz/harfbuzz/pull/1075.diff | git apply`) to see if it solves your issue. Thanks!

**Comment by ebraminio** [comment]
And thank you for your collaboration and bearing with me :)
