### ISSUE TITLE
Telugu Gautami: 

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1069]
![telugu_gautami](https://user-images.githubusercontent.com/38288804/41842564-d015b59c-7888-11e8-8b8b-1415837ac6b8.png)
[gautami.zip](https://github.com/harfbuzz/harfbuzz/files/2132560/gautami.zip)

Text: క్ష్

**Comment by cjchapman** [comment]
Seems like the `akhn` feature wasn't applied in the non-matching image above. However, in our testing, we saw HarfBuzz applying the feature and getting output that matched the two matching images above.

**Comment by behdad** [comment]
Yeah I also get the expected ligature.

**Comment by behdad** [comment]
@Amritasingh0512 can you figure out what's wrong in your setup?
