### ISSUE TITLE
AdobeDevanagari-Regular : Matra positioning

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1070]
Text: ष्ट्य ष्ट्‍य ष्ठ्य ष‍्य ट्ञ ष्ट्यि ष्ट्‍यि ष्ठ्यि ष‍्यि ट्ञि
[AdobeDevanagari-Regular.zip](https://github.com/harfbuzz/harfbuzz/files/2132599/AdobeDevanagari-Regular.zip)
<img width="594" alt="devanagari_git_1" src="https://user-images.githubusercontent.com/38288804/41843440-2aa06a5a-788b-11e8-9a17-6b1a83a75b17.PNG">

**Comment by behdad** [comment]
What's expected?

**Comment by behdad** [comment]
When I compare to Windows 7 rendering, it's only the ष्ट्‍यि produces different results.  What are you testing against?

**Comment by behdad** [comment]
I fixed the one case that we differed from Windows.
