### ISSUE TITLE
Devanagari: Halfless mangal

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1072]
<img width="778" alt="devanagari_halfless_mangal" src="https://user-images.githubusercontent.com/38288804/41844268-53700d62-788d-11e8-84d2-8cb301ef8a5d.PNG">
[mangal.zip](https://github.com/harfbuzz/harfbuzz/files/2132655/mangal.zip)

Text: ट्द्कि द्द्कि द्ण्कि द्ग्कि ड्र्कि क्र्कि ॥ ड्द्मि द्द्मिद्द्दि

**Comment by behdad** [comment]
Are you testing HarfBuzz against Windows, or against existing Adobe implementation?  For the font you attached, Windows 7 and HarfBuzz agree on the rendering.
