### ISSUE TITLE
Bengali: :Vrinda: Positioning of halant

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1073]
[vrinda.zip](https://github.com/harfbuzz/harfbuzz/files/2132660/vrinda.zip)

Text: ঘ্বে ঘ্বৌ ঘ্বূ ঘ্ব্ ঘ্যে ঘ্যৌ ঘ্যূ ঘ্য্
<img width="399" alt="bengali_below_post_vrinda" src="https://user-images.githubusercontent.com/38288804/41844597-46ce1b02-788e-11e8-981d-94be5f14d3f8.PNG">

**Comment by behdad** [comment]
Where is this version of vrinda from?  I tested with the one from Windows 7 and HarfBuzz works fine.

**Comment by behdad** [comment]
I confirm the bug though.  Our base logic gets tricked apparently.

**Comment by behdad** [comment]
I see, this is WinXP vrinda.  This uses, I think, old-Indic. We form ya-phala from the second halant somehow...

**Comment by behdad** [comment]
The lookup that makes the yaphala indeed matches ya,halant (not halant,ya). This assumes that we find ghain as the base and reorder the halant to after ya (because of this being old-indic). My guess is that we are finding ya as base however.

**Comment by behdad** [comment]
The feature that does this is `pstf` that sounds correct. We should find base at ghain.

**Comment by behdad** [comment]
This comment looks relevant:
```
  /* For old-style Indic script tags, move the first post-base Halant after 
   * last consonant. 
   * 
   * Reports suggest that in some scripts Uniscribe does this only if there 
   * is *not* a Halant after last consonant already (eg. Kannada), while it 
   * does it unconditionally in other scripts (eg. Malayalam).  We don't 
   * currently know about other scripts, so we single out Malayalam for now. 
   * 
   * Kannada test case: 
   * U+0C9A,U+0CCD,U+0C9A,U+0CCD 
   * With some versions of Lohit Kannada. 
   * https://bugs.freedesktop.org/show_bug.cgi?id=59118 
   * 
   * Malayalam test case: 
   * U+0D38,U+0D4D,U+0D31,U+0D4D,U+0D31,U+0D4D 
   * With lohit-ttf-20121122/Lohit-Malayalam.ttf 
   */ 
  if (indic_plan->is_old_spec) 
  { 
    bool disallow_double_halants = buffer->props.script != HB_SCRIPT_MALAYALAM; 
    for (unsigned int i = base + 1; i < end; i++) 
      if (info[i].indic_category() == OT_H) 
```
