### ISSUE TITLE
cmake build don't have an option to turn on/off fontconfig

### ISSUE THREAD

**Issue by maxinbjohn** [harfbuzz/harfbuzz#1074]
configure.ac has an option to turn on/off fontconfig:

AC_ARG_WITH(fontconfig,
 [AS_HELP_STRING([--with-fontconfig=@<:@yes/no/auto@:>@],
 [Use fontconfig @<:@default=auto@:>@])],,
 [with_fontconfig=auto])
 have_fontconfig=false

Whereas "CMakeLists.txt" don't have similar option to turn on/off fontconfig

**Comment by ebraminio** [comment]
And harfbuzz isn't going to use fontconfig directly in the foreseeable future or ever so lets close until we get a real use case for it.

**Comment by ebraminio** [comment]
But feel free to propose any patch to normalize the station, either by commenting the autotools support or adding cmake support :)

**Comment by maxinbjohn** [comment]
Hi @ebraminio , 
Thanks a lot for clarifying this. I will update configure.ac to comment out the fontconfig part.

Thanks!
