### ISSUE TITLE
CFF/CFF2 subsetting

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#1077]
- [x] Write structs for reading CFF/CFF2 (INDEX, DICT, etc)
- [x] Write charstring interpreter (incl. blend operator for VF)
- [x] Implement subset CharStrings
- [x] Implement subset FDSelect & FDArray
- [x] CFF2 support
- [x] CFF support
- [x] Flatten subroutines
- [x] Drop hints with --no-hinting option (requires flatten subrs)
- [x] Subset charset & strings in CFF
- [x] Add tests
- [x] Implement get_extents for CFF
- [x] Implement get_extents for CFF2 (incl. VF)
- [x] Subset VORG
- [x] fix flex bug
- [x] add CFF1 --desubroutinize option
- [x] add CFF2 --desubroutinize option
- [x] implement deprecated CFF1 operators (dotsection, seac behavior of endchar)

**Comment by cjchapman** [comment]
@behdad Can we get your thoughts? Thanks!

**Comment by blueshade7** [comment]
This is my plan for DICT.

DICT, PrivateDICT, CharString share the same base, ByteString, an UnsizedArrayOf<HBUInt8>.
ByteString has an accelerator, which is an interpreter of the byte string.
The interpreter takes 256-plus callback function table, unique to each struct (many of individual callback functions will be shared).
Each callback function in the table processes a particular byte value, e.g., func_0 processes byte value 0x00.
“Plus” functions are for two-byte operators, indirectly called with the second byte by the function for the first byte 12.
A callback function table will be initialized once in its “get” function and stored statically.
Interpreter for DICT and PrivateDICT takes a param from the caller filled with default values then overwritten by parsed out values on return.

Unlike DICT or PrivateDICT which deals with a limited set of values, CharString produces output of variable length, calls out to subroutines.
More on CharString later.

**Comment by behdad** [comment]
> Plan A:
> 
> template <typename Type>
> struct Index
> {
>   HBUINT32  count;
>   HBUINT8   offSize;
>   union {
>     UnsizedOffsetArrayOf<Type, HBUINT8>   objects1;
>     UnsizedOffsetArrayOf<Type, HBUINT16>  objects2;
>     UnsizedOffsetArrayOf<Type, HBUINT24>  objects3;
>     UnsizedOffsetArrayOf<Type, HBUINT32>  objects4;
>   } u;
> };
> 
> Then at run time switch on offSize to choose out of union of four offset arrays as implementation.
> 
> Plan B is to write OffsetN from scratch modeled on Offset but takes the offset size as param, in turn OffsetNTo, OffsetNArray, OffsetNArrayOf to be written from it.
> 
> Suggestions?

I suggest writing Index from scratch.  For one thing, the offsets in this struct are different in that an offset of 0 does NOT mean null.

Also, I suggest you write a non-template Index first, then write a templatized IndexOf<>.

Note that we already have something that uses 1 to 4 byte integers.  That's `DeltaSetIndexMap`.  Take a look.

A question arises as to what to sanitize.  I suggest we use the last entry in the offset table to sanitize the total size of Index, but not check all entries.  Then at run-time, we check all offsets against that last entry.

**Comment by behdad** [comment]
> Plan A:
> 
> template <typename Type>
> struct Index
> {
>   HBUINT32  count;
>   HBUINT8   offSize;
>   union {
>     UnsizedOffsetArrayOf<Type, HBUINT8>   objects1;
>     UnsizedOffsetArrayOf<Type, HBUINT16>  objects2;
>     UnsizedOffsetArrayOf<Type, HBUINT24>  objects3;
>     UnsizedOffsetArrayOf<Type, HBUINT32>  objects4;
>   } u;
> };
> 
> Then at run time switch on offSize to choose out of union of four offset arrays as implementation.
> 
> Plan B is to write OffsetN from scratch modeled on Offset but takes the offset size as param, in turn OffsetNTo, OffsetNArray, OffsetNArrayOf to be written from it.
> 
> Suggestions?

I suggest writing Index from scratch.  For one thing, the offsets in this struct are different in that an offset of 0 does NOT mean null.

Also, I suggest you write a non-template Index first, then write a templatized IndexOf<>.

Note that we already have something that uses 1 to 4 byte integers.  That's `DeltaSetIndexMap`.  Take a look.

A question arises as to what to sanitize.  I suggest we use the last entry in the offset table to sanitize the total size of Index, but not check all entries.  Then at run-time, we check all offsets against that last entry.

**Comment by behdad** [comment]
> Also, I suggest you write a non-template Index first, then write a templatized IndexOf<>.

The Index struct's operator [] will return hb_bytes_t.

**Comment by behdad** [comment]
> Also, I suggest you write a non-template Index first, then write a templatized IndexOf<>.

The Index struct's operator [] will return hb_bytes_t.

**Comment by behdad** [comment]
> This is my plan for DICT.
> 
> DICT, PrivateDICT, CharString share the same base, ByteString, an UnsizedArrayOf<HBUInt8>.
> ByteString has an accelerator, which is an interpreter of the byte string.
> The interpreter takes 256-plus callback function table, unique to each struct (many of individual callback functions will be shared).

Function tables are slightly problematic because of the relocation overhead they cause.  Given that most of the 256 entries are read_byte, I think I prefer a templatized interpretter that takes an OperatorSet that uses switch / if to parse the operators.

> Each callback function in the table processes a particular byte value, e.g., func_0 processes byte value 0x00.
> “Plus” functions are for two-byte operators, indirectly called with the second byte by the function for the first byte 12.
> A callback function table will be initialized once in its “get” function and stored statically.
> Interpreter for DICT and PrivateDICT takes a param from the caller filled with default values then overwritten by parsed out values on return.

Yes, agree with this part.

> Unlike DICT or PrivateDICT which deals with a limited set of values, CharString produces output of variable length, calls out to subroutines.
> More on CharString later.

Right. Let's focus on the first two first.

**Comment by KrasnayaPloshchad** [comment]
This would be necessary for variable fonts, since OpenType specifacation only CFF2 fonts are allowed to be variable, and many printer drivers and PDF rendering engines don't understand font variation.

**Comment by blueshade7** [comment]
>Function tables are slightly problematic … I think I prefer a templatized interpretter that takes an OperatorSet that uses switch / if to parse the operators.

OK. I assume you mean template parameter OperatorSet is another struct implementing a function like “process_byte” to be specialized for DICT, PrivateDICT, called from the interpreter loop?

**Comment by blueshade7** [comment]
How deep should we sanitize CFF/CFF2? If we are to sanitize font/private dicts, Subrs, CharStrings, we need to get their offsets first, it’s like interpreting dicts twice.

**Comment by ebraminio** [comment]
At some point we like to read CFF/CFF2 glyph coordinates, just like #875 a WIP for glyf. Not necessary for the initial work but please consider that for the design :)

**Comment by blueshade7** [comment]
>At some point we like to read CFF/CFF2 glyph coordinates, just like #875 a WIP for glyf. Not necessary for the initial work but please consider that for the design :)

Do you mean glyph extents by glyph coordinates? If so, it is part of the plan. Speaking of glyph extents, I noticed `hb_ot_get_glyph_extents` does not take variable font coordinates into account currently. I wonder if it is supposed to.

**Comment by ebraminio** [comment]
Coordinates, like the mentioned PR :)

**Comment by blueshade7** [comment]
Created cff-subset branch with Index, Dict structs
hb-subset takes CFF2 table, reads top dict, outputs empty CFF2

**Comment by blueshade7** [comment]
Currently planning on how to actually subset CFF2.

If any data are removed from CFF2/CFF, encoded offsets need to be updated in dicts, potentially occupying different number of bytes depending on their values. This may in return affect other offset values. AFDKO deals with this problem by iterating over the process until no more size change occurs.

I am planning a different approach by encoding an offset always as 4-byte integer for simplification at expense of potentially wasting some bytes for each.

Also, planning to copy over unaffected dict values, such as hints, as byte strings from source to dest without re-encoding. This avoids the problem of estimating the byte size of encoded operands. This is especially a problem with real numbers occupying a variable length of bytes. If naively implemented, each number will be encoded multiple times, a total waste when not modified.

For this, offset & length of operand byte string needs to be recorded for each operator during dict parse.

**Comment by blueshade7** [comment]
cff-subset branch is now able to subset CFF2 charstrings
moving on to subset FDSelect & FontDicts (along with local subrs belonging to unused FDs)

**Comment by blueshade7** [comment]
Pushed the implementation to subset FDSelect & FDArray
Moving onto add CFF support (now CFF2 only)

**Comment by blueshade7** [comment]
Pushed CFF subsetter
Moving onto charstring interpreter & nullifying unused subroutines (poor-man's subroutines removal)

**Comment by blueshade7** [comment]
Pushed CFF subroutine nullifier along with CFF charstring interpreter
Next work on CFF2 subroutine nullifier

**Comment by blueshade7** [comment]
Pushed CFF2 subroutine nullifier.
Next work on hint removal (from private dicts & charstrings).

**Comment by blueshade7** [comment]
Pushed CFF subroutine flattener (nullifier unused for now).
Hint removal partially implemented (from private dicts).
Next work on CFF2 subroutine flattener.

**Comment by blueshade7** [comment]
Pushed CFF2 subroutine flattener
Next work on drop hints from charstrings, subset charset & strings

**Comment by blueshade7** [comment]
Pushed drop hints from CFF & CFF2 charstrings.
Next work on subset charset & strings in CFF.

**Comment by blueshade7** [comment]
Implemented get_extents for CFF.

**Comment by blueshade7** [comment]
Added full-font & Japanese test fonts for CFF.
Japanese test case exposed VORG subsetting is missing.

**Comment by blueshade7** [comment]
Added VORG subsetter.

**Comment by blueshade7** [comment]
Added CFF fonts to full-font.tests & japanese.tests, added test-subset-cff1 & test-subset-cff2 using SourceSansPro & AdobeVFPrototype.
Planning to add a CFF Japanese font to test-subset-cff1 for better code coverage.

**Comment by blueshade7** [comment]
Added Source Han Sans subset font to test-subset-cff1.
Going to work on vsindex operator & CFF2 VF glyph extents.

**Comment by blueshade7** [comment]
Implemented CFF2 get_extents along with test cases (default & with VF coords).
Planning to add test cases for CFF2 vsindex and CFF1 legacy operators.

**Comment by blueshade7** [comment]
Added vsindex & CFF1 legacy op test cases.
Planning for more tests for better code coverage.

**Comment by blueshade7** [comment]
Found a bug with flex.
Even when hints are ignored, arguments to flex are coordinate deltas so the current point still needs to be updated with them. This is true for both glyph-extents and subsetting. pyftsubset seems to retain flex with --no-hinting though.

**Comment by behdad** [comment]
> pyftsubset seems to retain flex with --no-hinting though.

Right.  We consider flex an extinct species. :D  Feel free to fix that though.  Thanks.

**Comment by blueshade7** [comment]
Added desubroutinize option & implemented no desubroutinize (subroutines preserved) with CFF1 as default
Added api test cases for CFF1 desubroutinize / no desubroutinize
CFF2 no desubroutinize is yet to be implemented (currently always desubroutinized)

**Comment by blueshade7** [comment]
CFF2 no desubroutinize implemented

**Comment by blueshade7** [comment]
Implemented seac for extents and subsetting

**Comment by ebraminio** [comment]
As #1113 :fireworks: :fireworks:  let's file other separately
