### ISSUE TITLE
Thai :: Arial Unicode MS (Above base feature)

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1080]
<img width="435" alt="405" src="https://user-images.githubusercontent.com/38288804/41956375-08cfb468-7a01-11e8-9af8-b22ce15f3c07.PNG">
[arial-unicode-ms.zip](https://github.com/harfbuzz/harfbuzz/files/2139989/arial-unicode-ms.zip)::

TExt Sequence: ฬ๋

**Comment by Amritasingh0512** [comment]
Updated the text sequence

**Comment by cjchapman** [comment]
<img width="463" alt="screen shot 2018-07-31 at 2 16 11 pm" src="https://user-images.githubusercontent.com/17747678/43487734-5afc4658-94cc-11e8-8660-a7f9352d58c8.png">

I see the same output as HarfBuzz in BabelPad on Windows 10.
