### ISSUE TITLE
compile error: "src/hb-blob.cc", line 620: Error:  #20: identifier "EINTR" is undefined

### ISSUE THREAD

**Issue by imgtec** [harfbuzz/harfbuzz#1081]
compile log:
[https://paste.ubuntu.com/p/5GpF3wfGmN/](https://paste.ubuntu.com/p/5GpF3wfGmN/)

Hi, armcc doesn't define macro "EINTR". 
is this gcc special?

**Comment by ebraminio** [comment]
I was guessing it doesn't exist that's why I asked you :P
