### ISSUE TITLE
Thai belowmark shaping for minority languages

### ISSUE THREAD

**Issue by ohbendy** [harfbuzz/harfbuzz#1088]
While testing a Thai font we're developing, I noted a few errors with handling of uncommon mark combinations used in minority languages.

**Patani Malay**

This language employs the combining macron below on four Thai bases: ง̱ ญ̱ น̱ ม̱

[In the system font the yoYing still has its tail, but the font should use the tail-less version when the macron is attached below, in the same way that vowel marks below trigger that substitution.]

Even by making the yoYing_macronbelowcomb into a ligature glyph and adding a bottom anchor does not seem to allow below vowels to attach correctly, as shown in the bottom line here. There should be a gap between the macron and below saraU. Text sequence is ญุ ญุ̃ ญุ̱ ญุ̱̃ :

<img width="134" alt="screen shot 2018-07-07 at 12 59 44" src="https://user-images.githubusercontent.com/12471463/42410690-a9912ef4-81e5-11e8-9307-e31aa709bc27.png">

A similar problem exists with the base glyphs that are modified with phinthu [กฺ คฺ ซฺ ยฺ รฺ] . These can also take a below vowel [in the sequences กฺุ คฺุ ซฺุ ยฺุ รฺุ and กฺู คฺู ซฺู ยฺู รฺู and perhaps even with tildecomb in กฺุ̃] . Unfortunately the below vowels just sits on top of the phinthu:

<img width="232" alt="screen shot 2018-07-07 at 13 03 13" src="https://user-images.githubusercontent.com/12471463/42410704-205d517a-81e6-11e8-8140-16393fb07fe4.png">

These sequences work correctly in Safari [except when pasting from Firefox, weirdly]:

<img width="142" alt="screen shot 2018-07-07 at 13 08 58" src="https://user-images.githubusercontent.com/12471463/42410747-f4bb29ce-81e6-11e8-80a2-61371d7a92d3.png">

<img width="229" alt="screen shot 2018-07-07 at 13 09 48" src="https://user-images.githubusercontent.com/12471463/42410751-0b8554e0-81e7-11e8-9bb0-e8a78dfa2ccd.png">

**Comment by ohbendy** [comment]
In case of need, Peter Constable is registering "MFA " as a language tag for Patani Malay.

**Comment by behdad** [comment]
We need your font to test at least.  We don't do anything special, if your font has mkmk it should work.

**Comment by behdad** [comment]
What's actionable here?

**Comment by punchcutter** [comment]
@behdad Isn't this the same as https://github.com/googlei18n/noto-fonts/issues/1135 ?
We'll need to update Noto as well for this so either normalization shouldn't force the mark order for Patani Malay or the lookup needs to do a ligature substitution based on the normalized mark order. 

@ohbendy Did you try a ligature with the input order swapped so that it will apply after normalization?

**Comment by ohbendy** [comment]
I can't send the fonts now, but they'll be open source when published. I didn't try any workarounds as we delivered already, the fonts worked fine in other browsers and I assumed Harfbuzz would get fixed. It should be very easy to test this with the Noto fonts. 

In case of need: https://www.unicode.org/L2/L2018/18216-thai-order.pdf

**Comment by behdad** [comment]
What's the original twitter thread this was brought up?

**Comment by behdad** [comment]
Okay, I don't have time right now to read that document.  We'll get to this later.

**Comment by behdad** [comment]
@jfkthame any chance you can review this and advise?

**Comment by behdad** [comment]
@dscorbett Do you know what needs to be done here?

**Comment by dscorbett** [comment]
Nothing needs to be done in HarfBuzz. This should be dealt with in fonts. Even if HarfBuzz reordered marks more helpfully, fonts would still need to deal with Core Text and DirectWrite.
