### ISSUE TITLE
Make some of the CI bots non-C++11

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1095]
To catch bugs there.

**Comment by ebraminio** [comment]
Our `macos-llvm-gcc-4.2` already does that that is why it doesn't do https://github.com/harfbuzz/harfbuzz/commit/21fa170f0bfb0109c506ed17f5aff8b062564ffa but we can surely assign more easily but what compiler definition should be used for that?

**Comment by behdad** [comment]
Ah, ok, cool. I was wondering why no bot failed with https://github.com/harfbuzz/harfbuzz/commit/2aae617a84f47836f10efd30df43e13e3a9447e1

maybe it did. Maybe it supports constexpr even if not all of C++11.  Anyway, closing.
The compiler cmdline to do that would be -std=c++98
