### ISSUE TITLE
[cmake] hb-ft.h is missing in INSTALL

### ISSUE THREAD

**Issue by zhou-heng** [harfbuzz/harfbuzz#1096]
Some opensources, say FreeType, want this header, so please modify INSTALL configuration to copy it into ${CMAKE_INSTALL_PREFIX}\include\harfbuzz. I'm on Windows. Thanks.

**Comment by ebraminio** [comment]
Please explain this a little more. Thanks

**Comment by zhou-heng** [comment]
My environment:
- Windows 10 version 1803
- Visual Studio 2015 Update 3
- Cmake 3.11.4
- HarfBuzz 1.8.4 downloaded from https://www.freedesktop.org/software/harfbuzz/release/
- FreeType 2.9.1 downloaded from http://www.namesdir.com/mirrors/nongnu/freetype/

As I said, `FreeType` uses `HarfBuzz` to build.

This is the CMake command to build HarfBuzz: 

> cmake -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_INSTALL_PREFIX=C:\\...\harfbuzz-1.8.4\install_ -G"Visual Studio 14 2015 Win64" ..

After generating harfbuzz.sln, I build it inside Visual Studio and right-click INSTALL project->Build to install the distribution. There is no `hb-ft.h` in the distribution folder specified by ${CMAKE_INSTALL_PREFIX}, i.e., C:\\...\harfbuzz-1.8.4\install_\include\harfbuzz. Next I will build FreeType. The CMake command line is:
> cmake -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_INSTALL_PREFIX=C:\\...\freetype-2.9\install -DPKG_CONFIG_EXECUTABLE=C:\\...\pkg-config.exe -DZLIB_LIBRARY=C:\\...\zlib-1.2.11\install\lib\zlib.lib -DZLIB_INCLUDE_DIR=C:\\...\zlib-1.2.11\install\include -DPNG_LIBRARY=C:\\...\lpng1632\install_\lib\libpng16.lib -DPNG_PNG_INCLUDE_DIR=C:\\...\lpng1632\install_\include -DHARFBUZZ_INCLUDE_DIRS=C:\\...\harfbuzz-1.8.4\install_\include\harfbuzz -DHARFBUZZ_LIBRARIES=C:\\...\harfbuzz-1.8.4\install_\lib\harfbuzz.lib -DBZIP2_INCLUDE_DIR=C:\\...\bzip2-1.0.6 -DBZIP2_LIBRARIES=C:/.../bzip2-1.0.6/Release/libbz2.lib -G"Visual Studio 14 2015 Win64" ..
> 

After generating freetype.sln, I open it in VS and try to build the freetype project. An error is as follows:
`1>c:\...\freetype-2.9\src\autofit\afshaper.h(31): fatal error C1083: Cannot open include file: 'hb-ft.h': No such file or directory
`
If I copy `hb-ft.h` from `C:\...\harfbuzz-1.8.4\src` to `C:\...\harfbuzz-1.8.4\install_\include\harfbuzz`, everything will be fine. So I concluded that the error is caused by failure of HarfBuzz's INSTALL to copy hb-ft.h to the distribution folder, hence the ticket. There is nothing special in the above building steps, so it is easy to reproduce the problem.

**Comment by ebraminio** [comment]
So maybe passing -DHB_HAVE_FREETYPE=ON to CMake?

Supporting users using CMake on Windows is hard and we are unable to do so but HarfBuzz is already added to [vcpkg](https://github.com/Microsoft/vcpkg/), a quality package manager ensures workability of using HarfBuzz library among many others on Windows so I am closing this file. Please test that and keep up tuned about the result. Thanks
