### ISSUE TITLE
Can HarfBuzz change from #include (FindFreetype) to find_package (Freetype) to use root variable?

### ISSUE THREAD

**Issue by zhou-heng** [harfbuzz/harfbuzz#1101]
The new version of CMake 3.12 supports per-package root variable as a search hint. This root variable, however, seems to be available from stack only. Since #include does not create stack, can HarfBuzz change from `#include (FindFreetype)` (line 273 of CMakeLists.txt) to `find_package (Freetype)` to make use of root variable? Thanks.

**Comment by ebraminio** [comment]
Hi Zhou. Does reverting https://github.com/harfbuzz/harfbuzz/commit/6760021d6f4beef852c6560607b32090bcfa5acb#diff-af3b638bc2a3e6c650974192a53c7291 locally helps you? I really didn't want to be rude by closing your previous issues #1096 but all I want you to do to use [Microsoft's vcpkg](https://github.com/Microsoft/vcpkg/). Just trust me, it makes your work sooo much easier and no longer fighting with every project CMake project files.

**Comment by ebraminio** [comment]
I don't know to proceed here Behdad as this was proposed by @roxlu on https://github.com/harfbuzz/harfbuzz/issues/518 originally.
