### ISSUE TITLE
Cursive attachment ignored with 'musc' script tag

### ISSUE THREAD

**Issue by punchcutter** [harfbuzz/harfbuzz#1103]
For Noto Music there are cursive attachments, but they are ignored when the script tag is musc. When set to DFLT it works. 

Example: 
𝅘𝅧𝅥𝅮
U+1D158,U+1D165,U+1D167,U+1D16E

Without cursive attachment:
![musc_no_cursive](https://user-images.githubusercontent.com/11257204/43014180-3408670e-8c00-11e8-97f0-8f46ce5d9f46.png)

With cursive attachment:
![musc_cursive](https://user-images.githubusercontent.com/11257204/43014185-36dd323e-8c00-11e8-96d5-698fb697b4ae.png)

**Comment by jfkthame** [comment]
I don't recall running across Noto Music; is it available for testing somewhere?

**Comment by punchcutter** [comment]
No, we haven't delivered yet. We are finishing and testing now which is how we found this issue.

**Comment by behdad** [comment]
HB doesn't recognize 'musc' script tag indeed, since there's no such Unicode script value.  Please use DFLT.

**Comment by behdad** [comment]
I would say use both, but there's really no benefit in doing that.

**Comment by punchcutter** [comment]
Yes, that makes sense. Doesn't seem like there needs to be a 'musc' tag at all. Safari doesn't care if the script is 'musc' or DFLT and renders correctly either way, but using DFLT works everywhere so we'll go with that.
