### ISSUE TITLE
Fall back to Georgian lowercase letters when Georgian uppercase letters are missing in a font

### ISSUE THREAD

**Issue by jungshik** [harfbuzz/harfbuzz#1104]
Unicode 11 encoded Georgian uppercase letters, but there is virtually no font to cover them in wide use.

Nonetheless, those characters show up in web pages thanks to CSS text-transform when browsers support Unicode 11 case conversion rules. 

There are multiple ways to deal with this. One possibility is for HarfBuzz to map Georgian uppercase letters to the corresponding lowercase/existing letters when a font does not support them. 

That way, all the down-the-pipe users of HarfBuzz will benefit without changing their code (Blink, Firefox, Android, etc). 

More details: 
Because Georgian script was treated as unicameral before Unicode 11, the case conversion operation over Georgian letters used to be no-op.  Now that it has become bicameral, all of sudden uppercasing with CSS 'text-transform' yields newly encoded uppercase letters, but virtually no font covers them. 

A lot of web pages use CSS text-transform to uppercase on the fly because they don't want to have inconsistency between text in lowercase and the corresponding text in uppercase (especially, when they're localized strings - translated from English or original in other languages). 

Examples: visit these pages in Chrome canary build with Unicode 11 data (ICU 62.1)  and you'll see tofus where Georgian uppercase letters are supposed to be. 

1.[ a Georgian web page I came across](http://albius.ge/?action=blog_more)

2. [Google flight search](https://www.google.com/flights?hl=ka#flt=/m/0d6lp..2018-08-04*./m/0d6lp.2018-08-08;c:USD;e:1;sd:1;t:h) 

3. [A twit about Youtube having this issue](https://twitter.com/razmadzekoko/status/1018775401668251648)

Ref:  googlei18n/noto-fonts#1261  http://crbug.com/865427

**Comment by jfkthame** [comment]
Yes, we've seen the same issue in Firefox, and have a bug report on file.

I don't think this should be done in harfbuzz, however. If a client application asks HB to shape certain characters with a certain font, that's what HB should do. Detecting whether the characters are supported by the font, and falling back (to a different font, or to different characters) if they're missing, should be the responsibility of the client - or at least a higher-level text library that deals with issues of font selection, fallback, etc. It doesn't belong in the shaping library.

**Comment by jungshik** [comment]
Thank you for your take, @jfkthame 
I agree to  what you wrote in principle, but doing that in HarfBuzz seems to have the largest coverage with the least amount of change and can be rather quickly deployed in the field.

**Comment by khaledhosny** [comment]
Doing it in HarfBuzz won’t help clients that check font coverage before
shaping (like Firefox). Personally I don’t feel easy about doing such
fallback in HarfBuzz since that is 1) too high level from HarfBuzz, 2)
clients who will benefit from this  (like Chrome) will be disadvantaged
when the system has a font that supports the uppercase characters (and I’d
rather use uppercase from a different font than use lowercase from current
one), 3) that is not the same thing as doing fallback shaping or handling
composed vs decomposed forms.

**Comment by markusicu** [comment]
Ideally, HarfBuzz would do this fallback only if there is no glyph even in the fallback fonts. As soon as a real font has glyphs for these characters, the hack would become a harmless no-op.

I don't know how to make this work with Firefox checking font coverage beforehand. What does Firefox do with Georgian capital letters if there is no font at all for them?

FYI

http://www.unicode.org/versions/Unicode11.0.0/
    ... adds "Georgian Mtavruli capital letters, newly added to support modern casing practices"

(Some more information: https://en.wikipedia.org/wiki/Georgian_scripts)

https://en.wikipedia.org/wiki/Georgian_language 3.7M native speakers, lang code "ka"

Unicode 11 delta code chart showing the 46 new letters:
https://www.unicode.org/charts/PDF/Unicode-11.0/U110-1C90.pdf

Probably the easiest-to-read mapping from the new capital letters to the old regular (now lowercase) ones is in
https://www.unicode.org/Public/UCD/latest/ucd/CaseFolding.txt
(Map first column to third column; ignore the second column with its "C" value.)

1C90; C; 10D0; # GEORGIAN MTAVRULI CAPITAL LETTER AN
1C91; C; 10D1; # GEORGIAN MTAVRULI CAPITAL LETTER BAN
1C92; C; 10D2; # GEORGIAN MTAVRULI CAPITAL LETTER GAN
1C93; C; 10D3; # GEORGIAN MTAVRULI CAPITAL LETTER DON
1C94; C; 10D4; # GEORGIAN MTAVRULI CAPITAL LETTER EN
1C95; C; 10D5; # GEORGIAN MTAVRULI CAPITAL LETTER VIN
1C96; C; 10D6; # GEORGIAN MTAVRULI CAPITAL LETTER ZEN
1C97; C; 10D7; # GEORGIAN MTAVRULI CAPITAL LETTER TAN
1C98; C; 10D8; # GEORGIAN MTAVRULI CAPITAL LETTER IN
1C99; C; 10D9; # GEORGIAN MTAVRULI CAPITAL LETTER KAN
1C9A; C; 10DA; # GEORGIAN MTAVRULI CAPITAL LETTER LAS
1C9B; C; 10DB; # GEORGIAN MTAVRULI CAPITAL LETTER MAN
1C9C; C; 10DC; # GEORGIAN MTAVRULI CAPITAL LETTER NAR
1C9D; C; 10DD; # GEORGIAN MTAVRULI CAPITAL LETTER ON
1C9E; C; 10DE; # GEORGIAN MTAVRULI CAPITAL LETTER PAR
1C9F; C; 10DF; # GEORGIAN MTAVRULI CAPITAL LETTER ZHAR
1CA0; C; 10E0; # GEORGIAN MTAVRULI CAPITAL LETTER RAE
1CA1; C; 10E1; # GEORGIAN MTAVRULI CAPITAL LETTER SAN
1CA2; C; 10E2; # GEORGIAN MTAVRULI CAPITAL LETTER TAR
1CA3; C; 10E3; # GEORGIAN MTAVRULI CAPITAL LETTER UN
1CA4; C; 10E4; # GEORGIAN MTAVRULI CAPITAL LETTER PHAR
1CA5; C; 10E5; # GEORGIAN MTAVRULI CAPITAL LETTER KHAR
1CA6; C; 10E6; # GEORGIAN MTAVRULI CAPITAL LETTER GHAN
1CA7; C; 10E7; # GEORGIAN MTAVRULI CAPITAL LETTER QAR
1CA8; C; 10E8; # GEORGIAN MTAVRULI CAPITAL LETTER SHIN
1CA9; C; 10E9; # GEORGIAN MTAVRULI CAPITAL LETTER CHIN
1CAA; C; 10EA; # GEORGIAN MTAVRULI CAPITAL LETTER CAN
1CAB; C; 10EB; # GEORGIAN MTAVRULI CAPITAL LETTER JIL
1CAC; C; 10EC; # GEORGIAN MTAVRULI CAPITAL LETTER CIL
1CAD; C; 10ED; # GEORGIAN MTAVRULI CAPITAL LETTER CHAR
1CAE; C; 10EE; # GEORGIAN MTAVRULI CAPITAL LETTER XAN
1CAF; C; 10EF; # GEORGIAN MTAVRULI CAPITAL LETTER JHAN
1CB0; C; 10F0; # GEORGIAN MTAVRULI CAPITAL LETTER HAE
1CB1; C; 10F1; # GEORGIAN MTAVRULI CAPITAL LETTER HE
1CB2; C; 10F2; # GEORGIAN MTAVRULI CAPITAL LETTER HIE
1CB3; C; 10F3; # GEORGIAN MTAVRULI CAPITAL LETTER WE
1CB4; C; 10F4; # GEORGIAN MTAVRULI CAPITAL LETTER HAR
1CB5; C; 10F5; # GEORGIAN MTAVRULI CAPITAL LETTER HOE
1CB6; C; 10F6; # GEORGIAN MTAVRULI CAPITAL LETTER FI
1CB7; C; 10F7; # GEORGIAN MTAVRULI CAPITAL LETTER YN
1CB8; C; 10F8; # GEORGIAN MTAVRULI CAPITAL LETTER ELIFI
1CB9; C; 10F9; # GEORGIAN MTAVRULI CAPITAL LETTER TURNED GAN
1CBA; C; 10FA; # GEORGIAN MTAVRULI CAPITAL LETTER AIN
1CBD; C; 10FD; # GEORGIAN MTAVRULI CAPITAL LETTER AEN
1CBE; C; 10FE; # GEORGIAN MTAVRULI CAPITAL LETTER HARD SIGN
1CBF; C; 10FF; # GEORGIAN MTAVRULI CAPITAL LETTER LABIAL SIGN

**Comment by jfkthame** [comment]
> What does Firefox do with Georgian capital letters if there is no font at all for them?

The same as it does for any other character for which no font can be found: it displays a "hexbox" (a box containing the character code in tiny hex digits).

(For CSS text-transform:uppercase, I am proposing that we should patch it to omit the Georgian uppercase mappings for the time being. However, even assuming we do that to address the text-transform case, if the Mtravuli characters are present in the content -- rather than resulting from a CSS transform -- they'd still display as hexboxes in the absence of a font.)

**Comment by jungshik** [comment]
> if the Mtravuli characters are present in the content -- rather than resulting from a CSS transform -- they'd still display as hexboxes in the absence of a font.)

For the time being, the vast majority of web pages with this issue will suffer from it because it uses CSS transform for on-the-fly uppercasing. In [the Chrome bug](http://crbug.com/865427) above, that's why I initially made it only about disabling uppercasing for Georgian. (actually, I didn't change the summary line, yet although I mention other alternatives).

**Comment by jfkthame** [comment]
> For the time being, the vast majority of web pages with this issue will suffer from it because it uses CSS transform for on-the-fly uppercasing

Agreed -- that was my assumption too, and the reason for proposing a Firefox patch to just address that specific use-case.

**Comment by khaledhosny** [comment]
> Ideally, HarfBuzz would do this fallback only if there is no glyph even in the fallback fonts. As soon as a real font has glyphs for these characters, the hack would become a harmless no-op.

Which is why HarfBuzz is too low-level for such a fallback; HarfBuzz does not handle font fallback at all and has no access of such information as font fallback list and their character coverage.
