### ISSUE TITLE
Improper shaping for Sea languages with MN fonts

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1112]
<img width="1680" alt="git112" src="https://user-images.githubusercontent.com/38288804/43248236-db2a12b6-90d4-11e8-9e71-b606e7ab085a.png">

**Comment by olivierberten** [comment]
How is this related to Harfbuzz? Is Adobe Photoshop CC 2018 using Harfbuzz?

That said, the MN fonts are AAT only, which isn't yet supported by Harfbuzz.

**Comment by behdad** [comment]
Will be fixed when we finish implementing morx: https://github.com/harfbuzz/harfbuzz/issues/322

**Comment by behdad** [comment]
> How is this related to Harfbuzz? Is Adobe Photoshop CC 2018 using Harfbuzz?

Yes, that's in the works.
