### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Jens1278** [harfbuzz/harfbuzz#1117]
The reference counting in harfbuzz has several bugs and causes memory leaks. Many functions increment the reference count of an object but they do never decrement it! For example, hb_buffer_set_unicode_funcs() tries to delete the current unicode funcs object, but the reference count is already 2 and this prevents it from deletion. The same applies to all function objects.

It is not documented how the reference count of most objects should ever get zero.

I think it would be best to fully remove the reference counting since a buggy implementation causes just memory leaks and the current implemtation is more than buggy!

PLEASE USE A MEMORY DEBUGGER! You get it for free in Visual Studio, have a look at _CRTDBG_MAP_ALLOC, for example.

It would also be nice if you wouldn't call functions like malloc, calloc, realloc, and free in your code. These function calls should be replaced with macros or C functions which can be redefined in a config file, for example.

Overriding these functions, as you do in hb-private.hh, with macros is really badest practice.

BTW - A function call like hb_atomic_ptr_get() on a static variable is useless. This makes your code not thread-safe. It wastes just a bit processing time, that's all.

**Comment by behdad** [comment]
Sorry to disappoint, but none of what you said is correct. Our reference counting and memory routines are just fine. :)
