### ISSUE TITLE
Calling convention on Windows

### ISSUE THREAD

**Issue by Jens1278** [harfbuzz/harfbuzz#1118]
The calling convention cannot be changed to something else than __cdecl because the calling conventions of all callback functions wich are passed to qsort, for example, are not defined and therefore inherited from the project settings.

On Windows we use usually __stdcall since programming languages like VB 6, for example, depend on it.

**Comment by behdad** [comment]
Can you list all the places? I assume you're getting compiler errors?  I can fix (though it's ugly).

**Comment by HinTak** [comment]
Is this really an issue about calling convention, or rather than winX harfbuzz does not work correctly?

**Comment by Jens1278** [comment]
Is this really an issue about calling convention, or rather that win32/win64 harfbuzz does not work correctly?

If you don't know what a calling convention is then please google it. And yes, it is a big issue since one must change a lot of code to get the library compiled with standard call, for example.

 

Don't you think that it makes sense to compile the library at least one time by yourself on Windows? BTW - The community edition of Visual Studio is free of charge and it offers anything you need to develop stable and professional code.

 

Maybe you enable also the memory debugger so that you can see all the memory leaks in your library. Have a look at _CRTDBG_MAP_ALLOC to determine how the memory debugger can be used.

 

Using something like atexit() is bad practice too. BTW - My version of Harbuzz crashes if HB_USE_ATEXIT is defined!

 

A library that must allocate global data should contain functions like hb_init_library() and hb_free_library(). In these functions you can allocate and deallocate global data if you really need some.

 

However, the best global data is no global data!

 

Maybe you solve then also all the warnings that your code produces in Visual Studio and other compilers.

 

In addition, your code looks like C but it is C++. The extension of a C++ file should be cpp, and the extension of a header should be h.

 

These are no requirements but something like this makes your code more professional and produces less problems.

 

At this time I have stopped to work with Harbuzz since it contains too many critical bugs like memory leaks and there is no working example that produces correct results with text that contains Unicode control characters like PDF, LRE, RLE, and so on.

 

It would be nice to have an example like icu62/source/samples/layout that can be complied out of the box with Harfbuzz. It would also be nice to have somewhere hints why Unicode control characters are not handled and how to get them working.

 

I have attached a very simple Arabic test file that produces identical results with Notepad, MS Word, or BapelPad on Windows, and with TextEdit and most other apps on Mac OS X.

 

The only application that produces a different result is ICU with Harfbuzz. Ok, an older layout example of ICU 57 produces incorrect results too but it contains no memory leaks.

 

Greetings

 

Jens

**Comment by HinTak** [comment]
Hmm, Harfbuzz is not "my library" - I just came across this issue, as a harfbuzz user (not really directly, but indirectly via FreeType) trying to look for an answer for a win64-only crash - I.e. not Linux , not mac, and not win32 - I am experiencing.

Nevermind.

**Comment by behdad** [comment]
HarfBuzz is used on *billions* of devices, thanks to Android, Chrome, and Firefox, among others.  If it doesn't work for you, sorry, but not my problem.

If you have specific suggestions on how to improve calling convention, I like to hear.  Otherwise, not interested in your wisdom.  If our atexit() use crashes, needs to be debugged and figured out. Not badmouth.

**Comment by Jens1278** [comment]
HarfBuzz is used on billions of devices, thanks to Android, Chrome, and Firefox, among others.

 

Do you really mean that when billions of users work with a memory leaking library that there is no more a requirement to fix this?

 

If a web browser uses a leaking library then this is not so critical since you can simply restart the browser but server based software cannot be simply restarted. Memory leaks are fatal in such an environment.

 

If you have specific suggestions on how to improve calling convention, I like to hear.

 

I can send you the changed sources but you must be able to compile the library on Windows. Otherwise I don't want to waste more time on this.

**Comment by behdad** [comment]
HarfBuzz doesn't leak, when used correctly.  If you don't want to send changes, let me know and I'll close this issue.  Thanks.

**Comment by Jens1278** [comment]
>HarfBuzz doesn't leak, when used correctly.

 

Ok, simply call hb_buffer_set_language() and you get a memory leak. How to free the previous language tag that was created with hb_buffer_create()? hb_buffer_destroy() does not free that memory.

 

There are a few more leaks. They are all small, just a few bytes. I have already removed Harfbuzz from my code and I don't remember where the other leaks are. I hadn't define HB_USE_ATEXIT at my first tests, so, I saw too many leaks since there is no documentation that states that HB_USE_ATEXIT must be defined. Anyway, my version crashed if it was defined.

 

However, I've attached the sources which I changed. My version was from July 3, but it should be no big deal to copy the changes into the current version.

 

BTW - I would really love to use your library, but the memory leaks and atexit() are show stopper.

**Comment by behdad** [comment]
Attachment didn't come through...

What you see is not leaks.  A memory leak is what the code accidentally loses track of.  In our case it's not.  It's just memory held in global variables.  You, typically, do NOT need to worry about that.  It wouldn't get worse over time (unlike real leaks).  The atexit() calls are indeed there to clean those up, so you don't see "leaks" in a memory profiler.  Even without it, memory profiles like valgrind (and I'm sure others) distinguish between leaks ("definitely lost" in valgrind terms), and memory "still reachable".

**Comment by Jens1278** [comment]
>Attachment didn't come through...

How can I send it? It was a zip file.

 

>A memory leak is what the code accidentally loses track of. In our case it's not. It's just memory held in global variables. 

 

What I described with hb_buffer_set_language() is a memory leak so far I can see. BTW - hb_buffer_set_unicode_funcs() caused a leak too in my tests.

 

>It's just memory held in global variables.

 

This makes no difference for me. It is bad practice, dot. The memory debugger of Visual Studio, including my own debugger, pops up with memory leaks every time if Harfbuzz is involved.

 

So, just add functions like hb_init_library() and hb_free_library() and everything is fine, forever.

 

I still think that it would be better to avoid the usage of global variables at all but if this is not possible then please add initialization and de-initialization functions. This concept is proven and works without side effects since computers exist.

**Comment by behdad** [comment]
> Attachment didn't come through...
> How can I send it? It was a zip file.

You can open the issue in your browser and attach the zip file.

**Comment by behdad** [comment]
>  So, just add functions like hb_init_library() and hb_free_library() and everything is fine, forever. I still think that it would be better to avoid the usage of global variables at all but if this is not possible then please add initialization and de-initialization functions. This concept is proven and works without side effects since computers exist.

Except that it doesn't, when you have multiple libraries and application code, need to initialize and finalize the same library.

**Comment by Jens1278** [comment]
>Except that it doesn't, when you have multiple libraries and application code, need to initialize and finalize the same library.

Then would most libraries not work, including FreeType where your project is coming from, or not?

 

Sorry, but this is not true.

**Comment by behdad** [comment]
I have my opinions and don't need to convince you.  Hope you find way to use HarfBuzz for your needs.
