### ISSUE TITLE
[merge] "Merge" hinting if all fonts have same hinting data

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1125]
Currently we drop hinting from all but first font.  If all input fonts have the same fpgm/prep/cvt tables then it's trivial to merge.  We should do.  That makes it easier for font engineers to make multiple subsets of the same big font and merge them...

**Comment by anthrotype** [comment]
does harfbuzz also have a merge tool now? Or was this meant for the fonttools repo?

**Comment by behdad** [comment]
Err. Wrong repo indeed. :)

**Comment by behdad** [comment]
https://github.com/fonttools/fonttools/issues/1305
