### ISSUE TITLE
Devanagari: Myraid Devanagari font (Below base R not functioning properly with Ta)

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1126]
![capture](https://user-images.githubusercontent.com/38288804/43640922-67001e14-973f-11e8-9205-9f08135bb0e1.PNG)
Observe the difference in shaping with Harfbuzz and Lipika in the attached image.

**Comment by Amritasingh0512** [comment]
[MDev.zip](https://github.com/harfbuzz/harfbuzz/files/2257330/MDev.zip)

**Comment by behdad** [comment]
What is Lipika, and why should we care about it?  Report a bug if HarfBuzz result is different from Windows.

**Comment by behdad** [comment]
cc @cjchapman

**Comment by cjchapman** [comment]
The text is "मात्राएँ" and Windows 10 renders it the same as HarfBuzz when using the attached Myriad Devanagari font:
![screen shot 2018-08-03 at 12 05 28 pm](https://user-images.githubusercontent.com/17747678/43661034-94479f02-9715-11e8-8faa-405c2d0de37c.png)

**Comment by Amritasingh0512** [comment]
Yes, Harfbuzz is in synch with windows but this is not the best shaping for this particular word it seems. Lipika is yet another complex shaping engine which is providing another possible shape for this sequence.

**Comment by behdad** [comment]
What your language expert things does not matter. No one design gonna against a shaping Engineer no one heard of it expect HarfBuzz or Adobe products to be consistent with it.  They do however expect fonts to render the same way that they do on other windows applications and browsers.

**Comment by cjchapman** [comment]
@behdad I agree that this is a font issue, not a shaper issue. I'll work with @Amritasingh0512 and the Adobe Type team to sort it out.
