### ISSUE TITLE
Latest build causes issues with Firefox, Chromium, and LibreOffice

### ISSUE THREAD

**Issue by davisdude** [harfbuzz/harfbuzz#1128]
Output of `uname -a`:

    Linux archlinux 4.17.12-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 3 07:16:41 UTC 2018 x86_64 GNU/Linux

I believe the issue may be related to some interaction between harfbuzz and GTK3, as Firefox, Chromium, and LibreOffice all have GTK3 as a common dependency. 

---

Certain websites would not render properly (as in cause the browser to go to an error-reporting page saying that the page cannot be loaded) using the latest version of harfbuzz. This error was encountered in both Firefox and Chromium. Some of the websites which didn't work:

* [old.reddit.com](old.reddit.com) (though not new reddit)

* [gmail.com](gmail.com)

* [https://wiki.documentfoundation.org/QA/Bugzilla/Components/Writer/Help](https://wiki.documentfoundation.org/QA/Bugzilla/Components/Writer/Help)

The following output is given from `journalctl -xe` with the PID of Firefox (though oddly enough, Chromium left no such traces)

    $ journalctl -xe
    -- The start-up result is RESULT.
    Aug 08 22:05:36 archlinux systemd-coredump[1131]: Process 901 (Web Content) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 901:
                                                      #0  0x00007f3adeb39b5f raise (libc.so.6)
                                                      #1  0x00007f3adeb24452 abort (libc.so.6)
                                                      #2  0x00007f3adeb24328 __assert_fail_base.cold.0 (libc.so.6)
                                                      #3  0x00007f3adeb32176 __assert_fail (libc.so.6)
                                                      #4  0x00007f3ad82a60f4 n/a (libharfbuzz.so.0)
                                                      #5  0x00007f3ad82c76b8 n/a (libharfbuzz.so.0)
                                                      #6  0x00007f3ad82a3790 n/a (libharfbuzz.so.0)
                                                      #7  0x00007f3ad82a38ef hb_ot_layout_table_find_script (libharfbuzz.so.0)
                                                      #8  0x00007f3ad82a4c52 hb_ot_layout_collect_features (libharfbuzz.so.0)
                                                      #9  0x00007f3ad82a527d hb_ot_layout_collect_lookups (libharfbuzz.so.0)
                                                      #10 0x00007f3ad973c802 n/a (libfreetype.so.6)
                                                      #11 0x00007f3ad973cd4d n/a (libfreetype.so.6)
                                                      #12 0x00007f3ad973d649 n/a (libfreetype.so.6)
                                                      #13 0x00007f3ad96ef818 FT_Load_Glyph (libfreetype.so.6)
                                                      #14 0x00007f3ad30e3ffe n/a (libxul.so)

---

For libreoffice, the error occurred in both of the latest versions (5.4.7 and 6.0.6). The error occurred when trying to change the language ("Tools" > "Options" > "Language Settings" > "Languages"). The output message was 

    soffice.bin: hb-machinery-private.hh:642: void hb_lazy_loader_t<WheresFace, Subclass, Returned, Stored>::set_stored(Stored*) [with unsigned int WheresFace = 1; Subclass = hb_table_lazy_loader_t<1, OT::GDEF>; Returned = OT::GDEF; Stored = hb_blob_t]: Assertion `instance == nullptr' failed.

---

After rolling back to the previous version of harfbuzz (1.8.5), all of the above errors went away.

**Comment by behdad** [comment]
Yeah sorry about that.  Fixed: https://github.com/harfbuzz/harfbuzz/commit/883957688cc4aa4335e5131a60b3ac3b53290726

I'm making a release now.
