### ISSUE TITLE
handling _ in feature tags

### ISSUE THREAD

**Issue by mhosken** [harfbuzz/harfbuzz#1130]
Currently harfbuzz will not parse a feature which contains _ in its id. This isn't a problem with OT because there are no registered features with _ in the id. But it is a problem for a number of published fonts that use _ in graphite features.

Any chance the ISALNUM(**pp) could be relaxed to include (ISALNUM(**pp) || **pp == "_") in hb_common.cc in parse_tag()?

**Comment by behdad** [comment]
I'm fine with that.  Send a PR.

**Comment by khaledhosny** [comment]
PR was merged.
