### ISSUE TITLE
hb-machinery-private.hh kills thunderbird and firefox

### ISSUE THREAD

**Issue by Oozenthor** [harfbuzz/harfbuzz#1133]
Some emails I receive and some web pages cause thunderbird and firefox to crash with the following messages dumped:

thunderbird: hb-machinery-private.hh:642: void hb_lazy_loader_t<WheresFace, Subclass, Returned, Stored>::set_stored(Stored*) [with unsigned int WheresFace = 1; Subclass = hb_table_lazy_loader_t<1, OT::GDEF>; Returned = OT::GDEF; Stored = hb_blob_t]: Assertion `instance == nullptr' failed.
Aborted (core dumped)

firefox: hb-machinery-private.hh:642: void hb_lazy_loader_t<WheresFace, Subclass, Returned, Stored>::set_stored(Stored*) [with unsigned int WheresFace = 1; Subclass = hb_table_lazy_loader_t<1, OT::GDEF>; Returned = OT::GDEF; Stored = hb_blob_t]: Assertion `instance == nullptr' failed.

Any idea what is causing this?

**Comment by jfkthame** [comment]
This was a bug in the recent 1.8.6 release, and is fixed in 1.8.7.

**Comment by jfkthame** [comment]
See #1128.
