### ISSUE TITLE
Shaping not supported on some Apple-based fonts

### ISSUE THREAD

**Issue by ubitux** [harfbuzz/harfbuzz#1150]
For some reason, shaping doesn't seem to be supported with some fonts:

```
% hb-shape /tmp/emojione-android.ttf '🇫🇷'
[gid1349=0+2400]
% hb-shape /tmp/emojione-apple.ttf '🇫🇷'
[u1F1EB=0+800|u1F1F7=1+800]
```

Font from: https://github.com/emojione/emojione/tree/master/extras/fonts

The issue is also reproducible with `/System/Library/Fonts/Apple Color Emoji.ttf` available on Apple systems.

Tested with harfbuzz 1.8.8 on a Linux system.

**Comment by khaledhosny** [comment]
Shaping [AAT](https://en.wikipedia.org/wiki/Apple_Advanced_Typography) fonts is supported only on macOS right now since it HarfBuzz offloads this shaping Core Text libraries. We will have native AAT support at some point in the future, see https://github.com/harfbuzz/harfbuzz/projects/2
