### ISSUE TITLE
dist/kern and cursive attachment

### ISSUE THREAD

**Issue by punchcutter** [harfbuzz/harfbuzz#1152]
For Noto Music we have cursive attachment to join parts like shown here: https://github.com/harfbuzz/harfbuzz/issues/1103

Cursive attachment works in these situations, but if we try to apply dist or kern the x advance on the first glyph gets reset by the cursive attachment. 

From hb-ot-layout-gpos-table.hh the current code is 

```
    switch (c->direction) {
      case HB_DIRECTION_LTR:
	pos[i].x_advance = round (exit_x) + pos[i].x_offset;
	d = round (entry_x) + pos[j].x_offset;
	pos[j].x_advance -= d;
	pos[j].x_offset  -= d;
	break;
```
This resets the x_advance on the first glyph which could have been increased with dist or kern before applying cursive attachment. In this case we add width to allow for following dots that are attached on the right with mark to base. Since the x_advance is reset we get overlapping. 
![music_dist_bad](https://user-images.githubusercontent.com/11257204/45200057-e166a480-b223-11e8-8dff-27cfae3e3e09.png)
And my quick hack to make it work as we expect

```
    switch (c->direction) {
      case HB_DIRECTION_LTR:
        unsigned int z;
        unsigned int q;
	z = round (exit_x) + pos[i].x_offset;
	if (pos[i].x_advance > z) {
	  q = pos[i].x_advance - z;
	};

	d = round (entry_x) + pos[j].x_offset;
	q += d;
	pos[j].x_advance -= d;
	pos[j].x_offset  -= q;
	break;

```

![music_dist_good](https://user-images.githubusercontent.com/11257204/45199838-afa10e00-b222-11e8-8d9e-7895f23d546c.png)

With this change one test fails, but that one looks off to me in the first place. It's the Noto Newa test in use.tests (last one in there). Before looking at that any further, though, what do you think about all this @behdad ?

**Comment by punchcutter** [comment]
Argh, nevermind. Bug in the font code meant we were applying dist to the first glyph, not the second. That makes no sense unless the second glyph were a non-spacing mark, but then using cursive attachment also doesn't make much sense in that situation.

**Comment by behdad** [comment]
Exactly.  Changing advance width of first glyph is what cursive attachment does indeed.
