### ISSUE TITLE
Status of win64 harfbuzz , and 64-bit uniscribe.

### ISSUE THREAD

**Issue by HinTak** [harfbuzz/harfbuzz#1157]
I finally got round to spend a few days looking at a rather old bug in win64 FontVal ( https://github.com/HinTak/Font-Validator/issues/27 ) . It turns out the FreeType backend crashed when calling `hb_ft_font_create` in the autofit module. I probably will have to dive into harfbuzz myself, but meanwhile, it would be useful to know:

- the status of win64 harfbuzz

- update the wine README for 64-bit wine and 64-bit uniscribe, since 64-bit windows is rather the norm now.

**Comment by behdad** [comment]
> the status of win64 harfbuzz

I don't know.  "It should work" it is unless suggested otherwise.

> update the wine README for 64-bit wine and 64-bit uniscribe, since 64-bit windows is rather the norm now.

I haven't been able to get mingw64 to work for me.  Feel free to submit instructions.

**Comment by HinTak** [comment]
Well, fedora ships mingw64 harfbuzz. I tried building the FontVal FreeType backend without harfbuzz and the win64-only crash went away. It came back again when built against win64 harfbuzz 1.8.8 (most recent on fedora rawhide). So it is definitely a win64 harfbuzz problem of some sort.

I also tried 1.7.6 and hitted the linker problem and cannot get a build.

64-bit wine is actually quite neat

**Comment by behdad** [comment]
We have both `mingw32.sh` and `mingw64.sh` in the tree.  Running the 64 version now, it compiles fine for me.  I'm not sure what is left here for me to do.

**Comment by HinTak** [comment]
64-bit wine instructions.

**Comment by HinTak** [comment]
I think regarding the first part, I was inquiring about the testsuite status. There seems to be some sort of testsuite but it is not entirely clear how to run it.

**Comment by HinTak** [comment]
I have updated the wine readme with 64-bit wine, but somewhere specific to fedora (and what fedora ships) at https://github.com/HinTak/harfbuzz/tree/fedora%2B64bit-wine . It is a substantial rewrite and I don't think you want to pull as is. But I don't really want to merge with your current info as I don't like a few part of it (hence the rewrite and removal of a few items).

Anyway, my branch will stay and you can keep an eye out for reference.

**Comment by khaledhosny** [comment]
Or keep it open until we fix the instructions.

**Comment by ebraminio** [comment]
As mingw built version of libraries aren't publicly available for every distrobution, we can't provide a clean solution for other and README.wine.md is more for testing than instructing packagers so I believe we can close this but will accept PRs related to it of course.

**Comment by HinTak** [comment]
Okay - but I think the 64-bit version of uniscribe is what you should compare against, and therefore 64-bit wine, etc.

My fedora+64-bit-wine branch will stay indefinitely  , with those variant build scripts and readme.wine. They are for my own reference and you are welcomed to copy/adapt bits as you see fit, but I do not intend to include every instructions for every combination etc - they are my notes and I intend to keep them small.

**Comment by HinTak** [comment]
On Friday, 19 October 2018, 14:16:02 GMT+8, Ebrahim Byagowi <notifications@github.com> wrote:
 
> As mingw built version of libraries aren't publicly available for every distribution...

Actually you can... You can download the individual packages from the distribution directories, or fedora's build farm (koji.feforaproject.org). There is a pure /standalone version of rpm2cpio (in perl or python I forgot) that can unpack rpms. You will end up with something a bit more up to date than those Behdad provides - that's one reason I decide not to use Behdad's: the bulk of it was from 2012 or thereabouts.

It is probably worth you doing this once in a while.

**Comment by ebraminio** [comment]
> but I think the 64-bit version of uniscribe is what you should compare against

Is there any functional difference do you believe?

> that's one reason I decide not to use Behdad's:

You are right. We only use however only Uniscribe backend of harfbuzz on testing so that can't have much difference I believe.

**Comment by HinTak** [comment]
I don't believe that Microsoft would **intentionally** make 64-bit uniscribe behaves differently from 32-bit uniscribe. But this sort of problem is not unheard of; and also wine is not windows and will never be windows, despite 2+ decades of excellent work. Only windows is windows. You might as well use something that's closer to the "norm", whatever the norm is. Even for 32-bit wine, I worry that the underlying freetype based rendering may behave differently from real windows in subtle ways, and thus any tests of 32-bit uniscribe under wine invalid.

**Comment by ebraminio** [comment]
Uniscribe backend is not used that seriously on daily HarfBuzz development :) and just used to get a clue on what can be more corrrect when specs are not clear. @jfkthame does automatic testing but that uses an actual Windows AFAIK and that can be adopted with x64 if not already. What is even better to test against is DirectWrite which behaves differently and on a case I had experience with, incorrectly, but maybe improved on other places, not supported at all on Wine so something that just work is enough I believe.

**Comment by ebraminio** [comment]
> a case I had experience with, incorrectly

The case was reproducible with Edge also
