### ISSUE TITLE
Zawgyi-One rendering broken

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1162]
Eg. font from http://unobusa.org/2009/11/12/zawgyi-font-and-firefox-browser/
Text sequence: "\u1000\u103A\u1004\u1037\u1039\u1041" for zawgyi

![image](https://user-images.githubusercontent.com/142891/45551326-c8ff1700-b82d-11e8-8ca0-c1c2f221c370.png)

The problem is, Zawgyi uses some gen_cat=Mn chars as non-spacing.  The font does NOT have a GPOS table, so we invoke fallback mark positioning, which is not desired.

**Comment by behdad** [comment]
I wonder if we can detect this font (by size of it's GDEF etc) and disable fallback positioning...

**Comment by behdad** [comment]
@jfkthame any ideas?

**Comment by nona-google** [comment]
Just FYI, Android will use private script code for Zawgyi and we are passing language code to HarfBuzz.
You may be able to use that hint for detecting Zawgyi font.

**Comment by behdad** [comment]
> Just FYI, Android will use private script code for Zawgyi and we are passing language code to HarfBuzz.
> You may be able to use that hint for detecting Zawgyi font.

That actually helps.  What script and language codes will you be passing?  Script is enough for us to disable all kinds of processing.

**Comment by nona-google** [comment]
The new script code for Zawgyi will be "Qaag".
Currently this is in draft of UTS35.
http://unicode.org/repos/cldr/trunk/specs/ldml/tr35.html#unicode_script_subtag_validity

Once it is released, that should be written in here
http://www.unicode.org/reports/tr35/tr35.html#unicode_script_subtag_validity

**Comment by behdad** [comment]
I just meant whether to expose `HB_SCRIPT_MYANMAR_ZAWGYI`.  Application can still create a `hb_script_t` tag without me exposing it.  Indeed, for example, using hb-icu, or other bridges, it will go in automagically.

**Comment by behdad** [comment]
I'm worried that opening that can of worms will give legitimacy to encoding other pseudo- or non-Unicode- scripts.

**Comment by jfkthame** [comment]
Ah, OK. Yes, I don't think we need an `HB_SCRIPT_` constant for this.

**Comment by behdad** [comment]
@nona-google Do you know what the language tag would be?

**Comment by nona-google** [comment]
Not yet decided in Android. Either en-Qaag-MM or my-Qaag-MM could be sent to HarfBuzz. The thing we can tell now is "Qaag" should be there if the text should be rendered in Zawgyi encoding.

**Comment by behdad** [comment]
Okay.  As it happens, we don't care about the language tag.  This should be fixed as far as I'm concerned.

**Comment by andjc** [comment]
@nona-Google would use of Qaag for Zawgyi mean we have to add script tags for each of the major psuedo-Unicode myanmar script fonts out there? Or would my-Qaag specifically imply Zawgyi and other language tags would imply other pseudo Unicode fonts for Myanmar script?

**Comment by khaledhosny** [comment]
From cursory look in the code, I guess one can use the tag for any pseudo encoding, as all it does is disabling any-script specific shaping, in addition to zeroing mark advances and fallback positioning, so that pretty much applied to any such pseudo encoding.

**Comment by yuanzhenxia** [comment]
> I wonder if we can detect this font (by size of it's GDEF etc) and disable fallback positioning...
I have a method i think it cau be use to detect the font which is unicode or zawgyi.
In zawgyi  the font is not contain \u1022 and \u1028
If the font contain \u1021 but not \u1022, it is a zawgyi font.
