### ISSUE TITLE
Add bots with address- and thread-sanitizer

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1168]
This is how ICU is doing it:

https://github.com/unicode-org/icu/blob/master/.travis.yml#L33

**Comment by behdad** [comment]
Continuing here.
For address-sanitizer, maybe add some flags.  From https://clang.llvm.org/docs/AddressSanitizer.html maybe "-O1 -g -fsanitize=address -fno-omit-frame-pointer"

For thread-sanitizer to have any use, we need to add multi-threaded test, and then just run that one with thread-sanitizer.

Also useful is undefined-behavior sanitizer, and memory sanitizer. Unfortunately doesn't seem like they can be combined...  But one bot should be fine.

**Comment by behdad** [comment]
Also, how did you read the reports?  I don't see any symbols.  Check this: https://clang.llvm.org/docs/AddressSanitizer.html#symbolizing-the-reports

**Comment by behdad** [comment]
Also these?

Use-after-return (runtime flag ASAN_OPTIONS=detect_stack_use_after_return=1)
Use-after-scope (clang flag -fsanitize-address-use-after-scope)

**Comment by behdad** [comment]
(I used asan_symbolize.)

**Comment by behdad** [comment]
Oh, I just saw that you added msan, etc as well.

**Comment by ebraminio** [comment]
'-O1 -g -fsanitize=address -fno-omit-frame-pointer' it was making symbol exporting test to fail

**Comment by ebraminio** [comment]
> Also these?

Default enabled AFAIK.

> (I used asan_symbolize.)

Let me know exact build environment you have used locally and I will put that on the bot.

**Comment by ebraminio** [comment]
Ok, lets close this.
