### ISSUE TITLE
leak of post table?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1171]
Trying to make #1169 happen,

If I apply this, hb-shape's leak (on asan) will be resolved,

```diff
diff --git a/src/hb-ot-font.cc b/src/hb-ot-font.cc
index faacecb9..9a1c2e9d 100644
--- a/src/hb-ot-font.cc
+++ b/src/hb-ot-font.cc
@@ -160,8 +160,9 @@ hb_ot_get_glyph_name (hb_font_t *font HB_UNUSED,
                       char *name, unsigned int size,
                       void *user_data HB_UNUSED)
 {
-  const hb_ot_face_data_t *ot_face = (const hb_ot_face_data_t *) font_data;
-  return ot_face->post->get_glyph_name (glyph, name, size);
+  // const hb_ot_face_data_t *ot_face = (const hb_ot_face_data_t *) font_data;
+  // return ot_face->post->get_glyph_name (glyph, name, size);
+  return false;
 }
```

Apparently post's fini is not called

![image](https://user-images.githubusercontent.com/833473/45918993-fc7c1a00-be9b-11e8-8e14-9f39c9d44ccc.png)

Any hint?

**Comment by behdad** [comment]
I think your printf didn't print because it had no newline and process was killed before it flushed.  fini() was being called.  Just that it was not freeing blob.
