### ISSUE TITLE
Write a multi-threaded test

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1173]
From https://github.com/harfbuzz/harfbuzz/issues/1168#issuecomment-423852823:

> For thread-sanitizer to have any use, we need to add multi-threaded test, and then just run that one with thread-sanitizer.

It will be fun.

**Comment by behdad** [comment]
Can be an additional test runner that just hb_shape()'s text in multiple threads.  Ten for example.  See Pango's for example:

  https://gitlab.gnome.org/GNOME/pango/blob/master/tests/test-pangocairo-threads.c

We can either use pthread directly, or use glib's.

We can then just feed this the existing shaping tests.

**Comment by khaledhosny** [comment]
Or may be an option for `hb-shape` to run multiple threads (similar too `--num-iterations`), so that it integrates nicely with the existing test framework. It can even check and env variable, to make things dead simple.

**Comment by behdad** [comment]
That was my other thought.  hb-shape internals use global variables though so there's some minor cleanup needed.

**Comment by behdad** [comment]
Thinking more, I think adding that complexity into hb-shape is overkill.  We just need to port the pango test to hb.  Just take font file and text and num-threads / num-iters....  Probably check that results are all the same as well.
