### ISSUE TITLE
Badges for individual bots?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1177]
I wish we could see on project's front page exactly which bots are passing... ideally also mark something like msan currently as expected-fail, so we still get it build and see the errors...  Feel free to close. Just wishlisting.

**Comment by ebraminio** [comment]
I don't see much configuration available for the badges, https://circleci.com/gh/harfbuzz/harfbuzz/edit#badges sorry, maybe if we migrate them to Travis.
