### ISSUE TITLE
Sinhala differences in rendering with Edge - Windows 10

### ISSUE THREAD

**Issue by JelleBosmaMT** [harfbuzz/harfbuzz#1182]
The sequence Ra + Virama + ZWJ is used to create the reph form. Virama + ZWJ + Ra is for the below base form of Ra and Virama + ZWJ + Ya the post base Ya. This creates an ambiguity for Ra + Virama + ZWJ + (Ra or Ya).

I am not sure whether Ya-Reph or Ra-Yapost is preferable. It seems Ya-Reph is OK. Ra-RaBelow doesn't happen because shapers seem to prefer the reph form. But the Noto fonts are set up to prevent Ra-Reph.  For Windows this works with a "pres" lookup that splits the Reph into Virama + Ra, when it follows Ra. Proofing combinations with reph look like this in Edge on Windows 10:

![image](https://user-images.githubusercontent.com/12729011/46067541-5b30e480-c177-11e8-99d9-1e96acc31cd1.png)

And like this in Chrome on Mac:

![image](https://user-images.githubusercontent.com/12729011/46067826-093c8e80-c178-11e8-9d14-2078dd99e82e.png)

Harfbuzz orders the Reph after Virama and vowel signs, rather than after the consonants. Also note the difference in the first word where there is consonant + Virama + ZWJ + Ra + Virama + ZWJ + Ra. Harfbuzz inserts two below base Ra's and Windows must given precedence to making a Reph instead (which is split up).

When I add a lookup to the akhn feature that removes the ZWJ between two Ra's then Edge gives me this:

![image](https://user-images.githubusercontent.com/12729011/46069177-3a6a8e00-c17b-11e8-9c74-2412910d4867.png)

The first word "ස්ථ්‍ර්‍රවම" now uses a subscript for the first of the two Ra's. Not sure if that is an improvement or not. And the triple Ra no longer has a Reph floating in front, which is better.

For Chrome I get this:

![image](https://user-images.githubusercontent.com/12729011/46069531-06439d00-c17c-11e8-90d9-5d9f1d15f949.png)

This is an improvement from the point of view of preventing overlaps. But when there are split-vowels, something must be between the Ra's when the akhn lookup is applied. And then the fix doesn't work.

When there is a Reph and a post base Ya the Reph is attached to the base consonant, unless the base is the Ya itself. Then it is attached to the post form. Windows seems to put the Reph after the Yapost, and it is reordered by a lookup. (Which doesn't work when there is a below base Ra too, but I am not worried about that.)

**Comment by behdad** [comment]
@JelleBosmaMT please paste the text used in the above tests.  Thanks.

**Comment by JelleBosmaMT** [comment]
ස්ථ්‍ර්‍රවම ර්‍ව්‍ය ර්‍ය්‍ය

ර්‍ර් ර්‍ර ර්‍රා ර්‍රැ ර්‍රෑ ර්‍රි ර්‍රී ර්‍රු ර්‍රූ ර්‍රෙ ර්‍රේ ර්‍රො ර්‍රෝ ර්‍රෘ ර්‍රෲ ර්‍රෟ ර්‍රෳ ර්‍රෛ ර්‍රෞ ර්‍ර්‍ර

ර්‍ය ර්‍යා ර්‍යැ ර්‍යෑ ර්‍යි ර්‍යී ර්‍යු ර්‍යූ ර්‍යෙ ර්‍යේ ර්‍යො යෝ ර්‍යෘ ර්‍යෲ ර්‍යෟ ර්‍යෳ ර්‍යෛ ර්‍යෞ ර්‍ය්‍ර

ර්‍ච් ර්‍ච ර්‍චා ර්‍චැ ර්‍චි ර්‍චී ර්‍චු ර්‍චූ ර්‍චෘ ර්‍චෙ ර්‍චේ ර්‍චෛ ර්‍චො ර්‍චං ර්‍චඃ

ර්‍ග්‍ය් ර්‍ග්‍ය ර්‍ග්‍යා ර්‍ග්‍යැ ර්‍ග්‍යෑ ර්‍ග්‍යි ර්‍ග්‍යී ර්‍ග්‍යු ර්‍ග්‍යූ ර්‍ග්‍යෙ ර්‍ග්‍යේ ර්‍ග්‍යො ර්‍ග්‍යෝ ර්‍ග්‍යෘ ර්‍ග්‍යෲ ර්‍ග්‍යෟ ර්‍ග්‍යෳ ර්‍ග්‍යෛ ර්‍ග්‍යෞ ර්‍ග්‍ය්‍ර

**Comment by behdad** [comment]
Anything that needs to be done here?

**Comment by dscorbett** [comment]
I think this is the same issue as #1044.
