### ISSUE TITLE
mingw bots unhappy again

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1185]
https://ci.appveyor.com/project/harfbuzz/harfbuzz/build/1.0.2257/job/c1tgyigp8hlroqy5

**Comment by ebraminio** [comment]
No idea and not having mingw locally, sorry.

**Comment by ebraminio** [comment]
Fixed, yay! https://github.com/harfbuzz/harfbuzz/commit/9be8062b4d241f02bb96df436e98f10f08bda4f8 https://github.com/harfbuzz/harfbuzz/commit/d4d261a97723b27fb9ad9a69b8dc7fd8c560a98b https://github.com/harfbuzz/harfbuzz/commit/d289d6381864649504abfb1196ac20a1d4664a4e
