### ISSUE TITLE
Documentation/modification of top/bottom margin in eps/pdf/svg hb-view output

### ISSUE THREAD

**Issue by HinTak** [harfbuzz/harfbuzz#1186]
The pixel-based output of hb-view (png and ansi) seems to have 16 as pixels in the margin and can be lowered by --margin. But the eps/pdf (I.e cairo) -based output, it is not exactly clear what 16 means, though I suppose it is in dpi units.

What's troubling is the space above and below - compared to ansi, perhaps?

**Comment by HinTak** [comment]
I think I have asked this question before, though I don't remember the answer :) . The font I am having a lot of head/bottom room is Lohit Devanagari , if that's important.

**Comment by HinTak** [comment]
I guess Lohit Devanagari has gigantic ascent/descent. Would be nice to have a "tight bounding" mode like the ansi one for the Cairo based outputs... Anyway, some of these info could go into the `--help-...` display messages.

**Comment by behdad** [comment]
This was previous discussion: https://github.com/harfbuzz/harfbuzz/issues/79
Feel free to submit PR for doc improvements.  Thanks.
