### ISSUE TITLE
[tsan] setlocale() is not threadsafe

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1191]
I don't see a threadsafe alternative.

**Comment by behdad** [comment]
Should replace with newlocale equivalent if available: https://stackoverflow.com/questions/4057319/is-setlocale-thread-safe-function

**Comment by behdad** [comment]
Using newlocale(), then I don't see a standard way how to access current locale name.  Looking at /usr/include/xlocale.h shows a hacky way though, by accessing locale->__names directly.

**Comment by ebraminio** [comment]
So, what should be done here? Reverting use of hb_buffer_guess_segment_properties on tsan? Below is my try

```diff
diff --git a/src/hb-common.cc b/src/hb-common.cc
index a9c62e80..d4f07f7e 100644
--- a/src/hb-common.cc
+++ b/src/hb-common.cc
@@ -358,6 +358,22 @@ hb_language_to_string (hb_language_t language)
   return language->s;
 }
 
+#ifdef HAVE_NEWLOCALE
+# include <langinfo.h>
+#endif
+
+static char *
+_safe_setlocale (int category, const char *locale)
+{
+#ifdef HAVE_NEWLOCALE
+  locale_t loc = newlocale (LC_CTYPE, nullptr, nullptr);
+  uselocale (loc);
+  freelocale (loc);
+#else
+  return setlocale (LC_CTYPE, nullptr);
+#endif
+}
+
 /**
  * hb_language_get_default:
  *
@@ -375,7 +391,7 @@ hb_language_get_default (void)
   hb_language_t language = default_language.get ();
   if (unlikely (language == HB_LANGUAGE_INVALID))
   {
-    language = hb_language_from_string (setlocale (LC_CTYPE, nullptr), -1);
+    language = hb_language_from_string (_safe_setlocale (LC_CTYPE, nullptr), -1);
     (void) default_language.cmpexch (HB_LANGUAGE_INVALID, language);
   }
 ````

**Comment by khaledhosny** [comment]
The `HAVE_NEWLOCALE` branch above does not return anything, so I’m not sure how would it work. I guess for the test we can explicitly set the language before calling `hb_buffer_guess_segment_properties()` and probably mark `hb_language_get_default()` in the documentation as being thread-unsafe if we can’t come up with a thread safe one. If I’m not mistaken, it is only a fallback function and shouldn’t normally be called.

**Comment by ebraminio** [comment]
> The HAVE_NEWLOCALE branch above does not return anything, so I’m not sure how would it work.

Because I don't know how :)

>  hb_buffer_guess_segment_properties() and probably mark hb_language_get_default()

Good idea :)

**Comment by ebraminio** [comment]
I think we can assume this resolved somehow and we just need to add a note on the document for it, what about

```diff
@@ -1500,6 +1500,10 @@ hb_buffer_reverse_clusters (hb_buffer_t *buffer)
  * hb_language_get_default().  This may change in the future by
  * taking buffer script into consideration when choosing a language.
  *
+ * Please note that this is not thread-safe in first call, call
+ * hb_language_get_default once somewhere safe before use and it will
+ * become thread-safe.
+ *
  * Since: 0.9.7
  **/
 void
```

```diff
--- a/src/hb-common.cc
+++ b/src/hb-common.cc
@@ -361,7 +361,8 @@ hb_language_to_string (hb_language_t language)
 /**
  * hb_language_get_default:
  *
- *
+ * It is not thread-safe in first call but call it once and it will become.
  *
  * Return value: (transfer none):
  *
```

If it make sense please apply it or send me its polished version. Thank

**Comment by behdad** [comment]
I like to fix the library than document random pitfalls.  But sure in this case.  I'll improve the wording.

**Comment by behdad** [comment]
Did you forget to push your change?
