### ISSUE TITLE
[morx] MORX-32: Insertion At Mark Without SetMark

### ISSUE THREAD

**Issue by brawer** [harfbuzz/harfbuzz#1195]
When processing a `morx` table, CoreText and HarfBuzz currently behave differently when inserting a glyph sequence at the current mark position and no mark has actually been set. Admittedly it’s a corner case, but you still might want to fix it. Compare these:

https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-32
https://rawgit.com/unicode-org/text-rendering-tests/master/reports/CoreText.html#MORX-32

**Comment by behdad** [comment]
Just fixed that a few minutes ago: https://github.com/harfbuzz/harfbuzz/issues/1195

**Comment by behdad** [comment]
Actually, the fix for this broke MORX-31 for me.  If, not setting mark is to be same as mark being set at index 0, why does one not get more insertions for the first test in MORX-31?  Ie. XXAYYAZZ should produce INSXXINSAYYAZZ.

**Comment by behdad** [comment]
I see CoreText has more problems.  But yeah, I think the correct expectation should be changed, now that we want (as per MORX-32) an unset mark to be considered at 0.  One way or another.  We cannot have both.  @nedley let me know which way you want to go.

**Comment by behdad** [comment]
@brawer Can we change test to current HarfBuzz behavior at least, until we agree with Apple on what to do?  I personally think assuming mark=0 is not useful, but I need to choose one way or another.  Other lookup assumes mark not set skipping mark action.  We can do that here, then MORX-33 needs to be changed.

**Comment by brawer** [comment]
Sounds good, will do. (Might take a few days, I’ll be mostly offline tomorrow).

**Comment by brawer** [comment]
Personally I’d agree that assuming a default of mark=0 is not useful. Changed MORX-32 in test suite.
