### ISSUE TITLE
--enable-introspection=yes alone (without gobject) does not work but does not tell you why

### ISSUE THREAD

**Issue by HinTak** [harfbuzz/harfbuzz#1202]
It is a bit confusing that `--enable-introspection=yes` has no effect until `--with-gobject` is added. So `--enable-introspection=auto` seems redundant, since that's basically what happens if `--with-gobjects` is on.

I would suggest `--enable-introspection=yes` (or even auto) should imply `--with-gobject`.

**Comment by behdad** [comment]
> So `--enable-introspection=auto` seems redundant

Sure, specifying "auto" when it's the default, is always redundant.

I'm hesitant to touch this.

**Comment by behdad** [comment]
Better documentation is welcome.

**Comment by HinTak** [comment]
My issue is that `--enable-introspection=yes` on its own has no effect - it should switch on gobject.

**Comment by behdad** [comment]
> My issue is that `--enable-introspection=yes` on its own has no effect - it should switch on gobject.

I think that should err if gobject is not enabled, and suggest enabling it, yes.

**Comment by HinTak** [comment]
Yes, that is better than the current behavior too.

**Comment by HinTak** [comment]
Yes, I should go back to explain: my failing this issue is that `--enable-introspection=yes` on its own, does not work and does not tell you what is the problem either. Either (1) auto-switch on gobject, or (2) fail visibly with a message saying gobject should be on too, are better than the current be behavior.

BTW, the sample.py could be moved to a more visible place - like a separate `py-gobject-examples` directory.

**Comment by HinTak** [comment]
Actually looking at the autoconf code, whatever you specify at `--enable-introspection=...` is ignored. At the moment decision is made entirely based on whether gobject is checked,  and introspection of recent enough version.

**Comment by behdad** [comment]
> whatever you specify at `--enable-introspection=...` is ignored

Nope.  That's checked by `GOBJECT_INTROSPECTION_CHECK`.

**Comment by HinTak** [comment]
Ok. I guess you want to change the false setting in the else clause to an abort/error message.

**Comment by HinTak** [comment]
Here is the 2nd approach (fail on introspection without gobject) - https://github.com/HinTak/harfbuzz/commit/b5d71c845f83177bc18d306bde48b27e07c1d9d7 - you might consider rewording the message. Please feel free to cherry-pick the commit with or without edits.

**Comment by khaledhosny** [comment]
I don’t think we will be changing autotools build significantly anymore. Please open an new issue if meson build does not address this.
