### ISSUE TITLE
[msan] Use newer glib

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1204]
From hb-glib.h:
```
#if GLIB_CHECK_VERSION(2,31,10) 
HB_EXTERN hb_blob_t * 
hb_glib_blob_create (GBytes *gbytes); 
#endif 
```

We install 2.28...  Why so old?  Just use newer and it should fix the check-symbols.sh failure.  You should then revert your hack.  Thanks.

**Comment by ebraminio** [comment]
> We install 2.28... Why so old?

Just copied a wrong version from top of a page, didn't know about their versioning, that helps fixing a lot of things also
