### ISSUE TITLE
Regression - d3e2a06b0f2587e913a9c3ff1a20c187f260db80 added gid3 at cluster zero

### ISSUE THREAD

**Issue by HinTak** [harfbuzz/harfbuzz#1208]
If you compare the result of hb-shape with the `src/sample.py` before and after this change:
https://github.com/harfbuzz/harfbuzz/commit/d3e2a06b0f2587e913a9c3ff1a20c187f260db80

You would notice that somehow a space is added at the beginning of the buffer, with the shaping result showing an extra item of gid3 on one side (depending on whether you are trying to shape Arabic or not)

**Comment by HinTak** [comment]
Noticed this issue trying to extent the python example in the direction of hb-shape/hb-view to address https://github.com/harfbuzz/harfbuzz/issues/79

**Comment by HinTak** [comment]
That may be the case, but should the shaping code treat BOM as a space character???

**Comment by khaledhosny** [comment]
That is how HarfBuzz handles default ignorable characters, the get converted to the glyph for space character and its width is set to zero.

**Comment by khaledhosny** [comment]
This way, they work and are invisible even if the font has no glyphs for them or the glyphs are not blank (which is the case for many fonts).

**Comment by HinTak** [comment]
That sounds a bit wrong. There are probably special language/usage where the space glyph is not inkless...

**Comment by anthrotype** [comment]
@HinTak if you're interested in python bindings for harfbuzz you may want to also have a look at https://github.com/trufont/uharfbuzz (shameless plug)

**Comment by HinTak** [comment]
I just thought of one such usage: in the era of color font, a space glyph might be of a plain block of colours. In that case, inserting a space with zero advance could be visible.

@anthrotype : thanks for that plug - I appreciate that. On my quick search I found the gobject inspection one and a project from the same guy who tries to rewrite pycairo in rather odd ways, and a few other projects of not very noticeable maturity. Mainly I am on the gobject introspection one (hence all the issues/pulls in that area) . Already rewritten a good part of hb-shape/hb-view-view in python. Though I'd be happier with ctype/cffi than gobject...

**Comment by anthrotype** [comment]
yeah i don't really understand gobject-introspection. The one I linked is wrapped with cython.

**Comment by HinTak** [comment]
Well, gobject is similar to ctype in that you write stub code telling python (or a non-C language) how to talk to a c-based library. The difference with gobject is that, the bits of "stub code" happens as functional comment blocks next to the c code on the c code's side, rather than on the python side. Those comments could set default parameter values for non-C languages, re-arrange arguments (e.g. The python routine receives multiple results as a list when the C code have output pointers to be filled in) and other tasks. 

So perhaps the oddity you notice is due to the fact that the foreign (non-c) interface is declared on the C side, and may not necessarily feel natural on the python side.

**Comment by anthrotype** [comment]
it's also not well supported on windows -- at least the last time I tried I couldn't make it work. In my cython bindings, I have cmake build a static harfbuzz library from source and embed that in the python extension module so it's self-contained. Anyway, we're digressing :)

**Comment by HinTak** [comment]
@khaledhosny : I assume you mean zero advance rather than zero width. The problem is you assume that space glyph is unmarked. Let's say you have a color font where the space glyph is a block of plain color. Harfbuzz insert a space for BOM. In Arabic layout, the BOM/space is rearrange to the right. Then you have a visible block of space-colour on the right to your Arabic phrase.

Why is harfbuzz not skipping BOM? That sounds more sensible.

**Comment by khaledhosny** [comment]
In case of BOM, the client should probably not pass it to HarfBuzz in the first place, so that is an edge case. For the general issue, IIUC, HarfBuzz never skips characters, any character in the input must be accounted for to have reliable mapping between output glyphs and input characters. But anyway, I’m just describing the cuurent HarfBuzz behavior, I neither designed it nor I’m the one you need to convince to change it (if it is ever going to happen).

**Comment by behdad** [comment]
I thought there's an issue for it.  Maybe it was just in the TODO for a while.  Anyway, open an issue for API to set "invisible-glyph-id".

**Comment by khaledhosny** [comment]
BTW, this is already an issue with fonts like https://fonts.google.com/specimen/Zilla+Slab+Highlight, but personally I consider such fonts to be a hack, and visible default ignorable characters is the least of their problems.

**Comment by HinTak** [comment]
This was meant to be that issue :-), to open. I could change the title, I guess.

Initially I noticed the issue comparing the result of running `src/sample.py` with `hb-shape`, on the same input. The results are the same (minus cosmetic formatting), except the python script shows an extra entry on one side - depending on whether you are doing devanagari or arabic, the entra entry is at the beginning, or at the end.

The idea is to rewrite hb-shape/hb-view in python, based on `src/sample.py`. Of course I could add code to remove the extra entry, but that beg the question, why was it added in the first place? :-).

**Comment by HinTak** [comment]
@khaledhosny : I see your latest change to `src/sample.py` . Striping the BOM before passing to harfbuzz still sounds wrong though, considerin that you are now passing streams of bytes without BOM. 

I think there is also the issue of what other shaping engines (coretext, uniscribe) do with BOM. Do they do strange things with space glyphs when encountering BOM too?

**Comment by khaledhosny** [comment]
Not sure what is wrong with stripping BOM that there only as a side effect of Python UTF-32 and UTF-16 codecs.

**Comment by HinTak** [comment]
Well, BOM has a determinative meaning, but not a typographical one, to put it in linguistic terms. So removing it just to work around a typographical problem (which should not be there in the first place...) seems wrong.

I'd be interested to know if uniscribe emits spurious glyphs too, if fed with BOM.

**Comment by khaledhosny** [comment]
OK.

**Comment by behdad** [comment]
> I'd be interested to know if uniscribe emits spurious glyphs too, if fed with BOM.

It does.  Now leave us alone! ;) jk

**Comment by behdad** [comment]
https://github.com/harfbuzz/harfbuzz/issues/1216
