### ISSUE TITLE
Run termination tests

### ISSUE THREAD

**Issue by brawer** [harfbuzz/harfbuzz#1212]
[Unicode’s test suite for text rendering engines](https://github.com/unicode-org/text-rendering-tests) now also contains a couple of test cases where any result is considered a success, as long as the rendering engine terminates within 3 seconds and does not crash. Perhaps harfbuzz wants to run those test cases too, in addition to those that check for a specific result. Currently, these test cases are [GSUB-3](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#GSUB-3), [MORX-24](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-24) and [MORX-34](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-34).

**Comment by behdad** [comment]
Yep, thanks.  I'll add that feature to our test suite.  We want to do the same about fuzzer-found tests (and then bulk-import them maybe).  I also would expect much faster than 3s.  3s for such a short test is still DoS for browsers...

**Comment by behdad** [comment]
Implemented.  We should update harfbuzz/test/shaping/data/text-rendering-tests/update.sh to generate new syntax from whatever syntax you choose for such tests.
