### ISSUE TITLE
Switch to Azure Pipelines for Windows testing?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1219]
ICU does: https://github.com/unicode-org/icu
both 32 and 64 bits.

**Comment by ebraminio** [comment]
I've installed a Linux bot on Azure Pipeline. The issue is msys2 and vcpkg are not available on their Windows bots so I don't see a reason for migration but I'll investigate the possibility as I personally like to know more about CI bots.

**Comment by ebraminio** [comment]
Correct and makes sense. We will welcome if you want to participate on the work. Also any possibility for having a freebsd vmimage there also? Thanks
