### ISSUE TITLE
[morx] Failing test MORX-35: Insertion with DontAdvance

### ISSUE THREAD

**Issue by brawer** [harfbuzz/harfbuzz#1224]
When handling `morx` insertion, the `DontAdvance` flag isn’t handled as expected. See 
[test case MORX-35](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-35). CoreText is passing this test.

![image](https://user-images.githubusercontent.com/1527880/46487072-69c66e00-c7ff-11e8-8ddb-80b3365036e9.png)

**Comment by behdad** [comment]
Just wondering, why do we not see two "E"'s in the output?

**Comment by behdad** [comment]
Or, at least, one.

**Comment by behdad** [comment]
Ie. "A" becomes "AC" while cursor still at A, then becomes "ABC" with cursor at "C".  Then an "E" should be inserted.  No?

**Comment by behdad** [comment]
(Typo in MORX-36 "theww" instead of "three".)

**Comment by brawer** [comment]
First, my assumption had been the following: When the machine advances its cursor, it skips past the freshly inserted glyphs. For example, `X̳AY` ⟹ `XA̳Y` ⟹ `XA̳Y` ⟹ `XABCY̳`. So the implementation would count how many glyphs have been inserted since the last cursor change (not the last state change), and add this to the cursor position when advancing.

But, I made some other font to confirm this assumption, and it seems to be wrong. Adding more test cases.

**Comment by brawer** [comment]
I’ve now added `X` and `Y` to the test font. For `XAY`, CoreText gives `XABCEY` which surprises me.

> Ie. "A" becomes "AC" while cursor still at A, then becomes "ABC" with cursor at "B". Then two "E"s should be inserted. No?

Indeed, that’s what fontkit does; but CoreText (the “Expected” row) disagrees...

![image](https://user-images.githubusercontent.com/1527880/46521159-eb111580-c87e-11e8-99e4-c23df9e04678.png)

**Comment by behdad** [comment]
Since CoreText's behavior is inconsistent, guess we just pick one and go ahead with it.  I personally find the "skip everything inserted since last advance" the worse option just by Occam's Razor.

**Comment by behdad** [comment]
> Yup, agree. Can you make a patch to HarfBuzz that implements this? Then, I’ll make HarfBuzz’s output the expected result.

So, basically doing what fontkit is doing? "ABECE"?  I agree that's what I would have expected HarfBuzz to generate.  I'll fix that and let you know.

**Comment by brawer** [comment]
I’ve changed MORX-35 to expect what fontkit currently generates.

**Comment by behdad** [comment]
We should also test where things get inserted if mark is not reset and
multiple insertions happen.

**Comment by behdad** [comment]
Umm.  That now seems to break MORX-33.

**Comment by behdad** [comment]
Maybe skipping over *just-inserted* glyphs is better indeed.

**Comment by behdad** [comment]
Yeah, I think I like to keep MORX-33 working, and make the non-DontAdvance case jump over the just-inserted glyphs.  So, XAX will produce XABCEX, which is actually what CoreText does now.  But A will also produce ABCE.

**Comment by brawer** [comment]
Updated the expected output for [MORX-35](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-35) to match what HarfBuzz produces at f62f6e90ad1f1a83f77771ad65ee1ffb79470a8a.

> We should also test where things get inserted if mark is not reset and multiple insertions happen.

We already test that in [MORX-30](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-30), no?

**Comment by behdad** [comment]
> We already test that in [MORX-30](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#MORX-30), no?

Right.

Though, would be better with two different insertion sequences, so we know if the second one is being inserted before or after the first insertion.

Indeed, the second in MORX-30 is what I was wondering about.  Ie. whether "MAB" should result in "INSMINSAB" or "INSINSMAB".  If everyone agrees on the second, let it be so.

Thanks for all the tests!
