### ISSUE TITLE
GSUB-3 is making timeout on Windows

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1226]
https://ci.appveyor.com/project/harfbuzz/harfbuzz/history

https://ci.appveyor.com/project/harfbuzz/harfbuzz/build/1.0.2434

All the bots are running test on Windows, CMake and Autotools, are failing, 
![image](https://user-images.githubusercontent.com/833473/46488770-83bc7c80-c810-11e8-82cc-d9cd5342ce76.png)

https://ci.appveyor.com/project/harfbuzz/harfbuzz/build/1.0.2434/job/o59vtu9w5ikclnb6#L1220
https://ci.appveyor.com/project/harfbuzz/harfbuzz/build/1.0.2434/job/cnqbt9aqusajpfi5#L1755

**Comment by behdad** [comment]
I'm out of ideas.  There's nothing Windows-specific there.  There's no way we are running GSUB-3 on uniscribe, right?
