### ISSUE TITLE
hb_vector_t is not nestable

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#1227]
Template hb_vector_t::fini () frees its allocated buffer as:
```
if (arrayZ != static_array)
  free (arrayZ);
```
The condition may hold true even when arrayZ points to a static array, if the struct has been moved in memory, ending up in a crash in free ().

This prevents hb_vector_t from being nested, because a lower level hb_vector_t may be realloc'ed in memory by a higher level hb_vector_t. It may be a limitation of hb_vector_t, but even so an obscure crash is not a kind way to tell a developer about the limitation.

**Comment by behdad** [comment]
I never thought about that... I'll get this fixed.

**Comment by behdad** [comment]
Fixed.  I also added `fini_deep()`, which you might find useful.
