### ISSUE TITLE
iOS build still broken after 824111d

### ISSUE THREAD

**Issue by tn0502** [harfbuzz/harfbuzz#1230]
824111d still doesn't fix iOS builds because `TARGET_OS_MAC` is always set even if built for iOS. See `TargetConditionals.h` for iOS:
```c
#if defined(__GNUC__) && ( defined(__APPLE_CPP__) || defined(__APPLE_CC__) || defined(__MACOS_CLASSIC__) )
    #define TARGET_OS_MAC               1
    #define TARGET_OS_WIN32             0
    #define TARGET_OS_UNIX              0

    #if !DYNAMIC_TARGETS_ENABLED
        #define TARGET_OS_OSX               0
        #define TARGET_OS_IPHONE            1
        #define TARGET_OS_IOS               1
        #define TARGET_OS_WATCH             0
        
        #define TARGET_OS_TV                0
        #define TARGET_OS_SIMULATOR         0
        #define TARGET_OS_EMBEDDED          1 
        #define TARGET_OS_RTKIT             0 
    #endif
```
And for Simulator:
```c
#if defined(__GNUC__) && ( defined(__APPLE_CPP__) || defined(__APPLE_CC__) || defined(__MACOS_CLASSIC__) )
    #define TARGET_OS_MAC               1
    #define TARGET_OS_WIN32             0
    #define TARGET_OS_UNIX              0

    #if !DYNAMIC_TARGETS_ENABLED
        #define TARGET_OS_OSX               0
        #define TARGET_OS_IPHONE            1
        #define TARGET_OS_IOS               1
        #define TARGET_OS_WATCH             0
        
        #define TARGET_OS_TV                0
        #define TARGET_OS_SIMULATOR         1
        #define TARGET_OS_EMBEDDED          0 
        #define TARGET_OS_RTKIT             0 
    #endif
```
I suggest using `!TARGET_OS_IOS` instead.

**Comment by behdad** [comment]
I changed it to `TARGET_OS_OSX`.

**Comment by tn0502** [comment]
Thanks for the quick fix ❤️

**Comment by ebraminio** [comment]
Lets fix this fundamentally, can you tell us how you are building harfbuzz for iOS? I like to put a CI bot for that and we currently have bots having xcode 10.

**Comment by tn0502** [comment]
For my project, I've simply included all the files directly in my Xcode project:

<img width="258" alt="screenshot 2018-10-10 at 12 38 05" src="https://user-images.githubusercontent.com/4123478/46730856-6f053c00-cc89-11e8-88ea-497ebdf176b3.png">

And have these macros defined:
- `HAVE_CORETEXT=1`
- `HAVE_FALLBACK=1`
- `HAVE_FREETYPE=1`
- `HAVE_OT=1`
- `HAVE_UCDN=1`

For reference, you can find my project here: https://bitbucket.org/tido/rainbow/src/master/build/ios/

**Comment by ebraminio** [comment]
Great. Thanks

**Comment by ebraminio** [comment]
#1233
