### ISSUE TITLE
USE glyph reordering is broken for some scripts

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#1235]
`_hb_ot_complex_shaper_use` does not reorder glyphs correctly in all cases. This hasn’t come up before because, by chance, these cases are not relevant to most of the scripts passed to the USE.

It reorders pre-base vowel signs to just before the last base of the cluster, or to just after the last halant of the cluster, whichever comes last. For example, the cluster ⟨half-form base pre-base-vowel⟩ will reorder to ⟨half-form pre-base-vowel base⟩. It should instead reorder pre-base vowel signs to the beginning of the cluster, or to just after the last halant of the cluster, whichever comes last. I am fairly sure that is what [the USE spec’s section on reordering](https://docs.microsoft.com/en-us/typography/script-development/use#glyph-reordering) means: when it says “base consonant” it probably means “maximal sequence of non-reordering non-halant glyphs within a cluster”, not “single glyph with class B or GB”. See MicrosoftDocs/typography-issues#104.

A specific example is the sequence 𑒞𑓂𑒏𑒱 <i>tki</i> <1149E 114C2 1148F 114B1> in [Noto Sans Tirhuta](https://github.com/googlei18n/noto-fonts/blob/b20c9c07139b22eb38013b1f80f9a5222c6058c6/phaseIII_only/hinted/ttf/NotoSansTirhuta/NotoSansTirhuta-Regular.ttf). Before reordering, the glyphs are ⟨<i>ta</i><sub>half</sub> <i>ka</i> halant <i>i</i>⟩. (That there is a halant there is an idiosyncrasy of Tirhuta; `is_halant` returns `false` for it and HarfBuzz treats it as a base.) The vowel sign gets reordered to before the preceding base, i.e. the halant, which looks wrong.

![𑒞𑓂𑒏𑒱](https://user-images.githubusercontent.com/1124347/46757684-e2fb1080-cc98-11e8-8c44-626a313fa0e3.png)

Contrast this with HarfBuzz’s Indic shaper. Here are क्खि in Noto Sans Devanagari with the current HarfBuzz and with HarfBuzz modified to map 'dev2' to the USE. I don’t think moving to the USE is supposed to break fonts this much or require so much refactoring to fix.

![क्खि](https://user-images.githubusercontent.com/1124347/46758324-88fb4a80-cc9a-11e8-8857-f454b2caa788.png) ![क्खि](https://user-images.githubusercontent.com/1124347/46758460-dd062f00-cc9a-11e8-9d58-342ecd4b83a5.png)

This is all true for the reph too, except for the direction of the reordering.

**Comment by behdad** [comment]
> I have a font with KND3, how to test in hardbuzz?

Send me the font first!  I'll enable it.

**Comment by behdad** [comment]
@dscorbett do we support indi3 tags yet?  Can you work that out?  I'll work on routing them to USE.

**Comment by MayuraVerma** [comment]
> > I have a font with KND3, how to test in hardbuzz?
> 
> Send me the font first! I'll enable it.

Here is one.
https://github.com/unicode-org/text-rendering-tests/blob/master/fonts/TestShapeKndaV3.ttf

I have another one. But I have not seeked permission to distribute. I will request for permission and upload it here. 
But that font is more tuned to USE shaper. I have tested it on mac OS. I am finding some issues. I am not sure if it is font issue or the shaping engine issue.

**Comment by dscorbett** [comment]
No, Indic3 is not yet supported. I can add it easily. [This USE proposal](https://github.com/OpenType/opentype-layout/blob/4d2b0cc39aa2e6ca010a899aac2b7d1a417f6679/proposals/20160520-JohnHudson-USE-arbitrary-scripts.md) mentions a different convention with initial capital letters. Did that idea go anywhere?

**Comment by behdad** [comment]
Not that I know.  Apple is shipping with 'dev3' etc.  Please add that, and I'll wire them to USE.

**Comment by MayuraVerma** [comment]
I am not an expert in this subject.

What happens to legacy fonts, who have labeled the script name in caps already? They had written their contextual lookups with reference to legacy indic engine not USE! This would mean some or many legacy indic fonts would be passed to USE without the intention of doing it. 

FYI: Mac OS is passing all indic scripts to dev3, bng3, knd3, etc to USE

**Comment by behdad** [comment]
> https://github.com/unicode-org/text-rendering-tests/blob/master/fonts/TestShapeKndaV3.ttf

So, that font is untested in that repo, right?

**Comment by behdad** [comment]
> For example, the cluster ⟨half-form base pre-base-vowel⟩ will reorder to ⟨pre-base-vowel half-form base⟩. It should instead reorder pre-base vowel signs to the beginning of the cluster, or to just after the last halant of the cluster, whichever comes last.

Is your example wrong?  I thought you mean we currently put the pre-base-vowel *after* half-form?

Got patch?

**Comment by behdad** [comment]
> How can I test it in a local machine?

Build and use hb-view?

**Comment by dscorbett** [comment]
Yes, my example was wrong. I fixed it.

**Comment by behdad** [comment]
Okay so if I understand correctly, you are saying that we get this wrong both for pre-base-reordering vowels, as well as reph?  Those are two different things.

**Comment by behdad** [comment]
There's also pre-base-reordering medial ra stuff (pref feature)

**Comment by dscorbett** [comment]
Yes, that is what I mean. They are all essentially the same problem: they are all wrong due to the vague wording of the USE spec and are all implemented in the same function.

**Comment by behdad** [comment]
Okay.  Not going to rush to a fix here.  Will do after next release.

**Comment by dscorbett** [comment]
Actually, I have already almost finished a fix for this.

**Comment by behdad** [comment]
Oh cool.  I'll wait then.  Thanks.

**Comment by tiroj** [comment]
> So, a repha should be reordered to after all vowels and everything else in the syllable?

I think only after the last consonant in a cluster, not after a vowel sign, final virama, or other sign such as anusvara. This maintains behaviour for Indic 2 lookups that may ligate such signs or position them relative to each other.

**Comment by dscorbett** [comment]
That would make sense. Does anyone have access to a recent Uniscribe to test it?

**Comment by tiroj** [comment]
We'd need a font (Noto?) for a script that is processed via USE in Uniscribe (so not Indic 3 tags), which we've confirmed has repha shaping plus some kind of repha plus other glyoh interaction (GSUB or GPOS), and know how that interaction takes place, i.e. what the expected ordering is for the lookup.

The only USE-targeted font I've made so far is for Javanese, which doesn't include repha behaviour.

**Comment by dscorbett** [comment]
A good test string is 𑘨𑘿𑘐𑘿𑘎𑘽 <11628 1163F 11610 1163F 1160E 1163D> in Noto Sans Modi.

**Comment by tiroj** [comment]
Here is the rendering of that sequence in Noto Sans Modi (Version 2.000;GOOG;noto-source:20181019:f8f3770) in Notepad under Windows 10 Pro (Version 1803):

<img width="141" alt="screen shot 2018-10-22 at 2 31 35 pm" src="https://user-images.githubusercontent.com/5614500/47320907-b2579700-d607-11e8-8b6a-e3881c36d460.png">

**Comment by dscorbett** [comment]
What does hb-shape emit?

**Comment by tiroj** [comment]
I don't have a Harfbuzz test environment set up on this machine, and don't have time today to set one up.

**Comment by tiroj** [comment]
I have taken a look inside the Noto Sans Modi OTL tables, and have confirmed that the repha + anusvara interaction is handled via a GPOS 'mkmk' feature lookup, and the order of the lookup presumes that the repha precedes the anusvara.

**Comment by dscorbett** [comment]
Okay, that confirms that Uniscribe does indeed reorder a reph past half forms but not past vowel modifiers. I’ll have to update my pull request.

**Comment by punchcutter** [comment]
One of the most noticeable situations occurs in Grantha where the repha is a post-base spacing glyph that can appear along with a post-base YA as well as a post-base RA. In the Unicode proposal both positions are mentioned (repha before or after the other post-base forms), but the favored position is where the repha comes directly after the base with post-base RA and YA following the repha. This is the current harfbuzz behavior (which also seems to be what Uniscribe is doing):

𑌰𑍍𑌦𑍍𑌰𑍍𑌯
11330,1134D,11326,1134D,11330,1134D,1132F
![grantha_repha_before_fix](https://user-images.githubusercontent.com/11257204/48383553-0dc2f500-e69b-11e8-8518-f2ce4fe8b02d.png)

The current pull request matches CoreText in the reordering: 

![grantha_repha_after_fix](https://user-images.githubusercontent.com/11257204/48383555-11567c00-e69b-11e8-9701-e20b972568b4.png)

I believe this pull request is the correct way to handle it, but at least for Grantha I'd like to hear if there are arguments for the current way other than that's just the way it has been. I've seen examples of both ways in both print and handwritten text.

**Comment by behdad** [comment]
Which one is the repha in the visuals?  Or rather, does HarfBuzz currently put repha after base, or at the end?  My expectation is different from what you are reporting regarding what this PR does.

**Comment by dscorbett** [comment]
The repha is the one with the loop: HarfBuzz currently puts it directly after the base. This Grantha example is analogous to the Kannada example ⟨ರ್ಕ್ಕ⟩, where the repha should go at the end. That Uniscribe behaves as it does is unfortunate for Indic3.

**Comment by behdad** [comment]
Okay so I wasn't wrong being confused by Zachary's comment?  He says "but the favored position is where the repha comes directly after the base with post-base RA and YA following the repha." but also "'d like to hear if there are arguments for the current way other than that's just the way it has been."  Aren't those two in conflict?

**Comment by punchcutter** [comment]
The only thing in conflict is that there are two ways to position the repha. The "favored" position in the Unicode proposal is directly after the base (B Rphf H+B H+B = the current harfbuzz position). But the other position (B H+B H+B Rphf = the current pull request) is also found in writing and printing. So I would like to know if/why one or the other is considered more "correct".

**Comment by jfkthame** [comment]
> The only thing in conflict is that there are two ways to position the repha. The "favored" position in the Unicode proposal is directly after the base (B Rphf H+B H+B = the current harfbuzz position). But the other position (B H+B H+B Rphf = the current pull request) is also found in writing and printing. So I would like to know if/why one or the other is considered more "correct".

It sounds like this may be a situation where the author should be given control, somehow -- it should be possible for them to encode their text in such a way that the desired repha position results. I don't have a specific proposal in mind, but some kind of convention involving a join-control or CGJ character might work. (Would need to be agreed and documented somewhere, obviously.)

Another point of view would be to put the control in the hands of the font designer: if the two visual orderings are clearly understood as equivalent, so it's purely a stylistic difference, maybe it doesn't need to be represented in the plain text but can be decided as part of styling, by choosing a font or feature that provides the desired rendering.

What I think we should avoid, given evidence that both versions are "found in writing and printing", would be choosing one to support, and making it impossible (or at best very awkward) for users to achieve the other. Whether control of the order belongs more properly in the hands of the author of the text or the designer of the font is unclear to me.

**Comment by dscorbett** [comment]
I think it should probably match Uniscribe, but I’d like a test done first.

We shouldn’t decide anything based only on Kannada, which Uniscribe doesn’t put through USE, and Grantha, where both options are valid. Among the other USE scripts I found five which have rephas and post- or below-base medial consonants: Balinese, Modi, Siddham, Sinhala, and Tirhuta. Someone with Windows 10 should test them to see how Uniscribe shapes them. Test strings are ⟨ᬭ᭄ᬫ᭄ᬧ⟩, ⟨𑘨𑘿𑘎𑘿𑘨⟩, ⟨𑖨𑖿𑖎𑖿𑖧⟩, ⟨ර්‍ක්‍ය⟩, ⟨ර්‍ය්‍ය⟩, and ⟨𑒩𑓂𑒏𑓂𑒨⟩. The Balinese string requires a font that supports Kawi, like the one @punchcutter created in googlei18n/noto-fonts#1123. There are two Sinhala strings because of the stylistic variation described in googlei18n/noto-fonts#523. These should be tested with fonts where the repha, base, and medial consonant have separate glyphs at reordering time.

I suspect Uniscribe does not reorder the rephas past the post-base consonants. I am not so sure about the below-base consonant in the Modi example, but since it is below the base, it probably doesn’t matter much, as it doesn’t interact with the repha either way. All this implies that the repha should _not_ be reordered past medial consonants, and that I need to change my pull request.

That will make rephas inconvenient in 'knd3' and 'tel3', and in some styles and contexts 'gran' and 'sinh'. For these, font developers can use chaining 'psts' lookups to move the repha to the end. I don’t think think that is too bad: 'knd3' and 'tel3' are uncommon, and for 'gran' and 'sinh' both behaviors are attested so there will be an inconvenience no matter what.

**Comment by dscorbett** [comment]
So Uniscribe reorders a repha past a post-base <i>ya</i> in Tirhuta but not in Grantha. The only difference I see is that in Noto Sans Tirhuta, Ya.post is a base glyph, and in Noto Sans Grantha, yaPhalaa_gran is a mark glyph.

**Comment by behdad** [comment]
Using GDEF classes for determining "base" is eaaaaasy.  I like that.

**Comment by dscorbett** [comment]
Yeah, but I could be wrong. What does Uniscribe do for those strings if Noto Sans Grantha’s yaPhalaa_gran is changed to a base glyph and Noto Sans Tirhuta’s Ya.post to a mark glyph?

**Comment by punchcutter** [comment]
Sorry, Uniscribe does the same thing with Grantha. I'm not sure why I wrote it the other way above. It acts the same as CoreText and reorders the repha past subscripts/post-base. But talking about post-base glyphs is a little confusing because there's no way for the shaper to know if an H+B is a subscript form or post-base form. The important part is it's some kind of H+B. In both Tirhuta and Grantha it starts [Rphf B H+B] and the repha moves past the H+B or past multiple H+Bs. It doesn't matter how that "post-base" glyph is classified.

**Comment by dscorbett** [comment]
In that case, my PR matches Uniscribe. I think it is ready to merge.

As for your original question, [L2/09-372](https://www.unicode.org/L2/L2009/09372-grantha.pdf#page=31) says “Sometimes the YA-phalaa is seen before the repha [...]. This is to be considered an aberration since the repha _mostly_ stands before the YA-phalaa. [...] ﻿﻿We have remarked that in “standard” orthography, repha, YA-phalaa and spacing vowel signs stand in that order. A further justification for this is that it makes some sense for displayed forms to not excessively deviate from their underlying characters in logical (phonetic) order.” It is strongly implied that putting the repha to the right of the <i>ya</i>, though not unattested, should not be done by default in fonts like Noto Sans Grantha.

**Comment by tiroj** [comment]
> Using GDEF classes for determining "base" is eaaaaasy. I like that.

So eaaaaasy I can see why it would be tempting. The trouble is that we can't always define a glyph in GDEF in the way that accurately represents its role in the cluster, because sometimes we need to class post-based spacing signs as 'marks' so that they can be skipped in GSUB using lookup flags.

**Comment by behdad** [comment]
Is that the consensus here, that I should merge this as is?

**Comment by punchcutter** [comment]
Based on the tests done for all of the above scripts I think this PR is good. Some fonts will need to be updated to get the desired behavior, but this PR definitely fixes situations where the default behavior is not what we want.

**Comment by dscorbett** [comment]
I just fixed a merge conflict. It should be all set to merge now.
