### ISSUE TITLE
Bizarre calculation of width for vertical layout in hb-view

### ISSUE THREAD

**Issue by HinTak** [harfbuzz/harfbuzz#1243]
For horizontal layout, the height calculating from `font_height` (which comprised of ascender + descender, and most of `leading` is) is fine, but for vertical layout, I mean true vertical one like Japanese, rather than rotated ones like mongolian, the size of ascender and descender bears no relationship with the width of a vertical column of characters...

Referring to line 57-ish of util/view-cairo.cc

```
(vertical ? w : h) = (int) lines->len * leading - view_options.line_space;
```

**Comment by HinTak** [comment]
Hmm, this seems to happen to be not noticeable because of get_v_extents_with_fallback putting the "baseline" down the middle...

**Comment by behdad** [comment]
Got any better suggestions?

**Comment by HinTak** [comment]
I was staring at that bit of code because of 
https://github.com/harfbuzz/harfbuzz/issues/1248 , actually.

Depends a bit on the design goal, really. If it is purely for demonstration purposes, to cater for the case of a font where the glyphs are all rather wide and short, one might do a max () of the two. OTOH, if it is about showing "best practice", I would suggest using one of the font's own "design" widths.

**Comment by behdad** [comment]
> the size of ascender and descender bears no relationship with the width of a vertical column of characters...

In the spec the vmtx ascender/descender are defined exactly as we used them. So there's no issue in my opinion.
