### ISSUE TITLE
Fallback for Sinhala Conjuncts

### ISSUE THREAD

**Issue by Richard57** [harfbuzz/harfbuzz#1246]
There is the problem with rendering a request for a Sinhala conjunct followed by a left-reordering matra if the conjunct is not in the font.  For a fairly sure example of such a lack, consider the following encoding for the rare Pali syllable thve ථ්‍වෙ <U+0DAE MAHAAPRAANA TAYANNA, U+0DCA AL-LAKUNA, U+200D ZWJ, U+0DC0 VAYANNA, U+0DD9 KOMBUVA>.

With Windows 7 Uniscribe and with HarfBuzz, it renders like thēva ථේව <U+0DAE, U+0DDA DIGA KOMBUVA, U+0DC0> .

On Notepad on Windows 10 and on email on iPhone, it renders like Sinhalese thve ථ්වෙ  <U+0DAE, U+0DCA, U+0DC0, U+0DD9>, and I endorse this fallback.  As the al-lakuna is an unchanged virama glyph, it should force a syllable break, so the left reordering matra should be written before the second consonant.

An unsatisfied request for touching consonants, e.g. Pali thve as ථ‍්වෙ <U+0DAE, U+200D, U+0DCA,  U+0DC0, U+0DD9>, is currently rendered the same more or less as <U+0DAE, U+0DCA, U+0DC, U+0DD9>.  Some fonts, e.g. LKLUG, fail to achieve the proper interaction between the glyphs of the initial consonant and al-lakuna; allowing the glyph of U+200D to block it appears to be a font error.  (A satisfied request results in the matra appearing at the left of the cluster and the lack of an explicit al-lakuna glyph.)

It is arguable that touching glyphs would be a better fallback for a missing conjunct, but I think that should be a font issue rather than a renderer issue, unless user control were to be included somehow.

**Comment by behdad** [comment]
What needs to be done here?

**Comment by Richard57** [comment]
The ideal solution should be to render Sinhala using the USE.  Failing that, the USE / Indic 2 behaviour of not moving vowels past an unsubstituted virama should be implemented in the Sinhala renderer.
