### ISSUE TITLE
TRAK support for .SFNSText disagrees with CoreText

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1263]
Using ToT HarfBuzz in Chromium after the kerning fixes still results in about ~420 layout test failures, many of them related to CSS system-font usage or themed UI controls rendering with differing spacing. Also the designated TRAK test that we have to compare tracking to Safari fails. HarfBuzz seems to apply some tracking, which still results in a non-linear run-width to font-size ratio, but the values are very different from Safari.

I am testing with `.SFNSText`, which has the following `trak` info:

```
$ ttx -o- -ttrak /System/Library/Fonts/SFNSText.ttf 
Dumping "/System/Library/Fonts/SFNSText.ttf" to "-"...
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.22">

Dumping 'trak' table...
  <trak>
    <version value="1.0"/>
    <format value="0"/>
    <horizData>
      <!-- nTracks=3, nSizes=20 -->
      <trackEntry value="-1.0" nameIndex="291">
        <track size="6.0" value="54"/>
        <track size="9.0" value="10"/>
        <track size="10.0" value="-4"/>
        <track size="11.0" value="-16"/>
        <track size="12.0" value="-28"/>
        <track size="13.0" value="-40"/>
        <track size="14.0" value="-50"/>
        <track size="15.0" value="-60"/>
        <track size="16.0" value="-68"/>
        <track size="17.0" value="-75"/>
        <track size="20.0" value="-83"/>
        <track size="22.0" value="-88"/>
        <track size="28.0" value="-94"/>
        <track size="32.0" value="-96"/>
        <track size="36.0" value="-98"/>
        <track size="50.0" value="-106"/>
        <track size="64.0" value="-114"/>
        <track size="80.0" value="-120"/>
        <track size="100.0" value="-120"/>
        <track size="138.0" value="-120"/>
      </trackEntry>
      <trackEntry value="0.0" nameIndex="290">
        <track size="6.0" value="82"/>
        <track size="9.0" value="38"/>
        <track size="10.0" value="24"/>
        <track size="11.0" value="12"/>
        <track size="12.0" value="0"/>
        <track size="13.0" value="-12"/>
        <track size="14.0" value="-22"/>
        <track size="15.0" value="-32"/>
        <track size="16.0" value="-40"/>
        <track size="17.0" value="-47"/>
        <track size="20.0" value="-55"/>
        <track size="22.0" value="-60"/>
        <track size="28.0" value="-66"/>
        <track size="32.0" value="-68"/>
        <track size="36.0" value="-70"/>
        <track size="50.0" value="-78"/>
        <track size="64.0" value="-86"/>
        <track size="80.0" value="-92"/>
        <track size="100.0" value="-92"/>
        <track size="138.0" value="-92"/>
      </trackEntry>
      <trackEntry value="2.0" nameIndex="292">
        <track size="6.0" value="74"/>
        <track size="9.0" value="30"/>
        <track size="10.0" value="16"/>
        <track size="11.0" value="4"/>
        <track size="12.0" value="-8"/>
        <track size="13.0" value="-20"/>
        <track size="14.0" value="-30"/>
        <track size="15.0" value="-40"/>
        <track size="16.0" value="-48"/>
        <track size="17.0" value="-55"/>
        <track size="20.0" value="-76"/>
        <track size="22.0" value="-84"/>
        <track size="28.0" value="-93"/>
        <track size="32.0" value="-98"/>
        <track size="36.0" value="-103"/>
        <track size="50.0" value="-116"/>
        <track size="64.0" value="-124"/>
        <track size="80.0" value="-124"/>
        <track size="100.0" value="-124"/>
        <track size="138.0" value="-124"/>
      </trackEntry>
    </horizData>
    <vertData>
      <!-- nTracks=0, nSizes=0 -->
    </vertData>
  </trak>

</ttFont>

```

Running the following test script:

```
#!/bin/bash
for ptem_size in 6 9 10 11 12 13 14 15 16 17 20 22 28 32 36 50 64 80 100 138
do
    printf "\nfont-ptem %d:\n" $ptem_size
    for shaper in coretext ot
    do
        printf "%8s: %s\n" $shaper `./hb-shape --font-ptem=$ptem_size --shaper=$shaper /System/Library/Fonts/SFNSText.ttf "YoVa"`
    done
done

```

outputs:

```
font-ptem 6:
coretext: [gid345=0+1226|gid771=1+1162|gid332=2+1332|gid572=3+1182]
      ot: [gid345=0@12,0+1369|gid771=1@12,0+1235|gid332=2@12,0+1405|gid572=3@12,0+1155]

font-ptem 9:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-14,0+1316|gid771=1@-14,0+1182|gid332=2@-14,0+1352|gid572=3@-14,0+1102]

font-ptem 10:
coretext: [gid345=0+1159|gid771=1+1095|gid332=2+1265|gid572=3+1115]
      ot: [gid345=0@-22,0+1301|gid771=1@-22,0+1167|gid332=2@-22,0+1337|gid572=3@-22,0+1087]

font-ptem 11:
coretext: [gid345=0+1146|gid771=1+1082|gid332=2+1252|gid572=3+1102]
      ot: [gid345=0@-28,0+1287|gid771=1@-28,0+1153|gid332=2@-28,0+1323|gid572=3@-28,0+1073]

font-ptem 12:
coretext: [gid345=0+1134|gid771=1+1070|gid332=2+1240|gid572=3+1090]
      ot: [gid345=0@-34,0+1276|gid771=1@-34,0+1142|gid332=2@-34,0+1312|gid572=3@-34,0+1062]

font-ptem 13:
coretext: [gid345=0+1127|gid771=1+1063|gid332=2+1233|gid572=3+1083]
      ot: [gid345=0@-38,0+1268|gid771=1@-38,0+1134|gid332=2@-38,0+1304|gid572=3@-38,0+1054]

font-ptem 14:
coretext: [gid345=0+1123|gid771=1+1059|gid332=2+1229|gid572=3+1079]
      ot: [gid345=0@-40,0+1265|gid771=1@-40,0+1131|gid332=2@-40,0+1301|gid572=3@-40,0+1051]

font-ptem 15:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-42,0+1261|gid771=1@-42,0+1127|gid332=2@-42,0+1297|gid572=3@-42,0+1047]

font-ptem 16:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-43,0+1258|gid771=1@-43,0+1124|gid332=2@-43,0+1294|gid572=3@-43,0+1044]

font-ptem 17:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-44,0+1255|gid771=1@-44,0+1121|gid332=2@-44,0+1291|gid572=3@-44,0+1041]

font-ptem 20:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-46,0+1251|gid771=1@-46,0+1117|gid332=2@-46,0+1287|gid572=3@-46,0+1037]

font-ptem 22:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-47,0+1249|gid771=1@-47,0+1115|gid332=2@-47,0+1285|gid572=3@-47,0+1035]

font-ptem 28:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-49,0+1245|gid771=1@-49,0+1111|gid332=2@-49,0+1281|gid572=3@-49,0+1031]

font-ptem 32:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-51,0+1242|gid771=1@-51,0+1108|gid332=2@-51,0+1278|gid572=3@-51,0+1028]

font-ptem 36:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-52,0+1239|gid771=1@-52,0+1105|gid332=2@-52,0+1275|gid572=3@-52,0+1025]

font-ptem 50:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-58,0+1229|gid771=1@-58,0+1095|gid332=2@-58,0+1265|gid572=3@-58,0+1015]

font-ptem 64:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-60,0+1224|gid771=1@-60,0+1090|gid332=2@-60,0+1260|gid572=3@-60,0+1010]

font-ptem 80:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-60,0+1224|gid771=1@-60,0+1090|gid332=2@-60,0+1260|gid572=3@-60,0+1010]

font-ptem 100:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-60,0+1224|gid771=1@-60,0+1090|gid332=2@-60,0+1260|gid572=3@-60,0+1010]

font-ptem 138:
coretext: [gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]
      ot: [gid345=0@-80,0+1184|gid771=1@-80,0+1050|gid332=2@-80,0+1220|gid572=3@-80,0+970]

```

So CoreText and OT seem to vastly disagree on the spacing here. I don't have a plausible interpretation on what's going on.

**Comment by behdad** [comment]
> For testing, I’ve made an OFL-licensed font with a `trak` table; `H` is its only glyph: https://github.com/unicode-org/text-rendering-tests/blob/master/fonts/TestTRAKOne.ttf

There's also one @ebraminio and I made for HarfBuzz.  It's in the repo test/shaping/data/in-house/fonts/TestTRAK.ttf if you want to grab.  It has morx table and support ABC glyphs.

**Comment by drott** [comment]
This issue seems more pronounced when kern and trak are present, as in the SFNSText.ttf example with the heavily kerned "YoVa" test string. Certainly we should be able to bring both, trak only and kern + trak into alignment or at the very least have a good explanation of why we differ.

**Comment by behdad** [comment]
Can you paste a few samples of coretext output w kern and trak?

**Comment by drott** [comment]
I'm saying the font I'm using has both Kern and trak, the output above should have both features on by default.

**Comment by behdad** [comment]
Okay.  I found a bug in my implementation and fixed it.  However, for in your output looks like CoreText stops applying trak at 16ptem.  That is when the trak values start getting negative.  I don't know, do we want to match that?

**Comment by behdad** [comment]
Also, looks like we apply trak to the sides of the text run as well, while CoreText doesn't.  I think our behavior is more correct.

**Comment by behdad** [comment]
Reopening while we figure out the rest.  But please give it a run with these changes.

**Comment by behdad** [comment]
Note that CoreText points are equal to CSS pixels, equal to 4./3. typographic points.  So, when you put --font-ptem=9, it matches the number 12 in the trak table, which happens to be 0-tracking value.

**Comment by behdad** [comment]
BTW, you can use `--ned` to get absolute glyph positions. That better matches CoreText output.

**Comment by drott** [comment]
Thanks for the fix! So which tracking table will be used and how can I control that? Is the 0 entry now used by default?

> Note that CoreText points are equal to CSS pixels, equal to 4./3. typographic points. So, when you put --font-ptem=9, it matches the number 12 in the trak table, which happens to be 0-tracking value.

What does that mean for my testing?

I thought we noticed that Safari's CSS font px sizes are directly used without conversion for the trak table, aren't they? 
In the test case expectations that we recorded from Safari:
https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/text/mac-system-ui-trak.html?q=ui+trak+layout+tests&sq=package:chromium&dr=C&l=38
There is non-linear scaling down to 6px/Mac-Points, so I don't think CoreText stops applying tracking lower down.

**Comment by ebraminio** [comment]
> So which tracking table will be used and how can I control that? Is the 0 entry now used by default?

Currently only table with value="0" is used, like Firefox. We need bilinear interpolation for supporting other tables.

> What does that mean for my testing?

Probably nothing, just rebase the tests if visually not noticeable. (at least that is what I understand)

> I don't think CoreText stops applying tracking lower down.

We are doing extrapolation AFAIK, Behdad has fixed that.

**Comment by drott** [comment]
In https://github.com/drott/harfbuzz/tree/testTrakTools I wrote a python script based on the [Pillow image processing library for Python](https://pillow.readthedocs.io/en/stable/) to overlay the CoreText results with the OT results for the couple of examples that were discussed in this issue. 

The tool draws the output from hb-view with CoreText as a green background, then overlays hb-view with the OT shaper in red with 50% opacity.

@brawer, I added your test font to that tree for quick testing as well.

I get the following results (it'd be good if you could also quickly review the tool before analysing the results):

**Example 0, TestTrak.ttf, "ABC"**
`$ ./trak_ot_coretext.py 0 coretext_green_ot_red_0.png`

OT is quite literally losing track at ptem 3 and ptem 6, then it looks good at 9, and and a tighter tracking starts creeping in from 10 with the difference increasing. At ptem 80 in OT the glyphs start touching, at ptem 150 they are overlapping, see [coretext_green_ot_red_0.png](https://roettsch.es/coretext_green_ot_red_0.png). At the higher ptem sizes, the first glyph is pulled left quite far.

Example 1, SFNSText.ttf, "YoVa":
`$ ./trak_ot_coretext.py 1 coretext_green_ot_red_1.png`

OT does not seem to do any kerning in this example and pulls the Y left in all examples. None of the examples is aligned. Even if we would correct the first glyph's offset, I don't think we would see a fully aligned run. See [coretext_green_ot_red_1.png](https://roettsch.es/coretext_green_ot_red_1.png)

**Example 2, TestTRAKOne.ttf, "HH"**
`$ ./trak_ot_coretext.py 2 coretext_green_ot_red_2.png`

Strangely, CoreText and OT seem to track in different directions in this test. While the two H's are moving closer together with increasing ptem size in OT, they move further apart in CoreText. the initial H glyph is not aligned in any of the runs. See [coretext_green_ot_red_2.png](https://roettsch.es/coretext_green_ot_red_2.png)

**Comment by drott** [comment]
Script updated to output shape data to file, e.g.
`$ ./trak_ot_coretext.py 2 example_2_shape_data.txt --shape-data`

Shape data files available here:
https://roettsch.es/example_0_shape_data.txt
https://roettsch.es/example_1_shape_data.txt
https://roettsch.es/example_2_shape_data.txt

**Comment by ebraminio** [comment]
What I see is CoreText applies some heuristucs and doesn't extrapolate apparently which it should per specification AFAIK. Are there any noticable difference on Chrome web pages also?

**Comment by ebraminio** [comment]
> What I see is CoreText applies some heuristucs and doesn't extrapolate apparently 

Well what I see is CoreText is doesn't do anything on case 0 and 2 (also can be seen on .txt results) which matches what Behdad said [here](https://github.com/unicode-org/text-rendering-tests/issues/46#issuecomment-370410810), you can still compare them to Firefox which has similar implementation but not exact.

On case 1, "[gid345=0+1174|gid771=1+1110|gid332=2+1280|gid572=3+1130]" matches with 15 one of them which is the heuristic, `trak` should support extrapolate, [trak specification](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6trak.html), "[,,] interpolation or extrapolation is performed to determine the adjustment [,,]"

I mean like what happened on switching Chrome from Uniscribe and CoreText to HarfBuzz, there should be some tests be rebased anyway.

I will see also if our code can be modified to match better with CoreText.

**Comment by drott** [comment]
True that the aspect of comparing example 0 and 2 to CoreText is not too useful, thanks for pointing that out. However, either there is something wrong in the extrapolation, or the trak specs of  `TestTrak.ttf` are not optimal, as I don't think it is intended that the glyphs start colliding / overlapping.

**Comment by ebraminio** [comment]
This is Firefox in house implementation https://dxr.mozilla.org/mozilla-central/source/gfx/thebes/gfxMacPlatformFontList.mm#660-684 which they are shipping also (but doesn't do extrapolation), can you see whether that looks better?

**Comment by drott** [comment]
When I eyeball-align CoreText and HB AAT by dividing the HB start-glyph offsets by -7 (why this number?!), I get this result:
$ ./trak_ot_coretext.py 1 coretext_ot_aligned_eyeballed.png --align-ct-ot-start

Image result: https://roettsch.es/coretext_ot_aligned_eyeballed.png

So there is still a lot of misalignment, even if we take the initial glyph offset out of the equation.

**Comment by drott** [comment]
> This is Firefox in house implementation https://dxr.mozilla.org/mozilla-central/source/gfx/thebes/gfxMacPlatformFontList.mm#660-684 which they are shipping also (but doesn't do extrapolation), can you see whether that (testing Firefox itself) looks better?

In my understanding we're not really touching interpolation here since the test font ptem sizes, except for the extra 3 and 150, we are only testing at the thresholds.

**Comment by behdad** [comment]
> What I see is CoreText applies some heuristucs and doesn't extrapolate apparently which it should per specification AFAIK. Are there any noticable difference on Chrome web pages also?

No.  There's something else going on.  hb-coretect tries to create systemUI font such that traking is applied by coretext.  However, coretext will switch to SFDisplay after 16.  hb-coretext detects this and discards the systemUI font created, hence essentially traking not applied by coretext.  Trying with SFDisplay makes it work > 16.

**Comment by drott** [comment]
Here are values for SFNSDisplay on top of HB 79b63561552bdfe
https://roettsch.es/sfdisplay_16_up.png
https://roettsch.es/sfdisplay_16_up.txt

**Comment by drott** [comment]
Additionally, https://roettsch.es/sfdisplay_16_up_YYYoooVVVaaa.txt
https://roettsch.es/sfdisplay_16_up_YYYoooVVVaaa.png with a different test string.

**Comment by drott** [comment]
And https://roettsch.es/sfdisplay_16_up_HHHHHHHHH_newptem.txt and https://roettsch.es/sfdisplay_16_up_HHHHHHHHH_newptem.png with scaling from csspx in trak to ptem.

**Comment by twardoch** [comment]
The question whether to apply tracking to the edges of a text run is interesting and there is no obvious way to say which way it should go. I wish we knew the rationale behind CoreText not doing it. 

Overall, at the beginning and end of each line, in really well-done typesetting a different sidebearing should always be used — whether you apply tracking or not, the sidebearings are rarely super-good for the line bounds. 

But since the support for OT/AAT margin alignment (lfbd, rtbd etc) is very rare and there are practically no fonts that include this info, it's a question for another day. 

When switching fonts, when one font has tracking and another has not, it's always better if there is a bit too much space than too little between the text runs. So I think adding space to the run bounds is a better choice. 

Overall, in typesetting (within reason), "too much space" is usually better than "too little space" (which is why "stupid" positive tracking is OK — but simple reducing inter-glyph space when the text is tight is much more likely to cause ugly effects).

**Comment by twardoch** [comment]
Also, I'd love it if "trak" is added to OT Layout at some point. It's such a simple table that I think most fonts should have it. Users world hugely benefit from it. 

May I ask: in HB, when the font has GSUB+GPOS+trak (no morx/kerx), will trak be used, and if so, under which circumstances?

**Comment by twardoch** [comment]
thanks!

**Comment by ebraminio** [comment]
IIRC shape results always can be scaled and there a flag using shaping result on different scales without shaping again, isn't better an API is put to let users they can't scale shaping result or `trak` is available or something?

**Comment by drott** [comment]
At b92b9d7e5290eaa83e94fd40cddaee71628a3c2a this now looks pretty good for `SFNSText` and `SFNSDisplay`, but there still big differences for `Apple Chancery`.

![chancery_trak_small](https://user-images.githubusercontent.com/1021784/47299784-4da63780-d61b-11e8-802b-177d272663e4.png)


https://roettsch.es/chancery_trak.png
https://roettsch.es/chancery_trak.txt

```
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.22">

  <trak>
    <version value="1.0"/>
    <format value="0"/>
    <horizData>
      <!-- nTracks=2, nSizes=7 -->
      <trackEntry value="-1.0" nameIndex="302">
        <!-- Ad -->
        <track size="5.0" value="40"/>
        <track size="6.0" value="40"/>
        <track size="12.0" value="0"/>
        <track size="18.0" value="-40"/>
        <track size="36.0" value="-80"/>
        <track size="72.0" value="-120"/>
        <track size="73.0" value="-120"/>
      </trackEntry>
      <trackEntry value="0.0" nameIndex="303">
        <!-- Book -->
        <track size="5.0" value="50"/>
        <track size="6.0" value="50"/>
        <track size="12.0" value="0"/>
        <track size="18.0" value="-25"/>
        <track size="36.0" value="-50"/>
        <track size="72.0" value="-50"/>
        <track size="73.0" value="-50"/>
      </trackEntry>
    </horizData>
    <vertData>
      <!-- nTracks=0, nSizes=0 -->
    </vertData>
  </trak>

</ttFont>

```

So with this font, the values only align for 12ptem, 9ptem - but for above and below that, the tracking is vastly off.

**Comment by drott** [comment]
Ugh, never mind the tracking differences for Chancery: CoreText does not apply tracking for this font, as it's not a UI font - same issue, but I guess our implementation of applying tracking is an improvement. What remains: Is there a way I can disable `trak` from the hb-* tools --feature string or from `font-feature-settings: 'trak' 0;` for example? I did try `--features=-trak`, but that did not seem to have any effect.

**Comment by behdad** [comment]
I'll hook up --features=-trak...

**Comment by ebraminio** [comment]
Here you go https://github.com/harfbuzz/harfbuzz/pull/1296 :)

**Comment by behdad** [comment]
Can we close this now?

**Comment by drott** [comment]
Thank you for fixing the issues we discovered in this thread. Yes, I currently see no `trak` specific issues. I'll open separate issues for the general landing of HarfBuzz 2.0.2 in Chrome.

**Comment by drott** [comment]
--features=-trak moved to https://github.com/harfbuzz/harfbuzz/issues/1303
