### ISSUE TITLE
Set ptem in hb_ft_face_create?

### ISSUE THREAD

**Issue by brawer** [harfbuzz/harfbuzz#1269]
For correctly shaping fonts with a `trak` table, the nominal point size needs to be considered. While FreeType clients pass a nominal height to [FT_Set_Char_Size()](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Set_Char_Size), HarfBuzz currently does not call `hb_font_set_ptem()` in `hb_ft_face_create()`. Should HarfBuzz infer the ptem from `ft_face->size->metrics` when `ft_face->size` is not null?

I’m trying to test `trak` in the [test suite for rendering engines](https://github.com/unicode-org/text-rendering-tests). My code calls `FT_Set_Char_Size()` on an `FT_Face` which is passed to libraqm. Instead of letting HarfBuzz set ptem in `hb_ft_face_create()`, libraqm could possibly be changed to call `hb_font_set_ptem()`. But I’m wondering if this isn’t something that should be done at the HarfBuzz-FT level.

/cc @khaledhosny

**Comment by brawer** [comment]
Can’t point-size be deduced from [FT_Size_Metrics](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Size_Metrics).y_scale?

> y_scale — A 16.16 fractional scaling value to convert vertical metrics from font units to 26.6 fractional pixels. Only relevant for scalable font formats.

**Comment by behdad** [comment]
> Can’t point-size be deduced from [FT_Size_Metrics](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Size_Metrics).y_scale (and the font’s upem)?
> 
> > y_scale — A 16.16 fractional scaling value to convert vertical metrics from font units to 26.6 fractional pixels. Only relevant for scalable font formats.

No.  That's pixel size.  The point size relates to pixel size through the dpi, which *can* be passed to `FT_Set_Char_Size`.  I have to poke into it.  Let's leave this open until I figure out.  I'm not positive it's a good idea to do it automatically.

**Comment by lemzwerg** [comment]
FreeType doesn't give access to the point size.  Internally, only the TrueType driver stores the horizontal resolution so that the point size can be properly computed for the `MPS` bytecode instruction.

It seems to me that HarfBuzz should provide an interface for setting and retrieving the point size – AFAICS, it's not needed one level below (except for `MPS`).

**Comment by behdad** [comment]
HarfBuzz already has that.  So, need raqm API maybe?  @khaledhosny

**Comment by khaledhosny** [comment]
I’m not sure I understand the issue here, but if @brawer can propose the API he wants, I’ll merge it.

**Comment by behdad** [comment]
We want `hb_font_set_ptem` called on `hb_font_t`.
