### ISSUE TITLE
Backstop mechanism for disabling HB-AAT?

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1278]
When shipping HarfBuzz AAT, I would prefer to have a backstop mechanism for un-shipping HarfBuzz AAT if we discover issues in the field. After experimenting with font-format detection on the Blink side, I noticed, that HarfBuzz still seems to use the CoreText backend for AAT fonts if hb-coretext.* are built. 

Can we keep this behaviour until we've gone through one Chrome stable cycle? In that case, I would only need to modify one switch in the HarfBuzz BUILD.gn file to build and link hb-coretext.cc to revert to the old behavior.

Is this assumption correct?

**Comment by ebraminio** [comment]
I think you have right to want that, I wonder if locally applying is also a possibility as if you put false on apply_morx, apply_kerx and apply_trak on [here](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape.cc#L90-L119) it disables AAT shaping (something like `plan.apply_kerx = true; plan.apply_morx = true; plan.apply_trak = true;` at the ending)

**Comment by drott** [comment]
Currently, if I build hb-coretext.* trak values match what Safari does for our 
https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/text/mac-system-ui-trak.html test case, so it seems to do the job? Not sure the additional flag patching is needed?

**Comment by ebraminio** [comment]
Aha, now I see. You need to modify shapers, basically `hb_shape_full` instead `hb_shape` [here](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/fonts/shaping/harfbuzz_shaper.cc?g=0&l=240) I guess.

**Comment by ebraminio** [comment]
Or, can you just control HAVE_CORETEXT of chromium build [here](https://cs.chromium.org/chromium/src/third_party/harfbuzz-ng/BUILD.gn?type=cs&q=HAVE_CORETEXT&g=0&l=219)?

**Comment by drott** [comment]
I don't seem to need to do that even, that was what I first tried, but only in case I had a font that had `kerx` and `morx`. I just need to indeed keep the [whole block](https://cs.chromium.org/chromium/src/third_party/harfbuzz-ng/BUILD.gn?type=cs&q=HAVE_CORETEXT&g=0&l=214)  including the HAVE_CORETEXT.

Yes, this seems to work, this issue is just to confirm that we can keep this until HB AAT in Chromium has settled.

Just to note, I kicked [another bot run](https://chromium-review.googlesource.com/c/chromium/src/+/1275945), but I don't think we're there yet until we have a good story for the [mac-system-ui-trak.html](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/text/mac-system-ui-trak.html) test case. That still looks wrong with HB AAT, because of too wide spacing between the Y and o.

**Comment by ebraminio** [comment]
Just to note, https://github.com/harfbuzz/harfbuzz/blob/38a7a8a89ed035a1d1fc34a675a1860ad660b6ff/src/hb-shaper-list.hh#L39 is the place CoreText AAT, the shaper that shapes with CoreText only if `kerx`, `morx` and `trak` available defined. I guess patching that is easier than using hb_shape_full.

> That still looks wrong with HB AAT, because of too wide spacing between the Y and o.

Understandable

**Comment by behdad** [comment]
> Can we keep this behaviour until we've gone through one Chrome stable cycle?

Yes, the coretext_aat will stay there till we are confident about our AAT shaping.

**Comment by ebraminio** [comment]
So lets close this. Thanks
