### ISSUE TITLE
BCP 47 language handling / API

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1286]
As suggested by Behdad [here](https://github.com/harfbuzz/harfbuzz/pull/730#issuecomment-430382266), can we now remove [this line of TODO](https://github.com/harfbuzz/harfbuzz/blob/c93d379bf2414eb6ee6d38fb9753ddf818a777ea/TODO#L18)?

**Comment by dscorbett** [comment]
The way I read Behdad’s comment, that TODO has been done and can be removed, and “Getting most-likelly language from script, and scripts from language” is a separate issue.

**Comment by ebraminio** [comment]
Thanks
