### ISSUE TITLE
[uniscribe] Use of deprecated symbol

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1289]
../../src/hb-uniscribe.cc:846:94: warning: ‘hb_tag_t hb_ot_tag_from_language(hb_language_t)’ is deprecated: Use 'hb_ot_tags_from_script_and_language' instead [-Wdeprecated-declarations]

**Comment by khaledhosny** [comment]
Fixed in 252632c477b963f305116d69fcafacd8bf7b97bf.
