### ISSUE TITLE
A few missing glyphs in Apple Emoji Font

### ISSUE THREAD

**Issue by ubitux** [harfbuzz/harfbuzz#1292]
The following glyphs are missing/misshaped when using Harfbuzz shaping on `Apple Emoji Font.ttf`: `4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 44, 994, 996, 997, 998, 1000, 1001, 1003, 1005, 1006`

Here is the glyph 1000 with Harfbuzz 2.0.2 on Linux:

```
% hb-shape 'Apple Color Emoji.ttf' '👨<200d>👩<200d>👧<200d>👦'
[u1F46A.0.MWG=0+800|space=0+0|u1F466.0=0+800]
```

Same one with Coretext shaping on Mac:

```
% hb-shape 'Apple Color Emoji.ttf' '👨<200d>👩<200d>👧<200d>👦'
[u1F46A.0.MWGB=0+800]
```

**Comment by behdad** [comment]
Thanks!  Do you have a comprehensive list of the ligatures you can contribute for testing?

**Comment by behdad** [comment]
Humm.  Works for me:
$ ./hb-shape 'AppleColorEmoji.ttf' --font-funcs=ot -u U+1F468,200d,U+1F469,200d,U+1F467,200d,U+1F466 
[u1F46A.MWGB=0+800]

Can you double-check?  Can you try with HarfBuzz master?  Though, I don't remember changing anything regarding these.  What's the font file size / checksum you have?

**Comment by ubitux** [comment]
```
% git describe
2.0.2-53-ge1b8e933
% util/hb-shape 'Apple Color Emoji.ttf' --font-funcs=ot -u U+1F468,200d,U+1F469,200d,U+1F467,200d,U+1F466
[u1F46A.0.MWG=0+800|space=0+0|u1F466.0=0+800]
```

The version of this font is pretty old though (but it's the same one I used to compare with harfbuzz Coretext shaping); it's 66M (69108708) with the following (sha256) checksum:

```
57651bd993f76edc7ce0db67c7b324fdb5a990b04860d7b24a7ed7e14a4c5849  Apple Color Emoji.ttf
```

Should I just share that file?

**Comment by behdad** [comment]
Thanks.  Let me know if they are all fixed.

**Comment by ubitux** [comment]
The following are still not fixed: `4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 44`. They correspond to `# 0 1 2 3 4 5 6 7 8 9 *` followed by VS16.

This can be tested with the following: `for c in $(python -c "print(' '.join('U+%04x,U+FE0F' % ord(x) for x in '#012345679*'))"); do hb-shape 'Apple Color Emoji.ttf' --font-funcs=ot -u $c; done`

Without Coretext:

```
[numbersign=0+800|space=0+0]
[zero=0+800|space=0+0]
[one=0+800|space=0+0]
[two=0+800|space=0+0]
[three=0+800|space=0+0]
[four=0+800|space=0+0]
[five=0+800|space=0+0]
[six=0+800|space=0+0]
[seven=0+800|space=0+0]
[nine=0+800|space=0+0]
[asterisk=0+800|space=0+0]
```

With CoreText:

```
[numbersign=0+1600]
[zero=0+1600]
[one=0+1600]
[two=0+1600]
[three=0+1600]
[four=0+1600]
[five=0+1600]
[six=0+1600]
[seven=0+1600]
[nine=0+1600]
[asterisk=0+1600]
```

**Comment by behdad** [comment]
Are those same glyphs, or the glyphs have duplicate names?  What's the output with --no-glyph-names?

**Comment by brawer** [comment]
Might be worth testing against all valid Emoji sequences?
https://unicode.org/emoji/charts/full-emoji-list.html
https://unicode.org/emoji/charts/full-emoji-modifiers.html
http://unicode.org/Public/emoji/11.0/

**Comment by behdad** [comment]
Hah.  So the actual glyph is the same.  It's just spacing that differs?

**Comment by behdad** [comment]
That we leave a space glyph and CoreText does is expectd.  The advance width difference isn't.

**Comment by behdad** [comment]
Humm.  That font doesn't even have a kerx table.  Something unusual is going on.  I have no idea what.

**Comment by ebraminio** [comment]
i remember there was a lowdpi hidpi issue on Chrome on macOS pretty sinilar to what is described here happenning with Apple Emoji font, may the info will help.

**Comment by ebraminio** [comment]
May unrelated, does `hb-shape`, freetype or anyone considers `originOffsetX`, `originOffsetY` value? https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6sbix.html

**Comment by ubitux** [comment]
So, mmh, I misinterpreted my results and made a mistake by saying the glyphs of "#012345679*" were somehow missing. Allow me to correct myself: the only issue remaining here is that the Variation Selectors do not shape as expected: VS-15 (`FE0E`) and VS-16 (`FE0F`) are respectively expected to shape the emojis as text or as emoji (see previously shared https://www.unicode.org/Public/emoji/11.0/emoji-variation-sequences.txt). Harfbuzz seems to raise 2 glyphs (one for the emoji, and the glyph number `3`), while CoreText doesn't (and instead provides a different x-spacing).

The reason I raised "#012345679*" as problematic was because my code was filtering out ASCII characters, and since Harfbuzz was always raising more than one glyph for a given combination, they were never considered valid emojis. But basically, the issue here applies to every emojis used with VS-15 and VS-16.

I think this issue can be closed (because it's not about missing glyphs anymore, this has been fixed), but the variations selector issue remains to be fixed. I'll open a new issue if this one is closed.

**Comment by behdad** [comment]
The VS-15 / VS-16 remaining as glyph3 is NOT a problem.  You can ask HB to remove them by passing `--remove-default-ignorables` to hb-shape.  Also, what font to choose for them based on the VS is above the shaping engine.  That happens in higher levels.  So, the only remaining question is why does CoreText widen the digit if VS-15 follows, when the font has no positioning tables whatsoever.  I bet someone wrote some custom logic to do this...  I'll ask my Apple contacts.

**Comment by behdad** [comment]
I asked Ned and he gave me a hint.  It's possible that when you are adding VS-15 CoreText is switching to its own color emoji font and hb-coretext fails to detect.  Is the AppleColorEmoji font you are testing with the same as the system one you are on?

**Comment by ubitux** [comment]
> The VS-15 / VS-16 remaining as glyph3 is NOT a problem. You can ask HB to remove them by passing `--remove-default-ignorables` to hb-shape.

Oh, thanks. Great, this indeed reduces the differences with CoreText.

> Is the AppleColorEmoji font you are testing with the same as the system one you are on?

No it's not, it's an old copy.

> It's possible that when you are adding VS-15 CoreText is switching to its own color emoji font and hb-coretext fails to detect.

I traced `hb-shape` and it doesn't seem to be the case:

```
58949/0x69cdd:  open("/dev/dtracehelper\0", 0x2, 0xFFFFFFFFE7D80CF0)             = 3 0
58949/0x69cdd:  open("Apple Color Emoji.ttf\0", 0x0, 0x0)                = 3 0
58949/0x69cdd:  open("/usr/local/bin/hb-shape\0", 0x0, 0x1FF)            = 3 0
58949/0x69cdd:  open("/usr/share/icu/icudt59l.dat\0", 0x0, 0x0)          = 3 0
```

Last thing: thanks to `--remove-default-ignorables` I was able to spot one more difference with CoreText:

With CoreText:

```
% hb-shape 'Apple Color Emoji.ttf' --remove-default-ignorables --font-funcs=ot -u 'U+1F3F4,U+E0067,U+E0062,U+E0065,U+E006E,U+E0067,U+E007F'
```

Without CoreText:

```
% hb-shape 'Apple Color Emoji.ttf' --remove-default-ignorables --font-funcs=ot -u 'U+1F3F4,U+E0067,U+E0062,U+E0065,U+E006E,U+E0067,U+E007F'
[u1F3F4=0+800]
```

This sequence corresponds to one the three Emoji Tag Sequence:

```
# Emoji Tag Sequence: See Annex C of TR51 for more information.

1F3F4 E0067 E0062 E0065 E006E E0067 E007F; Emoji_Tag_Sequence; England                                     #  7.0  [1] (🏴󠁧󠁢󠁥󠁮󠁧󠁿)
1F3F4 E0067 E0062 E0073 E0063 E0074 E007F; Emoji_Tag_Sequence; Scotland                                    #  7.0  [1] (🏴󠁧󠁢󠁳󠁣󠁴󠁿)
1F3F4 E0067 E0062 E0077 E006C E0073 E007F; Emoji_Tag_Sequence; Wales                                       #  7.0  [1] (🏴󠁧󠁢󠁷󠁬󠁳󠁿)
```

I'm not sure what's the correct behaviour here, but basically CoreText doesn't raise the black flag, while Harfbuzz does. This might not be expected.

**Comment by behdad** [comment]
I'm going to close this now.  Not sure about the last comment.  For remaining issues, please open new issues.

**Comment by ebraminio** [comment]
Similar: #1420
