### ISSUE TITLE
[CMake] harbuzz-icu not created

### ISSUE THREAD

**Issue by donny-dont** [harfbuzz/harfbuzz#1293]
When compiling with ICU support in CMake the harbuzz-icu library is not created. Not sure if this is by design or just an oversight.

**Comment by ebraminio** [comment]
Right, it is not generating a separate library and that is not intended, feel free if you like to provide a patch :)

**Comment by donny-dont** [comment]
Will do thanks @ebraminio!

**Comment by khaledhosny** [comment]
CMake is being phased-out.
