### ISSUE TITLE
[aat] Provide a way to disable `trak` and other AAT features

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1303]
Spun off from https://github.com/harfbuzz/harfbuzz/issues/1263#issuecomment-431873761

We need a way to disable AAT features, such as trak. 

#1296 is an initial PR going into this direction.

**Comment by drott** [comment]
Works for me, thanks! 

https://roettsch.es/chancery_no_trak.txt
https://roettsch.es/chancery_no_trak.png

**Comment by drott** [comment]
Is my understanding correct that additional features inside `morx` or `kerx` can be controlled using feature arguments, according to the existing mappings that are now stored in [hb-aat-layout.cc](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-aat-layout.cc#L44)?

**Comment by behdad** [comment]
That's not hooked up yet, no.

I can look into it. Though probably only for whole buffer, not ranges.

**Comment by drott** [comment]
Ok, then let's reopen this. For whole buffer would be sufficient for Chrome.
