### ISSUE TITLE
[aat] Expose 'feat' table

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1304]
I don't think we are ever going to expose it in API.  Suggest remove.

**Comment by khaledhosny** [comment]
Can’t we expose the feature name ids in `hb_ot_layout_feature_get_name_ids()`?

**Comment by behdad** [comment]
The feature's don't map straightforward.  It's doable, I'm just not sure if it's worth the effort.  Can leave it for a while longer see if it happens.

**Comment by drott** [comment]
I need to determine what smcp and c2sc features the font has, similar to https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/fonts/opentype/open_type_caps_support.cc?sq=package:chromium&g=0&l=105  but for AAT. 

But I found a way to implement that based on CoreText and CTFontDescriptor API.

For example `CTFontDescriptorCopyAttribute(font_descriptor, kCTFontFeaturesAttribute);` gives me a dictionary of stuff that's in the feat table. 

I can scan for kLetterCaseType with kSmallCapsSelector and kLowerCaseType and kUpperCaseType with their respective enabled selectors.

So using CoreText for checking which small-caps parts I need to synthesise might be sufficient.

**Comment by jfkthame** [comment]
> I need to determine what smcp and c2sc features the font has....
> So using CoreText for checking which small-caps parts I need to synthesise might be sufficient.

That won't be available as a solution for handling AAT fonts on other platforms than macOS, now that harfbuzz can shape them on all platforms.

**Comment by drott** [comment]
> That won't be available as a solution for handling AAT fonts on other platforms than macOS, now that harfbuzz can shape them on all platforms.

Good point, thanks. I agree. For Chrome, it might be sufficient as a start though. So small caps / c2sc feature detection for AAT fonts would not work on non Mac platforms, which is probably acceptable in the first iteration of switching to native HarfBuzz AAT.

**Comment by behdad** [comment]
Okay, we'll expose API for this then.

**Comment by behdad** [comment]
@ebraminio Want to take this on?

**Comment by behdad** [comment]
https://github.com/harfbuzz/harfbuzz/issues/1342 shows CoreText's abstraction of 'feat' table, which is a direction translation.

**Comment by ebraminio** [comment]
> #1342 shows CoreText's abstraction of 'feat' table, which is a direction translation.

I got the idea from 'ftxdumperfuser' but I found objc's attributes system interesting also.

Now that Chromium doesn't need it much I guess we can wait for another client (maybe Scribus or InDesign) request.

**Comment by ebraminio** [comment]
> [..] Chromium doesn't need it much [..]

As https://github.com/harfbuzz/harfbuzz/commit/40b19fd46951e2f9b402e59e1fbbf06fde7ecd61

**Comment by behdad** [comment]
I think @drott still likes to be able to query the font.

**Comment by ebraminio** [comment]
Ok so, lets start from something,

```

/**
 * hb_aat_type_t:
 *
 * Feature identifier
 *
 * Since: REPLACEME
 */
typedef unsigned int hb_aat_feature_type_t;

/**
 * hb_aat_feature_t:
 *
 * Value a feature can have
 *
 * Since: REPLACEME
 */
typedef unsigned int hb_aat_feature_setting_t;

/**
 * hb_aat_feature_option_record_t:
 *
 * Feature type record
 *
 * Since: REPLACEME
 **/
typedef struct
{
  hb_bool_t is_default;
  hb_aat_feature_setting_t setting;
  hb_ot_name_id_t name_id;
} hb_aat_feature_option_record_t;

unsigned int
hb_aat_get_feature_settings (hb_face_t *face,
			     hb_aat_feature_type_t identifier,
			     hb_bool_t *is_exclusive, /* OUT */
			     unsigned int *records_count, /* IN/OUT.  May be NULL */
			     hb_aat_feature_option_record_t *records_buffer);
```

`hb_aat_feature_type_t` and `hb_aat_feature_setting_t` should be used internally also, for example on https://github.com/harfbuzz/harfbuzz/blob/52a00cd87f63c8ab32413a1a9ce792a3e2ec84e2/src/hb-aat-layout-morx-table.hh#L956-L957 als

**Comment by ebraminio** [comment]
Client should know whether the options group are exclusive or not, to decide to show radiogroup or combobox, in GUI terms. Or, let it deduce that if one of the records is already default?

**Comment by jfkthame** [comment]
> Clients should know whether the options group is exclusive or not, to decide to show radiogroup or combobox, in GUI terms. Or, let it deduce that if one of the records is already default?

If I'm understanding this properly, the client cannot deduce for itself whether the group is exclusive. A non-exclusive feature can have one (or more, or zero) of its options enabled by default.

**Comment by ebraminio** [comment]
There is not default enabled on non-exclusive cases AFAIK but didn't go on removing exclusive yet, have a look #1346 :)

**Comment by jfkthame** [comment]
Ah, right - this is about the default for exclusive features only; whether non-exclusive settings are enabled by default just depends on the flags in the mort/morx table.

So for the exclusive case, would it make sense to return a single default_index value, rather than putting an is_default flag into every option? And then we could also use default_index=-1 to indicate non-exclusive, I guess.

**Comment by ebraminio** [comment]
Great. Applied on #1346 except it is not feature index but feature setting value itself because I felt index makes less sense when we have iteration and I should've over the rest of the records to find the default one. Make have a look if looks good. Thanks

**Comment by KrasnayaPloshchad** [comment]
> Now that Chromium doesn't need it much I guess we can wait for another client (maybe Scribus or InDesign) request.

And LibreOffice too.

**Comment by ebraminio** [comment]
Fixed on https://github.com/harfbuzz/harfbuzz/commit/926f512f354835f8323bb2c2e58789dd918a9b65
