### ISSUE TITLE
error: use of undeclared identifier 'bzero'

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#1308]
harfbuzz 2.0.2 builds fine on macOS High Sierra when building for 64-bit, but if I build 32-bit (using `-arch i386` in `CFLAGS`, `CXXFLAGS`, `LDFLAGS`) I get this curious failure, apparently in the system headers:

```
In file included from hb-coretext.cc:34:
In file included from ./hb-coretext.h:37:
In file included from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:63:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/MacMemory.h:1633:85: error: use of undeclared identifier 'bzero'
  static inline void BlockZero(void *destPtr,Size byteCount) { if ( byteCount > 0 ) bzero( destPtr, (size_t)byteCount ); }
                                                                                    ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/MacMemory.h:1643:93: error: use of undeclared identifier 'bzero'
  static inline void BlockZeroUncached(void *destPtr,Size byteCount) { if ( byteCount > 0 ) bzero( destPtr, (size_t)byteCount ); }
                                                                                            ^
2 errors generated.
```

This didn't happen with harfbuzz 1.x, nor have I seen this when building any other software 32-bit, which makes me think it is a harfbuzz problem, not a bug in the system headers.

The relevant parts of `<MacMemory.h>` that call `bzero` are inside an `#if ! __LP64__` which explains why the problem is not seen on 64-bit.

`<MacMemory.h>` includes `<strings.h>` which is where `bzero` is supposed to be defined, and it is, but it's inside an `#if !defined(_POSIX_C_SOURCE) || _POSIX_C_SOURCE < 200809L`. Your src/hb.hh header defines `#define _POSIX_C_SOURCE 200809L` which is why `bzero` doesn't get defined. I don't really understand `_POSIX_C_SOURCE` so I can't offer advice on the right way to fix this. Harfbuzz changed `_POSIX_C_SOURCE` to this value in e3a15d0c6d088963e61f7fbebe25e1096d8e2903, but that was in January and has been included in harfbuzz 1.7.5 and later, which doesn't have this build problem. Maybe harfbuzz 2.0.2 is using more parts of the macOS system headers than 1.9.0 did. I know harfbuzz 2 added support for macOS dfont files but I didn't examine the changes that were made to accomplish that.

It's important to be able to build harfbuzz 32-bit, even on modern 64-bit Macs, because it is in the dependency chain of wine which at this point must still be built 32-bit in order to run 32-bit Windows software.

**Comment by ebraminio** [comment]
Didn't looked at this yet just but want to let you know about https://github.com/harfbuzz/harfbuzz/commit/e1b8e93 personally don't like we are not going to support the compiler anymore, I wish we can find a solution bring back the bots, and you can dedicate any bot on that file to environments you like harfbuzz be tested by just editing the .circleci/config.yml.

**Comment by behdad** [comment]
No idea.  We didn't change our includes much, nor do we use bzero.

**Comment by HinTak** [comment]
I don't think wine depends on harfbuzz - afaik wine's uniscribe implementation does not use harfbuzz. You are perhaps experiencing 2nd dependency via freetype, which wine does depend on. Build freetype without harfbuzz and you are probably going to be fine.

**Comment by ebraminio** [comment]
How Wine dependency is brought up? It doesn't harfbuzz AFAIK also.

**Comment by khaledhosny** [comment]
Does not look like there anything actionable here.

**Comment by ryandesign** [comment]
Please reopen. harfbuzz 2 cannot be compiled 32-bit on macOS, which is a regression from harfbuzz 1. I don't want to update harfbuzz in MacPorts to version 2 while this loss in functionality exists.

harfbuzz is in the dependency chain of wine in MacPorts, which means I cannot at present update harfbuzz to version 2 without making wine unbuildable, which I don't want to do. wine links with openal-soft, which dynamically loads the pulseaudio library, which declares a library dependency on gtk3 (although [I'm not clear yet on how pulseaudio uses gtk3](https://trac.macports.org/ticket/57643)), which links with pango, which links with harfbuzz.

**Comment by khaledhosny** [comment]
Re-opening won’t magically fix the issue. `bzero` is not used anywhere in HarfBuzz source tree, so whatever using `bzero` is the culprit which is a system header from that error above. But since this is starting from the Core Text shaper, and we now have native support for AAT fonts, you can alternatively build with `--with-coretext=no`.

**Comment by behdad** [comment]
I support disabling CoreText with latest HarfBuzz builds.

**Comment by khaledhosny** [comment]
May be we should change the default from `auto` to `no`?

**Comment by behdad** [comment]
> May be we should change the default from `auto` to `no`?

Works for me.  Go ahead.

**Comment by khaledhosny** [comment]
The default is `no` already actually and seems to have always been like that.

**Comment by ryandesign** [comment]
> But since this is starting from the Core Text shaper, and we now have native support for AAT fonts, you can alternatively build with `--with-coretext=no`.

Ok, we are indeed specifying `--with-coretext` in MacPorts, and it does successfully build 32-bit if we don't do that. So that's good to know.

But we enabled the CoreText shaper earlier this year, because that was required in order to build [kitty](https://github.com/kovidgoyal/kitty). I've asked the developer of kitty if they could do without the CoreText shaper (https://github.com/kovidgoyal/kitty/issues/1187), and they are not aware how that would be accomplished. Can you offer any assistance?

**Comment by behdad** [comment]
If kitty's using our CoreText constructors, guess there's nothing to change for them right now.  If you have clues as to how to fix this bug, we are open to it, but otherwise can't help.

**Comment by ryandesign** [comment]
Using `git-bisect` I was able to find that the problem was introduced by 3f08750fa6772e7e342b96192b84cb9963f7335b. Prior to this change, HarfBuzz only set `_POSIX_C_SOURCE` in hb-blob.cc. After this change, the setting of `_POSIX_C_SOURCE` was moved to hb.hh, which is included in many more HarfBuzz files, including those involved with the CoreText backend. As I [mentioned above](#issue-373374765), the macOS headers included in the HarfBuzz CoreText files vary their behavior depending on the value of `_POSIX_C_SOURCE`.

I tried reverting that commit, and it seemed to fix the problem. A universal build of harfbuzz 2.3.0 with the CoreText backend then succeeds on macOS High Sierra. How would you feel about reverting that commit? The commit message didn't explain why the change was made. As I mentioned above, I don't know much about `_POSIX_C_SOURCE` and don't know what other consequences this might have.

**Comment by behdad** [comment]
Fixed.

**Comment by ryandesign** [comment]
Thanks!
