### ISSUE TITLE
tai le shaping problem

### ISSUE THREAD

**Issue by mhosken** [harfbuzz/harfbuzz#1312]
I'm confused by what I am seeing with regard to NotoSansTaiLe-Regular.ttf:

```
hb-shape --font-file=NotoSansTaiLe-Regular.ttf --script="tale" --unicodes="1952 1964 0300 1964" -V

trace: start lookup 0	buffer: [uni1952=0|uni1964=1|uni0300=1|uni1964=3]
trace: end lookup 0	buffer: [uni1952=0|uni1964=1|uni0300=1|uni1964=3]
trace: start lookup 1	buffer: [uni1952=0|uni1964=1|uni0300=1|uni1964=3]
trace: end lookup 1	buffer: [uni1952=0|uni1964=1|uni0300=1|uni1964=3]
trace: start lookup 0	buffer: [uni1952=0+536|uni1964=1+549|uni0300=1+0|uni1964=3+549]
trace: end lookup 0	buffer: [uni1952=0+536|uni1964=1+549|uni0300=1@976,0+0|uni1964=3+549]
[uni1952=0+536|uni1964=1+549|uni0300=1@427,0+0|uni1964=3+549]
```

I would expect to see lookup 1 change the `uni0300` to `uni0300.space`. I've tried this in master, 1.9.0, 1.8.8 and 1.8.0.

**Comment by behdad** [comment]
umm.  I get that with the version of the font from noto-fonts repo.  Which version you have?

```
$ hb-shape --font-file=NotoSansTaiLe-Regular.ttf --script="tale" --unicodes="1952 1964 0300 1964" -V
trace: start lookup 0	buffer: [uni1952=0|uni1964=1|uni0300=1|uni1964=3]
trace: end lookup 0	buffer: [uni1952=0|uni1964=1|uni0300=1|uni1964=3]
trace: start lookup 1	buffer: [uni1952=0|uni1964=1|uni0300=1|uni1964=3]
trace: end lookup 1	buffer: [uni1952=0|uni1964=1|uni300.space=1|uni1964=3]
trace: start lookup 0	buffer: [uni1952=0+1098|uni1964=1+1125|uni300.space=1+904|uni1964=3+1125]
trace: end lookup 0	buffer: [uni1952=0+1098|uni1964=1+1125|uni300.space=1+904|uni1964=3+1125]
[uni1952=0+1098|uni1964=1+1125|uni300.space=1+904|uni1964=3+1125]
```

**Comment by mhosken** [comment]
Built harfbuzz against master. Pulled from noto fonts in master branch and I run the command in both hinted/ and unhinted/ and I still get my results rather than what you get. I would love to get your results! It's bad enough debugging this kind of thing locally, but by github issue, it's nigh on impossible! All ideas welcomed.

**Comment by behdad** [comment]
You know you can compile with "make CPPFLAGS=-DHB_DEBUG_APPLY=100"?
That helps a lot, specially the line numbers of where it decides to return false.

**Comment by behdad** [comment]
My noto-fonts was not uptodate.  I'm pulling down now and rechecking.

**Comment by behdad** [comment]
With noto-fonts master I don't get either!

**Comment by behdad** [comment]
Indeed, it works before this commit: https://github.com/googlei18n/noto-fonts/commit/31470525463038cb0995249abc171c744fb7f18f

Debugging.  cc @marekjez86

**Comment by behdad** [comment]
Humm.  The GSUB diff between the two versions is very curious:
```
--- NotoSansTaiLe-Regular.ttx	2018-10-25 17:05:27.040530676 -0700
+++ NotoSansTaiLe-Regular#1.ttx	2018-10-25 19:58:19.879040658 -0700
@@ -6,7 +6,7 @@
     <ScriptList>
       <!-- ScriptCount=1 -->
       <ScriptRecord index="0">
-        <ScriptTag value="DFLT"/>
+        <ScriptTag value="tale"/>
         <Script>
           <DefaultLangSys>
             <ReqFeatureIndex value="65535"/>
@@ -98,7 +98,7 @@
         <LookupFlag value="0"/>
         <!-- SubTableCount=1 -->
         <SingleSubst index="0" Format="1">
-          <Substitution in="uni0300" out="uni300.space"/>
+          <Substitution in="uni0300" out="uni0300.space"/>
           <Substitution in="uni0301" out="uni0301.space"/>
           <Substitution in="uni0307" out="uni0307.space"/>
           <Substitution in="uni0308" out="uni0308.space"/>
```

**Comment by behdad** [comment]
Oh I know what's going on.  We recently made USE apply ccmp within syllables only.  And this font update sends the font to USE.  Finding the commit that we made that decision.  cc @jfkthame

**Comment by marekjez86** [comment]
@behdad : sounds like I might need to rebuild everything
@mhosken : you found a hole in our testing. Thank you for catching this

**Comment by behdad** [comment]
>  We recently made USE apply ccmp within syllables only.

Faulty memory maybe?  Looks like it has always been like that.

**Comment by behdad** [comment]
> @behdad : sounds like I might need to rebuild everything

Would be nice if you can improve testing to detect something like this, but not clear whose bug it is yet.  It sounds like HarfBuzz's behavior is expected.  Let us figure out what the correct fix is before taking any actions.

So, U+0300 doesn't fit in USE grammar, that's expected, right?

**Comment by behdad** [comment]
Umm.  Stil, backtrack/lookahead should go beyond syllable.  So, yeah, this is not expected?

**Comment by behdad** [comment]
> Umm. Stil, backtrack/lookahead should go beyond syllable. So, yeah, this is not expected?

Also faulty memory?  Looks like even backtrack/lookahead are matched within syllable.  @jfkthame am I misremembering anything?

**Comment by jfkthame** [comment]
> Looks like even backtrack/lookahead are matched within syllable

I don't recall us making changes in this area recently, so I'd be surprised if the behavior had changed. Might be interesting to see what tests fail if we were to change this? ISTR we may have seen examples where the restriction was expected.

**Comment by jfkthame** [comment]
> So, U+0300 doesn't fit in USE grammar, that's expected, right?

I'm inclined to think it (and any other similar accents that are used) should probably be added, though it may be tricky to decide exactly where in the grammar to accept them.

Or maybe a Tai Le-specific accent character should be encoded for this purpose? I'm reminded of a recent discussion re the use of a macron in Oriya script, where the preferred suggestion was to propose a new character.

**Comment by behdad** [comment]
> > Looks like even backtrack/lookahead are matched within syllable
> 
> I don't recall us making changes in this area recently, so I'd be surprised if the behavior had changed. Might be interesting to see what tests fail if we were to change this? ISTR we may have seen examples where the restriction was expected.

Yeah I think we did it because of Indic results.  I can go look back, or try and see what breaks.

But maybe we can reconsider it for USE, and possibly ask MS to change the spec.

Re grammar I agree letting Latin marks in doesn't sound like a good fit.

**Comment by behdad** [comment]
Also, now that this is going through USE, ccmp is not the best feature for this.  Later features (abvs?) etc are not bound to syllables.  I think I consider that the right resolution for the issue at hand.

**Comment by behdad** [comment]
> This script is pretty trivial and could easily be handled by DFLT. I would be happy to go that route or route tale through DFLT.

USE spec specified Tai Le as routed there.  So we will do that.  Font designer ALWAYS can choose to use DFLT.  At least with HarfBuzz.

**Comment by Richard57** [comment]
However, going through DFLT is not always an option.  If it were, making a working Tai Tham font would be much easier.  You might just as well say one could always use morx.

**Comment by behdad** [comment]
Anything to do here, @dscorbett?

**Comment by dscorbett** [comment]
No. It’s easy for a Tai Le font to work around this by using the default shaper or by using USE’s presentation features.
