### ISSUE TITLE
API design for exposing image glyphs

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1316]
What the public API of different image glyphs should look like? Do we like to have a unified access to all the three tables (CBDT, sbix, SVG) or separated ones?

If we want former, we should prioritize which tables we should search first which I guess not that common case as who ships two/three tables of color font standard in one font. This is a possiblity if 

    

    hb_blob_t hb_ot_color_create_blob_for_glyph
      (hb_font_t *font, /* so we use its ppem, as below [1] */
       hb_codepoint_t glyph,
       hb_tag_t *preferred_types, /* IN, 'svg ', 'png ', or 'jpg '/'png '/'tiff' */ see [2] */
               /* maybe an enum like hb_ot_color_graphic_type instead */
       unsigned int preferred_types_length, /* size of above array */
       hb_tab_t *result_type /* OUT, result time */

[1]: https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color-cbdt-table.hh#L414 and https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color-sbix-table.hh#L75
[2]: https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color-sbix-table.hh#L51

And what about ebdt? Shouldn't be better to consider something useful for monochrome images in fonts (ebdt) now that we are supporting cbdt?

Or if separa5ed ones acceptable there is one exposing SVG
https://github.com/harfbuzz/harfbuzz/pull/1306

Or maybe we can expose SVG separately but to have rest unified? sbix on Apple specification can support PDF also but OT spec has banned that.

Or maybe a separate API for each table?

**Comment by khaledhosny** [comment]
`sbix` can theoretically provide more format (Apple spec has `pdf` IIRC, not sure if any fonts have it), so may be an API for bitmaps and an API for vector formats to be a bit more feature-proof.

**Comment by behdad** [comment]
I believe pdf was removed when sbix was being incorporated into OpenType, but jpg,tif left.  However, very unlikely that anyone will ever use them, or even Apple support them currently...

Given that client would need to be ready to handle this, I'm fine they having to call new API for new formats if ever supported.  Or we can add MIME_TYPE like cairo does it.  But yeah maybe vector vs bitmap distinction is good to have, since bitmap involves size selection.  I don't want to overengineer it though if it's only SVG and PNG that are ever going to be used.

**Comment by behdad** [comment]
Umm. CBDT also allows raw images.  Even that I'm not sure if I care about exposing.  I'm happy with just SVG and PNG.

**Comment by ebraminio** [comment]
Given SVG, unlike the others, doesn't depend on `ppem`, I think it can go separate. Maybe this for others?

```
hb_blob_t hb_ot_color_create_blob_for_glyph
  (hb_face_t *face, unsigned int ppem, /* or hb_font_t instead the two? */
   hb_codepoint_t glyph,
   hb_ot_color_image_t *preferred_type); /* in/out */
enum hb_ot_color_image_t { RAW, PNG, TIFF, JPEG, ... };
```

Or maybe that should include SVG also?

My first comment proposal was similar to HTTP headers, request have `Accept: */*` and response have `content-type: text/javascript` for example. Maybe we can defer such API to later and expose only SVG and PNG separately.

**Comment by ebraminio** [comment]
> Having one preferred type input doesn't help.

c#0 was asking for an array of types.

> For SVG, take hb-face still I guess.

The only challenge is if we want to over-engineer it and return all the things by one API.

>> Or maybe a separate API for each table?
> No.

No problem. not my preference also, but in case we have a _png, we need to decide whether to choose choose between CBDT or sbix if both exist at the same time.

**Comment by behdad** [comment]
> > Having one preferred type input doesn't help.
> 
> c#0 was asking for an array of types.

Yeah, not needed.  When we add API for other types later, client can call them in succession.  If we ever add more than just PNG/SVG, or even with just that and colr/cpal, we can add API to query image types supported for a font and for a glyph.

> > For SVG, take hb-face still I guess.
> 
> The only challenge is if we want to over-engineer it and return all the things by one API.

What's all things?  I'm only thinking if it makes sense to fill in for the user the id name of the glyph they should be looking for in the SVG.

> > > Or maybe a separate API for each table?
> 
> > No.
> 
> No problem. not my preference also, but in case we have one _png API, we need to decide whether to choose between CBDT or sbix first if both exist at the same time no matter one considers it superficial.

We make that kind of decisions all the time... morx/GSUB.  If HB_OPTIONS=aat is set, we prefer sbix, otherwise CBDT.  That's the tiniest thing to worry about.

So, are you going to propose a fully fleshed API here in a comment, or I should do that?

**Comment by behdad** [comment]
> > We also need to return the matched ppem so client knows how much to scale the image.
> 
> Do they really need it? Shouldn't they be able to measure and resize the image anyway?

How would you do that? Say, I give you a W x H image.  You have the font ptem.  What do you do exactly? :D

**Comment by behdad** [comment]
> > What do you do exactly?
> 
> The same with SVG I guessed :) I see now I guess

:).

If both sbix and CBDT have one ppem for both directions, let's just have one.  I'm not sure about sbix.

> What do to with sbix xOffset yOffset and resolution? Those should be used somewhere I guess

Right.  The origin needs to be output as well.

**Comment by ebraminio** [comment]
> If both sbix and CBDT have one ppem for both directions, let's just have one. I'm not sure about sbix.

What if font author defined different ppem for the directions? sbix has only one.

> Right. The origin needs to be output as well.

What is `CBDT` its equivalent, extends?

**Comment by behdad** [comment]
> > If both sbix and CBDT have one ppem for both directions, let's just have one. I'm not sure about sbix.
> 
> What if font author defined different ppem for the directions? Which to return? sbix has only one.

Ok, CBDT has both...  So we return both I guess.  For matching, with sbix, we just take the larger of both direction to match.

> > Right. The origin needs to be output as well.
> 
> What is its `CBDT` equivalent, extents?

bearingX/bearingY and others.
https://docs.microsoft.com/en-us/typography/opentype/spec/eblc#smallglyphmetrics

**Comment by behdad** [comment]
> > 
> 
> bearingX/bearingY and others.
> https://docs.microsoft.com/en-us/typography/opentype/spec/eblc#smallglyphmetrics

Possibly even lsb/tsb from hmtx/vmtx tables.  Let's read FreeType code to figure out.

**Comment by behdad** [comment]
Regarding bearings, we already have glyph extents API, so one *can* call that to position the image.  So, maybe we don't need here?

Donno.  @jfkthame?  I know you are not interested in this work, but can I get your opinion please?

**Comment by ebraminio** [comment]
> Ok, CBDT has both... So we return both I guess. For matching, with sbix, we just take the larger of both direction to match.

Already done on #1318 :)

Maybe you can take the CBDT part on #1318? It is huge, needs some refactoring and am not that familiar with it as was there before me (except the dump part).

**Comment by ebraminio** [comment]
Or give me some time for it before releasing the next version as I wish we support all the Emojis at the same time.

**Comment by behdad** [comment]
> Maybe you can take the CBDT part on #1318? It is huge, needs some refactoring and am not that familiar with it as was there before me (except the dump part).

I'm not excited about doing that!  But yeah, can add it for the one format that NotoColorEmoji does, and we add more later on request.

**Comment by behdad** [comment]
I'm already late for getting a release out.  We don't hold release for features.  Features get merged when they are ready.  I'll happily make a new release when we merge SVG and PNG. :)

**Comment by behdad** [comment]
If we are expecting user to call get_glyph_extents to figure out the bearings, I suppose they can use the width/height from that to scale the image as well...

**Comment by behdad** [comment]
Yes, let's fully flesh out SVG and PNG api and then get them in together.  Both are nontrivial as in have open questions.  I need to read SVG spec again re glyph id thing to see if we should expose that.  PNG has bearings and ptem issue as discussed above.  Though now I'm liking my get_glyph_extents proposal more.

**Comment by ebraminio** [comment]
#1319 which hopefully can easily apply result of the discussion here if we reach to some consensus.

**Comment by behdad** [comment]
> #1319 which hopefully can easily apply result of the discussion here if we reach to some consensus.

Thanks.  So, two points:

- For SVG.  Since client is supposed to look for "glyphXXX" id in the returned document, to remind them, do we want the API to also optionally return the identifier name they need to look up?  Ie. fill up a buffer with "glyphXXX" for them?  This is purely to remind them....

- For PNG.  Can we remove the ptem, since we decided the bearings need to be fetched by calling get_glyph_extents()?  My hunch is that we should have a demo app using this API and try that and see if it works....  I can double-check the code that confirm that indeed the size we return in get_extents is what is needed to scale...  It is by definition though.

**Comment by behdad** [comment]
I thought about this more.  Let's go for the simplest functional API now:
```
HB_EXTERN hb_bool_t
hb_ot_color_has_svg (hb_face_t);

HB_EXTERN hb_blob_t *
hb_ot_color_glyph_reference_svg (hb_face_t, hb_codepoint_t);

HB_EXTERN hb_bool_t
hb_ot_color_has_png (hb_face_t);

HB_EXTERN hb_blob_t *
hb_ot_color_glyph_reference_png (hb_font_t, hb_codepoint_t);
```

Do we want the enum as well?

**Comment by ebraminio** [comment]
Applied on #1319.

Don't know about that enum.

**Comment by ebraminio** [comment]
Removed strike_{x,y}_ppem from the patch but be honest this was what I was thinking a color capable drawing will look like (may completely silly, I wanted to study it more while actually implementing it)

```
if (!is_png && !is_svg)
  draw_glyph(gid, ppem);
else if (is_png) {
  int strike_ppem;
  png := get_png(gid, &strike_ppem);
  resize_scale := strike_ppem * ppem / upem;
  draw_png(scale_png(png, resize_scale));
} else if (is_svg) {
  resize_scale := ppem / upem;
  draw_svg(scale_svg(get_svg(), resize_scale));
}
```

But now I don't know how get_extents should be hooked with the table, specially `SVG` that has nothing about them anyway.

**Comment by behdad** [comment]
Your code is still what will happen for SVG.  For PNG, it will look like this:
```
    hb_glyph_extents_t extents;
    hb_font_get_glyph_extents (font, glyph, &extents);
    draw png, scaling to fit extents' width,height and translate by extents' x/y_bearing.
```
this *does* assume that the extent we are returning is from the PNG.  We should make sure to order our get_extents to do it that way.

**Comment by ebraminio** [comment]
CBDT part apparently is OK, except [this](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color-cbdt-table.hh#L407), and the code obviously should be refactored...

But `sbix`... apparently every color glyph has `glyf` equivalent, not sure it is guaranteed by spec, given different strikes however, we probably should multiply its values to something.

**Comment by behdad** [comment]
> But `sbix` ... apparently on `Apple Color Emoji` every color glyph has `glyf` equivalent, not sure it is guaranteed by spec, given different strikes however, we probably should multiply its values to something from `sbix`, otherwise, no idea.

Right.  'sbix' extents should take over 'glyf' extents IMO.

**Comment by behdad** [comment]
Or maybe doesn't matter.  The two should match.

**Comment by behdad** [comment]
There's no guarantee that the 'glyf' extent should match the sbix extent.  So, we should prefer sbix.

Not sure how to do it with zero cost though.  One extra check per glyph :D umm.

**Comment by behdad** [comment]
Oh, it's glyph_extents.  Performance for that doesn't matter.

**Comment by behdad** [comment]
So yeah, right now, hb-ot-font's glyph_extents is:
```
  const hb_ot_face_data_t *ot_face = (const hb_ot_face_data_t *) font_data; 
  bool ret = ot_face->glyf->get_extents (glyph, extents); 
  if (!ret) 
    ret = ot_face->CBDT->get_extents (glyph, extents); 
  // TODO Hook up side-bearings variations. 
  extents->x_bearing = font->em_scale_x (extents->x_bearing); 
  extents->y_bearing = font->em_scale_y (extents->y_bearing); 
  extents->width     = font->em_scale_x (extents->width); 
  extents->height    = font->em_scale_y (extents->height); 
  return ret; 
} 
```
sbix should be preferred over glyf.

**Comment by behdad** [comment]
It also means, in the reference_png(), we should prefer sbix over CBDT.

**Comment by ebraminio** [comment]
But sbix doesn't provide width and height at all, am I wrong?

**Comment by behdad** [comment]
Humm.  Pull it out of the PNG.  It's trivial.  More reason to just support PNG.

**Comment by behdad** [comment]
> Humm. Pull it out of the PNG. It's trivial. More reason to just support PNG.

https://github.com/behdad/color-emoji/blob/master/png.py#L86

**Comment by behdad** [comment]
Basically, bytes 8..12 are weidth, 12..16 are height.  Zero-indexing.  By byte 8 I mean actually ninth.

**Comment by ebraminio** [comment]
OK. Let me see what I can do.

**Comment by behdad** [comment]
Write a PNGHeader struct and use blob->as<>

**Comment by ebraminio** [comment]
Merged, yay :fireworks:
