### ISSUE TITLE
Only one API for detecting color fonts?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1320]
Before release thought, DirectWrite only has one `IsColorFont` instead https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color.h#L46 and https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color.h#L93 maybe we should do that also before the release?

On that case, hb_ot_color_has_palettes can be replaced with hb_ot_color_palette_get_count, not sure about a solution for https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color.h#L93 however.

![image](https://user-images.githubusercontent.com/833473/47605009-cfc4a080-da0d-11e8-9452-55c1e09f5c7b.png)

Also have a look at the other APIs also.

https://github.com/apitrace/dxsdk/blob/master/Include/dwrite_2.h#L682

**Comment by behdad** [comment]
We should keep has_whatever, but also add one api that returns an enum flag of available formats (layers, png, svg, ...).  that serves as "IsColorFont"

**Comment by ebraminio** [comment]
OK. That case this looks nonessential to me so lets close it till someone actually need it, thanks.
