### ISSUE TITLE
get_extents on other formats of cbdt

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1327]
cbdt obviously needs refactoring and some parts of it may is my fault as I didn't want to touch parts I wasn't familiar. This one shouldn't be missed however, [get_extents](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color-cbdt-table.hh#L432-L447) support only format 17 but [reference_png](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-color-cbdt-table.hh#L476-L499) apparently support others, but the only one available on NotoColorEmoji AFAICS is 17.

**Comment by behdad** [comment]
Implemented Format 18.  Remains Format 19.
