### ISSUE TITLE
Exposing OS/2 table?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#1337]
I’m working on a small project using HarfBuzz and I need to access a couple of fields from `OS/2` table. It is a simple table and I can just read it in my code, but HarfBuzz already reads it for the font extents so I thought to ask if exposing the rest of the table is something HarfBuzz might want to do?

**Comment by behdad** [comment]
If we can model them in a nice way, sure. Which fields?

**Comment by khaledhosny** [comment]
I currently only want sxHeight and sCapHeight, but I guess the API would expose anything. How that API would look is really a tough question, I have been thinking about it and I don’t have an answer. The only similar API I know is [FT_Get_Sfnt_Table](https://www.freetype.org/freetype2/docs/reference/ft2-truetype_tables.html#FT_Get_Sfnt_Table), I like how it can handle newer table versions with additional fields, but I don’t really know if it is a good API design-wise or if it is a good fit for HarfBuzz.

**Comment by brawer** [comment]
Perhaps an API could be based on value tags from the [MVAR table](https://docs.microsoft.com/en-us/typography/opentype/spec/mvar#value-tags)? For example, `xhgt` for OS/2.sxHeight, `cpht` for OS/2.sCapHeight, and `undo` for post.underlinePosition. For a variable font, the implementation would interpolate according to MVAR; for a non-variable font, it would retrieve the value from the respective tables in the font.

```c
HB_EXTERN hb_bool_t
hb_ot_font_get_metrics (hb_font_t *font,
                        hb_tag_t tag,  // eg. hasc, hlgp, undo, xhgt, cpht
                        hb_position_t *position);
```

**Comment by behdad** [comment]
Thanks Sascha.  Yes, that's indeed what I liked before.  A couple changes:
1. The tag should be it's own enum. `hb_ot_metric_t`,
2. API name should say "metric" instead of "metrics".  Not sure if `hb_ot_font_get_metric` or `hb_ot_metric_get`.  Like neither of them.  Anyway, this goes into `hb-ot-metric.h`.

**Comment by khaledhosny** [comment]
`OS/2` has more than metrics, they might not all be useful but why not just expose them all. I guess the enum would then be `hb_ot_os2_field_t` and the function would be `hb_ot_font_get_os2_fields()` or something like that. This can then be a model for other simple tables.

**Comment by behdad** [comment]
I prefer not to expose table by table.

Which OS/2 fields do you need that are not supported by MVAR tags? https://docs.microsoft.com/en-us/typography/opentype/spec/mvar

**Comment by khaledhosny** [comment]
Not currently in this project, but in LibreOffice I need also `fsSelection`. I’m likely to need also need it in this project, in addition `usWeightClass` and`usWidthClass` when I start working on font matching.

**Comment by behdad** [comment]
I prefer to have the metrics API, and expose more things separately.

**Comment by behdad** [comment]
width/wght we can add private MVAR-like tags and fetch using the same API (and hook to variations as well).

**Comment by behdad** [comment]
Why do you rely on fsSelection?

**Comment by khaledhosny** [comment]
In LibreOffice `fsSelection` is checked for the `USE_TYPO_METRICS` bit. In the current project *I think* I’ll need it for the `ITALIC`, `BOLD`, `REGULAR`, and `OBLIQUE` bits.

Edit. I just checked XeTeX, and it uses `OS/2.usWeightClass`, `OS/2.usWidthClass`, `OS/2.fsSelection`, `head.macStyle`, and `post.italicAngle` to classify the fonts, so that is probably what I will need. May be I better read the tables myself first until I’m sure what I need exactly, if we are going to selectively expose table fields.

**Comment by behdad** [comment]
> In LibreOffice `fsSelection` is checked for the `USE_TYPO_METRICS` bit.

Our font-metrics code already takes that into account.

> In the current project _I think_ I’ll need it for the `ITALIC`, `BOLD`, `REGULAR`, and `OBLIQUE` bits.

Right.  Those would be useful.

> Edit. I just checked XeTeX, and it uses `OS/2.usWeightClass`, `OS/2.usWidthClass`, `OS/2.fsSelection`, `head.macStyle`, and `post.italicAngle` to classify the fonts, so that is probably what I will need. May be I better read the tables myself first until I’m sure what I need exactly, if we are going to selectively expose table fields.

Okay, let us know.

**Comment by brawer** [comment]
Weight, width and italic angle sound like candidates for an API that could be modeled around the STAT table; the implementation would fall back to OS/2 if STAT is not present.

**Comment by behdad** [comment]
@ebraminio want to implement the proposed API, with MVAR?

**Comment by ebraminio** [comment]
Sounds interesting!

**Comment by ebraminio** [comment]
My conclusion till this point from the discussion and reading some parts of the specs is the imagined API should be like this and will be placed on `hb-ot-metrics.h`:

```
HB_EXTERN hb_bool_t
hb_ot_font_get_metrics (hb_font_t *font,
                        hb_ot_metrics_t metrics_tag,  // eg. hasc, hlgp, undo, xhgt, cpht
                        hb_position_t *position);
```

And valid values for hb_ot_metrics_t are the ones [here](https://docs.microsoft.com/en-us/typography/opentype/spec/mvar#value-tags) that will be fetched from `mvar` table and polyfilling with OS/2.

Also the ones [here](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg) which will be fetched from [STAT](https://docs.microsoft.com/en-us/typography/opentype/spec/stat), `ital` tag of it will be polyfilled with [fsSelection](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fsselection) bit0/Italic, `wght` with `OS/2.usWeightClass`, `wdth` with `OS/2.usWidthClass`, `slnt` with `OS/2.fsSelection` (bit 9/oblique?) and `opsz` with `OS/2.usLowerOpticalPointSize`/`OS/2.usHigherOpticalPointSize`? So at this point no need for separate API for OS/2 I guess? And should we try [`fvar`](https://docs.microsoft.com/en-us/typography/opentype/spec/fvar) before `STAT`? What to do with name ids STAT has? I mean we should be aware of the API we are designing is not `STAT` oriented but just uses it.

Now that we are here, why not expose [`BASE`](https://docs.microsoft.com/en-us/typography/opentype/spec/BASE) with its tags [tags](https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags) also? Or isn't better we have three separate APIs?

**Comment by brawer** [comment]
Personally I’d find a separate API for stylistic attributes more natural because the returned range is different. Metrics are positions; stylistic attributes are values along variation axes. Personally, I’d also keep `BASE` separate because baseline positions are language-dependent.

**Comment by ebraminio** [comment]
OK so we clearly need three different APIs, back to API design I guess,
* One dealing with values only available at STAT polyfilled with OS/2. And also fvar?
* One for MVAR positions on hb-ot-metrics.h?
* BASE API, also in hb-ot-metrics.h (and expose bsln on hb-aat.h?)

**Comment by behdad** [comment]
Forget about STAT and BASE tables.  Let's define one simple API for MVAR tags for now.

**Comment by ebraminio** [comment]
Sooner or later ot-metrics will be finished, any idea about the other part using tags on https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg on a different API, what should be named? And can I have a digest of what is STAT use, still confused I can say.

**Comment by ebraminio** [comment]
Hehehe

**Comment by ebraminio** [comment]
From `head`,

```
  HBINT16	xMin;			/* For all glyph bounding boxes. */
  HBINT16	yMin;			/* For all glyph bounding boxes. */
  HBINT16	xMax;			/* For all glyph bounding boxes. */
  HBINT16	yMax;			/* For all glyph bounding boxes. */
  HBUINT16	macStyle;		/* Bit 0: Bold (if set to 1);
					 * Bit 1: Italic (if set to 1)
					 * Bit 2: Underline (if set to 1)
					 * Bit 3: Outline (if set to 1)
					 * Bit 4: Shadow (if set to 1)
					 * Bit 5: Condensed (if set to 1)
					 * Bit 6: Extended (if set to 1)
					 * Bits 7-15: Reserved (set to 0). */
```

So `yMin` and `yMax` can be used instead ascender and descender I guess and `macStyle` to polyfill OS/2? (or which one should be prioritized?)

**Comment by behdad** [comment]
> So `yMin` and `yMax` can be used instead ascender and descender I guess

No.

**Comment by ebraminio** [comment]
Its STAT tags part #1459, this should be considered fixed together with #1396 AFAICU.

**Comment by ebraminio** [comment]
Its metrics part is resolved (but needs tweaks), here is style/STAT related part #1468

**Comment by ebraminio** [comment]
Guess we can consider original request of this page fixed with metrics API introduced some releases ago, and #1880 and #1920 are considered its remaining parts. Thanks

**Comment by behdad** [comment]
I thought more and like to expose italicAngle in ot-metrics and font-extents.  I suggest we expose it not as an angle but as, eg for horizontal direction, `scale_x * tan(angle)`.

**Comment by behdad** [comment]
> I thought more and like to expose italicAngle in ot-metrics and font-extents. I suggest we expose it not as an angle but as, eg for horizontal direction, `scale_x * tan(angle)`.

If/when we do that we should also update our fallback mark-positioning to use that to adjust mark x position depending on the y.

**Comment by ebraminio** [comment]
Was thinking about you proposal more in caret sense, apparently italicAngle is considered to have some use other than caret https://github.com/harfbuzz/harfbuzz/issues/1880#issuecomment-517989436 so like to know what is Khaled's use as I don't want its only user reverse our work exactly to access some value it should've accessed easily at the first place and the advantage of hb-style was to query the value first from fvar/STAT/fdsc tables before `post->italicAngle`.

**Comment by behdad** [comment]
Italic angle is used by TeX for mark positioning as well as "italic correction".  While using this for mark positioning is considered fallback behavior in OpenType fonts, Italic correction is a legit thing.
