### ISSUE TITLE
[aat] Tamil shaping fails to combine glyphs

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1348]
I guess something is wrong here, https://chromium-review.googlesource.com/c/chromium/src/+/1275945/33/third_party/WebKit/LayoutTests/platform/mac-mac10.10/fast/text/international/complex-character-based-fallback-expected.png
 
I don't have access to 10.10-11 where the issue shows itself more but I see something on 10.13 also,

bash-3.2$ util/hb-view /Library/Fonts/Tamil\ MN.ttc --shaper coretext தொகுக்கப்பட்டு

bash-3.2$ util/hb-view /Library/Fonts/Tamil\ MN.ttc --shaper ot தொகுக்கப்பட்டு

![image](https://user-images.githubusercontent.com/833473/47912642-a6dd5900-deae-11e8-81cb-0ee36d1e8fa7.png)

Maybe two separate issues, mort on first and morx on second.

**Comment by ebraminio** [comment]
No, probably I am not using the same font as said but there still a difference and some subtle others

**Comment by ebraminio** [comment]
Oh, font funcs let me see

**Comment by ebraminio** [comment]
btw can you see which font on 10.10 and 10.11 is used actually on that test, it shouldn't be Latha, or, is it? Exact version will helpful I guess

**Comment by drott** [comment]
I'll try to figure out which font is used on the 10.10 bot. On 10.13 the browser fallback code, calling AppKit finds "/Library/Fonts/Tamil Sangam MN.ttc", in which it looks correct and not disjointed.

**Comment by ebraminio** [comment]
No difference with --font-funcs=ot

![image](https://user-images.githubusercontent.com/833473/47916909-06426580-debd-11e8-8e48-4c041d4b9583.png)

**Comment by drott** [comment]
However, we do have a reproduction on 10.13 with `/Library/Fonts/Tamil\ MN.ttc` - I am assuming `Tamil Sangam MN` might not be available on the older bots / Mac OS versions.

**Comment by ebraminio** [comment]
Ah, I didn't notice it was in commit queue :/

**Comment by drott** [comment]
Well, emotionally, I would agree :) But it's better to work these out first instead of facing a revert or these issue reaching users. Good that you spotted these.

**Comment by drott** [comment]
I ran a short simulation of the fallback code on Mac OS 10.10 and it comes back with
"Tamil Sangam MN" on the 10.10 bot as well.

**Comment by drott** [comment]
Images

CoreText

![tamil_coretext](https://user-images.githubusercontent.com/1021784/47922343-7d78f900-debf-11e8-9364-c8f6ace8f750.png)

HB AAT

![tamil_ot](https://user-images.githubusercontent.com/1021784/47922348-82d64380-debf-11e8-951e-9b6e575a5912.png)

**Comment by behdad** [comment]
Ok, this is an easy and hard one at the same time.  The font has broken GSUB/GPOS tables.  So, it's our priority that is getting in the way.  At the same time, I'm not sure I want to switch the priority around.

So, if a font has both tables, it will behave differently on Mac compared to other OSes.  The Mac behavior might still be inferior to the GSUB/GPOS behavior but have been done because older Mac didn't support full Indic2... So, by always prefering Mac tables we will be doing such fonts a disservice, even though that's what you'd get with them on Mac still.

Not sure.  @jfkthame ?

**Comment by behdad** [comment]
Other idea was to prefer AAT for Apple fonts.  But checking OS/2 vendor ID for Tamil Sangam MN, it's "MUTF".  So, that wouldn't work.

Next idea, we can blacklist their GSUB/GPOS tables same way we blacklist GDEF table of many fonts.  I like this best.  I just need the GSUB/GPOS/GDEF lengths of affected fonts.  Maybe someone can run a check to see which fonts on OS X 10.10 have both sets of tables.

**Comment by behdad** [comment]
Or I can blacklist for vendor "MUTF" if that covers everything.

**Comment by behdad** [comment]
> Or I can blacklist for vendor "MUTF" if that covers everything.

Change priority, not blacklist.

**Comment by khaledhosny** [comment]
Another idea, would to have programmatic way to select AAT over OTL (https://github.com/harfbuzz/harfbuzz/issues/322) and then Chrome (and other clients) can give AAT priority on Mac. Thinking about it, might not be a good idea as every client now has to do it.

**Comment by behdad** [comment]
> Another idea, would to have programmatic way to select AAT over OTL (#322) and then Chrome (and other clients) can give AAT priority on Mac. Thinking about it, might not be a good idea as every client now has to do it.

Right.  Thought about it.  I also prefer automagic solution.

**Comment by ebraminio** [comment]
That undermines cross-platform typesetting systems to get reproducible results on different platforms, please don't go there if possible.

**Comment by khaledhosny** [comment]
You couldn’t get consistent cross-platform output with AAT fonts before, so anyone who cares about that won’t be using them to begin with. Not much lost. Still doing the right thing by default for such broken font when possible is a desired goal on its own.

**Comment by olivierberten** [comment]
By the way, the same happens with Khmer Sangam MN (or at least something very similar)

![khmer sangam mn](https://user-images.githubusercontent.com/213117/47963581-60af0380-e02e-11e8-9519-2b1423939b15.png)

(in the first 2 samples you can also see the problem described at #1357)

**Comment by olivierberten** [comment]
Same with XenoType's khmer fonts:
![xenotype khmer ttf](https://user-images.githubusercontent.com/213117/47963738-7291a600-e030-11e8-97dc-a600a4c71fe2.png)
![xenotype khmerbold ttf](https://user-images.githubusercontent.com/213117/47963739-7291a600-e030-11e8-9272-edef3bab572c.png)

**Comment by behdad** [comment]
Okay.  Let's say we prefer AAT over OT all the time.  Do we know of fonts that have better OT tables than AAT?

**Comment by behdad** [comment]
> Okay. Let's say we prefer AAT over OT all the time. Do we know of fonts that have better OT tables than AAT?

Well, doing that on all platforms will be problematic.

**Comment by behdad** [comment]
Let's collect all the broken fonts.  Can you all email me?  Then, if all have empty-detectable GSUB, we throw out the GSUB.  Apple also doesn't apply GPOS if GSUB wasn't applied.  I can add the same maybe.

**Comment by behdad** [comment]
@jfkthame can I get your thoughts here?

**Comment by jfkthame** [comment]
I'm leaning towards the idea that there's no "magic" solution here, and the question of AAT/OTL priority should be left for the client application to decide via an API of some kind. (Buffer flag?)

So clients will need to choose between consistency with the platform (so preferring AAT on macOS, OTL elsewhere) or consistency (one way or the other) across platforms; or they can implement some kind of blacklist or explicit user control or whatever.

We'd still need to decide on a default -- I think I prefer "follow platform convention" for this -- but clients would be able to opt in to different behavior.

**Comment by behdad** [comment]
> I'm leaning towards the idea that there's no "magic" solution here,

I was going to say we blacklisted GDEF of Tahoma etc before whereas we could do something else.  But then noticed that I'm suggesting blacklisting every font made with this particular feature (dual tables).

> and the question of AAT/OTL priority should be left for the client application to decide via an API of some kind. (Buffer flag?)

My resistence to new API was that I had in mind to implement this via the shaper selection method, which requires some refactoring.  I like buffer flag API, even if slightly abusive.  I'll go ahead and do that.

So:
```
@HB_BUFFER_FLAG_FIDELITY_CROSS_PLATFORM
```
?

**Comment by khaledhosny** [comment]
IMHO, using the shaper selection API for this allow applications to re-use any existing support for selecting shapers that they might have already. A new different methods sounds rather confusing.

**Comment by behdad** [comment]
> IMHO, using the shaper selection API for this allow applications to re-use any existing support for selecting shapers that they might have already. A new different methods sounds rather confusing.

That is a compelling argument...  Okay, let me think about it more.  Not rushing it in.

**Comment by behdad** [comment]
>     * why call the GSUB/GPOS of these fonts "broken"? As far as I can tell, they're just limited : the MN GSUB is just empty, while the XenoType only has the `sups` feature. As far as I can tell, the GPOS table just feature a very limited number of kerning pairs.

Because using those tables results in broken text rendering (compared to using their morx table)?

>     * this leads to another question: why would OT and AAT features be mutually exclusive? And for the kerning issue, why couldn't we just merge kern and GPOS(kern) tables? or just take the wider set?

Because it may result in broken rendering if you apply both, with correct fonts.

>     * and a last one: I guess the current AAT support in harfbuzz is enough for fancy features of latin fonts but it falls short for smart fonts made for complex scripts...

What makes you guess so?  We implement all there is to mort and morx and kern and kerx tables now (with one exception, to be done, https://github.com/harfbuzz/harfbuzz/issues/1356)  It's as complete as Apple's.

**Comment by khaledhosny** [comment]
>  * why call the GSUB/GPOS of these fonts "broken"? As far as I can tell, they're just limited : the MN GSUB is just empty, while the XenoType only has the `sups` feature. As far as I can tell, the GPOS table just feature a very limited number of kerning pairs.

Because you can’t properly render the complex scripts these fonts support with these tables, so if AAT is not used the font become unusable. That makes it functionally broken, not structurally.



>  * this leads to another question: why would OT and AAT features be mutually exclusive? And for the kerning issue, why couldn't we just merge kern and GPOS(kern) tables? or just take the wider set?

I don’t think merging the tables is a wise idea (not sure if it is technically possible). Fonts that has both GPOS kerning and kern table are built with the expectation that one of them will be used at a time (these days it is usually GPOS that will be used and kern table is built as a limited fallback for legacy applications). I expect this to be true for essentially anything that is duplicated between different layout models.

**Comment by olivierberten** [comment]
I guess I was just disappointed that it doesn't work out of the box for the fonts I'm interested in 😉

An option for setting the prefered shaper (OT, AAT or Graphite) per font should be good enough and shouldn't be too difficult to implement in Scribus or LibreOffice, and maybe even in fontconfig...

That said, going back to your [question](https://github.com/harfbuzz/harfbuzz/issues/1348#issuecomment-435684064), are there many fonts where choosing for AAT features when available would result in poorer features than their OT capabilities?

**Comment by ebraminio** [comment]
> Okay. Let's say we prefer AAT over OT all the time. Do we know of fonts that have better OT tables than AAT?

Yeah why not, lets say we limit that to macOS, wouldn't broken AAT fonts be problematic for Chrome on macOS anyway? Didn't such fonts got enough feedback from Apple users already before? Apple products and CoreText users, iOS and macOS, have already enough user base to think there aren't just some random broken AAT font out there and they are unnoticed. If we fear that much from AAT fonts, lets browsers to use something like `font-feature-settings: morx off;` on other platforms (and making sure that results to OTL be run) then gradually rolling AAT to users so we can make a list of fonts having `morx` but also a better GSUB/GPOS. Desktop publishing software also can follow variants of the pattern (experimental flag and such).

Or, does OTS use on Chrome/Firefox already whitelisted `morx`/`mort`?

> Well, doing that on all platforms will be problematic.

Do we have real examples for that in hand? If so lets find and special case those instead?

There are also variants of newly introduced San Fransisco fonts that don't use `morx`/`kerx` tables and rely on OTL and using `.otf` file extension (interestingly enough `trak` is still there) so Apple considers not mixing them apparently but if already mixed, lets run AAT first.

**Comment by ebraminio** [comment]
Supporting and against my comment, I just remembered http://wiki.irmug.com/index.php/X_Series_2 fonts that now I checked have both GSUB/GPOS and `morx` and we should see if their AAT are OK to be used with XeTeX instead their GSUB/GPOS.

**Comment by NorbertLindenberg** [comment]
When talking about “macOS”, keep in mind that iOS also comes with CoreText and the same preference for AAT morx/kerx/ankr over OT GDEF/GSUB/GPOS. I don’t know much about the other Apple platforms, watchOS and tvOS, but would guess it’s the same there.

**Comment by behdad** [comment]
I like to go back and check the fonts to see if detecting their GSUB empty helps...

**Comment by drott** [comment]
If you have a python script that I can run against the Mac fonts that I have archived here on my system, I am happy to run it against those? Or how would you like to check them? Can I dump something from them using fonttools API?

**Comment by ebraminio** [comment]
> I like to go back and check the fonts to see if detecting their GSUB empty helps...

I don't see "Tamil MN.ttc" `GSUB` empty but may is sparse? How that can be detected?

Don't XeTeX also already applies CoreText first for AAT fonts, so for example no need to fear from TeX documents having popular [X Persian](http://wiki.irmug.com/index.php/X_Series_2) fonts as they are already compiled with macOS sometimes also?

**Comment by jfkthame** [comment]
On 13/11/2018 17:25, Ebrahim Byagowi wrote:
 >     I like to go back and check the fonts to see if detecting their GSUB
 >     empty helps...
 >
 > I don't see "Tamil MN.ttc" |GSUB| empty but may is sparse? How that can
 > be detected?
 >
 > Don't XeTeX also already applies CoreText first for AAT fonts,

XeTeX on macOS allows the author to explicitly specify whether AAT or OT 
(GSUB/GPOS) shaping should be used for any given font.

 > so for
 > example no need to fear from TeX documents having popular X Persian
 > <http://wiki.irmug.com/index.php/X_Series_2> fonts as they are already
 > compiled with macOS sometimes also?
 >
 > —
 > You are receiving this because you were mentioned.
 > Reply to this email directly, view it on GitHub
 > 
<https://github.com/harfbuzz/harfbuzz/issues/1348#issuecomment-438359318>,

**Comment by behdad** [comment]
For now I ended up ignoring empty GSUBs.  Fixes Tamil and similar ones.

Here's the list of fonts on 10.10 that have morx and empty GSUB (affected by change):
```
./Library/Fonts/ChalkboardSE.ttc
./Library/Fonts/Devanagari Sangam MN.ttc
./Library/Fonts/Bangla Sangam MN.ttc
./Library/Fonts/Tamil Sangam MN.ttc
./Library/Fonts/GillSans.ttc
./Library/Fonts/Trattatello.ttf
```

and here are the fonts that have morx and non-empty GSUB (we still prefer GSUB for these, but CoreText prefers morx):
```
./Library/Fonts/AppleSDGothicNeo-SemiBold.otf
./Library/Fonts/华文细黑.ttf
./Library/Fonts/Kefa.ttc
Compiling "./Library/Fonts/ChalkboardSE.ttx" to "./Library/Fonts/ChalkboardSE#3.ttf"...
Parsing 'GSUB' table...
./Library/Fonts/ヒラキノ明朝 Pro W3.otf
./Library/Fonts/ヒラキノ明朝 Pro W6.otf
./Library/Fonts/AppleSDGothicNeo-ExtraBold.otf
./Library/Fonts/ヒラキノ角コ Pro W6.otf
./Library/Fonts/ヒラキノ角コ Std W8.otf
./Library/Fonts/AppleSDGothicNeo-Thin.otf
./Library/Fonts/DecoTypeNaskh.ttc
./Library/Fonts/AppleSDGothicNeo-Heavy.otf
./Library/Fonts/AppleSDGothicNeo-UltraLight.otf
./Library/Fonts/ヒラギノ角ゴ StdN W8.otf
./Library/Fonts/PlantagenetCherokee.ttf
./Library/Fonts/AppleSDGothicNeo-Light.otf
./Library/Fonts/Damascus.ttc
./Library/Fonts/AppleSDGothicNeo-Medium.otf
./Library/Fonts/ヒラギノ丸ゴ Pro W4.otf
./Library/Fonts/ヒラギノ角ゴ Pro W3.otf
./Library/Fonts/Krungthep.ttf
./Library/Fonts/Ayuthaya.ttf
./Library/Fonts/Cochin.ttc
./Library/Fonts/ヒラギノ丸ゴ ProN W4.otf
./Library/Fonts/Silom.ttf
./System/Library/Fonts/AppleSDGothicNeo-Bold.otf
./System/Library/Fonts/ヒラギノ明朝 ProN W3.otf
./System/Library/Fonts/AppleSDGothicNeo-Regular.otf
./System/Library/Fonts/ArialHB.ttc
./System/Library/Fonts/ヒラギノ明朝 ProN W6.otf
```

**Comment by ebraminio** [comment]
To guys contributed here see #1982 also, Gill Sans won't get kerning between 'Ty' because `GPOS` isn't applied as `morx` presence.
