### ISSUE TITLE
[aat] Difference in WAW spacing between CoreText and HB AAT

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1350]
Using GeezaPro from Mac OS 10.10:

CoreText

```
$ ../test/shaping/hb-unicode-encode U+0648,U+0644,U+064A | ./hb-shape ~/dev/geeza_pro/GeezaPro_10_10.ttc --shaper=coretext  --direction=rtl
[u064a.final.yeh.001=2+1545|u0644.initial.lam=1+353|u0648.waw=0+868]
```

HB AAT:
```
$ ../test/shaping/hb-unicode-encode U+0648,U+0644,U+064A | ./hb-shape ~/dev/geeza_pro/GeezaPro_10_10.ttc --shaper=ot --font-funcs=ot  --direction=rtl
[u064a.final.yeh.001=2+1545|u0644.initial.lam=1+515|u0648.waw=0+868]
```

So, HarfBuzz AAT computes a much wieder advance for u0644.initial.lam for some reason.

**Comment by behdad** [comment]
I think I'm appyling kern wrong, adding space instead of removing...

**Comment by drott** [comment]
Images

CoreText

![waw_coretext](https://user-images.githubusercontent.com/1021784/47922562-098b2080-dec0-11e8-8e37-a07a30c40f35.png)

HB AAT

![waw_ot](https://user-images.githubusercontent.com/1021784/47922569-0db73e00-dec0-11e8-924d-ea2175c41f47.png)

**Comment by behdad** [comment]
Thanks.

**Comment by behdad** [comment]
Okay, it's not kerning at all.  Debugging.

**Comment by ebraminio** [comment]
>  Basically, mort of the kerx.

Hehehe. Looks much better now.
