### ISSUE TITLE
No hyphens on hyphenation

### ISSUE THREAD

**Issue by cmahte** [harfbuzz/harfbuzz#1353]
I'm working on alternate punctuation for optically aligned margins.  

Hyphen Ux002D becomes UxEB84, which has a similar glyph, but the sides of the glyph region are narrow. and the glyph kerns a large value for every pair. This makes hyphens appear normal, but 'justifies' hyphens to extend 50% beyond the margin. There are still issues, but the concept works. 

However, when LibreOffice 6.0.5 hyphenates a word, with the jalt table disabled I get hyphens, with jalt enabled i get no hyphen and the word is still broken but aligned to the edge. 

Something breaks between harfbuzz and LO, but the page belongs to harfbuzz on the wrapping, right? 

Font: [here](https://github.com/Avante-Vangard/AV-Marinus/blob/master/AV-Marinus-OTF/AVMarinus-Book.otf)

Example LO file: [here](https://drive.google.com/open?id=1TPoDNHBI_r7XXPSQq0vQKNRiB2g__AtT)

You can toggle the jalt table in the LO font field jalt=0 or jalt=1. 

Is this an expected failure (no hyphen when It's being substituted)?  Is it strictly harfbuzz? All LibreOffice? or a font problem? 

System: 
Macbook 2010 running High Sierra + LibreOffice 6.0.5.2 from libreoffice.org, 
Dell Lattitude E6320 running Ubuntu 18.04 64bit + LibreOffice 6.0.6.2 through Ubuntu repository

**Comment by khaledhosny** [comment]
That would be a LibreOffice bug or lack pf feature, HarfBuzz operates on a lower level than this.

**Comment by khaledhosny** [comment]
For reference, here is `hb-view` output:

`hb-view AVMarinus-Book.otf "a-b"`:
![nojalt](https://user-images.githubusercontent.com/93914/47955520-239d2f80-dfa2-11e8-86e2-71e09c7d5984.png)

`hb-view AVMarinus-Book.otf "a-b" --features="jalt=1"`:
![jalt](https://user-images.githubusercontent.com/93914/47955525-36afff80-dfa2-11e8-88f6-0bfad9f3c4f9.png)

**Comment by cmahte** [comment]
Thanks!  This isn't the best news, but it moves me along. 

and, in your examples, kern is expected to be active too. so jalt=1&kern=1  is a better demonstration whether it's working.

**Comment by khaledhosny** [comment]
`kern` is on by default, so there is no difference. In fact, I do see hyphenation in your document even with `jalt=1`, it is just at different places than when `jalt=0` is used, which I believe due to the words with manual hyphens being now shorter due to the changed spacing of the hyphen. See the word “number”, page 6, second paragraph, 4th line from below:
![image](https://user-images.githubusercontent.com/93914/47957458-c499e380-dfbe-11e8-9bfd-0342df7bb102.png)
