### ISSUE TITLE
Khmer difference with CoreText

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1357]
https://chromium-review.googlesource.com/c/chromium/src/+/1275945/33/third_party/WebKit/LayoutTests/platform/mac/fast/text/font-fallback-expected.png

Don't know which is better but from other fonts I feel CT is right,

It is a 10.13 machine, `3	en	Khmer MN; 13.0d1e3; 2017-06-14`

```
bash-3.2$ util/hb-view /Library/Fonts/Khmer\ MN.ttc អក្សរខ្មែរ --shaper coretext
bash-3.2$ util/hb-view /Library/Fonts/Khmer\ MN.ttc អក្សរខ្មែរ --shaper ot
```

CT:
![image](https://user-images.githubusercontent.com/833473/47970107-36912c00-e096-11e8-87b6-6d48a42f8c08.png)

OT:
![image](https://user-images.githubusercontent.com/833473/47970103-29743d00-e096-11e8-8419-b40a4fa7870d.png)

**Comment by khaledhosny** [comment]
You can always use scp to copy the PNGs from the remote machine.

**Comment by ebraminio** [comment]
> You can always use scp to copy the PNGs from the remote machine.

Few more commands :) I wish gnome-terminal could support https://www.iterm2.com/documentation-images.html or something similar, it is just easy work with, in fact dev-run already uses it https://github.com/harfbuzz/harfbuzz/blob/master/src/dev-run.sh#L56 but now I don't have mac

**Comment by khaledhosny** [comment]
BTW, you know you can get PNGs from hb-view, they are better than these fallback terminal renderings :)

**Comment by ebraminio** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/1275945/33/third_party/WebKit/LayoutTests/platform/mac/fast/text/selection/khmer-selection-expected.png

```
util/hb-view /Library/Fonts/Khmer\ MN.ttc ក្រុម --shaper ot
util/hb-view /Library/Fonts/Khmer\ MN.ttc ក្រុម --shaper ot
```

![image](https://user-images.githubusercontent.com/833473/47962108-cdc19980-e02c-11e8-8250-daf1a0fe4dc8.png)

> BTW, you know you can get PNGs from hb-view, they are better than these fallback terminal renderings :)

Too much hassle from bots/remote machines :)

**Comment by behdad** [comment]
> Few more commands :)

```hb-view ... | display```

That's not "few more commands".

**Comment by behdad** [comment]
This is same as the Tamil issue.  No need to open new issue.

**Comment by ebraminio** [comment]
> That's not "few more commands".

![image](https://user-images.githubusercontent.com/833473/47969842-6fc79d00-e092-11e8-88e5-197edaa265b7.png)

Does that work remotely, maybe through X forwarding? Apple removed X support for sometime and even that I doubt I can make it work on the bots... but xterm.js https://github.com/xtermjs/xterm.js/pull/1577/ will have 1337 protocol support soon, I think it would be good idea add the support to hb-view also.

**Comment by ebraminio** [comment]
Replaced with high quality images

**Comment by ebraminio** [comment]
So maybe something else going on...

**Comment by olivierberten** [comment]
Or maybe `HB_OPTIONS=aat` should go for kern/kerx instead of GPOS

**Comment by behdad** [comment]
In 10.12 and 10.13 I see this font has morx and kern, and no GSUB/GPOS.   So this is its own issue indeed.  I'll take a look.

**Comment by behdad** [comment]
Okay this is just mark advance zeroing.  I'll disable it if morx was applied.
