### ISSUE TITLE
All NotoSerifCJK latin glyphs have unsafe to break flag

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#1365]
Not sure if this is expected or not, but it seems all glyphs in the buffer except the first glyph and the glyph after space has unsafe to break flag set:
```
$ hb-shape NotoSerifCJK-Regular.ttc "abc abc" --show-flags --no-positions
[gid66=0|gid67=1#1|gid68=2#1|gid1=3#1|gid66=4|gid67=5#1|gid68=6#1]
```

Not sure how to debug this.

**Comment by khaledhosny** [comment]
```
$ hb-shape NotoSerifCJK-Regular.ttc "abc" --trace --show-flags
trace: start lookup 2	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 2	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 3	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 3	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 4	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 4	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 5	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 5	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 30	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 30	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 32	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 32	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 44	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 44	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 3	buffer: [gid66=0+552|gid67=1+627|gid68=2+529]
trace: end lookup 3	buffer: [gid66=0+552|gid67=1+627#1|gid68=2+529#1]
[gid66=0+552|gid67=1+627#1|gid68=2+529#1]
```

This seems to be a lookup used in `kern` feature, and indeed disabling the kerning drops the flag:
```
$ hb-shape NotoSerifCJK-Regular.ttc "abc" --trace --show-flags --features="-kern"
trace: start lookup 2	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 2	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 3	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 3	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 4	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 4	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 5	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 5	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 30	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 30	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 32	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 32	buffer: [gid66=0|gid67=1|gid68=2]
trace: start lookup 44	buffer: [gid66=0|gid67=1|gid68=2]
trace: end lookup 44	buffer: [gid66=0|gid67=1|gid68=2]
[gid66=0+552|gid67=1+627|gid68=2+529]
```
A bit of looking around, this is coming from `PairPosFormat2::apply()`, so I guess it is intentional. I wasn’t expecting GPOS lookups to set the flag, and it didn’t look like there is any glyph substitution involved.

Kerning shouldn’t be an issue for what I’m trying to do (checking how much I need to reshape after hyphenation) because I can reuse the old kerning value, but I guess I have to live with it.

**Comment by behdad** [comment]
Is it actually kerning?   We can make the code not flag if kern value was zero.  We should.

**Comment by behdad** [comment]
It's probably a class kerning table that doesn't actually kern ideographs next to each other.

**Comment by jfkthame** [comment]
> Kerning shouldn’t be an issue for what I’m trying to do (checking how much I need to reshape after hyphenation) because I can reuse the old kerning value, but I guess I have to live with it.

In general, I'd have thought you *do* need to reshape after hyphenation where kerning was present; if a glyph pair such as "AV" was kerned, but then you hyphenate so that one line ends "A-" and the next begins "V", the adjusted advances of the "A" and "V" glyphs resulting from the kerning will no longer be appropriate to use.

(Of course, if the kern value was zero we needn't set the flag.)

**Comment by khaledhosny** [comment]
Right, there is no difference in the positioning with or without kerning in the example above.

**Comment by behdad** [comment]
Fixed in my cross-kern branch.  Will reach master later today.
