### ISSUE TITLE
Upstream LibreOffice patches

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1366]
https://cgit.freedesktop.org/libreoffice/core/tree/external/harfbuzz some are interesting i guess

**Comment by khaledhosny** [comment]
I don’t think they are of much interest. One is removing `-fno-rtti ` from CXXFLAGS, and the comment above it in the original file shows how to it with no patching. One is obsolete fix for `_HB_SCRIPT_MAX_VALUE`. The last one is an obsolete iOS fix as well.

**Comment by ebraminio** [comment]
Oh, OK
