### ISSUE TITLE
[varLib] Change varStore storage format?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1371]
Currently we store delta rows as lists.  Can be tuples.  Of course in the builder API we accept both.  But what gets stored will be different, and ttx output will be different (showing `"(1, 2, ...)"` instead of `"[1, 2, ...]"`).  @anthrotype do you think it's worth it?

**Comment by khaledhosny** [comment]
That was meant for fonttools I guess.

**Comment by behdad** [comment]
Right... Let's use the fancy issue move feature on github.

**Comment by behdad** [comment]
> Right... Let's use the fancy issue move feature on github.

Umm. Only allows in same org.

**Comment by behdad** [comment]
> Right... Let's use the fancy issue move feature on github.

Umm. Only allows in same org.
