### ISSUE TITLE
Better name / ltag table language matching

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1372]
I know we decided not to get in the business of full language tag matching.  But if "fa-ir" was requsted and we found "fa", we should match it.  Just that much.  Same level as what we do for OpenType tag matching roughly?  I know I'm under-estimating @dscorbett's work on that.

**Comment by behdad** [comment]
> "fa" and "PES_arab_ir" both get mapped to 'FAR '.

Hah.  Wow.  That's definitely more than I thought it does (the part about macrolanguages really.)

> I notice that the `hb_ot_language_map_t[]`s in hb-ot-name-language.cc have entries with duplicate language tags; how does the matcher know which to map, say, "en" to?

Do they?  I thought I merge them into one.  But yeah, the distinction is lost, unless we add territories to those.

I think we should refactor the core of the logic you implemented and make it reusable by other parts of the code, and possibly expose it.  It's non-trivial and useful in many places, even if @brawer tells us it's not the complete BCP 47 language matching.

**Comment by behdad** [comment]
> > I think we should refactor the core of the logic you implemented and make it reusable by other parts of the code
> 
> How much of it? The basic parsing and some of the matching could be factored out of `hb_ot_tags_from_script_and_language` etc. The information about macrolanguages is in a format that does not generalize well, so that part would have to be rewritten.

As I said, the need we have is: we have a list of declared languages by the font (in name, ltag, or meta tables).  User sets a language.  We like to match the best declared language.


> > and possibly expose it.
> 
> In that case, the API would need more thought. I only designed those functions for mapping BCP 47 to OpenType, taking shortcuts to skip anything irrelevant to HarfBuzz; a publicly exposed BCP 47 parser would need to be more general, if it is to be useful for other projects.

Right.  Above API is along the line of what I want.  Perhaps, quite possibly, return a score instead of bool.  Fontconfig for example, does this:
```
typedef enum _FcLangResult { 
    FcLangEqual = 0, 
    FcLangDifferentCountry = 1, 
    FcLangDifferentTerritory = 1, 
    FcLangDifferentLang = 2 
} FcLangResult; 
```

I like something more generic.  Perhaps just being integers that are unspecified, but compare to eachother.  The higher the better the match, with 0 meaning no match whatsoever.

**Comment by behdad** [comment]
Without this, the current name table API is not usable.

**Comment by brawer** [comment]
> we have a list of declared languages by the font (in name, ltag, or meta tables). User sets a language. We like to match the best declared language.

Well, that’s language matching. Complex, but of course it can be done. If you really want a language matcher inside HarfBuzz, Go’s [x.text.language](https://blog.golang.org/matchlang) might be a good inspiration. ICU has a good working implementation too, but the code is entangled. fontconfig’s approach will likely give wrong results.

By the way, with modern systems (at least Android, Windows and macOS; not sure about Linux desktops) there isn’t necessarily just *one* user language. Users enter an ordered list of languages as their system preference, similar to HTTP Accept-Language.

**Comment by behdad** [comment]
> not sure about Linux desktops

envvar LANGUAGES has been around for decades...  I implement that in Pango.

We need *some* language matching.  I know it's complicated, but then again, in a GNOME stack, there's no better place to have it than in HarfBuzz.

**Comment by behdad** [comment]
So yeah, maybe I'm suggesting that we do the full implementation.

**Comment by behdad** [comment]
Closing this as I did some in #3354.
