### ISSUE TITLE
Change USE Category for Grantha Virama U+1134D

### ISSUE THREAD

**Issue by punchcutter** [harfbuzz/harfbuzz#1379]
As noted in https://github.com/googlei18n/noto-fonts/issues/1319 and https://github.com/googlei18n/noto-fonts/issues/1318 the virama ligatures in Grantha should allow marks, but because of USE cluster validation they can't. 

To resolve this Grantha virama should have the same `HVM` classification as Brahmi virama as addressed in https://github.com/harfbuzz/harfbuzz/issues/1102 

Here are a couple more examples in addition to the above noto-fonts issue
![virama_ligature_with_mark_2](https://user-images.githubusercontent.com/11257204/48382355-7ad38c00-e695-11e8-9c55-e60d43251dcf.png)
𑌤𑌨𑍍𑌨𑍈𑌰𑍍᳴𑌋॒𑌤
11324,11328,1134D,11328,11348,11330,1134D,1CF4,1130B,0952,11324

![virama_ligature_with_mark_1](https://user-images.githubusercontent.com/11257204/48382356-7ad38c00-e695-11e8-8dd1-411ffd7b7a9e.png)
𑌪𑍍𑌰॒𑌘𑌾॒𑌸𑍍𑌯𑌾𑌨𑍍᳴
1132A,1134D,11330,0952,11318,1133E,0952,11338,1134D,1132F,1133E,11328,1134D,1CF4

Note: Noto Grantha will also need updates to the GPOS to position these marks correctly.

**Comment by behdad** [comment]
PullRequest?
