### ISSUE TITLE
Completely move Chromium off sfntly

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1381]
"Completely move Chromium off sfntly" was on roadmap for mid 2019 but I was curious what is missing so am turning it into an issue.

Apparently this is the only use of sfntly https://cs.chromium.org/chromium/src/third_party/skia/src/pdf/SkPDFFont.cpp?l=423-440 and https://cs.chromium.org/chromium/src/third_party/skia/src/pdf/SkPDFFont.cpp?l=333-396 and sfntly can not provide `CFF` subsetting which we can provide eventually and GPOS/GSUB subsetting should be done before the port also I guess. Other than this, I wonder if is there any need for sfntly on Chromium?

**Comment by behdad** [comment]
In theory current subsetter should be enough.  GSUB/GPOS is NOT required (and is not implemented by sfntly either) since this is for PDF rendering, which has text already layed out.

**Comment by bungeman** [comment]
@HalCanary is interested in this as well.

**Comment by behdad** [comment]
Hal, can you list requirements / sfntly API you need to replace?

**Comment by HalCanary** [comment]
Here's what Skia's PDF generator backend (SkPDF) needs:

Reproduce the functionality of `SfntlyWrapper::SubsetFont`.

Given raw font data (as returned by `SkTypeface::openStream`), the ttcIndex, and a set of glyph indices, I would like minimal subset font data suitable for embedding in a PDF.

I don't need shaping information, since Skia outputs directly positioned glyphs.

**Comment by ebraminio** [comment]
Sure. It API is easy to use and test-subset-*.c are good starting, let me know anything needed

**Comment by ebraminio** [comment]
Simplest snippet for subsetting,

```C
/* Create some font */
hb_blob_create (font_data, font_data_length, HB_MEMORY_MODE_READONLY, nullptr, nullptr);
/* Or if you like to read an actual file: hb_blob_t *blob = hb_blob_create_from_file (path); */
hb_face_t *face = hb_face_create (blob, 0); // this is ttcIndex
hb_blob_destory (blob);

/* Add your codepoints here */
hb_set_t *codepoints = hb_set_create();
hb_set_add (codepoints, 97);
hb_set_add (codepoints, 99);
hb_face_t *subset = hb_subset (face, hb_subset_test_create_input (codepoints));
hb_set_destroy (codepoints);

/* Result blob */
hb_blob_t *result = hb_face_reference_blob (subset);
unsigned int length;
const char *data = hb_blob_get_data (blob, &length);

/* Writing, if you like */
FILE *f = fopen (output_path, "wb");
fwrite (data, 1, length, f);
fclose (f);

/* Clean up result */
hb_blob_destroy (result);
hb_face_destory (subset);
```

And am trying to build Skia here but a little Internet difficulty here.

**Comment by khaledhosny** [comment]
I think Skia would want a way to add glyph ids not Unicode code points.

**Comment by ebraminio** [comment]
> I think Skia would want a way to add glyph ids not Unicode code points.

Oh, fixed.

I think we need to drop more thing here https://github.com/harfbuzz/harfbuzz/blob/2c68f34bddbe506d0b22948562f2f59b9a5b6050/src/hb-subset.cc#L201 or defaulting to dropping? `mort` `morx` `kerx` `kern` `colr` `cpal` `CBDT` `EBDT` `name`...

**Comment by HalCanary** [comment]
Which version of Harfbuzz should I use?  I tried 2.1.1.

**Comment by bungeman** [comment]
In theory changing glyphs ids might be doable, but we would need the mapping from the original glyph ids to the new glyph ids so we can translate (even if that mapping is implicit in the order of the specified subset). Note that sfntly did not change the glyph ids (it replaced paths with trivial paths for 'removed' glyphs, why it didn't just write the loca table with empty glyph data I don't know) so the current code isn't written with that in mind. Microsoft's CreateFontPackage when doing glyph subsetting doesn't change glyphids either.

Note the issue for users here is a chicken and egg problem. They've accumulated a list of glyphs required by being given a bunch of drawing commands and potentially already writing out a lot of data with those glyph ids. It isn't possible to do the subsetting until the very end, so either the entire drawing model they had needs to be kept in memory so the subset can be done before writing out any glyph ids, or they need to go back and fix up the glyph ids, or they can just have the subsetter not change the glyph ids and not need to do anything special. So if at all possible, it would make the world a happier place to at least have the option of leaving the (retained) glyph ids alone (leaving lots of empty glyphs if needed).

**Comment by ebraminio** [comment]
Why not have that as default behavior? That way if we leave `morx` table for example untouched or infinite other table, layout will still work, otherwise we have fiddle into every table.

Any thought about the sample code above?

Shouldn't `hb_subset_input_{glyph,unicode}_set` be renamed to `hb_subset_input_get_{glyph,unicode}_set`?

**Comment by behdad** [comment]
> Why not have that as default behavior? That way if we leave `morx` table for example untouched or infinite other table, layout will still work, otherwise we have fiddle into every table.

Because that produces very suboptimal fonts.  For example, a TTF font with 60,000 glyphs will always contain at least 120kb of 'loca' table even if an optimal subset (of 10 glyphs) is 1kb.

> Any thought about the sample code above?
> 
> Shouldn't `hb_subset_input_{glyph,unicode}_set` be renamed to `hb_subset_input_get_{glyph,unicode}_set`?

The `harfbuzz-subset` API has not been designed yet.  It will all go through a design review / change process later.

**Comment by drott** [comment]
Bumping this, as the discussion about replacing sfntly came up again.

**Comment by drott** [comment]
CC @garretrieger @rsheeter

**Comment by ebraminio** [comment]
I think now we have to rely to @garretrieger and @rsheeter for this.

I think we always should accept suboptimal `loca`s, PDFs and network stacks have their own compression anyway, in addition to popularity of woff and woff2 (and maybe someday, woff3 with [zstd](https://github.com/facebook/zstd)).

**Comment by behdad** [comment]
I believe Garret implemented retain-gid mode, so this is feasible now.

**Comment by ebraminio** [comment]
The newly implemented `hb_subset_input_set_retain_gids` works fine but the comment on I put above https://github.com/harfbuzz/harfbuzz/issues/1381#issuecomment-439178821 still doesn't and hb-subset still is unable to subset a font from given gids works only from unicode set `hb_subset_input_unicode_set`.

The code I am using

```C
#include <stdio.h>

#include "src/hb.h"
#include "src/hb-subset.h"

int main (int argc, char** argv) {
  hb_blob_t *blob = hb_blob_create_from_file (argv[1]);
  hb_face_t *face = hb_face_create (blob, 0);
  hb_blob_destroy (blob);

  hb_subset_input_t *input = hb_subset_input_create_or_fail ();

  bool subset_with_glyph_set = false;

  hb_set_t *glyph_set = subset_with_glyph_set ?
    hb_subset_input_glyph_set (input) : hb_subset_input_unicode_set (input);

  // fill the set, the only important part is the `hb_set_add` call
  {
    hb_font_t *font = hb_font_create (face);
    hb_buffer_t *buffer = hb_buffer_create ();
    hb_buffer_add_utf8 (buffer, "CDEFG", -1, 0, -1);
    hb_buffer_set_direction (buffer, HB_DIRECTION_LTR);
    hb_buffer_set_script (buffer, HB_SCRIPT_LATIN);

    if (!subset_with_glyph_set)
      hb_shape (font, buffer, 0, 0);

    unsigned int length;
    hb_glyph_info_t *info = hb_buffer_get_glyph_infos (buffer, &length);

    for (unsigned int i = 0; i < length; ++i)
      hb_set_add (glyph_set, info[i].codepoint);

    hb_buffer_destroy (buffer);
    hb_font_destroy (font);
  }

  hb_subset_input_set_retain_gids (input, true);
  hb_subset_input_set_drop_hints (input, true);
  hb_subset_input_set_drop_layout (input, true);
  hb_face_t *subset = hb_subset (face, input);
  hb_subset_input_destroy (input);

  hb_blob_t *result = hb_face_reference_blob (subset);
  unsigned int length;
  const char *data = hb_blob_get_data (result, &length);

  FILE *f = fopen ("a.ttf", "wb");
  fwrite (data, 1, length, f);
  fclose (f);

  hb_blob_destroy (result);
  hb_face_destroy (subset);
}
```

And these commands to run:

```bash
g++ a.cc -L build/src/.libs -l harfbuzz -l harfbuzz-subset
LD_LIBRARY_PATH=build/src/.libs ./a.out /home/ebrahim/.local/share/fonts/Skia.ttf
hb-shape a.ttf BCDEFGH --no-glyph-names

[0=0+1488|67=1+1182|68=2+1497|69=3+1237|70=4+1167|71=5+1410|0=6+1488]
```

And if I turn `subset_with_glyph_set` to true it results to `[0=0+1488|0=1+1488|0=2+1488|0=3+1488|0=4+1488|0=5+1488|0=6+1488]` so either something wrong with my code or the functionality.

**Comment by garretrieger** [comment]
Retain glyph ids is now supported for truetype subsetting. I believe we're still waiting on an update to the CFF code to add support there as well.

hb_subset_input_glyph_set () is not yet hooked up and doesn't do anything. I can fix that and wire it up. Shouldn't be too much work.

**Comment by ebraminio** [comment]
@garretrieger I guess that is done also https://github.com/harfbuzz/harfbuzz/pull/1583 and the only part is `hb_subset_input_glyph_set`.

**Comment by garretrieger** [comment]
Ok great, I'll get hb_subset_input_glyph_set fixed up.

**Comment by garretrieger** [comment]
hb_subset_input_glyph_set should now work as expected.

**Comment by HalCanary** [comment]
https://review.skia.org/171223

**Comment by ebraminio** [comment]
Anything to do here from our part?

**Comment by drott** [comment]
No, thanks - remaining work in https://chromium-review.googlesource.com/c/chromium/src/+/1531173
