### ISSUE TITLE
Make WebKitGTK segfaulting on https://terminalizer.com/

### ISSUE THREAD

**Issue by loupianche** [harfbuzz/harfbuzz#1390]
WebKitGTK bug report with backtrace: https://bugs.webkit.org/show_bug.cgi?id=191805

**Comment by khaledhosny** [comment]
The crash does not seem to be in HarfBuzz, the last HarfBuzz function called in that traceback is `hb_font_get_nominal_glyph()` which most likely calls a font function inside WebKit and that is the one crashing. This has to be debugged in WebKit to see why it is crashing.

**Comment by khaledhosny** [comment]
The WebKit function HarfBuzz is calling is most likely https://github.com/WebKit/webkit/blob/master/Source/WebCore/platform/graphics/harfbuzz/HarfBuzzFaceCairo.cpp#L88.

I can not reproduce this crash on Arch Linux though, I have webkit2gtk 2.22.3-1, harfbuzz 2.1.3-1 and epiphany 3.30.2-2.

**Comment by ebraminio** [comment]
Oh, so lets close this per Khaled's comment as it is calling WebKit callbacks and we can't see the issue locally. But I will follow the bug on WebKit to see if anything is from our side, thanks :)

**Comment by mcatanzaro** [comment]
Um yeah, sorry I missed that WebKit was at the top of the trace.
