### ISSUE TITLE
[aat][Regression] 3c3eb5ea9ccf3 breaks accent placement on Times.ttc

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1393]
Bisecting identifies 3c3eb5ea9ccf3 as breaking accent placement on an f + fi ligature with Times.ttc. The commit 3c3eb5ea9ccf3 was intended as a fix for issue #1357 and did fix it, but also introduced this regression.

Good:
```
$ util/hb-shape --shaper=ot --font-funcs=ot /System/Library/Fonts/Times.ttc "Af̀fiZ" 
[A=0+1479|f=1+682|gravecmb=1@-480,588+0|fi=3+1139|Z=5+1251]
```

![affiz](https://user-images.githubusercontent.com/1021784/48768210-de267500-ecb8-11e8-8a56-8fae407afad3.png)

Bad:
```
$ util/hb-shape --shaper=ot --font-funcs=ot /System/Library/Fonts/Times.ttc "Af̀fiZ" 
[A=0+1479|f=1+682|gravecmb=1+682|fi=3+1139|Z=5+1251]
```

![affiz_bad](https://user-images.githubusercontent.com/1021784/48768216-e1b9fc00-ecb8-11e8-83eb-02efc990dd9f.png)

**Comment by drott** [comment]
Same results for Mac OS 10.13 Times.ttc and Mac OS 10.10 Times.ttc.

**Comment by khaledhosny** [comment]
What does Core Text output look like?

**Comment by drott** [comment]
```
$ ./hb-shape --shaper=coretext --font-funcs=ot /System/Library/Fonts/Times.ttc "Af̀fiZ" 
[A=0+1479|f=1+131|gravecmb=1@0,629+551|fi=3+1139|Z=5+1251]
```

![coretext_affiz](https://user-images.githubusercontent.com/1021784/48777290-81d04f00-ecd2-11e8-9e34-0599de52d00f.png)

**Comment by behdad** [comment]
Okay.  So, let's tweak further.  If morx is available, nor mark advance zeroing, but mark fallback positioning can still happen.  That should handle both cases.

**Comment by behdad** [comment]
It's trickier to NOT adjust mark advances, but do mark positioning.  Oh, I know.  Okay, let me see.  We know to NOT do mark positioning etc for Khmer, Indic, etc shapers.  Maybe I reuse that knowledge.

**Comment by behdad** [comment]
Fixed.
