### ISSUE TITLE
Support installable tests

### ISSUE THREAD

**Issue by rossburton** [harfbuzz/harfbuzz#1394]
It would be useful if harfbuzz could install the test suite, like GNOME etc can do.

**Comment by khaledhosny** [comment]
Can you be more specific, for those of us who don’t know what installable tests are and can’t find anything useful with web search.

**Comment by rossburton** [comment]
Installing the test suite so the installed library can be tested in the target environment.  Useful for integration testing in the general case and essential for cross-compiled environments where the test suite can't be ran at build time.

https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests has lots more explanation.

**Comment by rossburton** [comment]
Hi Behdad! :)  After Meson is fine by me, especially as it makes it so easy.

**Comment by khaledhosny** [comment]
Is this addressed by meson build, or do we need more work to support it?

**Comment by rossburton** [comment]
Looking at `tests/api`, the Meson build doesn't support installing either.

**Comment by khaledhosny** [comment]
I don’t personally have much experience with this, but if you can contribute such support it will be highly appreciated.

**Comment by behdad** [comment]
We need help for this; otherwise I don't think any of us can do this.

**Comment by behdad** [comment]
Also, we have many test suites; this is a nontrivial task.
