### ISSUE TITLE
Testing against system fonts

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1403]
Given that we don't have complex-enough mort/morx/kerx test fonts, one way to test those is to modify test suite to allow testing against system fonts.  In the .tests file format, if the font file path is absolute (starts with /), then that test should be skipped if font file does not exist.

If test fails, show sha1 of the font file, possibly font version as well.  A follow up would be to allow only testing if font file is of certain versions.  Then we can add mac-specific tests.

**Comment by behdad** [comment]
When that's possible, we need tests for at least following issues:

https://github.com/harfbuzz/harfbuzz/issues/1393
https://github.com/harfbuzz/harfbuzz/issues/1264
https://github.com/harfbuzz/harfbuzz/issues/1357
https://github.com/harfbuzz/harfbuzz/issues/1348

**Comment by ebraminio** [comment]
Yes, at least CI bots can check that but should be noted that `mort` fonts are not available on 10.13 but on 10.12, 10.12 is available on CircleCI, only xcode version should be correctly according to https://circleci.com/docs/2.0/testing-ios/

**Comment by behdad** [comment]
Plus, all various kerx / kern subformats.  mort if we can find any.  morx has great tests, thanks to @brawer.  Interaction of kern / kerx with fallback positioning etc is completely untested currently.

**Comment by ebraminio** [comment]
"PASS: tests/macos-10.12.tests" is about the one you mentioned https://circleci.com/gh/harfbuzz/harfbuzz/58065

> Plus, all various kerx / kern subformats. mort if we can find any. morx has great tests, thanks to @brawer. Interaction of kern / kerx with fallback positioning etc is completely untested currently.

Be more specific when filing bugs ;) Now it is easy to add more, just log into the bot (using "Rerun job with SSH" button on that specific bot) and add the interested ones, then commit and push the change locally.
