### ISSUE TITLE
GeezaPro rendering doesn't look good

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1405]
From a 10.12 machine "Geeza Pro Regular; 12.0d1e3; 2016-07-17",

```
util/hb-view /System/Library/Fonts/GeezaPro.ttc -u "U+0627,U+0644,U+0623,U+064E,U+0628,U+0652,U+062C,U+064E,U+062F,U+0650,U+064A,U+064E,U+0651,U+0629,U+0640,U+0627,U+0644,U+0639,U+064E,U+0631,U+064E,U+0628,U+0650,U+064A,U+064E,U+0651,U+0629" --shaper ot | display

util/hb-view /System/Library/Fonts/GeezaPro.ttc -u "U+0627,U+0644,U+0623,U+064E,U+0628,U+0652,U+062C,U+064E,U+062F,U+0650,U+064A,U+064E,U+0651,U+0629,U+0640,U+0627,U+0644,U+0639,U+064E,U+0631,U+064E,U+0628,U+0650,U+064A,U+064E,U+0651,U+0629" --shaper coretext | display
```
![image](https://user-images.githubusercontent.com/833473/48951719-d71b9300-ef54-11e8-81e5-c4f3a6409480.png)

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzz/blob/master/test/shaping/data/in-house/tests/macos-10.12.tests#L6 should be updated after the fix

**Comment by behdad** [comment]
Ugh. Did I break that?  We desperately need tests for this.  So yeah, thanks.

**Comment by behdad** [comment]
Fixed.  Please update tests.
