### ISSUE TITLE
"tr@foo=bar" locale doesn't fallback to "tr"

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1406]
Per https://test-results.appspot.com/data/layout_results/win10-blink-rel/2159/webkit_layout_tests%20%28with%20patch%29/layout-test-results/results.html on fast/text/small-caps-turkish.html, apparently hb used to recognize "tr@foo=bar" as "tr" but now isn't. Don't know if is intended or not

**Comment by dscorbett** [comment]
[That is an invalid value of `lang`.](https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes)
> The `lang` attribute (in no namespace) specifies the primary language for the element's contents and for any of the element's attributes that contain text. Its value must be a valid BCP 47 language tag, or the empty string.

**Comment by behdad** [comment]
I think that's a Linux / glibc locale tag.  We like to accept those.  Thanks for the fix.
