### ISSUE TITLE
Tamil MN on 10.13.6 is broken

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1410]
Unlike its 10.12.6 version which was fixed #1348, its 10.13.6 version is broken and it hasn't empty language list on gsub in order to be detected so it is broken.

![image](https://user-images.githubusercontent.com/833473/48973404-b6863280-f053-11e8-8a98-a3224738dc61.png)

**Comment by behdad** [comment]
Ugh.  This one (Tamil MN on 10.13.6) has non-empty GSUB.  So, back to needing to prefer morx/kerx on fonts that have GSUB/GPOS...

**Comment by behdad** [comment]
cc @drott

**Comment by ebraminio** [comment]
Obviously #1391 is the ultimate answer but maybe always favouring AAT over OT for Indic scripts as a workaround?

**Comment by behdad** [comment]
Given that the Khmer issue is resolved I'm back to thinking maybe we should just add exception to blacklist GSUB for MN fonts (ie. OS/2 VendorID 'mutu').

**Comment by drott** [comment]
SGTM, those seem to be the only other odd ones that we have encountered so far. We should perhaps also report it to Apple at the same time.
