### ISSUE TITLE
Should hb_ot_color_glyph_reference_{png,svg}() return NULL in no PNG/SVG is available?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#1413]
It currently returns an empty blob, which feels a bit counter-intuitive, and it is not clear if clients should/can destroy that empty blob or not. Returning NULL seems simpler.

**Comment by behdad** [comment]
Umm. I agree it's inconvenient...  But it's consistent with rest of API.

Whether empty blob can be destroyed should be document.  It doesn't need to be destroyed, but it's safe to destroy. (same about NULL).

In the subsetter API we started adding API that returns NULL, but those API names end in "_or_fail".  Can add the same here.

Typically my answer is that empty blob needs same handling that 1-byte blob gets, so user doesn't really need to know the difference.  This case is slightly different though...

**Comment by ebraminio** [comment]
blob_from_file also returns empty blob instead NULL when file not found which could make sense to return NULL on file not found to differentiate it with empty files.

**Comment by behdad** [comment]
> blob_from_file also returns empty blob instead NULL when file not found which could make sense to return NULL on file not found to differentiate it with empty files.

Right. That one bothers me most, since detecting file-not-found is essential.

**Comment by khaledhosny** [comment]
Another similar issue, is specifying an non-existing face index to `hb_face_create()` will return an empty face if this is a font collection, or will be ignored if it isn’t. I ended up checking against `hb_face_count()` myself. I guess I should report a separate issue.

**Comment by khaledhosny** [comment]
Ignoring face index for single faces is fine, the problematic part is returning an empty face if it is a font collection. We should either ignore face index in this case, return NULL, or have a documented way to detect empty objects.

**Comment by behdad** [comment]
> Ignoring face index for single faces is fine, the problematic part is returning an empty face if it is a font collection. We should either ignore face index in this case, return NULL, or have a documented way to detect empty objects.

Oh, yeah, it's lack of documentation then.  Checking for equality to `hb_face_get_empty()` is the way to check for that.  We can add API for checking.  `is_empty()` unfortunately is not the best name...

**Comment by khaledhosny** [comment]
Checking against `hb_face_get_empty()` is good enough for me (that was my initial guess, but I wasn’t sure that clients can rely on that).

**Comment by behdad** [comment]
@n8willis!
