### ISSUE TITLE
[aat] Recording pre-context does not seem to affect Arabic shaping with GeezaPro

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1415]
ot shaping with Courier New changes results depending on pre-context as expected:
```
$ ./hb-shape --direction=rtl --show-flags --shaper=ot --text-before=ه /Library/Fonts/Courier\ New.ttf "ي"
[afii62833=0+1229]
```

vs. without pre-context:

```
$ ./hb-shape --direction=rtl --show-flags --shaper=ot /Library/Fonts/Courier\ New.ttf "ي"
[afii57450=0+1229]
```

However, a comparable setup with ```Geeza Pro``` from Mac OS 10.13 does not work as expected:

```
$ ./hb-shape --direction=rtl --show-flags --shaper=ot --font-funcs=ot --text-before=ه /System/Library/Fonts/GeezaPro.ttc "ي"
[u064a.yeh=0+1417]

$ ./hb-shape --direction=rtl --show-flags --shaper=ot --font-funcs=ot /System/Library/Fonts/GeezaPro.ttc "ي"
[u064a.yeh=0+1417]

$ ./hb-shape --direction=rtl --show-flags --shaper=ot --font-funcs=ot  /System/Library/Fonts/GeezaPro.ttc "يه"
[u0647.final.heh=1+713#1|u064a.initial.yeh=0+656]
```

The first result should have `u0647.final.heh` instead of `u064a.yeh`.

**Comment by ebraminio** [comment]
Interesting. Courier New is not a AAT font but GeezaPro is so I guess applying state machine based shaping context is not implemented yet if is not possible.

**Comment by ebraminio** [comment]
Not also on CoreText AAT, neither AAT nor OT, so shouldn't be Chromium blocker.

**Comment by drott** [comment]
Not a blocker, however, important for LayoutNG.

**Comment by khaledhosny** [comment]
Probably because in AAT the shaping is done by the font state machine which does not take the HarfBuzz buffer context into account, unlike in OpenType where the font just provides the mapping from regular to isolated, initial, medial or final forms and HarfBuzz itself decides which form to select.

**Comment by khaledhosny** [comment]
This probably can be emulated by adding ZWJ as appropriate, if there is no other way to influence how the state machine works (not that I really know how AAT works, so what I’m seeing might be utter nonsense).

**Comment by khaledhosny** [comment]
BTW,  `يه` in the last test should be `هي` to actually get the expected result (i.e. the `ه` should go before, while you are putting it after here).

**Comment by behdad** [comment]
Correct.  This is hard to implement in the AAT model where the entire shaping is driven by font-specific logic.

**Comment by ebraminio** [comment]
Don't know if that shows anything, the result on Firefox,

`data:text/html;charset=utf8,<div style="font-family: 'Geeza Pro'"><span>%D8%B4</span>%D8%B4</div>`

![image](https://user-images.githubusercontent.com/833473/49043290-d5b1cb00-f1df-11e8-8446-7d7f253c077a.png)

**Comment by khaledhosny** [comment]
> Don't know if that shows anything, the result on Firefox,
> 
> `data:text/html;charset=utf8,<div style="font-family: 'Geeza Pro'"><span>%D8%B4</span>%D8%B4</div>`
> 
> ![image](https://user-images.githubusercontent.com/833473/49043290-d5b1cb00-f1df-11e8-8446-7d7f253c077a.png)

Firefox on macOS?

**Comment by ebraminio** [comment]
Yes

**Comment by khaledhosny** [comment]
Firefox does not use the context feature here (it does not allow other OpenType interaction), it passes the full string to the shaper if possible (same font), otherwise passes the substring without context (less ideal, though).

**Comment by ebraminio** [comment]
Oh, so I guess LayoutNG should follow that also

**Comment by khaledhosny** [comment]
Yes, I think so. If the spans are all the same font, then they should be shaped together, otherwise as sub runs with the appropriate context, this way one gets the best of both worlds.

It wouldn’t fix this issue though. One way to fix this is to see if the last non-mark character in the pre context is a left joining one and insert a ZWJ in the shaped string, and vice versa for the post context.

**Comment by behdad** [comment]
I don't think there's a feasible solution here.  Suggest ignoring and accepting this as a limitation.  Layout-ng should probably switch to Firefox-style shaping though, to support mark coloring, etc.

**Comment by khaledhosny** [comment]
Should we close this then?

**Comment by behdad** [comment]
I think so.
