### ISSUE TITLE
Need help with cross-compilation

### ISSUE THREAD

**Issue by r3d9u11** [harfbuzz/harfbuzz#1416]
Hi. I tried to compile harfbuzz 2.1.3 for host arm-linux-gnueabihf, but configuration process was failed with error:
```
/usr/lib/gcc-cross/arm-linux-gnueabihf/5/../../../../arm-linux-gnueabihf/bin/ld: cannot find -licuuc
/usr/lib/gcc-cross/arm-linux-gnueabihf/5/../../../../arm-linux-gnueabihf/bin/ld: cannot find -licudata
```
I can't find any information about libraries "icuuc" and "icudata". Where I can find them?
Thanks.

**Comment by ebraminio** [comment]
There are ICU and ICU data, you can have HarfBuzz without ICU, we have a good number of cross compile recipes [here](https://github.com/harfbuzz/harfbuzz/blob/b518e5/.circleci/config.yml#L248-L311) right on our CI, have a look :) am closing this thread but please continue the discussion here if you had any other question, thanks :)

**Comment by r3d9u11** [comment]
@ebraminio thanks for your answer and link, works fine with option --without-icu !

**Comment by ebraminio** [comment]
Try to enable ICU however if your other parts of software are using it, this way HarfBuzz can use data it offers instead using its own (which is called "built-in ucdn") which shrinks total binary size.
