### ISSUE TITLE
hb-blob.cc:207: error: using 'typename' outside of template

### ISSUE THREAD

**Issue by tlgbjk** [harfbuzz/harfbuzz#1419]
during build process for harfbuzz-2.1.3 getting following error.
is there any patch to get rid of this build error?

hb-blob.cc: In function 'hb_blob_t* hb_blob_get_empty()': 
hb-blob.cc:207: error: using 'typename' outside of template

**Comment by behdad** [comment]
> Same as #1341, I think Behdad you have to make C++11 dependency explicit finally.

It's not C++11.  I made a change to only add "typename" if C++ >= 11 and that broke bunch of compilers.  If you can find a way to tell which compilers need this token and which don't then code it in the code.

**Comment by behdad** [comment]
Okay let's see if this worked.

**Comment by tlgbjk** [comment]
I am still getting same error with latest version harfbuzz-2.2.0
maybe I missed something do you have a suggestion?

**Comment by tlgbjk** [comment]
I did not try master only tried released last version harfbuzz-2.2.0
What is the release plan that include this fix?
Do you have any information about that?

**Comment by ebraminio** [comment]
We will try to release the new version very soon, possibly this week :)
