### ISSUE TITLE
Difference with Apple Color Emoji on some Emojis

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1420]
Different advances, I guess CoreText is right, no differences however on other Emojis from [this list](http://unicode.org/Public/emoji/11.0/emoji-test.txt) (ignorable, like `👁️‍🗨` ot: `['[u1F441=0+800|u1F5E8=0+800]']`, ct: `['[u1F441=0+800|u1F5E8=3+800]']` or `🦹🏻`, ot: `['[.notdef=0+800|u1F3FB=0+800]']`, ct: `['[.notdef=0+800|u1F3FB=1+800]']`)

```
$ harfbuzz/util/hb-shape '/System/Library/Fonts/Apple Color Emoji.ttc' ©️©️©️ --shaper coretext
[u00A9=0+800|u00A9=2+800|u00A9=4+3200]
$ harfbuzz/util/hb-shape '/System/Library/Fonts/Apple Color Emoji.ttc' ©️©️©️ --shaper ot
[u00A9=0+800|space=0+0|u00A9=2+800|space=2+0|u00A9=4+800|space=4+0]
```

```
$ harfbuzz/util/hb-shape '/System/Library/Fonts/Apple Color Emoji.ttc' 5️⃣5️⃣5️⃣ --shaper coretext
[u0035_u20E3=0+800|u0035_u20E3=3+800|u0035_u20E3=6+3200]
$ harfbuzz/util/hb-shape '/System/Library/Fonts/Apple Color Emoji.ttc' 5️⃣5️⃣5️⃣ --shaper ot
[u0035_u20E3=0+800|space=0+0|u0035_u20E3=3+800|space=3+0|u0035_u20E3=6+800|space=6+0]
```

**Comment by ebraminio** [comment]
Wait a minute, this is actually what I wanted to report,

```
$util/hb-shape '/System/Library/Fonts/Apple Color Emoji.ttc' --shaper coretext 4️⃣
[u0034_u20E3=0+1600]

$util/hb-shape '/System/Library/Fonts/Apple Color Emoji.ttc' --shaper ot 4️⃣
[u0034_u20E3=0+800|space=0+0]
```

But now I guess I see the point, space glyph itself have 800 advanced, apparently coretext just have collapsed it. Thanks

**Comment by ebraminio** [comment]
Hmm, if so, this difference can be justified?

```
$ util/hb-shape '/System/Library/Fonts/Apple\ Color\ Emoji.ttc' -u U+1F468,200d,U+1F469,200d,U+1F467,200d,U+1F466 --shaper coretext 
[u1F46A.MWGB=0+800]
$ util/hb-shape '/System/Library/Fonts/Apple\ Color\ Emoji.ttc' -u U+1F468,200d,U+1F469,200d,U+1F467,200d,U+1F466 --shaper ot     
[u1F46A.MWGB=0+800|space=0+0|space=0+0|space=0+0]
```

**Comment by khaledhosny** [comment]
The 3 0 width spaces are just the three U+200D characters, there should be no difference visually. You can use `--remove-default-ignorables` option to get Core Text behavior as already discussed.

**Comment by ebraminio** [comment]
So I guess 1600s are just bugs on hb-coretext, thanks. Am going to add some tests

**Comment by ebraminio** [comment]
It should be desired I guess, some spacing still missing maybe however https://bugs.chromium.org/p/chromium/issues/detail?id=596223#c26 (72.0.3624.0 has hb-aat as I checked)

**Comment by behdad** [comment]
A picture please?  800 vs 1600 should be obvious to see.

**Comment by ebraminio** [comment]
I don't have hb-view on Apple Color Emoji when using --shaper ot IIUC so maybe someone else should help
