### ISSUE TITLE
Awareness of maximum possible value of macOS dynamic library minor version number

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#1431]
I noticed that harfbuzz uses rather large values for `-current_version` and `-compatibility_version` when making macOS dynamic libraries—for version 2.2.0, it uses the value 20201.0.0, for example.

I just wanted to make sure you're aware of the maximum possible values for dynamic library minor version numbers. The first component of the minor version number cannot be larger than 65535, and the second and third components cannot be larger than 255. Trying to use a larger value like 65536 for `-compatibility_version` produces the error:

```
ld: malformed 32-bit x.y.z version number: 65536
```

Using a larger value for `-current_version` produces the warning:

```
ld: warning: truncating -current_version to fit in 32-bit space used by old mach-o format
```

So you're ok for awhile, but if you ever want to be able to release a version 7.0.0 of harfbuzz, you'll need to change the minor version numbering scheme by then. Either that, or increase the major version number (which is currently 0, and which you would need to do if you ever make a backward-incompatible change), since that will let you reset your minor version number to 0.

**Comment by behdad** [comment]
Thanks for the heads up!  Let's close till we get closer to 6.55.36!

**Comment by ebraminio** [comment]
Guess now it's time to be reminded about this.

**Comment by behdad** [comment]
Ugh...

**Comment by behdad** [comment]
> you'll need to change the minor version numbering scheme by then.

Let's figure out a new scheme.

**Comment by behdad** [comment]
I suggest we use one-digit minor.micro numbers and leave the 60000 as a bias.

Ie. right now version 6.0.0 is 60000; version 6.0.1 will jump to 60601. Version 7.0.0 will become 60700.

**Comment by behdad** [comment]
The change to make this is trivial.
