### ISSUE TITLE
CFF warnings

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1436]
```
../../src/hb-ot-cff1-table.hh:374:60: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (unlikely (!ranges[i].sanitize (c) || (num_glyphs < ranges[i].nLeft + 1)))
                                                ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
```
Is there reason that `nLeft` etc are signed?

**Comment by blueshade7** [comment]
nLeft is HBUINT8 or HBUINT16 so must be unsigned. Any chance +1 makes it signed? Weird.

**Comment by behdad** [comment]
Right.  Yes.  That's C rules.  Make it +1u.

**Comment by behdad** [comment]
> nLeft is HBUINT8 or HBUINT16 so must be unsigned. Any chance +1 makes it signed? Weird.

What happens is that HBUINT8 and HBUINT16 have cast operators to uint8_t and uint16_t respectively.  When those are added with 1 which is int, the common type that is chosen is int, since it can fit both values...

**Comment by blueshade7** [comment]
Ah thanks for reminding me. For this particular case I guess I would replace the condition with `num_glyphs <= ranges[i].nLeft`. More concise and potentially more efficient on some platform.

**Comment by behdad** [comment]
> Ah thanks for reminding me. For this particular case I guess I would replace the condition with `num_glyphs <= ranges[i].nLeft`. More concise and potentially more efficient on some platform.

"<=" if done in loops causes the unsafe-optimization warning.  But in conditionals it is indeed more concise and efficient.

Maybe I should change the cast operators for HBUINT8/16/... to int and unsigned int, to avoid this issue.  Let me work on that.

**Comment by behdad** [comment]
Let me change the cast.  I think you don't need to change.

**Comment by behdad** [comment]
Okay, that did it.
