### ISSUE TITLE
redefinition of typedef 'hb_ot_name_id_t' is a C11 feature

### ISSUE THREAD

**Issue by Luflosi** [harfbuzz/harfbuzz#1438]
I'm using harfbuzz 2.2.0 on macOS installed via homebrew. When I try to build another project (kitty) that uses harfbuzz, I get the following error:
```
In file included from /path/to/kitty/kitty/core_text.m:14:
In file included from /usr/local/Cellar/harfbuzz/2.2.0/include/harfbuzz/hb-ot.h:33:
In file included from /usr/local/Cellar/harfbuzz/2.2.0/include/harfbuzz/hb-ot-color.h:37:
/usr/local/Cellar/harfbuzz/2.2.0/include/harfbuzz/hb-ot-name.h:79:22: error: 
      redefinition of typedef 'hb_ot_name_id_t' is a C11 feature
      [-Werror,-Wtypedef-redefinition]
typedef unsigned int hb_ot_name_id_t;
                     ^
/usr/local/Cellar/harfbuzz/2.2.0/include/harfbuzz/hb-deprecated.h:244:22: note: 
      previous definition is here
typedef unsigned int hb_ot_name_id_t; /* Since is in hb-ot.h */
                     ^
1 error generated.
make: *** [app] Error 1
```
If I downgrade harfbuzz with
```
brew switch harfbuzz 2.1.3
```
everything works again.
And according to https://github.com/kovidgoyal/kitty/issues/1196, this is a harfbuzz issue.

**Comment by behdad** [comment]
Is fixed in master.  I shall make a release this week.

**Comment by ebraminio** [comment]
I guess we can disable CFF's get_extents just for one release.

**Comment by behdad** [comment]
Agreed

**Comment by behdad** [comment]
> I guess we can disable CFF's get_extents just for one release.

Wish we had a way to enable certain experimental features in master builds but not in releases, such that it would still get testing (including fuzzer), but we didn't have to disable for every release...

**Comment by ebraminio** [comment]
And experimental APIs

**Comment by ebraminio** [comment]
And hiding whole subset APIs behind that flags

**Comment by behdad** [comment]
Subset API is separate headers and library file, so doesn't matter.

**Comment by Luflosi** [comment]
Could you make the new release please? Or is there something that needs to be done first?

**Comment by ebraminio** [comment]
We were waiting for our [not released yet] CFF/CFF2 implementation get stabilized (fuzzer wise), we are near to that, still two open issues per the bots (uninitialized memory read).

**Comment by behdad** [comment]
2.3.0 release is out.
