### ISSUE TITLE
Use ICU for Indic*Category's when ICU 63 or higher is available

### ISSUE THREAD

**Issue by jungshik** [harfbuzz/harfbuzz#1445]
ICU 63 or higher supports Indic{Syllable,Positional}Category. . Adding the support increased the ICU data size by a few tens of kBs.  If HarfBuzz relies on ICU for that (when it's configured to use ICU for other Unicode data),  downstream products such as Chrome that uses both ICU and HarfBuzz wouldn't have  "two copies" (conceptually) of Indic*Category data. 

See 
https://chromium-review.googlesource.com/c/1289168 .

@drott

**Comment by jungshik** [comment]
@markusicu

**Comment by behdad** [comment]
- We don't always require ICU,
- We tailor that data in very specific ways,
- It's important that data version match the code.

In short, benefits small.  Pain huge.

**Comment by jungshik** [comment]
Fair enough. Thanks. 

> We don't always require ICU,

I knew that.  I wondered if HB can rely on ICU for Indic* properties **when** HB is configured to use ICU.
