### ISSUE TITLE
[aat] Remove 'fdsc' table

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1453]
Not useful for anything.  We are not going to expose it, ever.  Looks like attempts towards what eventually STAT table became...

**Comment by ebraminio** [comment]
> We are not going to expose it, ever.

Why not, I was just going to implement `hb-ot-style` for `STAT` and `fdsc`, I even had created the branch locally...

> Looks like attempts towards what eventually STAT table became...

Yeah, that's the point, Apple doesn't use that inside their fonts. Search for `STAT` and `fdsc` [here](https://gist.github.com/ebraminio/d432e831b3f7ebe30245dde5775e1c7e) to see.

**Comment by behdad** [comment]
> Yeah, that's the point, Apple doesn't use that inside their fonts. Search for `STAT` and `fdsc` [here](https://gist.github.com/ebraminio/d432e831b3f7ebe30245dde5775e1c7e) to see.

Okay, new rule for you: You have to first implement table in fonttools, and only if there's a meaningful set of fonts using it you can push in HarfBuzz.  In this case, I'm not convinced the handful of fonts that have it can benefit from it being implemented at all.

**Comment by behdad** [comment]
> > I'm not convinced the handful of fonts that have it
> 
> How, I mean, isn't such a thing needed for a font matcher

Font weight and width are already available from OS/2 table.  The font "type" (dingbat, etc) is such a horrible idea (and why I asked you to remove this table).  I don't see much new info in this table for a font chooser.

**Comment by ebraminio** [comment]
Right. We don't have to expose that bit.

Still don't see this fundamentally different from STAT, as other values of `fdsc`, I believe, are in use so Apple still ships it.

**Comment by jfkthame** [comment]
> > > I'm not convinced the handful of fonts that have it
> > 
> > 
> > How, I mean, isn't such a thing needed for a font matcher
> 
> Font weight and width are already available from OS/2 table. 

OS/2 is not a required table, per Apple's truetype spec (note its name!), so it's possible they may have shipped some fonts where the appropriate weight/width/slant values are provided by 'fdsc' and not available elsewhere.

**Comment by behdad** [comment]
> OS/2 is not a required table, per Apple's truetype spec (note its name!), so it's possible they may have shipped some fonts where the appropriate weight/width/slant values are provided by 'fdsc' and not available elsewhere.

Sure, if it does fill a gap, I'm not against it.

**Comment by ebraminio** [comment]
Used in https://github.com/harfbuzz/harfbuzz/pull/1459 as I was imagining while adding it.

**Comment by nedley** [comment]
We don’t use fdsc.
