### ISSUE TITLE
Path from CFF/CFF2 glyphs

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1466]
The newly added CFF/CFF2 implementation has an interesting API which makes different applications easy to implement ("PathProcs"s, like "CFF1PathProcs_Extents" and "CFF2PathProcs_Extents"...). My question is in order to have some API to get glyph's paths for possible clients like [glyphy](https://github.com/behdad/glyphy), is getting SVG path like data from CFF/CFF2 table possible, or whether @blueshade7 interested in making such API (no need for a public API for now, just an internal debugging tool will be enough). Thanks

**Comment by behdad** [comment]
Why not have API design discussion for outline extraction first?  I keep saying.  We should start with API, and that should be informed by users' need.  NOT from implementation details.

**Comment by ebraminio** [comment]
I think something similar to [`GetGlyphOutlineW`](https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-getglyphoutlinew) from https://github.com/behdad/glyphy/pull/23/files is what we can have at the end and I like (no IoC). Extracting and dumping individual glyphs of Noto fonts family is the project I want to do at the end so having SVG path style outlines from the glyphs, in nearest way to the original fonts and at the same scale of the font is what I like to have (instead transformations Cairo may apply) so it will be fine to me to have even without a API public, just like what dump-emoji was for a while. And no personal interest in hinting as I want dump SVGs.

**Comment by behdad** [comment]
What is this in relation to https://github.com/harfbuzz/harfbuzz/issues/1686 ?

**Comment by ebraminio** [comment]
Let's close this in favor of that.
