### ISSUE TITLE
 Solaris compiler warning : E_TRAILING_COMMA_IN_ENUM

### ISSUE THREAD

**Issue by prrace** [harfbuzz/harfbuzz#1489]
There are a few occurrences of a Solaris compiler warning that I'll submit for
consideration to fix in upstream :

The Oracle Studio 12.6 C compiler issues these warnings :
"/harfbuzz/hb-ot-name.h", line 77: error: trailing "," prohibited in enum declaration (E_TRAILING_COMMA_IN_ENUM)
"harfbuzz/hb-ot-color.h", line 75: error: trailing "," prohibited in enum declaration (E_TRAILING_COMMA_IN_ENUM)
"harfbuzz/hb-ot-var.h", line 72: error: trailing "," prohibited in enum declaration (E_TRAILING_COMMA_IN_ENUM)

harfbuzz is C++, but if (as we do) you have C code that calls harfbuzz, that
code gets these warnings just by virtue of including standard harfbuzz headers
to as to use the public API.
Some people like the style of adding a trailing "," in lists like this, and if upstream
has these for that reason, I'll quite understand ..

FWIW I also see these warnings from Oracle Studio 12.6 C++ :
"/harfbuzz/hb-map.hh", line 47: Error, fieldsemicolonw: extra ";" ignored.
"harfbuzz/hb-set.hh", line 42: Error, fieldsemicolonw: extra ";" ignored.
but it looks bogus to me, as the macro definition HB_NO_COPY_ASSIGN does
not have the ";" so I'll just suppress that one.

**Comment by behdad** [comment]
> FWIW I also see these warnings from Oracle Studio 12.6 C++ :
> "/harfbuzz/hb-map.hh", line 47: Error, fieldsemicolonw: extra ";" ignored.
> "harfbuzz/hb-set.hh", line 42: Error, fieldsemicolonw: extra ";" ignored.
> but it looks bogus to me, as the macro definition HB_NO_COPY_ASSIGN does
> not have the ";" so I'll just suppress that one.

It's the #else branch that defines it to nothing.  I pushed a fix try.
