### ISSUE TITLE
Tests failing on mips arch

### ISSUE THREAD

**Issue by aelmahmoudy** [harfbuzz/harfbuzz#1498]
Some tests are failing on mips arch:

Relevant errors are:
 FAIL: test-aat-layout
 =====================

 /aat/get/feature/types: **
 ERROR:../../../test/api/test-aat-layout.c:41:test_aat_get_feature_types: assertion failed (11 == hb_aat_layout_get_feature_types (face, 0, &count, features)): (11 == 0)
 FAIL test-aat-layout (exit status: 134)

 FAIL: test-collect-unicodes
 ===========================

 /collect/unicodes: **
 ERROR:../../../test/api/test-collect-unicodes.c:84:test_collect_unicodes: assertion failed: (hb_set_next (codepoints, &cp))
 FAIL test-collect-unicodes (exit status: 134)

 FAIL: test-subset
 =================

 /subset/crash: **
 ERROR:../../../test/api/test-subset.c:91:test_subset_crash: assertion failed: (subset == hb_face_get_empty ())
 FAIL test-subset (exit status: 134)

 FAIL: test-subset-glyf
 ======================

 /subset/glyf: compare glyf
 compare loca
 FAIL test-subset-glyf (exit status: 139)

 FAIL: test-subset-hdmx
 ======================

 /subset/hdmx/invalid: **
 ERROR:../../../test/api/test-subset-hdmx.c:87:test_subset_hdmx_invalid: assertion failed: (subset == hb_face_get_empty ())
 FAIL test-subset-hdmx (exit status: 134)

 FAIL: test-subset-hmtx
 ======================

 /subset/hmtx/monospace: FAIL test-subset-hmtx (exit status: 138)

 FAIL: test-subset-vmtx
 ======================

 /subset/vmtx/noop: FAIL test-subset-vmtx (exit status: 138)

 FAIL: test-ot-color
 ===================

 /hb/ot/color/png: **
 ERROR:../../../test/api/test-ot-color.c:423:test_hb_ot_color_png: assertion failed (length == 224): (0 == 224)
 FAIL test-ot-color (exit status: 134)

 FAIL: test-ot-ligature-carets
 =============================

 /ot/layout/feature/get/name/ids/and/characters: **
 ERROR:../../../test/api/test-ot-ligature-carets.c:41:test_ot_layout_feature_get_name_ids_and_characters: assertion failed (2 == hb_ot_layout_get_ligature_carets (font, HB_DIRECTION_RTL, 98, 0, &caret_count, caret_array)): (2 == 0)
 FAIL test-ot-ligature-carets (exit status: 134)

 FAIL: test-ot-name
 ==================

 /ot/name: **
 ERROR:../../../test/api/test-ot-name.c:80:test_ot_name: assertion failed (12 == num_entries): (12 == 0)
 FAIL test-ot-name (exit status: 134)

 FAIL: test-ot-math
 ==================

 /has/data: **
 ERROR:../../../test/api/test-ot-math.c:97:test_has_data: assertion failed: (hb_ot_math_has_data (hb_face))
 FAIL test-ot-math (exit status: 134)

You can view build log on: https://buildd.debian.org/status/fetch.php?pkg=harfbuzz&arch=mips&ver=2.2.0-1&stamp=1544939431&raw=0

**Comment by behdad** [comment]
Weird.  Can we cross-compile to that arch?  That wouldn't allow us to test though...

**Comment by aelmahmoudy** [comment]
It seems to be failing on big endian archs: : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916782

**Comment by behdad** [comment]
Oh right I know why :(

**Comment by behdad** [comment]
Hopefully fixed.  We really should have a bigendian test bot...
