### ISSUE TITLE
API to get justification character of a script, or, an API for querying info about hb_script_t?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1500]
As #586 and Ben comment [here](https://github.com/harfbuzz/harfbuzz/issues/1487#issuecomment-447977498), we like to provide primitives needed for justification, and I guess the best place to learn what APIs can we provide is our [hb-directwrite](https://github.com/harfbuzz/harfbuzz/blob/244a8627f7b0ed651d6010c7ee7e54fa8fcca400/src/hb-directwrite.cc#L688-L765) implementation which uses that DirectWrite primitives in-action...

So one bit that I was thinking about, which is a good start point also, and needed either we want to do all of the justification by our own or letting client to handle it, is an API equal to [GetScriptProperties](https://github.com/harfbuzz/harfbuzz/blob/244a8627f7b0ed651d6010c7ee7e54fa8fcca400/src/hb-directwrite.cc#L706-L709). The call provides different things about script by [DWRITE_SCRIPT_PROPERTIES](https://docs.microsoft.com/en-us/windows/desktop/api/dwrite_1/ns-dwrite_1-dwrite_script_properties) which to me its only justificationCharacter field is useful for justification.

I wanted to just add that thing in an API maybe named `hb_script_get_justifciation_character` (not necessarily public and may be hold till we get other needed things anyway) but thought if we are going for having that, one may ask what about its other infos that dwrite call can provide, don't we need those? This is a sample of info it provides,

```
i	isoScriptCode	clusterLookahead	isBlockWriting	isConnectedWriting	isCursiveWriting	isDiscreteWriting	isDistributedWithinCluster	isoScriptNumber	justificationCharacter	reserved	restrictCaretToClusters	usesWordDividers
0	Zzzz	15	0	0	0	0	0	999	32	0	0	0
1	Zyyy	1	0	0	0	1	0	998	32	0	0	1
2	Zinh	15	0	0	0	0	0	994	32	0	1	0
3	Arab	8	0	1	1	0	0	160	1600	0	0	1
4	Armn	1	0	0	0	1	0	230	32	0	0	1
5	Avst	8	0	0	0	1	0	134	32	0	0	1
6	Bali	15	0	0	0	1	0	360	32	0	1	0
(...)
```

What are interesting columns we can have or provide, if any? As said, the interesting part to me was `justificationCharacter`, which is 1600 (Kashida) for `Arab`, `Mand`, `Syrc`, `Mani`, `Phlp`, 5760 for `Ogam`, and 32 (space) for others (which means that script doesn't have a Kashida-like character concept).

As said this may doesn't worth to have an API even, however I like to ask is Kashida of a script can be extract from unicode files directly? Is there any other library more suitable to provide such info?

Maybe better to have something like `hb-justification.h`, instead thinking about hb_script_get_* for this, and provide things like these there, populate it with an algorithm to detect good places for inserting Kashida?

**Comment by behdad** [comment]
> So one bit that I was thinking about, which is a good start point also, and needed either we want to do all of the justification by our own or letting client to handle it, is an API equal to [GetScriptProperties](https://github.com/harfbuzz/harfbuzz/blob/244a8627f7b0ed651d6010c7ee7e54fa8fcca400/src/hb-directwrite.cc#L706-L709). The call provides different things about script by [DWRITE_SCRIPT_PROPERTIES](https://docs.microsoft.com/en-us/windows/desktop/api/dwrite_1/ns-dwrite_1-dwrite_script_properties) which to me its only justificationCharacter field is useful for justification.

Okay, the info on that page is helpful.  I think providing such script properties is indeed useful.  I'm only skeptical about the clusterLookahead part.  The rest can come handy for implementing navigation and letterspacing.  @jfkthame @drott would you use such a per-script properties API?

**Comment by ebraminio** [comment]
Closing it in favor of its PR, #1505
