### ISSUE TITLE
[array] clang-everything complains copy=

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#1502]
For this code fragment copying an object of `hb_ubytes_t`:
```
hb_ubytes_t a;
hb_ubytes_t b;
b = a; 
```
bot `clang-everything` emits an error:
```
./hb-array.hh:46:3: error: definition of implicit copy assignment operator for 'hb_array_t<const unsigned char>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated]
  hb_array_t (const hb_array_t &o) : arrayZ (o.arrayZ), len (o.len) {}
```
It appears that clang option `-Wdeprecated` enforces C++11 “Rule of Three” <https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)>, broken by `hb_array_t` which defines only copy constructor, not the other two.

Question is whether array copying is allowed or disallowed. Either way, it shouldn't fail only with some compiler settings, not with others.

This issue was found during an attempt to fix #1496.

**Comment by behdad** [comment]
I'm hitting that as well: https://circleci.com/gh/harfbuzz/harfbuzz/68642
