### ISSUE TITLE
Logic or public API to check if a font supports adding Kashida

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1503]
Related to #586, even the fact we are not that clear on how Kashida API can or should happen, either by adding Kashida to input text, before shaping (which loses the chance to add alternative glyphs available to Kashida a font can support, like a half Kashida, provided by `JSTF`), or by adding the glyph after the shaping (we know DirectWrite [can do that](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-directwrite.cc#L686-L766) after the shaping but using the original information which was available before the shaping), one things certainly we need anyway I guess is a logic to check if a font supports adding Kashida.

Simply the issue is about detecting this case, regular Arabic fonts, used in displaying, can have Kashida everywhere the script is connected, but this is not the case with stylistic ones.

For example IranNastaliq v1 downloadable from [1](https://www.yjc.ir/fa/news/4555441/%D8%A2%D8%AE%D8%B1%D9%8A%D9%86-%D9%86%D8%B3%D8%AE%D9%87-%D9%81%D9%88%D9%86%D8%AA-%D9%86%D8%B3%D8%AA%D8%B9%D9%84%D9%8A%D9%82-%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF) > [2](https://cdn.yjc.ir/files/fa/news/1392/6/25/1538674_809.rar), this is the result with "متن مـتن متـن",

![image](https://user-images.githubusercontent.com/833473/50335098-841b0880-051f-11e9-8adf-082ffa24647b.png)

Which the two left ones, having Kashida, are broken.

IranNastaliq [v2](https://cdn.yjc.ir/files/fa/news/1392/6/25/1538677_674.rar) however can do this better as the point of update was to officially supports Kashida

![image](https://user-images.githubusercontent.com/833473/50335242-e83dcc80-051f-11e9-9df6-d102b606f5d8.png)

(not the best example, it works on different places, but I don't know how to detect that)

However for the sake of simplicity for such API (don't know if it should hb_face_t aware or hb_buffer_t) I guess the version v2 also should be marked as unsafe for adding Kashida.

Or, we should just somehow consider a font can support adding Kashida on the context, <s>then the final API feels like needs to be something like `hb_shape_justification_width` (like our hb_directwrite_shape_experimental_width) considering everything if there is usable entry for such elongation in GSUB while shaping I guess.</s> (not necessarily now I think) 

Microsoft has got this relatively right IIRC as it used to add Kashida to IranNastaliq in IE6 but IE7 was aware to not add Kashida on fonts they may get broken, so maybe we should ask what logic they've used. I didn't check LibreOffice also to see however if is using such logic.

**Comment by khaledhosny** [comment]
LibreOffice Writer first checks if the font has a kashida glyph with > 0 advance before doing any kashida insertion. After shaping it checks if any kashida insertion point is inside a ligature and drops it. Microsoft Word seemed to do different things at different version, but it did not seem to be doing any thing more sophisticated (it does not check for kashida width for sure, try with Amiri where the default kashida glyphs is zero width, it will insert empty gaps for kashida).

**Comment by shahryareiv** [comment]
I appreciate if anyone can contribute to this discussion [here](https://tex.stackexchange.com/questions/520026/what-is-the-current-status-of-kashida-in-bidi-with-luatex) about Kashida in Luatex, especially regarding Harfbuzz technology.

**Comment by typoman** [comment]
I'm not an expert but I was thinking if kashida substitutions are inside the `just` feature, then harfbuzz can hold the substitutions in that feature after the basic shaping. Then insert the kashida and execute the lookups inside the `just`. Maybe this way less proccess is needed to perfrom justification.

**Comment by typoman** [comment]
I just realized `just` is a [table not a feature tag](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6just.html) . Maybe then `jalt` can be the feature to be used for this purpose.

**Comment by ebraminio** [comment]
ot-math apparently had a similar request and the proposed API looks interesting `hb_ot_shape_math_stretchy` and `hb_ot_shape_math_stretchy_max_orthogonal_advance`, maybe something to learn here about how to provide the same JSTF / just
