### ISSUE TITLE
Shape "ۀ" as ه + ـٔ, and vice versa, if needed?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1518]
The Urdu character "ۀ" (U+06C0) is not available in DejaVu sans but ه + ـٔ = هٔ (U+0647,U+0654) is, the issue is however that character, perhaps due to availability in some outdated Persian keyboards, and being exclusively supported in "B Nazanin/..." fonts is used in Persian websites and such. I guess it would be nice to fix the issue on behalf of that popular fonts, or, if we don't like to do so, that can equally make sense to me.

**Comment by dscorbett** [comment]
U+06C0 is actually decomposed into <U+06D5, U+0654>, and HarfBuzz already decomposes and composes it properly:
```console
$ hb-shape DejaVuSans.ttf -u 06C0 --ned --no-positions
[uni0654|uni06D5]
$ hb-shape NotoSansArabic-Regular.ttf -u '06D5 0654' --ned --no-positions
[uni06C0]
```

**Comment by ebraminio** [comment]
So maybe an outdated harfbuzz or different part of stack, or incorrect callbacks?

`B Nazanin`, which supports 06C0 but not that combination,

![image](https://user-images.githubusercontent.com/833473/50522139-a643f600-0ade-11e9-96b8-c2509af02124.png)

`DejaVu Sans`, which is the reverse,

![image](https://user-images.githubusercontent.com/833473/50522187-e3a88380-0ade-11e9-8cdc-2e7d2e623243.png)

(same thing can be seen with Qt AFAICT)

**Comment by dscorbett** [comment]
U+06C0 is decomposed into <U+06D5, U+0654>, but you are testing the sequence <U+0647, U+0654>.

**Comment by ebraminio** [comment]
So we have two issues here, one not harfbuzz related I guess,

![image](https://user-images.githubusercontent.com/833473/50523074-6cc1b980-0ae3-11e9-8a28-8ac0e59ce9d1.png)

I just want to have Qt and Firefox to look like Chrome and hb-view, and seeing the issue on both Qt and Firefox made me think it is probably a harfbuzz bug.

**Comment by behdad** [comment]
Qt and Firefox do their own itemization, which does not consider Unicode normalization.  hb-view doesn't do itemization, and Chrome does HarfBuzz-driven itemization, which understands Unicode normalization.

**Comment by ebraminio** [comment]
Oh, thanks. My fault on mixing two different issues at the end I guess.

The other, which fails in Uniscribe/DirectWrite is,

![image](https://user-images.githubusercontent.com/833473/50523302-9c24f600-0ae4-11e9-8846-c88d7b7171d2.png)

The text sequence is U+0647,U+0654 and I like (personally) that fallbacks to 06C0,

![image](https://user-images.githubusercontent.com/833473/50523347-e0b09180-0ae4-11e9-96f9-79da630cf81a.png)

Why? Because that has blocked the correct unicode use on one of the most popular fonts used on Persian desktop publishing (recommended by universities and so)

Is that a valid wish? If so let's close this and open another for that? If not lets just close this.

**Comment by behdad** [comment]
Can you please describe the problem statement as a problem statement?

**Comment by ebraminio** [comment]
I am sorry again about mixing two separate issues...

`hb-view "B Nazanin.ttf" -u U+0647,U+0654` result is

![image](https://user-images.githubusercontent.com/833473/50523775-2f5f2b00-0ae7-11e9-947d-00e78699c85a.png)

What I like instead to have it like:

`hb-view "B Nazanin.ttf" -u U+06C0`

![image](https://user-images.githubusercontent.com/833473/50523726-f2933400-0ae6-11e9-814c-15cabaf4fbad.png)

So fixing "B Nazanin" on behalf of font designers which I don't know if is valid but I feel is somehow needed in order to encourage correct unicode use.

**Comment by behdad** [comment]
Right.  That comes down to what I said: What we want is for U+06D5 to "decompose" into U+0647 for glyph purposes but /not/ for Arabic-joining purposes, since the former is right-joining and the latter is dual. We currently don't have that capability.

**Comment by khaledhosny** [comment]
Do we really need to do anything here? It is basically bad fonts and unfortunate Unicode normalization (decomposing to a character with different joining behavior does not strike me as the most sensible idea).
