### ISSUE TITLE
Character 0xAD has a glyph in Wingdings font, harfbuzz replaces it with 0x20.

### ISSUE THREAD

**Issue by mowais786** [harfbuzz/harfbuzz#1527]
0xAD character is set default ignore able. Wingdings font has a glyph for 0xAD which is replaced with 0x20. For Wingdings or any other font which has glyph this should not be replaced with 0x20.

**Comment by khaledhosny** [comment]
U+00AD SOFT HYPHEN is a control character, whether it has a glyph in the font or not is irrelevant since its Unicode-complaint rendering is zero-width blank glyph (which is what HarfBuzz do). HarfBuzz has a number of APIs to control this behavior.

Please describe your issue more clearly, i.e. why this behavior is a problem for you.

**Comment by jfkthame** [comment]
I expect it should work to access that glyph via its Private Use codepoint U+F0AD.

**Comment by mowais786** [comment]
My application has a regression test which uses Wingdings font and renders all the characters in it. This character was being displayed with ICU layout engine. I upgraded to Harfbuzz and now 0xAD is not printing. I am new to harfbuzz so not aware of APIs to control this behavior.

**Comment by mowais786** [comment]
> U+00AD SOFT HYPHEN is a control character, whether it has a glyph in the font or not is irrelevant since its Unicode-complaint rendering is zero-width blank glyph (which is what HarfBuzz do). HarfBuzz has a number of APIs to control this behavior.
@khaledhosny  **can you please guide to the APIs to control this behavior?**
> 
> Please describe your issue more clearly, i.e. why this behavior is a problem for you.

**Comment by behdad** [comment]
> Ideally, HarfBuzz should do that for symbol fonts by default somehow.

Umm.  You are probably right.  To implement that we probably should rewrite the text instead of changing the cmap internally.

**Comment by khaledhosny** [comment]
So instead of doing the mapping inside the cmap accelerator, we directly modify the buffer contents early on in the shaping process? I have something locally like that but it feels ugly, should I make a pull request for you to review?

**Comment by behdad** [comment]
Share whatever you have please. I'll comment later, am on phone right now.

**Comment by khaledhosny** [comment]
Testing shows it does not work, will share once I have something working.

**Comment by behdad** [comment]
Don't spend too much time on it before discussing design maybe?  This also involves Eric Muller's request to turn off symbol font cmapping.

**Comment by khaledhosny** [comment]
What I’m considering right now is have `hb_face_set_is_symbol()` (provisional name) that marks the font as symbol font (still need to figure how font functions would be calling that), then check for it and do the mapping somewhere `hb_ot_shape_internal()` (I tried doing it right before the call for `hb_set_unicode_props()` but it does not seem to help, soft hyphen is still converted to space).

**Comment by Richard57** [comment]
There's a claim the the glyph of U+00AD should be used when the line is broken at its location.  How should a HarfBuzz client implement that convention if it so chooses?

**Comment by khaledhosny** [comment]
> There's a claim the the glyph of U+00AD should be used when the line is broken at its location.

That sounds dubious. The glyph should either be U+2010 HYPHEN, U+002D HYPHEN-MINUS, or some other script-specific hyphen glyph.

> How should a HarfBuzz client implement that convention if it so chooses?

Using `hb_font_get_nominal_glyph()` I guess.

**Comment by Richard57** [comment]
Shaping could do the script- or language-specific selection, with features for local variation.

Using hb_font_get_nominal_glyph() totally loses the benefits of shaping, unless I'm missing something.

**Comment by khaledhosny** [comment]
Right, but using the glyph of U+00AD is dubious in the first place. Alternatively, one can shape such buffer with `HB_BUFFER_FLAG_PRESERVE_DEFAULT_IGNORABLES` flag set, but it affects more than soft hyphen.

**Comment by Richard57** [comment]
I think the answer is that the rendering of hyphenation is widely broken when the writing systems doesn't work like English, and one can't cure it in the font.  It was Adam Twardoch who asserted that the glyph of U+00AD should be used.  I've seen some disparate modern line-breaking between aksharas of Pali words in Tai Tham script, from no hyphenation mark to a dash at the Roman baseline.  (I suppose straight lines are OK if one's writing on paper!)   Old style hyphenation will break within aksharas, but that's way beyond the capabilities of soft hyphens.

**Comment by behdad** [comment]
We don't currently have a good answer to how to implement shaping of a the hyphenation.

**Comment by khaledhosny** [comment]
In HarfTeX I shape the string once as if no line breaks occurred at the soft hyphen, and once with the soft hyphen replaced by real hyphen character (set by the user or TeX macro packages) as two parts one including the hyphen and moving backwards to the first safe to break point, and one after the hyphen moving forward to the next safe to break point.

The engine then chooses whether to use the first part of the 2nd two parts based on whether the line is broken here or not.
