### ISSUE TITLE
[AAT] OT vs CoreText discrepancy in shaping ill-formed mark sequence using Thai AAT font

### ISSUE THREAD

**Issue by jfkthame** [harfbuzz/harfbuzz#1528]
Using Thonburi.ttc from macOS 10.13.6:
```
$ hb-shape --font-file Thonburi.ttc --unicodes U+0E17,U+0E35,U+0E48,U+0E4A --shaper coretext
[thothahanthai_saraiithai_maiekthai=0+1616|maitrithai.key=0+1300]
```
where `maitrithai.key` is a glyph that shows MAI TRI over a dotted circle.

However:
```
$ hb-shape --font-file Thonburi.ttc --unicodes U+0E17,U+0E35,U+0E48,U+0E4A --shaper ot
[thothahanthai_saraiithai_maiekthai=0+1616|maitrithai.key=0@-1448,2895+0]
```
Note the incorrect positioning of the `maitrithai.key` glyph: it has been treated as a zero-width mark and overstrikes the preceding glyph.

**Comment by ebraminio** [comment]
`hb-view --font-file /System/Library/Fonts/Thonburi.ttc --unicodes U+0E17,U+0E35,U+0E48,U+0E4A --shaper coretext`

![image](https://user-images.githubusercontent.com/833473/50639512-fb688780-0f76-11e9-9f5b-c7b8838c7ba4.png)

`hb-view --font-file /System/Library/Fonts/Thonburi.ttc --unicodes U+0E17,U+0E35,U+0E48,U+0E4A --shaper ot`

![image](https://user-images.githubusercontent.com/833473/50639487-e7bd2100-0f76-11e9-9a23-9073aa16b7d0.png)

**Comment by behdad** [comment]
@jfkthame what do you suggest we do here?  There's no positioning table whatsoever, so we do our fallback positioning.  And there's no way to know that this is intended to be left standalone.

**Comment by khaledhosny** [comment]
IIRC, CoreText does fallback positioning only for Latin script, so may be we can do that for compatibility when we know it is an AAT font.

**Comment by jfkthame** [comment]
> IIRC, CoreText does fallback positioning only for Latin script, so may be we can do that for compatibility when we know it is an AAT font.

That sounds like it could be a reasonable way forward.

**Comment by behdad** [comment]
> That sounds like it could be a reasonable way forward.

Works for me.  The logic to apply fallback mark positioning is becoming quite a spaghetti though.

**Comment by Richard57** [comment]
Of course, the most natural fallback would be to write the tone marks side by side!  Tai Lue in Lao script uses multiple tone marks on a consonant, which offers a precedent.  Unfortunately, SIL don't provide pictures of the combinations.

**Comment by behdad** [comment]
> That sounds like it could be a reasonable way forward.

Asked Ned for clarification on scripts that do fallback.   Will report.

**Comment by behdad** [comment]
Ned says:
"""No mark width zeroing, and no fallback positioning for Hebrew, Thai, or script with “Shaping Required” == YES according to https://github.com/unicode-org/cldr/blob/master/common/properties/scriptMetadata.txt."""

**Comment by behdad** [comment]
> Ned says:
> """No mark width zeroing, and no fallback positioning for Hebrew, Thai, or script with “Shaping Required” == YES according to https://github.com/unicode-org/cldr/blob/master/common/properties/scriptMetadata.txt."""

Reconciling that with what we do:
```
behdad:src 0 (master)$ git grep fallback_position hb-ot-shape-complex-*.cc | grep true
hb-ot-shape-complex-arabic.cc:  true, /* fallback_position */
hb-ot-shape-complex-default.cc:  true, /* fallback_position */
hb-ot-shape-complex-hebrew.cc:  true, /* fallback_position */
```

So, generally we disagree on Arabic and Hebrew.  But I'm happy with our Arabic/Hebrew.  Don't want to touch that.

The issue is this then: when applying mort/morx, we always choose "default" OT complex-shaper.  It's *that* that has `fallback_position` true, not our Thai shaper.

I'll see what I can do.

**Comment by behdad** [comment]
@jfkthame can you please test / run this through some more testing?
