### ISSUE TITLE
[AAT] Telugu MN shaping discrepancy (CoreText vs OT)

### ISSUE THREAD

**Issue by jfkthame** [harfbuzz/harfbuzz#1529]
Here's a sequence that doesn't shape the same with OT as with CoreText using the Telugu MN font from macOS 10.13.6:
```
$ hb-shape --font-file "Telugu MN.ttc" --unicodes C15,C4D,C37,C3F --shaper coretext
[te_kssa.i=0+1189]

$ hb-shape --font-file "Telugu MN.ttc" --unicodes C15,C4D,C37,C3F --shaper ot
[te_ka.i=0+926|te_ssa.ottu=0@-459,0+0]
```

**Comment by ebraminio** [comment]
10.13.6:

`hb-view --font-file "/Library/Fonts/Telugu\ MN.ttc" --unicodes C15,C4D,C37,C3F --shaper coretext`

![image](https://user-images.githubusercontent.com/833473/50639768-df191a80-0f77-11e9-81bb-acaf22b0efd1.png)

`hb-view --font-file "/Library/Fonts/Telugu\ MN.ttc" --unicodes C15,C4D,C37,C3F --shaper ot`

![image](https://user-images.githubusercontent.com/833473/50639747-ce68a480-0f77-11e9-954a-92c2db695296.png)

**Comment by behdad** [comment]
Umm. That seems to be because we are applying GSUB, not morx.

**Comment by behdad** [comment]
This is because the os2.achVendID is "UNKN", NOT "MUTF". :(

**Comment by jfkthame** [comment]
The achVendID check in OT::GSUB::is_blacklisted to prefer morx over GSUB only on those certain fonts seems a bit of a hack; and these issues demonstrate that it turns out not be adequate.

Given that macOS prefers morx over GSUB (always, I think?), ISTM that for better compatibility, we should make it possible to use harfbuzz in the same way. Otherwise there are likely to be visible discrepancies compared to CoreText in the shaping of some standard system-installed fonts.

There's a tension between matching the behavior of the platform's native text system OR providing consistent behavior across all platforms; given that the native shapers differ between platforms, we can't have both simultaneously. I don't think the harfbuzz library is the right place to make that call; it should support both options and allow the application to determine which it prefers.

So IMO there should be some kind of API (a flag that can be set on the buffer?) to let the client app decide whether to prefer morx or GSUB in the case where both are present.

**Comment by behdad** [comment]
> So IMO there should be some kind of API (a flag that can be set on the buffer?) to let the client app decide whether to prefer morx or GSUB in the case where both are present.

Right.  Back to the flag.  I think at this point I'm most comfortable with this.  But, would that also enable Uniscribe bug compatibility for example?  I don't think it should...

Buffer flag `FIDELITY_PLATFORM` or something?

**Comment by behdad** [comment]
> Buffer flag `FIDELITY_PLATFORM` or something?

It's a bit unfortunate to put this on the buffer and not shape plan.  But shape plan abstraction has proved to be implementation detail and not useful externally.  So maybe doesn't matter.

**Comment by jfkthame** [comment]
> Buffer flag `FIDELITY_PLATFORM` or something?

I'd lean towards something like `PREFER_AAT` that directly says what it does. There may be various aspects of "platform fidelity" -- uniscribe bug-compatibility being the obvious example -- and I think harfbuzz should simply expose the individual options and let the client decide which combination of features it wants.

**Comment by behdad** [comment]
> I'd lean towards something like `PREFER_AAT` that directly says what it does. There may be various aspects of "platform fidelity" -- uniscribe bug-compatibility being the obvious example -- and I think harfbuzz should simply expose the individual options and let the client decide which combination of features it wants.

Okay then maybe exposing shaper name "aat" that prefers aat over ot is better approach.  Default remains shaper "ot" which prefers ot over aat.

**Comment by jfkthame** [comment]
Yeah, that could work. It feels a little weird to me, though, in that having shapers named "ot" and "aat" makes it sound like each of them *only* shapes that particular layout technology (and so a client would use a shaper list of "ot,aat" or "aat,ot" depending on its preference). But that's not how things would actually work; either one of them alone does handle both technologies, just with different priority.

**Comment by behdad** [comment]
Right.  That awkwardness is to maintain current behavior, which is that shaper "ot" is default.

**Comment by jfkthame** [comment]
Understood. I can live with it, just feel that it's a bit confusing (so needs to be highlighted in documentation, I guess -- something for @n8willis to note if you go this way). To my mind, a `PREFER_AAT` flag seems easier to understand, but it's your call.

**Comment by behdad** [comment]
I can change default shaper to "auto" and add "ot", "aat", "ot-aat", and "aat-ot".  I think only XeTeX calls HB with specific shaper, and they can switch.  Otherwise they just get OpenType only, which is not worse than before we supported AAT.

**Comment by jfkthame** [comment]
@behdad Could we move this forward, one way or another? My current thinking is that

> I can change default shaper to "auto" and add "ot", "aat", "ot-aat", and "aat-ot"

seems like overkill; if you want to go in that direction, I'd suggest just "auto", "ot", "aat" (where "ot" and "aat" *do* fall back to the other shaping technology, the only difference is their order of preference). "auto" (default) could include the current test for os2.achVendID=MUTF and adjust its preference accordingly (and any other heuristics we might come up with some day), whereas "ot" wouldn't do that, it would always prefer GSUB/GPOS.

**Comment by ebraminio** [comment]
Maybe adding just a `aat-ot` for now and leaving the rest for future, I don't believe something more than that is needed in practice anyway.

**Comment by behdad** [comment]
The other approach is to blacklist those GSUB tables, like we do for GDEF of other fonts; at least as interim solution to replace the 'MUTF' hack.

**Comment by behdad** [comment]
Jonathan and I talked about this now again.  I think we want to switch to preferring AAT over OT, and if necessary, later, add a new side table to allow font to opt into preferring OT over AAT shaping.

**Comment by ebraminio** [comment]
That's great! Considering the fonts that may break were broken in all of Apple products already anyway.

**Comment by drott** [comment]
For Chrome, this causes issues with "Hiragino Mincho ProN W3" (`ヒラギノ明朝 ProN W3.otf`) on Mac OS 10.10 which has mixed GSUB and morx. When we shape a run of text as dir=ttb the AAT vertical substitution gets applied which rotates the glyphs sideways. 

```
$ util/hb-shape  ヒラギノ明朝\ ProN\ W3.otf --features=-vert  --direction=ttb "(Hel
lo)" 
[gid9=0@-157,-880+0,-1000|gid41=1@-398,-880+0,-1000|gid70=2@-267,-880+0,-1000|gid77=3@-148,-880+0,-1000|gid77=4@-148,-880+0,-1000|gid80=5@-291,-880+0,-1000|gid10=6@-157,-880+0,-1000]

$ util/hb-shape  ヒラギノ明朝\ ProN\ W3.otf   --direction=ttb "(Hello)" 
[gid8728=0@-500,-880+0,-314|gid8760=1@-500,-880+0,-797|gid8789=2@-500,-880+0,-535|gid8796=3@-500,-880+0,-296|gid8796=4@-500,-880+0,-296|gid8799=5@-500,-880+0,-583|gid8729=6@-500,-880+0,-314]
```

When I disable `vert`, using `--features=-vert` nothing gets replaced, but that means I won't get rotated brackets when displaying `(Hello)` in upright.

**Comment by drott** [comment]
In a run like `(Hello)` `OrientationIterator` would break runs because the brackets are `VO_Rotated` and the latin text is not. So for the VO_Rotated runs, I would let the font do the rotation if it prefers to do so, otherwise we rotate ourselves (so I would have to move Orientation one level down and sync it with the font)? - and until we have that logic, disable `-vert`?

**Comment by twardoch** [comment]
In my internal terminology, SFNT has four major layout technologies: OT (GSUB, GPOS), AAT (morx, kerx/kern), TT (kern), SIL (Graphite). 

If the current "ot" shaper already uses OT but then falls back to AAT and turn falls back to TT, then the shaper name already works as a preference hint rather than an exclusive indicator. And it's the by far more useful approach then having it by "try this and nothing else" in practice. So "aat" should also work as a preference hint. 

There could be shaper names 'test-ot', 'test-aat' and maybe 'test-tt' that are used as "try this and nothing else". Or 'ot-only', 'aat-only' etc. They'd be more useful for testing or for apps such as FontLab etc. but would be clearly not the recommended general-use scenarios.

**Comment by twardoch** [comment]
Or 'ot-dev', 'aat-dev'. Those could also be clean of any other fallbacks like Arabic fallbacks based on Unicode (if HB still uses that).

**Comment by ebraminio** [comment]
Believe providing those specific things for the sake of font designers is a
justifiable requirement.
