### ISSUE TITLE
[AAT] ផ្ស៊ាំ ផ្ស‌៊ាំ

### ISSUE THREAD

**Issue by olivierberten** [harfbuzz/harfbuzz#1534]
I don't have a OSX at hand but could you check these sequences?
U+1795,U+17D2,U+179F,U+17CA,U+17B6,U+17C6 and U+1795,U+17D2,U+179F,U+200C,U+17CA,U+17B6,U+17C6

**Comment by olivierberten** [comment]
with https://scripts.sil.org/mondulkiri
(might be worth comparing it with Uniscribe too)

**Comment by ebraminio** [comment]
CoreText:

`hb-view Mondulkiri-7.100/Mondulkiri-R.ttf  -u U+1795,U+17D2,U+179F,U+17CA,U+17B6,U+17C6,U+20,U+1795,U+17D2,U+179F,U+200C,U+17CA,U+17B6,U+17C6 --shaper=coretext`

![image](https://user-images.githubusercontent.com/833473/50727811-724b7f00-1135-11e9-9f16-c8400ccb9339.png)

`[uni17C6.ms.psom=0+2775|space=6+1200|uni1795=7+1425|uni17D2179F=7+675|space=10+0|uni17CA.aa=10+0|uni17C6=10+0]`

HarfBuzz:

`HB_OPTIONS=aat hb-view Mondulkiri-7.100/Mondulkiri-R.ttf  -u U+1795,U+17D2,U+179F,U+17CA,U+17B6,U+17C6,U+20,U+1795,U+17D2,U+179F,U+200C,U+17CA,U+17B6,U+17C6 --shaper=ot`

![image](https://user-images.githubusercontent.com/833473/50727846-0ae1ff00-1136-11e9-8a40-17008e85db81.png)

[uni17C6.ms.psom=0+2775|space=6+1200|uni1795=7+1425|uni17D2179F=7+675|space=10+0|uni17CA.aa=10+0|uni17C6=10+0]

HarfBuzz replicates CoreText correctly but in OT mode, the default one, harfbuzz does what it does in other platforms,

`hb-view Mondulkiri-7.100/Mondulkiri-R.ttf  -u U+1795,U+17D2,U+179F,U+17CA,U+17B6,U+17C6,U+20,U+1795,U+17D2,U+179F,U+200C,U+17CA,U+17B6,U+17C6 --shaper=ot`

![image](https://user-images.githubusercontent.com/833473/50727820-9b6c0f80-1135-11e9-9a38-a372caf48e94.png)

[uni17C6.ms.psom=0+2775|space=6+1200|uni1795=7+1425|uni17D2179F=7+675|space=10+0|uni17CA=10+0|uni17B6=10+675|uni17C6.x=10+0]

**Comment by ebraminio** [comment]
I don't have macOS also, just misusing CI bots ;)

So the expected behavior from HarfBuzz AFAIK, closing the file :)
