### ISSUE TITLE
Investigate clang-format

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1536]
I'm open to investigating a clang-format config that is close to our code style and start enforcing it.  Also open to mass style changes when we have clang-format set up.

**Comment by ebraminio** [comment]
Great.

So the first issue, I couldn't find something able to apply our mixed tab-space style in clang-format, maybe I didn't search enough however, or can you see clang-format config of similar [Gnome] projects you know? Thanks

**Comment by ebraminio** [comment]
* https://zed0.co.uk/clang-format-configurator/
* https://clangformat.com/
* https://github.com/torvalds/linux/blob/master/.clang-format

**Comment by behdad** [comment]
> So the first issue, I couldn't find something able to apply our mixed tab-space style in clang-format

What about:
```
IndentWidth: 2
TabWidth: 8
UseTab: ForIndentation
```

**Comment by ebraminio** [comment]
Works, thanks! Doesn't work for function parameters, probably a bug. What I got till now, ruins the nice tables comments as now, will update the comment when finding things making clang-format more compatible with our style. To others, feel free to help and find things we have actually

```
IndentWidth: 2
TabWidth: 8
UseTab: ForIndentation
SpaceBeforeParens: Always
AllowShortLoopsOnASingleLine: true
BreakBeforeBraces: Stroustrup
AlignTrailingComments: true
AllowShortFunctionsOnASingleLine: Inline
AccessModifierOffset: 0
AlignConsecutiveDeclarations: true
AlignTrailingComments: true
AllowShortIfStatementsOnASingleLine: true
```

**Comment by behdad** [comment]
Try UseTab: Always.

**Comment by behdad** [comment]
Feel free to add a dot-file for your closest config.

**Comment by ebraminio** [comment]
Not enforcing it, maybe we should fill some bugs on clang-format side and opening this till the full adoption?
