### ISSUE TITLE
TARGET_OS_OSX is not defined on older OSX versions...

### ISSUE THREAD

**Issue by kencu** [harfbuzz/harfbuzz#1540]
So this beautiful workaround in `hb-coretext.cc` fails to function:
```
#if TARGET_OS_OSX && MAC_OS_X_VERSION_MIN_REQUIRED < 1060
      atsFont = CTFontGetPlatformFont (new_ct_font, NULL);
      status = ATSFontGetFileReference (atsFont, &fsref);
      if (status == noErr)
        new_url = CFURLCreateFromFSRef (NULL, &fsref);
#else
      new_url = (CFURLRef) CTFontCopyAttribute (new_ct_font, kCTFontURLAttribute);
#endif
```
Once that is fixed, the software builds perfectly on < 10.6, and thank you for that effort.

Would it be OK to just use?
```
#if MAC_OS_X_VERSION_MIN_REQUIRED < 1060
```

**Comment by ryandesign** [comment]
> It was [suggested](https://github.com/harfbuzz/harfbuzz/pull/1179) that this should be fixed by checking:
> 
> ```
> #if !TARGET_OS_IPHONE && MAC_OS_X_VERSION_MIN_REQUIRED < 1060
> ```
> I think that would have worked.

With that change it builds successfully on 10.4.

Another option could be:

```
#if defined(MAC_OS_X_VERSION_MIN_REQUIRED) && MAC_OS_X_VERSION_MIN_REQUIRED < 1060
```

Apple probably has some recommendations on what to do, but I'm not sure how to find them at the moment.

**Comment by kencu** [comment]
Ryan is the maintainer of this software in MacPorts, has patched it already in MacPorts, and originally asked me to open this issue. I will leave the suggested fix to Ryan.

**Comment by kencu** [comment]
@ryandesign -- do you want to finish this off, or shall I take it?

**Comment by kencu** [comment]
We have been using `!TARGET_OS_IPHONE` on MacPorts for the past weeks, and that works on all MacOS systems from 10.4 PPC on up to the current system. It will also exclude (obviously) IPHONE OS. 

I notice there are several other places in this source file where `MAC_OS_X_VERSION_MIN_REQUIRED` is used without any `OS` guards, but presumably these are still somehow working out OK and you want to leave those alone. I will make a PR for this one change, with a short note above it about why.
