### ISSUE TITLE
Changed behavior of Khmer character “◌្” (U+17D2)

### ISSUE THREAD

**Issue by wonrst** [harfbuzz/harfbuzz#1541]
Using KhmerOS.ttf from Ubuntu 16.04 LTS:

I have noticed that changed behavior of Khmer character “◌្” (U+17D2)
https://www.compart.com/en/unicode/U+17D2
is not normally represented in the latest harfbuzz.

It seems that the behavior has changed based on the commit below.

efefd87f3354d0ae6f599ea30672cb0b74dfcd80
![af](https://user-images.githubusercontent.com/11732754/51174374-fb637280-18fa-11e9-8eef-f063c64b78c3.png)
This is the result of typing U+17D2 8 times in text editor.
It is not visible on the platform I use(left), and gedit(right) overlaps 8 characters in one place.

82e6bf8e0c27d2fd16a908eed0c73e95b1a2c0f5
![be](https://user-images.githubusercontent.com/11732754/51174378-fdc5cc80-18fa-11e9-9ada-8351e2d63ce6.png)
In this commit,
8 characters are shown as a result of typing 8 times (this is my expected result).

I want to know if this is a normal behavior, or a bug.

**Comment by behdad** [comment]
I'm not sure I understand your report.  What does latest HarfBuzz do, and what do you expect it to do?

**Comment by wonrst** [comment]
Hello : )

This is the result of typing U+17D2 eight times in text editor.
I expected all 8 characters to be visible.
It seems that the behavior has changed since this commit. efefd87

[latest]
![af](https://user-images.githubusercontent.com/11732754/51291965-696b7f00-1a4c-11e9-9908-63e97433e2cd.png)

[expected] - 82e6bf8
![be](https://user-images.githubusercontent.com/11732754/51291970-70928d00-1a4c-11e9-91bc-e257e2faaaed.png)

**Comment by Ali-Alzyoud** [comment]
This project show the issue (modified harfbuzz tutorial):
https://github.com/Ali-Alzyoud/Harfbuzz-khmer.git

if you run the project with latest harfbuzz you will not get right results.
but if you run with harfbuzz (git checkout 82e6bf8) you will get right results.

After some investigations :
Old harfbuzz
when you add '\u17D2' to buffer and shape it will buffer will contains 'uni25CC' + 'uni17D2'
New harfbuzz
when you add '\u17D2' to buffer and shape it will buffer will contains only 'uni17D2'

**Comment by behdad** [comment]
Ah okay.  Finally I understand what this issue is about!  Thanks.  Will fix.

**Comment by behdad** [comment]
Jonathan, what do you think?  In the reworked Khmer shaper, we do not allow tail coeng without a following consonant.  Other shapers (indic, myanmar, use) allow that, typically in an exception to the grammar that accepts a final halant instead of matra group (I suppose that's to accommodate halants mid-typing).  I suggest doing the same to Khmer.

**Comment by behdad** [comment]
@jfkthame ^

**Comment by Ali-Alzyoud** [comment]
Many thanks for the fast reply and Fix
