### ISSUE TITLE
GPOS kerning broken on fonts with 'morx'

### ISSUE THREAD

**Issue by smarcum720** [harfbuzz/harfbuzz#1542]
Found in version 2.3.0

From what I can tell, if the 'morx' table is present the only option to kern is via the 'kerx' table (the decision made in hb_ot_shape_planner_t::compile). One of the Apple system fonts - GillSans.ttc - has the 'morx', but no 'kerx'.

Kerning information is correctly present in GPOS/kern, but this doesn't seem be accessed.

Font used - /Library/Fonts/GillSans.ttc on OSX 10.12.6
shasum - 12e6b81d634c959675c4d4325338d2b5c026140f

**Comment by smarcum720** [comment]
Seems intended via https://github.com/harfbuzz/harfbuzz/commit/7a97f70 ?

**Comment by behdad** [comment]
What does CoreText do?  What are a few good test sequences?

@ebraminio

**Comment by smarcum720** [comment]
I made a mistake in my initial assessment, Harfbuzz will actually go it's fallback path to get kerning information from the 'kern' table, which **is** present in GillSans.ttc.

I guess it could be possible that a font:
- Has morx
- Has empty GSUB
- Has GPOS/kern
- Does not have kerx table
- Does not have kern table

In which case I think we would not get any of the kerning values. However I don't have an example of this currently, and maybe such a font could be considered "broken".

Will close this issue for now.

**Comment by coreh** [comment]
I know this was originally closed, but we're hitting a kerning bug with Gill Sans on Chrome, and I _think_ it might be related to or caused by this. 

https://bugs.chromium.org/p/chromium/issues/detail?id=1004945

What if the `kern` table differs from the `kerx` table, could this lead to incorrect kerning on Gill Sans?

**Comment by ebraminio** [comment]
If the result of most recent versions of Firefox is different from Chrome
something else and probably not HarfBuzz related is going on specially as
Gill Sans doesn't have trakwhich is handeled differently, can you check
hb-view result with different back ends (--shaper=ot and --shaper=coretext)
(as we don't good access to macOS) and file a separate bug?

**Comment by coreh** [comment]
@ebraminio Thanks for running the `hb-view` tests and filing the other bug! Wasn't able to do it during the week, was going to try to tackle it today, but you saved me some time there! 🙌
