### ISSUE TITLE
Mark placement on multiple substitution

### ISSUE THREAD

**Issue by punchcutter** [harfbuzz/harfbuzz#1545]
Rather than reopen https://github.com/harfbuzz/harfbuzz/issues/740 I'm starting a new issue. We thought this was fixed there, but https://github.com/googlei18n/noto-fonts/issues/1379 shows that something is still not quite right.
With https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansNewa-Regular.ttf      

This sequence that I posted originally works fine and the Candrabindu attaches to the 2nd half of the AU split-vowel.

U+11410,U+11442,U+11411,U+11441,U+11443
[E_dv.alt=0+275|Ga.icd=0+367|Gha.diag=0@100,0+386|AU_dv_part.alt=0+213|Candrabindu.sm=0@-52,179+0]
![good](https://user-images.githubusercontent.com/11257204/51364910-9fcbed00-1a92-11e9-82c1-79fe62427280.png)

but this sequence does not apply mark to base even though we are assuming the same logic:

U+11410,U+11441,U+11443
[E_dv.alt=0+275|Ga=0+576|AU_dv_part.alt=0+213|Candrabindu.sm=0@-140,-8+0]

![bad](https://user-images.githubusercontent.com/11257204/51364939-b6724400-1a92-11e9-858a-5ff503f2a603.png)

The main difference is that the first sequence has an H+B form. Otherwise it's basically the same thing:
 
1. U+11441 Vowel Sign AU splits into pre-base E and post-base AU using a multiple substitution
2. The E vowel is reordered to before the base
3. The U+11443 Candrabindu at the end has mark to base and should apply to the 2nd part of this split vowel, in this case AU_dv_part.alt

**Comment by behdad** [comment]
Was this fixed, or worked around in the font? I cannot reproduce it.

**Comment by punchcutter** [comment]
This was worked around in the font by making composite glyphs with the candrabindu already in the correct position.
