### ISSUE TITLE
hb-shape --trace intermediate steps not accurate because of deferred mark attachment

### ISSUE THREAD

**Issue by punchcutter** [harfbuzz/harfbuzz#1554]
This never really bothered me too much before, but I'm trying to verify lookups with `hb-shape --trace` and because mark attachment is deferred the lookups that actually do the mark placement don't show the correct information for what's happening in that lookup. Instead they show no change between `trace: start lookup` and `trace: end lookup`. Then when we reach the final output it suddenly shows any deferred mark attachment. 
I'd like to see the actual result of each lookup as it happens, but if it's not possible or not desirable then we can just forget it and close this.

**Comment by behdad** [comment]
Yeah not easy...

Note that it's not that it doesn't do *anything* between start and end.  It puts the relative offsets there.  Then the relative numbers become absolute when resolution happens at the end.

**Comment by punchcutter** [comment]
Right, it's clear that it gets the offsets there, but the trace output shows as if nothing had happened. So if you try to draw the output at that point then of course nothing happens. So it _feels_ like nothing has happened. I would just love to be able to step through each lookup and see 100% what is going on before/after the lookup, but if that's too much to ask in `--trace` then I can deal with it another way.

**Comment by behdad** [comment]
I agree that it would be nice.  The trace interface was made such that a visual debugger can be made on top of.

There are two ways that that can be done:

1. When we expose the attachment tree, we can also then expose a function that does the "finishing".  We internally call that `gpos_finish` indeed.   Then you can copy the buffer and finish it in each trace callback.

2. If the trace function returns false from a lookup's start callback, then that lookup will be skipped.  You can shape multiple times, each time skipping all lookups after N, to get the effects up to N'th lookup.  Messy.

Neither case makes the output of `hb-shape --trace` more useful though.

**Comment by behdad** [comment]
> 2\. If the trace function returns false from a lookup's start callback, then that lookup will be skipped.  You can shape multiple times, each time skipping all lookups after N, to get the effects up to N'th lookup.  Messy.

This.

We discussing now in https://github.com/harfbuzz/harfbuzz/issues/2468
