### ISSUE TITLE
[subset] TrueType/CFF2 variable font

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#1558]
- [x] Add HVAR & VVAR subsetting for TT/CFF2
- [x] Add gvar struct for TT (sanitize, look-up, subsetting)
- [x] Calculate TT VF glyph widths (if HVAR/VVAR absent)
- [x] Calculate TT VF glyph extents from glyf & gvar (no hint support)
- [x] Add tests (subset: gvar, HVAR, VVAR)
- [x] Add tests (TT VF widths & extents)
- [x] ItemVariationStore subsetting in GPOS, GDEF
- [ ] Add tests (subset: VF GPOS, GDEF)

Not to subset: MVAR, BASE, cvar
Not in scope: axes subsetting, instantiation

**Comment by blueshade7** [comment]
Removed task "Calculate TT/CFF2 VF glyph widths from HVAR/VVAR" because it is already in place

**Comment by blueshade7** [comment]
This is my plan for HVAR & VVAR subsetting including VariationStore.

`HVAR::subset` to be called by `_subset2`; seems more convenient than `_subset` which requires to know size upfront (maybe rewrite CFF/CFF2 subsetter using `_subset2` later?)

To subset inner indices for VariationStore, I am going to repurpose `CFF::remap_t` (one for each outer index), rewriting it based on `hb_map_t` & `hb_set_t`. Inner indices referenced by advMap/lsbMap/rsbMap are collected in `hb_set_t`, then old to new mapping is stored in `hb_map_t`.

I am not going to bother subsetting & remapping outer indices; for an unused outer index, its corresponding item variation data subtable is emptied. This wastes 6 bytes each but I don’t expect to see many outer indices in wild after all.

**Comment by blueshade7** [comment]
Actually an empty item variation data subtable wastes 10 bytes counting 4-byte offset. It would be nice if an item variation data offset may be set to null for a missing table, but OTF spec doesn't seem to say so. Darn.

**Comment by blueshade7** [comment]
Created branch var-subset for this task

**Comment by blueshade7** [comment]
Decided to subset outer indices & variation data subtables after all, as fontTools appears to support it.
Pushed HVAR & VVAR subset to var-subset branch.

**Comment by blueshade7** [comment]
Pushed advance width calculation from gvar & glyf

**Comment by blueshade7** [comment]
Pushed glyph extents calculation using gvar & glyf
Added api test `test-ot-metrics-tt-var`, subset full font test with a TT variable font

**Comment by behdad** [comment]
Closing since there's nothing actionable here.
