### ISSUE TITLE
Contextual decomposition

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#1559]
I copied the following strings into LibreOffice Writer 6.2.0.2 (x64), and then set the font face as Source Sans Pro, but the diaeresis below doesn’t work. The developer suggests
```
ā̤ê̤ó̤ṳ
```
![snapshot](https://user-images.githubusercontent.com/10364351/51717260-1db26a00-2038-11e9-872e-710c6420bd7b.PNG)
The developer suggests to support contextual decomposition in order for proper mark positioning. Is it possible to do it in HarfBuzz?
See: https://github.com/adobe-fonts/source-sans-pro/issues/158

**Comment by khaledhosny** [comment]
Works with both `hb-view` and LibreOffice 6.1.4.2 on Linux with Source Sans Pro 2.045. Either a bug on your version of the fonts or LibreOffice.

**Comment by frankrolf** [comment]
The problem may be as simple as this (bundled fonts are outdated):
https://github.com/adobe-fonts/source-serif-pro/issues/61
