### ISSUE TITLE
Word spacing for Korean vertical text

### ISSUE THREAD

**Issue by EugeneKosmin** [harfbuzz/harfbuzz#1562]
Hi,

I'm facing a problem with a too high distance between words for Korean vertical text. Maybe not an issue, but I tried to play with options and no success. Maybe I missed something.

`hb-view.exe --unicodes="AF43 20 B3C4" --output-file=out.png --direction=ttb NanumBarunGothicOTFBold.otf`

Chrome and Photoshop work fine. I tried two different fonts, one of them from Adobe.
https://raw.githubusercontent.com/asata/react-native-naver-font/master/font/NanumBarunGothicOTFBold.otf

https://raw.githubusercontent.com/adobe-fonts/source-han-sans/release/OTF/Korean/SourceHanSansK-Regular.otf

![SourceHanSansK-Regular](https://user-images.githubusercontent.com/7608298/51815747-a4479f80-22f5-11e9-90cb-b30858986c5d.png)  ![NanumBarunGothicOTFBold](https://user-images.githubusercontent.com/7608298/51815724-9134cf80-22f5-11e9-89dd-3b24c00c8254.png)

Is there something I can do with harfbuzz to get the result closer to photoshop's?

**Comment by behdad** [comment]
Other systems are rendering the space character as rotated horizontal text (try entering some Latin to see what I mean) whereas hb-view renders it in the direction you instruct it to.  Segmenting text into multiple runs is beyond HarfBuzz and must happen in higher level.

**Comment by behdad** [comment]
That said, if your font has vertical advances (`vmtx` table) then it does specify the advance of the space character, and HarfBuzz will be using that exactly.  So you can modify the font to get different behavior.

**Comment by EugeneKosmin** [comment]
OK, thanks for the explanation.
