### ISSUE TITLE
[ci] multiarch/crossbuild compiler too old??

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1566]
The clang-O3-O0 bot uses this docker image, and for iter branch is giving me:
```
./hb-algs.hh:74:3: error: default initialization of an object of const type 'const struct (anonymous struct at ./hb-algs.hh:70:14)' requires a user-provided default constructor
```

This seems to be caused by an old compiler I think.
https://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a
has:
`gcc has accepted this since 4.6.4. clang has accepted this since 3.9.0. Visual Studio also accepts this (at least in 2017, not sure if sooner).`

I think I'll change configure to print compiler version.  But, why are we using this docker image?  Should I just change it to ubuntu?

**Comment by behdad** [comment]
I disabled it for now.  Please re-enable if we need this arch.  Or close.

**Comment by ebraminio** [comment]
Works for me
