### ISSUE TITLE
Need a design -> normalized coord api

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#1568]
I want to display sliders for the axes, using the min/default/max values from the axis info struct, which are in design coordinates. To position the sliders, I need to use the normalized coords I get from hb_font_get_var_coords_normalized, and ... translated them back into the design space.

I would sugggest an api like
```
HB_EXTERN void
hb_ot_var_denormalize_coords (hb_face_t    *face,
                                 unsigned int coords_length,
                                 const int *normalized_coords, /* IN */
                                 float *design_coords /* OUT */);
```

**Comment by behdad** [comment]
Right..

**Comment by matthiasclasen** [comment]
Now that hb_font_get_var_coords_design is no longer experimental, my problem here is solved.
