### ISSUE TITLE
Does Mark to Mark, depends on Mark to Base?

### ISSUE THREAD

**Issue by YKubi** [harfbuzz/harfbuzz#1570]
I have posted a discussion on TypeDrawers - [HERE](http://typedrawers.com/discussion/3033/does-mark-to-mark-depends-on-mark-to-base), about this issue.
I have made this font for checking: [HB_mkmk.zip](https://github.com/harfbuzz/harfbuzz/files/2832274/HB_mkmk.zip)

The font [Attached] has no Mark to Base {mark}, and has only Mark to Mark {mkmk}
HarfBuzz does not make the {mkmk} offset
I wish to understand the way HarfBuzz deal with that:
**Where in the code it handles it?**
This is what i got on HarfBuzz:
![image](https://user-images.githubusercontent.com/44770058/52275156-65e65c00-2957-11e9-9bf7-601ecb82af86.png)

And this is how it shows on FontCreator preview [doing the {mkmk} offset:
![td_mkmk](https://user-images.githubusercontent.com/44770058/52276197-3a18a580-295a-11e9-9578-2dd878eb28cc.png)

**Comment by behdad** [comment]
It doesn't.  Should work.

**Comment by YKubi** [comment]
Thank you very much for the amazing HarfBuzz!!
And thanks for your reply.
I have made a check with HarfBuzz, rendering: אָ֧ [=u05D0,u05B8,u05A7]
Using a font with **no** Mark to Base - Only Mark to Mark -
It **does not** work!
The result is that the second mark is on top of the first (see [picture](https://user-images.githubusercontent.com/44770058/52275156-65e65c00-2957-11e9-9bf7-601ecb82af86.png) above).
I will be most grateful if you can make this check with the font [attached](https://github.com/harfbuzz/harfbuzz/files/2832274/HB_mkmk.zip) above.

**Comment by moyogo** [comment]
It looks like you have the anchors set backwards. uni05A7 should be mark1, the attachment mark, and uni05B8 should be mark1, the base mark.

Here the ttx dump of what you currently have
```xml
      <Lookup index="0">
        <LookupType value="6"/>
        <LookupFlag value="1"/>
        <!-- SubTableCount=1 -->
        <MarkMarkPos index="0" Format="1">
          <Mark1Coverage Format="1">
            <Glyph value="uni05B8"/>
          </Mark1Coverage>
          <Mark2Coverage Format="1">
            <Glyph value="uni05A7"/>
          </Mark2Coverage>
          <!-- ClassCount=1 -->
          <Mark1Array>
            <!-- MarkCount=1 -->
            <MarkRecord index="0">
              <Class value="0"/>
              <MarkAnchor Format="1">
                <XCoordinate value="450"/>
                <YCoordinate value="0"/>
              </MarkAnchor>
            </MarkRecord>
          </Mark1Array>
          <Mark2Array>
            <!-- Mark2Count=1 -->
            <Mark2Record index="0">
              <Mark2Anchor index="0" Format="1">
                <XCoordinate value="0"/>
                <YCoordinate value="0"/>
              </Mark2Anchor>
            </Mark2Record>
          </Mark2Array>
        </MarkMarkPos>
      </Lookup>
```

It should have the following instead:
```xml
          <Mark1Coverage Format="1">
            <Glyph value="uni05A7"/>
          </Mark1Coverage>
          <Mark2Coverage Format="1">
            <Glyph value="uni05B8"/>
          </Mark2Coverage>
```

**Comment by khaledhosny** [comment]
What @moyogo said. The mark attachment should be in logical order; the first mark as the base and the second as the mark.

**Comment by khaledhosny** [comment]
Here is the result after adjusting the marks:
![td_mkmkcheck](https://user-images.githubusercontent.com/93914/52414791-e9d24c80-2aed-11e9-9788-4b75946169a3.png)
[TD_mkmkCheck.zip](https://github.com/harfbuzz/harfbuzz/files/2841013/TD_mkmkCheck.zip)
