### ISSUE TITLE
Arabic shaper: pause after rclt/calt breaks Sakkal Kitab

### ISSUE THREAD

**Issue by emuller-amazon** [harfbuzz/harfbuzz#1573]
In the font Sakkal Kitab, the rclt=calt and liga/dlig/ss01 features have interleaved lookups:

rclt and calt : 17-18, 20-42, 65-67
liga: 15-16, 43-63, 69
dlig: 64
ss01: 68

The formation of ligatures depends on that interleaving. For example, for the sequence <0646, 062C, 0627>, a noon-jeem ligature is intended and is formed if the lookups are interleaved:

![interleaved](https://user-images.githubusercontent.com/16089970/52519460-6d845a00-2c10-11e9-8961-16b5db76a1d4.png)

but is not formed if the lookups are not interleaved:

![notinterleaved](https://user-images.githubusercontent.com/16089970/52519466-7d9c3980-2c10-11e9-986a-5c48d17f36bb.png)

The shaper currently has a pause after rclt/calt, which prevents the interleaving.

This pause was introduced by commit c1432bc, on July 14, 2017, in order to fix issue #505, 'Incorrect shaping with of <0644, 064E, 0670, 0653, ...> with "KFGQPC Uthmanic Script HAFS".'  What's ironic is that I created that issue! There are other problems with that font (starting with the hijacking of code points, handling of end of ayah), so it cannot really be used for anything but the (non strictly Unicode) text of the Qu'ran provided by KFGQPC. 

Unfortunately, I cannot provide a copy of Sakkal Kitab here.

**Comment by behdad** [comment]
@emuller-amazon can you share the font with me for testing?

We need to find a pause order that satisfies all fonts we know of, instead of breaking KFGQPC in favor of this one... Would have been easier if someone in MS could share what they actually do.

**Comment by emuller-amazon** [comment]
I am afraid I don't have a license that allows me to do that. Sorry.

**Comment by khaledhosny** [comment]
I can contact Mamoun Sakkal and ask for a copy for testing, if @behdad still wants to look into this.

**Comment by behdad** [comment]
@khaledhosny That would help indeed. I''m sure you can look into it yourself as well.

**Comment by behdad** [comment]
> @khaledhosny That would help indeed. I''m sure you can look into it yourself as well.

Nevermind. There's an email thread that Eric started with me and Mamoun / Aida around the same time. (it was my last week at Google.) But I never received the font file. I'll CC you there so we can debug and make a resolution.

**Comment by behdad** [comment]
> I never received a copy of this font.

I now have. The only thing I can think of is that what Uniscribe might be doing is that if the font has `rclt`, it applies it without a pause, otherwise it applies `calt` with a pause... I don't think it applies both but I might be wrong. This is just guesswork though. And it's hard to implement this in HarfBuzz with our current setup.

**Comment by behdad** [comment]
If I shape this font with Uniscribe from Windows 7, I get the broken rendering. This font has the same lookups in calt and rclt. That suggests that Windows 7 is only doing calt followed by a pause.  If I do calt, pause, rclt, font is still broken. That does agree with my conclusion that newer windows skips calt and does rclt without pause if the font has rclt.

**Comment by behdad** [comment]
@khaledhosny Any chance you can test this theory?

**Comment by khaledhosny** [comment]
> @khaledhosny Any chance you can test this theory?

Not sure what I can do to test this. FWIW CoreText also gives the broken rendering for this font.
