### ISSUE TITLE
No way to create a hb_font_t from a DirectWrite font?

### ISSUE THREAD

**Issue by litherum** [harfbuzz/harfbuzz#1575]
Looking at `hb-directwrite.h`, it doesn't look like there's a way to create an `hb_font_t` from a native DirectWrite font.

For comparison, `hb-coretext.h` has `hb_coretext_font_create()`.

**Comment by khaledhosny** [comment]
You can use [`hb_face_create_for_tables()`](https://harfbuzz.github.io/harfbuzz-hb-face.html#hb-face-create-for-tables) with your own `reference_table_func` that takes DirectWrite font as input, which is basically what `hb_coretext_face_create` does for Core Text fonts:
https://github.com/harfbuzz/harfbuzz/blob/8f4eb919bd0498e997852aa39656adc4c65b3f0e/src/hb-coretext.cc#L296-L300

`hb-directwrite.h` is not meant to be used in production.

**Comment by litherum** [comment]
Yep. It would be convenient if such a function existed inside Harfbuzz.

**Comment by ebraminio** [comment]
I feel I like to take this as something good to do if no one is more interested in it than me, @litherum do you have an implementation for this now or anything helpful? I can figure it out I guess but such things will be so helpful as I'm not regular everyday user of dwrite. Thanks!

**Comment by litherum** [comment]
I don't have any code, but I think a solution would hook up `[IDWriteFontFace::TryGetFontTable()](https://docs.microsoft.com/en-us/windows/desktop/api/dwrite/nf-dwrite-idwritefontface-trygetfonttable)` to `hb_face_create_for_tables()` just like @khaledhosny described above.

**Comment by ebraminio** [comment]
Have a look at #1593 :)

**Comment by litherum** [comment]
Wonderful! Thank you so much!
