### ISSUE TITLE
CMake doesn't know how to set WINAPI_FAMILY for UWP apps

### ISSUE THREAD

**Issue by litherum** [harfbuzz/harfbuzz#1576]
The Universal Windows Platform replaces all the file access APIs with new ones. It would be beneficial for these apps if either `hb_blob_create_from_file` was able to work with these new APIs or if it could be conditionally omitted from Harfbuzz.

**Comment by khaledhosny** [comment]
Are you unable to use `hb_blob_create_from_file` or can’t use HarfBuzz in this situation because it uses restricted APIs?

**Comment by ebraminio** [comment]
While ago @Sibras added UWP support to it https://github.com/harfbuzz/harfbuzz/commit/24dd6c1a9d8d571c30dce4d39c1975b1d1cedc2a#diff-100509edaeca042e7568b5922093fb5d but honestly I don't know even what UWP is, is that related to Windows 8 metro apps (which renamed later or something?)? Any information will be nice I guess

**Comment by litherum** [comment]
Can’t use HarfBuzz in this situation because it uses restricted APIs.

**Comment by litherum** [comment]
Aha, yes, you are totally right. It looks like this is a CMake problem; CMake doesn't know whether or not to set the `WINAPI_FAMILY` preprocessor define.

Creating a new UWP app from the Visual Studio template sets `WINAPI_FAMILY=WINAPI_FAMILY_APP`. Perhaps `CMakeLists.txt` should have an option to set it that way too.

**Comment by khaledhosny** [comment]
CMake support is being phased out.
