### ISSUE TITLE
How to know how many characters have merged into one glyph?

### ISSUE THREAD

**Issue by RachamimYaakobov** [harfbuzz/harfbuzz#1577]
I am doing shape with `hb_shape` sending "fi" string, i get back one glyph after the `liga` substitution.
I have the information about the new glyph cluster, but i don't know how many characters have merged into one new glyph.
**My question is:**
When glyph is substituted and/or ligated does the number of characters replaced being stored 
somewhere?
How can I know how many characters belong to each glyph?

**Comment by khaledhosny** [comment]
Check the [clusters chapter](https://harfbuzz.github.io/clusters.html) in the manual.

**Comment by YKubi** [comment]
I have followed the link and could not find a direct answer.

> ...does the number of characters replaced being stored somewhere? 

So the answer to that is: NO!

> How can I know how many characters belong to each glyph?

It looks that the answer to that is: you must use `cluster_level` 2, and build quite a complex code for that, and to lose the merge of the clusters.

On the article it said:
>HarfBuzz records cluster information independently from how shaping operations affect the individual glyphs returned in an output buffer. Consequently, a client program using HarfBuzz can utilize the cluster information to implement features such as:
Correctly positioning the cursor within a shaped text run, even when characters have formed ligatures, composed or decomposed, reordered, or undergone other shaping operations. etc.

And it seems to be very complicated to achieve!
Dear @khaledhosny please try to point more directly on this question. Thanks!

**Comment by khaledhosny** [comment]
> I have followed the link and could not find a direct answer.

That link is as direct as answers to this question can get.

> > ...does the number of characters replaced being stored somewhere?
> 
> So the answer to that is: NO!
> 
> > How can I know how many characters belong to each glyph?
> 
> It looks that the answer to that is: you must use `cluster_level` 2, and build quite a complex code for that, and to lose the merge of the clusters.

All cluster levels can answer the question, but different level can merge more or less glyphs into the same cluster.

> On the article it said:
> 
> > HarfBuzz records cluster information independently from how shaping operations affect the individual glyphs returned in an output buffer. Consequently, a client program using HarfBuzz can utilize the cluster information to implement features such as:
> > Correctly positioning the cursor within a shaped text run, even when characters have formed ligatures, composed or decomposed, reordered, or undergone other shaping operations. etc.
> 
> And it seems to be very complicated to achieve!

If it is, then because the problem at hand is inherently complex. That being said, I don’t think it is that complex, it probably some ~10 lines of code or less.
