### ISSUE TITLE
Gurumukhi Shaping Issue

### ISSUE THREAD

**Issue by Amritasingh0512** [harfbuzz/harfbuzz#1587]
Text: ਬ੍ਹ
Vendor comments: This is frequently used combination, so it is “must fix” issue

**Comment by Amritasingh0512** [comment]
![raavi_hbz](https://user-images.githubusercontent.com/38288804/53011490-7e319d00-3466-11e9-985c-268b533ba140.png)
![raavi_word](https://user-images.githubusercontent.com/38288804/53011491-7e319d00-3466-11e9-90c2-6be5eea86eac.png)
[Raavi.zip](https://github.com/harfbuzz/harfbuzz/files/2879716/Raavi.zip)

**Comment by behdad** [comment]
What font?  What does Windows do?

**Comment by Amritasingh0512** [comment]
Hi Behdad!

The shaping given in blue is Harfbuzz shaping. However, word shapes the text as in black.
I have attached the font in Raavi.zip

**Comment by behdad** [comment]
Thanks.  Needs to be debugged...

Do you have hb-shape on Windows?

**Comment by behdad** [comment]
Need help here.  Anyone willing to debug?

**Comment by jfkthame** [comment]
This occurs with an older version of the Raavi font (it looks like it has since been updated), because the 'vatu' feature that was supposed to form the below-base form of HA has a ligature rule for <HA, VIRAMA> rather than <VIRAMA, HA>, and we're not recognizing this reversed sequence.

**Comment by behdad** [comment]
Thanks.  Indeed we were finding second consonant as base and that's causing this.  Fix is to consider 'Halant,Consonant' that matches `vatu` feature as below-base, so we keep looking for base.
