### ISSUE TITLE
Remove Forcing Diagnostic Colours from CMakeLists.txt

### ISSUE THREAD

**Issue by jrlanglois** [harfbuzz/harfbuzz#1596]
Harfbuzz makes an invalid assumption that the Clang and GCC versions of the toolchains provided support particular compiler flags. Unfortunately, for legacy systems that don't have this luxury compiler option, this kills the entire process and makes for heavily convoluted workarounds - especially when used in conjunction with Cmake/Hunter, and automating this building process across many systems.

The culprit code:
```cmake
if (UNIX AND CMAKE_GENERATOR STREQUAL "Ninja")
  if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fcolor-diagnostics")
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fcolor-diagnostics")
  endif ()
  if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fdiagnostics-color")
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fdiagnostics-color")
  endif ()
endif ()
```

Found here: https://github.com/harfbuzz/harfbuzz/blob/master/CMakeLists.txt#L845-L854

Please remove this section of code, or make use of [`CMAKE_<LANG>_COMPILER_VERSION`](https://cmake.org/cmake/help/v3.14/variable/CMAKE_LANG_COMPILER_VERSION.html?highlight=cmake_cxx_compiler_version) and check if the version of the compiler supports this feature.

**Comment by khaledhosny** [comment]
My vote is to just remove it, it is either on by default already or the users who really want it can just set `CFLAGS` env var accordingly.

**Comment by jrlanglois** [comment]
That's my thought too - users should have the full control over this...

**Comment by jrlanglois** [comment]
PR removing the contents: https://github.com/harfbuzz/harfbuzz/pull/1597

**Comment by ebraminio** [comment]
Originally it was done on #674 by @waywardmonkeys We don't care much now about out CMake as the plan for replacing it with meson #490 but changes still accepted. Thanks
