### ISSUE TITLE
MUTF blacklist

### ISSUE THREAD

**Issue by MayuraVerma** [harfbuzz/harfbuzz#1604]
in the version 2.2.0, it is listed.

o Blacklist 'GSUB' table of fonts from 'MUTF' foundry that also have 'morx'.

but murasu fonts are system fonts for all indic fonts in apple systems

Does it mean those fonts will not work in applications that uses harfbuzz?

**Comment by khaledhosny** [comment]
These fonts has unusable GSUB tables, what HarfBuzz is doing is ignoring these tables to allow using the working morx table. See #1348 and #1410.
