### ISSUE TITLE
Fixing or getting rid of Travis macOS bot

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1609]
Travis's macOS bot fails and apparently because it can't find glib-2.0 even the fact it is installed. I say let's get rid of the bot now that we have a number of CircleCI based macOS bots. The advantage to CircleCI is we can log into it every time we face an issue but Travis doesn't provide feature AFAIK. It will also simplify our Travis's Linux CI.

**Comment by khaledhosny** [comment]
+1 for that, but we need to make sure we have a CircleCI build with the same options as the Travis macOS build.

**Comment by behdad** [comment]
Fixed now?
