### ISSUE TITLE
check-symbols.sh: line 19: syntax error at line 29: `(' unexpected

### ISSUE THREAD

**Issue by Mno-hime** [harfbuzz/harfbuzz#1612]
Running test suite from HarfBuzz 2.3.1 on OpenIndiana 2018.10 (illumos kernel) with bash 4.4.23 fails in the `check-symbols.sh` test:

```
/export/home/newman/ws/oi-userland/components/library/harfbuzz/harfbuzz-2.3.1/src/check-symbols.sh: line 19: syntax error at line 29: `(' unexpected
FAIL check-symbols.sh (exit status: 3)
```

It used to pass for 1.7.4.

**Comment by khaledhosny** [comment]
Probably your `grep` does not support the syntax used on this line, introduced in e0939d811f1fdeda9c5763e7e53887b3d3cb21eb.

**Comment by Mno-hime** [comment]
illumos tools are for sure sometimes source of confusion, but in this case I set `PATH` in the build environment to pick GNU tools first, also tried to use GNU tool explicitely `grep` -> `ggrep` and so on. Also it seems to me that the error is produced by bash not `grep`.

**Comment by pyhalov** [comment]
The issue is not in grep. It seems, ksh (invoked as /bin/sh) doesn't like 
EXXPORTED_SYMBOLS="`..." "`" syntax (matches " inside ` to outside "). Don't know what is correct behavior here.

**Comment by pyhalov** [comment]
Replacing EXPORTED_SYMBOLS="``" with EXPORTED_SYMBOLS=$() works, and seems to be POSIX-conforming http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html.

**Comment by khaledhosny** [comment]
Thanks, please make a pull request to this effect.

**Comment by behdad** [comment]
Also note that we can just remove the outside set of double-quotes.

**Comment by behdad** [comment]
Anyone want to send a PR for this?
