### ISSUE TITLE
Dose Harfbuzz supports "curs" feature for Latin?

### ISSUE THREAD

**Issue by AlirezaAlipour** [harfbuzz/harfbuzz#1623]
I'm a type designer and now I'm working on ongoing cursive Latin type. I have used "curs" feature in order to attaching glyphs to each other, everything work, but "curs" feature don't work in Inkscape and as Inkscape is base on Harfbuzz, I decided to open an issue here.

**Comment by khaledhosny** [comment]
HarfBuzz supports `curs` feature. If you are using Inkscape on Windows or macOS then it does not using HarfBuzz (Inkscape does not use HarfBuzz directly, it uses Pango which currently does not use HarfBuzz on Windows or macOS).

**Comment by AlirezaAlipour** [comment]
> HarfBuzz supports `curs` feature. If you are using Inkscape on Windows or macOS then it does not using HarfBuzz (Inkscape does not use HarfBuzz directly, it uses Pango which currently does not use HarfBuzz on Windows or macOS).

My OS is Ubuntu 18.10, but `curs` feature doesn't work in Inkscape.

**Comment by khaledhosny** [comment]
Does it work on any other application? It might be an Inkscape bug.

**Comment by AlirezaAlipour** [comment]
> Does it work on any other application? It might be an Inkscape bug.

I tested it by CSS font-face and LibreOffice Writer, it work.

**Comment by khaledhosny** [comment]
So an Inkscape bug then, please report to Inkscape (LibreOffice, as well as Firefox and Chrome use HarfBuzz as well).
