### ISSUE TITLE
How to determine which ligature can insert carets or not?

### ISSUE THREAD

**Issue by anydream** [harfbuzz/harfbuzz#1624]
I am working on a custom edit box with Harfbuzz shaping, and I want insert carets into something like ligature "ffi" but not "ऱ्क़्क़्क़ि", how can I do?
Is distinguish between ligatures and reordering the key?

**Comment by anydream** [comment]
Most of browsers/edit boxes can separate between ligature "ffi" with cursor, but "ऱ्क़्क़्क़ि" can't, how did they do?

**Comment by khaledhosny** [comment]
Where to allow caret insertion in the text stream is determined by [Unicode grapheme cluster boundaries](http://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries).

**Comment by anydream** [comment]
Does it mean that I need to handle it myself, not just relying on the harfbuzz cluster values?
That's really helpful, Thanks!

**Comment by khaledhosny** [comment]
Yes, see the manual chapter on [clusters](https://harfbuzz.github.io/clusters.html)
