### ISSUE TITLE
VS2019 build error with alignof macro

### ISSUE THREAD

**Issue by egorpugin** [harfbuzz/harfbuzz#1634]
hb 2.3.1
VS2019 (16.0.0 RC.4)

https://github.com/harfbuzz/harfbuzz/blob/55d1d7c8bcd8d97c4e618e5dd21f13df50b10ce8/src/hb.hh#L251

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\xkeycheck.h(27): warning C4005: 'alignof': macro redefinition
1>D:\dev\swst\pkg\af\be\57db\src\sdir\src\hb.hh(251): note: see previous definition of 'alignof'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\xkeycheck.h(29): fatal error C1189: #error:  The C++ Standard Library forbids macroizing the keyword "alignof". Enable warning C4005 to find the forbidden define.
```

**Comment by khaledhosny** [comment]
I guess that block can be dropped as `alignof` is not used anywhere since fb10c021c8a32f8dc054f008caf86af82667e109.

**Comment by egorpugin** [comment]
Same issue with https://github.com/harfbuzz/harfbuzz/blob/55d1d7c8bcd8d97c4e618e5dd21f13df50b10ce8/src/hb.hh#L224

**Comment by khaledhosny** [comment]
OK, we need a better fix then. I don’t know what exactly though, may be enclose them in a C++ version check?

**Comment by khaledhosny** [comment]
Hmm, they are already guarded with `#if __cplusplus < 201103L`.

**Comment by egorpugin** [comment]
VS has `__cplusplus 199703` or something like that.

**Comment by khaledhosny** [comment]
Hmm, https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/ says this was fixed but a new compiler switch is needed to enable the correct value.

**Comment by egorpugin** [comment]
Yes, but your header is public. You cannot push it to all users probably.

**Comment by khaledhosny** [comment]
That is an internal header, though, not a public one, so one would only need the switch when building HarfBuzz itself. But I guess an extra check for `_MSVC_LANG` won’t hurt.

**Comment by egorpugin** [comment]
Maybe simple `#ifdef _MSC_VER` or check for specific msvc version will be enough around that block of defines.

**Comment by khaledhosny** [comment]
Yes, whatever works. Can you make a pull request?

**Comment by egorpugin** [comment]
https://github.com/harfbuzz/harfbuzz/pull/1635
