### ISSUE TITLE
2.4 tarball has wrong version info

### ISSUE THREAD

**Issue by waywardmonkeys** [harfbuzz/harfbuzz#1643]
This is the same sort of issue as #1271 ... the hb-version.h has a version 1.7.6, not 2.4.0

**Comment by behdad** [comment]
Phew.  @khaledhosny you probably had a stale hb-version.h in your build or src dir?

Let's roll a new release.  Khaled, do you want to do it completely yourself.  I can do the fdo upload.

If we upload all past releases to github, we can remove fdo dir.  Or people find it easier to (automatically) download from fdo directory than github?

**Comment by behdad** [comment]
So yeah, we are going to branch 2.4 and make fixup releases from.

**Comment by behdad** [comment]
Humm.  Since the source tree is correct and this is just a tarball issue, let's just recreate the tarball and upload.  @khaledhosny send me a new one.  Thanks.

**Comment by behdad** [comment]
Either way is fine.

**Comment by khaledhosny** [comment]
I had the correct `hb-version.h` in the source tree, but the build tree had a stale one indeed (which seems to have been there for so long!). I can check the release stuff tomorrow, it is pretty late here now.

**Comment by ebraminio** [comment]
RIP for 2.4 :/ We may can assign a bot and use its tarball artifact

**Comment by behdad** [comment]
Okay don't worry.  I'll take care of it here.

**Comment by behdad** [comment]
Also https://github.com/harfbuzz/harfbuzz/issues/1641 for context.

**Comment by behdad** [comment]
Okay, uploaded new tarball...
