### ISSUE TITLE
Broken .sha256 file for 2.4.0

### ISSUE THREAD

**Issue by atsampson** [harfbuzz/harfbuzz#1644]
The tarball and signature for 2.4.0 on freedesktop.org now appear fine, but the `.sha256` file has a stray CR character in it (i.e. it has a CRLF rather than LF newline), which means coreutils' sha256sum on GNU/Linux can't verify it:

```
$ sha256sum -c harfbuzz-2.4.0.tar.bz2.sha256
sha256sum: 'harfbuzz-2.4.0.tar.bz2'$'\r': No such file or directory
: FAILED open or read2
sha256sum: WARNING: 1 listed file could not be read
```

I'm guessing this is another MacOS/Windows-induced problem...

**Comment by behdad** [comment]
At this point I guess I'll just let this go.  I can remove it but then have to resign. Future releases will be made back from a trusted Linux machine...

**Comment by behdad** [comment]
Okay.  Fixed.  Please confirm.

**Comment by atsampson** [comment]
Yep, that works properly now - cheers!
