### ISSUE TITLE
hb_iter design / improvements

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1648]
Should have opened this before.  Anyway.  The design of hb_iter (the 'iter' branch that I merged) was derived from ideas involved in "ranges" as in D or C++20.  Indeed, https://github.com/ericniebler/range-v3 was the inspiration for the "pipeline" syntax.  Other resources:

C++ Library Design:
https://www.youtube.com/watch?v=zgOF4NrQllo
C++ range design considerations:
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4128.html
https://www.boost.org/doc/libs/1_69_0/libs/range/doc/html/index.html
https://www.youtube.com/watch?v=mFUXNMfaciE&t=5057s
For algorithm inspiration:
https://dlang.org/phobos/std_range.html
https://www.boost.org/doc/libs/1_69_0/libs/range/doc/html/index.html
https://en.cppreference.com/w/cpp/algorithm
http://ericniebler.com/2018/12/05/standard-ranges/

Below I share my ideas list for things to improve.  It's tempting to keep adding algorithms.  I've been trying to stick to adding only those that I plan to use for something.  Let's use that as a guide.

**Comment by behdad** [comment]
Improvement ideas (mixed with some non-iter ideas):

1. Currently, in `hb_filter` / `hb_map` etc where they take invokables, make them accept a pointer to object as well, and call `*p()` instead of `p()`.  This way we can pass eg `c->glyphs` to them instead of `*c->glyphs` where `c->glyphs` is a `hb_set_t*`.  Then update all call-sites. 

Origincally I was thinking of implementing this by implementing a `hb_invoke` that does this and some of what std::invoke() does.   But for this alone, we can just use `hb_deref_pointer`.  I prefer this one because I think it works better with the next idea:

2. Currently hb_filter and hb_map both invoke (ie. call operator()) on their object.  This means that something like a hb_map_t (the hashmap) cannot be used with both.  I suggest adding hb_has() and hb_get().  hb_has() will call obj.has() if that exists, otherwise calls obj().  hb_get() tries obj.get() first, then obj().  Maybe obj[] as well first or last, donno.  Anyway, the idea being that hb_filter will call hb_has, and hb_map will call hb_get, such that the same object can automatically work with both.

3. Make the pipeables "x | y() | ..." be partial-instantiations of otherwise two-argument functions?  Ie. hb_filter(Pred) is really just partial(hb_filter, Pred) where hb_filter takes (Pred, Iter) ala Python.

4. Related, implement hb_bind().  Possibly also add some sugar syntax for it?  Eg. "f << a" or "f <= b" will bind a to the first argument of f, and "f >> b" or "f >= b" to the second?  Probably a horrible idea :).  Then eg. one can call `hb_filter (hb_has << m))` (assuming hb_filter doesn't call hb_has automatically).

5. iter_t::operator- () { return riter(); } for reversing an iterator.

6. Add stride as a template parameter to hb_array_t, and use to implement reverse-iterator (riter)?

7. Implement hb_set_t::riter()

8. vector: Default-construct new entries now that we have assign / move semantics?  Currently we use the Null() object.  Maybe use Null() if object has min_size, construct otherwise?  Also, what about destruction?

9. MIN / MAX / .. -> function objects! hb_min / hb_max: both taking two-args version, and the pipeable one?

10. ArrayOf::serialize_iter_t in which more() returns !serializer->in_error()?

11.
hb_map_t::key_iter_t iter()
hb_map_t::key_iter_t keys()
hb_map_t::value_iter_t values()
hb_map_t::item_iter_t items()
ClassDef::iter_t iter() -> return pairs
hb_set_t(iterable) constructor
hb_map_t(iterable<pair>) constructor

12.
hb_lsearch()
hb_bsearch()
hb_qsort()

13. iter_tools: iter_intersect? iter_subset?

**Comment by ebraminio** [comment]
Not have seen your list yet, these can be used as inspiration also,

C#/Linq: https://github.com/dotnet/corefx/tree/master/src/System.Linq/src/System/Linq 
Kotlin: https://github.com/JetBrains/kotlin/blob/4a3e4f099da311f51d666e561d5420390f0c13e0/libraries/stdlib/common/src/generated/_Sequences.kt
Scala: https://github.com/scala/scala/blob/041fc2360f3527249e7376faefb0be6a7271b4ab/src/library/scala/collection/immutable/Stream.scala#L28
Ruby: https://github.com/ruby/ruby/tree/trunk/spec/ruby/core/enumerable (tests)
Elixir: https://github.com/elixir-lang/elixir/blob/a304aac97b222d91d1762cf2d6bec26f08a0a720/lib/elixir/lib/enum.ex
Clojure: https://github.com/clojure/clojure/blob/master/src/clj/clojure/core/reducers.clj
PHP: https://github.com/php/php-src/blob/master/ext/standard/array.c
Spark: https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/DatasetAggregatorSuite.scala
Pandas: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.aggregate.html
Numpy: https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html
Swift: https://github.com/apple/swift/blob/95a15d12bdc01ec392d01fdd6126f68cdd16aa42/stdlib/public/core/SequenceAlgorithms.swift#L579
TODO: OCaml/F#, Haskell, Rust, clisp/scheme

sample code demonstrates some of them: https://gist.github.com/ebraminio/5292017

**Comment by behdad** [comment]
Lets add `.begin()` and `.end()` to `hb_iter_t` and see if makes it possible to use them in range for.

**Comment by behdad** [comment]
Also implementing free `begin()` / `end()` functions on iterables.
