### ISSUE TITLE
Regarding glyph_index to Unicode Mapping

### ISSUE THREAD

**Issue by lifeisshubh** [harfbuzz/harfbuzz#1650]
Is there some way in harfbuzz through which I can identify glyph to Unicode mapping.
Thanks.

**Comment by jfkthame** [comment]
In general, no. Glyphs may not necessarily correspond to Unicode codepoints in a straightforward way.

**Comment by lifeisshubh** [comment]
I am looking for some way to create a mapping from a glyph to `[unicode_char_1, unicode_char_2 ...]`. Can anyone suggest some way that I should look for doing so?

**Comment by khaledhosny** [comment]
There is no reliable way to do this as @jfkthame said already. What do you need this mapping for?

**Comment by lifeisshubh** [comment]
I want to use glyphs as labeling for hindi ocr, Unicode is a horrible way to use as the label since due to the abundance of multiple mapping to the single actual character. 
Thanks.

**Comment by ebraminio** [comment]
You can try the reverse way, print the output of character and combinations you are going to detect, store a map of what turned to which sequence of glyphs and use the map, not best but most reliable I guess.

**Comment by khaledhosny** [comment]
Not sure I get what you want to do, but does not seem like something HarfBuzz can help with.

**Comment by lifeisshubh** [comment]
Thanks. @khaledhosny I was just want to know whether doing reverse is possible or not using harfbuzz. Thanks, @ebraminio I thought of this way but there is some dependency factor in the existence of glyph, often glyph is decided by the surrounding glyphs. Now, I think I will proceed in reverse mapping direction only.
Thanks, everyone.
