### ISSUE TITLE
Way to trim the fat down

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1652]
Back in the early days, libharfbuzz was about 200kb.  About half was the ot-layout stuff, and rest was the objects, shapers, etc.  These days, we're closer to (gasp) 800k!  And that's not even including the subsetter!

Not all of that is required for just shaping text.  Of course, some comes from more advanced, complete, and correct shaping ("use", "myanmar", etc)  But there's other stuff that is simply not needed for correct shaping, for most clients.

There are various usecases where trimming that down becomes necessary.  In particular: shipping in a downloadable app (Chrome, ...), or as WASM (https://github.com/harfbuzz/harfbuzz/issues/1633).  It's about time to add knobs to control that.

In particular, what's added the size recently:

- UCDN: 120kb
- AAT: 90kb
- CFF: 90kb
- hb-ot-font: 60kb
- hb-ot-layout: has grown to 190kb.  Not all new functions are needed for shaping.
- hb-buffer-serialize: 13kb
- hb-ot-math: 13kb
- hb-ot-name: 10kb
- hb-ot-map: 6kb
- hb-ot-shape-complex-arabic-fallback: ~25kb?
- hb-ot-shape-complex-vowel-constraints: 11kb

There's a lot that can be trimmed down...  Ideally, one should use a linker setup that trims down unused public symbols.  But that's not feasible in many cases as by that time it's too late to remove many symbols pulled in by those public symbols.  I'm not sure what the best way forward is.  In followup comments I make various ideas that come to my mind.

cc @ebraminio @jfkthame @drott

**Comment by behdad** [comment]
cc @plabatut

**Comment by ebraminio** [comment]
To be honest I'm not that excited about this and specifically if going to provide this using compiler directive and flags (and I know we have all the same concern) and there shouldn't be any assumption about use of what should be in wasm version of harfbuzz, hb-ot-color and hb-ot-name can easily be useful for online uses, let alone node.js server side JavaScript uses. I guess we should go as much to see what blocks linker to perform better and resolve them and optimize ucdn as you described before.

**Comment by behdad** [comment]
If we want to be able to grow library freely, we need to have a way to let people trim it down.  I sympathize with them.  I know of current users of the library that are trimming it by removing specific shapers.  That's BAD for our goals.  By giving them the tools to do what they need they can avoid that.

I honestly don't blame an app developer wanting to trim down HB from 800kb to ~200kb.

For example, CFF is only used in hb-ot-font's get_extents.  get_extents is only used for fallback shaping of fonts without GPOS.  Or if you use HB with FreeType or other libraries, hb-ot-font is not needed.  These are valid requests.  I'm not suggesting we disable anything automatically, but give the tools to clients to build smaller libraries without painful hacks on their side.

And linker goes just so far.  CFF cannot be optimized out using linker alone, since it *is* used, just not in a relevant way to correct fonts.

**Comment by ebraminio** [comment]
> get_extents is only used for fallback shaping of fonts without GPOS

I only was aware of the public API part not this one. Well you know, we should have a matrix of features then, or, adding only one flag, something like "minimal", removing those can't be eliminated by linker, like AAT and CFF?

**Comment by behdad** [comment]
I was thinking having a `hb-mini` mode indeed.  I'm still thinking how to proceed.  I'll post my design thoughts here.

**Comment by behdad** [comment]
I think `HB_NO_CFF` and `HB_NO_AAT` are definitely good idea to add.

**Comment by behdad** [comment]
Also `HB_NO_OT`!  An app using HarfBuzz can be built to just use hb-coretext on iOS and save a lot.

**Comment by behdad** [comment]
Okay so let's not worry about pruning public symbols, which is something the linker can do.  Though would be nice to document how clients can do that to our WASM or JS output.  Basically, static linking to their code.  I'll focus in this issue on configurations that cannot be figured out automatically.  By definition such configs limit functionality, but in ways that might be acceptable.

**Comment by drott** [comment]
See also here in a discussion about Android binary size going up when SkPDF is starting to use subsetting functionality in HarfBuzz:
https://chromium-review.googlesource.com/c/chromium/src/+/1531173/2#message-93ead7f9cbf5012581c82f339a647b558e90e6d0

Andrew's request was also to look into extracting identical shared functionality in templated code into helper classes instead of bloating the binary with redundant template instantiations.

**Comment by ebraminio** [comment]
Is the style used here compiler warnings safe? I guess something like `if ((true)) return;` is more safe to use.

**Comment by behdad** [comment]
> Is the style used here compiler warnings safe? I guess something like `if ((true)) return;` is more safe to use.

I think we have unreachable-code-warning/error etc set up, and seems to work.  I think clang understands that there's conditional macros involved.

**Comment by behdad** [comment]
We can address that if it comes up.

**Comment by behdad** [comment]
@dscorbett is it possible you can optimize `static const LangTag ot_languages[]` please?  Currently LangTag is: `struct { char[4]; hb_tag_t[3]; }`.  Since most entries only have one tag, can we change that to `struct { char[4]; hb_tag_t; }` and for languages that have more than one tag, have multiple (consecutive) entries in the table?  That would save ~8kb.  Thanks.

**Comment by behdad** [comment]
@dscorbett Also, maybe comment out entries from the table where the two tags are equivalent?

**Comment by dscorbett** [comment]
Sure. It’ll complicate the binary search, unfortunately.

**Comment by behdad** [comment]
> Sure. It’ll complicate the binary search, unfortunately.

Leave the bsearch as is.  When found, walk back till first entry, then walk forward till last entry?  I think the previous code did something like that.

Anyway.  Thanks again.

**Comment by behdad** [comment]
FWIW, optimizations that don't change functionality we should automatically enable if `__OPTIMIZE_SIZE__` is defined.  Clang defines that.  I assume gcc as well.

**Comment by brawer** [comment]
Yes, `__OPTIMIZE_SIZE__` is defined by gcc: http://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html
