### ISSUE TITLE
hb_buffer_get_glyph_infos only returns spaces on Linux if font functions aren't set manually

### ISSUE THREAD

**Issue by fschutt** [harfbuzz/harfbuzz#1653]
Calling `hb_buffer_get_glyph_infos` on any font returns only spaces (`0x20`) as the codepoint of the glyph instead of the actual glyph indices. This issue happens only on Linux and only if the font functions aren't initialized first via `hb_ot_font_set_funcs` - see https://github.com/maps4print/azul/issues/125#issuecomment-479172471

I wanted to report this issue in case it's still a problem - if this isn't a problem with harfbuzz but with [the code itself](https://github.com/maps4print/azul/blob/87f3fb2dfd5c3976a284ebb06c8ced6217e0950b/azul/src/text_shaping.rs#L79), then it would be great to know what the proper solution is, but as far as I can tell this is a problem of harfbuzz. While [the fix / workaround](https://github.com/maps4print/azul/commit/87f3fb2dfd5c3976a284ebb06c8ced6217e0950b) was fairly simple, it's not something that is documented anywhere. I am not sure if this bug has already been fixed (my version of harfbuzz is a bit out of date, maybe this has been fixed already).

- harfbuzz version: https://github.com/harfbuzz/harfbuzz/commit/6482fda519ca7d173e3bcb3717aa30e237f04b25 ([source](https://github.com/maps4print/azul-dependencies/tree/ed2ad88d47eda260f7e3b3d387c412801ae03c1b/harfbuzz-sys-0.3.0/harfbuzz))
- OS: Ubuntu 17.04

**Comment by behdad** [comment]
hb-ot-font  funcs are installed by default, as of HarfBuzz 2.0.0...  Thanks for the report. :)
