### ISSUE TITLE
Hindi matra misplaced

### ISSUE THREAD

**Issue by PranayShah** [harfbuzz/harfbuzz#1654]
Similar to #1020 , burning Hindi subtitles with Ffmpeg and Harfbuzz `2.4.0` causes the video to show 

![like this](https://res.cloudinary.com/qblm/image/upload/v1554292972/Annotation_2019-04-03_171815.jpg)

when it should have been `कहानियों के बारे में`

`ffmpeg`
![Annotation 2019-04-03 174606](https://user-images.githubusercontent.com/2013275/55478181-a81ad980-5638-11e9-8c3d-b8e36d729c8f.jpg)

`ldd ffmpeg`
![Annotation 2019-04-03 174917](https://user-images.githubusercontent.com/2013275/55478261-dbf5ff00-5638-11e9-9cad-df2cf8c7290e.jpg)

`ffmpeg -i ~/in.mp4 -y -vf subtitles=~/hindi.srt:force_style='Fontname=Noto Sans Devanagari' -acodec copy ~/out.mp4`
![Annotation 2019-04-03 044114 (2)](https://user-images.githubusercontent.com/2013275/55478337-18c1f600-5639-11e9-8463-8fe5d75b17f7.jpg)

I compiled Harfbuzz from its bz2 tarball and installed `libass` after that with the flag `--enable-harfbuzz` following [this issue](https://trac.ffmpeg.org/ticket/3165) on ffmpeg forums and [some instructions here](https://trac.ffmpeg.org/attachment/ticket/3165/installNotes)

Will be so grateful for any help.
Thanks a lot.

**Comment by astiob** [comment]
```22:55:44 < CoffeeFlux> he should test with hb-shape to see that the output is correct
22:55:54 < CoffeeFlux> and hb-view or whatever```

**Comment by khaledhosny** [comment]
Here is how the string above renderes with `hb-view` and Noto Sans Devanagari:
```
hb-view NotoSansDevanagari-Regular.ttf "कहानियों के बारे में"
```

![a](https://user-images.githubusercontent.com/93914/55737602-c3fdf100-5a25-11e9-94ce-1d20089f1cc3.png)

Please reopen if you can reproduce with `hb-view`.

**Comment by khaledhosny** [comment]
I get similar output like yours with the fallback shaper, which suggests either that HarfBuzz is not actually used (more likely) or something is incorrectly using the fallback shaper.

The output of `ldd ffmpeg` wouldn’t tell much, as HarfBuzz can be pulled as dependency of another library (e.g. FreeType) but this does not mean ffmpeg is using it for shaping.

**Comment by vitika1** [comment]
Hey, did anyone find a solution to this?

**Comment by astiob** [comment]
> Hey, did anyone find a solution to this?

This is an FFmpeg issue: it disables HarfBuzz for `-vf subtitles`. If `-vf ass` works for your use case, use that instead. I don’t know whether this has been reported to FFmpeg yet; you may want to do that.

**Comment by vitika1** [comment]
For making it work in FFmpeg, convert your srt to 'Kruti Dev' format and use a Kruti Dev font.

**Comment by kdcyberdude** [comment]
@PranayShah Did you find any solution for this?
