### ISSUE TITLE
harfbuzz-2.4.0 on Microsoft Visual Studio 2017

### ISSUE THREAD

**Issue by a-kakuto** [harfbuzz/harfbuzz#1658]
question: I cannot build 2.4.0 by MS Visual Studio 2017

I cannot build 2.4.0 by Microsoft Visual Studio 2017, with
error messages,
hb-iter.hh(205): error C2228: left side of '.iter' should be
class, struct, or union.
hb-iter.hh(205): note: type is 'T'.
If I remove '.iter ()' from 'hb_declval (T).iter ()' I can build
2.4.0 by Visual Studio 2017 without any problem.
Is the resulting library useless?

**Comment by khaledhosny** [comment]
It seems like the tarball for 2.4.0 was broken (see #1641, I sent Behdad (yet another) new tarball that should fix this (I hope).

**Comment by a-kakuto** [comment]
The size of obtained harfbuzz-2.4.0.tar.bz2 is 17922003,
and I think it is OK.

**Comment by khaledhosny** [comment]
The tarball was not created from a clean 2.4.0 tree and contained stuff from master (which I think includes the code breaking the build with MSVC). The new, I think correct, tarball is 17919355 bytes.

**Comment by a-kakuto** [comment]
Many thanks. I obtained sources from 2.4.0 tree, and
I could build on Visual Studio 2015 update3, and
on Visual Studio 2017 successfully,
by changing '*/*nullptr*/' to '* /* nullptr */'
in hb-ot-cff-common.hh to avoid warnings.
