### ISSUE TITLE
CMAKE_BUILD_TYPE=Release fails with unused variable in hb-coretext.cc

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/harfbuzz#1659]
when building harfbuzz 2.4.0 with cmake in "Release" mode on macOS, the build fails because of an unused variable in hb-coretext.cc

```
$ ninja
[50/73] Building CXX object CMakeFiles/harfbuzz.dir/src/hb-coretext.cc.o
FAILED: CMakeFiles/harfbuzz.dir/src/hb-coretext.cc.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DHAVE_ATEXIT -DHAVE_CORETEXT -DHAVE_FALLBACK -DHAVE_GETPAGESIZE -DHAVE_INTEL_ATOMIC_PRIMITIVES -DHAVE_ISATTY -DHAVE_MMAP -DHAVE_MPROTECT -DHAVE_NEWLOCALE -DHAVE_ROUND -DHAVE_STDBOOL_H -DHAVE_STRTOD_L -DHAVE_SYSCONF -DHAVE_SYS_MMAN_H -DHAVE_UCDN -DHAVE_UNISTD_H -DHAVE_XLOCALE_H -I../src -Isrc -I../src/hb-ucdn -Werror -Wunused-variable -fno-rtti -fno-exceptions -fno-threadsafe-statics -std=c++11 -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -MD -MT CMakeFiles/harfbuzz.dir/src/hb-coretext.cc.o -MF CMakeFiles/harfbuzz.dir/src/hb-coretext.cc.o.d -o CMakeFiles/harfbuzz.dir/src/hb-coretext.cc.o -c ../src/hb-coretext.cc
../src/hb-coretext.cc:1072:12: error: unused variable 'backward' [-Werror,-Wunused-variable]
      bool backward = HB_DIRECTION_IS_BACKWARD (buffer->props.direction);
           ^
1 error generated.
[63/73] Building CXX object CMakeFiles/harfbuzz.dir/src/hb-ot-layout.cc.o
ninja: build stopped: subcommand failed.
```

at this line here:
https://github.com/harfbuzz/harfbuzz/blob/4c19aa26204d0dc2f08b6e4a824e9088301f68d8/src/hb-coretext.cc#L1072

I use the cmake build system to compile the harfbuzz library embedded in the [uharfbuzz](https://github.com/trufont/uharfbuzz) python bindings, because cmake has better support for building cross-plartform python extensions than the autotools.

**Comment by anthrotype** [comment]
steps to reproduce:

```
$ mkdir cmake-build
$ cd cmake-build
$ cmake -G Ninja -DCMAKE_BUILD_TYPE:STRING=Release ..
$ ninja
```

**Comment by anthrotype** [comment]
the whole block is guarded by an `if (false)`. For the time being I ended up patching hb-coretext.cc by removing the offending lines, and I can build in release mode. https://github.com/trufont/uharfbuzz/commit/75170e875ed655e82f8180c0adcb8e8faf623064

**Comment by Gillibald** [comment]
Why do you need -Wunused-variable? That is the reason why your build fails. I don't think this is the right way to "fix" this.

**Comment by anthrotype** [comment]
I didn't enable that myself. Maybe CMAKE_BUILD_TYPE=Release does that automatically?
I am not familiar enough with cmake to debug this. I'm just pointing out that it used to work before harfbuzz 2.4.0, and now it no longer does.

**Comment by behdad** [comment]
In Release mode `assert` becomes no-op at a macro level it seems, which makes `backward` unused.
