### ISSUE TITLE
Investigate remaining AOTS tests

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1660]
We are currently have some of AOTS tests that are failing and the test suit are skipping them, look at the test that are commented https://github.com/harfbuzz/harfbuzz/tree/master/test/shaping/data/aots I guess it will be nice to see why they are failing sometime.

**Comment by khaledhosny** [comment]
I fixed a few in #3083. I checked some of the failing GPOS tests, and it seems related to advance zeroing of mark glyphs; AOTS does not expect the mark advances to be zeroed. Another one is related to the fact that we ignore yadvance when shaping in horizontal direction.
