### ISSUE TITLE
[discussion] provide tarballs compressed with xz instead of bzip2

### ISSUE THREAD

**Issue by vtorri** [harfbuzz/harfbuzz#1662]
hello

everything in the title. It will reduced the time downloading harfbuzz source

thank you

**Comment by behdad** [comment]
Next version tarballs will be ~4MB again, instead of current 16MB.  But yeah, I'm open to switching.

**Comment by vtorri** [comment]
you can also add such tarball, instead of switching, just add the option to AM_INIT_AUTOMAKE

**Comment by vtorri** [comment]
so, still no xz archives ?
