### ISSUE TITLE
Monotype Font licensing

### ISSUE THREAD

**Issue by juliaszegedi** [harfbuzz/harfbuzz#1671]
Hello,

Could you please help with licensing information for these fonts?: 

test/shaping/data/text-rendering-tests/fonts/TestGVARThree.ttf
test/shaping/data/text-rendering-tests/fonts/TestGVAROne.ttf 
test/shaping/data/text-rendering-tests/fonts/TestGVARTwo.ttf

Do you have a license agreement with Monotype, as mentioned in the reference from those fonts?:
“This font software is the property of Monotype Imaging Inc., one of its affiliated entities, or its licensors (collectively, Monotype) and its use by you is covered under the terms of a license agreement.”

Lots of thanks in advance!

Julia

**Comment by ebraminio** [comment]
Imported from https://github.com/unicode-org/text-rendering-tests per https://github.com/harfbuzz/harfbuzz/commits/master/test/shaping/data/text-rendering-tests/fonts/TestGVAROne.ttf apparently and it is OK apparently https://github.com/unicode-org/text-rendering-tests/commits/master/fonts/TestGVAROne.ttf @brawer

**Comment by juliaszegedi** [comment]
Thank you for your quick answer!

Best regards,
Julia
