### ISSUE TITLE
Different handling of England/Scotland/Wales flags in old Apple Color Emoji font

### ISSUE THREAD

**Issue by ubitux** [harfbuzz/harfbuzz#1672]
This is a continuation of the old issue https://github.com/harfbuzz/harfbuzz/issues/1292.

Using:
- `MD5 (Apple Color Emoji.ttf) = c764ac929e7a596b79d653b11035d648`
- `harfbuzz 2.4.0`

```
% hb-shape 'Apple Color Emoji.ttf' --remove-default-ignorables --shaper=coretext -u 'U+1F3F4,U+E0067,U+E0062,U+E0065,U+E006E,U+E0067,U+E007F'
[.notdef=0+800|.notdef=1+800|.notdef=2+800|.notdef=3+800|.notdef=4+800|.notdef=5+800|.notdef=6+800]
```

```
% hb-shape 'Apple Color Emoji.ttf' --remove-default-ignorables --shaper=ot -u 'U+1F3F4,U+E0067,U+E0062,U+E0065,U+E006E,U+E0067,U+E007F'
[u1F3F4=0+800]
```

The sequence corresponds to one the three Emoji Tag Sequence:

```
# Emoji_Tag_Sequence: See Annex C of TR51 for more information.

1F3F4 E0067 E0062 E0065 E006E E0067 E007F; Emoji_Tag_Sequence; flag: England                              #  7.0  [1] (🏴󠁧󠁢󠁥󠁮󠁧󠁿)
1F3F4 E0067 E0062 E0073 E0063 E0074 E007F; Emoji_Tag_Sequence; flag: Scotland                             #  7.0  [1] (🏴󠁧󠁢󠁳󠁣󠁴󠁿)
1F3F4 E0067 E0062 E0077 E006C E0073 E007F; Emoji_Tag_Sequence; flag: Wales                                #  7.0  [1] (🏴󠁧󠁢󠁷󠁬󠁳󠁿)
```

Source: http://www.unicode.org/Public/emoji/12.0/emoji-sequences.txt (note that this was present in previous Unicode versions).

**Comment by ebraminio** [comment]
Which is expected? Just showing an empty flag, OT, is not that bad when the font doesn't support anyway I guess? If that is the expected we can't do much about coretext backend I guess

**Comment by ubitux** [comment]
I'd say displaying the barebone black flag is better than nothing (and actually the expected behaviour?). I'll close for now.
