### ISSUE TITLE
knd3 issue in USE

### ISSUE THREAD

**Issue by MayuraVerma** [harfbuzz/harfbuzz#1677]
All these letter combinations are failing in knd3.
Same features with knd2 is rendering right text.

Text 1 (issue with reph and Kannada virama/virama U+0CCD) 
| ನ್ಯೂ ವರ್ಲ್ಡ್  

Expected output
![image](https://user-images.githubusercontent.com/14062593/56545378-0999de00-653d-11e9-890b-4731846d6e64.png)

Text 2 Issue with ZWJ
| ರ‍್ನಾ | ರ‍್ನ್ಕಾ | ರ್ರಾ
 | ರ‍್ನಿ | ರ‍್ನ್ಕಿ | ರ್ರಿ
 | ರ‍್ನೀ | ರ‍್ನ್ಕೀ | ರ್ರೀ
 | ರ‍್ನು | ರ‍್ನ್ಕು | ರ್ರು
 | ರ‍್ನೂ | ರ‍್ನ್ಕೂ | ರ್ರೂ
 | ರ‍್ನೃ | ರ‍್ನ್ಕೃ | ರ್ರೃ
 | ರ‍್ನೄ | ರ‍್ನ್ಕೄ | ರ್ರೄ
 | ರ‍್ನೆ | ರ‍್ನ್ಕೆ | ರ್ರೆ
 | ರ‍್ನೇ | ರ‍್ನ್ಕೇ | ರ್ರೇ
 | ರ‍್ನೈ | ರ‍್ನ್ಕೈ | ರ್ರೈ
 | ರ‍್ನೊ | ರ‍್ನ್ಕೊ | ರ್ರೊ
 | ರ‍್ನೋ | ರ‍್ನ್ಕೋ | ರ್ರೋ
 | ರ‍್ನೌ | ರ‍್ನ್ಕೌ | ರ್ರೌ
 | ರ‍್ನ್ | ರ‍್ನ್ಕ್ | ರ್ರ್

Expected output
![image](https://user-images.githubusercontent.com/14062593/56545468-4a91f280-653d-11e9-9473-8c52f4979b4f.png)

Text 3: U+0CB0 U+0CCD by itself should not form reph in Kannada.
ರ್

Expected output
![image](https://user-images.githubusercontent.com/14062593/56545598-ae1c2000-653d-11e9-8abc-5da9d44e0c0c.png)

Both version of the font is attached here.
knd2 and knd3

[Archive.zip](https://github.com/harfbuzz/harfbuzz/files/3105400/Archive.zip)

Summary:

All the above text is rendering the text correctly with knd2 but failing in knd3

**Comment by punchcutter** [comment]
With USE the features are handled in a different order so you need to be more explicit about which order things are happening. In your knd3 font `rphf` is being applied before `haln` which causes the reph to be formed first. 
Check the order of feature application on https://docs.microsoft.com/en-us/typography/script-development/use
You can also see which lookups are applied and in which order if you look at it with `hb-shape -V`
I haven't had a chance to check your ZWJ issues, but we had a lot of discussion about it at https://github.com/harfbuzz/harfbuzz/issues/542. Like I mentioned in the first comment there some features will skip ZWJ which could be what's happening if you aren't getting what you expect with ZWJ and knd3. Either way the first thing to check is which features are being used and the order they will be applied based on the USE spec. knd3 (and any Indic3) will definitely work correctly in USE, but it requires a slightly different approach.

**Comment by MayuraVerma** [comment]
@punchcutter 
I understand your explanation for Text 1. 
But for Text 3: ರ್ by itself, nothing before or after, must not form reph.

Please help me understand the below. 

lookup 22: 
lookup reph_kannada {
    lookupflag 0;
#    ignore sub [knRA ]' [knVirama ]' [knRA ] ;    
    ignore sub [knRA ]' [knVirama ]' [ZWJ ] [knKAc2 knKHAc2 knGAc2 knGHAc2 knNGAc2 knCAc2 knCHAc2 knJAc2 knJHAc2 knNYAc2 knTTAc2 knTTHAc2 knDDAc2 knDDHAc2 knNNAc2 knTAc2 knTHAc2 knDAc2 knDHAc2 knNAc2 knPAc2 knPHAc2 knBAc2 knBHAc2 knMAc2 knYAc2 knRAc2 knLAc2 knVAc2 knSHAc2 knSSAc2 knSAc2 knHAc2 knRRAc2 knLLAc2 knLLLAc2 knKSSAc2 knTAc2_RAc2 ] ;
    sub [knRA ]' [knVirama ]' by knReph;
} reph_kannada ;

lookup 19:
lookup haln0 {
	lookupflag IgnoreMarks;
	sub knKA knVirama by knK;
	sub knKHA knVirama by knKH;
	sub knGA knVirama by knG;
	sub knGHA knVirama by knGH;
	sub knNGA knVirama by knNG;
	sub knCA knVirama by knC;
	sub knCHA knVirama by knCH;
	sub knJA knVirama by knJ;
	sub knJHA knVirama by knJH;
	sub knNYA knVirama by knNY;
	sub knTTA knVirama by knTT;
	sub knTTHA knVirama by knTTH;
	sub knDDA knVirama by knDD;
	sub knDDHA knVirama by knDDH;
	sub knNNA knVirama by knNN;
	sub knTA knVirama by knT;
	sub knTHA knVirama by knTH;
	sub knDA knVirama by knD;
	sub knDHA knVirama by knDH;
	sub knNA knVirama by knN;
	sub knPA knVirama by knP;
	sub knPHA knVirama by knPH;
	sub knBA knVirama by knB;
	sub knBHA knVirama by knBH;
	sub knMA knVirama by knM;
	sub knYA knVirama by knY;
	sub knRA knVirama by knR;
	sub knLA knVirama by knL;
	sub knVA knVirama by knV;
	sub knSHA knVirama by knSH;
	sub knSSA knVirama by knSS;
	sub knSA knVirama by knS;
	sub knHA knVirama by knH;
	sub knRRA knVirama by knRR;
	sub knLLA knVirama by knLL;
	sub knLLLA knVirama by knLLL;
} haln0;

In knd2, hb-shape is ignoring the text [uni0CB0=0|uni0CCD=0] in lookup 22, which is reph sub and passing it in haln0 which is lookup 19
In knd3, hb-shape is ignoring the text [uni0CB0=0|uni0CCD=0] in lookup 22, which is reph sub.

Same issue is found in CoreText (Safari). 
Do we need to handle it this differently in feature file for knd3?

hb-shape output with knd2
trace: start lookup 22	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 22	buffer: [uni0CB0=0|uni0CCD=0]
trace: start lookup 23	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 23	buffer: [uni0CB0=0|uni0CCD=0]
trace: start lookup 25	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 25	buffer: [uni0CB0=0|uni0CCD=0]
trace: start lookup 14	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 14	buffer: [uni0CB0=0|uni0CCD=0]
trace: start lookup 15	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 15	buffer: [uni0CB0=0|uni0CCD=0]
trace: start lookup 16	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 16	buffer: [uni0CB0=0|uni0CCD=0]
trace: start lookup 17	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 17	buffer: [uni0CB0=0|uni0CCD=0]
trace: start lookup 18	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 18	buffer: [uni0CB0=0|uni0CCD=0]
trace: start lookup 19	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 19	buffer: [uni0CB00CCD=0]
trace: start lookup 20	buffer: [uni0CB00CCD=0]
trace: end lookup 20	buffer: [uni0CB00CCD=0]
trace: start lookup 21	buffer: [uni0CB00CCD=0]
trace: end lookup 21	buffer: [uni0CB00CCD=0]
trace: start lookup 27	buffer: [uni0CB00CCD=0]
trace: end lookup 27	buffer: [uni0CB00CCD=0]
trace: start lookup 28	buffer: [uni0CB00CCD=0]
trace: end lookup 28	buffer: [uni0CB00CCD=0]
trace: start lookup 29	buffer: [uni0CB00CCD=0]
trace: end lookup 29	buffer: [uni0CB00CCD=0]
trace: start lookup 30	buffer: [uni0CB00CCD=0]
trace: end lookup 30	buffer: [uni0CB00CCD=0]
trace: start lookup 31	buffer: [uni0CB00CCD=0]
trace: end lookup 31	buffer: [uni0CB00CCD=0]
trace: start lookup 32	buffer: [uni0CB00CCD=0]
trace: end lookup 32	buffer: [uni0CB00CCD=0]
trace: start lookup 33	buffer: [uni0CB00CCD=0]
trace: end lookup 33	buffer: [uni0CB00CCD=0]
trace: start lookup 34	buffer: [uni0CB00CCD=0]
trace: end lookup 34	buffer: [uni0CB00CCD=0]
trace: start lookup 35	buffer: [uni0CB00CCD=0]
trace: end lookup 35	buffer: [uni0CB00CCD=0]
trace: start lookup 36	buffer: [uni0CB00CCD=0]
trace: end lookup 36	buffer: [uni0CB00CCD=0]
trace: start lookup 37	buffer: [uni0CB00CCD=0]
trace: end lookup 37	buffer: [uni0CB00CCD=0]
trace: start lookup 0	buffer: [uni0CB00CCD=0+905]
trace: end lookup 0	buffer: [uni0CB00CCD=0+905]
trace: start lookup 1	buffer: [uni0CB00CCD=0+905]
trace: end lookup 1	buffer: [uni0CB00CCD=0+905]
trace: start lookup 2	buffer: [uni0CB00CCD=0+905]
trace: end lookup 2	buffer: [uni0CB00CCD=0+905]
trace: start lookup 3	buffer: [uni0CB00CCD=0+905]
trace: end lookup 3	buffer: [uni0CB00CCD=0+905]
[uni0CB00CCD=0+905]

hbshape output with knd3
trace: start lookup 22	buffer: [uni0CB0=0|uni0CCD=0]
trace: end lookup 22	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 23	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 23	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 25	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 25	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 14	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 14	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 15	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 15	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 16	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 16	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 17	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 17	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 18	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 18	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 19	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 19	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 20	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 20	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 21	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 21	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 27	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 27	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 28	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 28	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 29	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 29	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 30	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 30	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 31	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 31	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 32	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 32	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 33	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 33	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 34	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 34	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 35	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 35	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 36	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 36	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 37	buffer: [uni0CB00CCD.reph=0]
trace: end lookup 37	buffer: [uni0CB00CCD.reph=0]
trace: start lookup 0	buffer: [uni0CB00CCD.reph=0+482]
trace: end lookup 0	buffer: [uni0CB00CCD.reph=0+482]
trace: start lookup 1	buffer: [uni0CB00CCD.reph=0+482]
trace: end lookup 1	buffer: [uni0CB00CCD.reph=0+482]
trace: start lookup 2	buffer: [uni0CB00CCD.reph=0+482]
trace: end lookup 2	buffer: [uni0CB00CCD.reph=0+482]
trace: start lookup 3	buffer: [uni0CB00CCD.reph=0+482]
trace: end lookup 3	buffer: [uni0CB00CCD.reph=0+482]
[uni0CB00CCD.reph=0+482]

**Comment by MayuraVerma** [comment]
for ZWJ

Text : ರ‍್ಯಾ  [U+0CB0 U+200D U+0CCD U+0CAF U+0CBE]

hb-shape output for knd2:
trace: start lookup 22	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD=0|uni0CAF=0]
trace: end lookup 22	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD=0|uni0CAF=0]
trace: start lookup 23	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD=0|uni0CAF=0]
trace: end lookup 23	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 25	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 25	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 14	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 14	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 15	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 15	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 16	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 16	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 17	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 17	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 18	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 18	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 19	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 19	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 20	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 20	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 21	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 21	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 27	buffer: [uni0CB0=0|uni0CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 27	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 28	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 28	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 29	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 29	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 30	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 30	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 31	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 31	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 32	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 32	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 33	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 33	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 34	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 34	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 35	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 35	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 36	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 36	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 37	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: end lookup 37	buffer: [uni0CB00CBE=0|uni200D=0|uni0CCD0CAF=0]
trace: start lookup 0	buffer: [uni0CB00CBE=0+953|uni200D=0+0|uni0CCD0CAF=0+114]
trace: end lookup 0	buffer: [uni0CB00CBE=0+953|uni200D=0+0|uni0CCD0CAF=0+114]
trace: start lookup 1	buffer: [uni0CB00CBE=0+953|uni200D=0+0|uni0CCD0CAF=0+114]
trace: end lookup 1	buffer: [uni0CB00CBE=0+953|uni200D=0+0|uni0CCD0CAF=0+114]
trace: start lookup 2	buffer: [uni0CB00CBE=0+953|uni200D=0+0|uni0CCD0CAF=0+114]
trace: end lookup 2	buffer: [uni0CB00CBE=0+953|uni200D=0+0|uni0CCD0CAF=0+114]
trace: start lookup 3	buffer: [uni0CB00CBE=0+953|uni200D=0+0|uni0CCD0CAF=0+114]
trace: end lookup 3	buffer: [uni0CB00CBE=0+953|uni200D=0+0|uni0CCD0CAF=0+114]
[uni0CB00CBE=0+953|space=0+0|uni0CCD0CAF=0+114]

hb-shape output for knd3:
trace: start lookup 22	buffer: [uni0CB0=0|uni200D=0|uni0CCD=0|uni0CAF=3|uni0CBE=3]
trace: end lookup 22	buffer: [uni0CB0=0|uni200D=0|uni0CCD=0|uni0CAF=3|uni0CBE=3]
trace: start lookup 23	buffer: [uni0CB0=0|uni200D=0|uni0CCD=0|uni0CAF=3|uni0CBE=3]
trace: end lookup 23	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 25	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 25	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 14	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 14	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 15	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 15	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 16	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 16	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 17	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 17	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 18	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 18	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 19	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 19	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 20	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 20	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 21	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 21	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 27	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 27	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 28	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 28	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 29	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 29	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 30	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 30	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 31	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 31	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 32	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 32	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 33	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 33	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 34	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 34	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 35	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 35	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 36	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 36	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 37	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: end lookup 37	buffer: [uni0CB0=0|uni200D=0|uni0CCD0CAF=0|uni0CBE=0]
trace: start lookup 0	buffer: [uni0CB0=0+562|uni200D=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]
trace: end lookup 0	buffer: [uni0CB0=0+562|uni200D=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]
trace: start lookup 1	buffer: [uni0CB0=0+562|uni200D=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]
trace: end lookup 1	buffer: [uni0CB0=0+562|uni200D=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]
trace: start lookup 2	buffer: [uni0CB0=0+562|uni200D=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]
trace: end lookup 2	buffer: [uni0CB0=0+562|uni200D=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]
trace: start lookup 3	buffer: [uni0CB0=0+562|uni200D=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]
trace: end lookup 3	buffer: [uni0CB0=0+562|uni200D=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]
[uni0CB0=0+562|space=0+0|uni0CCD0CAF=0+0|uni0CBE=0+653]

**Comment by MayuraVerma** [comment]
@punchcutter thanks.
I think resolved the ZWJ issue, based on the hb-shape output clue.
But I would still like to hear your commentary on the above output. The text stream passed to lookup is different in knd2, I failing to understand.

**Comment by punchcutter** [comment]
Ah, I forgot about some of the special rules in the Indic shaper. In hb-ot-shape-complex-indic.cc 
```/* https://github.com/harfbuzz/harfbuzz/issues/435#issuecomment-335560167
   * // For compatibility with legacy usage in Kannada,
   * // Ra+h+ZWJ must behave like Ra+ZWJ+h...
```
which means your sequence knRA knVirama ZWJ will be reordered to knRA ZWJ knVirama in knd2, but not in knd3. So to get the same output you'll either need to change the lookups that expect this reordered output or do the reordering yourself first.

**Comment by MayuraVerma** [comment]
> which means your sequence knRA knVirama ZWJ will be reordered to knRA ZWJ knVirama in knd2, but not in knd3.

I have done that. It is resolved for ZWJ.

But the text ರ್  U+0CB0 U+0CCD by itself should not form reph in Kannada
This could be something that needs to be handled in shaper.
I am not sure if this can and should be handled in font.

**Comment by punchcutter** [comment]
Yes, the old way in Indic shapers is to handle the contextuality of <RA, VIRAMA> in the shaper so that it only forms a reph if there is a following consonant, but never when it's only <RA, VIRAMA>. But in USE shaping there is no check for this. This issue came up a couple times in https://github.com/googlefonts/noto-fonts/issues/1377 and https://github.com/googlefonts/noto-fonts/issues/1378. Either all USE shaping implementations will need to add checks for this or all USE shaped fonts will need to handle it at the font level. Like I wrote in https://github.com/googlefonts/noto-fonts/issues/1378 I don't really mind either way, but I'd like to hear what other people think about handling this in the USE shaper vs handling it in the font. @behdad @dscorbett ?

**Comment by MayuraVerma** [comment]
Also ರ್ರ ರ್ರಾ  
U+0CB0 U+0CCD U+0CB0 <any Kannada vowel mark>
must not form repha.

For Kannada.
1. reph can be formed only when it is followed by a Kannada vowel or consonant with or without vowel sign
2. reph can't be formed with U+0CB0 to the right of it.
3. reph can't be formed at the end of the word.

This above restriction must be implemented in the shaper. Since this is required for all Kannada font and its script definition. Many Kannada fonts don't implement it. 

I will report this is in microsoft USE definition
https://docs.microsoft.com/en-us/typography/script-development/kannada

Indic scripts must not be grouped together. There are more exceptions than similarities. 

Also, all Indic scripts are affected, because all definition, restrictions, features are defined for Devanagari first. This is defaulted to all other Indic scripts and later corrected as reported.

**Comment by dscorbett** [comment]
Why are you making a 'knd3' font? 'knd2' already does what you want and is more widely supported.

The USE and the Kannada shaper were never meant to be identical. The USE says nothing about only applying 'rphf' before certain letters, so when making a USE font 'rphf' should be a contextual lookup, with all the logic in the font. Microsoft is frustratingly unresponsive, so you will not be able to get them to change this. Even if they did, it would not be appropriate to put the script-specific exception that 'rphf' does not apply before U+0CB0 into the spec, so you’d need a contextual lookup anyway.

No change to HarfBuzz is needed. This issue should be closed.

**Comment by MayuraVerma** [comment]
Reason for knd3 is mac. They have serious bug in mac os/ios with U+0CCA and U+0CCB.
![Image-1](https://user-images.githubusercontent.com/14062593/56675193-27705b80-6681-11e9-91cb-06c73ef59ff9.jpg)

I understand for USE, we don't want to put any script script restrictions. But for knd2, we can have this restriction in all shaping engines. What would be a good starting point to do so?

Thanks to @punchcutter @dscorbett I learnt a lot in this discussion.

I will close this issue.

**Comment by behdad** [comment]
Agree with @dscorbett.
