### ISSUE TITLE
knd3 with USE contextual lookup

### ISSUE THREAD

**Issue by MayuraVerma** [harfbuzz/harfbuzz#1683]
Follow up to https://github.com/harfbuzz/harfbuzz/issues/1677

I am using contextual lookup with reph feature in knd3 script.

Text:
ರ್ಯಾಂಕ್ ಕರ್ಕೋಂರ್ ನ್ಯೂ ವರ್ಲ್ಡ್ 

Expected output:
![image](https://user-images.githubusercontent.com/14062593/56857422-e30be680-6932-11e9-8c1f-ca6c29fd6e8b.png)
Above is text rendered in Safari browser with CoreText.

Harfbuzz output with chrome:
![image](https://user-images.githubusercontent.com/14062593/56857441-39792500-6933-11e9-8d4a-bd0782f06f17.png)

Issue: Repha is not formed in harfbuzz.

Feature:
```fea
@KN_Letter = [knA knAA knI knII knU knUU knvR knvRR knvL knvLL knE knEE knAI knO knOO knAU
             knmAA knmI knmII knmU knmUU knmvR knmvRR knmvL knmvLL knmE knmEE knmAI knmO
             knmOO knmAU knLengthmark knAIlengthmark knKA knKHA knGA knGHA knNGA knCA knCHA
             knJA knJHA knNYA knTTA knTTHA knDDA knDDHA knNNA knTA knTHA knDA knDHA knNA
             knPA knPHA knBA knBHA knMA knYA knLA knVA knSHA knSSA knSA knHA knRRA knLLA
             knLLLA knAnusvara knCandrabindu knVisarga knNukta knSiddham knCandrabinduSign ];
lookup reph_kannada {
    lookupflag 0;
    ignore sub [knRA ]' [knVirama ]' [knRA ] ;
    sub [@KN_Letter knRA] [knRA ]' [knVirama ]' [@KN_Letter ] by knReph;
} reph_kannada ;
```

Logic: repha should be formed only in the middle of a Kannada word or in between Kannada letters.

Font: [Kannada-knd3-Regular.otf.zip](https://github.com/harfbuzz/harfbuzz/files/3124528/Kannada-knd3-Regular.otf.zip)

**Comment by MayuraVerma** [comment]
Also, harfbuzz is not adding the spacing to the text output for glyphs with "mark, spacing combing" type

**Comment by behdad** [comment]
I need someone to help debug this. I won't have time to look into it for a while.

**Comment by dscorbett** [comment]
'rphf' is applied per cluster, not per run. The rule can’t match `[@KN_Letter knRA]` because that would require backtracking into the previous cluster. This is the same problem as #1312.

**Comment by behdad** [comment]
For a second I thought we match context across syllables, but apparently not.  I think we tried that and it was breaking valid cases for Indic.  Also probably not a good idea to change given that there are other USE implementations as well. cc @jfkthame 

If you want to fix this for HarfBuzz only, I believe you can use the custom `HARF` feature to do substitutions before clusters are set up.

**Comment by dscorbett** [comment]
You should just remove the backtracking sequence from the rule. The only effect would be that a word beginning with ⟨<i>ra</i> virama consonant⟩ would now get a reph. I think such words do not exist, so it wouldn’t break anything. It would enable displaying standalone clusters with rephs for didactic purposes, which is a good thing.

**Comment by MayuraVerma** [comment]
"in Kannada reph is formed only in middle of two Kannada letters. 
'reph' shouldn't form when <ra virama> at the beginning of the word. 
'reph' shouldn't form for <ra virama ra>"

Word that starts with <ra virama consonant> is valid in Kannada script, it should form <ra blwf_consonant>.
In earlier version of open type fonts (Tunga) this sequence was wrongly presented with reph. Later, it was proposed to place ZWJ :->  <ra virama ZWJ consonant> and then <ra ZWJ virama consonant>

This is something which has missed in the original definition of Unicode for the Kannada. 

This should be resolved in shaping engine and font, not make average user to type ZWJ, when <ra> is at the beginning of the word. 

Even if they add  ZWJ, the Kannada text will not be dynamic. 
If the user edits the text and a Kannada letter in front of that word, reph should have been formed. But it won't be formed, because of ZWJ presence in the cluster.

Also, "find and replace text become an exception for <ra>.

Please do the needful.

**Comment by behdad** [comment]
I already provided a way that you can achieve this with HarfBuzz. You are welcome to file a bug report against OpenType's USE spec.

**Comment by MayuraVerma** [comment]
https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-39rphf39

**UI suggestion: In recommended usage, this feature triggers substitutions that are required for correct display of the given script. It should be applied in the appropriate contexts, as determined by script-specific processing.** 

Is this the right place to file the bug?

also, could you please let me know how to use make use of the custom HARF in this case or point me to some other font that uses this feature.

thanks.

**Comment by MayuraVerma** [comment]
Extract from Kannada comprehensive dictionary.
< ra virama consonant > reph is not formed
![image](https://user-images.githubusercontent.com/14062593/56937147-c43b5a80-6ac0-11e9-9618-939ce8eb98a7.png)
with reph
![image](https://user-images.githubusercontent.com/14062593/56937222-2d22d280-6ac1-11e9-97e8-fbdc0cb7dd05.png)

**Comment by behdad** [comment]
> Is this the right place to file the bug?

Thinking about it more, since indic3 is not part of OpenType (yet), there's nowhere to report.  I was thinking reporting against USE.  That is, here:

  https://docs.microsoft.com/en-us/typography/script-development/use

No harm filing a bug though.

**Comment by behdad** [comment]
> also, could you please let me know how to use make use of the custom HARF in this case or point me to some other font that uses this feature.

Just add a contextual rule to detect Ra,Halant at start of text and replace it with something that will prevent it later from forming reph...  Might be by inserting something after it for example.

**Comment by MayuraVerma** [comment]
> Just add a contextual rule to detect Ra,Halant at start of text and replace it

Is there a good way to detect beginning of text in word, beginning of document? I can use space, all punctuations, null, ... but there will be a case that will miss this exception. 

Thanks for the help.

**Comment by behdad** [comment]
> Is there a good way to detect beginning of text in word, beginning of document? I can use space, all punctuations, null, ... but there will be a case that will miss this exception.

There's a technic for that.  In Adobe .fea file format I think it's called an "ignore" rule?  Basically you match "[any] Ra Halant" (where any is matched in backtrack context), and do nothing, the following rule then matches "Ra Halant" and does something.  The second rule will only happen at beginning of text.

**Comment by behdad** [comment]
See: http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#5fii-specifying-exceptions-to-the-chain-sub-rule

**Comment by behdad** [comment]
Anything to be done in HarfBuzz here?
