### ISSUE TITLE
hb-shape trace coretext shaper

### ISSUE THREAD

**Issue by MayuraVerma** [harfbuzz/harfbuzz#1684]
hb-shape -V provides lookup by lookup "trace" for harfbuzz
but it doesn't provide the lookup by lookup "trace" for coretext with option --shapers=coretext
instead it provides the last step.

**Comment by MayuraVerma** [comment]
we have similar one line output in windows with --shapers=uniscribe flag.
Should I use some flag to get the full trace?

**Comment by jfkthame** [comment]
HarfBuzz has has no way of examining everything that's happening internally within core text or uniscribe. It just hands them the text and gets back the final shaped result, so it can't give more detailed tracing of the library's internal processing.

**Comment by behdad** [comment]
Indeed.  Can't.

**Comment by MayuraVerma** [comment]
is there a way to trace the text formation with "Adobe World Ready Composer" with hb-shape?

**Comment by behdad** [comment]
No.
