### ISSUE TITLE
Unified API to fetch glyph countors

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1686]
Having some API equal to `GetOutlineTextMetricsW`, `CTFontCreatePathForGlyph`, `FT_Outline_Decompose` will be nice now that we have both glyf and CFF parsing for subsetters inside harfbuzz. Personally all I want is to use the API to create a svg path.

* I think I don't like to have an API like `FT_Outline_Decompose` that user should pass callbacks to it but something like `CTFontCreatePathForGlyph` that returns `CGPathRef`, enough information upper layers to do their works not IoC.
* We should consider some flag parameter for the API so user can choose to have either the path in non-hinted (default), hinted or autohinted forms (whenever of whether implemented, we can proxy to freetype for that also)
* `GetOutlineTextMetricsW` and `CTFontCreatePathForGlyph`, both get a matrix in input, I am not sure what is the propose of it, I think we don't need it.
* Should it apply variation itself, thus, getting hb_font_t in input? If so that will be a huge work but that is OK since variable font instantiation is in roadmap anyway.
* We should resolve the subcomponents paths ourselves not exposing the concept to client I guess.
* If we can't offer all the things from the beginning, maybe exposing the API behind some compile flag initially before we get confident what would be best.

I have something related but very subtle on #875 and it doesn't deal with `glyf` glyphs' sub-components and lots of other things

**Comment by ebraminio** [comment]
Useful links:
* Glyphy's FT_Outline_Decompose use https://github.com/behdad/glyphy/blob/73d7fbd96975249c4eb806be94b9889df839335b/src/glyphy-freetype.h#L44-L97
* https://developer.apple.com/documentation/coretext/1510921-ctfontcreatepathforglyph?language=objc
* https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-getglyphoutlinew
* https://docs.microsoft.com/en-us/windows/desktop/api/wingdi/nf-wingdi-getoutlinetextmetricsw
* https://github.com/nothings/stb/blob/master/stb_truetype.h features both contours fetch of cff and glyf and rasterization in one single header.
* Typr.js's CFF https://github.com/photopea/Typr.js/blob/877046eeb2c78ffeeb1f34e167308e0b785a1457/src/tabs/cff.js and glyf https://github.com/photopea/Typr.js/blob/877046eeb2c78ffeeb1f34e167308e0b785a1457/src/tabs/glyf.js parsing
* OpenType.js https://github.com/opentypejs/opentype.js/blob/4c590023cf1e3a96947462d2dfbe9ae64c4b1c66/src/tables/glyf.js and https://github.com/opentypejs/opentype.js/blob/4c590023cf1e3a96947462d2dfbe9ae64c4b1c66/src/tables/cff.js
* https://github.com/ynakajima/ttf.js
* https://github.com/foliojs/fontkit

**Comment by ebraminio** [comment]
servo/webrender has to have freetype only because of this https://github.com/servo/webrender/pull/2566#issuecomment-375896077 of course freetype outline fetch is able to apply hinting and autohinting at the same time, not sure if that flags is used there, but having glyph outline API without hinting for now will be a good thing for smaller or embedded projects, like our harfbuzzjs for now.

**Comment by khaledhosny** [comment]
Would this also handle variable fonts (interpolate the outlines mainly)?

**Comment by ebraminio** [comment]
Current draft supposed #2016 supposed to support variable fonts, if it doesn't certainly a bug that should be fixed so have a look at the draft it should be easy to run

**Comment by khaledhosny** [comment]
Thanks, will check.

**Comment by ebraminio** [comment]
`$ src/test-ot-glyph ./test/api/fonts/AdobeVFPrototype.abc.otf`

```
    hb_variation_t var = {HB_TAG('w','g','h','t'), 100};
    hb_font_set_variations (font, &var, 1);
```

![image](https://user-images.githubusercontent.com/833473/68993955-71759480-0892-11ea-99dd-8c38bde584d2.png)

```
    hb_variation_t var = {HB_TAG('w','g','h','t'), 700};
    hb_font_set_variations (font, &var, 1);
```

![image](https://user-images.githubusercontent.com/833473/68993976-9ff36f80-0892-11ea-8bc9-9c3a62fdbc50.png)

It supposed to work but hadn't tested it till now which seems to be ok.
