### ISSUE TITLE
Add hb_face_set_table_tags_func()

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1697]
Currently `hb_face_get_table_tags()` only works with our own face loader.  Other loaders cannot implement it.  Add a callback setter such that they can.  Then implement it for hb-ft.

**Comment by behdad** [comment]
See https://github.com/harfbuzz/harfbuzz/issues/3609

**Comment by Outlaw999** [comment]
> Currently `hb_face_get_table_tags()` only works with our own face loader. Other loaders cannot implement it. Add a callback setter such that they can. Then implement it for hb-ft.

(Stranger)

**Comment by behdad** [comment]
Being worked on in https://github.com/harfbuzz/harfbuzz/issues/4821 and https://github.com/harfbuzz/harfbuzz/pull/4825
