### ISSUE TITLE
Add hb_blob_advise()?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1698]
Similar to fadvise()?

**Comment by ebraminio** [comment]
I was considering this before but now I studied it a little more it this Linux implementation detail seemed interesting to me,

> Linux notes
>       The Linux implementation requires that the address addr be page-aligned,

And it looks scary. Is this about `hb_blob_create_from_file`? Who is its client? That bit may fallbacks to fread thus making less use, and Windows, we have to polyfill there? I would say lets not involve with IO more that this.

**Comment by behdad** [comment]
Since this is purely advice, no need for polyfill.  I have a clear goal... Will share when I write up. :)

**Comment by behdad** [comment]
Humm I don't remember what "clear goal" I had in mind!  But I was thinking of just advising GSUB/GPOS/... whatever we need for shaping...

**Comment by behdad** [comment]
`posix_madvise` is what we will be using, not Linux fadvise.

**Comment by behdad** [comment]
But yeah am happy to just close as well.
