### ISSUE TITLE
Mapping a Smiley character

### ISSUE THREAD

**Issue by photopea** [harfbuzz/harfbuzz#1699]
I tried to shape a string "Ph☺t☻pea" with an attached font, but HarfBuzz maps both smileys (0x263a, 0x263b) to a Glyph 0 (empty glyph).

They should be mapped to glyphs 1218 and 1219 . 

In "cmap", there is a sub-table with Platform 0, Encoding 4, which has a format 12 and maps 0x263a to 1218.

[SourceCodePro-Black.zip](https://github.com/harfbuzz/harfbuzz/files/3153249/SourceCodePro-Black.zip)

**Comment by jfkthame** [comment]
Seems to work as expected here:

    $ ./util/hb-shape --font-file ~/Downloads/SourceCodePro-Black.otf "Ph☺t☻pea"
    [P=0+600|h=1+600|smileface=2+600|t=3+600|invsmileface=4+600|p=5+600|e=6+600|a=7+600]

**Comment by photopea** [comment]
@jfkthame @behdad @ebraminio   I am using a WASM release of the library https://github.com/harfbuzz/harfbuzzjs  Could that be a problem?

**Comment by ebraminio** [comment]
It is okay here also https://harfbuzz.github.io/harfbuzzjs/ as I get `[{"g":17,"cl":0,"dx":0,"dy":0,"ax":600,"ay":0},{"g":35,"cl":1,"dx":0,"dy":0,"ax":600,"ay":0},{"g":1218,"cl":2,"dx":0,"dy":0,"ax":600,"ay":0},{"g":47,"cl":5,"dx":0,"dy":0,"ax":600,"ay":0},{"g":1219,"cl":6,"dx":0,"dy":0,"ax":600,"ay":0},{"g":43,"cl":9,"dx":0,"dy":0,"ax":600,"ay":0},{"g":32,"cl":10,"dx":0,"dy":0,"ax":600,"ay":0},{"g":28,"cl":11,"dx":0,"dy":0,"ax":600,"ay":0}]` so I guess something is wrong with your code.

**Comment by photopea** [comment]
Guys, I am so sorry. It took me two hours to find out, that there are two versions of this font in my database, and have been testing HarfBuzz with a different font, than I attached here. Sorry :/
