### ISSUE TITLE
Completely move Google Fonts subsetting off fonttools.

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1707]
Was on roadmap for 2019, curious to know what will be needed so lets turn into a file

**Comment by ebraminio** [comment]
@garretrieger @rsheeter @anthrotype @nona-google hey there, do you know the status what is remained? Thanks

**Comment by behdad** [comment]
Guess finishing GSUB/GPOS in subsetter first, and then also variation instantiation.  So, probably would be next year.

**Comment by garretrieger** [comment]
Yeah, that's correct. Those are the last two things we need.

**Comment by khaledhosny** [comment]
OTL subsetting is done and instantiation is tracked in #2112.
