### ISSUE TITLE
hb_shape/hb_buffer_get_length returns size shorter then input string. Normal?

### ISSUE THREAD

**Issue by jasonchtai** [harfbuzz/harfbuzz#1712]
ISSUE: After hb_sharp, hb_buffer_get_length return size smaller than input string.

Sometimes harfuzz chops off 'fi's. In some parts of my program. It doesn't chop. Other parts, it chops. Sometime it draws but the horizontal advances slightly off. Any word that have 'fi' in it looks weird.

Detail: 'Artificial' and 'difficult' returns 1 less; e.g., the former returns 9 rather than 10, the latter returns 8 rather than 9. Consequently hb_buffer_get_glyph_positions's array excludes 'i' from 'fi' which I can tell from the values in the return array. 

Example:
    String : 'Artificial' (length = 10)
    x_advance : {11, 5, 4, 3, 8, 9, 3, 9, 3} (length = 9)
    
So {9, 3, 9, 3} was meant for 'cial' now taken to 'icia'. The last character 'l' remains uninitialized. This is reflected in the draw as well. Since 'l' normally maps to some large junk negative numbers, 'l' and rest of line was clipped.

Am I missing something or I have done something in my code should be aware of? Or it's a bug?

I must say that I constructed a simplistic test program that let me test specific strings and fonts did not have this problem. My main program uses mainly 1 ascii font but size varies in different places. The other font I use was a chinese font which only displays in Settings where I allow user to change language.

Jason Tai

---- info below -----

Font: Aileeron-Thin.oth downloaded from 1001fonts.com. Size used 19.
Version: 2.4 April 19.
System: Windows 64bit. Compiler defines : HAVE_UCDN and HAVE_DIRECTWRITE

Code:
	int TypeFace::GetAdvances(const wchar_t s[], int /* -1 if auto */ Length, short Advances[])
	{
		hb_buffer_t *hb_buffer = hb_buffer_create();

		hb_buffer_add_utf16(hb_buffer, (const uint16_t *) s, Length, 0, Length);
		hb_buffer_guess_segment_properties(hb_buffer);

		hb_font_t *hb_font = hb_ft_font_create(Face, null);
		hb_shape(hb_font, hb_buffer, NULL, 0);
		
		int n = hb_buffer_get_length(hb_buffer); //  <------- HERE
		hb_glyph_position_t *pos = hb_buffer_get_glyph_positions(hb_buffer, null);
		
		int PixelWidth = 0;
		
		for (int i = 0; i < n; i++)
		{
			int nPixels = pos[i].x_advance / 64.0;
			
			Advances[i] = nPixels;
			PixelWidth += nPixels;
		}

		hb_font_destroy(hb_font);
		hb_buffer_destroy(hb_buffer);

		return PixelWidth;
	}

**Comment by jfkthame** [comment]
On 14/05/2019 08:41, jasonchtai wrote:
> ISSUE: After hb_sharp, hb_buffer_get_length return size smaller than 
> input string.
> 
> Sometimes harfuzz chops off 'fi's. In some parts of my program. It 
> doesn't chop. Other parts, it chops. Sometime it draws but the 
> horizontal advances slightly off. Any word that have 'fi' in it looks weird.
> 
> Detail: 'Artificial' and 'difficult' returns 1 less; e.g., the former 
> returns 9 rather than 10, the latter returns 8 rather than 9. 
> Consequently hb_buffer_get_glyph_positions's array excludes 'i' from 
> 'fi' which I can tell from the values in the return array.
> 
> Example:
> String : 'Artificial' (length = 10)
> x_advance : {11, 5, 4, 3, 8, 9, 3, 9, 3} (length = 9)
> 
> So {9, 3, 9, 3} was meant for 'cial' now taken to 'icia'. The last 
> character 'l' remains uninitialized. This is reflected in the draw as 
> well. Since 'l' normally maps to some large junk negative numbers, 'l' 
> and rest of line was clipped.
> 
> Am I missing something or I have done something in my code should be 
> aware of? Or it's a bug?

I think you need to read up about the character/glyph model, understand 
the difference between character codes and glyph IDs, and understand 
that there is not a 1:1 mapping between characters in the Unicode text 
and glyphs that are rendered by a font.

You're using a font where the pair "fi" is substituted with a single "ﬁ" 
ligature glyph. The number of glyphs in the buffer after shaping may not 
be the same as the number of characters in the original text.

JK

**Comment by jasonchtai** [comment]
I didn't know that. Thanks :) I'll read up on it.

Jason Tai
