### ISSUE TITLE
Someway to configure HB_TINY?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1727]
I like to use all of the HB_TINY for harfbuzzjs but as I am using the serializer I have to issue
```diff
diff --git a/src/hb-config.hh b/src/hb-config.hh
index fd5a7134..b1ad48c1 100644
--- a/src/hb-config.hh
+++ b/src/hb-config.hh
@@ -52,7 +52,7 @@
 #define HB_DISABLE_DEPRECATED
 #define HB_NDEBUG
 #define HB_NO_ATEXIT
-#define HB_NO_BUFFER_SERIALIZE
+//#define HB_NO_BUFFER_SERIALIZE
 #define HB_NO_BITMAP
 #define HB_NO_CFF
 #define HB_NO_COLOR
```
before the build, either we should define someway to be able to tune HB_TINY, or writing something for harfbuzzjs to make it not use serializer

**Comment by behdad** [comment]
Sigh, yes.  Let's think what's easiest.  Does the following passed to configure or make work:
```
CPPFLAGS='-include hb-config.hh -UHB_NO_BUFFER_SERIALIZE`.

As discussed offline, I'm also fine with just removing the json serialize format and adding txt form.  But then again, most tiny use-cases don't need serialize.

**Comment by ebraminio** [comment]
That, and using other flags, doesn't apparently work with cmake :/

**Comment by behdad** [comment]
> That, and using other flags, doesn't apparently work with cmake :/

That's not very helpful.  Like, you cannot set CPPFLAGS in any way?  That's a stupid build system.

**Comment by behdad** [comment]
Why do you insist on using cmake anyway?

**Comment by ebraminio** [comment]
> That's not very helpful. Like, you cannot set CPPFLAGS in any way? That's a stupid build system.

Maybe my fault, I tried several options however but still.

> Why do you insist on using cmake anyway?

As emscripten provides a working cmake helper and I found building with emcmake works much smoother than autotools but I didn't try autotools again, maybe now I can set it up again.

**Comment by behdad** [comment]
Emscripten used to have `emconfigure`.

**Comment by ebraminio** [comment]
Yep confirming autotools works as well with emconfigure, it just need disabling ICU which is no issue, lets close this and track it in harfbuzzjs repo. Thanks
