### ISSUE TITLE
Update win32 instructions for Fedora

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1728]
On Fedora 29 I installed:
```
dnf install mingw32-gcc-c++ mingw32-glib2 mingw32-cairo mingw32-freetype
```
then configure with:
```
../mingw32.sh --with-uniscribe --with-freetype --with-cairo PKG_CONFIG_PATH=/usr/i686-w64-mingw32/sys-root/mingw/lib/pkgconfig
```

For 64bit:
```
dnf install mingw64-gcc-c++ mingw64-glib2 mingw64-cairo mingw64-freetype
```
then configure with:
```
../mingw64.sh --with-uniscribe --with-freetype --with-cairo PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig
```

Both seem to build fine.  I have not figured out the packaging part yet.

**Comment by ebraminio** [comment]
Then we should put the commands on https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml#L195 and using store_artifacts of https://github.com/ebraminio/DroidPersianCalendar/blob/master/.circleci/config.yml#L22-L26 CircleCI we can store hb-view/hb-shape of each build for bisecting reasons in CircleCI's storage

**Comment by behdad** [comment]
FWIW, the DLLs to bundle are in `/usr/i686-w64-mingw32/sys-root/mingw/bin/` and the respective 64-bit location.  Working on the bundle script now.

**Comment by behdad** [comment]
I used a modified version of https://github.com/xantares/mingw-ldd/blob/master/mingw-ldd.py to locate used DLLs:
```
../../mingw-ldd.py hb-view.exe  | grep -v 'not found' | cut -d '>' -f 2 | xargs cp -t .
```

**Comment by behdad** [comment]
Here's a bundle if anyone wants to test: https://drive.google.com/open?id=18YcvsM7mXDkeP05LGe7mV4WeouKQAppW

**Comment by ebraminio** [comment]
[image: image.png]
It says it can't find hb_buffer_set_invisible_glyph in hb-shape.exe or
something :/

**Comment by behdad** [comment]
My bad.  I had accidentally also copied libharfbuzz DLL from mingw.  Updated bundle:
https://drive.google.com/open?id=13Bt_cOmwWFKGDv0n7OifWVrZ-dJtFzln

**Comment by behdad** [comment]
Now one just need to run `../mingw32.sh` or `../mingw64.sh` on Fedora.

**Comment by ebraminio** [comment]
I can confirm all three executables work fantastically on a Windows 8
machine, was wishing to see it work on Windows XP soon :)

**Comment by behdad** [comment]
Fixed in https://github.com/harfbuzz/harfbuzz/commit/c41ed54b169c16fb9862e88ddf127ae68c1561e9

**Comment by behdad** [comment]
> was wishing to see it work on Windows XP soon :)

Doable if you want to tweak and see if you can make it detect pthread.  It's not for me.

**Comment by behdad** [comment]
I made mutex code prefer pthread over windows.  I also uploaded 2.5.0 win32 bundle with these changes to github and fdo.  Please test again both on win8 and winxp if you can.  I'm glad we have the bundles back.

**Comment by ebraminio** [comment]
Works perfectly with 8!

XP still has the issue so it can be libpthread compatibility itself.
