### ISSUE TITLE
Visual Studio build issue

### ISSUE THREAD

**Issue by egorpugin** [harfbuzz/harfbuzz#1730]
Using hb2.5.0 I see following error.
```
When executing: "[behdad.harfbuzz-2.5.0]/src/hb-ot-layout.cc"
D:\temp\29\.sw\src\aa5dc3ae8830\harfbuzz-2.5.0\src\hb-algs.hh(839): error C2440: 'return': cannot convert from 'hb_partial_t<2,Appl,V>' to 'hb_partial_t<2,Appl,V>'
        with
        [
            Appl=const <unnamed-type-hb_add> *,
            V=const OT::RuleSet *
        ]
        and
        [
            Appl=const <unnamed-type-hb_add> *const ,
            V=const OT::RuleSet *
        ]
D:\temp\29\.sw\src\aa5dc3ae8830\harfbuzz-2.5.0\src\hb-algs.hh(839): note: No constructor could take the source type, or constructor overload resolution was ambiguous
D:\temp\29\.sw\src\aa5dc3ae8830\harfbuzz-2.5.0\src\hb-ot-layout-gsubgpos.hh(1374): note: see reference to function template instantiation 'hb_partial_t<2,Appl,V> <unnamed-type-hb_add>::operator ()<const OT::RuleSet*>(_T &&) const' being compiled
        with
        [
            Appl=const <unnamed-type-hb_add> *const ,
            V=const OT::RuleSet *,
            _T=const OT::RuleSet *
        ]
```

There are tons of these errors from many source files.

Do you test VS2019? I use custom build, so it might be only my issue.
Or it could be VS issue.

**Comment by behdad** [comment]
I'm fairly sure it's VS2019 issue.  That's really unfortunate.  We have VS bots, but much older than 2019.  We also have a dozen other bots.  gcc 4.8 has a similar issue with that piece of code, but gcc 4.9+, multiple clang versions, one MSVC version, and at least another compiler are all happy with it.  I also reviewed the code and the error doesn't make sense.

**Comment by egorpugin** [comment]
See https://developercommunity.visualstudio.com/content/problem/583340/vs2019-errors-when-building-harfbuzz-250.html

**Comment by ebraminio** [comment]
We can dedicate a bot to VS2019 but now that it is broken lets see what Microsoft thinks about it https://developercommunity.visualstudio.com/comments/584497/view.html Thanks for filing the bug and reporting to Microsoft also.

**Comment by behdad** [comment]
VS2019 bot would be great.

For those reading this, the reason I think this is a compiler issue is that the relevant code uses decltype to return, so the error doesn't make sense.  What the error means is that decltype returned a type different from the type that returning the same expression from the function is deemed to have.

**Comment by ebraminio** [comment]
Ok, both 2017 and 2019 are broken right now

https://ci.appveyor.com/project/harfbuzz/harfbuzz/builds/24876208/job/kbbbuu0562f975a4

https://ci.appveyor.com/project/harfbuzz/harfbuzz/builds/24876208/job/0xv7ufq6r8j3ycss

**Comment by ebraminio** [comment]
2013 is also broken https://ci.appveyor.com/project/harfbuzz/harfbuzz/builds/24877151/job/2yt5d21fv4cww4t6 and the only MSVC which is not broken is apparently 2015 which was on our CI :)

**Comment by egorpugin** [comment]
Maybe it's worth it not to hide these errors and turn on VS2017 build bots back?
And probably it's possible to workaround the issue for VS.

**Comment by behdad** [comment]
Orvid King provided me the following extremely hacky patch that seems to at least make it compile:
```diff
diff --git a/src/hb-algs.hh b/src/hb-algs.hh
index 007db9e4..2bd86b3b 100644
--- a/src/hb-algs.hh
+++ b/src/hb-algs.hh
@@ -167,10 +167,18 @@ template <unsigned Pos=1, typename Appl, typename V>
 auto hb_partial (Appl&& a, V&& v) HB_AUTO_RETURN
 (( hb_partial_t<Pos, Appl, V> (a, v) ))
 
+#if _MSC_VER
+#define HB_PARTIALIZE(Pos)                         \
+  template <typename _T>                           \
+  decltype(auto) operator() (_T &&_v) const { \
+      hb_partial<Pos> (this, hb_forward<_T> (_v)) \
+  } static_assert (true, "")
+#else
 #define HB_PARTIALIZE(Pos) \
   template <typename _T> \
   auto operator () (_T&& _v) const HB_AUTO_RETURN (hb_partial<Pos> (this, hb_forward<_T> (_v))) \
   static_assert (true, "")
+#endif
 
 
 struct
```

**Comment by behdad** [comment]
Okay committed Orvid's solution.

**Comment by ebraminio** [comment]
Coool!

**Comment by egorpugin** [comment]
Thank you!
Works for me.
