### ISSUE TITLE
Valgrind timeout is not reported clearly

### ISSUE THREAD

**Issue by rsheeter** [harfbuzz/harfbuzz#1737]
Ran into an issue where what I'm told is Valgrind timeout made the bot report failure (https://circleci.com/gh/harfbuzz/harfbuzz/92125?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

It would be nice if it clearly said it was a timeout in this case, rather than reporting that tests failed.

**Comment by behdad** [comment]
Also bonus points if timeout can be increased when running under valgrind.

**Comment by behdad** [comment]
Closing as will never get to do anything about it.
