### ISSUE TITLE
Link syntax error on wiki

### ISSUE THREAD

**Issue by archiloque** [harfbuzz/harfbuzz#1743]
Not sure if it's the right place for this issue but didn't find another one.

The wiki page of the project at https://www.freedesktop.org/wiki/Software/HarfBuzz/ has a syntax error in a link to Apple Advanced Typography in the first paragraph 
[Apple Advanced Typography|https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6AATIntro.html]]

**Comment by behdad** [comment]
Fixed.  Thanks.
