### ISSUE TITLE
Disabling -Werror

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#1763]
harfbuzz builds with `-Werror`. How can I disable that?

**Comment by behdad** [comment]
Define `HB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR`.  What errors are you seeing?

**Comment by behdad** [comment]
Ping?

**Comment by ryandesign** [comment]
Thanks, adding `-DHB_NO_PRAGMA_GCC_DIAGNOSTIC_ERROR` to CFLAGS and CXXFLAGS worked.

Every year, Apple releases a new version of Xcode with a new version of clang, which might contain new warnings, so something that built without warnings in Xcode 10 might have some warnings in Xcode 11. I don't want users to encounter build failures just because they're using a newer Xcode than I was, which is why in MacPorts we don't build with `-Werror`.

**Comment by behdad** [comment]
FWIW I'm also against `-Werror`, for the same reasons.  What we do in HB though is enable error for specific warning flags that we know we should be clean of.

**Comment by ebraminio** [comment]
> Apple releases a new version of Xcode with a new version of clang, which might contain new warnings, so something that built without warnings in Xcode 10 might have some warnings in Xcode 11

We have the most brand new clang compiler, installed everytime from latest version of snapshot llvm releases in our -Weverything bot and we will get notice about every newly introduced compile flag. See source of the bot https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml#L118 I believe we won't have such issue in future

**Comment by behdad** [comment]
> We have the most brand new clang compiler, installed everytime from latest version of snapshot llvm releases in our -Weverything bot and we will get notice about every newly introduced compile flag. See source of the bot https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml#L118 I believe we won't have such issue in future

Except that we don't build `hb-coretext` there.  Also, different configurations... for example, we hit some errors when `CGFloat` was defined to `double` instead of `float`, or other way around.

**Comment by ebraminio** [comment]
:/ I wish we could just keep the defaults or disable errors for that specific auxiliary file
