### ISSUE TITLE
Suggestions for HB_TINY additions

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1764]
Would be nice if we had some definition for removing use of `setlocale` and disable `hb_blob_create_from_file` use of fopen/fclose/...

Also not sure why we have a round [polyfill](https://github.com/harfbuzz/harfbuzz/blob/3c240bd3dc0aaca38154da555d0aef350da62ee6/src/hb.hh#L518) but isn't used anywhere or instead roundf, probably should be deleted altogether.

**Comment by ebraminio** [comment]
Also would be nice to have `#define roundf __builtin_roundf` somewhere inside the project, probably guarded with `__has_builtin(__builtin_roundf)` or something

**Comment by ebraminio** [comment]
Some `#if defined(__OPTIMIZE_SIZE__) || defined(HB_USE_INTERNAL_QSORT)` https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-algs.hh#L846 is needed

**Comment by ebraminio** [comment]
801d93f

**Comment by behdad** [comment]
Right.  Let's rename NO_FILE_READ to NO_OPEN and then I add these to TINY.
