### ISSUE TITLE
Someway to make py3 strings work in _from_string APIs

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1769]
I'm not hopeful [and interested] in this https://stackoverflow.com/a/56533873 but as I'm asked to fill a file so someone may have solution, maybe there is someway to make `HarfBuzz.language_from_string('en')` work again in py3 like `HarfBuzz.language_from_string(b'en')`, or maybe not.

**Comment by khaledhosny** [comment]
Since the C APIs take C strings are these are byte strings, I think `bytes` in Python 3 is the appropriate match.

**Comment by adrientetar** [comment]
In uharfbuzz we just convert to bytes internally.

**Comment by ebraminio** [comment]
Thanks @khaledhosny and @adrientetar, so probably nothing can be done from our side, lets close this.
