### ISSUE TITLE
Metrics differ for CFF fonts between Ubuntu and Arch Linux / Mac

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#1776]
See simoncozens/sile#639. Using the `travisci/ci-sardonyx` docker image:

```
# wget https://github.com/alif-type/libertinus/raw/v6.9/LibertinusSerif-Regular.otf
# hb-shape --version
hb-shape (HarfBuzz) 2.5.1
Available shapers: ot,fallback

# hb-shape --shapers=ot --show-extents LibertinusSerif-Regular.otf 'a'
[a=0+457<27,456,437,-466>]
```

On my Mac locally:

```
$ wget https://github.com/alif-type/libertinus/raw/v6.9/LibertinusSerif-Regular.otf
$ hb-shape --version
hb-shape (HarfBuzz) 2.5.1
Available shapers: graphite2,ot,coretext,fallback
$ hb-shape --shapers=ot --show-extents .fonts/LibertinusSerif-Regular.otf 'a'
[a=0+457<36,439,419,-449>]
```

**Comment by ebraminio** [comment]
Most likely freetype version different, test with `--font-funcs ot` as see what happens

**Comment by simoncozens** [comment]
# hb-shape --font-funcs ot --show-extents .fonts/LibertinusSerif-Regular.otf 'a'
[gid66=0+457<36,439,419,-449>]

OK, that's it. So we need to make sure in our code that we are using the OT funcs. (I'm presuming that Harfbuzz OT funcs has the correct metrics and freetype is wrong...)

**Comment by ebraminio** [comment]
> OK, that's it. So we need to make sure in our code that we are using the OT funcs. (I'm presuming that Harfbuzz OT funcs has the correct metrics and freetype is wrong...)

Let's not call it wrong but different between different versions of freetype and also harfbuzz and I guess harfbuzz version, donated by Adobe, will be stable enough to use.

**Comment by behdad** [comment]
Someone should dump the glyph with ttx and see what the correct bounding box is.

**Comment by khaledhosny** [comment]
> Someone should dump the glyph with ttx and see what the correct bounding box is.
> 

Is there even a definition of the correct bounding box for CFF glyphs?

**Comment by behdad** [comment]
> Someone should dump the glyph with ttx and see what the correct bounding box is.
> Is there even a definition of the correct bounding box for CFF glyphs?

One can compute the control-box or the ink box the same way that's done for glyf outlines.  It's a matter of geometry.  FontTools actually has pens for those: `fontTools.pens.boundsPen.ControlBoundsPen` and `fontTools.pens.boundsPen.BoundsPen`.
