### ISSUE TITLE
Figure out how to support emoji ZWJ sequences properly

### ISSUE THREAD

**Issue by roozbehp** [harfbuzz/harfbuzz#179]
Currently, if a font has GSUB features for replacing a sequence of emoji characters interspersed with ZWJ, it won't work when the direction is RTL and there's no script information (or may get applied in reverse, etc).

UTC participants have informally agreed to keep the list as limited as possible. The official TR now says "The use of ZWJ sequences may be difficult in some implementations, so caution should taken before adding new sequences."

Perhaps we can add a special code path for the specific character sequences, hardcoding either the sequences or the characters that participate in them. A computer-processable list is at http://www.unicode.org/Public/emoji/2.0//emoji-zwj-sequences.txt.

(Note that the new OpenType proposal for carrying direction information in lookups would not solve this problem, since .)

/cc @raphlinus @dougfelt

**Comment by behdad** [comment]
> (Note that the new OpenType proposal for carrying direction information in lookups would not solve this problem, since .)

Broken sentence.

**Comment by khaledhosny** [comment]
This was recently fixed, right?

**Comment by behdad** [comment]
Right.
