### ISSUE TITLE
Add .editorconfig and .clang-format to EXTRA_DIST?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1794]
Currently they don't make it to the tarball (no dot-files do).  The CI-related ones shouldn't.  But these two sound like they should maybe?  Or perhaps doesn't matter.  No one should be doing development on top of tarball.  Yeah, closing immediately after opening. :)

**Comment by ebraminio** [comment]
Thanks for sharing your thoughts :)

**Comment by ebraminio** [comment]
And agreed with your reasoning
