### ISSUE TITLE
No autoswap between a tone and a vowel in Thai in specific cases

### ISSUE THREAD

**Issue by ars18wrw** [harfbuzz/harfbuzz#1803]
I want to bring up a question about a specific problem with Thai script processing. I don't claim that harfbuzz works incorrectly: I just need any opinion on the issue described below.

I'm not a native Thai speaker and I haven't found any relevant information on the Web, but from my experience it seems that 
a)  if two successive diacritics appear in a Unicode string, the second one should be rendered on top of the first one
b) in a correct Thai word tones are always rendered above vowels. 

Look at the following Unicode sequence for example: _"\u0E0a\u0E31\u0E49"_. That's how it gets processed with harfbuzz (image1):
![image](https://user-images.githubusercontent.com/7279310/60326107-99bb3000-9991-11e9-91f8-b6a79a7df44e.png)
As you can see, the tone (U+0E49: THAI CHARACTER MAI THO) is under the vowel (U+0E31: THAI CHARACTER MAI HAN-AKAT) 
Now let's swap MAI THO and MAI HAN-AKAT and process the following Unicode sequence: _"\u0E0a\u0E49\u0E31"_. It's rendered as follows (image2): 
![image](https://user-images.githubusercontent.com/7279310/60326252-f585b900-9991-11e9-802a-8695b65c155e.png) . It's incorrect from the Thai perspective, but the a) point is respected.
The same results one can get via Chrome (e.g. harfbuzz, I believe) / MsWord / Sublime on Windows.

Now let's see how the same Unicode sequences are processed on Mac. I've done the following in Sublime / Pages: typed "\u0e0a", "\u0e49" and "\u0e31" successively. The result: when one types the last letter, the tool automatically swaps it with the previous one, so that one sees image1 on the screen rather than image2.
The autoswap affects only rendition: if one copies the content to some content-to-Unicode tool, one gets an unchanged Unicode sequece - "\u0E0a\u0E49\u0E31".

For the first sequence everything is as expected: the same as on Windows.

Do you have any ideas about this issue? Is it a harfbuzz bug and, if so, will it be fixed? Or is it just a nice anti-mistype Mac feature?

**Comment by ars18wrw** [comment]
It can be reproduced not only for the mentioned unicode sequence. For example, please try "\u0E16\u0E33\u0E49" (and \u0E16\u0E49\u0E33" respectively)

**Comment by behdad** [comment]
The question we typically ask is, what does Windows do...  If we are consistent with Windows, I think that's what we want to do.  I'm open to suggestions by those who know the script better though.

**Comment by dscorbett** [comment]
Windows renders them differently, which is a good thing since they are not canonically equivalent. The Mac behavior is unhelpfully disguising a typo.

**Comment by behdad** [comment]
Right.  Working as intended then.

**Comment by ars18wrw** [comment]
Thank you for an timeous response, guys!
