### ISSUE TITLE
Merge CFF's parse_bcd with parse_float

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1808]
Apparently we only have these pow 10^ https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-cff-interp-dict-common.hh#L140-L158 in HB_TINY but for building hb-subset in wasm https://github.com/harfbuzz/harfbuzzjs/issues/9 I have to define a real `(double, double) -> double` https://github.com/harfbuzz/harfbuzzjs/blob/master/libc/main.c#L19 (which only supports positive integer exponents) and replacing that seems results to some performance gain in regular harfbuzz builds also. WDYT? @blueshade7 

P.S.: Of course I don't want to bug the project about every libc thing as I didn't till now, this one however feels like an easy to tackle one with having cast on all of its uses, underneath calling a complicated function doesn't need to I believe.

**Comment by blueshade7** [comment]
`pow` is used to parse out BCD numbers occurring rarely (but NOT deprecated) in Dicts. Its performance (good or bad) must be negligible.

BTW, AFDKO implements BCD by calling libc `strtod` whose behavior is locale dependent ('.' v.s. ','). To workaround, the code has a bizarre recalculation loop until the value becomes stable. If you are curious search for strtod.

In HB I wrote the code from scratch to avoid that. BCD spec in CFF is a pain in my butt.

**Comment by ebraminio** [comment]
Thanks for the clarification, now I wonder can that be merged with [parse_float](https://github.com/harfbuzz/harfbuzz/blob/ccf1448238c91da3cba8370ee527229013f6d362/src/hb-common.cc#L827) which takes care of locale issue by using C locale with strtod_l.

Apparently it is test covered already https://coveralls.io/builds/24346969/source?filename=src%2Fhb-cff-interp-dict-common.hh#L97 which is great.

That means now I have to implement strtod which means more work in harfbuzzjs for me but I like that as that results in general size reduction of harfbuzz in other places I think.

**Comment by ebraminio** [comment]
>That means now I have to implement strtod which means more work in harfbuzzjs for me but I like that as that results in general size reduction of harfbuzz in other places I think.

If you don't see any downside to it, or, lets always your implementation if strod_l wasn't available? I think that would work great for both uses, size reduction in main uses and reliability when xlocale is not available.

**Comment by blueshade7** [comment]
Not sure what you are trying to achieve but are you saying to rewrite/repurpose this `parse_bcd` code as our custom impl of `strtod_l`? That's fine with me but it needs to be fully tested. Some code paths are not currently exercised as you see.

**Comment by ebraminio** [comment]
Great, thanks for the information

**Comment by ebraminio** [comment]
Doesn't worth the hassle apparently but will look more later

**Comment by ebraminio** [comment]
Is in progress in #1949
