### ISSUE TITLE
Add amalgamation source file

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1809]
Add hb.cc that will include all base .cc files (easy) then make it actually compile (more work).

**Comment by behdad** [comment]
This works now!

Compile time is ~10s to 20s.  I also see some measurable size improvement... Not jumping to conclusions just yet though.

Leaving open to 1. document in CONFIG.md, and 2. add bots that use it.

Note the resulting hb.cc doesn't add hb-ft.cc, hb-glib.cc, .. the integrations need to be added separately.

**Comment by behdad** [comment]
@drott @jfkthame FYI.  I know Firefox already tries this itself.  Might want to switch to this (when released).

**Comment by behdad** [comment]
cc @nona-google as well.

**Comment by ebraminio** [comment]
Niiiice

**Comment by drott** [comment]
Thanks, yes, in Chrome we call these "jumbo builds", and I think we have some tools in our .gn build files for this approach. But it's good if we can simplify our HarfBuzz build file. Are you testing both configurations on the CI bot, building the amalgamated and the regular files?

**Comment by behdad** [comment]
> Are you testing both configurations on the CI bot, building the amalgamated and the regular files?

Not yet, but that's the plan indeed.

**Comment by ebraminio** [comment]
We can always use harfbuzz.cc in cmake which has the test suite, that way we don't have to modify autotools development and bots and make this test covered, deferring more to after meson migration.

**Comment by ebraminio** [comment]
> Are you testing both configurations on the CI bot, building the amalgamated and the regular files?

As https://github.com/harfbuzz/harfbuzz/commit/9fea6b4dd41bfe2b85f788523162658a7ab9bd49 we now have harfbuzz.cc both build and test-suite checked in different cmake CI bots (including two Windows bots), you will get some build/link time performance and size benefits in Chrome as the result I'd guess but harfbuzz.cc doesn't include subset files so you should include them separately, hmmm, maybe we should add those also when some compile flag is set.

**Comment by ebraminio** [comment]
harfbuzz.cc is released so let's close this, yay!

**Comment by ebraminio** [comment]
Filed crbug.com/995090 @drott this is built with our cmake which is test covered also so no worry about correctness AFAICT.
