### ISSUE TITLE
Subset APIs are not documented

### ISSUE THREAD

**Issue by SimonSapin** [harfbuzz/harfbuzz#1816]
The `hb-subset` utility program is mentioned in the documentation: https://harfbuzz.github.io/utilities.html#utilities-command-line-hbsubset

The source code also has a whole series of C APIs for sub-setting, including:

https://github.com/harfbuzz/harfbuzz/blob/b240d701fd98efa59a7f772ff39654fc95b8fc8f/src/hb-subset.cc#L268-L277

… but none of it is documented on https://harfbuzz.github.io/api-index-full.html. Is this intentional?

**Comment by behdad** [comment]
Yes. The subsetter API is not stable yet and will change before it is. Hence no documentation yet and also why it's in a separate library currently.

**Comment by SimonSapin** [comment]
Alright, thanks. No need to keep this issue, open, I’ll watch the `NEWS` file.
