### ISSUE TITLE
Are clusters reversed based on script or direction?

### ISSUE THREAD

**Issue by SimonSapin** [harfbuzz/harfbuzz#1818]
https://harfbuzz.github.io/working-with-harfbuzz-clusters.html
>  For left-to-right scripts (LTR) and top-to-bottom scripts (TTB), HarfBuzz will preserve the monotonic property: client programs are guaranteed that monotonically increasing initial cluster values will be returned as monotonically increasing final cluster values.
>
> For right-to-left scripts (RTL) and bottom-to-top scripts (BTT), the directionality of the buffer itself is reversed for final output as a matter of design. Therefore, HarfBuzz inverts the monotonic property: client programs are guaranteed that monotonically increasing initial cluster values will be returned as monotonically decreasing final cluster values. 

The word “script” here seems to refer to `hb_buffer_set_script` and  `hb_script_t`, but the enumeration of LTR/TTB/RTL/BTT cases seems to refer to `hb_buffer_set_direction` and `hb_direction_t`.

Which is is? Based on what setting does Harfbuzz reverse clusters?

----

Drive-by, semi-related questions:

* Cluster values can be specified by the user in `hb_buffer_add`, but not in other `hb_buffer_add_*` functions. As far as I can tell these functions use `old_next - (const T *) text` as cluster values, indices in the text input counted in the corresponding UTF’s code units. Is that accurate?
  - This behavior may be worth documenting in the API reference for each functions.
  - If several add calls are made to the same buffer (for example because the input text is discontinuous in memory), is the only way to obtain monotonic cluster values across calls is to only use `hb_buffer_add` directly and set values explicitly?
* Are some combinations of script and direction nonsensical, for example `HB_SCRIPT_ARABIC` and `HB_DIRECTION_LTR`?
* Why is it useful to reverse clusters?
* Is the kind of reversal discussed here the same that `hb_buffer_reverse_clusters` (un)does?
* How is relative order of glyphs meaningful, as long as they end up at the same positions? (For example if advance of offset were replaced with absolute coordinates.) https://harfbuzz.github.io/reordering-in-levels-0-and-1.html discusses reordering as an explicit operation that shapers do.

**Comment by behdad** [comment]
> The word “script” here seems to refer to `hb_buffer_set_script` and `hb_script_t`, but the enumeration of LTR/TTB/RTL/BTT cases seems to refer to `hb_buffer_set_direction` and `hb_direction_t`.
> 
> Which is is? Based on what setting does Harfbuzz reverse clusters?

Good point.  The reference to script is wrong and should be removed.  This solely depends on the buffer direction.

> Drive-by, semi-related questions:
> 
> * Cluster values can be specified by the user in `hb_buffer_add`, but not in other `hb_buffer_add_*` functions. As far as I can tell these functions use `old_next - (const T *) text` as cluster values, indices in the text input counted in the corresponding UTF’s code units. Is that accurate?

Correct.

>   * This behavior may be worth documenting in the API reference for each functions.

Yes.

>   * If several add calls are made to the same buffer (for example because the input text is discontinuous in memory), is the only way to obtain monotonic cluster values across calls is to only use `hb_buffer_add` directly and set values explicitly?

No.  One can use `hb_buffer_get_glyph_infos` and modify the clusters.

> * Are some combinations of script and direction nonsensical, for example `HB_SCRIPT_ARABIC` and `HB_DIRECTION_LTR`?

No!  That is used to implement Unicode bidi override characters (U+202D/202E...).  Though in reality rarely used.

> * Why is it useful to reverse clusters?

That is used internally so we expose it.  I don't know of an external usecase.  I mean, short of, if you cared about drawing order to follow the script direction for example.

> * Is the kind of reversal discussed here the same that `hb_buffer_reverse_clusters` (un)does?

Yes.

> * How is relative order of glyphs meaningful, as long as they end up at the same positions? (For example if advance of offset were replaced with absolute coordinates.) https://harfbuzz.github.io/reordering-in-levels-0-and-1.html discusses reordering as an explicit operation that shapers do.

Becomes relevant when you consider cursor movement / text selection for example.

**Comment by khaledhosny** [comment]
> Are some combinations of script and direction nonsensical, for example HB_SCRIPT_ARABIC and HB_DIRECTION_LTR?
> No! That is used to implement Unicode bidi override characters (U+202D/202E...). Though in reality rarely used.
> 

Properly itemized text would have numbers (either European or Arabic-Indic) when inside Arabic text be classified with Arabic script while still LTR, so this particular case is rather common.
