### ISSUE TITLE
62e60322cb9e18b breaks Chrome build

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1821]
The Chrome build does not support putting extern "C" declarations inside the function, I get:

```
../../third_party/harfbuzz-ng/src/src/hb-unicode.cc:138:10: error: expected unqualified-id
  extern "C" hb_unicode_funcs_t *hb_icu_get_unicode_funcs ();
         ^
../../third_party/harfbuzz-ng/src/src/hb-unicode.cc:139:10: error: use of undeclared identifier 'hb_icu_get_unicode_funcs'; did you mean 'hb_ucd_get_unicode_funcs'?
  return hb_icu_get_unicode_funcs ();
         ^~~~~~~~~~~~~~~~~~~~~~~~
         hb_ucd_get_unicode_funcs

```

but when reverting 62e60322cb9e18b (which moved the extern declarations inside the function) it builds okay. 

I suggest to revert this change if it's not needed for [amalgam].

**Comment by behdad** [comment]
Yes, please revert.

I thought it might break something but didn't upset out bots.

Sorry about that.

**Comment by drott** [comment]
Okay, I'll revert this one - I prepared a roll with a local revert already, to see if we can get the rounding optimizations past the trybots. Thanks for the quick response.
