### ISSUE TITLE
graphite: Use harfbuzz font funcs

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#1822]
I've been working on pango features to make spaces and ignorables visible (spaces by rendering centered dot and various arrows, ignorables by drawing hex boxes), here: https://gitlab.gnome.org/GNOME/pango/merge_requests/69

Some questions that came up in this context:

It seems I have a choice of:
a) Having ignorables removed outright
b) Having ignorables replaced by a single, fixed invisible glyph
c) Having ignorables turned into whatever glyphs the font has

Or maybe it is a mix of b) and c), depending on what glyphs the font has?

What happens if I set an invisible glyph _and_ ask for ignorables to be preserved?
Will harfbuzz call get_nominal_glyph() or use the invisible glyph?
Are there other things than ignorables for which harfbuzz might use the invisible glyph ?

**Comment by matthiasclasen** [comment]
With respect to non-ignorables, it would be nice if there was a way to get harfbuzz to ignore the fonts charmap for line and paragraph separators, so I can handle them in my get_nominal_glyph func when I want to make them visible. Currently, I'm at the mercy of the font for this.

**Comment by khaledhosny** [comment]
> What happens if I set an invisible glyph _and_ ask for ignorables to be preserved?
> Will harfbuzz call get_nominal_glyph() or use the invisible glyph?

The former, since preserving them here means using whatever glyph the font has.

> Are there other things than ignorables for which harfbuzz might use the invisible glyph ?

Only for default-ignorables.

**Comment by khaledhosny** [comment]
> With respect to non-ignorables, it would be nice if there was a way to get harfbuzz to ignore the fonts charmap

Not sure what you mean by this. HarfBuzz does not read font `cmap` directly, it uses ` get_nominal_glyph` function for all characters (HarfBuzz's own `ot` font functions read the `cmap` table of course to provide a ` get_nominal_glyph` function, but if you are using different font function then these will be used).

**Comment by matthiasclasen** [comment]
when I shape a text containing 0x2028 (line separator) with the Gentium font, I don't see a get_nominal_glyph call for 2028, yet I end up with a 0xae8 glyph in the output.  How does harfbuzz come up with that glyph?

**Comment by khaledhosny** [comment]
Grrr, spent so much time debugging this and banging my head against the wall, until I rememberd that Gentium is a hybrid OpenType/Graphite font and when graphite support is enabled, HarfBuzz will give priority to the `graphite2` shaper for fonts with Graphite tables.

Graphite support uses libgraphite and it reads the `cmap` table on its own and bypasses HarfBuzz font functions. CC @mhosken if there is a way to make lingraphite use HarfBuzz font functions.

**Comment by matthiasclasen** [comment]
Ah, hmm. I can live with things not working for weird fonts.

Is graphite support something that is worth keeping around ?

**Comment by khaledhosny** [comment]
There are few fonts that work better/only with Graphite, so I think it is good to keep. Probably such exotic feature does not need to work with each font type.

Anyway, if lingraphite2 can  extended to use HarfBuzz font functions as much as possible instead of its own it would be better overall (currently it only supports providing a function for glyph advances, but nothing else).

**Comment by matthiasclasen** [comment]
Agreed. Thanks for spending the time to track this down!

**Comment by behdad** [comment]
This will be addressed (and only) when we integrate libgraphite into harfbuzz directly.
