### ISSUE TITLE
Handle missing space

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#1824]
In https://gitlab.gnome.org/GNOME/pango/merge_requests/67 we've made Pango handle 0x20 missing in the font by just rendering nothing of the right width. It would be nice if we didn't have to do that - harfbuzz could just use the invisible glyph we give it, and figure out a good width to use.

**Comment by khaledhosny** [comment]
Not sure what HarfBuzz would do here. For other space characters it uses that glyph for space with different width, but if there is no space glyph what would HarfBuzz output here, the `invisible` glyph? it defaults to space glyph. Also how would it determine the space width?

**Comment by matthiasclasen** [comment]
In Pango, I've use the average width of the hex digits, for lack of a better alternative.

**Comment by behdad** [comment]
Note that if font doesn't have space glyph and user has not set `invisible` glyph, we delete the default-ignorable glyphs.  So, in theory we can do the same for space.  It will mess up cursor positioning, but not worse than showing a notdef...

If `invisible` glyph is set, that can be used indeed.  For the width we can use a heuristic.

**Comment by matthiasclasen** [comment]
This is all fixed now
