### ISSUE TITLE
Prefer OT shaping over Graphite if possible?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1830]
I'm leaning towards preferring OpenType shaping over Graphite if font seems to support both.  Please discuss.

cc @khaledhosny @jfkthame @mhosken

**Comment by jfkthame** [comment]
I think I'd vote the other way.

The main reason a font developer would put both in a font would be if there's some complex shaping behavior that Graphite can handle, but OpenType can't (or at least, is unreasonably difficult/inefficient to implement in OT). I doubt there are designers who are putting Graphite tables into fonts alongside OT layout tables if the Graphite support doesn't offer *anything* beyond what the OT does.

For example, IIRC in the extended Latin/Cyrillic fonts from SIL (like Charis SIL), the Graphite tables provide superior behavior for the "double combining marks" U+035D..U+0362.

**Comment by typoman** [comment]
As a designer, I can see it the opposite way. Since Graphite offers more flexibility, I would add OpenType tables as a fallback to Graphite as it could result in an inferior appearance.

**Comment by behdad** [comment]
Okay yeah fine.  I understand that's the reality.

Should we do the same for AAT then?  Currently we have the outstanding problem that Muthu's fonts have broken OpenType layout tables and we prefer them over AAT.

**Comment by behdad** [comment]
[Long-term, we should either import graphite2 code into harfbuzz and integrate it correctly, reimplement graphite shaping in harfbuzz from scratch, or just drop it.  The fact that our graphite shaper doesn't use our font funcs or otherwise integrate with our other features always pops up as a surprise, as eg in https://github.com/harfbuzz/harfbuzz/issues/1822  But that's a separate discussion.]

**Comment by jfkthame** [comment]
> Should we do the same for AAT then? Currently we have the outstanding problem that Muthu's fonts have broken OpenType layout tables and we prefer them over AAT.

AAT is a harder choice, as it's less clear that what can be implemented using one technology is a superset of what the other can do. IMO, the AAT model is better/more flexible than OT for the font designer in some respects, but weak in others.

**Comment by matthiasclasen** [comment]
'integrate correctly' is key here. It is a problem if I can't rely on basic promises of the harfbuzz api because some font may have the wrong table in it.

**Comment by mhosken** [comment]
I would be quite happy for there to be a closer relationship between harfbuzz and the graphite engine even with a view to reimplementation. Having tried to see how OT could replace Graphite in capability, I am coming to the conclusion that it would be easier to just support Graphite (given its maturity) and give people the choice in implementation. Yes you don't get much of the nice tooling that people like Google have created, but generally Graphite gets used when all else fails or someone needs a capability that just isn't possible in OT. The process of getting everyone to agree to every change in OT would take forever given the glacial speed that current discussions have taken.
This does not preclude OT increasing its capability and making Graphite redundant in due course (much like, to be honest, AAT).
