### ISSUE TITLE
Add hb_gdi_font_create

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#1831]
We want to provide hb_font_t objects for fonts in pango, across platforms. The win32 font backend in pango is written in terms of gdi and LOGFONTW.  Currently, harfbuzz has
hb_directwrite_face_create(), and it seems that going from gdi objects to directwrite ones requires going through C++, so harfbuzz might be the best place for such a helper.

**Comment by behdad** [comment]
Ebrahim, can you please summarize different Windows APIs that are relevant here?  GDI, DWrite, etc?  So we can pick which are right to provide?

**Comment by ebraminio** [comment]
I guess DirectWrite is a separate issue which already solved. To be honest I am not that familiar with Windows APIs and just happened to write hb-directwrite for some reasons you know... And there is a GDI+, something I never had direct experience, which has a C++ API apparently I guess (?), just saying maybe not the right person to answer...

This is the code I started with https://www.mail-archive.com/harfbuzz@lists.freedesktop.org/msg06538.html it uses HDC, https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getfontdata apparently can be generated from HFONT.

_Maybe_ the right abstraction for us, the easiest which is already implemented #1832, is to work with a HFONT and create a HDC from it to feed it into GetFontData. LOGFONTW (or LOGFONTA) can easily converted to HFONT by the client using `CreateFontIndirectW` or its may obsolete counterpart `CreateFontIndirectA`, letting client to do deal with such oddities. We may be able to map the things we have from a LOGFONTW object provide to create a hb_font_t instead hb_face_t also, that feels not that clean to have but let me know by leaving reviews in the PR.

**Comment by khaledhosny** [comment]
The choice of API really depends on what Pango is using right now, if it is using GDI then it needs to create fonts from GDI fonts. DirectWrite is used mainly with DirectDraw and though it can be used with GDI it probably isn‘t worth the hassle unless Pango is dropping support for GDI altogether. DirectWrite provides a modern and more pleasant to use API.

**Comment by matthiasclasen** [comment]
The pango win32 fontmap is using EnumFontFamiliesExW to enumerate fonts, and then calls pango_win32_font_description_from_logfontw on each LOGFONTW. For the other way, it seems to mainly get an HFONT object and call SelectObject(hdc, font).

Maybe somebody should write a DirectWrite backend for pango. Not me, though...
