### ISSUE TITLE
"Halantness" tracking

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1836]
Splitting from https://github.com/MicrosoftDocs/typography-issues/issues/270

USE spec says: "If a font developer wants the reordering behavior to not be blocked by an explicit virama, they can substitute the virama for an alternate glyph during basic cluster formation so that USE treats the cluster as a continuous cluster without explicit virama."

Our `is_virama_use` function currently is:
```c++
static inline bool
is_halant_use (const hb_glyph_info_t &info)
{
  return (info.use_category() == USE_H || info.use_category() == USE_HVM) &&
         !_hb_glyph_info_ligated (&info);
}
```
Just changing that `_ligated` to `_substituted` might be all we need.

**Comment by dscorbett** [comment]
This is one of the questions I asked in MicrosoftDocs/typography-issues#104:
> “If a font developer wants the reordering behavior to not be blocked by an explicit virama, they can substitute the virama for an alternate glyph during basic cluster formation”. What counts as an alternate glyph? If a font uses a single substitution of a virama to itself, does the virama lose its explicitness?

They haven’t answered yet. Do you know what Windows does?

**Comment by behdad** [comment]
> They haven’t answered yet. Do you know what Windows does?

I don't.  I'm guessing that they compare the glyph id.

@NorbertLindenberg might know,.

**Comment by NorbertLindenberg** [comment]
No, I don't.

**Comment by behdad** [comment]
Do we just forget about this?  Can someone test what Windows does?  Do we change and see?

**Comment by dscorbett** [comment]
I had been hoping Microsoft would just answer my question, but I can make a test font and see what Windows does.

**Comment by behdad** [comment]
Well I don't know who can look into their code and comment.  @xadxura maybe.

**Comment by dscorbett** [comment]
It turns I don’t know how to test this on Windows. I made some test fonts, but on Windows Server 2019 Datacenter, both Notepad and Internet Explorer do vowel reordering but ignore the 'half' feature. As a sanity check, I tried Noto Sans Sharada, for which they reordered vowels but ignored 'akhn', so it is not a problem with my fonts. How can I test them properly?
