### ISSUE TITLE
subset use of hmtxvmtx's accelerator should be reconsidered

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1840]
so we can remove the hb_ot_metrics_get_position_internal need in hb-subset thus merge of `hb-ot-metrics-internal.cc` file with `hb-ot-metrics.cc`

**Comment by behdad** [comment]
As I said privately, move ascent/descent/linegap code from hmtx accelerator to a (new) hhea accelerator.  That decouples the dependency.

**Comment by behdad** [comment]
Or just remove the ascent'descent'linegap caching completely.  The ot-metrics code provides it.  we'll just call that directly from hb-ot-font.  Yeah, I'm happy with that even more!
