### ISSUE TITLE
Should ZWNJ prevents kerning?

### ISSUE THREAD

**Issue by kojiishi** [harfbuzz/harfbuzz#1841]
It looks like HB applies kerning across ZWNJ; i.e., for a string of "a"+ZWNJ+"b", HB applies the kerning pair for "a"+"b". Is this intentional?

I understand ZWNJ prevents ligatures. From that, ZWNJ preventing kerning too seems natural to me, but I'd appreciate experts' advice.

**Comment by behdad** [comment]
No it shouldn't.
