### ISSUE TITLE
Why and how hb_ot_metrics_get_variation has nothing to do with a hb_face_t?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1853]
Asking about the just added API https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-metrics.cc#L179 @behdad has instructed me to use `face->table.MVAR->get_var (metrics_tag, nullptr, 0);` but I honestly still don't get it and thought this might be worth to ask before the release, isn't the whole point of variation on these values is to have varying e.g. ascender/descender value based on values of variation axes values? How and why this API doesn't reflect that?

**Comment by behdad** [comment]
lol.  Yeah.  It **should** need the font!!!!  Let me check what you did :D.

**Comment by behdad** [comment]
because (drumroll) someone was lazy and decided to pass...
```
float 
hb_ot_metrics_get_variation (hb_face_t *face, hb_ot_metrics_t metrics_tag) 
{ 
  return face->table.MVAR->get_var (metrics_tag, nullptr, 0); 
} 
```
...null variations down to...
```
  float get_var (hb_tag_t tag,
                 const int *coords, unsigned int coord_count) const
  {
    const VariationValueRecord *record;
    record = (VariationValueRecord *) hb_bsearch (&tag, valuesZ.arrayZ,
                                                  valueRecordCount, valueRecordSize,
                                                  tag_compare);
    if (!record)
      return 0.;

    return (this+varStore).get_delta (record->varIdx, coords, coord_count);
  }
```

I wonder why one would do that... umm.

Maybe they just put the nullptr there to compile "for now"...

Maybe it was just a big commit and no one noticed in reviewing.

Donno.  Suspect.

**Comment by ebraminio** [comment]
Thanks!

One last thing, we haven't exposed `gasp` part as you said it is not that useful for clients of such API, just saying to see if you like reconsider that or not. Thanks!

![image](https://user-images.githubusercontent.com/833473/61638962-c07a3700-acaf-11e9-8c1a-2943fd1a58d4.png)
from https://docs.microsoft.com/en-us/typography/opentype/spec/mvar#value-tags

**Comment by behdad** [comment]
I know that.  Only makes sense if we want to expose gasp in API.  I'm against that until any time that we expose *anything* remotely relevant to rasterization and/or hinting.  It just doesn't make sense without.

It should be exposed in *that* API, since it's not a font metric, it changes the gasp function of the font at a certain size.
