### ISSUE TITLE
Deprecate or consistently apply _MAX_VALUE in hb_tag_t compatible enums  

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1860]
For sake of consistency [as the off tracker discussions] we should decide either deprecate all the _MAX_VALUE entries in enums having 4 ascii characters with HB_TAG as `_HB_SCRIPT_MAX_VALUE` , or, add those to the rest of enums that don't have, like `hb_buffer_serialize_format_t` and `hb_ot_metrics_t`.

**Comment by behdad** [comment]
Have to do some digging to figure out, but I *think* it's undefined to cast values to an enum that fall outside the range of its declared values.  If that is indeed the case, we do want to keep these max values on all enums that accept tags.

**Comment by behdad** [comment]
Without looking into details, let's operate under that assumption.
