### ISSUE TITLE
[ot-metrics] Define undocumented values for untouched hhea/OS2 independently from typometrics flag

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1866]
It has been requested by suggested by @khaledhosny that we expose untouched values of OS/2 in an API but since that is not covered by https://docs.microsoft.com/en-us/typography/opentype/spec/mvar#value-tags we like to go for undocumented private tags (starting with uppercase) for them instead. The [current suggestion](https://github.com/harfbuzz/harfbuzz/pull/1846#discussion_r307413202) by @behdad is `'Hasc' / 'Oasc' for hhead/os2 versions of ascender. Same for other two.` but maybe we don't actually want `hhea` ones explicitly or need to do that for linegap also, depending what clients would like we to have.

**Comment by behdad** [comment]
If adding we might as well add them all consistently instead of piecemeal.
