### ISSUE TITLE
[config] Add option to disable our undocumented private extensions

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1870]
Zawgyi, as well as ot-metrics private tags...

**Comment by ebraminio** [comment]
Maybe https://github.com/harfbuzz/harfbuzz/commit/a62f37d6fa412b799b7247b813f6e65a968e7645 as well

**Comment by behdad** [comment]
> Maybe [a62f37d](https://github.com/harfbuzz/harfbuzz/commit/a62f37d6fa412b799b7247b813f6e65a968e7645) as well

I feel slightly differently about that one.  Don't know how to put it into words.

**Comment by ebraminio** [comment]
Understandable

**Comment by behdad** [comment]
Wonder if we should call this `HB_NO_BACKDOORS`. :)))
