### ISSUE TITLE
Rename hb_ot_meta_t to hb_ot_meta_tag_t 

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1874]
From https://github.com/harfbuzz/harfbuzz/pull/1868#discussion_r307892541 @behdad says,

> Also, maybe better name for hb_ot_meta_t? We have hb_ot_name_id_t. hb_ot_meta_tag_t sounds better to me.

But that is also what done here https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-metrics.h#L76 so we should decide before the release

**Comment by ebraminio** [comment]
Of course I understand if we see them differently.

**Comment by behdad** [comment]
Humm, yeah I cannot make up my mind.  Let's see what @jfkthame @khaledhosny think.

**Comment by khaledhosny** [comment]
Tag sounds better since these are tags and not just regular ids.

**Comment by behdad** [comment]
> Tag sounds better since these are tags and not just regular ids.

Do we do same for ot-metrics?

**Comment by khaledhosny** [comment]
I think so.

**Comment by behdad** [comment]
Agree.

Okay, so this goes in, also ot-metrics and baseline both get _tag in their enum.

**Comment by behdad** [comment]
This is how I convinced myself: hb_script_t doesn't need `tag` in name because the enum value *is* the script.  Whereas a name-id enum value is not a name, and a baseline tag is not a baseline, and a metrics tag is not the metric and meta tag is not the metadata itself.  So I've found order in there. :)

**Comment by khaledhosny** [comment]
I have been thinking along these lines as well 😄

**Comment by ebraminio** [comment]
Makes to me now also with the given explanation :)
