### ISSUE TITLE
Expose post table’s italicAngle?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#1880]
`italicAngle` is one of the two `post` table fields not exposed by the new metrics API (together with `isFixedPitch`, but I don’t need it and I don’t think it qualifies as a metric).

**Comment by behdad** [comment]
`isFixedPitch` probably very unreliable so not useful...

Wonder where to best expose `italicAngle`.  Same w weight and width?  All three are also affected by variations.

**Comment by behdad** [comment]
wonder if those make more sense in `hb_font_extents_t`?

**Comment by khaledhosny** [comment]
Not sure either, putting them `hb_font_extents_t` has some merit to it and that struct has quite a few reserved fields.

Agreed about `isFixedPitch` it isn’t reliable for anything.

**Comment by ebraminio** [comment]
I think that is in the domain of hb-ot-style https://github.com/harfbuzz/harfbuzz/pull/1468

**Comment by behdad** [comment]
> I think this is in the domain of hb-ot-style #1468

Italic angle is used for caret rendering in many environments, making it a font metric than style.

**Comment by behdad** [comment]
Technically speaking, we should make our mark-positioning fallback code also respect italic angle.  But since that's fallback code, we don't.

**Comment by ebraminio** [comment]
> Italic angle is used for caret rendering in many environments, making it a font metric than style.

It is what exposed https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg and https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6fdsc.html so maybe some API to expose all using tags?

**Comment by behdad** [comment]
How to implement though? Using variations API, or metrics API?

**Comment by ebraminio** [comment]
I thought it could be exposed using ot-style #1468 (will remove its fdsc part making it much simpler) with the assumption if a `style` axis doesn't exist simulate its current/default value using whatever we got (post, OS2, etc) "killing two stones with one bird"!

**Comment by khaledhosny** [comment]
IMHO `italicAngle` belongs to font metrics, weight, width, etc. might belong to style information.

**Comment by ebraminio** [comment]
This metrics v. style, where does it come from originally? I say this honestly as I understand I lack related knowledge on the topic as my shorter background on typographic than yours so like to learn about your understanding.

I know OpenType isn't prefect, from what it currently suggests however, from variable fonts stand point, metrics are ones that 'mvar' can varies and styles are equivalent to variation axes, according to that we have to expose italic angle in style API anyway and we should consider it's value in STAT the most reliable one with fallback to others and post table anyway, and style values themselves are not hb_font_t oriented as scaling doesn't make sense on them and they are not result of variation but themselves cause variation on metrics so if we do them in hb_font_t we should return user config if is set, we shouldn't expose angle in integer as it is internally represent with fixed pointer arithmetic so metrics current API isn't suitable and changing one of hb_font_metrics to float may cause some ABI headache.

**Comment by behdad** [comment]
> This metrics v. style, where does it come from originally?

Style is relative to other faces in the same family.  Metrics expose aspects of the face itself.

**Comment by ebraminio** [comment]
Okay, this now makes sense to me considering we are talking about a hint for synthetic italic fonts not the angle the itself has now which that one is for `STAT` table IIUC. So maybe some `float hb_ot_metrics_synthetic_italic_angle (hb_face_t *face)`, or, some private tag for this and exposing it in hb_ot_metrics_get (but we should round its value I guess?), considering we like to see real italics generated by variation not the current synthetic situation, IIUC.

**Comment by ebraminio** [comment]
Or like what Khaled said, let me see if I can progress it

**Comment by behdad** [comment]
We're not talking about synthetic italic.  This is about perceived italic / oblique angle of the font eg for cursor / selection-box drawing.

**Comment by ebraminio** [comment]
Drafted something #1888, hope you find it useful.

**Comment by jfkthame** [comment]
> We're not talking about synthetic italic. This is about perceived italic / oblique angle of the font eg for cursor / selection-box drawing.

There are fields (caretSlopRise/caretSlopRun) in the hhea/vhea tables that are specifically aimed at this use case; perhaps clients should be using those?

**Comment by behdad** [comment]
> > 
> 
> There are fields (caretSlopRise/caretSlopRun) in the hhea/vhea tables that are specifically aimed at this use case; perhaps clients should be using those?

You are absolutely right.

**Comment by khaledhosny** [comment]
I still need italicAngle (not for cursor position, but to fill-in legacy TeX font metrics data), or can I calculate it from `caretSlopRise` and `caretSlopRun`?

**Comment by behdad** [comment]
If font has post table we want to expose italicAngle from there.  I think we should fallback to caret-slope internally if post table is missing.

**Comment by ebraminio** [comment]
Uploaded something related on #2378

**Comment by jfkthame** [comment]
> If font has post table we want to expose italicAngle from there. I think we should fallback to caret-slope internally if post table is missing.

'post' table should never be missing, it's one of the "required" tables according to both the Apple TrueType spec and the Microsoft OpenType spec. A font without 'post' is invalid.

So I'm not sure it's worth trying to compute something from caret rise/run as a fallback. Just expose the angle from the 'post' table as part of font metrics; nothing more for harfbuzz to do here.

**Comment by behdad** [comment]
> 'post' table should never be missing, it's one of the "required" tables according to both the Apple TrueType spec and the Microsoft OpenType spec. A font without 'post' is invalid.
> 
> So I'm not sure it's worth trying to compute something from caret rise/run as a fallback. Just expose the angle from the 'post' table as part of font metrics; nothing more for harfbuzz to do here.

Agreed.  Thanks.

**Comment by ebraminio** [comment]
Continuing from https://github.com/harfbuzz/harfbuzz/pull/1888#issuecomment-653935281 if a var font font has `slnt` the approach on #1888 will return wrong values, so in order to expose this "correctly" we need to store design var coords (move `hb_font_get_var_coords_design` out of experimental) and do something similar to `hb_style_get_value (font, HB_STYLE_TAG_SLANT)` (of course possibly as fourth field of hb_font_extents_t but wonder why not `hb_style_get_value` itself then) in order to expose this correctly, my 2¢

**Comment by ebraminio** [comment]
Now is possible with `hb_style_get_value`
