### ISSUE TITLE
Expose `bsln` somehow?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1881]
Maybe with a different API or inside the just introduced `BASE` API? I had some unmerged code about it here https://github.com/harfbuzz/harfbuzz/pull/1354 Although may can considered dead or deprecated `bsln` actually is very popular between Apple font and I didn't found lots of `BASE` fonts in Windows installation. Not insisting much, just to not forget.

**Comment by behdad** [comment]
I'm fine inside the same API.
