### ISSUE TITLE
Simulate ideographic baseline per spec?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1882]
I had some unmerged work here https://github.com/harfbuzz/harfbuzz/compare/master...ebraminio:baseline-base or maybe lets wait if a client want it from us

**Comment by KrasnayaPloshchad** [comment]
According to [CSS Writing Modes Level 3](https://drafts.csswg.org/css-writing-modes-3/#line-directions):
> When text-orientation: upright, the baseline is still vertical, and the vertical baseline in the font is used, or the vertical baseline is synthesized if the font does not provide.

So this is useful to help web browsers deal with character orientations even if a bad font is used on the web page.

**Comment by KrasnayaPloshchad** [comment]
Here are some fonts probably useful for test: https://ctan.org/tex-archive/fonts/arphic-ttf

**Comment by behdad** [comment]
Fixed now.
