### ISSUE TITLE
Expose BASE.get_min_max?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1884]
https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-layout-base-table.hh#L461 what name it should have, `hb_ot_layout_get_baseline_min_max`? Or does it worth to have it even, our base.ttf test font doesn't have it so I should find some real use first and I don't think lots of fonts have such information and no DirectWrite API apparently.

**Comment by ebraminio** [comment]
https://github.com/xiaohuaxiong/hello-world/blob/5fd1fdcf58192ae77c05d692cfe3735a0496dc80/WaterSimulate/OceanCS_Microsoft/include/dwrite_1.h#L524
this is actually what happens, hmm, a bit different from OT tags we are exposing, it is ok if we delay release of the API just to make sure if we figured it correctly as we have to define some tag for min and max if we don't want to switch to small numbers enums

**Comment by behdad** [comment]
Call it extents, not min_max.  Not sure if we need to expose since it's defined as ink extents not logical...

**Comment by matthiasclasen** [comment]
This is being discussed in https://github.com/harfbuzz/harfbuzz/issues/3290
