### ISSUE TITLE
getting optical margins out of the font

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#1891]
The OpenType spec describes lfdb and rfbd features that supposedly contain the information I need to implement optical margins: https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#lfbd

But it is very unclear to me how 

> Application interface: For GIDs found in the 'lfbd' coverage table, the application passes a GID to the table and gets back a new XPlacement and XAdvance value

translates to harfbuzz api.

**Comment by khaledhosny** [comment]
There is no API for this, nor there are any fonts using these features to the best of my knowledge. After thinking about this for a long time, I think using layout features for optical margins was misguided since applications need this information after layout and during line breaking (at least PDFTeX and its descendants, I don’t know any other implementation), and using OpenType features makes for an awkward API.

Apple’s [`opbd`](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6opbd.html) table might be a better bet, though I doubt there are many fonts using it (certainly not on Linux).

**Comment by jfkthame** [comment]
FWIW, a quick scan of fonts on my macOS machine finds just two that have `opbd` tables, and they're both fonts (Apple Chancery and Hoefler Text) with roots back in the TrueType GX days. I suspect the presence of the table is just a historical accident at this point, and am doubtful it is really maintained or used -- I think it was an idea that failed to gain any traction.

**Comment by khaledhosny** [comment]
That is probably two fonts more than fonts with `opbd`/`lfbd`/`rfbd` features. But what I’m trying to say if fonts were to support optical bounds now, the Apple one is the best of the two.

**Comment by matthiasclasen** [comment]
so how do other text rendering stacks to optical margins? heuristics?

**Comment by khaledhosny** [comment]
In PDFTeX/XeTeX you have to set the values manually for each glyph. In Scribus it is some hard-coded value for certain punctuation character (Scribus is ugly). No idea what InDesign does, and I don’t know any other applications that support optical margins.

**Comment by matthiasclasen** [comment]
I fonts don't have the data, i guess that kills it.

**Comment by jfkthame** [comment]
Something of a chicken and egg situation, perhaps. If no software implements this feature, there's no motivation for font designers to include the data (and no way for them to check the result of providing it). And if fonts don't include the data, there's no motivation for software to implement support for it.

**Comment by matthiasclasen** [comment]
True.

Getting back to the original question: How would a harfbuzz api for opbd look like?

**Comment by ebraminio** [comment]
The table looks very simple, maybe some 
`hb_bool_t hb_aat_has_optical_bounds (hb_face_t *face);` and `hb_bool_t hb_aat_get_optical_bound (hb_font_t *font, unsigned int glyph_id, hb_glyph_extents_t *extents);` (or face? or something like hb_glyph_extents_t but not itself?) can be useful for it (fan of using hb_aat_ namespace for AAT specific things, can we polyfill that with something in OT spec to make it hb_ot_ API?) This was at least my 2cent.

**Comment by matthiasclasen** [comment]
the fontforge docs talk about translating opbd and lfbd/rfbd into each other, so they should be equivalent on some level

**Comment by behdad** [comment]
They're definitely equivalentish.  Let's draft API.

**Comment by behdad** [comment]
(and support both.)

**Comment by ebraminio** [comment]
So it reminds me `_get_ligature_carets`, I guess it should have the same arguments, `(hb_font_t, hb_direction_t, hb_codepoint_t, hb_glyph_extents_t*)`

**Comment by ebraminio** [comment]
I've implemented the parsing of opbd table, do you have some sample font or some code to learn about GPOS lfbd rfbd opbd? Fonttools and fontforge didn't have much information as far as I could see

**Comment by behdad** [comment]
Yeah I don't think we nee separate aat API for it.  Just look into AAT tables as part of the ot-layout API for it.

**Comment by khaledhosny** [comment]
> I've implemented the parsing of opbd table, do you have some sample font or some code to learn about GPOS lfbd rfbd opbd? Fonttools and fontforge didn't have much information as far as I could see

Linux Libertine has it (though last time I checked the values were garbage). It is just regular GPOS SinglePos positioning (and because of that, the API would need to take a language and script to select the right lookups).

**Comment by behdad** [comment]
> (and because of that, the API would need to take a language and script to select the right lookups).

That is a bummer indeed.  But like 'size' and 'vert' features, I think we should ignore script/language and find the first feature in the feature vector that matches request...

**Comment by khaledhosny** [comment]
Like I said earlier, having it as a feature was awkward, but `size` is much more worse.

**Comment by behdad** [comment]
Closing in favor of https://github.com/harfbuzz/harfbuzz/issues/3458
