### ISSUE TITLE
static_assert on m68k-buildroot-linux-uclibc

### ISSUE THREAD

**Issue by bkuhls** [harfbuzz/harfbuzz#1901]
Building harfbuzz 2.5.3 fails:
```
hb-pool.hh: In instantiation of ‘struct hb_pool_t<hb_serialize_context_t::object_t>’:
hb-serialize.hh:460:23:   required from here
hb-pool.hh:80:3: error: static assertion failed
   static_assert (alignof (T) % sizeof (void *) == 0, "");
```
using this toolchain
```
$ /home/buildroot/br4/output/host/bin/m68k-linux-g++ -v
Target: m68k-buildroot-linux-uclibc
gcc version 7.4.0 (Buildroot 2019.05.1) 
```
The error was caught by the buildroot autobuilders:
http://autobuild.buildroot.net/?reason=harfbuzz-2.5.3
http://autobuild.buildroot.net/results/121/121891c54f1f6ba3661bacdeb054aab56129d3e5/build-end.log

**Comment by behdad** [comment]
I pushed a change.  Please test and confirm if it fixes.  Thanks.

**Comment by bkuhls** [comment]
Bug is solved, thx!
