### ISSUE TITLE
Should dist be enabled by dfault for all scripts?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#1907]
The Segoe UI Emoji font has a `dist` feature to fix some spacing issues (see https://github.com/khaledhosny/harftex/issues/12#issuecomment-521450494) and seems to expect it to be applied to emoji text.

HarfBuzz seems to enable it only in USE and a selected set of scripts, but Core Text seems to apply it to the emoji text is well, can’t test Uniscribe/DirectWrite at the moment.

Is `dist` now enabled for all scripts or does emoji gets shaped with USE now?

**Comment by dscorbett** [comment]
See also MicrosoftDocs/typography-issues#106.

**Comment by behdad** [comment]
I'm fine enabling it

**Comment by behdad** [comment]
But really. Segoe UI Emoji, why?

**Comment by khaledhosny** [comment]
> But really. Segoe UI Emoji, why?

My guess would be because Word disables `kern` by default (I’d have used `mark` though, since mark anchors are already involved).

**Comment by behdad** [comment]
Right.. so using dist as required kerning basically. Let's do.
