### ISSUE TITLE
Wrong Positions with latest version

### ISSUE THREAD

**Issue by Ali-Alzyoud** [harfbuzz/harfbuzz#1910]
Please check this repository to reproduce the issue :
https://github.com/AbedSrour/harfbuzz_textdrawing_sample/tree/master

# harfbuzz_textdrawing_sample
A sample project that uses Harfbuzz library to draw text on stdout.

## Issue glyphs drawn overlapped on latest version
when dig deep we found that with this code issue occure 

```
hb_font_t *font = hb_ft_font_create(face, NULL);
hb_font_t *hb_font = hb_font_create_sub_font(font);
hb_font_destroy(font);
```   
but with (no issue)
```
hb_font_t *hb_font = hb_ft_font_create(face, NULL);
```

**Example(T+e):**

```
#########
#########
#########
   +#
   +#
   +#
   +# ###
   +######
   +######
   +##+ +#+
   +##   ##
   +#+   +#
   +#    +#
   +#######
   +#######
   +#######
   +#
   +#
   +#+
   +##    +
   +##+  #+
   +######+
   +######
   +# ###
```

**Comment by behdad** [comment]
When you create a sub-font, it will be created with its own scale.  It would *not* inherit the scale from the original.  It defaults to font UPEM.  Your code expects it to have some other scale, hence the mismatch.  This has always been that way, so there's nothing about new versions that changed this.

**Comment by Ali-Alzyoud** [comment]
the difference between released and latest harfbuzz version founded exactly in this part:
 **glyphPos[i].x_advance**
Latest return smaller x_advance value

**Comment by Ali-Alzyoud** [comment]
both use same code (latest and release), but output is different

**Comment by behdad** [comment]
Then tell is exactly what your mean by latest and release.

**Comment by Ali-Alzyoud** [comment]
By latest I mean latest version on github              **Issue appear**
By release I mean version 2.5.3 (b14e413)            **No Issue**

**Comment by ApostolosB** [comment]
2.6.0 has this problem.

https://www.enlightenment.org/ss/display.php?image=e-5d5a710e60fe37.23926110.png

The T and e on the bottom of the screenshot (popup) overlap.

**Comment by jfkthame** [comment]
What font is involved?

**Comment by Ali-Alzyoud** [comment]
it appear in multiple fonts, in my demo I use DejaVuSans

**Comment by jfkthame** [comment]
Doesn't happen for me; combinations like "Te" look fine with DejaVu Sans using current harfbuzz from github master. What exact version of the font are you using?

**Comment by Ali-Alzyoud** [comment]
you need to use small fontsize,  also you need to use font this way
```
hb_font_t *font = hb_ft_font_create(face, NULL);
hb_font_t *hb_font = hb_font_create_sub_font(font);
hb_font_destroy(font);
```

You can see it in this demo:
https://github.com/AbedSrour/harfbuzz_textdrawing_sample/tree/master

**Comment by behdad** [comment]
I correct myself: sub_font's inherit parent font's scale.  Anyway, I don't expect this change of behavior.  Someone needs to bisect.

**Comment by Ali-Alzyoud** [comment]
f18ea1dd3a9961661a383b2966de57ea68a267e7

**Comment by Ali-Alzyoud** [comment]
Issue founded since this commit

**Comment by behdad** [comment]
> Issue founded since this commit

Thanks for tracking that down.  I see what the problem is.  Fixing soon.
