### ISSUE TITLE
Implementation for Perl?

### ISSUE THREAD

**Issue by PhilterPaper** [harfbuzz/harfbuzz#1913]
(This was originally sent to the mailing list, but apparently disappeared. Per your suggestion, I'll put it on GitHub)

I support a Perl library, PDF::Builder, which creates PDFs using OTF and TTF fonts. Currently it can only handle left-to-right simple scripts, and not even ligatures, alternate representations, etc., much less bidirectional or complex scripts such as Arabic and Indic-family writing (e.g., Farsi, Devanagari, Khmer). Anyway, it sounds like HarfBuzz would do what I need: given a list of Unicode characters, select the glyphs, substitute and rearrange as necessary, and provide the final list of character (glyph) IDs with any positioning and size changes needed. I would take care of the rendering (putting it into a PDF file). Help with word break-points, length of text in points, etc. (for paragraph shaping) would be great. Bonus points for simple scripts (Latin, etc.) using a font's ligatures, suppressing selected ligatures, selection of alternate forms and swashes, etc. Is my understanding correct that the current HarfBuzz can also work with TTF files?

I looked at using Pango, but (besides loading a lot of rendering overhead that I don't need) it requires a lot of manual installation work to build GTK+ and other libraries, before its prereqs can even be installed by the 'cpan' tool (that's what Strawberry Perl calls its tool to build and install CPAN module packages). I need something that can be completely handled by 'cpan', and on ordinary Windows platforms (among others), or potential users will not be interested. 'cpan' can compile and link C/C++ code (gcc and g++ compilers), so long as it's reasonably platform-agnostic. I'm hoping that it would be just a matter of writing a thin wrapper around the HarfBuzz code to provide an interface to Perl. If it would simplify matters, Perl (CPAN) has a Font::TTF library that reads in a TTF or OTF font and loads the internal tables (GSUB, GPOS, etc.) into Perl structures ("hashes"). I don't know yet how to get C code to read a Perl hash. At worst, I would have to read in a second copy of the font file in some format usable for HarfBuzz. There _is_ a Font::FreeType library that may be usable by HarfBuzz. Since HarfBuzz libraries (.dll, .a, etc.) seem to not be standard equipment on all Operating Systems, it is not suitable to simply put a wrapper around a .dll or .a file that is presumed to be created elsewhere.

So, I've been looking for a Perl-compatible installation of HarfBuzz that could be built on any Perl platform by 'cpan', but haven't found anything. I see a few references to Perl on the mailing list, but these appear to be tools that happen to be Perl. HarfBuzz is big and complex enough that I really don't want to attempt to translate it into pure Perl, unless most of it is reading the file and loading up various data structures, in which case I would just use Font::TTF for that part of it. A pure Perl copy would likely be slower than C/C++, and I would have to scramble to keep up with HarfBuzz updates. A C/C++ version would be easier -- I would just copy over the source code after an update, test it, and release a new version on CPAN.

Does anyone have any experience in this area, or know of anyone who's already done this work? PDF::Builder is free, so I would prefer not to require someone to buy a library in order to handle more than very simple scripts. I don't see anything on CPAN or on GitHub, and Google hasn't turned up anything promising. Thanks much for any advice or pointers on this! My platform is Strawberry Perl 5.26 on Windows 10, but whatever it is has to work on a wide range of Perls and platforms. I just want to avoid re-inventing the wheel if someone has already done this! Python can not be assumed, so some test tools and examples might have to be rewritten in Perl. Tools like automake can not be assumed, so I may have to rewrite the Makefile. My next step will be to see if I can at least compile and link the sources, perhaps with a small test driver.

**Comment by ebraminio** [comment]
> Is my understanding correct that the current HarfBuzz can also work with TTF files?

Yes.

I think starting from harfbuzz won't be that easy and good for your work, have a look at https://github.com/HOST-Oman/libraqm that should be easy to use, see https://github.com/HOST-Oman/libraqm/blob/master/src/raqm.c#L58-L135

**Comment by behdad** [comment]
What Ebrahim said.  Proper text layout is a lot of work.  All the ingredients exist and libraqm is a lightweight way to pull them together.  Definitely don't even think about reimplementing everything in Perl...

**Comment by behdad** [comment]
What Ebrahim said.  Proper text layout is a lot of work.  All the ingredients exist and libraqm is a lightweight way to pull them together.  Definitely don't even think about reimplementing everything in Perl...

> Perl (CPAN) has a Font::TTF library that reads in a TTF or OTF font and loads the internal tables (GSUB, GPOS, etc.) into Perl structures ("hashes").

This is not useful to HarfBuzz.  Just giving HarfBuzz the binary font blob is enough.

**Comment by PhilterPaper** [comment]
Thanks for the pointer to `libraqm`. I'll keep it in mind in case I get stuck on HarfBuzz. It sounds like neither it nor HarfBuzz itself has been ported to the Perl world, so either way I've got a lot of work ahead of me. Starting from the C and C++ code, I'll have to see if I can successfully compile and link the unaltered sources, using the tools available to anyone installing from CPAN's distribution (gcc, g++, make, a handful of Linux utilities, and limited bash). automake is not available by default, although it appears that it may be possible to build it (prereq `Alien::Build` and `Alien::automake`?). As I said before, I can't count on any of these libraries being already available on any given system. I can consider manual installations of libraries and products _if_ it's something that can be close to a "one button" operation (especially on Windows). I don't think Perl users will be interested if it's a long and involved process to install on their system.

If I can get that far, the next step is a wrapper to make the Perl interface to whatever Harfbuzz or libraqm code has been compiled. Then I can package it all up into a standard Perl module with installation tests, documentation, some utilities, etc. translated from the current HarfBuzz package into Perl (no Python, no native binaries).

If HarfBuzz only needs an unprocessed binary blob from FreeType, that should be easy enough to write in Perl or C, bypassing FreeType. Is reading in the blob all FreeType is needed for, at least for the core function? There do appear to be a lot of `FT_*` references in the code, so I'm guessing that FreeType is heavily used. _Building.html_ suggests that Cairo can be omitted (not used by core). How about GLib? It sounds likes it's optional. HarfBuzz, FreeType, Cairo, and GLib libraries are not normally found on Windows systems, and I don't want to exclude my product from that large market. I also don't want to bloat the Perl module with lots of unneeded libraries and stuff my code will never use.

I will monitor this thread for any clarifications or suggestions that someone may care to give, and will let you know how the HarfBuzz build attempt turns out. Thanks much!

**Comment by matthiasclasen** [comment]
just for the record, you don't need to build GTK if you are just interested in Pango

**Comment by PhilterPaper** [comment]
Apparently, for the CPAN installable Perl module, Pango's build was set up so that GTK+ and Cairo libraries are required to be installed already (outside of Perl). I don't know if it's possible to get around this and have Perl's installer (`cpan` tool) build it from sources, without having to do a lot of manual work on a variety of platforms. If I'm going to do that, I might as well try HarfBuzz (and FreeType) direct build/install first.

All I'm looking for is a library to accept a TTF/OTF font, font size, and string of Unicode characters; and return me a list of glyph IDs and positioning (and size adjustment, if necessary) to use. I don't need anything fancy, and I don't need any rendering. It has to be callable from Perl, and preferably can build and install through the CPAN module installer (I'm going to try to work out this part of it).

**Comment by behdad** [comment]
You can use HarfBuzz without any dependency whatsoever.  You can also compile the single-file harfbuzz.cc if you wish.

If you go with libraqm (which I highly recommend you do), you need FriBidi and FreeType as well.  Anyway, packaging and building those on Windows is not something we can help much with.  They all build on Windows fine.  The details are for you to figure out.

**Comment by ebraminio** [comment]
If Perl could use webassembly wasm files, you could just use this brand new raqm port (harfbuzz, fribidi but minus freetype in this port) to webassembly https://harfbuzz.github.io/harfbuzzjs/raqm/raqm.html 87b zipped, freetype and  dependency outside of it, apparently just no one has went for creating wasm interpreter in Perl worlds, unlike PHP https://github.com/wasmerio/php-ext-wasm and native JS support.

**Comment by PhilterPaper** [comment]
> You can use HarfBuzz without any dependency whatsoever.

I see a lot of "FT" macros and function names in the source, including FT_FREETYPE_H, but I don't see them defined locally. Does HarfBuzz assume that FreeType source is present?

I also see `*.rl` files, but it appears that the corresponding `*.h` files have already been generated. I'm not familiar with the use of Automake (Makefile.am), so I'm not sure if these `*.in` files are input or output (anyway, they don't appear to be supplied). At any rate, that's another tool to be installed. There are `*.py` files in the Make process, so Python will have to be installed, and `*.sh` files, so something like _mingw_ is needed (I have it already with Git). This is getting rather complicated to build -- is there a list someplace of what prerequisite libraries need to be installed first, and what tools will be needed to build (either a minimal HarfBuzz install, or the full package)? There seem to be more and more things needed as I dig deeper. I think that package authors working on a loaded Linux box tend to forget that someone will want to build this thing on a plain Windoze box. If I can preprocess your source to the point of plain C/C++ input (`*.xs` files?), and an ordinary Makefile, this could be feasible as a Perl package, but otherwise I'm not confident.

**Comment by behdad** [comment]
If you won't listen to what we say, we cannot help you.  I'll repeat, with emphasis:

You **can** use HarfBuzz without any dependency whatsoever.

You can also compile the **single-file** harfbuzz.cc if you wish.

**Comment by PhilterPaper** [comment]
Just to bring you up to date, as Johan mentioned, he created a Perl build/install module "HarfBuzz::Shaper" that builds (if necessary) and uses the various HarfBuzz-related libraries. He is looking for help (over on sciurius/perl-HarfBuzz-Shaper/issues/2) to create an Alien::HarfBuzz package on CPAN, which would build (if necessary) the libraries from the official source. Then he would not have to maintain a copy of the HarfBuzz source.

I have taken HarfBuzz::Shaper and added support to [PDF::Builder](https://github.com/PhilterPaper/Perl-PDF-Builder) to create PDF documents using a wide range of simple and complex scripts. Sample: [HarfBuzz_example.pdf](https://github.com/harfbuzz/harfbuzz/files/4533581/HarfBuzz_example.pdf)

Thanks much for creating this useful library!
