### ISSUE TITLE
Expose more data through the Harfbuzz API 

### ISSUE THREAD

**Issue by pedronavf** [harfbuzz/harfbuzz#1917]
Harfbuzz is evolving into something more than a shaping library: math support was added, work is being done on a subsetter, there are plans to do rasterizing in the future, etc.

As all this new work is being done, wouldn't it make sense to export some of the OpenType functionality so libraries can be developed that extend Harfbuzz and/or take advantange of its robust OT parsers without having to be integrated into the main Harfbuzz codebase (like the subsetter, for example)?

We can think of several use cases:

### Font functions inheritance
The OpenType font functions are essential for an application, and they evolve with Harfbuzz. As client applications might have special needs that are not served by the default functions, could a client inherit and extend them without having to fork them?

In our application we want to override some font tables (for example tell harfbuzz that a character is present when it might not be in the font file that harfbuzz is reading), or customize the metrics (we might be transforming the glyph outline and want to tweak the metrics).

The OpenType font functions use many internal headers and, as such, can't be easily forked and integrated into an application. When you do, you can't easily upgrade to new versions of Harfbuzz. Ideally, the OpenType font functions would be callable from outside Harfbuzz so users could install their own functions, call harfbuzz's and tweak the result.

As an example, if we embolden a font we want to increase the x_advance by the emboldening factor, from our `hb_myfunction_get_glyph_h_advance` function we could call `hb_ot_get_glyph_h_advance` to get the h_advance as read from the font, add our custom advance and return that value to harfbuzz.

### OpenType table functions
In some cases it's useful to get 'raw' access to the Open Type table. While harfbuzz-style APIs could be added, of course, having in some cases access to the table could let clients provide an stop-gap solution until a formal API is introduced in Harfbuzz, or if the use is too specialized to warrant a public API. 

In our software we've needed to:

- Do a single call to get many values at once (like fetching everything from the OS/2 table). This, of course, could be accomplished by having an `hb_os2_get_values` or similar.

- Iterate trhough a CMAP to get all available glyphs in a font

- Get the glyph index of a codepoint (cmap table), its bounding box (glypf) or a font's maximum advance if available (hhea).

Considering that harfbuzz has already that information parsed and ready, it might make sense to just make it available.

### Additional thoughts
- Move the OpenType parser to its own library (hb_opentype) that can be used by other applications and Harfbuzz itself?

**Comment by ebraminio** [comment]
Hey there.

> As all this new work is being done, wouldn't it make sense to export some of the OpenType functionality so libraries can be developed that extend Harfbuzz and/or take advantange of its robust OT parsers without having to be integrated into the main Harfbuzz codebase (like the subsetter, for example)?

I think not. The advantage of our parser is using C++ features, if we want to expose the parser we should either limit ourselves to C features, or, expose C++ API which both doesn't feel great.

However Apple has one nice to get inspiration, apparently it can expose known requested table not only with binary data but using a dynamic object, say json like key-value object, I don't remember the details but to have something like that painlessly I think best would be waiting for C++ static reflection https://twitter.com/Cor3ntin/status/1127210941718962177 (apparently C++23?)? Then we can have fonttools like serializer, preferably in json format and we can expose that in our C APIs also.

So, let's not rush for such.

> The OpenType font functions are essential for an application, and they evolve with Harfbuzz. As client applications might have special needs that are not served by the default functions, could a client inherit and extend them without having to fork them?

I think you can do that using private APIs just right now.

> or customize the metrics (we might be transforming the glyph outline and want to tweak the metrics).

I guess you can already do such by overriding HB's glyph_h_extents callback and calling back the original functions and tweaking their results?

> Do a single call to get many values at once (like fetching everything from the OS/2 table). This, of course, could be accomplished by having an hb_os2_get_values or similar.

We might provide such eventually using the explained mechanism but wondering what is your use, we have developed ot-metrics API and are developing ot-style so you won't need to read whole OS/2 table by we exposing many different details of the fonts from different places with fallback and such. OS/2 isn't required table in AAT fonts, many of macOS fonts do have it but we like to provide abstraction so upper won't need to care about such details.

See #1337

> Iterate trhough a CMAP to get all available glyphs in a font

This makes sense of course specially for a font managing system.

> Get the glyph index of a codepoint (cmap table), its bounding box (glypf) or a font's maximum advance if available (hhea).

Don't we have the first right now (honestly not confident, I should check it)? We have the second also, also its CFF/CFF2/sbix/CBDT in one API. We have the third one also using ot-metrics API.

> Move the OpenType parser to its own library (hb_opentype) that can be used by other applications and Harfbuzz itself?

Sounds great, my 2c however, lets not expose that, let's just imaging if we switch someday to Rust we won't have components that are very C++ specific. Instead, lets see what clients need and expose only those. Thanks

**Comment by pedronavf** [comment]
Hi @ebraminio !

> I think not. The advantage of our parser is using C++ features, if we want to expose the parser we should either limit ourselves to C features, or, expose C++ API which both doesn't feel great.

> So, let's not rush for such.

Sure.

>> The OpenType font functions are essential for an application, and they evolve with Harfbuzz. As client applications might have special needs that are not served by the default functions, could a client inherit and extend them without having to fork them?

> I think you can do that using private APIs just right now.

It is what we are doing, yes. That means that we need to make harfbuzz part of our code, and we want to avoid that

>> or customize the metrics (we might be transforming the glyph outline and want to tweak the metrics).

> I guess you can already do such by overriding HB's glyph_h_extents callback and calling back the original functions and tweaking their results?

That is exactly what we want to do! The problem is that the functions in hb-ot-font are not public, only `hb_ot_font_set_funcs` is exposed. If there was something like `hb_ot_font_get_funcs` (similar to `hb_icu_get_unicode_funcs`) then we could get the function pointers, install our own font functions and then call harfbuzz's functions.

>We might provide such eventually using the explained mechanism but wondering what is your use, we have developed ot-metrics API and are developing ot-style so you won't need to read whole OS/2 table by we exposing many different details of the fonts from different places with fallback and such. OS/2 isn't required table in AAT fonts, many of macOS fonts do have it but we like to provide abstraction so upper level libraries won't need to care about such details.

We wanted to get the super/subscript/strikeout/underline positions from the os/2 and post tables. As all the information is there we figured that a simple function call would be enough, like our own implementation does.

ot-metrics was introduced just 8 days ago 😄  but it's a welcome addition, we'll begin using it. Our main problem is that we will require all integrators of our software to move to the very latest version of Harfbuzz, which might a problem depending on where they are on their device's firmware release cycle.

>>Iterate trhough a CMAP to get all available glyphs in a font

>This makes sense of course specially for a font managing system.

Our application manages its own fonts, so we need to know the glyph coverage for each font we load. Right now we are doing that at build time

>>Get the glyph index of a codepoint (cmap table), its bounding box (glypf) or a font's maximum advance if available (hhea).

>Don't we have the first right now (honestly not confident, I should check it)? We have the second also, also its CFF/CFF2/sbix/CBDT in one API. We have the third one also using ot-metrics API.

Are the first and second available through public APIs?

> Sounds great, my 2c however, lets not expose that, let's just imagine if we switch someday to Rust we won't have components that are very C++ specific. Instead, lets see what clients need and expose only those. Thanks

Sure.

**Comment by ebraminio** [comment]
> That is exactly what we want to do! The problem is that the functions in hb-ot-font are not public, only hb_ot_font_set_funcs is exposed. If there was something like hb_ot_font_get_funcs (similar to hb_icu_get_unicode_funcs) then we could get the function pointers, install our own font functions and then call harfbuzz's functions.

Correct. Maybe you should have two hb_font_t, one with ot-funcs so you can use its default callbacks, the other, with your own callbacks, or maybe, we should just expose those. @behdad

> We wanted to get the super/subscript/strikeout/underline positions from the os/2 and post tables. As all the information is there we figured that a simple function call would be enough, like our own implementation does.

Great that we've provided all of them in ot-metrics API, plus having them variation aware, please check if it works correctly there.

>>> Iterate trhough a CMAP to get all available glyphs in a font

>> This makes sense of course specially for a font managing system.

> Our application manages its own fonts, so we need to know the glyph coverage for each font we load. Right now we are doing that at build time

Any of your such applications should be supported I believe. In this case, isn't `hb_face_collect_unicodes ()` enough for it? If not just let us know, we just love to facilitate your work so you won't need to do any opentype parsing.

>>> Get the glyph index of a codepoint (cmap table), its bounding box (glypf) or a font's maximum advance if available (hhea).

>> Don't we have the first right now (honestly not confident, I should check it)? We have the second also, also its CFF/CFF2/sbix/CBDT in one API. We have the third one also using ot-metrics API.

> Are the first and second available through public APIs?

You can have access to `hb_font_get_nominal_glyph` and `hb_font_get_glyph_extents`... maybe again using that two `hb_font_t` trick, or maybe we should do something about it.

Thanks!

**Comment by pedronavf** [comment]
Thanks @ebraminio and @khaledhosny! We missed the fact the the hb_font functions can be called directly from outside. Now everything makes sense 😄 

>>* Iterate trhough a CMAP to get all available glyphs in a font

>I guess you mean all supported characters, there hb_face_follect_unicodes() for that.

No, I mean all glyphs. For some fonts we prerender all glyphs to a texture and create an atlas, we need the actual glyph indices so we can render harfbuzz buffers.

But regardless of this particular use case, I can use it to illustrate my general point: if we wanted to get all unicode characters we need to call `hb_face_collect_unicodes()` which does it work and returns a data structure which then we need to iterate ourselves to add the characters to our own data structure.

If the table was exported directly we could read it ourselves and add characters as we go, but I get that harfbuzz's direction is to provide APis to fetch the needed data. For cases like this, maybe there could be APIs that return an iterator?

>>or a font's maximum advance if available (hhea).

>what this would be useful for?

In our system we can synthesize a non-proportional font from a proportional font by using the max advance and centering the glyphs as we render them.

In any case, shouldn't the metrics API make all possible metrics accesible? (We can happily submit a PR for that). If that's not desired, our only option is to parse the hhea table ourselves and that brings me to the initial question, could we somehow use harfbuzz's hhea parser or do we to write our own code?

But, this has been very helpful. hb-font.h has been there with the functionality we required all these time, we just never looked in the right place!

**Comment by behdad** [comment]
> Harfbuzz is evolving into something more than a shaping library: math support was added, work is being done on a subsetter, there are plans to do rasterizing in the future, etc.

Correct.

> As all this new work is being done, wouldn't it make sense to export some of the OpenType functionality

We like to expose functionality.  But unlike libraries like FreeType, which export everything and then some, we like to hide complexity and expose opinionated user-friendly API.  So, things like handling bad input, common mistakes, etc, should be worked out inside HarfBuzz.

> so libraries can be developed that extend Harfbuzz and/or take advantange of its robust OT parsers without having to be integrated into the main Harfbuzz codebase (like the subsetter, for example)?

The parsing infrastructure is in C++.  We can export that sure, but we like to be able to evolve it freely, so we don't want to be constrained by any compatibility promises.  That said, clients that embed HarfBuzz can always access the private headers if they want to.  We don't encourage that, but if it makes sense for your use-case, feel free to do.

> We can think of several use cases:
> 
> ### Font functions inheritance
> The OpenType font functions are essential for an application, and they evolve with Harfbuzz. As client applications might have special needs that are not served by the default functions, could a client inherit and extend them without having to fork them?
> 
> In our application we want to override some font tables (for example tell harfbuzz that a character is present when it might not be in the font file that harfbuzz is reading), or customize the metrics (we might be transforming the glyph outline and want to tweak the metrics).
> 
> The OpenType font functions use many internal headers and, as such, can't be easily forked and integrated into an application. When you do, you can't easily upgrade to new versions of Harfbuzz. Ideally, the OpenType font functions would be callable from outside Harfbuzz so users could install their own functions, call harfbuzz's and tweak the result.
> 
> As an example, if we embolden a font we want to increase the x_advance by the emboldening factor, from our `hb_myfunction_get_glyph_h_advance` function we could call `hb_ot_get_glyph_h_advance` to get the h_advance as read from the font, add our custom advance and return that value to harfbuzz.

As was pointed out by Khaled, that's certainly a legitimate and possible use-case.  All of Chrome, Android, and Pango use hb-ot-font that way, by creating sub-font and overriding just some of the callbacks.  In those callbacks, you can call the parent font's callbacks using public API.  To get to the parent font, you can either call `hb_font_get_parent` every time, or faster, embed the parent pointer in the `font_data` that is passed down to the callbacks.

> ### OpenType table functions
> In some cases it's useful to get 'raw' access to the Open Type table. While harfbuzz-style APIs could be added, of course, having in some cases access to the table could let clients provide an stop-gap solution until a formal API is introduced in Harfbuzz, or if the use is too specialized to warrant a public API.

That's one thing we haven't been wanting to do.  But as I said, you can use private headers if that's *really* what you want.  There's no guarantees other than what the code is though in that case.

> In our software we've needed to:
> 
> * Do a single call to get many values at once (like fetching everything from the OS/2 table). This, of course, could be accomplished by having an `hb_os2_get_values` or similar.

Why does the "single call" matter?  There's hb-ot-metrics API for most of the values you *should* need.

> * Iterate trhough a CMAP to get all available glyphs in a font

People pointed to the collect_unicodes API.  You say you want the glyphs.  That's `hb_face_get_glyph_count`.  A font's glyphs are by definition from 0 to `glyph_count - 1`.

> * Get the glyph index of a codepoint (cmap table), its bounding box (glypf)

Various `hb_font_get_...` API.

> or a font's maximum advance if available (hhea).

Again, why do you need that?  Okay I guess for atlasing.  Problem is, that value is quite frequently unreliable.  Sure we can expose it in hb-ot-metrics if we decide it's reliable and useful.  Or you can just fetch every glyph's and find maximum yourself.

> Considering that harfbuzz has already that information parsed and ready, it might make sense to just make it available.

> ### Additional thoughts
> * Move the OpenType parser to its own library (hb_opentype) that can be used by other applications and Harfbuzz itself?

As I said at the beginning, we want to be able to evolve that code over time, as we do constantly...  Plus, we prefer to design API to expose what's actually useful, instead of letting clients shoot themselves in the foot by giving them raw table access.  Believe me, I've seen FreeType clients for 20 years... I know what problems I'm trying to avoid. :dagger:

**Comment by khaledhosny** [comment]
> Thanks @ebraminio and @khaledhosny! We missed the fact the the hb_font functions can be called directly from outside. Now everything makes sense 😄
> 
> > > * Iterate trhough a CMAP to get all available glyphs in a font
> 
> > I guess you mean all supported characters, there hb_face_follect_unicodes() for that.
> 
> No, I mean all glyphs. For some fonts we prerender all glyphs to a texture and create an atlas, we need the actual glyph indices so we can render harfbuzz buffers.

Then there is`hb_face_get_glyph_count()`.

> But regardless of this particular use case, I can use it to illustrate my general point: if we wanted to get all unicode characters we need to call `hb_face_collect_unicodes()` which does it work and returns a data structure which then we need to iterate ourselves to add the characters to our own data structure.
> 
> If the table was exported directly we could read it ourselves and add characters as we go, but I get that harfbuzz's direction is to provide APis to fetch the needed data. For cases like this, maybe there could be APIs that return an iterator?

> > > or a font's maximum advance if available (hhea).
> 
> > what this would be useful for?
> 
> In our system we can synthesize a non-proportional font from a proportional font by using the max advance and centering the glyphs as we render them.

This is going to render badly in many non-Latin fonts. For example, in Amiri 11435, over 10 times the average glyph width in the same font.

**Comment by behdad** [comment]
> maybe there could be APIs that return an iterator?

collect_unicodes returns the Unicodes into a set, which you can iterate.  We can add another one that returns the unicode-to-glyph mapping in a `hb_map_t`.  We should also provide `hb_map_t` iterator API.

> > > or a font's maximum advance if available (hhea).
> 
> > what this would be useful for?
> 
> In our system we can synthesize a non-proportional font from a proportional font by using the max advance and centering the glyphs as we render them.

That's a really sketchy and bad idea honestly.

> In any case, shouldn't the metrics API make all possible metrics accesible? (We can happily submit a PR for that). If that's not desired, our only option is to parse the hhea table ourselves and that brings me to the initial question, could we somehow use harfbuzz's hhea parser or do we to write our own code?

We can add more metrics if you list which you need.  The reason those are not available in `mvar` table is because the OpenType industry stakeholders all agree that things like max-advance are not useful for good reasons, as well as very hard / impossible to handle correctly in variable fonts.

> But, this has been very helpful. hb-font.h has been there with the functionality we required all these time, we just never looked in the right place!

Hehe.  Glad it helped. :)

**Comment by pedronavf** [comment]
Thanks everybody for the comments! I understand and agree with the arguments. We want to avoid integrating harfbuzz and calling its private headers, because they are private and subject to change and because partners that integrate our software provide their own FreeType, Harfbuzz, etc so we have to adapt to what we are linked against.

We are all for using a public API, but were afraid that some of our needs were too specific (or crazy) to warrant an official API, that's why there was some interest in accesing the tables directly.

>>In our system we can synthesize a non-proportional font from a proportional font by using the max advance and centering the glyphs as we render them.

>This is going to render badly in many non-Latin fonts. For example, in Amiri 11435, over 10 times the average glyph width in the same font.

>That's a really sketchy and bad idea honestly.

It is, no doubt about that. We are not proud 😄  We used to display closed captions (that means English, Spanish and French only, which means a very limited character set to contend with) on systems that don't have enough flash space to have more than one or two fonts (which we deplou and can make sure they have the right max advance) so we had to fake all the possible styles in the CEA-708 standard with as few fonts as possible. The code is still there.

> We can add more metrics if you list which you need. The reason those are not available in mvar table is because the OpenType industry stakeholders all agree that things like max-advance are not useful for good reasons, as well as very hard / impossible to handle correctly in variable fonts.

Thanks. I think we can deprecate some of the old code and we should be fine with the new metrics API, I'll reach out if not. We are moving from our integrated 1.7.6 to a stock 2.6.0 as it looks like it has everything we need.

**Comment by behdad** [comment]
Sounds great.

Anything a major client, eg Netflix, reasonably needs is legitimate for public API.  The only hard draw we've had so far (and even that is negotiable) is supporting old legacy non-OpenType formats.

**Comment by pedronavf** [comment]
Thanks! I'll close this and will open a new issue if we ever need to request some new API or metric.

**Comment by behdad** [comment]
Great.  We're working on exposing some bitfields in https://github.com/harfbuzz/harfbuzz/issues/1920
