### ISSUE TITLE
What is hb_glyph_extents_t for?

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#1940]
What is  `hb_glyph_extents_t` intended for? Internally calculated as floats from outlines (especially in case of VF), returned as integers, they can't be accurate. If they are used for clipping, I believe `floor` & `ceil` would produce better results, but I realized rounding better match FreeType results (though not exactly, probably due to math error).

**Comment by ebraminio** [comment]
We should do font scale at very same place we are turning floats to ints.

**Comment by ebraminio** [comment]
I wish I could just do that (moving all font scale from `hb_ot_get_glyph_extents` to the tables themselves, specially your VF glyf, but fear from conflict with your works 😂

**Comment by behdad** [comment]
> I wish I could just do that moving all font scales from `hb_ot_get_glyph_extents` to the tables themselves

Why?

Tables retrieve values in font units.  That's simpler, no?

**Comment by behdad** [comment]
Rounding doesn't matter.  User should set scale with sub-pixel precision (16.16, 22.10, 26.6, etc).  So half an integer doesn't really matter.

**Comment by behdad** [comment]
What does matter is to calculate and add up effects of various delta sets in variable fonts in float space ideally, then scale to user-space once.

**Comment by ebraminio** [comment]
> Tables retrieve values in font units. That's simpler, no?

That is the case for most of the glyph table but in VF that means turning floats to ints before scaling and losing precision, why losing that details when we can simply use it by reorganization.

> What does matter is to calculate and add up effects of various delta sets in variable fonts in float space ideally, then scale to user-space once.

This is where floor/ceil is applied https://github.com/harfbuzz/harfbuzz/blob/8106ba7f882f087be114801e857bc945e42cf45b/src/hb-ot-glyf-table.hh#L829-L840 those won't be needed if we just could do scaling at the place.

**Comment by behdad** [comment]
Sure, we can move the scaling further down to avoid rounding to font units before scaling.

**Comment by behdad** [comment]
But also, ceil/floor is harmless and correct for these.

I'm more interested making sure advances and glyph outlines are done with as much precision as possible.  Glyph extents are less important.

**Comment by ebraminio** [comment]
Answering OP,

> What is hb_glyph_extents_t intended for? [..]

AFIAUC the main use is hb-ot-shape-fallback.cc where positioning is not provided by GPOS and we do our fallback to give something.

> [..] Internally calculated as floats from outlines (especially in case of VF), returned as integers, they can't be accurate. [..]

As Behdad explained they can be accurate as much user wants, just by moving font scaling before turning floats to ints, which Behdad believes is not much of loss.

> [..] If they are used for clipping, 

We don't do clipping AFIAUC. Even if we plan for rasterization, we should get glyph contours extractions correctly and expose it in an API first and can care less about clipping, I think.

As a part of this work, I wish we could reach to `get_glyph_contour_point` from `glyf` and `CFF` tables also.

**Comment by behdad** [comment]
> As a part of this work, I wish we could reach to `get_glyph_contour_point` from `glyf` and `CFF` tables also.

Not necessary.

**Comment by ebraminio** [comment]
> Not necessary.

Correct, for other readers, all our uses of `get_glyph_contour_point` are in corner cases as some formats of anchors in `gdef`, `gpos`, AAT's `kerx`, `lcar`, not hooked `opbd`. Just nice to have eventually I guess.

**Comment by behdad** [comment]
What's this issue for?

**Comment by ebraminio** [comment]
Uploaded a possible fix on #2008
