### ISSUE TITLE
build failed with error libglib-2.0.la no such file or directory

### ISSUE THREAD

**Issue by slackernetuk** [harfbuzz/harfbuzz#1941]
Recently, I've upgraded glib 2.46.2 to 2.60.6 by source code. Since then I have issues to build harfbuzz.

`/usr/bin/grep: /usr/lib64/libglib-2.0.la: No such file or directory /usr/bin/sed: can't read /usr/lib64/libglib-2.0.la: No such file or directory libtool: error: '/usr/lib64/libglib-2.0.la' is not a valid libtool archive Makefile:1774: recipe for target 'libharfbuzz.la' failed make[4]: *** [libharfbuzz.la] Error 1 make[4]: Leaving directory '/root/build/harfbuzz/harfbuzz-2.6.0/src' Makefile:2939: recipe for target 'all-recursive' failed make[3]: *** [all-recursive] Error 1 make[3]: Leaving directory '/root/build/harfbuzz/harfbuzz-2.6.0/src' Makefile:1609: recipe for target 'all' failed make[2]: *** [all] Error 2 make[2]: Leaving directory '/root/build/harfbuzz/harfbuzz-2.6.0/src' Makefile:525: recipe for target 'all-recursive' failed make[1]: *** [all-recursive] Error 1 make[1]: Leaving directory '/root/build/harfbuzz/harfbuzz-2.6.0'`

**Comment by behdad** [comment]
Your build issue.  Nothing we can do.  Try reconfiguring HarfBuzz.
