### ISSUE TITLE
Implement something similar to itertools.chain

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#1943]
Frequently it's necessary to create an iterator of iterators. A chain like iterator operation would simplify these cases. For example here: https://github.com/googlefonts/harfbuzz/pull/9/files#diff-c5c255a43834386beff4d1d82645cb43R697

Also a a operation that collapsed integer iterators into ranges would be useful.

**Comment by behdad** [comment]
So I see two variants needed:  One that takes an iterator of iterators and chains them.  Another that takes two or more iterators (of possibly different types) and chains them.

**Comment by behdad** [comment]
Closing until we need it badly enough that we implement...
