### ISSUE TITLE
A possibly outdated comment

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#1965]
Is a comment at this line: 

https://github.com/harfbuzz/harfbuzz/blob/4905a2198b4c47c12c6356f72ae0d2b178630d25/src/hb-ot-shape-normalize.cc#L216

is outdated? Since `glyph` will always be 0 at this point, unless I'm missing something.

If so, we can replace it with something like:

```c
next_char (buffer, 0); /* Insert a .nodef glyph if decomposition is failed. */
```

**Comment by behdad** [comment]
Comment is accurate. A custom user get_nominal_glyph() callback can set glyph while returning false. Pango does that for example to display boxes with the Unicode number inside instead of a notdef glyph.

**Comment by RazrFalcon** [comment]
I see. Thanks for explanation.
