### ISSUE TITLE
Approach to dropping unused lookups/features/scripts during layout subsetting

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#1968]
Layout subsetting does not yet support dropping unused lookups/features/scripts and we'd like to start doing that. Starting this issue to discuss the design. My current though is that we should compute the set of reachable lookups, scripts, and features to keep as part of the subset plan computation and save those in the subset plan object. Then during GPOS/GSUB subsetting drop any lookups/features/scripts not in those sets.

Current lookup collection during subset plan just grabs all lookups that are reachable by looking at all features reachable from each script. We'll need to add an additional step that computes which lookup's can be activated by the retained glyph set. I believe we can do this by checking the "intersects" method of each lookup against the final glyph closure. Next:
-  For each feature intersect the lookup indices against the set of activated lookups. If the intersection is not empty, add the feature to a list to be kept.
- For each script intersect the feature indices against the set of retained features. If the intersection is not empty, add the script to a list to be kept.

Currently we only do lookup collection for GSUB, so we'll need to add that for GPOS as well.

Thoughts?

**Comment by garretrieger** [comment]
Notes from chat with Behdad:

Two approaches:

- Compute the lookup id remapping and retention set during the planning phase using intersects. The downside is that replicates some subsetting functionality.
- Alternatively we could have a two pass subset. First we subset all lookups and figure out which are empty and not empty. Compute the lookup id remapping during this. Then run a second subset pass which rewrites the lookup ids. Finally you can subset feature and script.

**Comment by behdad** [comment]
Closing.  I'm leaning towards the `intersects` model, which is what Qunxin already implemented.  Will followup in another issue.
