### ISSUE TITLE
Harfbuzz is not found on macosx using Cmake

### ISSUE THREAD

**Issue by koeppea** [harfbuzz/harfbuzz#1972]
Hi,
I've used the FindHarfBuzz.cmake from the CMake repository.
It works perfectly fine under Linux.
However on MacOSX, Cmake can't find it.
I already tried to set the env variable _HARFBUZZ_DIR_: 
```
-DHARFBUZZ_DIR=`brew --prefix harfbuzz`
```
but w/o success.
Could you help how to make harfbuzz found using Cmake on MacOSX?
Thanks.

**Comment by khaledhosny** [comment]
That is an issue for the FindHarfBuzz.cmake maintainers not HarfBuzz.
