### ISSUE TITLE
Enable -fno-sanitize-recover=undefined

### ISSUE THREAD

**Issue by tysmith** [harfbuzz/harfbuzz#1975]
At the moment the CI test suite is running without any sanitizers to help detect issues such as memory corruption/safety issues as well as undefined behavior. Adding an additional CI build/test run with AddressSanitizer and UndefinedBehaviorSanitizer enabled will help find existing issues and prevent regressions (perhaps a separate build with MemorySanitizer too).

Since many other project depend on Harfbuzz and do enable sanitizers in their test suites (or durring fuzzing) Harfbuzz issues are being discovered indirectly. We are currently trying to enable more UBSan checks in Firefox and we are coming across Harfbuzz issues. I ran the test suite locally with an ASan+UBSan build and it did turn up issues.

Is this a possibility? It would help prevent regressions and also prevent fuzz blockers on oss-fuzz.

**Comment by ebraminio** [comment]
We actually have all of the sanitizers in our CI

![image](https://user-images.githubusercontent.com/833473/65013806-d283f900-d931-11e9-8d00-b0f91ef3de9a.png)

what is missing apparently in your case is

**Comment by ebraminio** [comment]
> I ran the test suite locally with an ASan+UBSan build and it did turn up issues.

Let us know what has happened there as our CI, oss-fuzz itself and my local ubsan+asan enabled build are unable to detect any regression. Thanks

**Comment by tysmith** [comment]
My apologies I completely missed the CircleCI. I ran the test suite locally, saw failures, looked at the .travis.yml and incorrectly assumed UBSan was not being run.

After looking at the CircleCI config.yml I believe the reason it is missing issues it because it is missing `-fno-sanitize-recover=undefined` [here](https://github.com/harfbuzz/harfbuzz/blob/c930ae2bd8b6f626ddec0628ae6b38e3134e3c97/.circleci/config.yml#L197).

Setting the environment variable `UBSAN_OPTIONS=print_stacktrace=1` [here](https://github.com/harfbuzz/harfbuzz/blob/c930ae2bd8b6f626ddec0628ae6b38e3134e3c97/.circleci/config.yml#L199) would also be helpful because it would provide a stacktrace.

**Comment by ebraminio** [comment]
Oh, great infos, will just make them fix

**Comment by ebraminio** [comment]
Uploaded a fix here #1976

**Comment by tysmith** [comment]
Thank you for the quick response and all the fixes!

**Comment by ebraminio** [comment]
Thank *you*! Maybe oss-fuzz bots can have the flag also. We like also to
have GCC sanitizers also to see if they have different perspective but I
don't know the set of flags that can cover all the different things it
provides.
