### ISSUE TITLE
[subset] Subset CBLC/CBDT tables

### ISSUE THREAD

**Issue by ckitagawa** [harfbuzz/harfbuzz#1978]
Subsetting doesn't occur for the CBLC/CBDT tables. It looks like FontTools at least has experimental support for this as of https://github.com/fonttools/fonttools/pull/397 see the discussion at https://github.com/fonttools/fonttools/issues/395. It would be nice for Harfbuzz to support this as subsetting emoji/bitmap fonts is helpful due to their large size.

**Comment by khaledhosny** [comment]
Fixed in https://github.com/harfbuzz/harfbuzz/pull/2121 already.
