### ISSUE TITLE
Strange parenthesis placement in vertical layout in Noto Sans JP

### ISSUE THREAD

**Issue by t-veor** [harfbuzz/harfbuzz#1979]
Hey, I ran into this weird issue today with the Noto Sans JP font, downloaded from https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip.

When shaping the string `"（世界）"` (those are full width parentheses), the left parenthesis looks like it is positioned too high and so there looks like too much of a gap between the （ and the 世. Here's the output using `hb-view`:

```
./hb-view NotoSansCJKjp-Regular.otf "（世界）" --direction=ttb -O png -o test.png --annotate
```
![test](https://user-images.githubusercontent.com/22255669/65175460-d0fa2400-da4a-11e9-9638-bd59dee7f093.png)

Strangely, both Firefox and Chromium don't have this issue. I checked this simple test page, which tries to render the same text using the same font:
```html
<html>
    <head>
        <style>
            @font-face {
                font-family: "Noto Sans JP";
                src: url("NotoSansCJKjp-Regular.otf");
            }

            div {
                font-family: "Noto Sans JP";
                font-size: 96pt;
                writing-mode: vertical-rl;
            }
        </style>
    </head>
    <body>
        <div>（世界）</div>
    </body>
</html>
```

![image](https://user-images.githubusercontent.com/22255669/65176079-fb001600-da4b-11e9-9b6d-4829d8d7c0e4.png)

Any idea why this is happening? I did spend some time staring at the Chromium source, but it doesn't look like they're doing anything special with glyph offsets in vertical text.

**Comment by jfkthame** [comment]
This looks like the same issue as described in #452.

(I wonder, does it make any difference whether you use `ot` or `ft` font-funcs?)

**Comment by t-veor** [comment]
Hey, you're right, passing `--font-funcs=ot` to `hb-view` fixes it. It's strange that `hb-shape` looks like it returns the right thing with both `--font-funcs=ot` and `--font-funcs=ft` though.

In my actual application use case I am using FreeType to load fonts. Is it okay for me to call `hb_ot_font_set_funcs` on the result of `hb_ft_font_create`?

**Comment by behdad** [comment]
Feels like vertical glyph origin difference between hb-ft and hb-ot-font.  Need to investigate more.  hb-ot-font respects VORG table.  FreeType doesn't as far as I remember.

**Comment by KrasnayaPloshchad** [comment]
> Strangely, both Firefox and Chromium don't have this issue.

Me too with LibreOffice.

**Comment by behdad** [comment]
This seems fixed by changes I made a while ago.
