### ISSUE TITLE
has_format14 isn't used

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1986]
Revealed while 385741d56 to me, on this [line](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-cmap-table.hh#L1180), `has_format14` is defined but never used, probably something is wrong here. cc: @qxliu76 @garretrieger @rsheeter

**Comment by qxliu76** [comment]
It's not affecting functionality. I will delete this redundant variable.

**Comment by ebraminio** [comment]
Fixed it, thanks for checking it.

**Comment by qxliu76** [comment]
> Fixed it, thanks for checking it.

thank you!
