### ISSUE TITLE
compilation error when ICU support is enabled

### ISSUE THREAD

**Issue by vtorri** [harfbuzz/harfbuzz#1990]
hb 1.6.1 (latest as of today), i compile wit ICU support. here is the errors:

hb-icu.cc: In function 'hb_bool_t hb_icu_unicode_compose(hb_unicode_funcs_t*, hb_codepoint_t, hb_codepoint_t, hb_codepoint_t*, void*)':
hb-icu.cc:56:31: error: expected ';' before '}' token
   56 | #define HB_ICU_STMT(S) do { S } while (0)
      |                               ^
hb-icu.cc:191:3: note: in expansion of macro 'HB_ICU_STMT'
  191 |   HB_ICU_STMT (U16_APPEND (utf16, len, ARRAY_LENGTH (utf16), a, err));
      |   ^~~~~~~~~~~

there are plenty other errors like like because of the missing semi-colon

**Comment by behdad** [comment]
Which ICU version?  I wonder if this is the result of https://unicode-org.atlassian.net/browse/ICU-20601

@srl295 

I don't have Fredrik's github id handy.

**Comment by vtorri** [comment]
the problem is

 { S } 

which must be instead : 

 { S; }

**Comment by ebraminio** [comment]
> the problem is
>
> { S }
>
> which must be instead :
>
> { S; }

Right, we probably should remove whole HB_ICU_STMT and add extra semicolon warning exception to the file.

**Comment by vtorri** [comment]
once the fix is done, would it be possible to do a new release ? having a code which does not compile is quite problematic. For now, i have to use sed to add the semicolon in my build system (i'm on Windows)

**Comment by ebraminio** [comment]
> once the fix is done, would it be possible to do a new release ? having a code which does not compile is quite problematic. For now, i have to use sed to add the semicolon in my build system (i'm on Windows)

That's tempting but we are usually reluctant to such but our release cycles aren't long also :) If you are embedding harfbuzz, feel free to just pick the latest version, that's what Chrome uses also.

**Comment by vtorri** [comment]
i've set a notification to follow releases, so i've always the latest version of hb

**Comment by ebraminio** [comment]
Oh meant you can pick up the master also :) Uploaded a fix let's see what happens

**Comment by vtorri** [comment]
i can use also a git repo. Btw, I test ICU 65.1RC too in my build system

**Comment by behdad** [comment]
We're due for a release.  Will make one soon, maybe this afternoon.
