### ISSUE TITLE
Class kerning: split subtables with coverage overlap lead to some kerning being unreachable

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#1991]
I stumbled over a class-based kerning setup that results in two PairPos format 2 subtables instead of one because they have different value formats, but with the same coverage. When looking up the kern1 side of a class, HarfBuzz (and an up-to-date InDesign 2019) only look at the first table, the kerning of the second table becomes unreachable. In the following test file, the kerning is between an RTL and LTR glyph (Hebrew maqaf against one-hb), but I found that all it takes is a split due to different value formats, so it happens for LTR-to-LTR and RTL-to-RTL pair as well. PairPos tables of format 1 (glyph to glyph) do not have this problem.

The question is: should this work? Is this legal? Should the compiler explode?

The original issue with XML and feature file dumps, etc. is at https://github.com/googlefonts/ufo2ft/issues/341. Test TTF: [LTRRTLKerningTest.zip](https://github.com/harfbuzz/harfbuzz/files/3653762/LTRRTLKerningTest.zip)

Test text file:

```
־1־א־
```

hb-shape 2.6.1 output:
```
> hb-shape.exe --text-file testhebr.txt LTRRTLKerningTest.ttf
[maqaf-hb=4+600|alef-hb=3+600|maqaf-hb=2+600|one-hb=1+600|maqaf-hb=0+620]
```

Expected output:
```
> hb-shape.exe --text-file testhebr.txt LTRRTLKerningTest.ttf
[maqaf-hb=4+600|alef-hb=3+600|maqaf-hb=2@-50,0+550|one-hb=1+600|maqaf-hb=0+620]
```

**Comment by khaledhosny** [comment]
AFAIK, if the coverage is overlapping then they need to be different lookups not subtables of the same lookup. A glyph that is covered by one subtable is skipped for subsequent subtables.

I learnt the hard-way to avoid subtables altogether, one needs to be careful or they won’t do one one thinks they are doing.

**Comment by behdad** [comment]
What Khaled said.  Subtables should really be reserved for feature compiler to use to optimize binary size as well as work around offset size limitations.  From a functional point of view, a lookup is a unit.

**Comment by behdad** [comment]
This was/is a bug in feaLib.  HB behavior is correct and expected.

**Comment by anthrotype** [comment]
Thanks Khaled and Behdad.
So, if I understand this correctly, since within one PairPosFormat2 subtable there can only be one pair of ValueFormats (one for each side), if the `kern` feature definition in a feature file contains `pos` rules with different value formats (e.g. one has simple value for XAdvance of first glyph, another has both XPlacement and XAdvance), then we need to split them into two lookups, not two subtables?

Should that be done in ufo2ft KernFeatureWriter when generating the features or in feaLib when compiling them into GPOS table?

**Comment by behdad** [comment]
> Thanks Khaled and Behdad.
> So, if I understand this correctly, since within one PairPosFormat2 subtable there can only be one pair of ValueFormats (one for each side), if the `kern` feature definition in a feature file contains `pos` rules with different value formats (e.g. one has simple value for XAdvance of first glyph, another has both XPlacement and XAdvance), then we need to split them into two lookups, not two subtables?

No!

The ValueFormat is just an optimization mechanism.  (There's an exception to this, noted below).  Basically, forget about ValueFormat and fill in with 0 all the missing values.  Then you get a big matrix of all glyphs across all glyphs with bunch of non-zero values but a lot of zeros.  Now you figure out how to optimize storing this big matrix.  That's a heuristic logic we don't currently have.  We should develop.

The only exception is this: a ValueFormat of 0 for second glyph in a PairPos has a special meaning.  Changing it to non-zero will change the behavior of the lookup.  We should figure out what to do about those....
