### ISSUE TITLE
macOS Catalina System Font 10.15 tracking differs between CoreText and HarfBuzz

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#1995]
Screenshots in 
https://bugs.chromium.org/p/chromium/issues/detail?id=1005969#c3 

more details to follow. I don't have access to the font yet.

**Comment by behdad** [comment]
Details please.

**Comment by drott** [comment]
Initial finding: Catalina has a font SFNS.ttf which is a variable font that also has an 'opsz' axis ranging from 19.9 to 20. With 20, the default, applied, it tracks very narrowly. It looks like we need some instructions on how to scale 'opsz' for this font. Looks like this issue is more on the Chromium side in how to use the parameters for this font correctly.

**Comment by ebraminio** [comment]
One thing worth to be discussed I guess, is applying tracking to advance instead makes sense?

**Comment by behdad** [comment]
> One thing worth to be discussed I guess, is applying tracking to advance instead makes sense for us?

What does that mean?  There's only one way to apply trak.  Oh you mean putting it in the `get_h_advance`?  I see how that's tempting!

**Comment by behdad** [comment]
I think that would mess up mark positioning though.

**Comment by ebraminio** [comment]
As said in #1487 before I wished we could embed more logic on tracking, or, could able to not apply tracking for cursive scripts (which we have the info here #1505) at least, if we don't have any of them, perhaps matching CoreText is better.

**Comment by behdad** [comment]
If font declares traking we should apply.  I don't see how that's relevant to cursive scripts.

**Comment by ebraminio** [comment]
> If font declares traking we should apply. I don't see how that's relevant to cursive scripts.

Ok, makes sense, perhaps clients shouldn't send tracking value to us for cursive script at first place.

**Comment by behdad** [comment]
So, what's actionable here?

**Comment by ebraminio** [comment]
Nothing I guess, am following the matter on Chromium bug tracker so let's close

**Comment by tettoffensive** [comment]
Hey, I discovered this thread while trying to hunt down something I'm seeing. Can you tell me if this is related? I'm seeing Chrome's use of the Display and Text versions of the font not to behave as I expect.

https://www.reddit.com/r/web_design/comments/elxu29/confusion_between_sf_pro_display_and_sf_pro_text/

If this is the issue, is there any work around I could do in my css, until I see the fix in my browser?

**Comment by drott** [comment]
Yes, this is related. For details, please follow along (by star'ing for example) the [Chrome bug 1005969](https://bugs.chromium.org/p/chromium/issues/detail?id=1005969) mentioned in the original report up at the beginning of this thread here.
