### ISSUE TITLE
Extreme ScriptList expansion

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#1996]
I spent some time looking into a fuzzer reported timeout (https://oss-fuzz.com/testcase-detail/5721073428987904). The testcase is a ~300 kb font, when it's subsetted the ScriptList table gets expanded out to over 300 mb.

The timeout is the result of a few factors:
- A profile showed that >99% of the time is spent calculating hashes of hb_object_t's during serializer->pop_pack().
- The large number of items (~800,000 effective LangSys records) multiplied by the sub optimal hash implementation results in long execution times. 
- Finally, because of the extreme expansion the subset call repeatedly runs out of memory and re-runs with an expanded buffer making things even worse.

Some ideas to speed up:
- Cache hash values in hb_object_t's and invalidate them when new links get added.
- hb-arrays.h has a TODO to implement a custom hash function for hb_bytes_t. A custom implementation should be faster then the current generic hb_array_t hash function.
- hb-map.hh has a TODO to save hash values along with pointers to avoid repeated recomputation.

Some ideas to deal with this class of timeouts (tables that get significantly expanded by subsetting):
- Enforce HB_MAX_SCRIPTS during subsetting of the scriptList.
- To deal with the more general case of a table that has significant expansion, implement a maximum allowed expansion for a table. The maximum could be the large of some fixed threshold (say 1mb), or the input table size times some factor (say 4x).

**Comment by ebraminio** [comment]
> To deal with the more general case of a table that has significant expansion, implement a maximum allowed expansion for a table. The maximum could be the large of some fixed threshold (say 1mb), or the input table size times some factor (say 4x).

https://github.com/harfbuzz/harfbuzz/commit/88e9db19d29480fadcd4f49f0f4d9029ac64b429 and https://github.com/harfbuzz/harfbuzz/pull/1930 hmtx can be expanded to much bigger size of its original size, if we can have that assertion back we can find a good higher bound estimation by early failure of fuzzer in corner cases.

**Comment by behdad** [comment]
Is this still valid after https://github.com/harfbuzz/harfbuzz/pull/2001 ?

**Comment by garretrieger** [comment]
Closing as this has been fixed by #2001.
