### ISSUE TITLE
Add Repology badge to track downstream packaging of harfbuzz

### ISSUE THREAD

**Issue by luzpaz** [harfbuzz/harfbuzz#2002]
### Summary
A way for users to see what downstream repositories carry harfbuzz

### Proposed design
The compact badge looks like so:  
[![Packaging status](https://repology.org/badge/tiny-repos/harfbuzz.svg)](https://repology.org/project/harfbuzz/versions)

The full badge looks like so (but may be too "bulky"):  
[![Packaging status](https://repology.org/badge/vertical-allrepos/harfbuzz.svg?header=harfbuzz)](https://repology.org/project/harfbuzz/versions)  

---------

**Note:** There is also a possibility to add the full badge in to it's own section, like so:

```
### Packaging Status

<details>
  <summary>Expand to see the packaging status of harfbuzz...</summary>

[![Packaging status](https://repology.org/badge/vertical-allrepos/harfbuzz.svg?header=harfbuzz)](https://repology.org/project/harfbuzz/versions)  

</details>
```

**Which gives us:**  

### Packaging Status

<details>
  <summary>Expand to see the packaging status of harfbuzz...</summary

[![Packaging status](https://repology.org/badge/vertical-allrepos/harfbuzz.svg?header=harfbuzz)](https://repology.org/project/harfbuzz/versions)  

</details>

**Comment by behdad** [comment]
Lovely!  I like the collapsible section. Thanks!

**Comment by behdad** [comment]
Maybe with the small badge as well.

**Comment by ebraminio** [comment]
Excellent, just applied it, thanks!
