### ISSUE TITLE
hb_range () should do sanity check on invalid input

### ISSUE THREAD

**Issue by qxliu76** [harfbuzz/harfbuzz#2004]
hb_range () goes into infinite loop if input is invalid. e.g. hb_range(100, 2)
can we add a sanity check to just ignore invalid input?

**Comment by behdad** [comment]
Sure.  Just adjust `end_for` in hb-iter.hh?

**Comment by qxliu76** [comment]
Sounds good.

**Comment by qxliu76** [comment]
> Sure. Just adjust `end_for` in hb-iter.hh?

Sounds good.

**Comment by behdad** [comment]
Are you going to work on this?

**Comment by qxliu76** [comment]
yes I'll work on this.
