### ISSUE TITLE
Why is hb-warning a compilation unit?

### ISSUE THREAD

**Issue by dmoody256** [harfbuzz/harfbuzz#2005]
Can these preprocessor checks just be added to the bottom of hb.hh?

It produces a lnk4221 warning on windows builds:
https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4221?view=vs-2019

**Comment by ebraminio** [comment]
Interesting, and worth to fix, however feel free also to just use harfbuzz.cc, single file, whole harfbuzz, for now :)

**Comment by behdad** [comment]
It was made into a compilation unit so the warnings are emitted just once.

So we have completely become slaves to compilers now....  What's wrong with a compilation unit having everything compiled out, perhaps because of preprocessor symbols?

**Comment by dmoody256** [comment]
in hb-warning.cc aren't they preprocessor errors and would make build systems assume compilation failed, and therefore fail a build?

**Comment by dmoody256** [comment]
Could the preprocessor checks instead be at top of some main .cc file?
