### ISSUE TITLE
How to disable rtl?

### ISSUE THREAD

**Issue by aranmohyeddin** [harfbuzz/harfbuzz#2015]
could you please see the last two comments [here](https://github.com/kovidgoyal/kitty/issues/1851#issuecomment-541383251)

**Comment by khaledhosny** [comment]
HarfBuzz does not set text direction, the caller has to set the direction explicitly. Only place where HarfBuzz sets text direction itself is in  `hb_buffer_guess_segment_properties()` but the caller has to call it explicitl, and as the name suggests it gives it's best guess and if the application knows better it shouldn't be calling it to begin with.
