### ISSUE TITLE
Make -5717414645334016 subset faster

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2020]
Had to upload https://crbug.com/oss-fuzz/17898 in tree e76678315 as it was closed and as I didn't want we won't forget it but now it fails tsan bot https://circleci.com/gh/harfbuzz/harfbuzz/114791 @garretrieger @rsheeter @qxliu76 can you make faster please?

**Comment by garretrieger** [comment]
From a look at a profile it looks like the majority of the time is spent doing hash() calls for hb_map_t get and set's. Tackling some more of the hash speedup todo's (for example caching hash values) should probably help here.

Alternatively we could tune some of the limits (such as the script and langsys limits) for the sanitizer bots since having the sanitizers on looks like it adds significant overhead.

**Comment by garretrieger** [comment]
Another option would be to configure the bots to use -O3 instead of -O1. Cuts run time by 1/2.

**Comment by ebraminio** [comment]
To be honest I was thinking about some kind of limitation but this also
looks good, thanks.

در تاریخ سه‌شنبه ۲۲ اکتبر ۲۰۱۹،‏ ۰۰:۵۲ Garret Rieger <
notifications@github.com> نوشت:

**Comment by garretrieger** [comment]
https://github.com/harfbuzz/harfbuzz/pull/2024 this pr attempts to speed things up. Unfortunately looks like it still times out. Next I'm going to look into how easy it'll be to cache hash() calculations in map_t. If that doesn't end up working out then the only other options I can see are to either change the optimization level or set HB_MAX_LANGSYS to a lower value for the sanitizer bots.

**Comment by ebraminio** [comment]
In addition to what said here https://github.com/harfbuzz/harfbuzz/pull/2024#issuecomment-545366265 I don't think we like to decrease HB_MAX_LANGSYS just for a specific bot (tsan and valgrind) but if something is abusing time that much we like to limit that for all the users so maybe turning HB_MAX_LANGSYS to 1000 and HB_MAX_SCRIPTS to 250, optionally however if you see that can't happen feel free to increase https://github.com/harfbuzz/harfbuzz/blob/master/test/fuzzing/run-subset-fuzzer-tests.py#L36

**Comment by garretrieger** [comment]
Alright, I think then the best thing is to just increase the timeout thresholds for now. I'll send out a PR for that today.

**Comment by ebraminio** [comment]
> Alright, I think then the best thing is to just increase the timeout thresholds for now. 

To be honest now I regret my comment, decreasing HB_MAX_LANGSYS may is better than altering the script for all the users so I will submit a patch for that now. Thanks
