### ISSUE TITLE
Wishilist: debug shaping steps

### ISSUE THREAD

**Issue by norbusan** [harfbuzz/harfbuzz#2035]
To debug shaping errors with some fonts, I would like to see a debug facility that logs every step in the shaping process, in particular table lookups, replacements, etc etc, practically anything that changes the final rendering, similar to how the TeX log file can be used to track every single box placement.

**Comment by khaledhosny** [comment]
There is `-V` option for `hb-shape` which will show lookups being executed, and the output after each one.

**Comment by norbusan** [comment]
Ah, thanks a lot @khaledhosny 
So for the case of issue https://github.com/harfbuzz/harfbuzz/issues/2037 I see:
```
$ hb-shape -V fonts/NotoSerifTibetan-Regular.ttf ༀྰ
trace: start lookup 2	buffer: [uni0F00=0|uni0FB0=0]
trace: end lookup 2	buffer: [uni0F00=0|uni0FB0=0]
trace: start lookup 3	buffer: [uni0F00=0|uni0FB0=0]
trace: end lookup 3	buffer: [uni0F00=0|uni0FB0=0]
trace: start lookup 4	buffer: [uni0F00=0|uni0FB0=0]
trace: end lookup 4	buffer: [uni0F00=0|uni0FB0=0]
trace: start lookup 5	buffer: [uni0F00=0|uni25CC=0|uni0FB0=0]
trace: end lookup 5	buffer: [uni0F00=0|uni25CC=0|uni0FB0=0]
...
```
which unfortunately doesn't tell me anything more :-( Probably because there is not more to say. Anyway, that is already a great debug facility, but adding the lookup table  would help, too.

Thanks

**Comment by behdad** [comment]
> adding the lookup table would help, too.

What do you mean by that?  I suppose what would help most is to say which feature enabled a particular lookup.  But we don't have that information handy.

**Comment by mhosken** [comment]
What would be nice and possible is to document recursed lookups from chaining contextuals, and to list the sublookups called and their effects.

**Comment by behdad** [comment]
That's being tracked / slowly making progress at:
https://github.com/harfbuzz/harfbuzz/issues/2468

**Comment by norbusan** [comment]
Thanks a lot to everyone working on this!
