### ISSUE TITLE
Tibetan shaping errors when using OM U+0F00

### ISSUE THREAD

**Issue by norbusan** [harfbuzz/harfbuzz#2037]
`OM U+0F00` is a precomposed character which is decomposed into
```
        U+0F68 TIBETAN LETTER A
        U+0F7C TIBETAN VOWEL SIGN O
        U+0F7E TIBETAN SIGN RJES SU NGA RO
```
On the other hand, the combination of OM + A-CHUNG (`U+0FB0 TIBETAN SUBJOINED LETTER -A`) is common in Tibetan religious texts.

It turns out that the sequence `U+0F00 U+0FB0` is rendered in all fonts I have tested with the dotted circle. Only one font [YagpoUni](https://www.buddism.ru/yagpo/) renders it slightly better, but still has a too large a-chung.

My guess is that after applying the decomposition, the order is 
```
        U+0F68 TIBETAN LETTER A
        U+0F7C TIBETAN VOWEL SIGN O
        U+0F7E TIBETAN SIGN RJES SU NGA RO
        U+0FB0 TIBETAN SUBJOINED LETTER -A
```
which has the vowel before the subjoined letters, which make harfbuzz end up considering this an illegal sequence and adding the dotted circle.

One needs to input
```
        U+0F68 TIBETAN LETTER A
        U+0FB0 TIBETAN SUBJOINED LETTER -A
        U+0F7C TIBETAN VOWEL SIGN O
        U+0F7E TIBETAN SIGN RJES SU NGA RO
```
to fix the layout.

Would it be possible to support composition of OM with other subjoints, or is this a font issue?

**Comment by dscorbett** [comment]
U+0F00 TIBETAN SYLLABLE OM is not a precomposed character, even though it looks like it should be. The dotted circle is inserted because U+0F00 is not considered a valid base letter. You should avoid it and use the sequence <U+0F68, U+0F7C, U+0F7E> instead. See [L2/18-078](https://www.unicode.org/L2/L2018/18078-tibetan-depr.pdf) for details.

**Comment by norbusan** [comment]
Thanks @dscorbett 
In principle you are right, but input methods (ewts/m17n) offer `oM` and at least those Tibetologist whom I know tend to use `oM+'` to input the above, which gives the above unicode sequence. Then there is also the issue of already available text, not only new ones.

**Comment by dscorbett** [comment]
I just checked on Windows; DirectWrite doesn’t insert a dotted circle. So I guess HarfBuzz should override U+0F00 to class B.

**Comment by norbusan** [comment]
Thanks for checking!

**Comment by dscorbett** [comment]
DirectWrite also doesn’t insert a dotted circle when the base is U+0F04 TIBETAN MARK INITIAL YIG MGO MDUN MA, U+0F05 TIBETAN MARK CLOSING YIG MGO SGAB MA, or U+0F06 TIBETAN MARK CARET YIG MGO PHUR SHAD MA. Do any of them take subjoined letters or other marks?

**Comment by norbusan** [comment]
No, these are punctuation style characters. I wouldn't expect to put subjoined letters or marks

**Comment by behdad** [comment]
MS recategorizes it as a consonant according to https://github.com/microsoft/font-tools/blob/master/USE/IndicSyllabicCategory-Additional.txt

I let David fix it using current table generator, or when porting to use MS files.

**Comment by norbusan** [comment]
Indeed, thanks! What I am surprised that they recategorize 
```
0F04..0F06   ; Consonant         # Po       TIBETAN MARK INITIAL YIG MGO MDUN MA..TIBETAN MARK CARET YIG MGO PHUR SHAD MA
```
but this is probably to enable placement of whatever (not that I can imagine something) there.

There is another one that caught my eye:
```
0F71         ; Nukta             # Mn       TIBETAN VOWEL SIGN AA # Reassigned to get this before an above vowel
```
which is probably important.

Thanks a lot again!

**Comment by dscorbett** [comment]
HarfBuzz uses USE’s overrides and no longer inserts a dotted circle in <U+0F00, U+0FB0>.
