### ISSUE TITLE
[config] Add HB_EMBEDDED and HB_NO_LIBC

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2040]
HB_EMBEDDED should disable atexit, setlocale, etc.

HB_NO_LIBC those, errno, other.

**Comment by waywardmonkeys** [comment]
This would make doing a WebAssembly build of the Rust bindings easier. :)

**Comment by behdad** [comment]
Thanks @waywardmonkeys.  Can you comment on what things would help there?  @ebraminio and you should decide what we need and we'll go ahead and implement them.

**Comment by ebraminio** [comment]
> This would make doing a WebAssembly build of the Rust bindings easier. :)

What is your requirements? HB_TINY does most of this already guess your needs are interesting also however.

**Comment by behdad** [comment]
Closing for now.
