### ISSUE TITLE
hb-shape has a bug with  a contextual mark to ligature lookup. 

### ISSUE THREAD

**Issue by readroberts** [harfbuzz/harfbuzz#2044]
For a contextual mark to ligature lookup, hb-shape attaches marks to only the last component.

With the feature file below, and the test text string ”fl<>”,
hb-shape attaches mark glyphs only to the last component.

With the command-line:  hb-shape -V  test1.otf 'fl<>'
the output is: [f_l=0+612|less=2+531|greater=3@113,668+531]
Only the ‘greater’ glyph attaches to an anchor, the last one.
With the text string “vf<”, the ‘less’ still does not attach.
If we put both ‘less’ and ‘greater’ in the GREATER_MARKS class, then both marks attach to the last anchor.

Expected:
The 'less' glyph should attach to the first ligature component, and the 'greater' glyph should attach to the second ligature component.
Left bbox  of the ‘less' should be aligned with the left bbox of the f_l
Right bbox  of the ‘greater’ should be aligned with the right bbox of the f_l
Bottom of bbox of the ‘less’ and ‘greater’ glyphs should be aligned with the top of the bbox of the ‘f_l’ glyphs.

See thread on opentype-list@indx.co.uk, subject "Re: [OpenType] Tools for debugging application of Opentype lookups".

```fea
markClass less <anchor 57 81> @LESS_MARKS;
markClass greater <anchor 474 81> @GREATER_MARKS;


feature liga {
   lookupflag IgnoreMarks;
    substitute f l by f_l;
} liga;

lookup test1 {
  pos ligature f_l <anchor 34 749> mark @LESS_MARKS
        ligComponent <anchor 587 749> mark @GREATER_MARKS;
} test1;

feature mark {
    pos c f_l' less' lookup test1 greater' lookup test1  t;
} mark;
```

**Comment by khaledhosny** [comment]
Shouldn’t the input be `f<l>` for the first mark to attach to the first component of the ligature? Yiu are adding two marks to the `l` and no marks to the `f`.

**Comment by khaledhosny** [comment]
(your `liga` would need ignore marks flag as well).

**Comment by readroberts** [comment]
The 'liga' feature did indeed need the ignore marks flag. I had in in my test, but omitted it from my example. 
Others have suggested that the text string should be "f<l>" rather than "fl". However, the first pass of layout processing is to apply the GSUB features. The resulting text string, which is the source text string for GPOS processing, is then "f_l<>" for both versions of the original text string. I think that both original text strings should produce the same result, unless I am wrong in my assumptions about layout processing.

**Comment by khaledhosny** [comment]
The marks have to directly follow its base character. If two characters end up forming a ligature, the layout engine will remember which marks belong to which component and place them using the corresponding anchor. Even if no contextual rule is involved, the input has to be `<base1><marks1><base2><marks2>`

The input sequence does not change based on whether or not ligatures are involved.

**Comment by khaledhosny** [comment]
With:
```fea
languagesystem DFLT dflt;

markClass less <anchor 57 81> @LESS_MARKS;
markClass greater <anchor 474 81> @GREATER_MARKS;


feature liga {
lookupflag IgnoreMarks;
    substitute f l by f_l;
} liga;

lookup test1 {
  pos ligature f_l <anchor 34 749> mark @LESS_MARKS
        ligComponent <anchor 587 749> mark @GREATER_MARKS;
} test1;

feature mark {
  pos c f_l' less' lookup test1 greater' lookup test1  t;
} mark;
```
```
$ hb-shape -V test.otf "cf<l>t"
trace: start lookup 0	buffer: [c=0|f=1|less=2|l=3|greater=4|t=5]
trace: end lookup 0	buffer: [c=0|f_l=1|less=1|greater=4|t=5]
trace: start lookup 1	buffer: [c=0+428|f_l=1+540|less=1+550|greater=4+550|t=5+316]
trace: end lookup 1	buffer: [c=0+428|f_l=1+540|less=1@-23,668+550|greater=4@113,668+550|t=5+316]
[c=0+428|f_l=1+540|less=1@-563,668+0|greater=4@-427,668+0|t=5+316]
```

Which I think is working as expected.
![o](https://user-images.githubusercontent.com/93914/68474390-ebbc6e00-022d-11ea-849d-8802f6ca559d.png)

**Comment by khaledhosny** [comment]
The test font: 
[test.zip](https://github.com/harfbuzz/harfbuzz/files/3824393/test.zip)

**Comment by readroberts** [comment]
I agree that this is the expected output. Thanks for clarifying this.  Can you point me to any document which documents the expected text order? I don't find this in the OpenType spec.

**Comment by khaledhosny** [comment]
I don’t know if this is spelled-out anywhere in relation to behavior, but the general Unicode rules (which should be somewhere in the Unicode core spec), is that combining marks follow their bases.

Whether the font builds a ligature of two or more bases or not should not affect how the text is input.

If I input `<base1><base2><mark1><mark2>` then I’m putting no marks on `<base1>` and two marks on `<base2>`, which is *not* the same as `<base1><mark1><base2><mark2>`.

If a font makes a ligature from `<base1>` and `<base2>` and another does not, the marks should be placed on the right base on both cases for both fonts.

**Comment by readroberts** [comment]
Makes sense, thanks.

**Comment by behdad** [comment]
> I don’t know if this is spelled-out anywhere in relation to behavior, but the general Unicode rules (which should be somewhere in the Unicode core spec), is that combining marks follow their bases.
> 
> Whether the font builds a ligature of two or more bases or not should not affect how the text is input.
> 
> If I input `<base1><base2><mark1><mark2>` then I’m putting no marks on `<base1>` and two marks on `<base2>`, which is _not_ the same as `<base1><mark1><base2><mark2>`.
> 
> If a font makes a ligature from `<base1>` and `<base2>` and another does not, the marks should be placed on the right base on both cases for both fonts.

I haven't read the whole discussion but yes, this is how HarfBuzz works.  I don't think it's specified in OpenType, and I don't think any other engine prevents you from ligating <mark1><mark2> if they belong to different bases (which have ligated since).

I remember someone saying they need to do that.  It's not too hard to imagine.  But I don't see how to do it.  For shapers that enforce a strict encoding order maybe we can do.

**Comment by khaledhosny** [comment]
The issue here was not whether marks should ligate or not, but the proper input order of marks over ligature components.
