### ISSUE TITLE
Detecting 64bit

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [harfbuzz/harfbuzz#2049]
Detecting 64bit with __WORDSIZE == 64

try harfbuzz/src/hb-atomic.hh :
#if __ppc64__ || __x86_64__ || __aarch64__ || __WORDSIZE == 64
#define hb_atomic_ptr_impl_cmpexch(P,O,N)	OSAtomicCompareAndSwap64Barrier ((int64_t) (O), (int64_t) (N), (int64_t*) (P))
#else
#define hb_atomic_ptr_impl_cmpexch(P,O,N)	OSAtomicCompareAndSwap32Barrier ((int32_t) (O), (int32_t) (N), (int32_t*) (P))
#endif

**Comment by behdad** [comment]
Some words about what problem you are trying to address would be great.

**Comment by AlexandrParkhomenko** [comment]
Bitness checking is not correct by enumerating architectures, but if the arm64 platform?
Maybe the function is not used here.

**Comment by behdad** [comment]
> Bitness checking is not correct by enumerating architectures, but if the arm64 platform?

Except that on my Mac that macro (`__WORDSIZE` is not defined.  Who defines that?  That's the bit you are not telling us.
