### ISSUE TITLE
32bit build from master fails

### ISSUE THREAD

**Issue by shoober420** [harfbuzz/harfbuzz#2051]
https://github.com/harfbuzz/harfbuzz/commit/b372c3e95694c8b1cabc0eb01c5abef6c41d3dbd
https://github.com/harfbuzz/harfbuzz/commit/e6351d9b2c44c9abde90a6599ae7ebf0f6416c65

These two recent commits broke the 32bit build of harfbuzz.

```
 CC       test_unicode-test-unicode.o
  CCLD     test-unicode
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `unorm2_getNFCInstance_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `uscript_getShortName_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `unorm2_composePair_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `u_getCombiningClass_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `unorm2_getRawDecomposition_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `uscript_getScript_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `u_getIntPropertyMaxValue_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `u_countChar32_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `u_charMirror_64'
/usr/bin/ld: ../../src/.libs/libharfbuzz-icu.so: undefined reference to `u_getIntPropertyValue_64'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1170: test-unicode] Error 1
make[3]: Leaving directory '/home/jukilo420_-/lib32-harfbuzz-git/src/harfbuzz/test/api'
make[2]: *** [Makefile:421: all-recursive] Error 1
make[2]: Leaving directory '/home/jukilo420_-/lib32-harfbuzz-git/src/harfbuzz/test'
make[1]: *** [Makefile:517: all-recursive] Error 1
make[1]: Leaving directory '/home/jukilo420_-/lib32-harfbuzz-git/src/harfbuzz'
make: *** [Makefile:449: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by behdad** [comment]
That's because configure is finding your 64-bit ICU.  We fallback to calling icu-config if the icu pkg-config is not available, and icu-config doesn't know anything about multiarch.  Just `--without-icu` I'd say.

There's no easy fix other than not calling icu-config.  This was added back i 2013.  I'm happy to remove it now.  Yeah, let's do.

**Comment by shoober420** [comment]
@behdad There are literally no packages in the Arch official repo that require the 32bit build of “harfbuzz-icu”. I’m going to add that build option to my “lib32-harfbuzz-git” package in the AUR since nothing really uses the “lib32-harfbuzz-icu” package on Arch. I would imagine the same holds true for just about every other distro.

**Comment by ebraminio** [comment]
Not something we can do anything about as we don't have access to build the package for distros but packagers of each distribution do so nothing is actionable for us here I believe.

**Comment by shoober420** [comment]
Yes, those recent commits now require the 32bit build of harfbuzz-icu to have the “lib32-icu” package installed now. Not many 32bit packages require “lib32-harfbuzz-icu”, a legacy package from the AUR is the only one shown, but irrelevant and deprecated. Instead of adding “lib32-icu” to the build dependencies, I’m going add the “without-icu” to the 32bit harfbuzz package. Thanks guys.

**Comment by behdad** [comment]
> There's no easy fix other than not calling icu-config. This was added back i 2013. I'm happy to remove it now. Yeah, let's do.

@ebraminio let's do this.

**Comment by shoober420** [comment]
This has actually been fixed for some time, on my end at least...
