### ISSUE TITLE
MONGOLIAN FREE VARIATION SELECTOR and MONGOLIAN VOWEL SEPARATOR need to display

### ISSUE THREAD

**Issue by siqinbilige** [harfbuzz/harfbuzz#2059]
According to Mongolian Working Group Meeting 3 (MWG3) Report 
https://unicode.org/wg2/docs/n5061-19139-mwg3-18-meeting-rept-r2.pdf

1. the NNBSP is very problematic and should not be used. Instead use MVS for this purpose. The investigating progress confermed it by Liang Jinbao and font developers in Inner Mongolia in China.
2. FVS and MVS must be visible by default. They are only invisible when they have effect on the display of text.

We want to exclude FVS(180B,180C,180D) and MVS(180E) from Default_Ignorable codepoints and can diaplay them.

Thank you.

**Comment by behdad** [comment]
Currently we try to match Uniscribe.  I understand Mongolian encoding is going through a transformation, but we need to have a plan for how to implement that, would it use the same font GSUB/GPOS script tag, etc, before we can go ahead and implement any changes.

**Comment by behdad** [comment]
cc @lianghai

**Comment by behdad** [comment]
Nothing actionable currently.
