### ISSUE TITLE
[subset] Fails to subset GPOS in variable font

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#2060]
`hb-subset` fails with the attached CFF2 variable font if GPOS table included as:
```
hb-subset --text=A --drop-tables-=GPOS --output-file=out.otf AdobeVFPrototype.otf
```
`out.otf` is not created. If `GPOS` table is not included (default), `out.otf` is created.

[AdobeVFPrototype.otf.zip](https://github.com/harfbuzz/harfbuzz/files/3888753/AdobeVFPrototype.otf.zip)

**Comment by garretrieger** [comment]
Running the subsetter in debug mode. It looks like sanitization of the GPOS table is failing. I'll have to dig in a bit deeper to see if that's a bug, or the table is in fact invalid in some way.

**Comment by garretrieger** [comment]
More specifically sanitization is failing for "struct HintingDevice" which I believe corresponds with the device table (https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#device-and-variationindex-tables).

**Comment by blueshade7** [comment]
I see what's wrong. An offset to a device table within a PairPosFormat1 lookup must be based on the beginning of its "immediate parent", i.e., PairSet table, according to OT spec, but sanitizer uses its grandparent, PairPosFormat1 table as the base. Correcting this generated a bad subset font however. I suspect serialization has the same issue. Looking further.

**Comment by blueshade7** [comment]
Can't find code to serialize device tables. Seems unimplemented.

**Comment by blueshade7** [comment]
created a branch `subset-gpos-var` with GPOS device table fixes

**Comment by blueshade7** [comment]
Now a subset font can be generated with the change in the branch. fontTools `ttx` works fine with the output but doesn't pass `ots-sanitize` seemingly due to null lookup subtable offset:
https://github.com/harfbuzz/harfbuzz/blob/8ed46c3678cd4518efe5c9907bb9d22e6161bbd5/src/hb-ot-layout-common.hh#L855-L856
This prevents adding a test case. I guess I will just create a PR for what I have now.

**Comment by garretrieger** [comment]
We have a few PR's out that will add support for dropping null lookups (ex: https://github.com/harfbuzz/harfbuzz/pull/2043) hoping to get those merged in the next few days.

**Comment by blueshade7** [comment]
Subsetting variation store in GDEF hasn't been implemented yet, but subsetting var GPOS works now, so let me close this.
