### ISSUE TITLE
Thai character tone marks positioning

### ISSUE THREAD

**Issue by azbht** [harfbuzz/harfbuzz#2062]
I am trying to use HarfBuzz for Thai multi-layer characters positioning.

Here is the sample character combination.

Actual Presentation: ที่
Separated by space: ท ี ่

Unicode: 0x0E17, 0x0E35, 0x0E48
UTF-8: 0xE0B897, 0xE0B8B5, 0xE0B988

When the 3rd mark appears immediately after the 2nd mark, it should be rendered above the 2nd mark. However, if the 3rd mark appear after the first character, it should vertically placed almost as the 2nd mark.

I tried getting glyph positions using hb_shape() with Leelawadee and Angsa New fonts.

hb_shape(hb_ft_font, buf, NULL, 0);

With Leelawadee font, I am getting y-offset but not with Angsa New font. However, browsers are rendering the sample characters correctly with both fonts.

Due to this, 2nd and 3rd marks are overlapped with my sample.

Can you please guide if and how we can get correct x and y-offset properly for these fonts.

**Comment by behdad** [comment]
Sounds like bad font to me.

**Comment by mhosken** [comment]
This is done in the OpenType code in the font. Harfbuzz supports this just fine and there is no issue for Harfbuzz here. The normal approach is to create anchors (or attachment points) on the various glyphs and use first a 'mark' feature containing a mark2base lookup to attach the diacritic to the base and then a 'mkmk' feature containing a mark2mark lookup to attach the second diacritic to the first.

**Comment by mhosken** [comment]
You do need to set a script on the hb_buffer before you call hb_shape. You can use hb_script_from_string to have harfbuzz work one out for you. If that is missing, then harfbuzz won't know to use the Thai script features in the font and shaping won't happen.
