### ISSUE TITLE
Kannada <VIRAMA CONSONANT> wrong form

### ISSUE THREAD

**Issue by MayuraVerma** [harfbuzz/harfbuzz#2064]
Kannada virama with consonant with any consonant should not form below form without presence of consonant, vowel or ZWJ to the left of the virama

Unicode Codepoint: u0ccd u0caf

https://docs.microsoft.com/en-us/typography/script-development/kannada#usage

Below form of consonant can be formed only in presence of the consonant, vowel or zwj before virama

Per Microsoft typography: below form of consonant can be formed byself with presence of ZWJ.
https://docs.microsoft.com/en-us/typography/script-development/kannada#usage
![image](https://user-images.githubusercontent.com/14062593/70348908-4941db80-1829-11ea-92f9-de958778da77.png)

Issue: Harfbuzz is forming "below form" of the consonant even without the presence of the ZWJ.

Chrome vs IE comparison
![image](https://user-images.githubusercontent.com/14062593/70348599-a6895d00-1828-11ea-9c01-0b12e7649bbb.png)

Safari in iOS 13.2.3
![Unicode Converter - Decimal, text, URL, and unicode converter](https://user-images.githubusercontent.com/14062593/70349702-e5b8ad80-182a-11ea-93d0-a1c61c16a312.png)

**Comment by jfkthame** [comment]
I'm not sure this is wrong. The `nbsp` here is functioning as a base (just as if it were a consonant), and the `<virama, cons>` sequence forms a below-base combining mark that is applied to it.

FWIW, I see a similar below-base form in Safari on macOS using the system's Kannada MN font:

    data:text/html,<div style="font:60px kannada mn">&nbsp;&%23xccd;&%23xcaf;

No ZWJ seems to be required. How else should a sequence of `<nbsp, virama, cons>` be displayed?

**Comment by jfkthame** [comment]
And on Windows 10, Internet Explorer seems to accept *either* ZWJ or ZWNJ as suppressing the dotted circle, so that the below-base form displays by itself, while MS Edge doesn't accept *either* of them; a sequence of `<nbsp, zwj, virama, cons>` insists on giving me a dotted circle.

Not much consistency here. I think what we do is pretty logical.

**Comment by MayuraVerma** [comment]
> FWIW, I see a similar below-base form in Safari on macOS using the system's Kannada MN font:

Kannada MN and Kannada Sangam MN has both AAT and OT feature. These fonts are not consistent between AAT and OT features and also are not fully compliant with Kannada script per Unicode standard. Apple is using "Noto Sans Kannada" with only OT feature, as system font for Kannada script in both iOS and mac OS since iOS 13 and Catalina. In iOS, it is used as only display fonts in Safari reader, which can be downloaded on demand.

> No ZWJ seems to be required. 
Yes, ZWJ is required for below-base form to be formed. 

below-base form can be formed only under the below sequences.
1. `<Kannada consonant, virama, Kannada consonant>`
2. `<Kannada vowel, virama, Kannada consonant>`
3. `<zwj, virama, Kannada consonant>`
and
3a. `<Ra, zwj, virama, Kannada consonant>`
3b. `<Ra, virama, zwj, Kannada consonant>` (canonical equivalence of 3a.)
if you treat the above as a special case not generic case of `<zwj, virama, Kannada consonant>`

`<virama, cons>` can't form below-base form by itself.

> How else should a sequence of `<nbsp, virama, cons>` be displayed?
virama without 25cc (dotted circle) followed by consonant
not
below-base form of the consonant without 25cc (dotted circle)

**Comment by jfkthame** [comment]
>        3a. `<Ra, zwj, virama, Kannada consonant>`
>        3b. `<Ra, virama, zwj, Kannada consonant>` (canonical equivalence of 3a.)

These are not canonically equivalent.

**Comment by MayuraVerma** [comment]
> These are not canonically equivalent.

https://github.com/harfbuzz/harfbuzz/issues/435#issuecomment-335560167

**Comment by MayuraVerma** [comment]
Harfbuzz, CoreText and Uniscribe all supports <ra, halant, zwj, consonant> to form 
ra with below-base form of consonant.

If all the shaping engines can drop support for this sequence at the same time, will be fantastic. It will make the Kannada text more consistent across all shaping engines.

**Comment by behdad** [comment]
@dscorbett anything actionable here?

**Comment by dscorbett** [comment]
U+00A0 NO-BREAK SPACE has Indic_Syllabic_Category=Consonant_Placeholder. I can’t find anything in Unicode that says consonant placeholders require ZWJ for subjoined consonants. The most straightforward interpretation is that a consonant placeholder acts like a consonant. I conclude that <U+00A0, virama, consonant> should produce a subjoined consonant and that we don’t need to change anything.
