### ISSUE TITLE
Combination order of Myanmar vowel sign E: ေ (u1031)

### ISSUE THREAD

**Issue by wonrst** [harfbuzz/harfbuzz#2068]
Hello,
I want to support myanmar language in my app, but I have a question.

My question is about the combination order of Myanmar vowel sign E: ေ (u1031) and consonants.

In my app, the result of the combination of u1031 and consonant is below.
(The consonant used in the example is u1006,
but the combination of u1031 and other consonants produces also same results.)

![table](https://user-images.githubusercontent.com/11732754/70531179-b93cc280-1b97-11ea-9e50-988b84b0c4d4.PNG)

According to my app's Myanmar local tester,
in case of **u1031**, the dotted circle (u25CC) is **on the right side,**
**so it must be combined in case 1** and not in case 2.

But in my app it works contrary to the expected results.

I want to know if there are any features supported by harfbuzz to fix this.
Or is this a problem with Harfbuzz? I'm not sure about this, but I want to know.

Below is my simple test code.
https://github.com/wonrst/Harfbuzz-myanmar

Thank you

**Comment by jfkthame** [comment]
I think this is a misunderstanding of how Unicode represents the text.

In Unicode, combining marks (like the Myanmar vowel sign U+1031) are encoded *after* the base character to which they apply, even when the mark *appears* to the left.

The dotted circle you see in the display of U+1031 alone shows that the mark will appear to the left of its base (represented by the circle), but it still goes after it in the text.

So the correct encoding of "che" in Myanmar script is <U+1006 LETTER CHA, U+1031 VOWEL SIGN E>; the consonant provides the "base" of the syllable and then a combining sign is applied to modify its vowel sound.

And so the current harfbuzz behavior here is correct.
