### ISSUE TITLE
Do the features harf and buzz exist?

### ISSUE THREAD

**Issue by devosb** [harfbuzz/harfbuzz#2071]
I thought I remembered reading on the HarfBuzz list that two extra features were added, namely `harf` and `buzz` that only HarfBuzz would support, not any other OT rendering engines. That way, a font might be able to work around differences in rendering engines by using the extra features HarfBuzz to implement a fix. It seems to me that such features could also be used to check which OT engine is being used by an application.

I cannot find any documentation on such extra features. It seems that one other poster referenced this idea in https://github.com/harfbuzz/harfbuzz/issues/1310#issuecomment-441752995

If such extra features existed, they might be useful in testing the new HarfBuzz support in Adobe InDesign 2020, to see if HarfBuzz is being used for all scripts.

**Comment by behdad** [comment]
That has indeed been the case since October 2018:
https://github.com/harfbuzz/harfbuzz/commit/a62f37d6fa412b799b7247b813f6e65a968e7645

Need documentation. @n8willis

**Comment by mhosken** [comment]
IIRC the features are HARF and BUZZ (in uppercase) respectively.
