### ISSUE TITLE
Unnecessary check in hb_buffer_t::set_masks?

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2073]
In [hb_buffer_t::set_masks](https://github.com/harfbuzz/harfbuzz/blob/34ed8e7218d9147a6ccd99198db594cf8f66f61b/src/hb-buffer.cc#L430) we have this check:

https://github.com/harfbuzz/harfbuzz/blob/34ed8e7218d9147a6ccd99198db594cf8f66f61b/src/hb-buffer.cc#L441

But `hb_buffer_t::set_masks` used only once in [hb_ot_shape_setup_masks](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape.cc#L727) and we already filtered this case there:

https://github.com/harfbuzz/harfbuzz/blob/34ed8e7218d9147a6ccd99198db594cf8f66f61b/src/hb-ot-shape.cc#L740

Should we remove it and maybe add an `assert`?

PS: and probably, we should use `UINT_MAX` or `HB_FEATURE_GLOBAL_END` instead of `(unsigned int)-1`.

**Comment by behdad** [comment]
Just removed the fact path in that function please. Though I'm happy leaving it as is. No assert.

And yes, please use `HB_FEATURE_GLOBAL_END`. That was agreed much later than the code you referenced.

**Comment by RazrFalcon** [comment]
Ok. I will send a pull request than.

Thanks for the invitation, by the way. But I don't confident enough to push stuff directly to the master yet. =)

**Comment by behdad** [comment]
> Thanks for the invitation, by the way. But I don't confident enough to push stuff directly to the master yet. =)

You don't have to.  That's just to recognize you as a HarfBuzz developer, and also so we can assign issues to you. :)  Anyone who reads our code and suggests improvements is a HarfBuzz developer to me. :)
