### ISSUE TITLE
Remove _POSIX_C_SOURCE from hb-blob.cc

### ISSUE THREAD

**Issue by Rhialto** [harfbuzz/harfbuzz#2084]
There is this block of code in `src/hb-blob.cc`:
```
/* https://github.com/harfbuzz/harfbuzz/issues/1308
 * http://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html
 * https://www.oracle.com/technetwork/articles/servers-storage-dev/standardheaderfiles-453865.html
 */
#if !defined(_POSIX_C_SOURCE) && !defined(_MSC_VER) && !defined(__NetBSD__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-macros"
#define _POSIX_C_SOURCE 200809L
#pragma GCC diagnostic pop
#endif
```
I propose to remove it completely, on the grounds that it is doing more harm than good.

It seems the #define was originally introduced in commit f88d3bd7e407d332bb04688344c54756d24128c9 in 2013 with no other commit message than "Fix build with Sun compiler". It did not say which problem there actually was, nor how this change was supposed to fix it. Probably this fix was not the right thing to do, but we cannot be certain of it since we don't know what the problem was.

Since then, it has been adjusted several times, every time because it caused problems. Recently, it came to my attention, via openjdk11 which contains an outdated copy of harfbuzz.

The first reference, #1308, is one of those compilation problems.

The second reference, http://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html, at first seems to say that defining a feature macro *adds* features, but if you read it more carefully, including the final paragraphs, it explains that it *removes* features. As such, defining _POSIX_C_SOURCE is almost never the right thing to do. You do it only if your program claims to use POSIX features only, and nothing more. I doubt this is true for anything like harfbuzz.

The third reference, https://www.oracle.com/technetwork/articles/servers-storage-dev/standardheaderfiles-453865.html, does not even exist any more.

https://github.com/harfbuzz/harfbuzz/pull/1492 is a pull request to move this block around... because it caused problems on Solaris... which was the whole original reason for the define, and now it caused problems even there.

The issue I encountered was similar to https://github.com/harfbuzz/harfbuzz/pull/702 and you can look it up at http://mail-index.netbsd.org/tech-pkg/2020/01/03/msg022447.html

Summarizing I propose to remove the `#define` and the stuff around it on the grounds that it is harmful, outdated, and probably never should have been there in the first place.

**Comment by behdad** [comment]
I believe I added this because on the Sun compiler mentioned mmap and friends were not declared unless themacro was set.

I agree with removing it completely and let systems deal with it themselves.

**Comment by ebraminio** [comment]
Removed it, thanks for the detailed file :)
