### ISSUE TITLE
Manually enable lookup by index?

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#2092]
Does anyone know if there's a way (supported or otherwise) to manually add a lookup, specified by index ID, to the shaping plan? This'll be needed for implementing OpenType justification, which embeds lookup IDs in the JSTF table.

**Comment by ebraminio** [comment]
Now that your raised it, WDYT about some API for exposing JSTF bits itself, I mean what API you wished HarfBuzz could provide for jstf parsing?

**Comment by simoncozens** [comment]
The problem about providing an API is that the JSTF table is badly specified - the only things it tells you about are "extender glyphs" (without saying what to *do* with extender glyphs) and modification lists, which are actually GSUB/GPOS lookup IDs and are not useful at the layout engine level. Also it can return JstfMax records which abuse GPOS lookups to specify a maximum stretch/shrink without specifying *how* to expand it - works fine for the space glyph, which is the example, but not for anything else, and needs to be re-thought to work with variable fonts. It's all a terrible mess.

Probably the only thing we can sensibly do with this mess is have the client say "shape this glyph string with suggestion level 1/2/3/4 of expansion/contraction" so that HB can then apply the extensionEnableGSUB etc. lookups from JSTF. And you just have to ignore JstfMax because there's nothing sensible that can be done with it. Maybe the ability to return the extender glyphs for a font would be useful for completeness, but I am not sure that a layout engine can do anything sensible with the extender glyph list either. :-(

I wish they had tried implementing this while spec'ing it out...

**Comment by khaledhosny** [comment]
I don’t think we want to do this, it is a slippery slop and some clients are going to misuse it and shoot themselves in the foot. one of the HarfBuzz design principles it to not allow clients to do The Wrong Thing™.
