### ISSUE TITLE
Arithmetic overflow during kern[-1] feature parsing

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2102]
In this line

https://github.com/harfbuzz/harfbuzz/blob/8ffc9add2237899afc57184ad3297404659bc1cd/src/hb-common.cc#L805

if `feature->start` is `HB_FEATURE_GLOBAL_END`, `feature->end` will have a random value.

It doesn't seem to affect anything, but maybe we should check it anyway.

**Comment by behdad** [comment]
Sure we can fix this.

**Comment by behdad** [comment]
> will have a random value.

Aren't unsigned overflows welldefined in C / C++?

**Comment by behdad** [comment]
(unlike signed overflows, which are undefined-behavior).
