### ISSUE TITLE
Making HarfBuzz binding friendly

### ISSUE THREAD

**Issue by ahmetsait** [harfbuzz/harfbuzz#2104]
I've been working on [dlang](https://dlang.org) bindings for harfbuzz ([bindbc-harfbuzz](https://github.com/DlangGraphicsWG/bindbc-harfbuzz)) and I gathered some of the experience and difficulties in the process.  
Here is a simplified version of how I generate bindings, let's take this sample header as a starting point:
```C
typedef enum {
  HB_MEMORY_MODE_DUPLICATE,
  HB_MEMORY_MODE_READONLY,
  HB_MEMORY_MODE_WRITABLE,
  HB_MEMORY_MODE_READONLY_MAY_MAKE_WRITABLE
} hb_memory_mode_t;

typedef struct hb_blob_t hb_blob_t;

HB_EXTERN hb_blob_t *
hb_blob_create (const char        *data,
		unsigned int       length,
		hb_memory_mode_t   mode,
		void              *user_data,
		hb_destroy_func_t  destroy);

HB_EXTERN hb_blob_t *
hb_blob_create_from_file (const char *file_name);
```
- Use [DStep](https://github.com/jacob-carlborg/dstep) to generate D stubs from headers:
	```D
	enum hb_memory_mode_t
	{
		HB_MEMORY_MODE_DUPLICATE = 0,
		HB_MEMORY_MODE_READONLY = 1,
		HB_MEMORY_MODE_WRITABLE = 2,
		HB_MEMORY_MODE_READONLY_MAY_MAKE_WRITABLE = 3
	}

	struct hb_blob_t;

	hb_blob_t* hb_blob_create (
		const(char)* data,
		uint length,
		hb_memory_mode_t mode,
		void* user_data,
		hb_destroy_func_t destroy);
	}

	hb_blob_t* hb_blob_create_from_file (const(char)* file_name);
	```
- Use [Binding-Dynamizer](https://github.com/ahmetsait/Binding-Dynamizer) to create dynamic bindings from static bindings:
	```D
	enum hb_memory_mode_t
	{
		HB_MEMORY_MODE_DUPLICATE = 0,
		HB_MEMORY_MODE_READONLY = 1,
		HB_MEMORY_MODE_WRITABLE = 2,
		HB_MEMORY_MODE_READONLY_MAY_MAKE_WRITABLE = 3
	}

	struct hb_blob_t;

	version(BindHB_Static)
		hb_blob_t* hb_blob_create (
			const(char)* data,
			uint length,
			hb_memory_mode_t mode,
			void* user_data,
			hb_destroy_func_t destroy);
	else
	{
		private alias fp_hb_blob_create = hb_blob_t* function (
			const(char)* data,
			uint length,
			hb_memory_mode_t mode,
			void* user_data,
			hb_destroy_func_t destroy);
		__gshared fp_hb_blob_create hb_blob_create;
	}

	version(BindHB_Static)
		hb_blob_t* hb_blob_create_from_file (const(char)* file_name);
	else
	{
		private alias fp_hb_blob_create_from_file = hb_blob_t* function (const(char)* file_name);
		__gshared fp_hb_blob_create_from_file hb_blob_create_from_file;
	}
	```
- Lots of manual editing:
	```D
	enum : int // Assumed to be int but I'm not a C guru
	{
		HB_MEMORY_MODE_DUPLICATE = 0,
		HB_MEMORY_MODE_READONLY = 1,
		HB_MEMORY_MODE_WRITABLE = 2,
		HB_MEMORY_MODE_READONLY_MAY_MAKE_WRITABLE = 3
	}
	alias hb_memory_mode_t = int; // C doesn't have type-safe enums anyway

	struct hb_blob_t;

	version(BindHB_Static)
		hb_blob_t* hb_blob_create (
			const(char)* data,
			uint length,
			hb_memory_mode_t mode,
			void* user_data,
			hb_destroy_func_t destroy);
	else
	{
		private alias fp_hb_blob_create = hb_blob_t* function (
			const(char)* data,
			uint length,
			hb_memory_mode_t mode,
			void* user_data,
			hb_destroy_func_t destroy);
		__gshared fp_hb_blob_create hb_blob_create;
	}

	static if (hbSupport >= HBSupport.v2_6_3) // Somewhere between 1.7.2 ~ 2.6.3 this appears
	{
		version(BindHB_Static)
			hb_blob_t* hb_blob_create_from_file (const(char)* file_name);
		else
		{
			private alias fp_hb_blob_create_from_file = hb_blob_t* function (const(char)* file_name);
			__gshared fp_hb_blob_create_from_file hb_blob_create_from_file;
		}
	}
	```
Essentially it looks something like this: [generate-hb.bat](https://gist.github.com/ahmetsait/8bc1835f812fb70cbc31de6a5cf58bb4) + editing

Aside from all the improvements that can be done for DStep to make the process smoother and require less hand editing, there are many things that would immensely help for an easier and also higher quality binding on library developers' side:
- **Proper `#include` instead of abusing preprocessor**  
  D (among many other languages) do not use preprocessor for accessing symbols outside of the file. The fact that harfbuzz requires people to include `hb.h` instead of allowing invidual headers to be used is neither replicatable in other languages (or necessary) nor does it makes sense. This makes the process hacky in that I had to use `-DHB_H_IN`, `-DHB_OT_H_IN` and such so libclang doesn't just error out. The problem is further enchanced by some headers that do not include all files it uses such as `hb-shape-plan.h` not including `hb-face.h` because it is recursively done so by `hb-font.h`. This makes automation of import statements hard to pull off unless they are all marked as public. (I tried to avoid this so global namespace is not polluted as much)  
  Since C has no concept of local include/import, I couldn't decide whether to generate public imports or add private ones by hand.
  
- **Versioning of symbols in machine readable form**  
  BindBC-HarfBuzz currently supports choosing 2 different versions of the library: 1.7.2+ and 2.6.3+. Ideally I would want to support choosing any version possible but since there is no machine readable list of added/removed symbols for every version (also no semantic versioning what-so-ever); which means it is unfeasable to handcraft such capability thus I've chosen to just support 1.7.2 and the latest (2.6.3). What I did was to extract exported symbols via `dumpbin /exports libharfbuzz-0.dll` (which is also annoying to parse) as to easily determine which symbols are introduced between two versions (1.7.2 and 2.6.3). But this is not even reliable because what symbols gets compiled in changes based on configurations & environment.  
  I was expecting ABI Laboratory to have all these functionality but reality is often disappointing. If header files had easy to parse version comments something like: `/* Since: 1.6.0 BEGIN */` ~ `/* Since: 1.6.0 END */` I could wrap them with `static if (hbSupport >= 10600) { ... }` as well. I hope you consider this option.
  
- **64bit binaries with DirectWrite & Uniscribe glue on windows for testing**  
  Providing these would allow me to test the dynamic binding better without having to compile harfbuzz myself (something I don't want to bother) but I'm not holding my breath.
  
- **Less macros if possible**  
  Some of the macro functions are especially interesting that they cause name collisions with actual functions and screw up the automation but I don't know what could be done here as those are probably made for manual inlining & performance. I manually converted them and disabled the dynamic lib symbols entirely.  
  Maybe an `#ifdef` could enable body of those actual functions inside the headers but not much solution comes to my mind.
  
- **GLib / GObject introspection + template files (.tmpl)**  
  I have no idea what to do here. Currently the binding has no support for these because (1) I never use GTK-related libs, (2) I couldn't find proper documentation on how this works, and (3) I don't want to torture myself trying to build GLib or HarfBuzz on Windows. D actually does have complete [GTK bindings](https://gtkd.org) so I could hook them up easily.  
  At least a bit of documentation could help people like me. (Tell me if I'm missing something.)
  
- **Having always explicit enum types**  
  Some of the enums are bit flags but not defined to be `unsigned int`. Most (all?) enums are just not explicitly typed and I don't remember if C standard is reliable in this case. I can't tell slapping int onto them is the right thing but that's what I did for the time being.
  
- **Knowing library names for different distro & platforms**  
  https://github.com/DlangGraphicsWG/bindbc-harfbuzz/blob/v0.2.1/src/bindbc/hb/dynload.d#L47-L89  
  Complete speculation, I don't know whether same library name is something guaranteed across distros or not. I also don't own a Mac to check actual names myself. If there is an easy way to learn these let me know. Also, FreeType Windows builds are named `freetype.dll` but harfbuzz depends on `libfreetype-6.dll` and I would expect a `harfbuzz.dll` rather than a `libharfbuzz-0.dll` per Windows naming convention sake.
  
- **Dependency hell**  
  This isn't exactly binding related but Windows download of FreeType dll doesn't depend on anything meanwhile the one that comes with HarfBuzz depends on libraries that depends on other libraries that depends on other libraries that depends on...  
  `libgcc_s_sjlj-1.dll` seems to be there for error handling?  
  I don't know if it is all that hard to support Windows without things like GLib or not but I hope to be able see better _native_ Windows support in the future.

I think these are all the things that came to my mind. I wish library developers could remember that the world doesn't consist of C/C++/Python only :) That would make us miserable binding creators' life easier.

All that being said, I'm thankful for the hard work of you developers and I'm glad that this library exist.

**Comment by Gillibald** [comment]
I don't see what prevents you from writing a binding. You say that your automation isn't compatible with HarfBuzz but that might be only your issue.

Building HarfBuzz is trivial and requires very little. I had no issues writing this: https://github.com/mono/SkiaSharp/tree/master/binding/HarfBuzzSharp.Shared

This runs on all major platforms.

**Comment by ebraminio** [comment]
I think these are nice feedbacks, I read them curiously but should say the ones who make build compatibility break are unlikely to be changed and we can discuss the other if someone actually had provided a PR for them.

> Knowing library names for different distro & platforms

Have a look at final part of README, it provided something related at least, unlikely we can do better however.

Will try to provide some comment about the rest later maybe. Thanks

**Comment by khaledhosny** [comment]
Nothing actionable here. HarfBuzz is not doing anything unusual for a C library, and OP is either using broken tools or have some, IMO, unreasonable expectations. There existing binding for HarfBuzz for basically almost any popular programming language, so it can’t be that broken.
