### ISSUE TITLE
'hb_ot_layout_get_ligature_carets' can't get correct caret array data

### ISSUE THREAD

**Issue by anydream** [harfbuzz/harfbuzz#2105]
This line of code
```cpp
unsigned int result_caret_count = 0;
```
Causes the returned array length always be zero.

**Comment by ebraminio** [comment]
There should be some other issue, https://github.com/harfbuzz/harfbuzz/blob/f51bb6ee7bd4ebca9b432851adc527ec086360fe/test/api/test-ot-ligature-carets.c#L39 checks that it returns a correct answer and `result_caret_count` is passed to the table so is filled correctly. Am closing but feel free to comment here. Thanks
