### ISSUE TITLE
No CFF, CFF2 parsing tests?

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2107]
I could not find any CFF, CFF2 related tests. Afaiu, we need CFF and CFF2 only to get glyph extents during fallback shaping. And we have tests only for `glyf`,`CBDT` and `sbix` tables.

I can work on pull request if needed.

**Comment by ebraminio** [comment]
The patch on #2016 has a [currently failing!] has CFF/CFF2/vf-CFF2 tests, would you like to resolve the fails and add more tests like the tests there? I believe adding more tests like that is a good way to test them. I should also add a test for the failing case Khaled have fixed recently.

**Comment by RazrFalcon** [comment]
I will take a look.
