### ISSUE TITLE
Qt Creator support

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2109]
Currently, you cannot work with `harfbuzz` in Qt Creator. There are essentially three problems:

1. It loads only `*.h` and `*.c` files. `*.hh` are partly loaded and `*.cpp` are not loaded at all. 
1. You have to rewrite build steps, because `harfbuzz` cannot be built with a simple `cmake --build . --target all`, which QtC uses.
1. You have to set `G_TEST_SRCDIR` manually, otherwise tests do not work.

And I should note that Qt Creator uses cmake-server and doesn't parse cmake files by itself. So this is probably a configuration issue.

I haven't tests in CLion and MSVS, but I guess they will have the same problems.

**Comment by ebraminio** [comment]
I guess VSCode and its Microsoft provided C++ support extension is much better than QtC as it doesn't try to involve itself in the build system, supports all the file name extensions, provides autocompletion and raising syntax error etc without even knowing about the build system explicitly. Its Rust support also is known to be one of the best. Have you tried it? CMake isn't our development build system but nowadays provided only to make embedding harfbuzz possible for more targets like MSVC and with having 'harfbuzz.cc' it has become of less importance even.

I feel I like to say if QtC doesn't support autotools, it is also not support for development from our stand point also so like to close this as it is very unlikely that we do something about it but feel free to tweak and upload PR to improve anything that can ease you development process, and feel free to try autotools (our current supported development build script) + VSCode with C support which I use personally (I am installing editorconfig extension also to make tabs 8 spaces width, should open our provided .editorconfig file once after opening vscode so the changes can be applied)

Thanks

**Comment by RazrFalcon** [comment]
Makes sense. So you are using VSCode with C/C++ plugin (on Linux)? Can you share your task.json? Or how you manage building and testsing.

I'm not tied to QtC, I'm simply trying to understand the development process. And I was spoiled by Cargo.

>Its Rust support also is known to be one of the best. Have you tried it? 

The best Rust support by far is in IDEA. It's unbelievably slow (IDEA, not the Rust plugin), but it has a rich feature set.
There is also rust-analyzer plugin for VSCode, but it still in development.

> QtC doesn't support autotools

It does, kinda. Still beta. But it also wasn't able to load all files.

**Comment by ebraminio** [comment]
> Makes sense. So you are using VSCode with C/C++ plugin (on Linux)? Can you share your task.json? Or how do you manage building and testsing.

Yes but I use its terminal :) nice to aggregate some task.json but having some .vscode folder in root doesn't feel good. I use simple commands very similar to what our CI bots, the different CircleCI bots specially, use. Things like ./autogen.sh, make -j9 check, am not using a different folder for build most of the times even. Am using something like "make clean && make -j9 CC=clang CXX='clang++ -fsanitize=address' LD=ld.lld check" to run the test suit when we have an ASan issue and sometimes 'make -j9 && ./test/api/some-api-test' to run an API test. Had documented how to use gdb/lldb with libtool but can find it on the tracker.

> I'm simply trying to understand the development process.

I had the same struggle just some years ago so I feel what you say :)

**Comment by RazrFalcon** [comment]
Thanks. I will try using VSCode with autotools.

**Comment by ebraminio** [comment]
> And I was spoiled by Cargo.

Actually I had a raw idea in mind someday ago about whether we could use Cargo as build system instead migrating to Meson, if we want to migrate to Rust someday why not starting with adopting its build system, but have found Cargo isn't ready for handling C/C++ projects yet, or, is it?

**Comment by RazrFalcon** [comment]
`librsvg`  was ported completely to rust, afaik. autotools was left for compatibility, since it's more common in Linux distros and lirsvg still builds as a C library by default.

And yes, Cargo is Rust only and don't think it will be changed anytime soon. You can actually use it too build harfbuzz, which is what I do in rustybuzz, but it's still too strange to use Cargo for a C/C++ project. I thinks that meson is a better choice .

**Comment by ebraminio** [comment]
Rustybuzz looks very interesting! Will try to learn, experience and may contribute something back to it. Thanks!

**Comment by RazrFalcon** [comment]
Thanks! It's still in a very early stage. Right now it's basically a wrapper between harfbuzz and third-party crates, like ttf-parser.
