### ISSUE TITLE
Confusing results from hb-shape (cli) and font sizes

### ISSUE THREAD

**Issue by sciurius** [harfbuzz/harfbuzz#2111]
I'm trying to find out the effect of the miscellaneous font size arguments to the `hb-shape` tool.

    $ hb-shape LiberationSans-Regular.ttf LaVAT
    [L=0+1139|a=1+1139|V=2+1214|A=3+1214|T=4+1251]

When typesetting this text af fontsize 20 I get correct displacements when multiplied by fontsize/1000. Good.
Now with a font size:

    $ hb-shape --font-size=20 LiberationSans-Regular.ttf LaVAT
    [L=0+36|a=1+36|V=2+42|A=3+42|T=4+39]
    $ hb-shape --font-size=40 LiberationSans-Regular.ttf LaVAT
    [L=0+36|a=1+36|V=2+40|A=3+40|T=4+39]

These metrics are definitely not proportional to the font size.

If I understood the harfbuzz basics correctly, the metrics are based on the desired font size (important for hinting) but since the results are integer scaling is required to get accurate precision. The `hello-harfbuzz-opentype` demo program uses font size 36 and gives advance width 20.0156 for the initial `L`. 

What magic arguments do I need to supply to `hb-shape` to get the same, and as I assume correct, values as the demo program?

**Comment by khaledhosny** [comment]
This might be the effect of hinting since the `hb-shape` uses FreeType font functions by default (and FreeType applies hinting). Try with `--font-funcs=ot` which should be equivalent to the demo program.

**Comment by sciurius** [comment]
Thanks for the suggestion.

    $ hb-shape --font-size=36 --font-funcs=ot LiberationSans-Regular.ttf LaVAT
    [L=0+20|a=1+20|V=2+21|A=3+21|T=4+22]

Now the metrics seems to match the example. Hoewever, the precision is lost.

**Comment by behdad** [comment]
> Now the metrics seems to match the example. Hoewever, the precision is lost.

We use integers internally.  Use a larger `--font-size` as suits you.

**Comment by sciurius** [comment]
The font size controls hinting and glyph details, so setting this to a large value is not appropriate.

Using the harfbuzz library there are `hb_font_set_ptem` and `hb_font_set_scale`. I would expect hv-shape command line options `--font-ptem` and `--font-size` (or `--font-ppem`) to correspond with these.

**Comment by behdad** [comment]
> Using the harfbuzz library there are `hb_font_set_ptem` (for hinting) and `hb_font_set_scale` (for precision). I would expect hv-shape command line options `--font-ptem` and `--font-size` (or `--font-ppem`) to correspond with these.

That's exactly the case.
```
  --font-size=1/2 integers or 'upem'     Font size (default: upem)
  --font-ppem=1/2 integers               Set x,y pixels per EM (default: 0; disabled)
  --font-ptem=point-size                 Set font point-size (default: 0; disabled)
```
