### ISSUE TITLE
Add MVAR tests

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2115]
Looks like `_hb_ot_metrics_get_position_common` is never executed during testing.

**Comment by ebraminio** [comment]
https://coveralls.io/builds/28196393/source?filename=src/hb-ot-metrics.cc#L50

It is tested IIRC

**Comment by RazrFalcon** [comment]
Strange. I've added a `printf` and it never showed. But it should break tests since they are comparing the output.

**Comment by ebraminio** [comment]
IIRC printf wasn't reliable but fprintf(stderr, ) is more reliable.

**Comment by RazrFalcon** [comment]
Same. It used only by `_hb_fallback_shape`, as far as I can tell.

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzz/blob/master/test/api/test-ot-metrics.c#L39 should test it, otherwise, I don't know.

**Comment by RazrFalcon** [comment]
Yes, this is probably the issue. I'm using `cmake -DHB_CHECK=ON -Bbuild -H. -GNinja && ninja -Cbuild && CTEST_OUTPUT_ON_FAILURE=1 ninja -Cbuild test`  from `TESTING.md` and it probably doesn't run those tests.

**Comment by ebraminio** [comment]
Don't use cmake for development :)

**Comment by RazrFalcon** [comment]
Yes, running via autotools helped, but tests are failing at:

```
running subset fuzzer against ./fonts/clusterfuzz-testcase-minimized-hb-subset-fuzzer-5761434614497280
./fonts/clusterfuzz-testcase-minimized-hb-subset-fuzzer-5761434614497280
Traceback (most recent call last):
  File "./run-subset-fuzzer-tests.py", line 111, in <module>
    run_dir (os.path.join (srcdir, "fonts"))
  File "./run-subset-fuzzer-tests.py", line 98, in run_dir
    text, returncode = cmd ([hb_subset_fuzzer, path])
  File "./run-subset-fuzzer-tests.py", line 48, in cmd
    text = "" if is_debug_mode else text.decode ("utf-8").strip ()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 2388: invalid start byte
```

Is this an expected behavior?

My actions:
```
./autogen.sh
make -j16 CPPFLAGS='-DHB_DEBUG_SUBSET=100' && make -j16 check
```

**Comment by ebraminio** [comment]
It is a timeout fail, remove the testcase and feel free to run just that specific test.

**Comment by RazrFalcon** [comment]
I see. Thanks.

**Comment by ebraminio** [comment]
The testcase shouldn't timeout of course and that python script should be able to parse output of the failed command, whole things feel rusty here :/

**Comment by RazrFalcon** [comment]
There was a huge stack trace.
