### ISSUE TITLE
ZERO WIDTH NO-BREAK SPACE (U+FEFF) does not seem to disable the dotted circle in Bengali script

### ISSUE THREAD

**Issue by qsajib** [harfbuzz/harfbuzz#2116]
When a vowel sign (e.g., the U+09BE in Bengali script) is typeset in HarfBuzz,
as tested with XeLaTeX in TeX Live 2019, the sign is rendered with a
dotted circle; the dotted circle acts as a base character.
Using the NO-BREAK SPACE (U+00A0, NBSP), a _standalone_ vowel sign can be typeset
disabling the dotted circle but a white space is introduced.
The ZERO WIDTH NO-BREAK SPACE (U+FEFF, ZWNBSP), as the name suggests,
can be useful in typesetting a standalone vowel sign, i.e., disabling the
dotted circle as well as _without requiring_ extra white space.  In our test, it was
found that the ZWNBSP does not disable the dotted circle (see the attached screenshot).

Question remains, is the ZWNBSP (U+FEFF) accepted as a base character
to disable the dotted circle in rendering the combining marks?  If not,
maybe it is necessary to update the Unicode/OpenType accordingly?

The attached files (.tex, attached as .txt, and .pdf) contain some examples
regarding this issue.  The NotoSerifBengali-Regular.ttf font was used to produce
the examples.  The .tex file was processed with |xelatex| under TeX Live 2019 on
a GNU/Linux computer.

![Screenshot_2020-01-21_03-22-52](https://user-images.githubusercontent.com/13224047/72752563-7857b500-3bfd-11ea-86b4-94c97e12c143.png)

[bangla-script-test-zwnbsp.pdf](https://github.com/harfbuzz/harfbuzz/files/4087566/bangla-script-test-zwnbsp.pdf)

[bangla-script-test-zwnbsp.txt](https://github.com/harfbuzz/harfbuzz/files/4087578/bangla-script-test-zwnbsp.txt)

**Comment by kberry** [comment]
As Jonathan Kew suggested separately: maybe \XeTeXcharglyph"09BE is an alternate path to typesetting the glyph by itself?

**Comment by qsajib** [comment]
@kberry Yes, indeed. The \XeTeXglyph\XeTeXcharglyph"09BE can be used to typeset the glyph by itself as Jonathan Kew suggested.  Also, the Node renderer with lualatex-dev in TL does the similar job as Norbert Preining suggested separately.  But as you said for Jonathan's suggestion, which I think also applies to Norbert's suggestion for now, that they are _alternate_ paths to typesetting a glyph by itself.

**Comment by behdad** [comment]
> Question remains, is the ZWNBSP (U+FEFF) accepted as a base character to disable the dotted circle in rendering the combining marks? If not, maybe it is necessary to update the Unicode/OpenType accordingly?

It's not in our Indic shaper.

**Comment by behdad** [comment]
I'm not sure there's anything to  fix here.

**Comment by dscorbett** [comment]
Unicode only recommends U+00A0 as a base for standalone marks. It doesn’t say how to avoid the base’s extra space when the mark is spacing. There is nothing to fix in HarfBuzz until Unicode clarifies what to do.
