### ISSUE TITLE
[aat] Adding '-vrt2' to --features='smcp' breaks small caps in Apple Chancery and Baskerville

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2123]
```$ util/hb-view /Library/Fonts/Apple\ Chancery.ttf --features "+smcp" Smallcaps > smallcaps_working.png```

![smallcaps_working](https://user-images.githubusercontent.com/1021784/72992713-e74f2c80-3dfc-11ea-9a43-5e6a15b6b3c5.png)

```$ util/hb-view /Library/Fonts/Apple\ Chancery.ttf --features "+smcp,-vrt2" Smallcaps > smallcaps_broken_by_vrt2.png```

![smallcaps_broken_by_vrt2](https://user-images.githubusercontent.com/1021784/72992753-f59d4880-3dfc-11ea-8783-48da917eb629.png)

```$ util/hb-view /Library/Fonts/Baskerville.ttc --features "+smcp" Smallcaps > b_smallcaps_working.png```

![b_smallcaps_working](https://user-images.githubusercontent.com/1021784/72993015-575db280-3dfd-11ea-901c-4d34f0ce6ca3.png)

```$ util/hb-view /Library/Fonts/Baskerville.ttc --features "+smcp,-vrt2" Smallcaps > b_smallcaps_broken_by_vrt2.png```

![b_smallcaps_broken_by_vrt2](https://user-images.githubusercontent.com/1021784/72993024-5cbafd00-3dfd-11ea-9dfa-c8c4353f9c99.png)

**Comment by behdad** [comment]
Might be how the font is designed.  How about coretext backend?

**Comment by drott** [comment]
Doesn't break in CoreText backend:

```$ ./hb-view --shapers=coretext /Library/Fonts/Baskerville.ttc --features="+smcp,-vrt2" "SmallCaps" > baskerville_smcp_-vrt2_coretext.png```

![baskerville_smcp_-vrt2_coretext](https://user-images.githubusercontent.com/1021784/74434900-09702380-4e6c-11ea-91dc-cfda59710641.png)

**Comment by behdad** [comment]
Thanks.  Needs debugging then.  Not sure when I will get to that.

**Comment by behdad** [comment]
I cannot reproduce this. @drott can you?

**Comment by behdad** [comment]
Humm. I cannot reproduce this with 2.6.5 from April 2020 either.

**Comment by drott** [comment]
Not reproducible with  `Apple Chancery; 13.0d1e4; 2017-06-08` and `Baskerville; 13.0d1e10; 2017-06-15` from Mac OS 12.5 - I'll see if I can access the Mac OS 10.15 version.

**Comment by drott** [comment]
Reproducible with HarfBuzz 684ff3e0cd77dfa5e83c2110ea613b8b9678d4f5 and the same font versions (looks like the fonts have not been updated and stayed on the same version for most recent Mac OS revisions). After bisecting, fixed by 1faf0caae165f680689610b20c467b9308275308 and the fix for #2307. So thanks, @jfkthame!
