### ISSUE TITLE
Prefering AAT over GSUB breaks upright layout for Hiragino

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2124]
The [change to always prefer AAT over GSUB](https://github.com/harfbuzz/harfbuzz/commit/0414341ac576c4403231f507e216c7716c8f0828) triggered issues with upright vertical layout for the Hiragino fonts. 

On Mac OS 10.10 through 10.12 Hiragino Mincho & Kaku seem to have both, mort/morx and GSUB tables. Their AAT table does have the vertical substitution feature, but there it behaves rather like `vrt2` than `vert`, which means, it rotates Latin glyphs and digits sideways. This is not what's desired. 

But because AAT does not have a distinction between `vert`-style and `vrt2` style rotations, i.e. desired punctuation rotation and "Latin-sideways" rotation are not split, we would likely be better off using GSUB in these cases.

I would propose to experimentally partially revert 0414341ac576c4403231f507e216c7716c8f0828 in the sense of only preferring AAT over GSUB when the direction is horizontal. 

If that's too broad (what's your opinion @jfkthame ?) - then I'd be glad if we could similar to as before, fingerprint the fonts in question, and keep preferring GSUB for those that have too broad AAT vertical substitution and rotate Latin and digits sideways.

On Mac OS 10.13 and later, it seems that OpenType `vert` is preferred over AAT style vertical substitutions and some of the vertical fonts do not have mort/morx anymore.

More details about the issues after the roll in: https://bugs.chromium.org/p/chromium/issues/detail?id=1040017

**Comment by drott** [comment]
CC @kojii

**Comment by jfkthame** [comment]
The proposal to partially revert (i.e. only prefer AAT for horizontal) seems OK to me. The reason to prefer AAT shaping was primarily for some complex scripts such as Indic, so reverting for vertical shaping won't affect that.

**Comment by drott** [comment]
This seems to work, and an experimental bot run with this CL 115d7124c9fcddbac4282897699dd91ce83858c0 
https://chromium-review.googlesource.com/c/chromium/src/+/2017435 does not result in AAT-triggered vertical text failures.

**Comment by drott** [comment]
> The proposal to partially revert (i.e. only prefer AAT for horizontal) seems OK to me.

Thank you, Jonathan, for the quick feedback. I'm glad we could address this quickly.
