### ISSUE TITLE
Does reading past hb_buffer_t::len allowed?

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2136]
During `in-house/tests/khmer-misc.tests[9]` test, at this point:

https://github.com/harfbuzz/harfbuzz/blob/cf5f94675669154ab84695e5b24a1d54d2ad8c5e/src/hb-ot-shape-normalize.cc#L106

`buffer->len` is 2, but `buffer->out_len` is 3. So `buffer->prev()` will read past `buffer->len`.

This is fine, since we have allocated at least 32 items at this point (default chunk). But maybe in some specific situations it can actually read 32th item and crash. I'm not sure how `hb_buffer_t` manages this.

On the other hand, we are detecting Unicode properties of garbage or zeroed data.

The real problem is that in [rustybuzz](https://github.com/RazrFalcon/rustybuzz) I'm using `[0..buffer->len]` slices, and I'm catching out-of-bounds panic. I've added a hack for this specific case, but maybe this can be fixed in harfbuzz itself.

CLI: 

```
hb-shape test/shaping/data/in-house/fonts/3998336402905b8be8301ef7f47cf7e050cbb1bd.ttf -u U+179F,U+17C5
```

**Comment by behdad** [comment]
> `buffer->len` is 2, but `buffer->out_len` is 3. So `buffer->prev()` will read past `buffer->len`.

`buffer->prev()` reads from `out_buf`, which is non-empty.  There's no access violation in this.  I think you are implementing buffer differently in rustybuzz and that's where the problem is popping up.

**Comment by RazrFalcon** [comment]
Yes, I guess it was a bit premature. Turns out that it's a pretty common behavior in harfbuzz. And I initially thought that `len` is like a hard stop, but it turns out it just a hint.

I just wanted to clarify this behavior, since I thought that data after `len` is not initialized.

**Comment by behdad** [comment]
> And I initially thought that `len` is like a hard stop, but it turns out it just a hint.

I think you still are misunderstanding how our buffer works.  Accessing past len is not allowed.  You are missing the differentiation between main buffer and out-buffer indexing.

**Comment by RazrFalcon** [comment]
Yes, I still have no idea how it works. But I was able to successfully port it, so it's ok for now.

**Comment by behdad** [comment]
At any point the buffer contents are represented by the concatenation of two slices:

`out_buf[0:out_len] + buf[i:len]`

Hope that helps.
