### ISSUE TITLE
[aat] Consider not activating HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION on OpenType `vert` activation

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2137]
When `hb_feature_t` with feature tag `vert` is activated for a `hb_buffer_t` set for shaping, according to the [feature translation table](https://github.com/harfbuzz/harfbuzz/blob/bd55d4b49fcd1ac1335e60ead1fe9941e7b01f8c/src/hb-aat-layout.cc#L164) `HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION` gets activated for `vert` as well as for `vrt2`. Since according to information received from Apple their fonts were in the past mostly built to behave like `vrt2` and were rotating glyphs sideway, perhaps it makes sense to not activate `HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION` for `vert` but only for `vrt2`?

**Comment by behdad** [comment]
The translation table you are suggesting we change was also received from Apple.  Let me ask this: why do you care?  Why is anyone manually setting `vert` or `vrt2`?  Oh, or is it because we automatically do that when direction is vertical?

**Comment by drott** [comment]
Can't recall or find more context anymore, sorry. Ok to close this. Closest I could find was a (confused) bug that I filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=1041825 - and maybe https://bugs.chromium.org/p/chromium/issues/detail?id=899718.
