### ISSUE TITLE
Implementation for Perl

### ISSUE THREAD

**Issue by sciurius** [harfbuzz/harfbuzz#2143]
I followed the directions you gave in issue #1913 and succeeded to create a perl module to provide a interface with (a subset of) harfbuzz.
The building process is set up to use a platform supplied harfbuzz library if present, and otherwise tries to build the single-file `harfbuzz.cc`. This works great.

I include a copy of the harfbuzz `src` directory in the source kit for the perl module. Is it sufficient to include a copy of the top-level `COPYING` in my copy of the `src` directory, or do I need to include a particular licensing text?

Thanks for the great job!

**Comment by ebraminio** [comment]
`COPYING` is okay, guess your are fine from https://tldrlegal.com/license/mit-license standpoint :) Please make sure you are updating your copy regularly (like doing it as always ran yet optional part of the build system) and preferably don't use unreleased checkouts and APIs/features instability and so. Thanks :)
