### ISSUE TITLE
Improve glyph draw design

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2145]
Made at Behdad request on discussing and finalizing the API in GitHub. See https://github.com/harfbuzz/harfbuzz/issues/2145#issuecomment-589993318 also

Our current hb_font_draw_glyph/hb_draw_funcs_t design can be considered something stable and useful. It is able to draw a multilayer COLR/CPAL Emoji color fonts even[[1]](https://github.com/harfbuzz/harfbuzz/blob/master/src/main.cc#L127-L242)! But we like to make sure it is the best design we can go with. That's why I've upload a one-click away disable #2141 patch for and these #2142 #2144 to may improve its design.

See things like fonttools [BasePen](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/pens/basePen.py#L187) and its [other awesome pens](https://github.com/fonttools/fonttools/tree/master/Lib/fontTools/pens). I think we like to have a design like that to make us or the clients capable of implementing things like that or even implementing a rasterize on top of our API easily.

One request one may have is being able to call path commands callbacks from client code. The other request is being able to implement quadratic to cubic or, cubic-line to calls translation but those aren't useful if one doesn't have access to current point/state (as one needs to know starting point to translate those call) but our current API, tends to be immutable, doesn't hold the current point.

#2142 tries to tackle the issue by keeping current point and state in the object, #2144 goes the other way by passing state through the callbacks. The first looks more what BaePen does in fonttools but both sounds a bit off to me right now so guess we should create a separate object called pen to support these usecases and keep `hb_draw_funcs_t` intact. Maybe that pen object should return a `hb_draw_funcs_t` object that can be passed to `hb_font_draw_glyph` and having different kind of callbacks with having current point also.

Getting this right would be a nice thing considering if we get an in-house rasterizer someday, one will not only be able to rasterize a glyph of a font but call the rasterizer for their custom paths or implement several utilities like curve to lines translator using an established design, it makes testing of those functionalities also easier.

**Comment by ebraminio** [comment]
I am trying to convince myself more and more this is minimal but acceptable API we can provide and can build other things on top of it but am of course love to hear any feedback about the API before the release.

**Comment by ebraminio** [comment]
Skia uses quadTo instead quadratic, may we should also?

**Comment by ebraminio** [comment]
Useful links, 
* https://github.com/fonttools/fonttools/tree/master/Lib/fontTools/pens (added a pen #2170 should add more things from there)
* https://gist.github.com/ebraminio/10dbdd5c256f1f14fa094ca6f4b98173 (minimal rasterizer)
* https://github.com/google/skia/blob/master/src/ports/SkFontHost_FreeType_common.cpp#L186-L200 (we need to provide different, may our .get_bitmap can support them on the fly, a get_bitmap with callback would be nice)
* https://github.com/personal-mirrors/freetype2/blob/master/include/freetype/ftoutln.h#L54-L80 (nice to have them, things like FT_Outline_Get_CBox FT_Outline_Get_BBox are also important, we probably should probably provide an outline store for multiple use)
* https://github.com/personal-mirrors/freetype2/blob/master/src/base/ftoutln.c#L905 (guess a fake bold / embolden should be implemented for hb_font_t to alter `hb_position_t`s also)
* Should study Win32 and macOS related APIs also

**Comment by ebraminio** [comment]
I've implemented proxy for DirectWrite/GDI/FreeType/CoreText on #2183 and there and learned interesting things from them,
* All of them provide points as double but I think hb_position_t is what we should go for anyway.
* DirectWrite doesn't have quadratic call, just cubic ones which is called bezier https://github.com/harfbuzz/harfbuzz/pull/2183/files#diff-bad9a60fe707c3516a7fa7f2bf2d190bR1007
* DirectWrite batches its calls with `AddBeziers`/`AddLines` and calls it `move_to`/`close_path` `BeginFigure` and `EndFigure`
* DirectWrite returns negative `y` and I had to put a minus to make it similar to other platform calls.
* DirectWrite has `SetFillMode` with having two options, `D2D1_FILL_MODE_ALTERNATE` and
`D2D1_FILL_MODE_WINDING`, useful for drawing multiple overlapping glyphs maybe.
* CoreText stores a path, useful for further processing, we perhaps should provide a different abstraction for storing paths.
* CoreText `CGPathApply` calls our `void *user_data` a `void *info`.
* CoreText `CGPathApply` doesn't have separate callbacks and all the different elements should be handled with one callback by user. https://github.com/harfbuzz/harfbuzz/pull/2183/files#diff-7388b4fd559324d062507056fc7dcd38R1166
* FreeType's `FT_Outline_Decompose` is simpler as not having explicit struct for callbacks, similar to our `hb_font_extents_t` which has some reserved fields for being future proof.
* GDI can return `GLYPHMETRICS` with the same call.

Anything to learn?

**Comment by ebraminio** [comment]
Skia apparently favors DirectWrite negativity of paths instead positive sign so is negative what is getting from FreeType https://github.com/google/skia/blob/master/src/ports/SkFontHost_FreeType_common.cpp#L701 but not for DirectWrite https://github.com/google/skia/blob/master/src/utils/win/SkDWriteGeometrySink.cpp#L82

**Comment by ebraminio** [comment]
It sounds like https://github.com/harfbuzz/harfbuzz/commit/9fe0dc3464391e1cd51c01c499b6110d99895d25 draw_helper_t is something more nice to have exposed, as an API, specially it is nice for providing calling the commands by users, but it is stateful and needs to be tweaked for each call, so maybe we can have two APIs, one the current API and exposing something similar to draw_helper_t later with some naming like pen or something.

**Comment by Harachie** [comment]
Hi @ebraminio ,

I like the current implementation very much.
For me it's easy to use and I can easily fill a skia path object with the provided callback/user info strategy.
I cannot think of an more straight forward way.
This api provides everything you need to get the glyph paths.

Thank you very much for this effort!

Kind regards,
Bastian

**Comment by ebraminio** [comment]
Thank you @Harachie and @khaledhosny This is I think the first time a positive feedback about the API is provided :) As Behdad leaned toward disabling it I moved it behind a HB_EXPERIMENTAL_API flag. The implementation is of course needs more work on making it more performant but I felt the API, specially after Khaled's suggestion, has become good. It is even possible to proxy FreeType #2185 and any other API from this API.

The release delay however is considered because of the API and the other minor public APIs which is understandable yet I don't think if I didn't add them a sooner release was going to happen. I understand keeping master always ready to release is a value, I think getting these kind of feedback and fixing all the fuzzer found issues I could receive when the API was merged is also a value and we can keep a balance. Yet am waiting for Behdad to give his API reviews so can go for a release. Thanks

**Comment by behdad** [comment]
I've thought about this for days. I have most of it mapped out but some questions remain. Now I need to find a way to write them all down...

I keep coming back to "cooperative inheritance" and/or mixin ideas which almost address everything we need but not fully.

While I figure out how to write that all down, those interested can familiarize themselves with the concepts by reviewing the following article and its references: https://www.artima.com/weblogs/viewpost.jsp?thread=281127

**Comment by behdad** [comment]
I'll just start leaving small comments on each aspect of the design at a time, hoping that that would break my writer's block of how to put all the various aspects of the design into writing...

So I'm now convinced that we should introduce `hb_pen_t`.  The current draw_funcs will be called `hb_pen_funcs_t` and will be attached to a pen same way that `hb_font_funcs_t` attach to `hb_font_t`.  They provide the "instance data" part of any pen "subclass".  So `hb_pen_set_funcs()`.

`hb_font_draw_glyph(font, gid, pen, flags?` then should invoke a `draw_glyph` method on the font-funcs.  So https://github.com/harfbuzz/harfbuzz/pull/2185 is on right track.  Just fix the macro whatever issue by moving the `get_` prefix into method names.  I don't see why that's an issue.

With `draw_glyph` a font backend function one would get outlines that correspond to metrics of the same font.  So that's good.  This reminds me that, I believe, we should add a `get_metric` font-func and turn `hb_ot_metrics_get_position` then will be unnecessary and `hb_font_get_metric` will call into it.  Filed https://github.com/harfbuzz/harfbuzz/issues/2425  These combined would allow one to implement a full autohinter using the font-funcs functionality.

**Comment by behdad** [comment]
Nit: rename the arguments of calls to be:
- `move_to (x0, y0)`
- `line_to (x1, y1)`
- `quadratic_to (x1, y1, x2, y2)`
- `cubic_to (x1, y1, x2, y2, x3, y3)`

Those should receive `hb_pen_t` as first argument, and the callbacks receive `user_data` as well as `pen_data` just like font-funcs do.

The need for per-callback `user_data` and `destroy` is questionable indeed.  It was added to support binding callables from other languages (eg. C++ or Python).  But Python bindings seem to be using libffi to generace C code on the fly so they don't use the closure.  But I think we should keep it for consistency and completeness.  While I want to keep `hb_pen_t` and `hb_pen_funcs_t` very light, I don't think we should remove those.  We can optimize for when all are nullptr, like what I just filed for font-funcs: https://github.com/harfbuzz/harfbuzz/issues/2427

**Comment by behdad** [comment]
Between yesterday and today I questioned whether we should have any pens at all.  So today I'm reconsidering going back to a very simple API very much like what you have.  What you have is fine if it wasn't trying to decompose quadratics and other things inside of it...

Let me write down today what my objection to current implementation is and why I wanted to introduce a whole array of pens.  Then we can decide that maybe we can remove things from your implementation and ship that.  A pen library would be nice but there's no reason that should be in HarfBuzz... Though if it does get exported to Python, that can be a much faster alternative to some of the pens there.  I'll try to open the pandora box from scratch and document what I'm seeing today. :)

**Comment by ebraminio** [comment]
> [..]. Just fix the macro whatever issue by moving the get_ prefix into method names. I don't see why that's an issue.

It introduces a large change, something I wanted to know whether is needed before doing so, and, a bit unrelated to the previous, there is a name collision as there will be two `user_data`, one to pass the draw funcs and the other to `hb_destroy_func_t`.

```
typedef hb_bool_t (*hb_font_draw_glyph_func_t) (hb_font_t *font, void *font_data,
  hb_codepoint_t glyph, const hb_draw_funcs_t *funcs,
  void *call_user_data, void *user_data);
```

> I keep coming back to "cooperative inheritance" and/or mixin ideas which almost address everything we need but not fully.

I believe we will some limitation with providing that as a C API, and the fact pen like functionalities need to store a current point and we tend to provide some immutable objects. The idea behind providing different patches was to just show limitation we will have with implementing such ideas, guess didn't go well apparently however.

**Comment by behdad** [comment]
> > [..]. Just fix the macro whatever issue by moving the get_ prefix into method names. I don't see why that's an issue.
> 
> It introduces a large change, something I wanted to know whether is needed before doing so, and, a bit unrelated to the previous, there is a name collision as there will be two `user_data`, one to pass the draw funcs and the other to `hb_destroy_func_t`.

Yeah if we introduce a pen, then the pen data doesn't need to be passed in separately.


> ```
> typedef hb_bool_t (*hb_font_draw_glyph_func_t) (hb_font_t *font, void *font_data,
>   hb_codepoint_t glyph, const hb_draw_funcs_t *funcs,
>   void *call_user_data, void *user_data);
> ```
> 
> > I keep coming back to "cooperative inheritance" and/or mixin ideas which almost address everything we need but not fully.
> 
> I believe we will some limitation with providing that as a C API, and the fact pen like functionalities need to store a current point and we tend to provide some immutable objects. The idea behind providing different patches was to just show limitation we will have with implementing such ideas, guess didn't go well apparently however.

Sure you definitely did show the problems.  But then in other issue you say you don't know what the problem is.   I'm fine with not adding pens right now, but would require simplifying the implementation to remove most of draw-helper "sanitization".  Right now I'm reading T2CharString to check the corner cases there.  I'll comment more later today.

**Comment by ebraminio** [comment]
> I'm fine with not adding pens right now, but would require simplifying the implementation to remove most of draw-helper "sanitization".

Makes sense, those specially were needed to make end path callback possible however so that should be revisited also.

**Comment by behdad** [comment]
I like to focus on this, in light of Boring Expansion project...

cc @rsheeter.

**Comment by rsheeter** [comment]
I immediately wonder how plausible it is to bolt this onto piet-gpu :)

Would also dearly love something that wrote better svgs than hb-view => svg while still running faster than FontTools. IIUC this API would be a reasonable tool to power that?

**Comment by dfrg** [comment]
piet-gpu doesn’t currently vend a C API, so at the moment, you’d need to call into HarfBuzz from the Rust side. But you could definitely pass the appropriate functions to hb_font_draw_glyph to build a kurbo::BezPath and feed that to piet-gpu for rendering. 

I’m fairly certain there are plans for a C API in the future.

**Comment by behdad** [comment]
This work happened in https://github.com/harfbuzz/harfbuzz/pull/3411

**Comment by behdad** [comment]
> Would also dearly love something that wrote better svgs than hb-view => svg [or vector drawable or w/e suspiciously svg-like thing] while still running faster than FontTools. 

See https://github.com/harfbuzz/harfbuzz/pull/3411#issuecomment-1038950990

> IIUC this API would be a reasonable tool to power that?

Absolutely.
