### ISSUE TITLE
unexpected font extents and glyph extents for Apple Color Emoji font

### ISSUE THREAD

**Issue by zhuah** [harfbuzz/harfbuzz#2148]
I'm shaping some emoji glyphs with font size 16 using Apple Color Emoji font on macOS. 

when i call to `hb_font_get_h_extents`, it gives me ascender 16 and descender -5, and `hb_font_get_glyph_extents` gives y_bearing 16 and height -16.
the emoji glyph is totally above baseline, and the line height is 21.

when i shaping ascii characters, it works as intend, the line height is 16.

am i missing something, or should i ignore descender for emoji font? thanks.

**Comment by ebraminio** [comment]
guess the description https://github.com/harfbuzz/harfbuzz/commit/c9796d15e1ec5f8939f8b1ae368cb3352b6a9cb9#diff-6130f6f64e7ad63c31d565ad4a3dd447 would be useful, cc @khaledhosny

**Comment by zhuah** [comment]
I have changed my layout algorithm, line height will always be font size*1.25, and force vertical-align of color glyphs(emoji glyph) to middle of the line, regardless of their font extents and glyph extents.
