### ISSUE TITLE
Where to find files used by python scrips?

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2150]
`gen-arabic-table.py` requires `ArabicShaping.txt UnicodeData.txt Blocks.txt`.

`gen-tag-table.py` requires `languagetags language-subtag-registry`.

etc.

But I could not find those files in the repo, neither links from where to download them.

Yes, after some googling you can find them, but maybe it would be better if links were included in the scripts itself? They can also auto-download them.

**Comment by ebraminio** [comment]
They are for development use, guess unicode files aren't that stable in file format and path and as they should be ran only once for every unicode version bump it didn't felt more automation would be need, more comment from Behdad would be nice of course.

**Comment by behdad** [comment]
Feel free to add a readme file or otherwise document.  With each version of Unicode the scripts might need updating because they make assumptions that might have changed in the standard.

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzz/pull/2438 will download them automatically also
