### ISSUE TITLE
Consider providing std::unique_ptr based scope helpers?

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2152]
In [this Chromium CL](https://chromium-review.googlesource.com/c/chromium/src/+/2034111/3/third_party/harfbuzz-ng/utils/hb_scoped.h) we're introducing Chromium project wide std::unique_ptr based scope helpers for easier memory management when using HarfBuzz API from C++ in Blink or the fuzzers. The location for this code is not optimal and a wider number of clients would benefit if we could add those to upstream.

WDYT?

Example code below:

```
template <typename T>
struct always_false : std::false_type {};

template <class T>
struct HbSpecializedDeleter {
  inline void operator()(T* obj) {
    static_assert(always_false<T>::value,
                  "HbScoped is only allowed for HarfBuzz types that have a "
                  "deleter specialization.");
  }
};

// Defines a scoped pointer type HbScoped based on std::unique_ptr and using the
// corresponsing HarfBuzz destructor to commonly used public HarfBuzz types. The
// interface of HbScoped is the same as that of std::unique_ptr.
//
//  void MyFunction() {
//    HbScoped<hb_blob_t> scoped_harfbuzz_blob(
//        hb_blob_create(mydata, mylength));
//
//    DoSomethingWithBlob(scoped_harfbuzz_blob.get());
//  }
//
// When |scoped_harfbuzz_buffer| goes out of scope, hb_blob_destroy() is called
// for the hb_blob_t* created from hb_blob_create().
template <class T>
using HbScoped = std::unique_ptr<T, HbSpecializedDeleter<T>>;

#define SPECIALIZED_DELETER_FOR_HARFBUZZ_TYPE(TYPE, DESTRUCTOR) \
  template <>                                                   \
  struct HbSpecializedDeleter<TYPE> {                           \
    inline void operator()(TYPE* obj) { DESTRUCTOR(obj); }      \
  };

#define HB_TYPE_DESTRUCTOR_PAIRS_REPEAT(F) \
  F(hb_blob_t, hb_blob_destroy)            \
  F(hb_buffer_t, hb_buffer_destroy)        \
  F(hb_face_t, hb_face_destroy)            \
  F(hb_font_t, hb_font_destroy)            \
  F(hb_set_t, hb_set_destroy)              \
  F(hb_subset_input_t, hb_subset_input_destroy)

HB_TYPE_DESTRUCTOR_PAIRS_REPEAT(SPECIALIZED_DELETER_FOR_HARFBUZZ_TYPE)
```

**Comment by ebraminio** [comment]
I think providing some header only lightweight cpp RAII helper is possible, something that handles https://github.com/harfbuzz/harfbuzz/pull/1962 also but without STL support so can be used inside the project also, leaving wrapping it with smart pointers to users, like https://github.com/harfbuzz/harfbuzz/issues/1917#issuecomment-523462094 "let's imagine we switch to Rust someday, better to not have components that are C++ specific" same argument holds here also I believe.

**Comment by behdad** [comment]
Yes yes.  Agree with adding header-only C++ helpers.

**Comment by behdad** [comment]
Let's discuss the functionality first then get to implementation.

We probably like a version that does `reference()` upon initialization as well?  Or no.

**Comment by behdad** [comment]
@jfkthame I suppose Firefox has similar needs / homemade remedies?

**Comment by behdad** [comment]
I think I like it more if in the header files that we define those types we add something like:
```
typedef struct hb_buffer_t hb_buffer_t;
#ifdef __cplusplus__
template <> hb_destructor<hb_buffer_t> { ... };
#endif 
```

**Comment by drott** [comment]
Works for me, even better if the mapping between type and destructor is closer to the declarations.

**Comment by jfkthame** [comment]
> @jfkthame I suppose Firefox has similar needs / homemade remedies?

AFAIR, we just create/destroy our HB objects manually - it's limited to few enough places that it hasn't been much of an issue. I guess having unique_ptr-like helpers could make things a bit cleaner, though.

**Comment by behdad** [comment]
I feel like we should declare the reference() function for each type as well while at it.  Something like:
```
#if __cplusplus__ >= whateverneeded
template <> hb_something<hb_buffer_t> : hb_type_whatever<hb_buffer_reference, hb_buffer_destroy> {};
#endif 
```

**Comment by behdad** [comment]
The full set of functions all our types have are:
```
HB_EXTERN hb_buffer_t *
hb_buffer_get_empty (void);

HB_EXTERN hb_buffer_t *
hb_buffer_reference (hb_buffer_t *buffer);

HB_EXTERN void
hb_buffer_destroy (hb_buffer_t *buffer);

HB_EXTERN hb_bool_t
hb_buffer_set_user_data (hb_buffer_t        *buffer,
                         hb_user_data_key_t *key,
                         void *              data,
                         hb_destroy_func_t   destroy,
                         hb_bool_t           replace);

HB_EXTERN void *
hb_buffer_get_user_data (hb_buffer_t        *buffer,
                         hb_user_data_key_t *key);
```

**Comment by behdad** [comment]
I started prototyping this.  This is what I have so far:
```cxx

#ifndef HB_CPLUSPLUS_H
#define HB_CPLUSPLUS_H

#include "hb.h"

HB_BEGIN_DECLS
HB_END_DECLS

#ifdef __cplusplus

#if !(__cplusplus >= 201103L)
#error "HarfBuzz C++ helpers require C++11"
#endif

namespace hb {


template <typename T>
struct vtable;

template <typename T>
struct shared_ptr
{
  using v = vtable<T>;

  shared_ptr (T *p = nullptr) : p (p) {}
  shared_ptr (const shared_ptr &o) : p (v::reference (p)) {}
  //XXX move constructor
  //XXX copy assign
  //XXX move assign
  ~shared_ptr () { v::destroy (p); }

  // operator T * () const
  // get() const
  // get_const() const

  // operator * () const { return get (); }
  // operator -> () const { return get (); }

  // operator bool

  // operator == ??

  //static get_empty()
  //reference()
  //destroy() { ...; p = nullptr; }
  //set_user_data
  //get_user_data

  private:
  T *p;
};

template <typename T,
	  T * (*get_empty) (void),
	  T * (*reference) (T *),
	  void (*destroy) (T *),
	  hb_bool_t (*set_user_data) (T *,
				      hb_user_data_key_t *,
				      void *,
				      hb_destroy_func_t,
				      hb_bool_t),
	  void * (*get_user_data) (const T *,
				   hb_user_data_key_t *)>
struct vtable_t
{
  static constexpr auto get_empty_ = get_empty;
};

#define HB_DEFINE_VTABLE(name) \
	template<> \
	struct vtable<hb_##name##_t> \
	     : vtable_t<hb_##name##_t, \
			&hb_##name##_get_empty, \
			&hb_##name##_reference, \
			&hb_##name##_destroy, \
			&hb_##name##_set_user_data, \
			&hb_##name##_get_user_data> {}

HB_DEFINE_VTABLE (buffer);
HB_DEFINE_VTABLE (blob);
HB_DEFINE_VTABLE (face);
HB_DEFINE_VTABLE (font);
HB_DEFINE_VTABLE (font_funcs);
HB_DEFINE_VTABLE (set);
HB_DEFINE_VTABLE (map);
HB_DEFINE_VTABLE (shape_plan);
HB_DEFINE_VTABLE (unicode_funcs);

#undef HB_DEFINE_VTABLE


} // namespace hb

#endif /* __cplusplus */

#endif /* HB_CPLUSPLUS_H */
```

The version check already hit a snag as https://github.com/harfbuzz/harfbuzz/pull/2362#issuecomment-617849929

**Comment by behdad** [comment]
> ```c++
> 
>   //reference()
>   //destroy() { ...; p = nullptr; }
> ```

Calling `reference()` on shared_ptr returns a new raw reference.  Calling `destroy()` destroys the ref held by the shared_ptr and sets shared_ptr to nullptr.  I don't like that calling `reference(); destroy()` isn't a no-op but I think I'm fine with that.

**Comment by behdad** [comment]
Looking at https://en.cppreference.com/w/cpp/memory/shared_ptr maybe `reset` and `swap` also.  The swap won't be atomic.

**Comment by drott** [comment]
And then the usage would be `hb::shared_ptr<blob_t>  my_blob(hb_blob_create(...));` for example? Seems like that would work for Chrome. We mostly need the move contructor and the call to destroy, I think.

**Comment by behdad** [comment]
> And then the usage would be `hb::shared_ptr<blob_t> my_blob(hb_blob_create(...));` for example? Seems like that would work for Chrome. We mostly need the move contructor and the call to destroy, I think.

Exactly. If you initialize it with a pointer it takes over ownership of that reference.  If you assign to it a pointer it references it and keeps its own.  The move+destructor indeed make it a unique_ptr replacement.
