### ISSUE TITLE
[subset] add_link/resolve_links for absolute offset

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#2156]
The current implementation of `add_link` & `resolve_links` appears to assume a parent object containing an offset to a child object is also the base of the offset, maybe with some constant bias.
This is not the case with Private dict in CFF/CFF2, since its offset is stored in FontDict while its offset base is CFF/CFF2 itself (could be said global or absolute).

I am thinking to add a new function `add_link_abs` or a boolean flag to `add_link` to allow its offset to be calculated as absolute.

Better idea?

**Comment by blueshade7** [comment]
Let me interpret no feedback as “ok to proceed”.

I am also going to allow offset to be signed 2-byte or 4-byte, in addition to unsigned.
So in addition to `is_absolute`, going to add `is_signed` flag to `link_t` struct so that `check_assign` does the right thing.
https://github.com/harfbuzz/harfbuzz/blob/c31762e9e89bc440d21a94d8da34608d1649dc85/src/hb-serialize.hh#L70-L76
I am hesitant to steal two additional bits out of `position`, so going to separate flags from it.

`hb_is_signed` does not compile with `OT::IntType` as T. Any workaround?

**Comment by garretrieger** [comment]
One thought, is it possible to do a c->push() at the start of serializing the CFF table so that you have a parent obj and then use the start of the table as the base for calling c->add_link(...)?

**Comment by blueshade7** [comment]
I tried that, and didn't work... `base` arg to `add_link` is a mere char pointer. `link.bias` is calculated as diff between the current obj head from base at`add_link` time, which may change by `resolve_links` time.
A general grand solution may be allowing arg base to be another object, not just a pointer (maybe with an optional constant bias), but this seems an overkill. AFAIK no such table exists positioned at an offset based from another arbitrary table. Either from its immediate parent, or from the very beginning (this problem case).

**Comment by garretrieger** [comment]
Ah got it. In that case, I agree that the absolute offset is the way to go.

**Comment by behdad** [comment]
> I am hesitant to steal two additional bits out of `position`, so going to separate flags from it.

No.  Please steal.  Position doesn't need anything like even 20 bits.

**Comment by behdad** [comment]
If I would to do it, I'd make add_link take one or two additional optional parameters.  Maybe an enum.  Like to have three modes:
- Default: relative to start of current object
- Relative to end of current object; that's useful for name table and other places where there's a pool at the end of an object.
- Absolute.

**Comment by blueshade7** [comment]
Merging `add_link_abs()` into `add_link()` sounds nice, but one coding issue remains.

To set `is_signed`, I need to test signed/unsigned on T which may be `IntType` or `OffsetTo`. `hb_is_signed()` works on neither directly. `IntType` has `::type` but `OffsetTo` doesn't.

To work around this, I will add `typedef OffsetType type;` to `OffsetTo`, so  I can do:
```
link.is_signed = hb_is_signed (T::type);
```
Better idea?
(In the current PR, I dodged this problem by assuming T is always unsigned for `add_link()`, always `IntType` for `add_link_abs()`. Yes cheat)

**Comment by behdad** [comment]
Why don't we instead define hb_int_min and hb_int_max for those types?

**Comment by behdad** [comment]
OffsetTo derives from Offset which already has `typedef Type type`.

**Comment by behdad** [comment]
We should make `hb_is_signed` work for types that define a `::type`.  That's easy!

**Comment by behdad** [comment]
Or probably better.  Have a new metafunction that returns T::type if that exists, otherwise returns T.

**Comment by behdad** [comment]
> Or probably better. Have a new metafunction that returns T::type if that exists, otherwise returns T.

If you check hb-null.hh, there's lots of similar functions.

**Comment by blueshade7** [comment]
>OffsetTo derives from Offset which already has typedef Type type.

True, but it is typedef'ed to IntType, not a primitive type like uint32_t. So another level of `T::type` if exists otherwise `T` required. Much appreciated if you can write this. I tried it myself but gave up. I am new to SFINAE.

**Comment by blueshade7** [comment]
Never mind, I came up with an implementation of `hb_get_type(T)`.
If it is to be called with OffsetTo, caller needs to do: `hb_get_type (hb_get_type (T))`.
Please review. @behdad

**Comment by behdad** [comment]
Reviewed.  Thanks.

**Comment by blueshade7** [comment]
PR#2174 & PR#2163 merged to master. Let me close this.
