### ISSUE TITLE
Vertical alignment is off with vertical layout

### ISSUE THREAD

**Issue by epico** [harfbuzz/harfbuzz#2169]
Japanese chars and Latin chars in the same line do not vertically align when the pango context's gravity is set to PANGO_GRAVITY_EAST.

Tested with:
```
pango-view --text="あーいうえお abcde" --gravity east --gravity-hint line --font="Noto Sans JP 24" --annotate 1
```

I wrote one pango patch to work around this issue.
It works, but the patch may be not correct.

URL: https://gitlab.gnome.org/GNOME/pango/merge_requests/168

Could you help check the issue in harfbuzz?

**Comment by khaledhosny** [comment]
I don’t think there is an issue here for HarfBuz to fix.

**Comment by epico** [comment]
Could you help check why hardbuzz returns non-zero values in vertical layout for x_offset and y_offset?

URL: https://gitlab.gnome.org/GNOME/pango/merge_requests/168
