### ISSUE TITLE
[subset] pop_pack() call in end_serialize()

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#2177]
While working on PR#2176, the following piece of code caught my attention.
https://github.com/harfbuzz/harfbuzz/blob/a94d1af193ac1601a1725266dbb0dd51195af98b/src/hb-serialize.hh#L164-L169

Why do we need pop_pack() call in end_serialize()?
copy_bytes() called by copy_blob() appears to be already taking care of data left in the buffer unpacked.

Moreover, by calling pop_pack() with share=true by default may find a match in packed_map then data get discarded & not sent to output.

**Comment by behdad** [comment]
> Why do we need pop_pack() call in end_serialize()?

Because `start_serialize()` does a `push<Type> ()`.  The corresponding pop is in `end_serialize()`.

**Comment by behdad** [comment]
> Moreover, by calling pop_pack() with share=true by default may find a match in packed_map then data get discarded & not sent to output.

Agree we should call it with share=false.

**Comment by blueshade7** [comment]
OK, then I will add `false` to `pop_pack()`.
