### ISSUE TITLE
[subset] GSUB closure taking too long with a fuzzed font

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#2186]
subset_fuzzer is taking long time with a fuzzed font: https://github.com/harfbuzz/harfbuzz/blob/master/test/fuzzing/fonts/clusterfuzz-testcase-minimized-hb-subset-fuzzer-5763024094232576

As the result gcc-valgrind bot often times out as seen in: https://circleci.com/gh/harfbuzz/harfbuzz/127382?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Most of time appears to be spent in a while loop in `hb_ot_layout_lookups_substitute_closure` iterating up to 27 times.
https://github.com/harfbuzz/harfbuzz/blob/07504569d5e7ca2f7da987fc016fc4141eeca263/src/hb-ot-layout.cc#L1529

This is especially wasteful with this fuzzed font, because its `face->num_glyphs` is actually zero, i.e., containing no valid glyphs.

**Comment by ebraminio** [comment]
We should apply or lower some of our limits to alleviate the issue. Same goes for https://crbug.com/oss-fuzz/19802 and https://crbug.com/oss-fuzz/18529 I think, can you have a look at them to find some common pattern for limiting?

**Comment by blueshade7** [comment]
They all appear to be different issues, but 19802 may be similar in that GSUB subsetter is trying to process thousands of glyphs when num_glyphs=32. We may throw out gid >= num_glyphs. But We can’t prevent fuzzer to come up with a font containing a very large number as num_glyphs. Actually 18529 has num_glyphs=16384.

**Comment by blueshade7** [comment]
Actually oss-fuzz/19802 is different, `hb_ot_layout_collect_features` is collecting thousands of feature indices from thousands of scripts.

**Comment by ebraminio** [comment]
> They all appear to be different issues [..]
> Actually oss-fuzz/19802 is different, [..]

Correct. That is somehow what I meant as I think limiting operations to sane and usual cases is our only approach here like what happened in shaping also.

**Comment by blueshade7** [comment]
I think each case needs to be taken a look at separately for a different solution.
Created PR#2188 where `hb_closure_context_t::flush()` removes all glyphs above num_glyphs.

**Comment by ebraminio** [comment]
> I think each case needs to be taken a look at separately [..]

Yes, am referring to pattern of limiting than a particular fix, like https://github.com/harfbuzz/harfbuzz/commit/baf7779d2d6e4810168a8f036bbf8f9e6493dd1a

To be honest even shaping isn't prefect as for https://crbug.com/oss-fuzz/13943 which is the only open shaping timeout I came with #1647 but it wasn't good enough as one other font can issue the same timeout by providing multiple tables instead there, yet, the idea I think is to put some font-wide limitations that some other font can't replicate using some minor modification.

**Comment by ebraminio** [comment]
So, this can be closed now? Would you like to have a look at the other linked timeouts also? Thanks!

**Comment by blueshade7** [comment]
Yes, let's close this. I think I will open issues for the other two.

**Comment by ebraminio** [comment]
That sounds great. Thanks!
