### ISSUE TITLE
Burmese and ZERO WIDTH NON-JOINER

### ISSUE THREAD

**Issue by Ali-Alzyoud** [harfbuzz/harfbuzz#2189]
It seems that ZERO WIDTH NON-JOINER does not work with the Burmese script.
For example when rendering following string:  `"\u1006\u200C\u1031";`

Expected output:  ![out](https://user-images.githubusercontent.com/8048094/75115684-a64f6f80-5669-11ea-8ef7-db011f7efd60.png)

Current    output: ![out](https://user-images.githubusercontent.com/8048094/75115653-34772600-5669-11ea-928c-2ee0d197b3a1.png)

project to show the issue:
https://github.com/Ali-Alzyoud/Harfbuzz-Burmese

**Comment by Ali-Alzyoud** [comment]
If there are any more details It will be a delight to provide.

**Comment by khaledhosny** [comment]
Padauk-book.ttf is a hybrid OpenType/Graphite font and by default HarfBuzz would prefer Graphite over OpenType. If I force the OpenType shaper, I get your expected output:
```
$ $ hb-view Padauk-book.ttf -u 1006,200C,1031 --shaper=ot
```
![a](https://user-images.githubusercontent.com/93914/76546668-9373d200-6494-11ea-9c07-bc81379ff218.png)

Graphite layout is entirely in the hands of the font, so if you think the Graphite output is a bug, please raise the issue with the font developers.

**Comment by Ali-Alzyoud** [comment]
thank you, I try other font and issue does not appear
