### ISSUE TITLE
Reimplement hb_set_t::del_range()

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#2193]
The current implementation of `hb_set_t::del_range()` is inefficient especially when there are few values to delete in the specified range.
Also, when all values are deleted from a page, it is left empty. It should be removed instead.

**Comment by garretrieger** [comment]
After you remove pages the compact() function in hb-set.hh can be used to correct the page map and shrink the pages array. See process() for an example of how to use.

**Comment by behdad** [comment]
> After you remove pages the compact() function in hb-set.hh can be used to correct the page map and shrink the pages array. See process() for an example of how to use.

I was thinking doing without that, just remove pages that fall completely in the range to be deleted.  That way the runtime of the del_range won't be small if the range is small.

**Comment by garretrieger** [comment]
Oh, got it. Agreed, that sounds like a good idea.

**Comment by blueshade7** [comment]
pushed a tentative fix to branch set-del-range then fuzzed font #2186 timed out for me... karma?
