### ISSUE TITLE
A shape fuzzer timeout case

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2204]
I have apparently <s>a recent regression</s> (maybe not) of an infinite loop with this font,

[1746cad6bc3fb2b355db50a5af37c9b58d9ad376.zip](https://github.com/harfbuzz/harfbuzz/files/4263528/1746cad6bc3fb2b355db50a5af37c9b58d9ad376.zip)

`clang test/fuzzing/hb-shape-fuzzer.cc test/fuzzing/main.cc -Isrc src/harfbuzz.cc -DHB_NO_MT -lm -fno-exceptions -g -Og && ./a.out 1746cad6bc3fb2b355db50a5af37c9b58d9ad376`

```
Program received signal SIGINT, Interrupt.
0x00005555555b8ee5 in hb_set_t::get_major (this=0x555555710f70, 
    g=<optimized out>) at src/hb-set.hh:876
876	  unsigned int get_major (hb_codepoint_t g) const { return g / page_t::PAGE_BITS; }
(gdb) bt
#0  0x00005555555b8ee5 in hb_set_t::get_major (this=0x555555710f70, 
    g=<optimized out>) at src/hb-set.hh:876
#1  0x00005555555b8f12 in hb_set_t::page_for_insert (this=0x555555710f70, 
    g=361016) at src/hb-set.hh:843
#2  0x0000555555594bd5 in hb_set_t::add (this=0x555555710f70, g=361016)
    at src/hb-set.hh:289
#3  0x00005555555a16f2 in OT::CmapSubtableLongSegmented<OT::CmapSubtableFormat12>::collect_unicodes (this=<optimized out>, out=0x555555710f70)
    at src/hb-ot-cmap-table.hh:554
#4  0x00005555555565d7 in test_font (font=0x55555570fb00, cp=1744896000)
    at test/fuzzing/../api/test-ot-face.c:48
#5  0x0000555555556532 in LLVMFuzzerTestOneInput (data=<optimized out>, 
    size=23293) at test/fuzzing/hb-shape-fuzzer.cc:53
#6  0x0000555555556a2d in main (argc=2, argv=0x7fffffffdc58)
    at test/fuzzing/main.cc:15
```
Pretty sure this is a recent regression, can you @garretrieger @blueshade7 have a quick look at it? Thanks

**Comment by blueshade7** [comment]
Above stack shows hb_set_t so I thought I might have broken it, but del_range() is not called so it is not the case. Anyways looking further.

**Comment by blueshade7** [comment]
It is not an infinite loop, just being slow. It eventually completed for me.

It is taking time where it is reading all code points from the cmap table format 12 which supports 32-bit code points and glyph IDs.  Ranges in this table are fuzzed to contain very wide 32-bit ranges with glyph IDs beyond 0xFFFF.

Currently `hb_face_collect_unicodes()` simply calls out to each cmap sub-table reading code. Checking code points against HB_UNICODE_MAX is already in place but it does not appear to be enough to read this fuzzed cmap in reasonable time.

If we want to limit this further, I suggest pass-in num_glyphs into the cmap reading code to filter out code points mapped to glyph IDs beyond it. I don't know when OpenType starts supporting 32-bit glyph IDs, but hard-coding 0xFFFF as max gid into cmap reader is probably not a good idea.

How shall we proceed? @ebraminio

**Comment by ebraminio** [comment]
> I don't know when OpenType starts supporting 32-bit glyph IDs, [..]

"breaking 64k glyphs limit is risky" for OpenType 2.0 https://twitter.com/belleveinvis/status/1107252313008168960 so not soon I think.

**Comment by ebraminio** [comment]
> I don't know when OpenType starts supporting 32-bit glyph IDs, but hard-coding 0xFFFF as max gid into cmap reader is probably not a good idea.

Worth to have change I think.

**Comment by blueshade7** [comment]
ok I think I will create PR to pass in num_glyphs into cmap 12 and other sub-tables supporting 32-bit gids namely 8 & 13. In theory, 16-bit gids could be also filtered out, but not sure worth it.

**Comment by ebraminio** [comment]
Had to revert the fix e90213868b121af72d19b6022a671ebe72ff55aa 

@garretrieger is this related to #2167 I guess? (should do a bisect to pinpoint the change confidently of course) Can you also have a look #2208 fix and https://github.com/harfbuzz/harfbuzz/pull/2208#issuecomment-592598496 to brainstorm the fix with Ariza? Thanks!

**Comment by ebraminio** [comment]
> @garretrieger is this related to #2167 I guess? 

Hmm, see the issue with a99134c5 also so not sure :/

**Comment by garretrieger** [comment]
Also the CMAP 14 change should only affect subsetting and not the shaper.

**Comment by blueshade7** [comment]
I collected samples on the current master with the test file.
82% of time is spent at `out->add ()`, 14% at `group_get_glyph()`.

So clamping ranges may help on 14%, but the real problem is `add()`, which should be converted to `add_range()`. Clamping can be done at the same time, so that way we can see a substantial improvement.
