### ISSUE TITLE
Documentation incorrect about default application of “liga”

### ISSUE THREAD

**Issue by NorbertLindenberg** [harfbuzz/harfbuzz#2213]
The HarfBuzz documentation at
https://harfbuzz.github.io/shaping-opentype-features.html
says that for horizontal text the “liga” and “frac” features (among others) are enabled by default.

In testing with Brahmic scripts (9 × Indic, Khmer, Lao, Myanmar, Thai, Balinese, Sinhala, Tibetan) on Chrome 80, I found that not always to be the case. “frac” doesn’t seem to be enabled for any of these scripts, and “liga” only for Lao, Thai, and the USE scripts (which don’t include Sinhala yet in HarfBuzz).

“frac” isn’t applied to Brahmic scripts by CoreText and DirectWrite either, so it’s probably best to update the documentation to say for which scripts / engines HarfBuzz actually turns it on by default.

I see “liga” being applied to all Brahmic scripts by default by CoreText, and to Lao, Myanmar, Thai, and the USE scripts by DirectWrite. This means here the right answer isn’t obvious in the absence of a standard.

**Comment by khaledhosny** [comment]
`frac` is applied selectively to number(s) fraction slash number(s) sequences.

**Comment by NorbertLindenberg** [comment]
I see – thank you! Also, “frac” is only applied if the digit glyphs haven’t been substituted yet. After accounting for that in my tests, I see that HarfBuzz indeed applies “frac” across all the scripts I’m testing with. CoreText and DirectWrite still don’t.

**Comment by khaledhosny** [comment]
It is known that HarfBuzz application of `frac` (and also `numr`/`dnom`) by default is a unique HarfBuzz feature, which is mean to enable the Unicode-specified behavior of the fraction slash. From https://www.unicode.org/versions/Unicode12.0.0/ch06.pdf:

> Fraction Slash. U+2044 fraction slash is used between digits to form numeric fractions, such as 2/3 and 3/9. The standard form of a fraction built using the fraction slash is defined as follows: any sequence of one or more decimal digits (General Category = Nd), followed by the fraction slash, followed by any sequence of one or more decimal digits. Such a fraction should be displayed as a unit, such as ¾ or [3/4]. The precise choice of display can depend on additional formatting information.

**Comment by khaledhosny** [comment]
Looks like `indic`, `khmer`, and `myanmar` shapers explicitly disable `liga`. Few other shapers explicitly disable feature that are otherwise enabled for all scripts, so we need to list them all.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/pull/2665

**Comment by behdad** [comment]
> Looks like `indic`, `khmer`, and `myanmar` shapers explicitly disable `liga`.

Every time we disabled a feature, it was because there were fonts that misrendered. Ie. Uniscribe doesn't applying that feature and fonts in the wild were referring to them and relying on them NOT being applied. I'm sure that was the case for Khmer. Don't remember about Indic/Myanmar. Some git archeology might suggest why it was done.

I *think* was done in Indic shaper because Khmer was originally shaped with Indic shaper. Myanmar was forked off the Indic shaper so that's probably why is disabled there. Later we forked Khmer off Indic as well. So miight be doable to enable liga in Myanmar & Indic and just leave it off in Khmer.

**Comment by behdad** [comment]
Yep, this was done in 2012 in 6b389ddc3623d042ded4731f4d62dc354002fdd0
That commit is short on details. What I said is accurate I believe.
cc @jfkthame

**Comment by behdad** [comment]
See how same change was done re `kern`: eb10233b267909dee0245f126000e117f3b21c35

**Comment by khaledhosny** [comment]
I tested Indic (Oriya) and Myanmar with Uniscribe, it enables `liga` for Myanmar but not for Indic. I opened https://github.com/harfbuzz/harfbuzz/pull/2681 for the Myanmar shaper.

**Comment by khaledhosny** [comment]
One difference between HarfBuzz and Uniscribe (I don’t know if it is known), is that with HarfBuzz features disabled by the shaper can’t be overridden by the user, while it can be overridden with Uniscribe (i.e. `--features="+liga"` makes no difference with `ot` shaper but enables the feature with `uniscribe`).
