### ISSUE TITLE
[draw] Invalid rendering of some variable glyphs

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2215]
Font: https://github.com/aminabedi68/Estedad/blob/master/Font/ttf/Estedad-VF.ttf

Results using `main.c` and the latest master:

```diff
  unsigned num_glyphs = hb_face_get_glyph_count (hb_font_get_face (font));
  for (unsigned gid = 0; gid < num_glyphs; ++gid)
  {
+    hb_variation_t var;
+    hb_variation_from_string("wght=100", -1, &var);
+    hb_font_set_variations (font, &var, 1);
 
    hb_font_extents_t font_extents;
    hb_font_get_extents_for_direction (font, HB_DIRECTION_LTR, &font_extents);
    hb_glyph_extents_t extents = {0};
```

GID 156

![156](https://user-images.githubusercontent.com/725494/75605045-d07cb380-5ae7-11ea-9310-2121249bdb81.png)

GID 180

![180](https://user-images.githubusercontent.com/725494/75605046-d4103a80-5ae7-11ea-832f-bbf6cafb1589.png)

GID 262 (should be a circle)

![262](https://user-images.githubusercontent.com/725494/75605048-d6729480-5ae7-11ea-8b88-ff09ed067aca.png)

**Comment by ebraminio** [comment]
That's not good :/ Maybe @blueshade7 can help but it is possible that this is a regression introduced by me, oh well :/

**Comment by RazrFalcon** [comment]
Since this is glyf related, maybe this is because of the ttf-parser algorithm? Because I'm implementing gvar right now, and I have the same problem. But I did not investigated it yet.

**Comment by ebraminio** [comment]
Ok, is a regression, thanks for the finding @RazrFalcon and sorry for bothering @blueshade7, will provide a bisect, that will makes things clear.

**Comment by ebraminio** [comment]
11f3fca01d6840f3a690b59040ad7452e5343abf is to blame, will try to revert.
