### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2217]
TeX Live 2019 is frozen, so I guess 2020 release will follow soon (no idea about timeline, cc;ing @kberry and @norbusan). Master has at least one fix that affects TeX Live.

**Comment by norbusan** [comment]
Well, the sources should be in soon, as we are starting to build soon. If there is a release pending, it would be better for us to have it really rather soon. Thanks

**Comment by ebraminio** [comment]
Just to note I don't have the keys to do the release but moreover liked to get final Behdad's and you review on #2145 but Behdad hasn't been active so far so there is also a one click button to disable the API #2141 if Behdad likes to mark a release but wants to provide some API changes. Merged the API at the first place for getting it fuzzed and have fixed its issues on the recent days (they were gvar ones that could revealed by shape fuzzer also but wasn't since it didn't have variation practicing codes)

**Comment by kberry** [comment]
As far as TeX Live goes, personally, I prefer no release of harfbuzz now to trying to get something out "quickly". I think that way lies disaster for everyone. API changes would be especially bad at this point.

The TL schedule is on https://tug.org/texlive (and has been for months).

If there is one known fix for HB that we should apply, we could do that separately (asap). What is it?

Thanks.

**Comment by khaledhosny** [comment]
Cutting new releases used to be low effort, but probably not at this moment.

The changes I had in mind that the two commit by @zauguin (d70afb1e5a32f23d03cc69bbbc725d1e668eb616, b28c282585afd3bff844e84eae7f29e1a1267aef) which affect reading super big TTC fonts in `luahbtex`, not sure if they apply cleanly to the current release. It is not a big issue either, it probably affects only the “Super OTC” version of Source Han fonts and can be easily worked around by using the split files.

**Comment by zauguin** [comment]
While it isn't really a fix but more of a new feature, https://github.com/harfbuzz/harfbuzz/pull/2054/commits is also relevant for TeXLive: Without it, there are no glyph names available for OTF fonts, making it very hard to access individual glyphs reliably.

**Comment by kberry** [comment]
Can one of you send me the actual patch for the glyph names? I don't trust myself to extract the correct thing, given the several versions that are there. Thanks.

Regarding the super big TTC font patch, if it only affects one font and there is a workaround, I'm inclined to let it go for now.

**Comment by khaledhosny** [comment]
I don't think cherry-picking such a big change (for the glyph names) is wise, it probably depends on other changes that might have went into master before it. I guess TL better wait for a release, and if the release misses the 2020 train that would be pity but not the end of the world.

**Comment by khaledhosny** [comment]
Too late for TL now I guess, a new release will happen eventually.
