### ISSUE TITLE
[subset] assert(!current->next) in end_serialize()

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#2220]
Do we need to keep this assert in hb_serialize_context_t::end_serialize()?
https://github.com/harfbuzz/harfbuzz/blob/d38360397609d2f3d2dd115bcb0f58d10a1bb4a3/src/hb-serialize.hh#L170

If a table serializer function hits an error between a pair of calls to `h->push()` and `h->pop_pack()`, it may wish to return immediately, but it has to call `h->pop_discard()`, otherwise ends up triggering this assertion. This seems like a time-bomb.

It seems better for `end_serialize()` to not assert, instead pop-discard all objects left in the queue silently.

**Comment by ebraminio** [comment]
@garretrieger @qxliu76 please have a look, thanks

**Comment by behdad** [comment]
push/pop pairs MUST match even in error-recovery path.

In my original design, push/pop were to be called in very few places, in OffsetTo, ArrayOf, etc, but NOT generally by the subset logic directly.  I see you need to do it a lot in CFF.  We can add a RAII helper for that.  I've been thinking about that and would be happy to add / help.

**Comment by blueshade7** [comment]
>push/pop pairs MUST match even in error-recovery path.

RAII helper sounds good if this expectation needs to be enforced, rather than leaving it up to a human code reviewer or a fuzzer to find a usage where it is broken.

**Comment by behdad** [comment]
Agree.  I was thinking to move push/pop completely to a RIAA helper.  Thinking about it.  Maybe like:

```
{
  auto t = s->transaction ();
  t.push ();
  ...
  if (...)
    t.pop_pack ();
}
```

**Comment by behdad** [comment]
A transaction would allow multiple pushes as well.  Will pop them all back to the object that was current when transaction was created.

**Comment by behdad** [comment]
It *wouldn't interact with snapshot/revert.  Something tells me it should maybe.  Maybe allow `t.revert ()` as well.  Not sure.
