### ISSUE TITLE
Khitan Small Script Filler rendered as a visible character in vertical layout

### ISSUE THREAD

**Issue by babelstone** [harfbuzz/harfbuzz#2236]
In vertical layout only, U+16FE4 KHITAN SMALL SCRIPT FILLER is rendered as a visible character and interrupts Khitan Small Script clustering behaviour. There is no problem in horizontal layout where KSSF joins two characters vertically. See [this test page](https://www.babelstone.co.uk/Fonts/KSS_Mirror.html).
![KSS_Test_Horizontal](https://user-images.githubusercontent.com/20558386/76172811-54423a00-6191-11ea-85ad-5103a9827beb.png)
![KSS_Test_Vertical](https://user-images.githubusercontent.com/20558386/76172815-54dad080-6191-11ea-917e-c16a76b9239e.png)

**Comment by khaledhosny** [comment]
This does not seem like a HarfBuzz issue, if I’m understanding correctly the text is rendered horizontally then rotated (e.g. like sideways Latin and unlike upright CJK), so as far as HarfBuzz is concerned there is no vertical mode involved and the browser is asking HarfBuzz to shape the text horizontally in both cases.

Testing with `hb-view`, I get the following:
```
$ hb-view KhitanSmallRotated.ttf "𘭔𖿤𘭢 𘲽𘱸" --direction=ttb
```
![ttb](https://user-images.githubusercontent.com/93914/76318907-0e978580-62e7-11ea-8e0c-ea8e44445883.png)

```
$ hb-view KhitanSmallRotated.ttf "𘭔𖿤𘭢 𘲽𘱸" --direction=ltr
```
![ltr](https://user-images.githubusercontent.com/93914/76318912-10f9df80-62e7-11ea-8d3e-803172a74714.png)

My guess would be that browsers either failing to apply `ccmp` feature in vertical mode, or splitting the clusters and shaping each part separately.

In your test page, adding either `text-orientation: sideways;` or `text-orientation: sideways-right;` after `writing-mode: vertical-rl;` seems to give the expected output.

**Comment by babelstone** [comment]
Many thanks! You can close the issue now.
