### ISSUE TITLE
[meson] make distdir equivalent

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2250]
Most essential expectation from a build tool to make it the main one is I guess having things equivalent to `make distcheck` and `make distdir` etc.

https://github.com/harfbuzz/harfbuzz/blob/master/RELEASING.md and https://github.com/harfbuzz/harfbuzz/blob/master/BUILD.md should be updated with the instruction on how to make a dist

**Comment by khaledhosny** [comment]
https://mesonbuild.com/Creating-releases.html

`ninja dist` seems to work. From what I see, looks like it does a git clone so includes everything in the source repository (this missing autotools-generated files, but this is unavoidable and we shouldn’t use such dist package until we drop autotools build).

**Comment by tp-m** [comment]
(I will look at the various meson issues btw, just currently in a crunch finishing something else as I mentioned on irc.)

**Comment by ebraminio** [comment]
Thanks Khaled. So closing in favor of #2436
