### ISSUE TITLE
[meson] WARNING: Library target 'harfbuzz' has 'name_prefix' 

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2256]
I get the following warning when I invoke `meson`:
```
WARNING: Library target 'harfbuzz' has 'name_prefix' set. Compilers may not find it from its '-lharfbuzz' linker flag in the 'harfbuzz.pc' pkg-config file.
WARNING: Library target 'harfbuzz-subset' has 'name_prefix' set. Compilers may not find it from its '-lharfbuzz-subset' linker flag in the 'harfbuzz-subset.pc' pkg-config file.
```
Is this something to worry about, and can we suppress this warning if it is a false alarm?

**Comment by lazka** [comment]
meson docs state that it's empty on msvc and otherwise "lib", which is exactly what is passed in harfbuzz, so I think it should just be removed.
