### ISSUE TITLE
[meson] warning: unused function 'test_unicode_properties_lenient'

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2257]
I get this warning when building with meson but not with autotools:
```
../test/api/test-unicode.c:589:1: warning: unused function 'test_unicode_properties_lenient' [-Wunused-function]
test_unicode_properties_lenient (gconstpointer user_data)
^
1 warning generated.
```

Not sure if it is due to different warning options or something missing in the build.

**Comment by tp-m** [comment]
PR in https://github.com/harfbuzz/harfbuzz/pull/2259

Reason this happens is that `HAVE_CONFIG_H` wasn't passed for plain C source files, which means neither `#ifdef HAVE_GLIB` or `#ifdef HAVE_ICU` were set, so the function was indeed not used.

The warning could still be legitimate in some configurations though.
