### ISSUE TITLE
[autotools] How to enable 'dump_glyphs' in main.cc

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2263]
It is behind the `HB_EXPERIMENTAL_API` flag now and I can't figure out how to enable it.

**Comment by ebraminio** [comment]
Needs to be built with https://github.com/harfbuzz/harfbuzz/blob/755a77d6/.circleci/config.yml#L125

**Comment by RazrFalcon** [comment]
Thanks. It worked. I was using `env CCLAGS="-DHB_EXPERIMENTAL_API" CXXFLAGS="-DHB_EXPERIMENTAL_API" make`... autotools is the worst.

**Comment by RazrFalcon** [comment]
Wait, no. It doesn't work anyway. `dump_glyphs` is never executed.

**Comment by ebraminio** [comment]
> Wait, no. It doesn't work anyway. dump_glyphs is never executed.

It should be :/ https://github.com/harfbuzz/harfbuzz/blob/master/src/main.cc#L509 maybe needs a rebuild

**Comment by RazrFalcon** [comment]
Looks like

```
env HB_EXPERIMENTAL_API=1 make -j16 CPPFLAGS="-DHB_EXPERIMENTAL_API"
```

works, but

```
env HB_EXPERIMENTAL_API=1 CPPFLAGS="-DHB_EXPERIMENTAL_API" make -j16
```

is not...

Thanks again.

**Comment by ebraminio** [comment]
Should add an option for meson for an easy access to it

**Comment by RazrFalcon** [comment]
And here I'm again. I'm trying to link libharfbuzz with draw functions enabled, but I'm getting `use of undeclared identifier 'hb_draw_funcs_create'`.

I'm using 2.6.5 tag archive:

```
./autogen.sh
env HB_EXPERIMENTAL_API=1 make -j16 CPPFLAGS="-DHB_EXPERIMENTAL_API"
```

PS: looks like there is no way to enable it via cmake/meson too.

**Comment by RazrFalcon** [comment]
Hmm... defining `HB_EXPERIMENTAL_API` manually before including `hb.h` fixed it. But it worked before without it. Am I missing something?

**Comment by ebraminio** [comment]
Oh I've added a `meson -Dexperimental-api=true && ninja -Cbuild` that should work afaik and is tested in our CI also, please let me know if it doesn't, we should really try to make hb-draw available for the next releases. Thanks

**Comment by RazrFalcon** [comment]
Nope. Now it errors on *undefined reference*, while `HB_VERSION_STRING` returns 2.6.5, so I'm linking the right library (the system one is 2.6.4 on my machine).

**Comment by ebraminio** [comment]
Just ran `rm -rf out build && meson -Dexperimental-api=true build && ninja -Cbuild && mkdir out && build/src/main test/subset/data/fonts/Roboto-Regular.ttf` and it looks good? Sorry for the trouble :/

**Comment by RazrFalcon** [comment]
I've ran your command but it produces an empty `out` dir.

**Comment by ebraminio** [comment]
Just ran

`git fetch upstream && git reset --hard upstream/master && git clean -xxfd && meson -Dexperimental-api=true build && ninja -Cbuild && mkdir out && build/src/main test/subset/data/fonts/Roboto-Regular.ttf && du -B1 out`

And it says `5345280 out`, I think there is some issue but just I don't see it right now :/

`cd $(mktemp -d) && git clone https://github.com/harfbuzz/harfbuzz --depth=1 && cd harfbuzz && meson -Dexperimental-api=true build && ninja -Cbuild && mkdir out && build/src/main test/subset/data/fonts/Roboto-Regular.ttf && du -B1 out`

**Comment by RazrFalcon** [comment]
I've tried on master and it doesn't produce `main` at all. 

It kinda works with autotools, so t's fine for now.

**Comment by ebraminio** [comment]
> I've tried on master and it doesn't produce main at all.

That's weird and unwanted from out part :/

Here is no build system instruction,

`cd $(mktemp -d) && git clone https://github.com/harfbuzz/harfbuzz --depth=1 && cd harfbuzz && clang -fno-exceptions src/main.cc src/harfbuzz.cc -DHB_NO_MT -DHB_EXPERIMENTAL_API=1 -DMAIN_CC_NO_PRIVATE_API -lm && mkdir out && ./a.out test/subset/data/fonts/Roboto-Regular.ttf && du -B1 out`

`5304320	out`
