### ISSUE TITLE
Hanifi Rohingya /* 10D00 */

### ISSUE THREAD

**Issue by rafael-saraiva** [harfbuzz/harfbuzz#2267]
#define joining_offset_0x10d00u 1146

/* Hanifi Rohingya */

/* 10D00 / L,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,
/ 10D20 */ D,D,R,D,

It's claimed by the Rohingya Zuban Academy that the letter Aa can be eventually be set as medial and final shapes. This is illustrated in the unicode proposal p. 11

![74767703-1cb53180-5266-11ea-96a1-e61d97bed53e](https://user-images.githubusercontent.com/2631198/76851503-1d6ec280-6828-11ea-8489-4e8db0485815.png)

Please get in touch with Arifa Sultana and her team for more information (rozubanacademy@gmail.com).

Best,
Rafael

**Comment by khaledhosny** [comment]
Once the proposal gets through and Unicode data is updated, HarfBuzz code will be updated as well.
