### ISSUE TITLE
Custom glyph_h_kerning function is not called

### ISSUE THREAD

**Issue by epico** [harfbuzz/harfbuzz#2268]
I write some patch to implement grid fitting for horizontal kerning in pango.

The hb_font_funcs_set_glyph_h_kerning_func is called,
but the custom pango_hb_font_get_glyph_h_kerning is not called.

Could you help check why the custom glyph_h_kerning function is not called?

Here are the draft patch with printing.
URL: https://gitlab.gnome.org/pwu/pango/commit/7cf551c567fa8b0e4e79fff019027a1f94618f14

**Comment by khaledhosny** [comment]
These kerning functions are used for fallback kerning and only when the font does not provide kerning information (either in `GPOS` or `kerrn` table).

**Comment by khaledhosny** [comment]
Glyph positioning involve much more than just kerning, so even if this code would have worked it will not be enough. You really need to fix the underlying Cairo issues not work around them, or Pango should return to using grid-fitted glyph metrics as the ecosystem is apparently not ready for what Pango did.

**Comment by epico** [comment]
Could you tell me how to get and modify kerning value by using harfbuzz API
in pango code?

Sorry, I am not familiar with the harfbuzz API.

**Comment by khaledhosny** [comment]
You can’t. The positioning values can only be accessed after shaping through the buffer API.

**Comment by epico** [comment]
Could harfbuzz provide some API to support grid fitting option
when compute kerning like freetype did?

**Comment by behdad** [comment]
We can't.  You need to do any gridfitting you like on the output of HarfBuzz.
