### ISSUE TITLE
[hb-ft] FT_Face should get updated every time hb_font_t coords changes

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2270]
Apparently `FT_Set_Var_Blend_Coordinates` is [only called](https://github.com/harfbuzz/harfbuzz/blob/d5338ba/src/hb-ft.cc#L920) when `hb_ft_font_set_funcs` is called on a hb_font_t but possibly it should be called everytime `hb_font_t` coords changes via `hb_font_set_variations` or `hb_font_set_var_*` calls, shouldn't it? If is true, how it should be implemented?

**Comment by behdad** [comment]
This is the kind of property-change notification we do not currently support.  I'm not sure how to do, if at all.  Maybe adding a `changed` callback to font-funcs.
