### ISSUE TITLE
Setting script using private language tags gives unexpected result 

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2271]
Setting script using private subtags seems to enable non script-specific lookups only, perhaps it takes effect too late that the default shaper is used?

Here is an example:
```C
#include <hb.h>
#include <stdio.h>

int
main(int argc, char** argv) {
  char out[1000];
  hb_blob_t* blob = hb_blob_create_from_file("Amiri-Regular.ttf");
  hb_face_t* face = hb_face_create(blob, 0);
  hb_font_t* font = hb_font_create(face);
  hb_buffer_t* buffer = hb_buffer_create();
  //hb_buffer_set_script(buffer, HB_SCRIPT_ARABIC);
  hb_buffer_set_language(buffer, hb_language_from_string("x-hbotARA-hbscarab", -1));
  hb_buffer_set_direction(buffer, HB_DIRECTION_RTL);
  hb_buffer_add_utf8(buffer, "\u0639\u0631\u0628\u064a.", -1, 0, -1);
  hb_shape(font, buffer, NULL, 0);
  hb_buffer_serialize_glyphs(buffer, 0, hb_buffer_get_length(buffer),
    out, sizeof(out), NULL, font, HB_BUFFER_SERIALIZE_FORMAT_TEXT,
    HB_BUFFER_SERIALIZE_FLAG_NO_POSITIONS | HB_BUFFER_SERIALIZE_FLAG_NO_CLUSTERS);
  printf("%s\n", out);
}
```

This applies `locl` lookup only:
```
uni064A|uni0628|uni0631|uni0639|period.ara
```

But after commenting out the line that set Arabic script, `init`, `medi` etc. are applied as well:
```
uni064A.fina_KafYaaIsol|uni0628.init_BaaYaaIsol|uni0631.fina_MemRaaIsol|uni0639.init|period.ara
```

Is this expected?

**Comment by behdad** [comment]
Definitely not expected.  Can you debug please?  Search for "Arabic" in `hb-ot-shape-complex.hh` and see which shaper is selected.  That's a good start.

**Comment by behdad** [comment]
cc @dscorbett

**Comment by khaledhosny** [comment]
I think the shaper gets selected before the language is queried, so setting script there has no effect on the shaper selection.

**Comment by behdad** [comment]
> I think the shaper gets selected before the language is queried, so setting script there has no effect on the shaper selection.

Don't jump to conclusions.  The shaper-selection code has access to the OT script found, which in this case you want to come from language...  Anyway.  Debugging is best.  Can this be reproduced using `hb-shape`?

**Comment by khaledhosny** [comment]
That was my conclusion when I debugged this earlier, now I don’t recall the details but I can debug again. Tricky to reproduce with `hb-shape` since it will guess the script if not set.

**Comment by khaledhosny** [comment]
After adding:
```
printf("%c%c%c%c\n", HB_UNTAG((hb_tag_t) planner->props.script));
```

On top of `hb_ot_shape_complex_categorize`, and running:
```
hb-shape Amiri-Regular.ttf -u 0639,0631,0628,064a,002e --language="x-hbotARA-hbscarab" --script="DUMMY"
Dmmy
[uni0639|uni0631|uni0628|uni064A|period.ara]
```

So the explicit script set is used, and the one set in the language is not used here.

**Comment by khaledhosny** [comment]
`hb_ot_map_builder_t` constructor calls `hb_ot_tags_from_script_and_language()` but it does not change use its result to change the script of the segment properties, so it has no effect on shaper selection.

**Comment by behdad** [comment]
> So the explicit script set is used, and the one set in the language is not used here.

That much is expected.  It helps thinking this way: the one coming from language is a OT-script.  It's never treated as hb_script_t.  That's correct.  The lang one is expected to be used to change what OT-script is picked.  It's not an alternative to setting correct script.

**Comment by khaledhosny** [comment]
Quick and dirt patch:
```diff
diff --git a/src/hb-ot-map.cc b/src/hb-ot-map.cc
index e4bb4b63..58bb8210 100644
--- a/src/hb-ot-map.cc
+++ b/src/hb-ot-map.cc
@@ -70,6 +70,9 @@ hb_ot_map_builder_t::hb_ot_map_builder_t (hb_face_t *face_,
     found_script[table_index] = (bool) hb_ot_layout_table_select_script (face, table_tag, script_count, script_tags, &script_index[table_index], &chosen_script[table_index]);
     hb_ot_layout_script_select_language (face, table_tag, script_index[table_index], language_count, language_tags, &language_index[table_index]);
   }
+
+  if (found_script[0])
+    props.script = (hb_script_t) ((chosen_script[0] & 0xDFDFDFDFu) | 0x00202020u);
 }
 
 hb_ot_map_builder_t::~hb_ot_map_builder_t ()
diff --git a/src/hb-ot-shape-complex.hh b/src/hb-ot-shape-complex.hh
index a9f58344..596d42e5 100644
--- a/src/hb-ot-shape-complex.hh
+++ b/src/hb-ot-shape-complex.hh
@@ -176,7 +176,7 @@ HB_COMPLEX_SHAPERS_IMPLEMENT_SHAPERS
 static inline const hb_ot_complex_shaper_t *
 hb_ot_shape_complex_categorize (const hb_ot_shape_planner_t *planner)
 {
-  switch ((hb_tag_t) planner->props.script)
+  switch ((hb_tag_t) planner->map.props.script)
   {
     default:
       return &_hb_ot_complex_shaper_default;
```

**Comment by behdad** [comment]
Yeah I think what you are expecting is not what this was designed for.

**Comment by khaledhosny** [comment]
OK, so the answer to original question is that it is working as designed, right?

**Comment by behdad** [comment]
Yes.

Originally I missed the fact that if you don't call guess_segment_properties explicitly harfbuzz wouldn't for you.

**Comment by khaledhosny** [comment]
The original issue is that I was suggesting that clients that want to set script and language using OpenType tags should use the private language tag, but if this does not influence the shaper selection then it is a bad suggestion since said clients certainly want the right shaper to be selected.

**Comment by khaledhosny** [comment]
All good then, nothing to be fixed.
