### ISSUE TITLE
[meson] Use C linker for output library

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2276]
Equivalent of [this](https://github.com/harfbuzz/harfbuzz/blob/748e1cf/src/Makefile.am#L120-L129), our meson script needs someway to avoid linking to stdc++ by using a C linker instead C++.

**Comment by ebraminio** [comment]
[This](https://github.com/harfbuzz/harfbuzz/blob/e860000/CMakeLists.txt#L481-L488) is the way the it was working in meson, applied `link_language` from https://mesonbuild.com/Release-notes-for-0-51-0.html#new-target-keyword-argument-link_language and it didn't work

Meson has related things to it like https://github.com/mesonbuild/meson/blob/00104b1/mesonbuild/backend/ninjabackend.py#L2332

```
diff --git a/meson.build b/meson.build
index 8ca46b96..f2cc4626 100644
--- a/meson.build
+++ b/meson.build
@@ -1,5 +1,5 @@
 project('harfbuzz', 'c', 'cpp',
-  meson_version: '>= 0.47.0',
+  meson_version: '>= 0.51.0',
   default_options : ['cpp_std=c++11'],
   version: '2.6.4')
 
diff --git a/src/meson.build b/src/meson.build
index 72255da2..8228c3d3 100644
--- a/src/meson.build
+++ b/src/meson.build
@@ -359,6 +359,7 @@ libharfbuzz = library('harfbuzz', hb_sources,
   soversion: hb_so_version,
   version: version,
   install: true,
+  link_language: 'c',
   name_prefix: hb_lib_prefix)
 
 libharfbuzz_dep = declare_dependency(
@@ -434,10 +435,10 @@ if host_machine.system() != 'windows' and not meson.is_cross_build()
     'check-symbols.sh', # fails with "'harfbuzz.def' not found; skipping"
   ]
   if not get_option('amalgam')
-    dist_check_script += ['check-includes.sh']
+    dist_check_script += 'check-includes.sh'
   endif
-  if false # !WITH_LIBSTDCXX
-    dist_check_script += 'check-libstdc++.sh' # we don't have chosen_linker logic here yet
+  if true # !WITH_LIBSTDCXX
+    dist_check_script += 'check-libstdc++.sh'
   endif
 
   foreach name : dist_check_script
@@ -463,6 +464,7 @@ libharfbuzz_subset = library('harfbuzz-subset', hb_subset_sources,
   soversion: hb_so_version,
   version: version,
   install: true,
+  link_language: 'c',
   name_prefix: hb_lib_prefix)
 
 libharfbuzz_subset_dep = declare_dependency(
@@ -546,6 +548,7 @@ if have_gobject
     soversion: hb_so_version,
     version: version,
     install: true,
+    link_language: 'c',
     name_prefix: hb_lib_prefix)
 
   gir = find_program('g-ir-scanner', required: get_option('introspection'))
```

**Comment by tp-m** [comment]
Hrm, https://github.com/mesonbuild/meson/issues/6453 says it is only supposed to work with executables apparently not libraries.

**Comment by ebraminio** [comment]
Commented there also.

Can I alter CXX_LD and turn it to CC_LD from https://github.com/mesonbuild/meson/blob/master/docs/markdown/Reference-tables.md#compiler-and-linker-selection-variables the table has lots of things but no indication of where and how, should checkout meson and see myself most likely.

**Comment by tp-m** [comment]
As I understand it those environment variables are for users/distros, not for the project's use  (not sure how you would specify them anyway).

**Comment by ebraminio** [comment]
Hopefully going to be fixed by https://github.com/mesonbuild/meson/pull/6838
