### ISSUE TITLE
Figure out xlocale use

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2277]
Now that meson uses coloring for found / not found it has become more obvious for me that xlocale header isn't found in my distro :) and apparently not available in Alpine https://circleci.com/gh/harfbuzz/harfbuzz/134099 and ArchLinux https://circleci.com/gh/harfbuzz/harfbuzz/134090 Ubuntu https://circleci.com/gh/harfbuzz/harfbuzz/134086 and Fedora https://circleci.com/gh/harfbuzz/harfbuzz/134088 so guess this is something that used to work in the past and now is gone.

Per http://lua-users.org/lists/lua-l/2016-04/msg00216.html

> I'd suggest that future versions of lua use 'strtod_l' and friends
> (the locale independent variants) where available, and only fall back
> to the `localeconv` hack if compiling in C89 mode.
>   - strtod_l is available on linux (at least both glibc and musl) if
> _GNU_SOURCE is defined
>   - _strtod_l is available in MSVC since VS2005
>   - strtod_l is available on OSX since Darwin 8.
>   - strtod_l is available on FreeBSD since 9.1

Can we just remove https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-number.cc#L78-L133 anyway? Will upload a removal patch

**Comment by ePirat** [comment]
`strtod_l` on Darwin needs the xlocale header to be included.

**Comment by ebraminio** [comment]
Oh, thanks, I didn't know.
