### ISSUE TITLE
The story behind CBLC version 2.0?

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2281]
According to the Microsoft's OpenType [documentation](https://docs.microsoft.com/en-us/typography/opentype/spec/cblc), the CBLC version starts with 3.0, but harfbuzz also allows version 2.0 and `ee39587d13b2afa5499cc79e45780aa79293bbd4.ttf` and `3cf6f8ac6d647473a43a3100e7494b202b2cfafe.ttf` fonts are also use this version. 
Is this some legacy issue? Or the spec was changed?

I guess the source of this is [this commit](https://github.com/googlefonts/noto-emoji/commit/69952d1fd81e7813a4693714984b273eae09c7fc). And since 3.0 is the official number, maybe test fonts should be updated too?
Not sure about the harfbuzz itself since maybe someone is still using that old Noto font.

**Comment by ebraminio** [comment]
CBLC/CBDT once weren't part of OT spec and then Microsoft aggregated all the different color glyphs standard `sbix` / `CBDT` `CBLC` / `SVG ` in addition to their `COLR` `CPAL` to OT. For example there are also minor differences between Apple's sbix and OT's, guess this one is like that also.

**Comment by behdad** [comment]
Yeah when adding CBLC/CBDT to OpenType, in a meeting I wasn't present, it was decided to bump the major version to 3.  That went unnoticed to me until years later when I started fixing FreeType, HarfBuzz, Noto, etc.

**Comment by behdad** [comment]
But the damage was done, so to speak.
