### ISSUE TITLE
Disabling `liga` on Kokonoor AAT font breaks Tibetan shaping

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2285]
`$ util/hb-view  /Library/Fonts/Kokonor.ttf "རྒྱུ" > kokonor.png`

![kokonor](https://user-images.githubusercontent.com/1021784/77898226-81ab7080-7283-11ea-908a-d304304e08cb.png)

`util/hb-view --features=-liga /Library/Fonts/Kokonor.ttf "རྒྱུ" > kokonor_broken.png`

![kokonor_broken](https://user-images.githubusercontent.com/1021784/77898236-84a66100-7283-11ea-8f30-9b8f6fa93f11.png)

Expected: Disabling "common ligatures" / `liga` should not lead to disabling ligatures required to have readable text. Is there a way to identify required ligatures in AAT and stop those from being disable by the OpenType / AAT feature mapping?

**Comment by drott** [comment]
Spun off from https://bugs.chromium.org/p/chromium/issues/detail?id=1036390 
https://jsfiddle.net/ikopylov/zxt2k9r3/4/

CC @jfkthame - I see that you're handling this correctly for `font-variant-ligatures: none;` - do you special case this font, or how do you prevent font-variant-ligatures: none; from passing -liga to HarfBuzz?

**Comment by jfkthame** [comment]
Huh, that's strange actually - I don't think we have any special-casing of this. I think it's more likely you may be seeing a bug in how we manage feature settings, and it just happens to "improve" this case!

Specifically, we don't seem to handle `font-variant-ligatures: none;` correctly for AAT fonts, AFAICS. (If you use `font-variant-ligatures: no-common-ligatures` instead, that *does* disable them). But I'll need to investigate a bit to figure out what's actually happening.

**Comment by jfkthame** [comment]
It looks to me like there's an issue with the mapping of feature tags to AAT features/selectors. I'm seeing an unexpected dependency on the order in which feature tags are presented. Using Times.ttc from macOS 10.15 as a test font, compare:
```
$ hb-shape --font-file Times.ttc "fine" --features "liga=0,dlig=0"
[f=0+682|i=1+569|n=2+1024|e=3+909]
```
vs:
```
$ hb-shape --font-file Times.ttc "fine" --features "dlig=0,liga=0"
[fi=0+1139|n=2+1024|e=3+909]
```
ISTM the output should be identical in these two cases, but it's not. (If I pass `--shaper coretext`, OTOH, I do get consistent output.)

**Comment by jfkthame** [comment]
Coming back to this, I think the fact that the Tibetan AAT fonts break when 'liga' is turned off is simply a font bug; if the font uses ligatures to implement basic shaping like this, those ligatures should be under the "Required Ligatures" selector, not "Common Ligatures".

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type1

The fact that you don't see the same result in Firefox is a side-effect of #2290. Once that is fixed, the Tibetan fonts will show consistent breakage everywhere when (common) ligatures are disabled.

**Comment by jfkthame** [comment]
@litherum When using an AAT Tibetan font in Safari, it appears that I can't override font features at all -- applying CSS `font-feature-settings` doesn't change anything. Similarly with an Arabic AAT font. I'm guessing the mapping of OpenType tags like 'liga' (as specified in CSS) to AAT feature selectors may be applied only for certain scripts?

**Comment by drott** [comment]
> Coming back to this, I think the fact that the Tibetan AAT fonts break when 'liga' is turned off is simply a font bug; if the font uses ligatures to implement basic shaping like this, those ligatures should be under the "Required Ligatures" selector, not "Common Ligatures".
> 
> https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type1

Thanks for looking into this further, @jfkthame - I was trying to check the features of the Kokonor, but CoreText just reports this font as having no available features - is it hiding the features from clients of CoreText API? What happens when HarfBuzz lists this font's features?

```
    CTFontRef font = CTFontCreateWithName(CFSTR("Kokonor"), 12.0, NULL);
    CFShow(CTFontCopyPostScriptName(font));
    CFShow(CTFontCopyFeatures(font));
```

outputs: 

```
Kokonor
(null)
Program ended with exit code: 0
```

**Comment by jfkthame** [comment]
> > Coming back to this, I think the fact that the Tibetan AAT fonts break when 'liga' is turned off is simply a font bug; if the font uses ligatures to implement basic shaping like this, those ligatures should be under the "Required Ligatures" selector, not "Common Ligatures".
> > https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type1
> 
> Thanks for looking into this further, @jfkthame - I was trying to check the features of the Kokonor, but CoreText just reports this font as having no available features - is it hiding the features from clients of CoreText API? 

I guess that's most likely because the font has no 'feat' table. But the 'morx' table nevertheless sets up its subfeature flags to treat all its subtables as being controlled by Common Ligatures On (type 1, setting 2, matches the DefaultFlags) or Common Ligatures Off (type 1, setting 3).

      <DefaultFlags value="0x00000001"/>
      <MorphFeature index="0">
        <FeatureType value="1"/>
        <FeatureSetting value="2"/>
        <EnableFlags value="0x00000001"/>
        <DisableFlags value="0xFFFFFFFF"/>
      </MorphFeature>
      <MorphFeature index="1">
        <FeatureType value="1"/>
        <FeatureSetting value="3"/>
        <EnableFlags value="0x00000000"/>
        <DisableFlags value="0xFFFFFFFE"/>
      </MorphFeature>

And all subtables have `<SubFeatureFlags value="0x00000001"/>`, so they all get enabled or disabled together.

So although the font doesn't expose this via a 'feat' table, it still responds if the relevant feature/selector is applied. So they should've used more appropriate feature flag(s), or just left the feature table in the morx chain empty (apart from the terminating entry), if they didn't want the font to be controllable via feature requests.

> What happens when HarfBuzz lists this font's features?

Not sure if HB has implemented a tool to expose features from an AAT font? (I dumped it with TTX to see what was present.) As far as Firefox is concerned, at least, we just set the feature tags in accordance with the requested style, without needing to know (in most cases) whether the font actually implements them; unknown feature tags will just do nothing.

**Comment by jfkthame** [comment]
I suppose a possible workaround would be to look for the presence of the 'feat' table in an AAT font, and if it's absent, then just don't try to map any OT tags to AAT feature selectors. But IMO the real issue is that the font is poorly implemented.

**Comment by drott** [comment]
> I suppose a possible workaround would be to look for the presence of the 'feat' table in an AAT font, and if it's absent, then just don't try to map any OT tags to AAT feature selectors.

Yes, that may work as a signal. I'd be up for trying that. Which Arabic font did you test with? I also looked at `Kailasa` and it does also not return any features. So it might be a Mac OS way of saying: don't change the feature configuration on this font.

**Comment by jfkthame** [comment]
For Arabic, I tried Geeza Pro. It doesn't seem to respond to feature settings at all, afaict.

**Comment by jfkthame** [comment]
Note though that Geeza does have a 'feat' table; but the features listed there don't seem to follow the official feature registry, nor do I understand how they relate to the entries in the 'morx' table.

**Comment by jfkthame** [comment]
Also note that in (for example) TextEdit.app, features in Geeza *are* exposed in the Typography palette and can be controlled by the user, whereas the Tibetan fonts (without 'feat') don't expose anything there. So they're not entirely comparable.

Not sure what if anything we should do about trying to map features in Geeza, when it doesn't seem to follow the standard registry... suggest we ignore this for now!

**Comment by behdad** [comment]
Le Sighs...  I'm glad two of you are figuring this out.  I don't have capacity for more workarounds of AAT fonts...

**Comment by ebraminio** [comment]
@drott, feel free to update Chrome's version and keep me updated if possible, thanks

**Comment by drott** [comment]
HB Roll and WPT test in https://chromium-review.googlesource.com/c/chromium/src/+/2134234
