### ISSUE TITLE
hb-serialize.hh(331) : warning C4701: potentially uninitialized local variable 'offset' used

### ISSUE THREAD

**Issue by dejanyy** [harfbuzz/harfbuzz#2292]
When compiling the latest HarfBuzz (2.6.4) MS Visual C++ 15 gives the following warning:

---------------
hb-serialize.hh(331) : warning C4701: potentially uninitialized local variable 'offset' used
---------------

Here is the relevant code snippet from hb-serialize.hh (line 331 is at the very end):

---------------
unsigned offset;
switch ((whence_t)link.whence) {
case Head:     offset = child->head - parent->head; break;
case Tail:     offset = child->head - parent->tail; break;
case Absolute: offset = (head - start) + (child->head - tail); break;
default: assert (0);
}

assert (offset >= link.bias);
offset -= link.bias; <--- This is line 331
---------------

It looks like MS Visual C++ 15  might be right; if link.whence is not Head, Tail or Absolute then offset will be uninitialized resulting in undefined value at line 331. I'm not sure if link.whence can have any other value; in any case I guess a simple and safe fix is to change the first line of the code snippet to say:

unsigned offset = 0;

**Comment by behdad** [comment]
I'm actually not sure this code is necessarily best.  We should remove the assert and make default fallback to the default (Head).

The only other places we have an `assert (0)` we can provably show that branch can never happen.  Here, you cannot show that unless you check all callsites.  Is unnecessary check.

**Comment by behdad** [comment]
Ie. we assume a `hb_direction_t` value is always valid.  We don't assert around or otherwise check.  No difference here for `whence_t`.
