### ISSUE TITLE
Support space in font name in hb-shape's --batch mode

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2303]
[This](https://github.com/harfbuzz/harfbuzz/blob/a0b4ac4dce392326284138fc47cf3741e2798e21/util/hb-shape.cc#L173-L179) makes us unable to use space in font name in batch mode so we have to do [this hack](https://github.com/harfbuzz/harfbuzz/blob/03564fd/test/shaping/run-tests.py#L104-L108), figure out how we can avoid copying in --batch maybe by adding quote around font name in batch more or something, or, let's ignore the hack which isn't used much anyway.

**Comment by behdad** [comment]
Maybe using colon better?
