### ISSUE TITLE
Apple Chancery small caps fails after b1c0b9da2ff1

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2307]
After b1c0b9da2ff1:

```util/hb-view "/Library/Fonts/Apple Chancery.ttf" --features="smcp" "Chancery"```

![chancery_no_smcp](https://user-images.githubusercontent.com/1021784/78371195-4b962580-75d0-11ea-9d90-31bec5c840a9.png)

Before:

![chancery_smcp](https://user-images.githubusercontent.com/1021784/78371225-5781e780-75d0-11ea-9243-40eb029f2080.png)

**Comment by ebraminio** [comment]
Does it need a special casing like https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-aat-map.cc#L43 ? cc: @jfkthame please have a look if is possible. Thanks!

**Comment by jfkthame** [comment]
This is because we map 'smcp' to [TYPE_LOWER_CASE, SELECTOR_LOWER_CASE_SMALL_CAPS], but what Apple Chancery exposes is [TYPE_LETTER_CASE, SELECTOR_SMALL_CAPS]. We special-case this in Chain::compile_flags, but since b1c0b9d we end up dropping the "unexposed" feature before that gets a chance to handle it.

Guess it needs another bit of special-casing...

**Comment by drott** [comment]
Or would it make sense just to use presence of the the feature table to allowing feature mapping in general? Did you have a finer grained case where a feature table is present but a non-exposed feature must not be used/exposed?

**Comment by jfkthame** [comment]
> Or would it make sense just to use presence of the the feature table to allowing feature mapping in general? Did you have a finer grained case in mind where a feature table is present but a non-exposed feature (i.e. not present in feature table but available in morx) must not be used/exposed?

I originally considered just using presence of 'feat', without checking the feature type, but it seemed more "correct" to respect its actual contents, given that this is the canonical way for AAT fonts to describe their user-controllable features. I don't know how common it is for AAT fonts to have a 'feat' table that exposes only a subset of the features they use internally in their implementation, but it seems plausible that could happen.

**Comment by drott** [comment]
> I originally considered just using presence of 'feat', without checking the feature type, but it seemed more "correct" to respect its actual contents, given that this is the canonical way for AAT fonts to describe their user-controllable features. I don't know how common it is for AAT fonts to have a 'feat' table that exposes only a subset of the features they use internally in their implementation, but it seems plausible that could happen.

I agree, seems reasonable, thank you (and thanks for all the patches and tests!) Let's observe what happens with this `feat`-specific restriction in place and if we happen to run into other issues - then we may need other mapping special cases or we can then consider relaxing this.
