### ISSUE TITLE
Incorrect prefix computation in harfbuzz-config.cmake

### ISSUE THREAD

**Issue by lisyarus** [harfbuzz/harfbuzz#2316]
On my Gentoo system with harfbuzz-2.6.4, in appears that `harfbuzz-config.cmake` (located in `/usr/lib/cmake/harfbuzz/`) is incorrect. Specifically, it contains

```
get_filename_component(_harfbuzz_prefix "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
get_filename_component(_harfbuzz_prefix "${_harfbuzz_prefix}" DIRECTORY)
set(_harfbuzz_libdir "/usr/lib64")
string(REPLACE "${_harfbuzz_remove_string}/" "" _harfbuzz_libdir "${_harfbuzz_libdir}")
set(_harfbuzz_libdir_iter "${_harfbuzz_libdir}")
while (_harfbuzz_libdir_iter)
  set(_harfbuzz_libdir_prev_iter "${_harfbuzz_libdir_iter}")
  get_filename_component(_harfbuzz_libdir_iter "${_harfbuzz_libdir_iter}" DIRECTORY)
  if (_harfbuzz_libdir_prev_iter STREQUAL _harfbuzz_libdir_iter)
    break()
  endif ()
  get_filename_component(_harfbuzz_prefix "${_harfbuzz_prefix}" DIRECTORY)
endwhile ()
unset(_harfbuzz_libdir_iter)
```

which, as I can see, leads to `_harfbuzz_prefix` being just `/` and later the include path to be `//include/harfbuzz`, which is clearly wrong and basically makes the whole config file useless.

I'm attaching the full `harfbuzz-config.cmake`.

[harfbuzz-config.cmake.txt](https://github.com/harfbuzz/harfbuzz/files/4440598/harfbuzz-config.cmake.txt)

**Comment by ebraminio** [comment]
This was provided by @mathstuf in d38f37b2e3794 and to be honest I don't have any expertise on it, would you please see also how it can be fixed? Otherwise its fix may take more time. Thanks!

**Comment by ebraminio** [comment]
Oh @vkrause has apparently something related also in 9e9a36ee65 (very sorry for ping noise btw)

**Comment by mathstuf** [comment]
Hmm. Do you have symlinks in your install path or in the path you're using to refer to the directory? Do the symlinks point to the install prefix itself or directly into it?

**Comment by lisyarus** [comment]
Thanks you a lot for quick response.
@mathstuf You are right, /usr/lib is a symlink to /usr/lib64.
By the way, why is the config file so complicated? From my experience, XXX-config.cmake is usually an imported target (or a few of them) with plain hardcoded paths (specified at configuration time prior to installation).

**Comment by mathstuf** [comment]
> You are right, /usr/lib is a symlink to /usr/lib64.

What distribution (Linux or package manater) is this? This is usually not how this is done (e.g., `lib64` should point to `lib` for `virtualenv`).

> By the way, why is the config file so complicated? From my experience, XXX-config.cmake is usually an imported target (or a few of them) with plain hardcoded paths (specified at configuration time prior to installation).

The purpose is to be relocatable. Baking the paths into the `config.cmake` means that your build machine paths are in your install tree which means that you can't make a tarball and just distribute the SDK (more of a thing on macOS and Windows, but also useful on Linux as well for various use cases (Anaconda, Conan, etc.)).

**Comment by lisyarus** [comment]
@mathstuf I see. The distribution is Gentoo Linux with `portage` package system.

**Comment by mathstuf** [comment]
Hrm. I guess there, we need to search the real path before looking at the symlink path. Also, where do 

In the meantime, you can manually use the realpath when referring to `harfbuzz_DIR` to work around this.

Though, looking at Gentoo docs, that is an old layout schema. I suggest upgrading to the new layout (though I don't see docs immediately on that page, I assume there's some way to do so). https://wiki.gentoo.org/wiki/Project:AMD64/Multilib_layout

**Comment by mathstuf** [comment]
Heh, and that page is over 2 years old now. Yeah, I suspect that the problem just disappears if you use the new layout scheme. Given that it is not meant to be used anymore, that would be my recommended solution (detecting/working around it could be tricky).

**Comment by mathstuf** [comment]
This issue may be relevant: https://gitlab.kitware.com/cmake/cmake/-/issues/19419

**Comment by lisyarus** [comment]
@mathstuf Thanks for your suggestions. I'm already using direct linking to harfbuzz without find_package (which works since it is installed in standard directories) as a workaround. However, I don't feel like permanently switching to the new symlink layout (potentially breaking something) until it becomes necessary (the gentoo news item reads "we would like to request all users to upgrade" which is clearly not an indication of necessity).

**Comment by mathstuf** [comment]
This would require work in CMake to fix properly (basically to detect the old symlink layout in Gentoo and prefer the non-symlink directory first). But that will only help with a new CMake release (probably not an issue on Gentoo). However, with Gentoo itself not recommending the layout, I'm hesitant to put the work into CMake if the recommendation elsewhere is to get off of that setup in the first place.

**Comment by lisyarus** [comment]
@mathstuf Okay, got your point. I'll contact the ebuild maintainers, then. Thank you for your effort!

**Comment by ebraminio** [comment]
Guess nothing to do from our part, marking as closed.

**Comment by lisyarus** [comment]
As suggested by @mathstuf, I switched to the new gentoo profile, and now `/usr/lib` and `/usr/lib64` are real directories and not symlinks. However, I still face the same problem: `_harfbuzz_prefix` is computed as `/` and the harfbuzz include directory appears as `//include/harfbuzz`.

**Comment by lisyarus** [comment]
Looking at the relevant parts of `/usr/lib64/cmake/harfbuzz/harfbuzz-config.cmake`:

```
set(_harfbuzz_remove_string "REMOVE_ME")
set(exec_prefix "${_harfbuzz_remove_string}")
set(prefix "${_harfbuzz_remove_string}")

# Compute the installation prefix by stripping components from our current
# location.
get_filename_component(_harfbuzz_prefix "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
get_filename_component(_harfbuzz_prefix "${_harfbuzz_prefix}" DIRECTORY)
set(_harfbuzz_libdir "/usr/lib64")
string(REPLACE "${_harfbuzz_remove_string}/" "" _harfbuzz_libdir "${_harfbuzz_libdir}")
set(_harfbuzz_libdir_iter "${_harfbuzz_libdir}")
while (_harfbuzz_libdir_iter)
  set(_harfbuzz_libdir_prev_iter "${_harfbuzz_libdir_iter}")
  get_filename_component(_harfbuzz_libdir_iter "${_harfbuzz_libdir_iter}" DIRECTORY)
  if (_harfbuzz_libdir_prev_iter STREQUAL _harfbuzz_libdir_iter)
    break()
  endif ()
  get_filename_component(_harfbuzz_prefix "${_harfbuzz_prefix}" DIRECTORY)
endwhile ()
unset(_harfbuzz_libdir_iter)

# Get the include subdir.
set(_harfbuzz_includedir "${prefix}/include")
string(REPLACE "${_harfbuzz_remove_string}/" "" _harfbuzz_includedir "${_harfbuzz_includedir}")

...

add_library(harfbuzz::harfbuzz SHARED IMPORTED)
set_target_properties(harfbuzz::harfbuzz PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_harfbuzz_prefix}/${_harfbuzz_includedir}/harfbuzz"
  IMPORTED_LOCATION "${_harfbuzz_prefix}/${_harfbuzz_libdir}/libharfbuzz${_harfbuzz_lib_suffix}")
```

By the start of the `while` loop, both `_harfbuzz_libdir` and `_harfbuzz_prefix` are set to `/usr/lib64`. The loop proceeds with two iterations, and on the third iteration both `_harfbuzz_libdir_prev_iter` and `_harfbuzz_libdir_iter` are equal to `/`, so the loop exists. Thus, `_harfbuzz_prefix` is replaced with its parent directory twice, resulting in `_harfbuzz_prefix` being `/` after the loop. `_harfbuzz_includedir` is set just to the value `include`.

In the end, the include directory happens to be `${_harfbuzz_prefix}/${_harfbuzz_includedir}/harfbuzz`, which expands to `//include/harfbuzz`, while the library location is `${_harfbuzz_prefix}/${_harfbuzz_libdir}/libharfbuzz${_harfbuzz_lib_suffix}`, which expands to `///usr/lib64/libharfbuzz.so.0.20600.7`. Clearly, both paths are plain wrong.

I would be happy to fix this myself in a pull-request, but I still have no idea what this code is supposed to do.

**Comment by khaledhosny** [comment]
CMake supported is going to be dropped in a future release and its use is discouraged. Meson is our currently supported build system.

**Comment by lisyarus** [comment]
@khaledhosny So, how are CMake users supposed to use harfbuzz in their projects?

**Comment by khaledhosny** [comment]
I don’t know, like they use any other project without CMake support. We can not afford to support multiple build system, and CMake was never our main build system. We are also dropping autotools support.

**Comment by ebraminio** [comment]
Guess the two concept, cmake config (the pkg-config equivalent of) and cmake build system is confused, we are able to keep the first just not able to afford to keep the second one.

However, we haven't forgot cmake or other build system users, we have a single file source `src/harfbuzz.cc` that includes the whole library and it is super easy to embed the library on any other software, that's the first and easiest solution, and the second solution is to use vcpkg https://github.com/harfbuzz/harfbuzz/issues/2586#issuecomment-663877560 which is going to use meson also https://github.com/microsoft/vcpkg/issues/12572 internally, so we either recommend use of vcpkg.cmake or, learn have vcpkg as a cmake project has done the work.

So harfbuzz, to the best of my knowledge, will be still best at providing solution for being embedded at other projects and we are just going to recommend meson and drop other things as our development build system.

**Comment by khaledhosny** [comment]
I’d prefer we don’t maintain any CMake config files, that is better handled with people who have better experience with CMake. The file looks to big a complicated for what it is supposed to do (at least compared to `pkg-config` file), but I’m not the maintainer so I wouldn’t be bothred either way.

**Comment by ebraminio** [comment]
> The file looks to big a complicated for what it is supposed to do (at least compared to pkg-config file)

Oooh I see. I haven't thought about it at all, totally of my blind spot, okay we definitely can decide about that also, considering user base and risks whether that has become cumbersome to maintain. Thank you very much!

**Comment by lisyarus** [comment]
@khaledhosny  Yes, I am talking about using harfbuzz as a dependency via CMake, doesn't matter how harfbuzz itself is built.

It is true that the file is quite big and complicated. As I've already said a few months ago, typical config files just contain hard-coded paths to the library (and potentially its dependencies), properly generated upon installation, as needed. @mathstuf seems to have a different opinion on this.

Typically, either the library provides its own `xxx-config.cmake`, or CMake distribution or the users themselves provide `FindXXX.cmake` scripts. So, if you are going to support the former, then `harfbuzz-config.cmake.in` has to be fixed; if you don't want to support it, this file should probably be just removed to prevent further confusion on the users' side.

**Comment by ebraminio** [comment]
> if you don't want to support it, this file should probably be just removed to prevent further confusion on the users' side.

Are you able to pkg config one and if so does that prevent issues like the one filed here? Thanks

**Comment by lisyarus** [comment]
@ebraminio Yes, pkg-config works for my harfbuzz installation. For my use cases I can just roll my own `FindHarfbuzz.cmake` or even add harfbuzz to `PATH`, that's not the point. The presence of `harfbuzz-config.cmake` in harfbuzz distribution indicates that it is supposed to work out of the box, but currently it is broken.

**Comment by ebraminio** [comment]
So I lean also toward its removal also now.

>  but I’m not the maintainer so I wouldn’t be bothred either way.

The titles are just meaningless and you are just awesome, please keep giving your opinion on every aspect of the project, best can be done if we put our thoughts together. Thank you very much :)

**Comment by lisyarus** [comment]
> best can be done if we put our thoughts together

Absolutely!

So, if `harfbuzz-config.cmake` is subject to removal, I'll probably try to push a `Findharfbuzz.cmake` script to CMake itself. I guess it can simply rely on pkg-config. Is pkg-config a reliable way to use harfbuzz?

**Comment by ebraminio** [comment]
> I'll probably try to push a Findharfbuzz.cmake script to CMake itself.

Awesome!

>  Is pkg-config a reliable way to use harfbuzz?

Definitely.

Thank you very much :)

**Comment by lisyarus** [comment]
Ok, thank you for your help.

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzz/pull/2601

**Comment by mathstuf** [comment]
> I'll probably try to push a Findharfbuzz.cmake script to CMake itself.

We've been rejecting new find modules in CMake itself. Keeping them up-to-date has not been feasible and it's best that packages ship ways of finding themselves. If it is `pkg-config`, then CMake consumers of Harfbuzz should use the `pkg-config`-related macros from `find_package(PkgConfig)` to provide it for themselves.

**Comment by ebraminio** [comment]
> [..] then CMake consumers of Harfbuzz should use the pkg-config-related macros from find_package(PkgConfig) to provide it for themselves.

So cmake users able to use `find_package(harfbuzz)` now and with the change they won't be able to? This is a bit worrying I guess.

**Comment by ebraminio** [comment]
So I am also open to revert https://github.com/harfbuzz/harfbuzz/commit/75efa893433b6f352c28bda9d0a92683244900aa if you or others request for, our intention is just try to provide our software in most accessible and best shape and quality, that's it.

**Comment by ebraminio** [comment]
@heftig, you applied a cmake config specific fix to Arch Linux package, love to get your input also here.

**Comment by heftig** [comment]
I just cherry-picked 53b0a183c7a4 to fix the libtool version meson inserts into the config file. I don't know much about cmake or which projects need the config file.
