### ISSUE TITLE
increase hb_mask_t to int64_t

### ISSUE THREAD

**Issue by mhosken** [harfbuzz/harfbuzz#2317]
We have a font in beta [Charis SIL](https://github.com/silnrsi/font-charis/releases/download/v5.950-beta1/CharisSIL-5.950-beta-dev-3cbfea.zip) that has more than 32 features. A quick count gives it 40. Currently hb_mask_t is limited to 32 bits and therefore the last few features will just be ignored, which is not a good thing.

Is there any reason not to increase hb_mask_t to 8 bits?

**Comment by mhosken** [comment]
OK. I see it now. It's only selected features that are also in the font. So the user would have to select over 20 of the features for there to be a problem. OK

**Comment by behdad** [comment]
Correct.  And we can't change it for API / ABI reasons.
