### ISSUE TITLE
Meson function checks should use headers

### ISSUE THREAD

**Issue by ePirat** [harfbuzz/harfbuzz#2318]
Currently the meson function checks do not specify in which header(s) the functions should be found, which is not really portable and breaks for example macOS targeting, as the headers are required to properly detect if a function is available on the targeted OS version or not.

I documented this in the meson docs somewhere in the past, but I have no idea where that documentation is gone now, at least I can't find it anywhere anymore...

I believe a similar issue exists for Android, but I am not sure.

https://github.com/harfbuzz/harfbuzz/blob/0d5695983e8bf3184ecd4cb92f737b9dfe5d6d25/meson.build#L66-L76

**Comment by khaledhosny** [comment]
Is this breaking anything for you? The corresponding autotools line does not seem to specify any header either:
https://github.com/harfbuzz/harfbuzz/blob/a99e8721bfdb3f346d169e0d3ff0a52e13fbd1d7/configure.ac#L71

**Comment by ePirat** [comment]
Yes they do not and its causing a lot of trouble when you build for example on macOS 10.15 but target as low as macOS 10.10, as all the check will do then is check it can link the function, which it of course can even though it will not actually be there on macOS 10.10. IIRC for the listed functions its not yet a problem as none of it is partially available, but anyway its a good idea to always add the header too.

Ideally meson would completely deprecate this kind of check without header, as its so easy to fall apart in different cases…

**Comment by khaledhosny** [comment]
If you have a PR that would be great, otherwise it is a very low priority since we are talking about hypothetical problems.

**Comment by ePirat** [comment]
I will try to find time to submit a PR for this :)

**Comment by behdad** [comment]
PR welcome.
