### ISSUE TITLE
Html tags in document errounously eacaped.

### ISSUE THREAD

**Issue by araxius** [harfbuzz/harfbuzz#2324]
In the utilities page, you can see multiple occurances of `<program>` and `</program>`

**Comment by ebraminio** [comment]
Oooh, @n8willis please have a look https://harfbuzz.github.io/utilities.html and https://github.com/harfbuzz/harfbuzz/blob/master/docs/usermanual-utilities.xml thanks

**Comment by n8willis** [comment]
Okay, so this is actually a DocBook tag thing, not an HTML thing. (For future reference.) 

But I put a fix in #2327 -- I ran a check through the other DocBook pages and found no other instances of that tag. Should be good.
