### ISSUE TITLE
[serialize] Remove unnecessary snapshot callsites

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2326]
The snapshot/revert call in GPOS PairPos is not necessary.  Review all calls and adjust.

**Comment by garretrieger** [comment]
Makes sense, that's a pattern that's been copied quite a bit. Should also update subset_offset_array (https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-layout-common.hh#L202).

**Comment by behdad** [comment]
subset_offset_array *does* need to do it.  Any caller that wants to throw out what a subset() call it made needs to do the snapshot/revert.  But the subset call that is going to return false doesn't have to.  I'm going to document the agreement before we push for cleaning.
