### ISSUE TITLE
hb_ot_layout_closure_features is wrong

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2330]
That functionality shouldn't be necessary for susbetting.  Is wrong that it was added and used.  Please describe what you are trying to do with it.

**Comment by behdad** [comment]
cc @qxliu76 @garretrieger

**Comment by qxliu76** [comment]
the result of closure_feature is used in remapping feature indexes. And feature index mapping is needed in subsetting ScriptList->Script->LangSysRecord, where we need replace old feature index with new feature index.

**Comment by behdad** [comment]
I understand that much.  The way this is done in fonttools is that we collect which features need to be retained, from defaults & user input.  Then collect looksups from those.  Then subset lookups and some of those become empty, then you go through features and features whose lookups were completely subsetted out you remove.

No need to add API.  The API seems extremely narrow and only needed the way you implemented subsetting.  Shouldn't even be exposed to subset plan.  Feature indices are GSUB/GPOS's internal business.

**Comment by behdad** [comment]
Let's figure out better layout subsetting design before changing things.

**Comment by behdad** [comment]
I know what I want.  To make these internal API of the subsetter.  They should move to `hb-subset-ot-layout.{cc,hh}`.  I'm writing more in another issue about restructuring layout subsetting code.
