### ISSUE TITLE
2.6.5 release tarball is missing on freedesktop.org

### ISSUE THREAD

**Issue by jbeich** [harfbuzz/harfbuzz#2333]
Is http://www.freedesktop.org/software/harfbuzz/release/ deprecated or just late?

**Comment by ebraminio** [comment]
At least temporarily deprecated till we reestablish our access to it :/

**Comment by behdad** [comment]
I don't have access to my old SSH key.  Easier to deprecate it at this point.

**Comment by behdad** [comment]
Where are places we reference freedesktop.org as our repo?  We should change those.

**Comment by jbeich** [comment]
@behdad, on the homepage:
> For tarball releases of HarfBuzz, look [here](http://www.freedesktop.org/software/harfbuzz/release/)

**Comment by jbeich** [comment]
https://harfbuzz.github.io/install-harfbuzz.html#download also points to freedesktop.

**Comment by kleisauke** [comment]
> Where are places we reference freedesktop.org as our repo? We should change those.

[The version check URL on Anitya](https://release-monitoring.org/project/1299/) is one place.

**Comment by kleisauke** [comment]
The above comment is no longer relevant and is resolved now. Thanks! :smile:

**Comment by khaledhosny** [comment]
We don’t reference freedesktop.org page anymore as well.
