### ISSUE TITLE
meson: fix_get_types.py missing from tarball

### ISSUE THREAD

**Issue by lazka** [harfbuzz/harfbuzz#2337]
```
../harfbuzz-2.6.5/src/meson.build:529:2: ERROR: File fix_get_types.py does not exist.
```

**Comment by ebraminio** [comment]
Ops, `fix_get_types.py` should've put as an EXTRA_DIST https://github.com/harfbuzz/harfbuzz/blob/master/src/Makefile.am#L15 for autotools so it could be copied to release tarball (not at my desk to fix myself :/)
