### ISSUE TITLE
meson: harfbuzz-icu not created/installed

### ISSUE THREAD

**Issue by lazka** [harfbuzz/harfbuzz#2338]
The autotools build creates a harfbuzz-icu.pc file while the meson one doesn't (with icu support being enabled with meson)

**Comment by ebraminio** [comment]
harfbuzz-icu is not a separated module in our meson port, but it should :/

https://github.com/harfbuzz/harfbuzz/blob/dced2fb/src/meson.build#L328-L332
vs
https://github.com/harfbuzz/harfbuzz/blob/dced2fb/src/Makefile.am#L163-L180

**Comment by lazka** [comment]
I'll look into it

**Comment by lazka** [comment]
I've created #2341
