### ISSUE TITLE
Add --with-icu=builtin like option to meson

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2343]
As #2341, hb-icu is separated in meson also which now matches with defaults of our autotools and cmake porst but autotools had an option to not have hb-icu as a separate module also https://github.com/harfbuzz/harfbuzz/blob/f9bc373/configure.ac#L278-L280 and https://github.com/harfbuzz/harfbuzz/blob/dced2fb/src/Makefile.am#L163-L180 guess would be nice to add such option in meson also.

**Comment by lazka** [comment]
oh, does that mean I should have removed this as well? https://github.com/harfbuzz/harfbuzz/blob/8ae06c9489f132844cbede80b5fe8241ce47fc0e/meson.build#L193

**Comment by ebraminio** [comment]
Oh, actually I didn't want to bug you for this one, feel free to review #2344 :)
