### ISSUE TITLE
[subset] Might end up with multiple table entries for same tag

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2361]
Will fill in.  Submitting before I forget.

**Comment by behdad** [comment]
The face builder doesn't drop tables with duplicate tags.  Wasn't done back then because we didn't have a templated hashmap.  We have now so should be fixed.

This is possible to cause artefacts in glyf+loca+head subsetting but is very unlikely that glyf suceeds and then loca or head fails, which is the required condition for it.

**Comment by behdad** [comment]
@garretrieger Can you fix this? Should be trivial: just use a hashmap instead of set?

**Comment by garretrieger** [comment]
on it.
