### ISSUE TITLE
hb-shape resets the reported x position

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#2371]
hb-shape sometimes seems to reset its x position. One glyph’s position will be reported correctly, the next’s won’t be reported at all, and the next’s will be reported much smaller than it should be.
```console
$ wget --quiet https://github.com/googlefonts/noto-fonts/raw/da636d8d8c6654fe3199aba049a1a278859a892b/phaseIII_only/unhinted/otf/NotoSansYi/NotoSansYi-Regular.otf
$ shape() {
    hb-shape --ned -u "$(
        for n in `seq 41000 $1`; do printf '%04X ' $n; done
    )" NotoSansYi-Regular.otf \
    | tr '|' '\n' \
    | tail -n 1
}
$ shape 41064
uniA068@38393,0]
$ shape 41065
uniA069]
$ shape 41066 
uniA06A@576,0]
```

**Comment by behdad** [comment]
I know what's happening...

The shape results are fine.  It's the serializing API.  We use a smallish serialize buffer and serialize to it till full, print it, continue.  If you ask for positions but no advance (as in `--ned`), needs to accumulate x,y and when it starts from middle it doesn't go collect x,y from before.   `--ned` mode was an afterthough.

We can enlarge the buffer hb-shape uses maybe.  That's easiest right now.

**Comment by behdad** [comment]
Or better perhaps we should have a function like `hb_buffer_normalize_glyphs()` (but separate!) that does all the x/y summation so serialize doesn't have to.

**Comment by behdad** [comment]
Here: https://github.com/harfbuzz/harfbuzz/blob/19346524c698586c24b0461648b33373092c60df/util/options.cc#L920

**Comment by behdad** [comment]
Feel free to increase that number 32-fold for now.

**Comment by behdad** [comment]
So what I suggested about adding a new function to call on buffer to make glyph positions absolute (and throw away advances, ouch) would also suggest changing behavior of serialization API to NOT do some magic that it does right now, which is it makes glyph offsets absolute if positions are requested but advances are not.  I don't have problem dropping that.  I don't think anyone is relying on that.

As for the absolution-positions API, maybe it keeps advances as well.  That would be a different scheme of representation in the buffer, so might be confusing to people using API if we have both, but maybe that's fine.
