### ISSUE TITLE
Meson build on windows - freetype hb-ft.h header missing in install directory

### ISSUE THREAD

**Issue by boxerab** [harfbuzz/harfbuzz#2377]
Windows: cairo source build requres harbuzz, but can't find `hb-ft.h` header because `freetype` is not installed. What is the best way to build freetype + harfbuzz on windows ?

**Comment by ebraminio** [comment]
The recommended way is to install for example first freetype without harfbuzz support then install harfbuzz with freetype and then freetype with harfbuzz support, however, even the fact I guess will be blamed for this but feel free to install freetype without harfbuzz support as it is not that important if you can afford to make it work, Chrome on Android last time I checked didn't have that part as it is mostly used for improving freetype hinting which can work without, hb-ft is much more in use than ft-hb!

**Comment by boxerab** [comment]
Thanks! I will give it a try :)

**Comment by mulle-nat** [comment]
This is still very annoying, not just on windows but also on linux, if you don't have freetype and harfbuzz installed and need to build from scratch. Circular dependencies are just very bad. Shouldn't ideally hb-ft.c and hb-ft.h move out of the harfbuzz project and into the freetype project ?
