### ISSUE TITLE
Round-tripping OpenType tags through BCP 47 losslessly

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#2380]
Firefox [calls `hb_ot_tag_to_language` and `hb_buffer_set_language`](https://hg.mozilla.org/mozilla-central/file/2b0e2483e2eaaef7ac49866a98e8e857520bdd5c/gfx/thebes/gfxHarfBuzzShaper.cpp#l1393) to implement [`font-language-override`](https://drafts.csswg.org/css-fonts-4/#propdef-font-language-override), which causes [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1346261): the tag is parsed case-insensitively but CSS says the string is case-sensitive.

I would like to fix this by adding a new private use subtag syntax to HarfBuzz: x-hbot-<var>AABBCCDD</var>, where each pair of letters in the trailing subtag represents a byte of the tag. For example, `hb_ot_tag_to_language` would convert the tag 'trk ' (which is _not_ the right tag for Turkish) to x-hbot-74726b20, which `hb_ot_tags_from_script_and_language` would later interpret as 'trk ' instead of [normalizing the case to 'TRK '](https://github.com/harfbuzz/harfbuzz/blob/e53c44e3260d6136e27635b5bbcb2da43bc4f1b1/src/hb-ot-tag.cc#L322-L323).

@behdad @jfkthame What do you think?

**Comment by behdad** [comment]
I'm not convinced we need this but am open to it.  Suggested format looks good to me.
