### ISSUE TITLE
Status on support of macOS "resource forks"

### ISSUE THREAD

**Issue by Jehan** [harfbuzz/harfbuzz#2383]
Hi all!

In GIMP, we [have a problem where some people are reporting fonts](https://gitlab.gnome.org/GNOME/gimp/-/issues/4900) which use to work and not anymore on macOS. After some investigation, it would seem these are "resource fork" fonts (file look 0B and all the font data is actually as some filesystem metadata; other than this, it is a known format).

From what I am told, this is because Pango does not use xfree86 anymore (which had resource fork support), but now it uses harfbuzz.

Yet looking into harfbuzz code, I found code added by #949 (and according to code comments, what is called "dfont" in the commit message is the same as resource fork, isn't it?).

So are resource forks actually supported by harfbuzz? Thanks! 🙂

**Comment by ebraminio** [comment]
Hi Jehan, we of course support OpenType inside ResourceFork since the mentioned PR. Lots of comments there but apparently you don't still have access to the actual file personally, do you? How we can have access to it? Can you mail it to me privately for testing purposes? Thanks!

**Comment by Jehan** [comment]
Files themselves were 0B, but this comment has the resource fork content: https://gitlab.gnome.org/GNOME/gimp/-/issues/4900#note_782712

The call was not complete though, created by `xattr -p com.apple.ResourceFork Stencil > Stencil.ttf`, but in text hexa form. After having downloading the file from this comment, you can get the actual font with: `cat Stencil.ttf | xxd -r -p  > Stencil2.ttf`
(I don't know if this is a commercial font, at the very least the reporter did not ask us to make the report confidential)

This file works well here on my GIMP (Linux). And one of the reporters confirmed that for him too, once he did this process and left the new file in the same directory as the former empty file, it is now seen by his GIMP (macOS). I don't really know much more.

**Comment by khaledhosny** [comment]
I think these are old resource fork PostScript fonts. There is /System/Library/Fonts/HelveLTMM and  /System/Library/Fonts/TimesLTMM in latest macOS but FontBook does not list them. SFNT resource fork fonts like /System/Library/Fonts/Courier.dfont work fine.

**Comment by Jehan** [comment]
@khaledhosny Is there some command line or GUI tool on macOS which can tell us what exact type of resource font this is? We can ask the reporter to check.

In any case, it would be nice to have support for these older resource fork font types too (apparently the content format is already supported since it works by manually grabbing the content).

**Comment by khaledhosny** [comment]
> @khaledhosny Is there some command line or GUI tool on macOS which can tell us what exact type of resource font this is? We can ask the reporter to check.

`file` should do:
```
$ file /System/Library/Fonts/Monaco.dfont
/System/Library/Fonts/Monaco.dfont: Mac OSX datafork font, 'NFNT'
$ file /System/Library/Fonts/HelveLTMM 
/System/Library/Fonts/HelveLTMM: Mac OSX datafork font, PostScript
```

**Comment by khaledhosny** [comment]
I don’t have any tool that can open that Stencil.ttf file (after converting it with `xxd`) not FontForge (which often supports all forms of arcane font formats) and FontTools.

**Comment by khaledhosny** [comment]
> I don’t have any tool that can open that Stencil.ttf file

FontBook can open it and HarfBuzz can use it too, weird.

**Comment by Jehan** [comment]
After you told me it may be a postscript font, I searched what was the usual extension for such font files. If I rename it to `Stencil.pfm`, fontforge opens it without any problem. With the `.ttf` extension though, it indeed fails (seems like fontforge relies entirely on the extension instead of detecting actual format).

Also GNOME fonts open the file without issue too (however you name it, even with a wrong or no extension).

And GIMP was opening the font without any problem, whatever the extension as well (well not GIMP exactly, but whatever software stack we use for fonts, which includes fontconfig/Pango/HarfBuzz).

I guess it's just not a `ttf` file as you guessed first, and software which don't do proper format detection just fail to load it.

**Comment by Jehan** [comment]
For the record, `file` on these resource fork fonts just show "empty" (as run by one of the reporters). It doesn't seem to actually show what's inside the resource fork metadata.

```
Microsoft $ file Stencil
Stencil: empty
Microsoft $ file "Wide Latin"
Wide Latin: empty
Microsoft $ file "Trebuchet MS" 
Trebuchet MS: empty
```

**Comment by Jehan** [comment]
Also we discovered that the resource fork fonts broke since Pango 1.44 (we had an older installer with Pango 1.43 and suddenly they rework).

So if I understand correctly (it's all still a bit fuzzy to me), this is when harfbuzz started being used for font loading and some font formats stopped being supported. Yet if we extract the fonts manually with `xattr`, they just work fine, even with Pango 1.44. So it seems to be these fonts should not have been impacted by the bump to Pango 1.44. No?

**Comment by khaledhosny** [comment]
Does `hb-view` or `hb-shape` work on these fonts? If yes (which would be my guess), someone with access to these fonts will need to figure out how FreeType manages to load them.

**Comment by Jehan** [comment]
I asked. I'm not sure if our reporter will be able to figure out the second request (though who knows!).

Is there no way to transfer such resource fork fonts? Like maybe some reverse `xattr` or something to put metadata back into a file on some other system? This format is so weird.

**Comment by hughjonesd** [comment]
> Does hb-view or hb-shape work on these fonts?

Nope:
```
Microsoft $ hb-view Trebuchet\ MS 
hb-view: Couldn't read or find Trebuchet MS, or it was empty.
Microsoft $ hb-shape Trebuchet\ MS
hb-shape: Couldn't read or find Trebuchet MS, or it was empty.

```
Similar with other 0-byte fonts. This is using Harfbuzz 2.6.5, installed via brew.

**Comment by khaledhosny** [comment]
Oh, may bad, `hb-view` and `hb-shape` use HarfBuzz to read the font file (even when using FreeType font functions), so would suffer from the same issue. `ftview` from FreeType would be a better test then, but does not seem like Homebrew installs it.

**Comment by khaledhosny** [comment]
[`ftrfork.c`](https://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/src/base/ftrfork.c) presumably has the code that FreeType uses to load resource fork fonts, if it is of any help to @ebraminio.

**Comment by ebraminio** [comment]
Am asking again, is anyone able to share one of the fonts in question privately? I just checked with macOS installed resource fonts and they work fine except when the font inside ResourceFork container is Type1.

>> Does hb-view or hb-shape work on these fonts?
>
> Nope:

So it broken with freetype font funcs also as we use them by default, one should pass `--font-fucs=ot` to test harfbuzz font loading.

**Comment by Jehan** [comment]
@ebraminio 
> Am asking again, is anyone able to share one of the fonts in question privately?

If you tell us how to do so, then I'm sure @hughjonesd (our reporter from GIMP bugtracker) will be able to do so. So far, we have only been able to extract them with `xattr` into normal font files.

**Comment by jfkthame** [comment]
> Am asking again, is anyone able to share one of the fonts in question privately? I just checked with macOS installed .dfont files.

Just in case anyone is confused by this, note that .dfont files are not resource-fork files; IIRC, they use the same *format* as the old Mac resource-fork fonts, but stored in the data fork of the file.

To share a resource-fork font (e.g. by email) without converting it to some other format (such as with xattr), it might work (I haven't tested this!) to compress it into a .zip archive on the original macOS system (e.g. with the Finder's "Compress..." context-menu command, not with a third-party utility). But the recipient will also need to uncompress similarly (on a Mac) if there's to be any chance of it coming through intact; otherwise, the resource-fork is likely to either be split out into a separate directory or dropped.

> "/..namedfork/rsrc"

Yes, this is how to open the resource fork as a regular file on macOS. Having done that, I'd guess it would then be like handling a .dfont file.

**Comment by ebraminio** [comment]
> If you tell us how to do so, then I'm sure @hughjonesd (our reporter from GIMP bugtracker) will be able to do so.

Sure, my mail address is visible on my GitHub profile @ebraminio.

>  So far, we have only been able to extract them with xattr into normal font files.

That is a good sign I believe, however is the command issued to 0 length files? That weird.

**Comment by jfkthame** [comment]
> That is a good sign I believe, however is the command issued to 0 length files? That's weird.

The file size shown by e.g. `ls -l FontFile` only refers to the data fork. A resource-fork-only font file has an empty data fork, so this is expected.

**Comment by Jehan** [comment]
> Sure, my mail address is visible on my GitHub profile @ebraminio.

The problem was not where to, but how, since resource fork files are 0B files (all actual data is metadata in the file system). So every time reporters tried to send one, it was just sending empty files, which is why we ended up extracting the metadata instead.

@jfkthame 
> To share a resource-fork font (e.g. by email) without converting it to some other format (such as with xattr), it might work (I haven't tested this!) to compress it into a .zip archive on the original macOS system (e.g. with the Finder's "Compress..." context-menu command, not with a third-party utility). But the recipient will also need to uncompress similarly (on a Mac) if there's to be any chance of it coming through intact; otherwise, the resource-fork is likely to either be split out into a separate directory or dropped.

Ah this is exactly what we were looking for! @hughjonesd if you could try?

**Comment by Jehan** [comment]
@hughjonesd It doesn't look like the zip archive came through by email. Could you try uploading it directly with a browser?

**Comment by hughjonesd** [comment]
Try this.

[Archive.zip](https://github.com/harfbuzz/harfbuzz/files/4558598/Archive.zip)

**Comment by khaledhosny** [comment]
With the attached files:
```
$ hb-shape Garamond AAA --font-funcs=ot
hb-shape: Couldn't read or find Garamond, or it was empty.
$ hb-shape Garamond/..namedfork/rsrc AAA --font-funcs=ot
[A=0+1387|A=1+1387|A=2+1387]
```

I wounder if `hb_blob_create_from_file()` should try appending `/..namedfork/rsrc` to file name if normal loading fails?

**Comment by jfkthame** [comment]
Yes, that works. Unarchiving it on macOS, I get two files which the Finder reports as kind: Font Suitcase, with sizes around 282KB and 543KB; while `ls -l` shows them as being size 0.

And in Terminal (as expected):
```
$ file Garamond 
Garamond: empty
$ ls -l Garamond 
-rw-rw-r--@ 1 jkew  staff  0 17 May  2019 Garamond
$ ls -l Garamond/..namedfork/rsrc
-rw-rw-r--  1 jkew  staff  281960 17 May  2019 Garamond/..namedfork/rsrc
```

**Comment by jfkthame** [comment]
> I wounder if `hb_blob_create_from_file()` should try appending `/..namedfork/rsrc` to file name if normal loading fails?

Or perhaps it should just try that if `fstat` reports a file length of zero?

**Comment by khaledhosny** [comment]
Of course, opening dos not actually fail, `open()` rerturns a positive file descriptor, but indeed `fstat()` returns a size of zero.

**Comment by ebraminio** [comment]
Thank you all! So this may work but maybe it is Pango's or a font manager's job to workaround that as `hb_blob_create_from_file` isn't necessarily about font files? Of course ResourceFork also isn't necessarily font file, and what happens if a resource fork file has multiple files or it isn't possible?

```diff
diff --git a/src/hb-blob.cc b/src/hb-blob.cc
index 74a62f12..b3150e46 100644
--- a/src/hb-blob.cc
+++ b/src/hb-blob.cc
@@ -543,6 +543,20 @@ hb_blob_create_from_file (const char *file_name)
   struct stat st;
   if (unlikely (fstat (fd, &st) == -1)) goto fail;
 
+#ifdef __APPLE__
+  /* Empty file, maybe is a resource fork?
+   * https://github.com/harfbuzz/harfbuzz/issues/2383 */
+  if (unlikely (!st.st_size))
+  {
+    close (fd);
+    free (file);
+
+    char rsrc_path[1024];
+    snprintf (rsrc_path, 1024, "%s/..namedfork/rsrc", file_name);
+    return hb_blob_create_from_file (rsrc_path);
+  }
+#endif
+
   file->length = (unsigned long) st.st_size;
   file->contents = (char *) mmap (nullptr, file->length, PROT_READ,
                                  MAP_PRIVATE | MAP_NORESERVE, fd, 0);
```

Guess `if (unlikely (strstr (".namedfork/rsrc"))) return hb_blob_get_empty ();` can also be added after `free (file);` in order to mitigate superfluous nested call or let's add such logic to `hb-view` and Pango anyway.

**Comment by ebraminio** [comment]
So thanks to Khaled fix and jfk's key help this is fixed and will be in the next release which hopefully will be soon. Thanks!

**Comment by Jehan** [comment]
Thanks everyone for the reactivity on this report! 😃
