### ISSUE TITLE
Dotted circle is not inserted for Khmer Consonant Shifters and ROBAT

### ISSUE THREAD

**Issue by sovichet** [harfbuzz/harfbuzz#2384]
Most of Khmer marks have a dotted circle inserted when they are not attached to the base letter, but there are 3 glyphs that don't have it:

- Consonant Shifters: Triisap (U+17CA) and Muusikatoan (U+17C9)
- Robat (U+17CC)

<img width="1127" alt="Screen Shot 2020-04-29 at 10 33 47" src="https://user-images.githubusercontent.com/1669566/80558691-7627a280-8a05-11ea-8757-241ecb6b2f4d.png">

**Comment by behdad** [comment]
@jfkthame maybe knows.  Do those mark happen to be allowed on non-letters?

**Comment by Richard57** [comment]
In handwriting there is the combination ៙៉ <U+17D9 KHMER SIGN PHNAEK MUAN, U+17C9 KHMER SIGN MUUSIKATOAN>, cited in _Antelme inventaire provisoire des caractères et divers signes des écritures khmères pré-modernes et modernes employés pour la notation du khmer, du siamois, des dialectes thaïs méridionaux, du sanskrit et du pāli_ in paragraph 64, on p47.  It appears to be synonymous with plain U+17D9.  The identification of the superscript is supported by the description in Thai sources of the upper element as "rat's teeth" in the corresponding (and practically identical) punctuation mark.  MUUSIKATOAN means rat's teeth.

The simple solution is to treat non-letter U+17D9 as a 'general base', like U+00D7 MULTIPLICATION SIGN.

**Comment by Richard57** [comment]
"Antelme" is not part of the title - it's the name of the author.

**Comment by sovichet** [comment]
@behdad for better visual presentation, the dotted circle should be inserted for these marks or it will shift to the left (because it's a nonspacing mark).

_Screenshot on Chrome for the word ញ៉ាំ (ញ ៉ ា ំ)_

<img width="338" alt="Screen Shot 2020-05-27 at 16 29 17" src="https://user-images.githubusercontent.com/1669566/83002620-78e2db00-a037-11ea-956b-2b37ec643cb3.png">

**Comment by sovichet** [comment]
@Richard57 yes, there are chances like that, but I think that could be substituted by a single glyph in ccmp feature.

**Comment by Richard57** [comment]
Your spacing argument is invalid.  If you want spacing, you should remember to allocate a space-like character for a non-spacing mark to sit upon.

If my reading of collect_features_khmer() in hb-ot-shape-complex-khmer.cc is correct, ccmp applies after the insertion of dotted circles and does not apply across them.  The first cleanup opportunity would be in feature abvs.  Making phnaek muan a base is much more civilised, and leads to a Unicode-compliant solution.
