### ISSUE TITLE
RFE: provide unicode support using [g]glibc unicode support

### ISSUE THREAD

**Issue by kloczek** [harfbuzz/harfbuzz#2408]
Seems like harfbuzz is using libicu on handling univode.

Is it possoble to use by harfbuzz only unicode support from [g]libc?

Almost everything else uses charsets handl;ing support from libc ..

**Comment by ebraminio** [comment]
HarfBuzz supports glib's unicode support also but you can also use harfbuzz without any unicode library and that's even the preferred way to use harfbuzz nowadays.

**Comment by khaledhosny** [comment]
May be start with explaining the actual issue you have not what you think is the fix.

**Comment by kloczek** [comment]
OK I found how to compile harfbuzz without ICU.

A bit misleading was that is build separated DSO with ICO support but looks like that  DSO is for that kind of code which is intentionally using ICU :)

Closing
