### ISSUE TITLE
meson and mingw

### ISSUE THREAD

**Issue by vtorri** [harfbuzz/harfbuzz#2413]
Hello

for compilation of hb with msys2 + mingw-w64, i would use cross-compilation. Because technically  speaking, it is cross-compilation, and it allows also cross-compilation on linux. I use this kind of file with a sed command to replacewhat is between @ : 

https://github.com/vtorri/ewpi/blob/master/packages/glib2/cross_toolchain.txt

**Comment by ebraminio** [comment]
oh, not that sure about the intention so maybe something @lazka also can help as is apparently msys2 related but we do need such thing of course for our mingw builds to replace 10th level of our releasing https://github.com/harfbuzz/harfbuzz/blob/ba3c77e/RELEASING.md and to replace https://github.com/harfbuzz/harfbuzz/blob/ba3c77ef23eab3d0ab597ed89a7811be12ca0a6a/mingw32.sh and https://github.com/harfbuzz/harfbuzz/blob/ba3c77ef23eab3d0ab597ed89a7811be12ca0a6a/mingw64.sh thanks! Is it something you feel you can contribute here you believe? And if not I had to do eventually of course! We are using that script in our CI bot https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml#L216-L223 and like to replace that with some tested meson based solution of course. Thanks!

**Comment by vtorri** [comment]
the steps would be : 

- adding cross.txt
- adding  a script that takes as arguments (in that order) : 
  - the prefix
  - the host (either i686 or x86_64)
  - rm -rf builddir, create builddir and goes in it
  - does a sed command on cross.txt into this subdir
  - launch meson + ninja

is it ok for you ?

**Comment by lazka** [comment]
I don't have any experience with cross compiling. I know glib has a CI job doing it on fedora with meson using

* https://gitlab.gnome.org/GNOME/glib/-/blob/master/.gitlab-ci/mingw.Dockerfile
* https://gitlab.gnome.org/GNOME/glib/-/blob/master/.gitlab-ci/cross_file_mingw64.txt

**Comment by ebraminio** [comment]
Sounds great! Feel free to upload the PR. Thanks!

**Comment by ebraminio** [comment]
> I know glib has a CI job doing it on fedora with meson using

great, I should integrate those also, thanks!

**Comment by vtorri** [comment]
here is a preliminary work : 

[cross.txt](https://github.com/harfbuzz/harfbuzz/files/4648630/cross.txt)
[mingw-meson.sh.gz](https://github.com/harfbuzz/harfbuzz/files/4648668/mingw-meson.sh.gz)

Usage (with msys2 for example): 

```
./mingw-meson.sh /opt/hb x86_64
```

output :

**Comment by ebraminio** [comment]
Looks good, feel free to upload them in PR, cross.txt may need some more specific naming maybe meson-mingw-cross.txt.in to indicate it is a template used for meson for mingw builds. I am more interested on crosscompiling Windows binaries from Linux which I know as meson's subprojects system should be easily possible and will investigate that after merge of your so you can expect I change your works a little bit afterward, thanks :)

**Comment by vtorri** [comment]
i'm cross compiling on linux too and there is absolutely no change to do. This is one of my pet project which builds, on Linux or Windows, a set of libraries for a toolkit: https://github.com/vtorri/ewpi

**Comment by vtorri** [comment]
see #2423
