### ISSUE TITLE
meson output status

### ISSUE THREAD

**Issue by vtorri** [harfbuzz/harfbuzz#2414]
hello

configure is displaying a complete status, to see the options that are available or not

what about doing the same with meson build system ?

**Comment by ebraminio** [comment]
Is it possible and does that have a idiomatic way in meson? If so, I don't see why not! Some coloring also would be nice :)

**Comment by vtorri** [comment]
i use the message() function for that. It's not ideal, though.

**Comment by vtorri** [comment]
better : https://mesonbuild.com/Reference-manual.html#summary

**Comment by ebraminio** [comment]
oooh, that looks nice!

**Comment by ebraminio** [comment]
Uploaded a fix here https://github.com/harfbuzz/harfbuzz/pull/2421
