### ISSUE TITLE
Setting the wrong script results in nonsensical ligatures

### ISSUE THREAD

**Issue by pipcet** [harfbuzz/harfbuzz#2424]
I'm still trying to figure out how to make Emacs use harfbuzz more extensively. It's looking good, so far, but one problem we have is that we don't always know the language or script in use. (We do know the direction of writing).

So I played around a little to see just how bad things are with incorrect script values, and I was surprised that setting an hb buffer to the (nonsensical) combination of `HB_DIRECTION_LTR` and `HB_SCRIPT_HEBREW` results in "if" being replaced by an "fi" ligature.

While I understand that withholding the language or specifying the wrong script may make the results suboptimal, I do think they shouldn't be outright nonsensical.

(I guess I'm also highly skeptical of the whole idea of requiring language or script information to produce any output. It's probably a good idea with CJK unification, but I shudder to think of the irritating language-specific idiosyncrasies people might introduce in Latin alphabets. IIRC, MS-DOS had a different "p" glyph on the Icelandic code page, probably to make it more contrastive with the thorn character...)

So feel free to close this if you feel incorrect script selection is something that users should be punished for so severely, but I'd like to respectfully disagree.

**Comment by khaledhosny** [comment]
Script is a Unicode character property, so if you have the text then you can always get the script (the only complication are characters with no specific script like punctuation, which need to be resolved based on surroundings). Language is needed to select language-specific OpenType lookups (like Urdu having different set of digits than Persian while sharing the same Unicode code points, or Serbian Cyrrilic having some different italic forms than the default), but failure to set it will give the default lookups for the script which is not ideal but OKish (and for many languages and fonts that is all needed).

HarfBuzz always processes the text in the native direction of the specified script (RTL in case of Hebrew), and reverses the buffer (while keeping grapheme clusters as one unit) if the set direction does not match the native direction.

In general, setting the wrong script will result in all kinds of brokenness as there are often script-specific, and OpenType layout lookups inside the fonts are organized by script (and language, but of language is not set there is the ”default” language, but default script is not always present and even if present not always adequate for proper layout).

**Comment by behdad** [comment]
What khaled said.  It's one thing to not set script and call `hb_buffer_guess_segment_properties`.  Is another to set it wrong.

**Comment by pipcet** [comment]
Thanks! I think I understand the concepts much better now!

**Comment by behdad** [comment]
You are right that from a user point of view it doesn't make sense that we require script to be provided.  But that's how OpenType works and we have not found a better interface.  We do provide things like `guess_segment_properties` to help clients in transition to fully correct shaping.
