### ISSUE TITLE
[hb-view] Use libchafa if available...

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2430]
https://hpjansson.org/chafa/

We can also make it work without cairo with a bit of bitmap code.

**Comment by behdad** [comment]
<img width="852" alt="Screen Shot 2021-04-18 at 2 21 33 PM" src="https://user-images.githubusercontent.com/142891/115159641-0ca30880-a049-11eb-923a-70dcd4fd1bf9.png">
<img width="559" alt="Screen Shot 2021-04-18 at 2 21 41 PM" src="https://user-images.githubusercontent.com/142891/115159642-0d3b9f00-a049-11eb-8fb1-2f649d48fd32.png">

**Comment by behdad** [comment]
```
$ ./hb-view NotoNastaliqUrdu-Regular.ttf بهداد | chafa - -c none --invert
```
<img width="854" alt="Screen Shot 2021-04-18 at 2 40 41 PM" src="https://user-images.githubusercontent.com/142891/115160173-b7b4c180-a04b-11eb-8c28-fcb560e1cdc1.png">

**Comment by hpjansson** [comment]
![hb-view-hello](https://user-images.githubusercontent.com/234488/115955405-7eba9800-a4f6-11eb-8136-fcf12afe0ae0.png)

From top to bottom: Old renderer in VTE, Chafa renderer in VTE, Chafa renderer in mlterm.

**Comment by behdad** [comment]
<img width="444" alt="Screen Shot 2021-04-23 at 9 10 38 AM" src="https://user-images.githubusercontent.com/142891/115968209-94769000-a4eb-11eb-9472-3284af48129a.png">
<img width="986" alt="Screen Shot 2021-04-23 at 9 09 21 AM" src="https://user-images.githubusercontent.com/142891/115968213-950f2680-a4eb-11eb-8282-8bf71615faff.png">

**Comment by hpjansson** [comment]
Hmm, looks like there's room for improvement in the terminal detection; if I'm not mistaken, yours can do 256 colors, but you're getting 16 by default. Which terminal is it, and could you check what's in TERM? Maybe it sets other useful env vars too.

**Comment by behdad** [comment]
Oh mine was using cmdline chafa, not your patch. I'll text your patch soon. Thanks!

**Comment by khaledhosny** [comment]
From mlterm screenshot, looks like Chava supports sixel already, that is good news!
