### ISSUE TITLE
Manual and API reference Outdated

### ISSUE THREAD

**Issue by Rickodesea** [harfbuzz/harfbuzz#2435]
The manual and API reference are extremely outdated.  It is not 100% reliable to write code with the most up-to-date harfbuzz library.

[API reference](https://harfbuzz.github.io/ch12.html)
[manual](https://harfbuzz.github.io/ch03s03.html)

**Comment by ebraminio** [comment]
Hi! Thanks for reaching out! Hmm, they look good to me, any particular issue? (cc: @n8willis)

Maybe https://harfbuzz.github.io/ch03s03.html could use harfbuzz font loading as is simpler or maybe not as freetype many non-OT things we don't or may won't support ever.

**Comment by behdad** [comment]
> The manual and API reference are extremely outdated

Yeah I don't see what you are talking about either.  Looks recent to me, has 2.6 symbols listed:
https://harfbuzz.github.io/index.html

**Comment by ebraminio** [comment]
Maybe a bit unrelated but now it is built using GTK-Doc V1.27 instead GTK-Doc V1.20 https://github.com/harfbuzz/harfbuzz.github.io/commit/8bc36f4e75111f902692dcbdff42baf3d785086f since the migration https://github.com/harfbuzz/harfbuzz/commit/5293fdb
