### ISSUE TITLE
Meson migration

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2436]
Let's list things our meson port misses so we know when we can do the actual transition, (whom have access, feel free to edit the post)

* https://github.com/harfbuzz/harfbuzz/blob/e248a4e/test/api/Makefile.am#L189-L207 move the logic to some python script and put the CLEANFILES in .gitignore
* Done: https://github.com/harfbuzz/harfbuzz/blob/6058ede/Makefile.am#L47-L62 <s>do we need CHANGELOG? If so, how</s> #2475
* Done: https://github.com/harfbuzz/harfbuzz/blob/7250ade/src/Makefile.am#L271-L296 put them on some bash script I guess. (uploaded #2438)
* Done: Turning `gobject`, `introspection`, <s>`graphite`</s> features https://github.com/harfbuzz/harfbuzz/blob/master/meson_options.txt from 'disabled' to 'auto'? (uploaded #2437)
* Remove https://github.com/harfbuzz/harfbuzz/blob/6058ede/meson.build#L6

Anything else? Of course there are! Let me know!

**Comment by behdad** [comment]
So, where's the `make distcheck` and `make dist` equivalents in your list?

**Comment by tp-m** [comment]
> So, where's the `make distcheck` and `make dist` equivalents in your list?

`ninja dist` or `meson dist`? (Don't think there's a way to skip the checks yet during dist)

**Comment by ebraminio** [comment]
> So, where's the `make distcheck` and `make dist` equivalents in your list?

As indicated by @tp-m, those aren't separated in meson release process. We just need to make sure our regular build in meson is equivalent with distcheck that's why #2437 is needed.

**Comment by behdad** [comment]
> * [ ]  https://github.com/harfbuzz/harfbuzz/blob/e248a4e/test/api/Makefile.am#L189-L207 move the logic to some python script and put the CLEANFILES in .gitignore
> *

There's no CLEANFILES issue since meson builds out-of-tree only.

**Comment by ebraminio** [comment]
> There's no CLEANFILES issue since meson builds out-of-tree only.

Good point, it can do in tree ones which apparently not common anyway, thanks

**Comment by heftig** [comment]
Meson doesn't version the libraries like autotools does (`.so.0.20608.0` but should be `.so.0.20600.8`). If you want to keep the scheme, you need to use the libtool `current`, `age` and `revision` you calculate to determine the `version` and `soversion`.

**Comment by ebraminio** [comment]
Something completely overlooked, thank you very much! Our [meson versioning scheme](https://github.com/harfbuzz/harfbuzz/blob/e4203c1/meson.build#L13-L22) however apparently completely matches with [autotools one](https://github.com/harfbuzz/harfbuzz/blob/e4203c1/configure.ac#L46-L59) AFAICS? we really don't practice such kind of versioning, wonder where this logic is coming from as I've never seen use of it or any mention of it in RELEASING doc or anywhere.

**Comment by heftig** [comment]
This is the code that actually sets the library versions:

https://github.com/harfbuzz/harfbuzz/blob/e4203c14699cc0903a2b4611167a7b99532cfdb0/src/meson.build#L382-L392

**Comment by ebraminio** [comment]
> This is the code that actually sets the library versions:

Have a look at #2488

**Comment by ebraminio** [comment]
@heftig: Thanks for taking time and evaluate the meson port btw, hopefully this one isn't that issue as it was happening on odd minor versions on autotools also, please have a look if anything else is missing. Thank you very much!

**Comment by ebraminio** [comment]
Thanks to @heftig and other dear packagers, this is *slowly* happening, and our release process now is in favor of meson #2545 so let's close this, and carefully evaluate and apply the next steps, thanks :)
