### ISSUE TITLE
meson question: cairo pkg-config dependencies

### ISSUE THREAD

**Issue by lazka** [harfbuzz/harfbuzz#2441]
We currently get

```
prefix=/mingw64
libdir=${prefix}/lib
includedir=${prefix}/include

Name: harfbuzz
Description: HarfBuzz text shaping library
Version: 2.6.6
Requires.private: glib-2.0, gobject-2.0, cairo, cairo-ft, graphite2, freetype2, fontconfig
Libs: -L${libdir} -lharfbuzz
Libs.private: -lm -lusp10 -lgdi32 -lrpcrt4 -ldwrite
Cflags:-I${includedir}/harfbuzz
```

This makes libharfbuzz depend on cairo, gobject, freetype2, fontconfig, I wonder if this is on purpose?

Previously it was just

```
prefix=/mingw64
exec_prefix=/mingw64
libdir=/mingw64/lib
includedir=/mingw64/include

Name: harfbuzz
Description: HarfBuzz text shaping library
Version: 2.6.4

Libs: -L${libdir} -lharfbuzz
Libs.private: -lm  -lusp10 -lgdi32 -lrpcrt4   
Requires.private: glib-2.0 >= 2.19.1 graphite2 >= 1.2.0
Cflags: -I${includedir}/harfbuzz
```

**Comment by lazka** [comment]
ok, I guess the reason is that there is one giant "deps" list where all dependencies get put in instead of making libraries only depend on the things they actually use. If I clean this up the .pc files end up like with autotools

I can look into this, but this will touch everything, so I'd like to get approval first.

**Comment by ebraminio** [comment]
oh, how I didn't see this, makes sense, please go for it if possible
