### ISSUE TITLE
[meson] Why amalgam option?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2444]
The `harfbuzz.cc` file exists for people who can't / don't want to use our provided build systems.  Why is it deemed useful to expose an option for it in meson? It adds yet another configuration without any benefits.

To me, we just want to have one bot raw-compile `harfbuzz.cc` and that's about it.

Feel free to keep whatever.  But to me options that don't add value are not a good idea.

**Comment by ebraminio** [comment]
Makes sense. Gone 870304df76
