### ISSUE TITLE
[meson] with_stdcxx won't actually link to stdc++

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2446]
link_language is actually a not released yet feature of meson that's why I didn't get suspicious even after https://github.com/harfbuzz/harfbuzz/commit/d67553d12fc72c4a89fcb75400829b62d53ca064 about it but with further testing something feels wrong.

steps to reproduce, 
1. harfbuzz master
2. `pip install git+https://github.com/mesonbuild/meson` so link_language can have effect.
3. `rm -rf build && meson build -Dwith_libstdcxx=true && ninja -Cbuild -v`

`[75/246] clang++  -o src/libharfbuzz.so.0.20607.0 'src/25a6634@@harfbuzz@sha/hb-aat-layout.cc.o' ...  'src/25a6634@@harfbuzz@sha/hb-glib.cc.o' -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libharfbuzz.so.0 -pthread -lm /usr/lib/libfreetype.so /usr/lib/libglib-2.0.so -lstdc++ -Wl,--end-group`

(`...` is the trimmed part, note the clang++ and -lstdc++ also)

```
$ ldd build/src/libharfbuzz.so.0.20607.0

        linux-vdso.so.1 (0x00007ffc1a568000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f01f0c8c000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f01f0bbe000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f01f0a96000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f01f0a74000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f01f08ae000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f01f1065000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f01f089b000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f01f0861000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f01f0847000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f01f07d5000)
```

Note the lack libstdc++ on ldd result

For sake of completion this is what happens when -Dwith_libstdcxx isn't passed,

`[75/246] clang  -o src/libharfbuzz.so.0.20607.0 'src/25a6634@@harfbuzz@sha/hb-aat-layout.cc.o' ... 'src/25a6634@@harfbuzz@sha/hb-glib.cc.o' -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libharfbuzz.so.0 -pthread -lm /usr/lib/libfreetype.so /usr/lib/libglib-2.0.so -Wl,--end-group`

----

Now using autotools with libstdc++ option,

1. `./autogen.sh --with-libstdc++`
2. `make -j9 V=1`

`/bin/sh ../libtool  --tag=CXX   --mode=link clang++  -fno-rtti -g -O2 -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++11  -Bsymbolic-functions -o libharfbuzz.la  -lm -version-info 20600:7:20600 -no-undefined   -rpath /usr/local/lib libharfbuzz_la-hb-aat-layout.lo ... libharfbuzz_la-hb-ft.lo                -lglib-2.0  -lfreetype         `

```
$ ldd src/.libs/libharfbuzz.so          
        linux-vdso.so.1 (0x00007fffc12e0000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f61e68c0000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f61e67f2000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f61e6609000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f61e64c3000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f61e62fd000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f61e62e3000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f61e626f000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f61e624d000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f61e623a000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f61e6202000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f61e61e8000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f61e6b23000)
```

**Comment by ebraminio** [comment]
also comparing them, `-fno-rtti -g -O2 -fno-exceptions -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++11 -Bsymbolic-functions` are missing from linker, guess add_project_arguments [flags](https://github.com/harfbuzz/harfbuzz/blob/fb46a32/meson.build#L44-L49) aren't passed to linker.

**Comment by ebraminio** [comment]
But what was needed about the flag wasn't the need for linking to stdc++ but using of a C++ linker so one can get exceptions and things, so maybe we can rename the option also.

**Comment by behdad** [comment]
The reason we did this originally was to enable fuzzers etc that rely on libstdc++.  Maybe is okay without it until we hit that issue again.  I haven't fully studied the problem or history, but worth checking why we added it.

**Comment by behdad** [comment]
> The reason we did this originally was to enable fuzzers etc that rely on libstdc++. Maybe is okay without it until we hit that issue again. I haven't fully studied the problem or history, but worth checking why we added it.

But do debug please!

**Comment by ebraminio** [comment]
> But do debug please!

Sure, won't go without it anywhere! Just was thinking loudly if one can have C++ linker without stdc++, that isn't a bad thing but a good and maybe we can rename the option, that's it.

**Comment by behdad** [comment]
> if one can have C++ linker without stdc++

Yes.

**Comment by ebraminio** [comment]
The answer is in `-Wl,--as-needed` that meson passes but autotools don't, so now we can find a better naming for the option, but is there any interest on replicating that on autotools also and changing its option also?

**Comment by ebraminio** [comment]
It was introduced https://github.com/harfbuzz/harfbuzz/pull/770 as https://github.com/google/oss-fuzz/issues/1085 but no use oss-fuzz whatsoever, I wonder if we need this at all or lets drop it from meson anyway.

**Comment by behdad** [comment]
If oss-fuzz not using it currently, I'm fine with removing.

**Comment by ebraminio** [comment]
#2450
