### ISSUE TITLE
Add hb-subset --glyphs / --glyphs-file

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#2455]
IIUC, hb-subset will currently only take a text to choose what to subset. pyftsubset will also take a list of glyph names or a file with a list of glyph names (`--glyphs` and `--glyphs-file`). This allows to explicitly select glyphs without a Unicode code point attached. Would be nice to have in hb-subset :)

**Comment by garretrieger** [comment]
In addition to --text, hb-subset also supports the "--gids" option which can be used to specify the glyph ids to keep. So if you're able to map glyph names to ids for your use case you could use that.

**Comment by madig** [comment]
In version 2.6.7, there is no `--gids` option?

**Comment by behdad** [comment]
We should add the `--glyphs-file` and `--gids-file` etc that match pyftsubset IMO.
