### ISSUE TITLE
AAT and split vowels - case in point Sinhala

### ISSUE THREAD

**Issue by murasu** [harfbuzz/harfbuzz#2459]
There is a morx bug in Sinhala Sangam MN in macOS 10.15 (Catalina). Split vowel signs are handled correctly when a single code point is used. However, when the two code point equivalent is used, a dotted circle gets inserted. It's a simple bug that can be easily fixed in the morx table. (This is not the issue).

<img width="737" alt="image" src="https://user-images.githubusercontent.com/22926756/84163550-3217cb00-aaa4-11ea-9357-af66038ab870.png">
>Fig 1: The string `0DBA, 0DD9, 0DCF, 0020, 0DBA, 0DDC ` rendered in CoreText
<br />
The question is, this bug does not show up when the same string is rendered in Harfbuzz 2.6.7, which also picks the morx/kerx tables over GSUB/GPOS.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/22926756/84164084-b8341180-aaa4-11ea-8f12-fe6a9a100259.png">
>Fig 2: The same string is rendered correctly in Harfbuzz (ignore the color codes)
<br/>
I'm wondering if Harfbuzz substitutes the two code points to the single point equivalent internally before applying the morx rules. If this is the case, does it not handle morx differently than CoreText?

**Comment by khaledhosny** [comment]
HarfBuzz applies canonical composition if the composed form is supported by the font, so my guess is yes to your question:
```
$ hb-shape -V 'Sinhala Sangam MN.ttc' -u '0DBA,0DD9,0DCF,0020,0DBA,0DDC'
trace: start chain subtable 0	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: end chain subtable 0	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: start chain subtable 1	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: end chain subtable 1	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: start chain subtable 2	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: end chain subtable 2	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: start chain subtable 3	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: end chain subtable 3	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: start chain subtable 4	buffer: [sin_ya=0|sin_o_matra=0|space=3|sin_ya=4|sin_o_matra=4]
trace: end chain subtable 4	buffer: [sin_ya=0|sin_o_matra=0|sin_aa_matra=0|space=3|sin_ya=4|sin_o_matra=4|sin_aa_matra=4]
trace: start chain subtable 5	buffer: [sin_ya=0|sin_o_matra=0|sin_aa_matra=0|space=3|sin_ya=4|sin_o_matra=4|sin_aa_matra=4]
trace: end chain subtable 5	buffer: [sin_ya=0|sin_e_matra=0|sin_aa_matra=0|space=3|sin_ya=4|sin_e_matra=4|sin_aa_matra=4]
trace: start chain subtable 6	buffer: [sin_ya=0|sin_e_matra=0|sin_aa_matra=0|space=3|sin_ya=4|sin_e_matra=4|sin_aa_matra=4]
trace: end chain subtable 6	buffer: [sin_e_matra=0|sin_ya=0|sin_aa_matra=0|space=3|sin_e_matra=4|sin_ya=4|sin_aa_matra=4]
trace: start chain subtable 7	buffer: [sin_e_matra=0|sin_ya=0|sin_aa_matra=0|space=3|sin_e_matra=4|sin_ya=4|sin_aa_matra=4]
trace: end chain subtable 7	buffer: [sin_e_matra=0|sin_ya=0|sin_aa_matra=0|space=3|sin_e_matra=4|sin_ya=4|sin_aa_matra=4]
trace: start chain subtable 8	buffer: [sin_e_matra=0|sin_ya=0|sin_aa_matra=0|space=3|sin_e_matra=4|sin_ya=4|sin_aa_matra=4]
trace: end chain subtable 8	buffer: [sin_e_matra=0|sin_ya=0|sin_aa_matra=0|space=3|sin_e_matra=4|sin_ya=4|sin_aa_matra=4]
[sin_e_matra=0+1013|sin_ya=0+1266|sin_aa_matra=0+586|space=3+467|sin_e_matra=4+1013|sin_ya=4+1266|sin_aa_matra=4+586]
```

**Comment by jfkthame** [comment]
How are your sample images created? When I enable Core Text shaping in Firefox, both versions (decomposed and precomposed) still render the same for me (on macOS 10.15.4).

**Comment by khaledhosny** [comment]
I get the dotted circle with `hb-view --shaper=coretext` as well as in Text Edit.

**Comment by jfkthame** [comment]
Interesting! Ah, yes - I can also reproduce the dotted circle in TextEdit. It disappears if I turn off the "Stand Alone Matras" feature in the font.

I don't think we do anything special about this in Firefox, though, so I'm unsure why it works there.

**Comment by murasu** [comment]
I can precompose the decomposed forms in the morx. That will fix the problem in CoreText. It's good to know that Harfbuzz applies canonical composition.

**Comment by murasu** [comment]
> Interesting! Ah, yes - I can also reproduce the dotted circle in TextEdit. It disappears if I turn off the "Stand Alone Matras" feature in the font.
> 
> I don't think we do anything special about this in Firefox, though, so I'm unsure why it works there.

Is there a chance that the shaping is done with the OpenType tables in the font?

**Comment by khaledhosny** [comment]
(HarfBuzz will also apply canonical decomposition if the composed form is *not* supported by the font and decomposed form is supported, but it always prefers composed form when supported.

**Comment by jfkthame** [comment]
> > Interesting! Ah, yes - I can also reproduce the dotted circle in TextEdit. It disappears if I turn off the "Stand Alone Matras" feature in the font.
> > I don't think we do anything special about this in Firefox, though, so I'm unsure why it works there.
> 
> Is there a chance that the shaping is done with the OpenType tables in the font?

Maybe; I don't know how Core Text would make that choice. I don't recall that we do anything to "direct" its behavior, we just pass the font & text to CTLineCreateWithAttributedString, and then render the resulting glyphs.

**Comment by murasu** [comment]
> > > Interesting! Ah, yes - I can also reproduce the dotted circle in TextEdit. It disappears if I turn off the "Stand Alone Matras" feature in the font.
> > > I don't think we do anything special about this in Firefox, though, so I'm unsure why it works there.
> > 
> > 
> > Is there a chance that the shaping is done with the OpenType tables in the font?
> 
> Maybe; I don't know how Core Text would make that choice. I don't recall that we do anything to "direct" its behavior, we just pass the font & text to CTLineCreateWithAttributedString, and then render the resulting glyphs.

Is the composition of the decomposed matras done before calling CTLineCreateWithAttributedString ?  Just guessing.

**Comment by jfkthame** [comment]
> > > > Interesting! Ah, yes - I can also reproduce the dotted circle in TextEdit. It disappears if I turn off the "Stand Alone Matras" feature in the font.
> > > > I don't think we do anything special about this in Firefox, though, so I'm unsure why it works there.
> > > 
> > > 
> > > Is there a chance that the shaping is done with the OpenType tables in the font?
> > 
> > 
> > Maybe; I don't know how Core Text would make that choice. I don't recall that we do anything to "direct" its behavior, we just pass the font & text to CTLineCreateWithAttributedString, and then render the resulting glyphs.
> 
> Is the composition of the decomposed matras done before calling CTLineCreateWithAttributedString ? Just guessing.

Good idea, but no -- I double-checked (by logging the string at the CTLineCreateWithAttributedString call site) and it's definitely still decomposed when we pass it to Core Text.

**Comment by murasu** [comment]
> > > > > Interesting! Ah, yes - I can also reproduce the dotted circle in TextEdit. It disappears if I turn off the "Stand Alone Matras" feature in the font.
> > > > > I don't think we do anything special about this in Firefox, though, so I'm unsure why it works there.
> > > > 
> > > > 
> > > > Is there a chance that the shaping is done with the OpenType tables in the font?
> > > 
> > > 
> > > Maybe; I don't know how Core Text would make that choice. I don't recall that we do anything to "direct" its behavior, we just pass the font & text to CTLineCreateWithAttributedString, and then render the resulting glyphs.
> > 
> > 
> > Is the composition of the decomposed matras done before calling CTLineCreateWithAttributedString ? Just guessing.
> 
> Good idea, but no -- I double-checked (by logging the string at the CTLineCreateWithAttributedString call site) and it's definitely still decomposed when we pass it to Core Text.

I can't figure what's happening. I would also like to check if the ctFont used is the attributedString is created with Sinhala Sangam MN. The first image in the sample I posted above is constructed with the output from CTLineCreateWithAttributedString.

**Comment by jfkthame** [comment]
> I can't figure what's happening. I would also like to check if the ctFont used is the attributedString is created with Sinhala Sangam MN. The first image in the sample I posted above is constructed with the output from CTLineCreateWithAttributedString.

Yes, it is: I dumped the string with CFLog immediately before the CTLineCreateWithAttributedString call, and it shows:
```
2020-06-09 17:34:53.331 plugin-container[38150:2202306] යො 0x10842e7a0 {NSWritingDirection=(
    2
), NSFont=<CTFont: 0x1044ec660>{name = SinhalaSangamMN, size = 200.000000, matrix = 0x0, descriptor = <CTFontDescriptor: 0x17362f760>{attributes = {
    NSFontNameAttribute = SinhalaSangamMN;
}>}}} Len 3
```
And for the example using the precomposed split-vowel, it shows:
```
2020-06-09 17:34:53.332 plugin-container[38150:2202306] යො 0x10842ed20 {NSWritingDirection=(
    2
), NSFont=<CTFont: 0x1044ec660>{name = SinhalaSangamMN, size = 200.000000, matrix = 0x0, descriptor = <CTFontDescriptor: 0x17362f760>{attributes = {
    NSFontNameAttribute = SinhalaSangamMN;
}>}}} Len 2
```
And both versions result in proper shaping.

I still have no idea why it works here, while TextEdit (for example) fails.

**Comment by jfkthame** [comment]
BTW, in my Terminal the Sinhala string in the first case above actually *does* show the dotted circle, confirming that it is the decomposed representation (and Terminal's rendering doesn't handle it), also confirmed because it has length 3. It looks like copy/pasting it here may have normalized the string, but it really was in decomposed form within Firefox!

**Comment by murasu** [comment]
@jfkthame I'm not sure what's happening in Firefox. The outcome is consistent is all other places where the shaping is handled by CoreText. My initial question on what happens in HB is also answered. I added a substitution to compose the decomposed forms as the first table in morx. This makes the output of CoreText and Harfbuzz consistent :)
