### ISSUE TITLE
harfbuzz support in freetype, build fails

### ISSUE THREAD

**Issue by nofaceanime** [harfbuzz/harfbuzz#2460]
i am trying to add harfbuzz support to freetype in mobile-ffmpeg for android and ios. I tried building harfbuzz disabling freetype and fontconfig support. And then i enabled harfbuzz support when building freetype, But build fails with this error log

```bash
freetype/src/autofit/afshaper.h:31:10: fatal error: 'hb-ft.h' file not found
#include <hb-ft.h>
         ^~~~~~~~~
1 error generated.
```

can someone help please ?

**Comment by khaledhosny** [comment]
I think you have to do it the other way around, freetype, harfbuzz, freetype.

**Comment by nofaceanime** [comment]
alright, let me try it out

**Comment by ebraminio** [comment]
as https://github.com/harfbuzz/harfbuzz/issues/2377#issuecomment-619208446 feel free to skip building freetype to harfbuzz support (so just build freetype and then harfbuzz with freetype support, skip the rest), hinting isn't that important thing in mobile space given the DPI android and ios devices already have.
