### ISSUE TITLE
ReverseChainSingleSubstFormat1 with 0 glyphCount

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2467]
While working on https://github.com/adobe-type-tools/afdko/pull/1158, we noticed that `ReverseChainSingleSubstFormat1` subtable with 0 `glyphCount` will use GID 0 for replacement, while CoreText and Uniscribe will ignore the subtable. Using [ignore-rsub.zip](https://github.com/harfbuzz/harfbuzz/files/4767581/ignore-rsub.zip) font (which has one lookup with two lookups, one with 0 `glyphCount` and the other substituting `A` with `A.alt1`:
```
$ hb-shape ignore-rsub.otf 'AB A' --no-positions --shapers=ot 
[.notdef=0|B=1|space=2|A.alt1=3]
$ hb-shape ignore-rsub.otf 'AB A' --no-positions --shapers=coretext
[A.alt1=0|B=1|space=2|A.alt1=3]
```

Looks like HarfBuzz accepts the subtable during sanization, even though the length of the `substituteGlyphIDs` array does not match the coverage table, then the `[]` operator will return `Null` because the index (0) equals the array length (0).

The example is probably contrived and this is not the way to implement `ignore rsub` (if it makes any sense at all), but it might be nice to ignore the subtable for compatibility with the other implementations.

SingleSubstFormat2 and may be SingleSubstFormat3 might have a similar issue (I didn’t test that, though).

**Comment by behdad** [comment]
That's exactly what happening. Fix is to make a rule w zero glyphs to fail.

**Comment by behdad** [comment]
> Fix is to make a rule w zero glyphs to fail.

This part was wrong.

**Comment by behdad** [comment]
Okay we can refuse substituting.

**Comment by behdad** [comment]
> SingleSubstFormat2 and may be SingleSubstFormat3 might have a similar issue (I didn’t test that, though).

There's no Format3.  You meant just Format1?

**Comment by behdad** [comment]
SingleSubstFormat2 already does that:
```
    if (unlikely (index >= substitute.len)) return_trace (false);
```

**Comment by behdad** [comment]
Fixed.  Would be nice to add a test.  Thanks!

**Comment by khaledhosny** [comment]
Added a test in https://github.com/harfbuzz/harfbuzz/commit/2598855454b77b69633220e7e912b2ac82f450f9

**Comment by khaledhosny** [comment]
> > SingleSubstFormat2 and may be SingleSubstFormat3 might have a similar issue (I didn’t test that, though).
> 
> There's no Format3. You meant just Format1?

No idea what I was taking about, it was probably late at night.
