### ISSUE TITLE
Inconsistency in how cursive attachments override each other

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#2469]
I’ve found a puzzling inconsistency in how left-to-right and right-to-left cursive attachments choose the baseline when they override each other. I’m not sure whether it’s a bug.

[CursTest.otf](https://github.com/harfbuzz/harfbuzz/files/4774865/CursTest.otf.gz) contains two glyphs: `u1BC36`, which is cursively joining, and `period`, which serves to show where the baseline is. There are three cursive attachment lookups, with the features 'ltr1', 'rtl1', and 'ltr2'. The second one is marked right-to-left. Their anchor points are identical.

I tested the font with the string <U+002E, U+1BC36, U+1BC36, U+1BC36, U+1BC36> (“.𛰶𛰶𛰶𛰶”) with various combinations of those features. As expected, both 'ltr1' and 'ltr2' put the first letter on the baseline and 'rtl1' puts the last letter on the baseline. Enabling both 'ltr1' and 'rtl1' also puts the last letter on the baseline, implying that the last cursive attachment takes precedence.

'ltr1' or 'ltr2':
![“.𛰶𛰶𛰶𛰶” with 'ltr1'](https://user-images.githubusercontent.com/1124347/84572408-ae8e0080-ad67-11ea-842d-56ef0ad899fd.png)

'rtl1' or 'ltr1'+'rtl1':
![“.𛰶𛰶𛰶𛰶” with 'rtl1'](https://user-images.githubusercontent.com/1124347/84572416-ca91a200-ad67-11ea-889f-c32a84e54c19.png)

Enabling both 'rtl1' and 'ltr2' puts the _second_ letter on the baseline. I would have expected 'ltr2' to take precedence and produce a result identical to 'ltr2' alone. Alternatively, since this combination favors the second letter, I would have expected 'ltr1'+'rtl1' to favor the penultimate letter. Either way, it seems inconsistent.

'rtl1'+'ltr2':
![“.𛰶𛰶𛰶𛰶” with 'rtl1'+'ltr2'](https://user-images.githubusercontent.com/1124347/84572442-0167b800-ad68-11ea-95a3-a7920389c024.png)

**Comment by behdad** [comment]
You are right.  I have to think.  We do something rather convoluted in these cases.  I'll explain.

**Comment by behdad** [comment]
I was suspecting this dance:
https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-layout-gpos-table.hh#L1680-L1693

However, I know what's going on: The first two get recursively attached to eachother.  When we start resolving those, we attach first to second because that one is processed first. Called from:
https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-layout-gpos-table.hh#L2684

I'm not sure what's the best solution.  In that tree-walking loop we can also walk the parent's chain and if we find child there, then break that link.  I'm fine doing that in general.  What I don't like is that as marks keep piling up the runtime would be O(N^2).  Currently that's not, and that's something we make sure does not happen in shaping.

Let me think more.

**Comment by behdad** [comment]
The obvious fix is to just check if parent is immediately attached to child.  Yeah let me do that.

**Comment by behdad** [comment]
I pushed a fix.  Please add a test.  We have a test file for cursive attachments I believe.

**Comment by behdad** [comment]
[Didn't test that my fix works.]

**Comment by behdad** [comment]
And I broke our cursive test.  Fairly sure the expected-output can/should change.

**Comment by behdad** [comment]
cc @khaledhosny because last time we adjusted this based on his experiments.

**Comment by behdad** [comment]
Reverted my change.  Would be great if someone can finish it.  I won't be able to look into this again for a while but can discuss.

**Comment by behdad** [comment]
> And I broke our cursive test. Fairly sure the expected-output can/should change.

Checked the new output and am not sure is a welcome change.  The test was a very obscure set of lookups as well.  So we need to reanalyze which behavior is best in that situation.

**Comment by behdad** [comment]
This is the relevant commit:
https://github.com/harfbuzz/harfbuzz/commit/6578575cc8aeb05341f2053039acfcd735707674

**Comment by behdad** [comment]
And the thread: https://lists.freedesktop.org/archives/harfbuzz/2015-August/005005.html

**Comment by behdad** [comment]
Okay I read the thread again.  I think my proposed change shouldn't break the tests.  So, needs investigation towards that.

**Comment by dscorbett** [comment]
In your commit that you reverted, there’s `=` in a condition; did you mean `==`?

**Comment by behdad** [comment]
> In your commit that you reverted, there’s `=` in a condition; did you mean `==`?

Ha!

**Comment by behdad** [comment]
Please test now.

**Comment by dscorbett** [comment]
That change makes it more consistent but the result is still weird. 'rtl1'+'ltr2' now sets the baseline relative to the penultimate glyph, just as 'ltr1'+'rtl1' sets it relative to the second glyph. So the last cursive lookup takes precedence except for one glyph on the end? Is that what Windows does? I can work around this by adding an invisible cursive glyph at both ends, so that the whole visible part of the chain gets repositioned.


'ltr1'+'rtl1':
![.𛰶𛰶𛰶𛰶](https://user-images.githubusercontent.com/1124347/85020171-ec12d500-b13d-11ea-9974-74d48ae9689d.png)

**Comment by behdad** [comment]
Please text what windows and ideally mac do. I'll find a way to adjust.

**Comment by dscorbett** [comment]
I built the latest commit on Windows and ran all eight combinations of the three features with `--shapers uniscribe`. It seems like the first lookup takes precedence for positioning the baseline.

<table>
<th>'ltr1'<th>'rtl1'<th>'ltr2'<th>Result
<tr><td>0<td>0<td>0<td>no cursive attachment
<tr><td>0<td>0<td>1<td>baseline at first letter
<tr><td>0<td>1<td>0<td>baseline at last letter
<tr><td>0<td>1<td>1<td>baseline at last letter
<tr><td>1<td>0<td>0<td>baseline at first letter
<tr><td>1<td>0<td>1<td>baseline at first letter
<tr><td>1<td>1<td>0<td>baseline at first letter
<tr><td>1<td>1<td>1<td>baseline at first letter
</table>

Ditto for `--shapers directwrite`.

I also ran them on macOS with `--shapers coretext`. All of them (except the one with nothing enabled) put the baseline at the first letter.

**Comment by behdad** [comment]
Thanks!  I'll see if I can make this happen.  In a sense, it's a more solid way.

**Comment by behdad** [comment]
But yeah then we need to figure out what to do what Khaled's case.

**Comment by behdad** [comment]
Any chance you can run the tests in `cursive-joining` against Uniscribe as well?

**Comment by khaledhosny** [comment]
That test was supposed to match Uniscribe when it was made, if this changed I’m fine changing it (I ended up not using this idea as it would have meant waiting until new HarfBuzz is used widely enough back then, years passed since then I don’t think I’m changing the font at this point).

**Comment by behdad** [comment]
> That test was supposed to match Uniscribe when it was made, if this changed I’m fine changing it

No that hasn't changed.  We'll tweak till we match Uniscribe then.

**Comment by dscorbett** [comment]
Here are the cursive tests with Uniscribe:
```
$ test/shaping/run-tests.py build/util/hb-shape.exe test/shaping/data/in-house/tests/cursive-positioning.tests
Running tests in test/shaping/data/in-house/tests/cursive-positioning.tests
build/util/hb-shape.exe "test/shaping/data/in-house/fonts/c4e48b0886ef460f532fb49f00047ec92c432ec0.ttf" --shaper=uniscribe --verify  --unicodes U+0643,U+0645,U+0645,U+062B,U+0644
Actual:   [gid8=4+738|gid5=3@441,1197+0|gid6=3@0,432+405|gid9=2@0,477+452|gid9=1@0,977+472|gid10=0@0,1577+187]
Expected: [gid8=4+738|gid5=3@441,1197+0|gid6=3@0,432+405|gid9=2@0,477+452|gid9=1@0,977+452|gid10=0@20,1577+207]
build/util/hb-shape.exe "test/shaping/data/in-house/fonts/298c9e1d955f10f6f72c6915c3c6ff9bf9695cec.ttf" --shaper=uniscribe --verify  --unicodes U+0643,U+0645,U+0645,U+062B,U+0644
Actual:   [gid8=4+738|gid5=3@441,1197+0|gid6=3@0,432+405|gid9=2@0,477+500|gid9=1@0,577+472|gid10=0@0,1177+187]
Expected: [gid8=4+738|gid5=3@441,1197+0|gid6=3@0,432+405|gid9=2@0,477+500|gid9=1@0,577+452|gid10=0@20,1177+207]
# build/util/hb-shape.exe "test/shaping/data/in-house/fonts/706c5d7b625f207bc0d874c67237aad6f1e9cd6f.ttf" --unicodes U+0B1F,U+0B4D,U+0B1A,U+0B4D,U+0B1A
build/util/hb-shape.exe "test/shaping/data/in-house/fonts/07f054357ff8638bac3711b422a1e31180bba863.ttf" --shaper=uniscribe --verify --font-funcs=ot --no-glyph-names --unicodes U+0606,U+06E1
Actual:   [2=1@40,502+0|1=0+1000]
Expected: [2=0@40,502+0|1=0+1000]
build/util/hb-shape.exe "test/shaping/data/in-house/fonts/9fc3e6960b3520e5304033ef5fd540285f72f14d.ttf" --shaper=uniscribe --verify  --unicodes U+16F0A,U+16F57,U+16F8F
Actual:   error: all shapers failed.
Expected: [u16F0A=0+422|u16F57=0@0,209+338|u16F8F=0+0]
4 tests passed; 4 failed; 0 skipped.
```

**Comment by behdad** [comment]
Interesting about the "all shapers failed".

**Comment by behdad** [comment]
> I built the latest commit on Windows and ran all eight combinations of the three features with `--shapers uniscribe`. It seems like the first lookup takes precedence for positioning the baseline.

The code here doesn't look consistent with that, at least to my reading:
https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/MS/Internal/Shaping/Positioning.cs,1418

I was hoping that the CSharp code would illuminate what Uniscribe/Dwrite are doing.

**Comment by behdad** [comment]
Okay, I fixed

**Comment by behdad** [comment]
Okay I fixed most of this, which is the fact that things were aligning mid-sequence. It still is not the same as Uniscribe though.
We should probably at least add tests.
