### ISSUE TITLE
Rename "master" branch to "mainline" or other

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2470]
Ideally github will implement this so users requesting old name will automatically get new name and no one's dependencies will stop working.  But we should fix regardless.  Let's look at how other projects are doing it.

**Comment by khaledhosny** [comment]
GitHub seems to have support for renaming branches now which will take care of updating also open PR, but people will need to manually update their local clones (the instruction will be shown when people visit the repository after the rename, it seems).

https://github.com/github/renaming

**Comment by behdad** [comment]
Other projects have settled on "main" it seems. Let's do.

**Comment by behdad** [comment]
Fixed.
