### ISSUE TITLE
[meson] Having someway to identify the git commit a release tarball refers to

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2472]
There's no point whatsoever to shipping a ChangeLog file in tarballs.  meson replacement is the right time to remove that relic of the past.  I'm open to doing it earlier as well.

**Comment by behdad** [comment]
Well.  The only thing it serves as is to identify the git commit this tarball refers to.  So maybe we keep but let's rethink what it does and adjust as needed.

**Comment by ebraminio** [comment]
Meson doesn't have it, so nothing actionable here, merge with #2472

**Comment by ebraminio** [comment]
> Well. The only thing it serves as is to identify the git commit this tarball refers to.

Let's follow meson's tradition there I say and raise the concern with meson if needed.

**Comment by behdad** [comment]
> Let's follow meson's tradition there I say and raise the concern with meson if needed.

Yes please.  Can you do that?

**Comment by ebraminio** [comment]
https://github.com/mesonbuild/meson/issues/7354

**Comment by ebraminio** [comment]
https://github.com/mesonbuild/meson/issues/7354#issuecomment-646256479
