### ISSUE TITLE
Implement CFF

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#249]
It's a pain, but to implement hb-ot-font `get_extents` for CFF fonts, we need to implement pretty much all of CFF...

**Comment by KrasnayaPloshchad** [comment]
This may should be fixed along with CFF2 table.

**Comment by ebraminio** [comment]
Great that now we have #1113, shouldn't we merge that and add support for CFF's get_extents now that ot-font is used by default?

**Comment by ebraminio** [comment]
And of course it is another fuzzing hole :)

**Comment by behdad** [comment]
> Great that now we have #1113, shouldn't we merge that and add support for CFF's get_extents now that ot-font is used by default?

Yes.  Post-release.

**Comment by ebraminio** [comment]
As #1113
