### ISSUE TITLE
Memory leak in OpenType shape plan upon allocation failure...

### ISSUE THREAD

**Issue by sebras** [harfbuzz/harfbuzz#2495]
More testing of memory allocation failing using clang+ASAN revealed a memory leak in HarfBuzz 2.6.4, which still seems to be present in git HEAD.

This is the backtrace in HarfBuzz for where a call to `realloc()` makes an allocation that is never freed:

```
    #0 0x1242163 in hb_vector_t<hb_ot_map_t::feature_map_t>::alloc(unsigned int) harfbuzz/src/hb-vector.hh:202:28
    #1 0x1241d25 in hb_vector_t<hb_ot_map_t::feature_map_t>::resize(int) harfbuzz/src/hb-vector.hh:219:10
    #2 0x123e605 in hb_vector_t<hb_ot_map_t::feature_map_t>::push() harfbuzz/src/hb-vector.hh:167:9
    #3 0x123bb49 in hb_ot_map_builder_t::compile(hb_ot_map_t&, hb_ot_shape_plan_key_t const&) harfbuzz/src/hb-ot-map.cc:255:50
    #4 0xdb4168 in hb_ot_shape_planner_t::compile(hb_ot_shape_plan_t&, hb_ot_shape_plan_key_t const&) harfbuzz/src/hb-ot-shape.cc:108:7
    #5 0xdb67c9 in hb_ot_shape_plan_t::init0(hb_face_t*, hb_shape_plan_key_t const*) harfbuzz/src/hb-ot-shape.cc:225:11
    #6 0xe73f8c in hb_shape_plan_create2 harfbuzz/src/hb-shape-plan.cc:232:7
    #7 0xe75158 in hb_shape_plan_create_cached2 harfbuzz/src/hb-shape-plan.cc:489:33
    #8 0xe72443 in hb_shape_full harfbuzz/src/hb-shape.cc:135:33
    #9 0xe7251f in hb_shape harfbuzz/src/hb-shape.cc:169:3
```

This is the backtrace where the leak above is provoked by having `calloc()` return `NULL`:

```
#0  data_create_arabic (plan=0x612000000e28) at harfbuzz/src/hb-ot-shape-complex-arabic.cc:264
#1  0x0000000000db6896 in hb_ot_shape_plan_t::init0 (this=0x612000000e28, face=0x6140000c8648, key=0x612000000de0) at harfbuzz/src/hb-ot-shape.cc:229
#2  0x0000000000e73f8d in hb_shape_plan_create2 (face=0x6140000c8648, props=0x611000000a80, user_features=0x0, num_user_features=0, coords=0x0, num_coords=0, shaper_list=0x0) at harfbuzz/src/hb-shape-plan.cc:232
#3  0x0000000000e75159 in hb_shape_plan_create_cached2 (face=0x6140000c8648, props=0x611000000a80, user_features=0x0, num_user_features=0, coords=0x0, num_coords=0, shaper_list=0x0) at harfbuzz/src/hb-shape-plan.cc:489
#4  0x0000000000e72444 in hb_shape_full (font=0x60d0000006c8, buffer=0x611000000a48, features=0x0, num_features=0, shaper_list=0x0) at thirdparty/harfbuzz/src/hb-shape.cc:135
#5  0x0000000000e72520 in hb_shape (font=0x60d0000006c8, buffer=0x611000000a48, features=0x0, num_features=0) at harfbuzz/src/hb-shape.cc:169
```

Looking at the [source code](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape.cc#L221) reveals that in normal cases `data` will be set and `hb_ot_shape_plan_t::init0()` returns `true`, later on `hb_ot_shape_plan_t::fini()` would have been called, and it would have used `map.fini()` and `aat_map.fini()` to free the resources. But due to `data` being `NULL`, `hb_ot_shape_plan_t::init0()` returns `false`, and `hb_ot_shape_plan_t::fini()` will never be called, this is the reason for the memory leak.

**Comment by ebraminio** [comment]
I like these fixes but like to see a systematic fix for them also, do you think you can provide someway so we can have your exact testing setup?

Maybe we should fuzz harfbuzz under some kind of allocator that randomly fails given fuzzer input (to make it deterministic) so we can have such thing in oss-fuzz. Or maybe oss-fuzz should do something like that and this idea should be forwarded to this project.

**Comment by behdad** [comment]
> Maybe we should fuzz harfbuzz under some kind of allocator that randomly fails given fuzzer input (to make it deterministic) so we can have such thing in oss-fuzz. Or maybe oss-fuzz should do something like that and this idea should be forwarded to oss-fuzz.

Totally. It's actually trivial!  I'll try to come up with a solution.

**Comment by sebras** [comment]
> I like these fixes but like to see a systematic fix for them also,
> do you think you can provide someway so we can have your exact testing setup?

I'd advice against using [my setup](https://github.com/harfbuzz/harfbuzz/issues/2489#issuecomment-648281443) since it includes code not related to HarfBuzz, and does not cover the entire API. I agree with behdad that it would benefit HarfBuzz most if its own testsuite could be used to root out issues like these.

These four issues (#2489, #2493, #2495 and #2501) I found trivially. Sorry about somewhat flooding you guys with these, but I'd rather report than forget about them. At least #2501 was the last one.

**Comment by ebraminio** [comment]
> Sorry about somewhat flooding you guys with these, but I'd rather report than forget about them. 

Not at all, please go as far as you can, it is really nice to have them fixed and we will try to find some systematic solution for it.

> In my case I have wrapped malloc()/realloc() as a custom allocator for MuPDF, albeit with an allocation counter limit. When the limit is tripped I have the custom allocator (and thus hb_malloc_impl()) return NULL.

Oh this is very good. We can have something alike easily. Thanks!

How you ended up using -subset btw? http://git.ghostscript.com/?p=mupdf.git;a=blob;f=Makethird;h=1bc87e694d774dd9bce9eb738e06d700b943cf5c;hb=HEAD#l119 I like to encourage you to use src/harfbuzz.cc instead listing the sources which doesn't have the subset of course (do you need it? if so we can add that also there). Thanks

**Comment by ebraminio** [comment]
https://github.com/google/oss-fuzz/issues/1675#issuecomment-410371405

ulimit looked like that systematic solution but isn't asan compatible, apparently we have to handle ourselves like https://github.com/open62541/open62541/pull/2188/files

**Comment by behdad** [comment]
> Sorry about somewhat flooding you guys with these, but I'd rather report than forget about them.

PUHleeze. Keep them ALL coming!!!

I'll soon develop a rig for us to be continuously testing this and expect tens or more of issues coming in. :))

**Comment by behdad** [comment]
Only if we had a way for oss-fuzz or other CI to automatically file github issues?

**Comment by ebraminio** [comment]
> [...] we will try to find some systematic solution for it.

Our systematic solution has just landed https://github.com/harfbuzz/harfbuzz/pull/2566 just wanted to attribute your works :) and the fact hb-ft isn't covered with our fuzzer as we didn't want to fuzz an external library of course so feel free to see what else is missing. Thank you very much :)
