### ISSUE TITLE
Markdown in docs

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2500]
Can we have markdown docs in tree that get built and used by our gtk-doc-based docs? That would help me write a lot of documentation. cc @n8willis @simoncozens

[moved from https://github.com/harfbuzz/harfbuzz/pull/2485]

**Comment by simoncozens** [comment]
You already can, I think:

>  As of version 1.20, the preferred way is to use a subset of the basic text formatting syntax called Markdown. On older GTK-Doc versions any documentation that includes Markdown will be rendered as is. For example, list items will appear as lines starting with a dash.
> While markdown is now preferred one can mix both.

https://developer.gnome.org/gtk-doc-manual/stable/documenting_syntax.html.en

And if you can't, just write it and the magic documentation fairies will fix it up for you afterwards. :-)

**Comment by ebraminio** [comment]
> just write it and the magic documentation fairies will fix it up for you afterwards

cc: @khaledhosny 

Can you help me on https://github.com/harfbuzz/harfbuzz/wiki I've just tried to [merge](https://github.com/harfbuzz/harfbuzz/wiki/Home/_compare/f559ba810dfb33029214cc41c5e0d79d51680158...762685929bc1fb90e669ed7bb7cb311e90f011da) the [fdo homepage](https://github.com/harfbuzz/harfbuzz/wiki/Home/_compare/228149d62b5d5cf2516deafd564789e0d8b1c72e...f559ba810dfb33029214cc41c5e0d79d51680158) into it in hope to move the eventual result to README.md. We can perhaps use the same markdown file or parts of in the documentation home page https://harfbuzz.github.io/ also.

**Comment by ebraminio** [comment]
We have https://github.com/harfbuzz/harfbuzz/blob/master/docs/usermanual-install-harfbuzz.xml and https://github.com/harfbuzz/harfbuzz/blob/master/BUILD.md that are duplicated and needs to be update for meson also, oh well :/

**Comment by behdad** [comment]
I suggest we used main repo as new-developer landing page, the github.io for developer documentation, and wiki for building a knowledge base of font and text trending technology that is not HarfBuzz-specific and more of a topical Wikipedia, also ala Mozilla Developer Network.

**Comment by khaledhosny** [comment]
We can move the user manual out of the gtk-doc documentation and convert it to markdown. I’d do this anyway because I happen to dislike how the generated manual is split into many small pages with few paragraphs each, it is not that big actually and could be just a single page or one page per chapter.

**Comment by behdad** [comment]
> We can move the user manual out of the gtk-doc documentation and convert it to markdown.

You mean the parts other than API docs, right? I agree.

**Comment by khaledhosny** [comment]
> > We can move the user manual out of the gtk-doc documentation and convert it to markdown.
> 
> You mean the parts other than API docs, right? I agree.

Yes.
