### ISSUE TITLE
Upload all previous releases to github

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2507]
From: https://www.freedesktop.org/software/harfbuzz/release/
so we can forget about that page.

**Comment by alerque** [comment]
This would be pretty easy to script, but it has to be run by somebody with write access to the releases.

**Comment by behdad** [comment]
There's 67 missing (all up to 1.4.0). If easy enough to script to also pull the part out of NEWS and upload, then sure. I can run. Otherwise we'll just keep manually uploading 10 at a time and it will be done in a couple days. :))
