### ISSUE TITLE
OT/CoreText shaping difference in Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#2516]
As mentioned in https://github.com/googlefonts/noto-fonts/issues/1783:

```
simon@upo ~/Downloads/NotoNastaliqUrdu-unhinted $ hb-shape --shapers=ot NotoNastaliqUrdu-Regular.ttf 'بلے'
[YBc1=2@1566,-576+0|YehBarreeFin.2_3=2+133|LamMed.outD2HYB=1@0,400+1037|OneDotBelowYB=0@151,174+0|sp9=0+0|BehxIni.A=0@0,512+1609]
simon@upo ~/Downloads/NotoNastaliqUrdu-unhinted $ hb-shape --shapers=coretext NotoNastaliqUrdu-Regular.ttf 'بلے'
[OneDotBelowYB=2@1566,-374+0|YBc1=2@1566,-576+-1566|YehBarreeFin.2_3=2@1566,0+133|LamMed.outD2HYB=1@1566,400+1037|NullMk=0@1566,400+0|sp9=0@1566,512+0|BehxIni.A=0@1566,512+3175]
```

Dropping the issue here to track it for now. I plan to run the lookups by hand and see where the problem is.

**Comment by simoncozens** [comment]
The problem is in [lookup 42](https://github.com/googlefonts/noto-source/blob/master/src/NotoNastaliqUrdu/Noto%20Nastaliq%20Urdu%20Regular%20GSUB.txt#L7981), which is chained from [lookup 38](https://github.com/googlefonts/noto-source/blob/master/src/NotoNastaliqUrdu/Noto%20Nastaliq%20Urdu%20Regular%20GSUB.txt#L2365). When I apply it by hand, I get the following "trace":

```
38
  Class 5                  Class 29       Class 2
  This fires off two chain rules: lookup 42 pos 1, lookup 143 pos 1

  Chain 1,42
    BehxIni.A OneDotBelowYB LamMed.outD2HYB YehBarreeFin.2_3 YBc1
    Class 1   Class 10      Class 2         Class 4          Class 6
              Another two chain rules: 45 pos 2, 46 pos 2
              Chain 2, 45
              OneDotBelowYB LamMed.outD2HYB YehBarreeFin.2_3 YBc1
              Class 14      Class 2         Class 4          Class 6
                                                             Chain 4, 52
                                                             YBc1 -> YBc1 OneDotBelowYB
              Chain 2, 46
              OneDotBelowYB -> NullMk

  Chain 1,143
    BehxIni.A -> BehxIni.A sp9

  BehxIni.A sp9 NullMk LamMed.outD2HYB YehBarreeFin.2_3 YBc1 OneDotBelowYB
```

However, in Harfbuzz, *only the second rule applies*:

```
trace: start lookup 38	buffer: [BehxIni.A=0|OneDotBelowYB=0|LamMed.outD2HYB=1|YehBarreeFin.2_3=2|YBc1=2]
trace: end lookup 38	buffer: [BehxIni.A=0|sp9=0|OneDotBelowYB=0|LamMed.outD2HYB=1|YehBarreeFin.2_3=2|YBc1=2]
```

Does Harfbuzz correctly support multiple chaining contextuals at the same location?

**Comment by simoncozens** [comment]
It's not the multiple-lookups-at-once thing, but I suspect it's something to do with mark filtering / ignore marks. But I can't replicate it on a simple test case. :-/

**Comment by khaledhosny** [comment]
This seems to be a regression, checked 2.6.2 (arbitrarily chosen) and it renders right.

**Comment by jfkthame** [comment]
Oh, interesting! If you have time to bisect, that would be awesome...

**Comment by khaledhosny** [comment]
Bisected to f4cd99f28eefe695b86876736166fd119e22e04e.

**Comment by simoncozens** [comment]
Typical, it was my bug that caused it. :)

**Comment by simoncozens** [comment]
Confirmed that reverting that commit fixes it. I will add tests for both this and the original bug, and see if I can get something that makes both happy.

**Comment by behdad** [comment]
> Confirmed that reverting that commit fixes it. I

Please revert that and see if you can get Ebrahim to make a release. I'll work with you on proper fix.  I had some time today to sit and fix the regression but ended up fighting build system decisions went into master instead.  And now I have to go.

**Comment by ebraminio** [comment]
Related comments on https://github.com/harfbuzz/harfbuzz/pull/2616#issuecomment-671040278

**Comment by khaledhosny** [comment]
Should be closed now.

**Comment by behdad** [comment]
Or did we break this again when we reverted the GDEF changes in 2.7.1? I'm so confused...

**Comment by simoncozens** [comment]
This is the one broken by the GDEF changes. Should be good now. But merge my tests from #2553 and know for sure!

**Comment by behdad** [comment]
> This is the one broken by the GDEF changes. Should be good now. But merge my tests from #2553 and know for sure!

Got it. Can you merge the tests please? Just push to master. I trust you to push anything you want.

**Comment by simoncozens** [comment]
Thanks - I don't have write access yet, though.

**Comment by behdad** [comment]
> Thanks - I don't have write access yet, though.

What a mistake! Invited you as Admin.
