### ISSUE TITLE
OT/CoreText shaping difference - unattached marks in cursive pos

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#2520]
This is going to be a tricky one. When a mark with no attachments occurs in the middle of a (RightToLeft) cursively-positioned glyph sequence, how should it be positioned? CoreText puts it *at the current cursive positioning Y position*:

```
$ shape --shaper=coretext --features=-kern ~/work/nastaliq/noto-nastaliq-afdko/master_ttf/NotoNastaliqUrdu-Regular.ttf ' پ<0650>یچھے'
[YehBarreeFin.2=6+64|HehDoMed.inD2outD2YB=5@0,194+487|ThreeDotsDownBelowNS.YB=4@0,635+0|HahMed.inD2outD2D=4@0,635+211|TwoDotsBelowNS.YB=3@0,967+0|BehxMed.inT2outD2H=3@0,967+540|KasraNS=1@0,557+0|ThreeDotsDownBelowNS=1@0,926+-127|BehxIni.outT2=1@0,1078+155|space=0+131]
```

![shape](https://user-images.githubusercontent.com/106728/86277747-29ac3f00-bbcf-11ea-841e-72e920f99018.png)

Harfbuzz places it *at its design position*:

```
$ shape --shaper=ot --features=-kern ~/work/nastaliq/noto-nastaliq-afdko/master_ttf/NotoNastaliqUrdu-Regular.ttf ' پ<0650>یچھے'
[YehBarreeFin.2=6+64|HehDoMed.inD2outD2YB=5@0,195+487|ThreeDotsDownBelowNS.YB=4+0|HahMed.inD2outD2D=4@0,636+211|TwoDotsBelowNS.YB=3+0|BehxMed.inT2outD2H=3@0,968+413|KasraNS=1@127,557+0|ThreeDotsDownBelowNS=1@127,926+0|BehxIni.outT2=1@0,1078+156|space=0+132]
```
![shape](https://user-images.githubusercontent.com/106728/86277824-48aad100-bbcf-11ea-8a33-984095183324.png)

Who's right?

**Comment by simoncozens** [comment]
Assuming I've got this working properly, Uniscribe agrees with HB:

```
$ WINEDLLOVERRIDES="usp10=n" wine hb-shape.exe --features=-kern  ~/work/nastaliq/noto-nastaliq-afdko/master_ttf/NotoNastaliqUrdu-Regular.ttf -u 20,67e,650,6cc,686,6be,6d2 --shaper=uniscribe
[YehBarreeFin.2=6+64|HehDoMed.inD2outD2YB=5@0,195+487|ThreeDotsDownBelowNS.YB=4+0|HahMed.inD2outD2D=4@0,636+211|TwoDotsBelowNS.YB=3+0|BehxMed.inT2outD2H=3@0,968+413|KasraNS=1@127,557+0|ThreeDotsDownBelowNS=1@127,926+0|BehxIni.outT2=1@0,1078+156|space=0+132]
```

So either it's a CoreText bug or it's "undefined behaviour".

**Comment by simoncozens** [comment]
Simpler case at https://typedrawers.com/discussion/3696/cursive-positioning-handling-in-uniscribe-coretext-and-harfbuzz

**Comment by khaledhosny** [comment]
Since there is no such thing as current y position in OpenType, this is a clearly a Core Text bug (possibly an AAT-specific behavior leaking to OpenType implementation).
