### ISSUE TITLE
_hb_var_int_t

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2529]
https://github.com/harfbuzz/harfbuzz/blob/fb46a32ed0322d3f617dbfc7b982ff26f47d789c/src/hb-common.h#L98-L105

no use AFAICS? perhaps accidentally is put there?

**Comment by ebraminio** [comment]
oh, bindings? https://doc.servo.org/harfbuzz_sys/union._hb_var_int_t.html interesting

**Comment by behdad** [comment]
You are right that currently it's not used in our public API. Is only used to define `hb_glyph_info_t`. It was done that way such that inside HarfBuzz we can use it ergonomically.

However, that will change with what I'm working on to make the buffer message API more useful. So, please keep it, you will see how it's used when I make that change. But is a long work getting there.

**Comment by ebraminio** [comment]
No problem, I just wanted to see our current uses of union in public API that reached to this.

**Comment by behdad** [comment]
> No problem, I just wanted to see our current uses of union in public API that reached to this.

Right. Why are looking into unions? Curious. I'm doing the same for some other reason, looking at our use of unions internally to see if we can simplify things.
