### ISSUE TITLE
Testing fonts with glyf matching points?

### ISSUE THREAD

**Issue by RazrFalcon** [harfbuzz/harfbuzz#2543]
Looks like harfbuzz does support matching points, but there are no tests for it. Is there are existing fonts that use matching points to add to the tests suite or should we generate custom one?

**Comment by behdad** [comment]
What's matching points?

**Comment by RazrFalcon** [comment]
From the [glyf](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#composite-glyph-description) spec:

>Argument1 and argument2 can be either x and y offsets to be added to the glyph (the ARGS_ARE_XY_VALUES flag is set), or two point numbers (the ARGS_ARE_XY_VALUES flag is not set). In the latter case, the first point number indicates the point that is to be matched to the new glyph. The second number indicates the new glyph’s “matched” point

But turns out, you do test it indirectly in `test/api/test-ot-metrics-tt-var.c/test_advance_tt_var_anchor` + `test/api/fonts/SourceSansVariable-Roman.anchor.ttf`

Sorry for disturbing. Originally, I was looking only in shaping tests.
