### ISSUE TITLE
hb-set-fuzzer inefficiency

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2544]
It just doesn't test anything for the cast majority of fuzzer input. While fuzzer does learn the effective paths, let's help it more.

First, for instruction type, change the switch argument to: `instruction.operation % NUM_OPERATIONS`.

Then just split the available values into the two sets by looking up one integer from fuzzer and use that module size for set1 and the rest for set2.

**Comment by ebraminio** [comment]
have a look at https://github.com/harfbuzz/harfbuzz/issues/2302 also maybe we can think about some fuzzer that tests both

**Comment by behdad** [comment]
Yes. We'll get there. Just small fix for now.
