### ISSUE TITLE
[use] Kill `has_arabic_joining()`

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2559]
Make our Arabic table generator generate this in the Arabic table. Shouldn't be manual. Ouch.
```
static bool
has_arabic_joining (hb_script_t script)
{
  /* List of scripts that have data in arabic-table. */
  switch ((int) script)
  {
    /* Unicode-1.1 additions */
    case HB_SCRIPT_ARABIC:

    /* Unicode-3.0 additions */
    case HB_SCRIPT_MONGOLIAN:
    case HB_SCRIPT_SYRIAC:

    /* Unicode-5.0 additions */
    case HB_SCRIPT_NKO:
    case HB_SCRIPT_PHAGS_PA:

    /* Unicode-6.0 additions */
    case HB_SCRIPT_MANDAIC:

    /* Unicode-7.0 additions */
    case HB_SCRIPT_MANICHAEAN:
    case HB_SCRIPT_PSALTER_PAHLAVI:

    /* Unicode-9.0 additions */
    case HB_SCRIPT_ADLAM:

      return true;

    default:
      return false;
  }
}
```

David, just tentatively assigned to you. Feel free to remove yourself if you are not interested / can't do.  Thanks!

**Comment by dscorbett** [comment]
It doesn’t look like this function ever returns `true`, because all these scripts use the Arabic shaper. Is the plan to switch some of them to USE?

**Comment by khaledhosny** [comment]
That is a good question, does USE really support any Arabic-like scripts, and is it possible to make, say, an Arabic fonts use USE, may be using a special `3` tag?

**Comment by xadxura** [comment]
Microsoft's USE shapes all joining scripts except for Arabic and Syriac. I haven't had the time (and script expertise) to work out if using a 3 tag for Arabic to shape via USE is doable, but the thought is appealing. We didn't port Syriac because of the SAM support. The goal there would be to actually make stch feature generic.
