### ISSUE TITLE
Make Mongolian FVS GPOS-ignorable

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#256]
Right now it isn't.  Also, we should rename the bit in unicode-props for it and use it to mark all chars that are GPOS-ignorable but not GSUB-ignorable.

**Comment by KrasnayaPloshchad** [comment]
I have found an expert who is very experienced on Mongolian digitalization, he is also the author of Oyun Qagan Tig font, I think you can ask him for help when necessry. His contect information is [here](http://mglip.com/contect.html).

**Comment by behdad** [comment]
This has been done.
