### ISSUE TITLE
Large object passed by value detected by lgtm.com

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2563]
All are layout subset related issues https://lgtm.com/projects/g/harfbuzz/harfbuzz/alerts/?mode=list&severity=recommendation guess is worth to look, `Iterator it` should be replace with `Iterator &it` or `Iterator &&it` or something? cc: @garretrieger @qxliu76

**Comment by garretrieger** [comment]
Makes sense. We'll need to be careful that the code calling the function doesn't mind that the iterator passed by reference gets modified.

**Comment by behdad** [comment]
The design of the iterator interface was meant for them to be mostly passed by value.

Checking the link, they are all ~100bytes. That's a non-issue.

Note that a lot fo such copies will be elided by the compiler. Some are even guaranteed to be elided in C++17.

Passing by reference means that the receiving function will be draining the iterator, which will cause a surprise if the iterator is used more than once on the caller side.
