### ISSUE TITLE
hb_blob_create_from_file return the same thing when a file is not found or empty

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2567]
> Can you open an issue please? I have ideas.

https://github.com/harfbuzz/harfbuzz/commit/1339351105ce798ec5b701dfecc6d34b84273b4e#r40599376

Guess you are referring to this issue, honestly I like this uniform property of harfbuzz APIs as we even see a file system with the idea but I like to hear about what you are proposing.

**Comment by behdad** [comment]
I suggest we add a `hb_blob_create_from_file_or_fail()` variant that returns `nullptr` if file can't be opened.
