### ISSUE TITLE
hb-subset: Ligatures and GDEF/GPOS/GSUB not included in the subset font

### ISSUE THREAD

**Issue by papandreou** [harfbuzz/harfbuzz#2575]
Probably a known issue, but I was [adviced](https://github.com/harfbuzz/harfbuzzjs/issues/9#issuecomment-660138768) to open an issue here so it can be tracked :hugs:

This [Roboto-400.ttf](https://github.com/harfbuzz/harfbuzz/files/4938782/Roboto-400.zip) that I downloaded from Google Web Fonts produces an incomplete file when I subset it with `hb-subset`, resulting in ligatures not rendering. Here's a visual diff with magenta showing where the rendering is different from the original:

![waffle_stuffings_hbsubset_diff](https://user-images.githubusercontent.com/373545/87807059-17c9cd80-c858-11ea-949f-dbf0258d69d7.png)

I tried using `ttx` to compare the output of `hb-subset` to that of `pyftsubset` invoked with similar options:

```
pyftsubset --text="Waffle stuffings" --output-file=roboto-pyftsubset.ttf Roboto-400.ttf
../harfbuzz/build/util/hb-subset --output-file=roboto-hbsubset.ttf Roboto-400.ttf "Waffle stuffings"
diff -U1000 <(ttx -o - roboto-pyftsubset.ttf) <(ttx -o - roboto-hbsubset.ttf) > pyftsubset_vs_hbsubset_ttx.diff
```

The [ttx diff](https://gist.github.com/papandreou/da508079d11dda822cca67170668ce2c) shows that the 4 ligrature glyphs are missing from `<GlyphOrder>` and `<glyf>`, and that `<GDEF>`, `<GPOS>`, and `<GSUB>` blocks are missing altogether.

Tested on Ubuntu 19.10 with harfbuzz compiled from source (8e5bc535d10fb166f721520db6977cc4e949f1c5).

**Comment by ebraminio** [comment]
@garretrieger @qxliu76 can you have a look if anything unexpectd weird I thought some GPOS subsetting was implemented.

**Comment by garretrieger** [comment]
Since GSUB/GPOS subsetting is not yet fully implemented its disable by default and the two tables are just dropped. You can re-enable subsetting those tables by adding "--drop-tables-=GSUB,GPOS,GDEF" to your subset command. We currently support nearly all lookup types so that should work fine for something like Roboto.

**Comment by papandreou** [comment]
@garretrieger, thanks! Adding `--drop-tables-=GSUB,GPOS,GDEF` to the command line makes all my primitive test cases pass :relieved:

Does anyone know how to achieve the equivalent of that when using `hb-subset.wasm` via harfbuzzjs? (context: https://github.com/harfbuzz/harfbuzzjs/issues/9#issuecomment-660212107)

**Comment by garretrieger** [comment]
Similar process, use "hb_subset_input_drop_tables_set" to get the set of tables to be dropped and then remove GSUB, GPOS, and GDEF from the set. For example see the subset fuzzer code: https://github.com/harfbuzz/harfbuzz/blob/master/test/fuzzing/hb-subset-fuzzer.cc#L26

**Comment by ebraminio** [comment]
Oooh, you'll need something like [this](https://github.com/harfbuzz/harfbuzz/blob/945bcd7230277e648734b7d8a82e868d1f13257f/test/fuzzing/hb-subset-fuzzer.cc#L26-L28) then,
```
    exports.hb_set_del(export.hb_subset_input_drop_tables_set(input), HB_TAG('G', 'S', 'U', 'B'));
    exports.hb_set_del(export.hb_subset_input_drop_tables_set(input), HB_TAG('G', 'P', 'O', 'S'));
    exports.hb_set_del(export.hb_subset_input_drop_tables_set(input), HB_TAG('G', 'D', 'E', 'F'));
```
`hb_set_del` weren't in hb-subset https://github.com/harfbuzz/harfbuzzjs/commit/8c27ab152f9e66dec9b47b3b15a4694cc05535ad and this should make it work, the only left part will be a HB_TAG like thing, which you'll need something like https://github.com/harfbuzz/harfbuzz/blob/fb46a32ed0322d3f617dbfc7b982ff26f47d789c/src/hb-common.h#L112

**Comment by papandreou** [comment]
@ebraminio @garretrieger, thank you so much! [It works](https://travis-ci.org/github/Munter/subfont/jobs/709269965#L477-L481)!

I'm looking forward to feature-parity with `pyftsubset` and beyond, but this is probably good enough to get the harfbuzz support into subfont and put it behind an "experimental" switch :rocket:

(Would be nice with a new harfbuzzjs release soon so I don't have to ship the `hb-subset.wasm` I compiled myself :pray:)

**Comment by ebraminio** [comment]
> (Would be nice with a new harfbuzzjs release soon so I don't have to ship the hb-subset.wasm I compiled myself pray)

Oh, sure! https://github.com/harfbuzz/harfbuzzjs/releases/tag/0.1.3

btw, `chunkName.split('').reduce(function (a, x) { return (a << 8) + x.charCodeAt(0); }, 0);` also can be used but that may make it too cryptic so use that only if you also feel better with it :)

Guess you can close this and report other issues separately. Thanks! :)

**Comment by papandreou** [comment]
Yes, thanks a lot! :bow:
