### ISSUE TITLE
[Release tarball] Could it be added for 2.7.0? E. g. https://github.com/harfbuzz/harfbuzz/releases/download/2.7.0/harfbuzz-2.7.0.tar.xz

### ISSUE THREAD

**Issue by rubyFeedback** [harfbuzz/harfbuzz#2587]
Hello there,

Last version can be downloaded from:

https://github.com/harfbuzz/harfbuzz/releases/download/2.6.8/harfbuzz-2.6.8.tar.xz

I noticed that for 2.7.0 no such link exists. Could this be added for 2.7.0 too?

It is a minor issue; I can just download the release at
https://github.com/harfbuzz/harfbuzz/archive/2.7.0.tar.gz
and install that. But the reason I prefer the version in the URL itself
is because it simplifies downstream scripts that can more easily
parse the former. Hope I could describe my use case leading
up to this issue request. Thank you for reading this issue request -
please feel free to close this issue at any moment in time.

**Comment by ebraminio** [comment]
Hi. Please have a look at https://github.com/harfbuzz/harfbuzz/issues/2536 to see if makes sense, the point is with meson release tarballs aren't different from git checkouts and given the change I think there is a value on not making people to trust on locally generated tarballs and autotools in no longer our support build system https://github.com/harfbuzz/harfbuzz/blob/master/configure.ac#L506 since meson is in use in Arch Linux and Alpine Linux since 2.6.8 https://github.com/archlinux/svntogit-packages/blob/packages/harfbuzz/trunk/PKGBUILD , would that makes sense to you? Thanks!

**Comment by ebraminio** [comment]
https://repology.org/badge/vertical-allrepos/harfbuzz.svg?header=harfbuzz

Interesting that 2.7.0 without the release tarball has adopted this soon to this number of distributions. Some of them where using meson already but some were also ok to use GitHub generated tarballs also easily.

**Comment by vtorri** [comment]
```
-rw-r--r-- 1 vincent.torri Aucun  16M 28 juil. 05:53 2.7.0.tar.gz
-rw-r--r-- 1 vincent.torri Aucun 8,2M 11 mai   23:22 harfbuzz-2.6.6.tar.xz
-rw-r--r-- 1 vincent.torri Aucun 8,6M 22 juin  13:04 harfbuzz-2.6.8.tar.xz
```
size x2 ! i don't think it's an improvement... you don't respect the planet ! more bandwidth == more heat

**Comment by vtorri** [comment]
i'm sure that a script can automagically upload a .xz file

**Comment by ebraminio** [comment]
> size x2 ! i don't think it's an improvement... you don't respect the planet ! more bandwidth == more heat

I think that should be directed to GitHub, they can at least make https://github.com/harfbuzz/harfbuzz/archive/2.7.0.tar.xz work without putting its link in their UI. But our main recommendation weren't tar.gz but git checkouts as https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.0 Considering msys2 is shaped around Arch Linux packaging tools, I specially suggest using git checkouts just as Arch https://git.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/harfbuzz as mentioned also in https://github.com/harfbuzz/harfbuzz/wiki/Notes-on-migration-to-meson

> i'm sure that a script can automagically upload a .xz file

That won't address all of the concerns on https://github.com/harfbuzz/harfbuzz/issues/2536 as the release page doesn't have change log, the idea is just to have more eyes everywhere possible and now that meson dist pack isn't different from source checkout I think this is the best time to make that possible.

**Comment by vtorri** [comment]
> 
> 
> > size x2 ! i don't think it's an improvement... you don't respect the planet ! more bandwidth == more heat
> 
> I think that should be directed to GitHub, they can at least make https://github.com/harfbuzz/harfbuzz/archive/2.7.0.tar.xz work without putting its link in their UI. 

any link to send such question ? i would be haoy to ask :-)

**Comment by ebraminio** [comment]
> any link to send such question ? i would be happy to ask :-)

You should try a combination of https://support.github.com/contact/feedback and making twitter storming for such changes I guess :)

**Comment by ebraminio** [comment]
Many distributions have updated their version https://repology.org/badge/vertical-allrepos/harfbuzz.svg so guess we are fine here. And again, git source checkouts are best, if you can package using that just like ArchLinux, that would be just awesome. Thanks!

**Comment by ryandesign** [comment]
> size x2 ! i don't think it's an improvement... you don't respect the planet ! more bandwidth == more heat

I came here to report this too. This is terrible. You should continue to offer the xz download.


> I think that should be directed to GitHub

I will do that as well but waiting for them to take action on this possibly never shouldn't prevent you from reinstating what you had before.


> git source checkouts are best

They absolutely are not; they are the worst possible option. Surely downloading the source of all revisions ever would be larger than just downloading the version I want, and relying on a git repository is a single point of failure. Also git has configured their servers to prevent access from older operating systems. Tarballs, in contrast, can be and are mirrored across package managers' networks of mirror servers so users can get the file from a server closest to them and have fallbacks to other servers if one is not available.

**Comment by ebraminio** [comment]
> This is terrible. You should continue to offer the xz download.

Surely we can discuss things constructively.

> They absolutely are not; they are the worst possible option.

Used by Arch Linux, they shouldn't be that bad?

> Surely downloading the source of all revisions ever would be larger than just downloading the version I want

Why not using shallow cloning? As shown they they aren't as great as .xz but better than .gz

> Also git has configured their servers to prevent access from older operating systems.

I see

> and relying on a git repository is a single point of failure.

Isn't one person tarball upload dangerous enough? GitHub release page shows signature verified of me on release page https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.0 but multiple people other than me have access to change the actual release files, I just want to consider the worst case, account comprise of one the people have access to this repository release page, and like to make it as noticeable as possible.
