### ISSUE TITLE
hb_ft_font_create NULL dereference on missing size

### ISSUE THREAD

**Issue by fcartegnie** [harfbuzz/harfbuzz#2590]
According to documentation, size will be ignored if not set.

> Note: You must set the face size on ft_face before calling hb_ft_font_create() on it. Otherwise, HarfBuzz will not pick up the face size.

In reality, NULL dereference will happen due to the call to hb_ft_font_changed().
```
  hb_font_set_scale (font,
		     (int) (((uint64_t) ft_face->size->metrics.x_scale * (uint64_t) ft_face->units_per_EM + (1u<<15)) >> 16),
		     (int) (((uint64_t) ft_face->size->metrics.y_scale * (uint64_t) ft_face->units_per_EM + (1u<<15)) >> 16));
```

This can happen, for example, when using faces from the Freetype cache subsystem and not calling size functions.

**Comment by behdad** [comment]
We should just update documentation. It's a programmer error to do so.
