### ISSUE TITLE
windows: can't decompress windows archive because of symbolic link

### ISSUE THREAD

**Issue by vtorri** [harfbuzz/harfbuzz#2591]
can you remove symbolic link on README (or remove README) please ? tar fails with MSYS2. thank you

**Comment by ebraminio** [comment]
Just removing README should be ok I guess, @khaledhosny do you have any concern for doing so?

**Comment by khaledhosny** [comment]
README is required for autotools make dist.

**Comment by vtorri** [comment]
do you think that autotools will be removed soon ? managing several build systems is really difficult

another solution for README is copying README.md. As the tarball has anyway a size of 15Mb , some more bytes will be unnoticable
