### ISSUE TITLE
[meson] Ragel seems to be required

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2593]
Even though the generated files are checked in, ragel seems to be unconditionally called.

**Comment by ebraminio** [comment]
It is one time job, not much can be done about it given the solution meson team gave us on how to implement it, nothing I can think of can be done AFAIK.

**Comment by khaledhosny** [comment]
OK, should this be closed then?

**Comment by ebraminio** [comment]
I think so, thank you very much :) Of course ragel won't be called at all if isn't installed but I think we like users be able to always verify validity of ragel generated sources which our current config seems to be a good balance here but more works can be done also like #2573. Thanks!

**Comment by khaledhosny** [comment]
It gets called when not installed and the build fails, that is why I noticed this.

**Comment by khaledhosny** [comment]
Never-mind, this only happens if ragel was present when configuring but not when building.

**Comment by ebraminio** [comment]
> Never-mind, this only happens if ragel was present when configuring but not when building.

Oh, I was really concerned, thanks for letting me know
