### ISSUE TITLE
CMake Windows & static libs support

### ISSUE THREAD

**Issue by lisyarus** [harfbuzz/harfbuzz#2597]
Are there any plans on supporting Windows and/or static version of harfbuzz in CMake? Currently, `harfbuzz-config.cmake.in` just declares Windows as an unsupported platform, and unconditionally declares `SHARED` libraries.

**Comment by ebraminio** [comment]
harfbuzz config is at least somehow considered a legacy thing. Even if not removed at #2601, we may accept fixes for it but not actively maintaining it. So. Thanks :)
