### ISSUE TITLE
macOS library version change

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2598]
```
$ otool -L src/libharfbuzz.dylib
src/libharfbuzz.dylib:
	@rpath/libharfbuzz.0.dylib (compatibility version 0.0.0, current version 0.0.0)
```

Compared to 2.6.8:
```
$ otool -L /usr/local/lib/libharfbuzz.0.dylib
/usr/local/lib/libharfbuzz.0.dylib:
	/usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib (compatibility version 20601.0.0, current version 20601.8.0)
```

Is this intentional?

**Comment by lazka** [comment]
autotools vs meson maybe?

See for example: https://github.com/GNOME/atk/commit/08d8063b972e5a9542b0

**Comment by khaledhosny** [comment]
Looks like it is, and it seems to be causing linking failures for Homebrew https://github.com/Homebrew/homebrew-core/pull/58676

**Comment by ebraminio** [comment]
This is definitely concerning. How the autotools version was handling it? Just have faced with flood of messages :/ so any volunteer for this? Thanks!

**Comment by Bo98** [comment]
`darwin_versions` is the way to handle it, like `soversion`.

To match autotools, you typically set `darwin_versions` to be the equivalent of:
`[lt_current + 1, '@0@.@1@.0'.format(lt_current + 1, lt_revision)]`

**Comment by ebraminio** [comment]
Awesome, considering https://github.com/harfbuzz/harfbuzz/pull/2488 can we have something like `darwin_versions: [hb_version_int, '@0@.0.0'.format(hb_version_int)]` is it okay to have? (`hb_version_int` is `hb_version_major*10000 + hb_version_minor*100 + hb_version_micro`)

**Comment by Bo98** [comment]
Yes. If you still support autotools then you'll probably want `hb_version_int + 1` for the two build systems to match (autotool does that automatically to avoid version 0), otherwise what you have is fine.

**Comment by ebraminio** [comment]
https://github.com/harfbuzz/harfbuzz/pull/2605
