### ISSUE TITLE
Limitations with custom memory allocators

### ISSUE THREAD

**Issue by tiffany352** [harfbuzz/harfbuzz#2600]
Right now Harfbuzz allows custom allocators by defining `hb_malloc_impl`, and while this works, it has some issues. Like on some platforms linking is order dependent, and will fail if you have a cyclic dependency between your app and Harfbuzz. That requires you to put your memory allocation logic and your special Harfbuzz allocators into a separate library that's first in the list.

It also doesn't allow using a custom allocator with a binary distribution, but that's not relevant for my usecase.

I'd like if there was an alternate API where you can pass in pointers to memory allocation functions before using any HB APIs. It could be backwards compatible with the existing system, and it could be opt-in if performance is a concern.

Other libraries tend to work this way too, like with Freetype you pass in the allocator when creating the FT_Library.

I could put up a PR for this if it seems good to add.

**Comment by ebraminio** [comment]
I think this will be against original intention of the API to not have global configuration so I'm not so hopeful here :/

**Comment by ebraminio** [comment]
Highly unlikely we go with that direction as the mentioned overall API design of HarfBuzz. Sorry and thanks.
