### ISSUE TITLE
Noto Sinhala rendering of below base ra is broken.

### ISSUE THREAD

**Issue by JelleBosmaMT** [harfbuzz/harfbuzz#2624]
Working on an update of the Noto Sinhala fonts, I discovered the rendering in Chrome is broken. It was OK when we released an update to Noto Serif Sinhala in 2018 (I raised a Harfbuzz issue about something else, and this would not have gone unnoticed.) The ra-subscript is formed in the vatu feature as ligature of virama, 200D and ra. In subsequent context and ligature lookups of the abvs feature the required ligatures and context forms are created. But that no longer works. In the image Chrome on top shows the default vatu shape only. Below shows Safari the expected output. 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/12729011/89650960-79afad00-d8c3-11ea-8fd5-c90146260934.png">

I tried removing the mark-attachment type value 2 from the ligature lookup. That fixed it. But all the lookups for this mark use the mark-attachment type, because there might be other marks present, that need to be ignored. And I do not see any reason why the mark-attachment type of the lookup is working with the Mac, Microsoft and earlier Harfbuzz, if there is something wrong with it. I also went back to try the original TTFs from 2015, with the same results. 

So it seems I should report this.

This is the text from the proofing document that I was looking at:

ක්‍රි ඛ්‍රි ග්‍රි ඝ්‍රි ඞ්‍රි ඟ්‍රි ච්‍රි ඡ්‍රි ජ්‍රි ඣ්‍රි ඤ්‍රි ඥ්‍රි ඦ්‍රි ට්‍රි ඨ්‍රි ඩ්‍රි ඪ්‍රි ණ්‍රි ඬ්‍රි ත්‍රි ථ්‍රි ද්‍රි ධ්‍රි න්‍රි ඳ්‍රි ප්‍රි ඵ්‍රි බ්‍රි භ්‍රි ම්‍රි ඹ්‍රි ය්‍රි ර්‍රි ල්‍රි ව්‍රි ශ්‍රි ෂ්‍රි ස්‍රි හ්‍රි ළ්‍රි ෆ්‍රි ක්‍ව්‍රි ක්‍ෂ්‍රි ග්‍ධ්‍රි ඤ්‍ච්‍රි ට්‍ඨ්‍රි ත්‍ථ්‍රි ත්‍ව්‍රි ද්‍ධ්‍රි ද්‍ව්‍රි න්‍ථ්‍රි න්‍ද්‍රි න්‍ධ්‍රි න්‍ව්‍රි

**Comment by JelleBosmaMT** [comment]
Here is a font:
[NotoSansSinhala-Regular_OTL.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/5041836/NotoSansSinhala-Regular_OTL.ttf.zip)

**Comment by khaledhosny** [comment]
Duplicate of #2516

**Comment by JelleBosmaMT** [comment]
Almost three Months later I see no improvement in Chrome (Mac version 86.0.4240.111). I do not know how much time it takes for a Harfbuzz fix to get through the system. But I am starting to wonder if this is fixed?

**Comment by punchcutter** [comment]
Chrome takes forever to update harfbuzz, but they finally updated in Chrome Canary which means the update should be in a release version one of these days.
