### ISSUE TITLE
linker error with 2.7.0 release

### ISSUE THREAD

**Issue by rajeeshknambiar** [harfbuzz/harfbuzz#2644]
Trying to build 2.7.0 release (with `meson`) on Fedora 32 fails with following linker error (entire log is available at https://download.copr.fedorainfracloud.org/results/rajeeshknambiar/harfbuzz/fedora-32-x86_64/01612099-harfbuzz/build.log.gz):
```
/usr/bin/ld: src/libharfbuzz.so.0.20700.0.p/hb-aat-layout.cc.o:(.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
```

Quite similar to issue #880.

I can get the build succeed by `export CXXFLAGS="-fno-rtti -fPIE $CXXFLAGS"` before calling meson. See successful build log at https://download.copr.fedorainfracloud.org/results/rajeeshknambiar/harfbuzz/fedora-32-x86_64/01612104-harfbuzz/builder-live.log.gz

**Comment by khaledhosny** [comment]
Can you try again with 2.7.2, 2.7.0 might have been depending on too recent meson features.

**Comment by rajeeshknambiar** [comment]
Just tried building harfbuzz-2.7.2 with `meson` but the error remains (without `CXXFLAGS` update). Full build log is here: https://invent.kde.org/-/snippets/1181

Fedora official repositories built 2.7.2 successfully without using `meson` though: https://koji.fedoraproject.org/koji/buildinfo?buildID=1602653

**Comment by khaledhosny** [comment]
Sorry, no idea then.

**Comment by behdad** [comment]
Still relevant?!
