### ISSUE TITLE
[Khmer] rendering difference in 2.7.0

### ISSUE THREAD

**Issue by dnfield** [harfbuzz/harfbuzz#2646]
Flutter is trying to update Harfbuzz to 2.7.0 (from 2.6.2).  Before the update, this string renders as it appears in Chrome here:

`Start សេចក្ដីប្រកាសនេះ end`

But afterwards we're getting this:

![image](https://user-images.githubusercontent.com/8620741/90474937-506cf900-e0db-11ea-83d9-0b678c3e4fa3.png)

I do not speak Khmer and honestly have no idea what's going on, but I assume something is wrong here. 

/cc @mehmetf

**Comment by khaledhosny** [comment]
Duplicate of #2516

**Comment by khaledhosny** [comment]
Should be fixed in recently released 2.7.1.

**Comment by dnfield** [comment]
Great, thanks!

One thing I would have found helpful here is a CHANGELOG - is there something like that in the repo? If not I could file another issue about that.

**Comment by dnfield** [comment]
Ah, I found the NEWS file - although unfortunately I probably would not have understood the impact of the line that I think affects this anyway.  Thanks again for the quick response and update.

**Comment by dnfield** [comment]
We're still seeing this in 2.7.1.

**Comment by khaledhosny** [comment]
We will need to know the exact font file used then.

**Comment by dnfield** [comment]
Hmm. I'm still digging into this - it's possible that the person reporting this to me was still on the "bad" roll that contained 2.7.0.  I'll close this while I in vestigate some more, but it seems like it's ok to me.

**Comment by dnfield** [comment]
Ok, it's reproducing with NotoSerif Khmer (https://www.google.com/get/noto/#serif-khmr)

**Comment by dnfield** [comment]
On both 2.7.0 and 2.7.1

**Comment by dnfield** [comment]
Argh. I think I jumped the gun. The internal team reporting this bug is using a very old version of the Noto font. It's not reproducing with the latest Noto font as far as we can tell. Closing this again, since I don't really even want to try to track down a public version of the font they're using and there's nor eason for them to not just use the newest font.
