### ISSUE TITLE
Chinese Phonetic ("ZHP ") not converted to BCP 47?

### ISSUE THREAD

**Issue by RoelN** [harfbuzz/harfbuzz#2650]
I'm looking at what [gen-tag-table.py](https://github.com/harfbuzz/harfbuzz/blob/master/src/gen-tag-table.py) does, and noticed Chinese Phonetic ("Pinyin romanization") might be dropped from the LangSys-tag-to-BCP-47 conversion.

Around [this line](https://github.com/harfbuzz/harfbuzz/blob/master/src/gen-tag-table.py#L648) the language list is tweaked and amended, mostly by adding or substituting BCP 47 codes to LangSys tags. On [line 747](https://github.com/harfbuzz/harfbuzz/blob/master/src/gen-tag-table.py#L757) Chinese Phonetic ("ZHP ") is removed, but nothing is returned in place. If I understand [hb_ot_tag_to_language](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-tag.cc#L434) correctly, this means a "x-hbot-AABBCCDD" tag will be returned for "ZHP ", while I think it should be "zh-Latn" according to the [IANA](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry).

This was one of my test tags while researching for Wakamai Fondue, so I might be wrong as I only just begun grasping the extent of languages/scripts/fonts 😅

**Comment by behdad** [comment]
> It would be better if HarfBuzz could convert zh to 'ZHO ' or 'ZHP ' based on the buffer’s script, without requiring an explicit script subtag.

Which we now can because our new tag-choosing logic takes both script and language, right?

**Comment by dscorbett** [comment]
`hb_ot_tags_from_language` only takes the language. You can override the script in the language tag using `x-hbsc`, but the choice of language tag does not depend at all on the buffer’s script. I did consider adding this feature, but it would complicate gen-tag-table.py to support a single language system tag that probably no one uses, so I didn’t. That’s not to say we shouldn’t do it someday.

**Comment by RoelN** [comment]
For completeness sake, [here](https://github.com/Wakamai-Fondue/wakamai-fondue-engine/blob/master/tools/lang-tags-from-hb.py) is the script I use to convert HarfBuzz' `hb-ot-tag-table.hh` to a [JSON list](https://github.com/Wakamai-Fondue/wakamai-fondue-engine/blob/master/src/tools/ot-to-html-lang.js). I hope you don't mind me using HarfBuzz data like this!

**Comment by behdad** [comment]
> I hope you don't mind me using HarfBuzz data like this!

Of course not! Thanks for sharing.

**Comment by behdad** [comment]
> That’s not to say we shouldn’t do it someday.

Thanks.

**Comment by RoelN** [comment]
Feel free to close this issue, if you're making a new issue for the "should do it someday"-work!

**Comment by behdad** [comment]
@dscorbett anything we need to do here?

**Comment by dscorbett** [comment]
I opened #3783 for as much of this as is practical. We will probably never know the true intent behind 'ZHP ' but we do have a plausible guess. Alternatively, you could close this as not planned because a plausible guess is still just a guess, and because almost no fonts use 'ZHP '.
