### ISSUE TITLE
Meson generated CMake configs are broken....

### ISSUE THREAD

**Issue by Neumann-A** [harfbuzz/harfbuzz#2653]
- Not configuration aware
- Not working on windows

[harfbuzz-config.cmake.txt](https://github.com/harfbuzz/harfbuzz/files/5116605/harfbuzz-config.cmake.txt)

Please consider staying with cmake.... otherwise maintaining the port within vcpkg becomes notoriously difficult.

**Comment by khaledhosny** [comment]
We can’t really afford supporting three build systems going forward, especially cmake where we lack the expertise (as shown by this issue an other similar cmake issues that keep getting reported). We will keep supporting cmake and autotools a little bit longer, but this can’t go forever.

**Comment by Qix-** [comment]
Meson is not designed properly. It's going to cause massive issues for people who use harfbuzz in a nested project hierarchy, which the Meson developer is staunchly against supporting.

Please, _please_ do not migrate to Meson exclusively...

**Comment by behdad** [comment]
> Please, _please_ do not migrate to Meson exclusively... You're going to permanently break people using Harfbuzz as a submodule...

Any links?

**Comment by Qix-** [comment]
@behdad https://github.com/mesonbuild/meson/issues/422

**Comment by Neumann-A** [comment]
> Any links?

really? Simply said you are breaking `add_subdirectory(harfbuzz-submodule)` for the cmake people. Furthermore the broken config breaks find_package().

From my personal experience with vcpkg and integrating meson into vcpkg I can just tell you that meson is seriously broken in many ways.  
> Have fun, the rabbit hole goes deep. The maintainer doesn't understand build systems at any fundamental level - at least, not at the time of writing. Meson makes all of the mistakes (and more) that other failed build systems make, just with a flashier brand and more terse configuration.

That is exactly the same feeling I get from meson.

**Comment by pedronavf** [comment]
Another vote against moving to Meson. It doesn't understand well the concept of cross compiling and requires us jumping through too many hoops to automate builds for meson based libraries when building our toolchains (we build toolchains with the third pary libraries our product uses for 8 platforms), something that Autotools or CMake make seamless.

**Comment by khaledhosny** [comment]
We already moved to meson and it is currently our main build system. Autotools are still equally supported, but we don't want to support multiple build systems indefinitely. CMake never worked reliably for us and we have almost no one supporting it, and anyone using CMake is strongly adviced to switch to one of the other two, preferably meson.

Our Windows binaries are cross-compiled on Linux using meson, and it does not seem any difficult than autotools that was used before it.

**Comment by pedronavf** [comment]
We will, of course, have to take what the project moves to. I misread and I thought this was up to a vote.

Please don't mistake your succesful cross compilation for Windows as a signal of Meson's success or as lack of skill on our part. We are cross compiling for macOS and embedded devices with custom libcs and several ABIs and compiling for game consoles (PS and Xbox) and Meson based libraries have been very difficult to automate.

**Comment by Neumann-A** [comment]
> CMake never worked reliably for us 

considering you came from autotools you probably never understand how to correctly setup CMake.....

> lack of skill on our part. 

You can take a peek on how `vcpkg_configure_meson` works in vcpkg and look at ports like mesa on how it is used. 
But be aware that vcpkg internally uses a meson version which has not yet officially be released due to all the bugs meson has.....

>We already moved to meson

that is very unfortunate especially for windows users. Do you at least ship a working and correct cmake replacement target for `harfbuzz::harfbuzz` ? Otherwise you are probably breaking a lot of consumers......

**Comment by pedronavf** [comment]
> You can take a peek on how vcpkg_configure_meson works in vcpkg and look at ports like mesa on how it is used.
But be aware that vcpkg internally uses a meson version which has not yet officially be released due to all the bugs meson has.....

Thanks for the info, I'll take a look. We do use mesa already and we made it work by faking a pkgconfig directory (we are building all libraries from scratch, so there's no real pkgconfig Meson can use.) and wrapping the compiler because Meson has a hard time understanding that some compilers need ARCH_FLAGS when being invoked, even for the configure time tests. We had to do similar hacks for libdav1d, to the point that I wrote a shell script to "convert" from a regular autotools set of environment variables to an ugly Meson toolchain file.

For game console builds, which run on Windows, we wrote our own CMake file for those libraries.

**Comment by Qix-** [comment]
> CMake never worked reliably for us and we have almost no one supporting it

Uh... what? Almost every C/C++ project I see on Github has a CMakeLists.txt file now.

**Comment by behdad** [comment]
Instead of fighting with us about something we truly don't care about (cmake), maybe you can help maintain it? Help is needed in:

  https://github.com/harfbuzz/harfbuzz/pull/2874#issuecomment-782778263

because apparently all these years our cmake config didn't set up threading properly.

**Comment by NikitaFeodonit** [comment]
Please see PR #3210.

**Comment by NikitaFeodonit** [comment]
I also have a big request to continue supporting the CMake. I have a project with your library that is building for Linux, macOS, Windows, Android, iOS.

Android NDK has native support for CMake. CMake has a very good support for all these OSs. Meson has not a support for Android and iOS, as I know.

Please, do not remove CMake support. I could provide you with assistance as possible.

**Comment by kyawkyaw** [comment]
> > CMake never worked reliably for us and we have almost no one supporting it
> 
> 
> 
> Uh... what? Almost every major C/C++ project I see on Github has a CMakeLists.txt file now.

QT 6 and JUCE are using cmake and plus one for cmake.

**Comment by alerque** [comment]
@kyawkyaw Contributions to the CMake configuration file are welcome.

**Comment by khaledhosny** [comment]
If someone knows how to fix the issue here, patches are welcome, otherwise we don’t know anything about CMake.
