### ISSUE TITLE
Kerx kerning (bug?)

### ISSUE THREAD

**Issue by murasu** [harfbuzz/harfbuzz#2658]
I have a font that only has AAT tables for shaping.  The following kerning is done with kerning matrix. CoreText renders it correctly (blue) but not Harfuzz (red). I'm using hb-shape (HarfBuzz) 2.6.4

<img width="891" alt="TamilSimple-Regular_ttf" src="https://user-images.githubusercontent.com/22926756/91456239-9aad6180-e8b5-11ea-999b-9d0a0b2734e2.png">

Will be happy to send the font file over if it helps with debugging.

**Comment by behdad** [comment]
Can't help without the font for sure. Would be great if @jfkthame can look into this. I can't anytime soon.

**Comment by murasu** [comment]
@jfkthame can I send the font over by email?

**Comment by jfkthame** [comment]
@murasu Any update on this? We really need to see the font concerned if we're going to investigate...

**Comment by murasu** [comment]
CoreText is also causing the same problem. So, I'm trying to see if the kerx is done correctly. The earlier (correct) rendering was from the GPOS table. Will send the font over once I am able to ascertain that the kerx compilation is correct. I'll keep this thread posted.

**Comment by murasu** [comment]
I've confirmed that there is a bug in the tool that's used to add the kerx table. Once this is fixed, or a workaround is found, I'll retest this with HB. Thank you!
