### ISSUE TITLE
`hb_ot_layout_get_baseline` should not need `language_tag`

### ISSUE THREAD

**Issue by kojiishi** [harfbuzz/harfbuzz#2662]
Not 100% sure but wanted to hear what experts think. The current signature:
```
hb_bool_t
hb_ot_layout_get_baseline (hb_font_t                   *font,
			   hb_ot_layout_baseline_tag_t  baseline_tag,
			   hb_direction_t               direction,
			   hb_tag_t                     script_tag,
			   hb_tag_t                     language_tag,
			   hb_position_t               *coord        /* OUT.  May be NULL. */)
```
includes both `script_tag` and `language_tag`.

The [BASE table organization](https://docs.microsoft.com/en-us/typography/opentype/spec/base#table-organization) indicates that only script is needed to find values. The OpenType [BaseScript Table](https://docs.microsoft.com/en-us/typography/opentype/spec/base#basescript-table-1) can contain multiple min/max tables for [BaseLangSysRecord](https://docs.microsoft.com/en-us/typography/opentype/spec/base#baselangsysrecord), but there is only one base value.

So I believe `language_tag` is necessary for getting min/max extent values but not for getting base values.

I traced the code. `language_tag` is passed to ``BASE::get_baseline` and then to ``Axis::get_baseline`, but is not used there.

@ebraminio thoughts?

**Comment by behdad** [comment]
No harm leaving it there even if not currently used. Conceptually it makes complete sense to have different baselines for some different languages using same script.

**Comment by behdad** [comment]
Can use documentation update.
