### ISSUE TITLE
What is "Old MIT" license ?

### ISSUE THREAD

**Issue by mozoko** [harfbuzz/harfbuzz#2664]
Hi.
COPYING says "HarfBuzz is licensed under the so-called "Old MIT" license".
So, what is Old MIT license?
Is it OK to treat as MIT license?

**Comment by khaledhosny** [comment]
There is no single “MIT license”, and the file contains the full license text that you can compare to any other license.

**Comment by khaledhosny** [comment]
https://en.m.wikipedia.org/wiki/MIT_License
https://fedoraproject.org/wiki/Licensing:MIT
