### ISSUE TITLE
Question about API: `hb_font_set_ppem ` and `hb_font_set_scale`

### ISSUE THREAD

**Issue by kaiwk** [harfbuzz/harfbuzz#2670]
Hi,

I have read the [doc](https://harfbuzz.github.io/fonts-and-faces.html#fonts-and-faces-objects), but there still some points I can't fully understand.

1. The pixel in `ppem` stand for 'device pixel' or pixel which is 1/96 inch [in graphic and web design](https://en.wikipedia.org/wiki/Pixel)?

> Pixels, abbreviated as "px", are also a unit of measurement commonly used in graphic and web design, equivalent to roughly 1⁄96 inch (0.26 mm).

2. For `hb_font_set_scale`:

>  HarfBuzz lets you specify the degree subpixel precision you want through a scaling factor. 

I don't really understand what's the 'the degree subpixel precision', is there any example or detailed explanation?

3. what's the `hb_position_t` stand for? pixel or other unit? 

Hope someone could clarify it, thank you!

**Comment by behdad** [comment]
> what's the `hb_position_t` stand for? pixel or other unit?

is whatever you choose for it to be. And `set_scale` API reflects that.

For example, if you choose that the value 1234 will reflect 1 EM, then you pass 1234 to `set_scale`, and then a value of 1 EM will show up as 1234 in `hb_position_t`.

Hope that helps.

**Comment by behdad** [comment]
> 1. The pixel in `ppem` stand for 'device pixel' or pixel which is 1/96 inch [in graphic and web design](https://en.wikipedia.org/wiki/Pixel)?

Device pixel. And you can safely ignore that API completely.
