### ISSUE TITLE
Having issue in harfbuzz installation

### ISSUE THREAD

**Issue by sssikarwar** [harfbuzz/harfbuzz#2673]
In continuation of the issue [#4904](https://github.com/python-pillow/Pillow/issues/4904), I am having an issue installing harfbuzz while following the steps mentioned [here](https://harfbuzz.github.io/building.html#building.macos).

On the step: (2)(a) If you are installing HarfBuzz from a downloaded tarball release, extract the tarball and open a Terminal in the extracted source-code directory. Run:  `meson build`

I am getting the following error:
```
Build-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig, framework and cmake)
src/meson.build:649:4: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig, framework and cmake
```

But when I run `brew install gobject-introspection`, it says:
```
Warning: gobject-introspection 1.64.1_2 is already installed and up-to-date
To reinstall 1.64.1_2, run `brew reinstall gobject-introspection`
```

**Comment by khaledhosny** [comment]
You might be missing `pkg-config`.

**Comment by khaledhosny** [comment]
But why do you even need to build HarfBuizz from source, you can install the latest version with `brew install harfbuzz`.

**Comment by sssikarwar** [comment]
```
Warning: pkg-config 0.29.2_3 is already installed and up-to-date
To reinstall 0.29.2_3, run `brew reinstall pkg-config`
```

`brew install harfbuzz` says:
```
Warning: harfbuzz 2.7.2 is already installed and up-to-date
To reinstall 2.7.2, run `brew reinstall harfbuzz`
```

@khaledhosny as you are aware of my following error from issue #4904:
```
-- Checking for module 'harfbuzz>=0.9.20'
--   No package 'harfbuzz' found
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  CMakeLists.txt:147 (pkg_check_modules)
-- Configuring incomplete, errors occurred!
```

And I didn't find the solution so I am just deep diving for the reason behind getting this error which dragged me to build HarfBuzz from the source.

If `brew install harfbuzz` is enough to install HarfBuzz and if it's really installed in my system, then can you please help me to find out the reason for the above error?

**Comment by khaledhosny** [comment]
The above error is not coming from HarfBuzz, so I can’t really provide much help.
