### ISSUE TITLE
hb-view doesn't render anything with this font

### ISSUE THREAD

**Issue by olivierberten** [harfbuzz/harfbuzz#2675]
it seems to work anywhere else (hb-shape included) but hb-view renders an empty image
[SN Kh SONY Moul.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/5196735/SN.Kh.SONY.Moul.ttf.zip)
[source](https://akbalthom.blogspot.com/2020/04/khim-sony.html)

**Comment by khaledhosny** [comment]
The font has `COLR` table that seems to be breaking something, if I drop that table things get fixed.

I though the table is bogus, but it seems that hb-view will not show anything for glyphs not covered by `COLR`, not just in this font which makes no sense. I wounder where is this breaking, pango-view seems fine, so I guess it is not Cairo or FreeType.

**Comment by behdad** [comment]
Is definitely Cairo or FreeType issue since hb-view by  itself doesn't do any magic. It might be that `FT_HAS_COLOR` is broken for this font.

What happens if you pass `--background=01`?

**Comment by behdad** [comment]
When reporting bugs please also specify sample text to reproduce the bug. Thanks.

**Comment by behdad** [comment]
> What happens if you pass `--background=01`?

Doesn't do anything.

I can reproduce. Will look into later.

**Comment by khaledhosny** [comment]
The issue happens with other fonts too, for glyphs not covered by `COLRz` table (e.g. a م in Amiri Quran Colored).

**Comment by behdad** [comment]
So, the color glyphs work?

**Comment by khaledhosny** [comment]
Yes.

**Comment by simoncozens** [comment]
Removing the `0 &&` from this line https://github.com/harfbuzz/harfbuzz/blob/ea4476d7389b8b5d30f1d969787c752856c32088/util/view-cairo.cc#L123

makes it display. That might not be the fix because I presume it's if'd out for a reason. But it should be a good place to start looking.

**Comment by behdad** [comment]
> makes it display. That might not be the fix because I presume it's if'd out for a reason. But it should be a good place to start looking.

Basically what that suggests is that it's a bug in cairo's color-glyph processing. Which is what I knew anyway since we don't do any of that.

**Comment by matthiasclasen** [comment]
Here is what I see with that font:

![Screenshot from 2021-07-31 08-37-08](https://user-images.githubusercontent.com/4834845/127740084-c9567153-d8f8-4d73-ac15-1a496d966a53.png)

It is not that nothing is there, it is that you get white-on-white text.

**Comment by matthiasclasen** [comment]
Fixed here: https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/224

**Comment by behdad** [comment]
Thanks Matthias.

**Comment by behdad** [comment]
Related https://gitlab.freedesktop.org/cairo/cairo/-/issues/533
