### ISSUE TITLE
CI job that tests build using MSVC compiler broken

### ISSUE THREAD

**Issue by alerque** [harfbuzz/harfbuzz#2689]
See discussion in #2688.

**Comment by simoncozens** [comment]
As a reminder, the proximate cause of this is the Haskell-style C++ template magic in `hb-algs.hh` as described in #2293.  Behdad thinks this is exposing a MSVC compiler bug; I don't have anything like the C++ experience to know whether that's true, but I do have a VS2019 virtual machine I can test things on.
