### ISSUE TITLE
Question: callbacks for getting layouts?

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#2690]
This may not be an intelligent question. But...

We have font functions where a user can specify their own way to determine font metrics (`hb_font_funcs_set_glyph_h_advance_func` etc.). Is there also a way for a Harfbuzz user to specify how to get layout rules?

The reason I want this is to be able to render UFO fonts directly (using my own data structure to represent layout features), without having to compile down to OTF.

**Comment by khaledhosny** [comment]
> Is there also a way for a Harfbuzz user to specify how to get layout rules?

No, there isn’t. You will need to compile the layout tables and return the binary data to HarfBuzz. I don’t think what you are requesting is feasible.

**Comment by simoncozens** [comment]
Ah, that's a shame. Well, I guess I really *do* need my own OTL compiler then.

**Comment by behdad** [comment]
> The reason I want this is to be able to render UFO fonts directly (using my own data structure to represent layout features), without having to compile down to OTF.

Not down to OTF. Just to GDEF/GSUB/GPOS level and use the `hb_face_create_for_tables()` API.

Glyphs also asked for this. The matter is: HarfBuzz has *no* internal representation of OTL. It consumes the binary directly.

We can add a "print-preview" mode to feaLib to produce tables as fast and unoptimized as it can, and use that...
