### ISSUE TITLE
Question: ccmp and Arabic joining

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#2691]
Obviously this works, but I don't understand how. 

* `arabic_joining` (which, if I understand it correctly, happens *before* ccmp is processed) operates in codepoint-land and sets the joining types for each glyph
* Then the mapping to glyph-land happens
* Then `ccmp` is processed, which substitutes glyphs - possibly introducing new glyphs.
* Then the Arabic features are done based on the masks set by `arabic_joining`.

Where is joining information / masks computed for glyphs substituted or introduced by `ccmp`?

**Comment by behdad** [comment]
In buffer's methods like `replace_glyphs`. I think the masks for the first glyph survive.

**Comment by khaledhosny** [comment]
When glyph is decomposed by `ccmp` into two base glyphs, do joining features apply to the two glyphs or only one of them? (I only ever use `ccmp` to split into base and mark+).

**Comment by simoncozens** [comment]
> When glyph is decomposed by ccmp into two base glyphs, do joining features apply to the two glyphs or only one of them?

So it looks like `replace_glyphs` just copies the first glyph's mask. If you have:

```
feature ccmp {
            sub BEu1 by BEu1 JIMu1; # CRAZYFONT
```

Then BE LAM BE shapes to `JIMf1|BEf1|LAMm1|JIMi1|BEi1`

**Comment by behdad** [comment]
> When glyph is decomposed by `ccmp` into two base glyphs, do joining features apply to the two glyphs or only one of them?

To all. They're just copied into all. So, eg. you get multiple glyphs all getting `fina` applied.

**Comment by khaledhosny** [comment]
> > When glyph is decomposed by `ccmp` into two base glyphs, do joining features apply to the two glyphs or only one of them?
> 
> To all. They're just copied into all. So, eg. you get multiple glyphs all getting `fina` applied.

Thanks, I got that from Simon’s comment as well.
