### ISSUE TITLE
Please document how to actually build harfbuzz on windows

### ISSUE THREAD

**Issue by kg** [harfbuzz/harfbuzz#2693]
The current documentation says roughly "just use meson", so I did:

* Install meson
* Attempt to run meson to build harfbuzz
* It doesn't work
* Read random documentation on the internet, realize that you need to run meson with the visual studio environment vars set
* Run ```meson.exe build --wrap-mode=default``` and observe lots of stuff happening, with celebratory output at the end
* Where is harfbuzz?
* Nowhere, the answer is nowhere. 
* Read more random documentation and realize you need to run ```meson.exe builddir```
* Okay, now what
* Move into the builddir and run ```compile``` there, I guess? The builddir is in the output from ```build``` and it's named... ```builddir```.
* ```cd builddir; meson.exe compile```
* Awesome, I have a dll! In the ```src``` directory, for some reason.
* Examine the DLL in Dependencies to see that it requires the Debug visual studio runtime libraries, which you are not allowed to distribute to end users
* Read more documentation
* ```meson.exe configure . -Db_vscrt=mt```? Well, that worked, I think?
* No, it didn't, the output dll still needs the debug runtime library. Maybe I need to run ```meson.exe build``` again to apply the changes from ```configure```?
* Nope. Still needs the debug runtime library. Is this a debug build and the settings only apply to a release build? How do I perform a release build?

Just knowing how harfbuzz developers typically compile harfbuzz would be great. At this point I'm probably going to dig around in Chromium's build scripts until I figure out what magic incantations they use since I know they don't rely on the VC++ runtime libraries, but that probably won't help since I think they use clang now.

**Comment by behdad** [comment]
What are you trying to build?

As far as I know most of us don't build on windows locally.

**Comment by kg** [comment]
I need a harfbuzz.dll to pair with my freetype2.dll that I built so I can do text shaping in a windows app, I'll also be building linux binaries later for linux ports but the documentation for linux builds seems fine.

**Comment by kg** [comment]
From experimenting some more, I *think* the correct incantation is this and only this (running additional commands seems to mess with meson's state in a way I don't understand):
```
"C:\Program Files\Meson\meson.exe" build --wrap-mode=default --buildtype release -Db_vscrt=mt
cd build
"C:\Program Files\Meson\meson.exe" compile
```
I have a harfbuzz.dll now that only imports from freetype-6.dll and kernel32.dll. My previous attempts had actually been disabling freetype, apparently the 'configure' and 'builddir' commands are incompatible with 'build'.

**Comment by khaledhosny** [comment]
These are all basic meson questions, and I don’t see why you think it is HarfBuzz job to provide a meson tutorial for Windows. If you are not familiar with meson, you should consult meson documentation. There is nothing specific to HarfBuzz in your question.

**Comment by khaledhosny** [comment]
[`.github/workflows/msvc-ci.yml`](https://github.com/harfbuzz/harfbuzz/blob/master/.github/workflows/msvc-ci.yml) and [`.github/workflows/msys2-ci.yml`](https://github.com/harfbuzz/harfbuzz/blob/master/.github/workflows/msys2-ci.yml) have the CI build steps for Windows using MSVC and msys2, repectively.

**Comment by kg** [comment]
That's perfect, thanks khaled.
