### ISSUE TITLE
hb-subset Unable to open output file

### ISSUE THREAD

**Issue by typoman** [harfbuzz/harfbuzz#2711]
I've installed harfbuzz using homebrew on OSX Catalina and it seems that hb-subset cannot write the font into the disk. I even used sudo but got the same error: 
```
> hb-subset /path/test.otf text
Unable to open output file
```
Does anyone know why this is happening?
Thanks

**Comment by khaledhosny** [comment]
You need to specify output file path using `-o` option.

**Comment by typoman** [comment]
I see! `-o` option solved it.  I got the command from the documentation. I guess that was old. Thank you very much Khaled!
