### ISSUE TITLE
Interop with msdfgen Arabic glyph indices mismatch

### ISSUE THREAD

**Issue by kamokiz** [harfbuzz/harfbuzz#2712]
I'm getting proper rendering in English but HarfBuzz breaks down in Arabic even though I included all unicode characters required, only things rendering is a select few number of accents, although the positioning of the quads and everything is fine. I found out this has to do with the way the glyph indices are calculated, I'm using FreeType to get the unicode characters glyph index so I can index the packed quads map part of the font atlas, though it seems HarfBuzz has a different way to calculate this, I tried with `hb_font_get_nominal_glyph()` and use that to index but I am getting a similar issue where it's referring to the wrong glyphs. Is there any way that I can bake the Arabic huruf in an atlas and then refer to them later in rendering?

![image](https://user-images.githubusercontent.com/70410392/95675618-9f3c8980-0b86-11eb-9b34-6d32a2960afd.png)

I'm trying to render the following:
ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ

And this is the result:
![image](https://user-images.githubusercontent.com/70410392/95676434-20e2e600-0b8c-11eb-9bde-3dfd9901e689.png)
![image](https://user-images.githubusercontent.com/70410392/95745435-10516f00-0c63-11eb-858f-c5f4e15a5c4d.png)

With this mesh output:
![image](https://user-images.githubusercontent.com/70410392/95671332-a605d500-0b63-11eb-8734-8719de2d57d3.png)

Here I have the atlas map, it has the characters which are meant to be transitional or joint:
![image](https://user-images.githubusercontent.com/70410392/95671359-20365980-0b64-11eb-8216-2747d1d09f18.png)

If you have any ideas then please tell me, cause I'm out of them...

**Comment by khaledhosny** [comment]
We need to see the code where you are using HarfBuzz. HarfBuzz gives you glyph indices right away, no further mapping is needed.

**Comment by behdad** [comment]
You can't just pack the nominal glyphs. It doesn't work that way.

You can possibly use `hb_ot_layout_lookups_substitute_closure` combined with `hb_ot_shape_plan_collect_lookups` to collect indices of all glyphs you need to pack for a given starting set of glyphs (which you are already producing).

**Comment by kamokiz** [comment]
> You can possibly use `hb_ot_layout_lookups_substitute_closure` combined with `hb_ot_shape_plan_collect_lookups` to collect indices of all glyphs you need to pack for a given starting set of glyphs (which you are already producing).

I'll try that.
