### ISSUE TITLE
Unit conversion from glyph position advance to `point` or `mm`

### ISSUE THREAD

**Issue by drahnr** [harfbuzz/harfbuzz#2714]
I am currently attempting to obtain the length of a single phrase string in order to calculate the pdf anchor position in millimetres or point units.

Currently I use the accumulated `hg_position->advance_x`  for this purpose.
https://harfbuzz.github.io/harfbuzz-hb-buffer.html#hb-buffer-get-glyph-positions

This works sufficiently with a magic const, since I did not find in what unit (assuming `em`) means, but this breaks down for different font sizes.
It would be great if you could explicitly state the units in the documentation of the types that are denoted `offset` and `advance` to simplify using `harfbuzz` and possibly providing references to conversion functions for common text setting units (pixel, mm, pt come to mind).

**Comment by drahnr** [comment]
It seems this question was answered before on SO

https://stackoverflow.com/questions/50292283/units-used-by-hb-position-t-in-harfbuzz

https://github.com/harfbuzz/harfbuzz-tutorial/blob/master/hello-harfbuzz-freetype.c#L63-L66
https://github.com/harfbuzz/harfbuzz-tutorial/blob/master/hello-harfbuzz-freetype.c#L36

**Comment by khaledhosny** [comment]
The positions are in font units scaled by the font scale (set with `hb_font_set_scale()`).

**Comment by behdad** [comment]
> The positions are in font units scaled by the font scale (set with `hb_font_set_scale()`).

That's not very accurate. More accurate would be: they are in client-custom units, whereas the size of 1em in such client-custom coordinate space is what is specified by `hb_font_set_scale()`.

The use of 64 is FreeType- and hb-ft-specific and has no inherent relevance to `hb_position_t`.

We need to document this, with a bunch of suggestions for how to choose scale in one's application.

**Comment by blumens** [comment]
Other quantities that need explanations are `upem`, `ppem`, and `ptem`, in particular, their relation to each other. For instance, if I have a font using the standard 1000 units per em and I want to set it in a size of 10pt using units of 1/64 of a point, do I use

```
hb_font_set_scale(font, 10*64, 10*64);
hb_font_set_ptem(font, 64.0); // or should this also be 10.0*64.0
hb_font_set_ppem(font, 10*64, 10*64);
```

**Comment by behdad** [comment]
> hb_font_set_ptem(font, 64.0); // or should this also be 10.0*64.0

This should be just 10.0.

> hb_font_set_ppem(font, 10*64, 10*64);

Also just 10,10.

**Comment by behdad** [comment]
> > hb_font_set_ppem(font, 10_64, 10_64);
> 
> Also just 10,10.

Err. This one depends on your DPI. Assuming a 72dpi display it would be 10. Otherwise, convert 10pt to pixels and use that.

**Comment by behdad** [comment]
> > > hb_font_set_ppem(font, 10_64, 10_64);
> > 
> > 
> > Also just 10,10.
> 
> Err. This one depends on your DPI. Assuming a 72dpi display it would be 10. Otherwise, convert 10pt to pixels and use that.

ppem is mostly unused. Don't worry about setting it at all.

**Comment by behdad** [comment]
I added some docs to `hb_font_set_scale`. https://github.com/harfbuzz/harfbuzz/blob/fecce62a45d996fbca11cea6c34bdbadec283ba4/src/hb-font.cc#L2278-L2301
