### ISSUE TITLE
[util] Handle default output file in `output_options_t`

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2717]
Following up from https://github.com/harfbuzz/harfbuzz/issues/2711

I feel like `output_options_t` constructor should take a `const char *default_file = nullptr`. Then `hb-shape` / `hb-view` can pass `"stdout"` to it.

`hb-subset` will pass `nullptr` to it, and that will make `output_options_t` err if an output-file is not specified. Also adjusts the output of `--help-output`.

That said. There's a bigger issue: if the output file name is required by `hb-subset`, then it should have been part of the main signature, which it currently isn't:
```
Usage:
  hb-subset [OPTION…] [FONT-FILE] [TEXT]
```

Part of me like to go back to what `pyftsubset` used to do, which was to default to `subset.otf` as output file name or something similar. Alternatively we can default to `/dev/null`. Or to `/dev/stdout` if stdout is not to a terminal.

Anyway. Just filing because this is messy and confusing and should not have got to this mess in the first place.

**Comment by alerque** [comment]
As someone who lives in a terminal, my default expectation is that if I don't specify an output filename the output will be on STDOUT. Defaulting to a stock filename is not ideal and and a source of mistakes & frustration. If STDOUT is not writable for some reason or the output format isn't terminal safe, an error message about requiring an output argument is always much appreciated.

**Comment by khaledhosny** [comment]
Outputting binary data to STDOUT by default is bad UX IMHO and often messes with the terminal display.

**Comment by behdad** [comment]
> my default expectation is that if I don't specify an output filename the output will be on STDOUT

But that wouldn't be useful at all for binary output when stdout is terminal. I share all your expectations. Trying to do better.
