### ISSUE TITLE
Trying to build harfBuzz from downloded source i have this error with meson

### ISSUE THREAD

**Issue by saimmm** [harfbuzz/harfbuzz#2718]
meson.build:208:36: ERROR: lexer
    ['FT_Get_Var_Blend_Coordinates', {'deps': freetype_dep}],

**Comment by alerque** [comment]
I think you're going to have to provide a lot more context if anybody is going to be able to address this. What platform are you on, what version of Meson (and other relevant tooling and libraries, i.e. freetype) are you building with & againstg, what actual steps did you take and what is the full output? There isn't enough information in this message to identify what your problem might be.

**Comment by youmee** [comment]
Same s**t. Doing all by instruction: https://harfbuzz.github.io/building.html
apt installed all dependencies.

Debian 9.
