### ISSUE TITLE
Signedness of int in hb-ot-shape-fallback

### ISSUE THREAD

**Issue by laurmaedje** [harfbuzz/harfbuzz#2719]
In [hb-ot-shape-fallback#L304] the `correction` is stored as an unsigned integer and then only used with other signed arithmetic. Should this be just `int`? Or ist the reason that `correction` is always positive because `pos.y_offset` is always negative due to the previous if-condition and the fact that `y_gap` is always positive (at least if `units_per_em` can't be negative?). If so, I am wondering why the if-condition isn't just `pos.y_offset < 0`.

All of this is probably not really important in practice, but I just wanted to point it out.

[hb-ot-shape-fallback#L304]: https://github.com/harfbuzz/harfbuzz/blob/77e704d1dbfbdb6c54127112814b24358ec52eea/src/hb-ot-shape-fallback.cc#L304

**Comment by behdad** [comment]
That's just wrong. Should be int I think.

y_gap can be negative of y_scale is negative, which is used in a Y-grows-down coordinate system.
