### ISSUE TITLE
Egyptian Hieroglyphic text isn't shaping

### ISSUE THREAD

**Issue by xadxura** [harfbuzz/harfbuzz#2721]
Egyptian Hieroglyphic text has not been shaping correctly in HarfBuzz since June (no repro in Firefox 69.0). I thought this was related to #2553, but this may be a different issue since the the problem is still impacting current versions of Chrome and Firefox. 

The current, incorrect, rendering in Chrome (86.0.4240.75):
![image](https://user-images.githubusercontent.com/8731579/96311609-b6cca580-0fbe-11eb-9c71-7ca03975349c.png)

The previous, correct, rendering in Firefox (69.0)
![image](https://user-images.githubusercontent.com/8731579/96311684-e2e82680-0fbe-11eb-8bfd-3a7d52c21b28.png)

**Comment by punchcutter** [comment]
Does it work in Chrome Canary? 86.0.4240.75 is still horribly broken because it's still using the broken harfbuzz. I tried Canary for similar issues and it seems to be using the fixed harfbuzz now.

**Comment by alerque** [comment]
Can you include the codepoints you are trying to shape? My hieroglyph keyboard entries skills are hunt-and-peck at best ;-)

**Comment by xadxura** [comment]
13000 13430 13250 (𓀀𓐰𓉐)

**Comment by xadxura** [comment]
Thank you, @punchcutter. The canary version works. So #2553 is the right fix. 
#2558 is now the only open issue with shaping Egyptian in HarfBuzz.
