### ISSUE TITLE
Where is hb_font_get_font_funcs?

### ISSUE THREAD

**Issue by jfkthame** [harfbuzz/harfbuzz#2731]
According to https://harfbuzz.github.io/fonts-and-faces-custom-functions.html, I should be able to use `hb_font_get_font_funcs()` to get the current font functions for a font. But it doesn't appear to exist.

More generally, I'm interested in setting up an `hb_font_funcs_t` that uses the built-in OT functions, *except* that I want to replace one of the functions with my own implementation. I can't see how to do that using public API.

@behdad, is there a supported way to do this that I'm overlooking?

**Comment by khaledhosny** [comment]
I think you need to create a font, set ot functions on it (they are the default now), then create a subfont and override only the function you need and the subfont will fallback to the parent functions for the rest.

**Comment by jfkthame** [comment]
OK, I wondered if that was the approach I'd need to take. So actually getting the existing functions simply isn't supported, and the doc mention of `hb_font_get_font_funcs()` is obsolete. Thanks, will try it that way.

**Comment by khaledhosny** [comment]
This manual page needs to be updated as well, I don’t think HarfBuzz ever had an `hb_font_get_font_funcs()`.

**Comment by behdad** [comment]
In early designs I had `hb_font_steal_font_funcs()`; but even that never happened. There are two problems with such functionality:
1. The lifecycle of returned data needs to be managed by client, and might deviate from the assumptions of the creator of such font-funcs data,
2. The stolen / old font-funcs make assumptions that *they* are the font funcs on the font. When that assumption is violated anything can happen.

As a result, the font subclassing mechanism was added the way it is currently.

**Comment by khaledhosny** [comment]
We are keeping this open to fix the documentation since it is talking about non-existent API.
