### ISSUE TITLE
What is `hb_script_t`?

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#2732]
What does an `hb_script_t` represent? It uses ISO 15924 but it doesn’t exactly _represent_ an ISO 15924 code, or else `hb_script_from_iso15924_tag` wouldn’t do any conversions. It doesn’t represent an OpenType script tag’s ISO 15924 code, or else there wouldn’t be separate `HB_SCRIPT_HIRAGANA` and `HB_SCRIPT_KATAKANA`. The documentation describes `hb_script_t` as “an enumeration of Unicode scripts”, but then why are some ISO 15924 codes for script variants mapped (e.g. Cyrs and Syre) and some aren’t (e.g. Hans and Hant)?

I was about to make a PR to add more variants to `hb_script_from_iso15924_tag`, but I realized I don’t know what the intended behavior is.

**Comment by behdad** [comment]
`hb_script_t` represents Unicode scripts. Add more mappings as you see fit.

**Comment by dscorbett** [comment]
Thanks; I have add some mappings in #2747.
