### ISSUE TITLE
meson build error in MSYS2/MinGW: generator didn't stop

### ISSUE THREAD

**Issue by LigH-de** [harfbuzz/harfbuzz#2738]
[logs.zip](https://0x0.st/iduD.zip) collected by media-autobuild suite (contains meson log), ref. [MABS issue #1841](https://github.com/m-ab-s/media-autobuild_suite/issues/1841)

May this be related to recent autoconf-pkg-config changes?

**Comment by LigH-de** [comment]
Building passed on a Win10 PC but failed on a Win7 PC, despite re-installing the MSYS2 environment.

**Comment by khaledhosny** [comment]
> May this be related to recent autoconf-pkg-config changes?

This change didn’t touch meson build (we also were requiring newer pkg-config for a long time, we just didn’t declare the actual minimal version we want).

I don’t know what to do with the logs you attached, there are so many files.

**Comment by LigH-de** [comment]
The main log for this issue should be build/harfbuzz-git/build-32bit/ab-suite.meson.log

**Comment by khaledhosny** [comment]
OK, that is some obscure Python error coming from deep inside meson, I don’t even have the slightest idea how to debug this. But I suggest first trying to build HarfBuzz standalone, and see if it fails there.

**Comment by LigH-de** [comment]
Then I will hope for ideas from the MABS team and close this issue here when there are news.

**Comment by 1480c1** [comment]
@LigH-de, on the machine that it fails on, can you try getting a completely separate instance of msys2 installed and run
```bash
pacman -Syu --noconfirm
pacman -Su --noconfirm
pacman -S --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-ninja mingw-w64-x86_64-meson mingw-w64-x86_64-pkg-config git
git clone https://github.com/harfbuzz/harfbuzz.git
meson -D{glib,gobject,cairo,fontconfig,icu,tests,introspection,docs,benchmark}=disabled build harfbuzz
meson compile -C build
````

and see how far you get?

btw, my meson reported:
```none
WARNING: Project specifies a minimum meson_version '>= 0.47.0' but uses features which were added in newer versions:
 * 0.50.0: {'install arg in configure_file'}
```

**Comment by LigH-de** [comment]
Apparently it is related to [cleaning temporary directories](https://github.com/mesonbuild/meson/pull/7955) which may be delayed by Explorer hooks watching their content (like TortoiseGit's icon overlay service) ... so I assume it will be fixed when MSYS2 releases an updated build.

**Comment by LigH-de** [comment]
MSYS2 updated meson to 0.56; harfbuzz builds.

**Comment by LigH-de** [comment]
BTW: MSYS2 updated to meson 0.57.1, and there is a different issue with temporary directories now. The unsafe clearing may not succeed in time (possibly due to file monitoring processes keeping a previous output.exe a little while before deleting it), followed by many failing configuration builds where the access to output.exe gets denied. When the meson script aborts, the temporary directory is empty afterwards.

**Comment by guy-rouillier** [comment]
I'm encountering this same issue trying to build a different package on msys2.  Did a system update to msys2-runtime 3.1.7-8, same result. meson 0.57.1

**Comment by behdad** [comment]
Anything on our side to do here?

**Comment by LigH-de** [comment]
Sorry, forgot. It works in MABS since March 2021. Thanks to everyone who joined the efforts.
