### ISSUE TITLE
Crash on android device

### ISSUE THREAD

**Issue by whitespeed** [harfbuzz/harfbuzz#2739]
stack:

```
hb_font_t::get_nominal_glyphs(unsigned int, unsigned int const*, unsigned int, unsigned int*, unsigned int)
deps/harfbuzz-icu-freetype/harfbuzz/src/hb-font.hh:233

hb_ot_substitute_default(hb_ot_shape_context_t const*)
deps/harfbuzz-icu-freetype/harfbuzz/src/hb-ot-shape.cc:854

hb_shape_plan_execute
deps/harfbuzz-icu-freetype/harfbuzz/src/hb-shaper-list.hh:42

hb_shape_full
deps/harfbuzz-icu-freetype/harfbuzz/src/hb-shape.cc:141

hb_shape
deps/harfbuzz-icu-freetype/harfbuzz/src/hb-shape.cc:171
```

**Comment by alerque** [comment]
Perhaps somebody more familiar with Android could guess better than I, but I don't think there is enough information here to troubleshoot this for you. How have you built harfbuzz and what does the calling code look like? What were the inputs and content?

**Comment by behdad** [comment]
Yeah definitely not enough info to say anything whatsoever other than "more info needed".

**Comment by whitespeed** [comment]
<html>
<body>


0 | #00 pc 0000000000000000 <unknown>
-- | --
1 | _hb_ot_shape_normalize(hb_ot_shape_plan_t const*, hb_buffer_t*, hb_font_t*) ../../../../../../../core/deps/harfbuzz-icu-freetype/harfbuzz/src/hb-ot-shape-normalize.cc:346
2 | _hb_ot_shape ../../../../../../../core/deps/harfbuzz-icu-freetype/harfbuzz/src/hb-ot-shape.cc:1150
3 | hb_shape_plan_execute ../../../../../../../core/deps/harfbuzz-icu-freetype/harfbuzz/src/hb-shaper-list.hh:42
4 | hb_shape ../../../../../../../core/deps/harfbuzz-icu-freetype/harfbuzz/src/hb-shape.cc:171
 

<br class="Apple-interchange-newline">
</body>
</html>
