### ISSUE TITLE
Build from master fails with jhbuild

### ISSUE THREAD

**Issue by jonas2515** [harfbuzz/harfbuzz#2752]
jhbuild, a tool used by GNOME to build dependencies, fails to build harfbuzz from master for quite some time now, see https://gitlab.gnome.org/exalm/jhbuild-steps/-/issues/13.

The build fails because of an [unused variable](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ot-shape-complex-use-machine.rl#L193) in src/hb-ot-shape-complex-use-machine.rl.

jhbuild builds with the arguments `Dintrospection=enabled -Dgobject=enabled`, maybe nobody is testing that combination?

**Comment by khaledhosny** [comment]
See https://github.com/adrian-thurston/ragel/issues/56

But the generated files are included in the repository, and you can avoid regenerating them by not having ragel available to harfbuzz build at it has not been a build requirement for a long time (the files should not be regenerated if the source files are unchanged, but we couldn’t manage to make meson do this).
