### ISSUE TITLE
Kerx positioning bug

### ISSUE THREAD

**Issue by murasu** [harfbuzz/harfbuzz#2757]
I am trying to add kerx with 26 tables to my font. The results work fine in core-text but not in hb-shape 2.6.4

<img width="418" alt="image" src="https://user-images.githubusercontent.com/22926756/100616223-bc563300-3353-11eb-8eea-d6599e435ea7.png">

What's interesting is if I remove one of the tables (table 20), which has nothing to do with the two gyphs (U+0B95, U+0BCD ) shown in the image, the positioning works.

I'll be happy to send the font file, and the kerx source over by email, if I know which email to send to.

**Comment by murasu** [comment]
Upon further investigation, the bug is in the tool that generates the ankr table. The core-text correct rendering shown in the image is that of OpenType and not AAT.

**Comment by murasu** [comment]
I got some more insights. It's not just a tool issue, it also had to do with limitation to the size of the ankr table which in turn limits the number of anchors I can have in a font. The font I am testing is pan-Indic and the number of anchor points required is larger than that limit. That being said, macOS 11 and iOS 14 picks up GPOS for positioning, even if there is a morx table for substitution in the font. This is a welcome change. Basically morx + kerx is preferred, and if there's no kerx, morx + GPOS. It'll be great if we can have the same in Harfbuzz.

**Comment by behdad** [comment]
HarfBuzz already does that / always did since the first implementation of morx/kerx.

**Comment by murasu** [comment]
@behdad >> HarfBuzz already does that / always did since the first implementation of morx/kerx.

I'm afraid this is not the case. I'm attaching a font that has morx and GPOS. CoreText uses morx for the substitution and since there's no kerx, uses GPOS for positioning. Harfbuzz does morx but does not seem to pick up GPOS in the absence of kerx.

```
iMac:Typewknd-2021-Workshop muthu$ ftxdumperfuser -l NotoSansTamil-Regular.ttf
Noto Sans Tamil Regular (18 tables)
	'DSIG' (8 bytes, offset 300, checksum 0x00000001)
	'GDEF' (180 bytes, offset 616, checksum 0x0E0A0F96)
	'GPOS' (1670 bytes, offset 2756, checksum 0x42383655)
	'OS/2' (96 bytes, offset 520, checksum 0x08B588D6)
	'cmap' (462 bytes, offset 1424, checksum 0xD697DE32)
	'cvt ' (80 bytes, offset 440, checksum 0x0D690216)
	'fpgm' (3605 bytes, offset 9508, checksum 0x9E3613CE)
	'gasp' (8 bytes, offset 308, checksum 0x00000010)
	'glyf' (61874 bytes, offset 17676, checksum 0xDCAC4F72)
	'head' (54 bytes, offset 384, checksum 0xCABCF08E)
	'hhea' (36 bytes, offset 348, checksum 0x0A0A06EF)
	'hmtx' (868 bytes, offset 1888, checksum 0xCC5C16EB)
	'loca' (436 bytes, offset 988, checksum 0x7098ADC3)
	'maxp' (32 bytes, offset 316, checksum 0x02840FDD)
	'morx' (4560 bytes, offset 13116, checksum 0xDD3B687A)
	'name' (1726 bytes, offset 4428, checksum 0xEDC93F48)
	'post' (3351 bytes, offset 6156, checksum 0x33DE3650)
	'prep' (189 bytes, offset 796, checksum 0xB29249F4)
```
<img width="1072" alt="Screenshot 2021-10-04 at 10 11 38 PM" src="https://user-images.githubusercontent.com/22926756/135866881-f6215418-1a48-4900-808f-52b43d9abdd3.png">

The font can be downloaded from here:  https://www.dropbox.com/s/evmkkzaz9a9qv7q/NotoSansTamil-Regular.ttf?dl=0

It's NotoSans Tamil with morx and GPOS.

**Comment by behdad** [comment]
What test text?

**Comment by behdad** [comment]
And what makes you believe it's not applying GPOS?

**Comment by behdad** [comment]
I can reproduce. Let me look into this.

**Comment by behdad** [comment]
I broke this in a recent change; I believe in 5bc05ba155. Now GPOS is not applied if morx is.

**Comment by murasu** [comment]
`kerx` has limitations in the number of anchors it can handle. It was not able to handle a font with Devanagari, Tamil and Latin. Which is why we are switching to morx + GPOS. Will look forward to the fix.

**Comment by behdad** [comment]
Should be fixed. Please test.

**Comment by murasu** [comment]
Appears fixed in the current font I'm working on. Will do more tests later. Thank you!

**Comment by twardoch** [comment]
@murasu If you report issues, please always include specific example text strings. »Any Tamil consonant + Pulli« should be followed by an example text.

**Comment by murasu** [comment]
> @murasu If you report issues, please always include specific example text strings. »Any Tamil consonant + Pulli« should be followed by an example text.

I agree. I meant to include the string but missed it. Here are all the combinations : க் ச் ட் த் ப் ற் ய் ர் ல் வ் ழ் ள் ங் ஞ் ண் ந் ம் ன் ஜ் ஹ் ஸ் ஷ் ஶ் க்ஷ்
