### ISSUE TITLE
[hb-view] Add kitty, etc, image support

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2758]
Certain terminals support showing images these days. Support those?
Eg. https://github.com/simoncozens/font-engineering/pull/6

**Comment by behdad** [comment]
This thread also, for anyone who needs some encouragement (last of which showcases hb-view even.):
https://twitter.com/thingskatedid/status/1316074032379248640

**Comment by khaledhosny** [comment]
I looked into this before, but I’m not sure where to fit this in. Both iTerm and kitty support bas64-encoded PNG data (using different escape sequences, but lets ignore this for now).

If I’m reading the code correctly, hb-view will check if the output is atty and decide if to output “ansi” or “png”, so I thought we can check the terminal and decide we want to output base64-encoded PNG when supported, but hb-view ultimately uses `cairo_surface_write_to_png_stream ()` with a write function that writes to a FILE pointer, and I’m not sure how to make the write function encode the data without saving it first to some sort of temporary file. Can I just call `g_base64_encode ()` inside it, would that work on the partial data? `g_base64_decode_step ()` perhaps? (looks like it will need some non-trivial book-keeping).

**Comment by khaledhosny** [comment]
`cairo-svg-surface.c` has a `base64_write_func`, may be I can steal it.

**Comment by behdad** [comment]
Just store it in a `GString` or some other container...

**Comment by behdad** [comment]
> `cairo-svg-surface.c` has a `base64_write_func`, may be I can steal it.

That sounds even better.

**Comment by khaledhosny** [comment]
There is also [libsixell](https://github.com/saitoha/libsixel) which outputs a format supported by a few terminals, but I don’t know if there is a way to check if the terminal supports this format (short of hard-coding a list of terminal names).

**Comment by khaledhosny** [comment]
Got some code for detecting SIXEL support, working on it now.

**Comment by khaledhosny** [comment]
Scratch that, libsixel is a horrible, horrible, library.

**Comment by behdad** [comment]
> Scratch that, libsixel is a horrible, horrible, library.

I took a look and didn't see what's horribly wrong with it. At any rate, I think we should optionally add Chafa:

  https://github.com/harfbuzz/harfbuzz/issues/2430

**Comment by ctrlcctrlv** [comment]
> Scratch that, libsixel is a horrible, horrible, library.

Ha, funny, worlds colliding, I took over libsixel's maintainership with @dankamongmen when I was still green enough to think that I could get Kitty to link against libsixel. We fixed some CVE's but the consensus is that it needs complete replacement, meaning I agree, sigh. I'll try to remember to inform y'all if we figure out what to replace it _with_.

**Comment by khaledhosny** [comment]
We use [Chafa](https://github.com/hpjansson/chafa) (optionally) now, in additional to the built-in support for kitty and iTerm2 image protocols.
