### ISSUE TITLE
Syloti Nagri support

### ISSUE THREAD

**Issue by LornaSIL** [harfbuzz/harfbuzz#2773]
I'm not a developer, but it looks like HB is not supporting Syloti Nagri. I'm wondering if support can be added for:
- U+A806 and U+A82C.

The properties for U+A806 were changed from Pure_Killer to Virama in Unicode 12.0 and 
then in Unicode 13.0:
- U+A82C was added as Pure_Killer

So, for Unicode 13.0 we have:
```
A82C          ; Pure_Killer # Mn       SYLOTI NAGRI SIGN ALTERNATE HASANTA
A806          ; Virama # Mn       SYLOTI NAGRI SIGN HASANTA 
```
What can I do to assist support for these characters?

**Comment by behdad** [comment]
Hi Lorna. We do support Syloti Nagri through our USE shaper. What makes you believe it doesn't work?

**Comment by LornaSIL** [comment]
I thought I had responded to this via email, but that apparently didn't work. 
I have finally done some more testing with a font that actually has the conjuncts in the font, and they are working in both Graphite and OpenType.
I don't have a font that supports U+A82C so I can't test that one.
