### ISSUE TITLE
Allow ignorable characters

### ISSUE THREAD

**Issue by kelvin13** [harfbuzz/harfbuzz#278]
Harfbuzz should let you specify ignorable codepoints that count towards cluster incrementation but get bypassed for features such as contextual substitution. Ignorable characters should still interrupt ligatures. If you set the ignorable character to say `'#'`, and

```
sub A B' C by D;
```

is a feature then the string `'AB#C'` should shape to
`[A] [D] [C]` with the cluster values `0, 1, 3`

**Comment by behdad** [comment]
HarfBuzz already does that for a hardcoded set of characters:
https://github.com/behdad/harfbuzz/blob/master/src/hb-unicode-private.hh#L134

The question is do we want to allow that to be customized.  I'm not quite sure yet.

**Comment by kelvin13** [comment]
Can we have this happen for negative codepoints? I pass a unicode codepoint of –1 and the shaper treats it as ignorable instead of throwing an error?

**Comment by jfkthame** [comment]
No. Pass harfbuzz the actual sequence of Unicode characters that you want shaped using a given font. That's what it deals with. Don't include extraneous "codepoints" that are not really characters of the text, but something else specific to your application; filter them out before passing the text to HB, and just keep track of their original locations.

**Comment by kelvin13** [comment]
This is needed for preserving cluster values. filtering out the “extraneous” characters will invalidate cluster indexes, making editing impossible.

**Comment by jfkthame** [comment]
No, you just need to keep track of the mapping between indexes in your original storage (text + whatever else is interspersed in it) and the "pure" text that harfbuzz handles.

**Comment by behdad** [comment]
> making editing impossible

Not impossible.  You just would need to keep an extra mapping..

Another way is to call hb_buffer_add() and just pass whatever cluster value you want.

It's not feasible to add magic numbers (like, ignore all "negative"); what I had in mind was perhaps ignoring all unknown Gen_Cat=Cf chars as ignorable; that way the Unicode callbacks can mark any value as ignorable.

**Comment by kelvin13** [comment]
the act of filtering out the characters themselves will destroy any such mapping. If I have 'ABCDEF' and i take out the B and the D from positions 1 and 3, you cannot reinsert the D at position 3 of 'ACEF' to get the old string back. It gets even more problematic when you have to deal with index ranges because the removal of a characters from elsewhere in the string can invalidate the range.

**Comment by KrasnayaPloshchad** [comment]
That depends on lookups.

**Comment by behdad** [comment]
Basically, adjust our default_ignorables to better align with https://www.unicode.org/reports/tr44/tr44-22.html#Default_Ignorable_Code_Point

**Comment by behdad** [comment]
> Basically, adjust our default_ignorables to better align with https://www.unicode.org/reports/tr44/tr44-22.html#Default_Ignorable_Code_Point

It's aligned.  Question is, to have it hardcoded as currently is, or use gen_cat==Cf as part of the function.

**Comment by behdad** [comment]
Leaning on no for now, as I don't see a clear use-case.
