### ISSUE TITLE
Attach dist artifact to CI‌ jobs

### ISSUE THREAD

**Issue by alerque** [harfbuzz/harfbuzz#2785]
Per [this comment](https://github.com/harfbuzz/harfbuzz/pull/2781#issuecomment-751398292) we need a way to spot check the automatically generated dist tarballs if desired. They should be attached to [Circle CI jobs](https://app.circleci.com/pipelines/github/harfbuzz/harfbuzz) somewhere, probably on the *distcheck* builds since those are what ultimately end up being uploaded to releases when tags are posted.

**Comment by behdad** [comment]
Anything still outstanding here?

**Comment by alerque** [comment]
Nope nope, this work was done some time ago and the tracking issue never updated to match, my bad. (Running a little behind on notifications.)
