### ISSUE TITLE
Drop msys2 build job

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2795]
It is a constant source of unrelated CI failures, and I’m not sure what value it adds since we already has a separate job for cross-compiling wing MingW (and we use it to generate the Windows binaries), as well as MSVC build jobs for building and testing in Windows.

**Comment by behdad** [comment]
Let's either do or close.

**Comment by khaledhosny** [comment]
It is working again, so lets close until the next breakage. If it brook again too soon I’m going to drop it.
