### ISSUE TITLE
Our typedef's confuse GTK-Doc

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2796]
Many of our typedef's, like `typedef struct hb_face_t hb_face_t;` seem to confuse GTK-Doc and lead to lots of warning messages like:
```
../xml/hb-face.xml:777: element refsect2: validity error : ID hb-face-t already defined
<refsect2 id="hb-face-t" role="typedef">
```
 and
```
Warning: multiple "IDs" for constraint linkend: hb-face-t.
```

 (the log has hundreds of lines like the last one)

Also the HTML is slightly broken and links to `hb_face_t` go to the top of the page not to its documentation. 

I thin this was discussed before, but I can’t find the discussion or remember the conclusion.

**Comment by behdad** [comment]
I believe I filed this with gtk-doc before. But yeah, weird that something this simple doesn't work. Changing the struct names now would be an API break to some clients so I'm hesitant to do that. In particular, some might be using `struct hb_face_t` etc to refer to our types before including our headers...

Should be fairly easy to make gtk-doc understand and merge those two symbols.
