### ISSUE TITLE
Do we need to document hb-gobject?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2797]
I’m not entirely sure what the [hb-gobject](https://harfbuzz.github.io/harfbuzz-hb-gobject.html) API is for, but the documentation page is basically a list of API functions with no description at all.

Pango does not seem to list its similar GObject methods in its documentation, so may be we should do the same. Otherwise I need a bit of explanation what these symbols do, and may be we can generate some generic documentation for them (since the code is generated as well).

**Comment by behdad** [comment]
> I’m not entirely sure what the [hb-gobject](https://harfbuzz.github.io/harfbuzz-hb-gobject.html) API is for,

This are the mechanics that make gobject-introspection work.

Indeed, Pango puts them in `<SUBSECTION Private>`. I think we can do the same, yes.
