### ISSUE TITLE
Devanagari Sanskrit Indic typing should enforce Matra and Accent validation or no Duplicates

### ISSUE THREAD

**Issue by advaita56** [harfbuzz/harfbuzz#2803]
The Devanagari Unicode Block is 0900 to 097F = 128 glyphs. 
From a purely Sanskrit point-of-view (where glyphs from Awadhi, Dravidian, etc. are not accounted for).
The characters herein are classified as:
- Base Glyph Vowel = 0905 to 090C, 090F, 0910, 0913, 0914, 0960, 0961 = 14 glyphs = **V**
- Base Glyph Consonant = 0915 to 0928, 092A to 0930, 0932, 0933, 0935 to 0939, 097A = 35 glyphs = **C**
- Mark Glyph Matra Vowel Sign = 093E to 0944, 0947, 0948, 094B, 094C, 0962, 0963 = 13 glyphs = **M**
- Mark Glyph Nasalization Aspirate Sign = 0900, 0901, 0902, 0903 = 4 glyphs = **N**
- Mark Glyph Accent Stress Sign = 0951, 0952 = 2 glyphs = **A** 
--------------------------------------------------------------------------------
- Numerals = 0966 to 0970 = 10 glyphs = D
- Punctuation Sign = 0964, 0965 = 2 glyphs = P 
- Sandhi Sign = 093D = 1 glyph = S
- Halant Virama Sign = 094D = 1 glyph = H
--------------------------------------------------------------------------------
For the purposes of this discussion we have given arbitrary abbreviations:
- Base Glyph Vowel = V
- Base Glyph Consonant = C
- Mark Glyph Matra Vowel Sign = M
- Mark Glyph Nasalization Sign = N
- Mark Glyph Accent Stress Sign = A 

Indic Shaping properties must account for the following to create VALID text:
1.	Base Glyph Vowel = **V** cannot attach to Mark Glyph Matra Vowel Sign = **M**
“VM” is an invalid combination. Indic shaping must prevent this. E.g. 0905+0940 is invalid. 
2.	Base Glyph Vowel = **V** can attach to only one glyph from the - Mark Glyph Nasalization Sign = **N**
 “VNN” is an invalid combination. Here the last typed glyph should erase any previous **N**.
E.g. 0905+0901+0902 is invalid. 0905+0901+0901 is invalid.
3.	Base Glyph Vowel = **V** can attach to only one glyph from the - Mark Glyph Accent Stress Sign = **A**
 “VAA” is an invalid combination. Here the last typed glyph should erase any previous A.
E.g. 0905+0951+0952 is invalid. 0905+0951+0951 is invalid. 
4.	Base Glyph Vowel = **V** can attach to only two glyphs from glyph sets (N, A) with the provision that the two glyphs are from distinct glyph sets.
“VNA”, “VAN” are valid combinations. E.g. 0905+0901+0952 is valid. 
“VNAN”, “VANA” are invalid. Here the last typed glyph should erase any previous **N**, **A** if duplicate. 
5.	Ligatures consisting of Punctuation Sign, Sandhi Sign must be prevented in Indic shaping.
6.	Ligatures consisting **only** of Numerals 1 or 3  along with **both** the Accents are permitted.
0967 + 0951 + 0952 (all three together) is valid.
0969 + 0951 + 0952 (all three together) is valid.
0967 + 0951 is invalid. 
0967 + 0952 is invalid.
0969 + 0951 is invalid.
0969 + 0952 is invalid.
7.	Base Glyph Consonant = **C** can attach to only one Mark Glyph Matra Vowel Sign = **M**.
“CM” is a valid combination. 
“CMM” is invalid. Indic shaping must prevent this by keeping only the last typed **M**.
8.	Base Glyph Consonant = **C** can attach to only three glyphs from glyph sets (**M**, **N**, **A**) with the provision that the three glyphs are from distinct glyph sets, and CM cluster precedes the others.
“CMNA”, “CMAN”, “CNA”, “CAN” are valid combinations. 
“CMNAN”, “CMANA” are invalid. Here the last typed glyph should erase any previous **N**, **A** if duplicate.
9.	With the use of Halant Virama Sign **H**, indic shaping must select the appropriate consonant ligatures if present in the font.
10.	For invalid combinations, the dotted circle glyph 25CC **must show** if implemented in font.
11. Attached is a pdf file illustrating the above points using a Devanagari font.
12. The Sanskrit2020 font can be seen here [](https://sourceforge.net/projects/advaita-sharada-font/files/Devanagari/)
13. Alternatively we can check using the Sanskrit Text font that installs with Windows 10.
[harfbuzz Indic shaping Issues.pdf](https://github.com/harfbuzz/harfbuzz/files/5763824/harfbuzz.Indic.shaping.Issues.pdf)

**Comment by advaita56** [comment]
[https://sourceforge.net/projects/advaita-sharada-font/files/Devanagari/](url)

Devanagari font Sanskrit2020

**Comment by jfkthame** [comment]
These are issues specific to Sanskrit spelling/orthographic rules, and out of scope for the shaping engine, which must handle even sequences that would be regarded as invalid according to traditional Sanskrit rules but may be required for other languages and use cases.

In general, the concerns here should be addressed by (language-specific) spell-checkers and/or input methods, not within harfbuzz.
