### ISSUE TITLE
HarfBuzz-0.0.typelib version?

### ISSUE THREAD

**Issue by rubyFeedback** [harfbuzz/harfbuzz#2809]
Hey guys.

I am using ruby-gtk bindings, and compiling it has a problem.

    /root/.gem/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:37:in `require': Typelib file for namespace 'HarfBuzz', version '0.0' not found (GObjectIntrospection::RepositoryError::TypelibNotFound)

This may not be the fault of harfbuzz, but what I am confused here is why harfbuzz shows the version 0.0.

The file at hand is at girepository-1.0/HarfBuzz-0.0.typelib - but why is it 0.0?

For comparison, in atk I have a more higher numbered version: Atk-1.0.typelib

**Comment by khaledhosny** [comment]
What is the problem with having a 0.0 version?
