### ISSUE TITLE
Out of bounds memory read during AAT layout kerning

### ISSUE THREAD

**Issue by jwtowner** [harfbuzz/harfbuzz#2816]
I've come across an out of bounds memory access bug! Problem went undetected normally since `IntType<int16_t,2>::sanitize` would normally return false on the garbage data. However, on Android ARM-v7 builds with Clang 6.0 or greater and with optimizations turned on, `sanitize` will sometimes return true on certain fonts, resulting in space characters getting huge amounts of garbage kerning applied.

The problem occurs when [`KerxSubTableFormat2::get_kerning`](https://github.com/harfbuzz/harfbuzz/blob/c8c5e52aba904cfede1c7e8e1043a392053938e6/src/hb-aat-layout-kerx-table.hh#L389) calls `Types::offsetToIndex`, passing in the arguments `kern_idx`, `this` and `arrayZ.arrayZ`. An example of what these values might be are `kern_idx = 2`, `this = 0x0da00c3e` and `arrayZ.arrayZ = 0x0da00c4e`. The key point is that the address of `this` is less than `arrayZ`, and `kern_idx` is a value less than the difference between these two addresses.

Looking at [Types::offsetToIndex](https://github.com/harfbuzz/harfbuzz/blob/c8c5e52aba904cfede1c7e8e1043a392053938e6/src/hb-aat-layout-common.hh#L681), we see it computes the offset with this formula, casting the value back as an unsigned int.

`return (offset - ((const char *) array - (const char *) base)) / T::static_size;`

Plugging in our values, we get:

`return (2 - (0x0da00c4e - 0x0da00c3e)) / sizeof(HBUINT16);`

When evaluated and cast to an unsigned int, this results in the value `4294967289`. And after being assigned back to `kern_idx` and used as the index into `arrayZ`, this results in an out of bounds access, with different behavior depending on whether the CPU architecture is using 32-bit or 64-bit addressing.

I'm not sure what the correct fix here is. Any ideas?

**Comment by jfkthame** [comment]
Could you provide a test font and input text string that triggers this?

**Comment by jwtowner** [comment]
> Could you provide a test font and input text string that triggers this?

Thanks for the quick response. The font face is [Noto Sans Bold](https://www.google.com/get/noto/#sans-lgc) and the input text string is "To continue playing". The problem occurs when calling `hb_shape_full` with `HB_DIRECTION_LTR`, `HB_SCRIPT_LATIN` and a locale of "en-us" for the segment properties, and `HB_BUFFER_FLAG_BOT | HB_BUFFER_FLAG_EOT` as the buffer flags, and `HB_BUFFER_CLUSTER_LEVEL_MONOTONE_GRAPHEMES` as the cluster level, using the OpenType shaping backend. When it does the second AAT kerning pass on the input string, when kerning the first space character and the character 'c', results in a `kern_idx` of 2, leading to that out of bounds access.

Even on an x86_64 CPU, the final offset is 4294967289, but `sanitize` catches it and returns false, so no garbage kerning value is applied to the advance.

**Comment by jfkthame** [comment]
I don't understand this; when I examine Noto Sans Bold (just downloaded from your Google link), I don't see any sign of AAT layout tables (specifically, no `kerx`):

```
$ ttx -l NotoSans-Bold.ttf 
Listing table info for "NotoSans-Bold.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    GDEF  0xF0D7DDE7      1472    246680
    GPOS  0x19F55879     59880    248152
    GSUB  0x4437EA6A      5760    308032
    OS/2  0x6D3C895A        96       344
    cmap  0xC29FFEE4      2606     13396
    glyf  0x431DCB05    181156     28992
    head  0x108801BB        54       220
    hhea  0x0CA91424        36       276
    hmtx  0xA3FEF3FC     12956       440
    loca  0x1153FFCB     12988     16004
    maxp  0x0CE401EB        32       312
    name  0x8E41B8DB      1564    210148
    post  0xB1F507AA     34965    211712
```

**Comment by jwtowner** [comment]
I see what's happening. We're running our fonts through FontForge and then converting them into the WOFF2 format, which seems to add a bunch of additional tables. I've uploaded this version of the font here: [https://github.com/jwtowner/harfbuzz/blob/master/test/api/fonts/notosans-bold.woff2](https://github.com/jwtowner/harfbuzz/blob/master/test/api/fonts/notosans-bold.woff2)

Running `ttx` on gives the following, but still no `kerx` table which is indeed weird.

```$ ttx -l notosans-bold.woff2
Listing table info for "notosans-bold.woff2":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    FFTM  0x83A67C73        28         0
    GDEF  0x31B918C6      1032        28
    GPOS  0x342EEC8A     88298      1060
    GSUB  0xCF0E817F      6090     89358
    OS/2  0x6D4989F1        96     95448
    TTFA  0xB85118C3       511     95544
    cmap  0x31012004       982     96055
    cvt   0x824C14DE       372     97037
    feat  0xC04413EB       128     97409
    fpgm  0x3A288E7C      3437     97537
    gasp  0x00000010         8    100974
    glyf  0x2F09B958    149550    100982
    head  0xA4063686        54    250532
    hhea  0x0CA91434        36    250586
    hmtx  0xBA04F620     12992    250622
    kern  0x423F49B5     36112    263614
    lcar  0x1C162241        88    299726
    loca  0x00000000         0    250532
    maxp  0x0F920290        32    299814
    morx  0xE987E727      1944    299846
    name  0xF1E3336C      4771    301790
    post  0xFF9F0032        32    306561
    prep  0x369A8960       253    306593
    prop  0xE46C0129       866    306846
```

WOFF2 is just our transport/interchange format. Before use on each client system, we're first using https://github.com/google/woff2 to decompress the WOFF2 files into a cache directory on disk, and then memory mapping in the decompressed TTF/OTF before use with Harfbuzz and Freetype.

**Comment by behdad** [comment]
Thanks. The `kern` table can have data hitting that codepath. This should be enough for us to debug.

That said, something *really* wrong with what fontforge is doing for you. You *don't* want to ship those fonts.

Why are you running them through FontForge?

**Comment by behdad** [comment]
If you can upload the decompressed version that would be even easier for us to debug this. Thanks.

**Comment by jwtowner** [comment]
> That said, something _really_ wrong with what fontforge is doing for you. You _don't_ want to ship those fonts.

Agreed, I will look into that from my end, perhaps it's a bug that can be fixed there too. We're using FontForge to strip out the hinting tables from the fonts, since we do not render the glyphs with hinting at all and they take up a substantial amount of the font's file size, even when compressed. But if that's causing us problems, we may have to rethink how we do that.

> If you can upload the decompressed version that would be even easier for us to debug this. Thanks.

Sorry for the slight delay in getting you this, had just finished work for the day and was on a break. Here you go: https://github.com/jwtowner/harfbuzz/blob/master/test/api/fonts/noto-sans-bold-woff2-decompressed.ttf

Thanks for looking into it!

**Comment by behdad** [comment]
> Agreed, I will look into that from my end, perhaps it's a bug that can be fixed there too. We're using FontForge to strip out the hinting tables from the fonts, since we do not render the glyphs with hinting at all and they take up a substantial amount of the font's file size, even when compressed. But if that's causing us problems, we may have to rethink how we do that.

That's exactly why I built the FontTools subsetter. Just do:
```
$ pip install fonttools
$ fonttools subset --help
```

**Comment by jwtowner** [comment]
> That's exactly why I built the FontTools subsetter. Just do:

Very nice, I didn't realize the subset command existed. Got to try it out the other night, solves our problem with not generating the bad kern table! Thanks.

**Comment by behdad** [comment]
Fixed in https://github.com/harfbuzz/harfbuzz/commit/29708e959a04ee003b9c0738f0c5330584f15b4f
Forgot to include issue link in the commit message.
