### ISSUE TITLE
HarfBuzz.font_get_extents_for_direction() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by SpiderBraids** [harfbuzz/harfbuzz#2822]
I'm currently trying to use HarfBuzz in a Python docker (version 1.7.2), and I'm currently getting the error "HarfBuzz.font_get_extents_for_direction() takes exactly 3 arguments (2 given)":
![image](https://user-images.githubusercontent.com/54842128/105179228-a565dd00-5b5b-11eb-8c9c-89655f5b1172.png)

However, from what I've read [here](https://lazka.github.io/pgi-docs/HarfBuzz-0.0/functions.html), the function in question is only supposed to take two arguments in Python, as the 3rd argument in C is a pointer to a font_extents_t for returning the output, and adding a blank list as the 3rd argument in Python gives an error that seems to suggest it's supposed to be a font_extents_t:
![image](https://user-images.githubusercontent.com/54842128/105179399-e1993d80-5b5b-11eb-9d0f-2037891d799f.png)

I would like to know if this is an error that has been fixed in later versions, or if something else is wrong.

**ETA**
Just tried the latest tarball (2.7.4) and it still produces the same errors.

**Comment by khaledhosny** [comment]
I can’t reproduce this with 2.7.4:
```python
import sys
import gi

gi.require_version('HarfBuzz', '0.0')

from gi.repository import HarfBuzz as hb

blob = hb.blob_create_from_file (sys.argv[1])
face = hb.face_create (blob, 0)
font = hb.font_create (face)

extents = hb.font_get_extents_for_direction (font, hb.direction_t.LTR)
print (f"{extents.ascender=}, {extents.descender=}, {extents.line_gap=}")
```

```
$ python3 test.py Amiri-Regular.otf
extents.ascender=1124, extents.descender=-634, extents.line_gap=0
```
