### ISSUE TITLE
[subset/COLR] Uninitialized `firstLayerIdx`

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2829]
From a Coverity report:
```
src/hb-ot-color-colr-table.hh: 220 in OT::COLR::subset(hb_subset_context_t *) const::[lambda(unsigned int) (instance 1)]::operator ()(unsigned int) const()
214                                     if (unlikely (!old_record))
215                                       return hb_pair_t<bool, BaseGlyphRecord> (false, Null (BaseGlyphRecord));
216     
217                                     BaseGlyphRecord new_record;
218                                     new_record.glyphId = new_gid;
219                                     new_record.numLayers = old_record->numLayers;
>>>     CID 365706:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized value "new_record". Field "new_record.firstLayerIdx" is uninitialized when calling "hb_pair_t".
220                                     return hb_pair_t<bool, BaseGlyphRecord> (true, new_record);
221                                   })
222         | hb_filter (hb_first)
223         | hb_map_retains_sorting (hb_second)
224         ;
225     
```

Is right. Was this code tested at all?

**Comment by ckitagawa-work** [comment]
I believe the new_record's `firstLayerIdx` is always updated during serialization on line 181 of src/hb-ot-color-colr-table.hh as it relies on knowing the number of layers serialized before it. That said, this is a good catch as the value should probably be default initialized to 0 at line 220. I've put up https://github.com/harfbuzz/harfbuzz/pull/2831 for that.

> Was this code tested at all?

Yes a number of tests were added as part of https://github.com/harfbuzz/harfbuzz/pull/2132

**Comment by behdad** [comment]
> I believe the new_record's `firstLayerIdx` is always updated during serialization on line 181 of src/hb-ot-color-colr-table.hh as it relies on knowing the number of layers serialized before it.

Thanks. That's what I thought.
