### ISSUE TITLE
Use Glyph IDs, glyph names in SVG?

### ISSUE THREAD

**Issue by loveencounterflow** [harfbuzz/harfbuzz#2837]
To my surprise I realized that by doing `apt install libharfbuzz-bin` or `brew install harfbuzz` I do get some executables like `hb-shape` and `hb-view`. That's a well-hidden easter egg indeed, and such a useful one! 

So what I want to do is extract glyph shapes from fonts in SVG path format to do typesetting in SVGs and keep a database of glyph shapes. I realize I *could* do part of the job using `hb-view` which supports SVG output, but, alas, it insists on numbering glyphs (SVG `<symbol>`s) consecutively. I believe I could find out the glyph IDs by squaring the output of `hb-view` with the output of `hb-shape` and using the same font and the same text. OTOH why not just include Glyph IDs (and/or glyph names) in the SVG?

On a related note, wouldn't it be great if one could get a shape not from a text but from inputting glyph IDs (or glyph names)?

I fully realize all of this is somewhat outside the main scope of HarfBuzz, but then `hb-view` is not strictly within the scope of text shaping, is it?

**Comment by khaledhosny** [comment]
`hb-view` uses Cairo to render the glyphs, and the SVG output is generated by it. You can use [FontTools](https://github.com/fonttools) to extract glyph shapes and have more control over the output.
