### ISSUE TITLE
The win32 zip files don't have a directory anymore

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2840]
Back when I was making releases, the `harfbuzz-win32-*.zip` file included a similarly-named directory inside, within which was the built binaries. New releases don't have directory and the files are straight up in the root of the zip file. I find that clumsy. Any chance we can move back to the old scheme, since that's what our main release files (as well as pretty much all other release files?) do? Thanks.

**Comment by khaledhosny** [comment]
You can download the zip file from the CI build and it has a top level directory now https://app.circleci.com/pipelines/github/harfbuzz/harfbuzz/1560/workflows/f0253eab-57f0-4719-bf7c-68430c23cc8f/jobs/154815/artifacts
