### ISSUE TITLE
[subset] Cannot properly subset the COLR/CPAL fonts

### ISSUE THREAD

**Issue by yisibl** [harfbuzz/harfbuzz#2843]
Using the WASM rebuilt in this PR https://github.com/harfbuzz/harfbuzzjs/pull/32, some characters cannot be subset correctly. 

1. Used [colr-table.ttf.zip](https://github.com/harfbuzz/harfbuzzjs/files/5923335/colr-table.ttf.zip), This font is generated using [nanoemoji](https://github.com/googlefonts/nanoemoji).
2. Enter 'k', the font actually downloaded cannot be used(`abc` is fine).
[subset.ttf.zip](https://github.com/harfbuzz/harfbuzzjs/files/5923322/subset.ttf.zip)

**Comment by behdad** [comment]
cc @ckitagawa-work in case they have an opinion. I haven't looked into this. Thanks.

**Comment by yisibl** [comment]
https://github.com/fonttools/fonttools/pull/2177

**Comment by behdad** [comment]
COLRv1 is an unreleased proposal. 

Is this request for version 0 of COLR table, or the proposed COLRv1? I think we have COLRv0 subsetting already.

**Comment by behdad** [comment]
> * Used [colr-table.ttf.zip](https://github.com/harfbuzz/harfbuzzjs/files/5923335/colr-table.ttf.zip), This font is generated using [nanoemoji](https://github.com/googlefonts/nanoemoji).

Ah, yes. That would be COLRv1. That's being worked on. Should be in main in a few weeks.

https://github.com/harfbuzz/harfbuzz/pull/2937

Closing this issue.

**Comment by behdad** [comment]
Humm... Reopening to report back when it's merged.

@qxliu76

**Comment by yisibl** [comment]
> Used colr-table.ttf.zip, This font is generated using nanoemoji.

@behdad Thanks, this is a COLRv0 font.

**Comment by behdad** [comment]
> Thanks, this is a COLRv0 font.

And it doesn't work?

**Comment by yisibl** [comment]
After subsetting through harfbuzzjs, open an error in the browser:

```shell
OTS parsing error: glyf: Failed to parse table
```
[subset-k.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/6290255/subset-k.ttf.zip)

**Comment by behdad** [comment]
@qxliu76 @garretrieger any chance you can check this out?

**Comment by garretrieger** [comment]
Sure will do.

**Comment by yisibl** [comment]
@garretrieger Please update `hb-subset.wasm` in harfbuzzjs
