### ISSUE TITLE
Allow enabling features from specified language

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2847]
We accept BCP 47 language tags, which can specify script or orthographic variations already. And we have private extensions to specify OpenType script tag and language tag as well.

I propose we also enable pulling features from the BCP 47 language tag as well:

- Using language (possibly by specifying as envvar $LANGUAGE) as backdoor to (globally) enable features in applications that otherwise do not allow that. See eg. https://github.com/harfbuzz/harfbuzz/issues/2768

- To implement several regional and historical orthographies where OpenType has stipulated registered features for. From a cursory look at the feature tag registry, I see for example `hist`, `hlig`, `hojo`, `jp78`, `jp83`, `jp90`, `jp04` and others; even `simp` and `trad`.

cc https://github.com/harfbuzz/harfbuzz/issues/2680 https://github.com/harfbuzz/harfbuzz/issues/2844

**Comment by dscorbett** [comment]
So something like `fa-x-hbfeat-63737768-1` to enable 'cswh' in IranNastaliq?

**Comment by behdad** [comment]
> So something like `fa-x-hbfeat-63737768-1` to enable 'cswh' in IranNastaliq?

Something like that. Or maybe possibly a shorthand as well `x-hbfecswh`.
