### ISSUE TITLE
The behaviour of the new Oriya overline has changed in HB

### ISSUE THREAD

**Issue by devosb** [harfbuzz/harfbuzz#2849]
I am using the font Noto Sans Oriya as a base to produce Japa Sans Oriya, which supports the new (in Unicode 13) character U+0B55 ORIYA SIGN OVERLINE. For the word _spear_ (codepoints 0B2C,0B3E,0B55,0B32,0B3E from the [Unicode proposal for this character](http://www.unicode.org/L2/L2019/19005r2-odia-overline.pdf)) HB shows different output depending on what version of HB is used, as shown by `hb-shape` and `hb-view`.

HB 2.6.4 shows
```
[uni0B2C=0+718|uni0B3E=0+201|uni0B55=2@-100,0+0|uni0B32=3+833|uni0B3E=3+201]
```
![hb-264](https://user-images.githubusercontent.com/12450072/107445245-49a6c800-6af9-11eb-9215-34e8c1a2b967.png)
while HB compiled from source this afternoon (9 Feb) shows
```
[uni0B2C=0+718|uni0B55=0@-365,0+0|uni0B3E=0+201|uni0B32=3+833|uni0B3E=3+201]
```
![hb-git](https://user-images.githubusercontent.com/12450072/107445299-67742d00-6af9-11eb-9c35-dd6f95945fe5.png)
The older (2.6.4) output is correct.

**Comment by devosb** [comment]
The font can be download from our [CI server](https://build.palaso.org/buildConfiguration/Fonts_JapaSansOriya).

**Comment by behdad** [comment]
cc @dscorbett @jfkthame

**Comment by behdad** [comment]
FWIW, U+0B55 is categorized as Top Matra in our table; which we place After Main. So I'm not sure why this is happening.

**Comment by behdad** [comment]
> The font can be download from our [CI server](https://build.palaso.org/buildConfiguration/Fonts_JapaSansOriya).

That seems to require a login. Please attach font as zip file here.

**Comment by jfkthame** [comment]
When did the behavior change between 2.6.4 and now? Bisecting to identify the specific commit that changed things would be a great start.

**Comment by punchcutter** [comment]
2.6.4 is before Unicode 13 support and U+0B55 was added in Unicode 13 so I wouldn't be surprised that the behavior is different.

**Comment by jfkthame** [comment]
> U+0B55 was added in Unicode 13

Ah, that's a detail I hadn't checked on yet - thanks.

**Comment by devosb** [comment]
Oops, sorry about the CI. I think you can follow the Guest link, which I should have mentioned. I have uploaded a zip file with the needed font, which was build on my system (not the CI) so it has been tested as I write this issue.
[JapaSansOriya-2.000--dev-63d4dcM.zip](https://github.com/harfbuzz/harfbuzz/files/5962268/JapaSansOriya-2.000--dev-63d4dcM.zip)

Classifying U+0B55 ORIYA SIGN OVERLINE as a Top Matra might be the issue. I could not find that classification in the code. That term sounds suspicious, since OVERLINE needs to go over both consonants and matras, and generally matras do not go on matras. The font handles stacking the OVERLINE above U+0B3F ORIYA VOWEL SIGN I.

I agree that running `git bisect` to find the commit that changed the behaviour would be fantastic. However, with 2.6.4 I build with Autotools, and with recent versions I build with `meson/ninja`. I suppose I could have a script that checks for `meson.build`, and calls the correct tools.

However, when I tried to manually build the latest version of HB, after building 2.6.4, `hb-shape` gives an error message: 
```
hb-shape: symbol lookup error: hb-shape: undefined symbol: hb_buffer_serialize
```
and I don't know how to fix that, except by rolling back my VM. So running `git bisect` would probably encounter that issue.

I can understand the behaviour of OVERLINE changing after HB was updated for Unicode 13. However, InDesign 2020 and 2021, after enabling HB, shows the HB 2.6.4 type behaviour. So I am hesitant to add the reordering to the font to make it work with new versions of HB, especially if such changes to the font break it for use with InDesign, which might require two fonts, one for 2.6.4 era HB and one for new versions of HB. I did not want to go down that path unless I was sure that the change in HB was indeed correct.

Thank you all for your help!

**Comment by devosb** [comment]
This issue also happens with other matras
- U+0B40 ORIYA VOWEL SIGN II
- U+0B4B ORIYA VOWEL SIGN O
Lots of test data is at https://github.com/silnrsi/font-japa-sans-oriya/blob/main/tests/auto-overline.txt

**Comment by punchcutter** [comment]
InDesign currently does not have the Unicode 13.0 update to the internal harfbuzz so your result will change when it gets updated. 

Looking at the Noto Oriya source the aaMatra has a topright anchor while the base has a top anchor. If the U+0B55 only has a _top anchor it would explain why it attaches to the base and not the matra.

**Comment by devosb** [comment]
Indeed, U+0B55 only has a `_top` anchor. However, I add a `top` anchor to the matras.

**Comment by punchcutter** [comment]
It looks like those are getting reordered based on the USE categories. Your input makes it B VPst VAbv which should be B VAbv VPst according to the USE order. That's why it won't attach to the matra.

**Comment by behdad** [comment]
Reading the first few pages of the Unicode proposal, it seems wrong to categorize this as Top Matra it seems. Should have been categorized more like Nukta maybe?

**Comment by dscorbett** [comment]
That’s what I thought too, but [the Script Ad Hoc group disagreed](https://www.unicode.org/L2/L2019/19286-script-recs.pdf#page=7).

**Comment by devosb** [comment]
Thanks. I have two questions then.

1. Does your comment mean that the `ory2` is routed to the USE, as opposed to a dedicated Indic shaper?
2. In HB 2.6.4, why did it work? Was the USE not invoked, or was some default USE category selected for the (as that time) unknown codepoint?

Maybe it should have been categorised as Nukta. If so, should an override be done for HB? Somewhere in a GitHub issue, I cannot find it, sorry, it was stated that USE categories are for logical descriptions and should not be changed to make shaping easier. If the shaping needs a different property, an override should be entered.

**Comment by behdad** [comment]
> * Does your comment mean that the `ory2` is routed to the USE, as opposed to a dedicated Indic shaper?

No I think David misspoke. `ory2` goes to our Indic shaper.

> 2\. In HB 2.6.4, why did it work?

It probably was left out of the syllable so was not reordered. Then attached to previous glyph during GPOS (which works across syllable boundaries as well).

**Comment by behdad** [comment]
> If so, should an override be done for HB?

Yes, we can override it here ourselves. Right now is hardcoded in `hb-ot-shape-complex-indic.hh`. Some time soon we'll have an overrides text file for Indic shaper as well.

**Comment by behdad** [comment]
> That’s what I thought too, but [the Script Ad Hoc group disagreed](https://www.unicode.org/L2/L2019/19286-script-recs.pdf#page=7).

That's bizarre, given that the following are happily categorized as Nukta:
```
10A38..10A3A  ; Nukta # Mn   [3] KHAROSHTHI SIGN BAR ABOVE..KHAROSHTHI SIGN DOT BELOW
```

**Comment by punchcutter** [comment]
I'm the one who misspoke. I assumed USE at first since Oriya is defined in there, but didn't check that it's currently Indic shaper.

**Comment by dscorbett** [comment]
[Chapter 12](https://www.unicode.org/versions/Unicode13.0.0/ch12.pdf#page=46) says:
>This length mark is represented in text by U+0B55 ORIYA SIGN OVERLINE. It occurs in the text representation directly after the letter or sign it modifies, and after any nukta which is present.

So I think it would be appropriate for HarfBuzz to override its category to Nukta.

**Comment by behdad** [comment]
Sounds good. Let's add a test as well.

**Comment by devosb** [comment]
I think the change happened somewhere between the 2.6.4 and 2.6.5 releases. While the update to Unicode 13 happened during that time, it was not [merged](https://github.com/harfbuzz/harfbuzz/commit/fd748fac41366166307fd67a083759465d03bd64) until after 2.6.5.

**Comment by behdad** [comment]
Thanks. No reason to bisect. Is clear why this is happening.

**Comment by devosb** [comment]
I am glad it is clear to you, as I could not find the offending commit. Which is why I deleted my last comment about where I thought the offending commit was.

**Comment by behdad** [comment]
> I am glad it is clear to you, as I could not find the offending commit. Which is why I deleted my last comment about where I thought the offending commit was.

Should be:
commit c15146448b534479de08b6aa8e6b1795221a2e1e
Merge: 069c5de9f 7a961692e
Author: Behdad Esfahbod <behdad@behdad.org>
Date:   Thu May 14 19:12:41 2020 -0700

    Merge pull request #2264 from harfbuzz/unicode-13
    
    Update to Unicode 13.0.0

**Comment by PeterCon** [comment]
I've just been made aware of this issue after a bug was reported on DWrite. I'm wondering about the shaping behaviour for overline when it follows the pre-base vowel sign U+0B47. The shaper re-orders the vowel sign before the base. Does categorization as nukta cause the overline to get re-ordered before the base along with vowel sign?

**Comment by dscorbett** [comment]
Yes, in HarfBuzz, the nukta reorders with the vowel sign.

**Comment by PeterConstable** [comment]
@dscorbett Makes sense. Thanks.
