### ISSUE TITLE
Too frequent unsafe-to-break flags output for Lucida?

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2860]
```
$ hb-shape --show-flags /System/Library/Fonts/LucidaGrande.ttc "test multiple words"
[t=0+766|e=1+1141#1|s=2+1044#1|t=3+766#1|space=4+648#1|m=5+1912#1|u=6+1271#1|l=7+592#1|t=8+766#1|i=9+592#1|p=10+1289#1|l=11+592#1|e=12+1141#1|space=13+648#1|w=14+1578#1|o=15+1258#1|r=16+838#1|d=17+1289#1|s=18+1044#1]
```

shows that for the Lucida system font on Mac there's surprisingly few safe-to-break positions, in this case only the first glyph, if I interpret the output correctly? That seems wrong - although I haven't looked at Lucida's AAT tables more closely.

Lucida does have a morx table, [table directory here](https://gist.github.com/drott/4caca4bf4a02823a86a63de3cd3ee63f).

@jfkthame @javifernandez @kojiishi

**Comment by behdad** [comment]
So.. the "unsafe-to-break" handling for AAT `morx` table is implemented this way: as we running a state-machine, every time we are not in state=0 (start-of-text), we deem as unsafe-to-break.

As it happens, the chain 8 in this face, which seems to be implementing Thai Sara-Am handling, spends all its time in state=2 for non-Thai text.

I checked the transitions from state=0 vs state=2 to see if they are deemed identical (and as such maybe we can detect), but they are not. I'm not sure if we can do anything in this case short of a full state-machine analysis implementation.

Ideas? @jfkthame 

@drott is this just affecting performance, or have you seen other adverse effects? How critical is "fixing" this to Chrome?

**Comment by drott** [comment]
I first thought this was essential for a fix for https://bugs.chromium.org/p/chromium/issues/detail?id=1173219 - but it looks like @javifernandez found a different solution. So the priority is now lower.

**Comment by drott** [comment]
Thanks for looking into the state machine behaviour of Lucida, that's what I was hoping to get further insight in. So do I understand correctly, that the font immediately tries to go to state 2 to attempt handling Thai Sara-Am, then stays in state=2 for the Latin sequence all the time? 
Indeed, at the moment, with @javifernandez fix, it looks like this only affects performance when it comes to determining the size of to-be-reshaped portion of text during line layout.

**Comment by behdad** [comment]
> the font immediately tries to go to state 2 to attempt handling Thai Sara-Am, then stays in state=2 for the Latin sequence all the time?

I think it's using state=2 to mean "not start of text". Goes there and stays there for all irrelevant glyphs, which includes all Latin.

Okay I actually found a better heuristic that happens to take care of Lucida. PR coming. Need to add test and it's good to go.

**Comment by drott** [comment]
Thank you very much for working on this, I did study the comments in the new heuristic. 

Building from `HEAD` at cf203936d7ba74dfb567a92378476c3125010023 unfortunately, I still get the remainder of the run being marked as unsafe to break - maybe I am doing something wrong?

```
$ build/util/hb-shape  --show-flags /System/Library/Fonts/LucidaGrande.ttc "test multiple words"
[t=0+766|e=1+1141#1|s=2+1044#1|t=3+766#1|space=4+648#1|m=5+1912#1|u=6+1271#1|l=7+592#1|t=8+766#1|i=9+592#1|p=10+1289#1|l=11+592#1|e=12+1141#1|space=13+648#1|w=14+1578#1|o=15+1258#1|r=16+838#1|d=17+1289#1|s=18+1044#1]
```

**Comment by behdad** [comment]
> Building from `HEAD` at [cf20393](https://github.com/harfbuzz/harfbuzz/commit/cf203936d7ba74dfb567a92378476c3125010023) unfortunately

You need to build the branch in https://github.com/harfbuzz/harfbuzz/pull/2871
That is, `aat-safe-to-break` branch at https://github.com/harfbuzz/harfbuzz/commit/77d6050fd81c4ec88aa7d544e83e5681cef83a0a

**Comment by drott** [comment]
Confirming this works now

```
$ build/util/hb-shape  --show-flags /System/Library/Fonts/LucidaGrande.ttc "test multiple words"
[t=0+766|e=1+1141|s=2+1044|t=3+766|space=4+648|m=5+1912|u=6+1271|l=7+592|t=8+766|i=9+592|p=10+1289|l=11+592|e=12+1141|space=13+648|w=14+1578|o=15+1258|r=16+838|d=17+1289|s=18+1044]
```

Indeed I had not realised this was on a branch, sorry for the confusion.

**Comment by jfkthame** [comment]
One thing I noticed in trying this (though not directly related to the change here) is that HB does not appear to set the unsafe-to-break flag when fallback positioning occurs. Should it do so? Or is the assumption that it is always implicitly unsafe-to-break within a cluster?

@behdad wdyt?

**Comment by behdad** [comment]
> that HB does not appear to set the unsafe-to-break flag when fallback positioning occurs. Should it do so?

I see in `hb-ot-shape-fallback.cc`:
```
static inline void
position_around_base (const hb_ot_shape_plan_t *plan,
                      hb_font_t *font,
                      hb_buffer_t  *buffer,
                      unsigned int base,
                      unsigned int end,
                      bool adjust_offsets_when_zeroing)
{
  hb_direction_t horiz_dir = HB_DIRECTION_INVALID;

  buffer->unsafe_to_break (base, end);
```

> Or is the assumption that it is always implicitly unsafe-to-break within a cluster?

Indeed that is the assumption. For multiple reasons:
1. We don't have a place to return flags affecting positions that are NOT a cluster boundary.
2. If it was safe-to-break inside a cluster, there's no reason the two sides should have been cluster-merged.

In the first implementation a cluster boundary was to be deemed unsafe-to-break if *any* glyph with that cluster value indicated unsafe-to-break. That was cumbersome to use, so I added a final pass to mark all glyphs of a cluster unsafe-to-break if any indicated so.

You can test by increasing cluster-level to 2. In fact, the buffer merge-clusters implementation starts this way:
```
void
hb_buffer_t::merge_clusters_impl (unsigned int start,
                                  unsigned int end)
{
  if (cluster_level == HB_BUFFER_CLUSTER_LEVEL_CHARACTERS)
  {
    unsafe_to_break (start, end);
    return;
  }
```

HTH
