### ISSUE TITLE
Odd rounding artifacts with variable font

### ISSUE THREAD

**Issue by justvanrossum** [harfbuzz/harfbuzz#2866]
The glyphs in the attached test font draw a rectangle, the top edge of which is a long string of aligned points. There are two variable axes; each one pulls up the top edge from one side into a trapezoid. If the axes have the same value, the top edge should once again be a straight line. There are several characters with different dimensions for the shape, but I ended up using "C".

With FreeType, this works reasonable well, although it is visible in the trapezoids that the final points are rounded to the unit grid.

However, using HB for outline extraction (via `hb_font_draw_glyph`), this results in weird rounding artifacts:
![test](https://user-images.githubusercontent.com/4246121/108065178-e7e8df80-705d-11eb-8688-50338ed7e89b.png)
Red: FreeType/Skia, Blue: HarfBuzz

Detail:
![image](https://user-images.githubusercontent.com/4246121/108066937-56c73800-7060-11eb-850a-9abe76f7682c.png)

It's as if the scaled deltas are rounded individually and then added, instead of having the end result rounded after adding:

`result = round(scalar1 * delta1) + round(scalar2 * delta2)`

vs.

`result = round(scalar1 * delta1 + scalar2 * delta2)`

I haven't started searching for the relevant source code yet, I first wanted to post my observation and (possibly wrong) theory of what goes wrong.

The attached archive contains the test font and a drawbot(-skia) test script that produces the above image.

(drawbot-skia is a skia-python-based cross platform 2D drawing lib using uharfbuzz. Install with `$ pip install drawbot-skia`, then run the script as `$ drawbot test_drawing.py test_image.pdf`)

[test_font+script.zip](https://github.com/harfbuzz/harfbuzz/files/5988611/test_font%2Bscript.zip)

(Using the DrawBot macOS app gives the same result, although the red outline then comes from the OS font machinery instead of FreeType.)

**Comment by justvanrossum** [comment]
I just read through `hb-ot-var-gvar-table.hh` and I see zero evidence supporting my theory above, so right now I have no clue as to what could be the cause of the observed behavior :(

**Comment by justvanrossum** [comment]
(I deleted a previous comment that said the opposite if this one.)

If I read `hb-ot-var-gvar-table.hh` correctly, it seems that indeed the deltas from each tuple are rounded individually before being added to the points array:
https://github.com/harfbuzz/harfbuzz/blob/7a60f4e3a407cdadedc3b723eb2f1d716e99cd72/src/hb-ot-var-gvar-table.hh#L652-L658

I think this rounding should either not happen at all (I would *love* to be able to retrieve interpolated outlines that have _not_ been rounded to the unit grid!), or it should happen to the `points` array *after* all deltas have been applied (after the do/while loop).

**Comment by behdad** [comment]
Thanks. Happy to merge a PR to fix.

Note that the draw API is experimental, exactly because the API and implementation have not been fully vetted to my desired quality.

**Comment by justvanrossum** [comment]
FWIW if I simply remove those `roundf` calls, I get the correct behavior, at least via the draw API

Despite the draw API using int coordinates, I can still get more precise outlines by setting the font's scale appropriately. Doing rounding in `apply_deltas_to_points` (either like the current situation, or after the do/while loop) would prohibit that.

I can't really judge whether not rounding at all here could have adverse effects elsewhere in HB.

Either way, I can provide a PR.

**Comment by justvanrossum** [comment]
@behdad, thanks! Let me know whether you think rounding can be omitted altogether here (that would be my preference).

**Comment by behdad** [comment]
Yes, completely remove any rounding.

The *only* rounding that should happen is when converting from the internal `float` representation to the API `hb_position_t`. Even that doesn't mean you cannot get more refined output. You just need to use larger values for `hb_font_set_scale`; for example, using 6 or 8 bits of "sub-pixel" precision.
