### ISSUE TITLE
[ci] Review CI for excessive buidls

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2867]
Seeing this msvc CI failure:
https://github.com/harfbuzz/harfbuzz/runs/1913399571

Apparently we're building all dependencies on every CI run. That means glib, cairo, fontconfig, everything. That's just wasteful and introduces false positive failures.

Is nice that meson *can* do that. But I don't think we should be doing it like that. Can't we use vcpkg or some other system to install dependencies?

**Comment by khaledhosny** [comment]
The other place where we do this as well is the `crossbuild-win32`  job, which runs on Debian.

**Comment by behdad** [comment]
@khaledhosny since you've been cleaning up failing bots, how are we doing these days?

**Comment by alerque** [comment]
Another thing to look at is caching the part of CI runs that isn't relevant to this code repo (i.e. caching all the external stuff that is built) and only rebuilding when different dependencies are called for. Caching tends to be easier to fit in most CI build matrixes than a package manager that installs specific (often old) versions.

Both ways can introduce false positives and their own frustrations, but caching definitely improves CI run times.

**Comment by khaledhosny** [comment]
Yes, caching is probably a simpler solution. We should probably look into using something like ccache for a less error-prone setup.

**Comment by behdad** [comment]
Let's close if no one is going to look into this.

**Comment by khaledhosny** [comment]
I think our build is currently fast enough. There are few bottlenecks (the oss-fuzz, the distcheck, etc.) but if the build is really broken the fast jobs will fail fast and it will be apparent quickly.

**Comment by behdad** [comment]
> I think our build is currently fast enough. There are few bottlenecks (the oss-fuzz, the distcheck, etc.) but if the build is really broken the fast jobs will fail fast and it will be apparent quickly.

I agree.
