### ISSUE TITLE
Let's prepare a release

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2901]
Last release is from last year. Let's roll one.

@khaledhosny is that something you can do please?

I don't think there's anything major, but we might as well call it 2.8.0, at least because we now shape most joined scripts (other than Arabic / Syriac) with USE.

Here's what I see:
```
- Shape joining scripts other than Arabic/Syriac using the Universal Shaping Engine.
  Previously these were shaped using the generalized Arabic shaper. (David Corbett)
- Fix regression in shaping of U+0B55 ORIYA SIGN OVERLINE. (David Corbett)
- Update language tags. (David Corbett)
- Variations: reduce error: do not round each interpolated delta. (Just van Rossum) 
- Documentation improvements. (Khaled Hosny, Nathan Willis)
- Subsetter improvements: subsets most, if not all, lookup types now. (Garret Rieger, Qunxin Liu)
- Fuzzer-found fixes and other improvements when memory failures happen. (behdad)
- Removed most atomic implementations now that we have C++11 atomic impl. (behdad)
- General codebase upkeep; using more C++11 features: constexpr constructors, etc. (behdad)
```

**Comment by behdad** [comment]
There's one or two other issues that I might fix today. But as good practice, I don't see any reason to hold a release.

**Comment by khaledhosny** [comment]
I can do it, let me know if you want to release it now or wait a bit for you to work on the issues you want to fix.

**Comment by behdad** [comment]
Thanks Khaled. Go ahead. There's always the next release. :) Thanks.

**Comment by alerque** [comment]
I'll be keeping an eye on CI just to make sure everything goes smoothly. Once the tag is pushed artifacts should build and attach automatically...but we haven't had a full shake down yet since I implemented that.

**Comment by khaledhosny** [comment]
Release was cut, and CI upload of release artifacts went smoothly.
