### ISSUE TITLE
Give crowbar more bite

### ISSUE THREAD

**Issue by davelab6** [harfbuzz/harfbuzz#2910]
https://typedrawers.com/discussion/comment/48949/#Comment_48949 :

> "Ah, yes, this is probably where I am trying to be too clever. Crowbar uses Harfbuzz to shape the text, and Harfbuzz (correctly) uses a list of features as part of selecting the lookups to execute in a stage. But once it's chosen the lookup IDs, it throws the feature information away. So Crowbar tries to look back into the feature-lookup mapping to try to understand why a lookup got called and where it came from, but if a lookup appears in more than one feature then I can see that it might guess wrong."

— @simoncozens 

I was discussing this with @rsheeter and he observed that HB could offer the correct answer up,  and whether that fits into HB nicely might be another question :)

@behdad wdyt?

**Comment by simoncozens** [comment]
Remember that Crowbar supports and reads the fontTools DEBG table, and so any font built with feature debugging turned on gets annotated with what feature, lookup name and source line/column the lookup came from.

**Comment by behdad** [comment]
It's not super straightforward; will think about it.

**Comment by behdad** [comment]
Tracking in https://github.com/harfbuzz/harfbuzz/pull/3495
