### ISSUE TITLE
propagate_attachment_offsets() can recurse unboundedly

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#2927]
If there's, say, 1000 glyphs attached on top of each other, either cursive or mark attachment, and if its done in a certain order (rtl or ltr), then propagate_attachment_offsets() will recurse 1000 deep. That's not good. I haven't found a neat solution yet :(, other than maybe doing a backward run first, with no recursion, then do the forward run like we do now but limit recursion depth to a reasonable and small number.

Ideas? @jfkthame @khaledhosny @drott

**Comment by khaledhosny** [comment]
I don't have any ideas, but I think we can put some limit here. Like a 100 glyphs is much more than enough.

**Comment by behdad** [comment]
@khaledhosny Can you add that please? 64 maybe.

**Comment by behdad** [comment]
Limited it to our stack nesting depth limit, which currently is at 64.
