### ISSUE TITLE
Applying single substitution to variation selectors

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#2940]
I’m trying to make many control characters visible in a font, and making use of #2886 I apply single substitution substituting the glyphs by themselves. This works for other control characters but not variation selectors. Replacing variation selector by a different glyph than its nominal one works.

I tried to debug the code went but all I found is that `accel.may_have()` returns `false` if VS glyph is replaced by itself, but `true` for other control characters. If VS glyph is replaced by another glyph, it will return `true` as well:
https://github.com/harfbuzz/harfbuzz/blob/4af5dacedc8d45c701c8a559962f1b071419ca50/src/hb-ot-layout.cc#L1784-L1790

Uniscribe and CoreText seem to apply the substitution, since they keep the VS glyph and don’t replace it with space.

Testing with [NoNameFixed-Regular.otf](https://github.com/alif-type/noname-fixed/blob/main/NoNameFixed-Regular.otf):

```
$ hb-shape NoNameFixed-Regular.otf -u FE00 -V
trace: start table GSUB	buffer: [uniFE00=0]
trace: start lookup 6	buffer: [uniFE00=0]
trace: end lookup 6	buffer: [uniFE00=0]
trace: start lookup 7	buffer: [uniFE00=0]
trace: end lookup 7	buffer: [uniFE00=0]
trace: start lookup 9	buffer: [uniFE00=0]
trace: end lookup 9	buffer: [uniFE00=0]
trace: start lookup 10	buffer: [uniFE00=0]
trace: end lookup 10	buffer: [uniFE00=0]
trace: end table GSUB	buffer: [uniFE00=0]
trace: start table GPOS	buffer: [uniFE00=0+525]
trace: start lookup 0	buffer: [uniFE00=0+525]
trace: end lookup 0	buffer: [uniFE00=0+525]
trace: end table GPOS	buffer: [uniFE00=0+525]
[space=0+0]
$ hb-shape NoNameFixed-Regular.otf -u FE00 --shaper=coretext
[uniFE00=0+525]
$ hb-shape.exe NoNameFixed-Regular.otf -u FE00 --shaper=uniscribe
[uniFE00=0+525]
```

**Comment by khaledhosny** [comment]
Stupid me, I was not actually replacing the VS and was mislead by CoreText and Uniscribe keeping it anyway!

**Comment by behdad** [comment]
> I apply single substitution substituting the glyphs by themselves.

That's clever!
