### ISSUE TITLE
Include C headers with their C++ names : fail building with android ndk-21d

### ISSUE THREAD

**Issue by 1bsyl** [harfbuzz/harfbuzz#2944]
I have some trouble to build 2.8.0 with android ndk-r21d, whereas the previous version used was fine (2.3.1)

because of this commit : 
Include C headers with their C++ names
https://github.com/harfbuzz/harfbuzz/commit/7cb22ba7ebf6ef053790a3201cb7014bacd51e46

(have to revert it this way: https://github.com/libsdl-org/SDL_ttf/commit/f903900e8040a55486e8d59580db14002ea6e55f )

**Comment by 1bsyl** [comment]
```
[armeabi-v7a] Compile++ arm  : harfbuzz <= hb-aat-layout.cc
In file included from jni/SDL_ttf_git/external/harfbuzz-2.8.0/src/hb-aat-layout.cc:28:
jni/SDL_ttf/external/harfbuzz-2.8.0/src/hb.hh:182:10: fatal error: 'cassert' file not found
#include <cassert>
```

**Comment by behdad** [comment]
This is ugly. Which broken toolchains to accommodate :)).

Happy to add an option for including C names. Best if it can be automatically activated...

**Comment by 1bsyl** [comment]
Actually, I haven't tested,
 but the android ndk, has an option to use the STL. (which I don't use for building harfbuzz).
and the cassert and others, are there (ndk-21d)

```
./sources/cxx-stl/system/include/cassert
./sources/cxx-stl/llvm-libc++/include/cassert
./toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/cassert
./toolchains/llvm/prebuilt/linux-x86_64/include/c++/4.9.x/cassert
```

But STL, on ndk, is complicated ... https://developer.android.com/ndk/guides/cpp-support 
_You can specify c++_shared, c++static, none, or system using the APP_STL variable in your Application.mk file. For example:_

I'd rather not to pull the stl runtime simply to find the headers ...

**Comment by behdad** [comment]
Interesting. Thanks.

That's actually very relevant to something else we want to do: to switch to using STL headers but still try hard to avoid the runtime.

**Comment by behdad** [comment]
Try with the 'system'? Also let us know if we can automate that in any way.

I'm interested in using operator new / delete, and that seems to be exactly what the 'system' option there provides.

**Comment by behdad** [comment]
cc @garretrieger re STL header-only use.

**Comment by 1bsyl** [comment]
Yes, adding `APP_STL := system` in Application.mk gets it compiled ..

https://developer.android.com/ndk/guides/cpp-support
`new and delete. (Deprecated in r18.)`
And 'system' should be removed https://github.com/android/ndk/issues/744

**Comment by behdad** [comment]
I see.

**Comment by behdad** [comment]
We're moving towards requiring more of C++, eventually linking to std lib as well. As such, closing.
