### ISSUE TITLE
Canonical FindHarfBuzz.cmake?

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#2966]
Is there a canonical FindHarfBuzz.cmake file for inclusion in CMake-based build systems (FreeType!) and that has all them features? Maybe https://github.com/WebKit/WebKit/blob/main/Source/cmake/FindHarfBuzz.cmake?

**Comment by khaledhosny** [comment]
No idea, and I doubt anyone here knows. The recommended way for finding installed HarfBuzz is by using pkg-config.

**Comment by behdad** [comment]
Anything actionable here?

**Comment by khaledhosny** [comment]
No. We don’t provide a FindHarfBuzz.cmake file and we don’t know how to write one.

**Comment by behdad** [comment]
Okay. Anyone contributing one can open a PR. :)
