### ISSUE TITLE
#Harfbuzz version too old(1.2.4) despite having an updated one

### ISSUE THREAD

**Issue by ShafSpecs** [harfbuzz/harfbuzz#2971]
I get this error a lot and it's currently driving me nuts:
**(mongodb-compass:18855): Pango-ERROR **: 00:15:18.658: Harfbuzz version too old (1.4.2)**
This was the latest I had when trying to install mongo, happened with other packages too. I tried uninstalling then reinstalling, didn't work. I use Linux Ubuntu 20.04 LTS 64-bit. I thought it was a mongodb problem until I saw issues with several packages and several people complained of the same issue. Any help will be appreciated :).

**Comment by khaledhosny** [comment]
https://www.google.com/search?q=Harfbuzz+version+too+old

**Comment by behdad** [comment]
This happens with apps that use pango as a shared library, but also ship with their own static harfbuzz. Linux linker does not have a sane way to support that configuration I'm afraid.
