### ISSUE TITLE
ot functions position glyphs incorrectly with DFKai-SB font in TTB direction

### ISSUE THREAD

**Issue by marklh9** [harfbuzz/harfbuzz#2974]
We're revisiting how LibreOffice position TTB glyphs.

harfbuzz position glyphs incorrectly incorrectly with Windows built-in Chinese truetype font DFKai-SB font in TTB direction.
Characters U+300c and U+ff0c shift up too far. Characters U+3010, U+ff5b, U+3008, U+300e,U+300a have the similar problem.

With hb-shape with --font-funcs=ot and --font-funcs=ft, we can find there are big difference.

$ ./hb-shape -O text --shapers=ot,fallback --direction ttb --font-funcs=ot ../kaiu.ttf "「風調，雨順」"
[gid554=0@-512,-308+0,-1024|gid2405=1@-512,-973+0,-1024|gid4947=2@-512,-973+0,-1024|gid500=3@-512,-440+0,-1024|gid2008=4@-512,-973+0,-1
024|gid3817=5@-512,-973+0,-1024|gid555=6@-512,-652+0,-1024]

$ ./hb-shape -O text --shapers=ot,fallback --direction ttb --font-funcs=ft ../kaiu.ttf "「風調，雨順」"
[gid554=0@-512,-652+0,-1024|gid2405=1@-512,-804+0,-1024|gid4947=2@-512,-782+0,-1024|gid500=3@-512,-822+0,-1024|gid2008=4@-512,-778+0,-1
024|gid3817=5@-512,-783+0,-1024|gid555=6@-512,-992+0,-1024]

<img width="355" alt="output-side-by-side" src="https://user-images.githubusercontent.com/17537417/117303351-2f3d7a00-aeaf-11eb-8131-0ea1aae91336.png">

I didn't notice any features if viewing the font from font forge.
I hope if I can get some advice about this.

**Comment by behdad** [comment]
Fix in https://github.com/harfbuzz/harfbuzz/pull/3497

**Comment by marklh9** [comment]
@behdad @khaledhosny 

Fullwidth punctuations in the test case are now correct (verified with 4.1.0 ),
but the text ( glyph 1, 2, 4, 5 ) shift downward comparing to funcfuncs=ft.
( They are not highlighted with red boxes in the image ). 
Should I open another issue for that?

**Comment by behdad** [comment]
> Should I open another issue for that?

Yes please.
