### ISSUE TITLE
Chromium build failures with 89df3539966d7d544b49495a667ccebf94bb045c

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#2979]
Chromium build complains about

```
template <template<typename> template Var>
HB_INTERNAL void PaintTransform<Var>::closurev1 (hb_colrv1_closure_context_t* c) const
{
```

being a C++ 17 extension and can be fixed by changing `template Var` to `class Var`.

in `hb-subset-plan.cc` `_remap_indexes` is now used outside of `#ifndef HB_NO_SUBSET_LAYOUT`. 

Will submit a PR.

**Comment by drott** [comment]
CC @qxliu76

**Comment by qxliu76** [comment]
> CC @qxliu76 @garretrieger

thanks for your fix!
