### ISSUE TITLE
Omission in hello-harfbuzz example

### ISSUE THREAD

**Issue by ldo** [harfbuzz/harfbuzz#298]
In your hello-harfbuzz example, after loading a FreeType face with `FT_New_Face`, you need to call `FT_Set_Char_Size` to set a font size (e.g. set it to 1.0 with a resolution of 72). Otherwise it looks like the default font size is 0, and your glyph_positions all come out as 0, or the `hb_shape()` call fails with a floating-point exception.

**Comment by khaledhosny** [comment]
Do you mean http://behdad.github.io/harfbuzz/hello-harfbuzz.html?
cc @simoncozens

**Comment by ldo** [comment]
You have the source [right here in your tree](https://github.com/behdad/harfbuzz/blob/master/docs/usermanual-hello-harfbuzz.xml).

**Comment by simoncozens** [comment]
I will work on this.

**Comment by behdad** [comment]
@simoncozens can you take care of this?
