### ISSUE TITLE
multiple definition of `operator delete(void*)

### ISSUE THREAD

**Issue by msink** [harfbuzz/harfbuzz#2996]
Seems that static linking is broken, at least for `msys2-mingw` and `clang++`:
```
clang++ command returned non-zero exit code: 1.
output:
ld: f:\msys64\mingw64\lib\libharfbuzz.a(hb-directwrite.cc.obj):(.text+0x140): multiple definition of `operator delete(void*)'; f:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\9.2.0\libstdc++.a(del_op.o):(.text$_ZdlPv+0x0): first defined here
```

Any workarounds?

**Comment by behdad** [comment]
We should remove this block:
https://github.com/harfbuzz/harfbuzz/blob/243d056ff1c2af583ceb67e5dfbfaac51dc96e63/src/hb-directwrite.cc#L53-L60

and figure out how to do without it. We should just call malloc/free as we do, and use placement new/delete for construction/destruction.

cc @ebraminio

**Comment by msink** [comment]
Or maybe move that block to separate source file is sufficient.

**Comment by behdad** [comment]
In the meantime try marking those as static. Or just remove. I think we should just remove.

Also note that the directwrite backend is experimental and for testing only, and not needed for normal operation of the library.

**Comment by msink** [comment]
Well, I did not compile it from sources, MSYS2 is a binary distribution.
But on the other hand - for me there is no rush, if in the next release it will be removed or at least moved to a separate compilation unit (so static linker will drop it) - ok for me.

**Comment by behdad** [comment]
Moving to separate compilation unit doesn't make sense since these operator implementations are wrong and unnecessary to begin with.

**Comment by behdad** [comment]
@khaledhosny is this something you can clean up quick? I can't build hb-directwrite. Thanks.

**Comment by khaledhosny** [comment]
OK, so just remove them? I don’t think we should be concerned about people who override `malloc`/`free` when it comes to testing-only shapers.

**Comment by behdad** [comment]
> OK, so just remove them?

That's a good start.

> I don’t think we should be concerned about people who override `malloc`/`free` when it comes to testing-only shapers.

If you feel like, also change all uses of `new` / `delete` in that file to `malloc` / `free` like other shapers (eg. `hb-uniscribe`) do.  There's no reason to syntactically use `new` / `delete` in this file. Is not like we allocate and DWrite frees or vice versa.

**Comment by ebraminio** [comment]
Great that you've resolved this, new/delete was needed for vtable/vptr initiation of objects dwrite IIRC, I think their redefinition was also in attempt to avoid linking to stdc++ or something like that also but that specific check was later removed from build featuring hb-directwrite.
