### ISSUE TITLE
ZWNJ does not break ligature

### ISSUE THREAD

**Issue by projekter** [harfbuzz/harfbuzz#3000]
I run into a very curious case - which may be is a font issue, but probably it is HarfBuzz related.
The zero width non-joiner is supposed to prevent a ligature at the given position. However, I found that regardless of my attempts, the `ff` ligature (for example) was not split into separate characters when I inserted the ZWNJ in between. Then, I found out that when I switched my test font from `StixTwoText` to other fonts, it worked exactly as expected. But should a font be able to prevent this ZWNJ behavior at all?

Some test cases. First, using the harfbuzz API directly. My buffer is filled with `f<ZWNJ>f ff`, and the output of `hb_buffer_serialize_unicode` is:
```JSON
[{"u":102,"cl":0},{"u":8204,"cl":1},{"u":102,"cl":2},{"u":32,"cl":3},{"u":102,"cl":4},{"u":102,"cl":5}]
```

Shaping gives the following glyphs (output of `hb_buffer_serialize_glyphs`):
```JSON
[{"g":"f._f","cl":0,"dx":0,"dy":0,"ax":696,"ay":0},{"g":"space","cl":1,"dx":0,"dy":0,"ax":0,"ay":0},{"g":"f","cl":2,"dx":0,"dy":0,"ax":822,"ay":0},
 {"g":"space","cl":3,"dx":0,"dy":0,"ax":541,"ay":0},
 {"g":"f._f","cl":4,"dx":0,"dy":0,"ax":696,"ay":0},{"g":"f","cl":5,"dx":0,"dy":0,"ax":707,"ay":0}]
```
Both times, the `_f` glyph is used, which gives the ligature. Compare this to when I explicitly disable ligatures by setting the `liga` feature to zero:
```JSON
[{"g":"f","cl":0,"dx":0,"dy":0,"ax":707,"ay":0},{"g":"space","cl":1,"dx":0,"dy":0,"ax":0,"ay":0},{"g":"f","cl":2,"dx":0,"dy":0,"ax":822,"ay":0},
 {"g":"space","cl":3,"dx":0,"dy":0,"ax":541,"ay":0},
 {"g":"f","cl":4,"dx":0,"dy":0,"ax":707,"ay":0},{"g":"f","cl":5,"dx":0,"dy":0,"ax":707,"ay":0}]
```

To see whether I did something wrong with my buffers and API calls, I tried the same thing in LuaLaTeX (everything updated today):
```TeX
\documentclass{article}

\usepackage{fontspec}
\setmainfont{STIXTwoText-Regular.otf}[Renderer=HarfBuzz]

\begin{document}
   f\symbol{"0200C}f ff
\end{document}
```
If I use the `Renderer=HarfBuzz` option, both times the ligature is present. If I use TeX's default engine, the first ligature is split properly.

**Comment by khaledhosny** [comment]
STIX Two Text implements its `ff` “ligature” as contextual substitution, and ZWNJ seems to be skipped there:
```
$ hb-shape STIXTwoText-Regular.otf -u 66,200C,66,20,66,66
[f._f=0+302|space=1+0|f=2+357|space=3+235|f._f=4+302|f=5+307]

$ hb-shape Amiri-Regular.otf -u 66,200C,66,20,66,66
[f=0+300|space=1+0|f=2+300|space=3+292|f_f=4+546]
```

**Comment by behdad** [comment]
Right. We have no way of detecting that kind of "ligation".

**Comment by behdad** [comment]
cc @jfkthame

**Comment by KrasnayaPloshchad** [comment]
So is it possible to make ZWNJ able to prevent such contextual substitutions

**Comment by behdad** [comment]
> So is it possible to make ZWNJ to be aware during such contextual substitutions?

No.
