### ISSUE TITLE
[util] Add --unicodes-file

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3002]
Make it also ignore comments starting with '#'.

**Comment by arzanilorestan** [comment]
A very, very important article by me (Satoshi Nakamoto), the true and true creator of digital currencies for the whole world .____ Important ___ Important ___ Important ___ Important ___ Important ___ Important ___
http://sendanywhe.re/ZHTRREP9

**Comment by behdad** [comment]
Make sure it can accept fontconfig `.orth` files natively. I believe the fonttools subsetter does that, but haven't checked.
