### ISSUE TITLE
Korean font composition problem on Linux (works fine on Windows)

### ISSUE THREAD

**Issue by lukehutch** [harfbuzz/harfbuzz#3003]
See example here -- I pulled the problematic phrases from a larger document:

https://docs.google.com/document/d/1iQdm7CUohzYfIGWcwB_DbvSZIRHGgMZ4G_ZHkLfRJBs/edit?usp=sharing

**Screenshot from Chrome on Linux (which uses HarfBuzz for shaping):** (problems are marked in red)

![image](https://user-images.githubusercontent.com/811305/120845765-78c0c980-c52e-11eb-91d4-2a71e454d4fe.png)

**Screenshot from Windows:** (the red words all render correctly)

![image](https://user-images.githubusercontent.com/811305/120845725-6cd50780-c52e-11eb-90cb-aa119b52be9f.png)

Curiously, all the problematic cases happen in words after an initial syllable of 가.

Pasting the text here into the GitHub editor shows most of the issues in the screenshot have resolved, but one sentence exhibits an even longer run of the same problem, so it's not just a Google Docs issue:

> 해킹 당한 주요 이메일계정을 통해 비밀번호 재설정을 하여 피해자의 다른 계정들도 해킹 가능
> 
> 가끔, 해커는 타깃의 소셜미디어 네트워크, 직업 및 가족, 등에 관한 정보를 사전에 면밀히 조사한 후 진행
> 
> 통상적으로, 해커는 타깃이 믿을 수 있는 사람들의 프로파일을 이용하여 소셜미디어상에서 가짜 프로파일을 만듬
> 
> 중국 여행시, 가상 네트워크 (VPN)을 사용하여 본인의 인터넷 활동을 외부의 감시로부터 보호 
> 
> ProtonVPN의 경우 무료 사용도 가능
> 
> 한국 거주 100% 안전하다 가정하면 안돼: 북한 간첩 및 추종세력은 전 세계에서 활동
> 
> 스피어 피싱 조심하기 (악성 링크 또는 파일, 가짜 사이트)

**Screenshot of this in Chrome on Linux: (notice that the problematic paragraph, the entire second paragraph, still starts with 가, and everything else renders correctly)**

![image](https://user-images.githubusercontent.com/811305/120846186-000e3d00-c52f-11eb-9a8c-29a978d99d97.png)

This is probably an NFD vs. NFC issue -- but I have no idea why the IME of the user who created this document would have used NFD for the rest of a word after typing 가, and NFC for everything else.

**Comment by khaledhosny** [comment]
Most certainly these are font issues, you need to find the font(s) used in each problematic case (Firefox dev tools can show this, not sure about Chrome) and test them with hb-view.

**Comment by lukehutch** [comment]
@khaledhosny I looked at this, but (1) even in the "Computed" tab, multiple font families are listed, and I don't know which one is being selected by font fallback (Edge's developer tools can tell you the actual display font, but only on Windows, where there is no issue displaying these paragraphs); and (2) many fonts don't include CJK glyphs, but I have no idea how to determine which fonts are being used for glyph fallback -- it could be a font that is not even listed in the CSS properties.

**Comment by behdad** [comment]
In Chrome's inspector, Computed tab, at the very bottom there's "Rendered Fonts". Just select the broken parts and see what font they are rendered in.

**Comment by arzanilorestan** [comment]
A very, very important article by me (Satoshi Nakamoto), the true and true
creator of digital currencies for the whole world .____ Important ___
Important ___ Important ___ Important ___ Important ___ Important ___
http://sendanywhe.re/ZHTRREP9

در تاریخ شنبه ۵ ژوئن ۲۰۲۱،‏ ۱:۲۶ Behdad Esfahbod ***@***.***>
نوشت:

**Comment by lukehutch** [comment]
Ah, I couldn't see "Rendered Fonts" in Google Slides when I selected the font elements, but it does show up for text here in GitHub.

For the working paragraphs:

> Noto Sans CJK JP—Local file(46 glyphs)
> Liberation Sans—Local file(13 glyphs)

And for the broken paragraph (가끔, ...)

> Droid Sans Fallback—Local file(99 glyphs)
> Liberation Sans—Local file(18 glyphs)

**Comment by arzanilorestan** [comment]
در تاریخ شنبه ۵ ژوئن ۲۰۲۱،‏ ۱:۳۵ Luke Hutchison ***@***.***>
نوشت:

**Comment by lukehutch** [comment]
I can confirm that Droid Sans Fallback also shows the issue in oowriter on Linux:

![image](https://user-images.githubusercontent.com/811305/120862637-83875880-c546-11eb-9158-d8a7fd94c9b4.png)

But Droid Sans is fine:

![image](https://user-images.githubusercontent.com/811305/120862693-98fc8280-c546-11eb-80ea-bdf95bc3959c.png)

Can you please confirm whether Droid Sans Fallback font is itself the problem, and it's not a problem with how HarfBuzz is parsing the font shaping information? Here is the font:

[DroidSansFallbackFull.zip](https://github.com/harfbuzz/harfbuzz/files/6601251/DroidSansFallbackFull.zip)

**Comment by arzanilorestan** [comment]
A very, very important article by me (Satoshi Nakamoto), the true and true creator of digital currencies for the whole world .____ Important ___ Important ___ Important ___ Important ___ Important ___ Important ___
http://sendanywhe.re/ZHTRREP9

**Comment by arzanilorestan** [comment]
Yes, it works. A very, very important article by me (Satoshi Nakamoto), the
true and true creator of digital currencies for the whole world .____
Important ___ Important ___ Important ___ Important ___ Important ___
Important ___
http://sendanywhe.re/ZHTRREP9

در تاریخ شنبه ۵ ژوئن ۲۰۲۱،‏ ۱:۴۱ Luke Hutchison ***@***.***>
نوشت:

**Comment by khaledhosny** [comment]
Droid Sans Fallback is a known broken font for Hangul, see #2400.

**Comment by lukehutch** [comment]
Yes, that looks like the problem. Thank you for directing me to the correct issue!

**Comment by invisibleroads** [comment]
As a workaround, you can disable google-droid-sans-fonts altogether.

Adding the following configuration to `~/.config/fontconfig/fonts.conf` fixed the issue in Fedora 42:

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <rejectfont>
    <glob>/usr/share/fonts/google-droid-sans-fonts/*</glob>
  </rejectfont>
</fontconfig>
```

Thanks to https://802.11ac.net/2022/06/10/fedora-korean-font/ for the tip.
