### ISSUE TITLE
Drop codecov CI check?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3004]
It does not seem anyone is paying attention to the reported fails, they are pretty much ignored (no one is adding extra tests to make it happy), so I don't see what is the point of having the check if passing it is not enforced (at least when it is reasonable).

**Comment by behdad** [comment]
Agree. Let me see if I can configure it differently.

**Comment by behdad** [comment]
Looks like we can. Trying to figure out now.
https://docs.codecov.io/docs/codecovyml-reference
