### ISSUE TITLE
GPOS does not apply only in some fonts

### ISSUE THREAD

**Issue by kojiishi** [harfbuzz/harfbuzz#3008]
I'm not entirely sure whether this is an issue of uharfbuzz or not, but I can't figure it out after some days of investigations. Appreciate any feedback in advance.

I'm porting my Python program from `hb-shape` to `uharfbuzz`. This is so much faster and looks great, thank you for the work. But I've found one different behavior I could not figure out why. The difference occurs:
* Only in two fonts on Mac; 'ヒラギノ丸ゴ ProN W4.ttc' and 'ヒラギノ明朝 ProN.ttc'. I tested other Japanese fonts on Mac, Noto CJK, and some CJK fonts on Windows. So far only these two fonts hit this issue.
* `hb-shape` works fine for these two fonts.

The [test code at gist](https://gist.github.com/kojiishi/1c6b2f616a88d251b2f749102a51ae1b). Here's an sample output of the failure:
```
start table GSUB
start lookup 2
end lookup 2
start lookup 4
end lookup 4
start lookup 7
end lookup 7
start lookup 8
end lookup 8
start lookup 16
end lookup 16
start lookup 19
end lookup 19
end table GSUB
start subtable 0
end subtable 0
gid781=0@1000,0+0
hb-shape '--font-file=fonts/g/mac/10.15.7/Hiragino Mincho ProN.ttc' --trace '--text=１' --features=palt
trace: start lookup 2   buffer: [gid781=0]
trace: end lookup 2     buffer: [gid781=0]
trace: start lookup 4   buffer: [gid781=0]
trace: end lookup 4     buffer: [gid781=0]
trace: start lookup 7   buffer: [gid781=0]
trace: end lookup 7     buffer: [gid781=0]
trace: start lookup 8   buffer: [gid781=0]
trace: end lookup 8     buffer: [gid781=0]
trace: start lookup 16  buffer: [gid781=0]
trace: end lookup 16    buffer: [gid781=0]
trace: start lookup 19  buffer: [gid781=0]
trace: end lookup 19    buffer: [gid781=0]
trace: start lookup 1   buffer: [gid781=0+1000]
trace: end lookup 1     buffer: [gid781=0+1000]
trace: start lookup 2   buffer: [gid781=0+1000]
trace: end lookup 2     buffer: [gid781=0@-106,0+783]
[gid781=0@-106,0+783]
```
The advance is 783 when using `hb-shape`, but 1000 when using `uharfbuzz`. The output of other fonts is:
```
start table GSUB
start lookup 2
end lookup 2
start lookup 4
end lookup 4
start lookup 7
end lookup 7
start lookup 8
end lookup 8
start lookup 16
end lookup 16
start lookup 19
end lookup 19
end table GSUB
start table GPOS
start lookup 1
end lookup 1
start lookup 2
end lookup 2
end table GPOS
gid781=0@830,-87+0
hb-shape '--font-file=fonts/g/mac/10.15.7/Hiragino Kaku Gothic W4.ttc' --trace '--text=１' --features=palt
trace: start lookup 2   buffer: [gid781=0]
trace: end lookup 2     buffer: [gid781=0]
trace: start lookup 4   buffer: [gid781=0]
trace: end lookup 4     buffer: [gid781=0]
trace: start lookup 7   buffer: [gid781=0]
trace: end lookup 7     buffer: [gid781=0]
trace: start lookup 8   buffer: [gid781=0]
trace: end lookup 8     buffer: [gid781=0]
trace: start lookup 16  buffer: [gid781=0]
trace: end lookup 16    buffer: [gid781=0]
trace: start lookup 19  buffer: [gid781=0]
trace: end lookup 19    buffer: [gid781=0]
trace: start lookup 1   buffer: [gid781=0+1000]
trace: end lookup 1     buffer: [gid781=0+1000]
trace: start lookup 2   buffer: [gid781=0+1000]
trace: end lookup 2     buffer: [gid781=0@-87,0+830]
[gid781=0@-87,0+830]
```
The advances match, and I can see `start table GPOS` and `end table GPOS`, while for the two failing fonts, I can only see `start subtable 0` and `end subtable 0`.

I checked the `_harfbuzz.pyx` and tried to set as many properties as possible but I could not make this work. Any advices are greatly appreciated in advance.

Note, these font files on my Mac `/System/Library/Fonts` have Japanese file names. I'm not sure if it is so for everyone, but renamed to ASCII in the sample code above.

**Comment by khaledhosny** [comment]
> The `coretext` shaper gives the same output:

Actually no:
```
$ ./util/hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt"
[gid781=0+1000]
$ ./util/hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt" --shaper=coretext
[gid781=0@-78,0+841]
```

**Comment by kojiishi** [comment]
Thanks @khaledhosny, I built harfbuzz locally and confirmed that too. It is obvious that this is not a `uharfbuzz` issue, sorry about that.

Should I close this and open a new issue in harfbuzz?

**Comment by kojiishi** [comment]
Bisected, applying GPOS features works fine with uharfbuzz 0.9.1 (harfbuzz 2.6.4), but not with uharfbuzz 0.10.0 (harfbuzz 2.6.5).
https://github.com/harfbuzz/uharfbuzz/releases?after=v0.11.0

**Comment by behdad** [comment]
> The font has a `kerx` table, and that is probably why GPOS is not being applied:

Right. That's where I was heading with my analysis but the output didn't support either.

**Comment by behdad** [comment]
Any conclusion so far?

**Comment by behdad** [comment]
> $ ./util/hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt"
> [gid781=0+1000]
> $ ./util/hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt" --shaper=coretext
> [gid781=0@-78,0+841]

I can reproduce this as well. Without `palt` CoreText gets our result too. So, looks like our mapping of `palt` to `morx` selectors might be wrong?

This is how we currently have it set up:
```
  {HB_TAG ('p','a','l','t'), HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING,            HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT,          (hb_aat_layout_feature_selector_t) 7},
``
and
```
  HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING                       = 22,

  /* Selectors for #HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING */
  HB_AAT_LAYOUT_FEATURE_SELECTOR_PROPORTIONAL_TEXT              = 0,
  HB_AAT_LAYOUT_FEATURE_SELECTOR_MONOSPACED_TEXT                = 1,
  HB_AAT_LAYOUT_FEATURE_SELECTOR_HALF_WIDTH_TEXT                = 2,
  HB_AAT_LAYOUT_FEATURE_SELECTOR_THIRD_WIDTH_TEXT               = 3,
  HB_AAT_LAYOUT_FEATURE_SELECTOR_QUARTER_WIDTH_TEXT             = 4,
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_PROPORTIONAL_TEXT          = 5,
  HB_AAT_LAYOUT_FEATURE_SELECTOR_ALT_HALF_WIDTH_TEXT            = 6,
```

.... (20 mins later)

lol. This *isn't* a `morx` font. :))) We're failing `palt` in good ol' `GSUB`. Will continue / resume debugging later.

**Comment by behdad** [comment]
Ooh. I bet this is script detection fail.

**Comment by behdad** [comment]
> Ooh. I bet this is script detection fail.

Nope.

**Comment by behdad** [comment]
Err. My bad. morx/GSUB is irrelevant. `kerx` is the issue. Digging.

**Comment by behdad** [comment]
> `kerx` is the issue. Digging.

Which... fonttools doesn't support. Ugh.

**Comment by behdad** [comment]
Okay so the font has both `kerx` and `GPOS` tables.

Maybe what CoreText is doing is this:
If `GSUB` was applied, prefer `GPOS` over `kerx`.
If `morx` was applied, prefer `kerx` over `GPOS`.

@nedley any insight you can offer? Thanks.

**Comment by nedley** [comment]
That sounds right.

**Comment by behdad** [comment]
Thanks. I also removed the GSUB table from the font and observed CoreText seemingly pick up the `kerx` instead.

**Comment by behdad** [comment]
Should be fixed.

> $ ./util/hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt"
> [gid781=0@-78,0+842]
> $ ./util/hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt" --shaper=coretext
> [gid781=0@-78,0+841]

I've checked the font. The `ot` shaper result is correct according to the font tables. We're losing one unit in the coretext shaper float roundings I suppose.

**Comment by kojiishi** [comment]
Thank you @behdad!!
