### ISSUE TITLE
[subset] API (and ABI) stability of subset

### ISSUE THREAD

**Issue by mapreri** [harfbuzz/harfbuzz#3012]
Hi,

scribus has started (with version 1.5.7) to optionally link to hb-subset if available.

While packaging that in Debian, I've been told that hb-subset is not publicly available because back in 2018 it was marked as "API still subject to changes" (and I suppose ABI too, which from my POV is more important than the API in this case).

See https://bugs.debian.org/988781

Could I ask what's the status of hb-subset and if it can be considered API/ABI stable like the rest of harfbuzz?

**Comment by behdad** [comment]
Thanks. @garretrieger let's sit down and do a review of the `hb-subset` API, create roadmap to stablization. I can do that tomorrow if we start early.

@mapreri thanks for the report. I'm interested to hear more about the scribus experience.

**Comment by mapreri** [comment]
> @mapreri thanks for the report. I'm interested to hear more about the scribus experience.

I asked and these is what I got:

> for now we had no issue with harfbuzz-subset API stability
> other distros such as OpenSuse are already packaging it
> fox now we are using harfbuzz-subset only for CID keyed fonts
> so mostly asian fonts

**Comment by garretrieger** [comment]
Alright me and Behdad worked out a plan of what we want to change before making the API stable:
- hb_subset(...) the input should be a const.
- Add set inversion to allow for efficiently specifying all things in a set. Drop the retain all features method.
- Expose set/get user data methods.
- name lang id's should work with hb_lang_t's instead of a set.
- For boolean properties use an enum instead of a method for each property.
- Add a pass thru tables set.

**Comment by garretrieger** [comment]
@qxliu76 FYI

**Comment by garretrieger** [comment]
For the boolean properties, here's a proposed signature:

enum hb_subset_input_property_t {
  ...
};

void hb_subset_input_set_property (hb_subset_input_property_t property, bool value);
bool hb_subset_input_get_property (hb_subset_input_property_t property);

**Comment by behdad** [comment]
> For the boolean properties, here's a proposed signature:

alternatively suggesting: `set_bool`/`get_bool`.

**Comment by behdad** [comment]
> hb_subset_input_property_t

Would this naming be confusing as well? Since we only want to do it for boolean properties, not everything.

**Comment by khaledhosny** [comment]
Any thing else to be tracked here?

**Comment by behdad** [comment]
> Maybe just a final check the .so to make sure exposed symbols are all good and intended, and proper release notes.

And maybe autoconf/meson options to disable building it?

**Comment by behdad** [comment]
Closing, since the API is stable now, and we're tracking the release in https://github.com/harfbuzz/harfbuzz/issues/3078#issue-953422024
