### ISSUE TITLE
Add a `--unicode-ranges` runtime flag to hb-subset

### ISSUE THREAD

**Issue by Pomax** [harfbuzz/harfbuzz#3038]
Right now the only way to run `hd-subset` is by providing a _text_ that font will be used to style, but this isn't super great for huge fonts like CJK sources. It would be super useful if there was also a `--unicode-ranges` runtime flag that could be given one or more ranges (e.g. `hb-subset --unicode-ranges 0-100,520-1280,10000,10009 giant-font.otf`) to yield one font per range (e.g. `giant-font-0-100.otf, giant-font-520-1280.otf, etc..)

**Comment by anthrotype** [comment]
in the fonttools subsetter, which hb-subset is supposed to mimic, that option is called `--unicodes` (and `--unicodes-file` to parse from a text file) and takes comma/whitespace-separated hex digits or ranges of such (separated with hyphen). E.g. `–unicodes=41-5a,61-7a` adds ASCII letters

**Comment by jfkthame** [comment]
However, I don't think it's expected that the subsetting tool will produce *multiple* separate subset fonts when given several disjoint unicode ranges. E.g. if hb-subset (or fonttools) is used to generate an ASCII-letters-only subset, using `--unicodes=41-5a,61-7a`, the expectation is that it will generate a *single* subset font that includes both the upper- and lowercase ranges, and not that it will generate two separate subset fonts.

More generally, when preparing a CJK font for web use, it's likely to be better to group characters into sub-fonts according to patterns of usage, not simply split according to unicode ranges. For example, check https://fonts.googleapis.com/css2?family=Noto+Sans+SC to see how Google Fonts splits up a CJK font for webfont use; it is most emphatically *not* "one subset per Unicode range that's wanted in the overall result".

**Comment by Pomax** [comment]
that's a fair point.

**Comment by rsheeter** [comment]
For context, https://www.unicodeconference.org/presentations-42/S5T3-Sheeter.pdf gives an overview of how the ranges we use were selected.

**Comment by behdad** [comment]
Currently `--unicodes` docs on `hb-subset` say:
```
  -u, --unicodes=list of hex numbers                                  Set input Unicode codepoints
```
ie. it doesn't support ranges. Which is not surprising since it's sharing implementation with `hb-shape`.

We shouldd implement ranges for `hb-subset --unicodes`; and also add `--unicodes-file` (issue https://github.com/harfbuzz/harfbuzz/issues/3002).

**Comment by behdad** [comment]
Tracking ranges in https://github.com/harfbuzz/harfbuzz/issues/3109
