### ISSUE TITLE
kern table not applied when GPOS missing kern feature

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#3043]
Given a font with both `kern` table and `GPOS` table missing `kern` feature, `hb-shape` does not appear to apply `kern` table. Such a setup is seen in old TrueType fonts, like TimesNewRomanPSMT version 5.01 bundled in Windows Vista (can’t upload here for IP reason). In such a case [OT spec](https://docs.microsoft.com/en-us/typography/opentype/spec/recom) recommends applying kern table:
>When a 'kern' table and GPOS table are both present in a font, and an OpenType Layout engine is requested to apply kerning to a run of text of a particular script and language system: (a) If the number of 'kern' feature lookups in the resolved language system in the GPOS table is zero, then the 'kern' table should be applied, followed by any remaining GPOS features requested.

Actually I am seeing this code preparing for it  in `hb_ot_shape_planner_t::compile` (setting `apply_kern` to true when `apply_gpos` being true and `has_gpos_kern` being false): 
https://github.com/harfbuzz/harfbuzz/blob/0da9158f620077ec46dcdfa4c1556253b23337eb/src/hb-ot-shape.cc#L163-L174

but `hb_ot_shape_plan_t::position` does not apply `kern` after `GPOS` because of chain of if-elses.
https://github.com/harfbuzz/harfbuzz/blob/0da9158f620077ec46dcdfa4c1556253b23337eb/src/hb-ot-shape.cc#L267-L282

**Comment by Stubie7** [comment]
I came across this same issue only a couple of hours ago, but with version 1.100 of Open Sans. The current version of Open Sans, 1.101, from https://fonts.google.com/specimen/Open+Sans doesn't appear to have any kerning at all! 1.100 is available elsewhere though. If the TTF is ~200KB, it's likely 1.100. If it's ~100KB, it's likely 1.101.

I tried something like this:

```diff
diff --git a/src/hb-ot-shape.hh b/src/hb-ot-shape.hh
index acc9877..6313533 100644
--- a/src/hb-ot-shape.hh
+++ b/src/hb-ot-shape.hh
@@ -100,6 +100,7 @@ struct hb_ot_shape_plan_t
   static constexpr bool has_frac = false;
 #endif
   bool has_vert : 1;
+  bool has_gpos_kern : 1;
   bool has_gpos_mark : 1;
   bool zero_marks : 1;
   bool fallback_glyph_classes : 1;
diff --git a/src/hb-ot-shape.cc b/src/hb-ot-shape.cc
index 86ab0b4..4da650c 100644
--- a/src/hb-ot-shape.cc
+++ b/src/hb-ot-shape.cc
@@ -126,7 +126,7 @@ hb_ot_shape_planner_t::compile (hb_ot_shape_plan_t           &plan,
   plan.requested_tracking = !!plan.trak_mask;
 #endif
 
-  bool has_gpos_kern = plan.map.get_feature_index (1, kern_tag) != HB_OT_LAYOUT_NO_FEATURE_INDEX;
+  plan.has_gpos_kern = plan.map.get_feature_index (1, kern_tag) != HB_OT_LAYOUT_NO_FEATURE_INDEX;
   bool disable_gpos = plan.shaper->gpos_tag &&
 		      plan.shaper->gpos_tag != plan.map.chosen_script[1];
 
@@ -158,7 +158,7 @@ hb_ot_shape_planner_t::compile (hb_ot_shape_plan_t           &plan,
   else if (!apply_morx && !disable_gpos && hb_ot_layout_has_positioning (face))
     plan.apply_gpos = true;
 
-  if (!plan.apply_kerx && (!has_gpos_kern || !plan.apply_gpos))
+  if (!plan.apply_kerx && (!plan.has_gpos_kern || !plan.apply_gpos))
   {
     /* Apparently Apple applies kerx if GPOS kern was not applied. */
 #ifndef HB_NO_AAT_SHAPE
@@ -262,16 +262,22 @@ hb_ot_shape_plan_t::position (hb_font_t   *font,
 {
   if (this->apply_gpos)
     map.position (this, font, buffer);
+
+  if (!this->apply_gpos || !this->has_gpos_kern)
+  {
+    if (0)
+      ;
 #ifndef HB_NO_AAT_SHAPE
-  else if (this->apply_kerx)
-    hb_aat_layout_position (this, font, buffer);
+    else if (this->apply_kerx)
+      hb_aat_layout_position (this, font, buffer);
 #endif
 #ifndef HB_NO_OT_KERN
-  else if (this->apply_kern)
-    hb_ot_layout_kern (this, font, buffer);
+    else if (this->apply_kern)
+      hb_ot_layout_kern (this, font, buffer);
 #endif
-  else
-    _hb_ot_shape_fallback_kern (this, font, buffer);
+    else
+      _hb_ot_shape_fallback_kern (this, font, buffer);
+  }
 
 #ifndef HB_NO_AAT_SHAPE
   if (this->apply_trak)
```

which worked for this particular font/case, but I've no idea what else it might cause. I wasn't sure if `map.position()` should still even be called.

**Comment by behdad** [comment]
> I wasn't sure if `map.position()` should still even be called.

It should; there are features other than kern / mark.

**Comment by behdad** [comment]
I pushed a simpler fix (and a test) out. Please test.

**Comment by blueshade7** [comment]
works, thanks

**Comment by Stubie7** [comment]
> It should; there are features other than kern / mark.

I assumed as much, which is why I'd left it still doing that. Your fix works for me too. Thanks.
