### ISSUE TITLE
When defined custom allocator functions, hb-ft.cc file fails to compile

### ISSUE THREAD

**Issue by muratmat** [harfbuzz/harfbuzz#3044]
When compiling Harfbuzz (as a static library) specifying custom allocator functions (e.g. compiler flags **-D**hb_calloc_impl=svgHarfbuzzCalloc **-D**hb_free_impl=svgHarfbuzzFree **-D**hb_malloc_impl=svgHarfbuzzMalloc **-D**hb_realloc_impl=svgHarfbuzzRealloc), the file hb-ft.cc does not compile, generating the following errors:

```
Building CXX object CMakeFiles/harfbuzz.dir/harfbuzz/src/hb-ft.cc.o
<command-line>: error: 'svgHarfbuzzCalloc' has not been declared in 'std'
<command-line>: error: 'svgHarfbuzzFree' has not been declared in 'std'
<command-line>: error: 'svgHarfbuzzMalloc' has not been declared in 'std'
<command-line>: error: 'svgHarfbuzzRealloc' has not been declared in 'std'
```

The full compiler define macros are the following:

```
-DHAVE_FREETYPE
-DHB_LEAN
-DHB_NO_MT
-DHB_OPTIMIZE_SIZE
-DNDEBUG
-D__OPTIMIZE_SIZE__
-Dhb_calloc_impl=svgHarfbuzzCalloc
-Dhb_free_impl=svgHarfbuzzFree
-Dhb_malloc_impl=svgHarfbuzzMalloc
-Dhb_realloc_impl=svgHarfbuzzRealloc
```

Many thanks in advance!

**Comment by behdad** [comment]
Looks like something wrong with how you have declared those symbols; not something we can help with.

How have you defined those?

**Comment by muratmat** [comment]
I simplified the compile code that reproduces the issue.

This works (I used hb-buffer.cc as example, because it uses malloc/realloc/calloc):

`g++ -DHAVE_FREETYPE -DHB_LEAN -DHB_NO_MT -DNDEBUG -Dhb_calloc_impl=myCalloc -Dhb_free_impl=myFree -Dhb_malloc_impl=myMalloc -Dhb_realloc_impl=myRealloc -I./harfbuzz/src -I./freetype/include -fno-exceptions -fno-rtti -fPIC -fvisibility=hidden -fno-threadsafe-statics -std=gnu++11 -o hb-buffer.cc.o -c ./harfbuzz/src/hb-buffer.cc`

This rises the issue (hb-ft.cc):

`
g++ -DHAVE_FREETYPE -DHB_LEAN -DHB_NO_MT -DNDEBUG -Dhb_calloc_impl=myCalloc -Dhb_free_impl=myFree -Dhb_malloc_impl=myMalloc -Dhb_realloc_impl=myRealloc -I./harfbuzz/src -I./freetype/include -fno-exceptions -fno-rtti -fPIC -fvisibility=hidden -fno-threadsafe-statics -std=gnu++11 -o hb-ft.o -c ./harfbuzz/src/hb-ft.cc
`
```
<command-line>: error: 'myCalloc' has not been declared in 'std'
<command-line>: error: 'myFree' has not been declared in 'std'
<command-line>: error: 'myMalloc' has not been declared in 'std'
<command-line>: error: 'myRealloc' has not been declared in 'std'
```

The compiled hb-buffer.cc.o correctly shows the dependency of external myCalloc/myFree/myRealloc
```
nm hb-buffer.cc.o
...
U myCalloc
U myFree
U myRealloc
...
```

Many thanks for your help.

**Comment by behdad** [comment]
Succeeds for me:
```
$ g++ -DHAVE_FREETYPE -DHB_LEAN -DHB_NO_MT -DNDEBUG -Dhb_calloc_impl=myCalloc -Dhb_free_impl=myFree -Dhb_malloc_impl=myMalloc -Dhb_realloc_impl=myRealloc -I./harfbuzz/src -I./freetype2/include -fno-exceptions -fno-rtti -fPIC -fvisibility=hidden -fno-threadsafe-statics -std=gnu++11 -o hb-buffer.cc.o -c ./harfbuzz/src/hb-ft.cc
```

my g++ is Apple clang though. What version of g++? Can you get a raw processed output and minimize it in godbolt?

It feels like some header being pulled in by hb-ft (and by extension, by FreeType), is inadequate in that it's leaving the std namespace open? That's my feeling.

**Comment by muratmat** [comment]
Debian-testing, x86_64, gcc 10.2.1
I confirm that the Freetype headers imported by hb-ft.h (<ft2build.h> and FT_FREETYPE_H) are the problem.
I tried to modify the initial part of hb-ft.cc, from the official one:

```
#include "hb.hh"
#ifdef HAVE_FREETYPE
#include "hb-ft.h"
...
```

to a patched one:

```
#ifdef HAVE_FREETYPE
#include "hb-ft.h"
#include "hb.hh"
```

and it seems to solve the issue. It seems that hb-ft.h (and so Freetype headers) should be included before hb.hh
Anyway I wish in a better understanding at your side (thanks for your hard work!) and so a quick official patch/fix.

Many thanks in advance.

PS: on the same Debian system, mingw64 compiler (gcc 10.2.1 for Windows) do not show the problem, as also happens for your Apple Clang system.

**Comment by muratmat** [comment]
Performed some additional testing, here are the cross-compilers that fail (with the "myM/C/Realloc has not been declared in 'std'" error).

```
gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
gcc-mipsel-linux-gnu g++-mipsel-linux-gnu
gcc-mips64el-linux-gnuabi64 g++-mips64el-linux-gnuabi64
gcc-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu
gcc-i686-linux-gnu g++-i686-linux-gnu
```

Instead, `mingw-w64` (GCC 10.2.1 for Windows cross compilation), `Android NDK R21e` (i.e. Clang 9.0.9), `Apple Clang 12` (iOS and MacOS X, Xcode 12), all work fine.

**Comment by behdad** [comment]
Thanks. It's probably an issue with the GNU C they all share.

We have a rule in HarfBuzz to always (transitively) include `hb.hh` before any other header. That is to ensure we configure everything right that might affect how system headers behave. For that reason, moving `hb-ft.h` before `hb.hh` is something I like to avoid.

Can you produce a preprocessed version (`-E`) and either look for culprits in it, or attach it zipped here? If it's too large, feel free to email to me.

Thanks again.

**Comment by muratmat** [comment]
[harfbuzz_custom_alloc_test.zip](https://github.com/harfbuzz/harfbuzz/files/6783026/harfbuzz_custom_alloc_test.zip)

I simplified the test code (see attachment), by writing a minimal `hb-ft-test.cc` file that reproduces the issue.
Then i preprocessed it (`-E`):

```
g++ -DHAVE_FREETYPE -DHB_LEAN -DHB_NO_MT -DNDEBUG -Dhb_calloc_impl=myCalloc -Dhb_free_impl=myFree -Dhb_malloc_impl=myMalloc -Dhb_realloc_impl=myRealloc -I./harfbuzz/src -I./freetype/include -fno-exceptions -fno-rtti -fPIC -fvisibility=hidden -fno-threadsafe-statics -std=gnu++11 -E -o hb-ft-test-preprocessed.cc -c ./harfbuzz/src/hb-ft-test.cc
```

and you can see the result in attacched `hb-ft-test-preprocessed.cc`
I have to be honest, even looking at the result it is not very clear to me the origin of the problem... (BTW, I tried to compile the preprocessed file, and the issue is there too of course :) )

For your convenience, I attach also include files and directories of my GCC 10 installation.
[system_includes.zip](https://github.com/harfbuzz/harfbuzz/files/6783121/system_includes.zip)

Many thanks for your help.

**Comment by behdad** [comment]
> and you can see the result in attacched `hb-ft-test-preprocessed.cc`

Trying to compile that at least I get some useful error from clang:
```
In file included from ./harfbuzz/src/hb-ft-test.cc:7:
In file included from ./freetype/include/freetype/freetype.h:24:
In file included from ./freetype/include/freetype/config/ftconfig.h:42:
In file included from ./freetype/include/freetype/config/ftstdlib.h:120:
/usr/include/c++/10/stdlib.h:73:7: error: no member named 'myRealloc' in namespace 'std'; did you mean '::myRealloc'?
using std::
      ^~~~~
./harfbuzz/src/hb.hh:224:18: note: '::myRealloc' declared here
extern "C" void* myRealloc(void *ptr, size_t size);
                 ^
```

**Comment by behdad** [comment]
Ooh!!!

That line in `stdlib.h` reads:
```
using std::realloc;
```

which would now read:
```
using std::myRealloc;
```

Okay. Let me think about this...

**Comment by behdad** [comment]
I suggest we internally switch from `malloc/realloc/free` to `hb_malloc/hb_realloc/hb_free` such that our macros don't collapse with system headers.

**Comment by behdad** [comment]
Is much easier than imagined, fortunately.

**Comment by behdad** [comment]
Should be fixed in main. Let me know if it works for you. We're hoping for a release soon.
https://github.com/harfbuzz/harfbuzz/issues/3048
