### ISSUE TITLE
[subset] Missing TrueType table after subsetting NotoSerifMyanmar-Regular.otf

### ISSUE THREAD

**Issue by joycode** [harfbuzz/harfbuzz#3058]
[NotoSerifMyanmar-Regular.otf.zip](https://github.com/harfbuzz/harfbuzz/files/6805845/NotoSerifMyanmar-Regular.otf.zip)

OS: Debian Buster
Compiler: g++ (Debian 8.3.0-6) 8.3.0
harfbuzz version: 63e15eac4f443fa53565d1e4fb9611cdd7814f28 (HEAD -> main, tag: 2.8.2, origin/main, origin/HEAD)
test command: ./hb-subset NotoSerifMyanmar-Regular.otf "႒" -o subset-myanmar.ttf

"႒" is a glyph from NotoSerifMyanmar-Regular.otf, it's Glyph Name is "two_shn", Unicode Value is U+1092

Output file "subset-myanmar.ttf" seems a invalid TrueType file, when open with FontForge, it warns "subset-myanmar.ttf is not in a known format", and fails to open it. I also tried to open the file with FreeType library, it fails in tt_face_lookup_table(), which returns NULL.

**Comment by behdad** [comment]
Works fine for me.

**Comment by behdad** [comment]
Ah, you are right. FreeType doesn't like to open it.

**Comment by behdad** [comment]
@garretrieger any idea why `CFF ` table is dropped?

**Comment by behdad** [comment]
@joycode where did you get that font file? We've tracked down the issue and have a fix, but in my understanding the font is wrong for having a `FontName` op in `TopDict`. So I'm wondering what compiler built that font. Thanks.

cc @blueshade7 @anthrotype

**Comment by joycode** [comment]
@behdad Thanks for your fixing, It's a font from AOSP: https://android.googlesource.com/platform/external/noto-fonts/+/refs/heads/master/other/NotoSerifMyanmar-Regular.otf

**Comment by anthrotype** [comment]
I'm also curious to know how those .otf files were built.
ufo2ft (used by fontmake) never adds a `FontName` op to a CFF TopDict (see it's `setupTable_CFF` method [here](https://github.com/googlefonts/ufo2ft/blob/86c3357aa535d3eec73f8440435838c112eae639/Lib/ufo2ft/outlineCompiler.py#L1213-L1372)).
If I am not mistaken, the `FontName` op is specific to CID-keyed fonts and we always output name-keyed CFF fonts.
That NotoSerifMyanmar-Regular.otf is not a CID font (has no `FDArray`)...

Maybe @marekjez86 knows?

**Comment by behdad** [comment]
> ufo2ft (used by fontmake) never adds a `FontName` op to a CFF TopDict (see it's `setupTable_CFF` method [here](https://github.com/googlefonts/ufo2ft/blob/86c3357aa535d3eec73f8440435838c112eae639/Lib/ufo2ft/outlineCompiler.py#L1213-L1372)).

Right. I couldn't find it either.

> If I am not mistaken, the `FontName` op is specific to CID-keyed fonts and we always output name-keyed CFF fonts.

That's also my understanding of the spec and hence my surprise.

**Comment by behdad** [comment]
I just built NotoSansMyanmar from noto-source with fontmake main and I don't see `FontName`.

I'm guessing that the version in AOSP was delivered by Monotype perhaps? Marek might know indeed.

**Comment by behdad** [comment]
> I'm guessing that the version in AOSP was delivered by Monotype perhaps? Marek might know indeed.

I cloned that repo. The file in question was added in 2018 by Marek:
```
commit c39af9b6c874e97aacfff5e7035d4c58536c3365
Author: Marek Jeziorek <marekj@google.com>
Date:   Fri May 4 15:00:53 2018 -0400

    Add Medium weight OTF to 8 existing scripts.
    
    Bug: 77973710
    
    Note that to match the script style/design I also added Regular, Bold
    in OTF from the same delivery/build which resulted in addition of 46 OTF
    font files while deleting 32 TTF files.
    
    Scripts affected: Armenian, Bengali, Devanagari, Georgian, Malayalam,
    Myanmar, Sinhala, Tamil
    
    Arabic, Hebrew, Lao and Thai were NOT modified because:
    - Arabic UI font is not ready
    - Hebrew, Lao and Thai might cause user feedback as "too modern"
    
    The following sheet relates changes in this CL to the Android language
    priorities
    https://docs.google.com/spreadsheets/d/1QdmqwbthLDg13OzTLeLvqxRDyMVhpwZbbQdTLi8U1HE/edit?usp=sharing
    
    Two additional TTF deletions NotoSerifKhmer-Bold.ttf and
    NotoSerifKhmer-Regular.ttf were done as a cleanup ("garbage
    collection" of unused font files). They shouldn't be counted
    as a reduction in image size (they weren't in the text of this description).
    
    This CL is accompanied by
    I4c599c7c1305278392a0527ed0de601fc5586468 for
    changes in fonts.xml .
...
```

**Comment by behdad** [comment]
Ah, ufo2ft:
```
commit 40dec091431c771ba47c41ac2534c0a0b4909fce
Merge: ed1c038 4d38dac
Author: Cosimo Lupo <cosimo@anthrotype.com>
Date:   Fri Mar 16 08:29:41 2018 +0000

    Merge pull request #234 from anthrotype/cid-fontname
    
    [outlineCompiler] don't set CID-only FontName operator in CFF TopDict

```

**Comment by behdad** [comment]
Here's the fonts currently in AOSP that have the bad operation (which probably is all OTFs there):
```
      <FontName value="NotoSansAhom-Regular"/>
      <FontName value="NotoSansAnatolianHieroglyphs-Regular"/>
      <FontName value="NotoSansArmenian-Bold"/>
      <FontName value="NotoSansArmenian-Medium"/>
      <FontName value="NotoSansArmenian-Regular"/>
      <FontName value="NotoSansBassaVah-Regular"/>
      <FontName value="NotoSansBengali-Bold"/>
      <FontName value="NotoSansBengali-Medium"/>
      <FontName value="NotoSansBengali-Regular"/>
      <FontName value="NotoSansBengaliUI-Bold"/>
      <FontName value="NotoSansBengaliUI-Medium"/>
      <FontName value="NotoSansBengaliUI-Regular"/>
      <FontName value="NotoSansBhaiksuki-Regular"/>
      <FontName value="NotoSansDevanagari-Bold"/>
      <FontName value="NotoSansDevanagari-Medium"/>
      <FontName value="NotoSansDevanagari-Regular"/>
      <FontName value="NotoSansDevanagariUI-Bold"/>
      <FontName value="NotoSansDevanagariUI-Medium"/>
      <FontName value="NotoSansDevanagariUI-Regular"/>
      <FontName value="NotoSansElbasan-Regular"/>
      <FontName value="NotoSansHatran-Regular"/>
      <FontName value="NotoSansLinearA-Regular"/>
      <FontName value="NotoSansMalayalam-Bold"/>
      <FontName value="NotoSansMalayalam-Medium"/>
      <FontName value="NotoSansMalayalam-Regular"/>
      <FontName value="NotoSansMalayalamUI-Bold"/>
      <FontName value="NotoSansMalayalamUI-Medium"/>
      <FontName value="NotoSansMalayalamUI-Regular"/>
      <FontName value="NotoSansManichaean-Regular"/>
      <FontName value="NotoSansMarchen-Regular"/>
      <FontName value="NotoSansMeroitic-Regular"/>
      <FontName value="NotoSansMiao-Regular"/>
      <FontName value="NotoSansMro-Regular"/>
      <FontName value="NotoSansMultani-Regular"/>
      <FontName value="NotoSansMyanmar-Bold"/>
      <FontName value="NotoSansMyanmar-Medium"/>
      <FontName value="NotoSansMyanmar-Regular"/>
      <FontName value="NotoSansMyanmarUI-Bold"/>
      <FontName value="NotoSansMyanmarUI-Medium"/>
      <FontName value="NotoSansMyanmarUI-Regular"/>
      <FontName value="NotoSansNabataean-Regular"/>
      <FontName value="NotoSansNewa-Regular"/>
      <FontName value="NotoSansOldNorthArabian-Regular"/>
      <FontName value="NotoSansOldPermic-Regular"/>
      <FontName value="NotoSansPahawhHmong-Regular"/>
      <FontName value="NotoSansPalmyrene-Regular"/>
      <FontName value="NotoSansPauCinHau-Regular"/>
      <FontName value="NotoSansSharada-Regular"/>
      <FontName value="NotoSansSinhala-Bold"/>
      <FontName value="NotoSansSinhala-Medium"/>
      <FontName value="NotoSansSinhala-Regular"/>
      <FontName value="NotoSansSinhalaUI-Bold"/>
      <FontName value="NotoSansSinhalaUI-Medium"/>
      <FontName value="NotoSansSinhalaUI-Regular"/>
      <FontName value="NotoSansSoraSompeng-Regular"/>
      <FontName value="NotoSansTamil-Bold"/>
      <FontName value="NotoSansTamil-Medium"/>
      <FontName value="NotoSansTamil-Regular"/>
      <FontName value="NotoSansTamilUI-Bold"/>
      <FontName value="NotoSansTamilUI-Medium"/>
      <FontName value="NotoSansTamilUI-Regular"/>
      <FontName value="NotoSerifArmenian-Bold"/>
      <FontName value="NotoSerifArmenian-Regular"/>
      <FontName value="NotoSerifEthiopic-Bold"/>
      <FontName value="NotoSerifEthiopic-Regular"/>
      <FontName value="NotoSerifGurmukhi-Bold"/>
      <FontName value="NotoSerifGurmukhi-Regular"/>
      <FontName value="NotoSerifKhmer-Bold"/>
      <FontName value="NotoSerifKhmer-Regular"/>
      <FontName value="NotoSerifMyanmar-Bold"/>
      <FontName value="NotoSerifMyanmar-Regular"/>
      <FontName value="NotoSerifMyanmar-Regular"/>
      <FontName value="NotoSerifSinhala-Bold"/>
      <FontName value="NotoSerifSinhala-Regular"/>
      <FontName value="NotoSerifTamil-Bold"/>
      <FontName value="NotoSerifTamil-Regular"/>
```

**Comment by anthrotype** [comment]
@behdad you're right, I had forgotten about https://github.com/googlefonts/ufo2ft/pull/234 - thanks for digging that up

**Comment by behdad** [comment]
Still would be great if @marekjez86 / @davelab6 can make sure Android updates the fonts to ones without illegal operator.

**Comment by marekjez86** [comment]
@behdad : do we  need to rebuild all fonts to get the fonts without illegal operator?

**Comment by behdad** [comment]
> do we need to rebuild all fonts to get the fonts without illegal operator? I'm assuming the issue is in all of the currently published OTF fonts (but I could be wrong). Please advise

Correct. Issue only involves OTFs, not TTF. But if rebuilding, you may as well rebuild all.

The pipeline was fixed in March 2018. However, AOSP still has fonts built before that.
