### ISSUE TITLE
No glyphs detected using hb_face_get_glyph_count()

### ISSUE THREAD

**Issue by mealdy** [harfbuzz/harfbuzz#3065]
By using the hb_face_get_glyph_count function to detect some font files, but it always returned 0. When I tried to outline some glyphs and I got empty data.  These fonts can be opened in most programs such as Font Book, and can be parsed by most js libraries such as fontkitjs, opentype.js, Typr.js, etc.

[font_files_attached](https://drive.google.com/file/d/1tk2h0IYsLRKZicDNVa4vl0aHIEaAlKXs/view)

**Comment by behdad** [comment]
Please attach a zip of one of the fonts. The link requires access.

**Comment by mealdy** [comment]
[fonts_harfbuzz_test.zip](https://github.com/harfbuzz/harfbuzz/files/6864152/fonts_harfbuzz_test.zip)

**Comment by behdad** [comment]
I can reproduce. Debugging.

**Comment by behdad** [comment]
The fonts have wrong (unsorted) table entries. I pushed a fix to handle them.
