### ISSUE TITLE
Arabic ligature diacritic mis-positioning

### ISSUE THREAD

**Issue by aaronbell** [harfbuzz/harfbuzz#3069]
I'm trying to understand an observed behavior in the new Cascadia Code Arabic font. 

Here is a sequence used for the `lam_lam_heh-ar` ligature, with a couple of diacritics added:
`uni0644` `uni064E` `uni0644` `uni064F` `uni0647`

The output of such is:
<img width="160" alt="Screen Shot 2021-07-23 at 7 17 50 PM" src="https://user-images.githubusercontent.com/8460297/126854763-a442de9b-3ba1-4564-b05c-786f078cb5d8.png">

With the sequence (LTR, for convenience):
`lam_lam_hehar` `uni064E` `uni064F` `LIG`
(The LIG is an empty glyph added to maintain alignment with the monospace grid)

However, the output should look like:
<img width="136" alt="Screen Shot 2021-07-23 at 7 20 41 PM" src="https://user-images.githubusercontent.com/8460297/126854834-28fe6dc4-27d6-4065-99bf-9b5b9183b91e.png">

I can achieve this output by removing the substitution that adds the `LIG` character:
`sub [lam_lam_heh-ar allah-ar] @vocal damma-ar'      by damma-ar LIG;`

As far as I can tell, the OT mark to ligature feature in the font is working as expected, and this is purely on the rendering engine side (macOS renders it correctly). It appears that the presence of the `LIG` character is changing how Harfbuzz analyzes the mark positioning and thus is causing the mark next to the `LIG` to be incorrectly positioned. 

While I have a workaround (shift the position of the `LIG` to before the ligature), I was wondering if you could help clarify what is causing this behavior. 

Thanks!

For convenience, here is the latest version of the font:
[CascadiaCode.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/6871784/CascadiaCode.ttf.zip)

**Comment by khaledhosny** [comment]
My hunch would be that splitting the `damma-ar` glyph is causing HarfBuzz to miscalculate what component it applies to.

**Comment by behdad** [comment]
This was done intentionally to match Uniscribe. I can't find the commit right now. But basically there was a case demonstrated by one of the popular MS fonts, whereas if first eg. A,B ligated into AB, and then that AB ligated with a C into ABC, then a mark attached to second component of that ABC expected to be positioned on C, NOT B. That is, the AB would be considered one ligature component after the ABC was formed.

What would our Uniscribe backend do?

**Comment by khaledhosny** [comment]
That would be 7b84c536c10ab90ed96a033d88e9ad232d46c5b8.

```
$ hb-view CascadiaCode.ttf -u 0644,064E,0644,064F,0647
```
![h](https://user-images.githubusercontent.com/93914/127048229-c64d700c-6070-40ce-bfa1-3e1fcc040ac5.png)

```
hb-view.exe CascadiaCode.ttf -u 0644,064E,0644,064F,0647 --shaper=uniscribe
```
![u](https://user-images.githubusercontent.com/93914/127048407-7ee04b0a-bbbd-49d6-9d74-a67298af3a0b.png)

```
hb-view CascadiaCode.ttf -u 0644,064E,0644,064F,0647 --shaper=coretext
```
![c](https://user-images.githubusercontent.com/93914/127048471-039fbf94-4776-42cd-9ab9-ce53f7e9a01d.png)

**Comment by behdad** [comment]
> That would be [7b84c53](https://github.com/harfbuzz/harfbuzz/commit/7b84c536c10ab90ed96a033d88e9ad232d46c5b8).

No not that one. Let me try harder to find.

**Comment by behdad** [comment]
> No not that one. Let me try harder to find.

commit fe20c0f84f5ff518dc471bf22ac5a83ef079eb69
https://bugzilla.gnome.org/show_bug.cgi?id=437633

**Comment by behdad** [comment]
Thinking more, this is supposed to work. Debugging.

**Comment by behdad** [comment]
Okay so when you do a MultipleSubst on a mark, we are not retaining its ligature-component properties I suppose. Let me try.

**Comment by behdad** [comment]
Should be fixed.
