### ISSUE TITLE
Amalgam builds are broken when both DirectWrite and Uniscribe are enabled

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3070]
Both files define structs with similar names since #3034. Need to move that code to a shared place and templatize it after all.

**Comment by behdad** [comment]
You can rename them to be unique for now.

I would do it but I can't build the directwrite code.

[15mins later]

I checked the code. I believe the DWrite structs were designed to be byte-compatible with the uniscribe ones. So I believe we can use non-templatized shared code. Just need to define two structs and have static asserts that their sizes match the uniscribe / dwrite one, and use those.

- Unify `OPENTYPE_FEATURE_RECORD` and `DWRITE_FONT_FEATURE` into `hb_ms_feature_t`.
- Unify `TEXTRANGE_PROPERTIES` and `DWRITE_TYPOGRAPHIC_FEATURES` into `hb_ms_features_t`.
