### ISSUE TITLE
[subset] Consider adding a bulk flag setting method to the subset api

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#3086]
Now that we're using enum's to for flag setting we should add a variant of the flag setting method that allows multiple flags to be set in a single call. I'm thinking something like this:

hb_subset_input_set_flags(HB_SUBSET_FLAG_HINTING, HB_SUBSET_FLAG_RETAIN_GIDS)

or to clear flags:

hb_subset_input_clear_flags(HB_SUBSET_FLAG_HINTING, HB_SUBSET_FLAG_RETAIN_GIDS)

using variadic arguments to accept multiple flags.

**Comment by behdad** [comment]
I don't like variadic API..

I'm leaning towards:
```
hb_subset_input_set_flags (*input, hb_subset_flag_t mask, hb_subset_flag_t value);
``

but that makes me realize that these flags are not bit-flags. Maybe we *should* make them bitflags, rename `flag_t` to `flags_t` to match other similar API.
