### ISSUE TITLE
Make high-level color information available

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3101]
It would be nice to have apis that answer the questions:

- Does this font/face have any color glyphs ?
- Does this font/face have only color glyphs ?
- Does this glyph have color ?

**Comment by matthiasclasen** [comment]
Small inconveniences in the current api, noticed in passing: hb_ot_color_glyph_reference_png and 
hb_ot_color_glyph_reference_svg will return and empty blob instead of NULL, if the font has any pngs/svgs. 

It would be useful if the docs made it clear that one has to check for

```
blob != NULL && blob->length > 0
```

**Comment by behdad** [comment]
> will return and empty blob instead of NULL

That's indeed unfortunate...

Another issue is that Apple has started using a format other than PNG recently. So our old API is already obsolete. We might add one using mime types.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/issues/1413

**Comment by behdad** [comment]
> It would be useful if the docs made it clear that one has to check for
> 
> ```
> blob != NULL && blob->length > 0
> ```

Better check (and one that I do in hb-view in https://github.com/harfbuzz/harfbuzz/pull/3411) is to compare != to `hb_blob_get_empty()`).

**Comment by behdad** [comment]
> * Does this font/face have any color glyphs ?

That question currently is answered based on what kind of color information you are ready to consume. In https://github.com/harfbuzz/harfbuzz/pull/3411 I have, for example:
```
static inline bool
helper_cairo_user_scaled_font_has_color (cairo_scaled_font_t *scaled_font)
{
  /* Ignoring SVG for now, since we cannot render it. */
  hb_font_t *font = (hb_font_t *) (cairo_font_face_get_user_data (cairo_scaled_font_get_font_face (scaled_font),
                                                                  &_hb_font_cairo_user_data_key));
 
 hb_face_t *face = hb_font_get_face (font);
  return hb_ot_color_has_png (face) || hb_ot_color_has_layers (face);
}
```

> * Does this font/face have only color glyphs ?

That's not something we can ever answer.

> * Does this glyph have color ?

That also, one has to try all the different ways. In that same branch I first try `hb_ot_color_glyph_reference_png()`, then `hb_ot_color_glyph_get_layers()`.

**Comment by matthiasclasen** [comment]
Probably not worth keeping this open
