### ISSUE TITLE
Code and comments don't match in Khmer

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#3104]
Comments:

https://github.com/harfbuzz/harfbuzz/blob/47d47e8c43d71c6d6570d354400c0757940bbb94/src/hb-ot-shape-complex-khmer.cc#L43-L46

Code:

https://github.com/harfbuzz/harfbuzz/blob/47d47e8c43d71c6d6570d354400c0757940bbb94/src/hb-ot-shape-complex-khmer.cc#L112-L116

Notice no pause ("one at a time") between application.

**Comment by behdad** [comment]
Right. Khmer shaper was duplicated from Indic. Fixing comment. Thanks.
