### ISSUE TITLE
Vertical typographic features

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#3113]
Harfbuzz currently applies `vert` when the direction is vertical instead of the horizontal typographic positioning and shaping features:

https://github.com/harfbuzz/harfbuzz/blob/f25daa4794f22f7e0eaddb77ef7b47c8c6584453/src/hb-ot-shape.cc#L372-L382

I haven't tested vertical positioning in Uniscribe, but the [spec](https://docs.microsoft.com/en-us/typography/opentype/spec/features_uz#tag-vrt2) suggests that `vrt2` should be used in preference to `vert`. And `vkrn` should probably be applied too?

**Comment by behdad** [comment]
For all both, plus other vertical features, see: d71c0df2d17f4590d5611239577a6cb532c26528

**Comment by behdad** [comment]
> For all both, plus other vertical features, see: [d71c0df](https://github.com/harfbuzz/harfbuzz/commit/d71c0df2d17f4590d5611239577a6cb532c26528)

Which points to this thread: https://lists.freedesktop.org/archives/harfbuzz/2013-August/003490.html

**Comment by behdad** [comment]
Please reopen or file new issue if you think something should change.

**Comment by simoncozens** [comment]
Thanks, that's really helpful. Wouldn't the first time that the spec is at variance with reality... Well, this is why I'm writing a commentary on it...
