### ISSUE TITLE
What are `test/shaping/texts` for?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3123]
AFAICT these files are not used by any of our tests, or am I missing something?

**Comment by khaledhosny** [comment]
While at it, looks like this commit 61a58e26a5bda16851669404fc8206896e124740 did not add the text it intented to add (the file no is at `test/shaping/texts/in-house/shaper-indic/script-devanagari/misc/tricky-reordering.txt`.

**Comment by behdad** [comment]
These were added speculatively, before we had a test suite. The aim was that we'd have fonts, and texts, and tests files listing what combination of fonts and texts to test (eg. based on script). This was more useful for testing against Uniscribe, that is, when automated ("unsupervised") testing could be done.  Never materialized. Now it's just bunch of text; we should use if there's any value, or remove.

**Comment by behdad** [comment]
And when removing, maybe remove a couple directory levels as well.

**Comment by khaledhosny** [comment]
OK, I see if I can come up with a few interesting test cases and drop the rest.

**Comment by behdad** [comment]
Friendly pingish :)

**Comment by khaledhosny** [comment]
I’ve added some tests in https://github.com/harfbuzz/harfbuzz/pull/3627, the rest of the texts seem to be covered by other tests or too generic for a test.

**Comment by behdad** [comment]
On the one hand I'm happy to remove them. On the other hand they are an interesting collection of codepoints. The Indic utrrs ones can go. I guess they all can go and remain the history. Feel free to nuke them all. Thanks.
