### ISSUE TITLE
Add WOFF/WOFF2

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3125]
Both in the library as loaders, and in subset library as output options.

**Comment by behdad** [comment]
cc @garretrieger @khaledhosny

**Comment by khaledhosny** [comment]
WOFF will need gzip and WOFF2 will need brotli as extra dependencies, but WOFF2 tranformations are non-trivial so do we want to implment these directly in HarfBuzz or use https://github.com/google/woff2?

**Comment by behdad** [comment]
Using `woff2` is what I had in mind.

**Comment by jackyjjc-canva** [comment]
Hi, do you have a timeline in mind on when WOFF and WOFF2 support will be added? We are working on a project and evaluating subsetting libraries, having a bit of clarity on this would greatly help us make the right decision.

Awesome library, by the way, thanks for making it open source! 😃

**Comment by behdad** [comment]
We currently don't have any resources planned. But it's a small piece of work. We can get it scheduled fairly easily.

@garretrieger what's your feels about it?

**Comment by behdad** [comment]
We can probably skip woff and go to woff2 directly.

@garretrieger anyone on your team who can allocate some time to this?

**Comment by garretrieger** [comment]
Not immediately but either me or @qxliu76  could probably tackle this in the near future. I'll probably have time after we finish the code reorg.

**Comment by behdad** [comment]
Code reorg more important.

**Comment by warent** [comment]
Is this never being added? I was really looking forward to this feature

**Comment by behdad** [comment]
Unless someone wants to work on it...

**Comment by drott** [comment]
In the meantime, could we make the tools `hb-shape` and `hb-view` issue a warning or fail when given woff2 data? It seems they partially process it, and produce wrong results.

**Comment by drott** [comment]
`1.woff2` from https://emojicopy.com/ https://emojicopy.com/assets/fonts/9.0/SVG/1.woff2 does not get rejected.

**Comment by khaledhosny** [comment]
```
$ hb-shape 1.woff2
hb-shape: 1.woff2: Failed loading font face
Try `hb-shape --help' for more information.
```

May be you are using old version of the tools where invalid/unsupported files were silently accepted? This was changed relatively recently.

**Comment by drott** [comment]
Oh, I thought I was using tip of tree, but I was using a binary from <hb-dir>/util/, not <hb-dir>/build/util.. sorry for the noise.

**Comment by behdad** [comment]
Note that there's now `--face-loader=ft` that should allow loading these fonts if FreeType is compiled with support for them.
