### ISSUE TITLE
[util/hb-shape] Revisit single-paragraph mode in batch mode

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3129]
So 50379fbb1517387d91b3ec4cc55a7500dd09b436

I like to revisit that, mostly because I want to refactor the batch processing code.

I suggest that either:
- Make `hb-shape` always process as one-paragraph if input is given with `--text` or `--unicodes`; that would be a change of behavior but one that I think would be fine and I actually like it, 
- Add a `--single-par` option and make only the tests that need it invoke it.

@khaledhosny

**Comment by khaledhosny** [comment]
Option 2 seems fine, but I don’t have any strong preference either way, so whatever you think is best.

**Comment by khaledhosny** [comment]
Sounds good, do you want me to do it or are you working on this already?

**Comment by behdad** [comment]
I haven't started yet but I think it's easy-enough that I'll do it now. Thanks :)

**Comment by behdad** [comment]
So my plan is to share the batch code, but take hb-subset off `main-font-text`.

**Comment by behdad** [comment]
Fixed. I felt lazy and didn't send a PR. Please review @khaledhosny

**Comment by khaledhosny** [comment]
The tests pass, so all is good.
