### ISSUE TITLE
Subset glyph lacks outline.

### ISSUE THREAD

**Issue by bungeman** [harfbuzz/harfbuzz#3131]
Originally reported as [Chromium issue 1231818](https://crbug.com/1231818).

Building current tip of tree HarfBuzz ( 8940409e3c108e2c26c0f22679eb3c6cea4fee9d ) with the default meson build and running
```
    util/hb-subset --retain-gids testing-font.ttf "cdeopqr" -o test-font.subset.ttf
```
produces a subset font where 'd', 'p', and 'q' are present but have no outline, even though they have an outline in the original font. Even after laundering this font through `ttx` (decompile and recompile to ensure sane data) the same happens. The missing glyph outlines are strange in that they have a large number of points near each other (not sure if this is intentional or not).

Providing the font in [testing-font.zip](https://github.com/harfbuzz/harfbuzz/files/6963252/testing-font.zip), since `.ttf` files are blocked.

**Comment by garretrieger** [comment]
Looking into it.

**Comment by bungeman** [comment]
The issue appears to be in `SimpleGlyph::trim_padding` on the line `repeat = *glyph + 1;` since `const char *glyph` is signed. The specification states that `the next byte (read as unsigned) specifies the number of additional times...`.

**Comment by garretrieger** [comment]
Thanks, that indeed looks to be the issue. I'll make a fix.

**Comment by bungeman** [comment]
Locally verified a change like

```
diff --git a/src/hb-ot-glyf-table.hh b/src/hb-ot-glyf-table.hh
index 9b8658185..3ca090633 100644
--- a/src/hb-ot-glyf-table.hh
+++ b/src/hb-ot-glyf-table.hh
@@ -509,8 +509,8 @@ struct glyf
       const Glyph trim_padding () const
       {
        /* based on FontTools _g_l_y_f.py::trim */
-       const char *glyph = bytes.arrayZ;
-       const char *glyph_end = glyph + bytes.length;
+       const unsigned char *glyph = reinterpret_cast<const unsigned char*>(bytes.arrayZ);
+       const unsigned char *glyph_end = glyph + bytes.length;
        /* simple glyph w/contours, possibly trimmable */
        glyph += instruction_len_offset ();
 
@@ -524,7 +524,7 @@ struct glyf
        unsigned int coords_with_flags = 0;
        while (glyph < glyph_end)
        {
-         uint8_t flag = *glyph;
+         const unsigned char flag = *glyph;
          glyph++;
 
          unsigned int repeat = 1;
```
alleviates this particular issue with this particular font.
