### ISSUE TITLE
hb-subset feature request: ability to retrieve glyph id remapping

### ISSUE THREAD

**Issue by bungeman** [harfbuzz/harfbuzz#3140]
As things currently stand, the public API for subsetting allows one to specify which codepoints and glyphs to keep. If `HB_SUBSET_FLAGS_RETAIN_GIDS` is set the glyph ids are maintained, otherwise the glyph ids will be re-assigned somewhat arbitrarily in the subset font. The main reason for the existence of `HB_SUBSET_FLAGS_RETAIN_GIDS` is that a user may need to write out many glyph ids before subsetting and cannot currently know in advance what the subset glyph ids may be without setting this flag. (Related, the is no API for getting the `reverse_glyph_map` after mapping, so it isn't straight forward to do the mapping without setting this flag even after subsetting.) However, if the user could control the remapping of the glyph ids then it could make the assignments itself as it went along (mapping the first glyph id it sees from an input font to glyph 4 in the output font, the next to 5, etc).

This is a request for something like `hb_map* hb_subset_input_glyph_map()` which works something like `hb_subset_input_glyph_set` in that the keys of this map are input glyph ids to retain, but the values are the associated subset font glyph ids (if value is repeated at any point the result is failure or one or the other wins). This would then influence `_create_old_gid_to_new_gid_map` when `hb_subset_plan_create` is called, which appears to be the only actual code which would need to be modified.

This would allow the user to output `subset` glyph ids before actually creating the subset font while simply maintaining the hb_map as it goes. Then the subset font can be smaller (especially with large CJK fonts) since the overhead of `loca` and such can be elided. If for some reason the subset failed the user would need fail (or go back and start over again) but this is unlikely since in general the font was just used by HarfBuzz to shape the glyphs.

**Comment by behdad** [comment]
Very good point. Yes, we can do that.

Some tables depend on the relative order of gid's. We should make sure such tables are correctly typeset. The ones I have in mind involve OT Layout Coverage and ClassDef structures.

And yes providing a mapping sounds good.

**Comment by garretrieger** [comment]
Internally the subset plan maintains a glyph map from new to old which the subsetting code then uses to rewrite gids, so on the surface this could be pretty easy to support. However, I suspect that we may have instances of code that were written with the assumption that the glyph map always retains the relative order of the glyphs between the original and the subset.
So if we were to do this we may want to add some tests that attempt to locate parts of the subsetter operating under this assumption.

**Comment by bungeman** [comment]
I suppose one alternative API approach is like `cairo_truetype_font_use_glyph` (from `cairo-truetype-subset.c`) which in HarfBuzz would look something like `bool hb_subset_input_add_glyph_or_fail(hb_subset_input_t *input, hb_codepoint_t src_gid, hb_codepoint_t* subset_gid)`. I'm not sure I like this API much, mostly pointing it out here as how a different subsetter does this sort of thing. This of course doesn't really do anything about preserving the relative order of the glyphs (since it is never known if an earlier glyph might be added later).

**Comment by behdad** [comment]
Interesting.

Note that cairo's PS/PDF backend just record the entire document before generating any pages. So they don't have the same problem as you are bringing up here.

**Comment by behdad** [comment]
Sure that would be a lot easier indeed.

**Comment by garretrieger** [comment]
Yeah, we have that info in the subset plan so if we update the api to optionally return the plan then it would be easy to get information like glyph mapping from it. One option is we could add an explicit generate subset plan call and then add a second version of the subset method which takes a plan instead of input.

**Comment by behdad** [comment]
Exposing subset_plan in the API, originally with no extra functionality, sounds good to me. @garretrieger can you prepare a proposal?

**Comment by garretrieger** [comment]
Yes, I'll put something together.

**Comment by garretrieger** [comment]
Fixed by https://github.com/harfbuzz/harfbuzz/pull/3429
