### ISSUE TITLE
Latest harfbuzz doesn't work correctly with my font

### ISSUE THREAD

**Issue by Serg77m** [harfbuzz/harfbuzz#3153]
Hello. I updated my Debian Linux to a new version, and found that the new harfbuzz version 2.7.4 stopped working correctly with my psaltic font. It looks as if there is no Advanced Typography at all: no ligatures, no kerning. Previously, version 2.3.1 was used. Later it turned out that the problem occurs after adding one additional CALT table to the font, which should not actually affect it. I tried to build several different versions of harfbuzz from the source, version 2.6.4 works correctly, version 2.6.5 does not anymore. The latest version from the main branch also works incorrectly. Here is screenshots. There are two versions of the font here: UniPsaltica_good.otf works correctly, UniPsaltica_bad.otf does not. The second version contains an additional CALT table.
Version 2.6.5:
![harfbuzz_2 6 5](https://user-images.githubusercontent.com/55576707/129687567-f9274115-2f45-4ef0-8a38-71b8834d3add.png)
Version 2.6.4 works correctly with both versions:
![harfbuzz_2 6 4](https://user-images.githubusercontent.com/55576707/129688491-c72db0af-b333-4fd1-ac12-535f5f3803cf.png)
The string for the test: 𝁇𝁆𝃇    (unicode: 0x1D047 0x1D046 0x1D0C7)
[UniPsaltica.zip](https://github.com/harfbuzz/harfbuzz/files/6998139/UniPsaltica.zip)

**Comment by khaledhosny** [comment]
The bad version of the font contains a `morx` table, and newer versions of HarfBuzz will prefer it over GSUB table (older versions didn’t support `morx` natively).

This is probably not something you intended and looks like you use FontForge, so you need to uncheck the option that generated AAT tables when generated the font.
