### ISSUE TITLE
Should the docs still say go to the mailing list?

### ISSUE THREAD

**Issue by mahanstreamer** [harfbuzz/harfbuzz#3160]
The documentation says that "Discussion and questions are welcome on the HarfBuzz mailing list."

However @behdad  says here "https://lists.freedesktop.org/archives/harfbuzz/2021-June/007558.tml":
"We have also largely migrated to github issues and Discussions instead of
this list."
That being said, should the documentation be updated to reflect that?

**Comment by khaledhosny** [comment]
Where in the documentation mailing list is still recommended?

**Comment by mahanstreamer** [comment]
https://harfbuzz.github.io/install-harfbuzz.html
"Release notes are posted with each new release to provide an overview of the changes. The project tracks bug reports and other issues on GitHub. Discussion and questions are welcome on the HarfBuzz mailing list."
