### ISSUE TITLE
linker error with 2.9.0 release building with meson

### ISSUE THREAD

**Issue by Bonnietwin** [harfbuzz/harfbuzz#3163]
Trying to build 2.9.0 on IPFire (based on Linux From Scratch) as harfbuzz is now a required dependency for the latest pango.
I am getting the same type of error message as was raised in #2644 and #880

> /usr/bin/ld: src/libharfbuzz.so.0.20900.0.p/hb-aat-layout.cc.o (.data.rel.local.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'

The full log for the harfbuzz build is attached here.
[harfbuzz_build.ipfire.log](https://github.com/harfbuzz/harfbuzz/files/7040704/harfbuzz_build.ipfire.log)

**Comment by khaledhosny** [comment]
You seem to be using custom compiler flags, you `-fexceptions` but HarfBuzz shouold be built with `-fno-exceptions -fno-rtti`.

**Comment by Bonnietwin** [comment]
Thanks very much for the information.
I tried to change the cflags but nothing seemed to work.

-fno-rtti was not needed as we are using c and it appears to only be valid for c++
I tried add in -Dc_args=-fno-exceptions to the meson command and the -fexceptions command disappeared from the command but -fno-exceptions did not appear and the same linker error occurred.

As harfbuzz has both autotools and meson I eventually ran the build with autotools with no additional cflags defined and everything built without a murmur. So I will leave it like that for now and close this issue.

If eventually harfbuzz removes autools and only runs meson, like pango does, then I will have to come back and resolve the problem of how to define the cflags in the meson build.

**Comment by Bonnietwin** [comment]
harfbuzz-9.x removed autotools so when I tried to build the harfbuzz-10.1.0 I had to use meson and had to solve the above problem.

It turned out that instead of -Dc_args=-fno-exceptions I needed to use -Dcpp_args=-fno-exceptions and then harfbuzz built with meson without any problems.

Problem properly solved not just worked around.
