### ISSUE TITLE
[meson] Can we pin ragel to a 6.10 version?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3164]
With autoconf, if I don't touch the ragel source files, the outputs won't be regenerated. That makes it work even on my Fedora that has ragel 7. Ragel 7 changes the output completely. Ragel 7 is also not stable from upstream's point of view.

Whenever I have tried using meson, I've abandoned it immediately, because it regenerated all ragel files....

**Comment by khaledhosny** [comment]
I think the problem is that meson really really don’t want to write anything outside the build directory, so we fake it by writing to the build directory then copying to the source directory, so the first time meson setup is done the files will always be generated.

**Comment by behdad** [comment]
That part is fine as long as it's pinned to the correct ragel version.

**Comment by khaledhosny** [comment]
Do you want something like checking ragel version and ignoring it if it is not the right version?

I myself don’t install ragel since I don’t touch these files, and then meson wont try to regenerate them.

**Comment by behdad** [comment]
> Do you want something like checking ragel version and ignoring it if it is not the right version?

Given that meson really likes to wrap things, I was wondering if we can make it at least have an option to build the right version.

Ignoring bad version is a good start.

Thanks.
