### ISSUE TITLE
unexpected hb_ot_layout_glyph_class_t 

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3170]
I am calling hb_ot_layout_get_glyph_class on the glyphs returns from hb_shape in pango.

With Cantarell, I get UNCLASSIFIED for an fi or ffi ligature. I would have expected LIGATURE. In fact, the only place I ever get something other than UNCLASSIFIED is for marks, which do in fact get MARK.

With Source Sans Pro, I do get the expected BASE and LIGATURE values.

I don't see why this would depend on the font - a ligature is a ligature...

**Comment by behdad** [comment]
Nothing to do here, unless you want to commit a line or two to the docs.
