### ISSUE TITLE
[hb-subset] Failure to subset NotoSansCJK-Regular.ttc

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#3173]
HarfBuzz 2.9.0 from the provided Windows binaries.

1. Get https://github.com/googlefonts/noto-cjk/blob/165c01b46ea533872e002e0785ff17e44f6d97d8/Sans/OTC/NotoSansCJK-Regular.ttc
2. `hb-subset.exe --unicodes-file subset.txt --layout-features="*" NotoSansCJK-Regular.ttc --face-index 0 -o out.ttf`
3. Observe hb-subset exits with error code 1 and leaves a 0 bytes out.ttf.
4. Remove last Unicode value from subset.txt and try again
5. See it working this time?!

Some times it works with the last value, too, for some reason?!?! If you put the value as the only one into a new txt file and use it, hb-subset also finishes properly...

[subset.txt](https://github.com/harfbuzz/harfbuzz/files/7060110/subset.txt)

**Comment by behdad** [comment]
And I made it print an error message if operation failed, since we don't expect that to happen.
