### ISSUE TITLE
not decomposing arabic per UTR#53 

### ISSUE THREAD

**Issue by bobh0303** [harfbuzz/harfbuzz#3179]
Observed:

```
$ hb-shape -V /dev/null -u 0622,0670
trace: start reorder    buffer: <U+0622=0|U+0670=0>
trace: end reorder      buffer: <U+0622=0|U+0670=0>
```

Expected:

```
$ hb-shape -V /dev/null -u 0622,0670
trace: start reorder    buffer: <U+0622=0|U+0670=0>
trace: end reorder      buffer: <U+0627=0|U+0670=0|U+0653=0>
```

Description:

The first step in UTR#53 Unicode Arabic Mark Reordering algorithm [AMTRA](https://www.unicode.org/reports/tr53/#AMTRA_Specification) is to decompose to NFD, which would cause:
```
U+0622 ARABIC LETTER ALEF WITH MADDA ABOVE
U+0670 ARABIC SUBSCRIPT ALEF
```
to decompose to 
```
U+0627 ARABIC LETTER ALEF 
U+0653 ARABIC MADDAH ABOVE
U+0670 ARABIC SUBSCRIPT ALEF
```
which would then be correctly reordered (by existing harfbuzz logic) to:
```
U+0627 ARABIC LETTER ALEF 
U+0670 ARABIC SUBSCRIPT ALEF
U+0653 ARABIC MADDAH ABOVE
```
However the initial decomposition to NFD is not happening.

Tested with `hb-shape` 2.9.0

**Comment by behdad** [comment]
> $ hb-shape -V /dev/null -u 0622,0670

With `/dev/null` you won't get the decomposition, since the normalizer would only decompose if the font supports the decomposed sequences.  But if you try with a real font, you'll see that it's actually already working.

**Comment by bobh0303** [comment]
Thanks for your reply, Behdad, and that makes sense. However, something is still not right (or I'm not understanding something):
```
$ hb-shape -V Amiri-Regular.ttf -u 0622,0670
trace: start reorder    buffer: <U+0627=0|U+0653=0|U+0670=0>
trace: end reorder      buffer: <U+0627=0|U+0670=0|U+0653=0>
trace: start table GSUB buffer: [uni0622=0|uni0670=0]
...
```
As you predicted, with a real font the decomposition of U+0622 occurs and marks are reordered.

But then: Why is alefMadda apparently re-composed for the start of GSUB? Is there an NFC normalization pass between `end reorder` and `start table GSUB` ?

**Comment by behdad** [comment]
> Is there an NFC normalization pass between `end reorder` and `start table GSUB` ?

Exactly.

Does the Arabic reordering algo require inhibiting the NFC recomposition step? If yes, we did not realize that.

HarfBuzz implements a modified Unicode normalization algorithm that, depending on shaper-requested normalization mode, decomposes, reorders, and possibly recomposes input, at each step only doing so if the font supports it. It's the reordering step that the Arabic shaper modifies.

**Comment by behdad** [comment]
For example, here's a patch making the Arabic shaper request decomposed input:
```
diff --git a/src/hb-ot-shape-complex-arabic.cc b/src/hb-ot-shape-complex-arabic.cc
index 1f8c1410f..593779898 100644
--- a/src/hb-ot-shape-complex-arabic.cc
+++ b/src/hb-ot-shape-complex-arabic.cc
@@ -702,7 +702,7 @@ const hb_ot_complex_shaper_t _hb_ot_complex_shaper_arabic =
   data_destroy_arabic,
   nullptr, /* preprocess_text */
   postprocess_glyphs_arabic,
-  HB_OT_SHAPE_NORMALIZATION_MODE_DEFAULT,
+  HB_OT_SHAPE_NORMALIZATION_MODE_DECOMPOSED,
   nullptr, /* decompose */
   nullptr, /* compose */
   setup_masks_arabic,
```

**Comment by bobh0303** [comment]
> Does the Arabic reordering algo require inhibiting the NFC recomposition step? If yes, we did not realize that.

Correct: recomposition of any Arabic sequences (there are few) should not be done. UTR#53 specifically calls for NFD. See [FAQ 5.1](https://www.unicode.org/reports/tr53/#NFD_NFC).

**Comment by behdad** [comment]
> Correct: recomposition of any Arabic sequences (there are few) should not be done. UTR#53 specifically calls for NFD. See [FAQ 5.1](https://www.unicode.org/reports/tr53/#NFD_NFC).

Okay. We should see how to do this only for sequences that it matters; we depend on recomposition for old legacy fonts without positioning to work. cc @khaledhosny

**Comment by behdad** [comment]
Another approach is that we can make `reorder_marks` callback return whether recomposition should be disabled for that cluster. We don't have an easy place to store that but is not impossible.

**Comment by behdad** [comment]
Or just don't recompose if `reorder_marks` is implemented and there are more than one mark in the cluster.

Khaled, I know we rely on two marks composing in legacy Arabic. How much do we depend on that though?

**Comment by behdad** [comment]
cc @jfkthame

**Comment by khaledhosny** [comment]
I don’t think there are any canonical composition for pure Arabic mark sequences in Unicode, the compositions always include a base + mark.

Many Arabic canonical decompositions in Unicode are questionable, I don’t think preferring composed form is really a good idea. For example if I input alef madda above + superscript alef, I would never want the madda to be over the super script alef as it makes no sense.

Another questionable decompositions, yeh with hamza above decomposes into yeh + hamza above, but yeh has two dots below in all positions while yeh with hamza above never have dots (not in modern orthography).

**Comment by khaledhosny** [comment]
That madda is not treated as hamza in UTR#53 seems odd to me, because madda is a form of hamza (the use of madda in Quranic orthography should be limited to 06E4 exactly because it never composes). The rationale for excluding madda from MCM seems misguided to me, and including it could have made this whole discussion moot, since it it is the only other mark besides hamza that is involved in Arabic canonical decomposition.

**Comment by khaledhosny** [comment]
I’m pretty sure I raised this concern before and I’m still not convinced by the answer.

It does not appear that CoreText prefers decomposed form either:
```
$ hb-shape Amiri-Regular.otf -u 0627,0670,0653 --no-positions
[uni0670=0|uni0622=0]
$ hb-shape Amiri-Regular.otf -u 0627,0670,0653 --no-positions --shaper=coretext
[uni0670=0|uni0622=0]
```

I don’t know any other implantation of UTR#53, so it might not be too late to fix it.

**Comment by behdad** [comment]
> That madda is not treated as hamza in UTR#53 seems odd to me, because madda is a form of hamza (the use of madda in Quranic orthography should be limited to 06E4 exactly because it never composes). The rationale for excluding madda from MCM seems misguided to me, and including it could have made this whole discussion moot, since it it is the only other mark besides hamza that is involved in Arabic canonical decomposition.

Can you elaborate on that? What was Unicode's rationale? If we can justify departing from it, I'm fine with that.

**Comment by khaledhosny** [comment]
Quoting from  UTR#53:
> 3.1 Modifier Combining Marks (MCM)
>
> For use by this algorithm, this specification defines a group of combining marks called “Modifier Combining Marks” (MCM). MCM are combining characters that are normally used to modify the base character before them, and should normally be rendered closer to the base character than tashkil (supplementary diacritics, including vowels). The MCM characters are not formally classified as ijam (consonant pointing/nukta, and so on) in the Unicode Standard, but they are usually perceived by users as ijam.

and the rational for not including madda in MCM:
> Neither U+0653 ARABIC MADDAH ABOVE (ccc=230) nor U+06E4 ARABIC SMALL HIGH MADDA (ccc=230) are MCM because they are normally displayed above vowel marks.

Which while true for U+06E4, is never true for U+0653. U+06E4 is a form of hamza (early Arabic orthography had neither, Quranic orthography still uses standalone hamza + alef in place of alef madda).

P.S. The rationale why Unicode encoded U+06E4 seems to have been lost in time, but I like to believe its name is a misnomer and that it was encoded for the madda used in Quranic orthography, as I’m not aware of any use of a small madda as a distinct character.

**Comment by behdad** [comment]
> and the rational for not including madda in MCM:
> 
> > Neither U+0653 ARABIC MADDAH ABOVE (ccc=230) nor U+06E4 ARABIC SMALL HIGH MADDA (ccc=230) are MCM because they are normally displayed above vowel marks.
> 
> Which while true for U+06E4, is never true for U+0653.

To me it's clear that those two can and should be treated differently.

I'm supportive of your proposal.  @jfkthame?

**Comment by behdad** [comment]
Oh actually our algorithm was *supposed* to be able to handle composing and let blocking take care of compositions that should not happen. So, tailoring the algorithm to disallow undesirable compositions as Khaled is proposing is indeed the way forward.

**Comment by bobh0303** [comment]
> > Neither U+0653 ARABIC MADDAH ABOVE (ccc=230) nor U+06E4 ARABIC SMALL HIGH MADDA (ccc=230) are MCM because they are normally displayed above vowel marks.
> 
> Which while true for U+06E4, is never true for U+0653.

I'm no expert, which is why I asked [on the Unicode list in 2011](http://www.unicode.org/mail-arch/unicode-ml/y2011-m07/0143.html) where responses suggested 0653 always goes above vowel marks.

**Comment by khaledhosny** [comment]
It all boils down to whether you think U+0653 should be used in Quranic orthography or not. I believe it should not because the two uses are incompatible and because of the canonical decomposition. U+06E4 should be used in Quranic orthography instead, and the “small” in the name is a misnomer since there is no such thing as small madda.

**Comment by LornaSIL** [comment]
@roozbehp care to chime in?

**Comment by behdad** [comment]
After thinking about it again, I decided to change the Arabic shaper to prefer decomposed forms. Let's see how it sticks.

**Comment by khaledhosny** [comment]
```
$ hb-view Amiri-Regular.otf "ييي ي ئئئ ئ"
```
![o](https://user-images.githubusercontent.com/93914/131791346-5d6e118f-2528-495a-9cc6-343cf75259ce.png)

```
$ ./util/hb-view Amiri-Regular.otf "ييي ي ئئئ ئ"
```
![n](https://user-images.githubusercontent.com/93914/131791362-c1bf5758-7c41-44f9-a7d4-3b54c6b092e3.png)

**Comment by behdad** [comment]
Did this break things? Can you elaborate?

**Comment by khaledhosny** [comment]
The second screenshot is main branch, ئ got decomposed adding dots under it and broken hamza position.

**Comment by behdad** [comment]
Reverted. Thanks. Can you add tests?

**Comment by jfkthame** [comment]
Yeah, I think we really need to continue using precomposed forms here.

In theory, a font could take responsibility at the GSUB level for rendering the glyph sequence <YEH, HAMZA ABOVE> so that it looks like U+0626 YEH WITH HAMZA ABOVE (e.g. using a contextual substitution to replace the base YEH glyph with a dotless form when followed by HAMZA ABOVE). But I suspect that few if any common Arabic fonts handle this; font designers' assumption is that Arabic letters will be rendered "as-is", so that U+064A will have a dotted glyph in all positions, U+0626 will be handled separately as its own set of (dotless) glyphs, and the sequence <U+064A, U+0654> will be handled by canonical composition (not by a contextual variant of the base glyph).

**Comment by behdad** [comment]
So UTR#53 is just out of sync with reality.

**Comment by khaledhosny** [comment]
Should this be closed now?

**Comment by behdad** [comment]
> Should this be closed now?

I think so.

**Comment by roozbehp** [comment]
We just published a proposed update to UTR#53 (soon to be UAX#53) that addresses the <Yeh, Hamza Above> issue. Please take a look and send us any feedback you may have. Here's the new text (from https://www.unicode.org/reports/tr53/tr53-9.html#AMTRA_Specification):

**Implementation note:** Considering that most Arabic fonts have higher quality glyphs for precomposed characters, implementations may try to recombine base characters with a combining character immediately following them if that would result in a precomposed Unicode character. For example, if after running AMTRA the first two characters of the output are U+064A ARABIC LETTER YEH and U+0654 ARABIC HAMZA ABOVE, an implementation may want to replace them with U+0626 ARABIC LETTER YEH WITH HAMZA ABOVE. (This also helps make sure that the dots of U+064A are not displayed, even if the font is not aware of the Unicode requirement for U+064A losing its dots when combined with U+0654.)

When this step is done, implementations should not skip combining marks. For example, if the output of AMTRA is the sequence <U+0627 ARABIC LETTER ALEF, U+0670 ARABIC LETTER SUPERSCRIPT ALEF, U+0653 ARABIC MADDAH ABOVE>, an implementation may not replace the first and the third character with U+0622 ARABIC LETTER ALEF WITH MADDA ABOVE.

Here's where to send feedback and see the feedback already received:
https://www.unicode.org/review/pri487/

**Comment by behdad** [comment]
@khaledhosny Is this something you can look into? Thanks.

**Comment by khaledhosny** [comment]
Isn’t the described behavior what HarfBuzz already does?

**Comment by behdad** [comment]
It probably is. We can close till somebody proves otherwise.
