### ISSUE TITLE
expose unicode ranges ?

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3184]
I've been experimenting with making a PangoFont implementation that directly wraps a hb_font_t. One api that PangoFont has is to get a list of supported languages (its used to enable filtering by language in font choosers). I see there is a hb_ot_meta api to get the supported and design languages, but... none of the fonts I used it on have any such data.
My reading of the OpenType spec is that this meta table was added because the unicode range bitmap in the OS/2 table ran out of space to cover all of Unicode.
So, could that range data be made available in addition to the meta table ? Mind you, I haven't check if fonts are any better at providing data for that.

**Comment by behdad** [comment]
The ranges are not reliable / useful. What would be needed is basically a fontconfig clone inside HarfBuzz (which, longterm is in my plans). That is, the language database of fontconfig is needed to detect what languages are supported. The unicode-ranges just doesn't have enough data when you get past the first few languages.

**Comment by matthiasclasen** [comment]
I am curious: shouldn't it be fairly straightforward to write a tool do that does whatever fontconfig currently does (or something better, based on harfbuzz' ability to extend coverage via de-/composition), and use that data to correct the fonts coverage data ? If the ranges aren't granular enough, that could just spit out data for the meta table.

Sortof like a generate-coverage-data script that you run over your font once before publishing or packaging it.

**Comment by behdad** [comment]
> I am curious: shouldn't it be fairly straightforward to write a tool do that does whatever fontconfig currently does

Yes. The main part we don't currently have is the part that freezes multiple sets together, sharing pages, and making them mmap'able.

**Comment by behdad** [comment]
The font's unicode ranges are not reliable.
