### ISSUE TITLE
Add `hb_font_[sg]et_synthetic_slant` (was Add`hb_font_set_skew`)

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3196]
If a client skews a font during rendering (eg. faux Italic, as fontconfig+Pango do), then our positioning can go wrong. Add `hb_font_set_skew` such that the client can tell us what skew the font has so we adjust for it.

I'll expand with drawings later.

Another, related issue, is that our fallback-positioning can be improved by considering italic-angle. But that's separate and needs no API change.

**Comment by behdad** [comment]
cc @jfkthame @mclasen

**Comment by matthiasclasen** [comment]
A related thing I've been musing about is that a synthetic italic should maybe have a matching caret slope.

**Comment by behdad** [comment]
Yes I have a plan to fix all that with this.

**Comment by behdad** [comment]
This basically will be a ratio (as opposed to angle), and will be added to whatever slant ratio the font declares (as in what's returned in hb-style API https://github.com/harfbuzz/harfbuzz/issues/3199).

Whatever values we dig from the font ourselves, either in GPOS or in ot-font, we will skew by this value.  That would include the cursor rise/run as well.

This will address Matthias's point as well as my observation that Nastaliq cursive joins are wrong in synthetic-slanted fonts in Pango.  PangoFc just needs to call this API to set the synthetic slant.

**Comment by behdad** [comment]
I like to get this done soon.

**Comment by behdad** [comment]
The proposed set synthetic slant will be used for both horizontal and vertical direction. Which means it has to be a multiplier, not an absolute value. Hence a float:
```
void
hb_font_set_synthetic_slant (hb_font_t *font, float slant);

float
hb_font_set_synthetic_slant (hb_font_t *font);
```

**Comment by matthiasclasen** [comment]
Should I expect  HB_OT_METRICS_TAG_HORIZONTAL_CARET_RISE and HB_OT_METRICS_TAG_HORIZONTAL_CARET_RUN to be affected by this?

I tried this out with Cantarell Italic, setting the synthetic slant to 0.2. But I still get vertical carets.

**Comment by drott** [comment]
Thanks for the added API. 

> If a client skews a font during rendering (eg. faux Italic, as fontconfig+Pango do), then our positioning can go wrong. 

What positioning errors to look for? Would you have some examples?

**Comment by behdad** [comment]
> What positioning errors to look for? Would you have some examples?

There's example in https://github.com/harfbuzz/harfbuzz/pull/3338
I'll try putting a webpage together.

**Comment by behdad** [comment]
> What positioning errors to look for? Would you have some examples?

Here we go: The slanted should look like a geometric slant of the upright. On Linux Chome it doesn't: http://behdad.org/slant/

**Comment by behdad** [comment]
> On Linux Chome it doesn't

Also on Chrome Mac. Not surprising since our shaping code is the same.

**Comment by behdad** [comment]
Firefox gets it right.

**Comment by khaledhosny** [comment]
Interestingly, it looks good in Firefox already:
![Screenshot_20220103-162446~2](https://user-images.githubusercontent.com/93914/147941864-aa01b671-2124-4cb0-887e-e22ba6cbfaad.png)

Compared to Chrome:
![Screenshot_20220103-162551~2](https://user-images.githubusercontent.com/93914/147941955-fffde41a-0f50-48ed-8106-44d5978cedb7.png)

**Comment by behdad** [comment]
> Interestingly, it looks good in Firefox already:

I think Firefox is rightly skewing the shaping result coordinates as well.

**Comment by drott** [comment]
Thanks, for the examples - understood. Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1283928
