### ISSUE TITLE
Release hb-style.h API

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3199]
Is currently experimental. I like the way it is and seems to work fine. Need to move the enum from `hb-style.cc` to `hb-style.h` and call it stable. cc @ebraminio @khaledhosny @matthiasclasen @jfkthame

**Comment by khaledhosny** [comment]
It was fine when I used it last time, it was a couple years ago but I don’t think the API changed much sense then. I think it is still used by luaharfbuzz/luatex.

**Comment by khaledhosny** [comment]
I think I was actually using hb-ot-metrics API, I don’t think I have noticed hb-style API before. I’m working on a PR to un-experiment it.

**Comment by matthiasclasen** [comment]
I've used it once, and I liked the way it worked. It could be quite helpful in making PangoFont a thin wrapper around hb_font_t.
