### ISSUE TITLE
Private-use metric tags should be in all caps

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#3200]
The private-use tags added in #1867 don’t follow [the convention for private-use tags](https://docs.microsoft.com/en-us/typography/opentype/spec/mvar#value-tags): “Private-use tags must use begin with an uppercase letter and use only uppercase letters or digits.”

**Comment by behdad** [comment]
Note that I also added a private style tag in https://github.com/harfbuzz/harfbuzz/commit/39c20d2b9eb476065e64d3a3cccc6345aa50e4c1

we should apply whatever we conclude to that as well.  That one also uses one capital letter (last one).

**Comment by behdad** [comment]
Now to my main argument. I believe this is correct as is. The OT spec uses all-lowercase tags. It reserves all-uppercase tags for font vendors. Anything in-between is for system-developers, like HarfBuzz.

Originally I had added Harf/Buzz OT features as well. I wish I had not changed that (upon suggestion) to HARF/BUZZ in a62f37d6fa412b799b7247b813f6e65a968e7645

**Comment by behdad** [comment]
Note that other systems, like C/C++ are the same: C/C++ language say any identifier starting with `__` are reserved. Those are used by system libraries though. The "reservation" does not apply to the implementation of the language itself.  Similarly, the reservation doesn't apply to HarfBuzz, which is an implementation of OpenType.

**Comment by dscorbett** [comment]
Hmm, I guess that makes sense. I wish the spec would make that interpretation more explicit though.

**Comment by behdad** [comment]
Okay I re-added `Harf` and `Buzz` features, considering them required; whereas I see the `HARF` and `BUZZ` features as discretionary (user can turn on/off). So they serve distinct purposes now. Might need documentation update.

**Comment by behdad** [comment]
Good to close?

**Comment by behdad** [comment]
> Note that other systems, like C/C++ are the same: C/C++ language say any identifier starting with `__` are reserved. Those are used by system libraries though. The "reservation" does not apply to the implementation of the language itself. Similarly, the reservation doesn't apply to HarfBuzz, which is an implementation of OpenType.

This interpretation is also in line with Graphite's use of `Silf` etc. tags.
