### ISSUE TITLE
harfbuzz 3.0.0 removed symbols despite no soname / soversion change

### ISSUE THREAD

**Issue by pnemade** [harfbuzz/harfbuzz#3216]
Fedora Linux received a new bug against harfbuzz-3.0.0 build.
https://bugzilla.redhat.com/show_bug.cgi?id=2005912

````
[tasaka1@localhost x86_64]$ rpmsodiff harfbuzz-2.8.2-2.fc35.x86_64.rpm harfbuzz-3.0.0-1.fc36.x86_64.rpm 2>&1
	common sonames:
libharfbuzz-gobject.so.0	/usr/lib64/libharfbuzz-gobject.so.0.20802.0	/usr/lib64/libharfbuzz-gobject.so.0.30000.0
libharfbuzz-subset.so.0	/usr/lib64/libharfbuzz-subset.so.0.20802.0	/usr/lib64/libharfbuzz-subset.so.0.30000.0
libharfbuzz.so.0	/usr/lib64/libharfbuzz.so.0.20802.0	/usr/lib64/libharfbuzz.so.0.30000.0

--- harfbuzz-2.8.2-2.fc35/libharfbuzz-gobject.so.0	2021-07-22 18:48:31.000000000 +0900
+++ harfbuzz-3.0.0-1.fc36/libharfbuzz-gobject.so.0	2021-09-18 21:18:29.000000000 +0900
@@ -35,2 +35,3 @@
 hb_gobject_shape_plan_get_type	T
+hb_gobject_style_tag_get_type	T
 hb_gobject_unicode_combining_class_get_type	T

	1 symbols added
T hb_gobject_style_tag_get_type

# template for libharfbuzz-gobject.so.0 version script
HARFBUZZ_3.0.0 {
    global:
	hb_gobject_style_tag_get_type;
};

--- harfbuzz-2.8.2-2.fc35/libharfbuzz-subset.so.0	2021-07-22 18:48:31.000000000 +0900
+++ harfbuzz-3.0.0-1.fc36/libharfbuzz-subset.so.0	2021-09-18 21:18:29.000000000 +0900
@@ -1,26 +1,11 @@
-hb_subset	T
 hb_subset_input_create_or_fail	T
 hb_subset_input_destroy	T
-hb_subset_input_drop_tables_set	T
-hb_subset_input_get_desubroutinize	T
-hb_subset_input_get_drop_hints	T
-hb_subset_input_get_name_legacy	T
-hb_subset_input_get_no_prune_unicode_ranges	T
-hb_subset_input_get_notdef_outline	T
-hb_subset_input_get_overlaps_flag	T
-hb_subset_input_get_retain_all_features	T
-hb_subset_input_get_retain_gids	T
+hb_subset_input_get_flags	T
+hb_subset_input_get_user_data	T
 hb_subset_input_glyph_set	T
-hb_subset_input_layout_features_set	T
-hb_subset_input_nameid_set	T
-hb_subset_input_namelangid_set	T
 hb_subset_input_reference	T
-hb_subset_input_set_desubroutinize	T
-hb_subset_input_set_drop_hints	T
-hb_subset_input_set_name_legacy	T
-hb_subset_input_set_no_prune_unicode_ranges	T
-hb_subset_input_set_notdef_outline	T
-hb_subset_input_set_overlaps_flag	T
-hb_subset_input_set_retain_all_features	T
-hb_subset_input_set_retain_gids	T
+hb_subset_input_set	T
+hb_subset_input_set_flags	T
+hb_subset_input_set_user_data	T
 hb_subset_input_unicode_set	T
+hb_subset_or_fail	T

	21 symbols removed
T hb_subset
T hb_subset_input_drop_tables_set
T hb_subset_input_get_desubroutinize
T hb_subset_input_get_drop_hints
T hb_subset_input_get_name_legacy
T hb_subset_input_get_no_prune_unicode_ranges
T hb_subset_input_get_notdef_outline
T hb_subset_input_get_overlaps_flag
T hb_subset_input_get_retain_all_features
T hb_subset_input_get_retain_gids
T hb_subset_input_layout_features_set
T hb_subset_input_nameid_set
T hb_subset_input_namelangid_set
T hb_subset_input_set_desubroutinize
T hb_subset_input_set_drop_hints
T hb_subset_input_set_name_legacy
T hb_subset_input_set_no_prune_unicode_ranges
T hb_subset_input_set_notdef_outline
T hb_subset_input_set_overlaps_flag
T hb_subset_input_set_retain_all_features
T hb_subset_input_set_retain_gids

	6 symbols added
T hb_subset_input_get_flags
T hb_subset_input_get_user_data
T hb_subset_input_set
T hb_subset_input_set_flags
T hb_subset_input_set_user_data
T hb_subset_or_fail

# template for libharfbuzz-subset.so.0 version script
HARFBUZZ_3.0.0 {
    global:
	hb_subset_input_get_flags;
	hb_subset_input_get_user_data;
	hb_subset_input_set;
	hb_subset_input_set_flags;
	hb_subset_input_set_user_data;
	hb_subset_or_fail;
};

--- harfbuzz-2.8.2-2.fc35/libharfbuzz.so.0	2021-07-22 18:48:31.000000000 +0900
+++ harfbuzz-3.0.0-1.fc36/libharfbuzz.so.0	2021-09-18 21:18:29.000000000 +0900
@@ -365,2 +365,3 @@
 hb_shape_plan_set_user_data	T
+hb_style_get_value	T
 hb_tag_from_string	T

	1 symbols added
T hb_style_get_value

# template for libharfbuzz.so.0 version script
HARFBUZZ_3.0.0 {
    global:
	hb_style_get_value;
};

This breaks binaries and libraries depending on harfbuzz silently.

**Comment by alerque** [comment]
True. At least two points come to mind though:

1. The removed symbols were **never** stable, they were always marked as unstable. The 3.x release marks the first time the related ABIs are considered stable.

1. Harfbuzz has not yet used so name versioning at all. Personally I've wondered whether it should, but at this point the project versioning is the only place breaking vs. non-breaking changes are called out. Keep in mind even if there are arguments in favor of adding soname versioning, it would not have covered this use case because the changed interfaces were previously experimental and hence would not have called for a version bump.

**Comment by alerque** [comment]
Perhaps in the future experimental interfaces should be kept hidden behind a compile time flag until they are stabilized so they don't make their way to production places that are not aware of what they are getting themselves into. There have certainly been projects relying in these interfaces (e.g. Chromium) before but they were also aware they were unstable and they would need to adjust to compensate for future changes. It seems like being built into a distro package with unstable interfaces available might be a recipe for downstream projects to get into more trouble than they need to. Or would that just shuffle the problem downstream as the distro packages wouldn't be as useful and projects would have to bundle the library instead of linking distro packages?

**Comment by oliverlj** [comment]
I don't know if this related, I use https://hub.docker.com/r/timbru31/node-chrome docker image for chromium headless test.

This alpine image pull harfbuzz@edge and now I have this error :

not ok 1 Chromium - [undefined ms] - error
    ---
        message: >
            Error: Browser exited unexpectedly
            Non-zero exit code: 127
            Stderr: 
             Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_retain_gids: symbol not found
            Error relocating /usr/lib/chromium/chrome: hb_subset: symbol not found
            Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_drop_hints: symbol not found
            
            
        browser log: |
            {"type":"error","text":"Error: Browser exited unexpectedly"}
            {"type":"error","text":"Non-zero exit code: 127"}
            {"type":"error","text":"Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_retain_gids: symbol not found\nError relocating /usr/lib/chromium/chrome: hb_subset: symbol not found\nError relocating /usr/lib/chromium/chrome: hb_subset_input_set_drop_hints: symbol not found\n"}

please find ci log here : https://gitlab.com/fritzy/front/fz-front-simulator/-/jobs/1606202130

**Comment by behdad** [comment]
This is a neglect on Fedora packager part to not package `harfbuzz-subset.sh` into a separate `harfbuzz-subset-experimental` or something when it appeared. Nothing we can do. And we could not have been any clear. Just grep for `harfbuzz-subset` in https://github.com/harfbuzz/harfbuzz/blob/main/NEWS file and you see for yourself there's nothing we have done wrong or could do any differently :)):

```
Overview of changes leading to 3.0.0
Friday, September 17, 2021
====================================

- The hb-subset API and the harfbuzz-subset library's ABI are now declared
  stable. The harfbuzz-subset library would not have been possible without the
  work of ...

- Removed old unstable harfbuzz-subset API:
  ...

...

Overview of changes leading to 1.7.7
Tuesday, June 5, 2018
====================================
- Significant libharfbuzz-subset changes. API subject to change.

...

Overview of changes leading to 1.7.6
Wednesday, March 7, 2018
====================================
- New experimental harfbuzz-subset library. All of hb-subset.h
  is experimental right now and API WILL change.
```

The responsible thing would have been, on the side of a packager, to ask us to commit to stable API/ABI. Indeed, some packager asked just that on June 8 in https://github.com/harfbuzz/harfbuzz/issues/3012, and that's why we have a stable API released now.

**Comment by behdad** [comment]
> 2\. Harfbuzz has not yet used so name versioning at all.

The way I see it is that we do use soname versioning. It's just that we never break our soname.

Let's separate `libharfbuzz` from the new `libharfbuzz-subset`. From our stance, `libharfbuzz-subset` didn't exist with a stable soname until two days ago.

**Comment by argonzalez2016** [comment]
> I don't know if this related, I use https://hub.docker.com/r/timbru31/node-chrome docker image for chromium headless test.
> 
> This alpine image pull harfbuzz@edge and now I have this error :
> 
> not ok 1 Chromium - [undefined ms] - error
> ---
> message: >
> Error: Browser exited unexpectedly
> Non-zero exit code: 127
> Stderr:
> Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_retain_gids: symbol not found
> Error relocating /usr/lib/chromium/chrome: hb_subset: symbol not found
> Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_drop_hints: symbol not found
> 
> ```
>     browser log: |
>         {"type":"error","text":"Error: Browser exited unexpectedly"}
>         {"type":"error","text":"Non-zero exit code: 127"}
>         {"type":"error","text":"Error relocating /usr/lib/chromium/chrome: hb_subset_input_set_retain_gids: symbol not found\nError relocating /usr/lib/chromium/chrome: hb_subset: symbol not found\nError relocating /usr/lib/chromium/chrome: hb_subset_input_set_drop_hints: symbol not found\n"}
> ```
> 
> please find ci log here : https://gitlab.com/fritzy/front/fz-front-simulator/-/jobs/1606202130

Same issue here. Any fix for this on alpine?

**Comment by alerque** [comment]
> Same issue here. Any fix for this on alpine?

That is not a Harfbuzz issue. You need to take that up with the Alpine packagers. If I had to guess I'd say they probably stripped the vendored version of HB in the Chromium build and linked it to their system package instead, then swapped it an incompatible version. Chromium was deliberately using unstable interfaces, but they also bundle the version they required. The Alpine packagers need to sort that out.

**Comment by pnemade** [comment]
> This is a neglect on Fedora packager part to not package `libharfbuzz-subset.so` into a separate `harfbuzz-subset-experimental` or something when it appeared. Nothing we can do. And we could not have been any clear. Just grep for `harfbuzz-subset` in https://github.com/harfbuzz/harfbuzz/blob/main/NEWS file and you see for yourself there's nothing we have done wrong or could do any differently :)):

Sorry that I missed to package it separately. 
The Chromium package has been already fixed in Fedora Linux. I will work on fixing scribus and qt5-qtwebengine packages.
Let me also work on creating separate subpackage for `libharfbuzz-subset.so` library.

**Comment by behdad** [comment]
> Sorry that I missed to package it separately.
> The Chromium package has been already fixed in Fedora Linux. I will work on fixing scribus and qt5-qtwebengine packages.

No worries. I didn't know Qt has started using it.

Another option would have been to only make it available as a static library.

> Let me also work on creating separate subpackage for `libharfbuzz-subset.so` library.

Up to you what's best at this point.

**Comment by behdad** [comment]
While we have everyone's attention, lemme bring up a different matter:

There's discussion in https://github.com/harfbuzz/harfbuzz/issues/2524#issuecomment-920595766, suggesting that some time next year, perhaps for HarfBuzz 4.0.0, we break ABI by separating out hb-ft into its own library and probably its own tarball. Please advise what can be done to ease that pain.

We might bump soname and drop the few deprecated symbols we have been carrying. But that's not a huge priority for us. The deprecated symbols are painfree-enough.

**Comment by behdad** [comment]
> we break ABI by separating out hb-ft into its own library

*Maybe* the same for hb-glib. Not sure.

**Comment by behdad** [comment]
> _Maybe_ the same for hb-glib. Not sure.

Or, more likely, move that to Pango.

**Comment by matthiasclasen** [comment]
> Or, more likely, move that to Pango.

Yes, we can do that.

**Comment by behdad** [comment]
> > Or, more likely, move that to Pango.
> 
> Yes, we can do that.

`hb-glib` is all one-line functions. Let's make Pango duplicate it now; when we remove it from libharfbuzz, we move it to a libharfbuzz-compat. Pango can export the relevant functions under a different name, and we can keep many of the one-line functions as a header-only file in harfbuzz forever.

**Comment by behdad** [comment]
> `hb-glib` is all one-line functions. Let's make Pango duplicate it now; when we remove it from libharfbuzz, we move it to a libharfbuzz-compat. Pango can export the relevant functions under a different name, and we can keep many of the one-line functions as a header-only file in harfbuzz forever.

For context: we used to depend on hb-glib as our main provider of Unicode data. But now we provide our own.

**Comment by darix** [comment]
TBH it doesnt matter if the library was stable or not. the removal/rename of symbols should have triggered a bump. it does not really matter if you declare libharfbuzz-subset.so.0 stable or libharfbuzz-subset.so.10. there are tools like abigail which would help you to track that:

* https://youtu.be/b1fO-RLtDME
* https://media.ccc.de/v/1234-libabigail-how-semantic-analysis-of-c-and-c-elf-binaries-can-be-used-to-analyze-abi-changes

**Comment by behdad** [comment]
> TBH it doesnt matter if the library was stable or not. the removal/rename of symbols should have triggered a bump. it does not really matter if you declare libharfbuzz-subset.so.0 stable or libharfbuzz-subset.so.10.

Then we would have ended up with libharfbuzz.so.0 and libharfbuzz-subset.so.1 for the rest of eternity. That would have been more confusing. That's what we wanted to avoid.

**Comment by behdad** [comment]
And it would not have solved any of your problems. You would have got a different error message. "libharfbuzz-subset.so.0" not found instead "symbol not found".

**Comment by darix** [comment]
no we wouldnt because can have libharfbuzz-subset.so.0 and libharfbuzz-subset.so.1 in parallel in the filesystem for the transition period. then no application gets broken while we migrate them to the new API/ABI. what we cant have in the filesystem is a libharfbuzz-subset.so.0 that provides the old and the new ABI at the same time. 

for the mismatched soversion between the libraries. i can understand why one would want that, but in the end that is not a metric  that really matters for a project. no user cares if your library is called libharfbuzz-subset.so.0 or libharfbuzz-subset.so.10. what they do care about is semantic versioning violated and apps crashing because the symbols disappeared.

and tooling like abigail makes it easy for you to track if such breakage occured.

**Comment by behdad** [comment]
If we were to do this again, I would leave the old symbols around as deprecated. I had not realized that multiple applications had started using this library. :(.

**Comment by darix** [comment]
Hehe we just love your work and upgraded regularly!

**Comment by probonopd** [comment]
It appears that with harfbuzz 3.0.0 all existing software that uses harfbuzz is broken:

```
It appears FreeBSD% electron10
ld-elf.so.1: /usr/local/bin/electron10: Undefined symbol "hb_subset_input_set_retain_gids"
FreeBSD% electron12
ld-elf.so.1: /usr/local/bin/electron12: Undefined symbol "hb_subset_input_set_retain_gids"
```

Can you please re-introduce `hb_subset_input_set_retain_gids` and promise to never remove symbols again without increasing the major number after the `.so.`. (I find it confusing that it is still `libharfbuzz.so.0` and not `libharfbuzz.so.3.0.0` by the way.)

**Comment by DimStar77** [comment]
Just to add here: as long as there are apps in the wild that use `hb_subset_input_set_retain_gids` and libharfbuzz-subset sticks to .so.0, there is no sensible way for any distro to update to HB 3.x without accepting to break existing/working apps. For this reason, for example, openSUSE is still pinned to 2.9.1

We can't realistically expect the world to recompile because ABI was broken.

**Comment by khaledhosny** [comment]
There were only two codebases using this API, Chrome which bundles its own HarfBuzz and were knowingly using an unstable API, and Scribus in its development version (no idea if it even made a release using hb-subset API). If distributions are building Chrome (and its forks) without the bundled the HarfBuzz, then it is something they have to mange as they see fit.

**Comment by khaledhosny** [comment]
This will break applications that have been updated in the meantime and they will have to be recompiled, so it will be treating one breakage with another.

**Comment by behdad** [comment]
You're dramatizing the situation. The other distros have moved on and the world has not fallen apart.

We are NOT going to release libharfbuzz-subset.so.1. The reason is clear:

We have been releasing libharfbuzz.so.0 for over 15 years. We will continue to do so. We like to release libharfbuz-subset.so.0 in tandem.

**Comment by cryptomilk** [comment]
For the future: Use https://github.com/ansasaki/abimap

**Comment by LeoniePhiline** [comment]
This change breaks Signal Desktop on OpenSUSE: https://www.reddit.com/r/openSUSE/comments/rbfgen/signal_electron_is_broken_again_anyone_else/

What is the right way to make this work again?

**Comment by probonopd** [comment]
Try forcefully downgrading `libharfbuzz-subset.so`.
