### ISSUE TITLE
harfbuzz 3.0.0 did not build correctly with glib enums updated after hb-style added

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3219]
src/hb-gobject-enums.cc:1017:1: error: no previous prototype for function 'hb_gobject_style_tag_get_type' [-Werror,-Wmissing-prototypes]
hb_gobject_style_tag_get_type ()
^

**Comment by behdad** [comment]
This shows a huge gap in our CI/CD setup.

**Comment by behdad** [comment]
cc @khaledhosny / @alerque

**Comment by behdad** [comment]
This line in top-level `Makefile.am` is supposed to make sure tarballs are created with gobject enabled, such that this kind of error does not happen:
```
DISTCHECK_CONFIGURE_FLAGS = \
        --enable-gtk-doc \
        --disable-doc-cross-references \
        --with-gobject \
        --enable-introspection \
        $(NULL)
```

Are tarballs made with meson now? Then we need something equivalent.

**Comment by behdad** [comment]
Umm. Nevermind. It might all be my setup. Closing until I'm convinced otherwise. Sorry for the noise.

**Comment by alerque** [comment]
No, tarballs as attached to releases are still built with autoconf/automake. And yes we do run `make distcheck`. In fact the source tarball that gets posted *is* the one generated during the distcheck run.

**Comment by behdad** [comment]
Thanks. I tracked down the problem with meson build picking up stale `hb-gobject-enums.h` from my old in-tree autotools non-gobject-enabled build. Ouch :))

**Comment by alerque** [comment]
Ah, that explains what #3218 was about too then.

**Comment by behdad** [comment]
> Ah, that explains what #3218 was about too then.

Correct..
