### ISSUE TITLE
Support morx table

### ISSUE THREAD

**Issue by srl295** [harfbuzz/harfbuzz#322]
(could also support `mort` but it is obsolete.)

note:
- ICU implementation including http://bugs.icu-project.org/trac/ticket/10950

Just filing this to track.

**Comment by ebraminio** [comment]
As https://github.com/harfbuzz/harfbuzz/commit/14ff3cbe0f30dea24e1bb175b1e8e41039f6afdc

Now `trak` (mostly done, right?) and `kerx` #839

**Comment by olivierberten** [comment]
Is there a way to choose between OT and AAT ? Some fonts have both and as far as I know, iOS supports only AAT while Windows supports only OT. This would be useful for testing fonts.

**Comment by behdad** [comment]
Umm.  Not currently.  Open a separate issue please.  Not super excited about it though.

**Comment by brawer** [comment]
iOS does support OpenType.

**Comment by behdad** [comment]
> Is there a way to choose between OT and AAT ? Some fonts have both and as far as I know, iOS supports only AAT while Windows supports only OT. This would be useful for testing fonts.

Reopening to add this control.  I need it for testing the implementation as well.

My current thinking is to rename the default shaper to "auto".  Then add aliases "ot", "aat", "ot-aat", and "aat-ot" that control which technology is used and in which order.

**Comment by behdad** [comment]
I decided to just add a env-var option to prefer 'aat' over ot.  HB_OPTIONS=aat.

**Comment by behdad** [comment]
Reopening again, as programmatic control is desired.

**Comment by behdad** [comment]
cc @drott

**Comment by khaledhosny** [comment]
This was kept open for https://github.com/harfbuzz/harfbuzz/issues/322#issuecomment-429047034, which is not yet addressed.

**Comment by behdad** [comment]
> This was kept open for [#322 (comment)](https://github.com/harfbuzz/harfbuzz/issues/322#issuecomment-429047034), which is not yet addressed.

Right.  Depending on how we decide to address https://github.com/harfbuzz/harfbuzz/issues/1348 maybe we don't need this.

**Comment by khaledhosny** [comment]
Closing now, the remaining part is tracked in #1391.
