### ISSUE TITLE
[README, minor] Redirect seems to be wrong from 

### ISSUE THREAD

**Issue by rubyFeedback** [harfbuzz/harfbuzz#3226]
Hey guys,

The README right now has this URL:

http://harfbuzz.org/

But if you go there, you are redirected towards:

https://github.com/harfbuzz/harfbuzz

I then went on to that link instead:

https://harfbuzz.github.io/

Which appears to be the "real" homepage. Perhaps the first URL is a left over before
things got moved? Anyway, just letting you guys know in case this seems wrong; the
redirect is pecualiar. It may be best to avoid any redirects and just use
https://harfbuzz.github.io/ directly then, if that is the main homepage now.

**Comment by rubyFeedback** [comment]
(Just to clarify: with README I meant the page layout you get when you visit:

https://github.com/harfbuzz/harfbuzz

The link can be found near the ~bottom.
)

**Comment by behdad** [comment]
> But if you go there, you are redirected towards:
> 
> https://github.com/harfbuzz/harfbuzz
> 
> I then went on to that link instead:
> 
> https://harfbuzz.github.io/

The `harfbuzz.githu.io` is our documentation home. The `github.com/harfbuzz/harfbuzz` is what I consider our main homepage.
