### ISSUE TITLE
3.0.0 removes symbols without bumping soversion

### ISSUE THREAD

**Issue by darix** [harfbuzz/harfbuzz#3229]
Running an app compiled with 2.9.1 against 3.0.0  fails with

```
/usr/lib64/chromium/chromium: symbol lookup error:
/usr/lib64/chromium/chromium: undefined symbol: hb_subset_input_set_retain_gids
```

Wouldnt this need a bump in the so version if you change the library in a backwards incompatible way?

**Comment by khaledhosny** [comment]
Duplicate of #3227

**Comment by khaledhosny** [comment]
Duplicate of #3216
