### ISSUE TITLE
[USE] Update overrides to upstream

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3234]
https://github.com/microsoft/font-tools/pull/16

**Comment by behdad** [comment]
There's lots of whitespace changes. Without whitespace there's just a few chars:
https://github.com/microsoft/font-tools/pull/16/files?diff=unified&w=1

**Comment by xadxura** [comment]
Yes, sorry about all the whitespace changes. Going forward, the spacing should stabilize. I wanted to better align for the copy and paste needed from Unicode files.

**Comment by xadxura** [comment]
#16 now merged. Thanks for your input!

**Comment by behdad** [comment]
All good. Thanks Andrew!

**Comment by dscorbett** [comment]
Done in #3243.
