### ISSUE TITLE
Joining of Ethiopic Numerals

### ISSUE THREAD

**Issue by NeilSureshPatel** [harfbuzz/harfbuzz#3238]
Currently, in order to have the joining behavior of Ethiopic numbers, the OT code for init, medi, and fina requires first making substitutions for medial positions and then using those substitutions to inform the beginning and end of the run of numbers to make the initial and final form substitutions. This is implemented in NotoSansEthiopic as follows: 

```
lookup StandardMedial {
    sub @Standard @Standard' @Standard by @Medial;
    sub @Medial @Standard' @Standard by @Medial;
} StandardMedial;

lookup Initial {
    sub @Standard' @StandardMedial by @Initial;
} Initial;

lookup Final {
    sub @InitialMedial @Standard' by @Final;
} Final;
```

This would be more straight forward to implement in the way other connected scripts are implemented, i.e. define only substitutions for each position and let the shaper determine the beginning and end of the run of numbers. This would make for more consistent implementations. I looked at ArabicShaping.txt and I see that there are no entries for the Ethiopic numbers. If these were added to ArabicShapic.txt would Harfbuzz be able to determine the bounds of run of numbers and allow for code like this?:

```
sub one-ethiopic by one-ethiopic.medi;
sub two-ethiopic by two-ethiopic.medi;
sub three-ethiopic by three-ethiopic.medi;
sub four-ethiopic by four-ethiopic.medi;
sub five-ethiopic by five-ethiopic.medi;
sub six-ethiopic by six-ethiopic.medi;
sub seven-ethiopic by seven-ethiopic.medi;
sub eight-ethiopic by eight-ethiopic.medi;
sub nine-ethiopic by nine-ethiopic.medi;
sub ten-ethiopic by ten-ethiopic.medi;
sub twenty-ethiopic by twenty-ethiopic.medi;
sub thirty-ethiopic by thirty-ethiopic.medi;
sub forty-ethiopic by forty-ethiopic.medi;
sub fifty-ethiopic by fifty-ethiopic.medi;
sub sixty-ethiopic by sixty-ethiopic.medi;
sub seventy-ethiopic by seventy-ethiopic.medi;
sub eighty-ethiopic by eighty-ethiopic.medi;
sub ninety-ethiopic by ninety-ethiopic.medi;
sub hundred-ethiopic by hundred-ethiopic.medi;
sub tenthousand-ethiopic by tenthousand-ethiopic.medi;
```

Ideal rendering:

![image](https://user-images.githubusercontent.com/46502494/135165406-f9de999d-b431-4e2c-8b0b-aa4e1a2a17bf.png)

**Comment by behdad** [comment]
Interesting. This would have been easier if at least Ethiopic was routed to USE. As it is, it's just going to the default shaper. So, no, unless we expand init/medi/fina/isol to the default shaper, which is how they were written originally but we never implemented them.

I'm open to reconsidering that or adding features to that effect.

cc @jfkthame @tiroj

**Comment by behdad** [comment]
What complicates this case more is that they are numbers, so whatever definition we come up with for init/medi/fina application needs to be robust to that. In the end I suppose you're better off just doing what you are doing.

**Comment by behdad** [comment]
Yet another idea is to extend the Syriac abbreviation mark mechanism to the default shaper and make it work for this.

**Comment by khaledhosny** [comment]
There have been interest a few years ago in defining features that work on word boundaries that would not be tied to ArabicShaping.txt or be script-specific.

I think it was @tiroj’s idea when the descriptions for isol/init/medi/fina were amended to reflect implementation reality.

I think the complication would be defining word boundaries since it is not something Open type layout engines are currently concerned with AFAIK.

**Comment by LornaSIL** [comment]
In the Abyssinica SIL project we have the individual bars as the default and just use the extended line as an alternate. We ended up using this bit of code for the lookup so we just have one lookup:

```
lookup DigitAlternates {
    # Ethiopic digits
    sub [@c_init @c_medi] @cno_init' @cno_init by @c_medi;
    sub [@c_init @c_medi] @cno_init' by @c_fina;
    sub @cno_init' @cno_init by @c_init;
} DigitAlternates;
```

**Comment by tiroj** [comment]
Also worth noting that joining of the bar across numbers is not a consistent preference or practice in Ethiopic manuscripts: some scribes joing the bars, some do not.
![image](https://user-images.githubusercontent.com/5614500/135324195-10ec8afa-5e7d-47f4-bb54-7d97b5ce1c69.png)

I would be wary of standardising joining behaviour at the Unicode level.

Note also that at the font implementation level there are multiple ways to implement the connected bars, including decomposing the base number shape and bars, and treating the latter as marks of contextual width/shape. A model that assumes application of init/medi/fina features would limit implementations.

**Comment by jfkthame** [comment]
I don't think using init/medi/fina would particularly limit implementations -- a font could simply not implement those features, and do its own contextual thing if preferred.

Nevertheless, I agree that this doesn't feel like something that should or needs to be standardised at the Unicode level; it can perfectly well be implemented as contextual rendering in fonts using existing generic mechanisms.

**Comment by NeilSureshPatel** [comment]
Thanks, everybody. I am not very familiar with which scripts are routed to which shapers across all platforms, so it good to know. I personally use the contextual alternate method like the one described by @LornaSIL since it is the most robust. I was mostly curious why some OT features are active for some scripts and not others and whether an upstream change to shaping properties would simplify that. It is clear that is not quite how things really work, even if on its face, init/medi/fina/isol features would seem to be the most intuitive way to implement connected forms to a type designer. I think a lot of designers rely on auto OT code generation in Glyphs which takes .init/.medi/.fina suffixes on glyph names and generate features in those respective OT feature tags. I think I will get in touch with the Glyphs folks and see if they can change that behavior where applicable.
