### ISSUE TITLE
How do I enable documentation with meson?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3242]

**Comment by behdad** [comment]
Or introspection?

**Comment by khaledhosny** [comment]
`-Ddocs=enable`? (the docs will still not be built by default though, you need to run `ninja harfbuzz-doc` to build them).

**Comment by khaledhosny** [comment]
`-Dintrospection=enabled`?

**Comment by khaledhosny** [comment]
`feature` options take `enabled`, `disabled`, or `auto`, while `boolean` options take `true` or `false`.

The closes thing to `./configure --help` is running `meson configure` in the source dir.

**Comment by behdad** [comment]
Thanks. I was searching around in meson.build and I didn't see where `HAVE_INTROSPECTION` or `HAVE_GTK_DOC` are defined. Now I understand they are defined by external files.



> The closes thing to `./configure --help` is running `meson configure` in the source dir.

Got it. Thanks.

The values are quite arbitrary: Some are true/false; others are enabled/disabled. And sorted alphabetically instead of logically grouped... Okay, let me try to play with this meson thing a bit more before suggesting changes. But again, I don't like it that it's too late to make changes to it.

**Comment by khaledhosny** [comment]
I think `feature` options are used when we want `auto`, while `boolean` options only take `true` or `false`.
