### ISSUE TITLE
calt not getting executed by default

### ISSUE THREAD

**Issue by murasu** [harfbuzz/harfbuzz#3244]
I have a `calt` feature in the font the goes like this:
```
script tml2;
sub pa-tamil pa-tamil' by pa-tamil.001;
```
CoreText executes this by default, but not Harfbuzz

<img width="1278" alt="Screenshot 2021-10-05 at 9 57 35 AM" src="https://user-images.githubusercontent.com/22926756/135948613-f3d4731f-f730-4c7c-aecc-f680b51fb96e.png">

The font is here: https://www.dropbox.com/s/8vg9ck7act9b07o/NotoSansTamil-Regular.ttf?dl=0

Here are the test strings: 
பப் பப்பாளி பப்பி
பப்பு பப்புவா பப்மெட்
பப்லு பப்லோ பப்ளிக்

The strings appear as below (green=CoreText)

<img width="1098" alt="Notification_Center" src="https://user-images.githubusercontent.com/22926756/135948891-7c5e7d2a-9499-4554-8b2a-7b2bfdc9d08e.png">

Shouldn't `calt` be active by default?

**Comment by jfkthame** [comment]
What does Uniscribe do with this example?

**Comment by murasu** [comment]
I do not have a Windows machine to test this on Uniscribe at this time, unfortunately. I checked it with Word on macOS. The `calt` feature is not executed, even if I turn on the option manually. 

<img width="450" alt="Notification_Center" src="https://user-images.githubusercontent.com/22926756/136006349-acd3049e-efbb-487c-96ef-33a72f7eb593.png">

The specs say `calt` should be [active by default](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-case), although the description _'Can be used with scripts that have optional, cursive styles'_ for script/language sensitivity is a bit vague. The idea for using this is indeed for a cursive style Tamil typeface, ultimately.

What I understand is DirectWrite has not caught up with the specs as Harfbuzz and CoreText have. For example, if I move the feature code in this example from `calt` to `rlig`, the substitution happens in both CoreText and Harfbuzz but not on Word for macOS. Using `rlig` in this case gives me what I need. But it makes more sense for it to be defined in `calt` as this is indeed contextual alternate :)

**Comment by khaledhosny** [comment]
HarfBuzz enables `calt` by default and it applies it here (lookup 7 below), but it does not seem to have an effect:
```
trace: start preprocess-text	buffer: <U+0BAA=0|U+0BAA=1|U+0BCD=1>
trace: end preprocess-text	buffer: <U+0BAA=0|U+0BAA=1|U+0BCD=1>
trace: start reorder	buffer: <U+0BAA=0|U+0BAA=1|U+0BCD=1>
trace: end reorder	buffer: <U+0BAA=0|U+0BAA=1|U+0BCD=1>
trace: start table GSUB	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: start reordering indic initial	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: end reordering indic initial	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: start lookup 1	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: end lookup 1	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: start lookup 4	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: end lookup 4	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: start reordering indic final	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: end reordering indic final	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: start lookup 5	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: end lookup 5	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: start lookup 6	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: end lookup 6	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: start lookup 7	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: end lookup 7	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: end table GSUB	buffer: [pa-tamil=0|pa-tamil=1|pulli-tamil=1]
trace: start table GPOS	buffer: [pa-tamil=0+778|pa-tamil=1+778|pulli-tamil=1+0]
trace: start lookup 0	buffer: [pa-tamil=0+778|pa-tamil=1+778|pulli-tamil=1+0]
trace: end lookup 0	buffer: [pa-tamil=0+778|pa-tamil=1+778|pulli-tamil=1+0]
trace: start lookup 1	buffer: [pa-tamil=0+778|pa-tamil=1+778|pulli-tamil=1+0]
trace: end lookup 1	buffer: [pa-tamil=0+778|pa-tamil=1+778|pulli-tamil=1@393,0+0]
trace: start lookup 2	buffer: [pa-tamil=0+778|pa-tamil=1+778|pulli-tamil=1@393,0+0]
trace: end lookup 2	buffer: [pa-tamil=0+778|pa-tamil=1+778|pulli-tamil=1@393,0+0]
trace: end table GPOS	buffer: [pa-tamil=0+778|pa-tamil=1+778|pulli-tamil=1@393,0+0]
```

HarfBuzz outputs matches DirectWrite and Uniscribe, though.

**Comment by jfkthame** [comment]
Is the problem that 'calt' doesn't get applied across syllable boundaries?

Looking at collect_features_indic, I see that we append 'calt' (and 'clig') to the Indic features *before* the _hb_clear_syllables callback, so I think this means they'll be constrained to the syllable. So moving the call to `map->add_gsub_pause (_hb_clear_syllables);` ahead of these `enable_feature` calls might produce the desired result here.

(Of course, it might also break something else.... I haven't tested.)

**Comment by behdad** [comment]
> Is the problem that 'calt' doesn't get applied across syllable boundaries?
> 
> Looking at `collect_features_indic()`, I see that we append 'calt' (and 'clig') to the Indic features _before_ the `_hb_clear_syllables` callback, so I think this means they'll be constrained to the syllable. So moving the call to `map->add_gsub_pause (_hb_clear_syllables);` ahead of these `enable_feature` calls might produce the desired result here.
> 
> (Of course, it might also break something else.... I haven't tested.)

This was done in 42d0f55cbc68285e22d713df7062e520af708c82 for Khmer. Now that we have separated Khmer shaper, we can undo that.
