### ISSUE TITLE
API for clamping plan layout to max line width

### ISSUE THREAD

**Issue by grandinj** [harfbuzz/harfbuzz#3265]
I'm trying to optimise a line breaking algortihm (in LibreOffice), which is running into problems with very long runs of text.

Because we're repeatedly doing layout out a very long line of text, while we search for line breaking positions.

And the bulk of time is ending up in hb_shape_full.

So what I'd like to do is to tell the shaper to stop once it hits the maximum line width (in pixels)

Is there already an API for that?

**Comment by behdad** [comment]
Hi @grandinj,

We don't have API for that. But we do have API that might help you, in terms of `HB_GLYPH_FLAG_UNSAFE_TO_BREAK`. See docs at:

https://harfbuzz.github.io/harfbuzz-hb-buffer.html#hb-glyph-flags-t

However, there's gotchas around it. See discussion at https://github.com/harfbuzz/harfbuzz/issues/1463

**Comment by grandinj** [comment]
Thank you very much, that is very useful API

**Comment by behdad** [comment]
Cool. Please come back with more needs whenever.

**Comment by behdad** [comment]
@grandinj so far this is what we have to offer: https://github.com/harfbuzz/harfbuzz/issues/1463#issuecomment-448081494

**Comment by behdad** [comment]
@grandinj please review this: https://github.com/harfbuzz/harfbuzz/pull/3297

**Comment by grandinj** [comment]
thanks, but that makes a whooshing sound - it's over my head :-)

I have a reasonable enough fix for the problem I encountered when I logged this issue, it's not perfect, but it gets "good enough" performance without needing to mess with the fragile shaping code in LibreOffice.

https://cgit.freedesktop.org/libreoffice/core/commit/?id=95cc31f15712bcd2b9829a4f9708374647af6e74
