### ISSUE TITLE
rounding issue with scales and h advance

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3274]
While adding some tests around glyph extents in pango, I've noticed the following discrepancy:

```
ERROR:../tests/testmisc.c:741:test_gravity_metrics2: assertion failed (log[PANGO_GRAVITY_SOUTH].width == - log[PANGO_GRAVITY_NORTH].width): (54700 == 54701)
```
This is comparing the h_advances for two hb_font_t's with the only difference between the two is that we
call
```
hb_font_set_scale (font, x_scale, y_scale);
hb_font_set_scale (font2, - x_scale, - y_scale); 
```
I would have expected:
```
hb_font_get_glyph_h_advance (font, glyph) == - hb_font_get_glyph_h_advance (font2, glyph);
```
but they are off by 1, as you can see above.

Smells like values getting truncated instead of rounded somewhere around where the scale is applied.

**Comment by behdad** [comment]
Weird. This is the responsible line. I wouldn't have expected that from it:
```
    return (hb_position_t) ((v * mult) >> 16);
```

https://github.com/harfbuzz/harfbuzz/blob/52ccdc78e67b57645a83c6a55268dc19bf562e04/src/hb-font.hh#L624

**Comment by behdad** [comment]
Can you attach a test font? Can you try reproducing with `hb-shape`?

**Comment by behdad** [comment]
Might be that the computed `mult` is off.

**Comment by matthiasclasen** [comment]
I am seeing this with Cantarell-VF.otf. The font description was just: "Cantarell 64". But it happens with any size, I tried 100, 20,...

**Comment by matthiasclasen** [comment]
My brief look at the harfbuzz code led me to suspect

```
      return (hb_position_t) (v * (int64_t) this->x_scale / this->parent->x_scale);
```
in parent_scale_x_distance. Might be wrong though

**Comment by behdad** [comment]
> in parent_scale_x_distance. Might be wrong though

If you make a sub-font, and the scales are different, then yeah, that might be it. Regardless, that's a good catch.

**Comment by matthiasclasen** [comment]
This fails:

```
static void
test_hb_scale (void)
{
  hb_blob_t *blob;
  hb_face_t *face;
  hb_font_t *font1;
  hb_font_t *font2;
  double scale;

  blob = hb_blob_create_from_file ("Cantarell-VF.otf");
  face = hb_face_create (blob, 0);
  font1 = hb_font_create (face);
  scale = 64 * 1024 * 96./72.;
  hb_font_set_scale (font1, scale, scale);

  font2 = hb_font_create (face);
  hb_font_set_scale (font1, - scale, - scale);

  assert (hb_font_get_glyph_h_advance (font1, 1) == - hb_font_get_glyph_h_advance (font2, 1));
}
```

**Comment by behdad** [comment]
>   hb_font_set_scale (font1, - scale, - scale);

You mean `font2`, not `font1`.

**Comment by behdad** [comment]
I can reproduce. Thanks.

**Comment by behdad** [comment]
> ```
>     return (hb_position_t) ((v * mult) >> 16);
> ```

This *does* truncate after all. Which is the correct behavior. What we want is that if the scale (`mult`) is negative, for it to truncate in the opposite direction. Let me think.

**Comment by behdad** [comment]
Humm. Actually. Let me tuck a round there and bite the cost.
