### ISSUE TITLE
HarfBuzz started aggregating Hant/Hans to Hani in hb_script_from_iso15924_tag

### ISSUE THREAD

**Issue by nona-google** [harfbuzz/harfbuzz#3279]
After [this change](https://github.com/harfbuzz/harfbuzz/pull/2747), `hb_script_from_iso15924_tag` started returning Hani for Hant/Hans.
i.e.

`hb_script_from_iso15924_tag("Hant")  // returns Hani`
`hb_script_from_iso15924_tag("Hans")  // returns Hani`

Is this an expected behavior change?

Android is using `hb_script_t` for sub tag matching (e.g. Hani should be supported by Hant, etc) and this behavior breaks it. Of course we can change our code not to use `hb_script_t` for this purpose, but just want to confirm whether this is expected change or not.

**Comment by behdad** [comment]
Humm. I'm not comfortable with this change either. @dscorbett was there a particular reason for this? I think we should revert it as clients might have been relying on old behavior.

**Comment by behdad** [comment]
Also, differentiating between Traditional vs Simplified Chinese via a script tag is definitely common practice. Making it impossible is not good :).

**Comment by dscorbett** [comment]
According to you in https://github.com/harfbuzz/harfbuzz/issues/2732#issuecomment-728600389, “`hb_script_t` represents Unicode scripts”. Unicode doesn’t distinguish simplified and traditional Han from generic Han and neither does OpenType. That’s why I merged them.

I don’t fully understand what Android is doing, but if you want to check whether a variant code (e.g. Hant) matches a normal code (e.g. Hani), couldn’t you check whether `hb_script_from_iso15924_tag(variant_code)` equals `hb_script_from_iso15924_tag(normal_code)`?

**Comment by nona-google** [comment]
Android uses subscrtip matching for choosing font from locales.
For example, the font of Hant should be used for Hant/Hani, but should not be used for Hans, etc.

This logic is fully implemented in Android and we just uses HarfBuzz type `hb_script_t` as a script type in it because we anyway use this script for HarfBuzz input as well. Then just realized this behavior change during regular library update. We will update the Android code not to use `hb_script_t` and convert it to `hb_script_t` just before calling HarfBuzz API, so there is no problems at all. I filed this ticket just want to making sure this is the expected behavior.

**Comment by behdad** [comment]
> According to you in [#2732 (comment)](https://github.com/harfbuzz/harfbuzz/issues/2732#issuecomment-728600389), “`hb_script_t` represents Unicode scripts”. Unicode doesn’t distinguish simplified and traditional Han from generic Han and neither does OpenType. That’s why I merged them.

The problem I see is that `hb_script_from_iso15924_tag` is not supposed to do any conversions. And while `hb_script_t` *defined values* correspond to Unicode scripts, we do allow *other values* to be used by users without being clobbered. That's what was violated by this change.

**Comment by behdad** [comment]
I guess we can call it water under the bridge at this point. All good.
