### ISSUE TITLE
Allow class values to be used as keys in hb_hashmap_t

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#3293]
In trying to create a hashmap of type: hb_hashmap_t<bytes_t, unsigned> I run into the issue that it's not possible to specify the invalid key in the template due to limitations of c++ 14:

error: non-type template parameters of class type only available with ‘-std=c++2a’ or ‘-std=gnu++2a’

**Comment by behdad** [comment]
The first error I get is that `hb_int_mint<>` is not specialized for that type:
```
../src/hb-map.hh: In function ‘int main(int, char**)’:
../src/hb-meta.hh:203:38: error: incomplete type ‘hb_int_min<hb_array_t<const char> >’ used in nested name specifier
  203 | #define hb_int_min(T) hb_int_min<T>::value
      |                                      ^~~~~
../src/hb-map.hh:38:68: note: in expansion of macro ‘hb_int_min’
   38 |    K kINVALID = hb_is_pointer (K) ? 0 : std::is_signed<K>::value ? hb_int_min (K) : (K) -1,
      |                                                                    ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.
ninja: build stopped: subcommand failed.
```

**Comment by garretrieger** [comment]
Oh sorry, I didn't include the actual change I made. This is what I did:
constexpr hb_bytes_t invalid;
hb_hashmap_t<hb_bytes_t, unsigned, invalid> the_map;
