### ISSUE TITLE
hb-view treats newlines differently, according to command-line-arg versus stdin

### ISSUE THREAD

**Issue by drj11** [harfbuzz/harfbuzz#3298]
I think this is a recent change, possibly with hb-view 3.0.0

With text from `stdin` a newline (ASCII LF, U+000A) will produce a break in the output.

With text on the command-line a newline will, generally, produce a `.notdef` box in the output.

Essentially the problem is that the two following Unix commands have different output:

    echo 'harf
    buzz' | hb-view /System/Library/Fonts/Supplemental/AppleGothic.ttf

    hb-view /System/Library/Fonts/Supplemental/AppleGothic.ttf 'harf
    buzz'

Note that both of the above commands have newlines directly embedded in shell strings. If you would prefer without:

    printf 'harf\nbuzz' | hb-view /System/Library/Fonts/Supplemental/AppleGothic.ttf

    hb-view /System/Library/Fonts/Supplemental/AppleGothic.ttf "$(printf 'harf\nbuzz')"

I would expect _harf_ and _buzz_ to appear on separate lines. And this used to be the case. Now this behaviour only happens when the text comes from stdin, supplying the text on the command line (either as text or using `-u`) has a different behaviour: a bad one, where i see a `.notdef` box.

Example of correct output; no `.notdef` box.

![good](https://user-images.githubusercontent.com/1215412/142178509-9c124e24-fa27-47ca-81c9-f5ec7fb4a000.png)

**Comment by behdad** [comment]
Yeah I changed this and now I regret it. Will think about it and see what we can do. Needed it for the batch mode. Sorry about that.

**Comment by drj11** [comment]
It's broken basically all my scripts (for example https://gitlab.com/drj11/ranalina/-/blob/main/test/kern-J2 ).

Can we have an option? Although it still seems weird that you would be in a situation where you _want_ newlines to show a `.notdef` box.

Alternatively, stretch goal, can hb-view honour U+2028 LINE SEPARATOR?

**Comment by behdad** [comment]
I'll def want to unbreak your scripts :).

**Comment by behdad** [comment]
In `--batch` mode we want to treat the line as a single input, but otherwise I'm happy to go back to the old behavior.

**Comment by behdad** [comment]
This was done in https://github.com/harfbuzz/harfbuzz/issues/3129
Maybe I revert and add an option then.

**Comment by drj11** [comment]
I've already changed some of my tools to feed characters to `hb-view` as stdin: https://gitlab.com/drj11/plak/-/commit/c1101c2ca26716475e7a355684b0f68f020b8f0f

**Comment by behdad** [comment]
Fixed. Sorry about the breakage again. We'll get a release out.
