### ISSUE TITLE
hb-subset fails on empty glyphs

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#3316]
Subsetting certain single characters, such as U+1BC11 DUPLOYAN LETTER TH, from [this font](https://github.com/dscorbett/duployan-test/blob/4449d6351da8a32219556b2f44f8fa2d38aaa6de/assets/fonts/Duployan-Regular.otf) fails.
```
$ curl -LOs https://github.com/dscorbett/duployan-test/raw/4449d6351da8a32219556b2f44f8fa2d38aaa6de/assets/fonts/Duployan-Regular.otf
$ hb-subset --output-file=subset.otf --unicodes=1bc11 Duployan-Regular.otf
error: Operation failed. Probably a bug. File github issue.
```
U+1BC11 is derived from U+1BC03 plus a dot, like how in Arabic ⟨ذ⟩ is derived from ⟨د⟩. In this font, derived letters get glyphs with no contours and 0 advance width. A lookup then decomposes each one into a plain letter plus one or more dots. The subsetter seems to fail when given a range containing any such letter.

**Comment by garretrieger** [comment]
Checked this and it's a failure of the offset overflow resolution for GSUB. I'll look into it and see what we can do.

**Comment by garretrieger** [comment]
Ok, so what's happening is there's ~3700 extension lookups which are all connected by shared nodes and so end up all in a single space. The resolver is splitting them off from the shared space one at a time but gives up after the current 10 iteration limit.

When there's this many lookups sharing a single space splitting them off one at a time is likely going to be a very inefficient way of finding a working resolution. I see two possible approaches:

1. If after the max iterations have been reached there's still an overflow within a space that can be further split, go nuclear and split each lookup into it's own space.
2. When the number of lookups in a shared space is very large, don't peel off lookups one at a time, instead repeatedly split the space(s) in half.

**Comment by behdad** [comment]
> The resolver is splitting them off from the shared space one at a time

What's the current algorithm?

I wonder if there's a good heuristic there... I can ask my theory friends.
