### ISSUE TITLE
hb-subset fails to subset Bungee COLR 

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/harfbuzz#3320]
I found a similar bug in fonttools subsetter https://github.com/fonttools/fonttools/issues/2461

but whereas fonttools crashes, hb-subset completes without error message but the COLR table is simply dropped from the subsetted font.

To reproduce: download the font from https://github.com/google/fonts/blob/17fd8411fad0c1fb14e4c8bd18c87f45f65454f8/ofl/bungeecolor/BungeeColor-Regular.ttf

and do

```
$ hb-subset --output-file=/tmp/BungeeColor-Regular.subset.ttf --text="À" BungeeColor-Regular.ttf 
```

You'll see the subset font has no COLR, only a CPAL table.

The expected result would be a COLR table containing these two color glyphs:

```xml
  <COLR>
    <version value="0"/>
    <ColorGlyph name=".notdef">
      <layer colorID="0" name=".notdef.alt001"/>
      <layer colorID="1" name=".notdef.alt002"/>
    </ColorGlyph>
    <ColorGlyph name="Agrave">
      <layer colorID="0" name="Agrave.alt001"/>
      <layer colorID="1" name="Agrave.alt002"/>
    </ColorGlyph>
  </COLR>
```

I suspect hb-subset COLR implementation has the same bug that fonttools' had, see the linked bug for details.

**Comment by qxliu76** [comment]
I'll work on it

**Comment by behdad** [comment]
Thanks @qxliu76
