### ISSUE TITLE
hb-subset claims success but the resulting font’s shaping is wrong

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#3323]
Subsetting Duployan-Regular.otf can produce a font that produces different output than the original font. The character being tested appears in the subset so both fonts should produce identical output.
```bash
curl -LOs https://github.com/dscorbett/duployan-test/raw/4449d6351da8a32219556b2f44f8fa2d38aaa6de/assets/fonts/Duployan-Regular.otf
hb-subset --output-file=subset.otf --unicodes='1BC08 1BCA0' Duployan-Regular.otf
for font in Duployan-Regular subset
do
    hb-view --font-size 128 --margin -128,0 -O png -o $font.png -u 1BC08 $font.otf
done
```
![Duployan-Regular.png](https://user-images.githubusercontent.com/1124347/145091098-03c7bffc-e280-4a6e-ade7-5fa7f7a978cb.png)
![subset.png](https://user-images.githubusercontent.com/1124347/145091123-562708ff-3f57-4921-b6ae-d553ba5d374e.png)
In this example, the subset font’s output has extra space on the left side. Tracing both Duployan-Regular.otf and subset.otf for that string shows that both intermediately produce the glyph `_.adx.500` but only the original font correctly substitutes it with `_.adx.0e0 _.adx.1e1 _.adx.3e2 _.adx.3e3 _.adx.1e4 _.adx.0e5 _.adx.0e6`, among other similar discrepancies.

**Comment by garretrieger** [comment]
Found the problem, we're hitting the HB_MAX_LOOKUP_INDICES limit during GSUB closure. Same issue as in https://github.com/harfbuzz/harfbuzz/pull/3318. I did some quick testing and the limit would need to be raised from the current 20,000 to 35,000 for this subsetting operation to not hit the limit.

**Comment by garretrieger** [comment]
FYI @qxliu76

**Comment by garretrieger** [comment]
In reviewing the operation counting code I found two issues:

1. In the lookup closure, we're double counting the lookups during recursion once in the recurse function call and a second time in the SubstLookup::closure_lookups() call. Which effectively halves the actual limit.
2. In the gsub glyph closure, we use the same lookup limit (20,000) as in the lookup closure, but the glyph closure iterates up to 32 times. Where each iteration will likely visit the full lookup graph. So in a font that uses the full iteration count that's only 625 lookup visits allowed per iteration. Which in a fairly complicated font is probably not hard to hit.

I think we should:
- Fix 1 and remove the double counting.
- Reset the operation count at the start of each iteration in glyph closure.

@behdad what do you think?

**Comment by garretrieger** [comment]
Or alternatively we could use a total limit during glyph closure of HB_CLOSURE_MAX_STAGES * HB_MAX_LOOKUP_INDICES

**Comment by behdad** [comment]
> * Fix 1 and remove the double counting.
> * Reset the operation count at the start of each iteration in glyph closure.

Sounds good.
