### ISSUE TITLE
Consider using a dedicated replacement glyph for missing spaces

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3340]
Currently, harfbuzz will replace all sorts of missing spaces by proper amounts of nothing. 
But it will __only__ do so if the font has an ASCII space glyph. I figure this is because decomposition can only happen if you have something to decompose into. But it forces pango to fake a 0x20 space glyph for icon fonts in order to benefits from hb' space smarts. 
If you would use a dedicated replacement glyph for missing spaces, you could probably provide smart space replacements for all spaces including 0x20.

**Comment by behdad** [comment]
We should use the buffer invisible-glyph for these, and we can do so for ASCII space itself as well.
