### ISSUE TITLE
Always prefer InitializeCriticalSection (...) for WIN32?

### ISSUE THREAD

**Issue by Benau** [harfbuzz/harfbuzz#3343]
It seems that after https://github.com/harfbuzz/harfbuzz/commit/cb2d71c648137f1bd7586d3ec05050f0db50865f it always prefers to use pthread in WIN32, it makes mingw build depend on libwinpthread.dll (which is not nice)

Maybe it can be done this way?
```c++

#elif !defined(HB_NO_MT) && !defined(HB_MUTEX_IMPL_STD_MUTEX) && defined(_WIN32)

typedef CRITICAL_SECTION hb_mutex_impl_t;
#if !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
#define hb_mutex_impl_init(M)	InitializeCriticalSectionEx (M, 0, 0)
#else
#define hb_mutex_impl_init(M)	InitializeCriticalSection (M)
#endif
#define hb_mutex_impl_lock(M)	EnterCriticalSection (M)
#define hb_mutex_impl_unlock(M)	LeaveCriticalSection (M)
#define hb_mutex_impl_finish(M)	DeleteCriticalSection (M)

#elif !defined(HB_NO_MT) && !defined(HB_MUTEX_IMPL_STD_MUTEX) && (defined(HAVE_PTHREAD) || defined(__APPLE__))

#include <pthread.h>
typedef pthread_mutex_t hb_mutex_impl_t;
#define hb_mutex_impl_init(M)	pthread_mutex_init (M, nullptr)
#define hb_mutex_impl_lock(M)	pthread_mutex_lock (M)
#define hb_mutex_impl_unlock(M)	pthread_mutex_unlock (M)
#define hb_mutex_impl_finish(M)	pthread_mutex_destroy (M)
```
(check for WIN32 first then the rest)

**Comment by behdad** [comment]
> it always prefers to use pthread in WIN32

Only if `HAVE_PTHREAD` is defined...

> Maybe it can be done this way?

Then one cannot choose between pthread or win32 mutex.

I don't have a strong opinion. If it used to be that way before and it worked, am fine making it that way again.

**Comment by behdad** [comment]
> It seems that after [cb2d71c](https://github.com/harfbuzz/harfbuzz/commit/cb2d71c648137f1bd7586d3ec05050f0db50865f)

I just don't see how that commit changed the order as you suggest.

**Comment by behdad** [comment]
Ping @Benau

**Comment by Benau** [comment]
oh sorry it's actually 19cd84b4e95190f7ee236cb15a60d4a6be7040a0 which causes this issue, maybe there can be some cmake flag to choose between pthread or win32 mutex

**Comment by behdad** [comment]
@Benau If you can submit a patch we'll merge. The CMake build system of ours is unmaintained.
