### ISSUE TITLE
Clarify docs of hb_ot_var_normalize_coords

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3345]
The docs directly copy some language from the OpenType spec:

> The minimum and maximum values for the axis are mapped to the interval [-1,1], with the default
> axis value mapped to 0.

But that doesn't make a ton of sense, given that the coordinates are returned as ints.

I assume that the function returns some fp presentation. But which one ? 16.16 or something else ?

**Comment by behdad** [comment]
It's 2.14.
