### ISSUE TITLE
Make design coordinates of a hb_font_t available

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3349]
There is hb_font_get_var_coords_design, but it is still hidden behind HB_EXPERIMENTAL_API

Without that, an api like

![Screenshot from 2022-01-02 09-42-14](https://user-images.githubusercontent.com/4834845/147879378-03b920ae-25b1-4c57-85af-98638a64fd5e.png)

is difficult to make work.

**Comment by behdad** [comment]
Ah yeah. Closing in preference to https://github.com/harfbuzz/harfbuzz/issues/1865#issuecomment-964385680
