### ISSUE TITLE
Add minimally-sufficient BCP-47 language matching implementation

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3354]
Currently using our hb-ot-name API is cumbersome because eg. asking for "en_US" language name fails because font has "en" language name only. Fix this by adding minimally-sufficient BCP-47 language matching implementation.

cc @matthiasclasen

**Comment by dscorbett** [comment]
It sounds like you want `get_index` to find an entry with a close enough language instead of necessarily exactly the same language. Is that right?

It would also make sense to change the language maps in hb-ot-name-language-static.hh to use more precise subtags, e.g. 0x0409 is `"en-US"` and 0x0809 is `"en-GB"`. The Microsoft language IDs all include regions; for each language we’ll have to pick one region as the default.

**Comment by behdad** [comment]
Sounds about right.

**Comment by matthiasclasen** [comment]
That would be great to have. I'd love to use it in pango too, if you expose some hb_language api for it

**Comment by behdad** [comment]
Also see the rudimentary `pango_language_matches`:
https://www.manpagez.com/html/pango/pango-1.36.8/pango-Scripts-and-Languages.php#pango-language-matches

**Comment by behdad** [comment]
> close enough language instead of necessarily exactly the same language. Is that right?

Not just close-enough. They might be exact language, but not exact language *tag*. Eg. `zh_CN` vs `zh-Hant-CN`, etc.

**Comment by behdad** [comment]
> What about macrolanguages: do you want e.g. the requested language tag `pes` to match a font’s 0x0429 (`fa-IR`)?

I'd say no because `pes` is not in common use.

**Comment by behdad** [comment]
> What about macrolanguages: do you want e.g. the requested language tag `pes` to match a font’s 0x0429 (`fa-IR`)?

But if you are automatically generating tables and it generates that, then sure, I have no problem with that.

**Comment by behdad** [comment]
This is actually duplicate of https://github.com/harfbuzz/harfbuzz/issues/1372

**Comment by behdad** [comment]
@matthiasclasen Maybe we can flesh out the API for this.

**Comment by behdad** [comment]
So, the logic in `hb-ot-tag` applies here, right @dscorbett? We just need to take that out of `hb-ot-tag` and move it somewhere more generic.

**Comment by behdad** [comment]
I added `hb_language_matches()` with a trivial prefix-matching implementation.
