### ISSUE TITLE
unintended locale-dependency in hb_variations_to_string 

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3355]
hb_variations_to_string uses %g which depends on the current locale.

If using xlocale.h is an option, you could simply wrap the snprintf call in a uselocale() pair:

```
  locale_t old_locale;
  old_locale = uselocale (get_C_locale ());
  snprintf (...);
  uselocale (old_locale);
```

**Comment by matthiasclasen** [comment]
Relevant css spec for number formats: https://www.w3.org/TR/css-values-3/#numbers

**Comment by behdad** [comment]
Is there a threadsafe solution, at least under glibc?

**Comment by matthiasclasen** [comment]
uselocale is that threadsafe solution

xlocale is about per-thread locales

for the parsing side, there is strtod_l

**Comment by behdad** [comment]
Got it. Thanks. We do it alright for parsing already.

**Comment by matthiasclasen** [comment]
I see. Yay for a handrolled, untested parser :)

**Comment by behdad** [comment]
I hear ya.

**Comment by matthiasclasen** [comment]
looking around, xlocale.h was nuked at some point, and the _l family is a gnu extension. So I guess uselocale() is the somewhat portable thing to use

**Comment by behdad** [comment]
PR please?

**Comment by matthiasclasen** [comment]
https://github.com/harfbuzz/harfbuzz/pull/3357
