### ISSUE TITLE
Code reorg for HarfBuzz-next

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3372]
The codebase, specifically the hb-ot-layout files, have grown out unmaintainable with the addition of the subsetter. So much that I have pulled the break on the addition of a variable-font instancer until a "refactoring" and "tech-debt payoff" happens first".

The refactoring and tech-debt payoff I had in mind was to move the subsetting code out of the main header files into its own header files, that is, out of class and into its own template-specialization methods. But that would make it really inconvenient and separate like code into different files.

Yesterday, Garret and I decided that a better way to cut the complexity is to go Java style and break down individual classes into separate files. Think of each lookup type into its own file. The file starts with the class members, then sanitize, then smaller more basic methods, then serialize, sanitize, then instancer, and we can keep adding more aspects without making the file less navigatable for finding the basic structure.

To that extent Garret quickly put a design document and sample PR together:

https://docs.google.com/document/d/1QIzgHMdnpC2bMVAegA61l1HJM2RUvShA5XZBXKeXeJA/

https://github.com/harfbuzz/harfbuzz/pull/3370

Let's reiterate and converge on a scheme and implement this.

After doing that, I also like to separate the C api into it's own c-api directory, and expose a usable C++ API which big clients like the browsers can directly use, which would provide better compiler optimization opportunity I think. But that would be a separate project.

cc @jfkthame @drott @bungeman @khaledhosny @rsheeter

**Comment by garretrieger** [comment]
I've moved the document to a new link which is publicly accessible: https://docs.google.com/document/d/1QIzgHMdnpC2bMVAegA61l1HJM2RUvShA5XZBXKeXeJA/edit#heading=h.9r9d3crafamd

**Comment by khaledhosny** [comment]
Sounds good. I somehow dislike deeply nested directory trees, as they make it harder to get an overview of the source files, but may be I need to use less primitive tools.

**Comment by mta452** [comment]
Nice to see HarfBuzz taking a more modular approach in its architecture. I would also like to add my thoughts in this regard.

* There should be a top level namespace `SFNT`.
* There can be namespaces related to specific technologies inside `SFNT`.
* Every table should have a dedicated namespace inside `SFNT` or inside the technology specific nested namespace.
* `OT` should be renamed `OpenType`. In general it should be considered best practice not to name any identifier with less than three characters and `OpenType` is not a very large identifier.
* There is no need for additional namespace `Layout`.
* There should be no namespace `GSUBGPOS`. It seems confusing. The related structs can go inside `Common` and type aliased in `GSUB` and `GPOS`.
* The top level struct of a specific table should be named `Table` inside its namespace.

So with above rules, the structure would become something like this.

`SNFT` -> `OpenType` -> `GSUB` -> `Table`
`SNFT` -> `OpenType` -> `GSUB` -> `SingleSubst`

**Comment by behdad** [comment]
Thanks Muhammad.

> * There should be a top level namespace `SFNT`.

`SFNT` is a container, and just one container. What would this namespace serve?

> * There can be namespaces related to specific technologies inside `SFNT`.

OpenType is the technology. `SFNT` is not.

> * `OT` should be renamed `OpenType`. In general it should be considered best practice not to name any identifier with less than three characters and `OpenType` is not a very large identifier.

I disagree. In this context we will be repeating this one identifier so many times that I would want it as short as possible.

> * There is no need for additional namespace `Layout`.

Why not? The layout / var / color breakdown is very useful. What's the point of throwing all tables into one namespace?

> * There should be no namespace `GSUBGPOS`. It seems confusing. The related structs can go inside `Common` and type aliased in `GSUB` and `GPOS`.

Maybe.

> * The top level struct of a specific table should be named `Table` inside its dedicated namespace.

I'm not yet convinced that we want to go to one directory per table.

Thanks for the input.

**Comment by behdad** [comment]
> I somehow dislike deeply nested directory trees, as they make it harder to get an overview of the source files, but may be I need to use less primitive tools.

I'm in your camp myself.

**Comment by mta452** [comment]
> `SFNT` is a container, and just one container. What would this namespace serve?

Yeah, the way I see it is that all tables should be grouped inside a single namespace. And `SFNT` seems suitable name for that since all technologies, TrueType, OpenType, etc. are built on this format.

> OpenType is the technology. SFNT is not.

If we think of tables, OpenType is a format. If we think of functionality, OpenType is a technology.

> I disagree. In this context we will be repeating this one identifier so many times that I would want it as short as possible.

Even if it is repeated many times, it will have no impact on the compiled code. On the other side, `OpenType` is much clearer compared to `OT` and it is not that long to be abbreviated. Plus it can be refactored fairly easily with any modern IDE.

> Why not? The layout / var / color breakdown is very useful. What's the point of throwing all tables into one namespace?

There are two ways to structure the tables. It should be either based on functionality or format / technology. Mixing both would be confusing in my opinion.

> I'm not yet convinced that we want to go to one directory per table.

I'm suggesting one directory for any top level table such as `GSUB`. In this directory, there should be one file per table. But it is not necessary as long as the structure of namespaces is being followed properly. However it is very useful to structure the directories on namespaces as well because the navigation and understanding becomes easier this way.

**Comment by behdad** [comment]
I suggest using C++14 at the same time.
