### ISSUE TITLE
A couple of anti-viruses see a threat

### ISSUE THREAD

**Issue by Exchie** [harfbuzz/harfbuzz#3382]
HarfBuzz 3.2.0.
At the path test/fuzzing/fonts and test/shape/data/aots/fonts a couple of AV's see a threat. A saw probably resembling issues, but now according to VirusTotal 8 AV's detect the problem.
![hb virustotal 8](https://user-images.githubusercontent.com/24848707/150009708-8a65f537-9d81-4909-a15c-e0b4ae0acc67.png)

**Comment by alerque** [comment]
c.f.  #2750

**Comment by behdad** [comment]
This keeps coming up. Don't know what to do about it.

**Comment by khaledhosny** [comment]
I think we will have to live with that. We want to test bad fonts, and anti virus applications want to be overzealous and block anything as if it is the plague (how the mere download of a corrupt font a security issue is beyond me).
