### ISSUE TITLE
Prepare for 3.3.0 release

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3393]
After https://github.com/harfbuzz/harfbuzz/pull/3297 lands.

**Comment by behdad** [comment]
We are ready for a release I think.

**Comment by behdad** [comment]
* New API:
- HB_GLYPH_FLAG_UNSAFE_TO_CONCAT
- hb_segment_properties_overlay()
- hb_buffer_create_similar()
- hb_font_[sg]et_synthetic_slant()
* Improved documentation.
* Internal code cleanup, using more C++ std lib.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/3.3.0
