### ISSUE TITLE
Subsetting bug: Noto Nastaliq Urdu 3.0

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#3397]
I just built a new version of NNU from AFDKO-converted sources, and the submitter is having issues with it.

```
$ shape master_ttf/NotoNastaliqUrdu-Regular.ttf 'سے'
[YehBarreeFin=1+355|SeenIni.outD2YB=0@0,419+984]

$ ~/others-repos/harfbuzz/build/util/hb-subset --unicodes='*' --glyph-names master_ttf/NotoNastaliqUrdu-Regular.ttf --layout-features="*"  -o NNU.ttf

$ shape NNU.ttf 'سبے'
[YehBarree=2+1409|OneDotBelowNS=1+0|Behx=1+600|Seen=0+1113]
```

Get the font from https://github.com/googlefonts/noto-fonts/blob/main/hinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf

**Comment by behdad** [comment]
The two sequences don't look the same.

**Comment by behdad** [comment]
I can reproduce though:
```
behdad:build 0 (main)$ util/hb-shape NotoNastaliqUrdu-Regular.ttf 'سے'
[YehBarreeFin=1+355|SeenIni.outD2YB=0@0,419+984]
behdad:build 0 (main)$ 
behdad:build 0 (main)$ util/hb-subset --unicodes='*' --glyph-names NotoNastaliqUrdu-Regular.ttf -o NNU.ttf
behdad:build 0 (main)$ util/hb-shape NNU.ttf 'سے'
[YehBarree=1+1409|Seen=0+1113]
```

**Comment by simoncozens** [comment]
Only the first few GSUB lookups are firing. ccmp is there, but nothing after that.

**Comment by behdad** [comment]
I wonder if any of our arbitrary limits are hit...

**Comment by garretrieger** [comment]
I produced a subset using pyftsubset and the same args, and confirmed that shapes the same as the original font. Then I compared the ttx of the pyftsubset and the hb subset. The main diff I see is 3 glyphs are missing from the harfbuzz version:

```
-    <mtx name="BehxMed.inT1outT2Seen" width="178" lsb="-29"/>
-    <mtx name="BehxMed.inT1outT2SeenWide" width="231" lsb="-29"/>
-    <mtx name="SeenMed.SWinGoutT2" width="139" lsb="-46"/>
```

 My guess is the glyph closure is missing including these glyphs. I'll dig a bit deeper into the closure results in fonttools vs hb and see if that is indeed the case. If it is then we'll need to debug the relevant closure code to try and figure out why these 3 glyphs get missed.

**Comment by simoncozens** [comment]
It isn't just those three glyphs. The problem is that almost all of the glyphs are selected by (very complicated) selection rules, and the whole GSUB table has been garbled. The `init` feature now looks like this:

```
      <FeatureRecord index="8">
        <FeatureTag value="init"/>
        <Feature>
          <!-- LookupCount=1 -->
          <LookupListIndex index="0" value="188"/>
        </Feature>
      </FeatureRecord>
...
      <Lookup index="188">
        <LookupType value="7"/>
        <LookupFlag value="0"/>
        <!-- SubTableCount=1 -->
        <ExtensionSubst index="0" Format="1">
          <ExtensionLookupType value="2"/>
          <MultipleSubst>
            <Substitution in="KafSep" out="KafSep,SharetKafNS"/>
          </MultipleSubst>
        </ExtensionSubst>
      </Lookup>
```

That's... not what it looked like before.

**Comment by garretrieger** [comment]
the final lookup closure is  based on the glyphs selected, so the first thing we need to do is make sure the subset is starting with the same glyph set. Once we've got that sorted we'll see if there's still diffs remaining in the layout tables.

**Comment by garretrieger** [comment]
FontTools does drop some glyphs and modify the layout table in comparison to the original file, so I'm currently focusing on the diff between fontTools and harfbuzz first. Since the fontTools version appears to shape correctly still.

**Comment by garretrieger** [comment]
I modified the closure to manually insert the 3 missing glyphs in harfbuzz and that cleared up the diffs and I now get the correct shaping. So looks like it is indeed an issue in the glyph closure.

**Comment by garretrieger** [comment]
Getting closer:
- The substitution that produces one of the missing glyphs isn't being hit by the closure.
- That substitution is referenced from a ChainContextFormat2 subtable.
- The current glyph set contains the correct glyph to trigger closure of the appropriate ChainClassSet
- However, a prior closure of ChainClassSet incorrectly modifies the current glyph set, resulting in the removal of the glyph needed to trigger the ChainClassSet of interest.
