### ISSUE TITLE
Weird kerning in 3.3

### ISSUE THREAD

**Issue by HanabishiRecca** [harfbuzz/harfbuzz#3408]
After updating to 3.3 (Arch Linux official `harfbuzz` package) fonts kerning became weird.

Examples:
![image](https://user-images.githubusercontent.com/13597663/152077001-aa1fa4bc-04e1-47d4-a0aa-ab0f593d1be4.png)
![image](https://user-images.githubusercontent.com/13597663/152077074-f19001b7-ee4e-49de-9c2d-ce0446efb1aa.png)
![image](https://user-images.githubusercontent.com/13597663/152077137-83f73ca0-efb8-4aae-a182-f6d638644628.png)
![image](https://user-images.githubusercontent.com/13597663/152077999-f4ce021e-688f-4b85-b988-b4217b271aae.png)
![image](https://user-images.githubusercontent.com/13597663/152078144-cbc9eaa3-719f-4739-b8f6-dcb3efb0edd5.png)

The distortion strength varies for different fonts.
Also I noticed that this effect is only present when `fontconfig` hinting set to `hintmedium` or `hintfull`. And not present when set to `hintnone` or `hintslight`.
Also seems like this is mostly noticable in Qt apps.

**Comment by behdad** [comment]
What font for example? Can you give me reproduction commandlines with hb-view? hb-view takes `--ft-load-flags`. I don't remember how the hintmedium / hintfull map to those.

**Comment by behdad** [comment]
> Also seems like this is mostly noticable in Qt apps.

Also, qualify this please. Is it noticeable in any other apps?

**Comment by behdad** [comment]
Can you test whether the following patch to HarfBuzz fixes the issue:
```patch
diff --git a/src/hb-ot-layout-gpos-table.hh b/src/hb-ot-layout-gpos-table.hh
index e28c951f3..b5767f386 100644
--- a/src/hb-ot-layout-gpos-table.hh
+++ b/src/hb-ot-layout-gpos-table.hh
@@ -1587,6 +1587,7 @@ struct PairPosFormat2
 
     /* Isolate simple kerning and apply it half to each side.
      * Results in better cursor positinoing / underline drawing. */
+    if (0)
     {
       if (!len2)
       {
```

**Comment by HanabishiRecca** [comment]
> Can you test whether the following patch to HarfBuzz fixes the issue:

Yes, it fixes the issue.

**Comment by behdad** [comment]
Okay, reverted that change.

**Comment by behdad** [comment]
We'll get a release out soon. @khaledhosny

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/3.3.2
