### ISSUE TITLE
hb-view doesn't auto compute font extents for CBDT color font

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/harfbuzz#3409]
If I try to render a CBDT/CBLC font (e.g. NotoColorEmoji.ttf) with hb-view, the resulting PNG is always cropped. I need to add very large --margin in order to display something (but then the image is not centered). Manually setting --font-extents doesn't help either, or I can't figure out values that make it look ok.

This is the command I run:

```sh
$ hb-view -o /tmp/AD.png -u 1F1E6,1F1E9 Font.ttf
```

I get this (which is only a small portion of the actual color glyph):

![image](https://user-images.githubusercontent.com/6939968/152149683-b04ceefb-fd65-4f20-981a-341c864d7262.png)

The test font is attached in [test-cbdt-font.zip](https://github.com/harfbuzz/harfbuzz/files/7986149/test-cbdt-font.zip) along with a static html file that should display the correct image in Google Chrome - which looks like this:

<img width="84" alt="Screenshot 2022-02-02 at 12 00 35" src="https://user-images.githubusercontent.com/6939968/152149775-2cf40a31-3674-40eb-8daf-bf097dc141d0.png">

Am I doing something wrong?

**Comment by anthrotype** [comment]
forgot to say, I'm running hb-view (compiled from source from latest HEAD) on macOS 12.1

**Comment by behdad** [comment]
It's a problem hb-ft has with bitmap fonts. It's known issue. I think it works if you pass --font-funcs=ot. Probably duplicate of https://github.com/harfbuzz/harfbuzz/issues/489

**Comment by anthrotype** [comment]
thanks, using --font-funcs=ot works for me!
