### ISSUE TITLE
[ot-layout] Undeprecate hb_ot_tag_from_script() and hb_ot_tag_from_language()?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3439]
Just helping @matthiasclasen who needed to convert `hb_script_t` and a `hb_language_t` to their respective `hb_tag_t` for use with `hb_ot_layout_get_baseline()`, it took me a while to realize that we deprecated `hb_ot_tag_from_script()` and `hb_ot_tag_from_language()`. Moving those to `hb-ot-deprecated.h` made them invisible both from headers and from documentation...

It feels to me like there's still some uses that they are the best function for one's use.  Should we undeprecate them and just document them better and point to the alternative?

**Comment by behdad** [comment]
I guess the question also is, for eg. Devanagari, which tag one would use with `BASE` table. I guess the v1 tags? So, these functions have valid use with `BASE` table at least still...

**Comment by dscorbett** [comment]
I have opened MicrosoftDocs/typography-issues#912 requesting clarification.

`hb_ot_tags_from_script` returns the top two tags for a script. For example, for Devanagari it returns 'dev3' and 'dev2'. This would not be useful for BASE. It is probably not useful for anything. That is why it is deprecated.

`hb_ot_tag_from_language` returns the top tag for a language. Many languages have multiple relevant tags; for example, Malayalam has 'MAL ' and 'MLR '. The top tag is just the one that has precedence if the font supports more than one: it is not necessarily the most likely; for example, HYE0 has precedence over 'HYE ' but is much less likely to exist in any font. This function is therefore also not right for BASE.

Are BASE’s script and language tags supposed to match what the rest of the font uses (whether GSUB uses 'deva' and/or 'dev2', etc.)? If so, HarfBuzz’s baseline API should use `hb_ot_tags_from_script_and_language` to get all possible tags, then filter them down to what the font supports. If not, you’ll need a new function that returns exactly one script/language tag, but not necessarily the one with the highest precedence. Either way, the BASE table is underdocumented and these functions shouldn’t be undeprecated.

**Comment by behdad** [comment]
I noticed hb-graphite2 is also needing this and doing the "last tag" trick.

I suggest we do this:
- Undeprecate `hb_ot_tag_from_language`.
- Add `hb_ot_tag_from_script`.

**Comment by dscorbett** [comment]
Graphite doesn’t seem to actually use the script (https://github.com/silnrsi/graphite/blob/27572742003b93dc53dc02c01c237b72c6c25f54/src/Face.cpp#L197-L205):
```cpp
const Silf *Face::chooseSilf(uint32 script) const
{
    if (m_numSilf == 0)
        return NULL;
    else if (m_numSilf == 1 || script == 0)
        return m_silfs;
    else // do more work here
        return m_silfs;
}
```
Instead of undeprecating anything, `_hb_graphite2_shape` can be simplified to pass `0` as the script.

**Comment by behdad** [comment]
Thanks!
