### ISSUE TITLE
hb_ot_layout_get_horizontal_baseline_tag_for_script vs defaultBaselineIndex

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3446]
The BASE table contains defaultBaselineIndex fields which let the font specify which baseline to use by default per script.

Should hb_ot_layout_get_horizontal_baseline_tag_for_script use that field instead of hardcoding the script-to-baseline mapping ?

**Comment by behdad** [comment]
> The BASE table contains defaultBaselineIndex fields which let the font specify which baseline to use by default per script.

Indeed. I had missed that before.

> Should hb_ot_layout_get_horizontal_baseline_tag_for_script use that field instead of hardcoding the script-to-baseline mapping ?

The question is whether we can rely on that information... I don't think we can. How would we use it? Maybe if our function doesn't know anything, yes. But even then, we have to go out of our way to try to map what the font defaultBaselineIndex says, to a baselineTag, such that we can use the same tag for other shaping runs... Right?

**Comment by behdad** [comment]
That said, we can at least expose that information somehow.

**Comment by matthiasclasen** [comment]
> 
> The question is whether we can rely on that information... I don't think we can. How would we use it? Maybe if our function doesn't know anything, yes. But even then, we have to go out of our way to try to map what the font defaultBaselineIndex says, to a baselineTag, such that we can use the same tag for other shaping runs... Right?

Yes.

I wonder if there could be cases where the font contains only the one baseline that it wants to set defaultBaselineIndex to.

**Comment by behdad** [comment]
To me it feels like something over-engineered and to be ignored. This mechanism seems like part of the script logic and not to be controlled by the font. So what's default baseline per script is to be hardcoded, not encoded per font.

**Comment by matthiasclasen** [comment]
I'm fine with ignoring it

**Comment by behdad** [comment]
In other words: what would you do if a Latin font says it defaults to hanging baseline? Align the line hanging?
