### ISSUE TITLE
'OSMemoryBarrier' is deprecated in macOS 10.12

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#345]
Building with latest XCode I got lots of these warnings:

```
warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_thread_fence() from <atomic> instead [-Wdeprecated-declarations]
warning: 'OSAtomicAdd32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add() from <atomic> instead [-Wdeprecated-declarations]
warning: 'OSAtomicCompareAndSwap64Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Wdeprecated-declarations]
```

**Comment by behdad** [comment]
Feel free to patch conditionally.  Thanks.

**Comment by behdad** [comment]
Maybe we should support C++11 and use atomic on all platforms?

**Comment by khaledhosny** [comment]
But this would make us dependent on the C++ standard library on all platforms. C11 has a similar C API, may be we can use it if supported by platform/compiler and fallback to existing code otherwise?

**Comment by behdad** [comment]
> But this would make us dependent on the C++ standard library on all platforms.

Right.  Not sure if that's still a concern.

>  C11 has a similar C API, may be we can use it if supported by platform/compiler and fallback to existing code otherwise?

Whatever works.  I do prefer not changing this much as it seems to have been working.

**Comment by behdad** [comment]
What's suggested work item here?

**Comment by khaledhosny** [comment]
Someone familiar with the new C/C++ atomics adds support for them. It should be e.g. used by default when supported and else fall back to the existing implementations. I might give it a try at some point, unless some one beat me to it.

**Comment by behdad** [comment]
There's an alternative approach in https://bugs.freedesktop.org/show_bug.cgi?id=90305

Let's give that one a try?  I'll find some time to look into https://github.com/behdad/harfbuzz/pull/486 as well.

**Comment by behdad** [comment]
Also, to make TSan happy, we should replace `get_unsafe` to do an atomic fetch with `memory_order_relaxed` ordering instead of being a non-atomic read.

**Comment by waywardmonkeys** [comment]
My changes in #676 remove this warning by using the compiler primitives rather than the macOS APIs.

**Comment by behdad** [comment]
Let's see how the bots like my implementation.
