### ISSUE TITLE
VS 2015: Build failure regarding std::hash

### ISSUE THREAD

**Issue by fanc999** [harfbuzz/harfbuzz#3451]
Hi,

From the closed PR #3448, when building on Visual Studio 2015, I was met with the compiler error on the following:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xstddef(377): error C2338: The C++ Standard doesn't provide a hash for this type.
c:\users\fanc999\harfbuzz\src\hb-algs.hh(230): note: see reference to class template instantiation 'std::hash<hb_serialize_context_t::object_t>' being compiled
c:\users\fanc999\harfbuzz\src\hb-map.hh(199): note: while compiling class template member function 'bool hb_hashmap_t<const hb_serialize_context_t::object_t *,hb_serialize_context_t::objidx_t,const hb_serialize_context_t::object_t *,hb_serialize_context_t::objidx_t,0x0,0>::set(K,const V &)'
        with
        [
            K=const hb_serialize_context_t::object_t *,
            V=hb_serialize_context_t::objidx_t
        ]
c:\users\fanc999\harfbuzz\src\hb-serialize.hh(336): note: see reference to function template instantiation 'bool hb_hashmap_t<const hb_serialize_context_t::object_t *,hb_serialize_context_t::objidx_t,const hb_serialize_context_t::object_t *,hb_serialize_context_t::objidx_t,0x0,0>::set(K,const V &)' being compiled
        with
        [
            K=const hb_serialize_context_t::object_t *,
            V=hb_serialize_context_t::objidx_t
        ]
c:\users\fanc999\harfbuzz\src\hb-serialize.hh(680): note: see reference to class template instantiation 'hb_hashmap_t<const hb_serialize_context_t::object_t *,hb_serialize_context_t::objidx_t,const hb_serialize_context_t::object_t *,hb_serialize_context_t::objidx_t,0x0,0>' being compiled
```

This issue attempts to analyze what is going on with Visual Studio 2015 builds and/or to see whether we want to continue to support Visual Studio 2015 to build HarfBuzz or just require Visual Studio 2017 or later.  To use HarfBuzz though, Visual Studio 2015 or later should be enough as long as the running system has a new-enough UCRT package installed.

With blessings, thank you!

**Comment by fanc999** [comment]
For records, this is the part in the Visual Studio 2015 headers that tripped up the static_assert (i.e. C2338)
```
	// TEMPLATE STRUCT hash
template<class _Kty>
	struct hash
		: public _Bitwise_hash<_Kty>
	{	// hash functor for enums
	static constexpr bool _Value = __is_enum(_Kty);
	static_assert(_Value,
		"The C++ Standard doesn't provide a hash for this type.");
	};
```

**Comment by behdad** [comment]
You shouldn't get a compiler error because of SFINAE to begin with.

If I understand correctly we have MSVC bots of later versions that compiler HarfBuzz fine, correct? If yes, I suggest we just declare this version of VS unsupported. Please verify. Thanks.

**Comment by fanc999** [comment]
Hi @behdad,

As mentioned in issue #3379[1], I was able to successfully build (and run the tests) for the latest Visual Studio 2017, 2019 and 2022 out-of-the-box, I think it's fine with me to drop support for building with Visual Studio 2015.

For using HarfBuzz with Visual Studio 2015 or later, I think we should be able to do just fine unless the public headers added things that required later Visual Studio installations (for instance, I was able to build and run Pango 1.50.x with Visual Studio 2015 against HarfBuzz built with Visual Studio 2017 just fine).  The nice thing is that VS2015 and later builds use the same CRT DLLs, :)

Thanks for the time and patience with me :-).

[1]: https://github.com/harfbuzz/harfbuzz/issues/3379#issuecomment-1043870287

With blessings, thank you!

**Comment by behdad** [comment]
> I was able to successfully build (and run the tests) for the latest Visual Studio 2017, 2019 and 2022 out-of-the-box

Which MSVC versions do those translate to? Does the MSVC 2019 job reflect VS 2019 for example?

> I think it's fine with me to drop support for building with Visual Studio 2015.

Okay thanks.

**Comment by fanc999** [comment]
Hi @behdad,

> Which MSVC versions do those translate to? Does the MSVC 2019 job reflect VS 2019 for example?

Yup, Visual Studio=MSVC in this case, so MSVC 2019 job reflects VS2019.
