### ISSUE TITLE
Expose optical bounds

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3458]
As discussed in San Miguel, this information needs to be applied outside of shaping individual runs (when post-processing a line), so pango would need a getter for the boundary adjustments for a glyph. Something like

    hb_bool_t hb_ot_layout_get_optical_bounds (hb_font_t *font, 
                                               hb_direction_t direction,
                                               hb_codepoint_t glyph,
                                               hb_position_t *left_bound,
                                               hb_position_t *right_bound);

**Comment by behdad** [comment]
See https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#opbd

**Comment by behdad** [comment]
What's direction here for then?

**Comment by behdad** [comment]
A much nicer API would read:
```
hb_position_t hb_ot_layout_get_optical_bounds (hb_font_t *font,
                                               hb_direction_t direction,
                                               hb_codepoint_t glyph);
```

**Comment by behdad** [comment]
But this being `ot-layout`, we need script/language to find the respective feature. Ugh.

**Comment by behdad** [comment]
> But this being `ot-layout`, we need script/language to find the respective feature. Ugh.

The feature registry says "Script/language sensitivity: None.". So it's one of those that we just need to find any feature with the tag and run with it. We just need to cache the feature in the accelerator...

**Comment by matthiasclasen** [comment]
> What's direction here for then?

I was thinking for deciding between left/right and top/bottom

**Comment by behdad** [comment]
> I was thinking for deciding between left/right and top/bottom

Right. But since hb_direction_t has four values, the separate right/left is redundant.

Also, OpenType currently has no features for top/bottom.

Moreover, OpenType is unclear how such feature should be implemented.

**Comment by matthiasclasen** [comment]
My understanding of how this would be implemented is that pango would shape runs until it has a line assembled, then it asks hb for the left margin for the first char and the right margin of the last char, and adjusts the line width and positioning by those values, before justification (and it would only do that for justified lines...).

I have some renewed interest in this since I found that the linux libertine actually has the lfbd and rtbd features.

**Comment by behdad** [comment]
> first char and the right margin of the last char

Glyphs.



> and it would only do that for justified lines

One side should be done for non-justified lines too I would think.

I'll look into this again.

**Comment by n8willis** [comment]
Would you also need to check that the first/last glyph isn't a non-spacing mark?

**Comment by behdad** [comment]
> Would you also need to check that the first/last glyph isn't a non-spacing mark?

Right.

**Comment by matthiasclasen** [comment]
The first/last glyph could also be a ligature. I guess in theory, lfbd/rtbd should provide the right information for ligatures as well. If fonts actually do that... ?

**Comment by n8willis** [comment]
I guess I think the "correct" thing for the font to do would be to include lfbd+rtbd for ligature glyphs as well, yeah. The spec just says "glyphs".

If it doesn't, there's the possibility of fallback: use lfbd(f) and rtbd(i) for the "fi" and "ffi" ligatures, etc. Or the bounds for a base glyph if the accented version isn't included. Probably some others....

**Comment by matthiasclasen** [comment]
Yeah. More fun code to write

**Comment by n8willis** [comment]
Right; Pango has a full strategy (or possibly several) to consider there. What I was saying is that, at the HarfBuzz level, it doesn't seem wrong to return a fallback/synthetic bound for a ligature or accented-base glyph, if (i) there isn't one in the font and (ii) there is one for the fallback glyph(s).

The accented base might have gone through recomposition during normalization anyway, and if "a" had a `rtbd` but the glyph got replaced by a precomposed "á" that _doesn't_ have a `rtbd`, personally I would prefer (or even expect) to get the `rtbd` of the "a".

**Comment by n8willis** [comment]
...although, having just said that, I may be making assumptions that only hold for Latin. And I haven't thought about how returning fallback bounds would interfere with other features like `ccmp` or whatever. So, grain of salt.

**Comment by khaledhosny** [comment]
Another potential use of optical bounds https://typedrawers.com/discussion/4527/glyph-sidebearings-and-text-alignment

**Comment by n8willis** [comment]
> One side should be done for non-justified lines too I would think.

I interpreted that to mean one-or-both-sides justified, but it's better to be clear I guess.

That said, I almost hate to bring it up, but if the bounds for a given font _do_ work, they would be useful for centered lines as well. Most likely noticed with there are 2+ centered lines stacked together.

People certainly complain when there's a hanging-punctuation thing that makes a pair of centered lines look out-of-skew (hanging punctuation probably ought to be handled separately, but in a sense it's a corner case of optical bounds).
