### ISSUE TITLE
USE override for A982 no longer needed

### ISSUE THREAD

**Issue by NorbertLindenberg** [harfbuzz/harfbuzz#3463]
gen-use-table.py has an override for the Indic syllabic category of A982:

> 		# TODO: https://github.com/microsoft/font-tools/issues/1
>		if U == 0xA982: UISC = Consonant_Succeeding_Repha

This override is no longer needed, as the incorrect Microsoft override has been removed (again). It’s also wrong, because the InSC of this character has been corrected to Consonant_Final in Unicode 14.

**Comment by dscorbett** [comment]
This was fixed in #3475.
