### ISSUE TITLE
Question: Is directWrtite required by default dll builds?

### ISSUE THREAD

**Issue by EyeAndTea** [harfbuzz/harfbuzz#3478]
Greetings.

The dlls for Harfbuzz distributed for the 4.0.1 release appear to require DirectWrite. It is my understanding from elsewhere that by default this would not be the case. I got an error for a missing "dwrite.dll" under Windows XP.

**Comment by behdad** [comment]
No DirectWrite is not required by HarfBuzz. The Windows binaries we distribute might have it enabled for testing reasons. It's unfortunate what you are facing. cc @khaledhosny

**Comment by behdad** [comment]
I'm actually confused as to how it was being linked, given that I just added it to the link line here:
https://github.com/harfbuzz/harfbuzz/commit/ea5131507a723b4858f6a90584351ac14a990ecb

because without it it was failing to link using mingw32 for me. Any ideas?

**Comment by behdad** [comment]
I see the meson build is linking, but not the autotools build. That should explain I guess.

**Comment by lb90** [comment]
Hi! I can help on this. The problem is that https://github.com/harfbuzz/harfbuzz/pull/3670 causes a segfault on MSVC builds?

**Comment by behdad** [comment]
> Hi! I can help on this. The problem is that #3670 causes a segfault on MSVC builds?

Yes.

> How can one launch the failing test manually?

Just invoking hb-view with any font and text, and `--shaper=directwrite` should do.
