### ISSUE TITLE
`HB_NO_METRICS` build fails on Chrome Android

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#3482]
`hb_ot_layout_get_baseline_with_fallback` is available and unconditionally needs `hb_ot_metrics_get_position`, compare @bungeman 's analaysis in https://chromium-review.googlesource.com/c/chromium/src/+/3521601/6/third_party/harfbuzz-ng/BUILD.gn#349

**Comment by behdad** [comment]
I suggest we make baseline API conditional on HB_NO_METRICS as well. cc @matthiasclasen

**Comment by behdad** [comment]
> I suggest we make baseline API conditional on HB_NO_METRICS as well. cc @matthiasclasen

Humm. There's `HB_NO_BASE` for that. @matthiasclasen can you make the `hb_ot_metrics_get_position()` call guarded please? Also, the `hb_ot_metrics_get_position()` needs to be replaced with the `_with_fallback()` version.
