### ISSUE TITLE
[hb-subset] Subsetting CFF font requires unused character to be included for correct rendering

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#3486]
![image](https://user-images.githubusercontent.com/1021784/159037693-138d7989-9ee4-4568-b145-9b77f82a1c70.png)
[repro.zip](https://github.com/harfbuzz/harfbuzz/files/8305955/repro.zip)

Repro:
* Unpack zip
* Open vertical.html in Chrome Linux (_Edit:_ Easiest to repro on Linux)
* Observe positioning of third ideograph

Expected: Red overlay should appear in the same position as the black underlying glyph and not be positioned further down.

The subsetted font is produced with:
`$ hb-subset --output-file=notosanscjkjpsub.otf notosanscjkjp.otf --unicodes=3084,304d,306b`

If I add **U+302B** to the subsetted file, the rendering and positioning look correct. "Correct" because I would not expect an unused character to have an effect on the output.
`$ hb-subset --output-file=notosanscjkjpsub.otf notosanscjkjp.otf --unicodes=3084,304d,306b,302b`

Issue equivalent to fonttools subsetting issue: https://github.com/fonttools/fonttools/issues/2554

**Comment by drott** [comment]
TTX Diff: https://gist.github.com/drott/fcec7ea929282dfb20e03404fc2b33bb

**Comment by drott** [comment]
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/fonts/opentype/open_type_vertical_data.cc does take different code paths depending on existence of VORG, it seems.

**Comment by behdad** [comment]
Checking the diff is fairly clear to me that this is NOT a subsetting bug. Does this reproduce at all using non-FreeType? My guess is that something in FreeType is acting different, a hinter or autohinter.



> https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/fonts/opentype/open_type_vertical_data.cc does take different code paths depending on existence of VORG, it seems.

Right. But VORG exists in both, just having no entry in one and one entry in the other.... a minute later, yep: there's an underflow error in that code's sanitization: 
```
  size_t RequiredSize() const {
    return sizeof(*this) +
           sizeof(VertOriginYMetrics) * (num_vert_origin_y_metrics - 1);
  }
```
`num_vert_origin_y_metrics` is unsigned, and 0 in the bad font. This makes it reject the `VORG` table...

**Comment by khaledhosny** [comment]
Not a subsetter issue then.
