### ISSUE TITLE
Tamil psts w/ ss03 interaction

### ISSUE THREAD

**Issue by tiroj** [harfbuzz/harfbuzz#3488]
I am testing a new Tamil font which includes ss03 variant forms of Ssa letter and KSsa akhn ligature and also contextual alt forms of the spacing U and Uu vowel signs. The contextual alt substitutions are in the psts feature, and apply to the _default_ forms of Ssa and KSsa, whereas the default forms of the vowel signs are used with the ss03 variants of Ssa and KSsa. So in order to ensure that the default vowel signs are retained with the ss03 variants, the psts contextual substitution lookup for the alt vowel signs is ordered _after_ the ss03 substitution lookup.

This works fine in DWrite and CoreText environments, but does not work in HarfBuzz environments. In Chrome browser and InDesign with the HatfBuzz override active, I am getting the alt forms of U and Uu vowel signs being applied to the ss03 Ssa and KSsa. It’s as if HarfBuzz is not processing ss03 and psts based on lookup order, but instead processing psts before ss03.

Any insight?

**Comment by dscorbett** [comment]
HarfBuzz applies script-specific features before user-enabled discretionary features; see [Simon’s GSUB flowchart](https://twitter.com/simoncozens/status/1501610264160047113). The Indic shaper enables 'psts', so it is applied before 'ss03', regardless of lookup order.

Because DirectWrite and Core Text agree, and their behavior is not unreasonable, maybe HarfBuzz should match them. We’d have to hope no font is relying on HarfBuzz’s current order. We’d also have to do experiments with various scripts and features to see what exactly DirectWrite and Core Text are doing. [The Tamil spec](https://docs.microsoft.com/en-us/typography/script-development/tamil) offers no helpful guidance; cf. [the USE spec](https://docs.microsoft.com/en-us/typography/script-development/use), which explicitly puts “Custom substitution features requested by the application, GSUB” after “Standard typographic presentation, GSUB”, which includes 'psts'.

Here is a workaround, in case HarfBuzz doesn’t change or you want to support older versions of it. Put 'psts' before 'ss03'. In 'psts', substitute the vowel signs with their post-<i>ṣa</i> forms contextually. In 'ss03', substitute the post-<i>ṣa</i> forms with the default forms noncontextually.

**Comment by tiroj** [comment]
Thanks, David. I believe what DWrite and CoreText are doing—and also, I suspect, what their USE implementations might be doing based on conversations with Andrew Glass (albeit, a long time ago, before the USE spec was finalised) is processing all post-final-reordering GSUB as a block, determined by lookup order. My _[Enabling Typography](http://tiro.com/John/Enabling_Typography_(OTL).pdf)_ suggested processing model was published around the same time that Andrew was working on USE, and he commented that we had come up with very similar blocks. In my version, it is explicit that blocks 3a (script-specific standard typographic features) and 3b (script-agnostic typographic features) are processed simultaneously. I still think that model is generally the most sensible implementation of OTL in terms of providing the widest feature support and most flexibility to font makers regardless of script.

Thanks for the workaround tip. I had figured that I might need to do something like that.

**Comment by dscorbett** [comment]
I made a font ([HB3488.otf](https://github.com/harfbuzz/harfbuzz/files/8308520/HB3488.otf.zip)) supporting the letter <i>ka</i> and the vowel sign <i>-u</i>, with 'ss03' before 'psts' as in your font, all in both Tamil and Grantha. I tested with plain HarfBuzz and with Core Text, with and without 'ss03'.

Tamil works just as you reported.
```console
$ hb-shape --ned --no-positions -u '0B95 0BC1' HB3488.otf
[uni0B95|uni0BC1.psts]
$ hb-shape --ned --no-positions -u '0B95 0BC1' HB3488.otf --shapers coretext
[uni0B95|uni0BC1.psts]
$ hb-shape --ned --no-positions -u '0B95 0BC1' HB3488.otf --features ss03
[uni0B95.ss03|uni0BC1.psts]
$ hb-shape --ned --no-positions -u '0B95 0BC1' HB3488.otf --shapers coretext --features ss03
[uni0B95.ss03|uni0BC1]
```

Grantha works the way you want Tamil to work. This surprised me, because it is the opposite of what the USE spec specifies.
```console
$ hb-shape --ned --no-positions -u '11315 11341' HB3488.otf
[u11315|u11341.psts]
$ hb-shape --ned --no-positions -u '11315 11341' HB3488.otf --shapers coretext
[u11315|u11341.psts]
$ hb-shape --ned --no-positions -u '11315 11341' HB3488.otf --features ss03
[u11315.ss03|u11341]
$ hb-shape --ned --no-positions -u '11315 11341' HB3488.otf --features ss03 --shapers coretext
[u11315.ss03|u11341]
```

Could you run these tests on Windows with `--shapers uniscribe` and `--shapers directwrite`?

**Comment by dscorbett** [comment]
I ran those tests on Windows, but it looks like HarfBuzz doesn’t pass feature settings to Uniscribe and DirectWrite correctly, so it is was not useful.
<details>
<summary>Test results</summary>

```
>hb-shape --ned --no-positions -u 0B95,0BC1 HB3488.otf --shapers uniscribe
[uni0B95|uni0BC1.psts]

>hb-shape --ned --no-positions -u 0B95,0BC1 HB3488.otf --shapers directwrite
[uni0B95|uni0BC1.psts]

>hb-shape --ned --no-positions -u 0B95,0BC1 HB3488.otf --features ss03 --shapers uniscribe
[uni0B95|uni0BC1.psts]

>hb-shape --ned --no-positions -u 0B95,0BC1 HB3488.otf --features ss03 --shapers directwrite
error: Shaping failed.

>hb-shape --ned --no-positions -u 11315,11341 HB3488.otf --shapers uniscribe
[u11315|u11341.psts]

>hb-shape --ned --no-positions -u 11315,11341 HB3488.otf --shapers directwrite
[u11315|u11341.psts]

>hb-shape --ned --no-positions -u 11315,11341 HB3488.otf --features ss03 --shapers uniscribe
[u11315|u11341.psts]

>hb-shape --ned --no-positions -u 11315,11341 HB3488.otf --features ss03 --shapers directwrite
error: Shaping failed.
```

</details>

I made an HTML version of the test ([HB3488.html](https://github.com/harfbuzz/harfbuzz/files/8309403/HB3488.html.zip)) and opened it in Internet Explorer. The results were visually consistent with Core Text. I infer that Windows is processing script-specific standard features and script-agnostic features simultaneously.

Most of HarfBuzz’s shapers already work like that. Only the Indic one has a pause at the very end. For example, compare Indic:
https://github.com/harfbuzz/harfbuzz/blob/1f79ba9407ecd54e382997940cbcc3fb71bef8be/src/hb-ot-shape-complex-indic.cc#L202-L206
with Khmer:
https://github.com/harfbuzz/harfbuzz/blob/1f79ba9407ecd54e382997940cbcc3fb71bef8be/src/hb-ot-shape-complex-khmer.cc#L117-L121

@behdad, why does the Indic shaper clear syllables _after_ standard typographic presentation features whereas the Burmese, Khmer, and USE shapers clear them before? Moving the pause earlier for Indic fixes this issue but I don’t know what it might break.

**Comment by tiroj** [comment]
I took a look [how the USE works](https://docs.microsoft.com/en-us/typography/script-development/use#how-the-universal-shaping-engine-works), and it seems at least slightly ambiguous in this respect. There are two labeled sections

[Standard typographic presentation, GSUB](https://docs.microsoft.com/en-us/typography/script-development/use#standard-typographic-presentation-gsub)

[Custom substitution features requested by the application, GSUB](https://docs.microsoft.com/en-us/typography/script-development/use#custom-substitution-features-requested-by-the-application-gsub)

which I agree sort of suggests that they are to be processed subsequently, but this isn’t explicitly specified, and the second section is underspecified compared to the first. I suspect the intention is similar to that which I made explicit in my model, i.e. to note that some typographic features are required for some scripts, but that typographic features in general can and should be processed simultaneously following lookup order. That seems to be Microsoft’s and Apple’s implementation, and conforms to what I understood the intent to be from discussions with Andrew back to 2014. Definitely this is something that the spec should clarify.

[I am not set up to run the HB tests on Windows, but could perhaps set something up next week. Perhaps someone else can run the tests in the meantime?]

**Comment by behdad** [comment]
This is because of this line: https://github.com/harfbuzz/harfbuzz/blob/7bdc20ec810c14056d6362b076aa6717f10f26a0/src/hb-ot-shape-complex-indic.cc#L205

We can move that before the loop before it but that has other side effects...

**Comment by dscorbett** [comment]
Do you know whether the side effects are undesirable? I think that as DirectWrite, Core Text, and most other HarfBuzz script-specific shapers agree, we should move the pause earlier, unless there is some specific reason not to.

**Comment by behdad** [comment]
> Do you know whether the side effects are undesirable? 

Might even be desirable. Will make the `psts` not be bound to within clusters anymore. Is just a change to how we have been doing things, but if we can show that's how others do it, I think it's a desirable change.

> I think that as DirectWrite, Core Text, and most other HarfBuzz script-specific shapers agree, we should move the pause earlier, unless there is some specific reason not to.

I agree it's desirable to get closer to other shapers.

**Comment by behdad** [comment]
> @behdad, why does the Indic shaper clear syllables _after_ standard typographic presentation features whereas the Burmese, Khmer, and USE shapers clear them before?

Just historical reasons. The code was written that way; that's all.
