### ISSUE TITLE
Can't compile Harfbuzz 4.0.1 using the latest Intel C++ Compiler Classic (icc)

### ISSUE THREAD

**Issue by dejanyy** [harfbuzz/harfbuzz#3499]
It appears it's not possible to compile Harfbuzz 4.0.1 using Intel's latest C++ Compiler Classic (icc) - version 2021.5.0. Tried with -std=c++11, -std=c++14 and -std=c++17. There are 2 types of compilation errors:

Type 1:

error: more than one conversion function from "const hb_sorted_array_t<...>" to "bool" applies

Appears in:

- hb-iter.hh(382)
- hb-iter.hh(448)
- hb-iter.hh(558)

Type 2:

error: no suitable conversion function from "hb_sorted_array_t<...>  to "bool" exists

Appears in:

- hb-iter.hh(443)
- hb-iter.hh(449)
- hb-ot-layout-common.hh(1524)
- hb-ot-layout-gpos-table.hh(614)

Is there any interest in supporting Intel's icc compiler? If so, I'm happy to provide a detailed error log and help test your patches using this compiler.

**Comment by behdad** [comment]
There is interest but without a way to easily test, these kinds of errors are really hard to fix. Sure go ahead and provide the full error but I'm skeptical...

**Comment by dejanyy** [comment]
OK, in the attached text file is the full error output, hopefully it will be of some use. This is all I can get with icc.

If there is anything else I can do, please let me know. Again, I'm happy to help test any patches using this compiler.

[icc_errors.txt](https://github.com/harfbuzz/harfbuzz/files/8343718/icc_errors.txt)

**Comment by behdad** [comment]
This seems to be a compiler bug. `hb_sorted_array_t` clearly identifies one `operator bool` that should be preferred over others. I have no idea how to fix this.

**Comment by dejanyy** [comment]
I agree that this is most likely a compiler bug. The identical code compiles fine with all other compilers I tried and on several other platforms. I will reach out to icc developers to see if they can fix this bug. Thanks.

**Comment by behdad** [comment]
Thanks.
