### ISSUE TITLE
Bug with Recursive font

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3506]
HarfBuzz seems to have a problem applying variations to some glyphs of Recursive font downloaded from https://fonts.google.com/specimen/Recursive:
```
$ hb-shape Recursive-VariableFont_CASL,CRSV,MONO,slnt,wght.ttf -u c5 --variations="wght=300" --show-extents
[Aring=0+650<40,896,570,-896>]
$ hb-shape Recursive-VariableFont_CASL,CRSV,MONO,slnt,wght.ttf -u c5 --variations="wght=600" --show-extents
[Aring=0+650<0,0,0,0>]
```

`hb-view` also produces a blank image. FreeType font functions work fine:
```
$ hb-shape Recursive-VariableFont_CASL,CRSV,MONO,slnt,wght.ttf -u c5 --variations="wght=600" --font-funcs=ft --show-extents
[Aring=0+650<36,898,578,-898>]
```
[Recursive.zip](https://github.com/harfbuzz/harfbuzz/files/8340177/Recursive.zip)

**Comment by khaledhosny** [comment]
Interestingly, upstream files or even file downloaded directly [from Google Fonts git repository](https://github.com/google/fonts/blob/main/ofl/recursive/Recursive%5BCASL%2CCRSV%2CMONO%2Cslnt%2Cwght%5D.ttf) do not show this problem:
```
$ hb-shape "Recursive[CASL,CRSV,MONO,slnt,wght].ttf" -u c5 --variations="wght=600" --show-extents
[Aring=0+650<36,898,578,-898>]
```

cc @rsheeter in case the download zip from the website is modified by some tool.

**Comment by behdad** [comment]
Reproduces for me.

**Comment by behdad** [comment]
There's a bug inside gvar's `apply_deltas_to_points`. glyf is bailing if that function returns false. That's wrong. But also if I make it not do that, the ring doesn't get variations applied whereas freetype does apply. Debugging further.

**Comment by behdad** [comment]
> There's a bug inside gvar's `apply_deltas_to_points`

Looks to me like `unpack_deltas` is getting wrong bytes to unpack. This condition is being hit:
```
      if (j < run_count) 
```

**Comment by behdad** [comment]
I think we should apply this change regardless:
```diff
diff --git a/src/hb-ot-glyf-table.hh b/src/hb-ot-glyf-table.hh
index 066e152da..b4ac68834 100644
--- a/src/hb-ot-glyf-table.hh
+++ b/src/hb-ot-glyf-table.hh
@@ -820,8 +820,7 @@ struct glyf
       }
 
 #ifndef HB_NO_VAR
-      if (unlikely (!glyf_accelerator.gvar->apply_deltas_to_points (gid, font, points.as_array ())))
-       return false;
+      glyf_accelerator.gvar->apply_deltas_to_points (gid, font, points.as_array ());
 #endif
 
       switch (type) {
```
