### ISSUE TITLE
Meson build writes to the source directory

### ISSUE THREAD

**Issue by aneejit1** [harfbuzz/harfbuzz#3507]
The meson build process is writing to the source directory. This is a problem if there is only read only access to the source and causes the build to fail in one of two places:

- in "src/gen-hb-version.py" while running meson
- in "src/gen-harfbuzzcc.py" once ninja has been invoked

The scripts src/gen-harfbuzzcc.py and src/gen-hb-version.py need to be modified so a copy back to the source tree is only performed if the generated files differ from the baselined files (this should therefore only happen when something does
actually change as part of the development process).

**Comment by khaledhosny** [comment]
Fixed in https://github.com/harfbuzz/harfbuzz/pull/3508
