### ISSUE TITLE
Need a new release, to use new API.

### ISSUE THREAD

**Issue by andyjgf** [harfbuzz/harfbuzz#3517]
Hi there,
  In order to use the new hb_set_next_many call in hb-set.h, I need a new release (4.1.1?).
Thanks!
Andy

**Comment by behdad** [comment]
Good timing. I reverted the Indic regression, and have fixed the new Mac emoji rendering bug.

**Comment by behdad** [comment]
Small inconvenience for packagers is that we landed some of the new file structure (OT/Layout/GSUB/*)...

**Comment by behdad** [comment]
> Small inconvenience for packagers is that we landed some of the new file structure (OT/Layout/GSUB/*)...

There will be more in upcoming releases.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/4.2.0
