### ISSUE TITLE
Add an API to build code unit to glyph map

### ISSUE THREAD

**Issue by mta452** [harfbuzz/harfbuzz#3520]
In [Tehreer-Android](https://github.com/Tehreer/Tehreer-Android), I'm using [code unit to glyph map](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/jni/ShapingResult.cpp#L59) for pre-building the [caret locations](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/java/com/mta/tehreer/internal/layout/CaretEdgesBuilder.java#L123). This mechanism has proved very useful for me to implement some behaviour such as extracting a part of the shaped text or performing hit testing.

I believe it will be very useful for everyone if similar APIs become part of HarfBuzz itself.

**Comment by behdad** [comment]
You can use `hb_face_collect_unicodes` and `hb_font_get_nominal_glyph` to build that yourself. Sure we could add API to return a `hb_map_t`, but currently that would be a bit clumsy in how our face and font are setup...

**Comment by khaledhosny** [comment]
Looking at the linked code, I think what you are looking for is `cluster` of `hb_glyph_info_t`.

**Comment by mta452** [comment]
I'm already building that myself 😅
Basically I'm using the [cluster](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/jni/ShapingResult.h#L44) of `hb_glyph_info_t` to build this. The output is an array whose each index corresponds to the index of the input code unit. The value of each element specifies the first index of related glyph in `hb_glyph_info_t` array retrieved from the text shaping process.

**Comment by mta452** [comment]
Basically I'm proposing a new API `hb_buffer_build_cluster_map(hb_buffer_t *buffer, /* out */ uint32_t *glyph_info_indexes)`. The length of `glyph_info_indexes` must be >= input code units added with `hb_buffer_add_utf8()` or related API.

We already have `cluster` in `hb_glyph_info_t` which maps glyph to respective code unit. The proposed API will be the opposite of it. It will map code unit to respective glyph.

**Comment by mta452** [comment]
As a side question, is it possible to disable the visual order in shaping process? All of my logic is built around the logical order, so I have to [manipulate the index](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/jni/ShapingResult.h#L69) as well.

**Comment by behdad** [comment]
> As a side question, is it possible to disable the visual order in shaping process?

You can simply call `hb_buffer_reverse()` after `hb_shape()` if direction is backwards.

**Comment by behdad** [comment]
> Basically I'm proposing a new API `hb_buffer_build_cluster_map(hb_buffer_t *buffer, /* out */ uint32_t *glyph_info_indexes)`. The length of `glyph_info_indexes` must be >= input code units added with `hb_buffer_add_utf8()` or related API.

HarfBuzz only processes one run of text at a time, typically in the middle of paragraph. That means, clusters do not necessarily start from 0. It's best to leave cluster mapping to the client, since it depends on how they account for them. It's a bit of a tricky loop to write, but each client's loop is slightly different.

**Comment by mta452** [comment]
> You can simply call `hb_buffer_reverse()` after `hb_shape()` if direction is backwards.

Actually I was looking more of a flag to disable the following, since my logic is already built on the logical order:
https://github.com/harfbuzz/harfbuzz/blob/9d5730b958974bc9db95e46e6bad52e9e9cd6e1c/src/hb-ot-shape.cc#L1117

**Comment by mta452** [comment]
> HarfBuzz only processes one run of text at a time, typically in the middle of paragraph. That means, clusters do not necessarily start from 0. It's best to leave cluster mapping to the client, since it depends on how they account for them. It's a bit of a tricky loop to write, but each client's loop is slightly different.

It might be different for every client but every client more or less needs it. So actually it can be standardized inside the HarfBuzz. And since HarfBuzz is already expanding into other domains such as glyph rendering, I believe layout should be the top priority of all. But that's totally your decision.

I'll highlight the advantages I have seen by using the cluster map:
- Finding out the [start of cluster](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/java/com/mta/tehreer/internal/layout/IntrinsicRun.java#L172-L183) or the [end of cluster](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/java/com/mta/tehreer/internal/layout/IntrinsicRun.java#L186-L198) from character index
- Finding out the [glyph range for the character range](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/java/com/mta/tehreer/internal/layout/IntrinsicRun.java#L228-L243)
- [Pre-building caret locations](https://github.com/Tehreer/Tehreer-Android/blob/v2.8/tehreer-android/src/main/java/com/mta/tehreer/internal/layout/CaretEdgesBuilder.java) for following advantages:
  * [Custom advance handling](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/java/com/mta/tehreer/internal/layout/CaretEdgesBuilder.java#L100-L114) which can be useful to take GDEF based component advance into account
  * [Faster measurement of characters](https://github.com/Tehreer/Tehreer-Android/blob/e4d5e7d65f0aa2a538e5b7cd9de725e47564a2f2/tehreer-android/src/main/java/com/mta/tehreer/internal/layout/CaretUtils.java#L29-L35) with just a single subtractions

**Comment by behdad** [comment]
I don't think we can add any flexible API here.
