### ISSUE TITLE
[aat] Regression in Bengali AAT shaping

### ISSUE THREAD

**Issue by jfkthame** [harfbuzz/harfbuzz#3528]
Shaping of some AAT fonts was recently broken, as reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1763368.

Good (21c4fc1011854547edf564573fdbec4687e76e04):
```
$ hb-shape --font-file "/System/Library/Fonts/Supplemental/Bangla MN.ttc" --unicodes "U+09AC U+09BF"
[bn_ikaar=0+474|bn_ba=0+998]
```

Bad (23159084b43c1ce429d9e98035bf845919fd8a89, and same with current trunk code):
```
$ hb-shape --font-file "/System/Library/Fonts/Supplemental/Bangla MN.ttc" --unicodes "U+09AC U+09BF"
[bn_ba=0+998|bn_ikaar=0+474]
```

Note the inverted order of the ikaar and the base consonant. This was regressed by #3314.

This breaks at least the Bangla MN and Bangla Sangam MN fonts shipped with macOS; I have not exhaustively tested other AAT Indic fonts but it seems likely others may be similarly affected.

**Comment by jfkthame** [comment]
@behdad I checked that 23159084b43c1ce429d9e98035bf845919fd8a89 reverts cleanly on current trunk, and restores the expected result here. Given that Firefox apparently wasn't affected by #3314, we could do that locally as a band-aid, but obviously this will be less attractive to Chrome as #3314 was a problem for them. So you may want to try and find an alternative?

**Comment by behdad** [comment]
@jfkthame Right. I'm guessing that CoreText is treating regional-indicators as atomic units only? Let me find an alternative fix.

**Comment by behdad** [comment]
I'm out of bits :(.

**Comment by behdad** [comment]
> @jfkthame Right. I'm guessing that CoreText is treating regional-indicators as atomic units only? Let me find an alternative fix.

Nah.

The distinction can be made by looking at logical and reverse flags separately... Let me patch.

**Comment by behdad** [comment]
I'm confused. I think the original RI change was wrong. Let me go back there and discuss.

**Comment by behdad** [comment]
Okay I think I have a proper fix now: https://github.com/harfbuzz/harfbuzz/pull/3539
