### ISSUE TITLE
Leelawade UI shaping regression after 044d7a06db552e1

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#3531]
Still working on the HarfBuzz roll in 
https://chromium-review.googlesource.com/c/chromium/src/+/3550975
but the new Indic change in 044d7a06db552e1 after the revert in 61486746d3d893 causes a regression on Windows.

New behavior:
![leelaw_bad](https://user-images.githubusercontent.com/1021784/162711461-ad00c034-8800-4ea7-aaed-2015b7cd4cb6.png)

Expected:

![leelaw_good](https://user-images.githubusercontent.com/1021784/162711513-7b832937-5197-44f0-bdc2-94da11746482.png)

**Comment by drott** [comment]
CC @jfkthame

**Comment by jfkthame** [comment]
Could you confirm the exact text sequence you're using? Thanks.

**Comment by drott** [comment]
> Could you confirm the exact text sequence you're using? Thanks.

`$ hb-shape leelawui.ttf "ក្រុម"`

**Comment by drott** [comment]
> (FWIW, it looks to me like the "new behavior" is the better rendering, and the "expected" image has failed to position the vowel mark properly.)

The "expected" image matches what's shown for example in Wordpad on Windows.

**Comment by jfkthame** [comment]
I agree, that's what Wordpad shows, but I would argue it's a defect. The expected position for the vowel sign (u-matra) is directly under the right leg of the ka glyph; and there is no reason from the point of view of the writing system that the conjoined ro, which appears to the left, should affect its position relative to the base glyph.

Comparing the result in a few other fonts I have on hand (a mix of AAT and OT), this is consistent:
![image](https://user-images.githubusercontent.com/1706499/162939680-bf7504eb-e5c3-4e5e-ae9d-019f3cd3c21e.png)

So I believe Uniscribe's failure to position the u-matra is their bug, and the new harfbuzz behavior is an improvement.

**Comment by jfkthame** [comment]
Looks like the real issue here is that since the change in 044d7a0, the GSUB `blws` feature fails to change the u-matra to an alternate glyph when preceded by conjoined-ro and ka:

Old behavior:
```
$ hb-shape --font-file LeelawUI.ttf --unicodes U+1780,U+17D2,U+179A,U+17BB
[gid688=0+525|gid532=0+1725|gid813=0@330,10+0]
```
New:
```
$ hb-shape --font-file LeelawUI.ttf --unicodes U+1780,U+17D2,U+179A,U+17BB
[gid688=0+525|gid532=0+1725|gid812=0+0]
```
Note how the final glyph (the u-matra) is a different glyph ID. The relevant `blwm` lookup only applies to gid813.

**Comment by behdad** [comment]
This was easy. Adding a GSUB pause after Khmer basic features was all that was needed.

**Comment by behdad** [comment]
I checked and the other shapers are not affected.
