### ISSUE TITLE
Combining circle glyph order changed/regressed(?) after 5b995526

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#3535]
Spun off from [crbug.com/1313829](https://crbug.com/1313829)

After 5b995526 "Fix reverse_group() to reverse() at the end"

What used to be:
```
$ build/util/hb-shape /System/Library/Fonts/LucidaGrande.ttc --unicodes '20DD 1F174 1F175'
[circlecmb=0+0|.notdef=1+1536|.notdef=2+1536]
```

becomes inverted:
```
$ build/util/hb-shape /System/Library/Fonts/LucidaGrande.ttc --unicodes '20DD 1F174 1F175'
[.notdef=1+1536|circlecmb=0+0|.notdef=2+1536]
```

and the Blink cursor positioning and layout code does not seem to handle that well.

Coretext shaper output for comparison:
```
$ build/util/hb-shape /System/Library/Fonts/LucidaGrande.ttc --shaper=coretext --unicodes '20DD 1F174 1F175'
[circlecmb=0@2186,0+2186|.notdef=1+1536|.notdef=2+1536]
```

It seems to me the inversion should not happen and the reversing should not alter the combining circle's position in the glyph sequence, but I am not entirely sure what the rules in the font are.

This change causes upstream crashes in chrome when handling cursor positioning. In terms of a fix, it'd be good to have one that applies cleanly to older HarfBuzz versions as a bandaid. I'll see if I can add early returns somewhere to avoid the crash.

**Comment by behdad** [comment]
This will be fixed by https://github.com/harfbuzz/harfbuzz/pull/3529 or whatever else fix we put in as a result.
