### ISSUE TITLE
GSUB behaviour differences between harfbuzz and MS Word

### ISSUE THREAD

**Issue by seehuhn** [harfbuzz/harfbuzz#3545]
I constructed a test font which has two GSUB lookups:

- lookup 0 (type 5, format 1): this only applies if the input is one of AB, AAB or AAAB.  For these inputs it recursively applies lookups 1 (adding another A) and then lookup 0 again.

- lookup 1 (type 2, format 1): this replaces A -> AA.

Using this font, the current version of Word from Office 365 (on Mac) and the Mac "Font Book" typeset the input "AB" as "AAAAB", while harfbuzz just gives "AAB".  From my reading of the OpenType spec I believe that "AAAAB" is correct.

The font file (both as .otf and decoded via ttx) is here:
- https://m.seehuhn.de/hbdata/test9737.otf
- https://m.seehuhn.de/hbdata/test9737.ttx

I believe that the problem is caused by the following test: https://github.com/harfbuzz/harfbuzz/blob/9e59c401e05018eacc09d277251f692a517652c8/src/hb-ot-layout-gsubgpos.hh#L1418-L1421 Recursing to the same lookup at the same position does not necessarily indicate an infinite loop, since the input may have changed in the mean time.

**Comment by behdad** [comment]
Thanks. Indeed, removing that condition fixes it. Can I use your test font in our test suite?

**Comment by seehuhn** [comment]
Sure, feel free to use the font.  The glyph outlines come from the "Go Regular" TrueType font, which can be re-distributed under a BSD 3-clause license https://cs.opensource.google/go/x/image/+/master:font/gofont/ttfs/README .  You probably need to put a copy of this licence next to the font.  As far as my changes to the font are concerned (subsetting, conversion to Opentype etc.), I'm happy for you to use these in any way you see fit.

**Comment by behdad** [comment]
> Sure, feel free to use the font. The glyph outlines come from the "Go Regular" TrueType font,

Somehow `hb-view` doesn't render the outlines for me.

**Comment by seehuhn** [comment]
This is strange!  Outlines work fine for me on Mac (see screenshot).  What system are you on?

![Screenshot 2022-04-25 at 09 32 36](https://user-images.githubusercontent.com/584729/165051512-4718ac37-94e0-48a3-8e41-2e75ef369a28.png)

**Comment by seehuhn** [comment]
> > Sure, feel free to use the font. The glyph outlines come from the "Go Regular" TrueType font,
> 
> Somehow `hb-view` doesn't render the outlines for me.

One idea: there are very few glyphs in this font, to keep the file size small.  Maybe you tried glyphs which are simply not there?  It's just the capital letters A-Z, space, and three extra symbols which I plan to use for GPOS alignment tests.

**Comment by behdad** [comment]
Interesting. HB_DRAW=0 works, but HB_DRAW=1 fails. And this is a CFF font. Who wants to debug this, ugh. cc @khaledhosny @ebraminio

**Comment by khaledhosny** [comment]
The `sanitize()` call here returns false: https://github.com/harfbuzz/harfbuzz/blob/6454cec085ba51cefcd12b1f8027bc4a647347d5/src/hb-ot-cff1-table.hh#L1119-L1121

The `localSubrs` is empty, but the check here is failing:
https://github.com/harfbuzz/harfbuzz/blob/6454cec085ba51cefcd12b1f8027bc4a647347d5/src/hb-ot-cff-common.hh#L284-L291

Without knowing much about the code, I assume the first check should be true, but `c->check_struct (this)` is returning false.

**Comment by khaledhosny** [comment]
I I remove the empty Subrs from the Private dict and rerun ttx the font renders fine, so this empty index our code is tripping over.

**Comment by behdad** [comment]
> return_trace (likely ((c->check_struct (this) && count == 0) || /* empty INDEX */

This check is definitely wrong. If count is zero, nothing else is encoded. Thanks for debugging this. I know the fix.

**Comment by behdad** [comment]
Fixed it.
