### ISSUE TITLE
Repacker can't find resolution for overflowing table

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#3547]
I'm using fontmake/fontTools's hb-repacker functionality on a proprietary font and the repacker gives up.

The font I'm testing is proprietary, ~~where can I send the sources to?~~ I sent it via Google Drive. Please keep it to yourselves :)

I'm doing:

```
$ python3 -m venv .venv
$ . .venv/bin/activate
$ pip install fontmake git+https://github.com/harfbuzz/uharfbuzz.git@debug-repack
$ fontmake -m MyFont.designspace -o variable > log.txt 2>&1
```

The repacker typically signals:

> SUBSET_REPACK                      Ôö£Ôò┤: No resolution available :(
> SUBSET_REPACK                      Ôö£Ôò┤: Offset overflow resolution failed.

**Comment by garretrieger** [comment]
I'll take a look.

**Comment by garretrieger** [comment]
Without having looked into this my initial guess is that the table being repacked requires table splitting (which harfbuzz doesn't do yet). One workaround for this would be to round trip the font through ttx after it's built. Then harfbuzz will be working with a version of GSUB/GPOS that has already had table splitting applied and then should be able to repack it.

**Comment by anthrotype** [comment]
fonttools is already sort of doing that, i.e. re-trying hb repacker after the latter failed and fonttools has attempted to fix the overflow error by upgrading lookups to extensions or splitting subtables, see https://github.com/fonttools/fonttools/issues/2594

**Comment by anthrotype** [comment]
in fact, for the font in question, hb is able to repack at the end, but only after 6 "Attempting to fix OTLOffsetOverflowError". If you look at the fontmake output in log.txt file that Nikolaus shared, the last time there is no error from hb repack.

**Comment by garretrieger** [comment]
Ok great, I didn't realize that fonttools will retry hb repacker after using fonttools built in resolutions. Then there is probably nothing else to do here.
