### ISSUE TITLE
Request for advice when HarfBuzz swaps cluster ordering

### ISSUE THREAD

**Issue by kojiishi** [harfbuzz/harfbuzz#3553]
This issue is about questions and request for advice when HarfBuzz swaps cluster ordering.

This might be well-known to HarfBuzz experts, but one case we found is on Mac:
```
% hb-shape /System/Library/Fonts/Geneva.ttf --unicodes=1DDE,A74A --direction=ltr
[uniA74A=1+1861|uni1DDE=0@-371,826+0]
```
The direction is LTR, but the cluster indices are in the descending order. I guess they are swapped, because a combining mark (U+1DDE COMBINING LATIN LETTER SMALL CAPITAL L) is at the beginning of a run. When more characters follow:
```
% hb-shape /System/Library/Fonts/Geneva.ttf --unicodes=1DDE,A74A,0041,0042 --direction=ltr
[uniA74A=1+1861|uni1DDE=0@-371,826+0|A=2+1489|B=3+1303]
```
The cluster indices are [1, 0, 2, 3], neither in the ascending or the descending order.

The first question is, does this occur only at the beginning of a run, and only for one cluster? This question is because if yes, it's not too expensive to check the situation (check the first two glyphs) and run a special logic to handle this case. If no, I'll need to think a bit more.

Some background and details follow. I'm not sure if this is the right thing, but in Blink, there are several pieces of code that assume cluster indices are in the ascending order in LTR, and in the descending order in RTL. For example:
1. When extracting glyphs from `hb_buffer_t`, Blink computes corresponding indices of source text. This is done by `(glyph_info[0].cluster, glyph_info[end_glyph].cluster - 1)`. This computes wrong values when glyphs are swapped.
2. Once glyphs are extracted to Blink's data structure, Blink uses similar logic to compute the length of a cluster, searching a character index by binary-search, etc., relying on the assumption above.

Crashes probably related with this symptom started increasing since last Dec or Jan. Maybe because of a code change or a site change around that time. A workaround to prevent crashes is put in, but our data structure is still in a bad shape, so I'm hoping to understand the situation better.

For 2, I haven't tried yet but this is probably solvable, by such as splitting the Blink data structure for the reversed parts of a glyph run, and mark them as RTL. 

1 is more challenging. If this is only about the beginning of a run and the cluster for the first glyph is one glyph, I can add a code like this:
```
if (dir == ltr && num_glyphs >= 2 && glyph_info[0].cluster > glyph_info[1].cluster) {
```
and I suppose this shouldn't be too expensive.

If it could occur in other cases too, can I ask when it can occur? If it involves more complex logic or may change in future, is it a reasonable request to add flags to detect this situation?

@behdad Could you advise what would be the best way for us? /cc @drott

**Comment by kojiishi** [comment]
@drott pointed out that this is likely https://github.com/harfbuzz/harfbuzz/issues/3535. I'll re-check when the fix landed.

**Comment by khaledhosny** [comment]
In general, for cluster levels 0 and 1, if clusters are not in ascending order (either LTR or RTL based on buffer direction), then it is a bug that needs to be fixed.

**Comment by khaledhosny** [comment]
With 4.2.1:
```
$ hb-shape /System/Library/Fonts/Geneva.ttf --unicodes=1DDE,A74A --direction=ltr
[uni1DDE=0+0|uniA74A=1+1861]

$ hb-shape /System/Library/Fonts/Geneva.ttf --unicodes=1DDE,A74A,0041,0042 --direction=ltr
[uni1DDE=0+0|uniA74A=1+1861|A=2+1489|B=3+1303]
```

**Comment by kojiishi** [comment]
Thanks @khaledhosny!
