### ISSUE TITLE
another GSUB difference between harfbuzz and MS Word

### ISSUE THREAD

**Issue by seehuhn** [harfbuzz/harfbuzz#3556]
I managed to construct another test font where harfbuzz behaviour differs from what MS Word does.  The file uses the following lookups:

- lookup 0: a GSUB type 5, format 1 lookup which matches "ABA" and "A".   If ABA is matched, lookup 2 is called at position 1 (the glyph B) to replace BA...AB with BA...AAA.  If A is matched, it is replaced with an X (lookup 1)
- lookup 1: use GSUB type 1, format 2 to replace A -> X
- lookup 2: replace BB -> BAA (using type 5, format 1 and another lookup).  This ignores "base glyphs" and the font sets A as a base glyph, so this applies also to BAAAB etc.
- lookup 3: replace B -> AA for use in lookup 2.

(My aim was to find out what the "cursor" should be after lookup 0 is matched.)

Using these rules, MS Word turns the input "ABAAAB" into "ABAXXB", while harfbuzz turns the same input into "ABAAXXX".  Clearly, some care is needed to avoid infinite recursion (e.g. if lookup 3 is changed to replace B -> ABAAAB or similar), but I believe the harfbuzz behaviour of replacing the A at position 5, but *not* replacing the A at position 4 makes no sense.

To reproduce: the font files are at
- https://m.seehuhn.de/hbdata/test9738.otf 
- https://m.seehuhn.de/hbdata/test9738.ttx

Using the otf file, `hb-view test9738.otf ABAAAB` shows the problem.

`hb-view --version` says
```
hb-view (HarfBuzz) 4.2.1
Available shapers: graphite2,ot,coretext,fallback
```

All the best,
Jochen

**Comment by seehuhn** [comment]
I did a lot of experimenting, and my current impression is that MS Word does not allow nested lookups to match beyond the end or the original input pattern.  This would explain why lookup 3 is not applied in the example I reported.  (This seems to be a difference between Mac and Windows.  In my experiments, my Mac laptop was happily applying nested substitutions beyond the end of the original input pattern.)

**Comment by khaledhosny** [comment]
It is a known limitation of Microsoft implementation http://litherum.blogspot.com/2019/03/addition-font.html.

**Comment by behdad** [comment]
> I did a lot of experimenting, and my current impression is that MS Word does not allow nested lookups to match beyond the end or the original input pattern. This would explain why lookup 3 is not applied in the example I reported. (This seems to be a difference between Mac and Windows. In my experiments, my Mac laptop was happily applying nested substitutions beyond the end of the original input pattern.)

Right. And that also explains why they manage to track the relationship between what the sublookup does to the original lookup's matched position...

**Comment by seehuhn** [comment]
> It is a known limitation of Microsoft implementation http://litherum.blogspot.com/2019/03/addition-font.html.

On the web page I read the following: "The algorithms used for complex scripts can be quite involved; HarfBuzz tries to be compatible with the OpenType Layout specification and, wherever there is any ambiguity, HarfBuzz attempts to replicate the output of Microsoft's Uniscribe engine."  Does this mean that HarfBuzz is meant to replicate the Microsoft behaviour, i.e. should only allow nested lookups in the range covered by the input pattern?  Or does "attempts to replicate" refer to something else?

**Comment by behdad** [comment]
> Does this mean that HarfBuzz is meant to replicate the Microsoft behaviour,

Yes. To the extent that is feasible and desirable. In this case it's architecturally hard to enforce that, and undesirable as well.

**Comment by ErwinDenissen** [comment]
> It is a known limitation of Microsoft implementation http://litherum.blogspot.com/2019/03/addition-font.html.

From what I understand Microsoft just respects the [OpenType spec](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#lookup-table):

"Once a sequence is matched against the pattern in the main lookup, the nested lookups are then processed on glyphs in the sequence."

**Comment by behdad** [comment]
> > It is a known limitation of Microsoft implementation http://litherum.blogspot.com/2019/03/addition-font.html.
> 
> From what I understand Microsoft just respects the [OpenType spec](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#lookup-table):
> 
> "Once a sequence is matched against the pattern in the main lookup, the nested lookups are then processed on glyphs in the sequence."

The consensus has been that we want that limitation relaxed. HarfBuzz and CoreText have gone that route.

Our architecture does not allow easily fixing that either.
