### ISSUE TITLE
Expose whether two glyphs were anchored or not

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#358]
This is needed for e.g. in fonts using cursive anchors to let the client know it shouldn’t apply letter spacing between two glyphs.

See the discussion in http://typedrawers.com/discussion/1816/cursive-attachment-for-latin.

**Comment by KrasnayaPloshchad** [comment]
This is helpful for debugging when typographic designer want to find which anchor is missing or incorrect.

**Comment by eaenet** [comment]
We'd love to see this exposed so that we use the information to avoid breaking cursive connections when applying letter spacing in Chrome.

https://bugs.chromium.org/p/chromium/issues/detail?id=942012

**Comment by khaledhosny** [comment]
This won’t be enough for disabling letter spacing, though. The majority of Arabic glyphs (and I assume other cursive glyphs as well) don’t use cursive anchors. I think you simply need a hard-coded list of scripts where letter-spacing should be disabled. The request here would be useful for scripts that are not usually cursive (e.g. Latin), and then I don’t think it is enough either since cursive Latin fonts don’t usually use cursive anchors as well.

**Comment by khaledhosny** [comment]
I don’t even remember why I thought such a flag would be useful, thinking about it now I see only little utility for it.

**Comment by eaenet** [comment]
That's unfortunate, I had naively assumed that it would be widely used for at least latin. Thanks for the explanation and suggestions, really appreciate it!

**Comment by bungeman** [comment]
I imagine a HB_GLYPH_FLAG_UNSAFE_TO_SPACE which would imply that letter spacing should not be trivially added between this cluster and the previous cluster. It would be set anytime a GPOS type 3 lookup or a kCursiveConnection feature is applied. The absence of the flag does not imply that letter spacing is safe, but the presence of the flag would be a signal that letter spacing should not be added between clusters. This would at least allow font designers to provide a hint to the application that letter spacing shouldn't be applied by default to connected glyphs (like in Latin script fonts). The user would probably still need to be aware of scripts which may need to set this always (or HarfBuzz could just always set this flag for such scripts).

**Comment by behdad** [comment]
See also followup discussion on mailing list:
https://lists.freedesktop.org/archives/harfbuzz/2019-October/007446.html
continued in:
https://lists.freedesktop.org/archives/harfbuzz/2019-November/007447.html

**Comment by behdad** [comment]
> I don’t even remember why I thought such a flag would be useful, thinking about it now I see only little utility for it.

I agree, since a lot of Arabic fonts are cursive without using attachments.

**Comment by yisibl** [comment]
> We'd love to see this exposed so that we use the information to avoid breaking cursive connections when applying letter spacing in Chrome.
> 
> [bugs.chromium.org/p/chromium/issues/detail?id=942012](https://bugs.chromium.org/p/chromium/issues/detail?id=942012)

By the way, Chrome 138 fixed this bug.

<img width="1484" height="612" alt="Image" src="https://github.com/user-attachments/assets/7ef4dc76-474e-4b76-8f46-144073a8fd20" />

```html
data:text/html;charset=UTF-8,<!doctype html> 
<style>.foo {margin: 20px; font-size: 32px; letter-spacing: 20px; display:inline-block; outline: 1px solid green; }</style>
<div class="foo">English مرحبا بالعالم</div>
```

Servo's behavior is slightly different. Compared to Chrome, which one is better?

<img width="1472" height="750" alt="Image" src="https://github.com/user-attachments/assets/b784a87d-5482-43ed-b9d4-1a2431cfae30" />

Skia has also been fixed here: https://issues.skia.org/issues/458132646

**Comment by KrasnayaPloshchad** [comment]
So would you like to submit a pull request?
