### ISSUE TITLE
[docs] Logo source?

### ISSUE THREAD

**Issue by n8willis** [harfbuzz/harfbuzz#3580]
This might be a bit on the silly side, but I was wondering what font is used in the logo image (HarfBuzz.svg).

I ask because I was mocking up some hexagonal sticker concepts, and I thought it might be visually interesting to use, rather than the monochrome SVG itself, a multi-color version made with Simon's Crowbar utility, since that provides some allusions to the actual functionality....

**Comment by behdad** [comment]
It's IranNastaliq. Thanks
