### ISSUE TITLE
harfbuz meson uninstall

### ISSUE THREAD

**Issue by ReznicencuBogdan** [harfbuzz/harfbuzz#3583]
Some custom package script ran `sudo meson install` after compilation. Running 'meson uninstall' target returns with error:
> "ERROR: Neither directory contains a build file meson.build."

The `build.ninja` file reveals both the `install` target and the `uninstall` one. What am I missing ?

**Comment by eli-schwartz** [comment]
The uninstall target of a build.ninja file is processed by running `ninja`, not `meson`, so you can just run `sudo ninja uninstall` instead.
