### ISSUE TITLE
Release time

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3589]
We've done major optimizations in the subsetter. Mostly in CFF but not only there; For example, subsetting NotoNastaliqUrdu is about three times faster. Also in CFF loading in general, and in data structures in general. Time for a release.

**Comment by behdad** [comment]
cc @garretrieger

**Comment by khaledhosny** [comment]
Looks like the optimization work is still on going. Let me know when you feel it is really time for release and I’ll cut one.

**Comment by behdad** [comment]
I believe we are done for now.

I'm working on new API. Would be good to get a release out before landing those. Thanks.

**Comment by khaledhosny** [comment]
ubsan builds are currently failing, any chance to fix this?
https://app.circleci.com/pipelines/github/harfbuzz/harfbuzz/3662/workflows/b5df3e85-fac6-420b-a623-a55bb9854a72/jobs/172448?invite=true#step-106-898

**Comment by behdad** [comment]
> ubsan builds are currently failing, any chance to fix this?
> https://app.circleci.com/pipelines/github/harfbuzz/harfbuzz/3662/workflows/b5df3e85-fac6-420b-a623-a55bb9854a72/jobs/172448?invite=true#step-106-898

Should be fixed: https://github.com/harfbuzz/harfbuzz/commit/975a5f919467c9bc4cad1340ebf07ae32bf07e14

Thanks.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/4.3.0
