### ISSUE TITLE
hb-view rejects noncharacter despite unicode.org urging otherwise

### ISSUE THREAD

**Issue by drj11** [harfbuzz/harfbuzz#3590]
Here is me trying to get `.notdef` out of a font

    hb-view --unicodes=FDD0 thing.ttf

output:

    hb-view: Failed: input string not valid UTF-8

So, U+FDD0 is one the Unicode _noncharacters_. Are they invalid in input streams? No, they are valid.

The Unicode FAQ has [this to say on noncharacters](https://www.unicode.org/faq/private_use.html#nonchar8):

> Q: Are noncharacters invalid in Unicode strings and UTFs?
> 
> A: Absolutely not.

So. If it is within the power of harfbuzz, can we change it so that noncharacters can be passed through?

**Comment by behdad** [comment]
This is happening at the glib level. I have to convince glib to not do it. cc @matthiasclasen

**Comment by behdad** [comment]
If FDD0 is part of a surrogate pair, then I can imagine why it does...

**Comment by behdad** [comment]
Alternative would be to pass `--unicodes` to hb buffer directly without going through GString.

**Comment by drj11** [comment]
U+FDD0 is not (cannot?) be part of a surrogate pair. At least according to my recent readings of the FAQ and the UTF-16 wikipedia page.

If it's all part of `glib`, then clearly there is nothing to be done apart from be sad.

The alternative, of avoiding `glib` to construct the buffer directly, sounds attractive, but it seems like a bunch of work for what is frankly a fairly marginal feature.

**Comment by behdad** [comment]
Currently we use `g_string_append_unichar`. Would be hard to avoid going through glib. I suggest we relax that function. I agree with you that non-characters should not be rejected at this level, and I fixed Pango a lot to allow all kinds of non-characters in and render them.

**Comment by behdad** [comment]
Even the glib utf-8 API I made accept invalid input and replace it with -1 instead of rejecting it, such that Pango can render invalid UTF-8 input. So I'm really surprised you hit this.

**Comment by behdad** [comment]
Humm, or that might be coming from cairo...

**Comment by behdad** [comment]
https://github.com/freedesktop/cairo/blob/e562ff757bb7d88b708e07a9759c046413c52f94/src/cairo-unicode.c#L100-L104

**Comment by behdad** [comment]
Fixed:
https://gitlab.freedesktop.org/cairo/cairo/-/commit/b41cfe3fe0909bec8586d7a541dbb4eb5133b2be

**Comment by drj11** [comment]
Quite an emotional ride, but thanks for investigating!
