### ISSUE TITLE
Adding hash cache to set regresses some subsetting benchmarks

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#3599]
Benchmark before/after https://github.com/harfbuzz/harfbuzz/commit/44952bcc259a906b8875ed62dc40de96ade8b95c:

https://gist.github.com/garretrieger/e72f50c8331d0db722106b23f6423afc

Particularily note the 16% regression on Mplus1p/10000

**Comment by behdad** [comment]
That's weird. And I cannot reproduce it :(.

**Comment by behdad** [comment]
Happy to leave it as is since the set hash is current unused.
