### ISSUE TITLE
[subset] Doesn't work with hb_face_create_for_tables.

### ISSUE THREAD

**Issue by bungeman** [harfbuzz/harfbuzz#3609]
If an `hb_face` is created with `hb_face_create_for_tables` and passed to `hb_subset_or_fail` then a valid but very empty `hb_face` is returned (0 tables). At least one should get nullptr to indicate an error, or better yet an actual subset. This appears to be due to `hb_subset_plan_execute_or_fail` assuming `success` is true by default and `hb_face_get_table_tags` always returns 0 for faces created with `hb_face_create_for_tables` since that interface currently doesn't allow the user to specify the tables. Therefore `hb_subset_plan_execute_or_fail` returns that is has "successfully" subset the 0 tables it could find.

This is especially interesting for cases when using CoreText which does not provide a general API for the full flat data of the original font, the API is table based where one can query which tables are available and then get a copy of each table on request. It would be nice not to be required to flatten all the tables and re-create a ttf header to do the subset, which is more or less going to make another (partial) copy of the data anyway.

For the short term just making the check to ensure that the `hb_face` is capable of listing its tables should be made in `hb_subset_plan_execute_or_fail` and it should return nullptr if it is not. Longer term it would be nice to add a new API like `hb_face_create_for_tables` which takes a both a pointer to a `hb_reference_table_func_t` and a pointer to a new `hb_list_tables_func_t` which could fill out a list of table tags available. Then the subsetter could successfully subset table based fonts.

**Comment by garretrieger** [comment]
Another possible workaround I'm considering is if we detect the face was create_for_tables then try to subset all table types that we know how to subset and skip those that come back as empty/null. The one problem with this is that tables that we don't know how to subset will be dropped since we don't know to look for them, but that shouldn't be too much of a problem in practice.

**Comment by khaledhosny** [comment]
I think DirectWite supports returning the full font blob if the tag was NULL (or zero, I don't recall exactly), but I think CoreText does not support that. Might be worth trying first in case the underlying implementation supports it, though.

**Comment by behdad** [comment]
I'm leaning towards that as well, at least as a first step.

**Comment by behdad** [comment]
I think by default we drop unknown tables anyway(?). If user specifies passthrough-tables, we can query those and pass through. So no functionality loss?

**Comment by garretrieger** [comment]
I'll go ahead and implement my suggestion for now, definitely an improvement over the current state.

**Comment by behdad** [comment]
> I'll go ahead and implement my suggestion for now, definitely an improvement over the current state.

See if you can create a `static hb_vector_t<hb_pair_t<hb_tag_t, subset_table_func_t *>>` and populate it in a initializer list using macros...

**Comment by behdad** [comment]
Or not. Just do it however you do for now. We'll look into optimizing it later.

**Comment by bungeman** [comment]
I think we'd want to pass along more than just the list in this change. For example I don't see `avar` in this list. Probably should probe for all known tables (like this list should be the same as the list of tables in https://docs.microsoft.com/en-us/typography/opentype/spec/ ? Otherwise known tables won't be passed along.

**Comment by garretrieger** [comment]
avar and the other tables that need to be passthrough without being  subset are listed as part of no-subset tables: https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-subset-input.cc#L89

The change I'm working on checks for these in addition to the ones we explicitly subset.

**Comment by garretrieger** [comment]
I'll also add the full list of tables from the spec to be on the safe side.
