### ISSUE TITLE
Incorrect use of strncpy (destination string left unterminated)

### ISSUE THREAD

**Issue by francoisk** [harfbuzz/harfbuzz#3616]
https://github.com/harfbuzz/harfbuzz/blob/9eab6d326fc09d8957e082fb363cbe03b15feee0/src/hb-blob.cc#L574-L575

`strncpy` does not terminate the destination string if the first N characters of the source string does not contain a `'\0'` and thus the destination string (which was `malloc`'d) may be left unterminated.

**Comment by behdad** [comment]
Right. I wonder how this was tested...

Am I correct that removing the `- 1` is the right fix here?

**Comment by behdad** [comment]
> Right. I wonder how this was tested...
> 
> Am I correct that removing the `- 1` is the right fix here?

Because then the nul-termination from `_PATH_RSRCFORKSPEC` will be copied.

**Comment by francoisk** [comment]
> > Right. I wonder how this was tested...
> > Am I correct that removing the `- 1` is the right fix here?
> 
> Because then the nul-termination from `_PATH_RSRCFORKSPEC` will be copied.

Yes I also think that's the right fix.

**Comment by behdad** [comment]
Thanks. Fixed.
