### ISSUE TITLE
FT_Face size change seems different?

### ISSUE THREAD

**Issue by bungeman** [harfbuzz/harfbuzz#3619]
While attempting to roll [HarfBuzz into Chromium](https://chromium-review.googlesource.com/c/chromium/src/+/3673650) a number of tests failed to run as expected. I was able to locally bisect to https://github.com/harfbuzz/harfbuzz/commit/56e0ff9ea129aa91dfcc746cd61f8cbbc427dba7 . It appears that there is something off with the scale, most easily seen with https://ci.chromium.org/ui/p/chromium/builders/try/win10_chromium_x64_rel_ng/1196573/overview . Still investigating, but filing now for awareness.

**Comment by bungeman** [comment]
I was initially super confused about how this could even happen, since it doesn't look like blink if using these functions directly and Skia doesn't allow the FT_Faces it uses to escape for anyone to use them on. However, I now suspect this is due to [FreeType using HarfBuzz in the autohinter](https://source.chromium.org/chromium/chromium/src/+/main:third_party/freetype/src/src/autofit/afglobal.c;l=360;drc=773e31c78397a5471efb7c37d7cd1eca40b46351). I'll run a test to see if this is the case.

**Comment by behdad** [comment]
Oh my. Give me time to fully study your comments. But I keep forgetting that hb-ft is actually used by freetype and hence by Chrome and other serious apps...

**Comment by behdad** [comment]
> most easily seen with https://ci.chromium.org/ui/p/chromium/builders/try/win10_chromium_x64_rel_ng/1196573/overview

Can you please help me understand what to look for? I'm trying to understand what's failing, to understand what the best fix would be.

**Comment by behdad** [comment]
> > most easily seen with https://ci.chromium.org/ui/p/chromium/builders/try/win10_chromium_x64_rel_ng/1196573/overview
> 
> Can you please help me understand what to look for? I'm trying to understand what's failing, to understand what the best fix would be.

@bungeman

**Comment by bungeman** [comment]
I don't have a minimized case yet, but I might be able to work one up tomorrow. I think that this can be seen just by creating an `FT_Face`, setting it up with an `FT_Size` (I think just setting up the default one should work) and loading an outline glyph with `FT_Load_Glyph` with `FT_LOAD_FORCE_AUTOHINT`. While loading the outline the FreeType autohinter should create an `hb_font` from the `FT_Face` and then set it the `hb_font` to em size with [hb_font_set_scale](https://source.chromium.org/chromium/chromium/src/+/main:third_party/freetype/src/src/autofit/afshaper.c;l=483;drc=8d6a246c9be4f6b731dc7f6e680b7d5e13a512b5). I think that might be what's causing the difference here, as prior to this change this would not have affected the underlying `FT_Face`. Then again I haven't had time to poke at this much, so it could be due to one of the other calls on the `hb_font`, but I don't see anything else as obviously mutating.

**Comment by behdad** [comment]
The easiest fix might be fore FreeType to create sub-font of hb-font.

That said, my gut feeling is to revert that change and ask users to manually notify hb-ft if the hb-font changed. We shouldn't be checking for updates all the time (as this change is doing). Let me just do that.
