### ISSUE TITLE
[myanmar] Category OT_As (asat) is 18, which is same as OT_Symbol in indic file

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3632]
What title says. Not sure this was every intended.

**Comment by dscorbett** [comment]
It’s just a coincidence. `OT_As` was introduced in 98628cac9f733f2674d6409954cddb7d0634c233 when the Myanmar shaper was split off from the Indic shaper. The maximum Indic category at the time was 17, so `OT_As` became 18. `OT_Symbol` (originally called `OT_Avag`) was introduced later in 3c7b3641cfb00f2c4dcc0768b9854e4f4410d15f. The maximum Indic category at the time was still 17, so `OT_Avag` became 18.

Why does it matter?

**Comment by behdad** [comment]
If `OT_symbol` is not used in Myanmar shaper, that is not clear. I'll take a look to see if we can make that more clear.

**Comment by behdad** [comment]
The reason it matters is that if a Script=Common character has OT_Symbol category, then it would have been accepted where OT_As is accepted, because we start with Indic table data in the Myanmar shaper.

**Comment by behdad** [comment]
> because we start with Indic table data in the Myanmar shaper.

And Khmer shaper. But maybe we should stop doing that?
