### ISSUE TITLE
Shaping Tai Tham Analogue of Thai Sara Am

### ISSUE THREAD

**Issue by Richard57** [harfbuzz/harfbuzz#364]
Despite the title, I don't think this matter is specific to USE, and it may be that it is unreasonable to hope that OpenType renderers will all work the same way - I want to have a font that will have the same outcome on native Windows, HarfBuzz, M17n and Core text.  The essence of my problem is that the base-mark association logic does not work as I expected, and in particular works differently on Windows (as seen in MS Edge) and in HarfBuzz (as seen in Firefox Version 49).    Perhaps I should only trust base-mark association logic needed for Arabic.

Printed Northern Thai in the Lanna script has a close analogue (or rather two) of U+0E33 THAI CHARACTER SARA AM.  It was initially proposed to encode what would have become TAI THAM SIGN AM and TAI THAM SIGN TALL AM.  However, leading figures in the UTC insisted that these
compound vowel symbols be encoded as what became <U+1A63 TAI THAM VOWEL SIGN AA, U+1A74 TAI THAM SIGN MAI KANG> and <U+1A64 TAI THAM VOWEL SIGN TALL AA, U+1A74 TAI THAM SIGN MAI KANG>.

To shape these vowel symbols in the printed Northern Thai style (which is also many people's handwritten style), I have to transfer the non-spacing mark MAI KANG from the spacing mark SIGN AA or SIGN TALL AA  to the preceding consonant.  I had been doing this by aping the  processing for Thai, i.e.:

**Prelude:**
 1. Ligate SIGN AA and MAI KANG to glyph 'mai_kam', which imitates THAI CHARACTER SARA AM.

**Imitation of Thai:**
2. Decompose ('multiple substitution') 'mai_kam' to mark 'leftward_mai_kang' and the glyph 'mai_kaa' of SIGN AA.

3. Interchange leftward_mai_kang and any intermediately preceding tone mark.  (The Thai rendering engine does this, but USE does not.)

**Finalisation**
4. Replace 'leftward_mai_kang' by the normal glyph for MAI KANG.

Now, USE inserts U+25CC before SIGN AA and MS USE therefore also before all the subsequent marks.  However, it seems that the effects of cleaning them out are irrelevant to my problem, for this also occurs when I use a Latin to Lanna transliteration mode, where these inserts do not occur.  It also shows up in the Lanna script in LibreOffice 5.0.6 on Ubuntu, which appears to  be using the old SEA rendering engine.

The problem arises when the reduplication mark MAI SAM is appended to the word.  The problem appears whether or not there is a tone mark, though the detailed mechanism might be different.  The problem is that the MAI SAM glyph is not treated as being on the mai_kaa glyph regenerated by splitting mai_kam.  When mai_kam is split into the mark leftward_mai_kang and the base mai_kaa (in that order), the MAI SAM glyph is associated with the leftward_mai_kang rather than the residual base mai_kaa. This base-mark association logic was introduced in 2012 to match Microsoft's treatment of marks on an Arabic consonant ligature split by a multiple substitution. The practical consequence is that MAI SAM glyph is attached directly to the base consonant.  In my font it is then obscured by the mai_kang glyph which is also attached directly, and seems to disappear!

The problem does not occur with USE as in MS Edge - the word renders as expected.

The renderings of words with and without tone marks are shown below.  The text on the left was derived straight from Lanna script: the text in the middle was derived by rendering a transliteration.  Both involved the same sequence of Lanna glyphs in logical order.  The hex in the middle is the sequence of codepoints for the Lanna text.

![mammam](https://cloud.githubusercontent.com/assets/23389913/20232754/6c8ae3b4-a862-11e6-954a-0dc4c68cfd11.png)

**Comment by Richard57** [comment]
I've implemented a workaround which has the minor draw back that the displayed glyph for MAI KANG has no obvious connection to the corresponding character, but is instead a contextual extrusion of the tone mark or preceding base consonant.  (Does HarfBuzz clustering show the difference?  MS hit detection won't.)

My fonts suffering from the logged issue are Da Lekh (Seri) Version 0.05 (and earlier).

**Comment by behdad** [comment]
What's the concrete suggested change to HarfBuzz?

**Comment by Richard57** [comment]
I'm not sure.  Perhaps the answer is that bases should not be allowed to be split into mark + base, only base + mark.  If a base may legitimately split into mark + base, then the marks on the original base need to be associated with the new base.

Now, there is a very similar problem described by Martin Hosken at   https://github.com/OpenType/opentype-layout/blob/master/docs/ligatures.md .  That problem does apply to Windows.  It is probably not good if a HarfBuzz fix also cures this problem, for then a font developed against HarfBuzz will have an undiagnosable problem when used on Windows.

Perhaps I should have made SIGN AA a mark rather than a base, though that may cause other problems - the joys of mark filtering sets.

**Comment by behdad** [comment]
Okay closing based on discussion. Moreover, if any such change is to happen, it should be proposed to USE, not to HarfBuzz.
