### ISSUE TITLE
Windows build failures on main

### ISSUE THREAD

**Issue by rvandermeulen** [harfbuzz/harfbuzz#3647]
With current tip (9fc9b1e), I'm seeing Firefox build bustage as shown by the log below:
https://treeherder.mozilla.org/logviewer?job_id=380704829&repo=try&lineNumber=19640
```
INFO -  In file included from /builds/worker/checkouts/gecko/gfx/harfbuzz/src/hb-aat-layout.cc:28:
INFO -  /builds/worker/checkouts/gecko/gfx/harfbuzz/src/hb.hh(477,25): error: constexpr variable 'destroy' must be initialized by a constant expression
INFO -    static constexpr auto destroy = hb_free;
INFO -                          ^         ~~~~~~~
```
This is with clang 14. All other platforms build fine. Fallout from b5f621b it appears.

**Comment by behdad** [comment]
I reverted that. Fortunately it was unused still.

**Comment by behdad** [comment]
Do you know what Firefox defined `hb_free` to?

**Comment by rvandermeulen** [comment]
AFAIK, it's just following the `#define hb_free free` define. Not sure if I can manage to dig through our memory allocator far enough to figure out how `free` ends up defined on Windows vs. other platforms, though.
