### ISSUE TITLE
[myanmar] Reconsider punctuation_cluster

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3649]
See https://github.com/harfbuzz/harfbuzz/pull/3648#discussion_r894670004 and discussion.

**Comment by behdad** [comment]
Should we report U+104A to Unicode? In the corpus I see both characters taking Asat. It's weird that one is categorized by Unicode and not the other.

**Comment by dscorbett** [comment]
Yes, if you’re sure the evidence is trustworthy, and not a typo or something like Zawgyi.

**Comment by behdad** [comment]
> Yes, if you’re sure the evidence is trustworthy, and not a typo or something like Zawgyi.

I don't know that. Maybe @mhosken knows.
