### ISSUE TITLE
Inconsistent Seg Faults in hb_shape_plan_create_cached2

### ISSUE THREAD

**Issue by TruckDynasty** [harfbuzz/harfbuzz#3666]
Using a 5 day old build of libharfbuzz on a raspberry pi 3b+ (arm64).
The calling application is UVtools (a dotnet build that uses libHarfBuzzSharp as a shim)

4 out of 5 times the seg fault occurs the first time hb_shape_plan_create_cached2() is called (before execution finishes with the library function call).

1 out of 5 times the seg fault occurs after numerous calls to hb_shape_plan_create_cached2 () (the most recent run had more than 10 calls to hb_shape_plan_create_cached2 before I deleted the breakpoint and continued exectution, though a seg fault still occured during a call to hb_shape_plan_create_cached2)

The application is multi-threaded, but every observed call to hb_shape_plan_create_cached2() occurs in the primary thread

I'm still poking at this, going to try building the *most* recent version of harfbuzz now, then going to try older versions.  Please let me know if there's additional info that might be useful!

**Comment by behdad** [comment]
Are you building libharfbuzz with proper multi-threading facilities?

**Comment by behdad** [comment]
The 5day old vs latest should not matter at all.

**Comment by TruckDynasty** [comment]
I'm not sure if there's anything special I need to do for multi-threaded, but  the exact build steps I used were:
  git clone https://github.com/harfbuzz/harfbuzz
  cd ./harfbuzz
  meson build
  meson test -Cbuild

Then copied the final .so files over to my library directory (the libharfbuzz that's available from the apt repos don't work with libHarfBuzzSharp!)

**Comment by behdad** [comment]
That should work fine then.  You can also manually run `build/test/threads/hb-shape-threads` and see if that works.

**Comment by TruckDynasty** [comment]
Hmm, just ran the hb-shape-threads, outputs:

Num threads 3; num repetitions 1
Testing shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/hb
/opt/harfbuzz/build/test/threads/hb-shape-threads: symbol lookup error: opt/harfbuzz/build/test/threads/hb-shape-threads: undefined symbol: hb_blob_create_from_file_or_fail

Does this indicate an issue?

**Comment by behdad** [comment]
That's not the issue we care about here. That means it's linking to your older, system harfbuzz. Weird but not thread-related.

**Comment by TruckDynasty** [comment]
You're right!  For some reason everywhere else uses the ld.so.conf files for libraries, but dotnet is still defaulting to the (very old) version in /usr/lib/aarch64-linux-gnu

I think I need to update a specific path for dotnet, let me try that

**Comment by behdad** [comment]
But I'm not sure why the test is failing to run against the harfbuzz you just built.

**Comment by TruckDynasty** [comment]
I think it has something to do with the *.so vs the .so.0, I only copied the files over as libharfbuzz.so, didn't include a link for libharfbuzz.so.0.

readelf -Ws --dyn-syms on the built harfbuzz has the symbol hb_blob_create_from_file_or_fail, but the old system default I have does not...

**Comment by TruckDynasty** [comment]
The *.so.0 files actually exist, they must have been created when I ran ldconf, so it must just be a dotnet environment variable I'm missing

**Comment by TruckDynasty** [comment]
wow, I think you can close this issue...  I set my LD_LIBRARY_PATH variable (that dotnet uses) to prefer the system harfbuzz library over the built harfbuzz library.  I basically built libHarfBuzzSharp using the newest version of libharfbuzz, and told dotnet to use the old version of libharfbuzz....    Thank you so much for your help!
