### ISSUE TITLE
Applying multiple lookup records in (Chain)Context rules

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3675]
My reading of the code block at https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/MS/Internal/Shaping/Context.cs,92 suggests that this implementation at Microsoft applies lookup records in a (Chain)Context lookup in the order of their index, NOT in the order that they appear. It also suggests that duplicate records are only applied once.

Now that code is from 2002 and quite likely this has been changed in Uniscribe / DWrite. Asking for clarification. cc @PeterCon @SergeyMalkin

cc @seehuhn @khaledhosny

**Comment by behdad** [comment]
> applies lookup records in a (Chain)Context lookup in the order of their index, NOT in the order that they appear.

Or.. in the order of their lookup-index first, then their sequence-index?

**Comment by seehuhn** [comment]
Just a quick note (sorry I'm late): the behaviour you describe is [what the spec requires](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#features-and-lookups), too: "To implement features, a client processes the lookups referenced by a given feature in the order the lookup definitions occur in the LookupList. As a result, within the GSUB or GPOS table, lookups from several different features may be interleaved during text processing."

**Comment by behdad** [comment]
@seehuhn That applies to the top-level application of the features. I wouldn't have expected it to apply to the recursive lookups.
