### ISSUE TITLE
Adjust new namespace layout

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3677]
The new internal namespace layout needs some adjustment. For GSUB we are doing:
```
namespace OT::Layout::GSUB {
struct GSUB;
}

namespace OT {
struct GSUB_accelerator_t;
}
```

This scheme fails for non-accelerated tables. Eg.:
```
namespace OT::glyf {
...glyf's impl...
}
namespace OT {
struct glyf;
}
```
this errs because `OT::glyf` is defined both as a namespace and struct. Moving `glyf` inside `OT::glyf` doesn't work because the face object needs to find it at `OT_glyf`. I suggest we change things to:
```
namespace OT::glyf_impl {
...
}
namespace OT {
struct glyf;
}
```

cc @garretrieger

**Comment by behdad** [comment]
I'm trying to split the `glyf` code and hit this.

**Comment by behdad** [comment]
I did this in glyf. We probably should do in GSUB. Then move the top-level GSUB table up one namespace.

**Comment by garretrieger** [comment]
sounds good. I'll incorporate that into my GPOS reorg change and then can do the same for GSUB.
