### ISSUE TITLE
negation of LookupFlag::IgnoreFlags is not correctly done with arm gnu toolchain

### ISSUE THREAD

**Issue by arouaux-mej** [harfbuzz/harfbuzz#3703]
Hi,

We are currently using version 4.3.2 of harfbuzz and we compile it for a CortexM3 target compiling the code with the arm gnu toolchain.

We observed a rendering difference between what we have on our target compared to hb-view output, for the same font and script (thai script).

Digging into the code we found that the issue comes from this line of code in hb-ot-layout-gpos-table.hh
````
skippy_iter.set_lookup_props (c->lookup_props & ~LookupFlag::IgnoreFlags);
````
Before the call of set_look_props(), c->lookup_props value is 0x10010; but the input argument of set_lookup_props () is 0x10 whereas the value of LookupFlag::IgnoreFlags is 0xE;

We saw that ~LookupFlag::IgnoreFlags is computed to 0x0000FFF1 for CM33 implementation whereas it is computed to 0xFFFFFFF1 for linux implementation.
As LookupFlag is a HBUINT16, derived from IntType<uint16_t>, the 0x0000FFF1 is ok, but it seems that the bit 16 of lookup_props is used later in may_skip().

Could this be that bit 16 is not allowed in glyph_props?

This code is now located in MarkMarkPosFormat1.hh

Thanks for your help.

**Comment by arouaux-mej** [comment]
Digging into the code I found that the bit 16 is used to store the markFilteringSet information.

`  /* lookup_props is a 32-bit integer where the lower 16-bit is LookupFlag and
   * higher 16-bit is mark-filtering-set if the lookup uses one.
   * Not to be confused with glyph_props which is very similar. */
  uint32_t get_props () const
  {
    unsigned int flag = lookupFlag;
    if (unlikely (flag & LookupFlag::UseMarkFilteringSet))
    {
      const HBUINT16 &markFilteringSet = StructAfter<HBUINT16> (subTable);
      flag += (markFilteringSet << 16);
    }
    return flag;
  }`

Maybe the LookUpFlag enum should be move to HBUINT32?

**Comment by behdad** [comment]
Would this help?
```diff
diff --git a/src/OT/Layout/GPOS/MarkMarkPosFormat1.hh b/src/OT/Layout/GPOS/MarkMarkPosFormat1.hh
index c48a74f77..3462fb846 100644
--- a/src/OT/Layout/GPOS/MarkMarkPosFormat1.hh
+++ b/src/OT/Layout/GPOS/MarkMarkPosFormat1.hh
@@ -100,7 +100,7 @@ struct MarkMarkPosFormat1
     /* now we search backwards for a suitable mark glyph until a non-mark glyph */
     hb_ot_apply_context_t::skipping_iterator_t &skippy_iter = c->iter_input;
     skippy_iter.reset (buffer->idx, 1);
-    skippy_iter.set_lookup_props (c->lookup_props & ~LookupFlag::IgnoreFlags);
+    skippy_iter.set_lookup_props (c->lookup_props & ~(uint32_t)LookupFlag::IgnoreFlags);
     unsigned unsafe_from;
     if (!skippy_iter.prev (&unsafe_from))
     {
```
