### ISSUE TITLE
multiple warnings in hb-algs.hh and hb-ot-metrics.cc, possible misuse of comma operator, clang

### ISSUE THREAD

**Issue by kaie** [harfbuzz/harfbuzz#3716]
Building with clang 14.0.5 I get multiple warnings about possible misuse of comma operator

One example is:
mozilla/gfx/harfbuzz/src/hb-algs.hh:983:43: error: possible misuse of comma operator here [-Werror,-Wcomma]
for(; a < end; a++, b++) { ((tmp) = (*a), (*a) = (*b), (*b) = (tmp)); }

See https://phabricator.services.mozilla.com/D151590 for the places where I had to disable the warning.

**Comment by behdad** [comment]
Does this work? https://github.com/harfbuzz/harfbuzz/pull/3719

**Comment by behdad** [comment]
clang 14.0.0 doesn't catch those. We have -Wcomma in our error list...
