### ISSUE TITLE
Glyph flag for kashida insertion

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3721]
Kashida insertion as it is currently implemented in many software is incompatible with fonts that make heavy use of contextual alternates (e.g. Amiri), since kashida insertion is done after shaping and applications have no way to know if inserting a kashida after two glyphs will break their connection or not.

I considered checking for `HB_GLYPH_FLAG_UNSAFE_TO_BREAK`, but it is not usable for this as it is set between any two connected Arabic letters.

I’m wondering if it is possible to have a flag similar to `HB_GLYPH_FLAG_UNSAFE_TO_BREAK` but it would be set only if there is a substitution or positioning other than the `init`/`medi`/`fina` features?

For example in Amiri, in the following sequence the first and last glyphs are the same regardless of the presence of kashida, so it would be safe to insert it post shaping:
```
$ hb-shape Amiri-Regular.ttf "به بـه" --show-flags --no-positions --no-clusters
[heh-ar.fina#3|kashida-ar.1#3|beh-ar.init|space|heh-ar.fina#3|beh-ar.init]
```

But not in this sequence (since there is a contextual substitution involved):
```
$ hb-shape Amiri-Regular.ttf "له لـه" --show-flags --no-positions --no-clusters
[heh-ar.fina#3|kashida-ar.1#3|lam-ar.init|space|heh-ar.fina.LamHeh#3|lam-ar.init.LamHeh]
```

Both sequences currently get the same glyph flags. It is just an idea though, and might not be that useful since the only HarfBuzz client that does any kashida insertion at all is LibreOffice (it should be able to make use of such a glyph flag, though).

**Comment by khaledhosny** [comment]
I was thinking of something like this:
```
diff --git a/src/hb-ot-shaper-arabic.cc b/src/hb-ot-shaper-arabic.cc
index ea1d49daa..0261039ec 100644
--- a/src/hb-ot-shaper-arabic.cc
+++ b/src/hb-ot-shaper-arabic.cc
@@ -328,7 +328,7 @@ arabic_joining (hb_buffer_t *buffer)
     if (entry->prev_action != NONE && prev != UINT_MAX)
     {
       info[prev].arabic_shaping_action() = entry->prev_action;
-      buffer->unsafe_to_break (prev, i + 1);
+      //buffer->unsafe_to_break (prev, i + 1);
     }
     else
     {
@@ -362,7 +362,7 @@ arabic_joining (hb_buffer_t *buffer)
     if (entry->prev_action != NONE && prev != UINT_MAX)
     {
       info[prev].arabic_shaping_action() = entry->prev_action;
-      buffer->unsafe_to_break (prev, buffer->len);
+      //buffer->unsafe_to_break (prev, buffer->len);
     }
     else if (2 <= state && state <= 5) /* States that have a possible prev_action. */
     {
```

Wouldn’t contextual init/medi/fina lookups also cause the flag to be set on their own?

**Comment by behdad** [comment]
I see. Let me think about it.

**Comment by khaledhosny** [comment]
The flag have been working wonderfully so far.

The issue I’m having now is that this flag is not set for AAT or Graphite fonts, and all Arabic fonts that ship with macOS are AAT fonts. This is probably unfixible given how AAT (and Graphite) don’t make a distinction between basic and advanced shaping, but I thought to ask just in case.

**Comment by behdad** [comment]
> The flag have been working wonderfully so far.

Great!

> The issue I’m having now is that this flag is not set for AAT or Graphite fonts, and all Arabic fonts that ship with macOS are AAT fonts. This is probably unfixible given how AAT (and Graphite) don’t make a distinction between basic and advanced shaping, but I thought to ask just in case.

Correct. I don't have any ideas, short of considering all ContextualSubtable substitutions as basic shaping. Try this:
```diff
diff --git a/src/hb-aat-layout-morx-table.hh b/src/hb-aat-layout-morx-table.hh
index aa4ad4cf3..f206ff1fc 100644
--- a/src/hb-aat-layout-morx-table.hh
+++ b/src/hb-aat-layout-morx-table.hh
@@ -264,7 +264,7 @@ struct ContextualSubtable
       }
       if (replacement)
       {
-       buffer->unsafe_to_break (mark, hb_min (buffer->idx + 1, buffer->len));
+       buffer->unsafe_to_tatweel (mark, hb_min (buffer->idx + 1, buffer->len));
        buffer->info[mark].codepoint = *replacement;
        if (has_glyph_classes)
          _hb_glyph_info_set_glyph_props (&buffer->info[mark],
```

**Comment by khaledhosny** [comment]
Does not seem to make a differece:
```diff
diff --git a/src/hb-aat-layout-morx-table.hh b/src/hb-aat-layout-morx-table.hh
index aa4ad4cf3..e1fccce1e 100644
--- a/src/hb-aat-layout-morx-table.hh
+++ b/src/hb-aat-layout-morx-table.hh
@@ -264,7 +264,7 @@ struct ContextualSubtable
       }
       if (replacement)
       {
-       buffer->unsafe_to_break (mark, hb_min (buffer->idx + 1, buffer->len));
+       buffer->safe_to_insert_tatweel (mark, hb_min (buffer->idx + 1, buffer->len));
        buffer->info[mark].codepoint = *replacement;
        if (has_glyph_classes)
          _hb_glyph_info_set_glyph_props (&buffer->info[mark],
```

```
$ ./util/hb-shape /System/Library/Fonts/Supplemental/Beirut.ttc سنة --show-flags --safe-to-insert-tatweel
[tehmarbutafinalarabic=2+852#1|noonmedialarabic=1+682#1|seeninitialarabic=0+850]
```

But now I have some wild idea. These font have `just` table and it seems to have some notion of where Kashida can be inserted, may be one can check this table and find places where the flag can be set. May be I should give it a try.

**Comment by behdad** [comment]
Interesting. Yeah let's try.

**Comment by behdad** [comment]
> May be I should give it a try.

It's rather nontrivial piece of work though.
