### ISSUE TITLE
[subset] Doesn't build with HB_NO_VAR

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3735]

**Comment by qxliu76** [comment]
I have a PR  #3736  that fixes issues in hb-subset-plan.cc, but seems there're still issues in other files that need a fix.

**Comment by behdad** [comment]
> I have a PR #3736 that fixes issues in hb-subset-plan.cc, but seems there're still issues in other files that need a fix.

Thanks. Building the library is enough. I made the util/ dir build. The tests don't need to build.
