### ISSUE TITLE
[subset] COLR table closure need not repeat multiple times

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3739]
I don't think it does, because glyphs produced by it cannot be consumed by the table itself.

**Comment by behdad** [comment]
I might be wrong though.

**Comment by qxliu76** [comment]
So V0 and V1 closures are separate. 
V0 closure method is straightforward, just adding all referenced gids for base gids(through firstLayerIndex and numLayers). I think we would need to repeat this multiple times for V0 until we reach a stable gid set.

V1 closure is graph traversing so there's no need to repeat when V0 tables do not exist. I'm thinking I could add some code to break the loop when V0 tables do not exist.

When both V0 and V1 tables exist, we would need to repeat both. Let me know what you think

**Comment by behdad** [comment]
> V0 closure method is straightforward, just adding all referenced gids for base gids(through firstLayerIndex and numLayers). I think we would need to repeat this multiple times for V0 until we reach a stable gid set.

I don't think so, no. No need to repeat. Just a one-time map.

**Comment by behdad** [comment]
That's because, at least in V0, when a glyph maps to a set of layers, those layers are non-color layers, so no need to recurse on them.

**Comment by qxliu76** [comment]
> That's because, at least in V0, when a glyph maps to a set of layers, those layers are non-color layers, so no need to recurse on them.

oh OK, if these are non-color layers we don't need to repeat, I'll come up with a PR for this

**Comment by khaledhosny** [comment]
Fixed with 0f800769379d05a3086cd3fc56f0c4c1a19076f8
