### ISSUE TITLE
HarfBuzz 4.4.0 breaks character sizing with SDL2_ttf

### ISSUE THREAD

**Issue by a-hurst** [harfbuzz/harfbuzz#3746]
Hi there,

Just reported this to the `SDL2_ttf` team and they asked that I report it here. Basically, with HarfBuzz 4.4.1, updating the size of a font after opening it seems to update its internal character widths incorrectly such that increasing font size means characters get larger but not much farther apart. See the images in the SDL issue here for an illustration of what's going on: https://github.com/libsdl-org/SDL_ttf/issues/232

If I manually roll back HarfBuzz to 4.3.0 the problem disappears, so it's something that changed between that version and now that's causing problems. 

Internally, `SDL2_ttf` uses FreeType to update the size of an open font and then calls `hb_ft_font_changed` on the underlying harfbuzz font to update it (see the code for `TTF_SetFontSizeDPI` [here](https://github.com/libsdl-org/SDL_ttf/blob/b36f876a61d450d12042ac26d7e689ef1c472413/SDL_ttf.c#L1896-L1944)). The calculation of character sizes and spacing happens [here](https://github.com/libsdl-org/SDL_ttf/blob/b36f876a61d450d12042ac26d7e689ef1c472413/SDL_ttf.c#L3189-L3229). Is this code doing something wrong, or did 4.4.0/4.4.1 introduce an unexpected bug?

Thanks in advance!

Austin

**Comment by behdad** [comment]
> If I manually roll back HarfBuzz to 4.3.0 the problem disappears, so it's something that changed between that version and now that's causing problems.

Things did indeed change. I'm sorry it broke this. I'm looking into it. If you can share your SDL sample app it would help debugging. Thanks.

**Comment by behdad** [comment]
> If you can share your SDL sample app it would help debugging. Thanks.

Nevermind. I can reproduce this now.

**Comment by behdad** [comment]
Should be fixed.

**Comment by a-hurst** [comment]
Fantastic, thanks so much!
