### ISSUE TITLE
harfbuzz doesn't build correctly with clang-cl

### ISSUE THREAD

**Issue by Neumann-A** [harfbuzz/harfbuzz#3756]
reason:

https://github.com/harfbuzz/harfbuzz/blob/1945b400da4bb9fbc50e51b3e61f5d0c171c11c0/src/meson.build#L476

the check is wrong. It doesn't include clang-cl

**Comment by khaledhosny** [comment]
I have no idea what clang-cl is, but if you have a patch it will be appreciated.

**Comment by Neumann-A** [comment]
> I have no idea what clang-cl is

the cl replacement from llvm.  Basically clang but accepting MSVC style options for cl. 

since your are already using the solution elsewhere I assumed you knew what was going on:

https://github.com/harfbuzz/harfbuzz/blob/e2cc34e1908c26efddbfd497b707c712583f8243/meson.build#L87

So just change it to use `get_argument_syntax` instead of `get_id`
