### ISSUE TITLE
Disable BORING_EXPANSION by default?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3757]
Given that most users would also need FreeType support, should we disable this by default for the time being? That would allow us more room to tweak the format in case we need to.

**Comment by rsheeter** [comment]
I'm +1 on having this opt-in at this stage, but you are the owner :)

**Comment by behdad** [comment]
> I'm +1 on having this opt-in at this stage, but you are the owner :)

I'm asking opinions as you see. :)

**Comment by khaledhosny** [comment]
I think having it enabled by default makes testing simpler, and it is not like there are such fonts on the wild so users shouldn’t be affected. Hopefully FreeType changes wont take too long, and people using latest HarfBuzz tend to have latest FreeType, too.

**Comment by matthiasclasen** [comment]
Making it opt-in makes sense to me. It would be good to have tests with the new format to test that things fail cleanly and as expected.
