### ISSUE TITLE
[ot-font] Support non-Unicode cmap subtables

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3761]
I haven’t researched this fully yet, but such fonts seem to exist in the wild, e.g. https://bugs.documentfoundation.org/show_bug.cgi?id=146916. I suspect this is practically only CJK fonts. Opening in case we want to look into this.

**Comment by behdad** [comment]
I'm fine if there's algorithmic mapping to Unicode....

**Comment by khaledhosny** [comment]
Looks like this is going to require big mapping tables.
