### ISSUE TITLE
Building problem in harbuzz-5.1.0 inVisual Studio (MSVC) 2019 (version 16.11.17)

### ISSUE THREAD

**Issue by DJuego** [harfbuzz/harfbuzz#3769]
Hi! Thank you for this project!

Today I built the latest version in debug mode. I got:

```
harfbuzz-5.1.0\src\hb-subset.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
```
On the other hand, the compilation works correctly in release mode.

DJuego

**Comment by behdad** [comment]
Thanks for the kind words.

This is a limitation of your compiler, and it already tells you what to do to work around it, which is to compile with `/bigobj`.

**Comment by DJuego** [comment]
Yeah.  I was reporting it because it didn't happen in version 4.4.1. At least I have recorded the difference. :-)  Good. I'll test with the flag. 

Thanks for the quick reply!

DJuego
