### ISSUE TITLE
Import aots test suite

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#378]
https://github.com/adobe-type-tools/aots

There's already a harfbuzz test runner there.  Just build aots and import resulting font files and expectations into harfbuzz.

**Comment by behdad** [comment]
Currently I get 45 failures.  The first one I checked is because in horizontal direction, harfbuzz does ignores y-advance for example.

To run, in aots:
```
$ make
$ cd harfbuzz
$ make
$ g++ hb-aots-tester.cpp  `pkg-config --cflags --libs harfbuzz`
$ ./a.out
```

**Comment by behdad** [comment]
cc @brawer re opentype test suite.

**Comment by behdad** [comment]
@ebraminio any chance you want to look into this?

**Comment by ebraminio** [comment]
Let's track it on #1395 now that it has a uploaded patch
