### ISSUE TITLE
explanation on build.md

### ISSUE THREAD

**Issue by yashpalgoyal1304** [harfbuzz/harfbuzz#3784]
i am having trouble understanding this sentence - it contains two "when building with" clauses without any punctuation, so, i couldn't figure out the structure of it. can u help?

> ... when building with MSVC when building with meson

https://github.com/harfbuzz/harfbuzz/blob/dc09053f1924a486058a8737fda22567e6d95213/BUILD.md?plain=1#L21-L22

**Comment by behdad** [comment]
Thanks. I reworded to "when building with MSVC, using meson." Hope that helps.

**Comment by yashpalgoyal1304** [comment]
Thanks a lot for mentioning the issue in commit too
