### ISSUE TITLE
shaper differences between ot and ft font funcs with VS1/VS2 

### ISSUE THREAD

**Issue by wez** [harfbuzz/harfbuzz#3806]
Over in https://github.com/wez/wezterm/issues/2475 I'm trying to get VS1/VS2 variations to work with `MATHEMATICAL SCRIPT CAPITAL A`.

This font was provided by the user reporting the issue:
https://github.com/wez/wezterm/files/9480120/JuliaMono-Light.ttf.zip

The issue is that the shaper returns something that looks a bit wonky when using freetype font functions:

```
; hb-shape ~/Downloads/JuliaMono-Light.ttf/JuliaMono-Light.ttf $(printf "\U1d49c\Ufe01")  --show-flags --show-extents --no-glyph-names --font-funcs=ft
[3387=0+1200<69,1494,1080,-1518>|3=0+0<0,0,0,0>]
```

there's an extra zero-advance space, and the variation isn't respected, using glyph 3387 which is the default/VS1 variation.

Contrast with `ot` funcs, which returns the correct glyph 3388:

```
; hb-shape ~/Downloads/JuliaMono-Light.ttf/JuliaMono-Light.ttf $(printf "\U1d49c\Ufe01")  --show-flags --show-extents --no-glyph-names --font-funcs=ot
[3388=0+1200<26,1463,1147,-1481>]
```

Question 1:

Is this considered to be a bug in harfbuzz's `ft` font functions / shaping flow?

Question 2:

Is there a recommended way to use `ot` font functions with a face created by `hb_ft_font_create_referenced`?

I've been looking at not using a freetype face with harfbuzz and instead creating a face/font from a blob, but I'm having some trouble with the returned metrics.  In particular, I have doubts about how bitmap strikes are sized for otb/emoji fonts, and I'm seeing some funkiness with proportional fonts. The documentation around setting up the size in harfbuzz is a bit terse and I'd appreciate some guidance!

**Comment by khaledhosny** [comment]
> Is this considered to be a bug in harfbuzz's `ft` font functions / shaping flow?

Seems like a FreeType bug, HarfBuzz calls `FT_Face_GetCharVariantIndex()` and it is returning zero (i.e. not supported) for this sequence and font.

> Is there a recommended way to use ot font functions with a face created by hb_ft_font_create_referenced?
`hb_ot_font_set_funcs()`

**Comment by khaledhosny** [comment]
```
$ ./util/hb-shape JuliaMono-Light.ttf -u "1d49c,fe01" --font-funcs=ft
tt_face_build_cmaps: broken cmap sub-table ignored
[u1D49C=0+1200|space=0+0]
```

So it seems FreeType do not like the cmap subtable of this font. Decompiling then compiling the font with FontTools `ttx` magically fixes the issue.

Checking with `ots-sanitize`:
```
$ ots-sanitize JuliaMono-Light.ttf
ERROR: cmap: Out of order Unicode value (1D49C <= 1D4D0) in mapping 1 of variation selector 0
ERROR: cmap: Failed to parse format 14 cmap subtable 2
ERROR at ../src/ots.cc:711 (ProcessGeneric)
ERROR: cmap: Failed to parse table
Failed to sanitize file!
```

So the font is broken (out of spec at least), may be FreeType can be more tolerant, but better ask for the font to be fixed.

**Comment by cormullion** [comment]
Thanks. Can you say a bit more about what  

```
Out of order Unicode value (1D49C <= 1D4D0)
```

means? - I can then report it to the devs of the Glyphs app that builds the font.

**Comment by khaledhosny** [comment]
It means `uvsMappings` in [Non-Default UVS table](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#non-default-uvs-table) are not sorted by Unicode value, but Glyphs app devs should know what is means, just point them to the `ots-sanitize` output.

**Comment by cormullion** [comment]
OK, thanks for your help!

**Comment by wez** [comment]
@khaledhosny thanks for your help! I'm still having a hard time getting advance metrics that are consistent with those that I got from freetype when I try to use opentype funcs, so I'm inclined to stick with freetype functions, and revisit the metrics again in the future!

**Comment by khaledhosny** [comment]
Feel free to ask any further question in the discussions.

**Comment by behdad** [comment]
> I'm still having a hard time getting advance metrics that are consistent with those that I got from freetype when I try to use opentype funcs, so I'm inclined to stick with freetype functions, and revisit the metrics again in the future!

I'm curious to know what you're seeing, and to help you to transition to using hb-ot-font.
