### ISSUE TITLE
ZWNJ should be ignored in GPOS

### ISSUE THREAD

**Issue by aminabedi68** [harfbuzz/harfbuzz#3808]
Hi
ZWNJ should be ignored in GPOS so font engineers able to control relative space(kerning) between both sides.
for example in the following image, font has a negative kerning value between `ar_yeh_barree_fina` & `ar_gaf_init`, but it's not possible to apply it, because there is ZWNJ between them.

![rect5426](https://user-images.githubusercontent.com/25493297/188282176-ca4f398a-5335-4e2b-9887-fba362da8314.png)

**Comment by behdad** [comment]
My instinct is that we already do this. Let me check the code.

**Comment by behdad** [comment]
Yep:
https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-ot-layout-gsubgpos.hh#L485

So, there's another reason that it's not matching.

**Comment by behdad** [comment]
@aminabedi68 can you email me the font?

**Comment by aminabedi68** [comment]
> My instinct is that we already do this. Let me check the code.

i confirm, there was a mistake in my font, i was pretty sure kerning class include ar_yeh_barree_fina, i checked it again and realize it was not. i added it and now working perfectly. i apologize.

![image10](https://user-images.githubusercontent.com/25493297/188285045-584da300-196c-444b-bf85-669feb3b5c01.png)

(if you still want check the font please let me know)
