### ISSUE TITLE
Installing harfbuzz with cmake does not install any pkg-config pc files

### ISSUE THREAD

**Issue by ankith26** [harfbuzz/harfbuzz#3809]
Hello!

I'm trying to package freetype along with harfbuzz, and I'm using cmake on linux (which is a centos7 docker image running under Ubuntu 22.04 WSL, which in turn is running under Windows 11; this info is probably not relevant)

Before the install, freetype (without harfbuzz) is already installed, and none of the other dependencies are installed.

I'm running
```
mkdir build && cd build

cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/ \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=true \
  -DHB_HAVE_FREETYPE=true 
make
make install
```

The install runs without any fail, and the second pass of freetype compilation (with harfbuzz support) also runs: but I don't have a `harfbuzz.pc` in `/usr/local/lib/pkgconfig` as I'd expect.

This means I can't call `pkg-config` with `freetype2` (which errors)
```
sh-4.2# pkg-config --cflags freetype2
Package harfbuzz was not found in the pkg-config search path.
Perhaps you should add the directory containing `harfbuzz.pc'
to the PKG_CONFIG_PATH environment variable
Package 'harfbuzz', required by 'FreeType 2', not found
```

I did a `find` for `harfbuzz.pc` and it's not installed on any directory on the container.
I know that the meson build system is recommended by harfbuzz now, but I thought this bug was still worth reporting

**Comment by khaledhosny** [comment]
HarfBuzz CMake support is community maintained, if someone can fix the issue then patches are welcome.

**Comment by ankith26** [comment]
I just realised this issue is kinda a duplicate of #896
That being said, I'd like to try and patch this issue myself if it's easy enough... If it's not I'll give up on cmake and use meson
