### ISSUE TITLE
Can't disable required ligatures in Geeza Pro

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#3819]
Disabling required ligatures works well with Noto Sans Arabic:

```
$ build/util/hb-shape ~/Downloads/Noto_Sans_Arabic/NotoSansArabic-VariableFont_wdth,wght.ttf --features=-rlig "لا"
[uniFE8E=1+291|uniFEDF=0+260]
```

but does not seem to be possible with Geeza Pro, which is an AAT font:

```
$ build/util/hb-shape /System/Library/Fonts/GeezaPro.ttc --features=-rlig "لا"                                    
[u0644_u0627.isolated.lamAlef=0+1162]
```

This was discussed in:
https://github.com/w3c/csswg-drafts/issues/7634

Is this a limitation of the AAT font here (not allowing a separation between what's required an what's optional), or is this a bug in mapping the requested disabling or rlig to the AAT shaping execution?

(Mac Chrome fails a few now optional WPT tests because of that: https://bugs.chromium.org/p/chromium/issues/detail?id=1365036)

CC @jfkthame

**Comment by behdad** [comment]
Does it work in Safari?

**Comment by behdad** [comment]
Although, disabling required-ligatures is not supported anyway.

**Comment by behdad** [comment]
> is this a bug in mapping the requested disabling or rlig to the AAT shaping execution?

'rlig' is not mapped to any AAT features.

**Comment by drott** [comment]
> Although, disabling required-ligatures is not supported anyway.

Where?

**Comment by behdad** [comment]
> > Although, disabling required-ligatures is not supported anyway.
> 
> Where?

https://learn.microsoft.com/en-us/typography/opentype/spec/features_pt#rlig

"UI suggestion: Control of this feature should not generally be exposed to the user."

**Comment by behdad** [comment]
Another aspect is to say that AAT has no equivalent of `rlig` indeed.

**Comment by drott** [comment]
In the CSS WG I argued it's useful to disable it if fonts have their ligatures in the wrong category and for things like font debugging. But okay, if there is no mapping, than this is WontFix for AAT.

**Comment by jfkthame** [comment]
It should be possible to map to Feature = kLigatures, Selector = kRequiredLigaturesOffSelector, no?

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM09/AppendixF.html#Type1

**Comment by jfkthame** [comment]
This seems to work as expected:
```
$ ./util/hb-shape --font-file /System/Library/Fonts/GeezaPro.ttc --unicodes 644,627 
[u0644_u0627.isolated.lamAlef=0+1162]

$ ./util/hb-shape --font-file /System/Library/Fonts/GeezaPro.ttc --unicodes 644,627 --features rlig=0
[u0627.final.alef=1+647|u0644.initial.lam=0+515]
```
