### ISSUE TITLE
Unclear `hb_ot_color_glyph_reference_png()` documentation 

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3826]
From https://harfbuzz.github.io/harfbuzz-hb-ot-color.html#hb-ot-color-glyph-reference-png:
> To get an optimally sized PNG blob, the UPEM value must be set on the font object. If UPEM is unset, the blob returned will be the largest PNG available.

But there is no UPEM setting for `hb_font_t`, so I’m not sure what this mean, the scale? (but this defaults to UPEM already if I’m not mistaken).

**Comment by behdad** [comment]
Should say PPEM.
