### ISSUE TITLE
Preferring CBDT extents over glyf/CFF ones

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3827]
Currently we check extents in sbix, glyf, CFF, CBDT in that order. This is probably OK because CBDT fonts don’t usually have outline tables, but the font [`NotoColorEmoji_WindowsCompatible.ttf`](https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji_WindowsCompatible.ttf) has glyf table with empty glyphs (which makes installable on Windows as well as macOS), so we return empty extents for its glyphs.

Is there any reason we shouldn’t move CBDT extents before outline table, like we do with sbix extents?

**Comment by behdad** [comment]
SGTM.
