### ISSUE TITLE
There is a Crash on iOS platform

### ISSUE THREAD

**Issue by LukiYLS** [harfbuzz/harfbuzz#3832]

**Comment by LukiYLS** [comment]
crash shortcut

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/15795917/192504177-c498bf27-d6ee-4689-89cb-1354b1fc7de8.png">

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/15795917/192504240-8c5a0036-eca7-4098-966c-c9d7d46deb8a.png">

It likes this cast error

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/15795917/192504355-aed199c5-4519-4323-97e0-5d34dba30745.png">

**Comment by jfkthame** [comment]
What is the font involved?

**Comment by LukiYLS** [comment]
> What is the font involved?

I use a fallback typeface

**Comment by LukiYLS** [comment]
> What is the font involved?

It only happens Shape the emoji, and macos is ok

**Comment by LukiYLS** [comment]
> What version of HarfBuzz?

commit id 858570b1d9912a1b746ab39fbe62a646c4f7a5b1

**Comment by LukiYLS** [comment]
There is also a problem with the latest release version

**Comment by LukiYLS** [comment]
Fixed

**Comment by behdad** [comment]
> Fixed

What was the problem?

**Comment by LukiYLS** [comment]
> > Fixed
> 
> What was the problem?

```
auto typeface = reinterpret_cast<Typeface*>(user_data);

  auto data = typeface->CopyTableData(tag);
  if (!data) {
    return nullptr;
  }
  return hb_blob_create(reinterpret_cast<char*>(data->writable_data()), static_cast<unsigned int>(data->size()),
                        HB_MEMORY_MODE_DUPLICATE, data.get(), nullptr);
```

I use HB_MEMORY_MODE_READONLY , but data is deep copied 
use HB_MEMORY_MODE_DUPLICATE  is OK
