### ISSUE TITLE
Release time

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3836]
To get repacker changes out for uharfbuzz.

**Comment by behdad** [comment]
- "Women, Life, Freedom" #MahsaAmini
- ...
- Towards variable font instancing in the subsetter.
- Subsetter repacker improvements.
- New API: Optical bounds.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/5.3.0
