### ISSUE TITLE
New minor release needed for additional repacker fix

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#3840]
It would be good to get out a new minor release with this repacker bugfix: https://github.com/harfbuzz/harfbuzz/commit/9559d3c1c16812ed202852977ab11f10e3ebe804

So that it can be included in a uharfbuzz release.

**Comment by garretrieger** [comment]
We'll want to resolve: https://github.com/harfbuzz/harfbuzz/issues/3845 first

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/5.3.1
