### ISSUE TITLE
add defines for optional apis

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3843]
This https://gitlab.gnome.org/GNOME/pango/-/blob/main/meson.build#L281 is just ugly.

It would be nicer to have harfbuzz something like 

    #define HB_DIRECT_WRITE 1

in some always installed config header.

It would also be nice to install a pc file, like harfbuzz-dwrite.pc

**Comment by benjamin-otte** [comment]
See also https://gitlab.gnome.org/GNOME/pango/-/issues/707

**Comment by behdad** [comment]
I suppose we can install a `hb-config.h` that has those. Generating it (specially with our current two build systems) is ugly though. Time to drop one I guess...

**Comment by matthiasclasen** [comment]
See https://github.com/harfbuzz/harfbuzz/pull/3847

**Comment by matthiasclasen** [comment]
This was merged
