### ISSUE TITLE
question about grapheme clustering

### ISSUE THREAD

**Issue by wez** [harfbuzz/harfbuzz#3844]
Over in https://github.com/wez/wezterm/issues/2572 I had to do some extra post-processing for the sequence U+28 U+FF9F and @khaledhosny suggested that I raise this question over here to see if @behdad had opinions about it.

HarfBuzz shapes that sequence as two distinct clusters, the first with position 0 and the second with position 1.
However, when the application is using grapheme clustering, since that sequence is a single grapheme according to unicode segmentation rules, it would prefer to see them both reported as the same cluster with position 0.

Some background on that issue: wezterm uses grapheme clustering as the basis for deciding what comprises a cell in the terminal display, and then uses its notion of the number of cells that a grapheme should occupy for deciding the bounds when rendering the corresponding glyphs.  In this particular case, the difference in clustering and the fact that the U+FF9F glyph was found in a later fallback font meant that wezterm got confused and rendered both constituent glyphs with incorrect and overlapping bounding boxes.

wezterm already had some logic to reconcile re-ordered clusters but didn't consider that clustering might not be following the same rules. I've expanded the logic to compensate for this, but it is a bit inconvenient to retroactively determine this sort of mapping information.

If we could have harfbuzz use the same grapheme clustering then it could help shave off some overhead from wezterm's shaping logic.

What do you think about this?

I don't view it as HarfBuzz bug, but perhaps an enhancement to help with this case.

**Comment by behdad** [comment]
U+FF9F has the general-category Lm Letter-Mark. Those typically occupy their own space, unlike combining-marks. So I'm not sure why in this case you think it should combine with the parenthesis before it. Let me read the referenced issue.

**Comment by behdad** [comment]
If the Unicode algorithm combines them I guess we can do the same. Let me check that.

**Comment by behdad** [comment]
> If the Unicode algorithm combines them I guess we can do the same. Let me check that.

I have a hard time seeing which rule in the Unicode algorithm extends graphemes to Modifier_Letter's. In particular, they are not included here: https://unicode.org/reports/tr29/#Extend

**Comment by wez** [comment]
the https://github.com/dahosek/finl_unicode implementation assigns FF9F the Extend property based on this line in `auxiliary/GraphemeBreakProperty.txt` in the UCD data files:

```
FF9E..FF9F    ; Extend # Lm   [2] HALFWIDTH KATAKANA VOICED SOUND MARK..HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
```

**Comment by wez** [comment]
(that is consistent with the behavior of https://github.com/unicode-rs/unicode-segmentation as well, FWIW)

**Comment by behdad** [comment]
Okay, Grapheme_Extend minus Me,Mc,Mn is only four character ranges:
```
200C          ; Extend # Cf       ZERO WIDTH NON-JOINER
FF9E..FF9F    ; Extend # Lm   [2] HALFWIDTH KATAKANA VOICED SOUND MARK..HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
1F3FB..1F3FF  ; Extend # Sk   [5] EMOJI MODIFIER FITZPATRICK TYPE-1-2..EMOJI MODIFIER FITZPATRICK TYPE-6
E0020..E007F  ; Extend # Cf  [96] TAG SPACE..CANCEL TAG
```

We already handle ZWNJ, Emoji, and tags I believe.  It's just the U+FF9E..U+FF9F we are not handling. I'll add those in.  Indeed, current code says "Ignore Katakana for now.":

https://github.com/harfbuzz/harfbuzz/blob/bda42fc34a34c0c320784e4f8cba541ddc4573ca/src/hb-ot-shape.cc#L529-L539

**Comment by wez** [comment]
Thanks!
