### ISSUE TITLE
Fonts licensed under proprietary license

### ISSUE THREAD

**Issue by rahulmohang** [harfbuzz/harfbuzz#3845]
Hi, 

We have found some fonts licensed under an apparent proprietary license. Please see the font file, 'https://github.com/harfbuzz/harfbuzz/blob/main/test/subset/data/fonts/FranklinGothic-Regular.ttf'. The following reference to a license was seen in the file:

"
This font software is the property of Monotype Imaging Inc., or one of its affiliated entities (collectively, Monotype) and its use by you is covered under the terms of a license agreement. You have obtained this font software either directly from Monotype or together with software distributed by one of the licensees of Monotype. This software is a valuable asset of Monotype. Unless you have entered into a specific license agreement granting you additional rights, your use of this software is limited by the terms of the actual license agreement you have entered into with Monotype. You may not copy or distribute this software. If you have any questions concerning your rights you should review the license agreement you received with the software. You can learn more about Monotype here: www.monotype.comITCFranklinGothic LT Pro BkRegularCopyright © 2014 Monotype ITC Inc. All rights reserved.
"

Can you please let me know where can I find the license agreement for the file?

**Comment by behdad** [comment]
These seem to have been imported by mistake into the test suite. Thanks for bringing this to our attention. We should remove them.

**Comment by rahulmohang** [comment]
Thank you Behdad.
