### ISSUE TITLE
Indic reordering of pre-base reordering characters is backwards

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#3863]
<i>The Unicode Standard, Version 15.0</i> [clarifies](https://www.unicode.org/versions/Unicode15.0.0/ch02.pdf#page=50) that “For combining characters placed to the left of a base character, the combining characters start from the base character and are arranged leftward.” HarfBuzz’s USE shaper already does this.

The Indic shaper needs updating. Here is ⟨किॎ⟩ <U+0915, U+093F, U+094E>:
![किॎ](https://user-images.githubusercontent.com/1124347/199331645-46e53b58-90f6-4b4b-bd79-93f49c72b625.png)

The Myanmar shaper is a modification of the Indic shaper so it also needs updating. Here is ⟨ကေႄ⟩ <U+1000, U+1031, U+1084>:
![ကေႄ](https://user-images.githubusercontent.com/1124347/199332722-35759131-0052-4d38-8755-4c63bca7f2d7.png)

The Khmer shaper does not allow multiple pre-base vowels so this issue does not apply. It probably uses a copy of the Indic code for reordering too, though, so it still ought to be fixed.

**Comment by behdad** [comment]
> The Myanmar shaper is a modification of the Indic shaper so it also needs updating. Here is ⟨ကေႄ⟩ <U+1000, U+1031, U+1084>:

I thought for that one we tested and the order was intentional. @jfkthame @mhosken
