### ISSUE TITLE
Explicitly document what invariants the caller of hb_buffer_add_codepoints needs to uphold

### ISSUE THREAD

**Issue by hsivonen** [harfbuzz/harfbuzz#3889]
The documentation for `hb_buffer_add_codepoints` is unclear on whether the caller is required to guaranteed that the passed values are code points or scalar values. The terminology used in the direct documentation as well as  the function name and argument type says "code points", which doesn't make much sense. The NEWS file entry about the introduction of this methods strongly suggests that the invariant is scalar values.

Please document this more explicitly.

The context of this issue is that I'm [trying to figure out](https://github.com/unicode-org/icu4x/issues/2840) what whether [glue code between HarfBuzz and ICU4X](https://github.com/unicode-org/icu4x/pull/2839) should trust HarfBuzz to provide valid scalar values as the `ab` argument of `hb_unicode_decompose_func_t` and the `a` and `b` arguments of `hb_unicode_compose_func_t` on such a level that it would be appropriate to let Undefined Behavior ensue if HarfBuzz passes non-scalar values.

AFAICT, conceptually this depends on whether from the Rust perspective `hb_buffer_add_codepoints` should be considered equivalent to an unsafe Rust function that requires the caller to guarantee valid scalar value input.

**Comment by behdad** [comment]
> hb_buffer_add_codepoints

This function does not do any sanity check on the values. In contrast, `hb_buffer_add_utf32` does.

**Comment by hsivonen** [comment]
> I think code point and scalar value are the same thing. May be you mean _code units_?

No, I mean scalar values as the subset of code points that excludes surrogate code points.

> > hb_buffer_add_codepoints
> 
> This function does not do any sanity check on the values. In contrast, `hb_buffer_add_utf32` does.

Right. I think it would make sense to document that it is the reponsibility of the caller of `hb_buffer_add_codepoints` not to pass in values that would be caught by the checks performed by `hb_buffer_add_utf32`.

`hb_buffer_add_utf32`, as one would expect, does not consider surrogate code points as valid. Therefore, it would make sense to document that it is the responsibility of the caller of `hb_buffer_add_codepoints` to ensure that the code points passed in are, in fact, scalar values.

**Comment by behdad** [comment]
> Right. I think it would make sense to document that it is the reponsibility of the caller of `hb_buffer_add_codepoints` not to pass in values that would be caught by the checks performed by `hb_buffer_add_utf32`.

It's already there:

```
 * This function does not check the validity of @text, it is up to the caller 
 * to ensure it contains a valid Unicode code points. 
```

I'll add a note re `hb_buffer_add_utf32`.

**Comment by hsivonen** [comment]
> It's already there:
> 
> ```
>  * This function does not check the validity of @text, it is up to the caller 
>  * to ensure it contains a valid Unicode code points. 
> ```

It says "code points", but that doesn't make sense considering that `hb_buffer_add_utf32`, etc., ensure scalar values. This issue is about asking it to say "scalar values" rather than "code points" if that's what's actually meant. (If that's not what's meant, I'm interested in why.)

**Comment by hsivonen** [comment]
Thanks.
