### ISSUE TITLE
[draw] hb_font_get_glyph_shape() always uses the slant of the parent

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3890]
I’m trying to use hb_font_get_glyph_shape() on a font that has synthetic slant set on it, but I don’t want to apply the slant, so I created a sub font and set the slant on it to zero, but I’m still getting slanted outlines. Is this expected?

**Comment by behdad** [comment]
Definitely not expected. I think I know why it's happening though.

**Comment by behdad** [comment]
The parent font already returns shapes slanted. The subfont's slant, if anything, would be added to the parent font. Does *that* happen? I don't think it does.  Anyway, I think that would be the expected behavior, not what you expect.

**Comment by behdad** [comment]
> Does _that_ happen?

I don't think it does, but should be possible to fix.

**Comment by behdad** [comment]
> > 
> 
> I don't think it does, but should be possible to fix.

Humm. Seems to work. I'm not sure why.

**Comment by behdad** [comment]
Oh, because I set the slant on the parent font, nevermind.

**Comment by behdad** [comment]
> Oh, because I set the slant on the parent font, nevermind.

I tested setting slant on the child font only, still seems to work.

**Comment by behdad** [comment]
Adding the slants don't make sense though. Creating a new sub_font would double-slant.  Scratch that. Let me think more.

**Comment by behdad** [comment]
Oh. It looks like we *are* double-slanting currently.

**Comment by behdad** [comment]
> Oh. It looks like we _are_ double-slanting currently.

Or maybe not, but something very weird currently going on.

**Comment by behdad** [comment]
I agree with your initial expectation now. We just have to adjust the outlines for the difference in the slant in the `hb_font_get_glyph_shape_default_adaptor_t`.

For now, I'm seeing some weird behavior that I'm debugging.

**Comment by behdad** [comment]
> For now, I'm seeing some weird behavior that I'm debugging.

https://github.com/harfbuzz/harfbuzz/commit/2e9b270a496de14d3eee9d8b7e1372293bf13888

**Comment by behdad** [comment]
Fixed. Please test.

**Comment by khaledhosny** [comment]
Verified, thanks!
