### ISSUE TITLE
a HB_GLYPH_FLAG_UNSAFE_TO_BREAK and --features="-kern" case

### ISSUE THREAD

**Issue by caolanm** [harfbuzz/harfbuzz#3898]
Related to https://github.com/harfbuzz/harfbuzz/issues/3824 and https://github.com/harfbuzz/harfbuzz/issues/3888 and with the same font there I have one remaining issue I'm stuck on.

With
./hb-shape XBRoya34.ttf "إلى نل المواطدزد الذزد زُـساهمود دز الدضال ضد الزّور، والصشّ، والاسخـصلال، والاِسْخِلاص، والدساد، والاسخصداد، وزشملود مد أجل الحعزعة، والحرّزة، والنرامة، والشدالة، والدزمعراطزة، والخـعدّم، وحعوع الإدساد، والصززة السّلزمة، ودصل الدّزد شد الدولة.  " --direction=r --script=arab --language=ar --show-flags --features="-kern" --verify

I get:

...afii57388=187+638|afii57445=186+1040|afii57457=184+1#1|uniFEAA=184+1050#1|uniFECC=183+945#1...

so IIUC we can break before pos 186, but with the first 185 chars I get different results

./hb-shape XBRoya34.ttf "إلى نل المواطدزد الذزد زُـساهمود دز الدضال ضد الزّور، والصشّ، والاسخـصلال، والاِسْخِلاص، والدساد، والاسخصداد، وزشملود مد أجل الحعزعة، والحرّزة، والنرامة، والشدالة، والدزمعراطزة، والخـعد" --direction=r --script=arab --language=ar --show-flags --features="-kern" --verify

[uniFEAA=184+1050#1|uniFECC=183+945#1|afii57440=182+400#1...

Without --features=-"kern" I get, on the initial string I get:

...afii57388=187+638|afii57445=186+1040#1|afii57457=184+1#1|uniFEAA=184+1050#1|uniFECC=183+945#1...

and the issue doesn't arise

**Comment by behdad** [comment]
This one is really weird. Let me wrap my head around it.

**Comment by behdad** [comment]
> so IIUC we can break before pos 186, but with the first 185 chars I get different results

I think you're miscounting one here. Since the clusters start at 0, shouldn't you take the first 186? If I do that I get the same result.  I noticed this because in your original string there's two glyphs with cluster 184, but in your second result there's only one.  Indeed, in my testing, the string should end in والخـعدّ but yours ends in والخـعد.

```
build/util/hb-shape XBRoya34.ttf "إلى نل المواطدزد الذزد زُـساهمود دز الدضال ضد الزّور، والصشّ، والاسخـصلال، والاِسْخِلاص، والدساد، والاسخصداد، وزشملود مد أجل الحعزعة، والحرّزة، والنرامة، والشدالة، والدزمعراطزة، والخـعدّ" --direction=r --script=arab --language=ar --show-flags  --verify --features=-kern

[afii57457=184+1#1|uniFEAA=184+1050#1|uniFECC=183+945#1...
```

**Comment by behdad** [comment]
Also since you're passing `--verify` and it doesn't fail it means that things work fine as far as we can test.

**Comment by khaledhosny** [comment]
Is there anything left to address here?

**Comment by behdad** [comment]
I don't think so.
