### ISSUE TITLE
HB 6

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3918]
Let's remove `hb_subset_preprocess` from experimental and release HB 6 with it. It shows subset performance improvements of up to 80% and more in many cases, so I think it's worth a celebratory release.

**Comment by garretrieger** [comment]
hb_subset_preprocess is no longer experimental so we should be good to go with HB6. For the release notes: https://github.com/harfbuzz/harfbuzz/blob/main/docs/subset-preprocessing.md has some benchmarks for the speedup you can get with using preprocess.

**Comment by behdad** [comment]
Cool. Let's work on release notes here.

**Comment by garretrieger** [comment]
For the preprocess stuff how about:

* Added hb_subset_preprocess which adds data to a face that will speed up future subsetting operations on that face. Provides up to a 95% reduction in subsetting times. See: https://github.com/harfbuzz/harfbuzz/blob/main/docs/subset-preprocessing.md for more details and benchmarks.

**Comment by behdad** [comment]
There's been shaper speedup by skipping entire lookups when the buffer contents don't intersect with the lookup. Shows 10% speedup with Roboto-Regular.

**Comment by behdad** [comment]
I think we're good to go with those two items and "misc fixes and improvements".

**Comment by behdad** [comment]
Actually let's hold the release and get the VarComposites (varc branch) in as an experimental feature.

**Comment by behdad** [comment]
> Actually let's hold the release and get the VarComposites (varc branch) in as an experimental feature.

Okay. varc branch is merged. I'll prepare release notes for it.

**Comment by behdad** [comment]
Variable Composites is a new experimental feature in this release (enabled by passing `-Dexperimental_api=true` to `meson`). This technology enables drastic compression of fonts in the Chinese, Japanese, Korean, and other writing systems, by reusing the OpenType Font Variations technology for encoding "smart components" into the font.

These extensions to the font format adhere to the following specification of a new format of the `glyf` table:

  https://github.com/harfbuzz/boring-expansion-spec/blob/glyf1/glyf1.md

A test font with 3500 Hangul syllables has been built, with existing OpenType technology, as well as with the new Variable Composites (VarComposites) technology. The VarComposites font is 87% smaller than the OpenType version of the font!  Both fonts can be obtained from the "smarties" repository:

  https://github.com/behdad/smarties

When building HarfBuzz with experimental-api features enabled, you can test the "smarties" font with a sample character like this:

  $ build/util/hb-view butchered-hangul-serif-smarties-variable.ttf -u AC01

Finally, a Mac M1 binary of the FontGoggles font inspector application for the Mac is available:

  https://drive.google.com/drive/u/0/folders/1zOu2QpCtehSixPnt0OePJpdvWXkDKVpa

**Comment by behdad** [comment]
Good to go as far as I'm concerned. :)

**Comment by behdad** [comment]
@jfkthame @drott FYI.

**Comment by behdad** [comment]
Maybe we can sneak the (L1) instancing in as well: https://github.com/harfbuzz/harfbuzz/issues/3926

**Comment by behdad** [comment]
> Maybe we can sneak the (L1) instancing in as well: #3926

That is done as well. @garretrieger can you add release notes for it?

**Comment by drott** [comment]
In printing situations, we do one-off subsetting of fonts used in the page. Does preprocessing pay off for a one-off case, or does it only make sense if for one font, you'll call multiple different subsetting operations?

**Comment by behdad** [comment]
> In printing situations, we do one-off subsetting of fonts used in the page. Does preprocessing pay off for a one-off case, or does it only make sense if for one font, you'll call multiple different subsetting operations?

No it doesn't pay off for a single call.  The preprocessing cost is about that of subsetting the font for every glyph in it.

**Comment by behdad** [comment]
Okay, CFF infinite loop is fixed. I think we are good to go.

**Comment by garretrieger** [comment]
Release notes for instancing:
* Adds the ability for the subsetter to drop axes by pinning them to specific values (also referred to as instancing). There are a couple of restrictions currently:
  * Only works with truetype (glyf) based fonts. CFF and CFF2 fonts are not yet supported.
  * Only supports the case where all axes in a font are pinned.

**Comment by behdad** [comment]
I think we are good here finally!

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/6.0.0

**Comment by khaledhosny** [comment]
Can we drop autotools and CMake build support now?

**Comment by behdad** [comment]
> Can we drop autotools and CMake build support now?

Fine with me re autotools. I'm probably the last user. CMake seems to have users in the wild.

**Comment by khaledhosny** [comment]
> > Can we drop autotools and CMake build support now?
> 
> Fine with me re autotools. I'm probably the last user. CMake seems to have users in the wild.

When we drop autotools, CMake is going to bitrot much faster. Currently it shared `Makefile.sources` with autotools, but when it is the only user ~no one will remember to update them.

**Comment by Eli-Zaretskii** [comment]
Dropping autotools and CMake means the only supported build system is Meson, as far as I understand.  That requires Python 3.6 and Ninja, none of which are supported on Windows XP, as far as I know.  So dropping autotools means you are also dropping support for building HarfBuzz on Windows XP.  I hope this will not happen soon, because my main development machine still runs Windows XP.
