### ISSUE TITLE
[subset] Set old to new glyph mapping

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3920]
I’m looking into replacing LibreOffice’s own font subsetter with hb-susbet, and one issue is that LibreOffice collects  and writes text streams to the PDF before creating the font subsets, so the old to new glyph mapping need to be known up front.

There is `hb_subset_plan_old_to_new_glyph_mapping()` but I need to know the mapping before creating the subset plan, is there a way to have this?

**Comment by behdad** [comment]
> There is `hb_subset_plan_old_to_new_glyph_mapping()` but I need to know the mapping before creating the subset plan, is there a way to have this?

Not currently. There's a request from Ben for Skia as well.

**Comment by garretrieger** [comment]
It is something that we could support, but the one tricky part is some of the subsetting code is written with the assumption that the old to new glyph mapping is monotonic. So we wouldn't be able to accept arbitrary glyph mappings unless we audited the subsetting code and fixed the parts that depend on that assumption.

**Comment by behdad** [comment]
> It is something that we could support, but the one tricky part is some of the subsetting code is written with the assumption that the old to new glyph mapping is monotonic. So we wouldn't be able to accept arbitrary glyph mappings unless we audited the subsetting code and fixed the parts that depend on that assumption.

Accepting monotonic-only is acceptable I think.

We can't do any closure though.

**Comment by garretrieger** [comment]
Yeah that's right, in that case (mapping must be monotonic and no closure) it wouldn't be too hard to add support for supplying a mapping.

**Comment by behdad** [comment]
@garretrieger Let's get to this. Maybe this week?

**Comment by behdad** [comment]
> > It is something that we could support, but the one tricky part is some of the subsetting code is written with the assumption that the old to new glyph mapping is monotonic. So we wouldn't be able to accept arbitrary glyph mappings unless we audited the subsetting code and fixed the parts that depend on that assumption.
> 
> Accepting monotonic-only is acceptable I think.
> 
> We can't do any closure though.

If we can't do any closure, we would need to decompose any composite glyf though. Right? The PDF-producing client wouldn't know about composite glyphs.

**Comment by behdad** [comment]
> If we can't do any closure, we would need to decompose any composite glyf though. Right? The PDF-producing client wouldn't know about composite glyphs.

Or! Do glyf closure and add the glyphs higher up in the mapping.

**Comment by khaledhosny** [comment]
> Or! Do glyf closure and add the glyphs higher up in the mapping.

That should work.

**Comment by garretrieger** [comment]
Wouldn't that violate the monotonic mapping requirement? If we exclude the layout tables in the subset and check that the subsetting code for remaining tables doesn't rely on the monotonic mapping requirement then that could be fine.

**Comment by behdad** [comment]
> Wouldn't that violate the monotonic mapping requirement? If we exclude the layout tables in the subset and check that the subsetting code for remaining tables doesn't rely on the monotonic mapping requirement then that could be fine.

Yes. Even with layout subsetting, I *think* the glyf closure is not visible by the layout tables.

**Comment by garretrieger** [comment]
Yes, you're right. We don't add those to glyphset_gsub.
