### ISSUE TITLE
[hb-view] Relax build requirements on cairo-ft

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3925]
Currently we don't build hb-view if cairo-ft is not available. With hb-draw, that's not required anymore I believe. Can we test and relax that?

**Comment by behdad** [comment]
I do believe we still require freetype.

**Comment by khaledhosny** [comment]
I think I tried a while ago, it seems that freetype is still needed but probably can be worked out.

**Comment by behdad** [comment]
I'm trying to help @justvanrossum build hb-view on Mac, where he sees cairo as available but hb-view is not built. At least our messaging in meson configure is off as well. My guess is that his cairo lacks cairo-ft.
