### ISSUE TITLE
[draw] Composite glyph is shifted horizontally when using hb-draw

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#3929]
With the attached font and the glyph for U+064F is shifted horizontally when using hb-draw:
[Kitab-Regular.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/10202419/Kitab-Regular.ttf.zip)

```
$ HB_DRAW=1 hb-view Kitab-Regular.ttf -u 20,64f
```
![HB_DRAW=1](https://user-images.githubusercontent.com/93914/206909137-737164b4-d3cc-4381-982e-d0c70f1df574.png)

```
$ HB_DRAW=0 hb-view Kitab-Regular.ttf -u 20,64f
```
![HB_DRAW=0](https://user-images.githubusercontent.com/93914/206909160-bbf007dc-8e52-4bf3-8b42-e138547ccc74.png)

This seems to be a regression from a756bd1944404da6e53173c4061a2aef262e60f3 (or the font is faulty)

**Comment by behdad** [comment]
Upon reading the spec again, I'm reverting that commit.
