### ISSUE TITLE
COLRv1 api

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3931]
I want to use harfbuzz instead of freetype whereever possible. 
Currently, I can't get at the COLRv1 data without using freetype.

Here is a draft for a callback-style api for COLRv1, tentatively called hb-paint:

```
typedef struct hb_paint_funcs_t hb_paint_funcs_t;

typedef void (*hb_paint_push_transform_func_t) (hb_paint_funcs_t *funcs,
                                                void *draw_data,
                                                float xx, float xy,
                                                float yx, float yy,
                                                float x0, float y0,
                                                void *user_data);
typedef void (*hb_paint_pop_transform_func_t)  (hb_paint_funcs_t *funcs,
                                                void *draw_data,
                                                void *user_data);

typedef void (*hb_paint_push_clip_func_t)      (hb_paint_funcs_t *funcs,
                                                void *draw_data,
                                                hb_codepoint_t glyph,
                                                void *user_data); 
typedef void (*hb_paint_pop_clip_func_t)       (hb_paint_funcs_t *funcs,
                                                void *draw_data,
                                                void *user_data);

typedef void (*hb_paint_solid_func_t)          (hb_paint_funcs_t *funcs,
                                                void *draw_data,
                                                unsigned int color_index,
                                                void *user_data);

typedef struct hb_color_line_t hb_color_line_t;

typedef struct {
  float offset;
  unsigned int color_index;
} hb_color_stop_t;

unsigned int hb_color_line_get_color_stops (hb_color_line_t color_line,
                                            unsigned int start,
                                            unsigned int count,
                                            hb_color_stop_t *color_stops);

typedef enum {
  HB_PAINT_EXTEND_PAD,
  HB_PAINT_EXTEND_REPEAT,
  HB_PAINT_EXTEND_REFLECT
} hb_paint_extend_t;

hb_paint_extend_t hb_color_line_get_extend (hb_color_line_t color_line);

typedef void (*hb_paint_linear_gradient_func_t) (hb_paint_funcs_t *funcs,
                                                 void *draw_data,
                                                 hb_color_line_t *color_line,
                                                 hb_position_t x0, hb_position_t y0,
                                                 hb_position_t x1, hb_position_t y1,
                                                 hb_position_t x2, hb_position_t y2,
                                                 void *user_data);
                                             
typedef void (*hb_paint_radial_gradient_func_t) (hb_paint_funcs_t *funcs,
                                                 void *draw_data,
                                                 hb_color_line_t *color_line,
                                                 hb_position_t x0, hb_position_t y0,
                                                 float r0,
                                                 hb_position_t x1, hb_position_t y1,
                                                 float r1,
                                                 void *user_data);

typedef void (*hb_paint_sweep_gradient_func_t)  (hb_paint_funcs_t *funcs,
                                                 void *draw_data,
                                                 hb_color_line_t *color_line,
                                                 hb_position_t x0, hb_position_t y0,
                                                 float start_angle,
                                                 float end_angle,
                                                 void *user_data);

typedef enum {
  HB_PAINT_COMPOSITE_MODE_CLEAR,
  HB_PAINT_COMPOSITE_MODE_SRC,
  HB_PAINT_COMPOSITE_MODE_DEST,
  HB_PAINT_COMPOSITE_MODE_SRC_OVER,
  HB_PAINT_COMPOSITE_MODE_DEST_OVER,
  HB_PAINT_COMPOSITE_MODE_SRC_IN,
  HB_PAINT_COMPOSITE_MODE_DEST_IN,
  HB_PAINT_COMPOSITE_MODE_SRC_OUT,
  HB_PAINT_COMPOSITE_MODE_DEST_OUT,
  HB_PAINT_COMPOSITE_MODE_SRC_ATOP,
  HB_PAINT_COMPOSITE_MODE_DEST_ATOP,
  HB_PAINT_COMPOSITE_MODE_XOR,
  HB_PAINT_COMPOSITE_MODE_PLUS,
  HB_PAINT_COMPOSITE_MODE_SCREEN,
  HB_PAINT_COMPOSITE_MODE_OVERLAY,
  HB_PAINT_COMPOSITE_MODE_DARKEN,
  HB_PAINT_COMPOSITE_MODE_LIGHTEN,
  HB_PAINT_COMPOSITE_MODE_COLOR_DODGE,
  HB_PAINT_COMPOSITE_MODE_COLOR_BURN,
  HB_PAINT_COMPOSITE_MODE_HARD_LIGHT,
  HB_PAINT_COMPOSITE_MODE_SOFT_LIGHT,
  HB_PAINT_COMPOSITE_MODE_DIFFERENCE,
  HB_PAINT_COMPOSITE_MODE_EXCLUSION,
  HB_PAINT_COMPOSITE_MODE_MULTIPLY,
  HB_PAINT_COMPOSITE_MODE_HSL_HUE,
  HB_PAINT_COMPOSITE_MODE_HSL_SATURATION,
  HB_PAINT_COMPOSITE_MODE_HSL_COLOR,
  HB_PAINT_COMPOSITE_MODE_HSL_LUMINOSITY,
} hb_paint_composite_mode_t;

typedef void (*hb_push_group_func_t)            (hb_paint_funcs_t *funcs,
                                                 void *draw_data,
                                                 void *user_data);
typedef void (*hb_pop_group_and_composite_func_t) (hb_paint_funcs_t *funcs,
                                                   void *draw_data,
                                                   hb_paint_composite_mode_t mode,
                                                   void *user_data);

                                           
void hb_font_paint_glyph (hb_font_t *font,
                          hb_codepoint_t glyph,
                          hb_paint_funcs_t *funcs,
                          void *paint_data);
```

This should be sufficient to let hb walk the paint graph.

All the transform variations go like this:

```
push_transform (matrix)
// recurse
pop_transform ()
```
drawing a glyph is

```
push_clip (glyph)
paint_solid (...)
pop_clip ()
```

and composite is

```
push_group ()
// recurse for backdrop
push_group ()
// recurse for source
pop_group_and_composite (composite_mode)
pop_group_and_composite (OVER)
```

and layers are

```
for each layer
    push_group ()
    // recurse for layer paint
    pop_group_and_composite (OVER)
```

**Comment by behdad** [comment]
cc @drott

**Comment by matthiasclasen** [comment]
Essentially, this is a small portion of the cairo api, turned into hb callbacks

**Comment by behdad** [comment]
Thanks. I'm slowly studying this.

**Comment by matthiasclasen** [comment]
It'll need something very similar to hb_colrv1_closure_context_t for visiting all the Paint objects.

**Comment by matthiasclasen** [comment]
One thing missing is a way to pass the clipbox for PaintColrGlyph, since it needs to be respected too.

**Comment by matthiasclasen** [comment]
Here's a quick sketch: https://github.com/harfbuzz/harfbuzz/tree/wip/matthiasc/paint-api

**Comment by drott** [comment]
Thanks for the proposal, I didn't have time to fully review this yet, some thoughts:

One thing that I found while working on Skia impl: The equivalent of `push_clip()` + "unbounded fill" is slower than Skia operations for `fillRect()` and `fillPath()` etc. - I think this works with this callback pattern, but it might be slightly less ergonomic to implement such an optimization. The client receiving the callbacks would need to hold action and wait for the next callback to determine if the next table in the traversal is a `PaintGlyph`. So perhaps it may make sense to provide callbacks for something like `fillPath()` as an optionally set addition. 

Also, when designing the FreeType API we had to find a way to make the client aware of previously configured transformations on FreeType. I.e. the scaleX, scaleY, dx, dy state that the `FT_Face` could have. Then those need to be taken into account when doing the drawing on the client side. The way we did that there was that we inserted a `fake` `PaintTransform` at the beginning of the glyph paint table traversal, that would set the graphics context to the same state as if the FreeType internal transforms were applied - might be worth considering here. I am not sure how the callbacks you're proposing interact with HarfBuzz scaling values or configured `ptem_size` - I haven't looked closer at that.

COLRv1 also needs cycle detection (importantly: across `PaintColrGlyph` tables as well) , would this be implemented on the HarfBuzz side and the callbacks would end?

Related to that: What do you propose for making the client aware that something failed in the traversal? Would there be something like a cancel callback? I think the client may need to know if something failed? That could also be in the return value of `hb_font_paint_glyph`.

**Comment by matthiasclasen** [comment]
@behdad any preference for error handling here? Other apis, such as hb_font_get_glyph_shape() don't return anything, and hb_ot_color_glyph_reference_png() return an error object, basically (the empty blob).

I also notice that we have some oddity of naming here:

hb_font_get_glyph_shape() vs hb_ot_color_glyph_reference_png()

Which side should this paint_glyph fall on?

So far, I did hb_font_paint_glyph(), but it could also be hb_ot_color_glyph_paint().

**Comment by matthiasclasen** [comment]
Another bit of ugliness I find while working on root transforms:

The caller needs a upem-scaled copy of the font without artificial slant, in order to obtain unscaled outlines. That will be a bit of a trap for the unwary.

**Comment by behdad** [comment]
> @behdad any preference for error handling here? Other apis, such as hb_font_get_glyph_shape() don't return anything, and hb_ot_color_glyph_reference_png() return an error object, basically (the empty blob).

Maybe we should change hb_font_get_glyph_shape() to return a bool false if font didn't have outline?

Same here, return false if there was no painting?

> I also notice that we have some oddity of naming here:
> 
> hb_font_get_glyph_shape() vs hb_ot_color_glyph_reference_png()
> 
> Which side should this paint_glyph fall on?
>
> So far, I did hb_font_paint_glyph(), but it could also be hb_ot_color_glyph_paint().

I like it on the font. What do you think about adding a draw-raster for png etc? Then it's unified.

> But I did briefly ponder about allowing hb_font_paint_glyph (font, plain_outline_glyph_id...) to work.

Yeah I'm in for that I think.

**Comment by matthiasclasen** [comment]
Thanks for the answers.

---

> Maybe we should change hb_font_get_glyph_shape() to return a bool false if font didn't have outline?

Yes, that would be nice if it does not break api in some way.

At some point it might be nice to have some glyph-info api where I can find out what data is available for a glyph:

```
typedef enum {
  HB_GLYPH_HAS_OUTLINE = 1 << 0, /* any of glyf, cff, cff2 */
  HB_GLYPH_HAS_PNG         = 1 << 1,  /* CBDT or sbix */
 HB_GLYPH_HAS_SVG           = 1 << 2,  /* SVG */
 HB_GLYPH_HAS_LAYERS     = 1 << 3,  /* COLRv0 */
 HB_GLYPH_HAS_PAINT       = 1 << 6   /* COLRv1 */
} hb_glyph_info_t;
```

There's some other ancillary information that would be useful to have, such as

```
HB_GLYPH_USES_FOREGROUND_COLOR
HB_GLYPH_HAS_VARIATIONS
```

These would be useful for cairo when deciding about caching or rendered glyphs.

---

> I like it on the font. What do you think about adding a draw-raster for png etc? Then it's unified.

Sure, can do that. and draw-svg.

**Comment by behdad** [comment]
> There's some other ancillary information that would be useful to have, such as
> 
> ```
> HB_GLYPH_USES_FOREGROUND_COLOR
> ```

We have to walk the paint graph to determine this. Easier to let the renderer determine itself.

> ```
> HB_GLYPH_HAS_VARIATIONS
> ```

This is nontrivial for CFF2; We have to parse the charstring and see if any blend operation was seen.

**Comment by behdad** [comment]
> We have to walk the paint graph to determine this. Easier to let the renderer determine itself.
> 
> >

As cairo does.

**Comment by behdad** [comment]
This is being tracked in https://github.com/harfbuzz/harfbuzz/pull/3938
