### ISSUE TITLE
Provide COLRv0 glyph metrics

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3935]
As a follow-up to https://github.com/harfbuzz/harfbuzz/pull/3928

It should be enough to just look at the glyph from the first layer. Or we can walk the laters and union all the extents (but the spec says they should be the same).

**Comment by khaledhosny** [comment]
The glyph advance for layers should be the same, but the extents can’t be always the same.

This got me thinking, if application is not rendering color layers for whatever reason, reporting color extents would be wrong. I feel a bit uncomfortable about this low level API doing such high level calculation. IMHO it should be up to whatever is traversing and composing the color layers to compose their glyph extents as well.

**Comment by anthrotype** [comment]
not sure if relevant here, but while developing our nanoemoji color font compiler, we noticed that when building a COLRv0 font, if we left the base (fallback) color glyph blank (i.e. empty without outlines), then on Mac (I think it was Mac only, not 100% sure though) no color glyph would be rendered, even when COLR table had some color layers associated with that base glyph. 
We ended up adding an invisible contour consisting only of a single straight line from the bottom left corner to the top right corner of the color glyph bounding box: 

https://github.com/googlefonts/nanoemoji/blob/5e6281b1c881ca3597760a9c0e0ad60ebaed71f4/src/nanoemoji/write_font.py#L344-L361

**Comment by khaledhosny** [comment]
If one asks for extents of GID 1, one gets extents of GID 1, with the proposed change one might get the extents of an entirely different glyph. That is (somewhat) like applying GSUB or GPOS on the glyph and returning the extents of the result.

**Comment by matthiasclasen** [comment]
Is there a definition for "extents of GID" somewhere ?

If hb_font_get_glyph_extents is only meant to cover outlines, then a) that should be documented and b) the COLRv1 api needs to provide clipboxes too, then

**Comment by khaledhosny** [comment]
Currently the API is low level, it gets the extents of the specified GID without much smartness, it checks relevant outlines and bitmap tables but otherwise does not do any form of composition (except for the recently merged COLRv1 stuff). GID is a low low level concept, and COLR table handles layers by composing different GIDs (unlike, say, bitmap or SVG tables where all the relevant data is local to the GID, if so to speak).

Here is some scenario where mixing high level and low level concepts would produce wrong results:
1. Suppose a font has GIDs 1, 2, 3, 4, and 5
2. GID 1 uses 2 and 3 as COLR layers
3. GID 2 uses 4 and 5 as COLOR layers
4. Now I’m rendering GID 1 and want the extents of its layers, so I ask for the extents of GID 2 and 3, but since GID 2 has COLR layers, I will be getting the extents of GID 4 (and/or GID 5) which is not what I want since I will not be rendering the layers for GID 3 but its own outlines.

**Comment by khaledhosny** [comment]
COLR layers are different from composite glyphs components since components can be nested but COLR layers don’t. So I think we need a different API that also handles COLR layers.

**Comment by matthiasclasen** [comment]
Right, you are essentially arguing for a "just give me all the bits" api. And then every consumer has to implement all of the COLR spec (and other things) by picking the right bits and combining them in just the right way...

**Comment by khaledhosny** [comment]
> And then every consumer has to implement all of the COLR spec (and other things) by picking the right bits and combining them in just the right way.

That is already the case. As a parallel, hb-draw API returns “raw” outlines and does not do any thing for color layers.

I’m not against adding an API that fits your needs, it is just that IMHO hb_font_get_glyph_extents is not a suitable one for this level.

**Comment by behdad** [comment]
> not sure if relevant here, but while developing our nanoemoji color font compiler, we noticed that when building a COLRv0 font, if we left the base (fallback) color glyph blank (i.e. empty without outlines), then on Mac (I think it was Mac only, not 100% sure though) no color glyph would be rendered, even when COLR table had some color layers associated with that base glyph.

I remember this. Which suggests that we don't need to do anything and the glyf-table bounds are enough.

**Comment by behdad** [comment]
> > not sure if relevant here, but while developing our nanoemoji color font compiler, we noticed that when building a COLRv0 font, if we left the base (fallback) color glyph blank (i.e. empty without outlines), then on Mac (I think it was Mac only, not 100% sure though) no color glyph would be rendered, even when COLR table had some color layers associated with that base glyph.
> 
> I remember this. Which suggests that we don't need to do anything and the glyf-table bounds are enough.

So. Should we close this then? If that's what Mac does?

**Comment by matthiasclasen** [comment]
I think is a question about api direction and documentation clarity here.

Is hb_font_get_glyph_extents() high-level api that works with any kind of glyph? Or low-level api that only works for some kinds of glyphs? If the latter, can the documentation be amended to say which kinds? If the former, we should add a get_clip_box() api

**Comment by matthiasclasen** [comment]
> So. Should we close this then? If that's what Mac does?

Fine with me.
