### ISSUE TITLE
request: hb_shape to return kerning values separately

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#3944]
When kerned text needs to be broken into lines between a pair of glyphs, the pair shouldn’t be kerned, because the glyphs are no longer adjacent. Text width needs to be measured without kerning where line breaks, the rest with kerning. Can’t tell where line breaks before measuring text width. A chicken and egg problem.

A way to deal with this is to measure entire text width with kerning, then where a line is _likely_ to break, get the kerning value at the position, exclude it from the text width, making sure it really fits in the line.

This two-step process can be avoided if hb_shape returns kerning values (to exclude) along with kerned glyph positions.

**Comment by behdad** [comment]
Let me first say that it's great to see you back @blueshade7!

**Comment by behdad** [comment]
There are a couple problems here:

1. We don't have room in the buffer to return more values,
2. As you know, in OpenType, kerning is just part of more generic positioning, which can move glyph around arbitrarily.

*If* it was just kerning though, you can get back the original advance of a glyph using `hb_font_get_glyph_h_advance` yourself.

**Comment by matthiasclasen** [comment]
Surely, text width is just MAX (glyph.x + glyph.width) - MIN (glyph.x) ?

**Comment by matthiasclasen** [comment]
Ok. But for each glyph, you can determine what the rightmost point is that it should contribute to the overall text width.

**Comment by blueshade7** [comment]
Suppose other width modifying features such as `palt` is applied in addition to `kern`. In this case, I want to undo `kern` only, not `palt`. Ultimately, I may end up calling `hb_shape` twice, with `kern`, without `kern` (but other features in place). Twice the time hit which I would like to avoid.

**Comment by behdad** [comment]
For line-breaking we have the UNSAFE_TO_BREAK and UNSAFE_TO_CONCAT machinery to avoid shaping twice. Note that there's ligatures etc, so you really want to reshape the line-break boundary.

**Comment by blueshade7** [comment]
> UNSAFE_TO_BREAK

I suppose it tells me where I am allowed to break a line. I am struggling to know the correct text width in order to determine where to break a line.
> you really want to reshape the line-break boundary

Are you suggesting reshaping at line-break boundary may change text width, not just because of kerning? If so, a naive general line breaking implementation needs to shape text up to every possible line breaking point just to determine where to break a line, incurring O(N^2) where N is the paragraph length. I wonder how other people are dealing with this.

**Comment by behdad** [comment]
Pretty much everyone I know makes an assumption that although reshaping text at boundary might change the glyphs, it remains roughly the same width... Wrong assumption, I know.

**Comment by blueshade7** [comment]
So sounds like my request only serves as a partial solution to the bigger problem, not worth the hassle to implement? I have no idea what the correction solution is though. Ok to withdraw this for now.

**Comment by behdad** [comment]
Yes, the bigger problem is actual shapes changing eg. mid-ligature line-breaks.

Returning non-kerned values will require changes to the buffer which would be a big change and ABI break.
