### ISSUE TITLE
hb_font_get_glyph_extents returns empty extents for composite glyphs

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3949]
I was wondering why my paint code does not render COLRv0 glyphs from fonts like RocherColorGX or BungeeColor-Regular. It turns out that the glyphs in these fonts are composites in the glyf table, and hb_font_get_glyph_extents returns empty extents for them, which causes my code to clip all drawing away.

**Comment by behdad** [comment]
Do you have a sample glyph that returns empty extents? This shouldn't happen. I'm looking into BungeeColor-Regular. The components seem to have proper bounding boxes that we should be returning.

**Comment by matthiasclasen** [comment]
maybe I was confused. I'll double-check
