### ISSUE TITLE
Meson build broken?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3953]
Trying a fresh meson build on Mac I get:
```
meson.build:1:0: ERROR: wrap-redirect /Users/behdad/harfbuzz/subprojects/freetype/subprojects/libpng.wrap filename does not exist
```

**Comment by behdad** [comment]
Humm. Deleting my source subprojects/ fixed it.

**Comment by eli-schwartz** [comment]
subprojects/freetype/ seems like it might be a git subproject? Was that deleted? If so, it could leave a stale state file referencing it, I suppose. The freetype wrap checked into harfbuzz uses release tarballs though.

**Comment by khaledhosny** [comment]
The wrap file recently was switched from wrap-git to wrap-file.
