### ISSUE TITLE
Confusion in hb-draw api

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3955]
The hb-draw callbacks take two pieces of data, draw_data and user_data, but it is confusing / unclear, which one is which.

```
/**
 * hb_draw_move_to_func_t:
 * @dfuncs: draw functions object
 * @draw_data: The data accompanying the draw functions
 * @st: current draw state
 * @to_x: X component of target point
 * @to_y: Y component of target point
 * @user_data: User data pointer passed by the caller
 *
 * A virtual method for the #hb_draw_funcs_t to perform a "move-to" draw
 * operation.
 *
 * Since: 4.0.0
 *
 **/
typedef void (*hb_draw_move_to_func_t) (hb_draw_funcs_t *dfuncs, void *draw_data,
                                        hb_draw_state_t *st,
                                        float to_x, float to_y,
                                        void *user_data);
```

The docs would seem to indicate that draw_data is the data passed to hb_draw_set_move_to_func, and user_data is coming from the hb_font_get_glyph_shape() call. The location of the arguments in the argument list also fit that.

Unfortunately, the docs for hb_draw_funcs_set_move_to_func() call its data user_data, not draw_data.

And looking at the implementation,

```
  void emit_move_to (void *draw_data, hb_draw_state_t &st,
                     float to_x, float to_y)
  { func.move_to (this, draw_data, &st,
                  to_x, to_y,
                  !user_data ? nullptr : user_data->move_to); }
```

In the struct, the storage for the data that is 'accompanying the draw funcs is called user_data, and it is passed as the last argument to the callback!  :(

---

I am really confused here, and don't know what the original intention was, or how to fix things up to be consistent.

**Comment by behdad** [comment]
> The docs would seem to indicate that draw_data is the data passed to hb_draw_set_move_to_func, and user_data is coming from the hb_font_get_glyph_shape() call.

It's the other way around. "Accompanying the draw-funcs" means passed to `get_glyph_shape` with the draw-funcs.

**Comment by matthiasclasen** [comment]
Suggested doc clarification:

```
/**
 * hb_draw_move_to_func_t:
 * @dfuncs: draw functions object
 * @draw_data: The data accompanying the draw functions
 * @st: current draw state
 * @to_x: X component of target point
 * @to_y: Y component of target point
 * @user_data: User data pointer passed to hb_draw_funcs_set_move_to_func()
 *
 * A virtual method for the #hb_draw_funcs_t to perform a "move-to" draw
 * operation.
 *
 * Since: 4.0.0
 *
 **/
```

If you agree, I'm happy to make that change everwhere.

**Comment by behdad** [comment]
Suggestion:

> * @draw_data: The data accompanying the draw functions

`The data accompanying the draw functions passed to hb_font_get_glyph_shape()`?

**Comment by matthiasclasen** [comment]
Can do. But it may _also_ come from a call to hb_draw_move_to(), which is why I hesitated to add it there

**Comment by behdad** [comment]
> Can do. But it may _also_ come from a call to hb_draw_move_to(), which is why I hesitated to add it there

You are right.
