### ISSUE TITLE
hb-subset: Segfault when mixing `--help-all` and other args

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#3956]
Commit c7dd63d1a04e797f21ba3fd7bb5aa5d08524c9dd.

```
~/E/harfbuzz (main|✔) $ build/util/hb-subset --layout-features="*" --layout-scripts="*" --drop-tables-="*" --instance="wght=100,wght=400,wght=700,wght=900" ~/.fonts/Cantarell-VF.otf --help-all
fish: Job 1, 'build/util/hb-subset --layout-f…' terminated by signal SIGSEGV
```

**Comment by behdad** [comment]
parse_instance accesses the font, which is wrong since we are still parsing input...

**Comment by garretrieger** [comment]
According to this comment, https://github.com/harfbuzz/harfbuzz/blob/main/util/hb-subset.cc#L100 seems like that's fine except when help is enabled. Easiest fix is to skip parsing instancing options if no face is available: https://github.com/harfbuzz/harfbuzz/pull/3964
