### ISSUE TITLE
Subsetting fails on certain font

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#3959]
All I get is:

```
> hb-subset.exe --glyphs="*" --instance="wght=200,wght=500,wght=800" vf.ttf -o a.ttf
error: Operation failed. Probably a bug. File github issue.
```

Sending the font privately.

**Comment by behdad** [comment]
This block in hb-subset is clearly failing the operation for GDEF if overflow happened:
```
static hb_blob_t* 
_repack (hb_tag_t tag, const hb_serialize_context_t& c) 
{ 
  if (tag != HB_OT_TAG_GPOS 
      &&  tag != HB_OT_TAG_GSUB) 
  { 
    // Check for overflow in a non-handled table. 
    return c.successful () ? c.copy_blob () : nullptr; 
  } 
```

**Comment by garretrieger** [comment]
We gate access to the repacker to tables that we know have object graphs. So probably don't want to completely remove that check, but should at least add GDEF and probably the COLRv1 table to the check.

**Comment by behdad** [comment]
> We gate access to the repacker to tables that we know have object graphs. So probably don't want to completely remove that check, but should at least add GDEF and probably the COLRv1 table to the check.

Why? If there's no object graph there will be one object and no overflow.
