### ISSUE TITLE
Subsetting should remove pinned axes from `fvar`

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#3961]
Currently, all axes seem to be left in, but they don't do anything. They should be removed; their entries in the `STAT` should stay though.

**Comment by qxliu76** [comment]
Hi, can I get a testcase for this issue?

**Comment by madig** [comment]
I think you can use https://github.com/googlefonts/roboto-flex/releases/tag/3.100 and instantiate e.g. wght=400.

**Comment by qxliu76** [comment]
oh, if we only pin wght to 400, that's partial instancing and not supported yet. I just tried that and got an error in dumping avar table when converting subsetted ttf to ttx file. This is expected because there's no code handling avar table.
Currently for VFs, we only support full instancing(all axes in a font are pinned). I tried pinning all axes in this font and it's working fine, all variation tables are dropped.

**Comment by madig** [comment]
Oh? I thought this meant that the subsetter fills in the default values for the non-specified axes? I can confirm that specifying all does the job :) A warning or somesuch would be nice.

**Comment by garretrieger** [comment]
> A warning or somesuch would be nice.

The API documentation specifies that all axes must be pinned currently: https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-subset-input.cc#L408

**Comment by khaledhosny** [comment]
IMO, the command line tool should use the default value for any omitted axis.

**Comment by khaledhosny** [comment]
Or may be not, I probably don't know what is this about and should shut up 😅

**Comment by behdad** [comment]
I agree with you.

**Comment by garretrieger** [comment]
The plan is to support partial instancing in the near future which would allow axes to be left unset. So for defaulting unspecified axes I'd be worried about the behaviour of the command line suddenly changing once partial instancing support lands. Instead for the command line we could error out with a helpful message if all axes are not set.

**Comment by khaledhosny** [comment]
Some fonts can have a large number of axes and having to explicitly list them all might be inconvenient, so may be a command line option to control what to do with unspecified axes?

**Comment by madig** [comment]
Hm, maybe a special case syntax like `wght=400,*=default`? 😬

**Comment by garretrieger** [comment]
*=default or something like that could work. I'll go check if fonttools current handles this case. If it does we should follow what they do.

**Comment by garretrieger** [comment]
Doesn't look like they do, fonttools and hb both currently use "drop" to mean pin to default. So if we do this in hb I would suggest using: *=drop

**Comment by qxliu76** [comment]
Currently we have "wght=drop" which means pinning to default, I believe this is the same as fonttools. But user still needs to enter [axis name]=drop for each axis

**Comment by anthrotype** [comment]
We can add *=drop to fonttools varLib.instancer if we like. Seems useful shorthand to have.
The old varLib.mutator would fill in default values automatically, but was limited to full instances

**Comment by garretrieger** [comment]
Alright sounds good, we'll add *=drop on the harfbuzz side too.

**Comment by behdad** [comment]
@qxliu76 for `*=drop`.

In the mean time, if partial-instancing is requested we should just err instead of producing broken fonts.

**Comment by garretrieger** [comment]
Partial instancing is now fully supported.
