### ISSUE TITLE
better gtk-doc setup

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3965]
Looking at bc4c290b7581bbcb7632d74a2ebebc24bd5df9f1 I realize we should probably set up --ignore-decorators for scan-args.

See how glib does it here: https://gitlab.gnome.org/GNOME/glib/-/blob/main/docs/reference/meson.build#L14

**Comment by khaledhosny** [comment]
We do set `--ignore-decorators`:
https://github.com/harfbuzz/harfbuzz/blob/80e68f09c5daef0c3dfef4fb44ebfbd22899bf8a/docs/meson.build#L50-L61

**Comment by matthiasclasen** [comment]
Ah, I missed that
