### ISSUE TITLE
[docs] Build docs by default when documentation enabled

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3966]
Currently one has to build the harfbuzz-docs target. Make it build them by default if documentation is enabled in meson.

**Comment by khaledhosny** [comment]
Seems to be by design, from https://mesonbuild.com/Gnome-module.html#gnomegtkdoc (emphasis mine):
> This also creates a `$module-doc` target that can be run to build documentation. Normally the documentation is ***only built on install***.

I don’t see a way to override this.

**Comment by khaledhosny** [comment]
GTK seems to be using gi-docgen not gtk-doc

**Comment by behdad** [comment]
Ah right. Thanks for checking.
