### ISSUE TITLE
hb_color_t pre-multiplied alpha or not

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3970]
Currently we don't specify.

Currently we just return values from CPAL, which are *not* pre-multiplied.

Ideally I like to change that, to be more uniform with the new paint_image() which takes image in pre-multiplied alpha format.

Jonathan, you are the sole user of this API. Any chance we can change this beneath your code? I don't know of any fonts that currently use alpha in the CPAL.

cc @jfkthame @matthiasclasen

**Comment by jfkthame** [comment]
Offhand my instinct is to think that something like `hb_ot_color_palette_get_colors` should remain a low-level API that returns unmodified data from the font table, so it's up to the caller to do whatever it wishes with it. But I'll try to look at it more closely and think about the implications. (Sorry, life a bit chaotic at present, I may not be very responsive...)

**Comment by matthiasclasen** [comment]
We actually need it unpremultiplied for cairo too.

cairo_set_source_rgba() and cairo_pattern_add_color_stop_rgba() both take unpremultiplied alpha.

**Comment by behdad** [comment]
Ah right. It's just the images that are premultiplied. We're good.
