### ISSUE TITLE
[face] Expose cmap mapping

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3973]
We have hb_face_collect_unicodes, we should expose the mapping counterpart the returns both a set and a map so people can walk the set and map to glyph.

**Comment by matthiasclasen** [comment]
I would expect something like

```
hb_bool_t
hb_face_get_glyph (hb_face_t      *face,
                   hb_codepoint_t  unicode,
                   hb_codepoint_t  variation_selector,
                   hb_codepoint_t *glyph)
```

?

**Comment by behdad** [comment]
> hb_bool_t
> hb_face_get_glyph (hb_face_t      *face,
>                    hb_codepoint_t  unicode,
>                    hb_codepoint_t  variation_selector,
>                    hb_codepoint_t *glyph)

Given that one can just create a font and get that already, I'm not very keen on adding it. Exposing cmap is for performance reasons to avoid having to call get_glyph on every glyph. I don't remember where it was needed that I filed this though.

**Comment by behdad** [comment]
> both a set and a map so people can walk the set and map to glyph.

I added iterator to hb_map_t now. So the hb_set_t to such new API should be made optional.
