### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [harfbuzz/harfbuzz#3981]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “_hb_directwrite_shaper_face_data_destroy”](https://github.com/harfbuzz/harfbuzz/blob/c091d029c2038de28f77d104f472b2d3bd417f0c/src/hb-directwrite.cc#L254 "Update candidate").

**Comment by behdad** [comment]
Thanks. Can you send a Pull Request?

**Comment by behdad** [comment]
Same is true for hb_blob_destroy and family.

**Comment by behdad** [comment]
Fixed. Thanks.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/harfbuzz/harfbuzz/commit/326db329f84793152838ff8c45d284f4766c0a7a "\[directwrite\] Simplify delete").
