### ISSUE TITLE
Issues in hb-ft.cc

### ISSUE THREAD

**Issue by matthiasclasen** [harfbuzz/harfbuzz#3984]
hb-ft.cc has these checks all over the place:

```
  if (font->destroy != (hb_destroy_func_t) _hb_ft_font_destroy)
    ...
```

But from what I can make out, _hb_ft_font_destroy is never used as font->destroy.

In gdb, I see the following for a font created via hb_ft_face_create_referenced+hb_font_create:

```
(gdb) print font->destroy
$1 = (hb_destroy_func_t) 0x7ffff7cbe232 <_hb_ot_font_destroy(void*)>
```

This is what the tests in https://github.com/harfbuzz/harfbuzz/pull/3696 fail.

Following the trail of _hb_ft_font_destroy, it seems to be passed as destroy in hb_blob_create.

It would probably be better to mark 'ft' fonts and faces more explicitly.

**Comment by khaledhosny** [comment]
This is set by `hb_ft_font_create()` or `hb_ft_font_set_funcs()`, but you are not using either in in #3696.

**Comment by matthiasclasen** [comment]
The documentation explicitly recommends to use hb_ft_font_create_referenced over hb_ft_font_create, and does not mention any side-effects of that choice on hb_ft_font_get_face.

**Comment by matthiasclasen** [comment]
The documentation of hb_ft_font_get_face should be explicit about the fact that it only works with fonts created in just the right way.

**Comment by khaledhosny** [comment]
`hb_ft_font_create_referenced()` also sets it. I think it is a documentation failure. If you are using `hb_font_create()`, then this is not an ft-based font and `hb_ft_font_get_face()` rightly can’t return an `FT_Face` from it.

**Comment by matthiasclasen** [comment]
I see.

hb_ft_face_create_* is really just convenience api to pull a blob out of an FT_Face. The docs could make that clearer.

**Comment by khaledhosny** [comment]
This applies to all `hb_ft_font_*()` functions, they only work on fonts created with `hb_ft_font_create*()`

**Comment by khaledhosny** [comment]
> I see.
> 
> hb_ft_face_create_* is really just convenience api to pull a blob out of an FT_Face. The docs could make that clearer.

Basically, yes.
