### ISSUE TITLE
[subset] Make it easier to keep evereything

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#3998]
Maybe add API on subset-input to keep everything. Basically this code:
https://github.com/harfbuzz/harfbuzz/blob/52110f13b02678c24daa3c1b588683a8fb13e125/src/hb-subset-input.cc#L485-L503

User can call this, then modify the input.

**Comment by behdad** [comment]
Would be a bit tricky to hook it up in hb-subset though, to let user override aspects after requesting to keep everything. Though maybe that works?

**Comment by behdad** [comment]
It works with hb-subset if one first adds `--keep-everything` then modifies glyphs / unicodes etc by subtracting from them for example.

**Comment by madig** [comment]
So if i keep_everything and then emty out the GID list, would it subset the font such that everything is kept, except glyphs that cannot be reached via cmap, composites or layout?

**Comment by yisibl** [comment]
@behdad For the `--keep-everything` option, the documentation does not specify its usage scenario.

If I just want to turn variable fonts into static fonts, should I use this option right?

**Comment by behdad** [comment]
> If I just want to turn variable fonts into static fonts, should I use this option right?

Sounds about right, yes.
