### ISSUE TITLE
7.0.0 release time?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4002]
Now that the dust on paint and cairo APIs has settled, should we make a release? cc @matthiasclasen

**Comment by behdad** [comment]
There's also has been a subsetter new API addition as well as massive CFF subsetter memory user reduction, specially when preprocessing.

**Comment by matthiasclasen** [comment]
Fine with me, I don't have any outstanding issues on hb-paint or hb-cairo.

**Comment by khaledhosny** [comment]
A few bots are failing on main, we need to fix this before cutting a new release.

**Comment by behdad** [comment]
> A few bots are failing on main, we need to fix this before cutting a new release.

Ah, thanks. Working on it.

**Comment by behdad** [comment]
Should be clean.

**Comment by khaledhosny** [comment]
So what is the final decision here, wait for FreeType release, wait for something else, or release now? (CI looks like it is going to be all green, so I might as well cut a release now before anything breaks again).

**Comment by behdad** [comment]
Yeah we need a FreeType release and then require it and disable COLRv1 in ft for older FT since they changed ABI.  Seems like might arrive any day now.

**Comment by behdad** [comment]
Or should we call it HB 7? :))

**Comment by khaledhosny** [comment]
Looks like a HarfBuzz 7 indeed (though a bit odd to release this right after HarfBuzz 6, but 🤷🏽).

**Comment by behdad** [comment]
Let's disable freetype color use and go for a release.

main also has significant memory use optimizations, in both subsetting and in shaping; Android is interested in the latter.

**Comment by behdad** [comment]
Let's wait till next week, hopefully there will be a cairo release. And we'll see about a freetype one.

**Comment by behdad** [comment]
> Let's disable freetype color use and go for a release.

I conditioned it on the upcoming freetype 13.
