### ISSUE TITLE
Subsetting with axis pinning should apply MVAR

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#4007]
Behdad says HB appears not to do so.

**Comment by madig** [comment]
There's a related issue of `head.macStyle` and `OS/2.fsSelection` needing their RIBBi bits set appropriately. I'd suppose one can determine which of RIBBi the output is going to be by following the `STAT` table's linkedValue. If the STAT does not exist, look at `wght` axis being pinned to 400 or 700 and either the `ital` or `slnt` axis pinned to 0/1 or 0/something.

**Comment by qxliu76** [comment]
oh yes, we will need to apply MVAR deltas. Thanks! I'll work on this.

**Comment by behdad** [comment]
PR in https://github.com/harfbuzz/harfbuzz/pull/4028
