### ISSUE TITLE
[ft-colr] Doesn't work with FreeType master

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4013]
In https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/370#note_1711939 Adrian mentioned that:

* One problem I found is FreeType has changed the FT_ColorStop stop_offset type from FT_F2Dot14 to FT_Fixed in FreeType master but this change is not yet in a release. I'm using FreeType master and this change broke gradients. So we can't merge this until FreeType does a new release.

Indeed, our renderer doesn't render anything with FreeType master either.

cc @matthiasclasen

**Comment by behdad** [comment]
Just dividing stop_offset by 65536. instead of 16384. doesn't seem to fix it either. Needs debugging :(.

**Comment by behdad** [comment]
Nevermind. I'm getting a crash. Debugging.

**Comment by behdad** [comment]
Okay, yeah, compiling against the new headers, and changing the division, makes it work. Very unfortunate :(.

**Comment by behdad** [comment]
@lemzwerg can we get a new release of FreeType? The ABI change has been sitting in master since July. We need to at least be able to version-check it.

**Comment by behdad** [comment]
Or just enable color code for next version of FreeType.

**Comment by lemzwerg** [comment]
Dominik already has submitted https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/234 – when this gets applied, I will do a release (as soon as my spare time permits).

**Comment by behdad** [comment]
Thank you Werner.

**Comment by khaledhosny** [comment]
I think this is addressed now.

**Comment by behdad** [comment]
And FreeType release seems to be coming.
