### ISSUE TITLE
Build fails with Oracle Developer Studio 12.6

### ISSUE THREAD

**Issue by hege-li** [harfbuzz/harfbuzz#4037]
Solaris 11.4 on SPARC
CC: Studio 12.6 Sun C++ 5.15 SunOS_sparc Patch 152715-10 2021/08/27

"hb-bit-page.hh", line 85: Error: Constexpr function's parameter type 'hb_bit_page_t' is not a literal type.

**Comment by behdad** [comment]
What version of HarfBuzz is this? The line number doesn't match.

**Comment by behdad** [comment]
Does this fix it? https://github.com/harfbuzz/harfbuzz/commit/92d5ec2f1618c3b899c74216f7f05ea85f815b8e

**Comment by hege-li** [comment]
Sorry forgot to mention it was from 6.0.0. The actual problem I first encountered compiling OpenJDK 11, which includes 4.4.1.

But the patch indeed fixes this specific problem, thanks for quick response.
