### ISSUE TITLE
font with potentially proprietary license included in harfbuzz

### ISSUE THREAD

**Issue by dilinger** [harfbuzz/harfbuzz#4059]
While updating copyright info for harfbuzz, I came across the following license in EXIF data.

```
dilinger@hm90:~/sid-build/harfbuzz$ exiftool  test/shape/data/in-house/fonts/641ca9d7808b01cafa9a666c13811c9b56eb9c52.ttf  | grep Copyright
Copyright (en-US)               : The digitally signed machine readable Typeface(Font) licensed to you is copyrighted ©, (2010), King Fahd Glorious Quran Printing Complex...ISBN: 978-603-8010-15-0, Accession No. 1430/7278..All rights reserved. This Font is the property of King Fahd Glorious Quran Printing Complex, and may not be reproduced, modified without the express written approval of King Fahd Glorious Quran Printing Complex.
```

This license looks extremely non-free, and if it's accurate (and not just an outdated EXIF field), the font  test/shape/data/in-house/fonts/641ca9d7808b01cafa9a666c13811c9b56eb9c52.ttf  should probably be removed from the tree.  If the license is different, it would be good to update the EXIF data or mention the file in the in-house directory's COPYING file.

**Comment by behdad** [comment]
Thanks. We probably should just remove that one. Sometimes these creep in.
@khaledhosny Do you happen to know which font that is?

**Comment by behdad** [comment]
Ah it's "KFGQPC Uthmanic Script HAFS".

**Comment by behdad** [comment]
It's a freeware font. Removing.
