### ISSUE TITLE
[meson] ../src/hb-gobject.h:33:10: fatal error: hb-gobject-enums.h: No such file or directory

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4060]
I made `hb-info` use `hb-gobject.h` and linux-ci build is failing error not finding `hb-gobject-enums.h`. Help needed.

https://github.com/harfbuzz/harfbuzz/actions/runs/3981660110/jobs/6825536422

**Comment by behdad** [comment]
meson file also needs to only add harfbuzz_gobject_dep to hb-info if building with gobject. Or maybe that's a non-issue?

**Comment by khaledhosny** [comment]
This is odd. It looks like it is trying to build hb-info before generating hb-gobject-enums.h, but I don’t understand why.

**Comment by khaledhosny** [comment]
See #4061 for a possible fix, it seems to be a dependency issue but that *fix* feels rather ugly and shouldn’t be required. Someone better at meson than me should know a proper fix.

**Comment by behdad** [comment]
Thanks.

**Comment by behdad** [comment]
Trying to configure meson without gobject now says:
```
util/meson.build:44:2: ERROR: Unknown variable "enum_h".
```

**Comment by matthiasclasen** [comment]
enum_h is only defined `if have_gobject`.  You will have to make the hb-info build conditional on that.

**Comment by matthiasclasen** [comment]
Fix attempt: https://github.com/harfbuzz/harfbuzz/pull/4063

**Comment by khaledhosny** [comment]
> Fix attempt: #4063

I opened #4064 before seeing this.
