### ISSUE TITLE
fonts with potentially proprietary license found

### ISSUE THREAD

**Issue by dilinger** [harfbuzz/harfbuzz#4062]
I think I found another two:

test/shape/data/text-rendering-tests/fonts/TestGVAREight.ttf
test/api/fonts/TestGVAREight.ttf

Copyright: 1992-2017, Thomas A. Rickner

```
dilinger@hm90:~/sid-build/harfbuzz2$ exiftool test/api/fonts/TestGVAREight.ttf | grep License
License Info URL (en-US)        : https://github.com/TrueTyper/BuffaloGals/blob/master/LICENSE.txt
```

That page says:

"2.	You are hereby granted a non-exclusive, non-assignable, non-transferable (except as expressly permitted herein) license to install the Font Software on a single Workstation solely for the purpose of evaluating such Font Software. You have no rights to the Font Software other than as expressly set forth in the Agreement. You agree that Rickner owns all right, title and interest in and to the Font Software, its structure, organization, code, and related files, including all property rights therein such as copyright, design and trademarks rights. You agree that the Font Software, its structure, organization, code, and related files are valuable property of Rickner and that any intentional Use of the Font Software not expressly permitted by the Agreement constitutes a theft of valuable property. All rights not expressly granted in the Agreement are expressly reserved to Rickner. 

3.	You may install and Use the Font Software on a single file server for Use on a single local area network (“LAN”) only when the Use of such Font Software is limited to single Workstation for which you have been granted a license. 
[...]

8.	You may not rent, lease, sublicense, give, lend, or further distribute the Font Software, or any copy thereof."

**Comment by behdad** [comment]
BuffaloGals was explicitly given permission for testing but font file was not updated. I'm happy to remove if you prefer.

**Comment by dilinger** [comment]
Was permission given to distribute under an MIT license, or OSF-1.1?  If that's the case, then it's probably fine to leave it and make a note somewhere.

**Comment by dilinger** [comment]
I hexedited the two fonts to change the LicenseInfoURL-en-US tag to point to https://github.com/harfbuzz/harfbuzz/blob/main/COPYING. If the permission is for the same license as the rest of harfbuzz, I can submit a PR. If it's not, let me know and I can modify the field to point to whatever license it falls under.

**Comment by behdad** [comment]
The fonts come from this repo:
https://github.com/unicode-org/text-rendering-tests

So better to point the license there.  You can also use ttx which is more convenient than a hex editor.  Thanks.
