### ISSUE TITLE
[hb-info] -t TABLE?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4078]
We alias eg:

- `-tname` to `--list-names`
- `-tcmap` to `--list-unicodes`
- `-tCPAL` to `--list-palettes`
- `-tBASE` to `--list-baselines`
- `-tGSUB` and `-tGPOS` to `--list-scripts` and `--list-features`
- `-tpost` to `--list-glyphs`
- `-tfvar` to `--list-variations`
- `-tMVAR` to `--list-metrics`
- `-tSTAT` to `--list-style`

etc.

**Comment by behdad** [comment]
Maybe too fragile and confusing.

**Comment by behdad** [comment]
@khaledhosny wdyt?

**Comment by matthiasclasen** [comment]
I have some idle curiosity about glyph classes.

I don't think I need those -t shorthands, personally. If you like them, go for it.

**Comment by khaledhosny** [comment]
I’d expect `-tXXXX` to dump the table, either binary or some form of text serialization.
