### ISSUE TITLE
OpenType features not applied for Khitan Small Script using kits script tag

### ISSUE THREAD

**Issue by babelstone** [harfbuzz/harfbuzz#4082]
My Khitan Small Script font [Khitan Small Rotated](https://www.babelstone.co.uk/Fonts/Download/KhitanSmallRotated.ttf) which has OpenType features under the DFLT script tag shows expected shaping behaviour:

![KSSTest_Dflt](https://user-images.githubusercontent.com/20558386/214907260-4d225f23-17d7-46ce-9896-852b754236ad.png)

However, a [modified version of the same font](https://www.babelstone.co.uk/Fonts/Download/KhitanSmallRotated_kits.ttf) with the OpenType features under the correct 'kits' script tag has no shaping behaviour:

![KSSTest_Kits](https://user-images.githubusercontent.com/20558386/214908278-5f373ad1-9ffa-44ee-bcfb-19504e2ac1b1.png)

Tested using harfbuzz-win64-6.0.0. Test file available [here](https://www.babelstone.co.uk/Fonts/KSSTest.txt).

**Comment by behdad** [comment]
What's the test string?

**Comment by babelstone** [comment]
Linked to above: "Test file available [here](https://www.babelstone.co.uk/Fonts/KSSTest.txt)".

**Comment by khaledhosny** [comment]
`Kits` goes through USE shaper which has different feature order and scope, so that might be the source of difference.

**Comment by behdad** [comment]
USE is applying ccmp. I think it's because the USE grammar is putting those each into their own syllable and ccmp is then applied within syllable.

**Comment by behdad** [comment]
IndicSyllabicCategories has no data for Khitan script.

**Comment by khaledhosny** [comment]
Yes, that is the scope difference part I was thinking about. USE applies some features per-cluster and `ccmp` seems to be one of these.

FWIW, DirectWrite is giving me the same output as HarfBuzz for both fonts.

**Comment by behdad** [comment]
Try applying the lookups in `rlig` feature.

**Comment by babelstone** [comment]
Thank you for the quick reply! Based on your above comments, I do not understand why ccmp does not work, but I changed ccmp to rlig as you suggested, and I now get the correct shaping behaviour in harfbuzz (and in Chrome and Edge), although unfortunately the fonts no longer work on desktop applications (Word, Notepad) under Windows 10, so I suppose I will have to provide two versions of the fonts for the time being.

**Comment by behdad** [comment]
> I do not understand why ccmp does not work

The Universal Shaping Engine breaks text into syllables. In the case of Khitan script, every character ends up in its own syllable. It then limits application of certain features, including `ccmp` to within syllable only.



> the fonts no longer work on desktop applications

That's unexpected. Maybe try `liga` feature?  But as Khaled said, the font you had was broken with DirectWrite as well. Or are you saying it was working in Word/Notepad?

**Comment by babelstone** [comment]
To clarify, the original font using DFLT/ccmp works as expected on Windows 10 in Word and Notepad, but not in harfbuzz. The new font using kits/rlig works in harbuzz, but does not work on Windows 10 in Word and Notepad.

**Comment by behdad** [comment]
> To clarify, the original font using DFLT/ccmp works as expected on Windows 10 in Word and Notepad, but not in harfbuzz.

Oh? But you wrote:

> My Khitan Small Script font [Khitan Small Rotated](https://www.babelstone.co.uk/Fonts/Download/KhitanSmallRotated.ttf) which has OpenType features under the DFLT script tag shows expected shaping behaviour.

My testing shows that it works.

**Comment by babelstone** [comment]
Sorry, I got confused! The DFLT/ccmp font works with harbuzz and on Windows 10 desktop. The kits/ccmp font does not work anywhere, and the kits/rlig font works with harfbuzz only. I hope I've got that right now!
