### ISSUE TITLE
[ci] Disable macos-ci?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4101]
It TIMEOUTs most of the time. Since we have a circleCI mac bot, should we disable the Github one for now?

**Comment by khaledhosny** [comment]
We want to eventually move off CircleCI, but if the GHA macos bot keeps to be problematic I guess we can mark it OK to fail instead of outright disabling it.

**Comment by behdad** [comment]
That works for me.

**Comment by khaledhosny** [comment]
Lets revisit when CI bot annoys us again.
