### ISSUE TITLE
Zero-width non-joiner and ligatures

### ISSUE THREAD

**Issue by blumens** [harfbuzz/harfbuzz#4104]
(Sorry, if this is not the right place for this.)

According to the unicode standard, inserting a ZWNJ should prevent the formation of ligatures. But harfbuzz seems to be ignoring it and creating a ligature anyway. (In case it matters, I'm using a latin script and tested with the fi ligature.) Is this as intended, or am I doing something wrong?

More generally, what is the best way to tell harfbuzz not to use a ligature at a specific location, but not to prevent kerning?

**Comment by behdad** [comment]
Using ZWNJ should indeed prevent ligatures but allow kerning with current HarfBuzz. What font are you using? With some fonts we cannot make this work because of how the font is constructed.

**Comment by blumens** [comment]
I've tried with Roboto (Google) and Skolar Sans PE (Rosetta, variable font). Perhaps I'm doing something wrong in my code?

**Comment by blumens** [comment]
Okay, I found it: it was a stupid mistake in my code (using the unicode for ZWJ instead of ZWNJ). Sorry for the noise.
