### ISSUE TITLE
Devanagari matra positioning issue in Nirmala UI font

### ISSUE THREAD

**Issue by jfkthame** [harfbuzz/harfbuzz#4124]
We've had a report of bad matra positioning with the Nirmala UI font (from Win10); originally filed as Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1817366, but the issue is at the harfbuzz shaping level.

Compare:
```
$ hb-shape --font-file ~/Nirmala.ttf --unicodes U+0928,U+094B,U+0915,U+0947
[gid267=0+1244|gid316=0+532|gid248=2+1768|gid312=2@-692,0+0]
```

with the result when anusvara (U+0902) is added to the first syllable:
```
$ hb-shape --font-file ~/Nirmala.ttf --unicodes U+0928,U+094B,U+0902,U+0915,U+0947
[gid267=0+1244|gid316=0+532|gid323=0@93,0+0|gid868=3@-120,0+45|gid248=3+1768|gid312=3+0]
```

The final e-matra (U+0947 -> gid312) no longer gets positioned nicely over the ka.

Notepad on Win10 does not show the same behavior: the matra positioning is unaffected by a preceding anusvara.

**Comment by jfkthame** [comment]
It looks like it's 'abvm' lookup 13 that is expected to do the mark positioning here.

Without U+0902 in the text:
```
trace: start lookup 13 feature 'abvm'	buffer: [gid267=0+1244|gid316=0+532|gid248=2+1768|gid312=2+0]
trace: attaching mark glyph at 3 to glyph at 2	buffer: [gid267=0+1244|gid316=0+532|gid248=2+1768|gid312=2+0]
trace: attached mark glyph at 3 to glyph at 2	buffer: [gid267=0+1244|gid316=0+532|gid248=2+1768|gid312=2@1076,0+0]
trace: end lookup 13 feature 'abvm'	buffer: [gid267=0+1244|gid316=0+532|gid248=2+1768|gid312=2@1076,0+0]
```
Here, the final U+0947 (gid312) is successfully attached.

But with U+0902 inserted:
```
trace: start lookup 13 feature 'abvm'	buffer: [gid267=0+1244|gid316=0+532|gid323=0+0|gid868=3@-120,0+45|gid248=3+1768|gid312=3+0]
trace: attaching mark glyph at 2 to glyph at 1	buffer: [gid267=0+1244|gid316=0+532|gid323=0+0|gid868=3@-120,0+45|gid248=3+1768|gid312=3+0]
trace: attached mark glyph at 2 to glyph at 1	buffer: [gid267=0+1244|gid316=0+532|gid323=0@625,0+0|gid868=3@-120,0+45|gid248=3+1768|gid312=3+0]
trace: end lookup 13 feature 'abvm'	buffer: [gid267=0+1244|gid316=0+532|gid323=0@625,0+0|gid868=3@-120,0+45|gid248=3+1768|gid312=3+0]
```
The lookup successfully attaches U+0902 (gid323) to the preceding glyph, but then does not handle the final U+0947 (gid312).

**Comment by behdad** [comment]
This is what's happening: When anusvara is present, the Ka does a multiple substitute to gid868=3@-120,0+45|gid248=3+1768. Our attachment logic goes out of its way to attach to first of a multiple attachment. That was done because of other shapers it seems.

**Comment by behdad** [comment]
> That was done because of other shapers it seems.

Specifically, for Arabic IIRC.

**Comment by jfkthame** [comment]
Hmm. That's... unfortunate, as apparently the Windows shaper handles this (based on behavior in Notepad).
Possible way forward: if there's no attachment to the first glyph of the multiple, should we try the next (etc)?

**Comment by behdad** [comment]
> Hmm. That's... unfortunate, as apparently the Windows shaper handles this (based on behavior in Notepad).
> Possible way forward: if there's no attachment to the first glyph of the multiple, should we try the next (etc)?

Maybe if we see a multiple, I try all components until a match is found...  That should take care of it.  So, like you suggest but going from last to first.

**Comment by behdad** [comment]
The logic in the code becomes very convoluted, specially given the code changes I made for avoiding O(n^2) behavior :(.

**Comment by RiteshSingh** [comment]
Thank you @behdad and @jfkthame 🙏🏼🙏🏼
