### ISSUE TITLE
High CPU usage with harfbuzz 7.0

### ISSUE THREAD

**Issue by chrs8** [harfbuzz/harfbuzz#4139]
After upgrading harfbuzz from 6.0 to 7.0 I observe high CPU usage when scrolling inside neovim in kitty terminal (see kovidgoyal/kitty#6030)

Investigating with `perf top` reveals:

```
Overhead  Shared Object                   Symbol
  56,65%  libfreetype.so.6.19.0           [.] TT_RunIns
```
These calls don't occur with harfbuzz 6.0

**Comment by behdad** [comment]
Humm. We didn't make any changes in how we interact with freetype.

**Comment by chrs8** [comment]
Any hints where I could investigate further?

**Comment by behdad** [comment]
Does the upgrading to HB7 also upgrade FreeType by any chance?

**Comment by chrs8** [comment]
I'm on Archlinux and this issue came with the update of harfbuzz, freetype was upgraded a couple of days earlier. 
Current config:
Freetype2 2.13.0
Harfbuzz 7.0.1
-> the issue as described

If I downgrade Harfbuzz to 6.0.0 with everything else unchanged
-> no problem

**Comment by behdad** [comment]
Okay I did change some. My bad I think. Let me get to the bottom of this.

**Comment by behdad** [comment]
Fixed it I think. Any chance you can test?

**Comment by chrs8** [comment]
tbh, as I haven't done this before, I'd rather not mess with compiling and installing such a "low level" package myself. I will report back when the next release has made it to the arch repo.

Thank you for the fast response.

**Comment by chrs8** [comment]
Ok, I decided to take the risk and tested it. 

The problem is fixed!
