### ISSUE TITLE
7.1.0

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4140]
We should probably make a release for https://github.com/harfbuzz/harfbuzz/issues/4139

**Comment by behdad** [comment]
Ah yes.  Let me do that. Thanks.

**Comment by behdad** [comment]
So we'll have MSVC bots failing for a while until we also address https://github.com/harfbuzz/harfbuzz/issues/4137

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/issues/2293?

**Comment by behdad** [comment]
> #2293?

Yeah. But I don't think it's relevant given that the MSVC2019 is failing only on x86 here.

**Comment by behdad** [comment]
Seems to be green now. And given new justify experimental API, maybe 7.1

**Comment by khaledhosny** [comment]
Cutting it now.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/7.1.0
