### ISSUE TITLE
msan sanitize error in latest code

### ISSUE THREAD

**Issue by qxliu76** [harfbuzz/harfbuzz#4142]
![image](https://user-images.githubusercontent.com/48925186/221955001-1b6fdd57-9012-4559-a721-b5492af0c745.png)

**Comment by qxliu76** [comment]
according to the reporter, this `idx` is suspicious, since it has no default / constructor initializers, and it's only set to any value here, in a 'reset' function: https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-ot-layout-gsubgpos.hh#L519

**Comment by behdad** [comment]
Yeah I think I know what's going on. Will take a look. Thanks.

**Comment by behdad** [comment]
I pushed a fix. Please test. Thanks.

**Comment by qxliu76** [comment]
I tested and the issue is gone. Thank you!
