### ISSUE TITLE
CFF2 instancing: does not instantiate advance widths?

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#4149]
Follow-up to https://github.com/harfbuzz/harfbuzz/issues/4125.

Same font, but e.g. the instance of wght=400 and wght=800 have the same advance width, as if the `hmtx` table isn't being variated.

**Comment by anthrotype** [comment]
FWIW the fonttools instancer also [doesn't apply advance deltas from HVAR/VVAR, but from gvar phantom points](https://github.com/fonttools/fonttools/blob/e26da961ecbe6463f5a2a151a1588fea4a1e2cb6/Lib/fontTools/varLib/instancer/__init__.py#L640) (and in fact it's currently truetype only). The fontTools.varLib.mutator does support (full) CFF2 instancing and [applies deltas from H/VVAR](https://github.com/fonttools/fonttools/blob/e26da961ecbe6463f5a2a151a1588fea4a1e2cb6/Lib/fontTools/varLib/mutator.py#L112).

**Comment by qxliu76** [comment]
Thanks @anthrotype ! I'll work on this

**Comment by behdad** [comment]
> @behdad , it seems to update hmtx, we also need to extract bounds info from each glyph's CFF2 charstrings. Do you know if there's any existing function that does this already? If not, where I should add this code?

Sigh... There's code for it for sure. hb-ot-font's get_extents does that.

**Comment by qxliu76** [comment]
Thank you!
