### ISSUE TITLE
hb-shape and hb-view disagree. hb-shape is correct but hb-view is off.

### ISSUE THREAD

**Issue by jungshik** [harfbuzz/harfbuzz#416]
With the following font and [u1113.txt](https://github.com/googlei18n/noto-cjk/files/764919/u1113.txt)
, 
[NotoSansCJKkr-Regular.otf.zip](https://github.com/googlei18n/noto-cjk/files/763793/NotoSansCJKkr-Regular.otf.zip)

hb-shpae (default funt-funcs=ft  version: 09594df1) gives the following output. The vertical positions are as expected. 

<U+1113,U+1167,U+0020,U+1113,U+1167,U+11A8,U+0020,U+1113,U+1167,U+11A9,
U+0020,U+1113,U+1167,U+11AA,U+0020>
[{"g":"gid64051","cl":0,"dx":-460,"dy":-894,"ax":0,"ay":-1000,"xb":85,"yb":741,"w":458,"h":-581},
{"g":"gid64509","cl":0,"dx":0,"dy":106,"ax":0,"ay":0,"xb":-330,"yb":838,"w":210,"h":-914},
{"g":"gid1","cl":2,"dx":-112,"dy":-880,"ax":0,"ay":-1000,"xb":0,"yb":0,"w":0,"h":0},
{"g":"gid63676","cl":3,"dx":-460,"dy":-894,"ax":0,"ay":-1000,"xb":64,"yb":780,"w":468,"h":-402},
{"g":"gid64414","cl":3,"dx":0,"dy":106,"ax":0,"ay":0,"xb":-322,"yb":837,"w":185,"h":-518},
{"g":"gid64734","cl":3,"dx":0,"dy":106,"ax":0,"ay":0,"xb":-709,"yb":260,"w":574,"h":-323},
{"g":"gid1","cl":6,"dx":-112,"dy":-880,"ax":0,"ay":-1000,"xb":0,"yb":0,"w":0,"h":0},
{"g":"gid63676","cl":7,"dx":-460,"dy":-894,"ax":0,"ay":-1000,"xb":64,"yb":780,"w":468,"h":-402},
{"g":"gid64414","cl":7,"dx":0,"dy":106,"ax":0,"ay":0,"xb":-322,"yb":837,"w":185,"h":-518},
{"g":"gid64735","cl":7,"dx":0,"dy":106,"ax":0,"ay":0,"xb":-745,"yb":260,"w":609,"h":-322},
{"g":"gid1","cl":10,"dx":-112,"dy":-880,"ax":0,"ay":-1000,"xb":0,"yb":0,"w":0,"h":0},
{"g":"gid63676","cl":11,"dx":-460,"dy":-894,"ax":0,"ay":-1000,"xb":64,"yb":780,"w":468,"h":-402},
{"g":"gid64414","cl":11,"dx":0,"dy":106,"ax":0,"ay":0,"xb":-322,"yb":837,"w":185,"h":-518},
{"g":"gid64736","cl":11,"dx":0,"dy":106,"ax":0,"ay":0,"xb":-746,"yb":265,"w":649,"h":-331},
{"g":"gid1","cl":14,"dx":-112,"dy":-880,"ax":0,"ay":-1000,"xb":0,"yb":0,"w":0,"h":0}]
<>
[]

The hb-view output does not agree with hb-shape output. 

![u1113_ttb_notosans_ken](https://cloud.githubusercontent.com/assets/8578343/22804918/1308ea70-eed0-11e6-9e4d-1915ef94f69f.png)

When the same string (modulo spaces) is rendered in Chrome 56 (Harfbuzz 1.3.1),  I got 

![image](https://cloud.githubusercontent.com/assets/8578343/22804092/61370d02-eecc-11e6-88c0-f363e3dfb6cb.png)

which agrees with hb-shape output.

**Comment by behdad** [comment]
This need debugging... I'm not convinced hb-view is wrong.  What do you get with `--font-funcs=ot`?

**Comment by behdad** [comment]
I get correct output in hb-view now.
