### ISSUE TITLE
Vertical Japanese text

### ISSUE THREAD

**Issue by muratmat** [harfbuzz/harfbuzz#4160]
[MPLUS1p-Regular.zip](https://github.com/harfbuzz/harfbuzz/files/10943165/MPLUS1p-Regular.zip)

Hello, I'm having shaping problems with Harfbuzz version 6+ (even 7) when using vertical Japanese text. Here's the code:
```c
// kerning operations
static const hb_tag_t KernTag = HB_TAG('k', 'e', 'r', 'n');
// standard ligature substitution
static const hb_tag_t LigaTag = HB_TAG('l', 'i', 'g', 'a');
// contextual ligature substitution
static const hb_tag_t CligTag = HB_TAG('c', 'l', 'i', 'g');
// shaping features
static const hb_feature_t defaultShapingFeatures[] = {
    { KernTag, 1, 0, MAX_UINT32 },  // kerning ON
    { LigaTag, 1, 0, MAX_UINT32 },  // standard ligature substitution ON
    { CligTag, 1, 0, MAX_UINT32 }   // contextual ligature substitution ON
};

// create font (from Freetype face)
hb_font_t* hbFont = hb_ft_font_create(ftFace, NULL);

// create buffer
hb_buffer_t* hbBuffer = hb_buffer_create();
hb_buffer_reset(hbBuffer);
hb_buffer_set_direction(hbBuffer, HB_DIRECTION_TTB);

// fill buffer (utf8Text contains the japanese text 日本)
unsigned char utf8Text[6] = { 230, 151, 165, 230, 156, 172 };
hb_buffer_add_utf8(hbBuffer, utf8Text, 6, 0, 6);
hb_buffer_guess_segment_properties(hbBuffer);

// perform shaping
hb_shape(hbFont, hbBuffer, defaultShapingFeatures, sizeof(defaultShapingFeatures) / sizeof(hb_feature_t));

// get shaping result
hb_glyph_info_t* glyphInfo = hb_buffer_get_glyph_infos(hbBuffer, &glyphsCount);
hb_glyph_position_t* glyphPos = hb_buffer_get_glyph_positions(hbBuffer, &glyphsCount);
```

With Harfbuzz 5.3.1 (or previous), I get the following result (which lead to correct rendering):
```
glyphPos[0].x_offset = -32768
glyphPos[0].y_offset = -56361
glyphPos[0].x_advance = 0
glyphPos[0].y_advance = -65536
glyphPos[1].x_offset = -32768
glyphPos[1].y_offset = -56361
glyphPos[1].x_advance = 0
glyphPos[1].y_advance = -65536
```
With Harfbuzz 6.0.0 and all 7.x.y versions, I get the following result (which lead to wrong rendering):
```
glyphPos[0].x_offset = -32768
glyphPos[0].y_offset = -70451
glyphPos[0].x_advance = 0
glyphPos[0].y_advance = 65536
glyphPos[1].x_offset = -32768
glyphPos[1].y_offset = -70451
glyphPos[1].x_advance = 0
glyphPos[1].y_advance = 65536
```
Any idea on how to get correct numbers using Harfbuff 7+? I attach the used font.
Many thanks in advance!

**Comment by behdad** [comment]
I can't reproduce this with `hb-shape --font-funcs=ft --direction t --font-features=liga,kern,clig` but I'm probably doing something wrong. I'll try more. Can you try that as well?

**Comment by behdad** [comment]
Alternatively can you attach the full C code so I can compile?

**Comment by muratmat** [comment]
I will try to write a single main.c file, so you can compile and trace it. Just for your information, I compile Harfbuzz with HB_LEAN, HB_OPTIMIZE_SIZE, __OPTIMIZE_SIZE__, NDEBUG, HAVE_FREETYPE, HAVE_PTHREAD

**Comment by muratmat** [comment]
[test_hb.zip](https://github.com/harfbuzz/harfbuzz/files/10992177/test_hb.zip)

Hello, I was able to reproduce the bug with a standalone C file. I've also included a minimal script to compile Freetype and Harfbuzz in the way I use them. So here are the full instructions on how to reproduce the bug.

- Unzip the attached file in an empty directory
- Build the libraries for Linux x86_64: `bash ./build_cmake.sh` (the first time it will download Freetype and Harfbuzz from their public repositories, then it will run CMake)
- Build the test with: `gcc -I./freetype/include -I./harfbuzz/src -o test_hb test_hb.c -L./lib/linux/x86_64 -lfreetype -lharfbuzz -lm`
- Run the test and see (bugged) output: `./test_hb`
- Change Harfbuzz version to 5.3.1:
    - `cd ./harfbuzz`
    - `git checkout 970321db7bddbe8c579b73751fc655a924ea3ce6`
    - `cd ..`
- Build the libraries again: `bash ./build_cmake.sh`
- Build the test again: `gcc -I./freetype/include -I./harfbuzz/src -o test_hb test_hb.c -L./lib/linux/x86_64 -lfreetype -lharfbuzz -lm`
- Run the test again and see correct output

Many thanks for your support.

**Comment by behdad** [comment]
Thanks. Using your build instruction I get:
```
CMake Error at CMake/src_common.cmake:142 (target_sources):
  Cannot specify sources for target "harfbuzz," which is not built by this
  project.
Call Stack (most recent call first):
  CMakeLists.txt:32 (include)
```

I built your test file against HB main and cannot reproduce the buggy output again :(.

**Comment by behdad** [comment]
I also tried with the `HB_TINY` profile.

**Comment by muratmat** [comment]
[test_hb_v2.zip](https://github.com/harfbuzz/harfbuzz/files/10995434/test_hb_v2.zip)

Sorry, there was an unwanted comma. Please find the new package in the attachment.
From your comments, it seems that the bug is due on how FT and HB libraries are built (i.e. static).

Let me know if updated script are now ok. Thanks!

**Comment by behdad** [comment]
I can indeed reproduce the broken rendering using your test scripts.

**Comment by behdad** [comment]
Ah, this is because `HB_LEAN` has `HB_NO_VERTICAL` in it.

**Comment by behdad** [comment]
> Ah, this is because `HB_LEAN` has `HB_NO_VERTICAL` in it.

No. Not quite.

**Comment by behdad** [comment]
> > Ah, this is because `HB_LEAN` has `HB_NO_VERTICAL` in it.
> 
> No. Not quite.

Yeah, I believe that's the culprit. You can create a override config file to undef `HB_NO_VERTICAL` and define `HB_CONFIG_OVERRIDE` to point to it to fix the problem.
