### ISSUE TITLE
M_PI is a Posix extension.

### ISSUE THREAD

**Issue by bungeman** [harfbuzz/harfbuzz#4166]
While attempting to roll HarfBuzz in Skia the MSVC builds failed due to the use of `M_PI`. From a `git log -S M_PI` it appears that use of `M_PI` began with 39c20d2b9eb476065e64d3a3cccc6345aa50e4c1 in 2021, but this wasn't noticed because Skia doesn't build `hb-style.cc`. This is now noticed after 575d99406a5e40eab04b9d6c5c3a970b674b1753 when `M_PI` began being used for the COLRv1 transformations. `M_PI` is [required by Posix](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/math.h.html) but is not required by C. With Microsoft's C headers one [must define `_USE_MATH_DEFINES` before including `math.h` or before the first inclusion of `cmath`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/math-constants). It appears `hb.hh` does set this define before including `cmath`, but if something else includes `cmath` first then this doesn't work. In the Skia roll when `_USE_MATH_DEFINES` is set on the compiler command line, then everything builds. So there must be something pulling in `cmath` before `hb.hh` is (haven't determined what is doing that yet).

It appears the issue is that [Microsoft's `cmath`](https://github.com/microsoft/STL/blob/daa994bfc41c36196c536f2b68388f859d6bd656/stl/inc/cmath) does not allow any re-inclusion to change anything (it is `pragma once`), but their `math.h` does (couldn't find a good link for it, but looking at it locally, it does). If `hb.hh` included `math.h` then this would work, with `cmath` it does not (indeed, Microsoft's C++ STL will surprise a lot of users who expect the `c` versions of headers to defer to the `.h` versions, because for the most part they do not).

In any event, this can be worked around, but due to the fragility it seems like it might be easier for HarfBuzz to just provide its own constant for pi (or [tau](https://en.wikipedia.org/wiki/Turn_(angle)#Tau_proposals)).

**Comment by behdad** [comment]
Thanks for the detailed report. I'll fix this [tomorrow](https://www.piday.org/)
