### ISSUE TITLE
Occasionally, there is a problem of overlapping Chinese characters ?

### ISSUE THREAD

**Issue by LukiYLS** [harfbuzz/harfbuzz#4171]
The problem is as stated in the screenshot

<img width="381" alt="image" src="https://user-images.githubusercontent.com/15795917/225264590-486f532b-04f4-4bf2-9276-c3b35e3de085.png">

Debug found that because Harfbuzz this is the x_advance returned after shaping is 0

```
 for (unsigned i = 0; i < len; i++) {
    ShapedGlyph& glyph = run.glyphs[i];
    glyph.id = info[i].codepoint;
    glyph.cluster = info[i].cluster;
    glyph.offset.x = pos[i].x_offset * ScalarFromHBPosX;
    glyph.offset.y = pos[i].y_offset * ScalarFromHBPosY;
    glyph.advance.x = pos[i].x_advance * ScalarFromHBPosX;
    glyph.advance.y = pos[i].y_advance * ScalarFromHBPosY;

    glyph.has_visual = !glyphBounds[i].IsEmpty();  //! font->currentTypeface()->glyphBoundsAreZero(glyph.fID);
#if HB_VERSION_CHECK(1, 5, 0)
    glyph.unsafe_to_break = info[i].mask & HB_GLYPH_FLAG_UNSAFE_TO_BREAK;
#else
    glyph.unsafe_to_break = false;
#endif
    glyph.must_linebreak_before = false;
    runAdvance += glyph.advance;
  }
```
The script and language parameters are set like this

```
hb_buffer_set_script(buffer, HB_SCRIPT_HAN);
hb_buffer_set_language(buffer, hb_language_from_string("zh-CN", -1));
```

The font used is PingFang FC

Platform is Macos

**Comment by behdad** [comment]
Can you reproduce the problem with the `hb-shape` tool?

**Comment by LukiYLS** [comment]
> Can you reproduce the problem with the `hb-shape` tool?

I can't recurrent use hb-shape tool, because it's occasionally
What the possible reasons for this problem?

**Comment by behdad** [comment]
> What the possible reasons for this problem?

Quite possibly outside of HarfBuzz.
