### ISSUE TITLE
support for 'hang' BASE OpenType feature

### ISSUE THREAD

**Issue by eroux** [harfbuzz/harfbuzz#418]
Please support the [BASE](https://www.microsoft.com/typography/otspec/baselinetags.htm) OpenType feature. I've gathered all information I was able to find on [a dedicated Github repo](https://github.com/eroux/otf-base-hang). There's a font with a hang BASE table in the [LO bug report](https://bugs.documentfoundation.org/show_bug.cgi?id=104930). Apparently recent MS Word support it, OSX apps don't, but they support the [AAT bsln](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6bsln.html) table, which is more or less equivalent.

**Comment by brawer** [comment]
@eroux, would you be interested in implementing BASE in HarfBuzz? Personally I’d love doing it but I’m not sure if I’ll have the time in the coming weeks, so if you do it, it might be faster.

**Comment by eroux** [comment]
Thanks for your answer! Well, I have 0 knowledge of the harfbuzz code base, but if you think the difficulty is reasonably low, I can give it a try... maybe you could give me a few short hints on the way to do that and I can work on it next week-end? On the other hand, this crucial feature is missing for around 10 years, so I guess it missing a few more weeks is no big deal...

**Comment by eroux** [comment]
I've started to work in [a branch](https://github.com/eroux/harfbuzz/tree/add-base), I think I'm starting to understand what needs to be done

**Comment by behdad** [comment]
Great start! Please rename file to hb-ot-layout-base-table.hh

**Comment by eroux** [comment]
I'll do that, thanks for the hind and the support!

**Comment by KrasnayaPloshchad** [comment]
With this implementation we can also improve CJK support.

**Comment by eroux** [comment]
@KrasnayaPloshchad indeed, but what I understand is that Harfbuzz will just expose the BASE table, then each application must implement their use of it, there's nothing that Harfbuzz can do automatically (at least I don't think so)... or is there something I didn't understand?

**Comment by KrasnayaPloshchad** [comment]
I just found the specification also includes some instructions for using this table when for CJK layout, so I think this implementation would helpful to improve CJK support, especially for vertical CJK layout.

**Comment by eroux** [comment]
Yes, there are some hints, but, from what I understand, it's nothing Harfbuzz can implement simply... suppose for instance you have like in the example:

```
TimeNewRoman@20pt: By
MSMincho@20pt: [some Kanji]
TimesNewRomain@12pt: By
MSMincho@12pt: [some Kanji]
```

you make 4 harfbuzz shape calls... but what kind of arguments are you passing to it? My idea is (simplified):

#### Step 1
The application sees that there are parts with different base lines and sizes. It scratches its head and finds that it wants the `ideo` baseline always at, say `-0.5mm` from the `romn` baseline. Note that the value of `-0.5mm` depends on the size of the biggest font using the `ideo` baseline. If you used the `MSMincho` at 12pt only, maybe this value would be smaller. Harfbuzz cannot compute it, so even the very simple example of the doc needs some code in the applications to work.

##### Step 2
Two possibilities:

- in a first time, the application can read the `BASE` table from Harfbuzz and decide how to move the glyphs vertically
- in the future it could call `hb_shape()` with an option asking harfbuzz to align the `ideo` baseline at `-0.5mm`

I'm currently implementing the first possibility as it's quite obvious and necessary, for the second possibility I think designing the API is a much bigger job and I'm not sure I'm qualified for that... What I described above works with very simple cases, but the BASE table also has much more advanced possibilities so just passing one argument is not enough...

**Comment by kojiishi** [comment]
I think it's application/caller's responsibility to determine the so-called "dominant baseline", or "dominant run" in the [OpenType terminology](https://www.microsoft.com/typography/otspec/base.htm).

CSS has the [`dominant-baseline`](https://www.w3.org/TR/css-inline-3/#dominant-baseline-property) property, so when this is supported, browser engine is supposed to pass this property to HarfBuzz. For other apps, it's up to them how to determine it, but from HarfBuzz perspective, it should be given.

I don't have strong option on whether HarfBuzz automatically aligns glyphs using given dominant/font baselines, or just expose tables for apps to align them.

**Comment by eroux** [comment]
That's a good point... I'm still quite puzzled on how this works in real life, I'd like to write the algorithm somewhere in order for all applications to have a model. @kojiishi do you have a good understanding on how things should be implemented? If so can you contact me in a private email (my address is on my Github profile)?

On a side note, the dominant-baseline property doesn't even appear on caniuse.com, but it's possible to [vote for its appearance](https://github.com/Fyrd/caniuse/issues/1413)

**Comment by KrasnayaPloshchad** [comment]
I suggest we can try to handle the BASE table firstly, then we try to synthesize the baseline in the next version.

**Comment by eroux** [comment]
That's my plan yes, but I think we need to add some API functions to pass some infos of a `BASE` table to the application, like what happens with the `MATH` table

**Comment by kojiishi** [comment]
Sorry for late reply, I agree, APIs to read BASE table would be the most useful first step.

I have a basic idea, but I haven't coded using the OpenType `BASE` table yet, so I'm hoping to learn by playing with some real fonts.

**Comment by KrasnayaPloshchad** [comment]
Then we can discuss how to create these APIs?

**Comment by eroux** [comment]
Sure, I have a [working branch](https://github.com/eroux/harfbuzz/tree/add-base) with code to load and access all fields and just a simple 

```
hb_ot_base_has_data(hb_face_t *hb_face)
```

public api function (doing the same as its `math` equivalent). I've set up a [repository](https://github.com/eroux/harfbuzz-base-demo) to make a demo on how to use it. I won't have time to advance this week-end, but I'm more  than happy to discuss som API ideas. I think a public discussion would be best, maybe not here... where do you think would be an appropriate place? Maybe an issue on either of the repos?

**Comment by KrasnayaPloshchad** [comment]
@kojiishi You can try these fonts:

A modified Noto Sans Tibetan with `hang` baseline tag
https://bugs.documentfoundation.org/attachment.cgi?id=131129
Several CJK fonts can be found here, I think many of them includes this table
https://en.wikipedia.org/wiki/List_of_CJK_fonts

**Comment by eroux** [comment]
@KrasnayaPloshchad can you give a specific example of a CJK font with a base table in the Wikipedia list?

**Comment by kojiishi** [comment]
> can you give a specific example of a CJK font with a base table in the Wikipedia list?

Adobe source-han-sans/Google Noto CJK has one. The source of feature table is [here](https://github.com/adobe-fonts/source-han-sans/blob/master/Regular/features.JP).

**Comment by KrasnayaPloshchad** [comment]
W3C documentation Indic Layout Requirements also has an example of using hanging baseline at section 3.3.3.
https://w3c.github.io/ilreq/#h_indic_scripts_with_hanging_baseline

**Comment by kojiishi** [comment]
Happen to find today that canvas has these values defined
https://github.com/whatwg/html/issues/2470

**Comment by KrasnayaPloshchad** [comment]
> I suggest we can try to handle the BASE table firstly, then we try to synthesize the baseline in the next version for dominant purpose.

We can also just expose the whole table data to let the client process.

**Comment by KrasnayaPloshchad** [comment]
@eroux Is it possible to create a pull request for this?

**Comment by eroux** [comment]
I'm not sure what your question means, but the work I've done in [my branch](https://github.com/eroux/harfbuzz/tree/add-base) is not finished: it just parses the table, which is around 30% of the job I would say... and I've lost my momentum so no idea when I'll get back to this. If @behdad  thinks merging this is a good idea (which I doubt) I can make a pull request, but otherwise I'm affraid someone else will have to step up and continue where I stopped.

**Comment by KrasnayaPloshchad** [comment]
@eroux I understand, thanks. Don’t worry, feel free to submit a PR here.

**Comment by behdad** [comment]
Yep. Thanks. I'll get to the API part at some point.

**Comment by KrasnayaPloshchad** [comment]
This API could be fully compatible with CSS dominant-baseline or alignment-baseline values, also, hb-shape/hb-view need to add some corresponding parameters.

**Comment by KrasnayaPloshchad** [comment]
SVG has two attribute for this: alignment-baseline and dominant-baseline. If this API could be compatible with them any font would get proper alignments if the font includes BASE table.
See: 
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline

**Comment by ebraminio** [comment]
Will look into what can happen and what is common ground between BASE and AAT's bsln (which I found hard) and DirectWrite and CoreText APIs for them, if not someone does that before me. Feel free to discuss about should happen here and giving hints. Thanks

**Comment by ebraminio** [comment]
Lets discuss about the API #1345

**Comment by ebraminio** [comment]
Very initial patch: #1347

**Comment by eroux** [comment]
thanks a lot! @ebraminio @behdad do you happen to know if there's any software (open source or not) that uses base line so I could guess how they do it?

**Comment by ebraminio** [comment]
Thank you! This is the equivalent API in DirectWrite https://docs.microsoft.com/en-us/windows/win32/api/dwrite_1/nf-dwrite_1-idwritetextanalyzer1-getbaseline (which ours turned a bit differently and cleaner) one of the uses here https://github.com/search?q=dwrite+GetBaseline&type=Code should be real use I'd assume but most are header definition. If you could find from there feel free to share it with us also.

**Comment by eroux** [comment]
Excellent, thanks a lot!
