### ISSUE TITLE
[hb-subset] Drop unused name IDs

### ISSUE THREAD

**Issue by madig** [harfbuzz/harfbuzz#4183]
Instancing a location from a VF will leave in a bunch of now unused name IDs. They should probably be dropped to save some bytes.

**Comment by madig** [comment]
This may also include nameID 25, which AFAIU is only needed for variable fonts.

**Comment by qxliu76** [comment]
Can I get a testcase for this? It seems all retained name IDs are collected during name_id closure, it'd be helpful to have a testcase so I can debug into this issue.

**Comment by madig** [comment]
Ok, I take that back. I was using the uharfbuzz bindings; using hb-subset correctly drops unused name IDs. Need to look into how I get the bindings to do the same.
