### ISSUE TITLE
Problem with undefined reference `FT_Palette_Select'

### ISSUE THREAD

**Issue by Jamaika1** [harfbuzz/harfbuzz#4186]
```
c:/gcc1131/bin/../lib/gcc/x86_64-w64-mingw32/11.3.1/../../../../x86_64-w64-mingw32/bin/ld.exe: lib\harfbuzz_x64.a(harfbuzz.o):harfbuzz.cc:(.text+0x43fca): undefined reference to `FT_Palette_Select'
collect2.exe: error: ld returned 1 exit status
```
I use
https://github.com/harfbuzz/harfbuzz/commit/453ded05392af38bba9f89587edce465e86ffa6b
https://github.com/freetype/freetype/commit/4d8db130ea4342317581bab65fc96365ce806b77
http://msystem.waw.pl/x265/mingw-gcc1131-20221227.7z

**Comment by khaledhosny** [comment]
That looks like a mis-configuration issue.
