### ISSUE TITLE
Support --no-layout-closure

### ISSUE THREAD

**Issue by rsheeter** [harfbuzz/harfbuzz#4192]
A Google-style icon font has ligatures (e.g. "alarm") and PUA for each icon. See https://fonts.google.com/icons.

Sometimes you want to subset them, and you'd like to retain ligature and pua. However, if we use text= we over-retain, for example "alarm_off" will retain "alarm."

In FontTools we can resolve this by identifying what glyph ids we want then using `--gids= --no-layout-closure`. hb-subset has no `--no-layout-closure`, could we have it please?

**Comment by behdad** [comment]
I believe our subsetting code can handle this, we just need to add the option and skip layout closure in the subsetter calls.
