### ISSUE TITLE
Doc: clarify purpose of FreeType integration

### ISSUE THREAD

**Issue by jeanas** [harfbuzz/harfbuzz#4200]
First of all, thank you for your work on HarfBuzz!

On https://harfbuzz.github.io/integration-freetype.html, it is explained that you can use `hb_ft_font_set_funcs` to make a HarfBuzz font use the set of functions provided by FreeType rather than HarfBuzz's built-in set of functions.

What I miss in this documentation, though, is an explanation of *why* this might be useful. What do the FreeType functions bring over HarfBuzz's implementation? Do they support more font formats? Do they do better rasterization? Are they faster? Something else?

(CC @lemzwerg)

Related to #2524, I'm also not sure I understand what FreeType itself uses HarfBuzz for.

**Comment by lemzwerg** [comment]
A partial answer: FreeType uses HarfBuzz to find glyphs affected by a given OpenType feature for improved auto-hinting.  While just a very small part of HarfBuzz, it is extremely helpful.

The problem with the 'circular dependency' is only an annoyance for packagers but not a serious problem at all: You first have to build FreeType (which automatically recognizes that HarfBuzz is not available and correctly disables the affected code), then HarfBuzz (which needs FreeType for font rendering), then FreeType again, which now uses HarfBuzz.

**Comment by behdad** [comment]
Thanks. I'll try to update the documentation.

> What I miss in this documentation, though, is an explanation of _why_ this might be useful. What do the FreeType functions bring over HarfBuzz's implementation? Do they support more font formats? Do they do better rasterization? Are they faster? Something else?

It's mostly to help clients who already use FreeType for rasterization or font loading. If a client does *not* use FreeType, we do not recommend using hb-ft. It's true that using hb-ft allows for supporting more font formats, since FreeType supports formats (like Type1) that HarfBuzz does not natively support.
