### ISSUE TITLE
compile_points_with_deltas

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4201]
@qxliu76 Do you remember why for components you get the delta and add it in compile_points_with_deltas, instead of getting the shifted component points to begin with?

**Comment by qxliu76** [comment]
I don't remember now. I just checked and found you're right, we can just use the output of get_points(). Maybe at that time I was not so familiar with get_points(). I'll try to make some code changes for this.

**Comment by behdad** [comment]
Thanks.

**Comment by qxliu76** [comment]
I changed code but It seems not working as expected, I'll take a detailed look next week.

**Comment by behdad** [comment]
Thanks. Can you submit a WIP PR? I can take a look.

**Comment by qxliu76** [comment]
Sure, here's the PR: https://github.com/harfbuzz/harfbuzz/pull/4202
I guess maybe I missed some details

**Comment by behdad** [comment]
Fixed.
