### ISSUE TITLE
Release 7.1.1?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4208]
There was a syllabic bug introduced around 5.0.0 that I just fixed. Worth a release.

**Comment by behdad** [comment]
> Awaiting resolution of [#4207 (comment)](https://github.com/harfbuzz/harfbuzz/pull/4207#issuecomment-1523802806)
> since that's a backcompat issue.

Fixed.

**Comment by khaledhosny** [comment]
Shouldn’t it be 7.2.0 since we have two new public symbols: `HB_SUBSET_FLAGS_NO_LAYOUT_CLOSURE` and `HB_UNICODE_COMBINING_CLASS_CCC132`?

**Comment by behdad** [comment]
Works for me.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/7.2.0
