### ISSUE TITLE
Harfbuzz Not Correctly Linking Static Dependencies?

### ISSUE THREAD

**Issue by barndawgie** [harfbuzz/harfbuzz#4213]
I'm trying to build a static FFMPEG build and having issues with Harfbuzz, which I seem to have narrowed down to its use of pkg-config.

If I run:
`./autogen.sh --host=x86_64-w64-mingw32 --build=x86_64-linux-gnu --enable-static --disable-shared`
My subsequent `make` will fail:
```
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(decode.c.obj):decode.c:(.text+0x4c83): undefined reference to `BrotliTransformDictionaryWord'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(decode.c.obj):decode.c:(.text+0x3ff2): undefined reference to `BrotliTransformDictionaryWord'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(decode.c.obj):decode.c:(.text+0x558a): undefined reference to `BrotliSharedDictionaryAttach'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(decode.c.obj):decode.c:(.rdata$.refptr._kBrotliPrefixCodeRanges[.refptr._kBrotliPrefixCodeRanges]+0x0): undefined reference to `_kBrotliPrefixCodeRanges'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(decode.c.obj):decode.c:(.rdata$.refptr._kBrotliContextLookupTable[.refptr._kBrotliContextLookupTable]+0x0): undefined reference to `_kBrotliContextLookupTable'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(state.c.obj):state.c:(.text+0x116): undefined reference to `BrotliSharedDictionaryCreateInstance'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(state.c.obj):state.c:(.text+0x153): undefined reference to `BrotliDefaultFreeFunc'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(state.c.obj):state.c:(.text+0x15a): undefined reference to `BrotliDefaultAllocFunc'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(state.c.obj):state.c:(.text+0x2fe): undefined reference to `BrotliSharedDictionaryDestroyInstance'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(state.c.obj):state.c:(.rdata$.refptr.BrotliDefaultAllocFunc[.refptr.BrotliDefaultAllocFunc]+0x0): undefined reference to `BrotliDefaultAllocFunc'
/usr/bin/x86_64-w64-mingw32-ld: libbrotlidec.a(state.c.obj):state.c:(.rdata$.refptr.BrotliDefaultFreeFunc[.refptr.BrotliDefaultFreeFunc]+0x0): undefined reference to `BrotliDefaultFreeFunc'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:2118: test.exe] Error 1
make[4]: Leaving directory 'harfbuzz/src'
make[3]: *** [Makefile:3625: all-recursive] Error 1
make[3]: Leaving directory 'harfbuzz/src'
make[2]: *** [Makefile:1942: all] Error 2
make[2]: Leaving directory 'harfbuzz/src'
make[1]: *** [Makefile:517: all-recursive] Error 1
make[1]: Leaving directory 'harfbuzz'
make: *** [Makefile:449: all] Error 2
```

If I instead run:
`FREETYPE_LIBS="$(pkg-config --libs --static freetype2)" ./autogen.sh $configure_params`
My `make` succeeds. I suspect that Harfbuzz is not setting the `--static` flag on its call to pkg-config despite the `--enable-static` flag being passed at configuration time.

**Comment by behdad** [comment]
We just call `PKG_CHECK_MODULES`. Does the FreeType `pkg-config` file list Brotli?

**Comment by behdad** [comment]
Sorry for my stupid question. I see that it does because you're calling pkg-config also. I thought for a second that you were calling freetype-config manually.

**Comment by behdad** [comment]
When I make just with `--enable-static --disable-shared` on Linux build succeeds.

**Comment by behdad** [comment]
> `./autogen.sh --host=x86_64-w64-mingw32 --build=x86_64-linux-gnu --enable-static --disable-shared`

I tried this on Fedora, with mingw64 fedora-static package, and it succeeds as well.

**Comment by barndawgie** [comment]
Hmmm...brotli is breaking other packages too, so perhaps I'm wrong to blame Harfbuzz? I found this strange though since I assumed `FREETYPE_LIBS="$(pkg-config --libs --static freetype2)" ` should effectively be a no-op as that would be the default behavior under the hood.

**Comment by khaledhosny** [comment]
Does not seem like a HarfBuzz issue.
