### ISSUE TITLE
[config] Sort out `HB_OPTIMIZE_SIZE`

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4220]
Currently it's automatically defined if `__OPTIMIZE_SIZE__` is defined, which is the case when one compiling with `-Os` or `-Oz`. When this option (`HB_OPTIMIZE_SIZE`) is defined, currently we disable several caches as well as fast-paths. That's not ideal IMO. We should separate two options:

- True `__OPTIMIZE_SIZE__`, for things like smaller UCD table. Maybe disabling fast-path in gvar that has minimal impact,
- Something like `HB_OPTIMIZE_SIZE_MORE` or something that is enabled by `HB_TINY` and disables caches and other fast-paths that have significant slowdown for certain workloads.

**Comment by behdad** [comment]
cc @drott @jfkthame

**Comment by behdad** [comment]
> * True `__OPTIMIZE_SIZE__`, for things like smaller UCD table. Maybe disabling fast-path in gvar that has minimal impact,

Even this I'm unsure about. Should we never change any code behavior based on `__OPTIMIZE_SIZE__`?

**Comment by jfkthame** [comment]
One possible approach: use `__OPTIMIZE_SIZE__` to control things that primarily affect the compiled size of the binary (e.g., using a more compact but slower-to-access format for static data), and then have an additional `HB_MINIMIZE_MEMORY_USAGE` or something for the cases that are primarily about runtime footprint (e.g. caches). It's true that disabling caches may *also* reduce compiled code size, but ISTM the main focus there would be on the (runtime) size of the cache itself rather than the (static) size of the associated code.

**Comment by drott** [comment]
👆 Yes, I agree with @jfkthame's direction. Perhaps a tricky trade-off. I'd find it surprising if `__OPTIMIZE_SIZE__` changes logic or performance behavior to an extent that it sidesteps / disables caches. I would read this feature/define more as something that reduces binary footprint and really more controlled by the compiler, without attaching big functional changes to it. Things like leaving out UCD data, or removing redundant/optimized code paths should be a separate flag, yes. That makes it less surprising. `TINY` can then list them, which in a way documents the options as well.

**Comment by behdad** [comment]
Thank you both. Fortunately we don't allocate many caches. Let's work out everything. I'll leave the `HB_OPTIMIZE_SIZE` flag as is, and adjust it's uses only. I don't think it's wrong in many places, only one perhaps.

- UCD / USE tables: `HB_OPTIMIZE_SIZE` is adequate. We can use a smaller static table for slightly slower access cost.

- A `gvar` delta-application loop I (perhaps unnecessarily) hyper-optimized by copying four times for four different cases to avoid a conditional and a multiplication in the loop if possible. I think this is also a valid candidate for `HB_OPTIMIZE_SIZE`: https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-ot-var-gvar-table.hh#L353-L416

- hb-vector has a loop instead of calling memset. That's also fine.

- Ligature algorithm: I recently implemented a faster ligature-set matching algorithm. It sped up Roboto shaping by 25%. It has no memory implications, it's just more code. I'm leaning towards just adding an option and disabling it in `HB_TINY`: https://github.com/harfbuzz/harfbuzz/blob/3194963657a3049961fb64c9be86c1629afcea4b/src/OT/Layout/GSUB/LigatureSet.hh#L86

- GDEF cache: (`HB_NO_GDEF_CACHE`) This is a 512byte-per-face cache that sped up Roboto by 5%. I can disable it with `HB_TINY` as well as the proposed `HB_MINIMIZE_MEMORY_USAGE`.

- Lookup cache: (`HB_NO_OT_LAYOUT_LOOKUP_CACHE`) This one only saves 8 bytes per subtables. I can still disable it with `HB_MINIMIZE_MEMORY_USAGE` which will also get disabled in `HB_TINY`.

- `hb-ot-font` uses a 1kb-per-font advance-width if variations are set, as well as a transient varStore cache during `get_glyph_h_advances` function. I'll disable these in `HB_MINIMIZE_MEMORY_USAGE`. Though, if variations are set and font doesn't have `HVAR`, this would make the font *really* expensive to shape.

- `hb-ot-font` uses a 1kb-per-face cmap-cache. I'll disable it in `HB_MINIMIZE_MEMORY_USAGE`.

- `hb-ft` uses an advance-width cache. I'm not going to disable that since FreeType glyph loading is really slow and people will complain if not cached.

I think that's all.

**Comment by behdad** [comment]
> * Lookup cache: (`HB_NO_OT_LAYOUT_LOOKUP_CACHE`) This one only saves 8 bytes per subtables. I can still disable it with `HB_MINIMIZE_MEMORY_USAGE` which will also get disabled in `HB_TINY`.
> *

Added `HB_OPTIMIZE_SIZE_MORE` for this, and `HB_MINIMIZE_MEMORY_USAGE` as discussed.
