### ISSUE TITLE
New release to fix gcc warning

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4226]
7.2.0 causes gcc to warn spuriously:
```
In file included from ../src/OT/glyf/Glyph.hh:10,
                 from ../src/OT/glyf/glyf.hh:13,
                 from ../src/hb-ot-glyf-table.hh:33,
                 from ../src/hb-static.cc:37:
../src/OT/glyf/VarCompositeGlyph.hh: In member function ‘bool OT::glyf_impl::VarCompositeGlyphRecord::get_points(OT::contour_point_vector_t&) const’:
../src/OT/glyf/VarCompositeGlyph.hh:173:8: warning: offset ‘4’ outside bounds of constant string [-Warray-bounds]
  173 |   bool get_points (contour_point_vector_t &points) const
      |        ^~~~~~~~~~
../src/hb-static.cc:45:16: note: ‘_hb_NullPool’ declared here
   45 | uint64_t const _hb_NullPool[(HB_NULL_POOL_SIZE + sizeof (uint64_t) - 1) / sizeof (uint64_t)] = {};
      |                ^~~~~~~~~~~~
```

Some clients are sensitive to warnings. Maybe we can make a release now that it has gone away by itself.

**Comment by behdad** [comment]
Some changes:
* Over 40% gvar speed optimization with VarComposites fonts.
* Over 20% speedup instancing RobotoFlex.
* Over 30% speedup in shaping Roboto!
* VarComposites subsetting support
* beyond-64k subsetting support
* Add `HB_MINIMIZE_MEMORY_USAGE`

**Comment by khaledhosny** [comment]
Do you want to merge any of #4222, #4228, or #4229 first?

**Comment by behdad** [comment]
> Do you want to merge any of #4222, #4228, or #4229 first?

No, let's do without. Thanks.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/7.3.0
