### ISSUE TITLE
[hashmap] Long probe chain observed

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4227]
The hashmap implementation currently is showing long probe chains. We're observing up to 60 when running the subset command below:
```
util/hb-subset test/subset/data/fonts/NotoNastaliqUrdu-Regular.ttf --gids=0-1400 -o out.ttf
```

Upon investigation with @garretrieger, we believe there are two separate issues at play:

* The `std::hash()` implementation for integers is identity!!!!!!  This clearly causes `sqrt(n)` chains when eg. we have `hb_map_t` of `glyphmap` where all integers are added in a large range. The reason for the `sqrt(n)` is the quadratic probe algorithm.

* The `hb_bytes_t` hash has two issues itself:
  - The default `hb_array_t` hash function seems not to be very good. I upgraded it to FNV-a1, but still is not the best.
  - The optimized path for `hb_bytes_t` to process four-bytes at a time seems to make the problem worse.

So we recommend two remedies:
* A custom hash for integers that simply multiplies by a large prime,
* A much better `hb_bytes_t` hash function, like https://github.com/ztanml/fast-hash/blob/master/fasthash.c

The latter needs to be carefully profiled for performance though.

**Comment by garretrieger** [comment]
I tested using fast hash and found it to significantly reduce the length of chains, from >60 to 16 max.
