### ISSUE TITLE
[subset] Possibly use vector instead of map for a few items

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4231]
These: `bounds_width_map`, `bounds_height_map`, `hmtx_map`, `vmtx_map`.

**Comment by behdad** [comment]
Not sure if feasible. The main problem is retain-gid.

**Comment by behdad** [comment]
I'm working on it.

**Comment by qxliu76** [comment]
Oh sorry, just saw this. My understanding is we need to empty the glyphs that are not retained. During instancing, we call get_points() on empty glyphs to get phantom points so we can calculate adv width etc. I wonder if we need to do that for all emptied glyphs or just on one glyph and set the same metric for all emptied glyphs?

**Comment by behdad** [comment]
@qxliu76 
Thanks. I did the bounds maps in https://github.com/harfbuzz/harfbuzz/pull/4232
One test is failing though. Can you take a look?

**Comment by qxliu76** [comment]
sure, I'll take a look

**Comment by behdad** [comment]
Half of it is done. The other half maybe not worth it.
