### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4236]
Now that wasm is merged, should we make a release? What to call it? 8?

**Comment by behdad** [comment]
cc @simoncozens

**Comment by khaledhosny** [comment]
May be reserve the major version increase for when WASM shaper is stable? I also had some build issue when WASM is enable, I don’t remember the details but I’ll try to dig it up.

**Comment by behdad** [comment]
> May be reserve the major version increase for when WASM shaper is stable? I also had some build issue when WASM is enable, I don’t remember the details but I’ll try to dig it up.

Probably because iwasm needs to be built with certain flags. Sure, needs documentation, more streamlining, API review, etc. No rush.

**Comment by behdad** [comment]
> May be reserve the major version increase for when WASM shaper is stable?

It will be experimental for quite some time though.

**Comment by khaledhosny** [comment]
> > May be reserve the major version increase for when WASM shaper is stable?
> 
> It will be experimental for quite some time though.

I don’t mind cutting a release now, but a major version bump seems a little too much if the main feature is experimental and off by default. Not a big deal though.

**Comment by behdad** [comment]
Not rushing it. Let's get some more testing. I'm fine with a minor version.

**Comment by simoncozens** [comment]
> Probably because iwasm needs to be built with certain flags.

I'm not sure if that's true; it does for the wasm-modules stuff, but we don't really use that. I think I just built it with the JIT flag for speed and it was fine. (At least on Darwin.)

I added some build docs to the `wasm-shaper.md` file.

**Comment by behdad** [comment]
We require `-DWAMR_BUILD_REF_TYPES=1`.

**Comment by simoncozens** [comment]
So we do. I'll add that.

**Comment by behdad** [comment]
Probably time for a 7.4 release for all the subsetter optimization work at least.

**Comment by behdad** [comment]
- Support instancing cubic-glyf table.
- Up to 85% speedup in small subsets of CJK fonts (both TTF & OTF) with preprocessed-face.

**Comment by khaledhosny** [comment]
I was hoping to get #4269 in, since a major release is a good time to make such a change.

**Comment by behdad** [comment]
> I was hoping to get #4269 in, since a major release is a good time to make such a change.

Okay, let me get there.

**Comment by behdad** [comment]
> > I was hoping to get #4269 in, since a major release is a good time to make such a change.
> 
> Okay, let me get there.

I'm still undecided on that. Can we make a release, since over 600 commit have accumulated?

**Comment by behdad** [comment]
- beyond-64k subsetting.
- VarComposites subsetting.
- Cubic-glyf instancing.
- Optimization work:
  - Up to 89% speedup loading variable fonts for shaping.
  - Up to 88% speedup in small subsets of large (eg. CJK) fonts (both TTF & OTF), essential for Incremental Font Transfer (IFT).
  - Over 50% speedup in loading Roboto for shaping.
  - Up to 40% speed up in loading (sanitizing) complex fonts.
  - Over 25% speedup in glyph loading Roboto.
  - 10% speed up loading glyph shapes in VarComposite Hangul font.
  - hb-hashmap optimizations & hashing improvements.

**Comment by simoncozens** [comment]
JFDI. We can always do another one when #4269 lands, we don't have a shortage of version numbers.

**Comment by behdad** [comment]
Is it 7.4.0 or 8?

**Comment by khaledhosny** [comment]
Lets go for 8 then.
