### ISSUE TITLE
get StyleSet names if available

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [harfbuzz/harfbuzz#425]
Scribus uses HarfBuzz to get font features, but right now harfbuzz gives only the tags. This is enough for almost font features expect Stylistic Set 1 - Stylistic Set 20. In [one of scribus bugs](https://bugs.scribus.net/view.php?id=14621), a user requests a feature to display StyleSet names if available instead of just displaying ss01, ss02, ss03, …, ss20. 

Is this possible with current api?

**Comment by behdad** [comment]
> Is this possible with current api?

No. I'll add API for it soon.

**Comment by adrientetar** [comment]
Character variants (cvXX) also has names.

**Comment by ebraminio** [comment]
As its revert #1121

**Comment by ebraminio** [comment]
Fixed on #1239 finally
