### ISSUE TITLE
Determine if font has `subs` or `sups` with public HB API? Consider exposing API?

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#4265]
Context: https://groups.google.com/a/chromium.org/g/blink-dev/c/wQ_8T-AXLFA/m/IbL4wlAMBAAJ 
The I2S for `font-variant-position` in which the question is raised how likely synthesis for superscript and subscript through `font-variant-position` is needed. It's concluded that we tend to consider it a site-bug if `font-variant-position` is used with a font that doesn't have the feature. However, it would be useful to measure the occurrence of that issue (feature applied a font without support). 

So, I am a considering if we can measure with reasonable effort whether `subs` or `sups` is applied to a font that does not have such a feature. 

1. Based on a `hb_face_t` can I determine that with HB API without writing additional own parsing?
2. If not, could HarfBuzz ("temporarily" is an option) expose such an API to scan through GSUB for that (with script specified)?

This would help us measure whether `font-variant-position` or `font-feature-settings` with `sups` or `subs` is used successfully / correctly.

**Comment by jfkthame** [comment]
What Gecko does to determine whether a given (GSUB, but obviously extensible to GPOS) feature is supported in a font is something like this (slightly cleaned-up for clarity here):
```
    bool result = false;

    if (hb_ot_layout_has_substitution(face)) {
      // Get the OpenType tag(s) that match this script code
      unsigned int scriptCount = 4;
      hb_tag_t scriptTags[4];
      hb_ot_tags_from_script_and_language(script, HB_LANGUAGE_INVALID,
                                          &scriptCount, scriptTags, nullptr,
                                          nullptr);

      // Append DEFAULT to the returned tags, if room
      if (scriptCount < 4) {
        scriptTags[scriptCount++] = HB_OT_TAG_DEFAULT_SCRIPT;
      }

      // Now check for aFeatureTag under the first of those scripts that is present
      const hb_tag_t kGSUB = HB_TAG('G', 'S', 'U', 'B');
      result = std::any_of(scriptTags, scriptTags + scriptCount,
                           [&](const hb_tag_t& scriptTag) {
                             unsigned int scriptIndex;
                             return hb_ot_layout_table_find_script(
                                        face, kGSUB, scriptTag, &scriptIndex) &&
                                    hb_ot_layout_language_find_feature(
                                        face, kGSUB, scriptIndex,
                                        HB_OT_LAYOUT_DEFAULT_LANGUAGE_INDEX,
                                        aFeatureTag, nullptr);
                           });
    }
```
In theory this is incomplete, as it just checks the default langSys, so it would miss a feature that is present *only* under some specific langSys. But that hasn't ever been an issue in practice, as far as I'm aware.

**Comment by drott** [comment]
Thank you, Jonathan, that looks like what I was looking for, thanks for the snippet. I'll close this issue as it seems it's possible with existing API.

**Comment by behdad** [comment]
> 4

Use `HB_OT_MAX_TAGS_PER_SCRIPT + 1` here.
