### ISSUE TITLE
hb_swap doesn't work in copy constructor of a custom struct

### ISSUE THREAD

**Issue by qxliu76** [harfbuzz/harfbuzz#4268]
I have a simple unit test that would fail if I use hb_swap() in the copy constructor. Struct definition is below:

```
struct custom_struct
{
  hb_map_t m;
  hb_vector_t<unsigned> v;

  custom_struct () = default;
  custom_struct (const custom_struct& o) : custom_struct ()
  { copy (o); }
  
  custom_struct (custom_struct&& o) : custom_struct ()
  {
    //m = std::move (o.m);
    //v = std::move (o.v);
    hb_swap (*this, o);
  }
  
  custom_struct& operator = (const custom_struct& o)
  { copy (o); return *this; }

  custom_struct& operator = (custom_struct&& o)
  {
    hb_swap (*this, o);
    return *this;
  }

  void copy (const custom_struct& o)
  {
    m = o.m;
    v = o.v;
  }
};
```
And below test would crash during struct destruction:
```
static void
test_custom_struct ()
{
  hb_vector_t<custom_struct> t;

  hb_map_t m1;
  m1.set (1, 2);

  custom_struct c;
  c.m = std::move (m1);
  c.v.resize (2);
  c.v[0] = 1;
  c.v[1] = 2;

  t.push (std::move (c));
}
```
If hb_swap() is replaced by 2 std::move(), then the run is fine. I wonder if this is a bug in hb_map?
For convenience, I pushed test code onto this branch: https://github.com/googlefonts/harfbuzz/tree/hb_swap

**Comment by behdad** [comment]
> custom_struct (custom_struct&& o) : custom_struct ()
>   {
>     //m = std::move (o.m);
>     //v = std::move (o.v);
>     hb_swap (*this, o);
>   }

This is because `hb_swap` itself tries come like this:
```
  custom_struct tmp = a;
  a = b;
  b = std::move (tmp);
```
which calls the move constructor again. So you're getting infinite recursion.

You need to implement custom swap for `custom_struct`:
```
  friend void swap (custom_struct& a, custom_struct& b) 
  {
    hb_swap (a.m, b.m);
    hb_swap (a.v, b.v);
  }
```

**Comment by qxliu76** [comment]
Got it, thank you very much!
