### ISSUE TITLE
Rendering inconsistencies in Sinhala text for different fonts with same HarfBuzz version

### ISSUE THREAD

**Issue by sid-wr** [harfbuzz/harfbuzz#4286]
Hi,

For same input Sinhala text & same HarfBuzz version, there are inconsistencies for different fonts.

I tried **hb-view** for the input text
```-u "U+0DCFU+0020U+0D95U+0DCFU+0DCFU+0020U+0DD2U+0020U+0D95U+0DD2U+0DD2U+0020U+0DCAU+0020U+0D95U+0DCAU+0DCAU+0D95U+0020U+0D83U+0020U+0D95U+0D83U+0D83U+0020U+0D85U+0DDCU+0020U+0D95U+0D83U+0D82U+0020U+0D95U+0D82U+0D83U+0020U+0D82U+0020U+0D95U+0D82U+0D82"```

for 

- **NotoSansSinhala** latest version
- the widely used **UN-Malithi-4** font designed by the popular Sinhala font designer **Pushpananda Ekanayaka** (This font is available on https://github.com/JakeLoganUK/Sinhala-Unicode-Fonts)

---------------------------------------------------------------------------------------------------------------------
![file4](https://github.com/harfbuzz/harfbuzz/assets/136314541/65d74990-ff89-4a5c-90d6-a2bd7c484395)
---------------------------------------------------------------------------------------------------------------------

For example, the dotted circles are rendered for one font, but not for other. The matras are sometimes correctly applied & sometimes not.

---------------------------------------------------------------------------------------------------------------------
![file5](https://github.com/harfbuzz/harfbuzz/assets/136314541/61f3486c-6a56-413b-b5aa-13c4d514a042)
---------------------------------------------------------------------------------------------------------------------
This is happening with multiple fonts, as explained in [my earlier comment on another issue](https://github.com/harfbuzz/harfbuzz/issues/4276#issuecomment-1594888912)

Thanks

**Comment by behdad** [comment]
It looks like the dottedcircle glyph in UN-Malithi-4 has no ink.

**Comment by khaledhosny** [comment]
> It looks like the dottedcircle glyph in UN-Malithi-4 has no ink.

Yes, it is doesn’t. It has an advance width but no outlines.
