### ISSUE TITLE
[subset] instancer-solver crossing calculation fix

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4289]
This commit:
https://github.com/fonttools/fonttools/pull/3179/commits/023ad3a3639547ee1781d81bf38dbd25f75c3386

from this larger PR, that I'll file a separate issue for:
https://github.com/fonttools/fonttools/pull/3179

**Comment by behdad** [comment]
I pushed the fix, but not the tests.

**Comment by behdad** [comment]
@qxliu76 Can you add the tests please?

**Comment by qxliu76** [comment]
sure, I'll work on it.
