### ISSUE TITLE
[Feature request] Add Pango build for Windows

### ISSUE THREAD

**Issue by afalkenhahn** [harfbuzz/harfbuzz#4293]
I appreciate that there's an archive that contains Win32/Win64 builds of HarfBuzz along with all dependencies. May I suggest that you also add a Win32/Win64 build of Pango to that archive? I think that would make life easier for lots of people and it looks like all of Pango's dependencies are already in that archive so it probably wouldn't be too much work to add Pango itself as well.

**Comment by behdad** [comment]
While it seems out of scope for us, I see the convenience of having that. I'm not sure how easy or hard it would be with Pango's meson build system. If someone wants to volunteer, we'll definitely consider it.

**Comment by afalkenhahn** [comment]
Who builds those Win32/Win64 binaries of HarfBuzz that are available for download? I think it would be quite trivial to add a Pango build because AFAICS HarfBuzz uses the meson build system as well so Pango could probably be built out of the box on the machine that's currently used for building HarfBuzz and all its dependencies...

**Comment by behdad** [comment]
@khaledhosny would know, but I *think* they are built automatically when a release is made, by the github CI.



> AFAICS HarfBuzz uses the meson build system as well

For the windows builds I think we are still using the autotools build system:

  https://github.com/harfbuzz/harfbuzz/blob/main/mingw-configure.sh

We are cross-compiling using mingw32. So if you can figure out the magic to make Pango do the same, we can ship it.

**Comment by khaledhosny** [comment]
We build automatically with every CI build, but publish on GitHub only when cutting releases.

Building on CI machines is PITA and I’m not super thrilled to add more things to build, in fact we try very hard to build as less dependencies as possible to avoid random breakages that are bound to happen the more code we build.

I think it should be possible for someone to make a GitHub repository that specifically builds Pango binary and publishes them, or take the issue to Python repository that I think already do Windows builds on CI and can possibly make these binaries available somehow.

**Comment by behdad** [comment]
Maybe this:
https://github.com/wingtk/gvsbuild

**Comment by afalkenhahn** [comment]
> Maybe this: https://github.com/wingtk/gvsbuild

Yes, that looks promising for building it myself without too much hassle but of course it's not of much use for end users. For end users it would be very convenient if I could just point them to somewhere where they can download Pango binaries for Windows and since the HarfBuzz archive that is provided for download seems to contain all Pango dependencies already I think it would make very much sense to add Pango to it as well. It's like the last piece in the puzzle missing in that archive IMHO.

**Comment by vtorri** [comment]
you can look at what i wrote for the dependencies of Enlightenment : https://github.com/vtorri/ewpi I think that you can tweak it easily I think to build what ever package you want, with its dependencies. There is also an NSIS file that you can also modify if you want an NSIS installer for harfbuzz and its dependencies
