### ISSUE TITLE
Add the OpenSSF Scorecard Action

### ISSUE THREAD

**Issue by pnacht** [harfbuzz/harfbuzz#4296]
I'm back (see #4191, #4194 and #4273) with another security suggestion!

I managed to detect all of these possible improvements by using the [OpenSSF Scorecard](https://github.com/ossf/scorecard). It's a tool that runs a sort of "meta-analysis" of the repo's security-posture and gives actionable suggestions on how to improve.

The tool is also available as a [workflow Action](https://github.com/ossf/scorecard-action) that scans the repo after every commit to make sure there aren't any hiccups. Anything it detects gets sent to the project's [Security Panel](https://github.com/harfbuzz/harfbuzz/security) for easy access and management.

Spoiler alert: harfbuzz currently gets a 7.1/10, which puts it in the top 10% of relevant projects!

**Comment by behdad** [comment]
Sounds good to me. :D
