### ISSUE TITLE
Some possible Arabic rendering issues

### ISSUE THREAD

**Issue by sid-wr** [harfbuzz/harfbuzz#4302]
Hi,

I tried rendering the following input text via **hb-view** for different fonts:

```-u "U+0644U+064AU+0651U+0646U+064CU+0020U+0644U+064AU+0651U+064CU+0646U+0020U+0644U+064AU+0646U+0651U+064CU+0020U+0644U+064CU+0633U+064EU+0020U+0644U+0651U+064CU+0633U+0651U+064E"```

This gives almost correct output as:

![Arabic rendering issues](https://github.com/harfbuzz/harfbuzz/assets/136314541/980bf8e5-ddf0-49b6-9e60-02f7fe9a0571)

However there seem to be some issues:

1) Instead of the separate **Shadda (U+0651)** & **Dammatan (U+064C)** glyphs in the first word (from right to left), there should be **Shadda with Dammatan** ligature, similar to the second, third & fifth words.
Currently it is displaying that required ligature in the first word for only **GeezaPro** & **Arabic Transparent** fonts.

2) For some fonts like **DecoTypeNaskh**, the glyph for ligature **Shadda with Dammatan** is overlapping with glyph for **Arabic Lam**

3) For all the fonts, the ligature **Shadda with Dammatan** is not getting generated in the middle (it is on right hand side for second word & left hand side for third word). 

Can you please look at it?
Thanks

Please let me know if I need to log separate bugs for these

**Comment by behdad** [comment]
Can you test NotoSansArabic and NotoNaskhArabic as well?

My gut feeling is that these are all font bugs / limitations.

**Comment by sid-wr** [comment]
The issues no. 1) & 3) seem to be there for both of these Noto Arabic fonts as well.
Please find below the screenshots

![WithNotoArabicFonts](https://github.com/harfbuzz/harfbuzz/assets/136314541/43a9b588-e277-483e-aa4a-faaf70c585ca)

**Comment by behdad** [comment]
> 1. Instead of the separate **Shadda (U+0651)** & **Dammatan (U+064C)** glyphs in the first word (from right to left), there should be **Shadda with Dammatan** ligature, similar to the second, third & fifth words.
>    Currently it is displaying that required ligature in the first word for only **GeezaPro** & **Arabic Transparent** fonts.

Why is that? The sequence is "LAM + YEH + ARABIC SHADDA + NOON + ARABIC DAMMATAN". Why should the two marks ligate?!!

> 3\. For all the fonts, the ligature **Shadda with Dammatan** is not getting generated in the middle (it is on right hand side for second word & left hand side for third word).

I don't understand. Is this about the positioning of the glyph? Looks fine to me. And again, that's up to the font.

cc @khaledhosny

**Comment by khaledhosny** [comment]
I don’t see a bug here, except for the two fonts that form a mark ligature in the first word (Geeza Pro and Arabic Transparent), but these look like font bugs. May be the OP could tell us why they are expecting a mark ligature here s certainly there shouldn’t be one.
