### ISSUE TITLE
Graphite returns incorrect advance widths for Annapurna SIL font

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#4309]
Testing with https://software.sil.org/downloads/r/annapurna/AnnapurnaSIL-1.204.zip, in the following sequence, the last glyph has a very small advance width when using `graphite2` shaper (which is the default since the font has Graphite tables):

```
$ hb-shape AnnapurnaSIL-Regular.ttf -u 0930,094D,0935,093E,0923
[uni0935=0+1886|uni093E=0@-555,0+0|uni0930094D.reph=0@-46,0+0|uni0923=4+36]
```
![graphite2](https://github.com/harfbuzz/harfbuzz/assets/93914/b786703d-2962-42d7-8c44-c51fca5afd1a)

With `ot` shaper it has a more sensible advance:
```
$ hb-shape AnnapurnaSIL-Regular.ttf -u 0930,094D,0935,093E,0923 --shaper=ot
[uni0935=0+1331|uni093E=0+555|uni0930094D.reph=0+2|uni0923=4+1367]
```
![ot](https://github.com/harfbuzz/harfbuzz/assets/93914/20cf561d-747a-464b-a1dd-95bdfdb37ddf)

I’m not sure if it is a font, Graphite, or HarfBuzz bug, though.

**Comment by khaledhosny** [comment]
It seems to be a bug in the `graphite2` shaper, namely in the code that maps Graphite advances to HarfBuzz one. I don’t know Graphite 2 to API to grok that code, though.

cc @mhosken

**Comment by khaledhosny** [comment]
Another similar issue with [Linux Libertine G](http://www.numbertext.org/linux/e7a384790b13c29113e22e596ade9687-LinLibertineG-20120116.zip) font. When a tt ligature is followed by space the positioning becomes odd:
```
$ hb-shape LinLibertine_R_G.ttf "tt"
[t_t=0+1257]
$ hb-shape LinLibertine_R_G.ttf "tt "
[t_t=0+1769|space=0@-512,0+0]
```

**Comment by khaledhosny** [comment]
This diff is almost certainly wrong, but without I get saner glyph advances:

```diff
diff --git a/src/hb-graphite2.cc b/src/hb-graphite2.cc
index 9bb9136c4..ce324c46d 100644
--- a/src/hb-graphite2.cc
+++ b/src/hb-graphite2.cc
@@ -223,7 +223,6 @@ struct hb_graphite2_cluster_t {
   unsigned int base_glyph;
   unsigned int num_glyphs;
   unsigned int cluster;
-  int advance;
 };
 
 hb_bool_t
@@ -266,7 +265,7 @@ _hb_graphite2_shape (hb_shape_plan_t    *shape_plan HB_UNUSED,
   gr_segment *seg = nullptr;
   const gr_slot *is;
   unsigned int ci = 0, ic = 0;
-  unsigned int curradvx = 0, curradvy = 0;
+  int curradvx = 0, curradvy = 0;
 
   unsigned int scratch_size;
   hb_buffer_t::scratch_buffer_t *scratch = buffer->get_scratch_buffer (&scratch_size);
@@ -331,14 +330,6 @@ _hb_graphite2_shape (hb_shape_plan_t    *shape_plan HB_UNUSED,
   float xscale = (float) font->x_scale / upem;
   float yscale = (float) font->y_scale / upem;
   yscale *= yscale / xscale;
-  unsigned int curradv = 0;
-  if (HB_DIRECTION_IS_BACKWARD (direction))
-  {
-    curradv = gr_slot_origin_X(gr_seg_first_slot(seg)) * xscale;
-    clusters[0].advance = gr_seg_advance_X(seg) * xscale - curradv;
-  }
-  else
-    clusters[0].advance = 0;
   for (is = gr_seg_first_slot (seg), ic = 0; is; is = gr_slot_next_in_segment (is), ic++)
   {
     unsigned int before = gr_slot_before (is);
@@ -349,7 +340,6 @@ _hb_graphite2_shape (hb_shape_plan_t    *shape_plan HB_UNUSED,
     {
       clusters[ci-1].num_chars += clusters[ci].num_chars;
       clusters[ci-1].num_glyphs += clusters[ci].num_glyphs;
-      clusters[ci-1].advance += clusters[ci].advance;
       ci--;
     }
 
@@ -361,17 +351,6 @@ _hb_graphite2_shape (hb_shape_plan_t    *shape_plan HB_UNUSED,
       c->num_chars = before - c->base_char;
       c->base_glyph = ic;
       c->num_glyphs = 0;
-      if (HB_DIRECTION_IS_BACKWARD (direction))
-      {
-	c->advance = curradv - gr_slot_origin_X(is) * xscale;
-	curradv -= c->advance;
-      }
-      else
-      {
-	c->advance = 0;
-	clusters[ci].advance += gr_slot_origin_X(is) * xscale - curradv;
-	curradv += clusters[ci].advance;
-      }
       ci++;
     }
     clusters[ci].num_glyphs++;
@@ -379,11 +358,6 @@ _hb_graphite2_shape (hb_shape_plan_t    *shape_plan HB_UNUSED,
     if (clusters[ci].base_char + clusters[ci].num_chars < after + 1)
 	clusters[ci].num_chars = after + 1 - clusters[ci].base_char;
   }
-
-  if (HB_DIRECTION_IS_BACKWARD (direction))
-    clusters[ci].advance += curradv;
-  else
-    clusters[ci].advance += gr_seg_advance_X(seg) * xscale - curradv;
   ci++;
 
   for (unsigned int i = 0; i < ci; ++i)
@@ -393,50 +367,36 @@ _hb_graphite2_shape (hb_shape_plan_t    *shape_plan HB_UNUSED,
       hb_glyph_info_t *info = &buffer->info[clusters[i].base_glyph + j];
       info->codepoint = gids[clusters[i].base_glyph + j];
       info->cluster = clusters[i].cluster;
-      info->var1.i32 = clusters[i].advance;     // all glyphs in the cluster get the same advance
     }
   }
   buffer->len = glyph_count;
 
   /* Positioning. */
-  unsigned int currclus = UINT_MAX;
-  const hb_glyph_info_t *info = buffer->info;
   hb_glyph_position_t *pPos = hb_buffer_get_glyph_positions (buffer, nullptr);
   if (!HB_DIRECTION_IS_BACKWARD (direction))
   {
     curradvx = 0;
-    for (is = gr_seg_first_slot (seg); is; pPos++, ++info, is = gr_slot_next_in_segment (is))
+    for (is = gr_seg_first_slot (seg); is; pPos++, is = gr_slot_next_in_segment (is))
     {
       pPos->x_offset = gr_slot_origin_X (is) * xscale - curradvx;
       pPos->y_offset = gr_slot_origin_Y (is) * yscale - curradvy;
-      if (info->cluster != currclus) {
-	pPos->x_advance = info->var1.i32;
-	curradvx += pPos->x_advance;
-	currclus = info->cluster;
-      } else
-	pPos->x_advance = 0.;
-
+      pPos->x_advance = gr_slot_advance_X (is, grface, nullptr) * xscale;
       pPos->y_advance = gr_slot_advance_Y (is, grface, nullptr) * yscale;
+      curradvx += pPos->x_advance;
       curradvy += pPos->y_advance;
     }
   }
   else
   {
     curradvx = gr_seg_advance_X(seg) * xscale;
-    for (is = gr_seg_first_slot (seg); is; pPos++, info++, is = gr_slot_next_in_segment (is))
+    for (is = gr_seg_first_slot (seg); is; pPos++, is = gr_slot_next_in_segment (is))
     {
-      if (info->cluster != currclus)
-      {
-	pPos->x_advance = info->var1.i32;
-	curradvx -= pPos->x_advance;
-	currclus = info->cluster;
-      } else
-	pPos->x_advance = 0.;
-
+      pPos->x_advance = gr_slot_advance_X (is, grface, nullptr) * xscale;
       pPos->y_advance = gr_slot_advance_Y (is, grface, nullptr) * yscale;
-      curradvy -= pPos->y_advance;
-      pPos->x_offset = gr_slot_origin_X (is) * xscale - info->var1.i32 - curradvx + pPos->x_advance;
+      curradvx -= pPos->x_advance;
+      curradvy += pPos->y_advance;
       pPos->y_offset = gr_slot_origin_Y (is) * yscale - curradvy;
+      pPos->x_offset = gr_slot_origin_X (is) * xscale - curradvx;
     }
     hb_buffer_reverse_clusters (buffer);
   }
```

**Comment by mhosken** [comment]
That's quite a radical change which I am reluctant to make, partly because of the testing involved and partly because I remember trying this approach before and having problems.

But I agree there is a bug. I think there is a simpler solution:

```
-- a/src/hb-graphite2.cc
+++ b/src/hb-graphite2.cc
@@ -370,7 +370,7 @@ _hb_graphite2_shape (hb_shape_plan_t    *shape_plan HB_UNUSED,
       {
        c->advance = 0;
        clusters[ci].advance += gr_slot_origin_X(is) * xscale - curradv;
-       curradv += clusters[ci].advance;
+       curradv = gr_slot_origin_X(is) * xscale;
       }
       ci++;
     }
```

I'll do some more testing, but I'm hopeful that this is a sufficient solution. Unfortunately, due to travel, I won't be able to do that much testing. What minimal testing I have done implies to me that this minimal change is safe.

It's a shame the gr_slot_origin_X call is across a library boundary since optimisation probably can't do away with the two calls. I suppose we could use a variable.

This problem only shows up where a cluster is merged with a previous cluster and then a new cluster made.

**Comment by mhosken** [comment]
Thank you for digging into this problem.

I do like the idea of what you have done here to simplify things. So much so that I built a version of libharfbuzz with your changes in and it works to some extent. But in libo 7.3.7.2 if I try to use Awami Nastaliq, libo crashes. I don't have the wherewithall to dig any deeper on this atm.

Not trying to do your change down. I would love that it worked. But I did the same thing for my milder change and libo was happy all round.

**Comment by khaledhosny** [comment]
Did you build this, or the more complete patch in #4310?

**Comment by mhosken** [comment]
Just the patch I saw above.

**Comment by khaledhosny** [comment]
The one here indeed is broken for RTL text.

**Comment by mhosken** [comment]
trying #4310 now (by hand, so I hope I can dodge the typos)

**Comment by mhosken** [comment]
see #4310 for details

**Comment by khaledhosny** [comment]
> That's quite a radical change which I am reluctant to make, partly because of the testing involved and partly because I remember trying this approach before and having problems.
> 
> But I agree there is a bug. I think there is a simpler solution:
> 
> ```
> -- a/src/hb-graphite2.cc
> +++ b/src/hb-graphite2.cc
> @@ -370,7 +370,7 @@ _hb_graphite2_shape (hb_shape_plan_t    *shape_plan HB_UNUSED,
>        {
>         c->advance = 0;
>         clusters[ci].advance += gr_slot_origin_X(is) * xscale - curradv;
> -       curradv += clusters[ci].advance;
> +       curradv = gr_slot_origin_X(is) * xscale;
>        }
>        ci++;
>      }
> ```

This fixes the original issue reported here indeed. However I still get issues with other fonts/texts, eg. in the document from https://bugs.documentfoundation.org/show_bug.cgi?id=52577, text selection is unreliable, and moving the caret with arrow keys it jumps forward and backward.
