### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4320]
There were a couple of build issues with 8.0.0 that I fixed. Would be good to do a followup release. I also made more speed ups already:
* 60% speedup in retaingids subsetting SourceHanSans-VF.
* 38% speed up in subsetting (beyond-64k) mega-merged Noto.
* 16% speed up in retain-gid (used for IFT) subsetting of NotoSansCJKkr-Regular.otf.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/8.0.1
