### ISSUE TITLE
linker error related with using hb_hashmap_t<const hb_hashmap_t<hb_tag_t, Triple>*, unsigned>

### ISSUE THREAD

**Issue by qxliu76** [harfbuzz/harfbuzz#4322]
I got linker errors after enabling code that uses `hb_hashmap_t<const hb_hashmap_t<hb_tag_t, Triple>*, unsigned>`
code to reproduce is here: https://github.com/googlefonts/harfbuzz/tree/hashmap_issue

Error message:
```
[50/79] Linking target src/libharfbuzz-subset.so.0.60800.0
FAILED: src/libharfbuzz-subset.so.0.60800.0 
cc  -o src/libharfbuzz-subset.so.0.60800.0 src/libharfbuzz-subset.so.0.60800.0.p/hb-number.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-ot-cff1-table.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-ot-cff2-table.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-static.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-subset-cff-common.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-subset-cff1.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-subset-cff2.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-subset-input.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-subset-instancer-solver.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-subset-plan.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-subset-repacker.cc.o src/libharfbuzz-subset.so.0.60800.0.p/graph_gsubgpos-context.cc.o src/libharfbuzz-subset.so.0.60800.0.p/hb-subset.cc.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libharfbuzz-subset.so.0 -Bsymbolic-functions '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/usr/local/google/home/qxliu/harfbuzz/build/src src/libharfbuzz.so.0.60800.0 -lm -Wl,--end-group
/usr/bin/ld: src/libharfbuzz-subset.so.0.60800.0.p/hb-subset.cc.o: in function `std::_Hash_impl::hash(void const*, unsigned long, unsigned long)':
/usr/include/c++/12/bits/functional_hash.h:206: undefined reference to `std::_Hash_bytes(void const*, unsigned long, unsigned long)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
It seems to be that some header files are not found. However if I only use this hashmap inside test-map.cc, everything is fine. Code I added into test-map.cc:
 <pre><b>--- a/src/test-map.cc</b>
<b>+++ b/src/test-map.cc</b>
<span style="color:#2AA1B3">@@ -26,6 +26,7 @@</span>
 #include &quot;hb-map.hh&quot;
 #include &quot;hb-set.hh&quot;
 #include &lt;string&gt;
<span style="color:#26A269">+#include &quot;hb-subset-instancer-solver.hh&quot;</span>
 
 int
 main (int argc, char **argv)
<span style="color:#2AA1B3">@@ -354,5 +355,27 @@</span> main (int argc, char **argv)
     assert (values.is_equal (hb_set_t (m.values ())));
   }
 
<span style="color:#26A269">+  {</span>
<span style="color:#26A269">+    hb_hashmap_t&lt;hb_tag_t, Triple&gt; m1, m2, m3;</span>
<span style="color:#26A269">+    m1.set (1, Triple(0.0, 0.1, 0.2));</span>
<span style="color:#26A269">+    m1.set (2, Triple(0.0, 0.2, 0.4));</span>
<span style="color:#26A269">+</span>
<span style="color:#26A269">+    m2.set (1, Triple(0.1, 0.1, 0.2));</span>
<span style="color:#26A269">+    m2.set (2, Triple(0.1, 0.2, 0.4));</span>
<span style="color:#26A269">+</span>
<span style="color:#26A269">+    m3.set (1, Triple(0.0, 0.1, 0.2));</span>
<span style="color:#26A269">+    m3.set (2, Triple(0.0, 0.2, 0.4));</span>
<span style="color:#26A269">+</span>
<span style="color:#26A269">+    hb_hashmap_t&lt;const hb_hashmap_t&lt;hb_tag_t, Triple&gt;*, unsigned&gt; m;</span>
<span style="color:#26A269">+    m.set (&amp;m1, 1);</span>
<span style="color:#26A269">+    assert (m.has (&amp;m1));</span>
<span style="color:#26A269">+    assert (m.has (&amp;m3));</span>
<span style="color:#26A269">+    assert (m.get (&amp;m1) == 1);</span>
<span style="color:#26A269">+    assert (m.get (&amp;m3) == 1);</span>
<span style="color:#26A269">+    assert (!m.has (&amp;m2));</span>
<span style="color:#26A269">+    m.set (&amp;m2, 2);</span>
<span style="color:#26A269">+    assert (m.has (&amp;m2));</span>
<span style="color:#26A269">+    assert (m.get (&amp;m2) == 2);</span>
<span style="color:#26A269">+  }</span>
   return 0;
 }
</pre>

I've no idea what is missing in my code so I'd like to ask for help on this linker error. Thanks!

**Comment by qxliu76** [comment]
the error is caused by this function `merge_tuple_variations ()` in hb-ot-var-common.hh

**Comment by qxliu76** [comment]
Seems I can fix it by just changing `link_language` from `c` to `cpp` for libharfbuzz_subset. My question now is: can I make this change?

**Comment by behdad** [comment]
Try adding ::hash() impl to Triple.

**Comment by qxliu76** [comment]
> Try adding ::hash() impl to Triple.

Thanks, there's already an hash() impl existing for Triple, see below:
```
/* from hb_array_t hash ()*/
  uint32_t hash () const
  {
    uint32_t current = /*cbf29ce4*/0x84222325;
    current = current ^ hb_hash (minimum);
    current = current * 16777619;

    current = current ^ hb_hash (middle);
    current = current * 16777619;

    current = current ^ hb_hash (maximum);
    current = current * 16777619;
    return current;
  }
```
my guess is the hb_hash(float value) triggered this issue by calling std::hash<float>. I will try to add a hb_hash() impl for floating point.

**Comment by behdad** [comment]
> So we will need a hashing function for float values. 6 decimal precision for float might be enough for us, so my idea is to convert float to int and then do the hashing. Any suggestions?

Or call fasthash on its bytes.

**Comment by behdad** [comment]
There's `fasthash32` and `fasthash64`.

**Comment by behdad** [comment]
> `hb_hashmap_t<const hb_hashmap_t<hb_tag_t, Triple>*, unsigned>`

You probably want a uniqueptr there.

**Comment by qxliu76** [comment]
> There's `fasthash32` and `fasthash64`.

thank you!
