### ISSUE TITLE
Wcomma warning on 8.0.0

### ISSUE THREAD

**Issue by lissyx** [harfbuzz/harfbuzz#4328]
mozilla-central recently got updated to 8.0.0 and this re-introduced some `Wcomma` warning that are failing the build in my case: https://bugzilla.mozilla.org/show_bug.cgi?id=1843829

Doing similar fix https://phabricator.services.mozilla.com/D183719 as for similar earlier regressions fixes the issue on my side.

**Comment by behdad** [comment]
Fixed. No idea why it doesn't err on our side. We have Wcomma in our hb.hh setup.
