### ISSUE TITLE
Commit 4ea3737 changes shaping behavior

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#4336]
4ea3737d04c575cd9b6ffda1e4e0f2c9d2b60d9c changes shaping behavior, so it is not a valid optimization. For example, given [Duployan-Regular.otf](https://github.com/harfbuzz/harfbuzz/files/12115580/Duployan-Regular.otf.zip), this command:
```bash
hb-shape Duployan-Regular.otf -u '1BC09 1BC9E 1BC9E 1BC9E' -O json \
| jq -r 'map(.g | select(startswith("_") | not))[]'
```
used to produce:
```
u1BC09.v
u1BC9E_u1BC9E_u1BC9E_.double__double__double.30
```
but now produces:
```
u1BC09.v
u1BC9E_u1BC9E_.double__double.30
dupl_.Line.0.dotted
u1BC9E_.double.90.wl
```

**Comment by behdad** [comment]
Thanks. I'll investigate.

**Comment by behdad** [comment]
@dscorbett Is there a Duployan corpus (no matter how small) I can use for performance testing?
