### ISSUE TITLE
8.1.0 changes shaping results for "JetBrains Mono Regular" in wezterm when compiled in release mode

### ISSUE THREAD

**Issue by wez** [harfbuzz/harfbuzz#4358]
Sorry about this lazy report. Yesterday I tried updating wezterm's vendored build to 8.1.0.

When running wezterm's tests in debug mode everything was fine, but when the tests run in release mode, they failed.
It looks like the shaping results are dramatically different when built with optimization.
Reverting back to the prior release "resolved" the issue.

I haven't had time to dig further, but thought you'd appreciate the heads up that something seems to have changed in perhaps a surprising way.

Here's a link to one of the failing jobs; the failure was consistent across windows, mac and linux, but this one is from an ubuntu container:

https://github.com/wez/wezterm/actions/runs/5723004104/job/15506895240

**Comment by wez** [comment]
Here are some slightly more helpful links to what is being tested in wezterm's tests, so that it is a bit easier for you to verify the same font and sequence independently from wezterm's machinery:

"Fira Code", the sequence: "a..."
https://github.com/wez/wezterm/blob/ca9cf23019105b8093dc7ad44b91a68078514b5e/wezterm-gui/src/shapecache.rs#L221-L255

"JetBrains Mono Regular", the sequence: "a..."
https://github.com/wez/wezterm/blob/ca9cf23019105b8093dc7ad44b91a68078514b5e/wezterm-gui/src/shapecache.rs#L381-L413

**Comment by behdad** [comment]
Oof. I'll try to decipher this. Thanks.

**Comment by behdad** [comment]
I can easily reproduce this with hb-shape. Looking into it. Thanks for the report.

**Comment by behdad** [comment]
I believe I fixed this. Please test. cc @khaledhosny for 8.1.1.

**Comment by behdad** [comment]
I'm not sure why you were not seeing the bug in debug mode. The bug should have been present unless either you were compiling with optimize-size (-Os / -Oz), or if you had the unsafe-to-break buffer flag enabled.

**Comment by behdad** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/8.1.1

**Comment by wez** [comment]
> I'm not sure why you were not seeing the bug in debug mode. The bug should have been present unless either you were compiling with optimize-size (-Os / -Oz), or if you had the unsafe-to-break buffer flag enabled.

I think maybe there was/is something was funky in my build invalidation as I had a weird thing where I had to `cargo clean` just now in order for 8.1.1 to pass tests without showing the earlier errors from 8.1.0 :-/

However, I can confirm that 8.1.1 passes the tests; thank you!
