### ISSUE TITLE
Broken characters with Kitty terminal after updating to 8.1.0

### ISSUE THREAD

**Issue by xfzv** [harfbuzz/harfbuzz#4359]
Original issue with all details to reproduce: https://github.com/kovidgoyal/kitty/issues/6518

On both Arch Linux and Gentoo, downgrading from 8.1.0 to 8.0.1 immediately solves the issue as far as I'm concerned.

**Comment by behdad** [comment]
Yeah sorry about this. I think it's duplicate of https://github.com/harfbuzz/harfbuzz/issues/4358 which I fixed last night. We'll get a release out today.

**Comment by behdad** [comment]
No worries. Thanks for the report.
