### ISSUE TITLE
cannot build harfbuzz-8.1.1 on centos

### ISSUE THREAD

**Issue by 54huaxiao** [harfbuzz/harfbuzz#4360]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<const hb_serialize_context_t::object_t*, unsigned int>::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<unsigned int, Triple>::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<unsigned int, hb_pair_t<unsigned int, int> >::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<unsigned int, hb_vector_t<unsigned int> >::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<unsigned int, hb::unique_ptr<hb_set_t> >::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<hb::shared_ptr<hb_map_t>, unsigned int>::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<unsigned int, hb::shared_ptr<hb_set_t> >::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<unsigned int, const OT::Feature*>::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<unsigned int, hb_set_t>::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<unsigned int, face_table_info_t>::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<hb_hashmap_t<unsigned int, Triple>, unsigned int>::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<const hb_vector_t<bool>*, unsigned int>::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
/home/ops/library/harfbuzz-8.1.1/src/hb-iter.hh:165:3: error: ‘hb_array_t<Type><anonymous struct>::operator()(Type*, unsigned int) const [with Type = hb_hashmap_t<const hb_vector_t<bool>*, hb_array_t<const char> >::item_t]’, declared using anonymous type, is used but never defined [-fpermissive]
In file included from /home/ops/library/harfbuzz-8.1.1/src/hb-serialize.hh:36:0,
                 from /home/ops/library/harfbuzz-8.1.1/src/hb-subset.hh:36,
                 from /home/ops/library/harfbuzz-8.1.1/src/hb-open-type.hh:37,
                 from /home/ops/library/harfbuzz-8.1.1/src/hb-aat-ltag-table.hh:28,
                 from /home/ops/library/harfbuzz-8.1.1/src/hb-aat-layout.hh:33,
                 from /home/ops/library/harfbuzz-8.1.1/src/hb-aat-layout.cc:30,
                 from /home/ops/library/harfbuzz-8.1.1/src/harfbuzz.cc:1:
/home/ops/library/harfbuzz-8.1.1/src/hb-map.hh: In member function ‘uint32_t hb_hashmap_t<K, V, minus_one>::hash() const [with K = unsigned int; V = unsigned int; bool minus_one = true; uint32_t = unsigned int]’:
/home/ops/library/harfbuzz-8.1.1/src/hb-map.hh:366:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
make[2]: *** [CMakeFiles/harfbuzz.dir/src/harfbuzz.cc.o] Error 1
make[1]: *** [CMakeFiles/harfbuzz.dir/all] Error 2
make: *** [all] Error 2

**Comment by behdad** [comment]
What centos version? What compiler version?

**Comment by behdad** [comment]
Closing till more information is provided.
