### ISSUE TITLE
Supporting `stch` for Arabic subtending marks

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#4369]
I think some Arabic subtending marks can work rather well with [`stch`](https://learn.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-stch) feature, but this would need explicit support from HarfBuzz (and getting the feature registry entry updated).

In case we want to support this, here is a test font: [SubtendingTest.zip](https://github.com/harfbuzz/harfbuzz/files/12290097/SubtendingTest.zip)

I tested with:
```
$ hb-view master_ttf/SubtendingTest-Regular.ttf -u 0891,0661,0662,0663,066B --direction=l
```

and got:
![SubtendingTest](https://github.com/harfbuzz/harfbuzz/assets/93914/b9560791-795c-4366-9987-0467b133de20)
(I had to add `--margin=0,0,0,300` to see the rest of the glyphs)

It should have been something like:
![SubtendingTest-expectd](https://github.com/harfbuzz/harfbuzz/assets/93914/86b402ad-c8af-485e-a476-aa1bb5e90dda)

Two issues:
1. It does not work with LTR direction
2. It should try to cover the numbers only (this is not easy to test with hb-view/show, I think because adding a letter to th

**Comment by behdad** [comment]
> * It does not work with LTR direction

Right... I'll take a look.

**Comment by behdad** [comment]
I first have to debug why it doesn't work properly in RTL either...

**Comment by behdad** [comment]
I fixed a bug with advance widths and now at least for direction=r I get:

![out](https://github.com/harfbuzz/harfbuzz/assets/142891/da393280-2066-4f19-9dcc-75be07bce409)

Looks to me like the tail glyph has too large of an advance. That's why it doesn't connect.

**Comment by khaledhosny** [comment]
> I fixed a bug with advance widths and now at least for direction=r I get:
> 
> ![out](https://user-images.githubusercontent.com/142891/259191749-da393280-2066-4f19-9dcc-75be07bce409.png)
> 
> Looks to me like the tail glyph has too large of an advance. That's why it doesn't connect.

The glyph is designed to connect to the left and not to the right (the subtending marks have AN bidi class so they are always LTR).

**Comment by behdad** [comment]
Fixed I think?
![out](https://github.com/harfbuzz/harfbuzz/assets/142891/2a4e46af-aaba-461c-b7f4-ed889bb8f633)

**Comment by khaledhosny** [comment]
Excellent, looks perfect.

**Comment by khaledhosny** [comment]
I tested and things are looking good. The only remaining issue so far is how it looks when only one number is used (i.e. the width is less than the width of the fixed glyphs).

Here is an updated test font: [SubtendingTest.zip](https://github.com/harfbuzz/harfbuzz/files/12295379/SubtendingTest.zip)

With:
```
$ hb-view SubtendingTest-Regular.ttf -u 0891,0662 --direction=l
```
![SubtendingTest](https://github.com/harfbuzz/harfbuzz/assets/93914/7d0464c6-491e-4ee5-ab88-f6ff56e6277b)

But I would have expected the numbers and the sign to be centered in relation to each other.

**Comment by khaledhosny** [comment]
(if I were to shift the glyphs, I’d shift the numbers not the sign and make sure the last glyph gets positive advance, so that the sequence does not pump into sorrounding text)

**Comment by behdad** [comment]
I see your point. But I'm a bit hesitant to do that right now. I can at least center it without messing with advance widths. Lemme try that.

**Comment by behdad** [comment]
With centering:

![out](https://github.com/harfbuzz/harfbuzz/assets/142891/25e12f54-fd44-42db-9462-cb857d6c2768)
