### ISSUE TITLE
hb-view: Incomplete COLRv0 tables

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#4378]
I have a  [font (gzip)](https://github.com/harfbuzz/harfbuzz/files/12360663/NotoZnamennyMusicalNotation-Regular.ttf.gz) with a COLRv0 table. This table contains ColorGlyph entries for some glyphs but not for all. This is deliberate - I want some glyphs to be painted with a colour and others just to use the ink color, and I don't think I need to put in a ColorGlyph entry for every glyph.

In Chrome and Safari this works fine. But when I view this with hb-view, any combinations which include a glyph with no ColorGlyph entry ends up blank. For example in `-u 1cf52,1cf03`, 1CF03 has a ColorGlyph entry but 1CF52 does not, and the whole returned image is blank.

**Comment by behdad** [comment]
I can't reproduce. I get this:
![out](https://github.com/harfbuzz/harfbuzz/assets/142891/f6ab45aa-58d0-4ce7-b450-23b3b0765a8e)

Might be a very old cairo... Does setting HB_DRAW to 0 or 1 make a difference?

**Comment by khaledhosny** [comment]
Isn’t this the old Cairo bug that is fixed only in the unstable versions? (trying to find the old issue but I can’t seem to find it)

**Comment by khaledhosny** [comment]
There haven’t been a stable cairo release in ages and homebrew tracks only stable releases, so they are still on cairo 1.16.x, most Linux distro gave up and started packaging cairo unstable releases.

**Comment by behdad** [comment]
Yeah I don't think the stable vs unstable distinction holds anymore.

**Comment by khaledhosny** [comment]
I agree, and I raised that before, but the text on cairo website still warns about unstable releases. From https://cairographics.org/download/#development (it does not even call them releases, but “snapshots”):

> If you want to stay on the absolute cutting-edge of what's happening with cairo, and you don't mind playing with software that is unstable and full of rough edges, then we have several things you might enjoy:

**Comment by behdad** [comment]
cc @ebassi to see if we can at least change the cairo website.

**Comment by behdad** [comment]
FWIW I'm testing with cairo 1.16.0 on brew as well. Weird.

**Comment by ebassi** [comment]
I'm planning a 1.18.0 release this month—just a couple merge requests are left in the pipeline. In general, the even/odd pattern still applies; and, yes: 1.17 is still unstable. There are a bunch of changes in the API that has been introduced over the past few years, so I cannot recommend people consider it "stable". Various platforms have been shipping unstable Cairo snapshots for the past decade, as the result of Cairo's maintenance issues, so this isn't a particularly new development.

After 1.18 is done, I honestly don't know what will happen. I don't see a lot of work or effort being expended on Cairo, so the even/odd versioning may not make any more sense. If that happens, I'll make sure to notify downstreams.

**Comment by simoncozens** [comment]
Weird, I'm on Cairo 1.16.0(_5) on brew. HB_DRAW=0 shows the problem, HB_DRAW=1 and everything is black.

**Comment by behdad** [comment]
> Weird, I'm on Cairo 1.16.0(_5) on brew. HB_DRAW=0 shows the problem, HB_DRAW=1 and everything is black.

I see. I probably have newer cairo installed then. HB_DRAW=1 being black is expected with that old cairo. And yeah it's probably just a cairo bug.

**Comment by behdad** [comment]
I reconfigured using the 1.16.0 cairo and can reproduce like yours. I'll take a look.

**Comment by behdad** [comment]
I'm guessing this commit fixed it in cairo: https://gitlab.freedesktop.org/cairo/cairo/-/commit/65d4325e6f674e7b45b3001d9e4bc0aeecb19e0e
