### ISSUE TITLE
Ligatures are displayed when rendering fonts using pango with the `no_liga` option

### ISSUE THREAD

**Issue by aragon999** [harfbuzz/harfbuzz#4414]
After the upgrade of `harfbuzz` from version `8.1.1` to version `8.2.0` rendering of fonts through `pango` is not considering the `no_liga` font option anymore.

I only noticed the problem in sublime text, see the following issue: https://github.com/sublimehq/sublime_text/issues/6136

I have not verified if it occurs also in other applications. If you need additional information, please let me know.

**Comment by khaledhosny** [comment]
Pango has `no_liga` option, so I don’t know what that translates to. Are you able to build harfbuzz from source and bisect this issue?

**Comment by aragon999** [comment]
Thank you for the quick response.

Yes, I will bisect the issue :-) not sure when I will be able to do that though, hopefully some time during the weekend.

**Comment by behdad** [comment]
cc @matthiasclasen

**Comment by matthiasclasen** [comment]
I don't know what no_liga is

**Comment by khaledhosny** [comment]
LibreOffice got a test failure around `hb_feature_from_string()`, it might be related:
https://lists.freedesktop.org/archives/libreoffice/2023-September/091026.html

**Comment by khaledhosny** [comment]
It seems parsing CSS feature settings syntax is broken:
```C
#include <stdio.h>
#include <string.h>
#include <hb.h>

int main(int argc, char **argv) {
    char *text = argv[1];
    hb_feature_t feature;
    hb_bool_t ret = hb_feature_from_string(text, strlen(text), &feature);
    printf("ret: %d\n", ret);
}
```

```
$ ./test '+liga'
ret: 1
$ ./test '-liga'
ret: 1
$ ./test '"liga" on'
ret: 0
$ ./test '"liga" off'
ret: 0
```

**Comment by aragon999** [comment]
Ah, I totally forgot, I bisected the issue and the faulty commit is: https://github.com/harfbuzz/harfbuzz/commit/e8eb1dc5ff695427abc137d3d15c4eec64ab6c78 when reverting it, it works again.

**Comment by jfkthame** [comment]
Looks like this line
```
  while (*pp < end && (**pp != ' ' && **pp != '=' && **pp != '['))
```
should also be checking for a quote, so something like
```
  while (*pp < end && (**pp != ' ' && **pp != '=' && **pp != '[' && **pp != quote))
```
(untested) might fix things.

**Comment by khaledhosny** [comment]
> (untested) might fix things.

Seems to work.
