### ISSUE TITLE
[instancer] Port solver fix from fonttools

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4447]
See https://github.com/fonttools/fonttools/pull/3304

**Comment by behdad** [comment]
Is this still relevant?

**Comment by qxliu76** [comment]
No, fix is ported in #4484, could you help close the issue? I cannot close it.

**Comment by anthrotype** [comment]
> I cannot close it.

I now changed it your user to "Write", was only "Read" before for some reasons

**Comment by qxliu76** [comment]
> > I cannot close it.
> 
> I now changed your user to "Write", was only "Read" before for some reasons

thank you!
