### ISSUE TITLE
Consider including vhal, halt, chws, and vchw by default in subsetting.

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#4451]
These provide positioning for CJK font characters and are enabled by default in Chrome so we may want to include them in the list of default features for the subsetter.

**Comment by yisibl** [comment]
Looks like it's here, can I submit a PR?
https://github.com/harfbuzz/harfbuzz/blob/38f351d113fcc66cd4aaafbcee952a6067f315a9/src/hb-subset-input.cc#L82

**Comment by yisibl** [comment]
Yeah, it is needed for CSS text layout. https://chromium-review.googlesource.com/c/chromium/src/+/4881743

**Comment by behdad** [comment]
Yes please!

**Comment by anthrotype** [comment]
@behdad does it make sense to group them under `"east_asian_spacing": ["chws", "vchw", "halt", "vhal"],` like I did in https://github.com/fonttools/fonttools/pull/3305 or should we put them under a different heading
