### ISSUE TITLE
Wasm shaper docs create font

### ISSUE THREAD

**Issue by wipfli** [harfbuzz/harfbuzz#4456]
There might be an inconsistency in the wasm shaper docs at https://github.com/harfbuzz/harfbuzz/blob/main/docs/wasm-shaper.md#face-handling-functions

Which one is correct, face_create or get_font_face?

**Comment by behdad** [comment]
> Which one is correct, face_create or get_font_face?

`font_get_face` gets a face object from a font object. Those two are different.

`face_create` creates a font.

There's no `get_font_face`.

**Comment by wipfli** [comment]
Thanks
