### ISSUE TITLE
`HB_AAT_LAYOUT_FEATURE_TYPE_CURISVE_CONNECTION` is misspelled

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#4464]
The enum value `HB_AAT_LAYOUT_FEATURE_TYPE_CURISVE_CONNECTION` in the API is a typo for `HB_AAT_LAYOUT_FEATURE_TYPE_CURSIVE_CONNECTION`.

**Comment by ebraminio** [comment]
This is my fault and I'm sorry about it, I just wanted to provide a fix but I was late, I will recheck other addition for other mistakes possible. Sorry and thanks.

**Comment by behdad** [comment]
No worries @ebraminio!
