### ISSUE TITLE
msvc build fails

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4475]
Used to be because of old lxml. I updated that. Now it fails building glib. Can we avoid building glib from source?

https://github.com/harfbuzz/harfbuzz/actions/runs/6735851645/job/18309949869

**Comment by behdad** [comment]
The error is that some python code glib is running tries to import `distutils`, which is not installed. I'll add it to our .ci requirements and see.

**Comment by anthrotype** [comment]
distutils is no longer in the python 3.12 standard library and is deprecated. It's still bundled with setuptools.
See https://peps.python.org/pep-0632

**Comment by behdad** [comment]
https://gitlab.gnome.org/GNOME/glib/-/issues/3134

**Comment by behdad** [comment]
Yay. Bots are green again.

**Comment by khaledhosny** [comment]
> Can we avoid building glib from source?

I’d love to not build any dependencies from source with MSVC, but I don’t know how to use one of these Windows package managers to install the dependencies and have meson find them.
