### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#4486]
To include the `hb_barrier()` fix.

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/8.3.0

**Comment by yisibl** [comment]
Is the content in this PR https://github.com/harfbuzz/harfbuzz/pull/4455 worth logging into the changelog?

**Comment by behdad** [comment]
> Is the content in this PR #4455 worth adding into the changelog?

Was worth it but this train has left already. We cannot rewrite commits.

**Comment by yisibl** [comment]
It doesn't matter. 😂
