### ISSUE TITLE
harfbuzz.pc needs -lstdc++ dependency

### ISSUE THREAD

**Issue by fish47** [harfbuzz/harfbuzz#4502]
https://github.com/vitasdk/packages/issues/300

Hosts like ps vita need explicit `stdc++` dependency because most libraries are statically linked.
This subtle fix should be done on upstream, since `harfbuzz` does use C++ features internally while maintaing C-style public APIs.

**Comment by behdad** [comment]
While we use C++ internally, we go out of our way to NOT use libstdc++.

**Comment by fish47** [comment]
How about `-lsupc++`? It's lightweight enough and provides basic `c++` language support.

**Comment by behdad** [comment]
It's still not clear to me what the problem is. We've been building on a dozen platform without problem. You just need to pass those two flags to the compiler.

**Comment by fish47** [comment]
Thanks for your reply. I just missed the messages of the referred issue. I know what you mean now.
