### ISSUE TITLE
Opening a font file with a UTF8-encoded file name fails under Windows

### ISSUE THREAD

**Issue by utelle** [harfbuzz/harfbuzz#4511]
Under Windows the function `hb_blob_create_from_file(const char *file_name);` uses internally the function `mbstowcs()` to convert the file name to a wide string. Unfortunately this works only, if the file name is encoded in the default encoding scheme, which is `win-1252` on my system.

My application uses exclusively UTF8-encoded strings, and therefore `hb_blob_create_from_file()` (resp the underlying function `hb_blob_create_from_file_or_fail()`) fails to open a font file, if the font file name contains non-ASCII characters.

IMHO it would be good, if a function could be added to the harfbuzz API to allow to open font files with UTF8-encoded file names, for example by adding a function `hb_blob_create_from_file_utf8()`.

An alternative could be to use `_mbstowcs_l()` with a UTF-8 locale, or to allow to explicitly pass in a locale that should be used for the file name conversion.

**Comment by Eli-Zaretskii** [comment]
The Windows code in HarfBuzz should use `MultibyteToWideChar` passing it the appropriate codepage argument. Anything else will only works for characters supported by the current locale.

**Comment by utelle** [comment]
> I suggest we go with option one.

Ok, I will prepare a PR within the next couple of days.

**Comment by behdad** [comment]
Thanks.

**Comment by utelle** [comment]
Adjusting the implementation of `hb_blob_create_from_file_or_fail()` was easy and I have it working in my local environment.

However, I don't know what has to be done to adjust the API documentation, because it is not in the harfbuzz repository.

**Comment by utelle** [comment]
IMHO the modified implementation of PR https://github.com/harfbuzz/harfbuzz/pull/4514 should make (almost) everyone happy, because it tries to interpret the filename as UTF-8 first, but will fallback to the system codepage (as before), if the filename is **not** valid UTF-8.

**Comment by behdad** [comment]
Looks good to me. Thanks
