### ISSUE TITLE
CJK angle brackets shifted to the top of em-box on vertical text layout (Mongolian Baiti)

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#452]
This problem can be reproduced by coping the following codes into [WYMeditor integration example](https://wymeditor.github.io/wymeditor/dist/examples/01-basic.html) page:
```
<div style="font-family: Mongolian Baiti; font-size: 2em;">
<p><u>《|》</u></p>
<p style=" writing-mode: vertical-lr;"><u>《|》</u></p>
</div>
```
Both Chrome and Firefox looks the same as this screenshot.
![default](https://cloud.githubusercontent.com/assets/10364351/24622179/9cfb1638-18d6-11e7-8a48-827ad8ffc2a7.PNG)

With this file you can also see the effect on LibreOffice 5.3:
[Test file.zip](https://github.com/behdad/harfbuzz/files/890868/Test.file.zip)

**Comment by emuller-amazon** [comment]
This may be related:

emuller> type hb
hb is a function
hb () 
{ 
    ~/harfbuzz/harfbuzz/util/hb-view --output-format=png --annotate "$@" | tee ~/tmp/hb.png | open -a "Preview" -f;
    ~/harfbuzz/harfbuzz/util/hb-shape --no-glyph-names --no-clusters --trace "$@"
}
emuller> hb ~/fonts/noto/noto-cjk/NotoSerifCJKjp-Regular.otf -u 3008,5678 --direction=ttb
trace: start lookup 2	buffer: [1404|13006]
trace: end lookup 2	buffer: [1404|13006]
trace: start lookup 3	buffer: [1404|13006]
trace: end lookup 3	buffer: [1404|13006]
trace: start lookup 4	buffer: [1404|13006]
trace: end lookup 4	buffer: [1404|13006]
trace: start lookup 5	buffer: [1404|13006]
trace: end lookup 5	buffer: [1404|13006]
trace: start lookup 47	buffer: [1404|13006]
trace: end lookup 47	buffer: [59901|13006]
trace: start lookup 48	buffer: [59901|13006]
trace: end lookup 48	buffer: [59901|13006]
trace: start lookup 51	buffer: [59901|13006]
trace: end lookup 51	buffer: [59901|13006]
trace: start lookup 0	buffer: [59901@-500,-880+0,-1000|13006@-500,-880+0,-1000]
trace: end lookup 0	buffer: [59901@-500,-880+0,-1000|13006@-500,-880+0,-1000]
trace: start lookup 1	buffer: [59901@-500,-880+0,-1000|13006@-500,-880+0,-1000]
trace: end lookup 1	buffer: [59901@-500,-880+0,-1000|13006@-500,-880+0,-1000]
[59901@-500,-880+0,-1000|13006@-500,-880+0,-1000]
emuller> 


So the positions are as expected in the hb-shape output, but the hb-view ouput looks different:

![hb](https://user-images.githubusercontent.com/16089970/35890215-a0c7c2fa-0b53-11e8-8eea-219120361a19.png)

May be this is related to the lack of support for VORG?

**Comment by behdad** [comment]
Yes, I believe hb-view is wrong, and there's a bug for that as well.  I have to spend a better part of an afternoon debugging this.

**Comment by KrasnayaPloshchad** [comment]
I suggest you should make some improves to make upright glyphs always placed at the middle of em-box.

**Comment by KrasnayaPloshchad** [comment]
> May be this is related to the lack of support for VORG?

VORG table is used only for OT-CFF fonts, for TrueType fonts, the equivalance is VHEA/VMDX.

**Comment by HinTak** [comment]
I am glad I am not the only one noticing hb-shape is not processing vertical layout mongolian correctly. ( started working on https://github.com/HinTak/harfbuzz-python-demos/issues/1 ).

BTW, the monbaiti font is copyright Microsoft and probably should not be posted publicly.

BTW

**Comment by KrasnayaPloshchad** [comment]
> BTW, the monbaiti font is copyright Microsoft and probably should not be posted publicly.

Yeah, I just discovered on my computer, and tested again to confirmed, then I send screenshot here. But I think everyone can also reproduce via getting a VM if you don’t have Windows:
https://developer.microsoft.com/windows/downloads/virtual-machines
https://developer.microsoft.com/microsoft-edge/tools/vms/

**Comment by KrasnayaPloshchad** [comment]
In Firefox 62.0.3 they works pretty now, it’s interesting to investigate.
![1](https://i.imgur.com/Irp28CC.png)

**Comment by HinTak** [comment]
Harfbuzz is not working correctly for vertical layout   mongolian with monbaiti . I just tried and it is also behaving differently compared to uniscribe too.

**Comment by behdad** [comment]
> Harfbuzz is not working correctly for vertical layout mongolian with monbaiti . I just tried and it is also behaving differently compared to uniscribe too.

Instead of nagging in random github issues, file a proper issue with details.  Vertical Mongolian and Phags Pa with OpenType are achieved by horizontal typesetting and then rotating the results.  That's different from any other script.

**Comment by behdad** [comment]
Can someone test this again? I've fixed a few things in vertical recently.

**Comment by behdad** [comment]
This also seems fixed.
