### ISSUE TITLE
U+00AD Soft Hyphen not made visible on Line Breaks as is expected behaviour

### ISSUE THREAD

**Issue by TheSofox** [harfbuzz/harfbuzz#4520]
U+00AD, Soft Hyphen (aka SHY) has some distinct properties that HarfBuzz doesn't seem to currently support.

It's a control character that marks where line breaks can be made within text. In terms of visibility it is invisible EXCEPT when it appears at the end of the line in which case it appears as a hyphen. This is the trick, its visibility entirely depends on where it appears in a block of text.

Wikipedia has more details about this, including a block of text example that you can resize your browser window and see in real time how the character is meant to behave: https://en.wikipedia.org/wiki/Soft_hyphen 

I came across this bug when investigating this bug on the Godot Engine (original bug report here which has more details: https://github.com/godotengine/godot/issues/85815 ).

Ultimately, the flag `HB_BUFFER_FLAG_PRESERVE_DEFAULT_IGNORABLES` will determine whether _every_ Soft Hypen is visible, or invisible. Nothing seems to set the conditional visibility that such a unique control character needs.

**Comment by behdad** [comment]
You are right, that HarfBuzz itself does NOT handle visibility of SHY. The reason is simple: HarfBuzz does not know whether the text being shape is at the end of the line. Line-breaking happens at a higher level and its the higher-level's responsibility to insert a real hyphen and shape with HarfBuzz. That's what browsers do I believe.

cc @jfkthame

**Comment by jfkthame** [comment]
Agree, this is not the responsibility of the shaper, which doesn't know anything about line breaks.

It's the responsibility of the application that is breaking text into lines -- whether that's at whitespace or at soft-hyphen codepoints or at automatically-determined hyphenation positions (as with CSS `hyphens: auto`) or any other rules -- to make any necessary adjustments to the text that is to be displayed on each line.

**Comment by TheSofox** [comment]
Right, sorry I thought the shaper handled the vertical dimension, but from what you're saying it only handles things horizontally?

**Comment by behdad** [comment]
> Right, sorry I thought the shaper handled the vertical dimension, but from what you're saying it only handles things horizontally?

Yes. And even then just fragments that have the same script/language/direction.

**Comment by behdad** [comment]
@khaledhosny is Raqm used in Godot?

**Comment by khaledhosny** [comment]
> @khaledhosny is Raqm used in Godot?

No it doesn’t, it uses its own code that calls HarfBuzz and ICU, and from what I saw it is quite sophisticated than Raqm.

**Comment by TheSofox** [comment]
Thank you for all your help here, greatly appreciated.
From further investigation, I seem to have located the function that does the line breaks to `PackedInt32Array TextServer::shaped_text_get_line_breaks(...)` in `servers/text_server.cpp` (called from `scene/resources/text_paragraph`). This is most definitely within the Godot engine itself and not within HarfBuzz (which is stored in the `thirdparty/harbuzz` directory).
Sorry for the inconvenience and thank you once again for all your help.

**Comment by behdad** [comment]
No problem.
