### ISSUE TITLE
Harfbuzz can not shape this simple Latin font from 1993

### ISSUE THREAD

**Issue by photopea** [harfbuzz/harfbuzz#4540]
Harfbuzz can not shape this simple Latin font from 1993. Do you know what the problem is? Could you fix it?

[Brushstroke-Plain.zip](https://github.com/harfbuzz/harfbuzz/files/13832540/Brushstroke-Plain.zip)

**Comment by behdad** [comment]
The font has only a MacRoman cmap table and no Unicode one. We don't support that, though wouldn't be hard to add.

**Comment by behdad** [comment]
As a start we can assume that all Mac encodings are ASCII-compatible.

**Comment by behdad** [comment]
> As a start we can assume that all Mac encodings are ASCII-compatible.

I did a hack but am not getting the right numbers out. I'm baffled, because in the ttx, the mapping looks wrong:
```
      <map code="0x41" name="at"/> 
      <map code="0x42" name="A"/> 
      <map code="0x43" name="B"/> 
      <map code="0x44" name="C"/> 
      <map code="0x45" name="D"/> 
      <map code="0x46" name="E"/> 
```
Ie. 0x41 should be mapped to "A" but it isn't. Yet `--font-funcs=ft` seems to get this right. So I'm missing something.

**Comment by behdad** [comment]
@khaledhosny any ideas?

**Comment by jfkthame** [comment]
Opening the font in Glyphs.app, it looks like the glyph names are out of sync:

<img width="1138" alt="image" src="https://github.com/harfbuzz/harfbuzz/assets/1706499/0c4f9bd5-77d6-42a2-9e87-e298516bb630">

**Comment by jfkthame** [comment]
The font has a format 1.0 'post' table, which should mean that it "contains exactly the 258 glyphs in the standard Macintosh TrueType font file", but it doesn't actually conform to this. Hence the glyph names are invalid/unreliable.

**Comment by behdad** [comment]
Oh interesting! My hack actually *renders* correctly. `--font-funcs=ft` renders wrong. I wonder if FT is using glyph names instead. @lemzwerg

**Comment by lemzwerg** [comment]
This is an interesting font.  FreeType doesn't handle it correctly, AFAICS.  On the other hand, FontForge loads it apparently just fine.

@apodtele, can you please have a look?  Right now, I'm not very active on the FreeType side...

**Comment by apodtele** [comment]
@jfkthame is correct that the `post` is incorrectly 1.0. We can possibly reject it given that there is clearly less than 258 glyphs. However, I found [this font](https://www.dafontfree.net/brushstroke-plain-plain-font/f64546.htm) with an earlier timestamp still 1993 but later version number. This version has appropriate `post` 2.0 and a unicode cmap. Perhaps it was fixed at some point.

I am not sure if we should worry about the broken version.

**Comment by behdad** [comment]
Excuse my ignorance. But the font has a format0 cmap table which maps 256 chars exactly. That some of those seem to map to zero shouldn't throw off FreeType like that. Why does it?

**Comment by apodtele** [comment]
@behdad You are correct too. There is an incomplete MacRoman cmap. In ASCII range it misses `@` and `{|}~` after `z`. This is kind of a substituted font. 

FreeType, for a while now, tries to generate unicode cmap from glyph names if one is missing. I think it is a good behavior that we should not change because of one font with broken post and incomplete MacRoman.

**Comment by behdad** [comment]
Thanks @apodtele.

> FreeType, for a while now, tries to generate unicode cmap from glyph names if one is missing. I think it is a good behavior that we should not change because of one font with broken post and incomplete MacRoman.

I see.

For HarfBuzz I suggest we just use any Mac encoding just for the ASCII range and call it a day.

**Comment by apodtele** [comment]
Yes, but the broken synthetic unicode is active by default. You would need to detect that it is synthetic (has invalid format -1) and explicitly switch to MacRoman. If we rejected the broken post, there would not be any broken unicode.

**Comment by apodtele** [comment]
Should be fixed now.

https://gitlab.freedesktop.org/freetype/freetype/-/commit/4a85ff0b79ebb6a3e70c3b82cb63ffe4a0d4ccf0

**Comment by photopea** [comment]
Thanks a lot, guys!
