### ISSUE TITLE
MathKern::get_value() fix

### ISSUE THREAD

**Issue by lie-yan** [harfbuzz/harfbuzz#4542]
According to the current implementation comment of [`MathKern::get_value()`](https://github.com/harfbuzz/harfbuzz/blob/5852d328a4b3c0064feb58d465f58c247ae1ad90/src/hb-ot-math-table.hh#L341), current implementation seems to be based on an outdated OpenType spec. 
```cpp
/* The description of the MathKern table is a ambiguous, but interpreting
 * "between the two heights found at those indexes" for 0 < i < len as
 *
 *   correctionHeight[i-1] < correction_height <= correctionHeight[i]
 *
 * makes the result consistent with the limit cases and we can just use the
 * binary search algorithm of std::upper_bound:
 * /
```

[OpenType spec v1.9](https://learn.microsoft.com/en-us/typography/opentype/spec/math#mathkerninfo-table) states unambiguously about the index used for kern value as follows.
 > The kerning value corresponding to a particular height is determined by finding two consecutive entries in the correctionHeight array such that the given height is greater than or equal to the first entry and less than the second entry. The index of the second entry is used to look up a kerning value in the kernValues array. If the given height is less than the first entry in the correctionHeights array, the first kerning value (index 0) is used. For a height that is greater than or equal to the last entry in the correctionHeights array, the last entry is used.

Some test cases of [`test-ot-math.cc`](https://github.com/harfbuzz/harfbuzz/blob/5852d328a4b3c0064feb58d465f58c247ae1ad90/test/api/test-ot-math.c#L315) are evidently incorrect according to the spec above.

```cpp
  g_assert_cmpint(hb_ot_math_get_glyph_kerning (hb_font, glyph, HB_OT_MATH_KERN_TOP_RIGHT, 7), ==, 62); // lower than min height
  g_assert_cmpint(hb_ot_math_get_glyph_kerning (hb_font, glyph, HB_OT_MATH_KERN_TOP_RIGHT, 14), ==, 62); // equal to min height (should be 104)
  g_assert_cmpint(hb_ot_math_get_glyph_kerning (hb_font, glyph, HB_OT_MATH_KERN_TOP_RIGHT, 20), ==, 104);
```
```cpp
  g_assert_cmpint(hb_ot_math_get_glyph_kerning (hb_font, glyph, HB_OT_MATH_KERN_TOP_RIGHT, 86), ==, 398); // equal to max height (should be 440)
  g_assert_cmpint(hb_ot_math_get_glyph_kerning (hb_font, glyph, HB_OT_MATH_KERN_TOP_RIGHT, 91), ==, 440); // larger than max height
  g_assert_cmpint(hb_ot_math_get_glyph_kerning (hb_font, glyph, HB_OT_MATH_KERN_TOP_RIGHT, 96), ==, 440); // larger than max height
```

**Comment by khaledhosny** [comment]
cc @fred-wang
