### ISSUE TITLE
Compilation of 'harfbuzz' failed

### ISSUE THREAD

**Issue by nadyboy** [harfbuzz/harfbuzz#4557]
Error reported after executing the meson build command: meson. build: 217:56: ERROR: lexer

['cairo user font face set rendered color glyph fun ', {'deps': cairo dep}],

How to handle this issue? I used "harfbuzz-8.3.0. tar. gz" and the compilation environment is "ubuntu-18.04.5 desktop amd64"

**Comment by behdad** [comment]
What meson version are you using?

**Comment by nadyboy** [comment]
My "Mason" version is 0.45.1
