### ISSUE TITLE
HarfBuzz's `rand` implementation does not expose the seed

### ISSUE THREAD

**Issue by pontaoski** [harfbuzz/harfbuzz#4620]
(i've read https://github.com/harfbuzz/harfbuzz/pull/803 and https://github.com/harfbuzz/harfbuzz/issues/1155 for context)

Sitelen Pona has glyphs that are customarily written differently every time they are written (including in non-handwritten typefaces.) Many of the most popular Sitelen Pona typefaces (sitelen seli kiwen, linja lipamanka) take advantage of the `rand` feature in order to present random variants of these glyphs. HarfBuzz's current behaviour works decently enough, but is noticeably identical between lines (& other spans shaped and rendered separately). Exposing the random seed would allow tooling written with Sitelen Pona in mind to manually set the seed for each span, allowing these glyphs to be rendered as desired.

![grafik](https://github.com/harfbuzz/harfbuzz/assets/20326855/7ac4fe60-101f-4b78-9bd5-8f83585db755)
Example screenshot of the undesired behaviour.
The third and sixth glyphs on the first line and the third and seventh glyphs on the second line are what I am referring to here as having behaviour that is too deterministic.

**Comment by behdad** [comment]
Thanks. We were waiting for a user... I'll go ahead and add it.

**Comment by behdad** [comment]
Can you try the API in https://github.com/harfbuzz/harfbuzz/pull/4621 ?
