### ISSUE TITLE
build systems' glib and cairo version requirements outdated.

### ISSUE THREAD

**Issue by sezero** [harfbuzz/harfbuzz#4624]
configure.ac checks for glib-2.0 >= 2.19.1, but at least 2.30 is needed
for g_unicode_script_from_iso15924() and g_unicode_script_to_iso15924()
https://docs.gtk.org/glib/enum.UnicodeScript.html

configure.ac checks for cairo >= 1.8.0, but at least 1.10 is needed for
new cairo_operator_t members like CAIRO_OPERATOR_SCREEN:
https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t

It was super easy to fix those two in configure.ac: Feel free to apply:
```diff
diff --git a/configure.ac b/configure.ac
index 0d5b3d9..9a2b11d 100644
--- a/configure.ac
+++ b/configure.ac
@@ -132,7 +132,7 @@ AC_ARG_WITH(glib,
 			[Use glib @<:@default=auto@:>@])],,
 	[with_glib=auto])
 have_glib=false
-GLIB_DEPS="glib-2.0 >= 2.19.1"
+GLIB_DEPS="glib-2.0 >= 2.30"
 AC_SUBST(GLIB_DEPS)
 if test "x$with_glib" = "xyes" -o "x$with_glib" = "xauto"; then
 	PKG_CHECK_MODULES(GLIB, $GLIB_DEPS, have_glib=true, :)
@@ -193,7 +193,7 @@ AC_ARG_WITH(cairo,
 	[with_cairo=auto])
 have_cairo=false
 if test "x$with_cairo" = "xyes" -o "x$with_cairo" = "xauto"; then
-	PKG_CHECK_MODULES(CAIRO, cairo >= 1.8.0, have_cairo=true, :)
+	PKG_CHECK_MODULES(CAIRO, cairo >= 1.10, have_cairo=true, :)
 	save_libs=$LIBS
 	LIBS="$LIBS $CAIRO_LIBS"
 	AC_CHECK_FUNCS(cairo_user_font_face_set_render_color_glyph_func)
```

For meson: It doesn't check versions at all. It walks through a lot of
weirdness when a requirement isn't found, so I didn't touch it as I am
not proficient with it.

For cmake: It doesn't check versions at all. It is weirdly written, so
I didn't touch it as I am not very proficient with it..

**Comment by khaledhosny** [comment]
Looks good, please submit a PR.

**Comment by khaledhosny** [comment]
See also #4577
