### ISSUE TITLE
Packing of ItemVariationStore breaks GDEF table on InDesign CC2023

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#4636]
This is an odd one. I would not have believed it had I not debugged it myself.

This font ([remap.ttf.gz](https://github.com/harfbuzz/harfbuzz/files/14740341/remap.ttf.gz)), using the World-Ready Paragraph Composer in InDesign CC2023 looks like this:

<img width="490" alt="Screenshot 2024-03-25 at 07 41 04" src="https://github.com/harfbuzz/harfbuzz/assets/106728/5633128c-8c84-44b2-9325-97d07b25377c">

I perform the "no-op" subsetting:

```
hb-subset --gids=* --name-IDs=* --layout-features=* --keep-everything remap.ttf -o subset.ttf
```

Now it looks like this:

<img width="480" alt="Screenshot 2024-03-25 at 07 42 06" src="https://github.com/harfbuzz/harfbuzz/assets/106728/636e27c3-bceb-4963-acb7-780c0e1d8d3d">

The `head.checkSumAdjustment` value of `subset.ttf` is 0xac7885c.

However, I now run it through fontTools' ttx and back again:

```
$ ttx -o subset.ttx subset.ttf 2>/dev/null
$ ttx -o subset-2.ttf subset.ttx 2>/dev/null
```

subset-2.ttf looks like this:

<img width="478" alt="Screenshot 2024-03-25 at 07 43 26" src="https://github.com/harfbuzz/harfbuzz/assets/106728/fff4202e-978c-4407-8ca4-d7cce4b51e98">

The new `head.checkSumAdjustment` is 0xaf95e1ea. This is the only difference.

**Comment by simoncozens** [comment]
@anthrotype pointed out that the data is the same but there are other structural differences such as table order.

**Comment by anthrotype** [comment]
I suggest you recompile using `ttx -b --no-recalc-timestamp -o subset-2.ttf subset.ttx` to avoid spurious diffs coming from elsewhere. Then I confirm that only the checksumAdjustment appears to be different after round-tripping through ttx.

> there are other structural differences such as table order.

besides the table order that is different (but shouldn't be a problem in itself), I also see differences in the computed per-table checksums of only _some_ of the tables (but still same length...), among those the layout tables.
(Note in the diff below I have omitted the fourth "offsets" table of `ttx -l` to exclude table order from the comparison).

```diff
$ diff -u <(ttx -l subset.ttf) <(ttx -l subset-2.ttf) | colordiff
--- /dev/fd/63	2024-03-25 11:02:30
+++ /dev/fd/62	2024-03-25 11:02:30
@@ -1,24 +1,24 @@
-Listing table info for "subset.ttf":
+Listing table info for "subset-2.ttf":
     tag     checksum    length
     ----  ----------  --------
-    GDEF  0x649E3688       777
-    GPOS  0x35FCA02D     53698
-    GSUB  0x9B375396     58550
-    HVAR  0x0AEC3535      1492
+    GDEF  0x237B22AA       777
+    GPOS  0x031FC0A2     53698
+    GSUB  0x8C64700E     58550
+    HVAR  0x18A12229      1492
     OS/2  0x348A2872        96
     STAT  0xA1B678D4       122
     cmap  0xED24D1AF      1294
     fvar  0x7AFD699B        36
     gasp  0x00000010         8
     glyf  0xC6AFDD62    146322
-    gvar  0xCC0770D3    116240
+    gvar  0x53BD4E62    113336
     head  0x26A351E3        54
     hhea  0x08C607DE        36
     hmtx  0x10AB3DDE      5804
     loca  0x04E9AA8A      5808
     maxp  0x05C30116        32
     meta  0xFC0C0286       228
-    name  0xD0270035      1708
+    name  0xEB0F00C7      1708
     post  0xFA2BDE05     17439
     prep  0x68068C85         7
```

**Comment by anthrotype** [comment]
all in all, I doubt that hb-subset is computing "bad checksums", that's nothing fancy about computing checksums. The checksumAdjustment being different is simply a symptom of some other underlying difference in the table serialisation that is not visible at a TTX level, which must somehow be the root cause of the bug you're seeing in Indesign.

**Comment by jfkthame** [comment]
I'm not suggesting it's in any way definitive, but still.... does `ots-sanitize` (see https://github.com/khaledhosny/ots) have anything to report about the "suspect" version of the font? Or the MS font validator?

**Comment by anthrotype** [comment]
thanks for the suggestion. Apparently OTS looks fine with all three fonts, the original, the hb-subsetted one and the ttx roundtripped one as well. I get "File sanitized successfully!" in each case.

**Comment by anthrotype** [comment]
If we want to exclude the effect of table reordering, we can recompile the font with reorderTables=False so that fonttools keeps the same order in which hb-subset has serialized the font tables (although we can't do that from ttx itself, but using this simple python script):

```python
from fontTools.ttLib import TTFont
font = TTFont("/Users/clupo/Downloads/subset.ttf")
font.ensureDecompiled()
font.save("/Users/clupo/Downloads/subset-3.ttf", reorderTables=False)
```

Then the differences will only be within individual tables:

```diff
$ diff -u <(ttx -l subset.ttf) <(ttx -l subset-3.ttf) | colordiff
--- /dev/fd/63	2024-03-25 11:30:39
+++ /dev/fd/62	2024-03-25 11:30:39
@@ -1,24 +1,24 @@
-Listing table info for "subset.ttf":
+Listing table info for "subset-3.ttf":
     tag     checksum    length    offset
     ----  ----------  --------  --------
-    GDEF  0x649E3688       777       956
-    GPOS  0x35FCA02D     53698     35284
-    GSUB  0x9B375396     58550     88984
-    HVAR  0x0AEC3535      1492      3032
+    GDEF  0x237B22AA       777       956
+    GPOS  0x031FC0A2     53698     35284
+    GSUB  0x8C64700E     58550     88984
+    HVAR  0x18A12229      1492      3032
     OS/2  0x348A2872        96       508
     STAT  0xA1B678D4       122       604
     cmap  0xED24D1AF      1294      1736
     fvar  0x7AFD699B        36       380
     gasp  0x00000010         8       340
-    glyf  0xC6AFDD62    146322    263776
-    gvar  0xCC0770D3    116240    147536
-    head  0x26A351E3        54       452
+    glyf  0xC6B6DD62    146322    260872
+    gvar  0x53BD4E62    113336    147536
+    head  0x26A538FA        54       452
     hhea  0x08C607DE        36       416
     hmtx  0x10AB3DDE      5804      6232
     loca  0x04E9AA8A      5808     12036
     maxp  0x05C30116        32       348
     meta  0xFC0C0286       228       728
-    name  0xD0270035      1708      4524
+    name  0xEB0F00C7      1708      4524
     post  0xFA2BDE05     17439     17844
     prep  0x68068C85         7       332
```

I attached this font here, @simoncozens can you please check if this works in Indesign?
[subset-3.ttf.zip](https://github.com/harfbuzz/harfbuzz/files/14742786/subset-3.ttf.zip)

If this font does _not_ work in Indesign, whereas the one with the tables sorted like fonttools does work, then it may be it's actually the different table ordering that is causing the issue (i'd be very surprised).

**Comment by simoncozens** [comment]
subset-3 does work.

**Comment by simoncozens** [comment]
OK, here's something I'll try. Since it's a shaping error in the GSUB table, I'll just decompile and recompile that table.

**Comment by anthrotype** [comment]
> subset-3 does work.

ok then it should not be related to the table order.

> Since it's a shaping error in the GSUB table, I'll just decompile and recompile that table.

good idea

**Comment by simoncozens** [comment]
Loading and saving the `GDEF` table is enough to fix it.

**Comment by simoncozens** [comment]
My Rust fonttools can't parse the GDEF table of subset.ttf: `DeserializationError("End of file")`

**Comment by behdad** [comment]
> My Rust fonttools can't parse the GDEF table of subset.ttf: `DeserializationError("End of file")`

In the varStore?

**Comment by behdad** [comment]
cc @garretrieger

**Comment by simoncozens** [comment]
OK, we've done a bit more digging on this, and the answer seems to be that the Harfbuzz-packed version is packing the Item Variation Data before the Variation Region List, and (probably) Adobe assumes that it can keep reading the Item Variation Data until the end of the table.

**Comment by garretrieger** [comment]
We have the ability to force specific table ordering in harfbuzz. I'll see if I can make a patch that keeps the variation data at the end of GDEF and let's see if that fixes it. This seems quite similar to: https://github.com/harfbuzz/harfbuzz/commit/49c9392412ccf31cf948310acda057b96eb6afc6 where windows was depending on a specific ordering of sub tables

**Comment by garretrieger** [comment]
Can you build harfbuzz from this branch: https://github.com/googlefonts/harfbuzz/tree/gdef

 and then try running the font through and see if it works?

**Comment by simoncozens** [comment]
Yes, that now works, thank you!

**Comment by garretrieger** [comment]
Ok great, I'll finish that change up and get it PR'd
