### ISSUE TITLE
No clear summary of test results

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#4643]
After building harfbuzz 8.4.0 I ran `make check` which produced over 1500 lines of output with no clear summary at the end stating whether testing succeeded or failed.

**Comment by behdad** [comment]
Thank you. Our `make check` uses autotools testing system which doesn't have the nicest of reporting. But if it doesn't fail  it means that the tests pass. That said, I do get a report like this:
```

# TOTAL: 26
# PASS:  24
# SKIP:  1
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```
Our main build system these days (though, not the one we use for making releases), is the meson one, which has nicer test output.

That said, I ran the autotools test suite, and it failed on one test (`check-c-linkage-decls`) which I'm trying to fix.

**Comment by behdad** [comment]
Can you confirm please? It should pass now.

**Comment by ryandesign** [comment]
Yes I think tests pass; that's not the problem. The problem is the output doesn't make that clear.

When I test the latest code, it prints 165 lines of compilation and running tests and then:

```
============================================================================
Testsuite summary for HarfBuzz 8.4.0
============================================================================
# TOTAL: 26
# PASS:  26
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

and then an additional 132 lines of running tests and then:

```
============================================================================
Testsuite summary for HarfBuzz 8.4.0
============================================================================
# TOTAL: 63
# PASS:  63
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

and then an additional 82 lines of running tests and then:

```
============================================================================
Testsuite summary for HarfBuzz 8.4.0
============================================================================
# TOTAL: 78
# PASS:  76
# SKIP:  2
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

and then an additional 76 lines of running tests and then:

```
============================================================================
Testsuite summary for HarfBuzz 8.4.0
============================================================================
# TOTAL: 74
# PASS:  74
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

and then an additional 130 lines of running tests and then:

```
============================================================================
Testsuite summary for HarfBuzz 8.4.0
============================================================================
# TOTAL: 128
# PASS:  124
# SKIP:  4
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

and then an additional 12 lines of running tests and then:

```
============================================================================
Testsuite summary for HarfBuzz 8.4.0
============================================================================
# TOTAL: 6
# PASS:  0
# SKIP:  6
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

and then an additional 68 lines of running tests and then:

```
============================================================================
Testsuite summary for HarfBuzz 8.4.0
============================================================================
# TOTAL: 67
# PASS:  67
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

and then an additional 1080 lines of I don't know what.

Are those thousand lines after the final summary being printed just for fun or are they testing something? If the latter, why isn't a summary printed?

When I run the tests I don't want to have to scroll through thousands of lines of output trying to locate seven different summaries; there should be just one summary at the very end.

**Comment by behdad** [comment]
I understand your frustration.

We use recursive Makefile's which means each test suite gets run separately. The last lines seem to be the fuzzing test suite that simply crash if there's a failure.

Since the autotools build system is a deadend and we recommend meson, I'm not sure there's much we are going to do here.
