### ISSUE TITLE
Harfbuzz fails to compile using homebrew on Mac OS X 10.15

### ISSUE THREAD

**Issue by tobbi** [harfbuzz/harfbuzz#4660]
I'm trying to upgrade my HarfBuzz installation to the latest version. During building I keep getting the following very non-descript error:
`FAILED: src/HarfBuzz-0.0.gir`

Here's the complete build folder:
[harfbuzz-build-osx.zip](https://github.com/harfbuzz/harfbuzz/files/14964409/harfbuzz-build-osx.zip)
Log is in 02.meson

**Comment by lucasgelfond** [comment]
also have this problem, following

**Comment by khaledhosny** [comment]
From the log:
> Couldn't find include 'GObject-2.0.gir' (search path: '['/usr/local/Cellar/gobject-introspection/1.80.1/share/gir-1.0', '/private/tmp/harfbuzz-20240413-57808-ja79s2/harfbuzz-8.4.0/.brew_home/.local/share/gir-1.0', 'gir-1.0', '/usr/local/share/gir-1.0', '/usr/share/gir-1.0', '/usr/local/Cellar/gobject-introspection/1.80.1/share/gir-1.0', '/usr/local/Cellar/gobject-introspection/1.80.1/share/gir-1.0', '/usr/local/share/gir-1.0']')

Something is broken in your gobject-introspection installation.
