### ISSUE TITLE
The default glyph forms with vo=Tr in vertical texts

### ISSUE THREAD

**Issue by cheonhyeongsim** [harfbuzz/harfbuzz#4661]
I am now using Google Chrome 109.0.5414.168 and discovered this issue. I know that Google Chrome uses Harfbuzz as its shaping engine. If this issue has already been fixed in the newer version of Harfbuzz, please ignore my words here.

From http://www.unicode.org/reports/tr50/, we could know that, in vertical texts, the characters with a value Vertical_Orientation=Tr should be rotated 90 degrees clockwise as a fallback. That is, if we do not write anything in the OpenType `vert` feature, then a rotated glyph should be given, just the same as the characters with a value vo=R. But actually, Google Chrome show me an upright glyph for this kind of characters in default, which should be the behavior for the characters with a value vo=U or vo=Tu in principle.

Note that, when I proposed to add VS3 for Sibe form quotation marks, I also suggested to change their vo from R to Tr, and was agreed by the Script Encoding Working Group. If the issue I mentioned above still exists, then the quotation marks could not be shown as the expected glyphs in vertical texts, not only in Sibe texts, but also in English texts (if needed, for example a text mixing English and Chinese) and Chinese texts.

I used U+2329 `〈` and U+232A `〉` to test this issue. With vo=Tr and without any OpenType Layout, their default glyph form in vertical texts should be like `︿` and `﹀` but not `〈` and `〉`. Please check and fix this issue if possible.

**Comment by behdad** [comment]
HarfBuzz itself doesn't decide the orientation. The client (in this case Chrome) does. cc @drott @kojiishi

**Comment by cheonhyeongsim** [comment]
> HarfBuzz itself doesn't decide the orientation. The client (in this case Chrome) does.

Thank you for your quick reply. Could I ask where I should propose this issue to?

**Comment by behdad** [comment]
> > HarfBuzz itself doesn't decide the orientation. The client (in this case Chrome) does.
> 
> Thank you for your quick reply. Could I ask where I should propose this issue to?

https://issues.chromium.org/issues

**Comment by behdad** [comment]
Please paste the issue URL here when you file.

**Comment by cheonhyeongsim** [comment]
> Please paste the issue URL here when you file.

https://issues.chromium.org/issues/334110491

Thank you very much, I have already posted this issue to Chrome.
