### ISSUE TITLE
ZWJ failed to be ligated in vertical texts

### ISSUE THREAD

**Issue by cheonhyeongsim** [harfbuzz/harfbuzz#4662]
I am now using Google Chrome 109.0.5414.168 and discovered this issue. I know that Google Chrome uses Harfbuzz as its shaping engine. If this issue has already been fixed in the newer version of Harfbuzz, please ignore my words here.

I discovered that, ZWJ (U+200D) could not be ligated with the characters with upright glyphs in vertical texts. For example, in my font, the sequence `こ ZWJ と` could be ligated as a single glyph (koto-ligature). In horizontal texts, it works well, however in vertical texts, it does not work.

Also, ZWJ is useful in Emoji sequences, and the Emoji characters have the value Vertical_Orientation=U, which should be shown as upright glyphs in vertical texts. Then, the Emoji sequences may also fail to ligate.

I would guess that maybe this is not an issue solely related to ZWJ, but all the characters with a rotated glyph could not be ligated with a upright glyph in vertical texts.

In #4661, Behdad Esfahbod told me that that issue is not a Harfbuzz issue but a Chrome issue. I would also like to ask whether this issue is a Harfbuzz issue or a Chrome issue. If it is a Harfbuzz issue, please check and fix it; or please notice me and I will post this issue to the Chrome issue registry. Thanks very much!

**Comment by behdad** [comment]
I think this is also an itemization issue. Ie. Chrome is assigning rotated orientation to ZWJ hence breaking the run. I might be wrong. Can you try with `hb-view` or `hb-shape`?

cc @drott @kojiishi

**Comment by cheonhyeongsim** [comment]
> Can you try with `hb-view` or `hb-shape`?

Sorry but, I would like to know that how I could try with `hb-view` or `hb-shape` in *vertical texts*?

**Comment by behdad** [comment]
Just pass `--direction ttb` to them.

**Comment by cheonhyeongsim** [comment]
It works well on hb-shape. So you mean that the rotation done by Chrome prevents the running of the OpenType features?

https://issues.chromium.org/issues/334110492

**Comment by behdad** [comment]
> It works well on hb-shape. So you mean that the rotation done by Chrome prevents the running of the OpenType features?

Yes. Because they end up passed to HarfBuzz separately.

**Comment by khaledhosny** [comment]
It is a text segmentation issue.
