### ISSUE TITLE
Drop autotools build

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#4720]
We should drop it in the next major release. We don’t actively use it, and it is starting to be a maintenance burden.

**Comment by alerque** [comment]
I don't think "we don't actively use it" is quite accurate yet. One could wish, but..

The issue as I see it is that there a lot of distros stuck on decrepitly old versions of meson—older than the minimum supported version of Meson for Harfbuzz's build. Some of these distros have newer versions of Harfbuzz than Meson would otherwise allow them to have because the autotools builds are not limited to the autotools on the target system because the source distribution is batteries included. Given that Harfbuzz has a lovely track record of not breaking backwards compatibility is isn't uncommon to build and stuff a relatively new Harfbuzz into an otherwise aging distro release.

The most egregious examples I know of is the Amazon Linux build that sadly powers way more cloud computing things than it's prowess as a distro deserves. It's Meson is locked to 0.46.1 for ... reasons. It's Harfbuzz is fresher than that, but still a whole bushel of major versions behind.

Ubuntu is in a similar boat with their LTS releases, although now that Bionic has entered the final phase and is only an "extended" support not LTS standard support mode this is much less of an issue.

The situtation with distros and Meson has improved dramatically in the last couple years since I last made this argument in relation to HarfBuzz. CentOS and many others used to be in this boat too. Moste of the ones that still are are of diminishing value.

With autotools based source distributions it is trivial to rebuild a fresh Harfbuzz on the most delinquent system. Updating Meson on the other hand is a full fledged nightmare on these systems because of Python and other ecosystem blockages. Having to update Meson just to build Harfbuzz in a way that matches the system is a huge amount of friction by comparison.

**Comment by behdad** [comment]
Let's drop it at the same time we decide c++14 is kosher. That said, c++14 doesn't really bring many features we like to use.

My benchmark has been the oldest supported RHEL. But we know people still use gcc 4.9, so I'm a bit hesitant to remove it at this time as well.

**Comment by khaledhosny** [comment]
I compared https://repology.org/project/harfbuzz/versions with https://repology.org/project/meson/versions and I couldn’t find a distribution that has harfbuzz > 4 and meson < 0.55.0, so distributions that are likely to ever update to latest harfbuzz already have newer enough meson to build it.

**Comment by alerque** [comment]
If the distros (particularly ones with versioned releases) haven't updated already for the most part they never will. We're in agreement there. Ubuntu Bionic or Amazon Linux 1 are never getting HarfBuzz 2, much less 8.

The issues is that folks saddled with whatever project demands they run on whatever relic of a system their enterprise is stuck on do (sometimes) have the option of building using a newer version of Harfbuzz, even if it is in user-land or project scoped. A fresh user build version can pretty easily be used to override the libraries used for a specific project. That's the scenario where it is important that the *build tooling* available on these decrepit distros be able to build fresh libraries for their own use.

**Comment by khaledhosny** [comment]
Latest meson is `pip install meson` away, so I’m not convinced it is a major hurdle. One can even build HarfBuzz with only a C++ compiler: `c++ --std=c++11 -shared -o libharfbuzz.so src/harfbuzz.cc`.

Otherwise the line of argument here means we can never drop autotools build, because there will always be someone somewhere using some ancient enterprise Linux system that is supported for two centuries and never gets any new versions of anything. If we are never going to drop autotools, why did we introduce meson then? Autotools was good enough for building HarfBuzz and we had no issues with.

**Comment by debohman** [comment]
Note that ICU-75 requires c++17.

**Comment by behdad** [comment]
Let's do this finally...

**Comment by kberry** [comment]
Khaled, Behdad, anyone - I guess it's too late, but the TeX Live build entirely relies on automake/autoconf. harfbuzz is linked into the XeTeX and LuaTeX engines. I know of no feasible way to combine build systems, and also, I strongly suspect that some of the (intentionally older) systems we build on do not support the meson versions you need. So this decision has killed use of harfbuzz in the TeX world. Which I guess you don't especially care about, since harfbuzz is used so much more widely, but it is quite sad for us.

I guess my only recourse is to try to revive/maintain the autotools support myself. I don't know if that will be feasible. It is certainly painful to have to spend a lot of time, in perpetuity, merely to stand in the same place.

If you have any other ideas for continuing harfbuzz in TeX, please let me know.
(karl at freefriends dot org, as you both already know : ).

**Comment by khaledhosny** [comment]
I was under the impression that TeX Live does not use HarfBuzz’s build system. It has its own, independent [`configure.ac`](https://github.com/TeX-Live/texlive-source/blob/trunk/libs/harfbuzz/configure.ac), [`Makefile.am`](https://github.com/TeX-Live/texlive-source/blob/trunk/libs/harfbuzz/Makefile.am), etc, so it shouldn’t be affected by this change.

**Comment by kberry** [comment]
Hi Khaled. It's true that we don't directly run the harfbuzz-provided
configure to configure TL -- but the TL build of harfbuzz is not
independent in terms of maintenance. That is, TL's harfbuzz/configure.ac
and Makefile.am are entirely based on harfbuzz's configure.ac and
Makefile.am. We use the original harfbuzz source tree (in the
harfbuzz-src/ subdir).

So when things change (source files, dependencies, whatever) inside
harfbuzz, with autotools support dropped now, there's nothing
straightforward we can look at to discern how to update our autofiles.

BTW, that's why we haven't yet updated to 9.0.0 in the TL source
tree. The person who usually does those updates (Akira) didn't have new
autofiles to compare against. --thanks, karl.

**Comment by khaledhosny** [comment]
I don’t thin checking `meson.build` files for changes between releases is significantly harder than checking `configure.ac`/`Makefile.am`. For example, the [diff of the top level `meson.build` file](https://github.com/harfbuzz/harfbuzz/compare/8.5.0...9.0.0#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4) in the last release shows some changes to how FreeType is checked for, which shouldn’t concern TL (in general it is very unlikely that the core HarfBuzz library is getting any new dependencies, so TL should not be concerned about dependencies at all, other than libgraphite2 it already handles), and setting `-std=c++17` when building with newer ICU, but nothing else. In [`src/meson.build`](https://github.com/harfbuzz/harfbuzz/compare/8.5.0...9.0.0#diff-f28598af2e23aa5d2bc7c72e022ae2c56a33802eb970afffaeca1e40607f97fe) few new files are added to the library sources, so TL’s `Makefile.am` will need to do the same. Changes to other `meson.build` files, if any, should not concern TL build.

**Comment by kberry** [comment]
Thanks much for the info and review, Khaled. We'll give it a shot. -k

**Comment by ebraminio** [comment]
Maybe amalgam harfbuzz.cc can be helpful here also similar to https://patch-diff.githubusercontent.com/raw/harfbuzz/uharfbuzz/pull/48.patch 

I applied the following and it seemed to work for me, that makes you free for maintaining the files list at least,

```
diff --git a/libs/harfbuzz/Makefile.am b/libs/harfbuzz/Makefile.am
index 667ba16a..9b919821 100644
--- a/libs/harfbuzz/Makefile.am
+++ b/libs/harfbuzz/Makefile.am
@@ -33,297 +33,11 @@ AM_CPPFLAGS = -DHB_NO_MT -DHAVE_FALLBACK=1 \
 AM_CXXFLAGS = $(VISIBILITY_CXXFLAGS) $(WARNING_CXXFLAGS)
 
 libharfbuzz_dependencies =
-libharfbuzz_a_SOURCES =  \
-	@HARFBUZZ_TREE@/src/hb-algs.hh \
-	@HARFBUZZ_TREE@/src/hb-atomic.hh \
-	@HARFBUZZ_TREE@/src/hb-bimap.hh \
-	@HARFBUZZ_TREE@/src/hb-bit-page.hh \
-	@HARFBUZZ_TREE@/src/hb-bit-set-invertible.hh \
-	@HARFBUZZ_TREE@/src/hb-bit-set.hh \
-	@HARFBUZZ_TREE@/src/hb-blob.hh \
-	@HARFBUZZ_TREE@/src/hb-blob.cc \
-	@HARFBUZZ_TREE@/src/hb-buffer.hh \
-	@HARFBUZZ_TREE@/src/hb-buffer-serialize.cc \
-	@HARFBUZZ_TREE@/src/hb-buffer-verify.cc \
-	@HARFBUZZ_TREE@/src/hb-buffer.cc \
-	@HARFBUZZ_TREE@/src/hb-cache.hh \
-	@HARFBUZZ_TREE@/src/hb-cplusplus.hh \
-	@HARFBUZZ_TREE@/src/hb-cff-interp-common.hh \
-	@HARFBUZZ_TREE@/src/hb-cff-interp-cs-common.hh \
-	@HARFBUZZ_TREE@/src/hb-cff-interp-dict-common.hh \
-	@HARFBUZZ_TREE@/src/hb-cff1-interp-cs.hh \
-	@HARFBUZZ_TREE@/src/hb-cff2-interp-cs.hh \
-	@HARFBUZZ_TREE@/src/hb-common.cc \
-	@HARFBUZZ_TREE@/src/hb-config.hh \
-	@HARFBUZZ_TREE@/src/hb-debug.hh \
-	@HARFBUZZ_TREE@/src/hb-dispatch.hh \
-	@HARFBUZZ_TREE@/src/hb-draw.cc \
-	@HARFBUZZ_TREE@/src/hb-draw.hh \
-	@HARFBUZZ_TREE@/src/hb-face-builder.cc \
-	@HARFBUZZ_TREE@/src/hb-face.hh \
-	@HARFBUZZ_TREE@/src/hb-face.cc \
-	@HARFBUZZ_TREE@/src/hb-font.hh \
-	@HARFBUZZ_TREE@/src/hb-font.cc \
-	@HARFBUZZ_TREE@/src/hb-iter.hh \
-	@HARFBUZZ_TREE@/src/hb-kern.hh \
-	@HARFBUZZ_TREE@/src/hb-limits.hh \
-	@HARFBUZZ_TREE@/src/hb-map.hh \
-	@HARFBUZZ_TREE@/src/hb-map.cc \
-	@HARFBUZZ_TREE@/src/hb-machinery.hh \
-	@HARFBUZZ_TREE@/src/hb-meta.hh \
-	@HARFBUZZ_TREE@/src/hb-ms-feature-ranges.hh \
-	@HARFBUZZ_TREE@/src/hb-mutex.hh \
-	@HARFBUZZ_TREE@/src/hb-null.hh \
-	@HARFBUZZ_TREE@/src/hb-number-parser.hh \
-	@HARFBUZZ_TREE@/src/hb-number.cc \
-	@HARFBUZZ_TREE@/src/hb-number.hh \
-	@HARFBUZZ_TREE@/src/hb-object.hh \
-	@HARFBUZZ_TREE@/src/hb-open-file.hh \
-	@HARFBUZZ_TREE@/src/hb-open-type.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-cff-common.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-cff1-std-str.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-cff1-table.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-cff1-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-cff2-table.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-cff2-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-gasp-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-cmap-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-face.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-face.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-face-table-list.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-glyf-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-hdmx-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-head-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-hhea-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-hmtx-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-kern-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-maxp-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-name-language-static.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-name-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-stat-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-name-language.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-name.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-os2-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-os2-unicode-ranges.hh \
-	@HARFBUZZ_TREE@/src/hb-pool.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-post-macroman.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-post-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-post-table-v2subset.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-tag.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-tag-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-var-common.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-var-cvar-table.hh \
-	@HARFBUZZ_TREE@/src/hb-outline.cc \
-	@HARFBUZZ_TREE@/src/hb-outline.hh \
-	@HARFBUZZ_TREE@/src/hb-paint-extents.cc \
-	@HARFBUZZ_TREE@/src/hb-paint-extents.hh \
-	@HARFBUZZ_TREE@/src/hb-paint.cc \
-	@HARFBUZZ_TREE@/src/hb-paint.hh \
-	@HARFBUZZ_TREE@/src/hb-sanitize.hh \
-	@HARFBUZZ_TREE@/src/hb-serialize.hh \
-	@HARFBUZZ_TREE@/src/hb-set-digest.hh \
-	@HARFBUZZ_TREE@/src/hb-set.hh \
-	@HARFBUZZ_TREE@/src/hb-set.cc \
-	@HARFBUZZ_TREE@/src/hb-shape.cc \
-	@HARFBUZZ_TREE@/src/hb-shape-plan.hh \
-	@HARFBUZZ_TREE@/src/hb-shape-plan.cc \
-	@HARFBUZZ_TREE@/src/hb-shaper-list.hh \
-	@HARFBUZZ_TREE@/src/hb-shaper-impl.hh \
-	@HARFBUZZ_TREE@/src/hb-shaper.hh \
-	@HARFBUZZ_TREE@/src/hb-shaper.cc \
-	@HARFBUZZ_TREE@/src/hb-static.cc \
-	@HARFBUZZ_TREE@/src/hb-string-array.hh \
-	@HARFBUZZ_TREE@/src/hb-style.cc \
-	@HARFBUZZ_TREE@/src/hb-subset-accelerator.hh \
-	@HARFBUZZ_TREE@/src/hb-subset-cff-common.cc \
-	@HARFBUZZ_TREE@/src/hb-subset-cff-common.hh \
-	@HARFBUZZ_TREE@/src/hb-subset-cff1.cc \
-	@HARFBUZZ_TREE@/src/hb-subset-cff2.cc \
-	@HARFBUZZ_TREE@/src/hb-subset-input.hh \
-	@HARFBUZZ_TREE@/src/hb-subset-instancer-iup.cc \
-	@HARFBUZZ_TREE@/src/hb-subset-instancer-iup.hh \
-	@HARFBUZZ_TREE@/src/hb-subset-instancer-solver.cc \
-	@HARFBUZZ_TREE@/src/hb-subset-instancer-solver.hh \
-	@HARFBUZZ_TREE@/src/hb-subset.hh \
-	@HARFBUZZ_TREE@/src/hb-ucd-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ucd.cc \
-	@HARFBUZZ_TREE@/src/hb-unicode.hh \
-	@HARFBUZZ_TREE@/src/hb-unicode.cc \
-	@HARFBUZZ_TREE@/src/hb-unicode-emoji-table.hh \
-	@HARFBUZZ_TREE@/src/hb-vector.hh \
-	@HARFBUZZ_TREE@/src/hb-utf.hh \
-	@HARFBUZZ_TREE@/src/hb-buffer-deserialize-json.hh \
-	@HARFBUZZ_TREE@/src/hb-buffer-deserialize-text-glyphs.hh \
-	@HARFBUZZ_TREE@/src/hb-buffer-deserialize-text-unicode.hh \
-	@HARFBUZZ_TREE@/src/hb-fallback-shape.cc \
-	@HARFBUZZ_TREE@/src/hb.hh
-
-## native OpenType Layout backend
-libharfbuzz_a_SOURCES += \
-	@HARFBUZZ_TREE@/src/hb-aat-layout.cc \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-common.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-ankr-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-bsln-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-feat-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-just-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-kerx-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-morx-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-opbd-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout-trak-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-layout.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-ltag-table.hh \
-	@HARFBUZZ_TREE@/src/hb-aat-map.cc \
-	@HARFBUZZ_TREE@/src/hb-aat-map.hh \
-	@HARFBUZZ_TREE@/src/hb-array.hh \
-	@HARFBUZZ_TREE@/src/hb-multimap.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-font.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-layout.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-layout-base-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-layout-common.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-layout-gdef-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-layout-gpos-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-layout-gsubgpos.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-layout-gsub-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-layout-jstf-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-layout.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-color.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-map.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-map.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-math.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-math-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-meta-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-meta.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-metrics.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-metrics.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shape.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-arabic-fallback.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-arabic-joining-list.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-arabic-pua.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-arabic-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-arabic-win1256.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-arabic.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-arabic.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-default.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-hangul.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-hebrew.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-indic-machine.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-indic-table.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-indic.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-indic.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-khmer-machine.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-khmer.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-myanmar-machine.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-myanmar.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-syllabic.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-syllabic.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-thai.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-use-machine.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-use-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-use.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-vowel-constraints.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper-vowel-constraints.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shaper.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shape-normalize.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shape-normalize.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shape-fallback.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-shape-fallback.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-shape.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-var.cc \
-	@HARFBUZZ_TREE@/src/hb-ot-var-avar-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-var-fvar-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-var-gvar-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-var-hvar-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-var-mvar-table.hh \
-	@HARFBUZZ_TREE@/src/hb-ot-vorg-table.hh
-##
-libharfbuzz_a_SOURCES += \
-	@HARFBUZZ_TREE@/src/OT/Color/CBDT/CBDT.hh \
-	@HARFBUZZ_TREE@/src/OT/Color/COLR/COLR.hh \
-	@HARFBUZZ_TREE@/src/OT/Color/COLR/colrv1-closure.hh \
-	@HARFBUZZ_TREE@/src/OT/Color/CPAL/CPAL.hh \
-	@HARFBUZZ_TREE@/src/OT/Color/sbix/sbix.hh \
-	@HARFBUZZ_TREE@/src/OT/Color/svg/svg.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/glyf.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/glyf-helpers.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/loca.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/path-builder.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/Glyph.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/GlyphHeader.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/SimpleGlyph.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/CompositeGlyph.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/SubsetGlyph.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/VarCompositeGlyph.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/composite-iter.hh \
-	@HARFBUZZ_TREE@/src/OT/glyf/coord-setter.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/Common/Coverage.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/Common/CoverageFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/Common/CoverageFormat2.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/Common/RangeRecord.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GDEF/GDEF.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/Common.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/Sequence.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/SingleSubstFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/SingleSubstFormat2.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/SingleSubst.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/MultipleSubstFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/MultipleSubst.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/AlternateSubstFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/AlternateSubst.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/AlternateSet.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/LigatureSubstFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/LigatureSubst.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/LigatureSet.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/Ligature.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/ReverseChainSingleSubst.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/ReverseChainSingleSubstFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/ContextSubst.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/ChainContextSubst.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/ExtensionSubst.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/SubstLookupSubTable.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/SubstLookup.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GSUB/GSUB.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/AnchorFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/AnchorFormat2.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/AnchorFormat3.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/Anchor.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/AnchorMatrix.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/ChainContextPos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/Common.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/ContextPos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/CursivePosFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/CursivePos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/ExtensionPos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/GPOS.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/LigatureArray.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/MarkArray.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/MarkBasePosFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/MarkBasePos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/MarkLigPosFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/MarkLigPos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/MarkMarkPosFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/MarkMarkPos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/MarkRecord.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/PairPosFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/PairPosFormat2.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/PairPos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/PairSet.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/PairValueRecord.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/PosLookup.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/PosLookupSubTable.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/SinglePosFormat1.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/SinglePosFormat2.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/SinglePos.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/GPOS/ValueFormat.hh \
-	@HARFBUZZ_TREE@/src/OT/name/name.hh \
-	@HARFBUZZ_TREE@/src/OT/Layout/types.hh \
-	@HARFBUZZ_TREE@/src/graph/graph.hh \
-	@HARFBUZZ_TREE@/src/graph/serialize.hh
-
+libharfbuzz_a_SOURCES += @HARFBUZZ_TREE@/src/harfbuzz.cc
 
 ## Graphite library
 AM_CPPFLAGS += $(GRAPHITE2_INCLUDES)
 libharfbuzz_dependencies += $(GRAPHITE2_DEPEND)
-libharfbuzz_a_SOURCES += @HARFBUZZ_TREE@/src/hb-graphite2.cc
 
 $(libharfbuzz_a_OBJECTS): config.force
 
```

**Comment by kberry** [comment]
> Maybe amalgam harfbuzz.cc can be helpful here also similar to

Thank you!

**Comment by behdad** [comment]
Hi Karl. Glad we could help. Just came here to say that we care a lot about each and every HB client. And TeX has a special place in both my and Khaled's hearts.

**Comment by kberry** [comment]
Thank you Behdad, Khaled, and ebraminio! I greatly appreciate the
replies and help.

We applied ebraminio's patch to use the amalgam .cc and so far so good.
That will simplify maintenance in TL for sure.

By the way, if you'd ever like to write an article about harfbuzz for
TUGboat, that would be most welcome. Not necessarily anything TeX
specific or deeply technical (though it could be), I was imagining a
sort of overview, history, major challenges so far, future plans ...
(https://tug.org/TUGboat/location.html has a template and info, if
you're interested.)

Happy harfbuzzing,
Karl

**Comment by behdad** [comment]
> By the way, if you'd ever like to write an article about harfbuzz for TUGboat, that would be most welcome.

Oh I'm totally going to take that offer! Thank you Karl.
