### ISSUE TITLE
hb-view fails to render (composite) glyph that Font Book and TextEdit can show.

### ISSUE THREAD

**Issue by drj11** [harfbuzz/harfbuzz#4752]
Several glyphs from my font here https://gitlab.com/drj11/font-pjw/-/tree/main/fonts/ttf fail to render in `hb-view`. Specifically the rendering is blank.

The font is made from my own UFO using `fontmake`, so it's entirely possible that there is something suspect about the font. But it renders fine in Firefox (macOS), TextEdit, Font Book, and probably others.

It renders fine in Wakamai Fondue (thanks Roel Nieskens)

Two of the problematic glyphs are `/H` and `/W` (although i originally discovered the problem with U+2400 aka `/uni2400`)

Rendering in macOS Firefox:

![image](https://github.com/harfbuzz/harfbuzz/assets/1215412/f214f9b2-75bd-48b2-a1cf-17f20ba925f3)

Rendering in `hb-view`

    hb-view --font-size 143 fonts/ttf/PJW.ttf HELLOWORLD

![HW](https://github.com/harfbuzz/harfbuzz/assets/1215412/a9b49433-9b8c-4977-93dd-98efb744fe5c)

    ; hb-view --version
    hb-view (HarfBuzz) 8.5.0
    Available shapers: graphite2,ot,coretext,fallback

Some fun and possibly relevant facts:
- The font is made from UFO (not in the repo, but i can supply if needed) using `fontmake`.
- All glyphs are pixel constructed using positioned references to the `/_pixel` component (except for `/.notdef` and `/_pixel`)
- `/_pixel` has a large number of nodes (> 1,000 in the UFO) and an earlier version of the font had a glyph that exceeded the maximum value for the `maxCompositePoints` field in the `maxp` table (i deleted that glyph).

List of glyphs that fail (that i spotted, might have missed some):

`/dollar` `/eight` `/B` `/H` `/W` `/g` `/currency` `/sterling` `/section` `/registered` `/mu` `/Eth` `/Oslash` `/germandbls` `/eth` `/udieresis` `/thorn` `/uni2400` (plus some others above U+00FF that i don't care about so much)

These are definitely enriched for glyphs that have high pixel counts (and therefore a large number of nodes in the decomposed graphic), but others have high pixel counts and seem to render fine, so that's not the whole story.

While i was writing this i remembered that thanks to another rendering bug, i had `HB_DRAW=0` set in my environment. But unsetting it makes the rendering even worse:

    ; env - /usr/local/bin/hb-view --font-file fonts/ttf/PJW.ttf HELLO-WORLD

![HW-noenv](https://github.com/harfbuzz/harfbuzz/assets/1215412/e90f5638-439c-41e8-a41f-945f1f2c9dc5)

**Comment by behdad** [comment]
It is indeed limit on number of points. If I increase `HB_GLYF_MAX_POINTS` in `hb-limits.hh` then it works.

**Comment by behdad** [comment]
I made it ten times more. At 200,000 points per glyph, that should be enough for a while. :)

**Comment by drj11** [comment]
And certainly enough for any TTF file that has `maxCompositePoints` correctly set (because the maximum for that value is 65,535).

**Comment by drj11** [comment]
And many thanks for looking into this so promptly, thought i was seeing things tbh.

**Comment by behdad** [comment]
You're welcome. Thanks for the report.

Since HB_DRAW=0 is also buggy, we might need to report this to FreeType as well.

**Comment by behdad** [comment]
@lemzwerg

**Comment by apodtele** [comment]
If this is not https://gitlab.freedesktop.org/freetype/freetype/-/issues/1269 , which is recently fixed, please confirm it using ftview with FreeType HEAD. Then report it to us.

**Comment by lemzwerg** [comment]
I can confirm the problem.  With a development build from git HEAD I get

```
> ftview -f 21 20 PJW.ttf 
FreeType Glyph Viewer - press ? for help
[pressing 'q' key to exit]
Execution completed successfully.
Fail count = 23, Error code = 0x0A (array allocation size too large)
```

and glyph 21 doesn't get displayed.

**Comment by apodtele** [comment]
Give that endPtsOfContours[numberOfContours] is _uint16_, a simple glyph can only have 65536 points. A composite glyph does  not have any limits, but FreeType uses _short_. I am afraid this cannot be easily changed.

There must e incredible detail in those little portraits if those limits are reached. Even if only for the sake of memory use on other systems, can those details be toned down a little?

**Comment by drj11** [comment]
A composite glyph doesn't have any _intrinsic_ limit, but the `maxp` table has a `maxCompositePoints` field, which is a _uint16_; which is the same limit as a simpl glyph. So if `maxCompositePoints` is correctly set, then a composite glyph also has the same limit. And it seems reasonable to reject rendering of composite glyphs that exceed `maxCompositePoints`.

**Comment by lemzwerg** [comment]
It probably makes sense in FreeType to test in advance whether the `maxCompositePoints` limit is reached.  Right now, using the test font is awkard in the FreeType demo programs because it takes a lot of time until FreeType gives up, causing very sluggish behaviour.

**Comment by drj11** [comment]
and just to reiterate, this font doesn't have any glyphs that exceed the `maxCompositePoints` field (or if it does, that's a bug in `fontmake`).

**Comment by drj11** [comment]
oh wait, i just realised that @apodtele said FreeType uses a _short_; that is, a _signed short_; that is typically has a max representable positive integer of 32767. lol. Yes, that would definitely be a problem.

**Comment by apodtele** [comment]
Aha. I think we can actually proceed to _unsigned short_ n_points in FT_Outline. This should not be a huge compatibility issue. Just a release note warning would be sufficient.

**Comment by apodtele** [comment]
The proposed fix is above and [here](https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/330). Please check and comment if you compiler complains about it.
