### ISSUE TITLE
Build with vcpkg / MSVCC fails

### ISSUE THREAD

**Issue by tksharpless** [harfbuzz/harfbuzz#4787]
Trying to  build COLMAP for Windows x64 with vcpkg/MSVC 20017.  One of the zillion dependencies is harfbuzz, and its build is crashing. The problem is a  slew of compile errors indicating an improperly declared class "Condition".  Some snooping in the source suggests the  cause may be an incorrect header include sequence.
If anyone here maintains the vcpkg port, please  look into this.

**Comment by khaledhosny** [comment]
Please report vcpkg build issues to [vcpkg repository](https://github.com/microsoft/vcpkg/).

**Comment by tksharpless** [comment]
I have indeed reported this as a vcpkg issue; just thought you might be
interested.


‪On Sun, Jul 7, 2024 at 8:29 AM ‫خالد حسني (Khaled Hosny)‬‎ <
***@***.***> wrote:‬

**Comment by alerque** [comment]
https://github.com/microsoft/vcpkg/issues/39737
