### ISSUE TITLE
Mirrored ligatures not being substituted in RTL runic text

### ISSUE THREAD

**Issue by babelstone** [harfbuzz/harfbuzz#481]
Runic text may include "bind runes" which are ligatures of two or three rune letters. These are optional ligatures, and so are represented as ZWJ sequences (e.g. the ER bind rune is represented as 16D6 200D 16B1). Runic text may also be laid out RTL, in which case the rune letters are mirrored. My Runic fonts support both rune ligatures (using ccmp feature) and mirrored rune letters in RTL context (using rtlm feature). My fonts also supports mirrored forms of ligatures.

Using the test font and test page listed below, it can be seen that in Firefox ligatures and mirrored letterforms separately work as expected, but mirrored ligatures in RTL runic text do not work (they are displayed as separate mirrored letterforms). I am not sure what order the OT features are applied, but I have added two different substitutions for mirrored ligatures to allow for different possibilities. I have experimented with various different substitution routes, but have been unable to get mirrored ligatures to work, so think this may be an issue with harfbuzz.

Test font: http://www.babelstone.co.uk/Fonts/BabelStoneRunicBerhtwald.ttf (please use this rather than the released version of my BabelStone Runic Berhtwald font)

Test page: http://www.babelstone.co.uk/Fonts/BindRunesTest.html

**Comment by behdad** [comment]
Ok, I see Runic can be written in both directions.  I can change HB to work that way for this script.  But if you have rules for both directions, you *should* get what you want already.  Needs debugging, I'll get to it some time...

Humm. Try using rtla instead of rtlm.  I think rtla is more appropriate.

**Comment by babelstone** [comment]
Hi Behdad,

Thanks for the response. HB is already working correctly for LTR and RTL runs of Runic text, except for the one case of ligatures in RTL runs, so I don't think you need to change the way HB works. I am not sure whether the RTL ligatures issue is a problem with HB or a problem with my font, so any advice on what HB expects would be welcome. In particular, can you let me know in which order HB applies the ccmp and rtla/rtlm features, i.e. whether ligaturing or glyph-mirroring is done first, so I can order my glyph substitutions accordingly.

I originally used rtla for glyph mirroring in the first version of my fonts, but Peter Constable advised me to use rtlm for mirroring the glyphs, and then use rtla for any "final finessing" (possibly contextual) of the mirrored glyphs, so I changed my fonts to use the rtlm feature. Does that make sense to you?

**Comment by behdad** [comment]
> what HB expects would be welcome. In particular, can you let me know in which order HB applies the ccmp and rtla/rtlm features, i.e. whether ligaturing or glyph-mirroring is done first, so I can order my glyph substitutions accordingly.

If you pass Runic RTL text, HarfBuzz first flips it to become LTR, then applies glyph-mirroring, then lookups, and flip it all back at the end.  You can pass --trace to hb-shape to see.

> I originally used rtla for glyph mirroring in the first version of my fonts, but Peter Constable advised me to use rtlm for mirroring the glyphs, and then use rtla for any "final finessing" (possibly contextual) of the mirrored glyphs, so I changed my fonts to use the rtlm feature. Does that make sense to you?

That's correct advice.
