### ISSUE TITLE
SVG output displays very badly in Firefox

### ISSUE THREAD

**Issue by drj11** [harfbuzz/harfbuzz#4811]
Version info

```
; hb-view --version
hb-view (HarfBuzz) 8.5.0
Available shapers: graphite2,ot,coretext,fallback
```

(from brew, i think)

Using `hb-view` to output SVG, the SVG shows fine in most things, but is completely messed up in Firefox. Obviously i think there's a good chance that Firefox is wrong, but it may be easier to do the actual fix in harfbuzz. I guess it's all that fancy composite filter stuff.

```
hb-view --background=999 --foreground=555 --output-file=Dolphin.svg CraftyGirls-Regular.ttf Dolphin
```

Produces the file Dolphin.svg, attached.

![Dolphin](https://github.com/user-attachments/assets/7a218372-9168-48dc-9e9c-9f84f811ebe5)

Which looks okay in Inkscape

<img width="703" alt="image" src="https://github.com/user-attachments/assets/034d3f9c-e8d0-45d4-96c0-fc2422312489">

But is completely messed up in Firefox:

<img width="703" alt="image" src="https://github.com/user-attachments/assets/011f5db2-63c1-4eb9-9cfe-9c524cbd3fb0">

**Comment by jfkthame** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1909838 to report this as a Firefox bug (but it might still be desirable to adjust the hb-view SVG output to work around it somehow, if that's feasible).

**Comment by khaledhosny** [comment]
SVG output comes from cairo. If there is an issue here it would be in cairo (or may be in the particular way hb-draw uses cairo, user fonts I think, which is probably less tested).

**Comment by khaledhosny** [comment]
Or may be not, if this is a color font, then hb-cairo might have some responsability in the way it translates COLR table paints to cairo drawing operations.

**Comment by drj11** [comment]
It is not a colour font, it is Crafty Girls from the Google Fonts collection.

**Comment by behdad** [comment]
> SVG output comes from cairo. If there is an issue here it would be in cairo (or may be in the particular way hb-draw uses cairo, user fonts I think, which is probably less tested).

Would setting `HB_DRAW=0` before invoking `hb-view` fix the problem?

**Comment by khaledhosny** [comment]
> Would setting `HB_DRAW=0` before invoking `hb-view` fix the problem?

It does not seem to make any difference.

**Comment by behdad** [comment]
> > Would setting `HB_DRAW=0` before invoking `hb-view` fix the problem?
> 
> It does not seem to make any difference.

Then at least it's not a user-font issue.

**Comment by khaledhosny** [comment]
I can’t reproduce this with a simple C program that uses cairo directly:
```c
#include <cairo.h>
#include <cairo-svg.h>

int
main (int argc, char *argv[])
{
    cairo_surface_t *surface = cairo_svg_surface_create ("output.svg", 800, 200);
    cairo_t *cr = cairo_create (surface);
    cairo_select_font_face (cr, "sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_font_size (cr, 100);
    cairo_set_source_rgb (cr, 0.6, 0.6, 0.6);
    cairo_paint (cr);
    cairo_set_source_rgb (cr, 0.333, 0.333, 0.333);
    cairo_move_to (cr, 50, 150);
    cairo_show_text (cr, "Dolphin");
    cairo_destroy (cr);
    cairo_surface_destroy (surface);
    return 0;
}
```

The SVG created this way is much simpler, it has no filters for instance. So may be something we are doing is triggering this issue?

**Comment by behdad** [comment]
What if you do `set_source_rgba`?

**Comment by khaledhosny** [comment]
It makes no difference.

**Comment by behdad** [comment]
Okay lemme try. Might be `show_text_glyphs`.

**Comment by khaledhosny** [comment]
I hacked hb-view to support cairo script surface, and I found that it calls set operator twice and I can now reproduce with this:
```c
#include <cairo.h>
#include <cairo-svg.h>

int
main (int argc, char *argv[])
{
    cairo_surface_t *surface = cairo_svg_surface_create ("output.svg", 800, 200);
    cairo_t *cr = cairo_create (surface);
    cairo_select_font_face (cr, "sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_font_size (cr, 100);
    cairo_set_source_rgba (cr, 0.6, 0.6, 0.6, 1);
    cairo_paint (cr);
    cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE); // NEW
    cairo_paint (cr); // NEW
    cairo_set_operator (cr, CAIRO_OPERATOR_OVER); // NEW
    cairo_set_source_rgba (cr, 0.333, 0.333, 0.333, 1);
    cairo_move_to (cr, 50, 150);
    cairo_show_text (cr, "Dolphin");
    cairo_destroy (cr);
    cairo_surface_destroy (surface);
    return 0;
}
```

**Comment by behdad** [comment]
Oh. Definitely a cairo bug. But let's see if we can fix hb-view.

**Comment by behdad** [comment]
> Oh. Definitely a cairo bug. But let's see if we can fix hb-view.

I wonder if the SVG recording-surface is somehow leaking the glyph shapes...

**Comment by behdad** [comment]
This fixes it, and I think is correct change:
```
diff --git a/util/helper-cairo.hh b/util/helper-cairo.hh
index d931d1b70..a7f425d63 100644
--- a/util/helper-cairo.hh
+++ b/util/helper-cairo.hh
@@ -559,7 +559,7 @@ helper_cairo_create_context (double w, double h,
     default:
     case CAIRO_CONTENT_COLOR:
     case CAIRO_CONTENT_COLOR_ALPHA:
-      cairo_set_operator (cr, CAIRO_OPERATOR_SOURCE);
+      cairo_set_operator (cr, CAIRO_OPERATOR_OVER);
       cairo_set_source_rgba (cr, br / 255., bg / 255., bb / 255., ba / 255.);
       cairo_paint (cr);
       cairo_set_operator (cr, CAIRO_OPERATOR_OVER);
```

**Comment by behdad** [comment]
> This fixes it, and I think is correct change:

@khaledhosny Good to commit this?

**Comment by behdad** [comment]
> Definitely a cairo bug.

A Firefox bug I mean.

**Comment by khaledhosny** [comment]
This might be related to https://gitlab.freedesktop.org/cairo/cairo/-/issues/858
