### ISSUE TITLE
Different shaping output with HB_NO_OT_RULESETS_FAST_PATH

### ISSUE THREAD

**Issue by LaurenzV** [harfbuzz/harfbuzz#4813]
With the following font: https://fonts.google.com/noto/specimen/Noto+Serif+Gujarati

Running `hb-shape /Users/lstampfl/Downloads/Noto_Serif_Gujarati/NotoSerifGujarati-VariableFont_wght.ttf
--no-glyph-names --unicodes U+0ABE,U+0AA8,U+0ACD,U+200D,U+0AA4,U+0ABF` yields:

`[414=0+596|60=0+251|61=1+251|186=1+293|3=1+0|38=1+543]`

while if I enable `HB_NO_OT_RULESETS_FAST_PATH` I get:

`[414=0+596|60=0+251|102=1+251|186=1+293|3=1+0|38=1+543]`

**Comment by behdad** [comment]
Fixed. Thanks.
