### ISSUE TITLE
[subset] Documentation: hb_subset_or_fail and hb_face_get_table_tags

### ISSUE THREAD

**Issue by skef** [harfbuzz/harfbuzz#4821]
The documentation for `hb_face_create_for_tables()` notes that `hb_face_get_table_tags()` does not currently work with tables created by that method. However, there doesn't appear to be documentation that:

1. `hb_face_builder_create()` uses `hb_face_create_for_tables()`, or
2. `hb_subset_or_fail()` uses `hb_face_builder_create()`

Leaving it somewhat mysterious why `hb_face_get_table_tags()` returns no tables for a subset face.

**Comment by behdad** [comment]
You're right...

A workaround is to get the face blob from the subset font, and create a new face from it.

**Comment by behdad** [comment]
We can also make get_table_tags work on face_builder faces. And eventually, add a settable callback on the face so that user can implement get_table_tags, and see if we can implement it for freetype and other glue layers.

**Comment by skef** [comment]
This is the sort of restriction that sometimes turns up in this sort of API, so while it would certainly be *nice* if subsets are easier to post-process (with less memory copying), I would say that documentation is fine for the time being. It took me a bit of time to track down what was going on and other people might want to know in the future.

**Comment by behdad** [comment]
FreeType has: `FT_Load_Sfnt_Table`.

CoreText has `CTFontCopyAvailableTables`.
https://developer.apple.com/documentation/coretext/1510774-ctfontcopyavailabletables

I don't see a DirectWrite API for it.

I'll see about implementing this.

**Comment by behdad** [comment]
Hi @skef. In https://github.com/harfbuzz/harfbuzz/pull/4825 I implemented get_table_tags functionality for face-builder faces. Can you test? I haven't tested.

I'll continue with FreeType and CoreText faces.
