### ISSUE TITLE
hb_subset_or_fail and garbage

### ISSUE THREAD

**Issue by skef** [harfbuzz/harfbuzz#4824]
When I call hb_subset_or_fail with a face constructed from garbage (relative to what a valid font should look like) I would expect to get a nullptr back. Instead it seems like I tend to get a non-null face pointer that also returns a non-empty blob from hb_blob_get_data() with a length of 12 or so.

Is this the intention, and therefore should I be doing my own validity checking? (Maybe checking to see if there's a `head` reference blob on the input and output?)

(This seems to be just as true of the hb-subset command line interface -- call it on a garbage file, get back a file of length 12.)

Note that this is against 8.4.0 rather than 9.0.0, although there don't seem to be relevant changes in the commit stream.

**Comment by behdad** [comment]
Yeah to HB everything is a valid font (possibly one it doesn't understand), and will treat garbage as just blobs with no faces inside.

This decision was made intentionally such that eg. Type1 fonts could go through the same codepath as "valid" fonts...  For shaping this is a desired features. For subsetting, less so.

We have for years talked about exposing something like `hb-sanitize`, and the sanitize API publicly. But haven't so far, since what HB calls "sane" just means "HB code can operate on it", and has nothing to do with spec-sanity.

**Comment by skef** [comment]
Would you say that using hb_face_reference_blob to look for a `head` table is a reasonable sanity check for OpenType font/not-font (as opposed to font correctness)?

**Comment by behdad** [comment]
> Would you say that using hb_face_reference_blob to look for a `head` table is a reasonable sanity check for OpenType font/not-font (as opposed to font correctness)?

`hb_face_count(blob)` would do I think.

**Comment by skef** [comment]
> For subsetting, less so.

I guess this might be sufficient reason to leave this issue open ...

**Comment by behdad** [comment]
> > For subsetting, less so.
> 
> I guess this might be sufficient reason to leave this issue open ...

If the face-index is out-of-range (which would be for garbage fonts?) we can fail.

**Comment by behdad** [comment]
So, `if (face_index >= hb_face_count(blob)) return nullptr` kind of patch.

**Comment by skef** [comment]
> hb_face_count(blob) would do I think.

How much re-parsing does that involve? Most times I would be checking the blob coming into the subset, but I also want to check the face produced by the subsetter, which I do blobify but I don't usually post-process further.

**Comment by behdad** [comment]
> > hb_face_count(blob) would do I think.
> 
> How much re-parsing does that involve?

It just looks at a few bytes to see OpenType / TTC header. No actual parsing of tables.

**Comment by skef** [comment]
> It just looks at a few bytes to see OpenType / TTC header. No actual parsing of tables.

Cool, thanks!

**Comment by behdad** [comment]
> So, `if (face_index >= hb_face_count(blob)) return nullptr` kind of patch.

This wouldn't work since the subset API takes a created `hb_face_t`, not the `face_index`.

**Comment by behdad** [comment]
An alternative would be to fail if the face has no glyphs in it.

**Comment by behdad** [comment]
> An alternative would be to fail if the face has no glyphs in it.

Done.

**Comment by skef** [comment]
@behdad I've tested this. It works well from the library perspective, so thank you.

From the command line perspective, if I run `hb-subset` on garbage I get this message:

> error: Operation failed. Probably a bug. File github issue.

which should probably be more specific about what's going on.

**Comment by behdad** [comment]
> > error: Operation failed. Probably a bug. File github issue.
> 
> which should probably be more specific about what's going on.

Right. We only have a nullptr return value and no more info. I'll make it say "not valid font" if num_glyphs is 0 in the hb-subset command.
