### ISSUE TITLE
Visual Studio warnings for hb-open-type.hh "truncation of constant value"

### ISSUE THREAD

**Issue by jmckenna** [harfbuzz/harfbuzz#4844]
- compiling `main` with Visual Studio 2022
- warnings throughout compilation, repeated for each file compiled, all pointing to the same line on `hb-open-type.hh`
  ```
  src\hb-open-type.hh(1684): warning C4309: '=': truncation of constant value
  ```

**Comment by behdad** [comment]
Please include the error messages.

**Comment by jmckenna** [comment]
@beh Sorry I had pressed submit before finishing, I've included the messages above.

**Comment by behdad** [comment]
Can you please confirm what like 1684 in that file is in the version you are compiling?

**Comment by jmckenna** [comment]
@behdad I'm in today's `main branch, so the [line#1684](https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-open-type.hh#L1684) is:

```*it++ = (VALUES_ARE_LONGS | 63);```

**Comment by behdad** [comment]
Should be fixed. Thanks.

**Comment by jmckenna** [comment]
@behdad confirmed.  Thanks!
