### ISSUE TITLE
Chinese Characters not well aligned with 'vpal' feature enabled

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#485]
I have tested hb-view with Source Han Serif font, if 'vpal' feature enabled, then Chinese Characters not centered, and the height have not been changed.
![test](https://cloud.githubusercontent.com/assets/10364351/26042436/10729d8c-3968-11e7-93dd-c4d9f447816f.png)
They should works as this (found at [Type is Beautiful](http://www.typeisbeautiful.com/2017/04/11961/)):
![sample](http://www.typeisbeautiful.com/wp-content/uploads/2017/04/SHSPropMetrics.png)

**Comment by behdad** [comment]
Assigning to @kenlunde to see if he can figure out what's going on.  I have no idea and no time to debug any time soon.

**Comment by kenlunde** [comment]
@behdad: The glyph for a single ideograph, U+4E00 一, is included within the scope of the 'vpal' GPOS feature. The following is my raw (using Unicode-based working glyph names) "features" file code for this glyph:

`position uni4E00-CN <0 140 0 -280>;`

The second element adjusts lowers the Y-axis origin by 140 units, whose effect is to raise the glyph by 140 units. The fourth element trims 280 units from the vertical advance, making it 720 units. The end result is that 140 units are trimmed from both the top and bottom of the glyph.

**Comment by KrasnayaPloshchad** [comment]
So HarfBuzz need to handle all four elements to clip the glyph when this feature is activated. BTW I found HarfBuzz has the similar problem for 'vhal' feature.

**Comment by kenlunde** [comment]
The 'vert' GPOS (not GSUB) feature also uses the same four elements, so it needs to be checked, too. However, given that U+3001 、 IDEOGRAPHIC COMMA seems to behave correctly and is handled via the same feature ('vpal'), I wonder whether something else it at work here.

**Comment by behdad** [comment]
We seems to be applying GPOS just fine.  However, neither FreeType nor hb-ot-font implement VORG table.  I don't know what the reporter's screenshots are coming from, but probably same issue.  Without VORG, it's not possible to correctly get the vertical glyph origin..

**Comment by KrasnayaPloshchad** [comment]
> I don't know what the reporter's screenshots are coming from, but probably same issue. 

According to TIB, this screenshot came from Adobe Illusruator to show the effect when enabling 'vpal' feature in SHS font.

**Comment by KrasnayaPloshchad** [comment]
So this can be consider as duplicate of #250, isn’t it?

**Comment by behdad** [comment]
What's the text sequence?

**Comment by behdad** [comment]
Looks like https://github.com/behdad/harfbuzz/issues/416

Ie. hb-shape is fine, hb-view is wrong.

Also this: https://github.com/behdad/harfbuzz/issues/537

**Comment by KrasnayaPloshchad** [comment]
> What's the text sequence?

You can copying from here:
公元二一三年、十一月

**Comment by KrasnayaPloshchad** [comment]
Here is my test with hb-view 2.1.1
`harfbuzz-2.1.1-win32\hb-view.exe C:\Windows\Fonts\SourceHanSerifSC-Regular.otf --unicodes="516C 5143 4E8C 4E00 4E09 5E74 3001 5341 4E00 6708" --features=vpal --direction=ttb --output-format=png --output-file=test.png`
![test](https://user-images.githubusercontent.com/10364351/48299045-532acb00-e4bf-11e8-9cdb-c3afcff0e2fa.png)

**Comment by KrasnayaPloshchad** [comment]
After I got HarfBuzz 2.2.0, the problem is still there. So what’s wrong with it?

**Comment by behdad** [comment]
This also seems fixed to me.
