### ISSUE TITLE
Invalid-read bug in function _populate_gids_to_retain()

### ISSUE THREAD

**Issue by skorpion98** [harfbuzz/harfbuzz#4852]
### Describe the bug
We found an invalid-read bug in function `_populate_gids_to_retain()` after testing one of the harnesses provided on the OSS-Fuzz repository (hb-subset-fuzzer).
More specifically, the program allocates a 12 byte-long buffer and then attempts to perform a 4 byte-long read starting from the tenth byte of the buffer.

**Valgrind output**
==104== Invalid read of size 4
==104==	at 0x4BEF44: _populate_gids_to_retain(hb_subset_plan_t*, hb_set_t*) (in /out/hb-subset-fuzzer)
==104==	by 0x4B3BD0: hb_subset_plan_t::hb_subset_plan_t(hb_face_t*, hb_subset_input_t const*) (in /out/hb-subset-fuzzer)
==104==	by 0x4C30A4: hb_subset_plan_create_or_fail (in /out/hb-subset-fuzzer)
==104==	by 0x2DB1A8: hb_subset_or_fail (in /out/hb-subset-fuzzer)
==104==	by 0x10CAFD: trySubset(hb_face_t*, unsigned int const*, int, unsigned int, hb_subset_input_t*) (in /out/hb-subset-fuzzer)
==104==	by 0x10C7E4: LLVMFuzzerTestOneInput (in /out/hb-subset-fuzzer)
==104==	by 0x4FE909: ExecuteFilesOnyByOne (in /out/hb-subset-fuzzer)
==104==	by 0x4FE705: LLVMFuzzerRunDriver (in /out/hb-subset-fuzzer)
==104==	by 0x4FE2BD: main (in /out/hb-subset-fuzzer)
==104==  Address 0x4cbe39a is 10 bytes inside a block of size 12 alloc'd
==104==	at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==104==	by 0x10DF62: hb_blob_get_data_writable (in /out/hb-subset-fuzzer)
==104==	by 0x214440: hb_blob_t* hb_sanitize_context_t::sanitize_blob<OT::Layout::GSUB>(hb_blob_t*) (in /out/hb-subset-fuzzer)
==104==	by 0x4C9CC8: hb_subset_plan_t::source_table_loader<OT::Layout::GSUB>::operator()(hb_subset_plan_t*) (in /out/hb-subset-fuzzer)
==104==	by 0x4B8D69: _populate_gids_to_retain(hb_subset_plan_t*, hb_set_t*) (in /out/hb-subset-fuzzer)
==104==	by 0x4B3BD0: hb_subset_plan_t::hb_subset_plan_t(hb_face_t*, hb_subset_input_t const*) (in /out/hb-subset-fuzzer)
==104==	by 0x4C30A4: hb_subset_plan_create_or_fail (in /out/hb-subset-fuzzer)
==104==	by 0x2DB1A8: hb_subset_or_fail (in /out/hb-subset-fuzzer)
==104==	by 0x10CAFD: trySubset(hb_face_t*, unsigned int const*, int, unsigned int, hb_subset_input_t*) (in /out/hb-subset-fuzzer)
==104==	by 0x10C7E4: LLVMFuzzerTestOneInput (in /out/hb-

==104==	by 0x4FE909: ExecuteFilesOnyByOne (in /out/hb-subset-fuzzer)
==104==	by 0x4FE705: LLVMFuzzerRunDriver (in /out/hb-subset-fuzzer)

### To Reproduce
In the [attached archive](https://github.com/user-attachments/files/16845905/msan_bugs.zip) you will find:
- the executable on which we performed our tests
- the input file that caused the bug
- the output of Valgrind confirming our finding

To reproduce the error, a memory safety tool is required to expose the bug. 
Run the given binary with the testcase file inside Valgrind with a command like `valgrind ./hb-subset-fuzzer /path_to_testcase/input

The program has been tested on the standard Docker image provided on OSS-Fuzz using Ubuntu 20.04, providing AFL++ as fuzzing engine and build flag `--sanitizer=none`.

The hash commit used to perform the tests is `a070f9e`

### Environment
- OS: Linux
- Version/Distribution: Ubuntu 20.04
- Architecture: x86_64

**Comment by garretrieger** [comment]
It doesn't look like it reproduces compiling from source with default config, so I suspect this is another instance where the problem is only present depending on the specifics of how the code is compiled and a memory barrier might be needed (see: #3727). I'll see if I can track down where specifically it's happening.

**Comment by behdad** [comment]
It reproduced easily for me, and pointed to the problematic code.
