### ISSUE TITLE
CGJ blocks mark-to-base attachment

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#4869]
This is related to https://github.com/harfbuzz/harfbuzz/discussions/4796. I want to prevent shadda-kasra mark-to-mark attachment or ligation. So I input kasra+CGJ+shadda, the role of CGJ is to prevent the ro-ordering the kasra after the shadda.

The CGJ prevents the re-ordering, but it also prevents the shadda from attaching to the base letter:
It also prevents mark-to-mark attachment, but then the shadda is not attached to the base glyph:

It also prevents mark-to-mark attachment, but then the shadda is not attached to the base glyph:
```
$ hb-view "Fustat[wght].ttf" -u 0635,0650,034F,0651,0627
```
![fustat](https://github.com/user-attachments/assets/c2cfacd4-9b49-4a61-bfd4-c1fbb6c27722)

In CoreText the shadda attaches to the base just fine:
```
$ hb-view "Fustat[wght].ttf" -u 0635,0650,034F,0651,0627 --shaper=coretext
```
![fustat-ct](https://github.com/user-attachments/assets/6dac48de-9c0f-468f-b71a-c40fa4eacfdd)

DirectWrite is even worse than HarfBuzz, no attachment nor joining:
```
$ hb-view.exe "Fustat[wght].ttf" -u 0635,0650,034F,0651,0627 --shaper=directwrite
```
![fustat-dw](https://github.com/user-attachments/assets/297899a7-9813-49f1-8399-0d2c5d26fe7c)

I think CoreText behavior makes more sense as CGJ is Default_Ignorable, so should be ignored for anything other than its effect on normalization.

**Comment by behdad** [comment]
> I think CoreText behavior makes more sense as CGJ is Default_Ignorable, so should be ignored for anything other than its effect on normalization.

`Default_Ignorable` means "ignore it when it's not relevant". Here, I specifically made it block shaping (ligation, etc) because there were fonts (Noto Naskh Arabic?) That were ligating shadda+kasra in whatever order, because Uniscribe requires that to work...

I like the idea of making them block GSUB but no GPOS. What do you think?

**Comment by khaledhosny** [comment]
> `Default_Ignorable` means "ignore it when it's not relevant".

I’m arguing that CGJ is only relevant in preventing mark re-ordering, and should have no other effect.

> Here, I specifically made it block shaping (ligation, etc) because there were fonts (Noto Naskh Arabic?) That were ligating shadda+kasra in whatever order, because Uniscribe requires that to work...

Yes, there probably still many fonts that does this because Uniscribe does not normalize its input.

> I like the idea of making them block GSUB but no GPOS. What do you think?

Sounds good. It would even make fonts that ligate in either order not ligate when CGJ is used, which is desirable here.

**Comment by behdad** [comment]
> > I like the idea of making them block GSUB but no GPOS. What do you think?
> 
> Sounds good. It would even make fonts that ligate in either order not ligate when CGJ is used, which is desirable here.

Right. That's my point. Okay, let me see what I can do.

**Comment by behdad** [comment]
Fixed. Maybe worth a release.

**Comment by behdad** [comment]
Also Unicode 16...

**Comment by behdad** [comment]
10.0?

**Comment by khaledhosny** [comment]
https://github.com/harfbuzz/harfbuzz/releases/tag/10.0.0
