### ISSUE TITLE
Shaping results completely different with GeezaPro.ttc on MacOS 15?

### ISSUE THREAD

**Issue by LaurenzV** [harfbuzz/harfbuzz#4873]
Hello,

as you know, we run a lot of the MacOS tests of harfbuzz in rustybuzz, too. Instead of reusing the expected test outputs from harfbuzz, what we instead do is run the tests locally, capture the harfbuzz output and then use that as our expected test output.

I just wanted to sync up the tests again, but I noticed that harfbuzz suddenly yields very different results for a lot of tests, even without making any changes, meaning that the difference can only come from the fact that I recently upgraded to MacOS 15. So I thought maybe they just changed some things in the fonts themselves, but it seems like the selected glyphs also deviate from coretext itself.

To provide just one example:
```
hb-shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names
[883=0+0|1558=0+1415]

hb-shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names --shaper coretext
[883=0@250,-250+-250|242=0@250,0+1665]

shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names
883=0@250,-250+250|242=0@-250,0+1165
```

The last command is with rustybuzz, so it still matches `coretext` (except for the fact that the last advance width is a bit different). Am I missing something obvious here?

**Comment by khaledhosny** [comment]
Use `--ned` option when comparing HarfBuzz positioning to CoreText’s, the relative positions are setup differently between the two, but the absolute positions (that `--ned` makes) should match.

On my system (macOS 14.6.1) they match:
```
$ hb-shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names
[883=0@250,-250+250|242=0@-250,0+1165]
$ hb-shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names --shaper=coretext
[883=0@250,-250+-250|242=0@250,0+1665]
$ hb-shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names --ned
[883@250,-250|242]
$ hb-shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names --shaper=coretext --ned
[883@250,-250|242]
```

I don’t know why you are getting totally different output on macOS 15

**Comment by LaurenzV** [comment]
That's what I get:
```
hb-shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names --ned
[883|1558]

hb-shape /System/Library/Fonts/GeezaPro.ttc --unicodes U+0628,U+064F --no-glyph-names --shaper=coretext --ned
[883@250,-250|242]
```

I tried both, 9.0.0 and 10.0.0. So I think it has to be related to MacOS 15

**Comment by behdad** [comment]
> That's what I get:

Visually, which one is correct?  We're missing the BEH?

**Comment by khaledhosny** [comment]
Can you try passing `-V` to `hb-shape` to see what it is doing?

**Comment by jfkthame** [comment]
Hmm, does Geeza really have a GSUB table? With a null script tag? That seems to be what the trace suggests.

On 14.6, I don't see a GSUB at all:
```
Listing table info for "/System/Library/Fonts/GeezaPro.ttc":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    OS/2  0xBBAB6009        96    443008
    Zapf  0x9360AC2A     32712    480320
    cmap  0x88826019       716      5488
    feat  0xFD890F80       100   1018124
    glyf  0x8BE87E1E    175300    645276
    head  0x1A5319DD        54      1964
    hhea  0x3FA1377B        36    442936
    hmtx  0x01339670      6816    452664
    just  0x49F10278      3752    443200
    kern  0x73A5B458     14192   1003932
    loca  0x0B4FF818      6820    459480
    maxp  0x06E1054B        32    442872
    meta  0x5FA3A0CF      2341     16688
    morx  0xB13CE185     13144     64348
    name  0x36D3CEF9      1004     11280
    post  0x42444A30     48584    546592
```

**Comment by LaurenzV** [comment]
Just checked, and it doesn't have one...

**Comment by jfkthame** [comment]
The `trace: start table GSUB script tag...` output seems odd, then. Are tables being accessed directly from the raw font data, or loaded through a Core Text API (which I suspect might try to synthesize it on the fly)?

**Comment by behdad** [comment]
> The `trace: start table GSUB script tag...` output seems odd, then. Are tables being accessed directly from the raw font data, or loaded through a Core Text API (which I suspect might try to synthesize it on the fly)?

I think we load them ourselves.

I'm upgrading my machine to investigate. I suspect somehow we're rejecting the `morx` table, and then the Null GSUB kicks in. The fallback Arabic shaping seems to be in charge as well.

**Comment by behdad** [comment]
`hb_aat_layout_has_substitution` is returning false indeed.

**Comment by behdad** [comment]
One of the `morx` chains refuses to sanitize. Investigating.

**Comment by behdad** [comment]
> One of the `LookupFormat0`'s is failing to sanitize because it looks like there's two bytes out of range. I have a suspicion.

I'm out of ideas. `LookupFormat0` is supposed to have one value per glyph in the font. The font reports 1705 glyphs, but the subtable in question only has room for 1704 values.

Of course I can remove the `hb_sanitize_with_object_t` guards and sanitize against the whole table. That should "fix" this. I wonder if it's a bug in the font that the subtable has the wrong length.

@nedley

**Comment by behdad** [comment]
> Of course I can remove the `hb_sanitize_with_object_t` guards and sanitize against the whole table. That should "fix" this. I wonder if it's a bug in the font that the subtable has the wrong length.

This, for example, fixes the result:
```diff
diff --git a/src/hb-aat-layout-morx-table.hh b/src/hb-aat-layout-morx-table.hh
index 4a0f6da16..688018453 100644
--- a/src/hb-aat-layout-morx-table.hh
+++ b/src/hb-aat-layout-morx-table.hh
@@ -1062,7 +1062,7 @@ struct ChainSubtable
   bool apply (hb_aat_apply_context_t *c) const
   {
     TRACE_APPLY (this);
-    hb_sanitize_with_object_t with (&c->sanitizer, this);
+    //hb_sanitize_with_object_t with (&c->sanitizer, this);
     return_trace (dispatch (c));
   }
 
@@ -1075,7 +1075,7 @@ struct ChainSubtable
          c->check_range (this, length)))
       return_trace (false);
 
-    hb_sanitize_with_object_t with (c, this);
+    //hb_sanitize_with_object_t with (c, this);
     return_trace (dispatch (c));
   }
 
```

**Comment by behdad** [comment]
In theory I can flip the logic for `LookupFormat0` around and only declare it including glyph indices that fit into the subtable. Let me see how much plumbing that requires.

**Comment by behdad** [comment]
(We should also update the test suite for the new GeezaPro version.)

**Comment by jfkthame** [comment]
> I'm happy with commenting out the`with_object` guards. @jfkthame ?

So ignoring the claimed length of the subtable, and just ensuring we won't try to access bytes beyond the table as a whole, right? I guess that'd be OK. (I wonder if that "overflowing" glyph ID is one that in practice will never be looked up here?)

**Comment by behdad** [comment]
> > I'm happy with commenting out the`with_object` guards. @jfkthame ?
> 
> So ignoring the claimed length of the subtable, and just ensuring we won't try to access bytes beyond the table as a whole, right? I guess that'd be OK. (I wonder if that "overflowing" glyph ID is one that in practice will never be looked up here?)

Right and right.

**Comment by behdad** [comment]
PR in https://github.com/harfbuzz/harfbuzz/pull/4874
Worth a micro release.

**Comment by khaledhosny** [comment]
So why does rustybuzz not have the same issue?

**Comment by behdad** [comment]
> So why does rustybuzz not have the same issue?

I think `ttfparser` reads the structs without sanitizing across the subtable length boundary, like we do in the PR.

**Comment by khaledhosny** [comment]
Hmm, `git grep -i sanitize` yields nothing in rustybuzz, so it does not sanitize at all?

**Comment by behdad** [comment]
I see in ttf-parser:
```
            lookup: Lookup::parse(number_of_glyphs, data.get(lookup_table_offset..)?)?,
```
Suggests that it uses all data, not just the subtable length?

**Comment by khaledhosny** [comment]
> PR in #4874 Worth a micro release.

https://github.com/harfbuzz/harfbuzz/releases/tag/10.0.1

**Comment by nedley** [comment]
Sorry, a lot happened before I could read and comment. I believe the “correct” fix here would be for the subtable length to be propagated to the LookupTable, which would give an array count of 1704.

**Comment by behdad** [comment]
> Sorry, a lot happened before I could read and comment. I believe the “correct” fix here would be for the subtable length to be propagated to the LookupTable, which would give an array count of 1704.

Thanks. I'll see if I can do that. The thing is, Lookup's are so widely used, wiring the subtable length everywhere is cumbersome.

**Comment by nedley** [comment]
I wish I had a better answer, sorry. AAT has always been too clever by half.

**Comment by behdad** [comment]
> I wish I had a better answer, sorry. AAT has always been too clever by half.

Thanks. I'll keep the code as is for now..

**Comment by nedley** [comment]
The risk here is the possibility mentioned by @jfkthame that the glyph not covered is assigned the wrong class depending on what data happens to occur next in the file.

**Comment by behdad** [comment]
> The risk here is the possibility mentioned by @jfkthame that the glyph not covered is assigned the wrong class depending on what data happens to occur next in the file.

Correct. But how is this not considered a font bug? The documentation clearly says LookupFormat0 is indexed by glyph index. Doesn't that imply that there should be an entry for each glyph in the font?

**Comment by nedley** [comment]
There is enough information in the font to handle this case even without an explicit count, but I am happy to pass along your observation and see what people think. In any event, sorry about the fire drill.
