### ISSUE TITLE
hb-ft does not correctly scale bitmap-only fonts

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#489]
Like NotoColorEmoji for example.

**Comment by behdad** [comment]
In the meantime, using hb-ot font funcs works.  Eg. --font-funcs=ot

**Comment by behdad** [comment]
If anyone wants to attach this, here's the logic in cairo that picks up the best strike and uses that size to call FreeType, and scaling results:

https://github.com/behdad/cairo/blob/color-emoji/src/cairo-ft-font.c#L726

It's quite doable.  Just a bit of head-scratching to figure out where to do it to minimize changes.

**Comment by khaledhosny** [comment]
Now that FreeType has `FT_Get_Transform()` (https://github.com/harfbuzz/harfbuzz/issues/2428), what do we need to do here?

**Comment by khaledhosny** [comment]
It seems to have gotten worse:
```
$ hb-view NotoColorEmoji.ttf  123 --font-funcs=ft
hb-view: Failed: invalid matrix (not invertible)
```

**Comment by behdad** [comment]
> It seems to have gotten worse:
> 
> ```
> $ hb-view NotoColorEmoji.ttf  123 --font-funcs=ft
> hb-view: Failed: invalid matrix (not invertible)
> ```

Weird. I don't remember any changes that would trigger that.

Let me try to tackle this.

**Comment by behdad** [comment]
This is very peculiar. My system hb-view doesn't have the change of behavior whereas if I compile the same version (4.0.0) I get the `invalid matrix` error. With same system freetype and cairo.

**Comment by behdad** [comment]
The error message is from cairo FWIW.

**Comment by behdad** [comment]
I almost have a fix here: https://github.com/harfbuzz/harfbuzz/pull/3726
