### ISSUE TITLE
Swash feature not working with DAveau font

### ISSUE THREAD

**Issue by sid-wr** [harfbuzz/harfbuzz#4897]
Hi

For _**DAveau**_ font, the Swash OpenType feature doesn't seem to be working with HarfBuzz even though that Glyph is present in this font.

The **hb-view** tool is generating same output for the example text without v/s with Swash.

1) Without Swash
```
hb-view.exe daveauregular.otf --text="A" --output-file="DAveau-without-swash.png"
```
![DAveau-without-swash](https://github.com/user-attachments/assets/241972cb-d85b-42c7-b0ef-9ec4ec3755fb)

2) With Swash
```
hb-view.exe daveauregular.otf --features="swsh" --text="A" --output-file="DAveau-with-swash.png"
```
![DAveau-with-swash](https://github.com/user-attachments/assets/b399123f-1c0f-41d4-a627-007cc4a258fb)

Also confirmed the same from **hb-shape** tool

1) Without Swash
```
hb-shape.exe daveauregular.otf --text="A"
[A=0+921]
```

2) With Swash
```
hb-shape.exe daveauregular.otf --features="swsh" --text="A"
[A=0+921]
```

Both are generating same glyph ID in the output

Please help

**Comment by khaledhosny** [comment]
The font has a `morx` table which HarfBuzz will use instead of the `GSUB` table, and thus `GSUB` features will not be applied.
