### ISSUE TITLE
meson build?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#490]
That's what the Cool Kids(TM) are using these days... Ie. GNOME is switching to it.  It looks like cmake done right kind of project...  I'd be happy to replace all our current ones with meson if that works for our Windows developers.

http://mesonbuild.com/

@ebraminio?

**Comment by ebraminio** [comment]
Very compelling, specially the autotools removal part if is planned :) My concern was vcpkg compatibility part which it seems that is also not [an issue](https://github.com/Microsoft/vcpkg/blob/master/ports/libepoxy/portfile.cmake#L19) so this works well for Windows developers also I guess. I suggest some branch for that inside the repo.

**Comment by behdad** [comment]
Yeah that's what I thought.  Let's see how pango turns out...

**Comment by pedronavf** [comment]
I'd vote for CMake, its Windows support strikes me as more mature than what meson could have (being a newer project and considering that Microsoft contributes to CMake). Also, having to install Python 3 on Windows just to build seems to me like a very strong requirement.

**Comment by behdad** [comment]
Maybe @ebassi and I can take a look at this at GUADEC.

**Comment by behdad** [comment]
> I'd vote for CMake

We already have a CMake one.  But no, I'm not going to switch to that as the main build system.

**Comment by nacho** [comment]
FWIW in https://github.com/wingtk/gvsbuild we have support to build with meson without any issues

**Comment by nacho** [comment]
did you guys see https://github.com/centricular/harfbuzz ?

**Comment by tp-m** [comment]
I talked about it at GUADEC with behdad and he said we should submit a PR but we haven't gotten around to it yet, sorry!

**Comment by behdad** [comment]
@tp-m Ready to send a PR?

**Comment by tp-m** [comment]
> @tp-m Ready to send a PR?

Let me rebase and see what happens (wip is at https://github.com/tp-m/harfbuzz/tree/meson-rebased).
