### ISSUE TITLE
Is cmap14 glyph closure incorrect?

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#4911]
https://github.com/harfbuzz/harfbuzz/blob/main/src/hb-ot-cmap-table.hh#L1454

glyph closure for cmap 14 doesn't filter variation selector records by which variation selector code points are in the input set. As a result all variant glyphs get retained. If a variation selector codepoint isn't present in the subset definition then the variants for it shouldn't be reachable so we should be able to omit them from the subset.

**Comment by behdad** [comment]
I think this was probably done intentionally. But I'm fine changing it.

**Comment by behdad** [comment]
cc @jfkthame

**Comment by behdad** [comment]
What does fonttools do by the way?

**Comment by garretrieger** [comment]
Looks like it currently does the same thing as harfbuzz: https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/subset/__init__.py#L2870

**Comment by garretrieger** [comment]
Made a fix for fonttools as well: https://github.com/fonttools/fonttools/pull/3672

**Comment by behdad** [comment]
I'm unsure about this, but feel free to merge.

**Comment by behdad** [comment]
> I'm unsure about this, but feel free to merge.

Done for both HB and FT.
