### ISSUE TITLE
Blocklist Courier New `GDEF` table?

### ISSUE THREAD

**Issue by khaledhosny** [harfbuzz/harfbuzz#4936]
Courier New seems to give several spacing glyphs (notably several Latin letters) mark glyph class, resulting in zeroing their advance.

I checked both the version that ships with Windows 10 ([I reported it to Microsoft](https://github.com/MicrosoftDocs/typography-issues/issues/1184)) and the one ships with macOS 15 (seems to be an older version) and both have this issue.

Should we blocklist the `GDEF` table of these fonts?

**Comment by behdad** [comment]
I thought we do, but apparently not. Sounds good to me. @jfkthame ?

**Comment by jfkthame** [comment]
Yeah, sgtm. I'm surprised we hadn't caught that one before, along with the similar issues in Times etc.
