### ISSUE TITLE
[COLR] Incorrect character rendering and shape with Aref Ruqaa Ink colored font

### ISSUE THREAD

**Issue by munzirtaha** [harfbuzz/harfbuzz#4938]
It seems there is a problem at least with `hb-view`, In LibreOffice I don't see the problem

```
> pacman -Q harfbuzz
harfbuzz 10.1.0-1
> hb-view ArefRuqaaInk-Regular.ttf  "عل كم"
```
![arefRuqaaInk](https://github.com/user-attachments/assets/62116453-bba5-4eb8-8ed8-4bb8e322e4a1)

**Comment by khaledhosny** [comment]
FWIW, FontGoogles seems to not have an issue here
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/1cacd2a4-9eb0-4eb8-83ea-a22783b1ca89">

**Comment by khaledhosny** [comment]
It looks also fine with `HB_DRAW=0`.

**Comment by behdad** [comment]
Humm. Fixed with `--font-funcs=ot`. But `--font-funcs=ft` is still broken.

**Comment by behdad** [comment]
Oh, with `--font-funcs=ft`, it's picking up the SVG, which we don't support. I don't know if we can tell FreeType that we don't support SVG...

**Comment by behdad** [comment]
`FT_LOAD_NO_SVG` did it.

**Comment by munzirtaha** [comment]
Thanks! Quick as usual.

**Comment by behdad** [comment]
You're welcome!
