### ISSUE TITLE
Subsetting some fonts return "Operation failed" when enabling preproces

### ISSUE THREAD

**Issue by MIRIMIRIM** [harfbuzz/harfbuzz#4943]
When enabling preprocess, some fonts return this error if the subset contains 1500+ characters. I tested some FounderType fonts, and they all exhibited this issue.

The attachment contains my test font and characters text files. The harfbuzz version I am using is 10.1.0.
[test.zip](https://github.com/user-attachments/files/17812978/test.zip)

**Comment by behdad** [comment]
256?
