### ISSUE TITLE
hb-shape and hb-view should accept all OpenType language systems and scripts

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#495]
hb-shape and hb-view have the options `--language` and `--script`, which take ISO codes. There are some OpenType language systems and scripts that HarfBuzz does not convert any ISO codes to, e.g. 'PGR ' and 'musc'. It would therefore be useful to be able to specify the OpenType tags directly.

**Comment by khaledhosny** [comment]
`--script` essentially take an OT tag already (but lowercased), for `--language` you can use the custom `x-hbotABCD` to pass an `ABCD` tag directly.

**Comment by dscorbett** [comment]
I’d forgotten about x-hbotABCD; thanks!

The value of `--script` ends up getting passed to `hb_ot_tags_from_script`, which converts 'deva' to 'dev2'. Is there a way to explicitly request an old Indic implementation with these command-line tools?

**Comment by khaledhosny** [comment]
I don’t think so.

**Comment by behdad** [comment]
> Is there a way to explicitly request an old Indic implementation with these command-line tools?

Not currently.  I'm open to suggestions.

**Comment by dscorbett** [comment]
There could be a new command line option (`--ot-script=deva` vs. `--ot-script=dev2`) or an addition to the script tag parser (`--script=x-hbscdeva` vs. `--script=x-hbscdev2`).

**Comment by twardoch** [comment]
The hbscXXXX would be consistent with the language method and I would very much appreciate it. It would also be somewhat future-proof i.e. allow processing (through the general shaper) script codes that will be added to the OT spec in future. It would be also great for all kinds of font development purposes.

**Comment by behdad** [comment]
Note that hbscXXXX will be part of the language tag as well.  Our `hb_script_t` is an integer and does not allow such extensions.  I'll see how much work it is to implement it in the shaper selection code.

**Comment by rajeeshknambiar** [comment]
How does one pass specific script tag to `hb-shape` or `hb-view`?

For e.g., I tried the following (harfbuzz-2.7.2), but the `bwlf` lookup defined in `mlym` script in Noto Sans Malayalam doesn’t seem to apply:
```
hb-view --script=x-hbscmlym --font-file=NotoSansMalayalam-Regular.ttf "ല്" --output-file /tmp/notoml-blwf-la.png; xdg-open $_
```
The expected output is below base La glyph is displayed, but output is same two glyphs:
```
hb-shape --script=x-hbscmlym --features="+blwf" --verbose --font-file=NotoSansMalayalam-Regular.ttf "ല്" 
1: (ല്)
1: <U+0D32,U+0D4D>
1: [gid49=0+1759|gid72=0+0]
```

**Comment by khaledhosny** [comment]
You should pass the private tag to the `--language` not `--script` option. But even doing this does not get the output yoyu expect, but even if I subset the font with FontTools too keep only `mlym` script (`fonttools subset --layout-scripts=mlym --layout-features='*' --unicodes='*' --glyph-names NotoSansMalayalam-Regular.ttf`), I still get the same output.

This suggests either a font issue, or a general issue with how HarfBuzz applies `mlym` script, and not something related to script selection.

**Comment by simoncozens** [comment]
I think there *is* something wrong with script selection using private tags. For example, here is a Myanmar font:

```
$ ./util/hb-shape -V ~/work/myanmar/Noto/NSM-2.ttf -u '1000 1036 102B' | head -5
trace: start reorder   buffer: <U+1000=0|U+1036=0|U+102B=0>
trace: end reorder      buffer: <U+1000=0|U+1036=0|U+102B=0>
trace: start table GSUB buffer: [ka=0|anusvara=0|_tall_aa=0]
trace: start reordering myanmar buffer: [ka=0|anusvara=0|_tall_aa=0]
trace: end reordering myanmar   buffer: [ka=0|anusvara=0|_tall_aa=0]
```

Notice that the trace shows it is going through the Myanmar complex shaper. If I force the old `mymr` script it should go through the default shaper instead:

https://github.com/harfbuzz/harfbuzz/blob/9b8be9643cba165abf9256df1b8b8413b0574ab0/src/hb-ot-shape-complex.hh#L253-L263

OK, let's try it:

```
$ ./util/hb-shape -V ~/work/myanmar/Noto/NSM-2.ttf -u '1000 1036 102B' --language=x-hbscmymr | head -5
trace: start reorder   buffer: <U+1000=0|U+1036=0|U+102B=0>
trace: end reorder      buffer: <U+1000=0|U+1036=0|U+102B=0>
trace: start table GSUB buffer: [ka=0|anusvara=0|_tall_aa=0]
trace: start reordering myanmar buffer: [ka=0|anusvara=0|_tall_aa=0]
trace: end reordering myanmar   buffer: [ka=0|anusvara=0|_tall_aa=0]
```

Nope, still going through the Myanmar shaper.

**Comment by khaledhosny** [comment]
You can't select a different shaper using private language subtags, the shaper is always selected based on the script set on the buffer (guessed by hb-view/hb-shape if not explicitly set). The private subtags only control what OpenType language system to use with the already selected shaper.

**Comment by khaledhosny** [comment]
So if you want the default shaper, you have to also set a script (with `--script` option) that goes through default shaper.

**Comment by khaledhosny** [comment]
See https://github.com/harfbuzz/harfbuzz/issues/2271#issuecomment-614932478, and https://github.com/harfbuzz/harfbuzz/issues/2680

**Comment by rajeeshknambiar** [comment]
> You should pass the private tag to the `--language` not `--script` option. But even doing this does not get the output yoyu expect, but even if I subset the font with FontTools too keep only `mlym` script (`fonttools subset --layout-scripts=mlym --layout-features='*' --unicodes='*' --glyph-names NotoSansMalayalam-Regular.ttf`), I still get the same output.

Thanks. Passing only `--language` seems to apply lookups from both scripts `mlym` and `mlm2`; while passing both `--language` and `--script` seems to limit the selection properly. Further comments added to #2680.

> This suggests either a font issue, or a general issue with how HarfBuzz applies `mlym` script, and not something related to script selection.

That, indeed turned out to be the reason: @n8willis found that the first substitution is reversed by a subsequent lookup: https://github.com/n8willis/opentype-shaping-documents/pull/99#issuecomment-764834612
