### ISSUE TITLE
Pedantic warning while using HB_TAG 

### ISSUE THREAD

**Issue by ksvskushal** [harfbuzz/harfbuzz#504]
While compiling freetype2, I found the following warning.
```
hb-common.h:93:29: warning: ISO C restricts enumerator values to range of ‘int’ [-Wpedantic]
 #define HB_TAG(c1,c2,c3,c4) ((hb_tag_t)((((uint8_t)(c1))<<24)|(((uint8_t)(c2))<

```
HB_TAG_MAX seems to be the problem. 
```
hb-common.h:97:20: note: in expansion of macro ‘HB_TAG’
 #define HB_TAG_MAX HB_TAG(0xff,0xff,0xff,0xff)
```

**Comment by behdad** [comment]
Yeah, ignore it.

**Comment by lionel-** [comment]
FYI this is causing issues for getting packages accepted in [CRAN](https://cran.r-project.org/web/packages/index.html). No pedantic warning is part of their checking process. If possible, it'd be helpful to have this warning fixed.

**Comment by behdad** [comment]
Going to fix it.

**Comment by lionel-** [comment]
Thanks!
