### ISSUE TITLE
Showing .nodef instead of the default glyph when OT::GLYPH_VARIANT_NOT_FOUND

### ISSUE THREAD

**Issue by hfhchan** [harfbuzz/harfbuzz#515]
As far as most common browsers implement Unicode Variation Selectors, if no glyph is provided for a particular character variation, but a glyph exists for a given base character, no font fallback occurs and the base character's default glyph is displayed.

However, it is likely that China and Taiwan will use IVD to encode historic CJK variants in the near future, instead of stuffing them endlessly at the end of Unicode Plane 2 and filling up Plane 3.  In some cases, these glyph differences will need to be reliablly rendered, given the legal implications in Taiwan.  In these cases, getting tofu (.nodef) is much preferred over getting the base character's default glyph.

At the same time, it may be useful to unconditionally drop all variation selectors to render digitized texts in their modern day orthographies.  This could be done by stripping all variation selectors dynamically in the browser, or it could be activated on the help of the shaping engine.

I am seeking for a way to achieve these two desired behaviors, especially through the web browser.  My current thoughts are to register a fake OpenType tag `tofu` so that it can be implemented by piggybacking on `font-feature-settings`.  When activated with value 1, would overwrite `glyph` with the glyph ID 0 (.nodef) when `get_variation_glyph` returns false.  When activated with value 2, would overwrite `glyph` with the default glyph for the base character regardless of any defined records defined in CMAP 14.

I wonder if this is feasible and technically trivial to implement.

**Comment by kojiishi** [comment]
The algorithm is defined in [CSS Fonts, 5.3. Cluster Matching](https://drafts.csswg.org/css-fonts-3/#cluster-matching). Implementation may land in HarfBuzz, but I think you'd better go W3C to see if they can define a CSS properties for browsers to change the mode.

**Comment by hfhchan** [comment]
> 2. If no font was found in the font list in step 1:
> - If c1 is a variation selector, system fallback must be used to find a font that supports the full sequence of b + c1. If no font on the system supports the full sequence, match the single character b using the normal procedure for matching single characters and ignore the variation selector. Note: a sequence with more than one variation selector must be treated as an encoding error and the trailing selectors must be ignored. [UNICODE]
> - Otherwise, the user agent may optionally use system font fallback to match a font that supports the entire cluster.

Unfortunately, Chrome nor Firefox don't implement this.
Microsoft Word doesn't either. 

Variation Selectors seems to be treated differently compared to combining marks -- like at a much later phase.

**Comment by behdad** [comment]
> As far as most common browsers implement Unicode Variation Selectors, if no glyph is provided for a particular character variation, but a glyph exists for a given base character, no font fallback occurs and the base character's default glyph is displayed.
> 
> However, it is likely that China and Taiwan will use IVD to encode historic CJK variants in the near future, instead of stuffing them endlessly at the end of Unicode Plane 2 and filling up Plane 3. In some cases, these glyph differences will need to be reliablly rendered, given the legal implications in Taiwan. In these cases, getting tofu (.nodef) is much preferred over getting the base character's default glyph.
> 
> At the same time, it may be useful to unconditionally drop all variation selectors to render digitized texts in their modern day orthographies. This could be done by stripping all variation selectors dynamically in the browser, or it could be activated on the help of the shaping engine.
> 
> I am seeking for a way to achieve these two desired behaviors, especially through the web browser. My current thoughts are to register a fake OpenType tag tofu so that it can be implemented by piggybacking on font-feature-settings. When activated with value 1, would overwrite glyph with the glyph ID 0 (.nodef) when get_variation_glyph returns false. When activated with value 2, would overwrite glyph with the default glyph for the base character regardless of any defined records defined in CMAP 14.
> 
> I wonder if this is feasible and technically trivial to implement.

I have had wanted to add API that allows for this.  Thanks for bringing up.  It still will be up to the browsers to actually implement it, but HarfBuzz will provide the support for it.

What I'm thinking is an API like `hb_buffer_set_missing_variation()` or something.  Options I can think of currently:

  - Current behavior: ignore variation selector if combination not available,
  - Leave the variation selector glyph in the stream, don't remove it,
  - Show .notdef for the entire sequence (base+variation-selector)?  This is actually tricky, since we currently allow GSUB to consume to consume the sequence.  It's too late to do anything to do it post-GSUB,
  - Replace variation selector with a pre-set glyph number (eg. (unsigned int) -1) for detection by client.

@khaledhosny @jfkthame WDYT?  Suggestions on how the API might look appreciated.

**Comment by behdad** [comment]
cc @drott

**Comment by hfhchan** [comment]
> - Current behavior: ignore variation selector if combination not available,
> - Leave the variation selector glyph in the stream, don't remove it,

That will likely be useful for firefox, e.g. like displaying their custom glyph-not-found box with the codepoint in the middle.

> - Show .notdef for the entire sequence (base+variation-selector)? This is actually tricky, since we currently allow GSUB to consume to consume the sequence. It's too late to do anything to do it post-GSUB,

Hmm... replacing the whole cluster is preferred.  Is it possible to like fork VariationSelectorRecord::get_glyph() such that it acts as if a record with glyph mapping to 0 exists?  Or, we could make that two different behaviors...

> - Replace variation selector with a pre-set glyph number (eg. (unsigned int) -1) for detection by client.

That could be useful, but seemingly .nodef is supposed to be that glyph...

**Comment by hfhchan** [comment]
Probably something like this... 
(I don't code in C, I hope my code is correct)
https://github.com/hfhchan/harfbuzz/commit/802d78b6c983b3de782fd46b4b7de2b3700c55b0

**Comment by jfkthame** [comment]
>     However, it is likely that China and Taiwan will use IVD to encode
>     historic CJK variants in the near future, instead of stuffing them
>     endlessly at the end of Unicode Plane 2 and filling up Plane 3. In
>     some cases, these glyph differences will need to be reliablly
>     rendered, given the legal implications in Taiwan. In these cases,
>     getting tofu (.nodef) is much preferred over getting the base
>     character's default glyph.

A little more background about "the legal implications in Taiwan" would 
be interesting here, IMO.

If those "variant" glyphs need to be *reliably* rendered (distinct from 
the "character's default glyph"), it seems to me that using variation 
selectors to represent them is the wrong model in the first place. A 
documented need to reliably preserve the distinction in plain text would 
be a strong argument for encoding as separate characters.

**Comment by hfhchan** [comment]
> A little more background about "the legal implications in Taiwan" would
> be interesting here, IMO.

In a case in Taiwan, a person argued his name was written incorrectly (with a unifyable glyph variant, per Annex S of ISO10646, and semantically completely equivalent glyph variant) and thus due to procedural error, he could not be charged.  The court voted in his favour.

But the result is, CNS11643 has to keep expanding to accomodate all the different variants that show up regardless of how small the glyphic difference is.  TCA is not pressing for these variants glyphs to be encoded into ISO10646, as they will definitely be shot down by the IRG/WG2, and are currently left as PUA characters in CNS11643.  It would be a big benefit to them if they could encode them all into an IVD collection.

**Comment by behdad** [comment]
>         Leave the variation selector glyph in the stream, don't remove it,
> 
> That will likely be useful for firefox, e.g. like displaying their custom glyph-not-found box with the codepoint in the middle.

Right.  Same with Pango.

>         Show .notdef for the entire sequence (base+variation-selector)? This is actually tricky, since we currently allow GSUB to consume to consume the sequence. It's too late to do anything to do it post-GSUB,
> 
> Hmm... replacing the whole cluster is preferred. Is it possible to like fork VariationSelectorRecord::get_glyph() such that it acts as if a record with glyph mapping to 0 exists? Or, we could make that two different behaviors...
> 
>         Replace variation selector with a pre-set glyph number (eg. (unsigned int) -1) for detection by client.
> 
> That could be useful, but seemingly .nodef is supposed to be that glyph...

.notdef is used for everything.  Missing variations are slightly different in how they should be hooked up with font selection, hence a different value being valuable for detection ;).
> --
> 
> There's also the "ignore all variation selectors" behavior which could be useful for digitization projects.

**Comment by behdad** [comment]
@jfkthame @drott Is this something you are interested on?  Ie. do we care about doing font fallback if current font does not support variation sequence?  Guess it's more relevant to how Chrome does itemization than Firefox.

**Comment by jfkthame** [comment]
ISTM this isn't really the responsibility of harfbuzz, it's up to the application to handle font selection. (Or perhaps not even that: if it's critical that a particular glyph variant be used for a certain document, then it's the document author's responsibility to specify a font that provides the desired glyph. And that document can't reliably be interchanged as Unicode plain text, because Unicode plain text does not encode glyphs, it encodes abstract characters.)

I guess there could be a case, though, for harfbuzz to offer something comparable to the `HB_BUFFER_PRESERVE_DEFAULT_IGNORABLES` flag, to leave otherwise-unsupported codes in the buffer for the client or user to find and do with as they wish. Could we implement `HB_BUFFER_FLAG_PRESERVE_UNSUPPORTED_VARIATION_SELECTORS` to leave such VS glyphs in the output buffer?

I'm less persuaded that harfbuzz should offer an option to map unsupported base+VS sequences to `.notdef`, rather than showing the default glyph for the character in any form; this seems to me to violate the Unicode model pretty drastically, and is not a behavior we should facilitate. Nevertheless, if a client app wants this behavior and intends to handle the resulting .notdef itself, it could achieve this with a custom `get_variation_glyph` callback, couldn't it? No additional support within HB should be needed.

**Comment by brawer** [comment]
> [variants] can't reliably be interchanged as Unicode plain text

Actually, there’s a [registry of standardized variants](https://unicode.org/Public/UCD/latest/ucd/StandardizedVariants.txt), plus the [ideographic variation database](http://www.unicode.org/ivd/). See the [Unicode FAQ on variation sequences](http://unicode.org/faq/vs.html).

**Comment by jfkthame** [comment]
Sorry, that was poorly phrased. Variation sequences can be interchanged as plain text, indeed; but they cannot be relied upon to always render using a specific variant glyph. To quote the FAQ: "When a variation sequence is not valid or its display is not supported, the base character is displayed as usual, and the variation selector is invisible."

If the *display* of a specific variant glyph is critical, then something beyond plain text is required -- typically an associated font that is known to provide the desired glyph.

**Comment by khaledhosny** [comment]
Or that variant should be encoded as an atomic character. My understanding is the whole variation mechanism is meant for non-critical variants where the base glyph is still an acceptable representation.

**Comment by drott** [comment]
It's something that we're still interested in long term, but currently I don't have bandwidth to address this or design this more thoroughly for Chrome. At first sight, something like:
* keep ignoring unavaiable VS for now, but 
* allowing an opt-in to either drop the whole cluster as .notdef or mark it unambiguously in the output sequence
would perhaps be a future proof way for us to take care of VS fallback in Chrome when we get to it?

**Comment by behdad** [comment]
> I guess there could be a case, though, for harfbuzz to offer something comparable to the `HB_BUFFER_PRESERVE_DEFAULT_IGNORABLES` flag, to leave otherwise-unsupported codes in the buffer for the client or user to find and do with as they wish. Could we implement `HB_BUFFER_FLAG_PRESERVE_UNSUPPORTED_VARIATION_SELECTORS` to leave such VS glyphs in the output buffer?

That's exactly what I'm proposing here.  Though, for client to be able to detect them, I need to replace their glyph index with a magic number.  That's the API proposed here.

**Comment by behdad** [comment]
> What I'm thinking is an API like `hb_buffer_set_missing_variation()` or something. Options I can think of currently:
> 
> * Current behavior: ignore variation selector if combination not available,
> * Leave the variation selector glyph in the stream, don't remove it,
> * Show .notdef for the entire sequence (base+variation-selector)?  This is actually tricky, since we currently allow GSUB to consume to consume the sequence.  It's too late to do anything to do it post-GSUB,
> * Replace variation selector with a pre-set glyph number (eg. (unsigned int) -1) for detection by client.

For reference, this is my thinking on the API.

**Comment by behdad** [comment]
Okay, kso I take it as API would be useful, but not urgent.

**Comment by khaledhosny** [comment]
> Nevertheless, if a client app wants this behavior and intends to handle the resulting .notdef itself, it could achieve this with a custom `get_variation_glyph` callback, couldn't it? No additional support within HB should be needed.

I agree with @jfkthame comment above. I think HarfBuzz already provides enough API for clients to support the requested behavior if they so desire, no further HarfBuzz support is needed.

**Comment by behdad** [comment]
> > Nevertheless, if a client app wants this behavior and intends to handle the resulting .notdef itself, it could achieve this with a custom `get_variation_glyph` callback, couldn't it? No additional support within HB should be needed.
> 
> I agree with @jfkthame comment above. I think HarfBuzz already provides enough API for clients to support the requested behavior if they so desire, no further HarfBuzz support is needed.

True. Let's close then.
