### ISSUE TITLE
Incorrect use of shape_plan cache with variation fonts

### ISSUE THREAD

**Issue by jfkthame** [harfbuzz/harfbuzz#549]
Currently, hb_shape_plan_create_cached2 doesn't insert a plan in the cache if there were variation coords included in its parameters (see "XXX Fix me" comment in the source).

However, it does still look for an existing plan in the cache (without taking account of variations). This means that if the face has been used with no variation coords, so that a plan has been cached, any future attempt to use it _with_ variations will incorrectly find the existing, no-coord cached plan.

**Comment by behdad** [comment]
Thanks.

Reopening to fix properly by adding `hb_ot_layout_table_find_feature_variations()` output for GSUB/GPOS to shape-plan cache key.

**Comment by khaledhosny** [comment]
@behdad this is fixed now, right?

**Comment by behdad** [comment]
Yes.  Thanks.
