### ISSUE TITLE
Make matcher aware of CGJ

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#554]
Many Arabic fonts have GSUB rules to reorder marks.  Currently the matcher skips over CGJ.  It shouldn't.

**Comment by KrasnayaPloshchad** [comment]
So CGJ should be treated the same as other combining characters, isn’t it?

**Comment by khaledhosny** [comment]
Do we really want to do that? If the font supports <markA><markB> but the user inserts a CGJ between them because normalization re-orders them, skipping CGJ means the font will just work, while not skipping it means the font will have to explicitly support this case or CGJ will be making things worse.

**Comment by behdad** [comment]
Right now the matches jumps over CGJ because it's a Default_Ignorable.  This bug is exactly about not skipping over it, at least when matching marks.

**Comment by behdad** [comment]
The desired logic here is quite convoluted.  We want matcher to NOT skip a CGJ if and only if removing it would have reordered marks...

I think I can do this by changing the CGJ type to a skippable vs non-skippable during normalization.  Ie. turn it into a ZWNJ-like thing if it should not be skipped.

**Comment by behdad** [comment]
Fortunately we have a bit for that already; that's how Mongolian variation selectors are handled.  So I just need to turn that bit on for all or certain CGJ's.  A good start is to never skip CGJ.  I'll put that in now.

**Comment by khaledhosny** [comment]
With the last commit in master, the third case in https://github.com/w3c/alreq/issues/147 is now broken, but I guess the more refined logic would handle it? 

```
hb-view amiri-regular.ttf --unicodes="0649 0655 034F 0650 062F"
```
![q](https://user-images.githubusercontent.com/93914/31583674-5cdea234-b1a8-11e7-8a67-9b2cfafd3ea5.png)

**Comment by behdad** [comment]
> With the last commit in master, the third case in w3c/alreq#147 is now broken, but I guess the more refined logic would handle it?

Yes.  I'll work on it.  Good to have a test.

BTW, why doesn't Amiri have mark2mark attachments?

**Comment by khaledhosny** [comment]
> BTW, why doesn't Amiri have mark2mark attachments?

It has, but I substitute kasra following hamza with a smaller one and there is no mark to mark attachments between hamza and regular kasra.

**Comment by behdad** [comment]
I'm releasing 1.6.1.  I'm aware that this bug is not fully fixed and 1.6.1 will have different behavior from previous versions, and probably following versions.  Just documenting here for posterity.

**Comment by KrasnayaPloshchad** [comment]
@khaledhosny Is it possible to workaround for that? For example, add a zero-width glyph and mark attachments for CGJ in Amiri.

**Comment by behdad** [comment]
We don't want workarounds.
