### ISSUE TITLE
Figure out coveralls stuff

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#570]
Currently we have a coverage badge on our repo, which points to https://coveralls.io/github/behdad/harfbuzz but that was last updated on Jan 2016.  Either figure out how to getting hooked up again, or remove it.  I don't remember how I set it up.

**Comment by behdad** [comment]
Any takers? wink wink.

**Comment by behdad** [comment]
:D

**Comment by ebraminio** [comment]
Done :)

**Comment by behdad** [comment]
How does that tie into coveralls? I don't see it yet.

**Comment by behdad** [comment]
Ah, I see. In ecef95b21264347f9505e3ed4fb25ec7e4ccca5d

**Comment by behdad** [comment]
Should we remove the --coverage stuff from .travis.yml? The --enable-code-coverage stuff makes that redundant.

**Comment by ebraminio** [comment]
What can go wrong? :) https://github.com/harfbuzz/harfbuzz/commit/6659cb56fae0c900ae88e95bedcb3b76234c8838 

I just fear that https://github.com/harfbuzz/harfbuzz/commit/f7399796a1ed36cfc4f1ef7631584569baa80981#diff-480477e89f9b6ddafb30c4383dcdd705 was not enough.
