### ISSUE TITLE
The CJK glyphs shift up and right in vertical TTB direction 

### ISSUE THREAD

**Issue by marklh9** [harfbuzz/harfbuzz#573]
The glyphs shift up and right in vertical TTB direction.

The issues were reported in LibreOffice bugzilla:
https://bugs.documentfoundation.org/show_bug.cgi?id=111967   ( TDF#111967 )
https://bugs.documentfoundation.org/show_bug.cgi?id=112066   ( TDF#112066 )

Sorry I don't know much about HarfBuzz or font so that I can't describe very precisely and
can only describe what I observed here:

The issue was introduced in LibreOffice when it upgraded HarfBuzz from 1.3.3 to 1.4.8.
By testing every HarfBuzz version between 1.3.3 and 1.4.8 I found that
the issue was introduced in HarfBuzz 1.3.4. If I naively revert  

subtract_glyph_h_origin()
subtract_glyph_v_origin()
add_glyph_h_origin()
add_glyph_v_origin()
to what it was in 1.3.3, then the issue is fixed.

cyanshrike@gmail.com also mentioned that 
hb-view and hb-shape shows the difference between 1.3.3 and 1.3.4.

harfbuzz-1.3.3-win32\hb-shape --font-funcs=ot --shaper=ot --font-size=72 --direction=ltl --font-file="C:\Windows\Fonts\mingliu.ttc" --text=測試
[gid15828=0+72|gid23054=1+72]

harfbuzz-1.3.3-win32\hb-shape --font-funcs=ot --shaper=ot --font-size=72 --direction=ttb --font-file="C:\Windows\Fonts\mingliu.ttc" --text=測試
[gid15828=0+0,-72|gid23054=1+0,-72]

harfbuzz-1.3.4-win32\hb-shape --font-funcs=ot --shaper=ot --font-size=72 --direction=ltl --font-file="C:\Windows\Fonts\mingliu.ttc" --text=測試
[gid15828=0+72|gid23054=1+72]

harfbuzz-1.3.4-win32\hb-shape --font-funcs=ot --shaper=ot --font-size=72 --direction=ttb --font-file="C:\Windows\Fonts\mingliu.ttc" --text=測試
[gid15828=0@-36,-58+0,-72|gid23054=1@-36,-58+0,-72]

Please let me know if you need further information. Thanks.

**Comment by KrasnayaPloshchad** [comment]
Have you tested with Firefox Beta 57.0? This is also used HarfBuzz v1.4.8.

**Comment by KrasnayaPloshchad** [comment]
I have tested with Firefox 56.0.2, this version used HarfBuzz 1.4.7 (see [bug 1382083](https://bugzilla.mozilla.org/show_bug.cgi?id=1382083)). However the problem doesn’t appear to me. First. I opened [WYMeditor integration example](https://wymeditor.github.io/wymeditor/dist/examples/01-basic.html) in Firefox, then I input the following code for test:
```
<p style="font-family: MingLiU; font-size: 1.8em; writing-mode: vertical-rl">測試abg測試</p>
```
Then I saw all characters works as expected.
![1](https://i.imgur.com/rb5xzUY.png)

**Comment by KrasnayaPloshchad** [comment]
I tested again with hb-shape, it performanced the same as 1.3.4.

harfbuzz-1.4.7-win32\hb-shape --font-funcs=ot --shaper=ot --font-size=72 --direction=ltl --font-file="C:\Windows\Fonts\mingliu.ttc" --text= 測試
[gid15828=0+72|gid23054=1+72]

harfbuzz-1.4.7-win32\hb-shape --font-funcs=ot --shaper=ot --font-size=72 --direction=ttb --font-file="C:\Windows\Fonts\mingliu.ttc" --text= 測試
[gid15828=0@-36,-58+0,-72|gid23054=1@-36,-58+0,-72]

**Comment by marklh9** [comment]
@KrasnayaPloshchad 
I'm sorry to mislead you. Harfbuzz 1.3.3 is the last version that worked correctly with LibreOffice. Harfbuzz 1.3.4 is the first version that failed. I'd  compare Firefox 56 to some version that use Harfbuzz 1.3.3 or before. But which version do you suggest? I'm not a Firefox developer so it will take some time to dig the answer on my own.

Note that the text line in your test start from the left side of the screen and consist only one line. I'd prefer to produce a test that have multiple TTB lines and start from the right side of the screen.

**Comment by KrasnayaPloshchad** [comment]
Oh sorry, so it’s hard to know how does Fx developer made it works. BTW I found coping the following code into WYMeditor page you will see the text will be automatically hignlighted and it won’t be shifted.
```
<p><span style="font-family: MingLiU; font-size: 1.8em; writing-mode: vertical-rl">測試abg測試</span></p> 
```

**Comment by KrasnayaPloshchad** [comment]
CC @jfkthame

**Comment by marklh9** [comment]
@KrasnayaPloshchad Do you know what vertical and horizontal displacement mean and what the origin of the coordinate system they use when it comes to TTB?

Glyph shifting in LibreOffice is caused by displacement changes introduced in Harfbuzz 1.3.4.
The dx and dy values of hb-shape output  ( summarized from below )
For 1.3.3 ot functions:  (dx":-500,"dy":-1160 )
For 1.3.3 ft functions:  (dx": 0,"dy":0 )
For 1.3.4 ot functions: ("dx":-500,"dy":-880)

Despite dx and dy changes in HarfBuzz 1.3.4 caused issues in LibreOffice, those values get closer to ft functions values. Is that expected from HarfBuzz's point of view?

------- 1.3.3 ------- ot lang zh-TW
./harfbuzz-1.3.3/util/hb-shape --direction=ttb --font-funcs=ot --show-extents --output-format=json --language=zh-TW /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc 中文
[
{"g":"gid9893","cl":0,"dx":0,"dy":0,"ax":0,"ay":-1000,"xb":0,"yb":0,"w":0,"h":0},
{"g":"gid20434","cl":1,"dx":0,"dy":0,"ax":0,"ay":-1000,"xb":0,"yb":0,"w":0,"h":0}]
------- 1.3.3 ------- ft lang zh-TW
./harfbuzz-1.3.3/util/hb-shape --direction=ttb --font-funcs=ft --show-extents --output-format=json --language=zh-TW /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc 中文
[
{"g":"gid9893","cl":0,"dx":-500,"dy":-880,"ax":0,"ay":-1000,"xb":100,"yb":837,"w":799,"h":-913},
{"g":"gid20434","cl":1,"dx":-500,"dy":-880,"ax":0,"ay":-1000,"xb":40,"yb":842,"w":923,"h":-917}]
------- 1.3.4 ------- ot lang zh-TW
./harfbuzz-1.3.4/util/hb-shape --direction=ttb --font-funcs=ot --show-extents --output-format=json --language=zh-TW /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc 中文
[
{"g":"gid9893","cl":0,"dx":-500,"dy":-1160,"ax":0,"ay":-1000,"xb":0,"yb":0,"w":0,"h":0},
{"g":"gid20434","cl":1,"dx":-500,"dy":-1160,"ax":0,"ay":-1000,"xb":0,"yb":0,"w":0,"h":0}]
------- 1.3.4 ------- ft lang zh-TW
./harfbuzz-1.3.4/util/hb-shape --direction=ttb --font-funcs=ft --show-extents --output-format=json --language=zh-TW /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc 中文
[
{"g":"gid9893","cl":0,"dx":-500,"dy":-880,"ax":0,"ay":-1000,"xb":100,"yb":837,"w":799,"h":-913},
{"g":"gid20434","cl":1,"dx":-500,"dy":-880,"ax":0,"ay":-1000,"xb":40,"yb":842,"w":923,"h":-917}]

**Comment by KrasnayaPloshchad** [comment]
I have no idea for the vertical and horizontal displacement means, but the origin of the coordinate system they used looks is designed to make the strikethrough always go through the middle of upright glyphs.

**Comment by khaledhosny** [comment]
@behdad Apparently the fix on LibreOffice size is to call `hb_font_add_glyph_origin_for_direction()` on the x and y offsets when direction is vertical. Does this make any sense to you?

**Comment by behdad** [comment]
> @behdad Apparently the fix on LibreOffice size is to call hb_font_add_glyph_origin_for_direction() on the x and y offsets when direction is vertical. Does this make any sense to you?

It doesn't.  I have to spend some time understanding what's going on.  Can you point me to the font-funcs impl in LibreOffice?

**Comment by khaledhosny** [comment]
We use ot font-funcs without any modification.

**Comment by marklh9** [comment]
Hi @behdad ,
Here is my patch on LibreOffice gerrit for reference.
https://gerrit.libreoffice.org/#/c/44556/

**Comment by marklh9** [comment]
I tried to explain my point of view here: https://github.com/behdad/harfbuzz/pull/619

**Comment by KrasnayaPloshchad** [comment]
LibreOffice bugzilla reported they have fixed it recently, so this should be LibreOffice bug, not related with HarfBuzz.

**Comment by marklh9** [comment]
It's more like a question about how I can implement vertical writing correctly. Let's close the issue for now.

**Comment by KrasnayaPloshchad** [comment]
The problem is appearing with Hentaigana fonts. I found BabelStone Han and [UniHentaiKana](http://wakufactory.jp/densho/font/hentai/) fonts has different behavior in vertical layout. With BabelStone Han Hentaigana characters works within the box, but combining dakuten failed. With UniHentaiKana characters run out of the box.

hb-shape --font-funcs=ot --shaper=ot --font-size=72 --direction=ttb --font-file="C:\Windows\Fonts\BabelStoneHan.ttf" --unicodes="1B05B 1B0A6 3099"
[u1B05B=0@-36,-72+0,-72|u1B0A6=1@-36,-72+0,-72|uni3099=1@0,-72+0]

hb-shape --font-funcs=ot --shaper=ot --font-size=72 --direction=ttb --font-file="C:\Windows\Fonts\UniHentaiKana-Regular.otf" --unicodes="1B05B 1B0A6 3099"
[gid94=0@-36,-63+0,-72|gid290=1@-36,-63+0,-72]

hb-view C:\Windows\Fonts\BabelStoneHan.ttf --unicodes="1B05B 1B0A6 3099" --font-size=72 --direction=ttb --output-format=png --output-file=soba.png
![1](https://i.imgur.com/9RQ3rSv.png)
hb-view C:\Windows\Fonts\UniHentaiKana-Regular.otf --unicodes="1B05B 1B0A6 3099" --font-size=72 --direction=ttb --output-format=png --output-file=soba2.png
![2](https://i.imgur.com/plIH1VX.png)

**Comment by babelstone** [comment]
I was using positioning for the combining dakuten in BabelStone Han, but I have just changed the font to use glyph substitution instead, and now hentaigana plus combining dakuten work as expected in vertical layout (tested using HB 1.6.3). I will release a new version of the font later today or tomorrow.
![soba](https://user-images.githubusercontent.com/20558386/34060331-173b26d6-e1db-11e7-95a5-9727f0bb3a42.png)

**Comment by babelstone** [comment]
I've released a new version of BabelStone Han ([v. 10.0.2](http://www.babelstone.co.uk/Fonts/Han.html)) which seems to behave correctly with harfbuzz. Therefore I do not think there is a problem with harbuzz with vertical layout of hentaigana.

**Comment by KrasnayaPloshchad** [comment]
> Do you know what vertical and horizontal displacement mean and what the origin of the coordinate system they use when it comes to TTB?

It seems to me that Firefox is intended to do default behaivor of [`dominent-baseline`](https://www.w3.org/TR/css-inline-3/#dominant-baseline-property) property.

**Comment by KrasnayaPloshchad** [comment]
> Do you know what vertical and horizontal displacement mean and what the origin of the coordinate system they use when it comes to TTB?

It seems to me that Firefox is intended to do the default behaivor of [`dominant-baseline`](https://www.w3.org/TR/css-inline-3/#dominant-baseline-property) property. Such functionality should be built into HarfBuzz itself.

**Comment by behdad** [comment]
This needs to be tested again as I've fixed vertical placement recently.

**Comment by HinTak** [comment]
The dynalab kai misrendering is a freetype problem but should be worked around in recent freetype (less than 10 year old...). Is there anything unusual about your kaiu.ttf ? Like it has been modified by you yourself?

**Comment by HinTak** [comment]
Kaiu.ttf is one of the tricky fonts - see https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_face_flag_tricky - the question is why your usage seems to have the switched off the tricky flag (which is internal / automatic in freetype as far as I know)

**Comment by HinTak** [comment]
DFKai-SB is hard-coded in https://github.com/servo/libfreetype2/blob/f801061ee57dac0937cccffb0f7bf3fa120208f5/freetype2/src/truetype/ttobjs.c#L157

**Comment by marklh9** [comment]
@HinTak the broken one is created with --func-funcs=ot, i.e. it's from Harfbuzz instead of Freetype, but the information you provided is invaluable! I almost regard those fonts as standard because they are shpped with tradtional Chinese Windows. It becomes clear why only these fonts are borken now. Thank you!

**Comment by HinTak** [comment]
Well, mingliu and kaiu are common enough, and yet technically unusual, that the freetype developers deem the unusualness worth special-case consideration for, it it is hardcoded to auto-detect and workaround automatically applied. The question is why the auto-detect does not work - part of the auto-detection is just name (which is a clear exact match), but in addition to that, freetype can also cope if the font name is modified, based on the checksum of some of the tables I think. So I am wondering how you by-pass the fontname check; or is that a problem of harfbuzz calling freetype not passing the fontname info along.

**Comment by khaledhosny** [comment]
These “tricky” fonts require hinting and HarfBuzz does not support hinting. Since 4.0, `hb-view` is using HarfBuzz draw API to draw the glyphs, so with `ot` font functions no hinting is applied. This is orthogonal to the original issue. You can disable use of draw API by setting `HB_DRAW` env variable to 0 to test these fonts.

**Comment by khaledhosny** [comment]
Based on https://github.com/harfbuzz/harfbuzz/issues/573#issuecomment-1079549380 I think this issue is fixed.
