### ISSUE TITLE
hb-dsalgs.hh

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#593]
Just filing this to dump what I like to do.  I don't have time to do it right now, just logging for now.

We have hb_sort_r() and hb_bsearch_r() now.  Rename hb_sort_r() to hb_qsort_r(), and then add native implementation of hb_qsort() and hb_bsearch() as well as use them instead of system ones.  Since qsort is recursive, it won't inline well.  For bsearch, try templatizing it and see if it can be vectorized for certain types.

Add in-place mergesort (I have acquired a relicensed version of https://github.com/liuxinyu95/AlgoXY/blob/algoxy/sorting/merge-sort/src/mergesort.c from its author). Make it a `_r` version.  Use it instead of our current insertion-sort.

For both qsort and mergesort, add a version that takes a swap() function, such that we can sort two parallel arrays, like hb_buffer_t::sort().  Also, use bsearch_r() for CmapSubtableFormat4::accelerator_t::get_glyph_func().

In general, consolidate all search and sort functions.

Then add hb_prealloced_array_t and hb_lockable_set_t from hb-private.hh to hb-dsalgs.hh.  At some point implement a hashmap. Maybe public? Integer->integer only?

**Comment by ebraminio** [comment]
> For bsearch, try templatizing it and see if it can be vectorized for certain types.

This sounds very interesting given how hot bsearch is! How I should profile harfbuzz fairly?
