### ISSUE TITLE
Some Zanabazar Square sequences do not render as expected

### ISSUE THREAD

**Issue by babelstone** [harfbuzz/harfbuzz#617]
I'm working on a font for the Zanabazar Square script introduced in Unicode 10.0 this year, and during testing with HarfBuzz 1.6.3 I've found some issues with sequences including the vowel length mark (U+11A0A) or with two vowel signs. In the examples on pages 5-6 of Anshuman Pandey's [proposal to encode Zanabazar Square](http://www.unicode.org/L2/L2015/15337-zanabazar-square.pdf) he puts the vowel length mark after the vowel signs I, UE, U, E, OE, O, and Reversed I, but before the vowel signs AI and AU. However, there does not seem to be a canonical order for vowel signs and the vowel length mark (all have ccc=0), and we cannot predict what order users will input vowel signs, so my font includes OT substitutions for all possible legal sequences of vowel signs and vowel length mark. However, some of these sequences do not render as expected with HarfBuzz.

**Test 1. Single vowel vowel length mark**
Using [ZanabazarVowelsTest.txt](http://www.babelstone.co.uk/Fonts/Zanabazar/ZanabazarVowelsTest.txt) I get the results shown below.

![zanabazarvowelstest10](https://user-images.githubusercontent.com/20558386/32703287-7c89d30c-c7eb-11e7-9fec-efacc89e3d5f.png)
If the vowel length mark follows the vowel sign it renders correctly in all cases. But if the vowel length mark precedes the vowel sign, it renders correctly if the vowel is below the consonant (UE and U), but not if the vowel is above the consonant (I, E, OE, and O).

**Test 2. Diphthongs**
Using [ZanabazarDiphthongsTest.txt](http://www.babelstone.co.uk/Fonts/Zanabazar/ZanabazarDiphthongsTest.txt) I get the results shown below.

![zanabazardiphthongstest10](https://user-images.githubusercontent.com/20558386/32703322-16a6c74c-c7ec-11e7-9eea-a5bbc6deeee7.png)
This tests the 12 diphthongs listed on p. 6 of Anshu's proposal, with the sequence given by Anshu first on each line, followed by alternative sequences which I believe should render identically. All the sequences are supported in my font, and I have tested that all sequences work using VOLT. However, with HarfBuzz some sequences do not render as expected.

For the ii, iu, ei, oi, and ou ligatures, both orders of the two vowel signs render correctly, but in the case of the üi and ui ligatures, the sequences "Consonant AI UE" and "Consonant AI U" work but the sequences "Consonant UE AI" and "Consonant U AI" do not. For sequences with a vowel length mark, only certain sequences where the vowel length mark is the final or penultimate character in the sequence render as expected.

I hope that HarfBuzz can support all possible sequences of vowel signs and vowel length marks for Zanabazar Square. I have made a cut down test version of my font available for testing [here](http://www.babelstone.co.uk/Fonts/Zanabazar/BabelStoneZanabazarTest.ttf).

**Comment by behdad** [comment]
I won't be able to make sense of this alone. Maybe @jfkthame can advise.

**Comment by jfkthame** [comment]
> In the examples on pages 5-6 of Anshuman Pandey's proposal to encode Zanabazar Square he puts the vowel length mark after the vowel signs I, UE, U, E, OE, O, and Reversed I, but before the vowel signs AI and AU.

This is curious, given that it seems to conflict with the orthographic syllable structure presented in section 4.2 (page 4) of that same proposal document, which tells us it should be:

    V_{carrier} [V_{sign}*] [M_{length}] [C M_{final}]

I think the first thing to do here is to raise a query with Anshu, and see if we can get this clarified. Given that Unicode normalization can't help us here, I'd prefer to support a single well-defined ordering, rather that "anything goes"; but this depends on establishing a consensus as to what the accepted ordering is.

cc @pandey

**Comment by babelstone** [comment]
For me, I find it odd to put the length mark after a vowel sign (and even odder to put it between two vowel signs) because the mark corresponds to Tibetan a-chung (U+0F71) which is placed between consonant and vowel signs. Furthermore the Zanabazar length mark attaches (ligates) to the preceding consonant so I feel intuitively that it belongs after the consonant and before any vowel signs.

From a font implementation point of view it is much easier for me to deal with the the length mark using OT substitutions if it is not separated from the preceding consonant by one or more vowel signs. For example, for a sequence "C M V" I can simply substitute C M -> CM (ligatured consonant and length mark glyph) and just position the following vowel sign above or below the CM glyph. But for a sequence "C V M" I cannot directly substitute the ligatured consonant and length mark glyph; and things get a lot more complicated with complex clusters with one or more subjoined consonants and more than one vowel sign.

I would like the Unicode Standard to specify the encoding order so that end users and implementers can have a common understanding of how to write Zanabazar Square script. And my preference would be to define the order as C M V (this is just an example for a simple cluster). But if the Unicode Standard does not specify an encoding order I think we must support all legal sequences of characters forming a cluster (i.e. C M V and C V M, but not sequences such as C V Cluster-Final-Consonant). If HarfBuzz decides to only support one particular order we run the risk of other implementations supporting a different order, resulting in incompatibility across platforms.

**Comment by KrasnayaPloshchad** [comment]
Here is a document including all test cases copied from [BabelStone Zanabazar](http://www.babelstone.co.uk/Fonts/Zanabazar.html) page, produced using LO 6.01.

[Zanabazar_Test.zip](https://github.com/harfbuzz/harfbuzz/files/1745087/Zanabazar_Test.zip)

**Comment by behdad** [comment]
Anyone wants to summarize what needs to be done here?
