### ISSUE TITLE
Move documentations to harfbuzz/harfbuzz.github.io

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#624]
previous location of live documentation behdad.github.io/harfbuzz is broken now and harfbuzz.github.io/harfbuzz can be used instead. I think it is better to to go further and separate gh-pages into harfbuzz/harfbuzz.github.io to remove need of /harfbuzz on urls. Recently added config.yml also can be removed as no dummy circleci config would be needed for a separate repo. Token of that repo should be set on travisci environment variables.

**Comment by behdad** [comment]
Yes please.  I hate having gh_pages in the same git repo. Oh and link to the docs!
