### ISSUE TITLE
[coretext] Add hb_coretext_font_create()

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#628]
https://bugs.chromium.org/p/chromium/issues/detail?id=785522

**Comment by ebraminio** [comment]
Maybe reviving parts of #367 instead?

**Comment by behdad** [comment]
> Maybe reviving parts of #367 instead?

Same comment as https://github.com/harfbuzz/harfbuzz/pull/367#issuecomment-263238372
That is: a CGFont is a font face, CTFont is a font face plus font size. Same in HB: hb_face_t is a font face, hb_font_t is a font face plus size.  So the CGFont=hb_face_t / CTFont=hb_font_t is the right abstraction.

Plus, hb-coretext is extremely fragile.  I prefer this small change.

**Comment by ebraminio** [comment]
Definitely fragile, my change also had some unexpected results, I hope we implement AAT shaper someday.

**Comment by behdad** [comment]
> I hope we implement AAT shaper someday.

Sascha and I are sitting down together to work on that second week of January.
