### ISSUE TITLE
What's the purpose of this project?

### ISSUE THREAD

**Issue by mehrdaad** [harfbuzz/harfbuzz#631]
Hi,  
Sorry if the question seems irrelevant. But I couldn't find any purpose this project follows or any problem this project tries to solve.  
Can provide some info? tnx

**Comment by ebraminio** [comment]
HarfBuzz is a low-level typesetter used on many of projects, specially on non-Microsoft or Apple products. Here is some documentations that can give an overview to harfbuzz:

* http://behdad.org/text/
* https://www.freedesktop.org/wiki/Software/HarfBuzz/
* https://harfbuzz.github.io
* https://en.wikipedia.org/wiki/HarfBuzz

HarfBuzz already is in use on many software projects as the only option available and has reached its goals but supporting some other features like Apple specific font features is in its roadmap.

You may still wonder why harfbuzz has not that rich set of documentations and the same may applies to harfbuzz counterpart on Windows, Uniscribe https://maxradi.us/documents/uniscribe/ The main reason is harfbuzz is not suitable for directly use on many projects as it is only provides one of the parts for constructing a complete text rendering stack and a higher level library like https://en.wikipedia.org/wiki/Pango bringing together other pieces of a text rendering stack such as itemization, bidi algorithm, vector rasterization is usually what other projects should use directly instead.

Closing the issue but let us know right here if there are still unclear things. Cheers
