### ISSUE TITLE
Appveyor is stopped and its badge is incorrect

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#634]
Apparently appveyor doesn't recognize the GitHub organizations concept and for some reasons it also stopped. Behdad, can you first go to https://ci.appveyor.com/project/behdad/harfbuzz/settings/delete delete the project and create it from https://ci.appveyor.com/projects/new again? If you couldn't find harfbuzz/harfbuzz between available projects, you should logout and on logging in, give access of harfbuzz organization to appveyor.

After that please copy the badge code from https://ci.appveyor.com/project/behdad/harfbuzz/settings/badges to https://github.com/harfbuzz/harfbuzz/blob/master/README#L2 I guess my change on changing behdad/harfbuzz to harfbuzz/harfbuzz was incorrect.

I could do this but it will added to ebraminio/harfbuzz instead and its failure builds emails will be delivered to me.

**Comment by khaledhosny** [comment]
https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization

**Comment by anthrotype** [comment]
yeah, I remember we had to do the same when we moved behdad/fonttools over to fonttools/fonttools, and also with skia-pathops from khaled's repo.

it should work if you delete the old web hook and an admin re-registers the github repo with new organizational appveyor account.

**Comment by ebraminio** [comment]
That sounds fantastic, deleted the broken web hook. So we should follow this instead,

> You should have a separate email address which does not exist in AppVeyor and will be used as “organizational” account owner, for example {organization}-appveyor@your-domain.com. Go to Sign up page and register a new account with that email and password. For “Your name” use something like “{organization} admin”.

So we need some email to start with? Perhaps Behdad should do that?

**Comment by behdad** [comment]
Both of you can set this up yourself.  We already have the harfbuzz-admin@googlegroups.com, so you can set that up.  You can even make up infinite new addresses by adding "+whatever" after "harfbuzz-admin".

Thanks

**Comment by ebraminio** [comment]
So this is fixed I guess, thanks @khaledhosny @anthrotype @behdad
