### ISSUE TITLE
[Question] Difference between Consonants and Dead Consonants in syllable identification

### ISSUE THREAD

**Issue by n8willis** [harfbuzz/harfbuzz#637]
I'm unclear on how HarfBuzz matches syllables when there are CONSONANT_DEADs in the run.

In Bengali, it would appear that the explicit Khanda Ta (U+09CE) gets treated like a "normal" consonant, but in practice (AIUI) it is not entered with an accompanying Halant mark. That would mean that, in a mid-word position, the syllable-matching regular expression would identify it as the base consonant. Which would affect Reph placement.

The specific example that brought this to my attention is the word "bhortsona", as is discussed in this Apple thread: https://discussions.apple.com/message/28232883#28232883

The string is U+09AD, U+09B0, U+09CD, U+09CE, U+09B8, U+09A8, U+09BE ... although I think the operative part is just U+09B0, U+09CD, U+09CE, U+09B8 (Ra, Halant, Khanda Ta, Sa). hb-view indicates that HarfBuzz positions the Reph over the Khanda Ta with Murty Bangla, and tries to (?) with Noto Serif Bengali Regular. The Reph actually ends up in between the Khanda Ta and the Sa.

I'm not taking a position on what the correct behavior is in this case (based solely on the Apple support thread); I'm just trying to understand how the syllable-matching algorithm works. I have not found a detailed discussion on how dead consonants are meant to be handled here (which, admittedly, might have different answers for Bengali and Malayalam).

Murty:
![khandata-murty](https://user-images.githubusercontent.com/2192132/33611473-69e42526-d9c6-11e7-8241-2afef2421e8b.png)

Noto Serif Reg:
![khandata-notoserif](https://user-images.githubusercontent.com/2192132/33611474-69fffe04-d9c6-11e7-8e46-19385551ca96.png)

**Comment by behdad** [comment]
Your analysis sounds right to me.  The right question to ask re Indic shaper is, what does Uniscribe does with this?

Also, am I right to think that explicit Khanda Ta is a deprecated sequence?

**Comment by n8willis** [comment]
On the second point, actually I think I've read that there are some words where using Khanda Ta is required, to distinguish a Bengali word from a loanword, i.e. one uses Khanda Ta and the other uses Ta-Halant. I think that was in one of the Unicode PRI-30 documents supporting adding Khanda Ta as a separate codepoint, as a recent linguistic development.

(Still an open question on Uniscribe behavior)

**Comment by dscorbett** [comment]
The preferred representation of khanda ta is U+09CE. “র্ৎস” is syllabified into “র্ৎ” and “স” by both HarfBuzz and Uniscribe. It looks wrong in Noto Serif Bengali because of googlei18n/noto-fonts#1055.

The old sequence U+09A4 U+09CD U+200D is deprecated. If it is used, both HarfBuzz and Uniscribe consider “র্ত্‍স” a single syllable, so the reph goes above the sa instead of the khanda ta.

**Comment by behdad** [comment]
Anything to be done here?

**Comment by n8willis** [comment]
I defer completely to @dscorbett on whether or not there is a HarfBuzz bug here.

**Comment by dscorbett** [comment]
It’s not a HarfBuzz bug.
