### ISSUE TITLE
Add function for scripts that should disable letter-spacing?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#64]
According to Roozbeh these scripts have a cursive connection and as such can't take letter-spacing:

Arabic, Syriac, N'Ko, Manichaean, Psaltar Pahlavi, Mandaic, Mongolian, Phags-pa,
Devanagari, Bengali, Gurmukhi, Modi, Sharada, Syloti Nagri, Tirhuta,
Ogham

Not sure how useful it is to enumerate them somehow in HarfBuzz.  @jfkthame WDYT?

**Comment by roozbehp** [comment]
New information I found from a Hindi map I found in Bern, and discussions with Vivekanand Pani at the Unicode Conference: there is indeed letter-spacing in languages of India, but it's syllable-based, with a yet-unclear definition of syllable. Attaching my photo. ![img_20161015_180022](https://cloud.githubusercontent.com/assets/302255/20116330/af7a2ed2-a5b0-11e6-935d-5b46c6501497.jpg)

**Comment by behdad** [comment]
Thanks Roozbeh!

**Comment by ebraminio** [comment]
Hey there, see #1505

**Comment by ebraminio** [comment]
Sad to see such information is scattered everywhere https://github.com/flutter/engine/blob/f38f03fc883c8006f0896f61ff91acd9171e4453/third_party/txt/src/minikin/Layout.cpp#L400 even the fact we could provide that in similar to DirectWrite way.

If you don't like all of the #1505 provides, fine, lets break it, the point of that was to have a baseline of what we 'can' provide but everyone got that as going to be merge immediately change.

**Comment by Manishearth** [comment]
@roozbehp yeah so I had previously proposed to Unicode that for Indic writing systems that default to conjuncts (Devanagari but not Tamil) treat consonant clusters as a single EGC. I believe there was a draft of UAX 29 that included this, as well, but it was removed for reasons I cannot recall. 

This would be sufficient to fix the issue around Indic.
