### ISSUE TITLE
Incorrect assumption that sizeof(unsigned long) == sizeof(void*)

### ISSUE THREAD

**Issue by randomascii** [harfbuzz/harfbuzz#640]
In this line of code:

https://github.com/harfbuzz/harfbuzz/blob/be59f3cbf4e3269ea05d5a707cdae04a32e097ce/src/hb-debug.hh#L96

(which was recently copied from src/hb-private.hh) we have this:

    fprintf (stderr, "(%0*lx) ", (unsigned int) (2 * sizeof (void *)), (unsigned long) obj);

This code casts a pointer to unsigned long. However the assumption that sizeof(unsigned long) == sizeof(void*) is unjustified. On the Windows platform when compiling for 64-bits (whether compiling with VC++ or with clang-cl) the size of unsigned long is *always* 32 bits. That is, even in 64-bit builds an unsigned long is 32 bits.

A couple of fixes are available. Using unsigned long long is more portable - casting to a 64-bit type in 32-bit builds is not so terrible. Or, using %z as a size modifier and using size_t as the integer type will also work - %z has been supported on Windows since VC++ 2015.

This code triggers warnings in the latest preview builds of VC++ 2017 when compiling with /permissive- which is a switch that aggressively looks for non-portable code.

**Comment by behdad** [comment]
How portable is %z?  Umm, I'm not sure why I didn't use %p.  Is that supported-enough?

**Comment by randomascii** [comment]
%z should be a portable way to specify size_t as long as VC++ 2013 support is not needed. However %p would be even better - it is more broadly portable (every compiler supports it) and it is also simpler.

**Comment by behdad** [comment]
Thanks.  Feel like sending a Pull Request?

**Comment by behdad** [comment]
Or I can do myself.

**Comment by randomascii** [comment]
I wouldn't be able to conveniently test my PR so I'm happy to have you make the fix if that's okay.
