### ISSUE TITLE
font->klass(font functions) is never destroyed(memory leak?)

### ISSUE THREAD

**Issue by ribhukhaneja** [harfbuzz/harfbuzz#654]
**Some background:**
I am using my own memory manager by overloading the standard free/malloc/realloc methods.
Here is how I am creating and destroying the HarfBuzz font:
`hb_font = hb_ft_font_create(ft_face, nullptr);`
`hb_font_destroy(hb_font);`
And after hb_font_destroy(), I can see one memory buffer which was acquired in the creation, is not released after the destruction.  

**Some findings:**
- under _hb_ft_font_set_funcs() I can see that the `hb_font_funcs_t *funcs` is being made inert by `hb_object_make_inert(funcs);`
- hb_font_set_funcs() sets the `font->klass = klass`, where "klass" is our "funcs".
- hb_font_destroy() wouldn't really "destroy" the allocated font functions. 
`void hb_font_destroy (hb_font_t *font)`
`{`
`...`
`hb_font_funcs_destroy (font->klass); /* does not destroy font->klass because it was made inert */`
`...`
`}`

**Comment by behdad** [comment]
What HarfBuzz version are you using? 1.6.1?  If yes, that had a bug re this same thing.  Try latest release please. There's no `hb_object_make_inert()` anymore. It only was in that one broken version.

**Comment by ribhukhaneja** [comment]
Thanks for the prompt reply! 
I have now updated to the latest version and indeed there is no `hb_object_make_inert()`.

But now a different problem comes up: 
because of `hb_font_funcs_reference (klass)` under `hb_font_set_funcs()` the ref_count(v) of the klass is increamented to 2 
and in the end `hb_font_funcs_destroy()` just deceares the counter without releasing/freeing the actual memory.

**Comment by behdad** [comment]
The last reference is freed by free_static_ft_funcs() in an atexit() callback when the process terminates.
