### ISSUE TITLE
Support for Tai Tham (lana)

### ISSUE THREAD

**Issue by mjansche** [harfbuzz/harfbuzz#671]
(Moved from https://github.com/googlei18n/noto-fonts/issues/1022)

HarfBuzz does not appear to support Tai Tham reordering at the moment (tag 1.7.4).

Compare the behavior for Myanmar vs. Tai Tham on strings of corresponding characters ("kre"):

```
hb-view -u '1a20 1a55 1a6e' NotoSansTaiTham-Regular.ttf > TaiTham.png  # bad
hb-view -u '1000 103C 1031' NotoSansMyanmar-Regular.ttf > Myanmar.png  # good
```

Myanmar reordering works as expected, i.e. modifiers appear left of base:

![myanmar](https://user-images.githubusercontent.com/11460451/34496636-1f1b9b54-eff2-11e7-8b95-d52deb9c73ee.png)

Tai Tham reordering does not work as expected. Modifiers should appear left of base, but do appear right of base:

![taitham](https://user-images.githubusercontent.com/11460451/34496656-39932c72-eff2-11e7-836c-f83f1ddb6b09.png)

Some minimal, incomplete reordering appears to be happening; the current rendering corresponds to 1a20 1a6e 1a55, which is different from the character ordering in the input string.

The Tai Tham font used is https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansTaiTham-Regular.ttf (fontRevision "1.04", created "Wed Jan 9 14:35:23 2013", modified "Tue Dec 29 19:03:33 2015").

By comparison, Tai Tham renders as expected in TextEdit on macOS 10.12.

I'm unable to compare against Windows, but at least the documentation for the Universal Shaping Engine lists Tai Tham (script code "lana") as one of the supported scripts.

**Comment by mhosken** [comment]
This is because the NotoSansTaiTham font is using the DFLT shaper rather than USE. But, there are issues with USE not adequately supporting Tai Tham. For example, the USE rejects subjoined finals following spacing vowels (that happens in about 20% of words).

**Comment by punchcutter** [comment]
That version of Noto Sans Tai Tham is very old. The new version will reorder in harfbuzz as expected, but the example above does not follow the USE spec. 1a20 1a6e 1a55 is B VPre MPre, but the USE spec requires MPre to come before VPre. So I can tell you 1a20 1a55 1a6e works with the new version of the font, but I don't know when it will be released. I don't think this issue needs to be open because harfbuzz is doing what's expected.

**Comment by jfkthame** [comment]
OK, let's close this, and just wait for the updated font.
