### ISSUE TITLE
Add API to get glyph alternates

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#673]
Such that apps can do fancy GUI.

**Comment by Tavmjong** [comment]
I've been working on a Font Features dialog for Inkscape and would love to have this implemented. Using hb_ot_layout_lookup_collect_glyphs, one can git a list of input and output glyphs but cannot tell absolutely which output glyph corresponds to which input glyph if there is not a one-to-one correspondence as with a type 3 lookup table.

**Comment by ebraminio** [comment]
AAT's [Zapf](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6Zapf.html) also provides info related to this.

**Comment by behdad** [comment]
> AAT's [Zapf](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6Zapf.html) also provides info related to this.

That table is pretty big and very few fonts use it.  I'm hesitant to expose it, at least not before we expose OpenType GSUB properly first.

**Comment by behdad** [comment]
Any volunteers for this?

**Comment by ebraminio** [comment]
> Any volunteers for this?

Please explain what sort of API should be exposed for this.

**Comment by behdad** [comment]
For starters this would do:
```
HB_EXTERN hb_bool_t
hb_ot_layout_lookup_get_alternates (hb_face_t            *face,
                                    unsigned int          lookup_index,
                                    hb_codepoint_t    glyph,
                                    unsigned int         start_offset,
                                    unsigned int         alternate_count,
                                    hb_codepoint_t   *alternate_glyphs)
                                     ;
```

But maybe we can rename `get_substitutes` and make it work for single, alternate, and multiple substitutes and return a type enum.

In that case maybe can also take glyphstring and also work for ligatures.  That's very similar to `would_substitute` API already.  I think I like the latter.

**Comment by behdad** [comment]
Khaled, can you please work on this?  I'm surprised you went the tour to parsing GSUB yourself instead.

https://twitter.com/KhaledGhetas/status/1212830043602337792?s=19

**Comment by khaledhosny** [comment]
I looked into implementing the proposed API above first, but got overwhelmed by HarfBuzz internals, and it would have taken me too much time than it took me to write the 200 hundred or so JavaScript lines I needed to parse the few lookup types I needed for this project (I control the font, so I can do partial implementations and unsafe assumptions).

**Comment by behdad** [comment]
Fair enough.  Can you please comment on the API based on your learning?  I can give this a try.  Should be a dozen lines of code at it's core.

**Comment by khaledhosny** [comment]
I think the `would_substitute`-like API is fine. I used `would_substitute` and was quite happy with it.

One issue I had with it is ligatures, to reliably get all ligature substitutions involving the current glyph, I need to try it with all subsequent glyphs adding one at a time, i.e. if I have the string `abcdef` and I want to check ligatures involving the `a` glyph, I need to try `ab`, `abc`, `abcd`, `abcde`, and `abcdef` as input since I don’t know if `a` is involved in any ligatures at all and if yes what is the maximum length of such ligatures. When reading the GSUB lookups directly I can optimize this a bit by checking if `a` is in the lookup coverage at all, the max `componentCount`, etc.

**Comment by khaledhosny** [comment]
Contextual lookups propably suffer from the same issue, but I didn’t need to work with these.

**Comment by behdad** [comment]
That's good feedback.  Let me think.

**Comment by behdad** [comment]
I'm thinking that we should add the glyph-alternate API separate from ligature API.  Am not sure, but sounds like that would simplify things.  That wouldn't address contextual glyph alternates though.

**Comment by liamquin** [comment]
Any news on this? We get occasional requests for GIMP to access alternate glyphs too.

**Comment by behdad** [comment]
Okay let's do a version that works only for one-to-one alternates.  We'll add the context-aware versions and ligatures etc separately when we converge on the design.

Back to:
```
HB_EXTERN hb_bool_t
hb_ot_layout_lookup_get_alternates (hb_face_t            *face,
                                    unsigned int          lookup_index,
                                    hb_codepoint_t    glyph,
                                    unsigned int         start_offset,
                                    unsigned int         alternate_count,
                                    hb_codepoint_t   *alternate_glyphs)
                                     ;
```

It's inconvenient that takes `lookup_index` and user should know to collect all lookup indices for the right feature and to look over them and then ???

**Comment by ebraminio** [comment]
#2471

**Comment by ebraminio** [comment]
Have closed this by #2473, sure it misses things as "context-aware versions and ligatures etc" and the clients need to search the different GSUB lookups for alternates maybe using 

```
unsigned lookup_count = hb_ot_layout_table_get_lookup_count (face, HB_OT_TAG_GSUB);
for (unsigned lookup = 0; lookup < lookup_count; ++lookup)
  hb_ot_layout_lookup_get_alternates (face, lookup, ...)
```

yet it can be considered a good starting point and we can address those specially when there are demand and fonts using those.

**Comment by ebraminio** [comment]
And we don't provide a way to alter hb_buffer_t using chosen alternates yet but something achievable already by the clients like the way https://alif-type.github.io/rana-kufi/ works and sure we can provide more by analyzing usage of other clients.

**Comment by ebraminio** [comment]
> > AAT's [Zapf](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6Zapf.html) also provides info related to this.
> 
> That table is pretty big and very few fonts use it. I'm hesitant to expose it, at least not before we expose OpenType GSUB properly first.

Per https://gist.github.com/ebraminio/d52dd780fec59f8e2dfffe8e1a841823 there are 97 'Zapf' tables across the default Apple fonts, however we should start first with fonttools support, fonttools/fonttools#2000

**Comment by behdad** [comment]
> Per https://gist.github.com/ebraminio/d52dd780fec59f8e2dfffe8e1a841823 there are 97 'Zapf' tables across the default Apple fonts, however we should start first with fonttools support, [fonttools/fonttools#2000](https://github.com/fonttools/fonttools/issues/2000)

I still don't think that's a good idea.  We build for the future, not the past..

**Comment by behdad** [comment]
> And we don't provide a way to alter hb_buffer_t using chosen alternates yet

I don't know what you mean.  Users enable such alternates by setting OpenType features (`salt`, `aalt`, etc).

**Comment by ebraminio** [comment]
> I still don't think that's a good idea. We build for the future, not the past..

Understandable, specially since no one requested them either.

> I don't know what you mean. Users enable such alternates by setting OpenType features (salt, aalt, etc).

Are all of them referenced by ot features? So nvm.

**Comment by behdad** [comment]
> > I don't know what you mean. Users enable such alternates by setting OpenType features (salt, aalt, etc).
> 
> Are all of them referenced by ot features? So nvm.

Any lookup in the font that cannot be accessed via OT features doesn't really exist.

The reason our API takes a lookup index is because the alternative would be to take script, language, and feature tag, which would then need to do script & language tag selection first.  We expose that complexity of going from client's segment properties and feature of interest in our other API.  They collect the lookup indices, then call the various API that work on lookup indices.

> unsigned lookup_count = hb_ot_layout_table_get_lookup_count (face, HB_OT_TAG_GSUB);
> for (unsigned lookup = 0; lookup < lookup_count; ++lookup)
>   hb_ot_layout_lookup_get_alternates (face, lookup, ...)

Yep, DON'T DO THAT!

**Comment by behdad** [comment]
> Contextual lookups propably suffer from the same issue, but I didn’t need to work with these.

So, your point re `would_substitute` is legit.  We can / should add another API that takes all text and works with chain-context as well.

Since yesterday it was in my mind that the `get_glyph_alternates` API implementation is incomplete because it doesn't work with contextual lookups that substitute alternates in particular context.  I was relieved to remember just now, that the spec specifies `salt`, `aalt`, etc features _have_ to be of `AlternateSubst` type.  While that's something I generally oppose, I'm glad it's there in this case. :)

Which makes sense in a way, not fully in other ways.  But this is where we are.  Let's try to use this in Naskh / Nastaliq and see how we can do better.

**Comment by khaledhosny** [comment]
This reminds me of totally different issue. Usually single of alternate substitution is good enough for these features, but then if you need to do a contextual substitution with the alternate glyphs after that (because it, say, needs the previous glyph to be adapted in some way) things get messy as user selected features gets its lookups applied last.

So far, I worked around this by using a GPOS feature tag (I use `dist` currently) and making the lookups after those of the `salt` or `ssXX` feature, and this makes sure they are  applied last. This feels hacky and I’m pretty sure there are some implementation somewhere where this will fail.

I don’t know if there is an alternative, more robust way to do this.

**Comment by behdad** [comment]
> ...things get messy as user selected features gets its lookups applied last.

That's not true.  All features are intermixed, except for those that are pulled out and separately by a pause specifically in each shaper.  For Arabic that's in `collect_features_arabic`.   Unfortunately that one seems to steal most generic features (`rlig`, `rclt`, `calt`).  Windows used to do `cswh` which could work here but they stopped doing that.   It's all sad, I know.  But see if any feature stands out.  `curs` seems like might work for GSUB and `dist` for GPOS indeed.

**Comment by khaledhosny** [comment]
Oh, that explains a lot. I guess I should have checked the code (though most interesting parts of HarfBuzz are way above my head).

**Comment by behdad** [comment]
> (though most interesting parts of HarfBuzz are way above my head).

Please please please, keep reading the code and ask and I'll make sure to explain until you understand.  That's an infinitely better use of my time than to explain to clickbate "news" site mobs why we don't have resources to support hinting, why it's wrong that FreeType bans use of floats, or why FreeType doesn't need a logging library, all of which seem to be arguing to deaf ears.

**Comment by khaledhosny** [comment]
Sure, I’ll do.

**Comment by ebraminio** [comment]
@Tavmjong @liamquin 2.6.8 just released and contains the API, `hb_ot_layout_lookup_get_glyph_alternates`, please consider using it and bring up any issues here. Thanks!

**Comment by liamquin** [comment]
Thanks @ebraminio !

**Comment by Tavmjong** [comment]
Thanks! Will have a look later. (I wonder how long it takes Fedora to pick up 2.6.8.... or if I'll have to build it myself.)

**Comment by ebraminio** [comment]
> Thanks! Will have a look later. (I wonder how long it takes Fedora to pick up 2.6.8.... or if I'll have to build it myself.)

Sorry for all the delay btw @Tavmjong and @liamquin. You can build it yourself but installing it system wide isn't recommended I think.

**Comment by HinTak** [comment]
> On Tuesday, 23 June 2020, 17:54:43 BST, Ebrahim Byagowi <notifications@github.com> wrote:

> Thanks! Will have a look later. (I wonder how long it takes Fedora to pick up 2.6.8.... or if I'll have to build it 
> myself.)

2.6.8 is already on rawhide - i.e. it definitely will be in fc33 . If you want it for fc32, you might want to ask "Parag Nemade" ( pnemade AT redhat DOT com ) (read from the rpm packaging) or file a issue at bugzilla .

The last few redhat bugzilla ids are:

Update to 2.6.8 version (#1849805)
Update to 2.6.7 version (#1843592)
Update to 2.6.6 version (#1834887)

**Comment by liamquin** [comment]
Thanks @ebraminio ! Hmm, looks like i have it here in Mageia Linux too, but no clue yet how to use it :) I thought i saw some sample code somewhere that listed all fonts with alternate glyphs, or all alternate glyphs for a font, but now can't find it. Hoping to be able to access alternate glyphs via pango markup & use this function to populate a palette for the user to choose from...although for Arabic maybe that could be too large a palette to be usable?

**Comment by ebraminio** [comment]
@liamquin: As shown above also, to be honest I am not that familiar with related APIs and definitely we need a sample app, here is the parts I can help hope you, hopefully @khaledhosny or @behdad will help to fill missing part of the puzzle,
1. Users clicks a glyph and you should find `PangoFont *font` of that particular part of the text.
2. Call `pango_font_get_hb_font` of Pango on that object to get its `hb_font_t`.
3. Call `hb_font_get_face` of HarfBuzz from `hb_font_t` object to get its `hb_face_t`.
4. Now you have the first parameter of `hb_ot_layout_lookup_get_alternates`, so you should now find lookup index, I am not sure how best that can be retrieved correctly as I referred to a brute force way https://github.com/harfbuzz/harfbuzz/issues/673#issuecomment-646459497 and that considered incorrect. There is a `hb_ot_layout_feature_get_lookups` that I think can be used to get lookup of a feature and a `hb_ot_layout_language_find_feature` to find the feature index. I don't know to be honest, I'd think in worst case you can try the stupid brute force in your prototype till you others can answer how best lookup index should be retrieved from a Pango hosted face.
5. Assuming you got `hb_ot_layout_lookup_get_alternates` running like [this](https://github.com/harfbuzz/harfbuzz/blob/1348a2c865d368a4f6e83add0edfa9945d84914f/test/api/test-ot-alternates.c#L37), now you have alternates so you can with a UI like [Rana Kufi](https://alif-type.github.io/rana-kufi/app/)
6. After user selects an alternate you need to set that part of the text you started from with a `font-feature-settings: 'cv01' 2;` or something but using Pango's markup? https://developer.gnome.org/pango/stable/pango-Markup.html (the font feature part) To be honest I don't know the part of Pango API for that also but guess Pango markup would be ok.
7. Pango renders the text with the requested change and user sees the change :)

That's my try at least to help, hopefully "Cunningham's Law" will help here so other would help on how best lookup index can be retrieved and to fix other details. Thanks!

**Comment by ebraminio** [comment]
> although for Arabic maybe that could be too large a palette to be usable?

I don't see any specific reason you need be worried specifically about Arabic, it can be handled just like any other scripts.

**Comment by khaledhosny** [comment]
> > ...things get messy as user selected features gets its lookups applied last.
> 
> That's not true. All features are intermixed, except for those that are pulled out and separately by a pause specifically in each shaper. For Arabic that's in `collect_features_arabic`. Unfortunately that one seems to steal most generic features (`rlig`, `rclt`, `calt`). Windows used to do `cswh` which could work here but they stopped doing that. It's all sad, I know. But see if any feature stands out. `curs` seems like might work for GSUB and `dist` for GPOS indeed.

For the record, I finally got around trying this and found other features that can be used here:
* `clig`: enabled by default by not used by Arabic shaper, so no pause after it (Indic shaper uses it though, and there is a pause after it, so probably not good for Indic).
* `mset`:  enabled by Arabic shaper only but there is no pause after it (obviously nor good for other scripts).

`curs` is good for all scripts, but Glyphs makes it a bit complicated to use it for GSUB (but that is a tooling issue). I was using `dist`, but Core Text does not seem to enable it by default (not for GSUB at least).
