### ISSUE TITLE
Building docs with cmake

### ISSUE THREAD

**Issue by waywardmonkeys** [harfbuzz/harfbuzz#677]
Locally, I've started figuring out how to build the docs with cmake. I have a local branch, but don't see much point (yet) in sharing it ...

So far, I've had to submit a fix upstream for gtk-doc.

**Comment by ebraminio** [comment]
@waywardmonkeys Hi there, keep us updated on that. Thanks :)

**Comment by waywardmonkeys** [comment]
@ebraminio The fix was accepted upstream in gtk-doc, but they haven't done a new release yet. I'll fix up my branch a bit more in the next day or two and share it.

**Comment by waywardmonkeys** [comment]
@ebraminio This is a mess.

First, we'll need a new release of gtk-doc ... but perhaps we'll need more fixes upstream first.

The build system in harfbuzz will need to also generate `version.xml` and `gtkdocentities.ent` ... but I suspect that we can just get rid of `version.xml` and only use `gtkdocentities.ent` ...

Then, you run into the problem that not all of the `api-index-*` files are seemingly getting built by gtk-doc when invoked via cmake, so probably some flags are different in a way that matters. But I'm not sure yet which part of gtk-doc it is that generates those files...

**Comment by ebraminio** [comment]
No rush, and no problem, just feel free to do whatever you like to do :)

**Comment by waywardmonkeys** [comment]
It also looks like setting IGNOREHEADERS in the cmake stuff for GtkDoc doesn't actually work. :)

**Comment by behdad** [comment]
Do we care about this?

**Comment by ebraminio** [comment]
> Do we care about this?

Guess not, docs build has added to meson.
