### ISSUE TITLE
What Spectre mean for harfbuzz?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#686]
After reading https://webkit.org/blog/8048/what-spectre-and-meltdown-mean-for-webkit/ I was wondering whether interesting mitigations like "Index Masking" and "Pointer Poisoning" discussed over there should be incorporated into harfbuzz also

**Comment by behdad** [comment]
Interesting ideas but don't think there's anything to do here.

**Comment by ebraminio** [comment]
Great. Thank you

**Comment by behdad** [comment]
One thing we can do is, in font arrays that we know are limited in length to 16bit, mask the index variable to 0xffff. But I really doubt it matters in our case.
