### ISSUE TITLE
[test] Speed up test/shaping/run-tests.py

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#687]
Right now we spawn hb-shape for each line.  We can do just once and input multiple lines. Easier now that we are in Python.

**Comment by ebraminio** [comment]
Waiting to see your work on the branch https://github.com/harfbuzz/harfbuzz/pull/688#issuecomment-356461543 and whether I am able to do that :)

**Comment by ebraminio** [comment]
Was doing some housecleaning :) so do we need some new tool in C accepting multiple fonts and such?

**Comment by behdad** [comment]
Oh, humm.  Sorry yeah I have had forgotten that most tests have a different font for each line.

But then again, the slowest tests, tibetan-contractions-* etc all use the same font for every line.

I'm honestly surprised how slow the thing  is, given that those tests have only like 60 lines in them.

A design that might work is this: keep the hb-shape process open; instead of using --unicodes, convert to UTF-8 in Python and feed the line (assert that it's one line exactly) to the process and read one line. Then every time the hb-shape command that we want to invoke is different from the currently open hb-shape process, terminate the process and start a new one.

**Comment by behdad** [comment]
Maybe we should benchmark why it's slow instead.  I'm guessing it's the FreeType loading the face that is slow but have no data to back my claim.

**Comment by behdad** [comment]
I like to have a mode to hb-shape to read exactly what we have in the test files right now and run it. Ie. fold run-tests.py into hb-shape itself. That should make it, to pull numbers out of my a$$, ten times faster.

**Comment by behdad** [comment]
Maybe we don't care.
