### ISSUE TITLE
Harfbuzz with Unity3d

### ISSUE THREAD

**Issue by abusaadp** [harfbuzz/harfbuzz#69]
Hi,
 I would like the help of harfbuzz team to integrate harfbuzz in the unity3d engine so that we render indic fonts. Presently the unity3d engine does not render persian,arabic and indic fonts. I am not sure how to use harfbuzz in unity3d. Can anyone guide/help me in implementing harfbuzz in Unity3d?

Regards,
 Abu Saad Papa

**Comment by rutcreate** [comment]
Any progress?

**Comment by ebraminio** [comment]
I am not sure but possibly you will find https://github.com/Robmaister/SharpFont.HarfBuzz intresting I'd guess

**Comment by wutipong** [comment]
I think it's the Unity3D team who should look into this. You may want to report the bug/feature request to the Unity team.

**Comment by ammariqais** [comment]
old post, but i support skia and harbuzz + richkittext + skottie for unity

https://github.com/ammariqais/SkiaForUnity
