### ISSUE TITLE
_GNU_SOURCE is defined too late

### ISSUE THREAD

**Issue by kbrow1i** [harfbuzz/harfbuzz#693]
[0001-Move-the-define-of-_GNU_SOURCE-to-the-top-of-hb-priv.txt](https://github.com/harfbuzz/harfbuzz/files/1620042/0001-Move-the-define-of-_GNU_SOURCE-to-the-top-of-hb-priv.txt)
harfbuzz 1.7.4 doesn't build on Cygwin because _GNU_SOURCE is defined too late in hb-private.hh.  According to https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html, feature test macro defines "must come before any #include of a system header file. It is best to make them the very first thing in the file, preceded only by comments."

The attached patch moves the define of _GNU_SOURCE to the top of hb-private.hh and fixes the build.

**Comment by ebraminio** [comment]
We are testing harfbuzz on msys2 on CI, not sure why it fails on Cygwin but as it wouldn't break others work we like to have that patch! Uploaded it as PR #697 feel free to open PR yourself next time if you like to :)
