### ISSUE TITLE
support Stylistic Alternates salt feature

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [harfbuzz/harfbuzz#694]
since scribus use harfbuzz, there is a [request](https://bugs.scribus.net/view.php?id=15088) to support salt feature.
From opentype spec:

Tag: 'salt'

Friendly name: Stylistic Alternates

Registered by: Adobe

Function: Many fonts contain alternate glyph designs for a purely esthetic effect; these don't always fit into a clear category like swash or historical. As in the case of swash glyphs, there may be more than one alternate form. This feature replaces the default forms with the stylistic alternates.

Example: The user applies this feature to Industria to get the alternate form of g.

Recommended implementation: The salt table maps GIDs for default forms to one or more GIDs for corresponding stylistic alternatives. While many of these substitutions are one-to-one (GSUB lookup type 1), others require a selection from a set (GSUB lookup type 3). The manufacturer may choose to build two tables (one for each lookup type) or only one which uses lookup type 3 for all substitutions. As in any one-from-many substitution, alternates present in more than one face should be ordered consistently across a family, so that those alternates can work correctly when switching between family members.

Application interface: For GIDs found in the salt coverage table, the application passes the GIDs to the salt table and gets back one or more new GIDs. If more than one GID is returned, the application must provide a means for the user to select the one desired.

UI suggestion: This feature should be inactive by default. When more than one GID is returned, an application could display the forms sequentially in context, or present a palette showing all the forms at once, or give the user a choice between these approaches. The application may assume that the first glyph in a set is the preferred form, so the font developer should order them accordingly.

Script/language sensitivity: None.

Feature interaction: This feature may be used in combination with other substitution (GSUB) features, whose results it may override.

**Comment by jfkthame** [comment]
I don't think there's any harfbuzz issue here. Just specify 'salt' in the list of features passed to hb_shape, and it should work fine.

**Comment by Fahad-Alsaidi** [comment]
@jfkthame that's great. Then how to get the number of stylistic alternates if the font supports salt feature. The documentation doesn't help a lot.

**Comment by KrasnayaPloshchad** [comment]
> Then how to get the number of stylistic alternates if the font supports salt feature. The documentation doesn't help a lot.

See #673
