### ISSUE TITLE
Bots failing

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#701]
I think we might want to compiler our own freetype. Or maybe I should update the test suite to know how to skip some tests... That's why travis is failing for example.

**Comment by ebraminio** [comment]
Trying to fix this on #718, fixes for cmake builds but not [autotools](https://circleci.com/gh/harfbuzz/harfbuzz/4655)(!), which version of freetype is needed btw?

**Comment by behdad** [comment]
Thanks Ebrahim!!
