### ISSUE TITLE
[Question] Display ZWJ and ZWNJ glyphs with hb-view?

### ISSUE THREAD

**Issue by n8willis** [harfbuzz/harfbuzz#708]
I'm attempting to generate some example images with hb-view that illustrate (e.g.) ligature and conjunct formation.

The font I'm using has glyphs for U+200C and U+200D (ZWJ/ZWNJ). So far, no combination of arguments I've found is letting me actually render either glyph in the output, however. Which makes it impossible to visually show the difference that they make when used in different places within a sequence. Is there a way to force hb-view to display the glyphs?

**Comment by khaledhosny** [comment]
`hb-view --preserve-default-ignorables` should do what you want .

**Comment by n8willis** [comment]
Yeees! Thank you.
