### ISSUE TITLE
Set 'opsz' variation axis when font ptem is set?

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#713]
Am divided about this, but it sounds the right thing to do.

**Comment by behdad** [comment]
Also see https://github.com/harfbuzz/harfbuzz/pull/826 which was about adding API for tracking.

It occurs to me now that it was a mistake to add ptem API on hb-font. We did it simply because trak table takes point size and tracking numbers. I think we should have considered that a legacy thing superseded by opsz variation axis (and a trak variation axis to be standardized some time).

I mean, we don't have hb_font_set_weight / hb_font_set_width / ...

Another analogy is that TrueType kern table is a special legacy case of more generic GPOS. We reuse 'kern' font-feature-setting to control TrueType kern table.

I like to deprecate ptem API, or at least make it somehow do the same thing as opsz. They should be the same.

Thoughts?

@drott

**Comment by behdad** [comment]
If we add API that allows setting one variation at a time (while not resetting others), then ptem, weight, width etc can become sugar / convenience API around that.

**Comment by drott** [comment]
I see your point, and I'd be okay with renaming, moving the ptem API aside to clearer mark it a CoreText backend bridge / needed for getting `trak` support working. Do you know Apple's opinion on superseding `trak` tables with an `opsz` axis? Do you have any indications that that is really going to happen, vs. something that would be nice to happen as the standardization has a clean solution for it?

I think we should keep the APIs low level though and reduced to effecting single changes, defined in OpenType terms e.g. "apply opsz axis params" vs. broader definitions such as "make optical sizing happen", through any means, e.g. a combiantion of AAT trak, and applying ptem to opszs, + x...

**Comment by behdad** [comment]
> I think we should keep the APIs low level though and reduced to effecting single changes, defined in OpenType terms e.g. "apply opsz axis params" vs. broader definitions such as "make optical sizing happen", through any means, e.g. a combiantion of AAT trak, and applying ptem to opszs, + x...

We already do such reinterpretations for font-feature-settings, where we map from OpenType feature tags to their (rough) equivalent AAT thing.

As far as I understand, Apple's trak table is going to be superseded by OpenType variations, and I'm talking about this with Ned, he's supportive of pushing for registering a 'trak' standard variations axis in OpenType.

Let's keep talking.

**Comment by behdad** [comment]
Thinking more and talking to Jonathan, we think we should deprecate ptem API and pick up value for 'opsz' instead.  Long term...
