### ISSUE TITLE
Hrkt (Hiragana + Katakana) iso15924 script code not listed

### ISSUE THREAD

**Issue by anthrotype** [harfbuzz/harfbuzz#717]
in `hb-common.h` there's `HB_SCRIPT_HIRAGANA` ("Hira") and `HB_SCRIPT_KATAKANA` ("Kana"), but there is not an entry for the generic combined script code "Hrkt" for 

> Japanese syllabaries (alias for Hiragana + Katakana):

http://unicode.org/iso15924/iso15924-codes.html

The `hb_ot_tags_from_script` function returns a lowercased `hrkt` opentype script tag, however it should actually return `kana` for iso code "Hrkt" (like it already does for both "Hira" and "Kana" separately).

see https://github.com/fonttools/fonttools/pull/1150#issuecomment-358842009

**Comment by anthrotype** [comment]
actually, it looks like this "Hrkt" script code is not even used... :confused: 
https://stackoverflow.com/questions/42185370

**Comment by khaledhosny** [comment]
I think this is meant to overcome the fact that Japanese text mixes both Hiragana and Katakana and you woldn’t want to itemize them separately, so when doing script itemization you would give both Hiragana and Katakana characters `hrkt` code and keep them in one run. Or at least I hope that is the idea, looks like a neat solution to the itemization problem.

**Comment by dscorbett** [comment]
`hb_script_t` only includes ISO 15924 codes used by Unicode, and Unicode doesn’t use Hrkt anymore. It was used for characters like U+309B KATAKANA-HIRAGANA VOICED SOUND MARK which appear in both Katakana and Hiragana. Nowadays they use [script extensions](http://unicode.org/Public/10.0.0/ucd/ScriptExtensions.txt) instead.

**Comment by anthrotype** [comment]
@dscorbett thanks for the explanation. I guess we can close this then.
