### ISSUE TITLE
[util] hb-shape output truncated

### ISSUE THREAD

**Issue by punchcutter** [harfbuzz/harfbuzz#727]
Before https://github.com/harfbuzz/harfbuzz/commit/746a37d5bdd2e965aa316e95ba5a7bad809d76a7 I could run hb-shape on files with 1000 lines of text, but now the output gets cut to around 18 lines.

**Comment by behdad** [comment]
Huh.  Umm.

**Comment by punchcutter** [comment]
It seems to be fine for me on Linux, but not Mac. Just for fun in options.cc if I move setvbuf (line 783) to before g_string_new (line 780) then it works. Huh?  

```
    setvbuf(fp, NULL, _IOLBF, BUFSIZ); //setlinebuf (fp);
    gs = g_string_new (nullptr);
```

**Comment by behdad** [comment]
Ugh!!!

**Comment by behdad** [comment]
I'm fine removing them again. Or use setlinebuf if present perhaps?

**Comment by punchcutter** [comment]
At least in my case it works if I remove setvbuf and leave setlinebuf.
