### ISSUE TITLE
Allow mark placement on latter glyph in a reordered multiple substitution

### ISSUE THREAD

**Issue by punchcutter** [harfbuzz/harfbuzz#740]
Related issues:
https://github.com/harfbuzz/harfbuzz/issues/558
https://github.com/harfbuzz/harfbuzz/issues/364
https://github.com/OpenType/opentype-layout/blob/master/docs/ligatures.md

We have run into an issue with USE shaping of Newa script. The vowel signs AI, O, and AU get contexually decomposed into two parts: pre-base and post-base. Because this is a multiple substitution the current behavior is to attach any following marks to the first glyph of the multiple sub, but since we have a pre-base reordering triggered by the pref feature this makes no sense. Any marks should try attaching to the post-base half of the substitution instead.

**Comment by behdad** [comment]
I gave it a try.  Please test.

**Comment by punchcutter** [comment]
Tested and looks good. Thanks!

**Comment by behdad** [comment]
Can you please send me a sample font and short test string (or strings), so I can add to the test suite?

**Comment by punchcutter** [comment]
The font isn't delivered yet, but should be coming your way soon. 
Here's the string:
𑐐𑑂𑐑𑑀𑑃𑐐𑑂𑐑𑑁𑑃
11410,11442,11411,11440,11443,11410,11442,11411,11441,11443
11440 and 11441 get split in `pref` so the candrabindu attaches to the right half of each of those.

**Comment by behdad** [comment]
Send whatever you have. Doesn't have to be correct font. We just want to subset it for testing.
