### ISSUE TITLE
fonttools ttx is needed in the CI environments

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#764]
https://github.com/harfbuzz/harfbuzz/pull/763 adds the use off ttx to subsetting tests for comparing fonts.  Unfortunately it's not available in the CI environments so the test is still failing there.  Could we have fonttools added to the CI environments?

**Comment by ebraminio** [comment]
I guess `pip install`ing `fonttools` would be tricky as #1350 or maybe can be done with virtualenv or not. Is it possible to avoid failing on not presence of fonttools? Currently we have a dependency to python on harfbuzz test suit but not python-pip yet, it would be nice if we don't add that hard dependency to our tests and just testing that test with need of fonttools on one of the CircleCI bots https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml

**Comment by behdad** [comment]
I suggest we just do a shallow git checkout and use it from inside the checkout tree.

Also, yeah, should make the test skip if ttx is not found.

**Comment by garretrieger** [comment]
Good idea, I've updated my pull request to skip the test if ttx is not found.

**Comment by ebraminio** [comment]
@garretrieger: #777 added ttx on two bots but those bots are broken with the change. I guess you should have a look at them
