### ISSUE TITLE
Better Coverity integration

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#765]
I don't remember who / how set up our coverity integration, but it seems to be running infrequently. Perhaps we can improve it by integrating it with Travis: https://scan.coverity.com/travis_ci

**Comment by ebraminio** [comment]
Lets continue on #778

**Comment by pwithnall** [comment]
> I don't remember who / how set up our coverity integration, but it seems to be running infrequently.

I set it up, and it runs once a week on jenkins.freedesktop.org. If you (the Harfbuzz maintainers) want to take over the integration and integrate it better with your CI, I am all for it. I’ll reply further on #778.

**Comment by ebraminio** [comment]
Aha now I understand. Well don't know what to decide I guess current setup was good also, it just needed a more frequent triggers. If that can be done I guess we can cleanup things we've done here.

**Comment by pwithnall** [comment]
The old setup worked, but not fantastically well. I think it makes sense for you to be in control of the Coverity scan builds, since it means you can control the build and configuration environment more to your liking (and the frequency of builds).

**Comment by behdad** [comment]
> I set it up, and it runs once a week on jenkins.freedesktop.org. If you (the Harfbuzz maintainers) want to take over the integration and integrate it better with your CI, I am all for it. I’ll reply further on #778.

Ah I see. I didn't even know jenkins.freedesktop.org existed. Thanks!
