### ISSUE TITLE
Write check script for dist'ing whole directories

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#784]
We distribute some directories like test/shaping/data/fonts by including the entire directory. That is error-prone if there are extra files in there by accident. We need to write a check script that makes sure every file in there is in git when working from a git checkout.  Alternatively, list all files in a Makefile.sources, and check that all files listed in the Makefile are in git.  Such script comes handy in other projects too.

**Comment by behdad** [comment]
If doing the latter, it also applies to dirs like test/shaping/data/tests that we do list all test files in a Makefile.

**Comment by behdad** [comment]
(Or I suppose even to sources files, etc. A simple check to verify that all files listed in a Makefile are indeed added to git.)

**Comment by ebraminio** [comment]
```make
dirs := src src/hb-ucdn util test/subset/data \
    test/shaping/data/text-rendering-tests test/shaping/data/in-house

VARS_OLD := $(.VARIABLES)
d = src
include $(d)/Makefile.sources

echo $(foreach v, \
        $(filter-out $(VARS_OLD) VARS_OLD,$(.VARIABLES)), \
        $(foreach f, \
            $($(v)), \
            $(info $(d)/$(f)) \
        ))
```

https://stackoverflow.com/a/2406813

**Comment by behdad** [comment]
Fancy stuff!

**Comment by behdad** [comment]
I got something with this print.mk:
```
srcdir = .

VARS_OLD := $(.VARIABLES)
include $(srcdir)/Makefile.sources
VARS := $(filter-out $(VARS_OLD) VARS_OLD,$(.VARIABLES))

all:
	@echo -n \
		$(foreach v, \
			$(VARS), \
			$(foreach f, \
			    $($(v)), \
			    $(info $(f)) \
			))
```

and running:
```
$ diff -u <(git ls-files | LANG=C sort) <(make -f print.mk | LANG=C sort)
```

But that includes BUILT_FILES, which should be excluded. Perhaps just have a makefile that prints all the variables, and handle the rest in Python.

Back to the original request, would be better maybe to have a test that checks the fonts distributed are exactly the same set as the fonts referenced to from the tests.

**Comment by behdad** [comment]
Yeah, for the fonts, I think I like this more:
1. in distcheck, err if we're in git checkout and there are dangling files in fonts/
2. in check, check that all fonts referenced to by tests are in git.

Anyway, just braindumping right now.

**Comment by behdad** [comment]
> 1. in distcheck, err if we're in git checkout and there are dangling files in fonts/

Would be nice.  But let's close since who cares...
