### ISSUE TITLE
Coverity scan fail

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#785]
Filled if someone else likes to fix this as I am a little exhausted and feel need some rest, I defined pushing to coverity_scan branch here #778 as Behdad request but it doesn't seem to work, https://travis-ci.org/harfbuzz/harfbuzz/builds/340840072

My guess is PROJECT_NAME should be defined to match with https://scan.coverity.com/projects/behdad-harfbuzz/edit as "project name" can not be edited, or a new project should be created on coverity at harfbuzz/harfbuzz and change https://github.com/harfbuzz/harfbuzz/blob/master/.travis.yml#L15 to match with that, from https://scan.coverity.com/travis_ci

```
gem install travis
cd my_project
travis encrypt COVERITY_SCAN_TOKEN=project_token_from_coverity_scan
```

this time with a token from that new project of harfbuzz/harfbuzz on coverity.

I hope this fixes it.

**Comment by behdad** [comment]
Any idea why this still fails:
https://travis-ci.org/harfbuzz/harfbuzz/builds/342676747?utm_source=email&utm_medium=notification

**Comment by ebraminio** [comment]
Hmm, it sets PROJECT_NAME  at very end of the run, probably needs to setup the project first at harfbuzz/harfbuzz and redoing secure key and ... :/ ok lets put some more time on this
