### ISSUE TITLE
Better printing of logs for CI bots

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#786]
Right now when a build fails we do ```(cat `find -name '*.log'` && false)```. We should instead write a script `.collect_logs` or something and run that. That script should print the log filename before the contents. Also, not print configure.log which seems to be unnecessary most of the time.

**Comment by ebraminio** [comment]
Its one-linear:

    (for f in `find . -name '*.log' -not -name 'config.log'`; do echo '==== '$f' ===='; cat $f; done && false)

**Comment by behdad** [comment]
I know. But since it's copy/pasted in a dozen places, better to pu it in a file.  It can also report other interesting things.
