### ISSUE TITLE
Clean up homepage / online documentation

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#787]
Following up from https://github.com/harfbuzz/harfbuzz/pull/625

**Comment by behdad** [comment]
So, I think what I like is something like this:

- harfbuzz.github.io will be the main landing page and home of the project. harfbuzz.org to be retired in a year or two...  The harfbuzz.github.io to contain all the information that is currently on harfbuzz.org, and link to other places listed below among others.

- harfbuzz.github.io/reference or something similar will contain the main user documentation. Ie. what's generated out of gtk-doc and is currently on harfbuzz.github.io.

- github.com/harfbuzz/harfbuzz will be the landing page for developers. It will include what it does now, plus perhaps a bit more wording and links to docs related to getting started with developing harfbuzz.

- We shall shut down the github wiki and move its information to the above places.

**Comment by ebraminio** [comment]
My raw idea,

1. Moving current documentations to `harfbuzz.github.io/docs` (moving its repository to `github.com/harfbuzz/docs` and enabling serving it)
2. Interestingly GitHub wikis are on Git format theirselves, so mirroring  `https://github.com/harfbuzz/harfbuzz.wiki.git` on `https://github.com/harfbuzz/wiki` thus will be served on `harfbuzz.github.io/wiki` but can be edited by anyone (a Wiki hosting like a PRO!), closing its edit to public if we had any spamming issue, doing the mirroring using Travis CI's daily builds.
3. Making `harfbuzz.github.io` a brief homepage for the project, something like `https://ebraminio.github.io` and optionally a blog system, https://github.com/ebraminio/ebraminio.github.io

**Comment by behdad** [comment]
Not sure if we need a Wiki when we also have markdown.

**Comment by behdad** [comment]
@n8willis is this something you can take on?

**Comment by behnam** [comment]
@behdad, @ebraminio, @khaledhosny,

What's the plan here?

I propose to:
A. Get everything off freedesktop.org
B. Put everything on github.org

This is to make sure all content/source/binary is in one place, and there's no need to update two different sites (with separate accounts, etc) for maintenance.

To do so, looks like the project needs a homepage, to contain content of https://www.freedesktop.org/wiki/Software/HarfBuzz/ , as well as links to related code/projects, like language wrappers.

WDYT?

**Comment by behdad** [comment]
Agree.  Needs someone to do it though.

**Comment by behdad** [comment]
Tracking in other issues.
