### ISSUE TITLE
Add bot that compiles code with -O0

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#801]
Not sure what the bots default to. But would be good to have one with -O0. Ideally both gcc and clang. Also perhaps with -O3. Sometimes these catch memory bugs that otherwise go unnoticed.

**Comment by ebraminio** [comment]
They default to -O2. I saw also -O0 couldn't show an issue existed on -O2 on #774. I am just thinking how to not add 4 more bots, maybe we should add them on Travis.

**Comment by behdad** [comment]
Just changing one of the bots would be enough.
