### ISSUE TITLE
[Question] Reason for JOINING_TYPE "X" in Arabic?

### ISSUE THREAD

**Issue by n8willis** [harfbuzz/harfbuzz#802]
Trying to understand the Arabic shaper: what is the reason for creating the "X" Joining Type in the arabic-table?

Comments note that it means to derive the joining type of the character from the General Category of the codepoint in UnicodeCD. I'm just wondering whether this provides some speed benefit versus dropping in those joining types into the table or what. Because it seems like it adds complexity.

If there's a gain, I'm interested in understanding what it is.

**Comment by behdad** [comment]
Simply because that's how the data in `ArabicShaping.txt` is organized...
