### ISSUE TITLE
Allow compilation without hb-subset* functionality

### ISSUE THREAD

**Issue by drott** [harfbuzz/harfbuzz#806]
We currently do not need the subsetting functionality in Chrome and we use different build recipes. Please ensure that compilation is possible without the hb-subset* files as much as possible. 

Currently `hb-subset-plan.hh` and `hb-subset.h` are still needed to compile cleanly.

CC @garretrieger, @rsheeter

**Comment by behdad** [comment]
I'll try to untangle as much as possible. But there will be some overlap, as we cannot subset structs completely out of their own definitions.

**Comment by drott** [comment]
Thanks!

**Comment by rsheeter** [comment]
Sorry @drott and ty @behdad for volunteering to fix :)

It is plausible to have a "like Chrome" build bot? - didn't really consider we'd be toasting that build.

**Comment by drott** [comment]
If all goes well, we'll have a relatively easy way to create Chrome test CLs building newer HarfBuzz commit hashes by just running a roll-deps script and uploading it to Chrome's gerrit.

**Comment by behdad** [comment]
> It is plausible to have a "like Chrome" build bot? - didn't really consider we'd be toasting that build.

Looks like -Werror=unused-function might be very close to it. I'm personally against those kinds of enforcements by downstream clients on upstream dependencies. We deliberately add code and commit to master that is not hooked up yet.

@ebraminio

**Comment by ebraminio** [comment]
> It is plausible to have a "like Chrome" build bot? - didn't really consider we'd be toasting that build.

#832, interestingly it was just happening on clang on not gcc so I assume it is Chromium like as they are also using clang.

**Comment by ebraminio** [comment]
And https://github.com/harfbuzz/harfbuzz/commit/0bbf90ded00dd00ee3f79c1bd16c775d7c893278 hopefully to fix OP.
