### ISSUE TITLE
Split hb-ot-kern-table.hh into two?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#835]
`hb-ot-kern-table.hh` is so complex as it tries to implement both AAT and OT `kern` at the same time, isn't better to separate AAT parts into `hb-aat-layout-kern-table.hh` or something? (we perhaps didn't at first hand as `hb-aat-layout-*.hh` is a new thing anyway)

There is not any macOS installed font having AAT's `kern` but don't have `morx` so maybe AAT's `kern` is very associated with AAT's fonts. Interestingly however there are `morx` having fonts with OT's `kern` e.g. Palatino.

**Comment by ebraminio** [comment]
Hmm, or maybe this don't worth the hassle.

**Comment by behdad** [comment]
Yeah, no need, unless there's good reason to.
