### ISSUE TITLE
`kerx` implementation

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#839]
Useful links:
* Spec: https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6kerx.html
* kerx.js: https://github.com/devongovett/fontkit/blob/047c61423442a534fadf5ecd99b182fc4f6fc8f2/src/tables/kerx.js and the rest of the implementation https://github.com/devongovett/fontkit/compare/aat-kern

Now list of `kerx` having fonts from 10.13.3,

| version | format | font path |
|:--:|:--:|:--:|
| 3 | 2 | /Library/Fonts/Kefa.ttc |
| 3 | 4 | /Library/Fonts/Kannada Sangam MN.ttc |
| 3 | 4 | /Library/Fonts/Myanmar MN.ttc |
| 3 | 4 | /Library/Fonts/Telugu MN.ttc |
| 3 | 4 | /Library/Fonts/Myanmar Sangam MN.ttc |
| 3 | 0 | /Library/Fonts/Devanagari Sangam MN.ttc |
| 3 | 4 | /Library/Fonts/Bangla MN.ttc |
| 3 | 4 | /Library/Fonts/Bangla Sangam MN.ttc |
| 3 | 2 | /Library/Fonts/Tamil MN.ttc |
| 3 | 2 | /Library/Fonts/Tamil Sangam MN.ttc |
| 3 | 4 | /Library/Fonts/Kannada MN.ttc |
| 3 | 4 | /Library/Fonts/Telugu Sangam MN.ttc |
| 3 | 4 | /Library/Fonts/Gujarati Sangam MN.ttc |
| 3 | 4 | /Library/Fonts/Oriya MN.ttc |
| 3 | 4 | /Library/Fonts/Oriya Sangam MN.ttc |
| 4 | 6 | /System/Library/Fonts/SFNSDisplay.ttf |
| 3 | 0 | /System/Library/Fonts/ヒラギノ角ゴシック W8.ttc |
| 4 | 6 | /System/Library/Fonts/SFNSText.ttf |
| 3 | 0 | /System/Library/Fonts/ヒラギノ明朝 ProN.ttc |
| 4 | 6 | /System/Library/Fonts/SFNSTextItalic.ttf |
| 3 | 0 | /System/Library/Fonts/ヒラギノ丸ゴ ProN W4.ttc |
| 3 | 1 | /System/Library/Fonts/ArialHB.ttc |

So I guess we should start from format 0 fonts, "Devanagari Sangam MN", "ヒラギノ角ゴシック W8" and "ヒラギノ丸ゴ ProN W4", which is the most simple one of them.

**Comment by ebraminio** [comment]
Previous table didn't consider multiple kerning subtables of `kerx` table,
```
 2 /Library/Fonts/Kefa.ttc
 4  4  1  0 /Library/Fonts/Kannada Sangam MN.ttc
 4 /Library/Fonts/Myanmar MN.ttc
 4  4  4 /Library/Fonts/Telugu MN.ttc
 4 /Library/Fonts/Myanmar Sangam MN.ttc
 0  4 /Library/Fonts/Devanagari Sangam MN.ttc
 4  4 /Library/Fonts/Bangla MN.ttc
 4  4 /Library/Fonts/Bangla Sangam MN.ttc
 2 /Library/Fonts/Tamil MN.ttc
 2 /Library/Fonts/Tamil Sangam MN.ttc
 4  4  1  0 /Library/Fonts/Kannada MN.ttc
 4  4  4 /Library/Fonts/Telugu Sangam MN.ttc
 4  2 /Library/Fonts/Gujarati Sangam MN.ttc
 4  4  4  4 /Library/Fonts/Oriya MN.ttc
 4  4  4  4 /Library/Fonts/Oriya Sangam MN.ttc
 6 /System/Library/Fonts/SFNSDisplay.ttf
 0  0 /System/Library/Fonts/ヒラギノ角ゴシック W8.ttc
 6 /System/Library/Fonts/SFNSText.ttf
 0  0 /System/Library/Fonts/ヒラギノ明朝 ProN.ttc
 6 /System/Library/Fonts/SFNSTextItalic.ttf
 0  0 /System/Library/Fonts/ヒラギノ丸ゴ ProN W4.ttc
 1  1  1  1  1  1  4  4  4  4  4  4  1  1  1  1  4  4  4  0 /System/Library/Fonts/ArialHB.ttc
```

**Comment by behdad** [comment]
Done.
