### ISSUE TITLE
Making font structs not copyable

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#843]
As a development hint, it would be nice if we could mark most of font structs to not be copyable. We should investigate the available various ways to add this assertion. From Behdad on [1](https://github.com/harfbuzz/harfbuzz/pull/836#discussion_r171033551),

> I can make it by creating a new empty type to be derived from by all font structs. Eg.:
```
struct FontStruct 
{ 
  private: 
  FontStruct (const FontStruct &); 
  FontStruct & operator = (const FontStruct &); 
}; 
```
> I don't know What else we can do with that. Also not sure if the DEFINE_* should check that we inherit from this. Note that for basic types (HBINT*, Tag, GlyphID, ...) we don't want to enforce this.  So maybe we can have two different types, one for ValueTypes and one for others.  I like the idea. Can you open an issue for it?
> 
> If we make the base type a template that takes the inherited type (https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) we might be able to do more useful things as well.

**Comment by behdad** [comment]
Thanks :)

**Comment by behdad** [comment]
I experimented with a few approaches for this.  Couldn't find any that works.

**Comment by ebraminio** [comment]
So lets close it, at least we tried to and the file documents the attempt.
