### ISSUE TITLE
Code style change?

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#844]
I guess talking about code style on established/grown up projects like harfbuzz is more like a joke but I still try. Maybe we can discuss about it to make the development a bit easier? I know such change will ruin `git blame` but I like to have some place to discuss that so if we want to apply such thing, at least we do it once.

* [vscode](https://github.com/Microsoft/vscode/issues/44438) and Atom editors don't support configuring tab sizes (without change indention style) and Rod and Garret also don't use them always AFAICS. Maybe we can remove their use? Have a look at this https://youtu.be/99Zacm7SsWQ?t=329 also
* Removing space before function call.
* Not putting starting curly braces on new line, to resemble more Java code style! Have a look at the interesting case of JS https://youtu.be/hQVTIJBZook?t=1837 :)

**Comment by khaledhosny** [comment]
Alternatively, we can look into using `clang-format` and making a format file that matches the existing style, so people can just use it to format the code before committing.

**Comment by rsheeter** [comment]
I'm skeptical it makes sense to _change_ the style of a mature project but making it easier to follow would be great. +1 for a clang-format rig.

**Comment by behdad** [comment]
Don't think will happen.

The tab vs space thing is weird not supported by those editors. This is the common style across many common Open Source C libraries.

**Comment by ebraminio** [comment]
No need for other crazy changes, I can go without them, but just no tabs, what @waywardmonkeys said on #1279

**Comment by ebraminio** [comment]
> I can go without them

Not a personal opinion but the mentioned editors requirement, you can see also that every new contributor have the issue (in addition to space before the calls). Khaled said we can alternatively build `clang-format` config but I couldn't find a way to explain mixed space-tabs on that formatter, maybe I didn't investigate enough however.

**Comment by behdad** [comment]
Stupid request: can you please draft a vim tagline or whatever can be added to project to make it do what you propose?

**Comment by behdad** [comment]
> Stupid request: can you please draft a vim tagline or whatever can be added to project to make it do what you propose?

https://andrew.stwrt.ca/posts/project-specific-vimrc/

@anthrotype can we add this for fonttools as well?

**Comment by behdad** [comment]
What's the proposed indentation?  Just expand all tabs?

**Comment by ebraminio** [comment]
Two spaces is good and enough I believe, not changing that makes many lines untouched also. We should focus on the issues newcomers will be confused EVERYTIME with them ([see this experiment](https://linguistics.stackexchange.com/q/18859/13419)), this one isn't.

**Comment by ebraminio** [comment]
The reason behind not using space before function call parameter is to distinguish it function calls with language per Douglas Crockford (pretty famous person in JavaScript, best known for the invention of JSON and advocate for caring about code style for better maintainability of the codes) but I don't know what is the reason to put space, and even so you are not seeing that in contributed codes.

I understand however you like to use an already in use style for the project and don't create, something nice to do is to list the known and relevant codestyle standards and see which is most relevant to us

**Comment by ebraminio** [comment]
The reason behind not using space before function call parameter is to distinguish it function calls with language per Douglas Crockford (pretty famous person in JavaScript, best known for the invention of JSON and advocate for caring about code style for better maintainability of the codes) but I don't know what is the reason to put space, and even so you are not seeing that in contributed codes.

I understand however you like to use an already in use style for the project and don't create, something nice to do is to list the known and relevant codestyle standards and see which is most relevant to us

**Comment by anthrotype** [comment]
> can we add this for fonttools as well?

@behdad you could add one if you like. But what I was planning to do was to use the [black](https://github.com/ambv/black) auto-formatter, and enforce it via CI checks. It also has good integration with vim and other editors as well.
