### ISSUE TITLE
Renaming to hb-ot-color-*

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#856]
Let's rename the color tables to have a hb-ot-color-* prefix. I'm still making my mind re the public API. It probably will be hb-ot-color.h, NOT hb-color.h

**Comment by ebraminio** [comment]
I hope we could provide it for the next release :) Just imagine how wonderful it would be, HarfBuzz 2.0, featuring subset, AAT (morx/kerx/ankr/trak), deprecation of coretext_aat shaper, and... COLR/CPAL :)
