### ISSUE TITLE
Tibetan reordering does not match Uniscribe

### ISSUE THREAD

**Issue by dscorbett** [harfbuzz/harfbuzz#861]
U+0F3F TIBETAN SIGN MAR TSHES is a spacing mark that goes to the left of digits. Uniscribe reorders it before digits but HarfBuzz does not.

**Comment by KrasnayaPloshchad** [comment]
CC @domschl

**Comment by behdad** [comment]
Sample text, ideally with hb-shape output of ot vs uniscribe?

**Comment by dscorbett** [comment]
```console
$ unicode 0f21 0f3f
U+0F21 TIBETAN DIGIT ONE
U+0F3F TIBETAN SIGN MAR TSHES
$ hb-shape /c/Windows/Fonts/himalaya.ttf -u '0f21 0f3f' --shapers ot
[tibOne=0+655|tibTailL=0+680]
$ hb-shape /c/Windows/Fonts/himalaya.ttf -u '0f21 0f3f' --shapers uniscribe
[tibTailL=0+680|tibOne=0+655]
```

The [OpenType Tibetan spec](https://docs.microsoft.com/en-us/typography/script-development/tibetan) defines a digit-based cluster as D [Md] (a digit with one optional digit modifier) but Uniscribe (as usual) puts its own spin on things. Uniscribe considers these to be valid: D [MdPre] [MdBlw] [MdPst], where MdPre = U+0F3F, MdBlw = < U+0F18 | U+0F19 >, and MdPst = U+0F3E. That is, it allows one modifier in each position, which is reasonable: even if such combinations are unattested, the shaper should not forbid them. If MdPre is present, all of the modifiers are reordered before the base digit, which makes no sense.

I recommend that HarfBuzz reorder a single U+0F3F immediately following an eligible base to immediately before the base. Digits and dotted circles should be considered eligible; other characters, like consonants, could be too. If U+0F3F does not follow an eligible base, a dotted circle should be inserted before it.

**Comment by behdad** [comment]
One way would be to route Tibetan through USE. I think that's what Microsoft does in their latest implementation. Right now our Tibetan shaper doesn't do any reordering or other magic. @jfkthame any preferences?

**Comment by behdad** [comment]
Still relevant?

**Comment by behdad** [comment]
I get same output from HB master.

**Comment by dscorbett** [comment]
With Tibetan using USE, U+0F3F is reordered properly.
