### ISSUE TITLE
[set] hb_set_union fails with large codepoints.

### ISSUE THREAD

**Issue by garretrieger** [harfbuzz/harfbuzz#863]
For some codepoints hb_set_union fails to create a correct union.

For exampe: {} U {0x660E} gives a result of {0x20E}

Reproduction:
https://github.com/googlefonts/harfbuzz/commit/d3772e7acce85469c567635b414d23d7bbaca4e1

**Comment by behdad** [comment]
@drott Do we use hb_set_union or other binary set ops in Blink? If yes, we should grab these fixes.
