### ISSUE TITLE
"OT::_hb_NullPool" multiple definition errors trying to build 1.7.6

### ISSUE THREAD

**Issue by rvandermeulen** [harfbuzz/harfbuzz#865]
I'm trying to update Firefox to version 1.7.6 and am hitting errors with OT::_hb_NullPool in hb-subset.cc with at least GCC 4.9.4. Can we maybe move that definition to somewhere shared between hb-subset.cc and hb-ot-layout.cc?

**Comment by jfkthame** [comment]
For the time being, can you just omit hb-subset.cc from the Firefox build? We haven't adopted any of the new subsetting functionality at this point.

**Comment by rvandermeulen** [comment]
Yeah, that's working fine for now.

**Comment by behdad** [comment]
hb-subset.cc is supposed to compile to separate library, so this is as expected. I'll add a HB_SUBSET_BUILTIN define that you can define to fix this if you are compiling them into the same library.

**Comment by behdad** [comment]
You can also define HB_NO_VISIBILITY, but that would be less efficient.
