### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by unsacrificed** [harfbuzz/harfbuzz#876]
Where is documentation? May be I miss something?

User Guide is broken:
Wiki -> User Guide -> https://behdad.github.io/harfbuzz/ - Error 404

Internal manual is broken too:
fonts-and-faces.html - empty (even if builded with FT support)
using-harfbuzzs-native-opentype-implementation.html - empty
using-your-own-font-functions.html - empty

Internal API documentation is just a syntax with no comment or description:
harfbuzz-hb-ft.html - what all functions on this page perform?

**Comment by behdad** [comment]
Docs are at https://harfbuzz.github.io/
We should take down the wiki.

**Comment by unsacrificed** [comment]
https://harfbuzz.github.io/fonts-and-faces.html#using-freetype - empty
https://harfbuzz.github.io/harfbuzz-hb-ft.html - only syntax

**Comment by ebraminio** [comment]
Thank you @unsacrificed, removed the section as it was the old link for https://harfbuzz.github.io/

You are right. *Someone* should put effort on filling them https://github.com/harfbuzz/harfbuzz/blob/master/docs/usermanual-fonts-and-faces.xml and https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ft.cc interestingly there are some comments about the usage on https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ft.h

**Comment by ebraminio** [comment]
Lets merge this #725, thanks
