### ISSUE TITLE
linker issue with 1.7.6 release

### ISSUE THREAD

**Issue by pnemade** [harfbuzz/harfbuzz#880]
Just reporting here in case anyone knows solution for this issue.
1.7.5 release is building fine for Fedora 27 but the 1.7.6 release introduced something that is causing linker error.
e.g. See this failed build log -> https://kojipkgs.fedoraproject.org//work/tasks/9948/25659948/build.log

few lines from log given below

```
libtool: link: DIE_RPATH_DIE="/usr/lib64:" gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Bsymbolic-functions -o .libs/test-subset-hmtx test-subset-hmtx.o  ../../src/.libs/libharfbuzz.so -lglib-2.0 ../../src/.libs/libharfbuzz-subset.so
make[3]: *** [Makefile:896: test-shape] Error 1
../../src/.libs/libharfbuzz.so: undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:876: test-object] Error 1
```

**Comment by ebraminio** [comment]
`/usr/lib/rpm/redhat/redhat-hardened-cc1` is in you command and `-fexceptions` is explicitly stated, hmmm. I guess you need to build harfbuzz with `--with-libstdc++`.

**Comment by pnemade** [comment]
Okay. I also read CMakeLists.txt and found that switch. Let me check if build passes with that switch.

**Comment by ebraminio** [comment]
Oh, it is for autotools already and is defined [https://github.com/khaledhosny/harfbuzz/blob/master/configure.ac#L60-L65](here), you should pass it either to ./autogen.sh or ./configure. But you are right, the no-exception was applied globally to the project and on 1.7.6 and it is just passed to certain objects, I wonder however why no one, even our dear [Fedora bot](https://github.com/harfbuzz/harfbuzz/blob/master/.circleci/config.yml#L56-L63) doesn't complain about the situation and passes the tests also, perhaps it has something to do with `redhat-hardened-cc1`.

**Comment by behdad** [comment]
That's weird. Can you check the link / compile commands across the two version and see what changed? We didn't intend to change how libharfbuzz.so is built. Using `--with-libstdc++` is NOT the solution.

**Comment by behdad** [comment]
> But you are right, the no-exception was used to be applied globally to the project but on 1.7.6 and it is just passed to certain objects,

Is it? At least in master, my reading is that it applies to everything.

**Comment by pnemade** [comment]
I asked help to Florian but could not able to get his reply on downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=1552962

I still have not officially built the new update in Fedora yet.

**Comment by behdad** [comment]
I tried a fix. Please let me know if it fixes and I'll roll a new release. Thanks.

**Comment by pnemade** [comment]
I am still getting linker error with the current snapshot of this project code. 
See https://koji.fedoraproject.org/koji/taskinfo?taskID=25995018
and failure is still same 

```
libtool: link: gcc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -Wl,-z -Wl,relro -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Bsymbolic-functions -o .libs/test-blob test-blob.o  ../../src/.libs/libharfbuzz.so -lm -lfreetype -lgraphite2 -lglib-2.0
../../src/.libs/libharfbuzz.so: undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:923: test-shape] Error 1
```

Maybe above should use g++ and not gcc to link as suggested in downstream bug?

**Comment by behdad** [comment]
Why is there `-fexceptions` in there? That's the problem.

**Comment by behdad** [comment]
Also, our CXXFLAGS are missing.  I wonder where they went. This looks very suspicious. What command is used to configure?

**Comment by behdad** [comment]
Humm. I don't see them when I try here either. Let me debug.

**Comment by behdad** [comment]
I take that back. I see them here. I see `-fno-exceptions -fno-threadsafe-statics -fno-rtti` in my compile commands, as we expect.  We have to figure out why you don't.

**Comment by behdad** [comment]
Humm. Ok, you don't see because this is compiling a C source file.

Still, question is why do we have `-fexceptions` there. Apparently your build system has added it. How did that work before, I don't know.

**Comment by ebraminio** [comment]
> Still, question is why do we have -fexceptions there. Apparently your build system has added it. How did that work before, I don't know.

That's why they should test it with --with-stdc++ https://github.com/harfbuzz/harfbuzz/issues/880#issuecomment-372469463 I guess they way was used to work before was having both `-fexception` was reverted by `-fno-exception` (or the reverse way) on the same command. Don't get me right, I just don't like to touch stdc++ related things anymore :D

**Comment by ebraminio** [comment]
@pnemade: Can you give us exact instructions to reproduce the issue?

**Comment by pnemade** [comment]
1) With 1.7.5 version compilation I saw this line
```
make[4]: Entering directory '/home/parag/harfbuzz/f28/harfbuzz-1.7.5/src'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/freetype2 -I/usr/include/libpng16      -I./hb-ucdn    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -fno-rtti -fno-exceptions -fno-threadsafe-statics -Wcast-align -fvisibility-inlines-hidden -std=c++11 -c -o libharfbuzz_la-hb-blob.lo `test -f 'hb-blob.cc' || echo './'`hb-blob.cc
```

and with 1.7.6 version
```
make[4]: Entering directory '/home/parag/harfbuzz/master/harfbuzz-1.7.6/src'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -fno-exceptions -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/freetype2 -I/usr/include/libpng16      -I./hb-ucdn  -fno-threadsafe-statics -fno-rtti    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -Wcast-align -fvisibility-inlines-hidden -std=c++11 -c -o libharfbuzz_la-hb-blob.lo `test -f 'hb-blob.cc' || echo './'`hb-blob.cc
```

Both are the lines from SPEC file compilation. That is log from rpmbuild. What we can notice here is that compiler flags are not at same location within those lines.
e.g.  `-fno-rtti -fno-exceptions -fno-threadsafe-statics` is in 1.7.5 log but all these are separated in 1.7.6
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  **-fno-exceptions** -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/freetype2 -I/usr/include/libpng16      -I./hb-ucdn  **-fno-threadsafe-statics -fno-rtti** ....   

I am not sure if such distributed placement makes any difference.

2) Another thing compilation is always failing for harfbuzz-1.7.6/test/api/

3) I removed test/api/ directory, rebuilt new harbuzz tarball and built successfully using rpmbuild. Not sure what wrong is happening in api directory source compilation.

4) currently in SPEC file I am using
%configure --disable-static --with-graphite2
but if I change this to 
%configure --disable-static --with-graphite2 --with-libstdc 
then it compiles successfully using rpmbuild.

**Comment by behdad** [comment]
Ok I know what's going on. Will fix soon.

**Comment by behdad** [comment]
Ok, I almost reverted things to how they were in 1.7.5. Should be better now.

**Comment by pnemade** [comment]
I confirm the current snapshot that included https://github.com/harfbuzz/harfbuzz/commit/08b8eb678a6cb74c118a32e75b880599e3ac4a7c commit fixed the issue I reported here.
