### ISSUE TITLE
CMake doesn't support pkg-config and cmake modules installation

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#896]
Lets don't forget, useful links also:

* https://github.com/wingtk/gvsbuild/commit/7b01de13a354fa81333160725df66f62a9bfc122
* https://github.com/harfbuzz/harfbuzz/pull/822

**Comment by alan-kozlay** [comment]
I'm guessing this is referring to the issue I'm running into.  If harfbuzz is built using the cmake system, /src/harfbuzz.pc.in doesn't get installed.  So, when building other projects which query for harfbuzz.pc, it looks like my system doesn't have harfbuzz installed.

**Comment by behdad** [comment]
Either fix or close please!

**Comment by rdp** [comment]
freetype uses pkg-config to detect harfbuzz FWIW...a workaround is to use ./autogen.sh then ./configure instead of cmake...

**Comment by ebraminio** [comment]
The plan now is to ditch cmake and autotools altogether in favor of meson, maybe we should can close this

**Comment by rdp** [comment]
works for me...
