### ISSUE TITLE
Errors building hb-blob.cc

### ISSUE THREAD

**Issue by chmeeedalf** [harfbuzz/harfbuzz#901]
When building the harfbuzz FreeBSD port on 32-bit powerpc (gcc 4.2.1) I get the following errors while compiling hb-blob.cc:

hb-private.hh:417: error: integer constant is too large for 'long' type
hb-private.hh:493: error: integer constant is too large for 'long' type
hb-private.hh:494: error: integer constant is too large for 'long' type
hb-private.hh:495: error: integer constant is too large for 'long' type
hb-private.hh:496: error: integer constant is too large for 'long' type
hb-private.hh:497: error: integer constant is too large for 'long' type

And looking at the relevant lines, I do see constants of 0xFFFFFFFF00000000 (line 417), 0x00000000FFFFFFFF, 0x0000FFFF0000FFFF, 0x00FF00FF00FF00FF, 0x0F0F0F0F0F0F0F0F, 0x3333333333333333, and 0x5555555555555555.  On 32-bit architectures these likely need to be suffixed ULL, unless a more recent compiler can cope with it.  Is a more recent compiler required to build harfbuzz?

**Comment by behdad** [comment]
Fixed. Thanks. Maybe we can add a bot with that config. @ebraminio

**Comment by chmeeedalf** [comment]
The change only fixes line 417, the other 5 lines are still affected.

**Comment by behdad** [comment]
You are right. Fixed. Thanks.

**Comment by sideeffect42** [comment]
While the `ULL` suffix works (on most platforms?), I would go for the `UINT64_C()`/`INT64_C()` macros from `stdint.h` for variables of type `[u]int64_t`.

**Comment by behdad** [comment]
I'd rather not touch it until someone else complains. We support all kinds of old systems...
