### ISSUE TITLE
Implement ltag table parsing

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#905]
This table is used for localized features in AAT fonts, connecting with `morx` and `feat` tables.
See: https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6ltag.html

**Comment by ebraminio** [comment]
(just a personal note)

List of Apple fonts on macOS 10.13.3 with `ltag` table:

```
/Library/Fonts/Kefa.ttc
/Library/Fonts/BigCaslon.ttf
/Library/Fonts/Al Nile.ttc
/Library/Fonts/Muna.ttc
/Library/Fonts/Farah.ttc
/Library/Fonts/Diwan Kufi.ttc
/Library/Fonts/Skia.ttf
/Library/Fonts/Beirut.ttc
/Library/Fonts/Sana.ttc
/Library/Fonts/Al Tarikh.ttc
```

**Comment by ebraminio** [comment]
Similar to `fmtx` issue :)
