### ISSUE TITLE
Implement fmtx table parsing

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#908]
This table is used to present AAT specific font metrics.
See: https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6fmtx.html

**Comment by ebraminio** [comment]
List of Apple fonts with `fmtx`:

```
/Library/Fonts/Apple Chancery.ttf
/Library/Fonts/Hoefler Text Ornaments.ttf
/Library/Fonts/Skia.ttf
/Library/Fonts/Hoefler Text.ttc
```

**Comment by ebraminio** [comment]
Lets repurpose your issue and close ones have parsing now. That feels better also :)
