### ISSUE TITLE
Implement gcid table parsing

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#914]
This table provides data to map characters in the font to CIDs. 
See: https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6gcid.html

**Comment by ebraminio** [comment]
There is no font on macOS 10.13.3 with the table AFAICS.

**Comment by ebraminio** [comment]
If you or anyone could find any, I will implement its parsing at least.

**Comment by ebraminio** [comment]
Unfortunately I couldn't any font with `gcid` so lets defer till I get any.

**Comment by ebraminio** [comment]
AppleGothic.ttf on macOS Sierra has the gcid table and I learned that from [fonttools](https://github.com/fonttools/fonttools/blob/master/Tests/ttLib/tables/_g_c_i_d_test.py#L10-L28)! Patch is coming :) The table is removed on the High Sierra version however.

**Comment by behdad** [comment]
What are we to do with this table?

**Comment by ebraminio** [comment]
You are right Behdad. Better to put that as closed PR instead merging it or never do it :/

**Comment by behdad** [comment]
Right. Unlike FreeType or FontTools, in HarfBuzz we are NOT interested in implementing every table under the sun just for the sake of it. We provide a limited set of highly user-friendly APIs, and implement tables only to support those.
