### ISSUE TITLE
Implement just table parsing

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [harfbuzz/harfbuzz#917]
This is used to to accommodate AAT specific justification functions.
See: https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6just.html

(not to be confused with OT's JSTF https://docs.microsoft.com/en-us/typography/opentype/spec/jstf )

**Comment by ebraminio** [comment]
List of Apple fonts on macOS 10.13.3 with `just` table: (on their first face)

```
/Library/Fonts/AlBayan.ttc
/Library/Fonts/Nadeem.ttc
/Library/Fonts/KufiStandardGK.ttc
/Library/Fonts/Farisi.ttf
/Library/Fonts/Mishafi.ttf
/Library/Fonts/Corsiva.ttc
/Library/Fonts/Al Nile.ttc
/Library/Fonts/Baghdad.ttc
/Library/Fonts/Muna.ttc
/Library/Fonts/Apple Chancery.ttf
/Library/Fonts/Farah.ttc
/Library/Fonts/Diwan Kufi.ttc
/Library/Fonts/Hoefler Text Ornaments.ttf
/Library/Fonts/DevanagariMT.ttc
/Library/Fonts/Beirut.ttc
/Library/Fonts/NewPeninimMT.ttc
/Library/Fonts/Diwan Thuluth.ttf
/Library/Fonts/Sana.ttc
/Library/Fonts/Hoefler Text.ttc
/Library/Fonts/Gurmukhi.ttf
/Library/Fonts/Al Tarikh.ttc
/Library/Fonts/Raanana.ttc
/Library/Fonts/Mishafi Gold.ttf
/Library/Fonts/Damascus.ttc
/Library/Fonts/Waseem.ttc
/Library/Fonts/DecoTypeNaskh.ttc
/System/Library/Fonts/Symbol.ttf
/System/Library/Fonts/LucidaGrande.ttc
/System/Library/Fonts/Palatino.ttc
/System/Library/Fonts/GeezaPro.ttc
/System/Library/Fonts/Times.ttc
```

**Comment by ebraminio** [comment]
Reading the specification, `just` has some dependency to `mort` structures so we have to revive some the removed ones I guess. I am not sure, maybe `morx` InsertionSubtable was developed in a way to play `just` role also @behdad? I liked to have this so in case we go for implementing a justification system, we know what is the prerequisites but `just` seems to be yet another AAT state machine.

**Comment by behdad** [comment]
Can wait till we have the AAT shaper complete (morx / kerx / ankr...) and when we start implementing justification. Of course, feel free to put the table for it in, but I prefer to have fewer incomplete tables than more.

**Comment by behdad** [comment]
Was going to close this.  But guess, you can also start putting the implementation of the table in?

**Comment by ebraminio** [comment]
> Was going to close this. But guess, you can also start putting the implementation of the table in?

I like to but not rushed as we don't have justification anyway but the problem is it has some dependencies and similarities with `mort`, is it OK revive those?

**Comment by behdad** [comment]
Not excited about that, but if is needed, sure.  Let's not touch this right now though.
