### ISSUE TITLE
Implement Zapf table parsing

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#919]
Now that we have an issue for every other AAT table, lets have for this one also,

> The 'Zapf' table—named with permission after legendary type designer Hermann Zapf—contains information about the individual glyphs in the font.  Conceptually, this information consists of:
>
> A text string which the glyph represents
> A set of identifiers
> A set of font features
> A set of glyph collections

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6Zapf.html

**Comment by ebraminio** [comment]
List of Apple fonts on macOS 10.13.3 with `Zapf` table: (on their first face)

```
/Library/Fonts/AlBayan.ttc
/Library/Fonts/Zapfino.ttf
/Library/Fonts/Silom.ttf
/Library/Fonts/Nadeem.ttc
/Library/Fonts/KufiStandardGK.ttc
/Library/Fonts/Papyrus.ttc
/Library/Fonts/Farisi.ttf
/Library/Fonts/Mishafi.ttf
/Library/Fonts/BigCaslon.ttf
/Library/Fonts/Al Nile.ttc
/Library/Fonts/Baghdad.ttc
/Library/Fonts/AmericanTypewriter.ttc
/Library/Fonts/Muna.ttc
/Library/Fonts/Apple Chancery.ttf
/Library/Fonts/Farah.ttc
/Library/Fonts/Diwan Kufi.ttc
/Library/Fonts/Hoefler Text Ornaments.ttf
/Library/Fonts/Beirut.ttc
/Library/Fonts/Diwan Thuluth.ttf
/Library/Fonts/Ayuthaya.ttf
/Library/Fonts/Sana.ttc
/Library/Fonts/Hoefler Text.ttc
/Library/Fonts/Sathu.ttf
/Library/Fonts/Krungthep.ttf
/Library/Fonts/Al Tarikh.ttc
/Library/Fonts/Damascus.ttc
/Library/Fonts/Waseem.ttc
/Library/Fonts/DecoTypeNaskh.ttc
/System/Library/Fonts/PingFang.ttc
/System/Library/Fonts/LucidaGrande.ttc
/System/Library/Fonts/Thonburi.ttc
/System/Library/Fonts/Palatino.ttc
/System/Library/Fonts/Apple Symbols.ttf
/System/Library/Fonts/GeezaPro.ttc
/System/Library/Fonts/Helvetica.ttc
```

**Comment by ebraminio** [comment]
Too complicated with no use on harfbuzz, I'll try to create some patch about it somewhere but won't merge it.

**Comment by behdad** [comment]
Yeah looks like a huge table with little use.

**Comment by Enivex** [comment]
Is this still out of scope for Harfbuzz? We've seen a few questions about Zapfino from Typst users.

**Comment by behdad** [comment]
> Is this still considered out of scope for Harfbuzz?

I think so. How many fonts have that table?

> We've seen a few questions about Zapfino from Typst users.

What kind of questions?

**Comment by Enivex** [comment]
> > Is this still considered out of scope for Harfbuzz?
> 
> I think so. How many fonts have that table?

That I do not know. Though someone listed some above 

> > We've seen a few questions about Zapfino from Typst users.
> 
> What kind of questions?

See e.g. https://github.com/typst/typst/issues/4393

**Comment by behdad** [comment]
> See e.g. [typst/typst#4393](https://github.com/typst/typst/issues/4393)

Thanks. I don't know how typst works internally, but there are ways to get HB to choose a glyph by glyph-id. You can then implement choosing glyphs by name. I can elaborate on that if you are interested.
