### ISSUE TITLE
hb-view: stch feature for SAM cannot be deactivated

### ISSUE THREAD

**Issue by n8willis** [harfbuzz/harfbuzz#929]
When using hb-view, adding the switch `--features=-stch` appears not to disable the application of the `stch` feature for the Syriac Abbreviation Mark.

Test case:

> hb-view --font-size=110 --margin=2,16,2,16 --output-file=syriac-stch-after.png --features=-stch --background=FFFFFF00 /usr/share/fonts/truetype/noto/NotoSansSyriacEastern-Regular.ttf --unicodes=0712,0732,070f,0728,0721,0735,0710

and 

> hb-view --font-size=110 --margin=2,16,2,16 --output-file=syriac-stch-after.png --features=+stch --background=FFFFFF00 /usr/share/fonts/truetype/noto/NotoSansSyriacEastern-Regular.ttf --unicodes=0712,0732,070f,0728,0721,0735,0710

produce identical output.

**Comment by n8willis** [comment]
Hmm; upon additional digging this may be more due to broken fonts than anything else....

Closing for now, pending further investigation.

**Comment by behdad** [comment]
Yeah I'm not sure our Noto fonts implement that. Probably something to file against Noto.
