### ISSUE TITLE
GPOS lookup code MarkMarkPosFormat1 ignores “ignore” lookup flags

### ISSUE THREAD

**Issue by blueshade7** [harfbuzz/harfbuzz#938]
`MarkMarkPosFormat1::apply` has this line of code (source hb-ot-layout-gpos-table.hh, line 1288):
```
    skippy_iter.set_lookup_props (c->lookup_props & ~LookupFlag::IgnoreFlags);
```
It should read (NOTE: '~' removed):
```
    skippy_iter.set_lookup_props (c->lookup_props & LookupFlag::IgnoreFlags);
```
Otherwise, `~LookupFlag::IgnoreFlags=~0x000Eu` masks out “ignore” bits, aka “skip” bits, `ignoreBaseGlyphs=0x002, ignoreLigatures=0x0004, ignoreMasks=0x0008` from the lookup table, that the skipping iterator is supposed to test against.

**Comment by behdad** [comment]
Nope. Logic is exactly as intended. You cannot skip over base or ligature glyphs or ALL marks when attaching a mark to another mark.
