### ISSUE TITLE
graphite2 shaper does not work

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#953]
With harfbuzz 1.7.6 compiled using MacPorts, I have:

```
$ hb-view --list-shapers
graphite2
coretext_aat
ot
coretext
fallback
```

`hb-view` works if I don't specify a shaper, but specifying the graphite2 shaper produces this message:

```
$ hb-view /System/Library/Fonts/LucidaGrande.ttc ABC --shaper=graphite2
hb-view: all shapers failed.
```

I've tried using graphite2 1.3.10 on macOS Sierra 10.12.6, and using graphite2 1.3.9 on earlier Mac operating system versions.

Should this work? Can I get more information somehow about why it failed?

**Comment by ryandesign** [comment]
I should also mention that the test suite passed. Is the test suite supposed to test the shapers?

**Comment by ebraminio** [comment]
macOS 10.13.3 and it is working for me,

```
$ util/hb-shape Simple-Graphite-Font.ttf abc --shapers=graphite2  
[a=0+462|B=1+676|C=2+694]
$ util/hb-shape Simple-Graphite-Font.ttf abc --shapers=ot      
[a=0+462|b=1+520|c=2+462]
```

(the difference indicates the effect [this graphite2 font](http://scripts.sil.org/cms/scripts/render_download.php?site_id=projects&format=file&media_id=SimpleGraphiteFont&filename=SimpleGraphiteFont.zip) should have)

I tested it with fonts without graphite tables and it fails but I can say that is expected so closing the bug but please test if you have fails with the mentioned font. Thanks

**Comment by khaledhosny** [comment]
Yes, this is expected if you specify `graphite2` shaper only and the font is not a Graphite font, `graphite2` shaper will not shape non-Graphite fonts and fail, expecting the next shaper to do the job, but you have only one shaper so all fails.
