### ISSUE TITLE
coretext and coretext_aat shapers don't work with .ttc fonts on OS X 10.8 or earlier

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#954]
With harfbuzz 1.7.6 compiled using MacPorts, I have:

```
$ hb-view --list-shapers
graphite2
coretext_aat
ot
coretext
fallback
```

`hb-view` works if I don't specify a shaper, but specifying the coretext or coretext_aat shapers produces this message if I'm running on Mac OS X 10.5, 10.6, or 10.7 (with my patch from #952) or 10.8:

```
$ hb-view /System/Library/Fonts/LucidaGrande.ttc ABC --shaper=coretext
hb-view: all shapers failed.
```
```
$ hb-view /System/Library/Fonts/LucidaGrande.ttc ABC --shaper=coretext_aat
hb-view: all shapers failed.
```

(10.5 doesn't ship with any .ttc fonts so I copied one over from a newer system.)

Should this work? Can I get more information somehow about why it failed?

It works fine on OS X 10.9 and later, though the output that is produced looks identical to what's produced when I don't specify a shaper; is that to be expected?

**Comment by ebraminio** [comment]
> hb-view works if I don't specify a shaper

Great, so the issue perhaps is limited to hb-coretext.

> (10.5 doesn't ship with any .ttc fonts so I copied one over from a newer system.)

What if you run it with on the available fonts and not one brought from newer versions? And what happens without your patch? Can you run bisect to see if this a regression? Theoretically it should work with the installed fonts and if not something of course is wrong which we like to be solved but I don't have that versions to help.

> Should this work? Can I get more information somehow about why it failed?

I believe, but it can be regressed before your patch as hb-coretext is used to be maintained mainly for Chromium use and Chrome has abandoned that macOS versions.

> It works fine on OS X 10.9 and later, though the output that is produced looks identical to what's produced when I don't specify a shaper; is that to be expected?

Yes. Specifying shaper backend is like changing JavaScript engines, they should give identical or similar results at least. They are mainly for comparison and development purposes but on the special case of hb-coretext, Chromium has used them on production even they weren't ready for so maintainers dealt with that at the time.

**Comment by ebraminio** [comment]
And the reason Chromium is using hb-coretext is the fact HarfBuzz (loose transliteration of Persian translation of "OpenType") was shaped to work with OpenType and wasn't capable of AAT additional standards but that is going to be changed (hopefully on HarfBuzz 2.0 release) and soon Chromium will abandon hb-coretext use but of course that part of the project won't be removed.

**Comment by ebraminio** [comment]
Fortunately I remembered I have an old OS X 10.6.8 machine also so will see what we can do :)

**Comment by ebraminio** [comment]
Just checked this on #952 and found the issue is not about all of fonts but just `.ttc` and `.dfont`. HarfBuzz's own font loading is not used by default and I guess this is freetype that is in charge for this so this is a problem on harfbuzz but can be closed fortunately. Thanks!

**Comment by ryandesign** [comment]
I suggest making this issue about .ttc fonts only. All system-provided .ttc fonts fail with the CoreText shaper on OS X 10.8 and earlier:

```
$ find /System/Library/Fonts -name *.ttc -print0 | xargs -0 -I % sh -c 'set -x; hb-view "%" ABC --shaper=coretext;'
+ hb-view /System/Library/Fonts/AquaKana.ttc ABC --shaper=coretext
hb-view: all shapers failed.
+ hb-view /System/Library/Fonts/HelveticaNeueDeskUI.ttc ABC --shaper=coretext
hb-view: all shapers failed.
+ hb-view /System/Library/Fonts/LucidaGrande.ttc ABC --shaper=coretext
hb-view: all shapers failed.
+ hb-view /System/Library/Fonts/MarkerFelt.ttc ABC --shaper=coretext
hb-view: all shapers failed.
+ hb-view /System/Library/Fonts/Menlo.ttc ABC --shaper=coretext
hb-view: all shapers failed.
+ hb-view /System/Library/Fonts/Noteworthy.ttc ABC --shaper=coretext
hb-view: all shapers failed.
+ hb-view '/System/Library/Fonts/STHeiti Light.ttc' ABC --shaper=coretext
hb-view: all shapers failed.
+ hb-view '/System/Library/Fonts/STHeiti Medium.ttc' ABC --shaper=coretext
hb-view: all shapers failed.
```

I filed a separate issue about .dfont fonts, which fail on all versions of macOS. See #958.

**Comment by ebraminio** [comment]
I guess this has one solution, reverting your patch and putting https://github.com/harfbuzz/harfbuzz/commit/dd4b321b4a429c6e6a28441ea9ae52f8f9dd1dad behind `#ifdef`, can you check if that can help?

**Comment by behdad** [comment]
> Just checked this on #952 and found the issue is not about all types of fonts but just .ttc and .dfont. HarfBuzz's own font loading is not used by default and I guess this is freetype that is in charge for this so this is not a problem on harfbuzz and can be closed fortunately. Thanks!

But FreeType is supposed to handle those.

**Comment by behdad** [comment]
Not sure how to proceed.  Anyone volunteering to debug?

**Comment by khaledhosny** [comment]
Core Text shaper is on its way out and no one can debug this, should be closed I think.

**Comment by ebraminio** [comment]
I believe also
