### ISSUE TITLE
Test additional shapers backends when they exist

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#955]
As #934, #954 and #953, now I feel we should have tests for our shapers backends and that should be considered at least whenever #687 is going to happen.

**Comment by behdad** [comment]
Sure, feel free to implement. Not sure how to best skip if the shaper dosn't exist, as opposed to shaper failing.

Alternatively, at least for Mac fonts, we can make run-tests.py recognize absolute font file paths, and skip the test if the font doesn't exist.

**Comment by behdad** [comment]
Closing DON'T CARE.
