### ISSUE TITLE
No distinction between failed shaper and nonexistent shaper

### ISSUE THREAD

**Issue by ryandesign** [harfbuzz/harfbuzz#956]
Hello, with harfbuzz 1.7.6 on macOS I have:

```
$ hb-view --list-shapers
graphite2
coretext_aat
ot
coretext
fallback
```

There isn't any difference in output between a shaper that exists but doesn't work:

```
$ hb-view /System/Library/Fonts/LucidaGrande.ttc ABC --shaper=graphite2; echo $?
hb-view: all shapers failed.
1
```

...and a shaper that doesn't exist at all:

```
$ hb-view /System/Library/Fonts/LucidaGrande.ttc ABC --shaper=foobar; echo $?
hb-view: all shapers failed.
1
```

This has caused me to have to be very careful in my recent testing, and double-check all of my typing, to make sure I wasn't inadvertently mistyping a shaper name. I had expected to see a message like "shaper foobar doesn't exist".

**Comment by behdad** [comment]
I suppose we can add code in hb-shape / hb-view to do that just to help user.
