### ISSUE TITLE
Make NotoColorEmoji actually work and implement IndexSubtableFormat{0,2} on CBLC

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#960]
Steps to repro:
1. Download `NotoColorEmoji.ttf`
2. `make -Cbuild/src dump-emoji`
3. `rmdir out || true; mkdir out`
4. `build/src/dumo-emoji NotoColorEmoji.ttf`

Actual:
Not all emojis can be dumped on `out/` folder.

Expected:
All the glyphs be dumped correctly.

**Comment by ebraminio** [comment]
This is the result of this patch,

```diff
diff --git a/src/hb-ot-color-cbdt-table.hh b/src/hb-ot-color-cbdt-table.hh
index cf1c69c..1aa896d 100644
--- a/src/hb-ot-color-cbdt-table.hh
+++ b/src/hb-ot-color-cbdt-table.hh
@@ -168,6 +168,7 @@ struct IndexSubtable
                       unsigned int *format) const
   {
     *format = u.header.imageFormat;
+    printf("%d", (int) u.header.indexFormat);
     switch (u.header.indexFormat) {
     case 1: return u.format1.get_image_data (idx, offset, length);
     case 3: return u.format3.get_image_data (idx, offset, length);
@@ -482,7 +483,11 @@ struct CBDT

             if (!subtable_record.get_image_data (gid,
                   &image_offset, &image_length, &image_format))
+           {
+             printf("-");
               continue;
+           }
+           printf("+");

             switch (image_format)
             {
```

```1+1+1+1+1+1+1+1+1+1+1+1+1+1+0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-1+2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-1+1+1+1+1+1+1+0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-```

which means only index format 1 are passing `get_image_data` which was available before the dump tool so the issue is not dump tool specific.

**Comment by ebraminio** [comment]
Which obviously because only the format 1 is implemented...

**Comment by ebraminio** [comment]
There is no IndexSubTable0 on https://docs.microsoft.com/en-us/typography/opentype/spec/eblc#indexsubtable1-variable-metrics-glyphs-with-4-byte-offsets how must of them are 0 on Noto? (put `printf ("%d\n", (int) u.header.indexFormat);` on top of sanitization or get_image_data to see yourself)

**Comment by ebraminio** [comment]
I wonder why this is implemented at the first place (probably for CLBC on Android) and how now that is broken no body cares

**Comment by khaledhosny** [comment]
Looks like his was introduced to get glyph extents since fonts with CBDT/CBLC tables must not have glyph outlines tables, see 831852594b777f250efedb76d19bee1cfc8eeaa4.

**Comment by ebraminio** [comment]
I know, and I feel it is implemented somewhere else so nobody cares about harfbuzz, but am thinking about why it is introduced first here or moved afterward.

**Comment by behdad** [comment]
I'll check this today.

**Comment by behdad** [comment]
@nona-google

**Comment by behdad** [comment]
I can confirm this doesn't work:
```
$ ./hb-shape  NotoColorEmoji.ttf -u 1f98a --font-funcs ot --show-extents 
[gid1120=0+2550<0,0,0,0>]
```

**Comment by behdad** [comment]
That said, we have a `color-fonts.tests` that seem to work.

**Comment by behdad** [comment]
Test font has:
```
    <strikedata index="0"> 
      <cbdt_bitmap_format_17 name="u1F42F"> 
        <SmallGlyphMetrics> 
          <height value="128"/> 
          <width value="136"/> 
          <BearingX value="0"/> 
          <BearingY value="100"/> 
          <Advance value="136"/> 
        </SmallGlyphMetrics> 
        <rawimagedata> 
```

NotoColorEmoji has:
```
    <strikedata index="0"> 
      <cbdt_bitmap_format_17 name="glyph02253"> 
        <SmallGlyphMetrics> 
          <height value="128"/> 
          <width value="136"/> 
          <BearingX value="0"/> 
          <BearingY value="101"/> 
          <Advance value="136"/> 
        </SmallGlyphMetrics> 
        <rawimagedata> 
```
so not sure why it doesn't work.

**Comment by behdad** [comment]
That code is too complicated for me to get my head around of. :(

**Comment by behdad** [comment]
Or rather, that table...

**Comment by behdad** [comment]
IIRC @nona-google implemented this and I cleaned up and merged it, but he also sent a patch to FreeType to allow loading metrics without loading bitmaps, and that got merged and he ended up using that.  That would explain why this was broken and we never noticed.

**Comment by nona-google** [comment]
I just debugged and somehow the image format is invalid number and leached here.
https://cs.chromium.org/chromium/src/third_party/harfbuzz-ng/src/src/hb-ot-color-cbdt-table.hh?rcl=54d332dd9b0263821376161cdffb60ffb3c7847f&l=450

**Comment by nona-google** [comment]
Android still uses this code but not sure why I wasn't noticed the breakage.
I'm going to take some time tomorrow for further debugging and explain why we missed this.

**Comment by behdad** [comment]
Okay. Believe I fixed this.  `dump-emoji` still crashes though.  @ebraminio can you debug?

**Comment by behdad** [comment]
Thanks @nona-google.  I believe I fixed the core issue here.

**Comment by khaledhosny** [comment]
`dump-emoji` is trying to write files to a directory named `out` without checking for its existence or creating it, so it gets `NULL` from `fopen()` and crashes writing to it.

**Comment by khaledhosny** [comment]
I get lots of more glyphs here. The code should at least check if `fopen()` returned `NULL` and abort or warn, not just crash.

**Comment by khaledhosny** [comment]
```
$ ./src/dump-emoji /usr/share/fonts/noto/NotoColorEmoji.ttf
$ ls out/ | wc -l
2581
```

**Comment by ebraminio** [comment]
Oh thanks. Hmm, just to confirm, are you using a new version of NotoColorEmoji.ttf? Maybe we just lack the support on new one.

**Comment by khaledhosny** [comment]
Font version is 2.017, which I think is the latest.

**Comment by ebraminio** [comment]
It works now with the fixes, also your applying your comment #1251, have a look, thanks :)
