### ISSUE TITLE
Support .fon files

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#992]
Split from #681, apparently [this issue on Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1045139) and [this change](https://github.com/harfbuzz/harfbuzz/commit/f28b1c823db2ad56fed356ef864a7508d23048b8) on harfbuzz was about supporting `.fon` rendering. As these bitmap fonts don't have cmap and are very outdates, @dscorbett [suggested here](https://github.com/harfbuzz/harfbuzz/issues/681#issuecomment-358361891) we can read dfCharSet by our own and use it with our Arabic 1256 implementation so no Uniscribe support and testing and such (see the part I wanted to remove on #991). The good news is we now have [.fon/.fnt parsing code](https://github.com/harfbuzz/harfbuzz/pull/981) inside harfbuzz so maybe we can somehow move that implementation and use it on production sometime (which this bug is about). As we will expose bitmap glyph data of Emoji someday on harfbuzz someday, maybe we can expose .fnt bitmap through that API also someday also!

Even the fact Firefox is having that correctly for years I guess Mozilla (@jfkthame) will be interested on this with their Servo engine work maybe.

**Comment by behdad** [comment]
Given other issue, do we want .fon support? Leaning towards not.

If anything, implement Type1 ;)

**Comment by behdad** [comment]
Given new findings, let's focus on TrueType, and NOT implement .fon. Delete dump-fon?
